HE_Mesh: wblut.hemesh.HEC_IsoSurfaceVOL2D Class Reference
wblut.hemesh.HEC_IsoSurfaceVOL2D Class Reference
Public Member Functions
HEC_IsoSurfaceVOL2D ()
HEC_IsoSurfaceVOL2D setResolution (final int resx, final int resy)
HEC_IsoSurfaceVOL2D setSize (final double dx, final double dy)
HEC_IsoSurfaceVOL2D setZFactor (final double zf)
HEC_IsoSurfaceVOL2D setValues (final double[][] values)
HEC_IsoSurfaceVOL2D setValues (final float[][] values)
HEC_IsoSurfaceVOL2D setValues (final WB_ScalarParameter function, final double xi, final double yi, final double dx, final double dy, final int width, final int height)
HEC_IsoSurfaceVOL2D setValues (final WB_HashGridDouble2D values)
HEC_IsoSurfaceVOL2D setValues (final String path, final PApplet home, final int width, final int height)
HEC_IsoSurfaceVOL2D setValues (final String path, final PApplet home, final int width, final int height, final WB_IsoValues2D.Mode mode)
HEC_IsoSurfaceVOL2D setValues (final PImage image, final PApplet home, final int width, final int height)
HEC_IsoSurfaceVOL2D setValues (final PImage image, final PApplet home, final int width, final int height, final WB_IsoValues2D.Mode mode)
HEC_IsoSurfaceVOL2D setValues (final WB_IsoValues2D values)
HEC_IsoSurfaceVOL2D setIsolevel (final double isolevelmin, final double isolevelmax)
HEC_IsoSurfaceVOL2D setCenter (final WB_Coord c)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Static Public Member Functions
static void main (final String[] args)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Member Functions
int index (final int i, final int j)
double value (final int i, final int j)
HE_Vertex vertex (final int i, final int j, final WB_Point offset)
HE_Vertex xedge (final int i, final int j, final WB_Point offset, final double isolevel)
HE_Vertex yedge (final int i, final int j, final WB_Point offset, final double isolevel)
HE_Vertex interp (final double isolevel, final WB_Point p1, final WB_Point p2, final double valp1, final double valp2)
int classifyCell (final int i, final int j)
void polygonise ()
void getPolygons (final int i, final int j, final int cubeindex, final WB_Point offset)
HE_Vertex getIsoVertex (final int isopointindex, final int i, final int j, final WB_Point offset)
Private Attributes
int[] digits = new int[4]
int[][] entries
WB_IsoValues2D values
int resx
double cx
double dx
double isolevelmin
IntObjectHashMap< HE_Vertex > xedges
IntObjectHashMap< HE_Vertex > yedges
IntObjectHashMap< HE_Vertex > vertices
HE_Mesh mesh
double zFactor
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Constructor & Destructor Documentation
wblut.hemesh.HEC_IsoSurfaceVOL2D.HEC_IsoSurfaceVOL2D ()
Member Function Documentation
int wblut.hemesh.HEC_IsoSurfaceVOL2D.classifyCell (final int i, final int j) private
Classify cell.
Parameters
i the i
j the j
Returns
the int
References wblut.hemesh.HEC_IsoSurfaceVOL2D.value().
HE_Mesh wblut.hemesh.HEC_IsoSurfaceVOL2D.createBase () protected
References wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HEC_IsoSurfaceVOL2D.mesh, wblut.hemesh.HE_Mesh.pairHalfedges(), and wblut.hemesh.HEC_IsoSurfaceVOL2D.polygonise().
HE_Vertex wblut.hemesh.HEC_IsoSurfaceVOL2D.getIsoVertex (final int isopointindex, final int i, final int j, final WB_Point offset) private
Parameters
isopointindex
i
j
offset
Returns
References wblut.hemesh.HEC_IsoSurfaceVOL2D.vertex(), wblut.hemesh.HEC_IsoSurfaceVOL2D.xedge(), and wblut.hemesh.HEC_IsoSurfaceVOL2D.yedge().
void wblut.hemesh.HEC_IsoSurfaceVOL2D.getPolygons (final int i, final int j, final int cubeindex, final WB_Point offset) private
Gets the polygons.
Parameters
i the i
j the j
cubeindex the cubeindex
offset
Returns
the polygons
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HEC_IsoSurfaceVOL2D.getIsoVertex(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setVertex().
int wblut.hemesh.HEC_IsoSurfaceVOL2D.index (final int i, final int j) private
Parameters
i
j
Returns
HE_Vertex wblut.hemesh.HEC_IsoSurfaceVOL2D.interp (final double isolevel, final WB_Point p1, final WB_Point p2, final double valp1, final double valp2) private
Interp.
Parameters
isolevel the isolevel
p1 the p1
p2 the p2
valp1 the valp1
valp2 the valp2
Returns
the h e_ vertex
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static void wblut.hemesh.HEC_IsoSurfaceVOL2D.main (final String[] args) static
References wblut.hemesh.HEC_Creator.center, wblut.geom.WB_GeometryOp3D.getSqDistance3D(), wblut.hemesh.HEC_IsoSurfaceVOL2D.HEC_IsoSurfaceVOL2D(), and wblut.hemesh.HEC_IsoSurfaceVOL2D.resx.
void wblut.hemesh.HEC_IsoSurfaceVOL2D.polygonise () private
Polygonise.
References wblut.hemesh.HEC_IsoSurfaceVOL2D.classifyCell(), wblut.hemesh.HEC_IsoSurfaceVOL2D.getPolygons(), and wblut.hemesh.HEC_IsoSurfaceVOL2D.resx.
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setCenter (final WB_Coord c)
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setIsolevel (final double isolevelmin, final double isolevelmax)
Parameters
isolevelmin
isolevelmax
Returns
References wblut.hemesh.HEC_IsoSurfaceVOL2D.isolevelmin.
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setResolution (final int resx, final int resy)
Number of cells.
Parameters
resx the resx
resy the resy
Returns
self
References wblut.hemesh.HEC_IsoSurfaceVOL2D.resx.
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setSize (final double dx, final double dy)
Parameters
dx
dy
Returns
References wblut.hemesh.HEC_IsoSurfaceVOL2D.dx.
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setValues (final double values[][])
Values at grid points.
Parameters
values double[resx+1][resy+1]
Returns
self
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setValues (final float values[][])
Values at grid points.
Parameters
values float[resx+1][resy+1]
Returns
self
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setValues (final WB_ScalarParameter function, final double xi, final double yi, final double dx, final double dy, final int width, final int height)
Parameters
function
xi
yi
dx
dy
Returns
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setValues (final WB_HashGridDouble2D values)
Parameters
values
Returns
References wblut.geom.WB_HashGridDouble2D.getHeight(), and wblut.geom.WB_HashGridDouble2D.getWidth().
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setValues (final String path, final PApplet home, final int width, final int height)
Parameters
path
home
width
height
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), and wblut.geom.WB_IsoValues2D.getWidth().
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setValues (final String path, final PApplet home, final int width, final int height, final WB_IsoValues2D.Mode mode)
Parameters
path
home
width
height
mode
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), and wblut.geom.WB_IsoValues2D.getWidth().
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setValues (final PImage image, final PApplet home, final int width, final int height)
Parameters
image
home
width
height
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), and wblut.geom.WB_IsoValues2D.getWidth().
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setValues (final PImage image, final PApplet home, final int width, final int height, final WB_IsoValues2D.Mode mode)
Parameters
image
home
width
height
mode
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), and wblut.geom.WB_IsoValues2D.getWidth().
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setValues (final WB_IsoValues2D values)
Parameters
values
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), wblut.geom.WB_IsoValues2D.getWidth(), and wblut.hemesh.HEC_IsoSurfaceVOL2D.values.
HEC_IsoSurfaceVOL2D wblut.hemesh.HEC_IsoSurfaceVOL2D.setZFactor (final double zf)
double wblut.hemesh.HEC_IsoSurfaceVOL2D.value (final int i, final int j) private
Value.
Parameters
i the i
j the j
Returns
the double
References wblut.geom.WB_IsoValues2D.value().
HE_Vertex wblut.hemesh.HEC_IsoSurfaceVOL2D.vertex (final int i, final int j, final WB_Point offset) private
Parameters
i
j
offset
Returns
References wblut.hemesh.HE_Mesh.add(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HEC_IsoSurfaceVOL2D.index(), and wblut.hemesh.HEC_IsoSurfaceVOL2D.value().
HE_Vertex wblut.hemesh.HEC_IsoSurfaceVOL2D.xedge (final int i, final int j, final WB_Point offset, final double isolevel) private
Xedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
offset
isolevel
Returns
edge vertex
References wblut.hemesh.HE_Mesh.add(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HEC_IsoSurfaceVOL2D.index(), wblut.hemesh.HEC_IsoSurfaceVOL2D.interp(), and wblut.hemesh.HEC_IsoSurfaceVOL2D.value().
HE_Vertex wblut.hemesh.HEC_IsoSurfaceVOL2D.yedge (final int i, final int j, final WB_Point offset, final double isolevel) private
Yedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
offset
isolevel
Returns
edge vertex
References wblut.hemesh.HE_Mesh.add(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HEC_IsoSurfaceVOL2D.index(), wblut.hemesh.HEC_IsoSurfaceVOL2D.interp(), and wblut.hemesh.HEC_IsoSurfaceVOL2D.value().
Member Data Documentation
double wblut.hemesh.HEC_IsoSurfaceVOL2D.cx private
int [] wblut.hemesh.HEC_IsoSurfaceVOL2D.digits = new int[4] private
double wblut.hemesh.HEC_IsoSurfaceVOL2D.dx private
int [][] wblut.hemesh.HEC_IsoSurfaceVOL2D.entries private
double wblut.hemesh.HEC_IsoSurfaceVOL2D.isolevelmin private
HE_Mesh wblut.hemesh.HEC_IsoSurfaceVOL2D.mesh private
int wblut.hemesh.HEC_IsoSurfaceVOL2D.resx private
WB_IsoValues2D wblut.hemesh.HEC_IsoSurfaceVOL2D.values private
IntObjectHashMap<HE_Vertex> wblut.hemesh.HEC_IsoSurfaceVOL2D.vertices private
IntObjectHashMap<HE_Vertex> wblut.hemesh.HEC_IsoSurfaceVOL2D.xedges private
IntObjectHashMap<HE_Vertex> wblut.hemesh.HEC_IsoSurfaceVOL2D.yedges private
double wblut.hemesh.HEC_IsoSurfaceVOL2D.zFactor private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_IsoSurfaceVOL2D.java