HE_Mesh: wblut.geom.WB_Frame.WB_FrameStrut Class Reference
wblut.geom.WB_Frame.WB_FrameStrut Class Reference
Public Member Functions
WB_FrameStrut (final WB_FrameNode s, final WB_FrameNode e, final int id)
WB_FrameStrut (final WB_FrameNode s, final WB_FrameNode e, final int id, final double r)
WB_FrameStrut (final WB_FrameNode s, final WB_FrameNode e, final int id, final double rs, final double re)
WB_FrameNode start ()
WB_FrameNode end ()
int getStartIndex ()
int getEndIndex ()
int getIndex ()
WB_Vector toVector ()
WB_Vector toNormVector ()
double getSqLength ()
double getLength ()
double getRadiusStart ()
double getRadiusEnd ()
void setRadiusStart (final double r)
void setRadiusEnd (final double r)
double getOffsetStart ()
double getOffsetEnd ()
void setOffsetStart (final double o)
void setOffsetEnd (final double o)
WB_Point getCenter ()
WB_Segment toSegment ()
WB_Plane toPlane ()
Private Attributes
final WB_FrameNode start
final WB_FrameNode end
final int index
double radiuss
double radiuse
double offsets
double offsete
Constructor & Destructor Documentation
wblut.geom.WB_Frame.WB_FrameStrut.WB_FrameStrut (final WB_FrameNode s, final WB_FrameNode e, final int id)
Parameters
s
e
id
wblut.geom.WB_Frame.WB_FrameStrut.WB_FrameStrut (final WB_FrameNode s, final WB_FrameNode e, final int id, final double r)
Parameters
s
e
id
r
wblut.geom.WB_Frame.WB_FrameStrut.WB_FrameStrut (final WB_FrameNode s, final WB_FrameNode e, final int id, final double rs, final double re)
Parameters
s
e
id
rs
re
Member Function Documentation
WB_FrameNode wblut.geom.WB_Frame.WB_FrameStrut.end ()
Returns
WB_Point wblut.geom.WB_Frame.WB_FrameStrut.getCenter ()
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_Frame.WB_FrameStrut.end(), wblut.geom.WB_Point.mulSelf(), and wblut.geom.WB_Frame.WB_FrameStrut.start().
int wblut.geom.WB_Frame.WB_FrameStrut.getEndIndex ()
Returns
References wblut.geom.WB_Frame.WB_FrameNode.getIndex().
int wblut.geom.WB_Frame.WB_FrameStrut.getIndex ()
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.index.
double wblut.geom.WB_Frame.WB_FrameStrut.getLength ()
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.end(), wblut.geom.WB_GeometryOp3D.getDistance3D(), and wblut.geom.WB_Frame.WB_FrameStrut.start().
double wblut.geom.WB_Frame.WB_FrameStrut.getOffsetEnd ()
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.offsete.
double wblut.geom.WB_Frame.WB_FrameStrut.getOffsetStart ()
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.offsets.
double wblut.geom.WB_Frame.WB_FrameStrut.getRadiusEnd ()
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.radiuse.
double wblut.geom.WB_Frame.WB_FrameStrut.getRadiusStart ()
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.radiuss.
double wblut.geom.WB_Frame.WB_FrameStrut.getSqLength ()
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.end(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), and wblut.geom.WB_Frame.WB_FrameStrut.start().
int wblut.geom.WB_Frame.WB_FrameStrut.getStartIndex ()
Returns
References wblut.geom.WB_Frame.WB_FrameNode.getIndex().
void wblut.geom.WB_Frame.WB_FrameStrut.setOffsetEnd (final double o)
Parameters
o
void wblut.geom.WB_Frame.WB_FrameStrut.setOffsetStart (final double o)
Parameters
o
void wblut.geom.WB_Frame.WB_FrameStrut.setRadiusEnd (final double r)
Parameters
r
void wblut.geom.WB_Frame.WB_FrameStrut.setRadiusStart (final double r)
Parameters
r
WB_FrameNode wblut.geom.WB_Frame.WB_FrameStrut.start ()
Returns
WB_Vector wblut.geom.WB_Frame.WB_FrameStrut.toNormVector ()
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.end(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Frame.WB_FrameStrut.start(), and wblut.geom.WB_Point.subToVector3D().
WB_Plane wblut.geom.WB_Frame.WB_FrameStrut.toPlane ()
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.start(), and wblut.geom.WB_Frame.WB_FrameStrut.toVector().
WB_Segment wblut.geom.WB_Frame.WB_FrameStrut.toSegment ()
Returns
WB_Vector wblut.geom.WB_Frame.WB_FrameStrut.toVector ()
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.end(), wblut.geom.WB_Frame.WB_FrameStrut.start(), and wblut.geom.WB_Point.subToVector3D().
Member Data Documentation
final WB_FrameNode wblut.geom.WB_Frame.WB_FrameStrut.end private
final int wblut.geom.WB_Frame.WB_FrameStrut.index private
double wblut.geom.WB_Frame.WB_FrameStrut.offsete private
double wblut.geom.WB_Frame.WB_FrameStrut.offsets private
double wblut.geom.WB_Frame.WB_FrameStrut.radiuse private
double wblut.geom.WB_Frame.WB_FrameStrut.radiuss private
final WB_FrameNode wblut.geom.WB_Frame.WB_FrameStrut.start private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Frame.java