HE_Mesh: wblut.hemesh.HET_WriterSimpleMesh Class Reference
wblut.hemesh.HET_WriterSimpleMesh Class Reference
Public Member Functions
void beginSave (final OutputStream stream)
void beginSave (final String fn, final String name)
void endSave ()
void faces (final int[][] f)
void face (final int[] f)
void vertices (final WB_Coord[] v)
void vertices (final List<?extends WB_Coord > v)
void intValue (final int v)
Protected Member Functions
void handleBeginSave ()
Protected Attributes
OutputStream simpleMeshStream
PrintWriter simpleMeshWriter
Static Private Member Functions
static void createDirectories (final File file)
Detailed Description
Helper class for HE_Export.saveToSimpleMesh.
Author
Frederik Vanhoutte, W:Blut
Member Function Documentation
void wblut.hemesh.HET_WriterSimpleMesh.beginSave (final OutputStream stream)
Begin save.
Parameters
stream the stream
References wblut.hemesh.HET_WriterSimpleMesh.handleBeginSave().
void wblut.hemesh.HET_WriterSimpleMesh.beginSave (final String fn, final String name)
Begin save.
Parameters
fn the fn
name
References wblut.hemesh.HET_WriterSimpleMesh.createDirectories(), and wblut.hemesh.HET_WriterSimpleMesh.handleBeginSave().
static void wblut.hemesh.HET_WriterSimpleMesh.createDirectories (final File file) static private
Parameters
file
void wblut.hemesh.HET_WriterSimpleMesh.endSave ()
End save.
void wblut.hemesh.HET_WriterSimpleMesh.face (final int[] f)
Face.
Parameters
f the f
void wblut.hemesh.HET_WriterSimpleMesh.faces (final int f[][])
Faces.
Parameters
f the f
References wblut.hemesh.HET_WriterSimpleMesh.face().
void wblut.hemesh.HET_WriterSimpleMesh.handleBeginSave () protected
Handle begin save.
void wblut.hemesh.HET_WriterSimpleMesh.intValue (final int v)
Int value.
Parameters
v the v
void wblut.hemesh.HET_WriterSimpleMesh.vertices (final WB_Coord[] v)
Vertices.
Parameters
v the v
void wblut.hemesh.HET_WriterSimpleMesh.vertices (final List<?extends WB_Coord > v)
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
Member Data Documentation
OutputStream wblut.hemesh.HET_WriterSimpleMesh.simpleMeshStream protected
The simple mesh stream.
PrintWriter wblut.hemesh.HET_WriterSimpleMesh.simpleMeshWriter protected
The simple mesh writer.
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_WriterSimpleMesh.java