HE_Mesh: wblut.hemesh.HE_PathHalfedge Class Reference
wblut.hemesh.HE_PathHalfedge Class Reference
Public Member Functions
HE_PathHalfedge ()
HE_PathHalfedge (final HE_Halfedge he)
void clearNext ()
HE_Halfedge getHalfedge ()
HE_Vertex getVertex ()
HE_Vertex getStartVertex ()
HE_Vertex getEndVertex ()
void setHalfedge (final HE_Halfedge he)
HE_PathHalfedge getNextInPath ()
HE_PathHalfedge getPrevInPath ()
Long key ()
void setNext (final HE_PathHalfedge he)
void setPrev (final HE_PathHalfedge he)
String toString ()
void clear ()
void clearPrecomputed ()
Public Member Functions inherited from wblut.hemesh.HE_MeshElement
HE_MeshElement ()
void clearVisited ()
void setVisited ()
void setVisited (final boolean b)
boolean isVisited ()
void setVisible (final boolean b)
boolean isVisible ()
int hashCode ()
boolean equals (final Object other)
void copyProperties (final HE_MeshElement el)
int getColor ()
void setColor (final int color)
Public Member Functions inherited from wblut.hemesh.HE_Element
HE_Element ()
final void setUserLabel (final int label)
final long getKey ()
final int getInternalLabel ()
final int getUserLabel ()
int hashCode ()
boolean equals (final Object other)
void copyProperties (final HE_Element el)
Private Member Functions
void clearPrev ()
Private Attributes
HE_Halfedge _he
HE_PathHalfedge _next
HE_PathHalfedge _prev
Additional Inherited Members
Protected Member Functions inherited from wblut.hemesh.HE_MeshElement
abstract void clear ()
Protected Member Functions inherited from wblut.hemesh.HE_Element
final void setInternalLabel (final int label)
abstract void clear ()
abstract void clearPrecomputed ()
Protected Attributes inherited from wblut.hemesh.HE_MeshElement
volatile boolean visited
boolean visible
int color
Protected Attributes inherited from wblut.hemesh.HE_Element
final long key
int internalLabel
int userLabel
Static Protected Attributes inherited from wblut.hemesh.HE_MeshElement
static final WB_GeometryFactory gf = new WB_GeometryFactory()
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Static Protected Attributes inherited from wblut.hemesh.HE_Element
static AtomicLong currentKey = new AtomicLong(0)
Constructor & Destructor Documentation
wblut.hemesh.HE_PathHalfedge.HE_PathHalfedge ()
wblut.hemesh.HE_PathHalfedge.HE_PathHalfedge (final HE_Halfedge he)
Parameters
he
Member Function Documentation
void wblut.hemesh.HE_PathHalfedge.clear ()
void wblut.hemesh.HE_PathHalfedge.clearNext ()
References wblut.hemesh.HE_PathHalfedge.clearPrev().
void wblut.hemesh.HE_PathHalfedge.clearPrecomputed ()
void wblut.hemesh.HE_PathHalfedge.clearPrev () private
HE_Vertex wblut.hemesh.HE_PathHalfedge.getEndVertex ()
Returns
References wblut.hemesh.HE_Halfedge.getEndVertex().
HE_Halfedge wblut.hemesh.HE_PathHalfedge.getHalfedge ()
Returns
References wblut.hemesh.HE_PathHalfedge._he.
HE_PathHalfedge wblut.hemesh.HE_PathHalfedge.getNextInPath ()
Returns
References wblut.hemesh.HE_PathHalfedge._next.
HE_PathHalfedge wblut.hemesh.HE_PathHalfedge.getPrevInPath ()
Returns
References wblut.hemesh.HE_PathHalfedge._prev.
HE_Vertex wblut.hemesh.HE_PathHalfedge.getStartVertex ()
Returns
References wblut.hemesh.HE_Halfedge.getVertex().
HE_Vertex wblut.hemesh.HE_PathHalfedge.getVertex ()
Returns
References wblut.hemesh.HE_Halfedge.getVertex().
Long wblut.hemesh.HE_PathHalfedge.key ()
Returns
void wblut.hemesh.HE_PathHalfedge.setHalfedge (final HE_Halfedge he)
Parameters
he
void wblut.hemesh.HE_PathHalfedge.setNext (final HE_PathHalfedge he)
Parameters
he
void wblut.hemesh.HE_PathHalfedge.setPrev (final HE_PathHalfedge he)
Parameters
he
String wblut.hemesh.HE_PathHalfedge.toString ()
References wblut.hemesh.HE_PathHalfedge.key().
Member Data Documentation
HE_Halfedge wblut.hemesh.HE_PathHalfedge._he private
HE_PathHalfedge wblut.hemesh.HE_PathHalfedge._next private
HE_PathHalfedge wblut.hemesh.HE_PathHalfedge._prev private
The documentation for this class was generated from the following file:
src/hemesh_core/wblut/hemesh/HE_PathHalfedge.java