HE_Mesh: wblut.nurbs.WB_RBezierSurface Class Reference
wblut.nurbs.WB_RBezierSurface Class Reference
Public Member Functions
WB_RBezierSurface (final WB_Coord[][] controlPoints)
WB_RBezierSurface (final WB_Coord[][] controlPoints, final double[][] weights)
WB_RBezierSurface (final WB_PointHomogeneous[][] controlPoints)
WB_Point surfacePoint (final double u, final double v)
WB_Coord[][] points ()
int n ()
int m ()
double loweru ()
double upperu ()
double lowerv ()
double upperv ()
WB_RBezierSurface elevateUDegree ()
WB_RBezierSurface elevateVDegree ()
Public Member Functions inherited from wblut.nurbs.WB_BezierSurface
WB_BezierSurface ()
WB_BezierSurface (final WB_Coord[][] controlPoints)
WB_BezierSurface (final WB_PointHomogeneous[][] controlPoints)
WB_Point surfacePoint (final double u, final double v)
WB_Coord[][] points ()
int n ()
int m ()
double loweru ()
double upperu ()
double lowerv ()
double upperv ()
WB_BezierSurface elevateUDegree ()
WB_BezierSurface elevateVDegree ()
HE_Mesh toControlHemesh ()
Public Member Functions inherited from wblut.geom.WB_Surface
WB_Point surfacePoint (double u, double v)
Protected Attributes
WB_PointHomogeneous[][] wpoints
Protected Attributes inherited from wblut.nurbs.WB_BezierSurface
WB_Coord[][] points
int n
int m
Private Attributes
final double[][] weights
Constructor & Destructor Documentation
wblut.nurbs.WB_RBezierSurface.WB_RBezierSurface (final WB_Coord controlPoints[][])
Parameters
controlPoints
References wblut.nurbs.WB_RBezierSurface.m(), wblut.nurbs.WB_RBezierSurface.n(), and wblut.nurbs.WB_RBezierSurface.points().
wblut.nurbs.WB_RBezierSurface.WB_RBezierSurface (final WB_Coord controlPoints[][], final double weights[][])
Parameters
controlPoints
weights
References wblut.nurbs.WB_RBezierSurface.m(), wblut.nurbs.WB_RBezierSurface.n(), wblut.nurbs.WB_RBezierSurface.points(), and wblut.nurbs.WB_RBezierSurface.weights.
wblut.nurbs.WB_RBezierSurface.WB_RBezierSurface (final WB_PointHomogeneous controlPoints[][])
Parameters
controlPoints
References wblut.nurbs.WB_RBezierSurface.m(), wblut.nurbs.WB_RBezierSurface.n(), and wblut.geom.WB_MutableCoordinate4D.wd().
Member Function Documentation
WB_RBezierSurface wblut.nurbs.WB_RBezierSurface.elevateUDegree ()
References wblut.geom.WB_PointHomogeneous.interpolate(), wblut.nurbs.WB_RBezierSurface.m(), wblut.nurbs.WB_RBezierSurface.n(), and wblut.nurbs.WB_RBezierSurface.WB_RBezierSurface().
WB_RBezierSurface wblut.nurbs.WB_RBezierSurface.elevateVDegree ()
References wblut.geom.WB_PointHomogeneous.interpolate(), wblut.nurbs.WB_RBezierSurface.m(), wblut.nurbs.WB_RBezierSurface.n(), and wblut.nurbs.WB_RBezierSurface.WB_RBezierSurface().
double wblut.nurbs.WB_RBezierSurface.loweru ()
Get the lower end of the u parameter range.
Returns
u
Implements wblut.geom.WB_Surface.
double wblut.nurbs.WB_RBezierSurface.lowerv ()
Get the lower end of the v parameter range.
Returns
v
Implements wblut.geom.WB_Surface.
int wblut.nurbs.WB_RBezierSurface.m ()
int wblut.nurbs.WB_RBezierSurface.n ()
WB_Coord [][] wblut.nurbs.WB_RBezierSurface.points ()
WB_Point wblut.nurbs.WB_RBezierSurface.surfacePoint (final double u, final double v)
References wblut.geom.WB_Point4D.addMulSelf(), wblut.math.WB_Bernstein.getBernsteinCoefficientsOfOrderN(), wblut.nurbs.WB_RBezierSurface.m(), wblut.nurbs.WB_RBezierSurface.n(), and wblut.geom.WB_PointHomogeneous.project().
double wblut.nurbs.WB_RBezierSurface.upperu ()
Get the upper end of the u parameter range.
Returns
u
Implements wblut.geom.WB_Surface.
double wblut.nurbs.WB_RBezierSurface.upperv ()
Get the upper end of the v parameter range.
Returns
v
Implements wblut.geom.WB_Surface.
Member Data Documentation
final double [][] wblut.nurbs.WB_RBezierSurface.weights private
WB_PointHomogeneous [][] wblut.nurbs.WB_RBezierSurface.wpoints protected
The documentation for this class was generated from the following file:
src/nurbs/wblut/nurbs/WB_RBezierSurface.java