HE_Mesh: wblut.processing.WB_Color Class Reference
wblut.processing.WB_Color Class Reference
Static Public Member Functions
static int color (int v1, int v2, int v3)
static int normColor (final double v1, final double v2, final double v3)
static int spectralColor (final double wavelength)
static int spectralColorZucconi6 (final double wavelength)
Static Public Attributes
static int[] HEAT
static int[] HOTMETAL
static int[] HOTMETALBLUE
static int[] OPTIMAL
static int[] GRAY
static int[] LINGRAY
static int[] PLRAINBOW
static int[] SPECTRUM = new int[256]
static int[] MAGMA
static int[] INFERNO
static int[] PLASMA
static int[] VIRIDIS
static int Candle = color(255, 147, 41)
static int Tungsten40W = color(255, 197, 143)
static int Tungsten100W = color(255, 214, 170)
static int Halogen = color(255, 241, 224)
static int CarbonArc = color(255, 250, 244)
static int HighNoonSun = color(255, 255, 251)
static int DirectSunlight = color(255, 255, 255)
static int OvercastSky = color(201, 226, 255)
static int ClearBlueSky = color(64, 156, 255)
static int WarmFluorescent = color(255, 244, 229)
static int StandardFluorescent = color(244, 255, 250)
static int CoolWhiteFluorescent = color(212, 235, 255)
static int FullSpectrumFluorescent = color(255, 244, 242)
static int GrowLightFluorescent = color(255, 239, 247)
static int BlackLightFluorescent = color(167, 0, 255)
static int MercuryVapor = color(216, 247, 255)
static int SodiumVapor = color(255, 209, 178)
static int MetalHalide = color(242, 252, 255)
static int HighPressureSodium = color(255, 183, 76)
Detailed Description
Author
FVH
Member Function Documentation
static int wblut.processing.WB_Color.color (int v1, int v2, int v3) static
Parameters
v1
v2
v3
Returns
static int wblut.processing.WB_Color.normColor (final double v1, final double v2, final double v3) static
References wblut.processing.WB_Color.color().
static int wblut.processing.WB_Color.spectralColor (final double wavelength) static
Wavelength to RGB color
Parameters
wavelength wavelength from 400nm-700nm
Returns
References wblut.processing.WB_Color.color().
static int wblut.processing.WB_Color.spectralColorZucconi6 (final double wavelength) static
Parameters
wavelength 400-700
Returns
References wblut.geom.WB_Vector.addSelf(), wblut.processing.WB_Color.color(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Vector.scaleSelf(), wblut.geom.WB_Vector.sub(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
Member Data Documentation
int wblut.processing.WB_Color.BlackLightFluorescent = color(167, 0, 255) static
int wblut.processing.WB_Color.Candle = color(255, 147, 41) static
int wblut.processing.WB_Color.CarbonArc = color(255, 250, 244) static
int wblut.processing.WB_Color.ClearBlueSky = color(64, 156, 255) static
int wblut.processing.WB_Color.CoolWhiteFluorescent = color(212, 235, 255) static
int wblut.processing.WB_Color.DirectSunlight = color(255, 255, 255) static
int wblut.processing.WB_Color.FullSpectrumFluorescent = color(255, 244, 242) static
int [] wblut.processing.WB_Color.GRAY static
int wblut.processing.WB_Color.GrowLightFluorescent = color(255, 239, 247) static
int wblut.processing.WB_Color.Halogen = color(255, 241, 224) static
int [] wblut.processing.WB_Color.HEAT static
int wblut.processing.WB_Color.HighNoonSun = color(255, 255, 251) static
int wblut.processing.WB_Color.HighPressureSodium = color(255, 183, 76) static
int [] wblut.processing.WB_Color.HOTMETAL static
int [] wblut.processing.WB_Color.HOTMETALBLUE static
int [] wblut.processing.WB_Color.INFERNO static
int [] wblut.processing.WB_Color.LINGRAY static
int [] wblut.processing.WB_Color.MAGMA static
int wblut.processing.WB_Color.MercuryVapor = color(216, 247, 255) static
int wblut.processing.WB_Color.MetalHalide = color(242, 252, 255) static
int [] wblut.processing.WB_Color.OPTIMAL static
int wblut.processing.WB_Color.OvercastSky = color(201, 226, 255) static
int [] wblut.processing.WB_Color.PLASMA static
int [] wblut.processing.WB_Color.PLRAINBOW static
int wblut.processing.WB_Color.SodiumVapor = color(255, 209, 178) static
int [] wblut.processing.WB_Color.SPECTRUM = new int[256] static
int wblut.processing.WB_Color.StandardFluorescent = color(244, 255, 250) static
int wblut.processing.WB_Color.Tungsten100W = color(255, 214, 170) static
int wblut.processing.WB_Color.Tungsten40W = color(255, 197, 143) static
int [] wblut.processing.WB_Color.VIRIDIS static
int wblut.processing.WB_Color.WarmFluorescent = color(255, 244, 229) static
The documentation for this class was generated from the following file:
src/processing/wblut/processing/WB_Color.java