HE_Mesh: wblut.hemesh.HEM_PunchHoles Class Reference
wblut.hemesh.HEM_PunchHoles Class Reference
Public Member Functions
HEM_PunchHoles ()
HEM_PunchHoles setWidth (final double w)
HEM_PunchHoles setWidth (final double w, final double hew)
HEM_PunchHoles setWidth (final WB_ScalarParameter w)
HEM_PunchHoles setWidth (final WB_ScalarParameter w, final WB_ScalarParameter hew)
HEM_PunchHoles setFuse (final boolean b)
HEM_PunchHoles setThresholdAngle (final double a)
HEM_PunchHoles setFuseAngle (final double a)
HEM_PunchHoles setRelative (final boolean relative)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_ScalarParameter sew
WB_ScalarParameter hew
double thresholdAngle
boolean fuse
double fuseAngle
boolean relative
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_PunchHoles.HEM_PunchHoles ()
References wblut.math.WB_ScalarParameter.ZERO.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_PunchHoles.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.deleteFaces(), wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HEM_Extrude.setChamfer(), wblut.hemesh.HEM_Extrude.setDistance(), wblut.hemesh.HEM_Extrude.setFuse(), wblut.hemesh.HEM_Extrude.setFuseAngle(), wblut.hemesh.HEM_Extrude.setHardEdgeChamfer(), wblut.hemesh.HEM_Extrude.setRelative(), wblut.hemesh.HEM_Extrude.setThresholdAngle(), and wblut.math.WB_ScalarParameter.ZERO.
HE_Mesh wblut.hemesh.HEM_PunchHoles.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Mesh.deleteFaces(), wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Selection.modify(), wblut.hemesh.HEM_Extrude.setChamfer(), wblut.hemesh.HEM_Extrude.setDistance(), wblut.hemesh.HEM_Extrude.setFuse(), wblut.hemesh.HEM_Extrude.setFuseAngle(), wblut.hemesh.HEM_Extrude.setHardEdgeChamfer(), wblut.hemesh.HEM_Extrude.setRelative(), wblut.hemesh.HEM_Extrude.setThresholdAngle(), and wblut.math.WB_ScalarParameter.ZERO.
HEM_PunchHoles wblut.hemesh.HEM_PunchHoles.setFuse (final boolean b)
Parameters
b
Returns
HEM_PunchHoles wblut.hemesh.HEM_PunchHoles.setFuseAngle (final double a)
Parameters
a
Returns
HEM_PunchHoles wblut.hemesh.HEM_PunchHoles.setRelative (final boolean relative)
Parameters
relative
Returns
References wblut.hemesh.HEM_PunchHoles.relative.
HEM_PunchHoles wblut.hemesh.HEM_PunchHoles.setThresholdAngle (final double a)
Parameters
a
Returns
HEM_PunchHoles wblut.hemesh.HEM_PunchHoles.setWidth (final double w)
Parameters
w
Returns
References wblut.math.WB_ScalarParameter.ZERO.
HEM_PunchHoles wblut.hemesh.HEM_PunchHoles.setWidth (final double w, final double hew)
Parameters
w
hew
Returns
References wblut.math.WB_ScalarParameter.ZERO.
HEM_PunchHoles wblut.hemesh.HEM_PunchHoles.setWidth (final WB_ScalarParameter w)
Parameters
w
Returns
HEM_PunchHoles wblut.hemesh.HEM_PunchHoles.setWidth (final WB_ScalarParameter w, final WB_ScalarParameter hew)
Parameters
w
hew
Returns
References wblut.hemesh.HEM_PunchHoles.hew.
Member Data Documentation
boolean wblut.hemesh.HEM_PunchHoles.fuse private
double wblut.hemesh.HEM_PunchHoles.fuseAngle private
WB_ScalarParameter wblut.hemesh.HEM_PunchHoles.hew private
boolean wblut.hemesh.HEM_PunchHoles.relative private
WB_ScalarParameter wblut.hemesh.HEM_PunchHoles.sew private
double wblut.hemesh.HEM_PunchHoles.thresholdAngle private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_PunchHoles.java