HE_Mesh: wblut.hemesh.HES_TriDec Class Reference
wblut.hemesh.HES_TriDec Class Reference
Classes
class Entry
class Heap
Public Member Functions
HES_TriDec ()
HES_TriDec setLambda (final double f)
HES_TriDec setGoal (final int r)
HES_TriDec setGoal (final double f)
Public Member Functions inherited from wblut.hemesh.HES_Simplifier
HES_Simplifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Static Public Member Functions
static double[] getVertexColor (final HE_Mesh mesh)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HES_Simplifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Member Functions
void buildHeap (final HE_Mesh sel)
void updateHeap (final List< HE_Vertex > vertices, final HE_Mesh selection)
double halfedgeCollapseCost (final HE_Halfedge he)
Static Private Member Functions
static double visualImportance (final HE_Vertex v)
Private Attributes
double _lambda
HE_Mesh _mesh
Heap heap
int goal
double fraction
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HES_TriDec.HES_TriDec ()
Member Function Documentation
HE_Mesh wblut.hemesh.HES_TriDec.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HES_TriDec._mesh, wblut.hemesh.HES_TriDec.buildHeap(), wblut.hemesh.HET_MeshOp.collapseHalfedge(), wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HES_TriDec.fraction, wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_Vertex.getNeighborVertices(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HES_TriDec.goal, wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HES_TriDec.Heap.pop(), wblut.hemesh.HE_Mesh.resetVertexInternalLabels(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HES_TriDec.Heap.size(), wblut.hemesh.HE_Machine.tracker, wblut.hemesh.HE_Mesh.triangulate(), and wblut.hemesh.HES_TriDec.updateHeap().
HE_Mesh wblut.hemesh.HES_TriDec.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HES_TriDec._mesh, wblut.hemesh.HES_TriDec.buildHeap(), wblut.hemesh.HE_Selection.clear(), wblut.hemesh.HET_MeshOp.collapseHalfedge(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HES_TriDec.fraction, wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_Vertex.getNeighborVertices(), wblut.hemesh.HE_Selection.getNumberOfVertices(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HES_TriDec.goal, wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HES_TriDec.Heap.pop(), wblut.hemesh.HE_Selection.remove(), wblut.hemesh.HE_Mesh.resetVertexInternalLabels(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HES_TriDec.Heap.size(), wblut.hemesh.HE_Machine.tracker, wblut.hemesh.HE_Mesh.triangulate(), and wblut.hemesh.HES_TriDec.updateHeap().
void wblut.hemesh.HES_TriDec.buildHeap (final HE_Mesh sel) private
Parameters
sel
References wblut.hemesh.HE_Vertex.getHalfedgeStar(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HES_TriDec.halfedgeCollapseCost(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Vertex.isBoundary(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HES_TriDec.Heap.push(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Machine.tracker, wblut.hemesh.HES_TriDec.visualImportance(), and wblut.hemesh.HE_Mesh.vItr().
static double [] wblut.hemesh.HES_TriDec.getVertexColor (final HE_Mesh mesh) static
Parameters
mesh
Returns
References wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.math.WB_Epsilon.isZero(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HES_TriDec.visualImportance(), and wblut.hemesh.HE_Mesh.vItr().
double wblut.hemesh.HES_TriDec.halfedgeCollapseCost (final HE_Halfedge he) private
Parameters
he
Returns
References wblut.geom.WB_Vector.dot(), wblut.geom.WB_Triangle.getArea(), wblut.hemesh.HE_Halfedge.getEdge(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceArea(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Halfedge.getLength(), wblut.hemesh.HE_Vertex.getNeighborVertices(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.geom.WB_Plane.getNormal(), wblut.hemesh.HE_Halfedge.getPair(), wblut.geom.WB_Triangle.getPlane(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Vector.subToVector3D().
HES_TriDec wblut.hemesh.HES_TriDec.setGoal (final int r)
Parameters
r
Returns
HES_TriDec wblut.hemesh.HES_TriDec.setGoal (final double f)
Parameters
f
Returns
HES_TriDec wblut.hemesh.HES_TriDec.setLambda (final double f)
Parameters
f
Returns
void wblut.hemesh.HES_TriDec.updateHeap (final List< HE_Vertex > vertices, final HE_Mesh selection) private
Parameters
vertices
selection
References wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HES_TriDec.halfedgeCollapseCost(), wblut.hemesh.HES_TriDec.Heap.push(), wblut.hemesh.HE_Mesh.setHalfedge(), and wblut.hemesh.HES_TriDec.visualImportance().
static double wblut.hemesh.HES_TriDec.visualImportance (final HE_Vertex v) static private
Parameters
v
Returns
References wblut.geom.WB_Vector.addMulSelf(), wblut.geom.WB_Vector.divSelf(), wblut.hemesh.HE_Vertex.getFaceStar(), wblut.geom.WB_Vector.getLength(), and wblut.math.WB_Epsilon.isZero().
Member Data Documentation
double wblut.hemesh.HES_TriDec._lambda private
HE_Mesh wblut.hemesh.HES_TriDec._mesh private
double wblut.hemesh.HES_TriDec.fraction private
int wblut.hemesh.HES_TriDec.goal private
Heap wblut.hemesh.HES_TriDec.heap private
The documentation for this class was generated from the following file:
src/hemesh_subdividors/wblut/hemesh/HES_TriDec.java