HE_Mesh: wblut.hemesh.HEC_Dual Class Reference
wblut.hemesh.HEC_Dual Class Reference
Public Member Functions
HEC_Dual ()
HEC_Dual (final HE_Mesh mesh)
HEC_Dual setSource (final HE_Mesh mesh)
HEC_Dual resetCenter (final boolean b)
HEC_Dual setKeepBoundary (final boolean b)
HEC_Dual setFixNonPlanarFaces (final boolean b)
HE_Mesh createBase ()
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Private Attributes
HE_Mesh source
boolean fixNonPlanarFaces
boolean setCenter
boolean keepBoundary
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Creates the dual of a mesh. Vertices are replace with faces connecting all face centers surrounding original vertex. The faces are replaced by vertices at their center.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_Dual.HEC_Dual ()
Instantiates a new HEC_Dual.
References wblut.hemesh.HEC_Creator.toModelview.
wblut.hemesh.HEC_Dual.HEC_Dual (final HE_Mesh mesh)
Instantiates a new HEC_Dual.
Parameters
mesh source mesh
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_Dual.createBase ()
References wblut.geom.WB_Point.add(), wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.addHalfedges(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HE_Mesh.cycleHalfedges(), wblut.geom.WB_Point.divSelf(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HEC_Dual.fixNonPlanarFaces, wblut.hemesh.HET_MeshOp.flipFaces(), wblut.hemesh.HE_Mesh.get(), wblut.hemesh.HE_Mesh.getCenter(), wblut.hemesh.HE_Halfedge.getEdgeCenter(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Mesh.getFaces(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getPrevInVertex(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Mesh.getVertexWithKey(), wblut.hemesh.HE_Mesh.heItr(), wblut.hemesh.HE_Vertex.isBoundary(), wblut.hemesh.HE_Halfedge.isOuterBoundary(), wblut.hemesh.HE_Halfedge.key(), wblut.hemesh.HE_Face.key(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HE_Mesh.moveToSelf(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HEM_TriSplit.splitFaceTri(), and wblut.hemesh.HE_Mesh.vItr().
HEC_Dual wblut.hemesh.HEC_Dual.resetCenter (final boolean b)
Parameters
b
Returns
HEC_Dual wblut.hemesh.HEC_Dual.setFixNonPlanarFaces (final boolean b)
Parameters
b
Returns
HEC_Dual wblut.hemesh.HEC_Dual.setKeepBoundary (final boolean b)
Parameters
b
Returns
HEC_Dual wblut.hemesh.HEC_Dual.setSource (final HE_Mesh mesh)
Set source mesh.
Parameters
mesh source mesh
Returns
self
Member Data Documentation
boolean wblut.hemesh.HEC_Dual.fixNonPlanarFaces private
boolean wblut.hemesh.HEC_Dual.keepBoundary private
boolean wblut.hemesh.HEC_Dual.setCenter private
HE_Mesh wblut.hemesh.HEC_Dual.source private
Source mesh.
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_Dual.java