HE_Mesh: wblut.geom.WB_Tetrahedron Class Reference
wblut.geom.WB_Tetrahedron Class Reference
Public Member Functions
WB_Tetrahedron (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4)
WB_Coord p1 ()
WB_Coord p2 ()
WB_Coord p3 ()
WB_Coord p4 ()
WB_Coord getPoint (final int i)
WB_Point getCenter ()
double getVolume ()
double getCircumradius ()
WB_Point getCircumcenter ()
WB_Sphere getCircumsphere ()
double getInradius ()
WB_Point getIncenter ()
WB_Sphere getInsphere ()
boolean isAcute ()
WB_Tetrahedron apply (final WB_Transform T)
Protected Member Functions
WB_Tetrahedron ()
Private Attributes
WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.geom.WB_Tetrahedron.WB_Tetrahedron () protected
wblut.geom.WB_Tetrahedron.WB_Tetrahedron (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4)
Parameters
p1
p2
p3
p4
References wblut.geom.WB_GeometryFactory3D.createPoint().
Member Function Documentation
WB_Tetrahedron wblut.geom.WB_Tetrahedron.apply (final WB_Transform T)
References wblut.geom.WB_Point.applyAsPoint(), and wblut.geom.WB_GeometryFactory3D.createTetrahedron().
WB_Point wblut.geom.WB_Tetrahedron.getCenter ()
References wblut.geom.WB_GeometryFactory3D.createMidpoint().
WB_Point wblut.geom.WB_Tetrahedron.getCircumcenter ()
Find the center of the circumscribing sphere.
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_GeometryFactory3D.createVectorFromTo(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.crossSelf(), wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Vector.mulSelf().
double wblut.geom.WB_Tetrahedron.getCircumradius ()
Calculate the radius of the circumsphere.
Returns
References wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_GeometryFactory3D.createVectorFromTo(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.crossSelf(), wblut.geom.WB_Vector.dot(), wblut.geom.WB_Vector.getLength(), and wblut.geom.WB_Vector.mulSelf().
WB_Sphere wblut.geom.WB_Tetrahedron.getCircumsphere ()
Find the circumscribing sphere.
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_GeometryFactory3D.createSphereWithRadius(), wblut.geom.WB_GeometryFactory3D.createVectorFromTo(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.crossSelf(), wblut.geom.WB_Vector.dot(), wblut.geom.WB_Vector.getLength(), and wblut.geom.WB_Vector.mulSelf().
WB_Point wblut.geom.WB_Tetrahedron.getIncenter ()
Find the center of the inscribed sphere.
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_GeometryFactory3D.createVectorFromTo(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.divSelf(), wblut.geom.WB_Vector.getLength(), and wblut.geom.WB_Vector.mulSelf().
double wblut.geom.WB_Tetrahedron.getInradius ()
Calculate the radius of the insphere.
Returns
References wblut.geom.WB_Vector.addMulSelf(), wblut.geom.WB_GeometryFactory3D.createVectorFromTo(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.crossSelf(), wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Vector.getLength().
WB_Sphere wblut.geom.WB_Tetrahedron.getInsphere ()
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_GeometryFactory3D.createSphereWithRadius(), wblut.geom.WB_GeometryFactory3D.createVectorFromTo(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.divSelf(), wblut.geom.WB_Vector.getLength(), and wblut.geom.WB_Vector.mulSelf().
WB_Coord wblut.geom.WB_Tetrahedron.getPoint (final int i)
References wblut.geom.WB_Tetrahedron.p1(), wblut.geom.WB_Tetrahedron.p2(), wblut.geom.WB_Tetrahedron.p3(), and wblut.geom.WB_Tetrahedron.p4().
double wblut.geom.WB_Tetrahedron.getVolume ()
Get the volume of the tetrahedron.
Returns
References wblut.geom.WB_GeometryFactory3D.createVectorFromTo(), wblut.geom.WB_Vector.crossSelf(), and wblut.geom.WB_Vector.dot().
boolean wblut.geom.WB_Tetrahedron.isAcute ()
Returns
References wblut.geom.WB_GeometryOp3D.getCosDihedralAngle().
WB_Coord wblut.geom.WB_Tetrahedron.p1 ()
Returns
WB_Coord wblut.geom.WB_Tetrahedron.p2 ()
Returns
WB_Coord wblut.geom.WB_Tetrahedron.p3 ()
Returns
WB_Coord wblut.geom.WB_Tetrahedron.p4 ()
Returns
Member Data Documentation
WB_GeometryFactory wblut.geom.WB_Tetrahedron.geometryfactory = new WB_GeometryFactory() private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Tetrahedron.java