HE_Mesh: wblut.hemesh.HET_Import Class Reference
wblut.hemesh.HET_Import Class Reference
Static Public Member Functions
static HE_Mesh readFromHemeshFile (final String path)
static HE_Mesh readFromBinaryHemeshFile (final String path)
static HE_Mesh readFromBinarySTLFile (final String path)
static HE_Mesh readFromOBJFile (final String path)
static HE_Mesh readFromOBJFileNoCheck (final String path)
static HE_Mesh readFromSimpleMeshFile (final String path)
Detailed Description
The Class HET_Import.
Member Function Documentation
static HE_Mesh wblut.hemesh.HET_Import.readFromBinaryHemeshFile (final String path) static
Parameters
path
Returns
References wblut.hemesh.HEC_FromBinaryHemeshFile.setPath().
static HE_Mesh wblut.hemesh.HET_Import.readFromBinarySTLFile (final String path) static
Parameters
path
Returns
References wblut.hemesh.HEC_FromBinarySTLFile.setPath().
static HE_Mesh wblut.hemesh.HET_Import.readFromHemeshFile (final String path) static
Parameters
path
Returns
References wblut.hemesh.HEC_FromHemeshFile.setPath().
static HE_Mesh wblut.hemesh.HET_Import.readFromOBJFile (final String path) static
Parameters
path
Returns
References wblut.hemesh.HEC_FromOBJFile.setPath().
static HE_Mesh wblut.hemesh.HET_Import.readFromOBJFileNoCheck (final String path) static
Parameters
path
Returns
References wblut.hemesh.HEC_FromOBJFileNoCheck.setPath().
static HE_Mesh wblut.hemesh.HET_Import.readFromSimpleMeshFile (final String path) static
Parameters
path
Returns
References wblut.hemesh.HEC_FromSimpleMeshFile.setPath().
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_Import.java