HE_Mesh: wblut.hemesh.HEM_Stretch Class Reference
wblut.hemesh.HEM_Stretch Class Reference
Public Member Functions
HEM_Stretch ()
HEM_Stretch setGroundPlane (final WB_Plane P)
HEM_Stretch setGroundPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
HEM_Stretch setStretchFactor (final double f)
HEM_Stretch setCompressionFactor (final double f)
HEM_Stretch setPosOnly (final boolean b)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_Plane groundPlane
WB_Vector stretchDirection
double stretchFactor
double compressionFactor
boolean posOnly
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Stretch and compress a mesh. Determined by a ground plane, a stretch factor and a compression factor. Most commonly, the ground plane normal is the stretch direction.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_Stretch.HEM_Stretch ()
Instantiates a new HEM_Stretch.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Stretch.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Point.addSelf(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Plane.getOrigin(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Point.mulSelf(), wblut.hemesh.HEM_Stretch.stretchDirection, wblut.geom.WB_Point.subSelf(), and wblut.hemesh.HE_Mesh.vItr().
HE_Mesh wblut.hemesh.HEM_Stretch.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Point.addSelf(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Plane.getOrigin(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Point.mulSelf(), wblut.hemesh.HEM_Stretch.stretchDirection, wblut.geom.WB_Point.subSelf(), and wblut.hemesh.HE_Selection.vItr().
HEM_Stretch wblut.hemesh.HEM_Stretch.setCompressionFactor (final double f)
Set compression factor perpendicular to stretch direction.
Parameters
f the f
Returns
self
HEM_Stretch wblut.hemesh.HEM_Stretch.setGroundPlane (final WB_Plane P)
Set ground plane.
Parameters
P ground plane
Returns
self
HEM_Stretch wblut.hemesh.HEM_Stretch.setGroundPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
Sets the ground plane.
Parameters
ox the ox
oy the oy
oz the oz
nx the nx
ny the ny
nz the nz
Returns
the hE m_ stretch
HEM_Stretch wblut.hemesh.HEM_Stretch.setPosOnly (final boolean b)
Positive only? Only apply modifier to positive side of ground plane.
Parameters
b true, false
Returns
self
HEM_Stretch wblut.hemesh.HEM_Stretch.setStretchFactor (final double f)
Set stretch factor along stretch direction.
Parameters
f the f
Returns
self
Member Data Documentation
double wblut.hemesh.HEM_Stretch.compressionFactor private
Compression factor.
WB_Plane wblut.hemesh.HEM_Stretch.groundPlane private
Ground plane.
boolean wblut.hemesh.HEM_Stretch.posOnly private
Modify only positive side of ground plane?.
WB_Vector wblut.hemesh.HEM_Stretch.stretchDirection private
Stretch direction.
double wblut.hemesh.HEM_Stretch.stretchFactor private
Stretch factor.
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Stretch.java