HE_Mesh: wblut.nurbs.WB_BezierSurface Class Reference
wblut.nurbs.WB_BezierSurface Class Reference
Public Member Functions
WB_BezierSurface ()
WB_BezierSurface (final WB_Coord[][] controlPoints)
WB_BezierSurface (final WB_PointHomogeneous[][] controlPoints)
WB_Point surfacePoint (final double u, final double v)
WB_Coord[][] points ()
int n ()
int m ()
double loweru ()
double upperu ()
double lowerv ()
double upperv ()
WB_BezierSurface elevateUDegree ()
WB_BezierSurface elevateVDegree ()
HE_Mesh toControlHemesh ()
Public Member Functions inherited from wblut.geom.WB_Surface
WB_Point surfacePoint (double u, double v)
Protected Attributes
WB_Coord[][] points
int n
int m
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.nurbs.WB_BezierSurface.WB_BezierSurface ()
wblut.nurbs.WB_BezierSurface.WB_BezierSurface (final WB_Coord controlPoints[][])
Parameters
controlPoints
wblut.nurbs.WB_BezierSurface.WB_BezierSurface (final WB_PointHomogeneous controlPoints[][])
Parameters
controlPoints
References wblut.nurbs.WB_BezierSurface.m(), wblut.nurbs.WB_BezierSurface.n(), and wblut.geom.WB_PointHomogeneous.project().
Member Function Documentation
WB_BezierSurface wblut.nurbs.WB_BezierSurface.elevateUDegree ()
Returns
References wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.nurbs.WB_BezierSurface.m(), wblut.nurbs.WB_BezierSurface.n(), and wblut.nurbs.WB_BezierSurface.WB_BezierSurface().
WB_BezierSurface wblut.nurbs.WB_BezierSurface.elevateVDegree ()
Returns
References wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.nurbs.WB_BezierSurface.m(), wblut.nurbs.WB_BezierSurface.n(), and wblut.nurbs.WB_BezierSurface.WB_BezierSurface().
double wblut.nurbs.WB_BezierSurface.loweru ()
Get the lower end of the u parameter range.
Returns
u
Implements wblut.geom.WB_Surface.
double wblut.nurbs.WB_BezierSurface.lowerv ()
Get the lower end of the v parameter range.
Returns
v
Implements wblut.geom.WB_Surface.
int wblut.nurbs.WB_BezierSurface.m ()
Returns
int wblut.nurbs.WB_BezierSurface.n ()
Returns
WB_Coord [][] wblut.nurbs.WB_BezierSurface.points ()
Returns
WB_Point wblut.nurbs.WB_BezierSurface.surfacePoint (final double u, final double v)
References wblut.geom.WB_Point.addMulSelf(), wblut.math.WB_Bernstein.getBernsteinCoefficientsOfOrderN(), wblut.nurbs.WB_BezierSurface.m(), and wblut.nurbs.WB_BezierSurface.n().
HE_Mesh wblut.nurbs.WB_BezierSurface.toControlHemesh ()
Returns
References wblut.nurbs.WB_BezierSurface.m(), wblut.nurbs.WB_BezierSurface.n(), wblut.hemesh.HEC_FromFacelist.setFaces(), and wblut.hemesh.HEC_FromFacelist.setVertices().
double wblut.nurbs.WB_BezierSurface.upperu ()
Get the upper end of the u parameter range.
Returns
u
Implements wblut.geom.WB_Surface.
double wblut.nurbs.WB_BezierSurface.upperv ()
Get the upper end of the v parameter range.
Returns
v
Implements wblut.geom.WB_Surface.
Member Data Documentation
WB_GeometryFactory wblut.nurbs.WB_BezierSurface.gf = new WB_GeometryFactory() static private
int wblut.nurbs.WB_BezierSurface.m protected
int wblut.nurbs.WB_BezierSurface.n protected
WB_Coord [][] wblut.nurbs.WB_BezierSurface.points protected
The documentation for this class was generated from the following file:
src/nurbs/wblut/nurbs/WB_BezierSurface.java