HE_Mesh: wblut.hemesh.HEC_FromVoronoiCells Class Reference
wblut.hemesh.HEC_FromVoronoiCells Class Reference
Public Member Functions
HEC_FromVoronoiCells ()
HEC_FromVoronoiCells setCells (final HE_MeshCollection cells)
HEC_FromVoronoiCells setCells (final HE_Mesh[] cells)
HEC_FromVoronoiCells setCells (final Collection< HE_Mesh > cells)
HEC_FromVoronoiCells setActive (final boolean[] on)
HEC_FromVoronoiCells setSurface (final boolean b)
HEC_FromVoronoiCells setCapBoundaries (final boolean b)
HEC_FromVoronoiCells setMembrane (final boolean b)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Attributes
HE_MeshCollection cells
boolean[] on
boolean capBoundaries
boolean membrane
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
This creator combines meshes created with HEMC_VoronoiCells into one mesh. A boolean array determines what cells to include.
Limitation:
this creator only works with meshes generated with HEMC_VoronoiCells.
Constructor & Destructor Documentation
wblut.hemesh.HEC_FromVoronoiCells.HEC_FromVoronoiCells ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_FromVoronoiCells.createBase () protected
References wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HE_Mesh.cleanUnusedElementsByFace(), wblut.hemesh.HEC_FromFacelist.createBase(), wblut.hemesh.HE_Mesh.deleteFace(), wblut.hemesh.HE_Selection.fItr(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HET_Fixer.fixNonManifoldVertices(), wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_MeshCollection.getMesh(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Element.getUserLabel(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HEC_FromVoronoiCells.membrane, wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_Mesh.selectFacesWithInternalLabel(), wblut.hemesh.HE_MeshElement.setColor(), wblut.hemesh.HEC_FromFacelist.setDuplicate(), wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Element.setUserLabel(), wblut.hemesh.HEC_FromFacelist.setVertices(), wblut.hemesh.HE_MeshCollection.size(), and wblut.hemesh.HE_Mesh.uncapBoundaryHalfedges().
HEC_FromVoronoiCells wblut.hemesh.HEC_FromVoronoiCells.setActive (final boolean[] on)
Parameters
on
Returns
References wblut.hemesh.HEC_FromVoronoiCells.on.
HEC_FromVoronoiCells wblut.hemesh.HEC_FromVoronoiCells.setCapBoundaries (final boolean b)
Parameters
b
Returns
HEC_FromVoronoiCells wblut.hemesh.HEC_FromVoronoiCells.setCells (final HE_MeshCollection cells)
Parameters
cells
Returns
References wblut.hemesh.HEC_FromVoronoiCells.cells.
HEC_FromVoronoiCells wblut.hemesh.HEC_FromVoronoiCells.setCells (final HE_Mesh[] cells)
Parameters
cells
Returns
HEC_FromVoronoiCells wblut.hemesh.HEC_FromVoronoiCells.setCells (final Collection< HE_Mesh > cells)
Parameters
cells
Returns
HEC_FromVoronoiCells wblut.hemesh.HEC_FromVoronoiCells.setMembrane (final boolean b)
Parameters
b
Returns
HEC_FromVoronoiCells wblut.hemesh.HEC_FromVoronoiCells.setSurface (final boolean b)
Parameters
b
Returns
Member Data Documentation
boolean wblut.hemesh.HEC_FromVoronoiCells.capBoundaries private
HE_MeshCollection wblut.hemesh.HEC_FromVoronoiCells.cells private
boolean wblut.hemesh.HEC_FromVoronoiCells.membrane private
boolean [] wblut.hemesh.HEC_FromVoronoiCells.on private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_FromVoronoiCells.java