HE_Mesh: wblut.geom.WB_Subdivision.WB_SubdivisionResult Class Reference
wblut.geom.WB_Subdivision.WB_SubdivisionResult Class Reference
Public Member Functions
WB_SubdivisionResult ()
void addTriangle (final WB_Triangle triangle)
void addQuad (final WB_Quad quad)
void addPentagon (final WB_Pentagon pentagon)
void addHexagon (final WB_Hexagon hexagon)
void addOctagon (final WB_Octagon octagon)
void addTriangle (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
void addQuad (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4)
void addPentagon (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4, final WB_Coord p5)
void addHexagon (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4, final WB_Coord p5, final WB_Coord p6)
void addOctagon (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4, final WB_Coord p5, final WB_Coord p6, final WB_Coord p7, final WB_Coord p8)
List< WB_Triangle > getTriangles ()
List< WB_Quad > getQuads ()
List< WB_Pentagon > getPentagons ()
List< WB_Hexagon > getHexagons ()
List< WB_Octagon > getOctagons ()
Constructor & Destructor Documentation
wblut.geom.WB_Subdivision.WB_SubdivisionResult.WB_SubdivisionResult ()
Member Function Documentation
void wblut.geom.WB_Subdivision.WB_SubdivisionResult.addHexagon (final WB_Hexagon hexagon)
void wblut.geom.WB_Subdivision.WB_SubdivisionResult.addHexagon (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4, final WB_Coord p5, final WB_Coord p6)
void wblut.geom.WB_Subdivision.WB_SubdivisionResult.addOctagon (final WB_Octagon octagon)
void wblut.geom.WB_Subdivision.WB_SubdivisionResult.addOctagon (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4, final WB_Coord p5, final WB_Coord p6, final WB_Coord p7, final WB_Coord p8)
void wblut.geom.WB_Subdivision.WB_SubdivisionResult.addPentagon (final WB_Pentagon pentagon)
void wblut.geom.WB_Subdivision.WB_SubdivisionResult.addPentagon (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4, final WB_Coord p5)
void wblut.geom.WB_Subdivision.WB_SubdivisionResult.addQuad (final WB_Quad quad)
References wblut.geom.WB_Subdivision.WB_SubdivisionResult.addTriangle(), wblut.geom.WB_Quad.isConvex(), wblut.geom.WB_Quad.p1, wblut.geom.WB_Quad.p2, wblut.geom.WB_Quad.p3, wblut.geom.WB_Quad.p4, and wblut.geom.WB_GeometryOp3D.pointInTriangleBary3D().
void wblut.geom.WB_Subdivision.WB_SubdivisionResult.addQuad (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4)
References wblut.geom.WB_Subdivision.WB_SubdivisionResult.addQuad().
void wblut.geom.WB_Subdivision.WB_SubdivisionResult.addTriangle (final WB_Triangle triangle)
void wblut.geom.WB_Subdivision.WB_SubdivisionResult.addTriangle (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
List<WB_Hexagon> wblut.geom.WB_Subdivision.WB_SubdivisionResult.getHexagons ()
List<WB_Octagon> wblut.geom.WB_Subdivision.WB_SubdivisionResult.getOctagons ()
List<WB_Pentagon> wblut.geom.WB_Subdivision.WB_SubdivisionResult.getPentagons ()
List<WB_Quad> wblut.geom.WB_Subdivision.WB_SubdivisionResult.getQuads ()
List<WB_Triangle> wblut.geom.WB_Subdivision.WB_SubdivisionResult.getTriangles ()
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Subdivision.java