HE_Mesh: wblut.geom.WB_Coordinate2D Class Reference
wblut.geom.WB_Coordinate2D Class Reference
Public Member Functions
WB_Coordinate2D ()
WB_Coordinate2D (final double x, final double y)
WB_Coordinate2D (final double[] x)
WB_Coordinate2D (final WB_Coord p)
double getd (final int i)
float getf (final int i)
double xd ()
double yd ()
double zd ()
double wd ()
float xf ()
float yf ()
float zf ()
float wf ()
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_Coord
double getd (int i)
float getf (int i)
Constructor & Destructor Documentation
wblut.geom.WB_Coordinate2D.WB_Coordinate2D ()
wblut.geom.WB_Coordinate2D.WB_Coordinate2D (final double x, final double y)
Parameters
x
y
wblut.geom.WB_Coordinate2D.WB_Coordinate2D (final double[] x)
Parameters
x
wblut.geom.WB_Coordinate2D.WB_Coordinate2D (final WB_Coord p)
Parameters
p
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
Member Function Documentation
int wblut.geom.WB_Coordinate2D.compareTo (final WB_Coord p)
References wblut.geom.WB_Coord.wd(), wblut.geom.WB_Coordinate2D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coordinate2D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_Coordinate2D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_Coordinate2D.zd().
int wblut.geom.WB_Coordinate2D.compareToY1st (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_Coord.wd(), wblut.geom.WB_Coordinate2D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coordinate2D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_Coordinate2D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_Coordinate2D.zd().
boolean wblut.geom.WB_Coordinate2D.equals (final Object o)
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_Coordinate2D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coordinate2D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_Coordinate2D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_Coordinate2D.zd().
double wblut.geom.WB_Coordinate2D.getd (final int i)
float wblut.geom.WB_Coordinate2D.getf (final int i)
int wblut.geom.WB_Coordinate2D.hashCode ()
References wblut.math.WB_HashCode.calculateHashCode(), wblut.geom.WB_Coordinate2D.xd(), and wblut.geom.WB_Coordinate2D.yd().
String wblut.geom.WB_Coordinate2D.toString ()
References wblut.geom.WB_Coordinate2D.xd(), and wblut.geom.WB_Coordinate2D.yd().
double wblut.geom.WB_Coordinate2D.wd ()
Get w as double.
Returns
w
Implements wblut.geom.WB_Coord.
float wblut.geom.WB_Coordinate2D.wf ()
Get w as float.
Returns
w
Implements wblut.geom.WB_Coord.
double wblut.geom.WB_Coordinate2D.xd ()
Get x as double.
Returns
x
Implements wblut.geom.WB_Coord.
float wblut.geom.WB_Coordinate2D.xf ()
Get x as float.
Returns
x
Implements wblut.geom.WB_Coord.
double wblut.geom.WB_Coordinate2D.yd ()
Get y as double.
Returns
y
Implements wblut.geom.WB_Coord.
float wblut.geom.WB_Coordinate2D.yf ()
Get y as float.
Returns
y
Implements wblut.geom.WB_Coord.
double wblut.geom.WB_Coordinate2D.zd ()
Get z as double.
Returns
z
Implements wblut.geom.WB_Coord.
float wblut.geom.WB_Coordinate2D.zf ()
Get z as float.
Returns
z
Implements wblut.geom.WB_Coord.
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Coordinate2D.java