HE_Mesh: wblut.hemesh.HEM_CenterSplit Class Reference
wblut.hemesh.HEM_CenterSplit Class Reference
Public Member Functions
HEM_CenterSplit ()
HEM_CenterSplit setOffset (final double d)
HEM_CenterSplit setChamfer (final double c)
HEM_CenterSplit setRelative (final boolean b)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
double d
double c
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_CenterSplit.HEM_CenterSplit ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_CenterSplit.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HE_Mesh.renameSelection(), wblut.hemesh.HEM_Extrude.setChamfer(), wblut.hemesh.HEM_Extrude.setDistance(), wblut.hemesh.HEM_Extrude.setRelative(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), and wblut.hemesh.HE_Machine.tracker.
HE_Mesh wblut.hemesh.HEM_CenterSplit.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Selection.modify(), wblut.hemesh.HE_Mesh.renameSelection(), wblut.hemesh.HEM_Extrude.setChamfer(), wblut.hemesh.HEM_Extrude.setDistance(), wblut.hemesh.HEM_Extrude.setRelative(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), and wblut.hemesh.HE_Machine.tracker.
HEM_CenterSplit wblut.hemesh.HEM_CenterSplit.setChamfer (final double c)
Parameters
c
Returns
References wblut.hemesh.HEM_CenterSplit.c.
HEM_CenterSplit wblut.hemesh.HEM_CenterSplit.setOffset (final double d)
Parameters
d
Returns
References wblut.hemesh.HEM_CenterSplit.d.
HEM_CenterSplit wblut.hemesh.HEM_CenterSplit.setRelative (final boolean b)
Member Data Documentation
double wblut.hemesh.HEM_CenterSplit.c private
double wblut.hemesh.HEM_CenterSplit.d private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_CenterSplit.java