HE_Mesh: wblut.hemesh.HE_Halfedge Class Reference
wblut.hemesh.HE_Halfedge Class Reference
Public Member Functions
HE_Halfedge ()
long key ()
HE_Halfedge getPrevInFace ()
HE_Halfedge getPrevInFace (final int n)
HE_Halfedge getNextInFace ()
HE_Halfedge getNextInFace (final int n)
HE_Halfedge getNextInVertex ()
HE_Halfedge getNextInVertex (final int n)
HE_Halfedge getPrevInVertex ()
HE_Halfedge getPrevInVertex (final int n)
HE_Halfedge getPair ()
WB_Classification getHalfedgeType ()
WB_Coord getHalfedgeVector ()
WB_Coord getHalfedgeTangent ()
WB_Coord getEdgeTangent ()
WB_Coord getHalfedgeCenter ()
WB_Coord getHalfedgeCenter (final double f)
WB_Coord getEdgeCenter ()
WB_Coord getEdgeCenter (final double f)
HE_Halfedge getEdge ()
HE_Face getFace ()
HE_Vertex getVertex ()
WB_Point getPosition ()
HE_Vertex getStartVertex ()
WB_Point getStartPosition ()
HE_Vertex getEndVertex ()
WB_Point getEndPosition ()
WB_Coord getEdgeNormal ()
WB_Coord getHalfedgeNormal ()
double getHalfedgeArea ()
double getHalfedgeDihedralAngle ()
String toString ()
double getLength ()
double getSqLength ()
boolean isEdge ()
boolean isBoundary ()
boolean isInnerBoundary ()
boolean isOuterBoundary ()
double getEdgeArea ()
double getEdgeDihedralAngle ()
double getEdgeCosDihedralAngle ()
void copyProperties (final HE_Halfedge el)
double getAngle ()
double getCotan ()
HE_TextureCoordinate getUVW ()
HE_TextureCoordinate getHalfedgeUVW ()
HE_TextureCoordinate getVertexUVW ()
void clearUVW ()
void setUVW (final double u, final double v, final double w)
void setUVW (final WB_Coord uvw)
void setUVW (final HE_TextureCoordinate uvw)
boolean hasHalfedgeUVW ()
boolean hasUVW ()
boolean hasVertexUVW ()
int compareTo (final HE_Halfedge he)
int hashCode ()
void clearPrecomputed ()
Public Member Functions inherited from wblut.hemesh.HE_MeshElement
HE_MeshElement ()
void clearVisited ()
void setVisited ()
void setVisited (final boolean b)
boolean isVisited ()
void setVisible (final boolean b)
boolean isVisible ()
int hashCode ()
boolean equals (final Object other)
void copyProperties (final HE_MeshElement el)
int getColor ()
void setColor (final int color)
Public Member Functions inherited from wblut.hemesh.HE_Element
HE_Element ()
final void setUserLabel (final int label)
final long getKey ()
final int getInternalLabel ()
final int getUserLabel ()
int hashCode ()
boolean equals (final Object other)
void copyProperties (final HE_Element el)
Protected Member Functions
void _setNext (final HE_Halfedge he)
void _setPrev (final HE_Halfedge he)
void _setPair (final HE_Halfedge he)
void _setFace (final HE_Face face)
void _setVertex (final HE_Vertex vertex)
void _clearNext ()
void _clearPrev ()
void _clearPair ()
void _clearFace ()
void _clearVertex ()
void clear ()
Protected Member Functions inherited from wblut.hemesh.HE_MeshElement
abstract void clear ()
Protected Member Functions inherited from wblut.hemesh.HE_Element
final void setInternalLabel (final int label)
abstract void clear ()
abstract void clearPrecomputed ()
Private Attributes
HE_Vertex _vertex
HE_Halfedge _pair
HE_Halfedge _next
HE_Halfedge _prev
HE_Face _face
HE_TextureCoordinate uvw
Additional Inherited Members
Protected Attributes inherited from wblut.hemesh.HE_MeshElement
volatile boolean visited
boolean visible
int color
Protected Attributes inherited from wblut.hemesh.HE_Element
final long key
int internalLabel
int userLabel
Static Protected Attributes inherited from wblut.hemesh.HE_MeshElement
static final WB_GeometryFactory gf = new WB_GeometryFactory()
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Static Protected Attributes inherited from wblut.hemesh.HE_Element
static AtomicLong currentKey = new AtomicLong(0)
Detailed Description
Half-edge element of half-edge data structure.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HE_Halfedge.HE_Halfedge ()
Instantiates a new HE_Halfedge.
Member Function Documentation
void wblut.hemesh.HE_Halfedge._clearFace () protected
Clear face.
void wblut.hemesh.HE_Halfedge._clearNext () protected
Clear next.
void wblut.hemesh.HE_Halfedge._clearPair () protected
Clear pair.
void wblut.hemesh.HE_Halfedge._clearPrev () protected
Clear prev.
void wblut.hemesh.HE_Halfedge._clearVertex () protected
Clear vertex.
void wblut.hemesh.HE_Halfedge._setFace (final HE_Face face) protected
Sets the face.
Parameters
face the new face
void wblut.hemesh.HE_Halfedge._setNext (final HE_Halfedge he) protected
Set next halfedge in face.
Parameters
he next halfedge
void wblut.hemesh.HE_Halfedge._setPair (final HE_Halfedge he) protected
Pair halfedges.
Parameters
he halfedge to pair
void wblut.hemesh.HE_Halfedge._setPrev (final HE_Halfedge he) protected
Sets previous halfedge in face, only to be called by setNext.
Parameters
he next halfedge
void wblut.hemesh.HE_Halfedge._setVertex (final HE_Vertex vertex) protected
Sets vertex.
Parameters
vertex vertex
void wblut.hemesh.HE_Halfedge.clear () protected
void wblut.hemesh.HE_Halfedge.clearPrecomputed ()
void wblut.hemesh.HE_Halfedge.clearUVW ()
Clear halfedge UVW.
int wblut.hemesh.HE_Halfedge.compareTo (final HE_Halfedge he)
Parameters
he
Returns
References wblut.hemesh.HE_Vertex.compareTo(), wblut.hemesh.HE_Halfedge.getVertex(), and wblut.hemesh.HE_Halfedge.key().
void wblut.hemesh.HE_Halfedge.copyProperties (final HE_Halfedge el)
Parameters
el
References wblut.hemesh.HE_Halfedge.getUVW().
double wblut.hemesh.HE_Halfedge.getAngle ()
Returns
References wblut.geom.WB_GeometryOp3D.getAngleBetween(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.hemesh.HE_Halfedge.getCotan ()
Computes cotangent of the angle opposite this halfedge. Triangles only
Returns
References wblut.hemesh.HET_MeshOp.getCotan().
HE_Halfedge wblut.hemesh.HE_Halfedge.getEdge ()
Get edge of halfedge.
Returns
edge
References wblut.hemesh.HE_Halfedge._pair, and wblut.hemesh.HE_Halfedge.isEdge().
double wblut.hemesh.HE_Halfedge.getEdgeArea ()
Get area of faces bounding edge.
Returns
area
References wblut.hemesh.HE_Halfedge._face, wblut.hemesh.HE_Halfedge._pair, wblut.hemesh.HE_Face.getFaceArea(), and wblut.hemesh.HE_Halfedge.isEdge().
WB_Coord wblut.hemesh.HE_Halfedge.getEdgeCenter ()
Returns
References wblut.hemesh.HE_Halfedge._vertex, wblut.geom.WB_GeometryFactory3D.createMidpoint(), wblut.hemesh.HE_Halfedge.getVertex(), and wblut.hemesh.HE_MeshElement.gf.
WB_Coord wblut.hemesh.HE_Halfedge.getEdgeCenter (final double f)
Parameters
f
Returns
References wblut.hemesh.HE_Halfedge._vertex, wblut.geom.WB_GeometryFactory3D.createMidpoint(), wblut.hemesh.HE_Halfedge.getEdgeNormal(), wblut.hemesh.HE_Halfedge.getVertex(), and wblut.hemesh.HE_MeshElement.gf.
double wblut.hemesh.HE_Halfedge.getEdgeCosDihedralAngle ()
References wblut.hemesh.HE_Halfedge._face, wblut.hemesh.HE_Halfedge._pair, wblut.geom.WB_GeometryOp3D.getCosDihedralAngleNorm(), wblut.hemesh.HE_Face.getFaceNormal(), and wblut.hemesh.HE_Halfedge.isEdge().
double wblut.hemesh.HE_Halfedge.getEdgeDihedralAngle ()
Return angle between adjacent faces.
Returns
angle
References wblut.hemesh.HE_Halfedge._face, wblut.hemesh.HE_Halfedge._pair, wblut.geom.WB_GeometryOp3D.getDihedralAngleNorm(), wblut.hemesh.HE_Face.getFaceNormal(), and wblut.hemesh.HE_Halfedge.isEdge().
WB_Coord wblut.hemesh.HE_Halfedge.getEdgeNormal ()
Returns
References wblut.hemesh.HE_Halfedge._face, wblut.hemesh.HE_Halfedge._pair, wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Halfedge.isEdge(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Coord wblut.hemesh.HE_Halfedge.getEdgeTangent ()
Returns
References wblut.hemesh.HE_Halfedge.getHalfedgeTangent(), wblut.hemesh.HE_Halfedge.isEdge(), and wblut.geom.WB_Vector.mul().
WB_Point wblut.hemesh.HE_Halfedge.getEndPosition ()
Get end position of halfedge.
Returns
vertex
References wblut.hemesh.HE_Halfedge._vertex, and wblut.hemesh.HE_Vertex.getPosition().
HE_Vertex wblut.hemesh.HE_Halfedge.getEndVertex ()
Get end vertex of halfedge.
Returns
vertex
References wblut.hemesh.HE_Halfedge._vertex.
HE_Face wblut.hemesh.HE_Halfedge.getFace ()
Get face of halfedge.
Returns
face
References wblut.hemesh.HE_Halfedge._face.
double wblut.hemesh.HE_Halfedge.getHalfedgeArea ()
Get area of faces bounding halfedge.
Returns
area
References wblut.hemesh.HE_Halfedge.getEdgeArea().
WB_Coord wblut.hemesh.HE_Halfedge.getHalfedgeCenter ()
Get center of halfedge.
Returns
center
References wblut.hemesh.HE_Halfedge._vertex, wblut.geom.WB_GeometryFactory3D.createMidpoint(), wblut.hemesh.HE_Halfedge.getVertex(), and wblut.hemesh.HE_MeshElement.gf.
WB_Coord wblut.hemesh.HE_Halfedge.getHalfedgeCenter (final double f)
Get offset center of halfedge.
Parameters
f
Returns
center
References wblut.hemesh.HE_Halfedge._vertex, wblut.geom.WB_GeometryFactory3D.createMidpoint(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Halfedge.getVertex(), and wblut.hemesh.HE_MeshElement.gf.
double wblut.hemesh.HE_Halfedge.getHalfedgeDihedralAngle ()
Get angle between adjacent faces.
Returns
angle
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Halfedge.getHalfedgeTangent(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.isInnerBoundary(), and wblut.hemesh.HE_Halfedge.isOuterBoundary().
WB_Coord wblut.hemesh.HE_Halfedge.getHalfedgeNormal ()
Get halfedge normal.
Returns
in-face normal of face, points inwards
References wblut.geom.WB_Vector.cross(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_MutableCoordinate.set(), and wblut.geom.WB_Vector.subSelf().
WB_Coord wblut.hemesh.HE_Halfedge.getHalfedgeTangent ()
Get tangent WB_Vector of halfedge.
Returns
tangent
References wblut.hemesh.HE_Halfedge._vertex, wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Vector.subToVector3D().
WB_Classification wblut.hemesh.HE_Halfedge.getHalfedgeType ()
Get type of face vertex associated with halfedge.
Returns
HE.FLAT, HE.CONVEX, HE.CONCAVE
References wblut.hemesh.HE_Halfedge._face, wblut.geom.WB_Classification.CONCAVE, wblut.geom.WB_Classification.CONVEX, wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Classification.FLAT, wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.geom.WB_Vector.isParallel(), wblut.geom.WB_Vector.mul(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Vector.subToVector3D().
HE_TextureCoordinate wblut.hemesh.HE_Halfedge.getHalfedgeUVW ()
Get texture coordinate belonging to this halfedge . If no halfedge UVW exists, zero coordinates are returned.
Returns
References wblut.hemesh.HE_Halfedge.uvw, and wblut.hemesh.HE_TextureCoordinate.ZERO.
WB_Coord wblut.hemesh.HE_Halfedge.getHalfedgeVector ()
References wblut.hemesh.HE_Halfedge._vertex, wblut.hemesh.HE_Halfedge.getVertex(), and wblut.geom.WB_Vector.subToVector3D().
double wblut.hemesh.HE_Halfedge.getLength ()
Returns
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.hemesh.HE_Halfedge.getEndVertex(), and wblut.hemesh.HE_Halfedge.getVertex().
HE_Halfedge wblut.hemesh.HE_Halfedge.getNextInFace ()
Get next halfedge in face.
Returns
next halfedge
References wblut.hemesh.HE_Halfedge._next.
HE_Halfedge wblut.hemesh.HE_Halfedge.getNextInFace (final int n)
Get n'th next halfedge in face.
Returns
next halfedge
References wblut.hemesh.HE_Halfedge.getNextInFace().
HE_Halfedge wblut.hemesh.HE_Halfedge.getNextInVertex ()
Get next halfedge in vertex.
Returns
next halfedge
References wblut.hemesh.HE_Halfedge.getNextInFace().
HE_Halfedge wblut.hemesh.HE_Halfedge.getNextInVertex (final int n)
Get n'th next halfedge in vertex.
Returns
References wblut.hemesh.HE_Halfedge.getNextInVertex().
HE_Halfedge wblut.hemesh.HE_Halfedge.getPair ()
Get paired halfedge.
Returns
paired halfedge
References wblut.hemesh.HE_Halfedge._pair.
WB_Point wblut.hemesh.HE_Halfedge.getPosition ()
References wblut.hemesh.HE_Vertex.getPosition().
HE_Halfedge wblut.hemesh.HE_Halfedge.getPrevInFace ()
Get previous halfedge in face.
Returns
previous halfedge
References wblut.hemesh.HE_Halfedge._prev.
HE_Halfedge wblut.hemesh.HE_Halfedge.getPrevInFace (final int n)
Get n'th previous halfedge in face.
Returns
References wblut.hemesh.HE_Halfedge.getPrevInFace().
HE_Halfedge wblut.hemesh.HE_Halfedge.getPrevInVertex ()
Get previous halfedge in vertex.
Returns
References wblut.hemesh.HE_Halfedge.getPair(), and wblut.hemesh.HE_Halfedge.getPrevInFace().
HE_Halfedge wblut.hemesh.HE_Halfedge.getPrevInVertex (final int n)
Get n'th previous halfedge in vertex.
Returns
References wblut.hemesh.HE_Halfedge.getPrevInVertex().
double wblut.hemesh.HE_Halfedge.getSqLength ()
Returns
References wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), and wblut.hemesh.HE_Halfedge.getVertex().
WB_Point wblut.hemesh.HE_Halfedge.getStartPosition ()
References wblut.hemesh.HE_Vertex.getPosition().
HE_Vertex wblut.hemesh.HE_Halfedge.getStartVertex ()
Returns
References wblut.hemesh.HE_Halfedge._vertex.
HE_TextureCoordinate wblut.hemesh.HE_Halfedge.getUVW ()
Get texture coordinate belonging to the halfedge vertex in this face. If no halfedge UVW exists, returns the vertex UVW. If neither exist, zero coordinates are returned.
Returns
References wblut.hemesh.HE_Vertex.getVertexUVW(), wblut.hemesh.HE_Halfedge.uvw, and wblut.hemesh.HE_TextureCoordinate.ZERO.
HE_Vertex wblut.hemesh.HE_Halfedge.getVertex ()
Get vertex of halfedge.
Returns
vertex
References wblut.hemesh.HE_Halfedge._vertex.
HE_TextureCoordinate wblut.hemesh.HE_Halfedge.getVertexUVW ()
Get texture coordinate belonging to the halfedge vertex. If no vertex UVW exists, zero coordinates are returned.
Returns
References wblut.hemesh.HE_Vertex.getVertexUVW(), and wblut.hemesh.HE_TextureCoordinate.ZERO.
boolean wblut.hemesh.HE_Halfedge.hasHalfedgeUVW ()
Check if this halfedge has texture coordinates.
Returns
int wblut.hemesh.HE_Halfedge.hashCode ()
References wblut.math.WB_HashCode.calculateHashCode(), wblut.hemesh.HE_Halfedge.getVertex(), and wblut.hemesh.HE_Vertex.hashCode().
boolean wblut.hemesh.HE_Halfedge.hasUVW ()
Check if the halfedge vertex has a UVW for this face, either a halfedge UVW or a vertex UVW.
Returns
References wblut.hemesh.HE_Vertex.hasVertexUVW().
boolean wblut.hemesh.HE_Halfedge.hasVertexUVW ()
Check if the halfedge vertex has a vertex UVW.
Returns
References wblut.hemesh.HE_Vertex.hasVertexUVW().
boolean wblut.hemesh.HE_Halfedge.isBoundary ()
Returns
References wblut.hemesh.HE_Halfedge.isInnerBoundary().
boolean wblut.hemesh.HE_Halfedge.isEdge ()
A halfedge is considered an edge if it has a paired halfedge and one of these conditions is met:
a) both the halfedge and its pair have no face, and the halfedge key is lower b) the halfedge has a face and its pair has no face c) both the halfedge and its pair have a face, and the halfedge key is lower.
Returns
References wblut.hemesh.HE_Halfedge._face, and wblut.hemesh.HE_Halfedge.key().
boolean wblut.hemesh.HE_Halfedge.isInnerBoundary ()
Returns
References wblut.hemesh.HE_Halfedge._face.
boolean wblut.hemesh.HE_Halfedge.isOuterBoundary ()
Returns
long wblut.hemesh.HE_Halfedge.key ()
Get key.
Returns
key
void wblut.hemesh.HE_Halfedge.setUVW (final double u, final double v, final double w)
Set halfedge UVW.
Parameters
u
v
w
void wblut.hemesh.HE_Halfedge.setUVW (final WB_Coord uvw)
Set halfedge UVW.
Parameters
uvw WB_Coord
void wblut.hemesh.HE_Halfedge.setUVW (final HE_TextureCoordinate uvw)
Set halfedge UVW.
Parameters
uvw HE_TextureCoordinate
String wblut.hemesh.HE_Halfedge.toString ()
References wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Element.getUserLabel(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.isEdge(), wblut.hemesh.HE_Halfedge.key(), and wblut.hemesh.HE_Vertex.key().
Member Data Documentation
HE_Face wblut.hemesh.HE_Halfedge._face private
Associated face.
HE_Halfedge wblut.hemesh.HE_Halfedge._next private
Next halfedge in face.
HE_Halfedge wblut.hemesh.HE_Halfedge._pair private
Halfedge pair.
HE_Halfedge wblut.hemesh.HE_Halfedge._prev private
Previous halfedge in face.
HE_Vertex wblut.hemesh.HE_Halfedge._vertex private
Start vertex of halfedge.
HE_TextureCoordinate wblut.hemesh.HE_Halfedge.uvw private
Associated edge.
The documentation for this class was generated from the following file:
src/hemesh_core/wblut/hemesh/HE_Halfedge.java