HE_Mesh: wblut.hemesh.HEM_KeepLargestParts Class Reference
wblut.hemesh.HEM_KeepLargestParts Class Reference
Classes
class MeshSizeComparator
Public Member Functions
HEM_KeepLargestParts ()
HEM_KeepLargestParts (final int number)
HEM_KeepLargestParts setNumberOfParts (final int n)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
int n
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_KeepLargestParts.HEM_KeepLargestParts ()
wblut.hemesh.HEM_KeepLargestParts.HEM_KeepLargestParts (final int number)
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_KeepLargestParts.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.clear(), wblut.hemesh.HE_MeshCollection.getMesh(), wblut.hemesh.HEMC_Explode.setMesh(), and wblut.hemesh.HE_MeshCollection.size().
HE_Mesh wblut.hemesh.HEM_KeepLargestParts.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HEM_KeepLargestParts.applySelf().
HEM_KeepLargestParts wblut.hemesh.HEM_KeepLargestParts.setNumberOfParts (final int n)
Parameters
n
Returns
References wblut.hemesh.HEM_KeepLargestParts.n.
Member Data Documentation
int wblut.hemesh.HEM_KeepLargestParts.n private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_KeepLargestParts.java