HE_Mesh: wblut.geom.WB_IsoValues3D.HashGrid3D Class Reference
wblut.geom.WB_IsoValues3D.HashGrid3D Class Reference
Public Member Functions
HashGrid3D (final WB_HashGridDouble values)
double getValue (final int i, final int j, final int k)
int getSizeI ()
int getSizeJ ()
int getSizeK ()
Public Member Functions inherited from wblut.geom.WB_IsoValues3D
abstract double getValue (int i, int j, int k)
abstract int getSizeI ()
abstract int getSizeJ ()
abstract int getSizeK ()
WB_BinaryGrid3D getBinaryGrid3D (final int sizeX, final int sizeY, final int sizeZ, final double threshold)
Private Attributes
WB_HashGridDouble values
Constructor & Destructor Documentation
wblut.geom.WB_IsoValues3D.HashGrid3D.HashGrid3D (final WB_HashGridDouble values)
References wblut.geom.WB_IsoValues3D.HashGrid3D.values.
Member Function Documentation
int wblut.geom.WB_IsoValues3D.HashGrid3D.getSizeI ()
References wblut.geom.WB_HashGridDouble.getSizeI().
int wblut.geom.WB_IsoValues3D.HashGrid3D.getSizeJ ()
References wblut.geom.WB_HashGridDouble.getSizeJ().
int wblut.geom.WB_IsoValues3D.HashGrid3D.getSizeK ()
References wblut.geom.WB_HashGridDouble.getSizeK().
double wblut.geom.WB_IsoValues3D.HashGrid3D.getValue (final int i, final int j, final int k)
References wblut.geom.WB_HashGridDouble.getValue().
Member Data Documentation
WB_HashGridDouble wblut.geom.WB_IsoValues3D.HashGrid3D.values private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_IsoValues3D.java