HE_Mesh: wblut.math.WB_SNoise Class Reference
wblut.math.WB_SNoise Class Reference
Classes
class Grad
Public Member Functions
WB_SNoise ()
WB_SNoise (final long seed)
void setSeed (long seed)
double value1D (final double x)
double value2D (final double x, final double y)
double value3D (final double x, final double y, final double z)
double value4D (final double x, final double y, final double z, final double w)
void setScale (final double sx)
void setScale (final double sx, final double sy)
void setScale (final double sx, final double sy, final double sz)
void setScale (final double sx, final double sy, final double sz, final double sw)
Public Member Functions inherited from wblut.math.WB_Noise
double value1D (double x)
double value2D (double x, double y)
double value3D (double x, double y, double z)
double value4D (double x, double y, double z, double w)
void setScale (double sx)
void setScale (double sx, double sy)
void setScale (double sx, double sy, double sz)
void setScale (double sx, double sy, double sz, double sw)
Static Private Member Functions
static int fastfloor (final double x)
static double dot (final Grad g, final double x, final double y)
static double dot (final Grad g, final double x, final double y, final double z)
static double dot (final Grad g, final double x, final double y, final double z, final double w)
Private Attributes
short p [] = new short[256]
short perm [] = new short[512]
short permMod12 [] = new short[512]
double sx
Static Private Attributes
static Grad grad3 []
static Grad grad4 []
static final double F2 = 0.5 * (Math.sqrt(3.0) - 1.0)
static final double G2 = (3.0 - Math.sqrt(3.0)) / 6.0
static final double F3 = 1.0 / 3.0
static final double G3 = 1.0 / 6.0
static final double F4 = (Math.sqrt(5.0) - 1.0) / 4.0
static final double G4 = (5.0 - Math.sqrt(5.0)) / 20.0
Constructor & Destructor Documentation
wblut.math.WB_SNoise.WB_SNoise ()
wblut.math.WB_SNoise.WB_SNoise (final long seed)
Parameters
seed
References wblut.math.WB_SNoise.setSeed().
Member Function Documentation
static double wblut.math.WB_SNoise.dot (final Grad g, final double x, final double y) static private
Parameters
g
x
y
Returns
static double wblut.math.WB_SNoise.dot (final Grad g, final double x, final double y, final double z) static private
Parameters
g
x
y
z
Returns
static double wblut.math.WB_SNoise.dot (final Grad g, final double x, final double y, final double z, final double w) static private
Parameters
g
x
y
z
w
Returns
static int wblut.math.WB_SNoise.fastfloor (final double x) static private
Parameters
x
Returns
void wblut.math.WB_SNoise.setScale (final double sx)
References wblut.math.WB_SNoise.sx.
void wblut.math.WB_SNoise.setScale (final double sx, final double sy)
References wblut.math.WB_SNoise.sx.
void wblut.math.WB_SNoise.setScale (final double sx, final double sy, final double sz)
References wblut.math.WB_SNoise.sx.
void wblut.math.WB_SNoise.setScale (final double sx, final double sy, final double sz, final double sw)
References wblut.math.WB_SNoise.sx.
void wblut.math.WB_SNoise.setSeed (long seed)
Parameters
seed
Implements wblut.math.WB_Noise.
double wblut.math.WB_SNoise.value1D (final double x)
References wblut.math.WB_SNoise.value2D().
double wblut.math.WB_SNoise.value2D (final double x, final double y)
References wblut.math.WB_SNoise.dot(), wblut.math.WB_SNoise.fastfloor(), and wblut.math.WB_SNoise.G2.
double wblut.math.WB_SNoise.value3D (final double x, final double y, final double z)
References wblut.math.WB_SNoise.dot(), wblut.math.WB_SNoise.fastfloor(), and wblut.math.WB_SNoise.G3.
double wblut.math.WB_SNoise.value4D (final double x, final double y, final double z, final double w)
References wblut.math.WB_SNoise.dot(), wblut.math.WB_SNoise.fastfloor(), and wblut.math.WB_SNoise.G4.
Member Data Documentation
final double wblut.math.WB_SNoise.F2 = 0.5 * (Math.sqrt(3.0) - 1.0) static private
final double wblut.math.WB_SNoise.F3 = 1.0 / 3.0 static private
final double wblut.math.WB_SNoise.F4 = (Math.sqrt(5.0) - 1.0) / 4.0 static private
final double wblut.math.WB_SNoise.G2 = (3.0 - Math.sqrt(3.0)) / 6.0 static private
final double wblut.math.WB_SNoise.G3 = 1.0 / 6.0 static private
final double wblut.math.WB_SNoise.G4 = (5.0 - Math.sqrt(5.0)) / 20.0 static private
Grad wblut.math.WB_SNoise.grad3[] static private
Initial value:
= { new Grad(1, 1, 0), new Grad(-1, 1, 0), new Grad(1, -1, 0), new Grad(-1, -1, 0),
            new Grad(1, 0, 1), new Grad(-1, 0, 1), new Grad(1, 0, -1), new Grad(-1, 0, -1), new Grad(0, 1, 1),
            new Grad(0, -1, 1), new Grad(0, 1, -1), new Grad(0, -1, -1) }
Grad wblut.math.WB_SNoise.grad4[] static private
Initial value:
= { new Grad(0, 1, 1, 1), new Grad(0, 1, 1, -1), new Grad(0, 1, -1, 1),
            new Grad(0, 1, -1, -1), new Grad(0, -1, 1, 1), new Grad(0, -1, 1, -1), new Grad(0, -1, -1, 1),
            new Grad(0, -1, -1, -1), new Grad(1, 0, 1, 1), new Grad(1, 0, 1, -1), new Grad(1, 0, -1, 1),
            new Grad(1, 0, -1, -1), new Grad(-1, 0, 1, 1), new Grad(-1, 0, 1, -1), new Grad(-1, 0, -1, 1),
            new Grad(-1, 0, -1, -1), new Grad(1, 1, 0, 1), new Grad(1, 1, 0, -1), new Grad(1, -1, 0, 1),
            new Grad(1, -1, 0, -1), new Grad(-1, 1, 0, 1), new Grad(-1, 1, 0, -1), new Grad(-1, -1, 0, 1),
            new Grad(-1, -1, 0, -1), new Grad(1, 1, 1, 0), new Grad(1, 1, -1, 0), new Grad(1, -1, 1, 0),
            new Grad(1, -1, -1, 0), new Grad(-1, 1, 1, 0), new Grad(-1, 1, -1, 0), new Grad(-1, -1, 1, 0),
            new Grad(-1, -1, -1, 0) }
short wblut.math.WB_SNoise.p[] = new short[256] private
short wblut.math.WB_SNoise.perm[] = new short[512] private
short wblut.math.WB_SNoise.permMod12[] = new short[512] private
double wblut.math.WB_SNoise.sx private
The documentation for this class was generated from the following file:
src/math/wblut/math/WB_SNoise.java