HE_Mesh: wblut.hemesh.HEM_CenterSplitHole Class Reference
wblut.hemesh.HEM_CenterSplitHole Class Reference
Public Member Functions
HEM_CenterSplitHole ()
HEM_CenterSplitHole setOffset (final double d)
HEM_CenterSplitHole setChamfer (final double c)
HEM_CenterSplitHole setRelative (final boolean b)
HE_Selection getWallFaces ()
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
double d
double c
HE_Selection selectionOut
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_CenterSplitHole.HEM_CenterSplitHole ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_CenterSplitHole.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.deleteFaces(), wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HE_Mesh.removeSelection(), wblut.hemesh.HEM_Extrude.setChamfer(), wblut.hemesh.HEM_Extrude.setDistance(), and wblut.hemesh.HEM_Extrude.setRelative().
HE_Mesh wblut.hemesh.HEM_CenterSplitHole.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Mesh.deleteFaces(), wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Selection.modify(), wblut.hemesh.HE_Mesh.removeSelection(), wblut.hemesh.HEM_Extrude.setChamfer(), wblut.hemesh.HEM_Extrude.setDistance(), and wblut.hemesh.HEM_Extrude.setRelative().
HE_Selection wblut.hemesh.HEM_CenterSplitHole.getWallFaces ()
Returns
References wblut.hemesh.HEM_CenterSplitHole.selectionOut.
HEM_CenterSplitHole wblut.hemesh.HEM_CenterSplitHole.setChamfer (final double c)
Parameters
c
Returns
References wblut.hemesh.HEM_CenterSplitHole.c.
HEM_CenterSplitHole wblut.hemesh.HEM_CenterSplitHole.setOffset (final double d)
Parameters
d
Returns
References wblut.hemesh.HEM_CenterSplitHole.d.
HEM_CenterSplitHole wblut.hemesh.HEM_CenterSplitHole.setRelative (final boolean b)
Member Data Documentation
double wblut.hemesh.HEM_CenterSplitHole.c private
double wblut.hemesh.HEM_CenterSplitHole.d private
HE_Selection wblut.hemesh.HEM_CenterSplitHole.selectionOut private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_CenterSplitHole.java