HE_Mesh: wblut.geom.WB_RandomSegment Class Reference
wblut.geom.WB_RandomSegment Class Reference
Public Member Functions
WB_RandomSegment (final WB_Coord start, final WB_Coord end)
WB_RandomSegment (final WB_Coord start, final WB_Coord end, final long seed)
WB_RandomSegment setSeed (final long seed)
WB_Point nextPoint ()
WB_Vector nextVector ()
void reset ()
WB_RandomSegment setOffset (final WB_Coord offset)
WB_RandomSegment setOffset (final double x, final double y)
WB_RandomSegment setOffset (final double x, final double y, final double z)
Public Member Functions inherited from wblut.geom.WB_RandomPoint
WB_RandomPoint setOffset (WB_Coord offset)
WB_RandomPoint setOffset (double x, double y)
WB_RandomPoint setOffset (double x, double y, double z)
Private Attributes
final WB_MTRandom randomGen
WB_Vector offset
Detailed Description
Random generator for vectors uniformly distributed on a halfopen linesegment
Author
Frederik Vanhoutte, W:Blut
Constructor & Destructor Documentation
wblut.geom.WB_RandomSegment.WB_RandomSegment (final WB_Coord start, final WB_Coord end)
Parameters
start
end
wblut.geom.WB_RandomSegment.WB_RandomSegment (final WB_Coord start, final WB_Coord end, final long seed)
Parameters
start
end
seed
Member Function Documentation
WB_Point wblut.geom.WB_RandomSegment.nextPoint ()
Get the next random point.
Returns
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.nextDouble(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_RandomSegment.nextVector ()
Get the next random vector.
Returns
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.nextDouble(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_RandomSegment.reset ()
Reset the RNG.
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.reset().
WB_RandomSegment wblut.geom.WB_RandomSegment.setOffset (final WB_Coord offset)
WB_RandomSegment wblut.geom.WB_RandomSegment.setOffset (final double x, final double y)
References wblut.geom.WB_MutableCoordinate.set().
WB_RandomSegment wblut.geom.WB_RandomSegment.setOffset (final double x, final double y, final double z)
References wblut.geom.WB_MutableCoordinate.set().
WB_RandomSegment wblut.geom.WB_RandomSegment.setSeed (final long seed)
Set the seed for the RNG.
Parameters
seed
Returns
this
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.setSeed().
Member Data Documentation
WB_Vector wblut.geom.WB_RandomSegment.offset private
final WB_MTRandom wblut.geom.WB_RandomSegment.randomGen private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_RandomSegment.java