HE_Mesh: wblut.hemesh.HEC_Creator Class Reference
wblut.hemesh.HEC_Creator Class Reference abstract
Public Member Functions
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Public Attributes
PApplet home
Protected Member Functions
abstract HE_Mesh createBase ()
Protected Attributes
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Abstract base class for mesh creation. Implementation should return a valid HE_Mesh.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_Creator.HEC_Creator ()
Constructor.
References wblut.geom.WB_Vector.Z.
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_Creator.apply (final HE_Mesh mesh)
References wblut.hemesh.HEC_Creator.create().
HE_Mesh wblut.hemesh.HEC_Creator.apply (final HE_Selection sel)
References wblut.hemesh.HEC_Creator.create().
final HE_Mesh wblut.hemesh.HEC_Creator.create ()
Generate a mesh, move to center and orient along axis.
Returns
HE_Mesh
References wblut.math.WB_Math.clamp(), wblut.hemesh.HEC_Creator.createBase(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.hemesh.HET_Fixer.fixNonManifoldVertices(), wblut.hemesh.HE_Mesh.getCenter(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.hemesh.HE_Mesh.moveToSelf(), wblut.hemesh.HE_Mesh.rotateAboutAxis2PSelf(), wblut.hemesh.HE_Mesh.scaleSelf(), wblut.hemesh.HE_Vertex.set(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Machine.tracker, wblut.hemesh.HE_Mesh.vItr(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.hemesh.HE_Vertex.xf(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.hemesh.HE_Vertex.yf(), wblut.geom.WB_Coord.zd(), wblut.geom.WB_MutableCoordinate.zd(), and wblut.hemesh.HE_Vertex.zf().
abstract HE_Mesh wblut.hemesh.HEC_Creator.createBase () abstract protected
Creates the base.
Returns
HE_Mesh
HEC_Creator wblut.hemesh.HEC_Creator.setCenter (final double x, final double y, final double z)
Set center of mesh.
Parameters
x x-coordinate of center
y y-coordinate of center
z z-coordinate of center
Returns
self
References wblut.geom.WB_MutableCoordinate.set().
HEC_Creator wblut.hemesh.HEC_Creator.setCenter (final WB_Coord c)
Set center of mesh.
Parameters
c center
Returns
self
References wblut.geom.WB_MutableCoordinate.set().
HEC_Creator wblut.hemesh.HEC_Creator.setManifoldCheck (final boolean b)
Parameters
b
Returns
HEC_Creator wblut.hemesh.HEC_Creator.setOverride (final boolean b)
Parameters
b
Returns
HEC_Creator wblut.hemesh.HEC_Creator.setScale (final double s)
Parameters
s
Returns
HEC_Creator wblut.hemesh.HEC_Creator.setToModelview (final PApplet home)
Use the applet's modelview coordinates.
Parameters
home calling applet, typically "this"
Returns
self
References wblut.hemesh.HEC_Creator.home.
HEC_Creator wblut.hemesh.HEC_Creator.setToWorldview ()
Use absolute coordinates.
Returns
self
HEC_Creator wblut.hemesh.HEC_Creator.setZAngle (final double a)
Rotation of mesh about local Z-axis.
Parameters
a angle
Returns
self
HEC_Creator wblut.hemesh.HEC_Creator.setZAxis (final double x, final double y, final double z)
Orientation of local Z-axis of mesh.
Parameters
x x-coordinate of axis vector
y y-coordinate of axis vector
z z-coordinate of axis vector
Returns
self
References wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
HEC_Creator wblut.hemesh.HEC_Creator.setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
Local Z-axis of mesh.
Parameters
p0x x-coordinate of first point on axis
p0y y-coordinate of first point on axis
p0z z-coordinate of first point on axis
p1x x-coordinate of second point on axis
p1y y-coordinate of second point on axis
p1z z-coordinate of second point on axis
Returns
self
References wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
HEC_Creator wblut.hemesh.HEC_Creator.setZAxis (final WB_Coord p)
Orientation of local Z-axis of mesh.
Parameters
p axis vector
Returns
self
References wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
HEC_Creator wblut.hemesh.HEC_Creator.setZAxis (final WB_Coord p0, final WB_Coord p1)
Local Z-axis of mesh.
Parameters
p0 first point on axis
p1 second point on axis
Returns
self
References wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_MutableCoordinate.set(), and wblut.geom.WB_Vector.sub().
Member Data Documentation
WB_Point wblut.hemesh.HEC_Creator.center protected
Center.
PApplet wblut.hemesh.HEC_Creator.home
Calling applet.
boolean wblut.hemesh.HEC_Creator.manifoldCheck protected
boolean wblut.hemesh.HEC_Creator.override protected
Override.
boolean wblut.hemesh.HEC_Creator.override2D protected
double wblut.hemesh.HEC_Creator.scale protected
boolean wblut.hemesh.HEC_Creator.toModelview protected
Use applet model coordinates.
WB_Vector wblut.hemesh.HEC_Creator.Z protected
Base Z-axis.
double wblut.hemesh.HEC_Creator.zangle protected
Rotation angle about Z-axis.
WB_Vector wblut.hemesh.HEC_Creator.zaxis protected
Z-axis.
The documentation for this class was generated from the following file:
src/hemesh_core/wblut/hemesh/HEC_Creator.java