HE_Mesh: wblut.nurbs.WB_Bezier Class Reference
wblut.nurbs.WB_Bezier Class Reference
Public Member Functions
WB_Bezier (final WB_Coord[] controlPoints)
WB_Bezier (final WB_PointHomogeneous[] controlPoints)
WB_Point curvePoint (final double u)
WB_Vector firstDerivative (final double u)
WB_Vector curveDirection (final double u)
WB_Vector curveDerivative (final double u)
double n ()
double getLowerU ()
double getUpperU ()
WB_Bezier elevateDegree ()
WB_Bezier derivative ()
Public Member Functions inherited from wblut.geom.WB_Curve
WB_Point curvePoint (double u)
WB_Vector curveDirection (double u)
WB_Vector curveDerivative (double u)
Protected Attributes
WB_Coord[] points
int n
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.nurbs.WB_Bezier.WB_Bezier (final WB_Coord[] controlPoints)
n+1 controlpoint.
Parameters
controlPoints
wblut.nurbs.WB_Bezier.WB_Bezier (final WB_PointHomogeneous[] controlPoints)
Parameters
controlPoints
Member Function Documentation
WB_Vector wblut.nurbs.WB_Bezier.curveDerivative (final double u)
References wblut.nurbs.WB_Bezier.firstDerivative().
WB_Vector wblut.nurbs.WB_Bezier.curveDirection (final double u)
References wblut.nurbs.WB_Bezier.firstDerivative(), and wblut.geom.WB_Vector.normalizeSelf().
WB_Point wblut.nurbs.WB_Bezier.curvePoint (final double u)
References wblut.geom.WB_Point.addMulSelf(), wblut.math.WB_Bernstein.getBernsteinCoefficientsOfOrderN(), and wblut.nurbs.WB_Bezier.n().
WB_Bezier wblut.nurbs.WB_Bezier.derivative ()
Returns
References wblut.geom.WB_Point.mulSelf(), wblut.nurbs.WB_Bezier.n(), wblut.geom.WB_Point.sub(), and wblut.nurbs.WB_Bezier.WB_Bezier().
WB_Bezier wblut.nurbs.WB_Bezier.elevateDegree ()
Returns
References wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.nurbs.WB_Bezier.n(), and wblut.nurbs.WB_Bezier.WB_Bezier().
WB_Vector wblut.nurbs.WB_Bezier.firstDerivative (final double u)
Parameters
u
Returns
References wblut.geom.WB_Vector.addMulSelf(), wblut.math.WB_Bernstein.getBernsteinCoefficientsOfOrderN(), wblut.geom.WB_Vector.mulSelf(), and wblut.geom.WB_Point.sub().
double wblut.nurbs.WB_Bezier.getLowerU ()
Returns
Implements wblut.geom.WB_Curve.
double wblut.nurbs.WB_Bezier.getUpperU ()
Returns
Implements wblut.geom.WB_Curve.
double wblut.nurbs.WB_Bezier.n ()
Get degree.
Returns
Member Data Documentation
WB_GeometryFactory wblut.nurbs.WB_Bezier.gf = new WB_GeometryFactory() static private
int wblut.nurbs.WB_Bezier.n protected
Degree of the Bezier curve
WB_Coord [] wblut.nurbs.WB_Bezier.points protected
The documentation for this class was generated from the following file:
src/nurbs/wblut/nurbs/WB_Bezier.java