HE_Mesh: wblut.hemesh.HE_BoundaryFaceCirculator Class Reference
wblut.hemesh.HE_BoundaryFaceCirculator Class Reference
Public Member Functions
boolean hasNext ()
HE_Face next ()
void remove ()
Private Attributes
final HE_Halfedge _start
HE_Halfedge _current
Member Function Documentation
boolean wblut.hemesh.HE_BoundaryFaceCirculator.hasNext ()
References wblut.hemesh.HE_BoundaryFaceCirculator._start, and wblut.hemesh.HE_Halfedge.getNextInFace().
HE_Face wblut.hemesh.HE_BoundaryFaceCirculator.next ()
References wblut.hemesh.HE_BoundaryFaceCirculator._start, wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getPair().
void wblut.hemesh.HE_BoundaryFaceCirculator.remove ()
Member Data Documentation
HE_Halfedge wblut.hemesh.HE_BoundaryFaceCirculator._current private
final HE_Halfedge wblut.hemesh.HE_BoundaryFaceCirculator._start private
The documentation for this class was generated from the following file:
src/hemesh_core/wblut/hemesh/HE_BoundaryFaceCirculator.java