HE_Mesh: wblut.geom.WB_HashGridObject Class Reference
wblut.geom.WB_HashGridObject Class Reference
Public Member Functions
WB_HashGridObject (final int sizeI, final int sizeJ, final int sizeK, final Object defaultValue)
WB_HashGridObject (final int sizeI, final int sizeJ, final int sizeK)
boolean setValue (final Object value, final int i, final int j, final int k)
boolean clearValue (final int i, final int j, final int k)
Object getValue (final int i, final int j, final int k)
int getWidth ()
int getHeight ()
int getDepth ()
Object getDefaultValue ()
long[] getKeys ()
int size ()
Private Member Functions
long safeIndex (final int i, final int j, final int k)
Private Attributes
final LongObjectHashMap values
final Object defaultValue
final int sizeI
Constructor & Destructor Documentation
wblut.geom.WB_HashGridObject.WB_HashGridObject (final int sizeI, final int sizeJ, final int sizeK, final Object defaultValue)
Parameters
sizeI
sizeJ
sizeK
defaultValue
References wblut.geom.WB_HashGridObject.defaultValue, and wblut.geom.WB_HashGridObject.sizeI.
wblut.geom.WB_HashGridObject.WB_HashGridObject (final int sizeI, final int sizeJ, final int sizeK)
Parameters
sizeI
sizeJ
sizeK
References wblut.geom.WB_HashGridObject.defaultValue, wblut.geom.WB_HashGridObject.sizeI, and wblut.geom.WB_HashGridObject.values.
Member Function Documentation
boolean wblut.geom.WB_HashGridObject.clearValue (final int i, final int j, final int k)
Parameters
i
j
k
Returns
References wblut.geom.WB_HashGridObject.safeIndex(), and wblut.geom.WB_HashGridObject.values.
Object wblut.geom.WB_HashGridObject.getDefaultValue ()
Returns
References wblut.geom.WB_HashGridObject.defaultValue.
int wblut.geom.WB_HashGridObject.getDepth ()
Returns
int wblut.geom.WB_HashGridObject.getHeight ()
Returns
long [] wblut.geom.WB_HashGridObject.getKeys ()
Returns
References wblut.geom.WB_HashGridObject.values.
Object wblut.geom.WB_HashGridObject.getValue (final int i, final int j, final int k)
Parameters
i
j
k
Returns
References wblut.geom.WB_HashGridObject.defaultValue, wblut.geom.WB_HashGridObject.safeIndex(), and wblut.geom.WB_HashGridObject.values.
int wblut.geom.WB_HashGridObject.getWidth ()
Returns
References wblut.geom.WB_HashGridObject.sizeI.
long wblut.geom.WB_HashGridObject.safeIndex (final int i, final int j, final int k) private
Parameters
i
j
k
Returns
References wblut.geom.WB_HashGridObject.sizeI.
boolean wblut.geom.WB_HashGridObject.setValue (final Object value, final int i, final int j, final int k)
Parameters
value
i
j
k
Returns
References wblut.geom.WB_HashGridObject.safeIndex(), and wblut.geom.WB_HashGridObject.values.
int wblut.geom.WB_HashGridObject.size ()
Returns
References wblut.geom.WB_HashGridObject.values.
Member Data Documentation
final Object wblut.geom.WB_HashGridObject.defaultValue private
final int wblut.geom.WB_HashGridObject.sizeI private
final LongObjectHashMap wblut.geom.WB_HashGridObject.values private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_HashGridObject.java