HE_Mesh: wblut.geom.WB_Subdivision.O11 Class Reference
wblut.geom.WB_Subdivision.O11 Class Reference
Public Member Functions
WB_SubdivisionResult apply (final WB_Octagon octagon)
O11 setF (final double ff)
Public Member Functions inherited from wblut.geom.WB_Subdivision.WB_OctagonSubdivision
WB_SubdivisionResult apply (WB_Octagon octagon)
Private Attributes
double f = 0.5
Member Function Documentation
WB_SubdivisionResult wblut.geom.WB_Subdivision.O11.apply (final WB_Octagon octagon)
References wblut.geom.WB_Subdivision.WB_SubdivisionResult.addOctagon(), wblut.geom.WB_Subdivision.WB_SubdivisionResult.addPentagon(), wblut.geom.WB_GeometryFactory3D.createCentroid(), wblut.geom.WB_Point.interpolate(), wblut.geom.WB_Octagon.p1, wblut.geom.WB_Octagon.p2, wblut.geom.WB_Octagon.p3, wblut.geom.WB_Octagon.p4, wblut.geom.WB_Octagon.p5, wblut.geom.WB_Octagon.p6, wblut.geom.WB_Octagon.p7, and wblut.geom.WB_Octagon.p8.
O11 wblut.geom.WB_Subdivision.O11.setF (final double ff)
Member Data Documentation
double wblut.geom.WB_Subdivision.O11.f = 0.5 private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Subdivision.java