HE_Mesh: wblut.geom.WB_AABB Class Reference
wblut.geom.WB_AABB Class Reference
Public Member Functions
WB_AABB (final WB_Coord p)
WB_AABB ()
WB_AABB (final WB_Coord[] points)
WB_AABB (final Collection<?extends WB_Coord > points)
WB_AABB (final double[] min, final double[] max)
WB_AABB (final float[] min, final float[] max)
WB_AABB (final int[] min, final int[] max)
WB_AABB (final WB_Coord min, final WB_Coord max)
WB_AABB (final double minx, final double miny, final double maxx, final double maxy)
WB_AABB (final double minx, final double miny, final double minz, final double maxx, final double maxy, final double maxz)
WB_AABB (final double[] values)
WB_AABB (final int[] values)
WB_AABB (final float[] values)
double getSize (final int i)
int minOrdinate ()
int maxOrdinate ()
void expandToInclude (final WB_Coord p)
void add (final WB_Coord p)
void expandBy (final double distance)
void expandBy (final double[] delta)
void expandBy (final double dx, final double dy, final double dz)
void expandToInclude (final double[] p)
void expandToInclude (final double x, final double y, final double z)
void expandToInclude (final WB_AABB other)
void add (final WB_AABB other)
void translate (final double[] d)
boolean intersects (final WB_AABB other)
boolean intersects (final WB_Coord p)
boolean intersects (final double[] x)
boolean intersects (final double x, final double y, final double z)
boolean intersects (final WB_Sphere sphere)
boolean contains (final WB_AABB other)
boolean contains (final WB_Coord p)
boolean contains (final double[] x)
boolean covers (final double[] x)
boolean covers (final double x, final double y, final double z)
boolean covers (final WB_Coord p)
boolean covers (final WB_AABB other)
double getDistance (final WB_AABB other)
double getDistanceSquare (final WB_AABB other)
double getDistance (final WB_Coord tuple)
double getDistanceSquare (final WB_Coord tuple)
boolean equals (final WB_AABB other)
String toString ()
int numberOfPoints ()
int numberOfSegments ()
int numberOfTriangles ()
int numberOfFaces ()
WB_Point[] getCorners ()
List< int[]> getSegments ()
int getId ()
void setId (final int id)
boolean isDegenerate ()
void set (final WB_AABB src)
WB_AABB get ()
WB_AABB getUnion (final WB_AABB aabb)
WB_AABB getIntersection (final WB_AABB other)
double getWidth ()
double getHeight ()
double getDepth ()
double getMin (final int i)
double getMax (final int i)
double getCenter (final int i)
double getMinX ()
double getMaxX ()
double getCenterX ()
double getMinY ()
double getMaxY ()
double getCenterY ()
double getMinZ ()
double getMaxZ ()
double getCenterZ ()
double getVolume ()
double getArea ()
double minExtent ()
double maxExtent ()
void translate (final double x, final double y, final double z)
List< int[]> getTriangles ()
int[][] getFaces ()
WB_Point getMin ()
WB_Point getMax ()
WB_Point getCenter ()
int getDim ()
int getTrueDim ()
void pad (final double factor)
int hashCode ()
void setToNull ()
boolean isNull ()
boolean isValid ()
Static Public Member Functions
static boolean intersects (final WB_Coord p1, final WB_Coord p2, final WB_Coord q)
static boolean intersects (final WB_Coord p1, final WB_Coord p2, final WB_Coord q1, final WB_Coord q2)
Protected Attributes
double[] _min
double[] _max
Private Member Functions
List< double[]> getCoords ()
void init ()
int hashCode (final double v)
Constructor & Destructor Documentation
wblut.geom.WB_AABB.WB_AABB (final WB_Coord p)
Parameters
p
References wblut.geom.WB_AABB.expandToInclude(), wblut.geom.WB_AABB.init(), and wblut.geom.WB_AABB.setToNull().
wblut.geom.WB_AABB.WB_AABB ()
References wblut.geom.WB_AABB.init().
wblut.geom.WB_AABB.WB_AABB (final WB_Coord[] points)
Parameters
points
References wblut.geom.WB_Coord.getd(), and wblut.geom.WB_AABB.init().
wblut.geom.WB_AABB.WB_AABB (final Collection<?extends WB_Coord > points)
Parameters
points
References wblut.geom.WB_AABB.init().
wblut.geom.WB_AABB.WB_AABB (final double[] min, final double[] max)
Parameters
min
max
References wblut.geom.WB_AABB.init().
wblut.geom.WB_AABB.WB_AABB (final float[] min, final float[] max)
Parameters
min
max
References wblut.geom.WB_AABB.init().
wblut.geom.WB_AABB.WB_AABB (final int[] min, final int[] max)
Parameters
min
max
References wblut.geom.WB_AABB.init().
wblut.geom.WB_AABB.WB_AABB (final WB_Coord min, final WB_Coord max)
Parameters
min
max
References wblut.geom.WB_Coord.getd(), and wblut.geom.WB_AABB.init().
wblut.geom.WB_AABB.WB_AABB (final double minx, final double miny, final double maxx, final double maxy)
Parameters
minx
miny
maxx
maxy
References wblut.geom.WB_AABB.expandToInclude().
wblut.geom.WB_AABB.WB_AABB (final double minx, final double miny, final double minz, final double maxx, final double maxy, final double maxz)
Parameters
minx
miny
minz
maxx
maxy
maxz
References wblut.geom.WB_AABB.expandToInclude().
wblut.geom.WB_AABB.WB_AABB (final double[] values)
Parameters
values
References wblut.geom.WB_AABB.init().
wblut.geom.WB_AABB.WB_AABB (final int[] values)
Parameters
values
References wblut.geom.WB_AABB.init().
wblut.geom.WB_AABB.WB_AABB (final float[] values)
Parameters
values
References wblut.geom.WB_AABB.init().
Member Function Documentation
void wblut.geom.WB_AABB.add (final WB_Coord p)
Parameters
p
References wblut.geom.WB_AABB.expandToInclude(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_AABB.add (final WB_AABB other)
Parameters
other
References wblut.geom.WB_AABB.expandToInclude().
boolean wblut.geom.WB_AABB.contains (final WB_AABB other)
Parameters
other
Returns
References wblut.geom.WB_AABB.covers().
boolean wblut.geom.WB_AABB.contains (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_AABB.covers().
boolean wblut.geom.WB_AABB.contains (final double[] x)
Parameters
x
Returns
References wblut.geom.WB_AABB.covers().
boolean wblut.geom.WB_AABB.covers (final double[] x)
Parameters
x
Returns
References wblut.geom.WB_AABB.isNull().
boolean wblut.geom.WB_AABB.covers (final double x, final double y, final double z)
Parameters
x
y
z
Returns
References wblut.geom.WB_AABB.isNull().
boolean wblut.geom.WB_AABB.covers (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_AABB.covers(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
boolean wblut.geom.WB_AABB.covers (final WB_AABB other)
Parameters
other
Returns
References wblut.geom.WB_AABB._max, wblut.geom.WB_AABB._min, and wblut.geom.WB_AABB.isNull().
boolean wblut.geom.WB_AABB.equals (final WB_AABB other)
Parameters
other
Returns
References wblut.geom.WB_AABB._max, wblut.geom.WB_AABB._min, and wblut.geom.WB_AABB.isNull().
void wblut.geom.WB_AABB.expandBy (final double distance)
Parameters
distance
References wblut.geom.WB_AABB.isNull(), and wblut.geom.WB_AABB.setToNull().
void wblut.geom.WB_AABB.expandBy (final double[] delta)
Parameters
delta
References wblut.geom.WB_AABB.isNull(), and wblut.geom.WB_AABB.setToNull().
void wblut.geom.WB_AABB.expandBy (final double dx, final double dy, final double dz)
Parameters
dx
dy
dz
References wblut.geom.WB_AABB.isNull(), and wblut.geom.WB_AABB.setToNull().
void wblut.geom.WB_AABB.expandToInclude (final WB_Coord p)
Parameters
p
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_AABB.expandToInclude (final double[] p)
Parameters
p
References wblut.geom.WB_AABB.isNull().
void wblut.geom.WB_AABB.expandToInclude (final double x, final double y, final double z)
Parameters
x
y
z
References wblut.geom.WB_AABB.isNull().
void wblut.geom.WB_AABB.expandToInclude (final WB_AABB other)
Parameters
other
References wblut.geom.WB_AABB._max, wblut.geom.WB_AABB._min, and wblut.geom.WB_AABB.expandToInclude().
WB_AABB wblut.geom.WB_AABB.get ()
Returns
References wblut.geom.WB_AABB.WB_AABB().
double wblut.geom.WB_AABB.getArea ()
References wblut.geom.WB_AABB.getDepth(), wblut.geom.WB_AABB.getHeight(), and wblut.geom.WB_AABB.getWidth().
double wblut.geom.WB_AABB.getCenter (final int i)
WB_Point wblut.geom.WB_AABB.getCenter ()
Returns
double wblut.geom.WB_AABB.getCenterX ()
Returns
double wblut.geom.WB_AABB.getCenterY ()
Returns
double wblut.geom.WB_AABB.getCenterZ ()
Returns
List<double[]> wblut.geom.WB_AABB.getCoords () private
Returns
References wblut.geom.WB_AABB.isNull(), and wblut.geom.WB_AABB.numberOfPoints().
WB_Point [] wblut.geom.WB_AABB.getCorners ()
Returns
References wblut.geom.WB_AABB.isNull(), and wblut.geom.WB_AABB.numberOfPoints().
double wblut.geom.WB_AABB.getDepth ()
Returns
References wblut.geom.WB_AABB.getSize().
int wblut.geom.WB_AABB.getDim ()
Returns
double wblut.geom.WB_AABB.getDistance (final WB_AABB other)
Parameters
other
Returns
References wblut.geom.WB_AABB._max, wblut.geom.WB_AABB._min, and wblut.geom.WB_AABB.intersects().
double wblut.geom.WB_AABB.getDistance (final WB_Coord tuple)
Parameters
tuple
Returns
References wblut.geom.WB_Coord.getd().
double wblut.geom.WB_AABB.getDistanceSquare (final WB_AABB other)
Parameters
other
Returns
References wblut.geom.WB_AABB._max, wblut.geom.WB_AABB._min, and wblut.geom.WB_AABB.intersects().
double wblut.geom.WB_AABB.getDistanceSquare (final WB_Coord tuple)
Parameters
tuple
Returns
References wblut.geom.WB_Coord.getd().
int [][] wblut.geom.WB_AABB.getFaces ()
Returns
double wblut.geom.WB_AABB.getHeight ()
Returns
References wblut.geom.WB_AABB.getSize().
int wblut.geom.WB_AABB.getId ()
Returns
WB_AABB wblut.geom.WB_AABB.getIntersection (final WB_AABB other)
Parameters
other
Returns
References wblut.geom.WB_AABB._max, wblut.geom.WB_AABB._min, wblut.geom.WB_AABB.intersects(), wblut.geom.WB_AABB.isNull(), and wblut.geom.WB_AABB.WB_AABB().
double wblut.geom.WB_AABB.getMax (final int i)
Parameters
i
Returns
WB_Point wblut.geom.WB_AABB.getMax ()
Returns
double wblut.geom.WB_AABB.getMaxX ()
Returns
double wblut.geom.WB_AABB.getMaxY ()
Returns
double wblut.geom.WB_AABB.getMaxZ ()
Returns
double wblut.geom.WB_AABB.getMin (final int i)
Parameters
i
Returns
WB_Point wblut.geom.WB_AABB.getMin ()
Returns
double wblut.geom.WB_AABB.getMinX ()
Returns
double wblut.geom.WB_AABB.getMinY ()
Returns
double wblut.geom.WB_AABB.getMinZ ()
Returns
List<int[]> wblut.geom.WB_AABB.getSegments ()
Returns
References wblut.geom.WB_AABB.getCoords(), and wblut.geom.WB_AABB.numberOfSegments().
double wblut.geom.WB_AABB.getSize (final int i)
Parameters
i
Returns
References wblut.geom.WB_AABB.isNull().
List<int[]> wblut.geom.WB_AABB.getTriangles ()
Returns
int wblut.geom.WB_AABB.getTrueDim ()
Returns
References wblut.math.WB_Epsilon.EPSILON, and wblut.geom.WB_AABB.isValid().
WB_AABB wblut.geom.WB_AABB.getUnion (final WB_AABB aabb)
Parameters
aabb
Returns
References wblut.geom.WB_AABB._max, wblut.geom.WB_AABB._min, and wblut.geom.WB_AABB.WB_AABB().
double wblut.geom.WB_AABB.getVolume ()
Returns
References wblut.geom.WB_AABB.getDepth(), wblut.geom.WB_AABB.getHeight(), and wblut.geom.WB_AABB.getWidth().
double wblut.geom.WB_AABB.getWidth ()
Returns
References wblut.geom.WB_AABB.getSize().
int wblut.geom.WB_AABB.hashCode ()
int wblut.geom.WB_AABB.hashCode (final double v) private
Parameters
v
Returns
void wblut.geom.WB_AABB.init () private
boolean wblut.geom.WB_AABB.intersects (final WB_AABB other)
Parameters
other
Returns
References wblut.geom.WB_AABB._max, wblut.geom.WB_AABB._min, and wblut.geom.WB_AABB.isNull().
boolean wblut.geom.WB_AABB.intersects (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_AABB.intersects(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
boolean wblut.geom.WB_AABB.intersects (final double[] x)
Parameters
x
Returns
References wblut.geom.WB_AABB.isNull().
boolean wblut.geom.WB_AABB.intersects (final double x, final double y, final double z)
Parameters
x
y
z
Returns
References wblut.geom.WB_AABB.isNull().
boolean wblut.geom.WB_AABB.intersects (final WB_Sphere sphere)
References wblut.geom.WB_Sphere.getCenter(), wblut.geom.WB_Sphere.getRadius(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static boolean wblut.geom.WB_AABB.intersects (final WB_Coord p1, final WB_Coord p2, final WB_Coord q) static
Parameters
p1
p2
q
Returns
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static boolean wblut.geom.WB_AABB.intersects (final WB_Coord p1, final WB_Coord p2, final WB_Coord q1, final WB_Coord q2) static
Parameters
p1
p2
q1
q2
Returns
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
boolean wblut.geom.WB_AABB.isDegenerate ()
Returns
References wblut.geom.WB_AABB.getTrueDim().
boolean wblut.geom.WB_AABB.isNull ()
Returns
boolean wblut.geom.WB_AABB.isValid ()
Returns
References wblut.geom.WB_AABB.isNull().
double wblut.geom.WB_AABB.maxExtent ()
Returns
References wblut.geom.WB_AABB.getDepth(), wblut.geom.WB_AABB.getHeight(), wblut.geom.WB_AABB.getWidth(), and wblut.geom.WB_AABB.isNull().
int wblut.geom.WB_AABB.maxOrdinate ()
Returns
References wblut.geom.WB_AABB.getSize(), and wblut.geom.WB_AABB.isNull().
double wblut.geom.WB_AABB.minExtent ()
Returns
References wblut.geom.WB_AABB.getDepth(), wblut.geom.WB_AABB.getHeight(), wblut.geom.WB_AABB.getWidth(), and wblut.geom.WB_AABB.isNull().
int wblut.geom.WB_AABB.minOrdinate ()
Returns
References wblut.geom.WB_AABB.getSize(), and wblut.geom.WB_AABB.isNull().
int wblut.geom.WB_AABB.numberOfFaces ()
Returns
References wblut.geom.WB_AABB.isNull().
int wblut.geom.WB_AABB.numberOfPoints ()
Returns
References wblut.geom.WB_AABB.isNull().
int wblut.geom.WB_AABB.numberOfSegments ()
Returns
References wblut.geom.WB_AABB.isNull().
int wblut.geom.WB_AABB.numberOfTriangles ()
Returns
References wblut.geom.WB_AABB.isNull().
void wblut.geom.WB_AABB.pad (final double factor)
Parameters
factor
References wblut.geom.WB_AABB.getCenter(), and wblut.geom.WB_Point.getd().
void wblut.geom.WB_AABB.set (final WB_AABB src)
Parameters
src
References wblut.geom.WB_AABB._max, and wblut.geom.WB_AABB._min.
void wblut.geom.WB_AABB.setId (final int id)
Parameters
id
void wblut.geom.WB_AABB.setToNull ()
String wblut.geom.WB_AABB.toString ()
void wblut.geom.WB_AABB.translate (final double[] d)
Parameters
d
References wblut.geom.WB_AABB.isNull().
void wblut.geom.WB_AABB.translate (final double x, final double y, final double z)
Parameters
x
y
z
References wblut.geom.WB_AABB.isNull().
Member Data Documentation
double [] wblut.geom.WB_AABB._max protected
double [] wblut.geom.WB_AABB._min protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_AABB.java