HE_Mesh: wblut.geom.WB_HashGridInteger Class Reference
wblut.geom.WB_HashGridInteger Class Reference
Public Member Functions
WB_HashGridInteger (final int sizeI, final int sizeJ, final int sizeK, final int defaultValue)
WB_HashGridInteger (final int sizeI, final int sizeJ, final int sizeK)
boolean setValue (final int value, final int i, final int j, final int k)
boolean addValue (final int value, final int i, final int j, final int k)
boolean clearValue (final int i, final int j, final int k)
int getValue (final int i, final int j, final int k)
int getSizeI ()
int getSizeJ ()
int getSizeK ()
int getDefaultValue ()
long[] getKeys ()
int size ()
Private Member Functions
long safeIndex (final int i, final int j, final int k)
Private Attributes
final LongIntHashMap values
final int defaultValue
final int sizeI
Constructor & Destructor Documentation
wblut.geom.WB_HashGridInteger.WB_HashGridInteger (final int sizeI, final int sizeJ, final int sizeK, final int defaultValue)
Parameters
sizeI
sizeJ
sizeK
defaultValue
References wblut.geom.WB_HashGridInteger.defaultValue, and wblut.geom.WB_HashGridInteger.sizeI.
wblut.geom.WB_HashGridInteger.WB_HashGridInteger (final int sizeI, final int sizeJ, final int sizeK)
Parameters
sizeI
sizeJ
sizeK
References wblut.geom.WB_HashGridInteger.sizeI.
Member Function Documentation
boolean wblut.geom.WB_HashGridInteger.addValue (final int value, final int i, final int j, final int k)
Parameters
value
i
j
k
Returns
References wblut.geom.WB_HashGridInteger.safeIndex().
boolean wblut.geom.WB_HashGridInteger.clearValue (final int i, final int j, final int k)
Parameters
i
j
k
Returns
References wblut.geom.WB_HashGridInteger.safeIndex().
int wblut.geom.WB_HashGridInteger.getDefaultValue ()
Returns
References wblut.geom.WB_HashGridInteger.defaultValue.
long [] wblut.geom.WB_HashGridInteger.getKeys ()
Returns
int wblut.geom.WB_HashGridInteger.getSizeI ()
Returns
References wblut.geom.WB_HashGridInteger.sizeI.
int wblut.geom.WB_HashGridInteger.getSizeJ ()
Returns
int wblut.geom.WB_HashGridInteger.getSizeK ()
Returns
int wblut.geom.WB_HashGridInteger.getValue (final int i, final int j, final int k)
Parameters
i
j
k
Returns
References wblut.geom.WB_HashGridInteger.defaultValue, and wblut.geom.WB_HashGridInteger.safeIndex().
long wblut.geom.WB_HashGridInteger.safeIndex (final int i, final int j, final int k) private
Parameters
i
j
k
Returns
boolean wblut.geom.WB_HashGridInteger.setValue (final int value, final int i, final int j, final int k)
Parameters
value
i
j
k
Returns
References wblut.geom.WB_HashGridInteger.safeIndex().
int wblut.geom.WB_HashGridInteger.size ()
Returns
Member Data Documentation
final int wblut.geom.WB_HashGridInteger.defaultValue private
final int wblut.geom.WB_HashGridInteger.sizeI private
final LongIntHashMap wblut.geom.WB_HashGridInteger.values private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_HashGridInteger.java