HE_Mesh: wblut.geom.WB_HashGridDouble2D Class Reference
wblut.geom.WB_HashGridDouble2D Class Reference
Public Member Functions
WB_HashGridDouble2D (final int K, final int L, final double defaultValue)
WB_HashGridDouble2D (final int K, final int L)
boolean setValue (final double value, final int i, final int j)
boolean addValue (final double value, final int i, final int j)
boolean clearValue (final int i, final int j)
double getValue (final int i, final int j)
int getWidth ()
int getHeight ()
double getDefaultValue ()
long[] getKeys ()
int size ()
Private Member Functions
long safeIndex (final int i, final int j)
Private Attributes
final LongDoubleHashMap values
final double defaultValue
final int K
Constructor & Destructor Documentation
wblut.geom.WB_HashGridDouble2D.WB_HashGridDouble2D (final int K, final int L, final double defaultValue)
Parameters
K
L
defaultValue
References wblut.geom.WB_HashGridDouble2D.defaultValue, and wblut.geom.WB_HashGridDouble2D.K.
wblut.geom.WB_HashGridDouble2D.WB_HashGridDouble2D (final int K, final int L)
Parameters
K
L
References wblut.geom.WB_HashGridDouble2D.K.
Member Function Documentation
boolean wblut.geom.WB_HashGridDouble2D.addValue (final double value, final int i, final int j)
Parameters
value
i
j
Returns
References wblut.geom.WB_HashGridDouble2D.safeIndex().
boolean wblut.geom.WB_HashGridDouble2D.clearValue (final int i, final int j)
Parameters
i
j
Returns
References wblut.geom.WB_HashGridDouble2D.safeIndex().
double wblut.geom.WB_HashGridDouble2D.getDefaultValue ()
Returns
References wblut.geom.WB_HashGridDouble2D.defaultValue.
int wblut.geom.WB_HashGridDouble2D.getHeight ()
Returns
long [] wblut.geom.WB_HashGridDouble2D.getKeys ()
Returns
double wblut.geom.WB_HashGridDouble2D.getValue (final int i, final int j)
Parameters
i
j
Returns
References wblut.geom.WB_HashGridDouble2D.defaultValue, and wblut.geom.WB_HashGridDouble2D.safeIndex().
int wblut.geom.WB_HashGridDouble2D.getWidth ()
Returns
References wblut.geom.WB_HashGridDouble2D.K.
long wblut.geom.WB_HashGridDouble2D.safeIndex (final int i, final int j) private
Parameters
i
j
Returns
References wblut.geom.WB_HashGridDouble2D.K.
boolean wblut.geom.WB_HashGridDouble2D.setValue (final double value, final int i, final int j)
Parameters
value
i
j
Returns
References wblut.geom.WB_HashGridDouble2D.safeIndex().
int wblut.geom.WB_HashGridDouble2D.size ()
Returns
Member Data Documentation
final double wblut.geom.WB_HashGridDouble2D.defaultValue private
final int wblut.geom.WB_HashGridDouble2D.K private
final LongDoubleHashMap wblut.geom.WB_HashGridDouble2D.values private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_HashGridDouble2D.java