HE_Mesh: wblut.geom.WB_Network.Connection Class Reference
wblut.geom.WB_Network.Connection Class Reference
Public Member Functions
Connection (final Node s, final Node e, final int id)
Connection (final Node s, final Node e, final int id, final double r)
Connection (final Node s, final Node e, final int id, final double rs, final double re)
Node start ()
Node end ()
int getStartIndex ()
int getEndIndex ()
int getIndex ()
WB_Vector toVector ()
WB_Vector toNormVector ()
double getSqLength ()
double getLength ()
double getRadiusStart ()
double getRadiusEnd ()
void setRadiusStart (final double r)
void setRadiusEnd (final double r)
double getOffsetStart ()
double getOffsetEnd ()
void setOffsetStart (final double o)
void setOffsetEnd (final double o)
WB_Point getCenter ()
WB_Segment toSegment ()
WB_Plane toPlane ()
Private Attributes
final Node start
final Node end
final int index
double radiuss
double radiuse
double offsets
double offsete
Constructor & Destructor Documentation
wblut.geom.WB_Network.Connection.Connection (final Node s, final Node e, final int id)
Parameters
s
e
id
wblut.geom.WB_Network.Connection.Connection (final Node s, final Node e, final int id, final double r)
Parameters
s
e
id
r
wblut.geom.WB_Network.Connection.Connection (final Node s, final Node e, final int id, final double rs, final double re)
Parameters
s
e
id
rs
re
Member Function Documentation
Node wblut.geom.WB_Network.Connection.end ()
Returns
WB_Point wblut.geom.WB_Network.Connection.getCenter ()
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_Network.Connection.end(), wblut.geom.WB_Point.mulSelf(), and wblut.geom.WB_Network.Connection.start().
int wblut.geom.WB_Network.Connection.getEndIndex ()
Returns
References wblut.geom.WB_Network.Node.getIndex().
int wblut.geom.WB_Network.Connection.getIndex ()
Returns
References wblut.geom.WB_Network.Connection.index.
double wblut.geom.WB_Network.Connection.getLength ()
Returns
References wblut.geom.WB_Network.Connection.end(), wblut.geom.WB_GeometryOp3D.getDistance3D(), and wblut.geom.WB_Network.Connection.start().
double wblut.geom.WB_Network.Connection.getOffsetEnd ()
Returns
References wblut.geom.WB_Network.Connection.offsete.
double wblut.geom.WB_Network.Connection.getOffsetStart ()
Returns
References wblut.geom.WB_Network.Connection.offsets.
double wblut.geom.WB_Network.Connection.getRadiusEnd ()
Returns
References wblut.geom.WB_Network.Connection.radiuse.
double wblut.geom.WB_Network.Connection.getRadiusStart ()
Returns
References wblut.geom.WB_Network.Connection.radiuss.
double wblut.geom.WB_Network.Connection.getSqLength ()
Returns
References wblut.geom.WB_Network.Connection.end(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), and wblut.geom.WB_Network.Connection.start().
int wblut.geom.WB_Network.Connection.getStartIndex ()
Returns
References wblut.geom.WB_Network.Node.getIndex().
void wblut.geom.WB_Network.Connection.setOffsetEnd (final double o)
Parameters
o
void wblut.geom.WB_Network.Connection.setOffsetStart (final double o)
Parameters
o
void wblut.geom.WB_Network.Connection.setRadiusEnd (final double r)
Parameters
r
void wblut.geom.WB_Network.Connection.setRadiusStart (final double r)
Parameters
r
Node wblut.geom.WB_Network.Connection.start ()
Returns
WB_Vector wblut.geom.WB_Network.Connection.toNormVector ()
Returns
References wblut.geom.WB_Network.Connection.end(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Network.Connection.start(), and wblut.geom.WB_Point.subToVector3D().
WB_Plane wblut.geom.WB_Network.Connection.toPlane ()
Returns
References wblut.geom.WB_Network.Connection.start(), and wblut.geom.WB_Network.Connection.toVector().
WB_Segment wblut.geom.WB_Network.Connection.toSegment ()
Returns
WB_Vector wblut.geom.WB_Network.Connection.toVector ()
Returns
References wblut.geom.WB_Network.Connection.end(), wblut.geom.WB_Network.Connection.start(), and wblut.geom.WB_Point.subToVector3D().
Member Data Documentation
final Node wblut.geom.WB_Network.Connection.end private
final int wblut.geom.WB_Network.Connection.index private
double wblut.geom.WB_Network.Connection.offsete private
double wblut.geom.WB_Network.Connection.offsets private
double wblut.geom.WB_Network.Connection.radiuse private
double wblut.geom.WB_Network.Connection.radiuss private
final Node wblut.geom.WB_Network.Connection.start private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Network.java