HE_Mesh: wblut.geom.WB_CoordinateSystem2D Class Reference
wblut.geom.WB_CoordinateSystem2D Class Reference
Public Member Functions
WB_CoordinateSystem2D ()
WB_CoordinateSystem2D (final WB_CoordinateSystem2D parent)
WB_CoordinateSystem2D get ()
WB_CoordinateSystem2D setParent (final WB_CoordinateSystem2D parent)
WB_CoordinateSystem2D setOrigin (final WB_Point o)
WB_CoordinateSystem2D setOrigin (final double ox, final double oy)
WB_Vector getX ()
WB_Vector getY ()
WB_Point getOrigin ()
WB_CoordinateSystem2D getParent ()
boolean isWorld ()
WB_CoordinateSystem2D setX (final WB_Coord X)
WB_CoordinateSystem2D setY (final WB_Coord Y)
WB_CoordinateSystem2D setX (final double xx, final double xy)
WB_CoordinateSystem2D setY (final double yx, final double yy)
WB_CoordinateSystem2D rotateAboutOrigin (final double a)
WB_Transform2D getTransformFromParent ()
WB_Transform2D getTransformToParent ()
WB_Transform2D getTransformFromWorld ()
WB_Transform2D getTransformToWorld ()
WB_Transform2D getTransformFrom (final WB_CoordinateSystem2D CS)
WB_Transform2D getTransformTo (final WB_CoordinateSystem2D CS)
void flip ()
String toString ()
Protected Member Functions
WB_CoordinateSystem2D (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_CoordinateSystem2D parent)
WB_CoordinateSystem2D (final boolean world)
void set (final WB_Coord origin, final WB_Coord x, final WB_Coord y)
void set (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_CoordinateSystem2D CS)
Static Protected Member Functions
static final WB_CoordinateSystem2D WORLD ()
Private Attributes
WB_CoordinateSystem2D _parent
WB_Point _origin
WB_Vector _X
WB_Vector _Y
boolean _isWorld
Constructor & Destructor Documentation
wblut.geom.WB_CoordinateSystem2D.WB_CoordinateSystem2D (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_CoordinateSystem2D parent) protected
Parameters
origin
x
y
parent
wblut.geom.WB_CoordinateSystem2D.WB_CoordinateSystem2D (final boolean world) protected
Parameters
world
References wblut.geom.WB_CoordinateSystem2D.WORLD(), wblut.geom.WB_Vector.X, wblut.geom.WB_Vector.Y, and wblut.geom.WB_Point.ZERO.
wblut.geom.WB_CoordinateSystem2D.WB_CoordinateSystem2D ()
wblut.geom.WB_CoordinateSystem2D.WB_CoordinateSystem2D (final WB_CoordinateSystem2D parent)
Parameters
parent
References wblut.geom.WB_Vector.X, wblut.geom.WB_Vector.Y, and wblut.geom.WB_Point.ZERO.
Member Function Documentation
void wblut.geom.WB_CoordinateSystem2D.flip ()
References wblut.geom.WB_Vector.mulSelf().
WB_CoordinateSystem2D wblut.geom.WB_CoordinateSystem2D.get ()
Returns
References wblut.geom.WB_CoordinateSystem2D.WB_CoordinateSystem2D().
WB_Point wblut.geom.WB_CoordinateSystem2D.getOrigin ()
Returns
References wblut.geom.WB_Point.copy().
WB_CoordinateSystem2D wblut.geom.WB_CoordinateSystem2D.getParent ()
Returns
References wblut.geom.WB_CoordinateSystem2D._parent.
WB_Transform2D wblut.geom.WB_CoordinateSystem2D.getTransformFrom (final WB_CoordinateSystem2D CS)
Parameters
CS
Returns
References wblut.geom.WB_Transform2D.addFromCSToCS2D().
WB_Transform2D wblut.geom.WB_CoordinateSystem2D.getTransformFromParent ()
Returns
References wblut.geom.WB_Transform2D.addFromParentToCS2D().
WB_Transform2D wblut.geom.WB_CoordinateSystem2D.getTransformFromWorld ()
Returns
References wblut.geom.WB_Transform2D.addFromWorldToCS2D().
WB_Transform2D wblut.geom.WB_CoordinateSystem2D.getTransformTo (final WB_CoordinateSystem2D CS)
Parameters
CS
Returns
References wblut.geom.WB_Transform2D.addFromCSToCS2D().
WB_Transform2D wblut.geom.WB_CoordinateSystem2D.getTransformToParent ()
Returns
References wblut.geom.WB_Transform2D.addFromCSToParent2D().
WB_Transform2D wblut.geom.WB_CoordinateSystem2D.getTransformToWorld ()
Returns
References wblut.geom.WB_Transform2D.addFromCSToWorld2D().
WB_Vector wblut.geom.WB_CoordinateSystem2D.getX ()
Returns
References wblut.geom.WB_Vector.copy().
WB_Vector wblut.geom.WB_CoordinateSystem2D.getY ()
Returns
References wblut.geom.WB_Vector.copy().
boolean wblut.geom.WB_CoordinateSystem2D.isWorld ()
Returns
References wblut.geom.WB_CoordinateSystem2D._isWorld.
WB_CoordinateSystem2D wblut.geom.WB_CoordinateSystem2D.rotateAboutOrigin (final double a)
Parameters
a
Returns
References wblut.geom.WB_Vector.rotateAboutAxisSelf().
void wblut.geom.WB_CoordinateSystem2D.set (final WB_Coord origin, final WB_Coord x, final WB_Coord y) protected
Parameters
origin
x
y
void wblut.geom.WB_CoordinateSystem2D.set (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_CoordinateSystem2D CS) protected
Parameters
origin
x
y
CS
WB_CoordinateSystem2D wblut.geom.WB_CoordinateSystem2D.setOrigin (final WB_Point o)
Parameters
o
Returns
References wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem2D wblut.geom.WB_CoordinateSystem2D.setOrigin (final double ox, final double oy)
Parameters
ox
oy
Returns
References wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem2D wblut.geom.WB_CoordinateSystem2D.setParent (final WB_CoordinateSystem2D parent)
Parameters
parent
Returns
WB_CoordinateSystem2D wblut.geom.WB_CoordinateSystem2D.setX (final WB_Coord X)
Parameters
X
Returns
References wblut.geom.WB_Vector.getOrthoNormal2D(), and wblut.geom.WB_Vector.normalizeSelf().
WB_CoordinateSystem2D wblut.geom.WB_CoordinateSystem2D.setX (final double xx, final double xy)
Parameters
xx
xy
Returns
References wblut.geom.WB_Vector.getOrthoNormal2D(), and wblut.geom.WB_Vector.normalizeSelf().
WB_CoordinateSystem2D wblut.geom.WB_CoordinateSystem2D.setY (final WB_Coord Y)
Parameters
Y
Returns
References wblut.geom.WB_Vector.getOrthoNormal2D(), wblut.geom.WB_Vector.mulSelf(), and wblut.geom.WB_Vector.normalizeSelf().
WB_CoordinateSystem2D wblut.geom.WB_CoordinateSystem2D.setY (final double yx, final double yy)
Parameters
yx
yy
Returns
References wblut.geom.WB_Vector.getOrthoNormal2D(), wblut.geom.WB_Vector.mulSelf(), and wblut.geom.WB_Vector.normalizeSelf().
String wblut.geom.WB_CoordinateSystem2D.toString ()
static final WB_CoordinateSystem2D wblut.geom.WB_CoordinateSystem2D.WORLD () static protected
Returns
References wblut.geom.WB_CoordinateSystem2D.WB_CoordinateSystem2D().
Member Data Documentation
boolean wblut.geom.WB_CoordinateSystem2D._isWorld private
WB_Point wblut.geom.WB_CoordinateSystem2D._origin private
WB_CoordinateSystem2D wblut.geom.WB_CoordinateSystem2D._parent private
WB_Vector wblut.geom.WB_CoordinateSystem2D._X private
WB_Vector wblut.geom.WB_CoordinateSystem2D._Y private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_CoordinateSystem2D.java