HE_Mesh: wblut.geom.WB_GeometryOp3D.WB_SphereFit Class Reference
wblut.geom.WB_GeometryOp3D.WB_SphereFit Class Reference
Public Member Functions
WB_SphereFit (final WB_Sphere sphere, final int iterations)
Static Public Member Functions
static double cotan (final WB_Coord v0, final WB_Coord v1)
static double cotan (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2)
static double[] cross (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz)
static double[] cross (final double cx, final double cy, final double cz, final double px, final double py, final double pz, final double qx, final double qy, final double qz)
static double dot (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz)
static double getAngleBetween (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz)
static double getAngleBetween (final double cx, final double cy, final double cz, final double px, final double py, final double pz, final double qx, final double qy, final double qz)
static double getAngleBetweenNorm (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz)
static double getCosAngleBetween (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz)
static double getCosAngleBetween (final double cx, final double cy, final double cz, final double px, final double py, final double pz, final double qx, final double qy, final double qz)
static double getCosAngleBetweenNorm (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz)
static double getDistance3D (final double px, final double py, final double pz, final double qx, final double qy, final double qz)
static double getDistance3D (final WB_Coord p, final WB_Coord q)
static double getLength3D (final double ux, final double uy, final double uz)
static double getLength3D (final WB_Coord p)
static double getSqDistance3D (final double px, final double py, final double pz, final double qx, final double qy, final double qz)
static double getSqDistance3D (final WB_Coord p, final WB_Coord q)
static double getSqLength3D (final double ux, final double uy, final double uz)
static double getSqLength3D (final WB_Coord p)
static double[] interpolate (final double px, final double py, final double qx, final double qy, final double t)
static double[] interpolate (final double px, final double py, final double pz, final double qx, final double qy, final double qz, final double t)
static double[] interpolateEase (final double px, final double py, final double pz, final double qx, final double qy, final double qz, final double t, final WB_Ease ease, final WB_Ease.EaseType type)
static double[] interpolateEase (final double px, final double py, final double qx, final double qy, final double t, final WB_Ease ease, final WB_Ease.EaseType type)
static boolean isCollinear (final WB_Coord o, final WB_Coord p, final WB_Coord q)
static boolean isOrthogonal (final WB_Coord v0, final WB_Coord v1)
static boolean isOrthogonal (final WB_Coord v0, final WB_Coord v1, final double epsilon)
static boolean isOrthogonalNorm (final WB_Coord v0, final WB_Coord v1)
static boolean isOrthogonalNorm (final WB_Coord v0, final WB_Coord v1, final double epsilon)
static boolean isParallel (final WB_Coord v0, final WB_Coord v1)
static boolean isParallel (final WB_Coord v0, final WB_Coord v1, final double epsilon)
static boolean isParallelNorm (final WB_Coord v0, final WB_Coord v1)
static boolean isParallelNorm (final WB_Coord v0, final WB_Coord v1, final double epsilon)
static boolean isParallelNormX (final WB_Coord o, final WB_Coord p)
static boolean isParallelNormX (final WB_Coord o, final WB_Coord p, final double t)
static boolean isParallelX (final WB_Coord o, final WB_Coord p)
static boolean isParallelX (final WB_Coord o, final WB_Coord p, final double t)
static boolean isZero3D (final double ux, final double uy, final double uz)
static double scalarTriple (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz, final double wx, final double wy, final double wz)
static double[][] tensor3D (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz)
Public Attributes
WB_Sphere sphere
int iterations
Constructor & Destructor Documentation
wblut.geom.WB_GeometryOp3D.WB_SphereFit.WB_SphereFit (final WB_Sphere sphere, final int iterations)
References wblut.geom.WB_GeometryOp3D.WB_SphereFit.iterations, and wblut.geom.WB_GeometryOp3D.WB_SphereFit.sphere.
Member Function Documentation
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.cotan (final WB_Coord v0, final WB_Coord v1) static
Parameters
v0
v1
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Vector.getLength().
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.cotan (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2) static
Parameters
p0
p1
p2
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.geom.WB_Vector.getLength(), and wblut.geom.WB_Vector.subToVector3D().
static double [] wblut.geom.WB_GeometryOp3D.WB_SphereFit.cross (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz) static
Parameters
ux
uy
uz
vx
vy
vz
Returns
static double [] wblut.geom.WB_GeometryOp3D.WB_SphereFit.cross (final double cx, final double cy, final double cz, final double px, final double py, final double pz, final double qx, final double qy, final double qz) static
Parameters
cx
cy
cz
px
py
pz
qx
qy
qz
Returns
References wblut.geom.WB_GeometryOp3D.WB_SphereFit.cross().
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.dot (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz) static
Parameters
ux
uy
uz
vx
vy
vz
Returns
References wblut.math.WB_Math.getExp().
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getAngleBetween (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz) static
Parameters
ux
uy
uz
vx
vy
vz
Returns
References wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Vector.normalizeSelf().
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getAngleBetween (final double cx, final double cy, final double cz, final double px, final double py, final double pz, final double qx, final double qy, final double qz) static
Parameters
cx
cy
cz
px
py
pz
qx
qy
qz
Returns
References wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Vector.normalizeSelf().
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getAngleBetweenNorm (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz) static
Parameters
ux
uy
uz
vx
vy
vz
Returns
References wblut.geom.WB_Vector.dot().
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getCosAngleBetween (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz) static
Parameters
ux
uy
uz
vx
vy
vz
Returns
References wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Vector.normalizeSelf().
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getCosAngleBetween (final double cx, final double cy, final double cz, final double px, final double py, final double pz, final double qx, final double qy, final double qz) static
Parameters
cx
cy
cz
px
py
pz
qx
qy
qz
Returns
References wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Vector.normalizeSelf().
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getCosAngleBetweenNorm (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz) static
Parameters
ux
uy
uz
vx
vy
vz
Returns
References wblut.geom.WB_Vector.dot().
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getDistance3D (final double px, final double py, final double pz, final double qx, final double qy, final double qz) static
Parameters
px
py
pz
qx
qy
qz
Returns
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getDistance3D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp3D.WB_SphereFit.getSqDistance3D().
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getLength3D (final double ux, final double uy, final double uz) static
Parameters
ux
uy
uz
Returns
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getLength3D (final WB_Coord p) static
Parameters
p
Returns
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getSqDistance3D (final double px, final double py, final double pz, final double qx, final double qy, final double qz) static
Parameters
px
py
pz
qx
qy
qz
Returns
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getSqDistance3D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getSqLength3D (final double ux, final double uy, final double uz) static
Parameters
ux
uy
uz
Returns
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.getSqLength3D (final WB_Coord p) static
Parameters
p
Returns
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double [] wblut.geom.WB_GeometryOp3D.WB_SphereFit.interpolate (final double px, final double py, final double qx, final double qy, final double t) static
Parameters
px
py
qx
qy
t
Returns
static double [] wblut.geom.WB_GeometryOp3D.WB_SphereFit.interpolate (final double px, final double py, final double pz, final double qx, final double qy, final double qz, final double t) static
Parameters
px
py
pz
qx
qy
qz
t
Returns
static double [] wblut.geom.WB_GeometryOp3D.WB_SphereFit.interpolateEase (final double px, final double py, final double pz, final double qx, final double qy, final double qz, final double t, final WB_Ease ease, final WB_Ease.EaseType type) static
References wblut.math.WB_Ease.easeIn(), wblut.math.WB_Ease.easeInOut(), and wblut.math.WB_Ease.easeOut().
static double [] wblut.geom.WB_GeometryOp3D.WB_SphereFit.interpolateEase (final double px, final double py, final double qx, final double qy, final double t, final WB_Ease ease, final WB_Ease.EaseType type) static
References wblut.math.WB_Ease.easeIn(), wblut.math.WB_Ease.easeInOut(), and wblut.math.WB_Ease.easeOut().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isCollinear (final WB_Coord o, final WB_Coord p, final WB_Coord q) static
Parameters
o
p
q
Returns
References wblut.geom.WB_Vector.crossSelf(), wblut.geom.WB_GeometryOp3D.getSqDistanceToPoint3D(), wblut.math.WB_Epsilon.isZeroSq(), and wblut.geom.WB_Vector.sub().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isOrthogonal (final WB_Coord v0, final WB_Coord v1) static
References wblut.geom.WB_GeometryOp3D.WB_SphereFit.dot(), wblut.geom.WB_GeometryOp3D.WB_SphereFit.getLength3D(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isOrthogonal (final WB_Coord v0, final WB_Coord v1, final double epsilon) static
References wblut.geom.WB_GeometryOp3D.WB_SphereFit.dot(), wblut.geom.WB_GeometryOp3D.WB_SphereFit.getLength3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isOrthogonalNorm (final WB_Coord v0, final WB_Coord v1) static
References wblut.geom.WB_GeometryOp3D.WB_SphereFit.dot(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isOrthogonalNorm (final WB_Coord v0, final WB_Coord v1, final double epsilon) static
References wblut.geom.WB_GeometryOp3D.WB_SphereFit.dot(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isParallel (final WB_Coord v0, final WB_Coord v1) static
References wblut.geom.WB_GeometryOp3D.WB_SphereFit.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_GeometryOp3D.WB_SphereFit.getLength3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isParallel (final WB_Coord v0, final WB_Coord v1, final double epsilon) static
References wblut.geom.WB_GeometryOp3D.WB_SphereFit.dot(), wblut.geom.WB_GeometryOp3D.WB_SphereFit.getLength3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isParallelNorm (final WB_Coord v0, final WB_Coord v1) static
References wblut.geom.WB_GeometryOp3D.WB_SphereFit.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isParallelNorm (final WB_Coord v0, final WB_Coord v1, final double epsilon) static
References wblut.geom.WB_GeometryOp3D.WB_SphereFit.dot(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isParallelNormX (final WB_Coord o, final WB_Coord p) static
Parameters
o
p
Returns
References wblut.geom.WB_Vector.cross(), wblut.math.WB_Epsilon.EPSILON, and wblut.geom.WB_Vector.getLength().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isParallelNormX (final WB_Coord o, final WB_Coord p, final double t) static
Parameters
o
p
t
Returns
References wblut.geom.WB_Vector.cross(), wblut.math.WB_Epsilon.EPSILON, and wblut.geom.WB_Vector.getLength().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isParallelX (final WB_Coord o, final WB_Coord p) static
Parameters
o
p
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.geom.WB_Vector.getSqLength3D(), wblut.math.WB_Epsilon.SQEPSILON, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isParallelX (final WB_Coord o, final WB_Coord p, final double t) static
Parameters
o
p
t
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.geom.WB_Vector.getSqLength3D(), wblut.math.WB_Epsilon.SQEPSILON, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static boolean wblut.geom.WB_GeometryOp3D.WB_SphereFit.isZero3D (final double ux, final double uy, final double uz) static
Parameters
ux
uy
uz
Returns
References wblut.geom.WB_GeometryOp3D.WB_SphereFit.getSqLength3D(), and wblut.math.WB_Epsilon.SQEPSILON.
static double wblut.geom.WB_GeometryOp3D.WB_SphereFit.scalarTriple (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz, final double wx, final double wy, final double wz) static
Parameters
ux
uy
uz
vx
vy
vz
wx
wy
wz
Returns
References wblut.geom.WB_GeometryOp3D.WB_SphereFit.cross(), and wblut.geom.WB_GeometryOp3D.WB_SphereFit.dot().
static double [][] wblut.geom.WB_GeometryOp3D.WB_SphereFit.tensor3D (final double ux, final double uy, final double uz, final double vx, final double vy, final double vz) static
Parameters
ux
uy
uz
vx
vy
vz
Returns
Member Data Documentation
int wblut.geom.WB_GeometryOp3D.WB_SphereFit.iterations
WB_Sphere wblut.geom.WB_GeometryOp3D.WB_SphereFit.sphere
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_GeometryOp3D.java