HE_Mesh: wblut.geom.WB_PolygonTriangulatorJTS Class Reference
wblut.geom.WB_PolygonTriangulatorJTS Class Reference
Classes
class EdgeFlipper
class IndexedDouble
class IndexedDoubleComparator
class IndexedEnvelope
class IndexedEnvelopeComparator
class IndexedTriangle
Public Member Functions
WB_PolygonTriangulatorJTS ()
WB_Triangulation2D triangulatePolygon2D (final WB_Polygon polygon, final boolean optimize)
WB_Triangulation2DWithPoints triangulatePolygon2D (final List<?extends WB_Coord > outerPolygon, final List<?extends WB_Coord >[] innerPolygons, final boolean optimize, final WB_Map2D context)
WB_Triangulation2DWithPoints triangulatePolygon2D (final int[] polygon, final WB_Coord[] points, final boolean optimize, final WB_Map2D context)
WB_Triangulation2D triangulatePolygon2D (final int[] polygon, final List<?extends WB_Coord > points, final boolean optimize, final WB_Map2D context)
int[] triangulateFace (final HE_Face face, final boolean optimize)
int[] triangulateSimplePolygon (final WB_Polygon polygon, final boolean optimize)
Static Public Member Functions
static int[] triangulateQuad (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
static void main (final String[] args)
Protected Member Functions
WB_Polygon makeSimplePolygon (final WB_Polygon polygon)
void createShell (final Polygon inputPolygon)
Private Member Functions
int[] triangulate (final Polygon inputPolygon, final boolean improve)
boolean isValidEdge (final int index0, final int index1)
int nextShellCoord (final int pos)
void doImprove (final List< IndexedTriangle > earList)
void joinHoleToShell (final Polygon inputPolygon, final Geometry hole)
void doJoinHole (final int shellVertexIndex, final Coordinate[] holeCoords, final int holeVertexIndex)
Static Private Member Functions
static int[] extractEdgesTri (final int[] ears)
static long getIndex (final int i, final int j, final int f)
static List< Geometry > getOrderedHoles (final Polygon poly)
static int getLowestVertex (final Geometry geom)
Private Attributes
final WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
List< Coordinate > shellCoords
boolean[] shellCoordAvailable
Constructor & Destructor Documentation
wblut.geom.WB_PolygonTriangulatorJTS.WB_PolygonTriangulatorJTS ()
Member Function Documentation
void wblut.geom.WB_PolygonTriangulatorJTS.createShell (final Polygon inputPolygon) protected
Transforms the input polygon into a single, possible self-intersecting shell by connecting holes to the exterior ring, The holes are added from the lowest upwards. As the resulting shell develops, a hole might be added to what was originally another hole.
Parameters
inputPolygon
References wblut.geom.WB_PolygonTriangulatorJTS.getOrderedHoles(), and wblut.geom.WB_PolygonTriangulatorJTS.joinHoleToShell().
void wblut.geom.WB_PolygonTriangulatorJTS.doImprove (final List< IndexedTriangle > earList) private
Attempts to improve the triangulation by examining pairs of triangles with a common edge, forming a quadrilateral, and testing if swapping the diagonal of this quadrilateral would produce two new triangles with larger minimum interior angles.
Parameters
earList
References wblut.geom.WB_PolygonTriangulatorJTS.EdgeFlipper.flip(), and wblut.geom.WB_PolygonTriangulatorJTS.IndexedTriangle.getSharedVertices().
void wblut.geom.WB_PolygonTriangulatorJTS.doJoinHole (final int shellVertexIndex, final Coordinate[] holeCoords, final int holeVertexIndex) private
Helper method for joinHoleToShell. Insert the hole coordinates into the shell coordinate list.
Parameters
shellVertexIndex insertion point in the shell coordinate list
holeCoords array of hole coordinates
holeVertexIndex attachment point of hole
static int [] wblut.geom.WB_PolygonTriangulatorJTS.extractEdgesTri (final int[] ears) static private
Parameters
ears
Returns
References wblut.geom.WB_PolygonTriangulatorJTS.getIndex().
static long wblut.geom.WB_PolygonTriangulatorJTS.getIndex (final int i, final int j, final int f) static private
Parameters
i
j
f
Returns
static int wblut.geom.WB_PolygonTriangulatorJTS.getLowestVertex (final Geometry geom) static private
Return the index of the lowest vertex.
Parameters
geom input geometry
Returns
index of the first vertex found at lowest point of the geometry
References wblut.math.WB_Epsilon.EPSILON.
static List<Geometry> wblut.geom.WB_PolygonTriangulatorJTS.getOrderedHoles (final Polygon poly) static private
Returns a list of holes in the input polygon (if any) ordered by y coordinate with ties broken using x coordinate.
Parameters
poly input polygon
Returns
a list of Geometry objects representing the ordered holes (may be empty)
boolean wblut.geom.WB_PolygonTriangulatorJTS.isValidEdge (final int index0, final int index1) private
Check if a candidate edge between two vertices passes through any other available vertices.
Parameters
index0 first vertex
index1 second vertex
Returns
true if the edge does not pass through any other available vertices; false otherwise
References wblut.geom.WB_PolygonTriangulatorJTS.nextShellCoord().
void wblut.geom.WB_PolygonTriangulatorJTS.joinHoleToShell (final Polygon inputPolygon, final Geometry hole) private
Join a given hole to the current shell. The hole coordinates are inserted into the list of shell coordinates.
Parameters
inputPolygon
hole the hole to join
References wblut.geom.WB_PolygonTriangulatorJTS.doJoinHole(), and wblut.geom.WB_PolygonTriangulatorJTS.getLowestVertex().
static void wblut.geom.WB_PolygonTriangulatorJTS.main (final String[] args) static
References wblut.hemesh.HE_Mesh.modify(), and wblut.hemesh.HEC_Archimedes.setEdge().
WB_Polygon wblut.geom.WB_PolygonTriangulatorJTS.makeSimplePolygon (final WB_Polygon polygon) protected
Parameters
polygon
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonFromJTSPolygon2D(), and wblut.geom.WB_PolygonTriangulatorJTS.createShell().
int wblut.geom.WB_PolygonTriangulatorJTS.nextShellCoord (final int pos) private
Get the index of the next available shell coordinate starting from the given candidate position.
Parameters
pos candidate position
Returns
index of the next available shell coordinate
int [] wblut.geom.WB_PolygonTriangulatorJTS.triangulate (final Polygon inputPolygon, final boolean improve) private
Perform the triangulation.
Parameters
inputPolygon
improve if true, improvement of the triangulation is attempted as a post-processing step
Returns
GeometryCollection of triangular polygons
References wblut.geom.WB_PolygonTriangulatorJTS.createShell(), wblut.geom.WB_PolygonTriangulatorJTS.doImprove(), wblut.geom.WB_PolygonTriangulatorJTS.isValidEdge(), and wblut.geom.WB_PolygonTriangulatorJTS.nextShellCoord().
int [] wblut.geom.WB_PolygonTriangulatorJTS.triangulateFace (final HE_Face face, final boolean optimize)
References wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.add(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Face.getHalfedge(), wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.getNearestNeighbor(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_PolygonTriangulatorJTS.triangulate(), wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.WB_KDEntryInteger< T extends WB_Coord >.value, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Swizzle.xd(), wblut.geom.WB_Swizzle.XY, wblut.geom.WB_Coord.yd(), wblut.geom.WB_Swizzle.yd(), wblut.geom.WB_Swizzle.YZ, wblut.geom.WB_Coord.zd(), and wblut.geom.WB_Swizzle.ZX.
WB_Triangulation2D wblut.geom.WB_PolygonTriangulatorJTS.triangulatePolygon2D (final WB_Polygon polygon, final boolean optimize)
Parameters
polygon
optimize
Returns
References wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.add(), wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane(), wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_Triangulation2D.getEdges(), wblut.geom.WB_Triangulation2DWithPoints.getPoints(), wblut.geom.WB_Triangulation2D.getTriangles(), and wblut.geom.WB_CoordCollection.size().
WB_Triangulation2DWithPoints wblut.geom.WB_PolygonTriangulatorJTS.triangulatePolygon2D (final List<?extends WB_Coord > outerPolygon, final List<?extends WB_Coord >[] innerPolygons, final boolean optimize, final WB_Map2D context)
Parameters
outerPolygon
innerPolygons
optimize
context
Returns
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_PolygonTriangulatorJTS.extractEdgesTri(), wblut.geom.WB_Map.mapPoint3D(), wblut.geom.WB_PolygonTriangulatorJTS.triangulate(), wblut.geom.WB_Map2D.unmapPoint2D(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
WB_Triangulation2DWithPoints wblut.geom.WB_PolygonTriangulatorJTS.triangulatePolygon2D (final int[] polygon, final WB_Coord[] points, final boolean optimize, final WB_Map2D context)
Parameters
polygon
points
optimize
context
Returns
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_PolygonTriangulatorJTS.extractEdgesTri(), wblut.geom.WB_Map.mapPoint3D(), wblut.geom.WB_PolygonTriangulatorJTS.triangulate(), wblut.geom.WB_Map2D.unmapPoint2D(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
WB_Triangulation2D wblut.geom.WB_PolygonTriangulatorJTS.triangulatePolygon2D (final int[] polygon, final List<?extends WB_Coord > points, final boolean optimize, final WB_Map2D context)
Parameters
polygon
points
optimize
context
Returns
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_PolygonTriangulatorJTS.extractEdgesTri(), wblut.geom.WB_Map.mapPoint3D(), wblut.geom.WB_PolygonTriangulatorJTS.triangulate(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static int [] wblut.geom.WB_PolygonTriangulatorJTS.triangulateQuad (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord p3) static
Parameters
p0
p1
p2
p3
Returns
References wblut.geom.WB_GeometryOp3D.pointInTriangleBary3D().
int [] wblut.geom.WB_PolygonTriangulatorJTS.triangulateSimplePolygon (final WB_Polygon polygon, final boolean optimize)
References wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.add(), wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.getNearestNeighbor(), wblut.geom.WB_Polygon.getNormal(), wblut.geom.WB_Polygon.getNumberOfShellPoints(), wblut.geom.WB_Polygon.getPoint(), wblut.geom.WB_PolygonTriangulatorJTS.triangulate(), wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.WB_KDEntryInteger< T extends WB_Coord >.value, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Swizzle.xd(), wblut.geom.WB_Swizzle.XY, wblut.geom.WB_Coord.yd(), wblut.geom.WB_Swizzle.yd(), wblut.geom.WB_Swizzle.YZ, wblut.geom.WB_Coord.zd(), and wblut.geom.WB_Swizzle.ZX.
Member Data Documentation
final WB_GeometryFactory wblut.geom.WB_PolygonTriangulatorJTS.geometryfactory = new WB_GeometryFactory() private
boolean [] wblut.geom.WB_PolygonTriangulatorJTS.shellCoordAvailable private
List<Coordinate> wblut.geom.WB_PolygonTriangulatorJTS.shellCoords private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_PolygonTriangulatorJTS.java