HE_Mesh: wblut.hemesh.HE_BoundaryHalfedgeInnerCirculator Class Reference
wblut.hemesh.HE_BoundaryHalfedgeInnerCirculator Class Reference
Public Member Functions
boolean hasNext ()
HE_Halfedge next ()
void remove ()
Private Attributes
final HE_Halfedge _start
HE_Halfedge _current
Member Function Documentation
boolean wblut.hemesh.HE_BoundaryHalfedgeInnerCirculator.hasNext ()
References wblut.hemesh.HE_BoundaryHalfedgeInnerCirculator._start, and wblut.hemesh.HE_Halfedge.getNextInFace().
HE_Halfedge wblut.hemesh.HE_BoundaryHalfedgeInnerCirculator.next ()
References wblut.hemesh.HE_BoundaryHalfedgeInnerCirculator._start, wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getPair().
void wblut.hemesh.HE_BoundaryHalfedgeInnerCirculator.remove ()
Member Data Documentation
HE_Halfedge wblut.hemesh.HE_BoundaryHalfedgeInnerCirculator._current private
final HE_Halfedge wblut.hemesh.HE_BoundaryHalfedgeInnerCirculator._start private
The documentation for this class was generated from the following file:
src/hemesh_core/wblut/hemesh/HE_BoundaryHalfedgeInnerCirculator.java