HE_Mesh: wblut.hemesh.HES_QuadSplit Class Reference
wblut.hemesh.HES_QuadSplit Class Reference
Public Member Functions
HES_QuadSplit ()
HES_QuadSplit setOffset (final double d)
HE_Selection getSplitFaces ()
Public Member Functions inherited from wblut.hemesh.HES_Subdividor
HES_Subdividor ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection sel)
Protected Member Functions inherited from wblut.hemesh.HES_Subdividor
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
HE_Selection selectionOut
double d
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HES_QuadSplit.HES_QuadSplit ()
Member Function Documentation
HE_Mesh wblut.hemesh.HES_QuadSplit.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.geom.WB_Point.addMul(), wblut.hemesh.HE_Selection.addVertices(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HES_QuadSplit.d, wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Mesh.getFacesAsArray(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Selection.getVerticesAsArray(), wblut.hemesh.HE_Halfedge.hasHalfedgeUVW(), wblut.hemesh.HE_Vertex.hasUVW(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Mesh.selectAllFaces(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Vertex.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HET_MeshOp.splitEdges(), wblut.hemesh.HE_Machine.tracker, wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), and wblut.hemesh.HE_TextureCoordinate.wd().
HE_Mesh wblut.hemesh.HES_QuadSplit.applySelf (final HE_Selection sel) protected
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Selection.addFaces(), wblut.geom.WB_Point.addMul(), wblut.hemesh.HE_Selection.addVertices(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HES_QuadSplit.d, wblut.hemesh.HE_Selection.fItr(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Selection.getFacesAsArray(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Selection.getNumberOfFaces(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Selection.getVertices(), wblut.hemesh.HE_Halfedge.hasHalfedgeUVW(), wblut.hemesh.HE_Vertex.hasUVW(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Vertex.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HET_MeshOp.splitEdges(), wblut.hemesh.HE_Machine.tracker, wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), and wblut.hemesh.HE_TextureCoordinate.wd().
HE_Selection wblut.hemesh.HES_QuadSplit.getSplitFaces ()
Returns
References wblut.hemesh.HES_QuadSplit.selectionOut.
HES_QuadSplit wblut.hemesh.HES_QuadSplit.setOffset (final double d)
Parameters
d
Returns
References wblut.hemesh.HES_QuadSplit.d.
Member Data Documentation
double wblut.hemesh.HES_QuadSplit.d private
HE_Selection wblut.hemesh.HES_QuadSplit.selectionOut private
The documentation for this class was generated from the following file:
src/hemesh_subdividors/wblut/hemesh/HES_QuadSplit.java