HE_Mesh: wblut.hemesh.HE_Boundary Class Reference
wblut.hemesh.HE_Boundary Class Reference
Public Member Functions
HE_Boundary ()
HE_BoundaryEdgeCirculator beCrc ()
HE_BoundaryFaceCirculator bfCrc ()
HE_BoundaryVertexCirculator bvCrc ()
HE_BoundaryHalfedgeInnerCirculator bheiCrc ()
HE_BoundaryHalfedgeOuterCirculator bheoCrc ()
HE_BoundaryEdgeRevCirculator beRevCrc ()
HE_BoundaryFaceRevCirculator bfRevCrc ()
HE_BoundaryHalfedgeInnerRevCirculator bheiRevCrc ()
HE_BoundaryHalfedgeOuterRevCirculator bheoRevCrc ()
HE_BoundaryVertexRevCirculator bvRevCrc ()
long key ()
List< HE_Vertex > getUniqueBoundaryVertices ()
List< HE_Vertex > getBoundaryVertices ()
List< HE_Halfedge > getBoundaryHalfedges ()
List< HE_Halfedge > getBoundaryHalfedgesTwoSided ()
List< HE_Halfedge > getBoundaryEdges ()
HE_Halfedge getHalfedge ()
HE_Halfedge getHalfedge (final HE_Vertex v)
HE_Halfedge getHalfedge (final HE_Face f)
void sort ()
int compareTo (final HE_Boundary b)
List< HE_Face > getNeighborFaces ()
String toString ()
void copyProperties (final HE_Face el)
void clear ()
WB_CoordCollection getPoints ()
Public Member Functions inherited from wblut.hemesh.HE_MeshElement
HE_MeshElement ()
void clearVisited ()
void setVisited ()
void setVisited (final boolean b)
boolean isVisited ()
void setVisible (final boolean b)
boolean isVisible ()
int hashCode ()
boolean equals (final Object other)
void copyProperties (final HE_MeshElement el)
int getColor ()
void setColor (final int color)
Public Member Functions inherited from wblut.hemesh.HE_Element
HE_Element ()
final void setUserLabel (final int label)
final long getKey ()
final int getInternalLabel ()
final int getUserLabel ()
int hashCode ()
boolean equals (final Object other)
void copyProperties (final HE_Element el)
Protected Member Functions
void _setHalfedge (final HE_Halfedge halfedge)
void _clearHalfedge ()
void clearPrecomputed ()
Protected Member Functions inherited from wblut.hemesh.HE_MeshElement
abstract void clear ()
Protected Member Functions inherited from wblut.hemesh.HE_Element
final void setInternalLabel (final int label)
abstract void clear ()
abstract void clearPrecomputed ()
Private Attributes
HE_Halfedge _halfedge
Additional Inherited Members
Protected Attributes inherited from wblut.hemesh.HE_MeshElement
volatile boolean visited
boolean visible
int color
Protected Attributes inherited from wblut.hemesh.HE_Element
final long key
int internalLabel
int userLabel
Static Protected Attributes inherited from wblut.hemesh.HE_MeshElement
static final WB_GeometryFactory gf = new WB_GeometryFactory()
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Static Protected Attributes inherited from wblut.hemesh.HE_Element
static AtomicLong currentKey = new AtomicLong(0)
Detailed Description
Author
FVH
Constructor & Destructor Documentation
wblut.hemesh.HE_Boundary.HE_Boundary ()
Instantiates a new HE_Boundary.
Member Function Documentation
void wblut.hemesh.HE_Boundary._clearHalfedge () protected
void wblut.hemesh.HE_Boundary._setHalfedge (final HE_Halfedge halfedge) protected
Parameters
halfedge
HE_BoundaryEdgeCirculator wblut.hemesh.HE_Boundary.beCrc ()
Returns
HE_BoundaryEdgeRevCirculator wblut.hemesh.HE_Boundary.beRevCrc ()
Returns
HE_BoundaryFaceCirculator wblut.hemesh.HE_Boundary.bfCrc ()
Returns
HE_BoundaryFaceRevCirculator wblut.hemesh.HE_Boundary.bfRevCrc ()
Returns
HE_BoundaryHalfedgeInnerCirculator wblut.hemesh.HE_Boundary.bheiCrc ()
Returns
HE_BoundaryHalfedgeInnerRevCirculator wblut.hemesh.HE_Boundary.bheiRevCrc ()
Returns
HE_BoundaryHalfedgeOuterCirculator wblut.hemesh.HE_Boundary.bheoCrc ()
Returns
HE_BoundaryHalfedgeOuterRevCirculator wblut.hemesh.HE_Boundary.bheoRevCrc ()
Returns
HE_BoundaryVertexCirculator wblut.hemesh.HE_Boundary.bvCrc ()
Returns
HE_BoundaryVertexRevCirculator wblut.hemesh.HE_Boundary.bvRevCrc ()
Returns
void wblut.hemesh.HE_Boundary.clear ()
void wblut.hemesh.HE_Boundary.clearPrecomputed () protected
int wblut.hemesh.HE_Boundary.compareTo (final HE_Boundary b)
Parameters
f
Returns
References wblut.hemesh.HE_Halfedge.compareTo(), and wblut.hemesh.HE_Boundary.getHalfedge().
void wblut.hemesh.HE_Boundary.copyProperties (final HE_Face el)
Parameters
el
List<HE_Halfedge> wblut.hemesh.HE_Boundary.getBoundaryEdges ()
Returns
References wblut.hemesh.HE_Boundary._halfedge, wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPair(), and wblut.hemesh.HE_Halfedge.isEdge().
List<HE_Halfedge> wblut.hemesh.HE_Boundary.getBoundaryHalfedges ()
Returns
References wblut.hemesh.HE_Boundary._halfedge, and wblut.hemesh.HE_Halfedge.getNextInFace().
List<HE_Halfedge> wblut.hemesh.HE_Boundary.getBoundaryHalfedgesTwoSided ()
Returns
References wblut.hemesh.HE_Boundary._halfedge, wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getPair().
List<HE_Vertex> wblut.hemesh.HE_Boundary.getBoundaryVertices ()
References wblut.hemesh.HE_Boundary._halfedge, wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getVertex().
HE_Halfedge wblut.hemesh.HE_Boundary.getHalfedge ()
Returns
References wblut.hemesh.HE_Boundary._halfedge.
HE_Halfedge wblut.hemesh.HE_Boundary.getHalfedge (final HE_Vertex v)
Parameters
v
Returns
References wblut.hemesh.HE_Boundary._halfedge, wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getVertex().
HE_Halfedge wblut.hemesh.HE_Boundary.getHalfedge (final HE_Face f)
Parameters
f
Returns
References wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Boundary.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getPair().
List<HE_Face> wblut.hemesh.HE_Boundary.getNeighborFaces ()
Returns
References wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Boundary.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getPair().
WB_CoordCollection wblut.hemesh.HE_Boundary.getPoints ()
References wblut.hemesh.HE_Boundary.getBoundaryVertices(), and wblut.geom.WB_CoordCollection.getCollection().
List<HE_Vertex> wblut.hemesh.HE_Boundary.getUniqueBoundaryVertices ()
Returns
References wblut.hemesh.HE_Boundary._halfedge, wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getVertex().
long wblut.hemesh.HE_Boundary.key ()
Returns
void wblut.hemesh.HE_Boundary.sort ()
References wblut.hemesh.HE_Boundary._halfedge, wblut.hemesh.HE_Vertex.compareTo(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getVertex().
String wblut.hemesh.HE_Boundary.toString ()
References wblut.hemesh.HE_Boundary.key().
Member Data Documentation
HE_Halfedge wblut.hemesh.HE_Boundary._halfedge private
Halfedge associated with this boundary.
The documentation for this class was generated from the following file:
src/hemesh_core/wblut/hemesh/HE_Boundary.java