HE_Mesh: wblut.hemesh.HEM_TaubinSmooth Class Reference
wblut.hemesh.HEM_TaubinSmooth Class Reference
Public Member Functions
HEM_TaubinSmooth ()
HEM_TaubinSmooth setAutoRescale (final boolean b)
HEM_TaubinSmooth setIterations (final int r)
HEM_TaubinSmooth setKeepBoundary (final boolean b)
HEM_TaubinSmooth setLambda (final double lambda)
HEM_TaubinSmooth setMu (final double mu)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
boolean autoRescale
boolean keepBoundary
double lambda
double mu
int iter
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_TaubinSmooth.HEM_TaubinSmooth ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_TaubinSmooth.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.hemesh.HE_Mesh.fitInAABB(), wblut.hemesh.HE_Mesh.getAABB(), wblut.hemesh.HE_Vertex.getNeighborVertices(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Vertex.isBoundary(), wblut.hemesh.HEM_TaubinSmooth.iter, wblut.hemesh.HEM_TaubinSmooth.keepBoundary, wblut.hemesh.HEM_TaubinSmooth.mu, wblut.geom.WB_Point.mulSelf(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HE_Vertex.set(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Machine.tracker, and wblut.hemesh.HE_Mesh.vItr().
HE_Mesh wblut.hemesh.HEM_TaubinSmooth.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Mesh.fitInAABB(), wblut.hemesh.HE_Mesh.getAABB(), wblut.hemesh.HE_Vertex.getNeighborVertices(), wblut.hemesh.HE_Selection.getNumberOfVertices(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Vertex.isBoundary(), wblut.hemesh.HEM_TaubinSmooth.iter, wblut.hemesh.HEM_TaubinSmooth.keepBoundary, wblut.hemesh.HEM_TaubinSmooth.mu, wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HE_Vertex.set(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Machine.tracker, and wblut.hemesh.HE_Selection.vItr().
HEM_TaubinSmooth wblut.hemesh.HEM_TaubinSmooth.setAutoRescale (final boolean b)
Parameters
b
Returns
HEM_TaubinSmooth wblut.hemesh.HEM_TaubinSmooth.setIterations (final int r)
Parameters
r
Returns
HEM_TaubinSmooth wblut.hemesh.HEM_TaubinSmooth.setKeepBoundary (final boolean b)
Parameters
b
Returns
HEM_TaubinSmooth wblut.hemesh.HEM_TaubinSmooth.setLambda (final double lambda)
Parameters
lambda
Returns
References wblut.hemesh.HEM_TaubinSmooth.lambda.
HEM_TaubinSmooth wblut.hemesh.HEM_TaubinSmooth.setMu (final double mu)
Parameters
mu
Returns
References wblut.hemesh.HEM_TaubinSmooth.mu.
Member Data Documentation
boolean wblut.hemesh.HEM_TaubinSmooth.autoRescale private
int wblut.hemesh.HEM_TaubinSmooth.iter private
boolean wblut.hemesh.HEM_TaubinSmooth.keepBoundary private
double wblut.hemesh.HEM_TaubinSmooth.lambda private
double wblut.hemesh.HEM_TaubinSmooth.mu private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_TaubinSmooth.java