HE_Mesh: wblut.geom.WB_Danzer Class Reference
wblut.geom.WB_Danzer Class Reference
Classes
enum Type
class WB_DanzerTile
Public Member Functions
WB_Danzer (final double sc, final Type t)
WB_Danzer (final double sc, final Type t, final WB_Coord offset)
WB_Danzer (final double sc, final Type t, final double angle)
WB_Danzer (final double sc, final Type t, final double angle, final WB_Coord offset)
WB_Danzer (final double sc, final Type t, final WB_Map2D context)
WB_Danzer (final double sc, final Type t, final double angle, final WB_Coord offset, final WB_Map2D context)
void centerOnPoint (final int i)
void setSeed (final long seed)
void inflate ()
void inflate (final int rep)
void inflate (final double probability)
void inflate (final double probability, final int rep)
WB_DanzerTile tile (final int i)
int oldest ()
int youngest ()
void inflateTile (final int i)
void inflateOldest ()
void inflateOldest (final int r)
void removeTile (final int i)
int size ()
int numberOfPoints ()
List< WB_Point > points ()
WB_CoordCollection getPoints ()
List< WB_Polygon > getTiles ()
int[] getTriangles ()
WB_Triangulation2DWithPoints getTriangulation ()
int[] getTilesAsIndices ()
Protected Member Functions
List< WB_DanzerTile > inflateTileInt (final WB_DanzerTile T, final double probability)
Protected Attributes
double a
Type type
List< WB_Point > points
List< WB_DanzerTile > tiles
WB_MTRandom rnd
Private Member Functions
void clean ()
Private Attributes
WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.geom.WB_Danzer.WB_Danzer (final double sc, final Type t)
Parameters
sc
t
wblut.geom.WB_Danzer.WB_Danzer (final double sc, final Type t, final WB_Coord offset)
Parameters
sc
t
offset
wblut.geom.WB_Danzer.WB_Danzer (final double sc, final Type t, final double angle)
Parameters
sc
t
angle
wblut.geom.WB_Danzer.WB_Danzer (final double sc, final Type t, final double angle, final WB_Coord offset)
Parameters
sc
t
angle
offset
wblut.geom.WB_Danzer.WB_Danzer (final double sc, final Type t, final WB_Map2D context)
Parameters
sc
t
context
wblut.geom.WB_Danzer.WB_Danzer (final double sc, final Type t, final double angle, final WB_Coord offset, final WB_Map2D context)
Parameters
sc
t
angle
offset
context
References wblut.geom.WB_Transform.addRotateZ(), wblut.geom.WB_Point.applySelf(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_Map2D.unmapPoint2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
Member Function Documentation
void wblut.geom.WB_Danzer.centerOnPoint (final int i)
References wblut.geom.WB_Point.subSelf().
void wblut.geom.WB_Danzer.clean () private
WB_CoordCollection wblut.geom.WB_Danzer.getPoints ()
Returns
Implements wblut.geom.WB_TriangleGenerator.
References wblut.geom.WB_CoordCollection.getCollection().
List<WB_Polygon> wblut.geom.WB_Danzer.getTiles ()
Returns
References wblut.geom.WB_Danzer.clean(), and wblut.geom.WB_GeometryFactory2D.createSimplePolygon().
int [] wblut.geom.WB_Danzer.getTilesAsIndices ()
Returns
References wblut.geom.WB_Danzer.clean().
int [] wblut.geom.WB_Danzer.getTriangles ()
Returns
Implements wblut.geom.WB_TriangleGenerator.
References wblut.geom.WB_Danzer.clean().
WB_Triangulation2DWithPoints wblut.geom.WB_Danzer.getTriangulation ()
References wblut.geom.WB_Danzer.getPoints(), and wblut.geom.WB_Danzer.getTilesAsIndices().
void wblut.geom.WB_Danzer.inflate ()
References wblut.geom.WB_Danzer.inflateTileInt().
void wblut.geom.WB_Danzer.inflate (final int rep)
Parameters
rep
References wblut.geom.WB_Danzer.inflate().
void wblut.geom.WB_Danzer.inflate (final double probability)
References wblut.geom.WB_Danzer.inflateTileInt().
void wblut.geom.WB_Danzer.inflate (final double probability, final int rep)
Parameters
probability
rep
References wblut.geom.WB_Danzer.inflate().
void wblut.geom.WB_Danzer.inflateOldest ()
void wblut.geom.WB_Danzer.inflateOldest (final int r)
Parameters
r
References wblut.geom.WB_Danzer.inflateTileInt(), and wblut.geom.WB_Danzer.oldest().
void wblut.geom.WB_Danzer.inflateTile (final int i)
Parameters
i
References wblut.geom.WB_Danzer.inflateTileInt().
List<WB_DanzerTile> wblut.geom.WB_Danzer.inflateTileInt (final WB_DanzerTile T, final double probability) protected
Parameters
T
probability
Returns
References wblut.geom.WB_Danzer.Type.A, wblut.geom.WB_Point.add(), wblut.geom.WB_Danzer.Type.B, wblut.geom.WB_Danzer.Type.C, wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), and wblut.math.WB_MTRandom.nextDouble().
int wblut.geom.WB_Danzer.numberOfPoints ()
Returns
int wblut.geom.WB_Danzer.oldest ()
Returns
List<WB_Point> wblut.geom.WB_Danzer.points ()
Returns
void wblut.geom.WB_Danzer.removeTile (final int i)
Parameters
i
void wblut.geom.WB_Danzer.setSeed (final long seed)
References wblut.math.WB_MTRandom.setSeed().
int wblut.geom.WB_Danzer.size ()
Returns
WB_DanzerTile wblut.geom.WB_Danzer.tile (final int i)
Parameters
i
Returns
int wblut.geom.WB_Danzer.youngest ()
Returns
Member Data Documentation
double wblut.geom.WB_Danzer.a protected
WB_GeometryFactory wblut.geom.WB_Danzer.geometryfactory = new WB_GeometryFactory() private
List<WB_Point> wblut.geom.WB_Danzer.points protected
WB_MTRandom wblut.geom.WB_Danzer.rnd protected
List<WB_DanzerTile> wblut.geom.WB_Danzer.tiles protected
Type wblut.geom.WB_Danzer.type protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Danzer.java