HE_Mesh: wblut.hemesh.HEC_Johnson Class Reference
wblut.hemesh.HEC_Johnson Class Reference
Public Member Functions
HEC_Johnson ()
HEC_Johnson (final int type, final double E)
HEC_Johnson setEdge (final double E)
HEC_Johnson setType (final int type)
String getName ()
HE_Mesh createBase ()
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Static Public Member Functions
static void printTypes ()
Private Attributes
double R
int type
String name
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Johnson polyhedra.
Author
Implemented by Frederik Vanhoutte (W:Blut), painstakingly collected by David Marec. Many thanks, without David this wouldn't be here.
Constructor & Destructor Documentation
wblut.hemesh.HEC_Johnson.HEC_Johnson ()
Instantiates a new dodecahedron.
wblut.hemesh.HEC_Johnson.HEC_Johnson (final int type, final double E)
Instantiates a new Johnson polyhedron.
Parameters
type the type
E edge length
References wblut.hemesh.HEC_Creator.center, and wblut.hemesh.HEC_Johnson.type.
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_Johnson.createBase ()
References wblut.hemesh.HEC_Creator.create(), wblut.hemesh.HE_Mesh.scaleSelf(), wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HEC_FromFacelist.setVertices(), and wblut.hemesh.HE_Mesh.vertices.
String wblut.hemesh.HEC_Johnson.getName ()
Gets the name.
Returns
the name
References wblut.hemesh.HEC_Johnson.name.
static void wblut.hemesh.HEC_Johnson.printTypes () static
HEC_Johnson wblut.hemesh.HEC_Johnson.setEdge (final double E)
Set edge length.
Parameters
E edge length
Returns
self
HEC_Johnson wblut.hemesh.HEC_Johnson.setType (final int type)
Set type.
Parameters
type the type
Returns
self
References wblut.hemesh.HEC_Johnson.type.
Member Data Documentation
String wblut.hemesh.HEC_Johnson.name private
The name.
double wblut.hemesh.HEC_Johnson.R private
Edge.
int wblut.hemesh.HEC_Johnson.type private
Type.
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_Johnson.java