HE_Mesh: wblut.hemesh.HEC_Box Class Reference
wblut.hemesh.HEC_Box Class Reference
Public Member Functions
HEC_Box ()
HEC_Box (final double W, final double H, final double D, final int L, final int M, final int N)
HEC_Box (final double x, final double y, final double z, final double W, final double H, final double D, final int L, final int M, final int N)
HEC_Box (final WB_Coord center, final double W, final double H, final double D, final int L, final int M, final int N)
HEC_Box setFromAABB (final WB_AABB AABB, final double padding)
HEC_Box setFromAABB (final WB_AABB AABB)
HEC_Box setFromCorners (final WB_Coord min, final WB_Coord max)
HEC_Box setFromCorners (final double minx, final double miny, final double minz, final double maxx, final double maxy, final double maxz)
HEC_Box setSegments (final int L, final int M, final int N)
HEC_Box setWidth (final double W)
HEC_Box setHeight (final double H)
HEC_Box setDepth (final double D)
HEC_Box setSize (final double W, final double H, final double D)
HEC_Box setWidthSegments (final int L)
HEC_Box setHeightSegments (final int M)
HEC_Box setDepthSegments (final int N)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Attributes
double W
double H
double D
int L
int M
int N
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Axis Aligned Box.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_Box.HEC_Box ()
Create a placeholder box.
wblut.hemesh.HEC_Box.HEC_Box (final double W, final double H, final double D, final int L, final int M, final int N)
Create a box at (0,0,0).
Parameters
W width (X)
H height (Y)
D depth (Z)
L number of width divisions
M number of height divisions
N number of depth divisions
References wblut.hemesh.HEC_Box.D, wblut.hemesh.HEC_Box.H, and wblut.hemesh.HEC_Box.W.
wblut.hemesh.HEC_Box.HEC_Box (final double x, final double y, final double z, final double W, final double H, final double D, final int L, final int M, final int N)
Create a box at (x,y,z).
Parameters
x x-ordinate of center
y y-ordinate of center
z z-ordinate of center
W width (X)
H height (Y)
D depth (Z)
L number of width divisions
M number of height divisions
N number of depth divisions
References wblut.hemesh.HEC_Box.D, wblut.hemesh.HEC_Box.H, wblut.hemesh.HEC_Creator.setCenter(), and wblut.hemesh.HEC_Box.W.
wblut.hemesh.HEC_Box.HEC_Box (final WB_Coord center, final double W, final double H, final double D, final int L, final int M, final int N)
Create a box at center.
Parameters
center center
W width (X)
H height (Y)
D depth (Z)
L number of width divisions
M number of height divisions
N number of depth divisions
References wblut.hemesh.HEC_Box.D, wblut.hemesh.HEC_Box.H, wblut.hemesh.HEC_Creator.setCenter(), wblut.hemesh.HEC_Box.W, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_Box.createBase () protected
References wblut.hemesh.HEC_FromFacelist.createBase(), wblut.hemesh.HEC_Box.D, wblut.hemesh.HEC_Box.H, wblut.hemesh.HEC_Box.L, wblut.hemesh.HEC_Box.M, wblut.hemesh.HEC_Box.N, wblut.hemesh.HEC_FromFacelist.setDuplicate(), wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HEC_FromFacelist.setFaceTextureIds(), wblut.hemesh.HEC_FromFacelist.setVertexUVW(), wblut.hemesh.HEC_FromFacelist.setVertices(), and wblut.hemesh.HEC_Box.W.
HEC_Box wblut.hemesh.HEC_Box.setDepth (final double D)
Set box depth.
Parameters
D depth of box (z-axis)
Returns
self
References wblut.hemesh.HEC_Box.D.
HEC_Box wblut.hemesh.HEC_Box.setDepthSegments (final int N)
Set box depth segments.
Parameters
N number of depth segments (z-axis)
Returns
self
HEC_Box wblut.hemesh.HEC_Box.setFromAABB (final WB_AABB AABB, final double padding)
Set box from AABB.
Parameters
AABB WB_AABB
padding the padding
Returns
self
References wblut.geom.WB_AABB.getCenter(), wblut.geom.WB_AABB.getDepth(), wblut.geom.WB_AABB.getHeight(), wblut.geom.WB_AABB.getWidth(), and wblut.hemesh.HEC_Creator.setCenter().
HEC_Box wblut.hemesh.HEC_Box.setFromAABB (final WB_AABB AABB)
References wblut.geom.WB_AABB.getCenter(), wblut.geom.WB_AABB.getDepth(), wblut.geom.WB_AABB.getHeight(), wblut.geom.WB_AABB.getWidth(), and wblut.hemesh.HEC_Creator.setCenter().
HEC_Box wblut.hemesh.HEC_Box.setFromCorners (final WB_Coord min, final WB_Coord max)
Parameters
min
max
Returns
References wblut.hemesh.HEC_Creator.setCenter(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
HEC_Box wblut.hemesh.HEC_Box.setFromCorners (final double minx, final double miny, final double minz, final double maxx, final double maxy, final double maxz)
Parameters
minx
miny
minz
maxx
maxy
maxz
Returns
References wblut.hemesh.HEC_Creator.setCenter().
HEC_Box wblut.hemesh.HEC_Box.setHeight (final double H)
Set box height.
Parameters
H height of box (y-axis)
Returns
self
References wblut.hemesh.HEC_Box.H.
HEC_Box wblut.hemesh.HEC_Box.setHeightSegments (final int M)
Set box height segments.
Parameters
M number of height segments (y-axis)
Returns
self
HEC_Box wblut.hemesh.HEC_Box.setSegments (final int L, final int M, final int N)
Parameters
L
M
N
Returns
References wblut.hemesh.HEC_Box.L, wblut.hemesh.HEC_Box.M, and wblut.hemesh.HEC_Box.N.
HEC_Box wblut.hemesh.HEC_Box.setSize (final double W, final double H, final double D)
References wblut.hemesh.HEC_Box.D, wblut.hemesh.HEC_Box.H, and wblut.hemesh.HEC_Box.W.
HEC_Box wblut.hemesh.HEC_Box.setWidth (final double W)
Set box width.
Parameters
W width of box (x-axis)
Returns
self
References wblut.hemesh.HEC_Box.W.
HEC_Box wblut.hemesh.HEC_Box.setWidthSegments (final int L)
Set box width segments.
Parameters
L number of width segments (x-axis)
Returns
self
Member Data Documentation
double wblut.hemesh.HEC_Box.D private
depth.
double wblut.hemesh.HEC_Box.H private
height.
int wblut.hemesh.HEC_Box.L private
width segments.
int wblut.hemesh.HEC_Box.M private
height segments.
int wblut.hemesh.HEC_Box.N private
depth segments.
double wblut.hemesh.HEC_Box.W private
width.
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_Box.java