HE_Mesh: wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element > Class Template Reference
wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element > Class Template Reference
Public Member Functions
HE_RASEC ()
HE_RASEC (final int n)
HE_RASEC (final Collection< E > items)
boolean add (final E item)
E removeAt (final int id)
boolean remove (final E item)
E get (final int i)
E getWithIndex (final int i)
E getWithKey (final long key)
int indexOf (final E object)
E pollRandom (final Random rnd)
int size ()
boolean contains (final E object)
boolean containsKey (final Long key)
Iterator< E > iterator ()
List< E > getObjects ()
Public Member Functions inherited from wblut.hemesh.HE_RAS< E >
HE_RAS ()
HE_RAS (final Collection< E > items)
abstract boolean add (final E item)
abstract E removeAt (final int id)
abstract boolean remove (final E item)
abstract E get (final int i)
abstract E getWithIndex (final int i)
abstract E getWithKey (final long key)
abstract int indexOf (final E object)
abstract E pollRandom (final Random rnd)
abstract int size ()
abstract boolean contains (final E object)
abstract boolean containsKey (final Long key)
abstract Iterator< E > iterator ()
Additional Inherited Members
Protected Member Functions inherited from wblut.hemesh.HE_RAS< E >
abstract List< E > getObjects ()
Detailed Description
Implementation of HE_RAS using Eclipse Collections library
Author
FVH
Parameters
<E> a class extending HE_Element
Constructor & Destructor Documentation
wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.HE_RASEC ()
wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.HE_RASEC (final int n)
Parameters
n
wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.HE_RASEC (final Collection< E > items)
Parameters
items
References wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.add().
Member Function Documentation
boolean wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.add (final E item)
boolean wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.contains (final E object)
boolean wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.containsKey (final Long key)
E wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.get (final int i)
List<E> wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.getObjects ()
E wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.getWithIndex (final int i)
E wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.getWithKey (final long key)
int wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.indexOf (final E object)
Iterator<E> wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.iterator ()
E wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.pollRandom (final Random rnd)
References wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.removeAt().
boolean wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.remove (final E item)
References wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.removeAt().
E wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.removeAt (final int id)
Override element at position id with last element.
Parameters
id
Returns
int wblut.hemesh.HE_RAS< E extends HE_Element >.HE_RASEC< E extends HE_Element >.size ()
The documentation for this class was generated from the following file:
src/hemesh_core/wblut/hemesh/HE_RAS.java