HE_Mesh: wblut.geom.WB_MutableCoordinate4D Class Reference
wblut.geom.WB_MutableCoordinate4D Class Reference
Public Member Functions
WB_MutableCoordinate4D ()
WB_MutableCoordinate4D (final double x, final double y)
WB_MutableCoordinate4D (final double x, final double y, final double z)
WB_MutableCoordinate4D (final double x, final double y, final double z, final double w)
WB_MutableCoordinate4D (final double[] x)
WB_MutableCoordinate4D (final WB_Coord v)
WB_MutableCoordinate4D (final double[] fromPoint, final double[] toPoint)
double getd (final int i)
float getf (final int i)
double xd ()
double yd ()
double zd ()
double wd ()
float xf ()
float yf ()
float zf ()
float wf ()
void setX (final double x)
void setY (final double y)
void setZ (final double z)
void setW (final double w)
void setCoord (final int i, final double v)
void set (final double x, final double y)
void set (final double x, final double y, final double z)
void set (final double x, final double y, final double z, final double w)
void set (final WB_Coord v)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoordinate
WB_MutableCoordinate ()
WB_MutableCoordinate (final double x, final double y)
WB_MutableCoordinate (final double x, final double y, final double z)
WB_MutableCoordinate (final double[] x)
WB_MutableCoordinate (final double[] fromPoint, final double[] toPoint)
WB_MutableCoordinate (final WB_Coord v)
WB_MutableCoordinate (final WB_Coord fromPoint, final WB_Coord toPoint)
double getd (final int i)
float getf (final int i)
double xd ()
double yd ()
double zd ()
double wd ()
float xf ()
float yf ()
float zf ()
float wf ()
void setX (final double x)
void setY (final double y)
void setZ (final double z)
void setW (final double w)
void setCoord (final int i, final double v)
void set (final double x, final double y)
void set (final double x, final double y, final double z)
void set (final double x, final double y, final double z, final double w)
void set (final WB_Coord v)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoordinate2D
WB_MutableCoordinate2D ()
WB_MutableCoordinate2D (final double x, final double y)
WB_MutableCoordinate2D (final double[] x)
WB_MutableCoordinate2D (final double[] fromPoint, final double[] toPoint)
WB_MutableCoordinate2D (final WB_Coord v)
WB_MutableCoordinate2D (final WB_Coord fromPoint, final WB_Coord toPoint)
double getd (final int i)
float getf (final int i)
double xd ()
double yd ()
double zd ()
double wd ()
float xf ()
float yf ()
float zf ()
float wf ()
void setX (final double x)
void setY (final double y)
void setZ (final double z)
void setW (final double w)
void setCoord (final int i, final double v)
void set (final WB_Coord v)
void set (final double x, final double y)
void set (final double x, final double y, final double z)
void set (final double x, final double y, final double z, final double w)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoord
void setX (double x)
void setY (double y)
void setZ (double z)
void setW (double w)
void setCoord (int i, double v)
void set (WB_Coord p)
void set (double x, double y)
void set (double x, double y, double z)
void set (double x, double y, double z, double w)
Public Member Functions inherited from wblut.geom.WB_Coord
double getd (int i)
float getf (int i)
Static Public Member Functions
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord Z ()
static WB_Coord W ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
Static Public Member Functions inherited from wblut.geom.WB_MutableCoordinate
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord Z ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
Static Public Member Functions inherited from wblut.geom.WB_MutableCoordinate2D
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
Static Private Attributes
static final WB_Coord X = new WB_MutableCoordinate4D(1, 0, 0, 0)
static final WB_Coord Y = new WB_MutableCoordinate4D(0, 1, 0, 0)
static final WB_Coord Z = new WB_MutableCoordinate4D(0, 0, 1, 0)
static final WB_Coord W = new WB_MutableCoordinate4D(0, 0, 0, 1)
static final WB_Coord ORIGIN = new WB_MutableCoordinate4D(0, 0, 0, 0)
static final WB_Coord ZERO = new WB_MutableCoordinate4D(0, 0, 0, 0)
Constructor & Destructor Documentation
wblut.geom.WB_MutableCoordinate4D.WB_MutableCoordinate4D ()
wblut.geom.WB_MutableCoordinate4D.WB_MutableCoordinate4D (final double x, final double y)
Parameters
x
y
wblut.geom.WB_MutableCoordinate4D.WB_MutableCoordinate4D (final double x, final double y, final double z)
Parameters
x
y
z
wblut.geom.WB_MutableCoordinate4D.WB_MutableCoordinate4D (final double x, final double y, final double z, final double w)
Parameters
x
y
z
w
wblut.geom.WB_MutableCoordinate4D.WB_MutableCoordinate4D (final double[] x)
Parameters
x
wblut.geom.WB_MutableCoordinate4D.WB_MutableCoordinate4D (final WB_Coord v)
Parameters
v
References wblut.geom.WB_Coord.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
wblut.geom.WB_MutableCoordinate4D.WB_MutableCoordinate4D (final double[] fromPoint, final double[] toPoint)
Parameters
fromPoint
toPoint
Member Function Documentation
int wblut.geom.WB_MutableCoordinate4D.compareTo (final WB_Coord p)
References wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
int wblut.geom.WB_MutableCoordinate4D.compareToY1st (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
boolean wblut.geom.WB_MutableCoordinate4D.equals (final Object o)
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
double wblut.geom.WB_MutableCoordinate4D.getd (final int i)
float wblut.geom.WB_MutableCoordinate4D.getf (final int i)
int wblut.geom.WB_MutableCoordinate4D.hashCode ()
References wblut.math.WB_HashCode.calculateHashCode(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
static WB_Coord wblut.geom.WB_MutableCoordinate4D.ORIGIN () static
Returns
void wblut.geom.WB_MutableCoordinate4D.set (final double x, final double y)
void wblut.geom.WB_MutableCoordinate4D.set (final double x, final double y, final double z)
void wblut.geom.WB_MutableCoordinate4D.set (final double x, final double y, final double z, final double w)
void wblut.geom.WB_MutableCoordinate4D.set (final WB_Coord v)
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_MutableCoordinate4D.setCoord (final int i, final double v)
void wblut.geom.WB_MutableCoordinate4D.setW (final double w)
void wblut.geom.WB_MutableCoordinate4D.setX (final double x)
void wblut.geom.WB_MutableCoordinate4D.setY (final double y)
void wblut.geom.WB_MutableCoordinate4D.setZ (final double z)
String wblut.geom.WB_MutableCoordinate4D.toString ()
References wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
static WB_Coord wblut.geom.WB_MutableCoordinate4D.W () static
Returns
double wblut.geom.WB_MutableCoordinate4D.wd ()
Get w as double.
Returns
w
Implements wblut.geom.WB_Coord.
float wblut.geom.WB_MutableCoordinate4D.wf ()
Get w as float.
Returns
w
Implements wblut.geom.WB_Coord.
static WB_Coord wblut.geom.WB_MutableCoordinate4D.X () static
Returns
double wblut.geom.WB_MutableCoordinate4D.xd ()
Get x as double.
Returns
x
Implements wblut.geom.WB_Coord.
float wblut.geom.WB_MutableCoordinate4D.xf ()
Get x as float.
Returns
x
Implements wblut.geom.WB_Coord.
static WB_Coord wblut.geom.WB_MutableCoordinate4D.Y () static
Returns
double wblut.geom.WB_MutableCoordinate4D.yd ()
Get y as double.
Returns
y
Implements wblut.geom.WB_Coord.
float wblut.geom.WB_MutableCoordinate4D.yf ()
Get y as float.
Returns
y
Implements wblut.geom.WB_Coord.
static WB_Coord wblut.geom.WB_MutableCoordinate4D.Z () static
Returns
double wblut.geom.WB_MutableCoordinate4D.zd ()
Get z as double.
Returns
z
Implements wblut.geom.WB_Coord.
static WB_Coord wblut.geom.WB_MutableCoordinate4D.ZERO () static
Returns
float wblut.geom.WB_MutableCoordinate4D.zf ()
Get z as float.
Returns
z
Implements wblut.geom.WB_Coord.
Member Data Documentation
final WB_Coord wblut.geom.WB_MutableCoordinate4D.ORIGIN = new WB_MutableCoordinate4D(0, 0, 0, 0) static private
final WB_Coord wblut.geom.WB_MutableCoordinate4D.W = new WB_MutableCoordinate4D(0, 0, 0, 1) static private
final WB_Coord wblut.geom.WB_MutableCoordinate4D.X = new WB_MutableCoordinate4D(1, 0, 0, 0) static private
final WB_Coord wblut.geom.WB_MutableCoordinate4D.Y = new WB_MutableCoordinate4D(0, 1, 0, 0) static private
final WB_Coord wblut.geom.WB_MutableCoordinate4D.Z = new WB_MutableCoordinate4D(0, 0, 1, 0) static private
final WB_Coord wblut.geom.WB_MutableCoordinate4D.ZERO = new WB_MutableCoordinate4D(0, 0, 0, 0) static private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_MutableCoordinate4D.java