HE_Mesh: wblut.hemesh.HEC_UVParametric Class Reference
wblut.hemesh.HEC_UVParametric Class Reference
Public Member Functions
HEC_UVParametric ()
HEC_UVParametric setEvaluator (final WB_VectorParameter eval)
HEC_UVParametric setFixDuplicatedVertices (final boolean b)
HEC_UVParametric setUVSteps (final int usteps, final int vsteps)
HEC_UVParametric setScale (final double r)
HEC_UVParametric setURange (final double umin, final double umax)
HEC_UVParametric setVRange (final double vmin, final double vmax)
Public Member Functions inherited from wblut.hemesh.HEC_FromFacelist
HEC_FromFacelist ()
HEC_FromFacelist setVertices (final WB_Coord[] vs)
HEC_FromFacelist setVertices (final WB_CoordCollection vs)
HEC_FromFacelist setVertices (final Collection<?extends WB_Coord > vs)
HEC_FromFacelist setVertexUVW (final Collection<?extends WB_Coord > vs)
HEC_FromFacelist setVertexUVW (final WB_Coord[] vs)
HEC_FromFacelist setVertexUVW (final double[][] vs)
HEC_FromFacelist setFaceVertexUVW (final Collection<?extends WB_Coord > vs)
HEC_FromFacelist setFaceVertexUVW (final WB_Coord[] vs)
HEC_FromFacelist setFaceVertexUVW (final double[][] vs)
HEC_FromFacelist setVertices (final WB_Coord[] vs, final boolean copy)
HEC_FromFacelist setVertices (final double[][] vs)
HEC_FromFacelist setVertices (final double[] vs)
HEC_FromFacelist setVertices (final float[][] vs)
HEC_FromFacelist setVertices (final float[] vs)
HEC_FromFacelist setFaces (final int[][] fs)
HEC_FromFacelist setFaces (final int[] fs)
HEC_FromFacelist setFaces (final List< int[]> fs)
HEC_FromFacelist setFacesUVW (final int[][] fs)
HEC_FromFacelist setFacesUVW (final int[] fs)
HEC_FromFacelist setFacesUVW (final List< int[]> fs)
HEC_FromFacelist setFaceTextureIds (final int[] fts)
HEC_FromFacelist setDuplicate (final boolean b)
HEC_FromFacelist setCheckNormals (final boolean b)
HEC_FromFacelist setCheckManifold (final boolean b)
HEC_FromFacelist setCleanUnused (final boolean b)
HEC_FromFacelist setUseFaceInformation (final boolean b)
HEC_FromFacelist setUseVertexInformation (final boolean b)
HEC_FromFacelist setFaceInformation (final int[] colors, final int[] textureIds, final boolean[] visibility, final int[] labels, final int[] intLabels)
HEC_FromFacelist setVertexInformation (final int[] colors, final boolean[] visibility, final int[] labels, final int[] intLabels)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_FromFacelist
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Protected Attributes
int usteps
int vsteps
double scale
WB_VectorParameter evaluator
double uRange
boolean fixDuplicatedVertices
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEC_UVParametric.HEC_UVParametric ()
Instantiates a new HEC_UVParametric.
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_UVParametric.createBase () protected
References wblut.hemesh.HEC_FromFacelist.createBase(), wblut.math.WB_VectorParameter.evaluate(), wblut.hemesh.HEC_FromFacelist.faces, wblut.geom.WB_Point.scaleSelf(), wblut.hemesh.HEC_FromFacelist.setDuplicate(), wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HEC_FromFacelist.setVertexUVW(), wblut.hemesh.HEC_FromFacelist.setVertices(), wblut.hemesh.HEC_UVParametric.usteps, wblut.hemesh.HEC_FromFacelist.uvws, wblut.hemesh.HEC_FromFacelist.vertices, and wblut.hemesh.HEC_UVParametric.vsteps.
HEC_UVParametric wblut.hemesh.HEC_UVParametric.setEvaluator (final WB_VectorParameter eval)
Parameters
eval
Returns
HEC_UVParametric wblut.hemesh.HEC_UVParametric.setFixDuplicatedVertices (final boolean b)
Parameters
b
Returns
HEC_UVParametric wblut.hemesh.HEC_UVParametric.setScale (final double r)
Sets the scale factor.
Parameters
r the r
Returns
self
HEC_UVParametric wblut.hemesh.HEC_UVParametric.setURange (final double umin, final double umax)
Parameters
umin
umax
Returns
HEC_UVParametric wblut.hemesh.HEC_UVParametric.setUVSteps (final int usteps, final int vsteps)
Sets the number of subdivisions along u/v axes.
Parameters
usteps the number of subdivisions along u-axis
vsteps the number of subdivisions along v-axis
Returns
self
HEC_UVParametric wblut.hemesh.HEC_UVParametric.setVRange (final double vmin, final double vmax)
Parameters
vmin
vmax
Returns
Member Data Documentation
WB_VectorParameter wblut.hemesh.HEC_UVParametric.evaluator protected
The parametric evaluator.
boolean wblut.hemesh.HEC_UVParametric.fixDuplicatedVertices protected
double wblut.hemesh.HEC_UVParametric.scale protected
Scale factor.
double wblut.hemesh.HEC_UVParametric.uRange protected
int wblut.hemesh.HEC_UVParametric.usteps protected
Number of subdivisions along u-axis.
int wblut.hemesh.HEC_UVParametric.vsteps protected
Number of subdivisions along v-axis.
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_UVParametric.java