HE_Mesh: wblut.hemesh.HET_Fixer Class Reference
wblut.hemesh.HET_Fixer Class Reference
Classes
class HET_SelfIntersectionResult
Public Member Functions
void fixHalfedgeFaceAssignment (final HE_Mesh mesh)
void fixHalfedgeVertexAssignment (final HE_Mesh mesh)
Static Public Member Functions
static void deleteTwoEdgeFace (final HE_Mesh mesh, final HE_Face f)
static void deleteTwoEdgeFaces (final HE_Mesh mesh)
static void deleteTwoEdgeVertex (final HE_Mesh mesh, final HE_Vertex v)
static void deleteTwoEdgeVertices (final HE_Mesh mesh)
static void collapseDegenerateEdges (final HE_Mesh mesh)
static void collapseDegenerateEdges (final HE_Mesh mesh, final double d)
static boolean fixNonManifoldVerticesOnePass (final HE_Mesh mesh)
static void fixDegenerateTriangles (final HE_Mesh mesh)
static void fixNonManifoldVertices (final HE_Mesh mesh)
static void deleteCollinearVertices (final HE_Mesh mesh)
static void deleteDegenerateTriangles (final HE_Mesh mesh)
static void clean (final HE_Mesh mesh)
static void fixLoops (final HE_Mesh mesh)
static List< HET_SelfIntersectionResult > getSelfIntersection (final HE_Mesh mesh)
Static Public Attributes
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Author
FVH
Member Function Documentation
static void wblut.hemesh.HET_Fixer.clean (final HE_Mesh mesh) static
References wblut.hemesh.HE_Mesh.modify().
static void wblut.hemesh.HET_Fixer.collapseDegenerateEdges (final HE_Mesh mesh) static
Collapse all zero-length edges.
References wblut.hemesh.HET_MeshOp.collapseEdge(), wblut.hemesh.HE_Mesh.eItr(), wblut.hemesh.HE_Mesh.get(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), wblut.hemesh.HE_Halfedge.getVertex(), and wblut.math.WB_Epsilon.isZeroSq().
static void wblut.hemesh.HET_Fixer.collapseDegenerateEdges (final HE_Mesh mesh, final double d) static
Parameters
mesh
d
References wblut.hemesh.HET_MeshOp.collapseEdge(), wblut.hemesh.HE_Mesh.eItr(), wblut.hemesh.HE_Mesh.get(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), and wblut.hemesh.HE_Halfedge.getVertex().
static void wblut.hemesh.HET_Fixer.deleteCollinearVertices (final HE_Mesh mesh) static
Remove all redundant vertices in straight edges.
References wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getHalfedgeTangent(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Vertex.getVertexDegree(), wblut.geom.WB_Vector.isParallel(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setVertex(), and wblut.hemesh.HE_Mesh.vItr().
static void wblut.hemesh.HET_Fixer.deleteDegenerateTriangles (final HE_Mesh mesh) static
References wblut.hemesh.HET_MeshOp.collapseHalfedge(), wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HE_Mesh.deleteEdge(), wblut.hemesh.HE_Mesh.getFaces(), wblut.hemesh.HE_Halfedge.getLength(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.math.WB_Epsilon.isZero().
static void wblut.hemesh.HET_Fixer.deleteTwoEdgeFace (final HE_Mesh mesh, final HE_Face f) static
Parameters
mesh
f
References wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_Mesh.setHalfedge(), and wblut.hemesh.HE_Mesh.setPair().
static void wblut.hemesh.HET_Fixer.deleteTwoEdgeFaces (final HE_Mesh mesh) static
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_Mesh.setHalfedge(), and wblut.hemesh.HE_Mesh.setPair().
static void wblut.hemesh.HET_Fixer.deleteTwoEdgeVertex (final HE_Mesh mesh, final HE_Vertex v) static
Parameters
mesh
v
References wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Vertex.getVertexDegree(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setPair().
static void wblut.hemesh.HET_Fixer.deleteTwoEdgeVertices (final HE_Mesh mesh) static
References wblut.hemesh.HET_Fixer.deleteTwoEdgeVertex(), wblut.hemesh.HE_Vertex.getVertexDegree(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_VertexIterator.next(), and wblut.hemesh.HE_Mesh.vItr().
static void wblut.hemesh.HET_Fixer.fixDegenerateTriangles (final HE_Mesh mesh) static
References wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HE_Mesh.deleteEdge(), wblut.math.WB_Epsilon.EPSILON, wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getLength(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_Face.isDegenerate(), wblut.math.WB_Epsilon.isZero(), and wblut.hemesh.HE_FaceIterator.next().
void wblut.hemesh.HET_Fixer.fixHalfedgeFaceAssignment (final HE_Mesh mesh)
Iterate through all halfedges and reset the halfedge link to its face to itself. f=he.getFace() f.setHalfedge(he)
References wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Mesh.heItr(), and wblut.hemesh.HE_Mesh.setHalfedge().
void wblut.hemesh.HET_Fixer.fixHalfedgeVertexAssignment (final HE_Mesh mesh)
Iterate through all halfedges and reset the halfedge link to its vertex to itself. v=he.getVertex() v.setHalfedge(he)
References wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Mesh.heItr(), and wblut.hemesh.HE_Mesh.setHalfedge().
static void wblut.hemesh.HET_Fixer.fixLoops (final HE_Mesh mesh) static
Fix loops.
References wblut.hemesh.HE_Mesh.getHalfedges(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Mesh.setNext().
static void wblut.hemesh.HET_Fixer.fixNonManifoldVertices (final HE_Mesh mesh) static
References wblut.hemesh.HET_Fixer.fixNonManifoldVerticesOnePass().
static boolean wblut.hemesh.HET_Fixer.fixNonManifoldVerticesOnePass (final HE_Mesh mesh) static
Returns
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Vertex.getHalfedgeStar(), wblut.hemesh.HE_Mesh.getNumberOfHalfedges(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Mesh.heItr(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_VertexIterator.next(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setVertex(), and wblut.hemesh.HE_Mesh.vItr().
static List<HET_SelfIntersectionResult> wblut.hemesh.HET_Fixer.getSelfIntersection (final HE_Mesh mesh) static
References wblut.hemesh.HE_Selection.add(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.geom.WB_IntersectionResult.intersection, wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_IntersectionResult.object, wblut.hemesh.HE_Mesh.resetFaceInternalLabels(), and wblut.hemesh.HE_Mesh.triangulate().
Member Data Documentation
final WB_ProgressTracker wblut.hemesh.HET_Fixer.tracker = WB_ProgressTracker.instance() static
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_Fixer.java