HE_Mesh: wblut.math.WB_SphericalHarmonics Class Reference
wblut.math.WB_SphericalHarmonics Class Reference
Static Public Member Functions
static double Plm (final int L, final int M, final double x)
static WB_Coord rotateSpherical (final double angle, final double ax, final double ay, final double az, final double theta, final double phi)
static WB_Complex Y (final int L, final int M, final double theta, final double phi)
static WB_Complex Y (final int L, final int M, final double theta, final double phi, final double angle, final double ax, final double ay, final double az)
static double Ylm (final int L, final int M, final double theta, final double phi)
static double Ylm (final int L, final int M, final double theta, final double phi, final double angle, final double ax, final double ay, final double az)
static double Ylm2 (final int L, final int M, final double theta, final double phi)
static double Ylm2 (final int L, final int M, final double theta, final double phi, final double angle, final double ax, final double ay, final double az)
Static Private Member Functions
static double[][] initNormalization ()
static double getNormalizationLUT (final int L, final int M)
static double getNormalization (final int L, final int M)
Detailed Description
Spherical harmonic functions and associated Legendre polynomials. Calculated using recurrence relations: https://en.wikipedia.org/wiki/Associated_Legendre_polynomials# Recurrence_formula
Member Function Documentation
static double wblut.math.WB_SphericalHarmonics.getNormalization (final int L, final int M) static private
static double wblut.math.WB_SphericalHarmonics.getNormalizationLUT (final int L, final int M) static private
References wblut.math.WB_SphericalHarmonics.getNormalization().
static double [][] wblut.math.WB_SphericalHarmonics.initNormalization () static private
References wblut.math.WB_SphericalHarmonics.getNormalization().
static double wblut.math.WB_SphericalHarmonics.Plm (final int L, final int M, final double x) static
Associated Legendre polynomial at x. Recurrence property:
Parameters
L Spherical harmonic order
M Spherical harmonic index
x
Returns
static WB_Coord wblut.math.WB_SphericalHarmonics.rotateSpherical (final double angle, final double ax, final double ay, final double az, final double theta, final double phi) static
References wblut.geom.WB_Vector.rotateAboutOriginSelf(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
static WB_Complex wblut.math.WB_SphericalHarmonics.Y (final int L, final int M, final double theta, final double phi) static
Complex spherical harmonic of order l, index m
Parameters
L spherical harmonic order.
M spherical harmonic index. -l<=m<=l
theta
phi
Returns
Y(theta, phi)
References wblut.math.WB_Complex.conjugate(), wblut.math.WB_SphericalHarmonics.getNormalizationLUT(), wblut.math.WB_Complex.mul(), wblut.math.WB_Complex.negate(), and wblut.math.WB_SphericalHarmonics.Plm().
static WB_Complex wblut.math.WB_SphericalHarmonics.Y (final int L, final int M, final double theta, final double phi, final double angle, final double ax, final double ay, final double az) static
References wblut.math.WB_SphericalHarmonics.rotateSpherical(), wblut.geom.WB_Coord.xd(), wblut.math.WB_SphericalHarmonics.Y(), and wblut.geom.WB_Coord.yd().
static double wblut.math.WB_SphericalHarmonics.Ylm (final int L, final int M, final double theta, final double phi) static
References wblut.math.WB_SphericalHarmonics.getNormalizationLUT(), and wblut.math.WB_SphericalHarmonics.Plm().
static double wblut.math.WB_SphericalHarmonics.Ylm (final int L, final int M, final double theta, final double phi, final double angle, final double ax, final double ay, final double az) static
References wblut.math.WB_SphericalHarmonics.rotateSpherical(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.math.WB_SphericalHarmonics.Ylm().
static double wblut.math.WB_SphericalHarmonics.Ylm2 (final int L, final int M, final double theta, final double phi) static
References wblut.math.WB_SphericalHarmonics.Ylm().
static double wblut.math.WB_SphericalHarmonics.Ylm2 (final int L, final int M, final double theta, final double phi, final double angle, final double ax, final double ay, final double az) static
References wblut.math.WB_SphericalHarmonics.rotateSpherical(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.math.WB_SphericalHarmonics.Ylm2().
The documentation for this class was generated from the following file:
src/math/wblut/math/WB_SphericalHarmonics.java