HE_Mesh: wblut.geom.WB_IsoSurfaceVOL Class Reference
wblut.geom.WB_IsoSurfaceVOL Class Reference
Public Member Functions
WB_IsoSurfaceVOL ()
WB_IsoSurfaceVOL setResolution (final int resx, final int resy, final int resz)
WB_IsoSurfaceVOL setSize (final double dx, final double dy, final double dz)
WB_IsoSurfaceVOL setValues (final double[][][] values)
WB_IsoSurfaceVOL setValues (final float[][][] values)
WB_IsoSurfaceVOL setValues (final WB_ScalarParameter function, final double xi, final double yi, final double zi, final double dx, final double dy, final double dz, final int sizeI, final int sizeJ, final int sizeK)
WB_IsoSurfaceVOL setValues (final WB_HashGridDouble values)
WB_IsoSurfaceVOL setIsolevel (final double isolevelmin, final double isolevelmax)
WB_IsoSurfaceVOL setCenter (final WB_Coord c)
List< WB_Tetrahedron > getTetrahedra ()
Private Member Functions
int index (final int i, final int j, final int k)
double value (final int i, final int j, final int k)
WB_Point vertex (final int i, final int j, final int k, final WB_Point offset)
WB_Point xedge (final int i, final int j, final int k, final WB_Point offset, final double isolevel)
WB_Point yedge (final int i, final int j, final int k, final WB_Point offset, final double isolevel)
WB_Point zedge (final int i, final int j, final int k, final WB_Point offset, final double isolevel)
WB_Point interp (final double isolevel, final WB_Point p1, final WB_Point p2, final double valp1, final double valp2)
int classifyCell (final int i, final int j, final int k)
void polygonise ()
void getPolygons (final int i, final int j, final int k, final int cubeindex, final WB_Point offset)
Private Attributes
WB_IsoValues3D values
int resx
double cx
double dx
double isolevelmin
IntObjectHashMap< WB_Point > xedges
IntObjectHashMap< WB_Point > yedges
IntObjectHashMap< WB_Point > zedges
IntObjectHashMap< WB_Point > vertices
List< WB_Tetrahedron > tetra
Constructor & Destructor Documentation
wblut.geom.WB_IsoSurfaceVOL.WB_IsoSurfaceVOL ()
Member Function Documentation
int wblut.geom.WB_IsoSurfaceVOL.classifyCell (final int i, final int j, final int k) private
Classify cell.
Parameters
i the i
j the j
k the k
Returns
the int
References wblut.geom.WB_IsoSurfaceVOL.value().
void wblut.geom.WB_IsoSurfaceVOL.getPolygons (final int i, final int j, final int k, final int cubeindex, final WB_Point offset) private
Gets the polygons.
Parameters
i the i
j the j
k the k
cubeindex the cubeindex
offset
Returns
the polygons
List<WB_Tetrahedron> wblut.geom.WB_IsoSurfaceVOL.getTetrahedra ()
References wblut.geom.WB_IsoSurfaceVOL.polygonise(), and wblut.geom.WB_IsoSurfaceVOL.tetra.
int wblut.geom.WB_IsoSurfaceVOL.index (final int i, final int j, final int k) private
Parameters
i
j
k
Returns
WB_Point wblut.geom.WB_IsoSurfaceVOL.interp (final double isolevel, final WB_Point p1, final WB_Point p2, final double valp1, final double valp2) private
Interp.
Parameters
isolevel the isolevel
p1 the p1
p2 the p2
valp1 the valp1
valp2 the valp2
Returns
the h e_ vertex
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_IsoSurfaceVOL.polygonise () private
Polygonise.
References wblut.geom.WB_IsoSurfaceVOL.classifyCell(), wblut.geom.WB_IsoSurfaceVOL.getPolygons(), and wblut.geom.WB_IsoSurfaceVOL.resx.
WB_IsoSurfaceVOL wblut.geom.WB_IsoSurfaceVOL.setCenter (final WB_Coord c)
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_IsoSurfaceVOL wblut.geom.WB_IsoSurfaceVOL.setIsolevel (final double isolevelmin, final double isolevelmax)
Parameters
isolevelmin
isolevelmax
Returns
References wblut.geom.WB_IsoSurfaceVOL.isolevelmin.
WB_IsoSurfaceVOL wblut.geom.WB_IsoSurfaceVOL.setResolution (final int resx, final int resy, final int resz)
Number of cells.
Parameters
resx the resx
resy the resy
resz the resz
Returns
self
References wblut.geom.WB_IsoSurfaceVOL.resx.
WB_IsoSurfaceVOL wblut.geom.WB_IsoSurfaceVOL.setSize (final double dx, final double dy, final double dz)
Size of cell.
Parameters
dx
dy
dz
Returns
self
References wblut.geom.WB_IsoSurfaceVOL.dx.
WB_IsoSurfaceVOL wblut.geom.WB_IsoSurfaceVOL.setValues (final double values[][][])
Values at grid points.
Parameters
values double[resx+1][resy+1][resz+1]
Returns
self
WB_IsoSurfaceVOL wblut.geom.WB_IsoSurfaceVOL.setValues (final float values[][][])
Sets the values.
Parameters
values float[resx+1][resy+1][resz+1]
Returns
self
WB_IsoSurfaceVOL wblut.geom.WB_IsoSurfaceVOL.setValues (final WB_ScalarParameter function, final double xi, final double yi, final double zi, final double dx, final double dy, final double dz, final int sizeI, final int sizeJ, final int sizeK)
Parameters
function
xi
yi
zi
dx
dy
dz
Returns
WB_IsoSurfaceVOL wblut.geom.WB_IsoSurfaceVOL.setValues (final WB_HashGridDouble values)
Parameters
values
Returns
References wblut.geom.WB_HashGridDouble.getSizeI(), wblut.geom.WB_HashGridDouble.getSizeJ(), and wblut.geom.WB_HashGridDouble.getSizeK().
double wblut.geom.WB_IsoSurfaceVOL.value (final int i, final int j, final int k) private
Value.
Parameters
i the i
j the j
k the k
Returns
the double
References wblut.geom.WB_IsoValues3D.getValue().
WB_Point wblut.geom.WB_IsoSurfaceVOL.vertex (final int i, final int j, final int k, final WB_Point offset) private
Parameters
i
j
k
offset
Returns
References wblut.geom.WB_Point.addSelf(), and wblut.geom.WB_IsoSurfaceVOL.index().
WB_Point wblut.geom.WB_IsoSurfaceVOL.xedge (final int i, final int j, final int k, final WB_Point offset, final double isolevel) private
Xedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
k k: -1 .. resz+1
offset
isolevel
Returns
edge vertex
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_IsoSurfaceVOL.index(), wblut.geom.WB_IsoSurfaceVOL.interp(), and wblut.geom.WB_IsoSurfaceVOL.value().
WB_Point wblut.geom.WB_IsoSurfaceVOL.yedge (final int i, final int j, final int k, final WB_Point offset, final double isolevel) private
Yedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
k k: -1 .. resz+1
offset
isolevel
Returns
edge vertex
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_IsoSurfaceVOL.index(), wblut.geom.WB_IsoSurfaceVOL.interp(), and wblut.geom.WB_IsoSurfaceVOL.value().
WB_Point wblut.geom.WB_IsoSurfaceVOL.zedge (final int i, final int j, final int k, final WB_Point offset, final double isolevel) private
Zedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
k k: -1 .. resz+1
offset
isolevel
Returns
edge vertex
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_IsoSurfaceVOL.index(), wblut.geom.WB_IsoSurfaceVOL.interp(), and wblut.geom.WB_IsoSurfaceVOL.value().
Member Data Documentation
double wblut.geom.WB_IsoSurfaceVOL.cx private
double wblut.geom.WB_IsoSurfaceVOL.dx private
double wblut.geom.WB_IsoSurfaceVOL.isolevelmin private
int wblut.geom.WB_IsoSurfaceVOL.resx private
List<WB_Tetrahedron> wblut.geom.WB_IsoSurfaceVOL.tetra private
WB_IsoValues3D wblut.geom.WB_IsoSurfaceVOL.values private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurfaceVOL.vertices private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurfaceVOL.xedges private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurfaceVOL.yedges private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurfaceVOL.zedges private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_IsoSurfaceVOL.java