HE_Mesh: wblut.hemesh.HES_CatmullClark Class Reference
wblut.hemesh.HES_CatmullClark Class Reference
Public Member Functions
HES_CatmullClark ()
HES_CatmullClark setKeepEdges (final boolean b)
HES_CatmullClark setKeepBoundary (final boolean b)
HES_CatmullClark setBlendFactor (final double f)
HES_CatmullClark setBlendFactor (final WB_ScalarParameter f)
Public Member Functions inherited from wblut.hemesh.HES_Subdividor
HES_Subdividor ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Static Public Member Functions
static void main (final String[] args)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HES_Subdividor
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
boolean keepEdges
boolean keepBoundary = false
WB_ScalarParameter blendFactor
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Catmull-Clark subdivision of a mesh.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HES_CatmullClark.HES_CatmullClark ()
Member Function Documentation
HE_Mesh wblut.hemesh.HES_CatmullClark.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HES_QuadSplit.applySelf(), wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.geom.WB_Point.divSelf(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Selection.getOuterVertices(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Mesh.resetVertexInternalLabels(), wblut.geom.WB_Point.scaleSelf(), wblut.hemesh.HE_Mesh.selectAllFaces(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setDuringStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Machine.tracker, wblut.hemesh.HE_Mesh.vItr(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), and wblut.hemesh.HE_Vertex.zd().
HE_Mesh wblut.hemesh.HES_CatmullClark.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HES_QuadSplit.applySelf(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Selection.contains(), wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.geom.WB_Point.divSelf(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Selection.getAllBoundaryVertices(), wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Selection.getInnerVertices(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Selection.getOuterVertices(), wblut.hemesh.HE_Face.getPlane(), wblut.hemesh.HE_Mesh.getSharedFaces(), wblut.geom.WB_GeometryOp3D.isEqual(), wblut.hemesh.HE_Mesh.resetVertexInternalLabels(), wblut.geom.WB_Point.scaleSelf(), wblut.geom.WB_MutableCoordinate.set(), wblut.hemesh.HE_Mesh.vItr(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), and wblut.hemesh.HE_Vertex.zd().
static void wblut.hemesh.HES_CatmullClark.main (final String[] args) static
References wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HEC_Cylinder.setCap(), wblut.hemesh.HEC_Creator.setCenter(), wblut.hemesh.HEC_Cylinder.setFacets(), wblut.hemesh.HEC_Cylinder.setHeight(), wblut.hemesh.HEC_Cylinder.setRadius(), wblut.hemesh.HEC_Cylinder.setSteps(), wblut.hemesh.HE_Mesh.smooth(), and wblut.hemesh.HE_Mesh.validate().
HES_CatmullClark wblut.hemesh.HES_CatmullClark.setBlendFactor (final double f)
Sets the blend factor.
Parameters
f the f
Returns
the hE s_ catmull clark
HES_CatmullClark wblut.hemesh.HES_CatmullClark.setBlendFactor (final WB_ScalarParameter f)
Sets the blend factor.
Parameters
f the f
Returns
the hE s_ catmull clark
HES_CatmullClark wblut.hemesh.HES_CatmullClark.setKeepBoundary (final boolean b)
Keep boundary edges fixed?.
Parameters
b true/false
Returns
self
HES_CatmullClark wblut.hemesh.HES_CatmullClark.setKeepEdges (final boolean b)
Keep edges of selection fixed when subdividing selection?.
Parameters
b true/false
Returns
self
Member Data Documentation
WB_ScalarParameter wblut.hemesh.HES_CatmullClark.blendFactor private
The blend factor.
WB_GeometryFactory wblut.hemesh.HES_CatmullClark.gf = new WB_GeometryFactory() static private
boolean wblut.hemesh.HES_CatmullClark.keepBoundary = false private
Keep boundary?.
boolean wblut.hemesh.HES_CatmullClark.keepEdges private
Keep edges?.
The documentation for this class was generated from the following file:
src/hemesh_subdividors/wblut/hemesh/HES_CatmullClark.java