HE_Mesh: wblut.geom.WB_QuadtreeInteger Class Reference
wblut.geom.WB_QuadtreeInteger Class Reference
Classes
class WB_QuadtreeIntegerEntry
Public Member Functions
WB_QuadtreeInteger (final WB_Coord center, final double size)
void addPoint (final WB_Coord p, final int value)
void addAll (final Collection<?extends WB_Coord > points)
void clear ()
int getLevel ()
WB_QuadtreeInteger getNode (final WB_Coord p)
double getMinNodeSize ()
int getNumNodes ()
WB_Coord getCenter ()
WB_QuadtreeInteger getParent ()
int getNumberOfPoints ()
List< WB_QuadtreeInteger > getNodes ()
double getSize ()
boolean remove (final WB_Coord p)
void removeAll (final Collection< WB_Coord > points)
void setMinNodeSize (final double minNodeSize)
void setAutoPrune (final boolean state)
WB_AABB2D getBox ()
List< WB_QuadtreeIntegerEntry > getEntries ()
List< WB_QuadtreeIntegerEntry > getEntriesInRange (final WB_AABB2D AABB)
List< WB_QuadtreeIntegerEntry > getEntriesInRange (final WB_Circle circle)
List< WB_QuadtreeIntegerEntry > getEntriesInRange (final WB_Coord center, final double radius)
List< WB_Coord > getPoints ()
List< WB_Coord > getPointsInRange (final WB_AABB2D AABB)
List< WB_Coord > getPointsInRange (final WB_Circle circle)
List< WB_Coord > getPointsInRange (final WB_Coord center, final double radius)
int[] getValues ()
int[] getValuesInRange (final WB_AABB2D AABB)
int[] getValuesInRange (final WB_Circle circle)
int[] getValuesInRange (final WB_Coord center, final double radius)
Static Public Member Functions
static void main (final String[] args)
Protected Member Functions
final int getQuadrant (final WB_Coord p)
Protected Attributes
WB_AABB2D box
WB_Coord extent
WB_Coord min
double minNodeSize = 4.0
WB_QuadtreeInteger parent
WB_QuadtreeInteger[] nodes
int numNodes
List< WB_QuadtreeIntegerEntry > entries
double size
WB_Coord center
Private Member Functions
WB_QuadtreeInteger (final WB_QuadtreeInteger p, final WB_Coord center, final double size)
void prune ()
Private Attributes
int level = 0
boolean autoPrune = false
Constructor & Destructor Documentation
wblut.geom.WB_QuadtreeInteger.WB_QuadtreeInteger (final WB_QuadtreeInteger p, final WB_Coord center, final double size) private
References wblut.geom.WB_QuadtreeInteger.size, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
wblut.geom.WB_QuadtreeInteger.WB_QuadtreeInteger (final WB_Coord center, final double size)
References wblut.geom.WB_QuadtreeInteger.size, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
Member Function Documentation
void wblut.geom.WB_QuadtreeInteger.addAll (final Collection<?extends WB_Coord > points)
References wblut.geom.WB_QuadtreeInteger.addPoint().
void wblut.geom.WB_QuadtreeInteger.addPoint (final WB_Coord p, final int value)
References wblut.geom.WB_Point.add(), wblut.geom.WB_QuadtreeInteger.addPoint(), wblut.geom.WB_AABB2D.contains(), wblut.geom.WB_QuadtreeInteger.getQuadrant(), and wblut.geom.WB_QuadtreeInteger.WB_QuadtreeInteger().
void wblut.geom.WB_QuadtreeInteger.clear ()
WB_AABB2D wblut.geom.WB_QuadtreeInteger.getBox ()
References wblut.geom.WB_QuadtreeInteger.box.
WB_Coord wblut.geom.WB_QuadtreeInteger.getCenter ()
References wblut.geom.WB_QuadtreeInteger.center.
List<WB_QuadtreeIntegerEntry> wblut.geom.WB_QuadtreeInteger.getEntries ()
References wblut.geom.WB_QuadtreeInteger.getEntries().
List<WB_QuadtreeIntegerEntry> wblut.geom.WB_QuadtreeInteger.getEntriesInRange (final WB_AABB2D AABB)
References wblut.geom.WB_AABB2D.contains(), wblut.geom.WB_QuadtreeInteger.getEntriesInRange(), and wblut.geom.WB_AABB2D.intersects().
List<WB_QuadtreeIntegerEntry> wblut.geom.WB_QuadtreeInteger.getEntriesInRange (final WB_Circle circle)
References wblut.geom.WB_Circle.contains(), wblut.geom.WB_QuadtreeInteger.getEntriesInRange(), and wblut.geom.WB_AABB2D.intersects().
List<WB_QuadtreeIntegerEntry> wblut.geom.WB_QuadtreeInteger.getEntriesInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_QuadtreeInteger.getEntriesInRange().
int wblut.geom.WB_QuadtreeInteger.getLevel ()
References wblut.geom.WB_QuadtreeInteger.level.
double wblut.geom.WB_QuadtreeInteger.getMinNodeSize ()
References wblut.geom.WB_QuadtreeInteger.minNodeSize.
WB_QuadtreeInteger wblut.geom.WB_QuadtreeInteger.getNode (final WB_Coord p)
References wblut.geom.WB_AABB2D.contains(), wblut.geom.WB_QuadtreeInteger.getNode(), and wblut.geom.WB_QuadtreeInteger.getQuadrant().
List<WB_QuadtreeInteger> wblut.geom.WB_QuadtreeInteger.getNodes ()
int wblut.geom.WB_QuadtreeInteger.getNumberOfPoints ()
int wblut.geom.WB_QuadtreeInteger.getNumNodes ()
References wblut.geom.WB_QuadtreeInteger.numNodes.
WB_QuadtreeInteger wblut.geom.WB_QuadtreeInteger.getParent ()
References wblut.geom.WB_QuadtreeInteger.parent.
List<WB_Coord> wblut.geom.WB_QuadtreeInteger.getPoints ()
References wblut.geom.WB_QuadtreeInteger.getPoints().
List<WB_Coord> wblut.geom.WB_QuadtreeInteger.getPointsInRange (final WB_AABB2D AABB)
References wblut.geom.WB_QuadtreeInteger.getEntriesInRange().
List<WB_Coord> wblut.geom.WB_QuadtreeInteger.getPointsInRange (final WB_Circle circle)
References wblut.geom.WB_QuadtreeInteger.getEntriesInRange().
List<WB_Coord> wblut.geom.WB_QuadtreeInteger.getPointsInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_QuadtreeInteger.getPointsInRange().
final int wblut.geom.WB_QuadtreeInteger.getQuadrant (final WB_Coord p) protected
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_QuadtreeInteger.getSize ()
References wblut.geom.WB_QuadtreeInteger.size.
int [] wblut.geom.WB_QuadtreeInteger.getValues ()
References wblut.geom.WB_QuadtreeInteger.getEntries().
int [] wblut.geom.WB_QuadtreeInteger.getValuesInRange (final WB_AABB2D AABB)
References wblut.geom.WB_QuadtreeInteger.getEntriesInRange().
int [] wblut.geom.WB_QuadtreeInteger.getValuesInRange (final WB_Circle circle)
References wblut.geom.WB_QuadtreeInteger.getEntriesInRange().
int [] wblut.geom.WB_QuadtreeInteger.getValuesInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_QuadtreeInteger.getValuesInRange().
static void wblut.geom.WB_QuadtreeInteger.main (final String[] args) static
References wblut.geom.WB_QuadtreeInteger.addAll(), wblut.geom.WB_QuadtreeInteger.getPointsInRange(), wblut.geom.WB_RandomRectangle.setOffset(), wblut.geom.WB_RandomRectangle.setSize(), and wblut.geom.WB_QuadtreeInteger.WB_QuadtreeInteger().
void wblut.geom.WB_QuadtreeInteger.prune () private
References wblut.geom.WB_QuadtreeInteger.prune().
boolean wblut.geom.WB_QuadtreeInteger.remove (final WB_Coord p)
References wblut.geom.WB_QuadtreeInteger.WB_QuadtreeIntegerEntry.coord, wblut.geom.WB_QuadtreeInteger.entries, wblut.geom.WB_QuadtreeInteger.getNode(), and wblut.geom.WB_QuadtreeInteger.prune().
void wblut.geom.WB_QuadtreeInteger.removeAll (final Collection< WB_Coord > points)
void wblut.geom.WB_QuadtreeInteger.setAutoPrune (final boolean state)
void wblut.geom.WB_QuadtreeInteger.setMinNodeSize (final double minNodeSize)
Member Data Documentation
boolean wblut.geom.WB_QuadtreeInteger.autoPrune = false private
WB_AABB2D wblut.geom.WB_QuadtreeInteger.box protected
WB_Coord wblut.geom.WB_QuadtreeInteger.center protected
List<WB_QuadtreeIntegerEntry> wblut.geom.WB_QuadtreeInteger.entries protected
WB_Coord wblut.geom.WB_QuadtreeInteger.extent protected
int wblut.geom.WB_QuadtreeInteger.level = 0 private
WB_Coord wblut.geom.WB_QuadtreeInteger.min protected
double wblut.geom.WB_QuadtreeInteger.minNodeSize = 4.0 protected
WB_QuadtreeInteger [] wblut.geom.WB_QuadtreeInteger.nodes protected
int wblut.geom.WB_QuadtreeInteger.numNodes protected
WB_QuadtreeInteger wblut.geom.WB_QuadtreeInteger.parent protected
double wblut.geom.WB_QuadtreeInteger.size protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_QuadtreeInteger.java