HE_Mesh: wblut.geom.WB_TransformMap Class Reference
wblut.geom.WB_TransformMap Class Reference
Public Member Functions
WB_TransformMap (final WB_Transform transform)
void mapPoint3D (final WB_Coord p, final WB_MutableCoord result)
void mapPoint3D (final double x, final double y, final double z, final WB_MutableCoord result)
void unmapPoint3D (final WB_Coord p, final WB_MutableCoord result)
void unmapPoint3D (final double u, final double v, final double w, final WB_MutableCoord result)
void mapVector3D (final WB_Coord p, final WB_MutableCoord result)
void mapVector3D (final double x, final double y, final double z, final WB_MutableCoord result)
void unmapVector3D (final WB_Coord p, final WB_MutableCoord result)
void unmapVector3D (final double u, final double v, final double w, final WB_MutableCoord result)
WB_Point mapPoint3D (final WB_Coord p)
WB_Point mapPoint3D (final double x, final double y, final double z)
WB_Point unmapPoint3D (final WB_Coord p)
WB_Point unmapPoint3D (final double u, final double v, final double w)
WB_Vector mapVector3D (final WB_Coord p)
WB_Vector mapVector3D (final double x, final double y, final double z)
WB_Vector unmapVector3D (final WB_Coord p)
WB_Vector unmapVector3D (final double u, final double v, final double w)
Public Member Functions inherited from wblut.geom.WB_Map
void mapPoint3D (WB_Coord p, WB_MutableCoord result)
void mapPoint3D (double x, double y, double z, WB_MutableCoord result)
void unmapPoint3D (WB_Coord p, WB_MutableCoord result)
void unmapPoint3D (double u, double v, double w, WB_MutableCoord result)
void mapVector3D (WB_Coord p, WB_MutableCoord result)
void mapVector3D (double x, double y, double z, WB_MutableCoord result)
void unmapVector3D (WB_Coord p, WB_MutableCoord result)
void unmapVector3D (double u, double v, double w, WB_MutableCoord result)
WB_Coord mapPoint3D (WB_Coord p)
WB_Coord mapPoint3D (double x, double y, double z)
WB_Coord unmapPoint3D (WB_Coord p)
WB_Coord unmapPoint3D (double u, double v, double w)
WB_Coord mapVector3D (WB_Coord p)
WB_Coord mapVector3D (double x, double y, double z)
WB_Coord unmapVector3D (WB_Coord p)
WB_Coord unmapVector3D (double u, double v, double w)
Private Attributes
WB_Transform T
WB_Transform invT
Constructor & Destructor Documentation
wblut.geom.WB_TransformMap.WB_TransformMap (final WB_Transform transform)
Parameters
transform
References wblut.geom.WB_Transform.get(), and wblut.geom.WB_Transform.inverse().
Member Function Documentation
void wblut.geom.WB_TransformMap.mapPoint3D (final WB_Coord p, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsPointInto().
void wblut.geom.WB_TransformMap.mapPoint3D (final double x, final double y, final double z, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsPointInto().
WB_Point wblut.geom.WB_TransformMap.mapPoint3D (final WB_Coord p)
References wblut.geom.WB_Transform.applyAsPoint().
WB_Point wblut.geom.WB_TransformMap.mapPoint3D (final double x, final double y, final double z)
References wblut.geom.WB_Transform.applyAsPoint().
void wblut.geom.WB_TransformMap.mapVector3D (final WB_Coord p, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsVectorInto().
void wblut.geom.WB_TransformMap.mapVector3D (final double x, final double y, final double z, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsVectorInto().
WB_Vector wblut.geom.WB_TransformMap.mapVector3D (final WB_Coord p)
References wblut.geom.WB_Transform.applyAsVector().
WB_Vector wblut.geom.WB_TransformMap.mapVector3D (final double x, final double y, final double z)
References wblut.geom.WB_Transform.applyAsVector().
void wblut.geom.WB_TransformMap.unmapPoint3D (final WB_Coord p, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsPointInto().
void wblut.geom.WB_TransformMap.unmapPoint3D (final double u, final double v, final double w, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsPointInto().
WB_Point wblut.geom.WB_TransformMap.unmapPoint3D (final WB_Coord p)
References wblut.geom.WB_Transform.applyAsPoint().
WB_Point wblut.geom.WB_TransformMap.unmapPoint3D (final double u, final double v, final double w)
References wblut.geom.WB_Transform.applyAsPoint().
void wblut.geom.WB_TransformMap.unmapVector3D (final WB_Coord p, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsVectorInto().
void wblut.geom.WB_TransformMap.unmapVector3D (final double u, final double v, final double w, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsVectorInto().
WB_Vector wblut.geom.WB_TransformMap.unmapVector3D (final WB_Coord p)
References wblut.geom.WB_Transform.applyAsVector().
WB_Vector wblut.geom.WB_TransformMap.unmapVector3D (final double u, final double v, final double w)
References wblut.geom.WB_Transform.applyAsVector().
Member Data Documentation
WB_Transform wblut.geom.WB_TransformMap.invT private
WB_Transform wblut.geom.WB_TransformMap.T private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_TransformMap.java