HE_Mesh: wblut.geom.WB_AABBTree2D Class Reference
wblut.geom.WB_AABBTree2D Class Reference
Classes
class Entry
class EntryOrder
class WB_AABBNode2D
Public Member Functions
WB_AABBTree2D (final Collection<?extends WB_Triangle > mesh, final int mnof)
WB_AABBTree2D (final int[] triangles, final WB_CoordCollection points, final int mnof)
WB_AABBNode2D getRoot ()
int getDepth ()
WB_Coord getClosestPoint (final WB_Coord p)
WB_Triangle getClosestFace (final WB_Coord p)
Entry getClosestEntry (final WB_Coord p)
void expandBy (final double d)
Static Public Attributes
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Private Member Functions
void buildTree (final Collection<?extends WB_Triangle > mesh)
void buildTree (final int[] triangles, final WB_CoordCollection points)
void buildNode (final WB_AABBNode2D node, final List< WB_Triangle > faces, final Collection<?extends WB_Triangle > mesh, final int level)
double findOptimalSubset (double bestSah, final WB_AABBNode2D node, final List< WB_Triangle > childA, final List< WB_Triangle > childB, final List< WB_Triangle > faces)
double addNode (final WB_Coord p, final WB_AABBNode2D node, final PriorityQueue< Entry > entries, double closest2)
Static Private Member Functions
static double getSAH (final double denom, final double surfaceAreaA, final int numA, final double surfaceAreaB, final int numB)
Private Attributes
WB_AABBNode2D root
final int maxLevel
int depth
final int maxNumberOfFaces
Constructor & Destructor Documentation
wblut.geom.WB_AABBTree2D.WB_AABBTree2D (final Collection<?extends WB_Triangle > mesh, final int mnof)
Parameters
mesh
mnof
References wblut.geom.WB_AABBTree2D.buildTree().
wblut.geom.WB_AABBTree2D.WB_AABBTree2D (final int[] triangles, final WB_CoordCollection points, final int mnof)
References wblut.geom.WB_AABBTree2D.buildTree().
Member Function Documentation
double wblut.geom.WB_AABBTree2D.addNode (final WB_Coord p, final WB_AABBNode2D node, final PriorityQueue< Entry > entries, double closest2) private
References wblut.geom.WB_AABBTree2D.WB_AABBNode2D.aabb, wblut.geom.WB_AABBTree2D.WB_AABBNode2D.faces, wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), wblut.geom.WB_GeometryOp2D.getSqDistance2D(), and wblut.geom.WB_AABBTree2D.WB_AABBNode2D.isLeaf.
void wblut.geom.WB_AABBTree2D.buildNode (final WB_AABBNode2D node, final List< WB_Triangle > faces, final Collection<?extends WB_Triangle > mesh, final int level) private
Parameters
node
faces
mesh
level
References wblut.geom.WB_AABBTree2D.WB_AABBNode2D.aabb, wblut.geom.WB_AABBTree2D.WB_AABBNode2D.childA, wblut.geom.WB_AABBTree2D.WB_AABBNode2D.childB, wblut.geom.WB_AABB2D.expandToInclude(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.faces, wblut.geom.WB_AABBTree2D.findOptimalSubset(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.isLeaf, wblut.geom.WB_AABBTree2D.WB_AABBNode2D.level, wblut.geom.WB_AABBTree2D.maxNumberOfFaces, and wblut.core.WB_ProgressReporter.WB_ProgressTracker.setDuringStatus().
void wblut.geom.WB_AABBTree2D.buildTree (final Collection<?extends WB_Triangle > mesh) private
Parameters
mesh
References wblut.geom.WB_AABBTree2D.buildNode(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), and wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus().
void wblut.geom.WB_AABBTree2D.buildTree (final int[] triangles, final WB_CoordCollection points) private
References wblut.geom.WB_AABBTree2D.buildNode(), wblut.geom.WB_CoordCollection.get(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), and wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus().
void wblut.geom.WB_AABBTree2D.expandBy (final double d)
References wblut.geom.WB_AABBTree2D.WB_AABBNode2D.expandBy().
double wblut.geom.WB_AABBTree2D.findOptimalSubset (double bestSah, final WB_AABBNode2D node, final List< WB_Triangle > childA, final List< WB_Triangle > childB, final List< WB_Triangle > faces) private
References wblut.geom.WB_AABB.expandToInclude(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getAABB(), wblut.geom.WB_AABB2D.getArea(), wblut.geom.WB_AABB.getArea(), and wblut.geom.WB_AABBTree2D.getSAH().
Entry wblut.geom.WB_AABBTree2D.getClosestEntry (final WB_Coord p)
References wblut.geom.WB_AABBTree2D.addNode(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getChildA(), and wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getChildB().
WB_Triangle wblut.geom.WB_AABBTree2D.getClosestFace (final WB_Coord p)
References wblut.geom.WB_AABBTree2D.addNode(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getChildA(), and wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getChildB().
WB_Coord wblut.geom.WB_AABBTree2D.getClosestPoint (final WB_Coord p)
References wblut.geom.WB_AABBTree2D.addNode(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getChildA(), and wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getChildB().
int wblut.geom.WB_AABBTree2D.getDepth ()
References wblut.geom.WB_AABBTree2D.depth.
WB_AABBNode2D wblut.geom.WB_AABBTree2D.getRoot ()
Returns
References wblut.geom.WB_AABBTree2D.root.
static double wblut.geom.WB_AABBTree2D.getSAH (final double denom, final double surfaceAreaA, final int numA, final double surfaceAreaB, final int numB) static private
Surface area heuristic
Parameters
denom
surfaceAreaA
numA
surfaceAreaB
numB
Returns
Member Data Documentation
int wblut.geom.WB_AABBTree2D.depth private
final int wblut.geom.WB_AABBTree2D.maxLevel private
final int wblut.geom.WB_AABBTree2D.maxNumberOfFaces private
WB_AABBNode2D wblut.geom.WB_AABBTree2D.root private
final WB_ProgressTracker wblut.geom.WB_AABBTree2D.tracker = WB_ProgressTracker.instance() static
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_AABBTree2D.java