HE_Mesh: wblut.geom.WB_Network Class Reference
wblut.geom.WB_Network Class Reference
Classes
class Connection
class Node
Public Member Functions
WB_Network ()
WB_Network (final WB_Coord[] points, final WB_IndexedSegment[] connections)
WB_Network (final WB_Coord[] points, final Collection< WB_IndexedSegment > connections)
void add (final WB_Coord[] points, final Collection< WB_IndexedSegment > connections)
void add (final WB_Network frame)
WB_Network (final Collection<?extends WB_Coord > points, final Collection< WB_IndexedSegment > connections)
WB_Network (final WB_Coord[] points, final int[][] connections)
WB_Network (final Collection<?extends WB_Coord > points, final int[][] connections)
WB_Network (final double[][] points, final int[][] connections)
WB_Network (final float[][] points, final int[][] connections)
WB_Network (final int[][] points, final int[][] connections)
WB_Network (final WB_Coord[] points)
WB_Network (final Collection<?extends WB_Coord > points)
WB_Network (final double[][] points)
WB_Network (final float[][] points)
WB_Network (final int[][] points)
int addNode (final double x, final double y, final double z, final double v)
int addNode (final WB_Coord pos, final double v)
void removeNode (final Node node)
int addNodes (final Collection< WB_Coord > pos)
boolean addConnection (final int i, final int j)
void removeConnection (final Connection connection)
List< Connection > getConnections ()
List< WB_Segment > getSegments ()
List< WB_IndexedSegment > getIndexedSegments ()
int getNumberOfConnections ()
List< Node > getNodes ()
List< WB_Point > getPoints ()
WB_Point[] getPointsAsArray ()
int getNumberOfNodes ()
Node getNode (final int i)
Connection getConnection (final int i)
double getDistanceToConnection (final WB_Coord p)
int getClosestNodeOnConnection (final WB_Coord p)
WB_Coord getClosestPointOnConnection (final WB_Coord p)
double getDistanceToConnection (final double x, final double y, final double z)
WB_Coord getClosestPointOnConnection (final double x, final double y, final double z)
WB_Network smoothBiNodes ()
WB_Network smoothBiNodes (final int r)
WB_Network smoothNodes ()
WB_Network smoothNodes (final int r)
WB_Network refine (final double threshold)
WB_Network refineOnePass (final double threshold)
List< WB_Point > toPointCloud (final int n, final double r, final double d, final int l, final double rr, final double dr)
Private Attributes
List< Connection > connections
List< Node > nodes
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.geom.WB_Network.WB_Network ()
wblut.geom.WB_Network.WB_Network (final WB_Coord[] points, final WB_IndexedSegment[] connections)
Parameters
points
connections
References wblut.geom.WB_Network.addConnection(), and wblut.geom.WB_Network.addNode().
wblut.geom.WB_Network.WB_Network (final WB_Coord[] points, final Collection< WB_IndexedSegment > connections)
Parameters
points
connections
References wblut.geom.WB_Network.addConnection(), and wblut.geom.WB_Network.addNode().
wblut.geom.WB_Network.WB_Network (final Collection<?extends WB_Coord > points, final Collection< WB_IndexedSegment > connections)
Parameters
points
connections
References wblut.geom.WB_Network.addConnection(), and wblut.geom.WB_Network.addNode().
wblut.geom.WB_Network.WB_Network (final WB_Coord[] points, final int connections[][])
Parameters
points
connections
References wblut.geom.WB_Network.addConnection(), and wblut.geom.WB_Network.addNode().
wblut.geom.WB_Network.WB_Network (final Collection<?extends WB_Coord > points, final int connections[][])
Parameters
points
connections
References wblut.geom.WB_Network.addConnection(), and wblut.geom.WB_Network.addNode().
wblut.geom.WB_Network.WB_Network (final double points[][], final int connections[][])
Parameters
points
connections
References wblut.geom.WB_Network.addConnection(), and wblut.geom.WB_Network.addNode().
wblut.geom.WB_Network.WB_Network (final float points[][], final int connections[][])
Parameters
points
connections
References wblut.geom.WB_Network.addConnection(), and wblut.geom.WB_Network.addNode().
wblut.geom.WB_Network.WB_Network (final int points[][], final int connections[][])
Parameters
points
connections
References wblut.geom.WB_Network.addConnection(), and wblut.geom.WB_Network.addNode().
wblut.geom.WB_Network.WB_Network (final WB_Coord[] points)
Parameters
points
References wblut.geom.WB_Network.addNode().
wblut.geom.WB_Network.WB_Network (final Collection<?extends WB_Coord > points)
Parameters
points
References wblut.geom.WB_Network.addNode().
wblut.geom.WB_Network.WB_Network (final double points[][])
Parameters
points
References wblut.geom.WB_Network.addNode().
wblut.geom.WB_Network.WB_Network (final float points[][])
Parameters
points
References wblut.geom.WB_Network.addNode().
wblut.geom.WB_Network.WB_Network (final int points[][])
Parameters
points
References wblut.geom.WB_Network.addNode().
Member Function Documentation
void wblut.geom.WB_Network.add (final WB_Coord[] points, final Collection< WB_IndexedSegment > connections)
Parameters
points
connections
References wblut.geom.WB_Network.addConnection(), and wblut.geom.WB_Network.addNode().
void wblut.geom.WB_Network.add (final WB_Network frame)
Parameters
frame
References wblut.geom.WB_Network.addConnection(), wblut.geom.WB_Network.addNode(), wblut.geom.WB_Network.getIndexedSegments(), wblut.geom.WB_Network.Node.getValue(), and wblut.geom.WB_Network.nodes.
boolean wblut.geom.WB_Network.addConnection (final int i, final int j)
Parameters
i
j
Returns
int wblut.geom.WB_Network.addNode (final double x, final double y, final double z, final double v)
Parameters
x
y
z
v
Returns
int wblut.geom.WB_Network.addNode (final WB_Coord pos, final double v)
Parameters
pos
v
Returns
int wblut.geom.WB_Network.addNodes (final Collection< WB_Coord > pos)
Parameters
pos
Returns
int wblut.geom.WB_Network.getClosestNodeOnConnection (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp3D.getSqDistance3D().
WB_Coord wblut.geom.WB_Network.getClosestPointOnConnection (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_Network.Connection.end, wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.geom.WB_GeometryOp3D.getDistance3D(), and wblut.geom.WB_Network.Connection.start.
WB_Coord wblut.geom.WB_Network.getClosestPointOnConnection (final double x, final double y, final double z)
Parameters
x
y
z
Returns
References wblut.geom.WB_Network.Connection.end, wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.geom.WB_GeometryOp3D.getDistance3D(), and wblut.geom.WB_Network.Connection.start.
Connection wblut.geom.WB_Network.getConnection (final int i)
Parameters
i
Returns
List<Connection> wblut.geom.WB_Network.getConnections ()
Returns
double wblut.geom.WB_Network.getDistanceToConnection (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_Network.Connection.end, wblut.geom.WB_GeometryOp3D.getDistance3D(), and wblut.geom.WB_Network.Connection.start.
double wblut.geom.WB_Network.getDistanceToConnection (final double x, final double y, final double z)
Parameters
x
y
z
Returns
References wblut.geom.WB_Network.Connection.end, wblut.geom.WB_GeometryOp3D.getDistance3D(), and wblut.geom.WB_Network.Connection.start.
List<WB_IndexedSegment> wblut.geom.WB_Network.getIndexedSegments ()
Returns
References wblut.geom.WB_Point.add(), and wblut.geom.WB_Network.getPoints().
Node wblut.geom.WB_Network.getNode (final int i)
Parameters
i
Returns
List<Node> wblut.geom.WB_Network.getNodes ()
Returns
int wblut.geom.WB_Network.getNumberOfConnections ()
Returns
int wblut.geom.WB_Network.getNumberOfNodes ()
Returns
List<WB_Point> wblut.geom.WB_Network.getPoints ()
Returns
WB_Point [] wblut.geom.WB_Network.getPointsAsArray ()
Returns
References wblut.geom.WB_Network.getPoints().
List<WB_Segment> wblut.geom.WB_Network.getSegments ()
Returns
WB_Network wblut.geom.WB_Network.refine (final double threshold)
References wblut.geom.WB_Network.getNumberOfNodes(), wblut.geom.WB_Network.refine(), and wblut.geom.WB_Network.refineOnePass().
WB_Network wblut.geom.WB_Network.refineOnePass (final double threshold)
Parameters
threshold
Returns
References wblut.geom.WB_Network.addConnection(), wblut.geom.WB_Network.addNode(), wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.geom.WB_Network.getNumberOfNodes(), and wblut.geom.WB_Network.WB_Network().
void wblut.geom.WB_Network.removeConnection (final Connection connection)
Parameters
connection
References wblut.geom.WB_Network.Connection.getEndIndex(), and wblut.geom.WB_Network.Connection.getStartIndex().
void wblut.geom.WB_Network.removeNode (final Node node)
Parameters
node
References wblut.geom.WB_Network.Node.getConnections(), and wblut.geom.WB_Network.removeConnection().
WB_Network wblut.geom.WB_Network.smoothBiNodes ()
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.mulSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_Network wblut.geom.WB_Network.smoothBiNodes (final int r)
References wblut.geom.WB_Network.smoothBiNodes().
WB_Network wblut.geom.WB_Network.smoothNodes ()
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.mulSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_Network wblut.geom.WB_Network.smoothNodes (final int r)
References wblut.geom.WB_Network.smoothNodes().
List<WB_Point> wblut.geom.WB_Network.toPointCloud (final int n, final double r, final double d, final int l, final double rr, final double dr)
Parameters
n
r
d
l
rr
dr
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_Vector.addMul(), wblut.geom.WB_Point.addMul(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Vector.copy(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Plane.getU(), wblut.hemesh.HE_Mesh.getVerticesAsCoord(), wblut.math.WB_Math.max(), wblut.geom.WB_Vector.mul(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_RandomOnSphere.nextVector(), and wblut.geom.WB_Vector.rotateAboutAxisSelf().
Member Data Documentation
List<Connection> wblut.geom.WB_Network.connections private
WB_GeometryFactory wblut.geom.WB_Network.gf = new WB_GeometryFactory() static private
List<Node> wblut.geom.WB_Network.nodes private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Network.java