HE_Mesh: wblut.core.WB_ProgressReporter Class Reference
wblut.core.WB_ProgressReporter Class Reference
Classes
class WB_ProgressCounter
class WB_ProgressStatus
class WB_ProgressTracker
Public Member Functions
WB_ProgressReporter (final String path)
WB_ProgressReporter (final int depth, final int consoleDepth, final String path)
WB_ProgressReporter (final int depth, final String path, final boolean append)
void start ()
void run ()
Detailed Description
Output log to file and console
Author
FVH
Constructor & Destructor Documentation
wblut.core.WB_ProgressReporter.WB_ProgressReporter (final String path)
wblut.core.WB_ProgressReporter.WB_ProgressReporter (final int depth, final int consoleDepth, final String path)
wblut.core.WB_ProgressReporter.WB_ProgressReporter (final int depth, final String path, final boolean append)
References wblut.core.WB_ProgressReporter.WB_ProgressTracker.instance(), and wblut.core.WB_ProgressReporter.WB_ProgressTracker.setMaxLevel().
Member Function Documentation
void wblut.core.WB_ProgressReporter.run ()
References wblut.core.WB_ProgressReporter.WB_ProgressTracker.getStatus(), and wblut.core.WB_ProgressReporter.WB_ProgressTracker.isUpdated().
void wblut.core.WB_ProgressReporter.start ()
The documentation for this class was generated from the following file:
src/core/wblut/core/WB_ProgressReporter.java