HE_Mesh: wblut.geom.WB_Frame Class Reference
wblut.geom.WB_Frame Class Reference
Classes
class WB_FrameNode
class WB_FrameStrut
Public Member Functions
WB_Frame ()
WB_Frame (final WB_Coord[] points, final WB_IndexedSegment[] connections)
WB_Frame (final WB_Coord[] points, final Collection< WB_IndexedSegment > connections)
void add (final WB_Coord[] points, final Collection< WB_IndexedSegment > connections)
void add (final WB_Frame frame)
WB_Frame (final Collection<?extends WB_Coord > points, final Collection< WB_IndexedSegment > connections)
WB_Frame (final WB_Coord[] points, final int[][] connections)
WB_Frame (final Collection<?extends WB_Coord > points, final int[][] connections)
WB_Frame (final double[][] points, final int[][] connections)
WB_Frame (final float[][] points, final int[][] connections)
WB_Frame (final int[][] points, final int[][] connections)
WB_Frame (final WB_Coord[] points)
WB_Frame (final Collection<?extends WB_Coord > points)
WB_Frame (final double[][] points)
WB_Frame (final float[][] points)
WB_Frame (final int[][] points)
int addNode (final double x, final double y, final double z, final double v)
int addNode (final WB_Coord pos, final double v)
void removeNode (final WB_FrameNode node)
int addNodes (final Collection< WB_Coord > pos)
boolean addStrut (final int i, final int j)
void removeStrut (final WB_FrameStrut strut)
ArrayList< WB_FrameStrut > getStruts ()
ArrayList< WB_Segment > getSegments ()
ArrayList< WB_IndexedSegment > getIndexedSegments ()
int getNumberOfStruts ()
ArrayList< WB_FrameNode > getNodes ()
ArrayList< WB_Point > getPoints ()
WB_Point[] getPointsAsArray ()
int getNumberOfNodes ()
WB_FrameNode getNode (final int i)
WB_FrameStrut getStrut (final int i)
double getDistanceToFrame (final WB_Coord p)
int getClosestNodeOnFrame (final WB_Coord p)
WB_Coord getClosestPointOnFrame (final WB_Coord p)
double getDistanceToFrame (final double x, final double y, final double z)
WB_Coord getClosestPointOnFrame (final double x, final double y, final double z)
WB_Frame smoothBiNodes ()
WB_Frame smoothBiNodes (final int r)
WB_Frame smoothNodes ()
WB_Frame smoothNodes (final int r)
WB_Frame refine (final double threshold)
WB_Frame refineOnePass (final double threshold)
List< WB_Point > toPointCloud (final int n, final double r, final double d, final int l, final double rr, final double dr)
Protected Attributes
FastList< WB_FrameStrut > struts
FastList< WB_FrameNode > nodes
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.geom.WB_Frame.WB_Frame ()
wblut.geom.WB_Frame.WB_Frame (final WB_Coord[] points, final WB_IndexedSegment[] connections)
Parameters
points
connections
References wblut.geom.WB_Frame.addNode(), and wblut.geom.WB_Frame.addStrut().
wblut.geom.WB_Frame.WB_Frame (final WB_Coord[] points, final Collection< WB_IndexedSegment > connections)
Parameters
points
connections
References wblut.geom.WB_Frame.addNode(), and wblut.geom.WB_Frame.addStrut().
wblut.geom.WB_Frame.WB_Frame (final Collection<?extends WB_Coord > points, final Collection< WB_IndexedSegment > connections)
Parameters
points
connections
References wblut.geom.WB_Frame.addNode(), and wblut.geom.WB_Frame.addStrut().
wblut.geom.WB_Frame.WB_Frame (final WB_Coord[] points, final int connections[][])
Parameters
points
connections
References wblut.geom.WB_Frame.addNode(), and wblut.geom.WB_Frame.addStrut().
wblut.geom.WB_Frame.WB_Frame (final Collection<?extends WB_Coord > points, final int connections[][])
Parameters
points
connections
References wblut.geom.WB_Frame.addNode(), and wblut.geom.WB_Frame.addStrut().
wblut.geom.WB_Frame.WB_Frame (final double points[][], final int connections[][])
Parameters
points
connections
References wblut.geom.WB_Frame.addNode(), and wblut.geom.WB_Frame.addStrut().
wblut.geom.WB_Frame.WB_Frame (final float points[][], final int connections[][])
Parameters
points
connections
References wblut.geom.WB_Frame.addNode(), and wblut.geom.WB_Frame.addStrut().
wblut.geom.WB_Frame.WB_Frame (final int points[][], final int connections[][])
Parameters
points
connections
References wblut.geom.WB_Frame.addNode(), and wblut.geom.WB_Frame.addStrut().
wblut.geom.WB_Frame.WB_Frame (final WB_Coord[] points)
Parameters
points
References wblut.geom.WB_Frame.addNode().
wblut.geom.WB_Frame.WB_Frame (final Collection<?extends WB_Coord > points)
Parameters
points
References wblut.geom.WB_Frame.addNode().
wblut.geom.WB_Frame.WB_Frame (final double points[][])
Parameters
points
References wblut.geom.WB_Frame.addNode().
wblut.geom.WB_Frame.WB_Frame (final float points[][])
Parameters
points
References wblut.geom.WB_Frame.addNode().
wblut.geom.WB_Frame.WB_Frame (final int points[][])
Parameters
points
References wblut.geom.WB_Frame.addNode().
Member Function Documentation
void wblut.geom.WB_Frame.add (final WB_Coord[] points, final Collection< WB_IndexedSegment > connections)
Parameters
points
connections
References wblut.geom.WB_Frame.addNode(), and wblut.geom.WB_Frame.addStrut().
void wblut.geom.WB_Frame.add (final WB_Frame frame)
Parameters
frame
References wblut.geom.WB_Frame.addNode(), wblut.geom.WB_Frame.addStrut(), wblut.geom.WB_Frame.getIndexedSegments(), wblut.geom.WB_Frame.WB_FrameNode.getValue(), and wblut.geom.WB_Frame.nodes.
int wblut.geom.WB_Frame.addNode (final double x, final double y, final double z, final double v)
Parameters
x
y
z
v
Returns
int wblut.geom.WB_Frame.addNode (final WB_Coord pos, final double v)
Parameters
pos
v
Returns
int wblut.geom.WB_Frame.addNodes (final Collection< WB_Coord > pos)
Parameters
pos
Returns
boolean wblut.geom.WB_Frame.addStrut (final int i, final int j)
Parameters
i
j
Returns
int wblut.geom.WB_Frame.getClosestNodeOnFrame (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp3D.getSqDistance3D().
WB_Coord wblut.geom.WB_Frame.getClosestPointOnFrame (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.end, wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.geom.WB_GeometryOp3D.getDistance3D(), and wblut.geom.WB_Frame.WB_FrameStrut.start.
WB_Coord wblut.geom.WB_Frame.getClosestPointOnFrame (final double x, final double y, final double z)
Parameters
x
y
z
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.end, wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.geom.WB_GeometryOp3D.getDistance3D(), and wblut.geom.WB_Frame.WB_FrameStrut.start.
double wblut.geom.WB_Frame.getDistanceToFrame (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.end, wblut.geom.WB_GeometryOp3D.getDistance3D(), and wblut.geom.WB_Frame.WB_FrameStrut.start.
double wblut.geom.WB_Frame.getDistanceToFrame (final double x, final double y, final double z)
Parameters
x
y
z
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.end, wblut.geom.WB_GeometryOp3D.getDistance3D(), and wblut.geom.WB_Frame.WB_FrameStrut.start.
ArrayList<WB_IndexedSegment> wblut.geom.WB_Frame.getIndexedSegments ()
Returns
References wblut.geom.WB_Point.add(), and wblut.geom.WB_Frame.getPoints().
WB_FrameNode wblut.geom.WB_Frame.getNode (final int i)
Parameters
i
Returns
ArrayList<WB_FrameNode> wblut.geom.WB_Frame.getNodes ()
Returns
int wblut.geom.WB_Frame.getNumberOfNodes ()
Returns
int wblut.geom.WB_Frame.getNumberOfStruts ()
Returns
ArrayList<WB_Point> wblut.geom.WB_Frame.getPoints ()
Returns
WB_Point [] wblut.geom.WB_Frame.getPointsAsArray ()
Returns
References wblut.geom.WB_Frame.getPoints().
ArrayList<WB_Segment> wblut.geom.WB_Frame.getSegments ()
Returns
WB_FrameStrut wblut.geom.WB_Frame.getStrut (final int i)
Parameters
i
Returns
ArrayList<WB_FrameStrut> wblut.geom.WB_Frame.getStruts ()
Returns
WB_Frame wblut.geom.WB_Frame.refine (final double threshold)
References wblut.geom.WB_Frame.getNumberOfNodes(), wblut.geom.WB_Frame.refine(), and wblut.geom.WB_Frame.refineOnePass().
WB_Frame wblut.geom.WB_Frame.refineOnePass (final double threshold)
Parameters
threshold
Returns
References wblut.geom.WB_Frame.addNode(), wblut.geom.WB_Frame.addStrut(), wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.geom.WB_Frame.getNumberOfNodes(), and wblut.geom.WB_Frame.WB_Frame().
void wblut.geom.WB_Frame.removeNode (final WB_FrameNode node)
Parameters
node
References wblut.geom.WB_Frame.WB_FrameNode.getStruts(), and wblut.geom.WB_Frame.removeStrut().
void wblut.geom.WB_Frame.removeStrut (final WB_FrameStrut strut)
Parameters
strut
References wblut.geom.WB_Frame.WB_FrameStrut.getEndIndex(), and wblut.geom.WB_Frame.WB_FrameStrut.getStartIndex().
WB_Frame wblut.geom.WB_Frame.smoothBiNodes ()
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.mulSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_Frame wblut.geom.WB_Frame.smoothBiNodes (final int r)
References wblut.geom.WB_Frame.smoothBiNodes().
WB_Frame wblut.geom.WB_Frame.smoothNodes ()
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.mulSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_Frame wblut.geom.WB_Frame.smoothNodes (final int r)
References wblut.geom.WB_Frame.smoothNodes().
List<WB_Point> wblut.geom.WB_Frame.toPointCloud (final int n, final double r, final double d, final int l, final double rr, final double dr)
Parameters
n
r
d
l
rr
dr
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_Vector.addMul(), wblut.geom.WB_Point.addMul(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Vector.copy(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Plane.getU(), wblut.hemesh.HE_MeshStructure.getVerticesAsCoord(), wblut.math.WB_Math.max(), wblut.geom.WB_Vector.mul(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_RandomOnSphere.nextVector(), and wblut.geom.WB_Vector.rotateAboutAxisSelf().
Member Data Documentation
WB_GeometryFactory wblut.geom.WB_Frame.gf = new WB_GeometryFactory() static private
FastList<WB_FrameNode> wblut.geom.WB_Frame.nodes protected
FastList<WB_FrameStrut> wblut.geom.WB_Frame.struts protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Frame.java