HE_Mesh: wblut.hemesh.HET_WriterWRL Class Reference
wblut.hemesh.HET_WriterWRL Class Reference
Static Public Member Functions
static void saveMeshWithFaceColor (final HE_Mesh mesh, final String path, final String name)
static void saveMeshWithFaceColor (final HE_Mesh mesh, final OutputStream stream)
static final int red (final int what)
static final int green (final int what)
static final int blue (final int what)
static OutputStream createOutputStream (final File file) throws IOException
static void createDirectories (final File file)
static void saveMesh (final HE_Mesh mesh, final OutputStream stream)
static void saveMesh (final HE_Mesh mesh, final String path, final String name)
static void saveMeshWithVertexColor (final HE_Mesh mesh, final String path, final String name)
static void saveMeshWithVertexColor (final HE_Mesh mesh, final OutputStream stream)
Member Function Documentation
static final int wblut.hemesh.HET_WriterWRL.blue (final int what) static
Parameters
what
Returns
static void wblut.hemesh.HET_WriterWRL.createDirectories (final File file) static
Parameters
file
static OutputStream wblut.hemesh.HET_WriterWRL.createOutputStream (final File file) throws IOException static
Parameters
file
Returns
Exceptions
IOException
References wblut.hemesh.HET_WriterWRL.createDirectories().
static final int wblut.hemesh.HET_WriterWRL.green (final int what) static
Parameters
what
Returns
static final int wblut.hemesh.HET_WriterWRL.red (final int what) static
Parameters
what
Returns
static void wblut.hemesh.HET_WriterWRL.saveMesh (final HE_Mesh mesh, final OutputStream stream) static
Parameters
mesh
stream
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HE_Mesh.vItr(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
static void wblut.hemesh.HET_WriterWRL.saveMesh (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
References wblut.hemesh.HET_WriterWRL.createOutputStream(), and wblut.hemesh.HET_WriterWRL.saveMesh().
static void wblut.hemesh.HET_WriterWRL.saveMeshWithFaceColor (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
References wblut.hemesh.HET_WriterWRL.createOutputStream().
static void wblut.hemesh.HET_WriterWRL.saveMeshWithFaceColor (final HE_Mesh mesh, final OutputStream stream) static
Parameters
mesh
stream
References wblut.hemesh.HET_WriterWRL.blue(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HET_WriterWRL.green(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HET_WriterWRL.red(), wblut.hemesh.HE_Mesh.vItr(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
static void wblut.hemesh.HET_WriterWRL.saveMeshWithVertexColor (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
References wblut.hemesh.HET_WriterWRL.createOutputStream().
static void wblut.hemesh.HET_WriterWRL.saveMeshWithVertexColor (final HE_Mesh mesh, final OutputStream stream) static
Parameters
mesh
stream
References wblut.hemesh.HET_WriterWRL.blue(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HET_WriterWRL.green(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HET_WriterWRL.red(), wblut.hemesh.HE_Mesh.vItr(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_WriterWRL.java