HE_Mesh: wblut.hemesh.HES_PlanarMidEdge Class Reference
wblut.hemesh.HES_PlanarMidEdge Class Reference
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HES_Subdividor
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Additional Inherited Members
Public Member Functions inherited from wblut.hemesh.HES_Subdividor
HES_Subdividor ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Member Function Documentation
HE_Mesh wblut.hemesh.HES_PlanarMidEdge.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.addFaces(), wblut.hemesh.HE_Mesh.cycleHalfedges(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Mesh.getFaces(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Mesh.setVertex(), and wblut.hemesh.HET_MeshOp.splitEdges().
HE_Mesh wblut.hemesh.HES_PlanarMidEdge.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.addFaces(), wblut.hemesh.HE_Mesh.cycleHalfedges(), wblut.hemesh.HE_Selection.fItr(), wblut.hemesh.HE_Selection.getFacesAsArray(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Mesh.removeFaces(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Mesh.setVertex(), and wblut.hemesh.HET_MeshOp.splitEdges().
The documentation for this class was generated from the following file:
src/hemesh_subdividors/wblut/hemesh/HES_PlanarMidEdge.java