HE_Mesh: wblut.hemesh.HEM_MultiSliceSurface Class Reference
wblut.hemesh.HEM_MultiSliceSurface Class Reference
Public Member Functions
HEM_MultiSliceSurface setOffset (final double d)
HEM_MultiSliceSurface ()
HEM_MultiSliceSurface setPlanes (final Collection< WB_Plane > planes)
HEM_MultiSliceSurface setPlanes (final WB_Plane[] planes)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
ArrayList< WB_Plane > planes
HE_Selection cutFaces
HE_Selection newEdges
double offset
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Multiple planar cuts of a mesh. No faces are removed.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_MultiSliceSurface.HEM_MultiSliceSurface ()
Instantiates a new HEM_MultiSlice surface.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_MultiSliceSurface.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Selection.addEdge(), wblut.hemesh.HEM_SliceSurface.applySelf(), wblut.geom.WB_GeometryOp3D.classifySegmentToPlane3D(), wblut.hemesh.HE_Selection.cleanSelection(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.eItr(), wblut.geom.WB_Plane.get(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_GeometryOp3D.isEqual(), wblut.geom.WB_Classification.ON, wblut.hemesh.HE_Mesh.resetEdgeInternalLabels(), wblut.hemesh.HE_Mesh.resetFaceInternalLabels(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HEM_SliceSurface.setOffset(), and wblut.hemesh.HEM_SliceSurface.setPlane().
HE_Mesh wblut.hemesh.HEM_MultiSliceSurface.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Selection.addEdge(), wblut.hemesh.HEM_Modifier.apply(), wblut.geom.WB_GeometryOp3D.classifySegmentToPlane3D(), wblut.hemesh.HE_Selection.cleanSelection(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.eItr(), wblut.geom.WB_Plane.get(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_GeometryOp3D.isEqual(), wblut.geom.WB_Classification.ON, wblut.hemesh.HE_Mesh.resetEdgeInternalLabels(), wblut.hemesh.HE_Mesh.resetFaceInternalLabels(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HEM_SliceSurface.setOffset(), and wblut.hemesh.HEM_SliceSurface.setPlane().
HEM_MultiSliceSurface wblut.hemesh.HEM_MultiSliceSurface.setOffset (final double d)
Set offset.
Parameters
d offset
Returns
self
HEM_MultiSliceSurface wblut.hemesh.HEM_MultiSliceSurface.setPlanes (final Collection< WB_Plane > planes)
Set cut planes from an arrayList of WB_Plane.
Parameters
planes arrayList of WB_Plane
Returns
self
HEM_MultiSliceSurface wblut.hemesh.HEM_MultiSliceSurface.setPlanes (final WB_Plane[] planes)
Set cut planes from an array of WB_Plane.
Parameters
planes array of WB_Plane
Returns
self
Member Data Documentation
HE_Selection wblut.hemesh.HEM_MultiSliceSurface.cutFaces private
Store cut faces.
HE_Selection wblut.hemesh.HEM_MultiSliceSurface.newEdges private
The new edges.
double wblut.hemesh.HEM_MultiSliceSurface.offset private
The offset.
ArrayList<WB_Plane> wblut.hemesh.HEM_MultiSliceSurface.planes private
Cut planes.
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_MultiSliceSurface.java