HE_Mesh: wblut.hemesh.HEM_SliceSurface Class Reference
wblut.hemesh.HEM_SliceSurface Class Reference
Public Member Functions
HEM_SliceSurface ()
HEM_SliceSurface setPlane (final WB_Plane P)
HEM_SliceSurface setPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
HEM_SliceSurface setOffset (final double d)
List< HE_Path > getPaths ()
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Static Public Member Functions
static void main (final String[] args)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Member Functions
void buildPaths (final HE_Selection cutEdges)
Private Attributes
WB_Plane P
HE_Selection cutFaces
HE_Selection newEdges
List< HE_Path > paths
double offset
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Planar cut of a mesh. No faces are removed.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_SliceSurface.HEM_SliceSurface ()
Instantiates a new HEM_SliceSurface.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_SliceSurface.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Selection.addEdge(), wblut.geom.WB_Classification.BACK, wblut.hemesh.HEM_SliceSurface.buildPaths(), wblut.geom.WB_GeometryOp3D.checkIntersection3D(), wblut.geom.WB_GeometryOp3D.classifyPointToPlane3D(), wblut.hemesh.HE_Selection.cleanSelection(), wblut.geom.WB_Plane.d(), wblut.hemesh.HE_Selection.eItr(), wblut.math.WB_Epsilon.EPSILON, wblut.hemesh.HE_Selection.fItr(), wblut.hemesh.HE_Mesh.fItr(), wblut.geom.WB_Classification.FRONT, wblut.hemesh.HE_Mesh.getAABB(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Mesh.getHalfedgeWithKey(), wblut.hemesh.HET_MeshOp.getIntersection(), wblut.geom.WB_Plane.getNormal(), wblut.hemesh.HE_Selection.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces(), wblut.hemesh.HE_Halfedge.getStartVertex(), wblut.hemesh.HE_Face.isDegenerate(), wblut.hemesh.HE_Halfedge.key(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HEM_SliceSurface.offset, wblut.geom.WB_Classification.ON, wblut.hemesh.HE_Mesh.resetEdgeInternalLabels(), wblut.hemesh.HE_Mesh.resetVertexInternalLabels(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setDuringStatus(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HET_MeshOp.splitEdge(), wblut.hemesh.HE_Machine.tracker, and wblut.hemesh.HE_Selection.vItr().
HE_Mesh wblut.hemesh.HEM_SliceSurface.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Selection.addEdge(), wblut.hemesh.HE_Selection.addFaces(), wblut.geom.WB_Classification.BACK, wblut.hemesh.HEM_SliceSurface.buildPaths(), wblut.geom.WB_GeometryOp3D.classifyPointToPlane3D(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Selection.contains(), wblut.geom.WB_Plane.d(), wblut.hemesh.HE_Selection.eItr(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Classification.FRONT, wblut.hemesh.HE_Selection.get(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Mesh.getHalfedgeWithKey(), wblut.hemesh.HET_MeshOp.getIntersection(), wblut.geom.WB_Plane.getNormal(), wblut.hemesh.HE_Selection.getNumberOfEdges(), wblut.hemesh.HE_Selection.getNumberOfVertices(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces(), wblut.hemesh.HE_Halfedge.getStartVertex(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Selection.intersect(), wblut.hemesh.HE_Halfedge.key(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HEM_SliceSurface.offset, wblut.geom.WB_Classification.ON, wblut.hemesh.HE_Mesh.resetEdgeInternalLabels(), wblut.hemesh.HE_Mesh.resetVertexInternalLabels(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setDuringStatus(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HET_MeshOp.splitEdge(), wblut.hemesh.HE_Machine.tracker, and wblut.hemesh.HE_Selection.vItr().
void wblut.hemesh.HEM_SliceSurface.buildPaths (final HE_Selection cutEdges) private
Parameters
cutEdges
References wblut.geom.WB_GeometryOp3D.classifyPointToPlane3D(), wblut.geom.WB_Classification.FRONT, wblut.hemesh.HE_Selection.getEdges(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Selection.getNumberOfEdges(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HEM_SliceSurface.P, wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setDuringStatus(), and wblut.hemesh.HE_Machine.tracker.
List<HE_Path> wblut.hemesh.HEM_SliceSurface.getPaths ()
Returns
List of HE_Path created by the cutting plane
References wblut.hemesh.HEM_SliceSurface.paths.
static void wblut.hemesh.HEM_SliceSurface.main (final String[] args) static
References wblut.hemesh.HEM_SliceSurface.HEM_SliceSurface(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HEM_SliceSurface.setOffset(), and wblut.hemesh.HEM_SliceSurface.setPlane().
HEM_SliceSurface wblut.hemesh.HEM_SliceSurface.setOffset (final double d)
Set offset.
Parameters
d offset
Returns
self
HEM_SliceSurface wblut.hemesh.HEM_SliceSurface.setPlane (final WB_Plane P)
Set cut plane.
Parameters
P cut plane
Returns
self
References wblut.hemesh.HEM_SliceSurface.P.
HEM_SliceSurface wblut.hemesh.HEM_SliceSurface.setPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
Parameters
ox
oy
oz
nx
ny
nz
Returns
Member Data Documentation
HE_Selection wblut.hemesh.HEM_SliceSurface.cutFaces private
Stores cut faces.
HE_Selection wblut.hemesh.HEM_SliceSurface.newEdges private
Stores new edges.
double wblut.hemesh.HEM_SliceSurface.offset private
WB_Plane wblut.hemesh.HEM_SliceSurface.P private
Cut plane.
List<HE_Path> wblut.hemesh.HEM_SliceSurface.paths private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_SliceSurface.java