HE_Mesh: wblut.geom.WB_AABB2D Class Reference
wblut.geom.WB_AABB2D Class Reference
Public Member Functions
WB_AABB2D (final WB_Coord p)
WB_AABB2D ()
WB_AABB2D (final WB_Coord[] points)
WB_AABB2D (final Collection<?extends WB_Coord > points)
WB_AABB2D (final double[] min, final double[] max)
WB_AABB2D (final float[] min, final float[] max)
WB_AABB2D (final int[] min, final int[] max)
WB_AABB2D (final WB_Coord min, final WB_Coord max)
WB_AABB2D (final double minx, final double miny, final double maxx, final double maxy)
WB_AABB2D (final double[] values)
WB_AABB2D (final int[] values)
WB_AABB2D (final float[] values)
double getSize (final int i)
double getMin (final int i)
double getMax (final int i)
int minOrdinate ()
int maxOrdinate ()
void expandToInclude (final WB_Coord p)
void add (final WB_Coord p)
void expandBy (final double distance)
void expandBy (final double[] delta)
void expandBy (final double dx, final double dy)
void expandToInclude (final double[] p)
void expandToInclude (final double x, final double y)
void expandToInclude (final WB_AABB2D other)
void add (final WB_AABB2D other)
void translate (final double[] d)
boolean intersects (final WB_AABB2D other)
boolean intersects (final WB_Coord p)
boolean intersects (final double[] x)
boolean intersects (final double x, final double y)
boolean intersects (final WB_Circle circle)
boolean contains (final WB_AABB2D other)
boolean contains (final WB_Coord p)
boolean contains (final double[] x)
boolean covers (final double[] x)
boolean covers (final double x, final double y)
boolean covers (final WB_Coord p)
boolean covers (final WB_AABB2D other)
double getDistance (final WB_AABB2D other)
double getDistanceSquare (final WB_AABB2D other)
double getDistance (final WB_Coord tuple)
double getDistanceSquare (final WB_Coord tuple)
boolean equals (final WB_AABB2D other)
String toString ()
int numberOfPoints ()
int numberOfSegments ()
int numberOfTriangles ()
int numberOfFaces ()
WB_Point[] getCorners ()
List< int[]> getSegments ()
int getId ()
void setId (final int id)
boolean isDegenerate ()
void set (final WB_AABB2D src)
WB_AABB2D get ()
WB_AABB2D getUnion (final WB_AABB2D aabb)
WB_AABB2D getIntersection (final WB_AABB2D other)
WB_Point getCenter ()
double getWidth ()
double getHeight ()
double getMinX ()
double getCenterX ()
double getCenterY ()
double getMaxX ()
double getMinY ()
double getMaxY ()
double getArea ()
double minExtent ()
double maxExtent ()
void translate (final double x, final double y)
List< int[]> getTriangles ()
int[][] getFaces ()
WB_Point getMin ()
WB_Point getMax ()
int getDim ()
int getTrueDim ()
void pad (final double factor)
int hashCode ()
void setToNull ()
boolean isNull ()
boolean isValid ()
Static Public Member Functions
static boolean intersects (final WB_Coord p1, final WB_Coord p2, final WB_Coord q)
static boolean intersects (final WB_Coord p1, final WB_Coord p2, final WB_Coord q1, final WB_Coord q2)
Protected Attributes
double[] _min
double[] _max
Private Member Functions
void init ()
int hashCode (final double v)
Constructor & Destructor Documentation
wblut.geom.WB_AABB2D.WB_AABB2D (final WB_Coord p)
Parameters
p
References wblut.geom.WB_AABB2D.expandToInclude(), wblut.geom.WB_AABB2D.init(), and wblut.geom.WB_AABB2D.setToNull().
wblut.geom.WB_AABB2D.WB_AABB2D ()
References wblut.geom.WB_AABB2D.init().
wblut.geom.WB_AABB2D.WB_AABB2D (final WB_Coord[] points)
Parameters
points
References wblut.geom.WB_Coord.getd(), and wblut.geom.WB_AABB2D.init().
wblut.geom.WB_AABB2D.WB_AABB2D (final Collection<?extends WB_Coord > points)
Parameters
points
References wblut.geom.WB_AABB2D.init().
wblut.geom.WB_AABB2D.WB_AABB2D (final double[] min, final double[] max)
Parameters
min
max
References wblut.geom.WB_AABB2D.init().
wblut.geom.WB_AABB2D.WB_AABB2D (final float[] min, final float[] max)
Parameters
min
max
References wblut.geom.WB_AABB2D.init().
wblut.geom.WB_AABB2D.WB_AABB2D (final int[] min, final int[] max)
Parameters
min
max
References wblut.geom.WB_AABB2D.init().
wblut.geom.WB_AABB2D.WB_AABB2D (final WB_Coord min, final WB_Coord max)
Parameters
min
max
References wblut.geom.WB_Coord.getd(), and wblut.geom.WB_AABB2D.init().
wblut.geom.WB_AABB2D.WB_AABB2D (final double minx, final double miny, final double maxx, final double maxy)
Parameters
minx
miny
maxx
maxy
References wblut.geom.WB_AABB2D.expandToInclude().
wblut.geom.WB_AABB2D.WB_AABB2D (final double[] values)
Parameters
values
References wblut.geom.WB_AABB2D.init().
wblut.geom.WB_AABB2D.WB_AABB2D (final int[] values)
Parameters
values
References wblut.geom.WB_AABB2D.init().
wblut.geom.WB_AABB2D.WB_AABB2D (final float[] values)
Parameters
values
References wblut.geom.WB_AABB2D.init().
Member Function Documentation
void wblut.geom.WB_AABB2D.add (final WB_Coord p)
Parameters
p
References wblut.geom.WB_AABB2D.expandToInclude(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_AABB2D.add (final WB_AABB2D other)
Parameters
other
References wblut.geom.WB_AABB2D.expandToInclude().
boolean wblut.geom.WB_AABB2D.contains (final WB_AABB2D other)
Parameters
other
Returns
References wblut.geom.WB_AABB2D.covers().
boolean wblut.geom.WB_AABB2D.contains (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_AABB2D.covers().
boolean wblut.geom.WB_AABB2D.contains (final double[] x)
Parameters
x
Returns
References wblut.geom.WB_AABB2D.covers().
boolean wblut.geom.WB_AABB2D.covers (final double[] x)
Parameters
x
Returns
References wblut.geom.WB_AABB2D.isNull().
boolean wblut.geom.WB_AABB2D.covers (final double x, final double y)
Parameters
x
y
Returns
References wblut.geom.WB_AABB2D.isNull().
boolean wblut.geom.WB_AABB2D.covers (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_AABB2D.covers(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
boolean wblut.geom.WB_AABB2D.covers (final WB_AABB2D other)
Parameters
other
Returns
References wblut.geom.WB_AABB2D._max, wblut.geom.WB_AABB2D._min, and wblut.geom.WB_AABB2D.isNull().
boolean wblut.geom.WB_AABB2D.equals (final WB_AABB2D other)
Parameters
other
Returns
References wblut.geom.WB_AABB2D._max, wblut.geom.WB_AABB2D._min, and wblut.geom.WB_AABB2D.isNull().
void wblut.geom.WB_AABB2D.expandBy (final double distance)
Parameters
distance
References wblut.geom.WB_AABB2D.isNull(), and wblut.geom.WB_AABB2D.setToNull().
void wblut.geom.WB_AABB2D.expandBy (final double[] delta)
Parameters
delta
References wblut.geom.WB_AABB2D.isNull(), and wblut.geom.WB_AABB2D.setToNull().
void wblut.geom.WB_AABB2D.expandBy (final double dx, final double dy)
Parameters
dx
dy
References wblut.geom.WB_AABB2D.isNull(), and wblut.geom.WB_AABB2D.setToNull().
void wblut.geom.WB_AABB2D.expandToInclude (final WB_Coord p)
Parameters
p
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_AABB2D.expandToInclude (final double[] p)
Parameters
p
References wblut.geom.WB_AABB2D.isNull().
void wblut.geom.WB_AABB2D.expandToInclude (final double x, final double y)
Parameters
x
y
References wblut.geom.WB_AABB2D.isNull().
void wblut.geom.WB_AABB2D.expandToInclude (final WB_AABB2D other)
Parameters
other
References wblut.geom.WB_AABB2D._max, wblut.geom.WB_AABB2D._min, and wblut.geom.WB_AABB2D.expandToInclude().
WB_AABB2D wblut.geom.WB_AABB2D.get ()
Returns
References wblut.geom.WB_AABB2D.WB_AABB2D().
double wblut.geom.WB_AABB2D.getArea ()
Returns
References wblut.geom.WB_AABB2D.getHeight(), and wblut.geom.WB_AABB2D.getWidth().
WB_Point wblut.geom.WB_AABB2D.getCenter ()
Returns
double wblut.geom.WB_AABB2D.getCenterX ()
Returns
double wblut.geom.WB_AABB2D.getCenterY ()
Returns
WB_Point [] wblut.geom.WB_AABB2D.getCorners ()
Returns
References wblut.geom.WB_AABB2D.isNull(), and wblut.geom.WB_AABB2D.numberOfPoints().
int wblut.geom.WB_AABB2D.getDim ()
Returns
double wblut.geom.WB_AABB2D.getDistance (final WB_AABB2D other)
Parameters
other
Returns
References wblut.geom.WB_AABB2D._max, wblut.geom.WB_AABB2D._min, and wblut.geom.WB_AABB2D.intersects().
double wblut.geom.WB_AABB2D.getDistance (final WB_Coord tuple)
Parameters
tuple
Returns
References wblut.geom.WB_Coord.getd().
double wblut.geom.WB_AABB2D.getDistanceSquare (final WB_AABB2D other)
Parameters
other
Returns
References wblut.geom.WB_AABB2D._max, wblut.geom.WB_AABB2D._min, and wblut.geom.WB_AABB2D.intersects().
double wblut.geom.WB_AABB2D.getDistanceSquare (final WB_Coord tuple)
Parameters
tuple
Returns
References wblut.geom.WB_Coord.getd().
int [][] wblut.geom.WB_AABB2D.getFaces ()
Returns
double wblut.geom.WB_AABB2D.getHeight ()
Returns
References wblut.geom.WB_AABB2D.getSize().
int wblut.geom.WB_AABB2D.getId ()
Returns
WB_AABB2D wblut.geom.WB_AABB2D.getIntersection (final WB_AABB2D other)
Parameters
other
Returns
References wblut.geom.WB_AABB2D._max, wblut.geom.WB_AABB2D._min, wblut.geom.WB_AABB2D.intersects(), wblut.geom.WB_AABB2D.isNull(), and wblut.geom.WB_AABB2D.WB_AABB2D().
double wblut.geom.WB_AABB2D.getMax (final int i)
Parameters
i
Returns
WB_Point wblut.geom.WB_AABB2D.getMax ()
Returns
double wblut.geom.WB_AABB2D.getMaxX ()
Returns
double wblut.geom.WB_AABB2D.getMaxY ()
Returns
double wblut.geom.WB_AABB2D.getMin (final int i)
Parameters
i
Returns
WB_Point wblut.geom.WB_AABB2D.getMin ()
Returns
double wblut.geom.WB_AABB2D.getMinX ()
Returns
double wblut.geom.WB_AABB2D.getMinY ()
Returns
List<int[]> wblut.geom.WB_AABB2D.getSegments ()
Returns
References wblut.geom.WB_AABB2D.numberOfSegments().
double wblut.geom.WB_AABB2D.getSize (final int i)
Parameters
i
Returns
References wblut.geom.WB_AABB2D.isNull().
List<int[]> wblut.geom.WB_AABB2D.getTriangles ()
Returns
int wblut.geom.WB_AABB2D.getTrueDim ()
Returns
References wblut.math.WB_Epsilon.EPSILON, and wblut.geom.WB_AABB2D.isValid().
WB_AABB2D wblut.geom.WB_AABB2D.getUnion (final WB_AABB2D aabb)
Parameters
aabb
Returns
References wblut.geom.WB_AABB2D._max, wblut.geom.WB_AABB2D._min, and wblut.geom.WB_AABB2D.WB_AABB2D().
double wblut.geom.WB_AABB2D.getWidth ()
Returns
References wblut.geom.WB_AABB2D.getSize().
int wblut.geom.WB_AABB2D.hashCode ()
int wblut.geom.WB_AABB2D.hashCode (final double v) private
Parameters
v
Returns
void wblut.geom.WB_AABB2D.init () private
boolean wblut.geom.WB_AABB2D.intersects (final WB_AABB2D other)
Parameters
other
Returns
References wblut.geom.WB_AABB2D._max, wblut.geom.WB_AABB2D._min, and wblut.geom.WB_AABB2D.isNull().
boolean wblut.geom.WB_AABB2D.intersects (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_AABB2D.intersects(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
boolean wblut.geom.WB_AABB2D.intersects (final double[] x)
Parameters
x
Returns
References wblut.geom.WB_AABB2D.isNull().
boolean wblut.geom.WB_AABB2D.intersects (final double x, final double y)
Parameters
x
y
Returns
References wblut.geom.WB_AABB2D.isNull().
boolean wblut.geom.WB_AABB2D.intersects (final WB_Circle circle)
References wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static boolean wblut.geom.WB_AABB2D.intersects (final WB_Coord p1, final WB_Coord p2, final WB_Coord q) static
Parameters
p1
p2
q
Returns
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static boolean wblut.geom.WB_AABB2D.intersects (final WB_Coord p1, final WB_Coord p2, final WB_Coord q1, final WB_Coord q2) static
Parameters
p1
p2
q1
q2
Returns
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
boolean wblut.geom.WB_AABB2D.isDegenerate ()
Returns
References wblut.geom.WB_AABB2D.getTrueDim().
boolean wblut.geom.WB_AABB2D.isNull ()
Returns
boolean wblut.geom.WB_AABB2D.isValid ()
Returns
References wblut.geom.WB_AABB2D.isNull().
double wblut.geom.WB_AABB2D.maxExtent ()
Returns
References wblut.geom.WB_AABB2D.getHeight(), wblut.geom.WB_AABB2D.getWidth(), and wblut.geom.WB_AABB2D.isNull().
int wblut.geom.WB_AABB2D.maxOrdinate ()
Returns
References wblut.geom.WB_AABB2D.getSize(), and wblut.geom.WB_AABB2D.isNull().
double wblut.geom.WB_AABB2D.minExtent ()
Returns
References wblut.geom.WB_AABB2D.getHeight(), wblut.geom.WB_AABB2D.getWidth(), and wblut.geom.WB_AABB2D.isNull().
int wblut.geom.WB_AABB2D.minOrdinate ()
Returns
References wblut.geom.WB_AABB2D.getSize(), and wblut.geom.WB_AABB2D.isNull().
int wblut.geom.WB_AABB2D.numberOfFaces ()
Returns
References wblut.geom.WB_AABB2D.isNull().
int wblut.geom.WB_AABB2D.numberOfPoints ()
Returns
References wblut.geom.WB_AABB2D.isNull().
int wblut.geom.WB_AABB2D.numberOfSegments ()
Returns
References wblut.geom.WB_AABB2D.isNull().
int wblut.geom.WB_AABB2D.numberOfTriangles ()
Returns
References wblut.geom.WB_AABB2D.isNull().
void wblut.geom.WB_AABB2D.pad (final double factor)
Parameters
factor
References wblut.geom.WB_AABB2D.getCenter(), and wblut.geom.WB_Point.getd().
void wblut.geom.WB_AABB2D.set (final WB_AABB2D src)
Parameters
src
References wblut.geom.WB_AABB2D._max, and wblut.geom.WB_AABB2D._min.
void wblut.geom.WB_AABB2D.setId (final int id)
Parameters
id
void wblut.geom.WB_AABB2D.setToNull ()
String wblut.geom.WB_AABB2D.toString ()
void wblut.geom.WB_AABB2D.translate (final double[] d)
Parameters
d
References wblut.geom.WB_AABB2D.isNull().
void wblut.geom.WB_AABB2D.translate (final double x, final double y)
Parameters
x
y
References wblut.geom.WB_AABB2D.isNull().
Member Data Documentation
double [] wblut.geom.WB_AABB2D._max protected
double [] wblut.geom.WB_AABB2D._min protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_AABB2D.java