HE_Mesh: wblut.hemesh.HEC_RevolvePolygon Class Reference
wblut.hemesh.HEC_RevolvePolygon Class Reference
Public Member Functions
HEC_RevolvePolygon ()
HEC_RevolvePolygon setPolygon (final WB_Polygon poly)
HEC_RevolvePolygon setAxis (final WB_Coord p, final WB_Coord v)
HEC_RevolvePolygon setAxis (final double ox, final double oy, final double oz, final double vx, final double vy, final double vz)
HEC_RevolvePolygon setFacets (final int n)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Attributes
WB_Polygon polygon
WB_Line axis
int facets
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Constructor & Destructor Documentation
wblut.hemesh.HEC_RevolvePolygon.HEC_RevolvePolygon ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_RevolvePolygon.createBase () protected
References wblut.geom.WB_Point.copy(), wblut.hemesh.HEC_FromFacelist.createBase(), wblut.hemesh.HEC_RevolvePolygon.facets, wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Polygon.getNumberOfPoints(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Polygon.getPoint(), wblut.geom.WB_Point.rotateAboutAxisSelf(), wblut.hemesh.HEC_FromFacelist.setCheckNormals(), wblut.hemesh.HEC_FromFacelist.setDuplicate(), wblut.hemesh.HEC_FromFacelist.setFaces(), and wblut.hemesh.HEC_FromFacelist.setVertices().
HEC_RevolvePolygon wblut.hemesh.HEC_RevolvePolygon.setAxis (final WB_Coord p, final WB_Coord v)
Parameters
p
v
Returns
HEC_RevolvePolygon wblut.hemesh.HEC_RevolvePolygon.setAxis (final double ox, final double oy, final double oz, final double vx, final double vy, final double vz)
Parameters
ox
oy
oz
vx
vy
vz
Returns
HEC_RevolvePolygon wblut.hemesh.HEC_RevolvePolygon.setFacets (final int n)
Parameters
n
Returns
HEC_RevolvePolygon wblut.hemesh.HEC_RevolvePolygon.setPolygon (final WB_Polygon poly)
Parameters
poly
Returns
Member Data Documentation
WB_Line wblut.hemesh.HEC_RevolvePolygon.axis private
int wblut.hemesh.HEC_RevolvePolygon.facets private
WB_Polygon wblut.hemesh.HEC_RevolvePolygon.polygon private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_RevolvePolygon.java