HE_Mesh: wblut.nurbs.WB_BSpline Class Reference
wblut.nurbs.WB_BSpline Class Reference
Public Member Functions
WB_BSpline ()
WB_BSpline (final WB_Coord[] controlPoints, final WB_NurbsKnot knot)
WB_BSpline (final WB_PointHomogeneous[] controlPoints, final WB_NurbsKnot knot)
WB_BSpline (final WB_Coord[] controlPoints, final int order)
WB_Point curvePoint (final double u)
WB_Vector curveDirection (final double u)
WB_Vector curveDerivative (final double u)
WB_BSpline insertKnot (final double u)
WB_BSpline insertKnotMax (final double u)
WB_BSpline insertKnot (final double u, final int r)
WB_BSpline refineKnot (final WB_NurbsKnot K)
WB_Coord[] points ()
int p ()
int n ()
WB_NurbsKnot knot ()
WB_BSpline[] split (final double u)
WB_BSpline elevateDegree (final int t)
WB_Coord[][] curveDerivCPoints (final int d, final int r1, final int r2)
WB_Coord[] curveDerivs (final double u, final int d)
WB_Point[] curveDerivsNorm (final double u, final int d)
WB_Vector firstDerivative (final double u)
double getLowerU ()
double getUpperU ()
Public Member Functions inherited from wblut.geom.WB_Curve
WB_Point curvePoint (double u)
WB_Vector curveDirection (double u)
WB_Vector curveDerivative (double u)
Protected Attributes
WB_NurbsKnot knot
WB_Coord[] points
int p
int n
Private Member Functions
WB_BSpline refineKnotRestricted (final double[] X)
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.nurbs.WB_BSpline.WB_BSpline ()
wblut.nurbs.WB_BSpline.WB_BSpline (final WB_Coord[] controlPoints, final WB_NurbsKnot knot)
Parameters
controlPoints
knot
References wblut.nurbs.WB_BSpline.knot(), wblut.nurbs.WB_NurbsKnot.n, and wblut.nurbs.WB_NurbsKnot.p().
wblut.nurbs.WB_BSpline.WB_BSpline (final WB_PointHomogeneous[] controlPoints, final WB_NurbsKnot knot)
Parameters
controlPoints
knot
References wblut.nurbs.WB_BSpline.knot(), wblut.nurbs.WB_NurbsKnot.n, and wblut.nurbs.WB_NurbsKnot.p().
wblut.nurbs.WB_BSpline.WB_BSpline (final WB_Coord[] controlPoints, final int order)
Parameters
controlPoints
order
References wblut.nurbs.WB_NurbsKnot.n, and wblut.nurbs.WB_NurbsKnot.p().
Member Function Documentation
WB_Vector wblut.nurbs.WB_BSpline.curveDerivative (final double u)
References wblut.nurbs.WB_BSpline.firstDerivative().
WB_Coord [][] wblut.nurbs.WB_BSpline.curveDerivCPoints (final int d, final int r1, final int r2)
Parameters
d
r1
r2
Returns
References wblut.geom.WB_Point.mulSelf(), wblut.geom.WB_Point.sub(), and wblut.nurbs.WB_NurbsKnot.value().
WB_Coord [] wblut.nurbs.WB_BSpline.curveDerivs (final double u, final int d)
Parameters
u
d
Returns
References wblut.geom.WB_Point.addSelf(), wblut.nurbs.WB_NurbsKnot.allBasisFunctions(), wblut.nurbs.WB_BSpline.curveDerivCPoints(), wblut.geom.WB_Point.mul(), and wblut.nurbs.WB_NurbsKnot.span().
WB_Point [] wblut.nurbs.WB_BSpline.curveDerivsNorm (final double u, final int d)
Parameters
u
d
Returns
References wblut.geom.WB_Point.addSelf(), wblut.nurbs.WB_NurbsKnot.allBasisFunctions(), wblut.nurbs.WB_BSpline.curveDerivCPoints(), wblut.geom.WB_Point.mul(), wblut.geom.WB_Point.normalizeSelf(), and wblut.nurbs.WB_NurbsKnot.span().
WB_Vector wblut.nurbs.WB_BSpline.curveDirection (final double u)
References wblut.nurbs.WB_BSpline.firstDerivative(), and wblut.geom.WB_Vector.normalizeSelf().
WB_Point wblut.nurbs.WB_BSpline.curvePoint (final double u)
References wblut.geom.WB_Point.addSelf(), wblut.nurbs.WB_NurbsKnot.basisFunctions(), wblut.nurbs.WB_NurbsKnot.p(), wblut.nurbs.WB_BSpline.p(), wblut.nurbs.WB_NurbsKnot.span(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_BSpline wblut.nurbs.WB_BSpline.elevateDegree (final int t)
Parameters
t
Returns
References wblut.geom.WB_Point.addMulSelf(), wblut.math.WB_Binomial.bin(), wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.nurbs.WB_BSpline.p(), wblut.nurbs.WB_NurbsKnot.s(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.value(), and wblut.nurbs.WB_BSpline.WB_BSpline().
WB_Vector wblut.nurbs.WB_BSpline.firstDerivative (final double u)
Parameters
u
Returns
References wblut.geom.WB_Vector.addSelf(), wblut.nurbs.WB_NurbsKnot.allBasisFunctions(), wblut.nurbs.WB_BSpline.curveDerivCPoints(), wblut.geom.WB_Point.mul(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.nurbs.WB_NurbsKnot.span().
double wblut.nurbs.WB_BSpline.getLowerU ()
Returns
Implements wblut.geom.WB_Curve.
References wblut.nurbs.WB_NurbsKnot.value().
double wblut.nurbs.WB_BSpline.getUpperU ()
Returns
Implements wblut.geom.WB_Curve.
References wblut.nurbs.WB_NurbsKnot.m, and wblut.nurbs.WB_NurbsKnot.value().
WB_BSpline wblut.nurbs.WB_BSpline.insertKnot (final double u)
Parameters
u
Returns
WB_BSpline wblut.nurbs.WB_BSpline.insertKnot (final double u, final int r)
Parameters
u
r
Returns
References wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.nurbs.WB_NurbsKnot.multiplicity(), wblut.nurbs.WB_BSpline.n(), wblut.nurbs.WB_BSpline.p(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_NurbsKnot.value(), and wblut.nurbs.WB_BSpline.WB_BSpline().
WB_BSpline wblut.nurbs.WB_BSpline.insertKnotMax (final double u)
Parameters
u
Returns
References wblut.nurbs.WB_BSpline.insertKnot(), and wblut.nurbs.WB_NurbsKnot.multiplicity().
WB_NurbsKnot wblut.nurbs.WB_BSpline.knot ()
Returns
int wblut.nurbs.WB_BSpline.n ()
Returns
int wblut.nurbs.WB_BSpline.p ()
Returns
WB_Coord [] wblut.nurbs.WB_BSpline.points ()
Returns
WB_BSpline wblut.nurbs.WB_BSpline.refineKnot (final WB_NurbsKnot K)
Parameters
K
Returns
References wblut.nurbs.WB_NurbsKnot.multiplicity(), wblut.nurbs.WB_NurbsKnot.multVal(), and wblut.nurbs.WB_BSpline.refineKnotRestricted().
WB_BSpline wblut.nurbs.WB_BSpline.refineKnotRestricted (final double[] X) private
Parameters
X
Returns
References wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.math.WB_Epsilon.isZero(), wblut.nurbs.WB_NurbsKnot.m, wblut.nurbs.WB_BSpline.n(), wblut.nurbs.WB_BSpline.p(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_NurbsKnot.value(), and wblut.nurbs.WB_BSpline.WB_BSpline().
WB_BSpline [] wblut.nurbs.WB_BSpline.split (final double u)
Parameters
u
Returns
References wblut.nurbs.WB_BSpline.insertKnotMax(), wblut.nurbs.WB_BSpline.knot, wblut.nurbs.WB_NurbsKnot.m, wblut.nurbs.WB_NurbsKnot.normalize(), wblut.nurbs.WB_BSpline.p(), wblut.nurbs.WB_BSpline.points, wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_NurbsKnot.value(), and wblut.nurbs.WB_BSpline.WB_BSpline().
Member Data Documentation
WB_GeometryFactory wblut.nurbs.WB_BSpline.gf = new WB_GeometryFactory() static private
WB_NurbsKnot wblut.nurbs.WB_BSpline.knot protected
int wblut.nurbs.WB_BSpline.n protected
int wblut.nurbs.WB_BSpline.p protected
WB_Coord [] wblut.nurbs.WB_BSpline.points protected
The documentation for this class was generated from the following file:
src/nurbs/wblut/nurbs/WB_BSpline.java