HE_Mesh: wblut.hemesh.HET_WriterHemesh Class Reference
wblut.hemesh.HET_WriterHemesh Class Reference
Public Member Functions
void beginSave (final OutputStream stream)
void beginSave (final String fn, final String name)
void endSave ()
void vertex (final HE_Vertex v, final int heid)
void halfedge (final HE_Halfedge he, final int vid, final int henextid, final int hepairid, final int faceid)
void face (final HE_Face f, final int heid)
void sizes (final int v1, final int v2, final int v3)
Protected Member Functions
void handleBeginSave ()
Protected Attributes
OutputStream hemeshStream
PrintWriter hemeshWriter
Static Private Member Functions
static void createDirectories (final File file)
Member Function Documentation
void wblut.hemesh.HET_WriterHemesh.beginSave (final OutputStream stream)
Parameters
stream
References wblut.hemesh.HET_WriterHemesh.handleBeginSave().
void wblut.hemesh.HET_WriterHemesh.beginSave (final String fn, final String name)
Parameters
fn
name
References wblut.hemesh.HET_WriterHemesh.createDirectories(), and wblut.hemesh.HET_WriterHemesh.handleBeginSave().
static void wblut.hemesh.HET_WriterHemesh.createDirectories (final File file) static private
Parameters
file
void wblut.hemesh.HET_WriterHemesh.endSave ()
void wblut.hemesh.HET_WriterHemesh.face (final HE_Face f, final int heid)
Parameters
f
heid
References wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_Face.getTextureId(), and wblut.hemesh.HE_Element.getUserLabel().
void wblut.hemesh.HET_WriterHemesh.halfedge (final HE_Halfedge he, final int vid, final int henextid, final int hepairid, final int faceid)
Parameters
he
vid
henextid
hepairid
faceid
References wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Halfedge.getHalfedgeUVW(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_Element.getUserLabel(), wblut.hemesh.HE_Halfedge.hasHalfedgeUVW(), wblut.hemesh.HE_TextureCoordinate.xd(), wblut.hemesh.HE_TextureCoordinate.yd(), and wblut.hemesh.HE_TextureCoordinate.zd().
void wblut.hemesh.HET_WriterHemesh.handleBeginSave () protected
void wblut.hemesh.HET_WriterHemesh.sizes (final int v1, final int v2, final int v3)
Parameters
v1
v2
v3
void wblut.hemesh.HET_WriterHemesh.vertex (final HE_Vertex v, final int heid)
Parameters
v
heid
References wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_Element.getUserLabel(), wblut.hemesh.HE_Vertex.getVertexUVW(), wblut.hemesh.HE_Vertex.hasVertexUVW(), wblut.hemesh.HE_TextureCoordinate.xd(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_TextureCoordinate.yd(), wblut.hemesh.HE_Vertex.yd(), wblut.hemesh.HE_TextureCoordinate.zd(), and wblut.hemesh.HE_Vertex.zd().
Member Data Documentation
OutputStream wblut.hemesh.HET_WriterHemesh.hemeshStream protected
PrintWriter wblut.hemesh.HET_WriterHemesh.hemeshWriter protected
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_WriterHemesh.java