HE_Mesh: wblut.geom.WB_GeometryOpGLU Class Reference
wblut.geom.WB_GeometryOpGLU Class Reference
Static Public Member Functions
static boolean GLUvertEq (final WB_Coord u, final WB_Coord v)
static boolean GLUvertLeq (final WB_Coord u, final WB_Coord v)
static boolean GLUtransLeq (final WB_Coord u, final WB_Coord v)
static boolean GLUedgeGoesLeft (final WB_Segment e)
static boolean GLUedgeGoesRight (final WB_Segment e)
static double GLUedgeEval (final WB_Coord u, final WB_Coord v, final WB_Coord w)
static double GLUedgeSign (final WB_Coord u, final WB_Coord v, final WB_Coord w)
static double GLUtransEval (final WB_Coord u, final WB_Coord v, final WB_Coord w)
static double GLUtransSign (final WB_Coord u, final WB_Coord v, final WB_Coord w)
static boolean GLUvertCCW (final WB_Coord u, final WB_Coord v, final WB_Coord w)
static double GLUrealInterpolate (double a, final double x, double b, final double y)
static double GLUinterpolate (final double a, final double x, final double b, final double y)
static WB_Coord GLUedgeIntersect (WB_Coord o1, WB_Coord d1, WB_Coord o2, WB_Coord d2)
static int GLUlongAxis (final WB_Coord v)
static int GLUlongAxis (final double[] v)
static WB_Coord GLUcomputeNormal (final List<?extends WB_Coord > vertices)
Member Function Documentation
static WB_Coord wblut.geom.WB_GeometryOpGLU.GLUcomputeNormal (final List<?extends WB_Coord > vertices) static
References wblut.geom.WB_Coord.getd(), wblut.geom.WB_GeometryOpGLU.GLUlongAxis(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.geom.WB_GeometryOpGLU.GLUedgeEval (final WB_Coord u, final WB_Coord v, final WB_Coord w) static
References wblut.geom.WB_GeometryOpGLU.GLUvertLeq(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static boolean wblut.geom.WB_GeometryOpGLU.GLUedgeGoesLeft (final WB_Segment e) static
References wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Line.getOrigin(), and wblut.geom.WB_GeometryOpGLU.GLUvertLeq().
static boolean wblut.geom.WB_GeometryOpGLU.GLUedgeGoesRight (final WB_Segment e) static
References wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Line.getOrigin(), and wblut.geom.WB_GeometryOpGLU.GLUvertLeq().
static WB_Coord wblut.geom.WB_GeometryOpGLU.GLUedgeIntersect (WB_Coord o1, WB_Coord d1, WB_Coord o2, WB_Coord d2) static
References wblut.geom.WB_GeometryOpGLU.GLUedgeEval(), wblut.geom.WB_GeometryOpGLU.GLUedgeSign(), wblut.geom.WB_GeometryOpGLU.GLUinterpolate(), wblut.geom.WB_GeometryOpGLU.GLUtransEval(), wblut.geom.WB_GeometryOpGLU.GLUtransLeq(), wblut.geom.WB_GeometryOpGLU.GLUtransSign(), wblut.geom.WB_GeometryOpGLU.GLUvertLeq(), wblut.geom.WB_MutableCoordinate.setX(), wblut.geom.WB_MutableCoordinate.setY(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static double wblut.geom.WB_GeometryOpGLU.GLUedgeSign (final WB_Coord u, final WB_Coord v, final WB_Coord w) static
References wblut.geom.WB_GeometryOpGLU.GLUvertLeq(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static double wblut.geom.WB_GeometryOpGLU.GLUinterpolate (final double a, final double x, final double b, final double y) static
References wblut.geom.WB_GeometryOpGLU.GLUrealInterpolate().
static int wblut.geom.WB_GeometryOpGLU.GLUlongAxis (final WB_Coord v) static
References wblut.geom.WB_Coord.getd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static int wblut.geom.WB_GeometryOpGLU.GLUlongAxis (final double[] v) static
static double wblut.geom.WB_GeometryOpGLU.GLUrealInterpolate (double a, final double x, double b, final double y) static
static double wblut.geom.WB_GeometryOpGLU.GLUtransEval (final WB_Coord u, final WB_Coord v, final WB_Coord w) static
References wblut.geom.WB_GeometryOpGLU.GLUtransLeq(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static boolean wblut.geom.WB_GeometryOpGLU.GLUtransLeq (final WB_Coord u, final WB_Coord v) static
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static double wblut.geom.WB_GeometryOpGLU.GLUtransSign (final WB_Coord u, final WB_Coord v, final WB_Coord w) static
References wblut.geom.WB_GeometryOpGLU.GLUtransLeq(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static boolean wblut.geom.WB_GeometryOpGLU.GLUvertCCW (final WB_Coord u, final WB_Coord v, final WB_Coord w) static
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static boolean wblut.geom.WB_GeometryOpGLU.GLUvertEq (final WB_Coord u, final WB_Coord v) static
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static boolean wblut.geom.WB_GeometryOpGLU.GLUvertLeq (final WB_Coord u, final WB_Coord v) static
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_GeometryOpGLU.java