HE_Mesh: wblut.geom.WB_IndexedAABBTree2D Class Reference
wblut.geom.WB_IndexedAABBTree2D Class Reference
Classes
class Entry
class EntryOrder
class WB_IndexedAABBNode2D
Public Member Functions
WB_IndexedAABBTree2D (final int[] triangles, final WB_CoordCollection points, final int mnof)
WB_IndexedAABBTree2D (final WB_Triangulation2D triangulation, final WB_CoordCollection points, final int mnof)
WB_IndexedAABBTree2D (final WB_AlphaTriangulation2D triangulation, final double alpha, final int mnof)
WB_IndexedAABBTree2D (final WB_Triangulation2DWithPoints triangulation, final int mnof)
WB_IndexedAABBTree2D (final Collection<?extends WB_IndexedTriangle > mesh, final int mnof)
WB_IndexedAABBNode2D getRoot ()
int getDepth ()
WB_Coord getClosestPoint (final WB_Coord p)
int[] getClosestFace (final WB_Coord p)
Entry getClosestEntry (final WB_Coord p)
void expandBy (final double d)
Static Public Attributes
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Private Member Functions
void buildTree (final Collection<?extends WB_IndexedTriangle > mesh)
void buildNode (final WB_IndexedAABBNode2D node, final List< WB_IndexedTriangle > faces, final Collection<?extends WB_IndexedTriangle > mesh, final int level)
double findOptimalSubset (double bestSah, final WB_IndexedAABBNode2D node, final List< WB_IndexedTriangle > childA, final List< WB_IndexedTriangle > childB, final List< WB_IndexedTriangle > faces)
double addNode (final WB_Coord p, final WB_IndexedAABBNode2D node, final PriorityQueue< Entry > entries, double closest2)
Static Private Member Functions
static double getSAH (final double denom, final double surfaceAreaA, final int numA, final double surfaceAreaB, final int numB)
Private Attributes
WB_IndexedAABBNode2D root
final int maxLevel
int depth
final int maxNumberOfFaces
Constructor & Destructor Documentation
wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBTree2D (final int[] triangles, final WB_CoordCollection points, final int mnof)
Parameters
triangles
points
mnof
References wblut.geom.WB_IndexedAABBTree2D.buildTree().
wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBTree2D (final WB_Triangulation2D triangulation, final WB_CoordCollection points, final int mnof)
Parameters
triangulation
points
mnof
References wblut.geom.WB_IndexedAABBTree2D.buildTree(), and wblut.geom.WB_Triangulation2D.getTriangles().
wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBTree2D (final WB_AlphaTriangulation2D triangulation, final double alpha, final int mnof)
Parameters
triangulation
alpha
mnof
References wblut.geom.WB_IndexedAABBTree2D.buildTree(), wblut.geom.WB_AlphaTriangulation2D.getAlphaTriangles(), and wblut.geom.WB_AlphaTriangulation2D.getPoints().
wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBTree2D (final WB_Triangulation2DWithPoints triangulation, final int mnof)
Parameters
triangulation
mnof
References wblut.geom.WB_IndexedAABBTree2D.buildTree(), wblut.geom.WB_Triangulation2DWithPoints.getPoints(), and wblut.geom.WB_Triangulation2D.getTriangles().
wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBTree2D (final Collection<?extends WB_IndexedTriangle > mesh, final int mnof)
Parameters
mesh
mnof
References wblut.geom.WB_IndexedAABBTree2D.buildTree().
Member Function Documentation
double wblut.geom.WB_IndexedAABBTree2D.addNode (final WB_Coord p, final WB_IndexedAABBNode2D node, final PriorityQueue< Entry > entries, double closest2) private
References wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.aabb, wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.faces, wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), wblut.geom.WB_GeometryOp2D.getSqDistance2D(), and wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.isLeaf.
void wblut.geom.WB_IndexedAABBTree2D.buildNode (final WB_IndexedAABBNode2D node, final List< WB_IndexedTriangle > faces, final Collection<?extends WB_IndexedTriangle > mesh, final int level) private
Parameters
node
faces
mesh
level
References wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.aabb, wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.childA, wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.childB, wblut.geom.WB_AABB2D.expandToInclude(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.faces, wblut.geom.WB_IndexedAABBTree2D.findOptimalSubset(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.isLeaf, wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.level, wblut.geom.WB_IndexedAABBTree2D.maxNumberOfFaces, and wblut.core.WB_ProgressReporter.WB_ProgressTracker.setDuringStatus().
void wblut.geom.WB_IndexedAABBTree2D.buildTree (final Collection<?extends WB_IndexedTriangle > mesh) private
Parameters
mesh
References wblut.geom.WB_IndexedAABBTree2D.buildNode(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), and wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus().
void wblut.geom.WB_IndexedAABBTree2D.expandBy (final double d)
References wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.expandBy().
double wblut.geom.WB_IndexedAABBTree2D.findOptimalSubset (double bestSah, final WB_IndexedAABBNode2D node, final List< WB_IndexedTriangle > childA, final List< WB_IndexedTriangle > childB, final List< WB_IndexedTriangle > faces) private
References wblut.geom.WB_AABB.expandToInclude(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getAABB(), wblut.geom.WB_AABB2D.getArea(), wblut.geom.WB_AABB.getArea(), and wblut.geom.WB_IndexedAABBTree2D.getSAH().
Entry wblut.geom.WB_IndexedAABBTree2D.getClosestEntry (final WB_Coord p)
References wblut.geom.WB_IndexedAABBTree2D.addNode(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getChildA(), and wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getChildB().
int [] wblut.geom.WB_IndexedAABBTree2D.getClosestFace (final WB_Coord p)
References wblut.geom.WB_IndexedAABBTree2D.addNode(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getChildA(), and wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getChildB().
WB_Coord wblut.geom.WB_IndexedAABBTree2D.getClosestPoint (final WB_Coord p)
References wblut.geom.WB_IndexedAABBTree2D.addNode(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getChildA(), and wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getChildB().
int wblut.geom.WB_IndexedAABBTree2D.getDepth ()
References wblut.geom.WB_IndexedAABBTree2D.depth.
WB_IndexedAABBNode2D wblut.geom.WB_IndexedAABBTree2D.getRoot ()
Returns
References wblut.geom.WB_IndexedAABBTree2D.root.
static double wblut.geom.WB_IndexedAABBTree2D.getSAH (final double denom, final double surfaceAreaA, final int numA, final double surfaceAreaB, final int numB) static private
Surface area heuristic
Parameters
denom
surfaceAreaA
numA
surfaceAreaB
numB
Returns
Member Data Documentation
int wblut.geom.WB_IndexedAABBTree2D.depth private
final int wblut.geom.WB_IndexedAABBTree2D.maxLevel private
final int wblut.geom.WB_IndexedAABBTree2D.maxNumberOfFaces private
WB_IndexedAABBNode2D wblut.geom.WB_IndexedAABBTree2D.root private
final WB_ProgressTracker wblut.geom.WB_IndexedAABBTree2D.tracker = WB_ProgressTracker.instance() static
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_IndexedAABBTree2D.java