HE_Mesh: wblut.hemesh.HEM_Slice Class Reference
wblut.hemesh.HEM_Slice Class Reference
Public Member Functions
HEM_Slice setOffset (final double d)
HEM_Slice ()
HEM_Slice setPlane (final WB_Plane P)
HEM_Slice setPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
HEM_Slice setReverse (final Boolean b)
HEM_Slice setCap (final Boolean b)
HEM_Slice setOptimizeCap (final boolean b)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Static Public Member Functions
static void main (final String[] args)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_Plane P
boolean reverse = false
boolean capHoles = true
boolean optimizeCap = false
double offset
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Planar cut of a mesh. Faces on positive side of cut plane are removed.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_Slice.HEM_Slice ()
Instantiates a new HEM_Slice.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Slice.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Selection.addEdge(), wblut.hemesh.HE_Mesh.capHalfedges(), wblut.geom.WB_GeometryOp3D.classifyPointToPlane3D(), wblut.hemesh.HE_Mesh.cleanUnusedElementsByFace(), wblut.geom.WB_Plane.d(), wblut.hemesh.HE_Mesh.fItr(), wblut.geom.WB_Plane.flipNormal(), wblut.geom.WB_Classification.FRONT, wblut.geom.WB_Plane.get(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Selection.getFaces(), wblut.geom.WB_Plane.getNormal(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Mesh.getVertexWithKey(), wblut.hemesh.HET_MeshOp.improveTriangulation(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Face.isDegenerate(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HEM_Slice.offset, wblut.geom.WB_Classification.ON, wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Mesh.removeFaces(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setDuringStatus(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HEM_SliceSurface.setPlane(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Mesh.setVertex(), and wblut.hemesh.HE_Machine.tracker.
HE_Mesh wblut.hemesh.HEM_Slice.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HEM_Slice.applySelf().
static void wblut.hemesh.HEM_Slice.main (final String[] args) static
References wblut.hemesh.HEM_Slice.HEM_Slice(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HEM_Slice.setCap(), wblut.hemesh.HEM_Slice.setOffset(), wblut.hemesh.HEM_Slice.setPlane(), and wblut.hemesh.HEM_Slice.setReverse().
HEM_Slice wblut.hemesh.HEM_Slice.setCap (final Boolean b)
Set option to cap holes.
Parameters
b true, false;
Returns
self
HEM_Slice wblut.hemesh.HEM_Slice.setOffset (final double d)
Set offset.
Parameters
d offset
Returns
self
HEM_Slice wblut.hemesh.HEM_Slice.setOptimizeCap (final boolean b)
HEM_Slice wblut.hemesh.HEM_Slice.setPlane (final WB_Plane P)
Set cut plane.
Parameters
P cut plane
Returns
self
References wblut.hemesh.HEM_Slice.P.
HEM_Slice wblut.hemesh.HEM_Slice.setPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
Sets the plane.
Parameters
ox the ox
oy the oy
oz the oz
nx the nx
ny the ny
nz the nz
Returns
the hE m_ slice
HEM_Slice wblut.hemesh.HEM_Slice.setReverse (final Boolean b)
Set reverse option.
Parameters
b true, false
Returns
self
Member Data Documentation
boolean wblut.hemesh.HEM_Slice.capHoles = true private
Cap holes?. Capping holes does not work properly with self-intersection...
double wblut.hemesh.HEM_Slice.offset private
The offset.
boolean wblut.hemesh.HEM_Slice.optimizeCap = false private
WB_Plane wblut.hemesh.HEM_Slice.P private
Cut plane.
boolean wblut.hemesh.HEM_Slice.reverse = false private
HEM_slice keeps the part of the mesh on the positive side of the plane. Reverse planar cut.
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Slice.java