HE_Mesh: wblut.geom.WB_Quad Class Reference
wblut.geom.WB_Quad Class Reference
Public Member Functions
WB_Quad (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4)
boolean isConvex ()
void cycle ()
void cycle (int n)
Static Public Member Functions
static int[] triangulateQuad (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
Public Attributes
WB_Point p1
WB_Point p2
WB_Point p3
WB_Point p4
Private Attributes
WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
Detailed Description
Placeholder for quad.
Constructor & Destructor Documentation
wblut.geom.WB_Quad.WB_Quad (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4)
Instantiates a new WB_Quad. No copies are made.
Parameters
p1 first point
p2 second point
p3 third point
p4 fourth point
References wblut.geom.WB_GeometryFactory3D.createPoint().
Member Function Documentation
void wblut.geom.WB_Quad.cycle ()
References wblut.geom.WB_Quad.p1, wblut.geom.WB_Quad.p2, wblut.geom.WB_Quad.p3, and wblut.geom.WB_Quad.p4.
void wblut.geom.WB_Quad.cycle (int n)
References wblut.geom.WB_Quad.cycle().
boolean wblut.geom.WB_Quad.isConvex ()
References wblut.geom.WB_GeometryOp3D.pointInTriangleBary3D().
static int [] wblut.geom.WB_Quad.triangulateQuad (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord p3) static
Parameters
p0
p1
p2
p3
Returns
References wblut.geom.WB_GeometryOp3D.pointInTriangleBary3D().
Member Data Documentation
WB_GeometryFactory wblut.geom.WB_Quad.geometryfactory = new WB_GeometryFactory() private
WB_Point wblut.geom.WB_Quad.p1
First point.
WB_Point wblut.geom.WB_Quad.p2
Second point.
WB_Point wblut.geom.WB_Quad.p3
Third point.
WB_Point wblut.geom.WB_Quad.p4
Fourth point.
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Quad.java