HE_Mesh: wblut.geom.WB_Transform2D Class Reference
wblut.geom.WB_Transform2D Class Reference
Public Member Functions
WB_Transform2D ()
WB_Transform2D (final WB_Transform2D Trans)
WB_Transform2D get ()
WB_Transform2D addTranslate2D (final WB_Coord v)
WB_Transform2D addTranslate2D (final double f, final WB_Coord v)
WB_Transform2D addScale2D (final WB_Coord s)
WB_Transform2D addScale2D (final double sx, final double sy)
WB_Transform2D addScale2D (final double s)
WB_Transform2D addRotateAboutOrigin (final double angle)
WB_Transform2D addRotateAboutPoint (final double angle, final WB_Coord p)
WB_Transform2D addReflectX ()
WB_Transform2D addReflectY ()
WB_Transform2D addInvert2D ()
WB_Transform2D addReflectX (final WB_Coord p)
WB_Transform2D addReflectY (final WB_Coord p)
WB_Transform2D addInvert2D (final WB_Coord p)
WB_Transform2D addReflect2D (final WB_Coord p1, final WB_Coord p2)
WB_Transform2D addShear2D (final double shx, final double shy)
WB_Transform2D addFromCSToCS2D (final WB_CoordinateSystem2D CS1, final WB_CoordinateSystem2D CS2)
WB_Transform2D addFromCSToWorld2D (final WB_CoordinateSystem2D CS)
WB_Transform2D addFromWorldToCS2D (final WB_CoordinateSystem2D CS)
WB_Transform2D addFromCSToParent2D (final WB_CoordinateSystem2D CS)
WB_Transform2D addFromParentToCS2D (final WB_CoordinateSystem2D CS)
void inverse ()
void clear ()
WB_Point applyAsPoint2D (final WB_Coord p)
void applyAsPoint2DSelf (final WB_MutableCoord p)
void applyAsPoint2DInto (final WB_Coord p, final WB_MutableCoord result)
WB_Point applyAsPoint2D (final double x, final double y)
void applyAsPoint2DInto (final double x, final double y, final WB_MutableCoord result)
WB_Point applyInvAsPoint2D (final WB_Coord p)
void applyInvAsPoint2DSelf (final WB_MutableCoord p)
void applyInvAsPoint2DInto (final WB_Coord p, final WB_MutableCoord result)
WB_Point applyInvAsPoint2D (final double x, final double y)
void applyInvAsPoint2DInto (final double x, final double y, final WB_MutableCoord result)
WB_Vector applyAsVector2D (final WB_Coord p)
void applyAsVector2DSelf (final WB_MutableCoord p)
void applyAsVector2DInto (final WB_Coord p, final WB_MutableCoord result)
WB_Vector applyAsVector2D (final double x, final double y)
void applyAsVector2DInto (final double x, final double y, final WB_MutableCoord result)
WB_Vector applyInvAsVector2D (final WB_Coord p)
void applyInvAsVector2DSelf (final WB_MutableCoord v)
void applyInvAsVector2DInto (final WB_Coord p, final WB_MutableCoord result)
WB_Vector applyInvAsVector2D (final double x, final double y)
void applyInvAsVector2DInto (final double x, final double y, final WB_MutableCoord result)
WB_Vector applyAsNormal2D (final WB_Coord p)
void applyAsNormal2DSelf (final WB_MutableCoord n)
void applyAsNormal2DInto (final WB_Coord n, final WB_MutableCoord result)
WB_Vector applyAsNormal2D (final double x, final double y)
void applyAsNormal2DInto (final double x, final double y, final WB_MutableCoord result)
WB_Vector applyInvAsNormal2D (final WB_Coord n)
void applyInvAsNormal2DSelf (final WB_MutableCoord n)
void applyInvAsNormal2DInto (final WB_Coord n, final WB_MutableCoord result)
WB_Vector applyInvAsNormal2D (final double x, final double y)
void applyInvAsNormal2DInto (final double x, final double y, final WB_MutableCoord result)
String toString ()
Private Attributes
double _xt
WB_M33 T
WB_M33 invT
Constructor & Destructor Documentation
wblut.geom.WB_Transform2D.WB_Transform2D ()
Instantiates a new WB_Transfrom.
wblut.geom.WB_Transform2D.WB_Transform2D (final WB_Transform2D Trans)
Parameters
Trans
References wblut.math.WB_M33.get(), wblut.geom.WB_Transform2D.invT, and wblut.geom.WB_Transform2D.T.
Member Function Documentation
WB_Transform2D wblut.geom.WB_Transform2D.addFromCSToCS2D (final WB_CoordinateSystem2D CS1, final WB_CoordinateSystem2D CS2)
Parameters
CS1
CS2
Returns
References wblut.geom.WB_Transform2D.addFromCSToWorld2D(), and wblut.geom.WB_Transform2D.addFromWorldToCS2D().
WB_Transform2D wblut.geom.WB_Transform2D.addFromCSToParent2D (final WB_CoordinateSystem2D CS)
Parameters
CS
Returns
References wblut.geom.WB_Transform2D.addTranslate2D(), wblut.geom.WB_Vector.dot(), wblut.geom.WB_CoordinateSystem2D.getOrigin(), wblut.geom.WB_CoordinateSystem2D.getX(), wblut.geom.WB_CoordinateSystem2D.getY(), wblut.geom.WB_CoordinateSystem2D.isWorld(), wblut.math.WB_M33.mul(), wblut.geom.WB_Point.subSelf(), and wblut.geom.WB_CoordinateSystem2D.WORLD().
WB_Transform2D wblut.geom.WB_Transform2D.addFromCSToWorld2D (final WB_CoordinateSystem2D CS)
Parameters
CS
Returns
References wblut.geom.WB_Transform2D.addFromCSToParent2D(), wblut.geom.WB_CoordinateSystem2D.getParent(), and wblut.geom.WB_CoordinateSystem2D.isWorld().
WB_Transform2D wblut.geom.WB_Transform2D.addFromParentToCS2D (final WB_CoordinateSystem2D CS)
Parameters
CS
Returns
References wblut.geom.WB_Transform2D.addFromCSToParent2D(), wblut.geom.WB_Transform2D.invT, wblut.geom.WB_CoordinateSystem2D.isWorld(), wblut.math.WB_M33.mul(), wblut.geom.WB_Transform2D.T, and wblut.geom.WB_Transform2D.WB_Transform2D().
WB_Transform2D wblut.geom.WB_Transform2D.addFromWorldToCS2D (final WB_CoordinateSystem2D CS)
Parameters
CS
Returns
References wblut.geom.WB_Transform2D.addFromCSToWorld2D(), wblut.geom.WB_Transform2D.invT, wblut.math.WB_M33.mul(), wblut.geom.WB_Transform2D.T, and wblut.geom.WB_Transform2D.WB_Transform2D().
WB_Transform2D wblut.geom.WB_Transform2D.addInvert2D ()
Adds the invert.
Returns
References wblut.geom.WB_Transform2D.addScale2D().
WB_Transform2D wblut.geom.WB_Transform2D.addInvert2D (final WB_Coord p)
Adds the invert.
Parameters
p the p
Returns
References wblut.geom.WB_Transform2D.addScale2D(), and wblut.geom.WB_Transform2D.addTranslate2D().
WB_Transform2D wblut.geom.WB_Transform2D.addReflect2D (final WB_Coord p1, final WB_Coord p2)
Parameters
p1
p2
Returns
References wblut.math.WB_M33.mul(), wblut.geom.WB_Vector.sub(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
WB_Transform2D wblut.geom.WB_Transform2D.addReflectX ()
Adds the reflect x.
Returns
References wblut.geom.WB_Transform2D.addScale2D().
WB_Transform2D wblut.geom.WB_Transform2D.addReflectX (final WB_Coord p)
Adds the reflect x.
Parameters
p the p
Returns
References wblut.geom.WB_Transform2D.addScale2D(), and wblut.geom.WB_Transform2D.addTranslate2D().
WB_Transform2D wblut.geom.WB_Transform2D.addReflectY ()
Adds the reflect y.
Returns
References wblut.geom.WB_Transform2D.addScale2D().
WB_Transform2D wblut.geom.WB_Transform2D.addReflectY (final WB_Coord p)
Adds the reflect y.
Parameters
p the p
Returns
References wblut.geom.WB_Transform2D.addScale2D(), and wblut.geom.WB_Transform2D.addTranslate2D().
WB_Transform2D wblut.geom.WB_Transform2D.addRotateAboutOrigin (final double angle)
Add rotation around origin.
Parameters
angle angle in radians
Returns
self
References wblut.math.WB_M33.getTranspose(), and wblut.math.WB_M33.mul().
WB_Transform2D wblut.geom.WB_Transform2D.addRotateAboutPoint (final double angle, final WB_Coord p)
Add rotation around point.
Parameters
angle angle in radians
p point
Returns
self
References wblut.geom.WB_Transform2D.addRotateAboutOrigin(), and wblut.geom.WB_Transform2D.addTranslate2D().
WB_Transform2D wblut.geom.WB_Transform2D.addScale2D (final WB_Coord s)
Add uniform scale to transform.
Parameters
s scaling vector
Returns
self
References wblut.math.WB_M33.mul(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Transform2D wblut.geom.WB_Transform2D.addScale2D (final double sx, final double sy)
Add non-uniform scale to transform.
Parameters
sx scaling vector
sy scaling vector
Returns
self
References wblut.math.WB_M33.mul().
WB_Transform2D wblut.geom.WB_Transform2D.addScale2D (final double s)
Add uniform scale to transform.
Parameters
s scaling point
Returns
self
References wblut.math.WB_M33.mul().
WB_Transform2D wblut.geom.WB_Transform2D.addShear2D (final double shx, final double shy)
Returns
References wblut.math.WB_M33.inverse(), and wblut.math.WB_M33.mul().
WB_Transform2D wblut.geom.WB_Transform2D.addTranslate2D (final WB_Coord v)
Add translation to transform.
Parameters
v vector
Returns
self
References wblut.math.WB_M33.mul(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Transform2D wblut.geom.WB_Transform2D.addTranslate2D (final double f, final WB_Coord v)
Parameters
f
v
Returns
References wblut.math.WB_M33.mul(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_Transform2D.applyAsNormal2D (final WB_Coord p)
Apply as normal.
Parameters
p
Returns
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_Transform2D.applyAsNormal2D (final double x, final double y)
Apply as normal.
Parameters
x
y
Returns
References wblut.math.WB_M33.m11, and wblut.math.WB_M33.m21.
void wblut.geom.WB_Transform2D.applyAsNormal2DInto (final WB_Coord n, final WB_MutableCoord result)
Parameters
n
result
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_Transform2D.applyAsNormal2DInto (final double x, final double y, final WB_MutableCoord result)
Parameters
x
y
result
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_Transform2D.applyAsNormal2DSelf (final WB_MutableCoord n)
Apply transform to normal.
Parameters
n normal
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_Transform2D.applyAsPoint2D (final WB_Coord p)
Apply transform to point.
Parameters
p point
Returns
new WB_XYZ
References wblut.math.WB_Epsilon.isZero(), wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.math.WB_M33.m31, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_Transform2D.applyAsPoint2D (final double x, final double y)
Apply as point.
Parameters
x
y
Returns
References wblut.math.WB_Epsilon.isZero(), wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, and wblut.math.WB_M33.m31.
void wblut.geom.WB_Transform2D.applyAsPoint2DInto (final WB_Coord p, final WB_MutableCoord result)
Parameters
p
result
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.math.WB_M33.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_Transform2D.applyAsPoint2DInto (final double x, final double y, final WB_MutableCoord result)
Parameters
x
y
result
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.math.WB_M33.m31, and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_Transform2D.applyAsPoint2DSelf (final WB_MutableCoord p)
Apply transform to point.
Parameters
p point
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.math.WB_M33.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_Transform2D.applyAsVector2D (final WB_Coord p)
Apply transform to vector.
Parameters
p vector
Returns
new WB_Vector
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_Transform2D.applyAsVector2D (final double x, final double y)
Apply as vector.
Parameters
x
y
Returns
References wblut.math.WB_M33.m11, and wblut.math.WB_M33.m21.
void wblut.geom.WB_Transform2D.applyAsVector2DInto (final WB_Coord p, final WB_MutableCoord result)
Parameters
p
result
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_Transform2D.applyAsVector2DInto (final double x, final double y, final WB_MutableCoord result)
Parameters
x
y
result
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_Transform2D.applyAsVector2DSelf (final WB_MutableCoord p)
Apply transform to vector.
Parameters
p vector
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_Transform2D.applyInvAsNormal2D (final WB_Coord n)
Parameters
n
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_Transform2D.applyInvAsNormal2D (final double x, final double y)
Parameters
x
y
References wblut.math.WB_M33.m11, and wblut.math.WB_M33.m21.
void wblut.geom.WB_Transform2D.applyInvAsNormal2DInto (final WB_Coord n, final WB_MutableCoord result)
Parameters
n
result
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_Transform2D.applyInvAsNormal2DInto (final double x, final double y, final WB_MutableCoord result)
Parameters
x
y
result
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_Transform2D.applyInvAsNormal2DSelf (final WB_MutableCoord n)
Parameters
n
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_Transform2D.applyInvAsPoint2D (final WB_Coord p)
Parameters
p
Returns
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.math.WB_M33.m31, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_Transform2D.applyInvAsPoint2D (final double x, final double y)
Parameters
x
y
Returns
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, and wblut.math.WB_M33.m31.
void wblut.geom.WB_Transform2D.applyInvAsPoint2DInto (final WB_Coord p, final WB_MutableCoord result)
Parameters
p
result
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.math.WB_M33.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_Transform2D.applyInvAsPoint2DInto (final double x, final double y, final WB_MutableCoord result)
Parameters
x
y
result
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.math.WB_M33.m31, and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_Transform2D.applyInvAsPoint2DSelf (final WB_MutableCoord p)
Parameters
p
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.math.WB_M33.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_Transform2D.applyInvAsVector2D (final WB_Coord p)
Parameters
p
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_Transform2D.applyInvAsVector2D (final double x, final double y)
Parameters
x
y
References wblut.math.WB_M33.m11, and wblut.math.WB_M33.m21.
void wblut.geom.WB_Transform2D.applyInvAsVector2DInto (final WB_Coord p, final WB_MutableCoord result)
Parameters
p
result
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_Transform2D.applyInvAsVector2DInto (final double x, final double y, final WB_MutableCoord result)
Parameters
x
y
result
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_Transform2D.applyInvAsVector2DSelf (final WB_MutableCoord v)
Parameters
v
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_Transform2D.clear ()
Clear transform.
WB_Transform2D wblut.geom.WB_Transform2D.get ()
Returns
References wblut.geom.WB_Transform2D.WB_Transform2D().
void wblut.geom.WB_Transform2D.inverse ()
Invert transform.
References wblut.geom.WB_Transform2D.invT, and wblut.geom.WB_Transform2D.T.
String wblut.geom.WB_Transform2D.toString ()
References wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, and wblut.math.WB_M33.m31.
Member Data Documentation
double wblut.geom.WB_Transform2D._xt private
WB_M33 wblut.geom.WB_Transform2D.invT private
Inverse transform matrix.
WB_M33 wblut.geom.WB_Transform2D.T private
Transform matrix.
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Transform2D.java