HE_Mesh: wblut.nurbs.WB_RBezier Class Reference
wblut.nurbs.WB_RBezier Class Reference
Public Member Functions
WB_RBezier (final WB_Coord[] controlPoints)
WB_RBezier (final WB_PointHomogeneous[] controlPoints)
WB_RBezier (final WB_Coord[] controlPoints, final double[] weights)
WB_Point curvePoint (final double u)
WB_RBezier elevateDegree ()
Public Member Functions inherited from wblut.nurbs.WB_Bezier
WB_Bezier (final WB_Coord[] controlPoints)
WB_Bezier (final WB_PointHomogeneous[] controlPoints)
WB_Point curvePoint (final double u)
WB_Vector firstDerivative (final double u)
WB_Vector curveDirection (final double u)
WB_Vector curveDerivative (final double u)
double n ()
double getLowerU ()
double getUpperU ()
WB_Bezier elevateDegree ()
WB_Bezier derivative ()
Public Member Functions inherited from wblut.geom.WB_Curve
WB_Point curvePoint (double u)
WB_Vector curveDirection (double u)
WB_Vector curveDerivative (double u)
Protected Attributes
WB_PointHomogeneous[] wpoints
Protected Attributes inherited from wblut.nurbs.WB_Bezier
WB_Coord[] points
int n
Private Attributes
final double[] weights
Constructor & Destructor Documentation
wblut.nurbs.WB_RBezier.WB_RBezier (final WB_Coord[] controlPoints)
Parameters
controlPoints
References wblut.nurbs.WB_Bezier.n(), and wblut.nurbs.WB_Bezier.points.
wblut.nurbs.WB_RBezier.WB_RBezier (final WB_PointHomogeneous[] controlPoints)
Parameters
controlPoints
References wblut.nurbs.WB_Bezier.n(), and wblut.geom.WB_MutableCoordinate4D.wd().
wblut.nurbs.WB_RBezier.WB_RBezier (final WB_Coord[] controlPoints, final double[] weights)
Parameters
controlPoints
weights
References wblut.nurbs.WB_Bezier.n(), wblut.nurbs.WB_Bezier.points, and wblut.nurbs.WB_RBezier.weights.
Member Function Documentation
WB_Point wblut.nurbs.WB_RBezier.curvePoint (final double u)
References wblut.geom.WB_Point4D.addMulSelf(), wblut.math.WB_Bernstein.getBernsteinCoefficientsOfOrderN(), wblut.nurbs.WB_Bezier.n(), and wblut.geom.WB_PointHomogeneous.project().
WB_RBezier wblut.nurbs.WB_RBezier.elevateDegree ()
References wblut.geom.WB_PointHomogeneous.interpolate(), wblut.nurbs.WB_Bezier.n(), and wblut.nurbs.WB_RBezier.WB_RBezier().
Member Data Documentation
final double [] wblut.nurbs.WB_RBezier.weights private
WB_PointHomogeneous [] wblut.nurbs.WB_RBezier.wpoints protected
The documentation for this class was generated from the following file:
src/nurbs/wblut/nurbs/WB_RBezier.java