HE_Mesh: wblut.hemesh.HEM_FlipFaces Class Reference
wblut.hemesh.HEM_FlipFaces Class Reference
Public Member Functions
HEM_FlipFaces ()
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Flip face normals.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_FlipFaces.HEM_FlipFaces ()
Instantiates a new HEM_FlipFaces.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_FlipFaces.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Halfedge.clearUVW(), wblut.hemesh.HE_Mesh.clearVisitedElements(), wblut.hemesh.HE_Mesh.eItr(), wblut.hemesh.HE_Halfedge.getHalfedgeUVW(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Mesh.getNumberOfEdges(), wblut.hemesh.HE_Mesh.getNumberOfHalfedges(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.hasHalfedgeUVW(), wblut.hemesh.HE_EdgeIterator.hasNext(), wblut.hemesh.HE_Mesh.heItr(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_EdgeIterator.next(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatusStr(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatusStr(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatusStr(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), and wblut.hemesh.HE_Machine.tracker.
HE_Mesh wblut.hemesh.HEM_FlipFaces.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Halfedge.clearUVW(), wblut.hemesh.HE_Mesh.clearVisitedElements(), wblut.hemesh.HE_Selection.eItr(), wblut.hemesh.HE_Halfedge.getHalfedgeUVW(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Selection.getNumberOfEdges(), wblut.hemesh.HE_Selection.getNumberOfHalfedges(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.hasHalfedgeUVW(), wblut.hemesh.HE_EdgeIterator.hasNext(), wblut.hemesh.HE_Selection.heItr(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_EdgeIterator.next(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatusStr(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatusStr(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatusStr(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), and wblut.hemesh.HE_Machine.tracker.
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_FlipFaces.java