HE_Mesh: wblut.hemesh.HEC_FromFacelist Class Reference
wblut.hemesh.HEC_FromFacelist Class Reference
Public Member Functions
HEC_FromFacelist ()
HEC_FromFacelist setVertices (final WB_Coord[] vs)
HEC_FromFacelist setVertices (final WB_CoordCollection vs)
HEC_FromFacelist setVertices (final Collection<?extends WB_Coord > vs)
HEC_FromFacelist setVertexUVW (final Collection<?extends WB_Coord > vs)
HEC_FromFacelist setVertexUVW (final WB_Coord[] vs)
HEC_FromFacelist setVertexUVW (final double[][] vs)
HEC_FromFacelist setFaceVertexUVW (final Collection<?extends WB_Coord > vs)
HEC_FromFacelist setFaceVertexUVW (final WB_Coord[] vs)
HEC_FromFacelist setFaceVertexUVW (final double[][] vs)
HEC_FromFacelist setVertices (final WB_Coord[] vs, final boolean copy)
HEC_FromFacelist setVertices (final double[][] vs)
HEC_FromFacelist setVertices (final double[] vs)
HEC_FromFacelist setVertices (final float[][] vs)
HEC_FromFacelist setVertices (final float[] vs)
HEC_FromFacelist setFaces (final int[][] fs)
HEC_FromFacelist setFaces (final int[] fs)
HEC_FromFacelist setFaces (final List< int[]> fs)
HEC_FromFacelist setFacesUVW (final int[][] fs)
HEC_FromFacelist setFacesUVW (final int[] fs)
HEC_FromFacelist setFacesUVW (final List< int[]> fs)
HEC_FromFacelist setFaceTextureIds (final int[] fts)
HEC_FromFacelist setDuplicate (final boolean b)
HEC_FromFacelist setCheckNormals (final boolean b)
HEC_FromFacelist setCheckManifold (final boolean b)
HEC_FromFacelist setCleanUnused (final boolean b)
HEC_FromFacelist setUseFaceInformation (final boolean b)
HEC_FromFacelist setUseVertexInformation (final boolean b)
HEC_FromFacelist setFaceInformation (final int[] colors, final int[] textureIds, final boolean[] visibility, final int[] labels, final int[] intLabels)
HEC_FromFacelist setVertexInformation (final int[] colors, final boolean[] visibility, final int[] labels, final int[] intLabels)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Member Functions
Long ohash (final int u, final int v)
int consistentOrder (final int i, final int j, final int[] face, final int[] neighbor)
Private Attributes
WB_Coord[] vertices
WB_Coord[] uvws
WB_Coord[] vertexuvws
int[] vertexColors
boolean[] vertexVisibility
int[] vertexLabels
int[] vertexInternalLabels
int[] faceColors
int[] faceTextureIds
boolean[] faceVisibility
int[] faceLabels
int[] faceInternalLabels
int[][] faces
int[][] faceuvws
boolean duplicate
boolean normalcheck
boolean manifoldcheck
boolean cleanunused
boolean useFaceInfo
boolean useVertexInfo
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Creates a new mesh from a list of vertices and faces. Vertices can be duplicate.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_FromFacelist.HEC_FromFacelist ()
Instantiates a new HEC_Facelist.
Member Function Documentation
int wblut.hemesh.HEC_FromFacelist.consistentOrder (final int i, final int j, final int[] face, final int[] neighbor) private
HE_Mesh wblut.hemesh.HEC_FromFacelist.createBase () protected
References wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.add(), wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.addHalfedges(), wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HE_Mesh.cleanUnusedElementsByFace(), wblut.hemesh.HEC_FromFacelist.consistentOrder(), wblut.hemesh.HE_Mesh.cycleHalfedges(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HET_Fixer.fixNonManifoldVertices(), wblut.hemesh.HET_MeshOp.flipFaces(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.getNearestNeighbors(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Vertex.getVertexUVW(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HEC_FromFacelist.ohash(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_MeshElement.setColor(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Element.setUserLabel(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Vertex.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HE_MeshElement.setVisible(), wblut.math.WB_Epsilon.SQEPSILON, wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), wblut.hemesh.HE_TextureCoordinate.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
Long wblut.hemesh.HEC_FromFacelist.ohash (final int u, final int v) private
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setCheckManifold (final boolean b)
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setCheckNormals (final boolean b)
Check face normals?.
Parameters
b true/false
Returns
self
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setCleanUnused (final boolean b)
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setDuplicate (final boolean b)
Duplicate vertices in input?.
Parameters
b true/false
Returns
self
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setFaceInformation (final int[] colors, final int[] textureIds, final boolean[] visibility, final int[] labels, final int[] intLabels)
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setFaces (final int fs[][])
Set faces from 2D array of int: 1st index=face, 2nd=index of vertex.
Parameters
fs 2D array of vertex indices
Returns
self
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setFaces (final int[] fs)
Set faces from 1D array of int: triangles are assumed.
Parameters
fs 1D array of vertex indices
Returns
self
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setFaces (final List< int[]> fs)
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setFacesUVW (final int fs[][])
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setFacesUVW (final int[] fs)
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setFacesUVW (final List< int[]> fs)
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setFaceTextureIds (final int[] fts)
Parameters
fts
Returns
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setFaceVertexUVW (final Collection<?extends WB_Coord > vs)
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setFaceVertexUVW (final WB_Coord[] vs)
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setFaceVertexUVW (final double vs[][])
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setUseFaceInformation (final boolean b)
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setUseVertexInformation (final boolean b)
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setVertexInformation (final int[] colors, final boolean[] visibility, final int[] labels, final int[] intLabels)
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setVertexUVW (final Collection<?extends WB_Coord > vs)
Parameters
vs
Returns
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setVertexUVW (final WB_Coord[] vs)
Parameters
vs
Returns
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setVertexUVW (final double vs[][])
Parameters
vs
Returns
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setVertices (final WB_Coord[] vs)
Set vertex coordinates from an array of WB_point. No copies are made.
Parameters
vs vertices
Returns
self
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setVertices (final WB_CoordCollection vs)
References wblut.geom.WB_CoordCollection.toArray().
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setVertices (final Collection<?extends WB_Coord > vs)
Set vertex coordinates from an arraylist of WB_point.
Parameters
vs vertices
Returns
self
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setVertices (final WB_Coord[] vs, final boolean copy)
Set vertex coordinates from an array of WB_point.
Parameters
vs vertices
copy copy points?
Returns
self
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setVertices (final double vs[][])
Set vertex coordinates from a 2D array of double: 1st index=point, 2nd index (0..2) coordinates
Parameters
vs Nx3 2D array of coordinates
Returns
self
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setVertices (final double[] vs)
Set vertex coordinates from array of double: x0, y0 ,z0 ,x1 ,y1 ,z1 ,...
Parameters
vs array of coordinates
Returns
self
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setVertices (final float vs[][])
Set vertex coordinates from a 2D array of float: 1st index=point, 2nd index (0..2) coordinates
Parameters
vs Nx3 2D array of coordinates
Returns
self
HEC_FromFacelist wblut.hemesh.HEC_FromFacelist.setVertices (final float[] vs)
Set vertex coordinates from array of float: x0, y0 ,z0 ,x1 ,y1 ,z1 ,...
Parameters
vs array of coordinates
Returns
self
Member Data Documentation
boolean wblut.hemesh.HEC_FromFacelist.cleanunused private
boolean wblut.hemesh.HEC_FromFacelist.duplicate private
Duplicate vertices?.
int [] wblut.hemesh.HEC_FromFacelist.faceColors private
int [] wblut.hemesh.HEC_FromFacelist.faceInternalLabels private
int [] wblut.hemesh.HEC_FromFacelist.faceLabels private
int [][] wblut.hemesh.HEC_FromFacelist.faces private
Face indices.
int [] wblut.hemesh.HEC_FromFacelist.faceTextureIds private
int [][] wblut.hemesh.HEC_FromFacelist.faceuvws private
boolean [] wblut.hemesh.HEC_FromFacelist.faceVisibility private
boolean wblut.hemesh.HEC_FromFacelist.manifoldcheck private
boolean wblut.hemesh.HEC_FromFacelist.normalcheck private
Check face normal consistency?.
boolean wblut.hemesh.HEC_FromFacelist.useFaceInfo private
boolean wblut.hemesh.HEC_FromFacelist.useVertexInfo private
WB_Coord [] wblut.hemesh.HEC_FromFacelist.uvws private
int [] wblut.hemesh.HEC_FromFacelist.vertexColors private
int [] wblut.hemesh.HEC_FromFacelist.vertexInternalLabels private
int [] wblut.hemesh.HEC_FromFacelist.vertexLabels private
WB_Coord [] wblut.hemesh.HEC_FromFacelist.vertexuvws private
boolean [] wblut.hemesh.HEC_FromFacelist.vertexVisibility private
WB_Coord [] wblut.hemesh.HEC_FromFacelist.vertices private
Vertices.
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_FromFacelist.java