HE_Mesh: wblut.hemesh.HEC_Ring Class Reference
wblut.hemesh.HEC_Ring Class Reference
Public Member Functions
HEC_Ring ()
HEC_Ring setRadius (final double ir, final double or)
HEC_Ring setPhase (final double phase)
HEC_Ring setN (final int N)
HEC_Ring setCenter (final WB_Coord center)
HEC_Ring setNormal (final WB_Coord normal)
HEC_Ring setThickness (final double thickness)
HEC_Ring setOffset (final double offset)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Author
FVH
Constructor & Destructor Documentation
wblut.hemesh.HEC_Ring.HEC_Ring ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_Ring.createBase () protected
References wblut.geom.WB_Point.add(), wblut.hemesh.HEC_Disk.createBase(), wblut.hemesh.HEC_Polygon.createBase(), wblut.geom.WB_Circle.getPoints(), wblut.hemesh.HEC_Disk.setCenter(), wblut.hemesh.HEC_Disk.setN(), wblut.hemesh.HEC_Disk.setNormal(), wblut.hemesh.HEC_Disk.setOffset(), wblut.hemesh.HEC_Polygon.setOffset(), wblut.hemesh.HEC_Disk.setPhase(), wblut.hemesh.HEC_Polygon.setPolygon(), wblut.hemesh.HEC_Disk.setRadius(), wblut.hemesh.HEC_Disk.setThickness(), and wblut.hemesh.HEC_Polygon.setThickness().
HEC_Ring wblut.hemesh.HEC_Ring.setCenter (final WB_Coord center)
HEC_Ring wblut.hemesh.HEC_Ring.setN (final int N)
HEC_Ring wblut.hemesh.HEC_Ring.setNormal (final WB_Coord normal)
HEC_Ring wblut.hemesh.HEC_Ring.setOffset (final double offset)
HEC_Ring wblut.hemesh.HEC_Ring.setPhase (final double phase)
HEC_Ring wblut.hemesh.HEC_Ring.setRadius (final double ir, final double or)
HEC_Ring wblut.hemesh.HEC_Ring.setThickness (final double thickness)
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_Ring.java