HE_Mesh: wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord > Class Template Reference
wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord > Class Template Reference
Classes
class QueryResultInteger
class WB_KDEntryInteger
class WB_KDNodeInteger
Public Member Functions
WB_KDTreeInteger2D ()
WB_KDTreeInteger2D (final int binsize)
List< WB_AABB2D > getLeafBounds ()
List< WB_AABB2D > getAllBounds ()
List< WB_AABB2D > getLeafRegions ()
List< WB_AABB2D > getAllRegions ()
int add (final T coord, final int val)
WB_KDEntryInteger< T >[] getRange (final WB_AABB2D aabb)
WB_KDEntryInteger< T >[] getRange (final WB_Coord center, final double radius)
WB_KDEntryInteger< T >[] getRange (final WB_Coord center, final double lower, final double upper)
WB_KDEntryInteger< T >[] getNearestNeighbors (final WB_Coord coord, final int num)
WB_KDEntryInteger< T > getNearestNeighbor (final WB_Coord coord)
WB_KDEntryInteger< T > getNearestNeighbor (final double x, final double y)
Private Attributes
final int _dim
final int _maximumBinSize
final WB_KDNodeInteger< T > root
Detailed Description
Class WB_KDTree.
Parameters
<T> generic type
Constructor & Destructor Documentation
wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.WB_KDTreeInteger2D ()
wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.WB_KDTreeInteger2D (final int binsize)
Parameters
binsize
Member Function Documentation
int wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.add (final T coord, final int val)
Parameters
coord
val
Returns
References wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.WB_KDNodeInteger< T extends WB_Coord >.add().
List<WB_AABB2D> wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.getAllBounds ()
Returns
References wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.WB_KDNodeInteger< T extends WB_Coord >.addBox().
List<WB_AABB2D> wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.getAllRegions ()
Get all regions.
Returns
all regions
References wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.WB_KDNodeInteger< T extends WB_Coord >.addRegion().
List<WB_AABB2D> wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.getLeafBounds ()
Returns
References wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.WB_KDNodeInteger< T extends WB_Coord >.addLeafBounds().
List<WB_AABB2D> wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.getLeafRegions ()
Get the leaf regions.
Returns
leaf regions
References wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.WB_KDNodeInteger< T extends WB_Coord >.addLeafRegion().
WB_KDEntryInteger<T> wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.getNearestNeighbor (final WB_Coord coord)
Parameters
coord
Returns
References wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.QueryResultInteger< T extends WB_Coord >.entries, and wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.WB_KDNodeInteger< T extends WB_Coord >.findNearest().
WB_KDEntryInteger<T> wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.getNearestNeighbor (final double x, final double y)
Parameters
x
y
Returns
References wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.QueryResultInteger< T extends WB_Coord >.entries, and wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.WB_KDNodeInteger< T extends WB_Coord >.findNearest().
WB_KDEntryInteger<T> [] wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.getNearestNeighbors (final WB_Coord coord, final int num)
Parameters
coord
num
Returns
References wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.QueryResultInteger< T extends WB_Coord >.entries, and wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.WB_KDNodeInteger< T extends WB_Coord >.findNearest().
WB_KDEntryInteger<T> [] wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.getRange (final WB_AABB2D aabb)
Parameters
aabb
Returns
References wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.WB_KDNodeInteger< T extends WB_Coord >.range().
WB_KDEntryInteger<T> [] wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.getRange (final WB_Coord center, final double radius)
Parameters
center
radius
Returns
References wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.WB_KDNodeInteger< T extends WB_Coord >.range().
WB_KDEntryInteger<T> [] wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.getRange (final WB_Coord center, final double lower, final double upper)
Parameters
center
lower
upper
Returns
References wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.WB_KDNodeInteger< T extends WB_Coord >.range().
Member Data Documentation
final int wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >._dim private
dim.
final int wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >._maximumBinSize private
maximum bin size.
final WB_KDNodeInteger<T> wblut.geom.WB_KDTreeInteger2D< T extends WB_Coord >.root private
root.
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_KDTreeInteger2D.java