HE_Mesh: wblut.nurbs.WB_NurbsFactory Class Reference
wblut.nurbs.WB_NurbsFactory Class Reference
Static Public Member Functions
static WB_RBSplineSurface getSurfaceOfRevolution (final WB_BSpline C, final WB_Coord p, final WB_Coord axis, double theta)
static WB_RBSplineSurface getFullSurfaceOfRevolution (final WB_BSpline C, final WB_Coord p, final WB_Coord axis)
static WB_RBSplineSurface getSurfaceOfRevolution (final WB_RBSpline C, final WB_Coord p, final WB_Coord axis, double theta)
static WB_RBSplineSurface getFullSurfaceOfRevolution (final WB_RBSpline C, final WB_Coord p, final WB_Coord axis)
static WB_BSplineSurface getRuledSurface (WB_BSpline CA, WB_BSpline CB)
static WB_RBSplineSurface getRuledSurface (WB_RBSpline CA, WB_RBSpline CB)
static WB_BSplineSurface getSwungSurface (final WB_BSpline xzprofile, final WB_BSpline xytrajectory, final double alpha)
static WB_RBSplineSurface getSwungSurface (final WB_BSpline xzprofile, final WB_RBSpline xytrajectory, final double alpha)
static WB_RBSplineSurface getSwungSurface (final WB_RBSpline xzprofile, final WB_BSpline xytrajectory, final double alpha)
static WB_RBSplineSurface getSwungSurface (final WB_RBSpline xzprofile, final WB_RBSpline xytrajectory, final double alpha)
static WB_BSplineSurface getLineSweep (final WB_BSpline C, final WB_Coord v, final double f)
static WB_RBSplineSurface getLineSweep (final WB_RBSpline C, final WB_Coord v, final double f)
Detailed Description
Author
FVH
Member Function Documentation
static WB_RBSplineSurface wblut.nurbs.WB_NurbsFactory.getFullSurfaceOfRevolution (final WB_BSpline C, final WB_Coord p, final WB_Coord axis) static
References wblut.nurbs.WB_NurbsFactory.getSurfaceOfRevolution().
static WB_RBSplineSurface wblut.nurbs.WB_NurbsFactory.getFullSurfaceOfRevolution (final WB_RBSpline C, final WB_Coord p, final WB_Coord axis) static
References wblut.nurbs.WB_NurbsFactory.getSurfaceOfRevolution().
static WB_BSplineSurface wblut.nurbs.WB_NurbsFactory.getLineSweep (final WB_BSpline C, final WB_Coord v, final double f) static
Parameters
C
v
f
Returns
References wblut.geom.WB_Point.addMul(), wblut.nurbs.WB_BSpline.knot, wblut.nurbs.WB_BSpline.n, and wblut.nurbs.WB_BSpline.points.
static WB_RBSplineSurface wblut.nurbs.WB_NurbsFactory.getLineSweep (final WB_RBSpline C, final WB_Coord v, final double f) static
Parameters
C
v
f
Returns
References wblut.geom.WB_Point.addMul(), wblut.nurbs.WB_BSpline.knot, wblut.nurbs.WB_BSpline.n, wblut.nurbs.WB_BSpline.points, and wblut.nurbs.WB_RBSpline.weights.
static WB_BSplineSurface wblut.nurbs.WB_NurbsFactory.getRuledSurface (WB_BSpline CA, WB_BSpline CB) static
Parameters
CA
CB
Returns
References wblut.nurbs.WB_BSpline.elevateDegree(), wblut.nurbs.WB_BSpline.getLowerU(), wblut.nurbs.WB_BSpline.getUpperU(), wblut.nurbs.WB_BSpline.knot, wblut.nurbs.WB_NurbsKnot.merge(), wblut.nurbs.WB_NurbsKnot.n, wblut.nurbs.WB_BSpline.p, wblut.nurbs.WB_BSpline.points, and wblut.nurbs.WB_BSpline.refineKnot().
static WB_RBSplineSurface wblut.nurbs.WB_NurbsFactory.getRuledSurface (WB_RBSpline CA, WB_RBSpline CB) static
Parameters
CA
CB
Returns
References wblut.nurbs.WB_RBSpline.elevateDegree(), wblut.nurbs.WB_BSpline.getLowerU(), wblut.nurbs.WB_BSpline.getUpperU(), wblut.nurbs.WB_BSpline.knot, wblut.nurbs.WB_NurbsKnot.merge(), wblut.nurbs.WB_NurbsKnot.n, wblut.nurbs.WB_BSpline.p, wblut.nurbs.WB_RBSpline.refineKnot(), and wblut.nurbs.WB_RBSpline.wpoints.
static WB_RBSplineSurface wblut.nurbs.WB_NurbsFactory.getSurfaceOfRevolution (final WB_BSpline C, final WB_Coord p, final WB_Coord axis, double theta) static
Parameters
C
p
axis
theta
Returns
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Vector.addMulSelf(), wblut.geom.WB_Vector.crossSelf(), wblut.geom.WB_IntersectionResult.dimension, wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.nurbs.WB_BSpline.knot, wblut.geom.WB_Vector.mul(), wblut.geom.WB_Vector.mulSelf(), wblut.nurbs.WB_BSpline.n, wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_IntersectionResult.object, wblut.nurbs.WB_BSpline.points, wblut.geom.WB_MutableCoordinate.set(), and wblut.geom.WB_Vector.subToVector3D().
static WB_RBSplineSurface wblut.nurbs.WB_NurbsFactory.getSurfaceOfRevolution (final WB_RBSpline C, final WB_Coord p, final WB_Coord axis, double theta) static
Parameters
C
p
axis
theta
Returns
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Vector.addMulSelf(), wblut.geom.WB_Vector.crossSelf(), wblut.geom.WB_IntersectionResult.dimension, wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.nurbs.WB_BSpline.knot, wblut.geom.WB_Vector.mul(), wblut.geom.WB_Vector.mulSelf(), wblut.nurbs.WB_BSpline.n, wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_IntersectionResult.object, wblut.nurbs.WB_BSpline.points, wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Vector.subToVector3D(), wblut.geom.WB_MutableCoordinate4D.wd(), and wblut.nurbs.WB_RBSpline.wpoints.
static WB_BSplineSurface wblut.nurbs.WB_NurbsFactory.getSwungSurface (final WB_BSpline xzprofile, final WB_BSpline xytrajectory, final double alpha) static
Parameters
xzprofile
xytrajectory
alpha
Returns
References wblut.nurbs.WB_BSpline.knot, wblut.nurbs.WB_BSpline.n, wblut.nurbs.WB_BSpline.points, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static WB_RBSplineSurface wblut.nurbs.WB_NurbsFactory.getSwungSurface (final WB_BSpline xzprofile, final WB_RBSpline xytrajectory, final double alpha) static
Parameters
xzprofile
xytrajectory
alpha
Returns
References wblut.nurbs.WB_BSpline.knot, wblut.nurbs.WB_BSpline.n, wblut.nurbs.WB_BSpline.points, wblut.nurbs.WB_RBSpline.weights, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static WB_RBSplineSurface wblut.nurbs.WB_NurbsFactory.getSwungSurface (final WB_RBSpline xzprofile, final WB_BSpline xytrajectory, final double alpha) static
Parameters
xzprofile
xytrajectory
alpha
Returns
References wblut.nurbs.WB_BSpline.knot, wblut.nurbs.WB_BSpline.n, wblut.nurbs.WB_BSpline.points, wblut.nurbs.WB_RBSpline.weights, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static WB_RBSplineSurface wblut.nurbs.WB_NurbsFactory.getSwungSurface (final WB_RBSpline xzprofile, final WB_RBSpline xytrajectory, final double alpha) static
Parameters
xzprofile
xytrajectory
alpha
Returns
References wblut.nurbs.WB_BSpline.knot, wblut.nurbs.WB_BSpline.n, wblut.nurbs.WB_BSpline.points, wblut.nurbs.WB_RBSpline.weights, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
The documentation for this class was generated from the following file:
src/nurbs/wblut/nurbs/WB_NurbsFactory.java