HE_Mesh: wblut.hemesh.HET_Contours Class Reference
wblut.hemesh.HET_Contours Class Reference
Static Public Member Functions
static List< List< WB_Coord > > contoursAsPaths (final HE_Mesh mesh, final WB_Plane P)
static List< List< WB_Coord > > contoursAsPaths (final HE_Mesh mesh, final WB_Plane P, final double min, final double max, final double step)
static List< WB_Segment > contours (final HE_Mesh mesh, final WB_Plane P)
static List< WB_Segment > contours (final HE_Mesh mesh, final WB_Plane P, final double min, final double max, final double step)
static List< WB_Segment > contours (final HE_Mesh mesh, final WB_ScalarParameter function, final double level)
static List< WB_Segment > contours (final HE_Mesh mesh, final WB_ScalarParameter function, final double min, final double max, final double step)
static List< WB_Segment > contours (final HE_Mesh mesh, final double[] vertexValues, final double level)
static List< WB_Segment > contours (final HE_Mesh mesh, final double[] vertexValues, final double min, final double max, final double step)
Detailed Description
Author
FVH
Member Function Documentation
static List<WB_Segment> wblut.hemesh.HET_Contours.contours (final HE_Mesh mesh, final WB_Plane P) static
References wblut.geom.WB_Plane.d(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.geom.WB_Plane.getNormal(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.geom.WB_MutableCoordinate.set(), wblut.hemesh.HE_Mesh.triangulate(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
static List<WB_Segment> wblut.hemesh.HET_Contours.contours (final HE_Mesh mesh, final WB_Plane P, final double min, final double max, final double step) static
References wblut.geom.WB_Point.addMul(), wblut.geom.WB_Plane.d(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Plane.getOrigin(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.geom.WB_MutableCoordinate.set(), wblut.hemesh.HE_Mesh.triangulate(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
static List<WB_Segment> wblut.hemesh.HET_Contours.contours (final HE_Mesh mesh, final WB_ScalarParameter function, final double level) static
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.geom.WB_MutableCoordinate.set(), and wblut.hemesh.HE_Mesh.triangulate().
static List<WB_Segment> wblut.hemesh.HET_Contours.contours (final HE_Mesh mesh, final WB_ScalarParameter function, final double min, final double max, final double step) static
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.geom.WB_MutableCoordinate.set(), wblut.hemesh.HE_Mesh.triangulate(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static List<WB_Segment> wblut.hemesh.HET_Contours.contours (final HE_Mesh mesh, final double[] vertexValues, final double level) static
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Mesh.getIndex(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.geom.WB_MutableCoordinate.set(), and wblut.hemesh.HE_Mesh.triangulate().
static List<WB_Segment> wblut.hemesh.HET_Contours.contours (final HE_Mesh mesh, final double[] vertexValues, final double min, final double max, final double step) static
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Mesh.getIndex(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.geom.WB_MutableCoordinate.set(), wblut.hemesh.HE_Mesh.triangulate(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), and wblut.hemesh.HE_Vertex.zd().
static List<List<WB_Coord> > wblut.hemesh.HET_Contours.contoursAsPaths (final HE_Mesh mesh, final WB_Plane P) static
References wblut.hemesh.HET_Contours.contours(), wblut.hemesh.HE_Mesh.get(), wblut.hemesh.HEM_SliceSurface.getPaths(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HEM_SliceSurface.setPlane(), and wblut.hemesh.HE_Mesh.triangulate().
static List<List<WB_Coord> > wblut.hemesh.HET_Contours.contoursAsPaths (final HE_Mesh mesh, final WB_Plane P, final double min, final double max, final double step) static
References wblut.geom.WB_Point.addMul(), wblut.hemesh.HET_Contours.contours(), wblut.hemesh.HE_Mesh.get(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Plane.getOrigin(), wblut.hemesh.HEM_SliceSurface.getPaths(), wblut.hemesh.HEM_SliceSurface.setPlane(), and wblut.hemesh.HE_Mesh.triangulate().
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_Contours.java