HE_Mesh: wblut.hemesh.HEM_Mirror Class Reference
wblut.hemesh.HEM_Mirror Class Reference
Public Member Functions
HEM_Mirror ()
HEM_Mirror setOffset (final double d)
HEM_Mirror setPlane (final WB_Plane P)
HEM_Mirror setPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
HEM_Mirror setReverse (final Boolean b)
HEM_Mirror setKeepLargest (final Boolean b)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Static Public Member Functions
static void main (final String[] args)
Public Attributes
HE_Vertex[] pairs
HE_Vertex[] boundaryPairs
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_Plane P
boolean reverse = false
boolean keepLargest = false
double offset
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_Mirror.HEM_Mirror ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Mirror.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HE_Mesh.cleanUnusedElementsByFace(), wblut.geom.WB_Plane.extractPoint2D(), wblut.hemesh.HET_MeshOp.flipFaces(), wblut.hemesh.HE_Mesh.get(), wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.hemesh.HE_Vertex.getHalfedgeStar(), wblut.hemesh.HE_Selection.getNumberOfVertices(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Mesh.getVertexWithIndex(), wblut.hemesh.HE_Vertex.isBoundary(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Plane.localPoint(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Mesh.removeSelection(), wblut.hemesh.HE_Mesh.renameSelection(), wblut.geom.WB_Point.scaleSelf(), wblut.hemesh.HE_Mesh.selectAllFaces(), wblut.hemesh.HE_Mesh.selectBackVertices(), wblut.hemesh.HE_Mesh.selectFrontVertices(), wblut.hemesh.HE_Vertex.set(), wblut.hemesh.HEM_Slice.setCap(), wblut.hemesh.HEM_Slice.setOffset(), wblut.hemesh.HEM_Slice.setPlane(), wblut.hemesh.HEM_Slice.setReverse(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HE_Mesh.uncapBoundaryHalfedges(), and wblut.hemesh.HE_Mesh.vItr().
HE_Mesh wblut.hemesh.HEM_Mirror.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HEM_Mirror.applySelf().
static void wblut.hemesh.HEM_Mirror.main (final String[] args) static
References wblut.hemesh.HEM_Mirror.HEM_Mirror(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HEC_Cylinder.setFacets(), wblut.hemesh.HEC_Cylinder.setHeight(), wblut.hemesh.HEM_Mirror.setKeepLargest(), wblut.hemesh.HEM_Mirror.setOffset(), wblut.hemesh.HEM_Mirror.setPlane(), wblut.hemesh.HEC_Cylinder.setRadius(), wblut.hemesh.HEM_Mirror.setReverse(), and wblut.hemesh.HEC_Cylinder.setSteps().
HEM_Mirror wblut.hemesh.HEM_Mirror.setKeepLargest (final Boolean b)
HEM_Mirror wblut.hemesh.HEM_Mirror.setOffset (final double d)
Parameters
d
Returns
HEM_Mirror wblut.hemesh.HEM_Mirror.setPlane (final WB_Plane P)
Parameters
P
Returns
References wblut.hemesh.HEM_Mirror.P.
HEM_Mirror wblut.hemesh.HEM_Mirror.setPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
Set plane by origin and normal.
Parameters
ox
oy
oz
nx
ny
nz
Returns
HEM_Mirror wblut.hemesh.HEM_Mirror.setReverse (final Boolean b)
Parameters
b
Returns
Member Data Documentation
HE_Vertex [] wblut.hemesh.HEM_Mirror.boundaryPairs
boolean wblut.hemesh.HEM_Mirror.keepLargest = false private
double wblut.hemesh.HEM_Mirror.offset private
WB_Plane wblut.hemesh.HEM_Mirror.P private
HE_Vertex [] wblut.hemesh.HEM_Mirror.pairs
boolean wblut.hemesh.HEM_Mirror.reverse = false private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Mirror.java