HE_Mesh: wblut.hemesh.HEC_IsoSurface Class Reference
wblut.hemesh.HEC_IsoSurface Class Reference
Classes
class VertexRemap
Public Member Functions
HEC_IsoSurface ()
HEC_IsoSurface setGamma (final double gamma)
HEC_IsoSurface setResolution (final int resx, final int resy, final int resz)
HEC_IsoSurface setSize (final double dx, final double dy, final double dz)
HEC_IsoSurface setIsolevel (final double v)
HEC_IsoSurface setValueFactor (final WB_ScalarParameter v)
HEC_IsoSurface setValueShift (final WB_ScalarParameter v)
HEC_IsoSurface setValues (final double[][][] values)
HEC_IsoSurface setValues (final float[][][] values)
HEC_IsoSurface setValues (final WB_ScalarParameter function, final double xi, final double yi, final double zi, final double dx, final double dy, final double dz, final int sizeI, final int sizeJ, final int sizeK)
HEC_IsoSurface setValues (final WB_HashGridDouble values)
HEC_IsoSurface setValues (final String[] images, final PApplet home, final int sizeI, final int sizeJ, final int sizeK)
HEC_IsoSurface setValues (final String[] images, final PApplet home, final int sizeI, final int sizeJ, final int sizeK, final WB_IsoValues3D.Mode mode)
HEC_IsoSurface setValues (final WB_IsoValues3D values)
HEC_IsoSurface setBoundary (final double v)
HEC_IsoSurface clearBoundary ()
HEC_IsoSurface setInvert (final boolean invert)
HEC_IsoSurface setCenter (final WB_Coord c)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Static Public Member Functions
static void main (final String[] args)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Member Functions
void mapvertices ()
void polygonise ()
void getPolygons (final int i, final int j, final int k, final int cubeindex, final WB_Point offset, final boolean dummyrun)
int classifyCell (final int i, final int j, final int k)
HE_Vertex vertex (final int i, final int j, final int k, final WB_Point offset)
HE_Vertex xedge (final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun)
HE_Vertex yedge (final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun)
HE_Vertex zedge (final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun)
WB_Point interp (final double isolevel, final WB_Point p1, final WB_Point p2, final double valp1, final double valp2)
int index (final int i, final int j, final int k)
double value (final int i, final int j, final int k)
Private Attributes
WB_IsoValues3D values
int resx
double cx
double dx
double isolevel
double boundary
IntObjectHashMap< HE_Vertex > xedges
IntObjectHashMap< HE_Vertex > yedges
IntObjectHashMap< HE_Vertex > zedges
IntObjectHashMap< HE_Vertex > vertices
IntObjectHashMap< VertexRemap > vertexremaps
IntDoubleHashMap valueremaps
double gamma
boolean invert
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Constructor & Destructor Documentation
wblut.hemesh.HEC_IsoSurface.HEC_IsoSurface ()
References wblut.math.WB_ScalarParameter.ONE, and wblut.math.WB_ScalarParameter.ZERO.
Member Function Documentation
int wblut.hemesh.HEC_IsoSurface.classifyCell (final int i, final int j, final int k) private
Classify cell.
Parameters
i the i
j the j
k the k
Returns
the int
References wblut.hemesh.HEC_IsoSurface.isolevel, and wblut.hemesh.HEC_IsoSurface.value().
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.clearBoundary ()
Clear boundary level.
Returns
self
HE_Mesh wblut.hemesh.HEC_IsoSurface.createBase () protected
References wblut.hemesh.HE_Mesh.clean(), wblut.hemesh.HET_Fixer.fixNonManifoldVertices(), wblut.hemesh.HEC_IsoSurface.mapvertices(), and wblut.hemesh.HEC_IsoSurface.polygonise().
void wblut.hemesh.HEC_IsoSurface.getPolygons (final int i, final int j, final int k, final int cubeindex, final WB_Point offset, final boolean dummyrun) private
Gets the polygons.
Parameters
i the i
j the j
k the k
cubeindex the cubeindex
offset
dummyrun
Returns
the polygons
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setVertex().
int wblut.hemesh.HEC_IsoSurface.index (final int i, final int j, final int k) private
Parameters
i
j
k
Returns
WB_Point wblut.hemesh.HEC_IsoSurface.interp (final double isolevel, final WB_Point p1, final WB_Point p2, final double valp1, final double valp2) private
Interp.
Parameters
isolevel the isolevel
p1 the p1
p2 the p2
valp1 the valp1
valp2 the valp2
Returns
the h e_ vertex
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
static void wblut.hemesh.HEC_IsoSurface.main (final String[] args) static
References wblut.hemesh.HEC_IsoSurface.HEC_IsoSurface(), wblut.hemesh.HEC_IsoSurface.setBoundary(), wblut.hemesh.HEC_IsoSurface.setGamma(), wblut.hemesh.HEC_IsoSurface.setInvert(), wblut.hemesh.HEC_IsoSurface.setIsolevel(), wblut.hemesh.HEC_IsoSurface.setSize(), and wblut.hemesh.HEC_IsoSurface.setValues().
void wblut.hemesh.HEC_IsoSurface.mapvertices () private
References wblut.hemesh.HEC_IsoSurface.classifyCell(), wblut.hemesh.HEC_IsoSurface.getPolygons(), and wblut.hemesh.HEC_IsoSurface.resx.
void wblut.hemesh.HEC_IsoSurface.polygonise () private
Polygonise.
References wblut.hemesh.HEC_IsoSurface.classifyCell(), wblut.hemesh.HEC_IsoSurface.getPolygons(), and wblut.hemesh.HEC_IsoSurface.resx.
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setBoundary (final double v)
Boundary level.
Parameters
v boundary level
Returns
self
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setCenter (final WB_Coord c)
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setGamma (final double gamma)
Parameters
gamma
Returns
References wblut.hemesh.HEC_IsoSurface.gamma.
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setInvert (final boolean invert)
Invert isosurface.
Parameters
invert true/false
Returns
self
References wblut.hemesh.HEC_IsoSurface.invert.
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setIsolevel (final double v)
Isolevel to render.
Parameters
v isolevel
Returns
self
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setResolution (final int resx, final int resy, final int resz)
Number of cells.
Parameters
resx the resx
resy the resy
resz the resz
Returns
self
References wblut.hemesh.HEC_IsoSurface.resx.
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setSize (final double dx, final double dy, final double dz)
Size of cell.
Parameters
dx
dy
dz
Returns
self
References wblut.hemesh.HEC_IsoSurface.dx.
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setValueFactor (final WB_ScalarParameter v)
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setValues (final double values[][][])
Values at grid points.
Parameters
values double[resx+1][resy+1][resz+1]
Returns
self
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setValues (final float values[][][])
Sets the values.
Parameters
values float[resx+1][resy+1][resz+1]
Returns
self
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setValues (final WB_ScalarParameter function, final double xi, final double yi, final double zi, final double dx, final double dy, final double dz, final int sizeI, final int sizeJ, final int sizeK)
Parameters
function
xi
yi
zi
dx
dy
dz
Returns
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setValues (final WB_HashGridDouble values)
Parameters
values
Returns
References wblut.geom.WB_HashGridDouble.getSizeI(), wblut.geom.WB_HashGridDouble.getSizeJ(), and wblut.geom.WB_HashGridDouble.getSizeK().
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setValues (final String[] images, final PApplet home, final int sizeI, final int sizeJ, final int sizeK)
Parameters
images
home
sizeI
sizeJ
sizeK
Returns
References wblut.geom.WB_IsoValues3D.getSizeI(), wblut.geom.WB_IsoValues3D.getSizeJ(), and wblut.geom.WB_IsoValues3D.getSizeK().
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setValues (final String[] images, final PApplet home, final int sizeI, final int sizeJ, final int sizeK, final WB_IsoValues3D.Mode mode)
Parameters
images
home
sizeI
sizeJ
sizeK
mode
Returns
References wblut.geom.WB_IsoValues3D.getSizeI(), wblut.geom.WB_IsoValues3D.getSizeJ(), and wblut.geom.WB_IsoValues3D.getSizeK().
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setValues (final WB_IsoValues3D values)
References wblut.geom.WB_IsoValues3D.getSizeI(), wblut.geom.WB_IsoValues3D.getSizeJ(), wblut.geom.WB_IsoValues3D.getSizeK(), and wblut.hemesh.HEC_IsoSurface.values.
HEC_IsoSurface wblut.hemesh.HEC_IsoSurface.setValueShift (final WB_ScalarParameter v)
double wblut.hemesh.HEC_IsoSurface.value (final int i, final int j, final int k) private
Value.
Parameters
i the i
j the j
k the k
Returns
the double
References wblut.hemesh.HEC_IsoSurface.boundary, wblut.math.WB_ScalarParameter.evaluate(), wblut.geom.WB_IsoValues3D.getValue(), wblut.hemesh.HEC_IsoSurface.index(), and wblut.hemesh.HEC_IsoSurface.isolevel.
HE_Vertex wblut.hemesh.HEC_IsoSurface.vertex (final int i, final int j, final int k, final WB_Point offset) private
Parameters
i
j
k
offset
Returns
References wblut.hemesh.HE_Mesh.add(), wblut.geom.WB_Point.addSelf(), and wblut.hemesh.HEC_IsoSurface.index().
HE_Vertex wblut.hemesh.HEC_IsoSurface.xedge (final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun) private
Xedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
k k: -1 .. resz+1
offset
dummyrun
Returns
edge vertex
References wblut.hemesh.HE_Mesh.add(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HEC_IsoSurface.dx, wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HEC_IsoSurface.index(), wblut.hemesh.HEC_IsoSurface.interp(), wblut.hemesh.HEC_IsoSurface.value(), and wblut.hemesh.HEC_IsoSurface.vertex().
HE_Vertex wblut.hemesh.HEC_IsoSurface.yedge (final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun) private
Yedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
k k: -1 .. resz+1
offset
dummyrun
Returns
edge vertex
References wblut.hemesh.HE_Mesh.add(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HEC_IsoSurface.index(), wblut.hemesh.HEC_IsoSurface.interp(), wblut.hemesh.HEC_IsoSurface.value(), and wblut.hemesh.HEC_IsoSurface.vertex().
HE_Vertex wblut.hemesh.HEC_IsoSurface.zedge (final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun) private
Zedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
k k: -1 .. resz+1
offset
dummyrun
Returns
edge vertex
References wblut.hemesh.HE_Mesh.add(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HEC_IsoSurface.index(), wblut.hemesh.HEC_IsoSurface.interp(), wblut.hemesh.HEC_IsoSurface.value(), and wblut.hemesh.HEC_IsoSurface.vertex().
Member Data Documentation
double wblut.hemesh.HEC_IsoSurface.boundary private
double wblut.hemesh.HEC_IsoSurface.cx private
double wblut.hemesh.HEC_IsoSurface.dx private
double wblut.hemesh.HEC_IsoSurface.gamma private
boolean wblut.hemesh.HEC_IsoSurface.invert private
double wblut.hemesh.HEC_IsoSurface.isolevel private
int wblut.hemesh.HEC_IsoSurface.resx private
IntDoubleHashMap wblut.hemesh.HEC_IsoSurface.valueremaps private
WB_IsoValues3D wblut.hemesh.HEC_IsoSurface.values private
IntObjectHashMap<VertexRemap> wblut.hemesh.HEC_IsoSurface.vertexremaps private
IntObjectHashMap<HE_Vertex> wblut.hemesh.HEC_IsoSurface.vertices private
IntObjectHashMap<HE_Vertex> wblut.hemesh.HEC_IsoSurface.xedges private
IntObjectHashMap<HE_Vertex> wblut.hemesh.HEC_IsoSurface.yedges private
IntObjectHashMap<HE_Vertex> wblut.hemesh.HEC_IsoSurface.zedges private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_IsoSurface.java