HE_Mesh: wblut.geom.WB_Geodesic Class Reference
wblut.geom.WB_Geodesic Class Reference
Classes
enum Type
Public Member Functions
WB_Geodesic (final double radius, final int b, final int c)
WB_Geodesic (final double radius, final int b, final int c, final Type type)
WB_Mesh create ()
Static Public Member Functions
static WB_GreatCircleIntersection getGreatCircleIntersection (final WB_Coord v1, final WB_Coord v2, final WB_Coord v3, final WB_Coord v4)
static double[] getPointOnGreatCircle (final WB_Coord v1, final WB_Coord v2, final double f)
Private Member Functions
void createMesh ()
Static Private Member Functions
static WB_Vector vnor (final WB_Coord v1, final WB_Coord v2, final WB_Coord v3)
static double vcos (final WB_Coord v1, final WB_Coord v2, final WB_Coord v3)
Private Attributes
WB_Mesh mesh
final double radius
final Type type
final int b
final int c
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.geom.WB_Geodesic.WB_Geodesic (final double radius, final int b, final int c)
Parameters
radius
b
c
References wblut.geom.WB_Geodesic.b, wblut.geom.WB_Geodesic.c, wblut.geom.WB_Geodesic.Type.ICOSAHEDRON, and wblut.geom.WB_Geodesic.radius.
wblut.geom.WB_Geodesic.WB_Geodesic (final double radius, final int b, final int c, final Type type)
Parameters
radius
b
c
type
References wblut.geom.WB_Geodesic.b, wblut.geom.WB_Geodesic.c, wblut.geom.WB_Geodesic.radius, and wblut.geom.WB_Geodesic.type.
Member Function Documentation
WB_Mesh wblut.geom.WB_Geodesic.create ()
Returns
Implements wblut.geom.WB_MeshCreator.
References wblut.geom.WB_Geodesic.createMesh(), and wblut.geom.WB_Geodesic.mesh.
void wblut.geom.WB_Geodesic.createMesh () private
References wblut.geom.WB_Geodesic.Type.CUBE, and wblut.geom.WB_Geodesic.Type.DODECAHEDRON.
static WB_GreatCircleIntersection wblut.geom.WB_Geodesic.getGreatCircleIntersection (final WB_Coord v1, final WB_Coord v2, final WB_Coord v3, final WB_Coord v4) static
Parameters
v1
v2
v3
v4
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.coords(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_Vector.dot(), wblut.geom.WB_Vector.getLength(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Point.mul(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Geodesic.vnor().
static double [] wblut.geom.WB_Geodesic.getPointOnGreatCircle (final WB_Coord v1, final WB_Coord v2, final double f) static
Parameters
v1
v2
f
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_Point.coords(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_Point.mul(), and wblut.geom.WB_Geodesic.vcos().
static double wblut.geom.WB_Geodesic.vcos (final WB_Coord v1, final WB_Coord v2, final WB_Coord v3) static private
Parameters
v1
v2
v3
Returns
References wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Vector.getLength().
static WB_Vector wblut.geom.WB_Geodesic.vnor (final WB_Coord v1, final WB_Coord v2, final WB_Coord v3) static private
Parameters
v1
v2
v3
Returns
References wblut.geom.WB_Vector.cross().
Member Data Documentation
final int wblut.geom.WB_Geodesic.b private
final int wblut.geom.WB_Geodesic.c private
WB_GeometryFactory wblut.geom.WB_Geodesic.gf = new WB_GeometryFactory() static private
WB_Mesh wblut.geom.WB_Geodesic.mesh private
final double wblut.geom.WB_Geodesic.radius private
final Type wblut.geom.WB_Geodesic.type private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Geodesic.java