HE_Mesh: wblut.geom.WB_PolygonDecomposer Class Reference
wblut.geom.WB_PolygonDecomposer Class Reference
Static Public Member Functions
static List< WB_Polygon > decomposePolygon2D (WB_Polygon polygon)
Static Private Member Functions
static void decomposePolygon (final List< WB_Coord > pointlist, final List< WB_Polygon > accumulator)
static void decomposePolygon (final WB_CoordCollection pointlist, final List< WB_Polygon > accumulator)
static boolean isVisible (final WB_CoordCollection pointlist, final int i, final int j)
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Detailed Description
Mark Bayazit's algorithm for concave polygon decomposition https://mpen.ca/406/bayazit
Member Function Documentation
static void wblut.geom.WB_PolygonDecomposer.decomposePolygon (final List< WB_Coord > pointlist, final List< WB_Polygon > accumulator) static private
References wblut.geom.WB_CoordCollection.getCollection().
static void wblut.geom.WB_PolygonDecomposer.decomposePolygon (final WB_CoordCollection pointlist, final List< WB_Polygon > accumulator) static private
References wblut.geom.WB_Point.add(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory2D.createSimplePolygon(), wblut.geom.WB_PolygonDecomposer.decomposePolygon(), wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_GeometryOp2D.getLineIntersectionInto2D(), wblut.geom.WB_Vector.getSqDistance2D(), wblut.geom.WB_GeometryOp2D.isLeftStrict2D(), wblut.geom.WB_GeometryOp2D.isReflex2D(), wblut.geom.WB_GeometryOp2D.isRight2D(), wblut.geom.WB_GeometryOp2D.isRightStrict2D(), wblut.geom.WB_PolygonDecomposer.isVisible(), wblut.geom.WB_Point.mulSelf(), wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_CoordCollection.size(), and wblut.geom.WB_CoordCollection.subList().
static List<WB_Polygon> wblut.geom.WB_PolygonDecomposer.decomposePolygon2D (WB_Polygon polygon) static
Decompose the given polygon into a reasonably small number of convex polygons. Additional points can be introduced by the algorithm. There is no guarantee that the number of polygons is optimal.
Parameters
polygon input polygon
Returns
List<WB_Polygon>
References wblut.geom.WB_GeometryFactory2D.createSimplePolygon(), wblut.geom.WB_PolygonDecomposer.decomposePolygon(), wblut.geom.WB_Polygon.getNumberOfShellPoints(), wblut.geom.WB_TriangleGenerator.getPoints(), and wblut.geom.WB_Polygon.isSimple().
static boolean wblut.geom.WB_PolygonDecomposer.isVisible (final WB_CoordCollection pointlist, final int i, final int j) static private
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_GeometryOp2D.getSegmentIntersection2D(), wblut.geom.WB_GeometryOp2D.isLeft2D(), wblut.geom.WB_GeometryOp2D.isReflex2D(), wblut.geom.WB_GeometryOp2D.isRight2D(), and wblut.geom.WB_CoordCollection.size().
Member Data Documentation
WB_GeometryFactory wblut.geom.WB_PolygonDecomposer.gf = new WB_GeometryFactory() static private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_PolygonDecomposer.java