HE_Mesh: wblut.hemesh.HEC_ChamferBox Class Reference
wblut.hemesh.HEC_ChamferBox Class Reference
Public Member Functions
HEC_ChamferBox ()
HEC_ChamferBox (final double W, final double H, final double D, final double CW, final double CH, final double CD, final int L, final int M, final int N)
HEC_ChamferBox (final double x, final double y, final double z, final double W, final double H, final double D, final double CW, final double CH, final double CD, final int L, final int M, final int N)
HEC_ChamferBox (final WB_Coord center, final double W, final double H, final double D, final double CW, final double CH, final double CD, final int L, final int M, final int N)
HEC_ChamferBox setSegments (final int L, final int M, final int N)
HEC_ChamferBox setWidth (final double W)
HEC_ChamferBox setHeight (final double H)
HEC_ChamferBox setDepth (final double D)
HEC_ChamferBox setWidthSegments (final int L)
HEC_ChamferBox setHeightSegments (final int M)
HEC_ChamferBox setDepthSegments (final int N)
HEC_ChamferBox setChamfer (final double c)
HEC_ChamferBox setChamfer (final double CW, final double CH, final double CD)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Static Public Member Functions
static void main (final String[] args)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Attributes
double W
double H
double D
int L
int M
int N
double CW
double CH
double CD
double IW
double IH
double ID
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Axis Aligned Box.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_ChamferBox.HEC_ChamferBox ()
Create a placeholder box.
wblut.hemesh.HEC_ChamferBox.HEC_ChamferBox (final double W, final double H, final double D, final double CW, final double CH, final double CD, final int L, final int M, final int N)
Create a box at (0,0,0).
Parameters
W width (X)
H height (Y)
D depth (Z)
CW chamfer width (X)
CH chamfer height (Y)
CD chamfer depth (Z)
L number of width divisions
M number of height divisions
N number of depth divisions
References wblut.hemesh.HEC_ChamferBox.CD, wblut.hemesh.HEC_ChamferBox.CH, wblut.hemesh.HEC_ChamferBox.CW, wblut.hemesh.HEC_ChamferBox.D, wblut.hemesh.HEC_ChamferBox.H, and wblut.hemesh.HEC_ChamferBox.W.
wblut.hemesh.HEC_ChamferBox.HEC_ChamferBox (final double x, final double y, final double z, final double W, final double H, final double D, final double CW, final double CH, final double CD, final int L, final int M, final int N)
Create a box at (x,y,z).
Parameters
x x-ordinate of center
y y-ordinate of center
z z-ordinate of center
W width (X)
H height (Y)
D depth (Z)
CW chamfer width (X)
CH chamfer height (Y)
CD chamfer depth (Z)
L number of width divisions
M number of height divisions
N number of depth divisions
References wblut.hemesh.HEC_ChamferBox.CD, wblut.hemesh.HEC_ChamferBox.CH, wblut.hemesh.HEC_ChamferBox.CW, wblut.hemesh.HEC_ChamferBox.D, wblut.hemesh.HEC_ChamferBox.H, wblut.hemesh.HEC_Creator.setCenter(), and wblut.hemesh.HEC_ChamferBox.W.
wblut.hemesh.HEC_ChamferBox.HEC_ChamferBox (final WB_Coord center, final double W, final double H, final double D, final double CW, final double CH, final double CD, final int L, final int M, final int N)
Create a box at center.
Parameters
center center
W width (X)
H height (Y)
D depth (Z)
CW chamfer width (X)
CH chamfer height (Y)
CD chamfer depth (Z)
L number of width divisions
M number of height divisions
N number of depth divisions
References wblut.hemesh.HEC_ChamferBox.CD, wblut.hemesh.HEC_ChamferBox.CH, wblut.hemesh.HEC_ChamferBox.CW, wblut.hemesh.HEC_ChamferBox.D, wblut.hemesh.HEC_ChamferBox.H, wblut.hemesh.HEC_Creator.setCenter(), wblut.hemesh.HEC_ChamferBox.W, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_ChamferBox.createBase () protected
References wblut.hemesh.HEC_ChamferBox.CD, wblut.hemesh.HEC_ChamferBox.CH, wblut.hemesh.HEC_FromFacelist.createBase(), wblut.hemesh.HEC_ChamferBox.CW, wblut.hemesh.HEC_ChamferBox.D, wblut.hemesh.HEC_ChamferBox.H, wblut.hemesh.HEC_ChamferBox.ID, wblut.hemesh.HEC_ChamferBox.IH, wblut.hemesh.HEC_ChamferBox.IW, wblut.hemesh.HEC_ChamferBox.L, wblut.hemesh.HEC_ChamferBox.M, wblut.hemesh.HEC_ChamferBox.N, wblut.hemesh.HEC_FromFacelist.setDuplicate(), wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HEC_FromFacelist.setFaceTextureIds(), wblut.hemesh.HEC_FromFacelist.setVertexUVW(), wblut.hemesh.HEC_FromFacelist.setVertices(), and wblut.hemesh.HEC_ChamferBox.W.
static void wblut.hemesh.HEC_ChamferBox.main (final String[] args) static
References wblut.hemesh.HEC_ChamferBox.HEC_ChamferBox(), wblut.hemesh.HEC_ChamferBox.setDepth(), wblut.hemesh.HEC_ChamferBox.setDepthSegments(), wblut.hemesh.HEC_ChamferBox.setHeight(), wblut.hemesh.HEC_ChamferBox.setHeightSegments(), wblut.hemesh.HEC_ChamferBox.setWidth(), and wblut.hemesh.HEC_ChamferBox.setWidthSegments().
HEC_ChamferBox wblut.hemesh.HEC_ChamferBox.setChamfer (final double c)
HEC_ChamferBox wblut.hemesh.HEC_ChamferBox.setChamfer (final double CW, final double CH, final double CD)
References wblut.hemesh.HEC_ChamferBox.CD, wblut.hemesh.HEC_ChamferBox.CH, and wblut.hemesh.HEC_ChamferBox.CW.
HEC_ChamferBox wblut.hemesh.HEC_ChamferBox.setDepth (final double D)
Set box depth.
Parameters
D depth of box (z-axis)
Returns
self
References wblut.hemesh.HEC_ChamferBox.D.
HEC_ChamferBox wblut.hemesh.HEC_ChamferBox.setDepthSegments (final int N)
Set box depth segments.
Parameters
N number of depth segments (z-axis)
Returns
self
HEC_ChamferBox wblut.hemesh.HEC_ChamferBox.setHeight (final double H)
Set box height.
Parameters
H height of box (y-axis)
Returns
self
References wblut.hemesh.HEC_ChamferBox.H.
HEC_ChamferBox wblut.hemesh.HEC_ChamferBox.setHeightSegments (final int M)
Set box height segments.
Parameters
M number of height segments (y-axis)
Returns
self
HEC_ChamferBox wblut.hemesh.HEC_ChamferBox.setSegments (final int L, final int M, final int N)
Parameters
L
M
N
Returns
References wblut.hemesh.HEC_ChamferBox.L, wblut.hemesh.HEC_ChamferBox.M, and wblut.hemesh.HEC_ChamferBox.N.
HEC_ChamferBox wblut.hemesh.HEC_ChamferBox.setWidth (final double W)
Set box width.
Parameters
W width of box (x-axis)
Returns
self
References wblut.hemesh.HEC_ChamferBox.W.
HEC_ChamferBox wblut.hemesh.HEC_ChamferBox.setWidthSegments (final int L)
Set box width segments.
Parameters
L number of width segments (x-axis)
Returns
self
Member Data Documentation
double wblut.hemesh.HEC_ChamferBox.CD private
chamfer depth.
double wblut.hemesh.HEC_ChamferBox.CH private
chamfer height.
double wblut.hemesh.HEC_ChamferBox.CW private
chamfer width.
double wblut.hemesh.HEC_ChamferBox.D private
depth.
double wblut.hemesh.HEC_ChamferBox.H private
height.
double wblut.hemesh.HEC_ChamferBox.ID private
inner depth.
double wblut.hemesh.HEC_ChamferBox.IH private
inner height.
double wblut.hemesh.HEC_ChamferBox.IW private
inner width.
int wblut.hemesh.HEC_ChamferBox.L private
width segments.
int wblut.hemesh.HEC_ChamferBox.M private
height segments.
int wblut.hemesh.HEC_ChamferBox.N private
depth segments.
double wblut.hemesh.HEC_ChamferBox.W private
width.
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_ChamferBox.java