HE_Mesh: wblut.hemesh.HE_TextureCoordinate Class Reference
wblut.hemesh.HE_TextureCoordinate Class Reference
Public Member Functions
HE_TextureCoordinate ()
HE_TextureCoordinate (final WB_Coord uvw)
HE_TextureCoordinate (final double f, final HE_TextureCoordinate uvw1, final HE_TextureCoordinate uvw2)
HE_TextureCoordinate (final double u, final double v)
HE_TextureCoordinate (final double u, final double v, final double w)
void clear ()
double ud ()
double vd ()
double wd ()
float uf ()
float vf ()
float wf ()
void setUVW (final double u, final double v, final double w)
void setUVW (final WB_Coord u)
String toString ()
double xd ()
double yd ()
double zd ()
double getd (final int i)
float xf ()
float yf ()
float zf ()
float getf (final int i)
void setX (final double x)
void setY (final double y)
void setZ (final double z)
void setW (final double w)
void setCoord (final int i, final double v)
void set (final WB_Coord p)
void set (final double x, final double y)
void set (final double x, final double y, final double z)
void set (final double x, final double y, final double z, final double w)
int compareTo (final WB_Coord p)
boolean equals (final Object o)
Public Member Functions inherited from wblut.geom.WB_MutableCoord
void setX (double x)
void setY (double y)
void setZ (double z)
void setW (double w)
void setCoord (int i, double v)
void set (WB_Coord p)
void set (double x, double y)
void set (double x, double y, double z)
void set (double x, double y, double z, double w)
Public Member Functions inherited from wblut.geom.WB_Coord
double getd (int i)
float getf (int i)
Static Public Attributes
static final HE_TextureCoordinate ZERO = new HE_TextureCoordinate()
Private Attributes
double u
Constructor & Destructor Documentation
wblut.hemesh.HE_TextureCoordinate.HE_TextureCoordinate ()
wblut.hemesh.HE_TextureCoordinate.HE_TextureCoordinate (final WB_Coord uvw)
Parameters
uvw
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
wblut.hemesh.HE_TextureCoordinate.HE_TextureCoordinate (final double f, final HE_TextureCoordinate uvw1, final HE_TextureCoordinate uvw2)
Parameters
f
uvw1
uvw2
References wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), and wblut.hemesh.HE_TextureCoordinate.wd().
wblut.hemesh.HE_TextureCoordinate.HE_TextureCoordinate (final double u, final double v)
Parameters
u
v
References wblut.hemesh.HE_TextureCoordinate.u.
wblut.hemesh.HE_TextureCoordinate.HE_TextureCoordinate (final double u, final double v, final double w)
Parameters
u
v
w
References wblut.hemesh.HE_TextureCoordinate.u.
Member Function Documentation
void wblut.hemesh.HE_TextureCoordinate.clear ()
int wblut.hemesh.HE_TextureCoordinate.compareTo (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_Coord.wd(), wblut.hemesh.HE_TextureCoordinate.wd(), wblut.geom.WB_Coord.xd(), wblut.hemesh.HE_TextureCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.hemesh.HE_TextureCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.hemesh.HE_TextureCoordinate.zd().
boolean wblut.hemesh.HE_TextureCoordinate.equals (final Object o)
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_Coord.xd(), wblut.hemesh.HE_TextureCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.hemesh.HE_TextureCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.hemesh.HE_TextureCoordinate.zd().
double wblut.hemesh.HE_TextureCoordinate.getd (final int i)
References wblut.hemesh.HE_TextureCoordinate.u.
float wblut.hemesh.HE_TextureCoordinate.getf (final int i)
References wblut.hemesh.HE_TextureCoordinate.u.
void wblut.hemesh.HE_TextureCoordinate.set (final WB_Coord p)
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.hemesh.HE_TextureCoordinate.set (final double x, final double y)
void wblut.hemesh.HE_TextureCoordinate.set (final double x, final double y, final double z)
void wblut.hemesh.HE_TextureCoordinate.set (final double x, final double y, final double z, final double w)
void wblut.hemesh.HE_TextureCoordinate.setCoord (final int i, final double v)
void wblut.hemesh.HE_TextureCoordinate.setUVW (final double u, final double v, final double w)
Parameters
u
v
w
References wblut.hemesh.HE_TextureCoordinate.u.
void wblut.hemesh.HE_TextureCoordinate.setUVW (final WB_Coord u)
Parameters
u
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.hemesh.HE_TextureCoordinate.setW (final double w)
void wblut.hemesh.HE_TextureCoordinate.setX (final double x)
void wblut.hemesh.HE_TextureCoordinate.setY (final double y)
void wblut.hemesh.HE_TextureCoordinate.setZ (final double z)
String wblut.hemesh.HE_TextureCoordinate.toString ()
References wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), and wblut.hemesh.HE_TextureCoordinate.wd().
double wblut.hemesh.HE_TextureCoordinate.ud ()
Returns
References wblut.hemesh.HE_TextureCoordinate.u.
float wblut.hemesh.HE_TextureCoordinate.uf ()
Returns
References wblut.hemesh.HE_TextureCoordinate.u.
double wblut.hemesh.HE_TextureCoordinate.vd ()
Returns
float wblut.hemesh.HE_TextureCoordinate.vf ()
Returns
double wblut.hemesh.HE_TextureCoordinate.wd ()
Get w as double.
Returns
w
Implements wblut.geom.WB_Coord.
float wblut.hemesh.HE_TextureCoordinate.wf ()
Get w as float.
Returns
w
Implements wblut.geom.WB_Coord.
double wblut.hemesh.HE_TextureCoordinate.xd ()
Get x as double.
Returns
x
Implements wblut.geom.WB_Coord.
References wblut.hemesh.HE_TextureCoordinate.u.
float wblut.hemesh.HE_TextureCoordinate.xf ()
Get x as float.
Returns
x
Implements wblut.geom.WB_Coord.
References wblut.hemesh.HE_TextureCoordinate.u.
double wblut.hemesh.HE_TextureCoordinate.yd ()
Get y as double.
Returns
y
Implements wblut.geom.WB_Coord.
float wblut.hemesh.HE_TextureCoordinate.yf ()
Get y as float.
Returns
y
Implements wblut.geom.WB_Coord.
double wblut.hemesh.HE_TextureCoordinate.zd ()
Get z as double.
Returns
z
Implements wblut.geom.WB_Coord.
float wblut.hemesh.HE_TextureCoordinate.zf ()
Get z as float.
Returns
z
Implements wblut.geom.WB_Coord.
Member Data Documentation
double wblut.hemesh.HE_TextureCoordinate.u private
final HE_TextureCoordinate wblut.hemesh.HE_TextureCoordinate.ZERO = new HE_TextureCoordinate() static
The documentation for this class was generated from the following file:
src/hemesh_core/wblut/hemesh/HE_TextureCoordinate.java