HE_Mesh: wblut.geom.WB_IsoSurface2D Class Reference
wblut.geom.WB_IsoSurface2D Class Reference
Classes
class VertexRemap
Public Member Functions
WB_IsoSurface2D ()
WB_IsoSurface2D setGamma (final double gamma)
WB_IsoSurface2D setResolution (final int resx, final int resy)
WB_IsoSurface2D setSize (final double dx, final double dy)
WB_IsoSurface2D setValues (final double[][] values)
WB_IsoSurface2D setValues (final float[][] values)
WB_IsoSurface2D setValues (final WB_ScalarParameter function, final double xi, final double yi, final double dx, final double dy, final int width, final int height)
WB_IsoSurface2D setValues (final WB_HashGridDouble2D values)
WB_IsoSurface2D setValues (final String path, final PApplet home, final int width, final int height)
WB_IsoSurface2D setValues (final String path, final PApplet home, final int width, final int height, final WB_IsoValues2D.Mode mode)
WB_IsoSurface2D setValues (final PImage image, final PApplet home, final int width, final int height)
WB_IsoSurface2D setValues (final PImage image, final PApplet home, final int width, final int height, final WB_IsoValues2D.Mode mode)
WB_IsoSurface2D setValues (final WB_IsoValues2D values)
WB_IsoSurface2D setIsolevel (final double v)
WB_IsoSurface2D setBoundary (final double v)
WB_IsoSurface2D clearBoundary ()
WB_IsoSurface2D setInvert (final boolean invert)
WB_IsoSurface2D setCenter (final WB_Coord c)
List< WB_Segment > getSegments ()
Static Public Member Functions
static void main (final String[] args)
Private Member Functions
void mapvertices ()
void setvalues ()
void polygonise ()
void snapvertices ()
List< WB_Segment > getPolygons (final int i, final int j, final int cubeindex, final WB_Point offset, final boolean dummyrun)
int classifyCell (final int i, final int j)
WB_Point getIsoVertex (final int isopointindex, final int i, final int j, final WB_Point offset, final boolean dummyrun)
WB_Point vertex (final int i, final int j, final WB_Point offset)
WB_Point xedge (final int i, final int j, final WB_Point offset, final boolean dummyrun)
WB_Point yedge (final int i, final int j, final WB_Point offset, final boolean dummyrun)
WB_Point interp (final double isolevel, final WB_Point p1, final WB_Point p2, final double valp1, final double valp2)
int index (final int i, final int j)
double value (final int i, final int j)
Private Attributes
int[][] entries
WB_IsoValues2D values
int resx
double cx
double dx
double isolevel
double boundary
IntObjectHashMap< WB_Point > xedges
IntObjectHashMap< WB_Point > yedges
IntObjectHashMap< WB_Point > vertices
IntObjectHashMap< VertexRemap > vertexremaps
IntDoubleHashMap valueremaps
double gamma
boolean invert
FastList< WB_Segment > segs
Constructor & Destructor Documentation
wblut.geom.WB_IsoSurface2D.WB_IsoSurface2D ()
Member Function Documentation
int wblut.geom.WB_IsoSurface2D.classifyCell (final int i, final int j) private
Parameters
i
j
Returns
References wblut.geom.WB_IsoSurface2D.isolevel, and wblut.geom.WB_IsoSurface2D.value().
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.clearBoundary ()
Clear boundary level.
Returns
self
WB_Point wblut.geom.WB_IsoSurface2D.getIsoVertex (final int isopointindex, final int i, final int j, final WB_Point offset, final boolean dummyrun) private
Parameters
isopointindex
i
j
offset
dummyrun
Returns
References wblut.geom.WB_IsoSurface2D.vertex(), wblut.geom.WB_IsoSurface2D.xedge(), and wblut.geom.WB_IsoSurface2D.yedge().
List<WB_Segment> wblut.geom.WB_IsoSurface2D.getPolygons (final int i, final int j, final int cubeindex, final WB_Point offset, final boolean dummyrun) private
Gets the polygons.
Parameters
i the i
j the j
cubeindex the cubeindex
offset
dummyrun
Returns
the polygons
References wblut.geom.WB_IsoSurface2D.getIsoVertex(), and wblut.geom.WB_IsoSurface2D.segs.
List<WB_Segment> wblut.geom.WB_IsoSurface2D.getSegments ()
References wblut.geom.WB_IsoSurface2D.mapvertices(), wblut.geom.WB_IsoSurface2D.polygonise(), wblut.geom.WB_IsoSurface2D.segs, wblut.geom.WB_IsoSurface2D.setvalues(), and wblut.geom.WB_IsoSurface2D.snapvertices().
int wblut.geom.WB_IsoSurface2D.index (final int i, final int j) private
Parameters
i
j
Returns
WB_Point wblut.geom.WB_IsoSurface2D.interp (final double isolevel, final WB_Point p1, final WB_Point p2, final double valp1, final double valp2) private
Interp.
Parameters
isolevel the isolevel
p1 the p1
p2 the p2
valp1 the valp1
valp2 the valp2
Returns
the h e_ vertex
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static void wblut.geom.WB_IsoSurface2D.main (final String[] args) static
References wblut.geom.WB_IsoSurface2D.getSegments(), wblut.geom.WB_IsoSurface2D.setBoundary(), wblut.geom.WB_IsoSurface2D.setGamma(), wblut.geom.WB_IsoSurface2D.setIsolevel(), wblut.geom.WB_IsoSurface2D.setResolution(), wblut.geom.WB_IsoSurface2D.setSize(), wblut.geom.WB_IsoSurface2D.setValues(), and wblut.geom.WB_IsoSurface2D.WB_IsoSurface2D().
void wblut.geom.WB_IsoSurface2D.mapvertices () private
References wblut.geom.WB_IsoSurface2D.classifyCell(), wblut.geom.WB_IsoSurface2D.getPolygons(), and wblut.geom.WB_IsoSurface2D.resx.
void wblut.geom.WB_IsoSurface2D.polygonise () private
Polygonise.
References wblut.geom.WB_IsoSurface2D.classifyCell(), wblut.geom.WB_IsoSurface2D.getPolygons(), and wblut.geom.WB_IsoSurface2D.resx.
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setBoundary (final double v)
Boundary level.
Parameters
v boundary level
Returns
self
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setCenter (final WB_Coord c)
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setGamma (final double gamma)
Parameters
gamma
Returns
References wblut.geom.WB_IsoSurface2D.gamma.
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setInvert (final boolean invert)
Invert isosurface.
Parameters
invert true/false
Returns
self
References wblut.geom.WB_IsoSurface2D.invert.
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setIsolevel (final double v)
Isolevel to render.
Parameters
v isolevel
Returns
self
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setResolution (final int resx, final int resy)
Number of cells.
Parameters
resx the resx
resy the resy
Returns
self
References wblut.geom.WB_IsoSurface2D.resx.
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setSize (final double dx, final double dy)
Size of cell.
Parameters
dx
dy
Returns
self
References wblut.geom.WB_IsoSurface2D.dx.
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setValues (final double values[][])
Values at grid points.
Parameters
values double[resx+1][resy+1]
Returns
self
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setValues (final float values[][])
Values at grid points.
Parameters
values float[resx+1][resy+1]
Returns
self
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setValues (final WB_ScalarParameter function, final double xi, final double yi, final double dx, final double dy, final int width, final int height)
Parameters
function
xi
yi
dx
dy
Returns
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setValues (final WB_HashGridDouble2D values)
Parameters
values
Returns
References wblut.geom.WB_HashGridDouble2D.getHeight(), and wblut.geom.WB_HashGridDouble2D.getWidth().
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setValues (final String path, final PApplet home, final int width, final int height)
Parameters
path
home
width
height
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), and wblut.geom.WB_IsoValues2D.getWidth().
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setValues (final String path, final PApplet home, final int width, final int height, final WB_IsoValues2D.Mode mode)
Parameters
path
home
width
height
mode
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), and wblut.geom.WB_IsoValues2D.getWidth().
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setValues (final PImage image, final PApplet home, final int width, final int height)
Parameters
image
home
width
height
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), and wblut.geom.WB_IsoValues2D.getWidth().
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setValues (final PImage image, final PApplet home, final int width, final int height, final WB_IsoValues2D.Mode mode)
Parameters
image
home
width
height
mode
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), and wblut.geom.WB_IsoValues2D.getWidth().
WB_IsoSurface2D wblut.geom.WB_IsoSurface2D.setValues (final WB_IsoValues2D values)
Parameters
values
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), wblut.geom.WB_IsoValues2D.getWidth(), and wblut.geom.WB_IsoSurface2D.values.
void wblut.geom.WB_IsoSurface2D.setvalues () private
References wblut.geom.WB_IsoSurface2D.index().
void wblut.geom.WB_IsoSurface2D.snapvertices () private
double wblut.geom.WB_IsoSurface2D.value (final int i, final int j) private
Value.
Parameters
i i
j j
Returns
double
References wblut.geom.WB_IsoSurface2D.boundary, wblut.geom.WB_IsoSurface2D.index(), wblut.geom.WB_IsoSurface2D.isolevel, and wblut.geom.WB_IsoValues2D.value().
WB_Point wblut.geom.WB_IsoSurface2D.vertex (final int i, final int j, final WB_Point offset) private
Parameters
i
j
offset
Returns
References wblut.geom.WB_Point.addSelf(), and wblut.geom.WB_IsoSurface2D.index().
WB_Point wblut.geom.WB_IsoSurface2D.xedge (final int i, final int j, final WB_Point offset, final boolean dummyrun) private
Xedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
offset
dummyrun
Returns
edge vertex
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_IsoSurface2D.dx, wblut.geom.WB_IsoSurface2D.index(), wblut.geom.WB_IsoSurface2D.interp(), wblut.geom.WB_IsoSurface2D.value(), and wblut.geom.WB_IsoSurface2D.vertex().
WB_Point wblut.geom.WB_IsoSurface2D.yedge (final int i, final int j, final WB_Point offset, final boolean dummyrun) private
Yedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
offset
dummyrun
Returns
edge vertex
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_IsoSurface2D.index(), wblut.geom.WB_IsoSurface2D.interp(), wblut.geom.WB_IsoSurface2D.value(), and wblut.geom.WB_IsoSurface2D.vertex().
Member Data Documentation
double wblut.geom.WB_IsoSurface2D.boundary private
double wblut.geom.WB_IsoSurface2D.cx private
double wblut.geom.WB_IsoSurface2D.dx private
int [][] wblut.geom.WB_IsoSurface2D.entries private
double wblut.geom.WB_IsoSurface2D.gamma private
boolean wblut.geom.WB_IsoSurface2D.invert private
double wblut.geom.WB_IsoSurface2D.isolevel private
int wblut.geom.WB_IsoSurface2D.resx private
FastList<WB_Segment> wblut.geom.WB_IsoSurface2D.segs private
IntDoubleHashMap wblut.geom.WB_IsoSurface2D.valueremaps private
WB_IsoValues2D wblut.geom.WB_IsoSurface2D.values private
IntObjectHashMap<VertexRemap> wblut.geom.WB_IsoSurface2D.vertexremaps private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurface2D.vertices private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurface2D.xedges private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurface2D.yedges private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_IsoSurface2D.java