HE_Mesh: wblut.math.WB_Ease Class Reference
wblut.math.WB_Ease Class Reference abstract
Inherited by wblut.math.WB_Ease.EaseBack, wblut.math.WB_Ease.EaseBounce, wblut.math.WB_Ease.EaseCirc, wblut.math.WB_Ease.EaseCubic, wblut.math.WB_Ease.EaseElastic, wblut.math.WB_Ease.EaseExpo, wblut.math.WB_Ease.EaseLinear, wblut.math.WB_Ease.EaseQuad, wblut.math.WB_Ease.EaseQuart, wblut.math.WB_Ease.EaseQuint, and wblut.math.WB_Ease.EaseSine.
Classes
class EaseBack
class EaseBounce
class EaseCirc
class EaseCubic
class EaseElastic
class EaseExpo
class EaseLinear
class EaseQuad
class EaseQuart
class EaseQuint
class EaseSine
enum EaseType
Public Member Functions
abstract double easeIn (double t, double...parameters)
abstract double easeOut (double t, double...parameters)
abstract double easeInOut (double t, double...parameters)
abstract double easeIn (double t)
abstract double easeOut (double t)
abstract double easeInOut (double t)
double ease (final EaseType type, final double t, final double...params)
double ease (final EaseType type, final double t)
Static Public Member Functions
static WB_Ease getLinear ()
static WB_Ease getQuad ()
static WB_Ease getCubic ()
static WB_Ease getQuart ()
static WB_Ease getQuint ()
static WB_Ease getSine ()
static WB_Ease getExpo ()
static WB_Ease getCirc ()
static WB_Ease getBack ()
static WB_Ease getBack (final double s)
static WB_Ease getBounce ()
static WB_Ease getElastic ()
static WB_Ease getElastic (final double a, final double p)
Static Public Attributes
static WB_Ease linear = new EaseLinear()
static WB_Ease quad = new EaseQuad()
static WB_Ease cubic = new EaseCubic()
static WB_Ease quart = new EaseQuart()
static WB_Ease quint = new EaseQuint()
static WB_Ease sine = new EaseSine()
static WB_Ease expo = new EaseExpo()
static WB_Ease circ = new EaseCirc()
static WB_Ease back = new EaseBack()
static WB_Ease bounce = new EaseBounce()
static WB_Ease elastic = new EaseElastic()
Private Member Functions
WB_Ease ()
Static Private Attributes
static final double pmn = 1.70158
Detailed Description
Author
FVH
    Penning easing functions, straight translation of the umpteen
    implementations out there
    http://robertpenner.com/easing/
    TERMS OF USE - EASING EQUATIONS
    Open source under the BSD License.
    Copyright © 2001 Robert Penner All rights reserved.
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions
    are met:
    Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
    Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
    Neither the name of the author nor the names of contributors may be
    used to endorse or promote products derived from this software
    without specific prior written permission. THIS SOFTWARE IS PROVIDED
    BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
    IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
    ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
    OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
    BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
    WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
    OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
    EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Constructor & Destructor Documentation
wblut.math.WB_Ease.WB_Ease () private
Member Function Documentation
double wblut.math.WB_Ease.ease (final EaseType type, final double t, final double... params)
References wblut.math.WB_Ease.easeIn(), wblut.math.WB_Ease.easeInOut(), and wblut.math.WB_Ease.easeOut().
double wblut.math.WB_Ease.ease (final EaseType type, final double t)
References wblut.math.WB_Ease.easeIn(), wblut.math.WB_Ease.easeInOut(), and wblut.math.WB_Ease.easeOut().
abstract double wblut.math.WB_Ease.easeIn (double t, double... parameters) abstract
abstract double wblut.math.WB_Ease.easeIn (double t) abstract
abstract double wblut.math.WB_Ease.easeInOut (double t, double... parameters) abstract
abstract double wblut.math.WB_Ease.easeInOut (double t) abstract
abstract double wblut.math.WB_Ease.easeOut (double t, double... parameters) abstract
abstract double wblut.math.WB_Ease.easeOut (double t) abstract
static WB_Ease wblut.math.WB_Ease.getBack () static
static WB_Ease wblut.math.WB_Ease.getBack (final double s) static
static WB_Ease wblut.math.WB_Ease.getBounce () static
static WB_Ease wblut.math.WB_Ease.getCirc () static
static WB_Ease wblut.math.WB_Ease.getCubic () static
static WB_Ease wblut.math.WB_Ease.getElastic () static
static WB_Ease wblut.math.WB_Ease.getElastic (final double a, final double p) static
static WB_Ease wblut.math.WB_Ease.getExpo () static
static WB_Ease wblut.math.WB_Ease.getLinear () static
static WB_Ease wblut.math.WB_Ease.getQuad () static
static WB_Ease wblut.math.WB_Ease.getQuart () static
static WB_Ease wblut.math.WB_Ease.getQuint () static
static WB_Ease wblut.math.WB_Ease.getSine () static
Member Data Documentation
WB_Ease wblut.math.WB_Ease.back = new EaseBack() static
WB_Ease wblut.math.WB_Ease.bounce = new EaseBounce() static
WB_Ease wblut.math.WB_Ease.circ = new EaseCirc() static
WB_Ease wblut.math.WB_Ease.cubic = new EaseCubic() static
WB_Ease wblut.math.WB_Ease.elastic = new EaseElastic() static
WB_Ease wblut.math.WB_Ease.expo = new EaseExpo() static
WB_Ease wblut.math.WB_Ease.linear = new EaseLinear() static
final double wblut.math.WB_Ease.pmn = 1.70158 static private
WB_Ease wblut.math.WB_Ease.quad = new EaseQuad() static
WB_Ease wblut.math.WB_Ease.quart = new EaseQuart() static
WB_Ease wblut.math.WB_Ease.quint = new EaseQuint() static
WB_Ease wblut.math.WB_Ease.sine = new EaseSine() static
The documentation for this class was generated from the following file:
src/math/wblut/math/WB_Ease.java