HE_Mesh: wblut.geom.WB_AABBTree Class Reference
wblut.geom.WB_AABBTree Class Reference
Classes
class Entry
class EntryOrder
class WB_AABBNode
Public Member Functions
WB_AABBTree (final HE_Mesh mesh, final int mnof)
WB_AABBNode getRoot ()
int getDepth ()
WB_Coord getClosestPoint (final WB_Coord p)
HE_Face getClosestFace (final WB_Coord p)
Entry getClosestEntry (final WB_Coord p)
void expandBy (final double d)
Static Public Attributes
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Private Member Functions
void buildTree (final HE_Mesh mesh)
void buildNode (final WB_AABBNode node, final List< HE_Face > faces, final HE_Mesh mesh, final int level)
double findOptimalSubset (double bestSah, final WB_AABBNode node, final List< HE_Face > childA, final List< HE_Face > childB, final List< HE_Face > faces)
double addNode (final WB_Coord p, final WB_AABBNode node, final PriorityQueue< Entry > entries, double closest2)
Static Private Member Functions
static double getSAH (final double denom, final double surfaceAreaA, final int numA, final double surfaceAreaB, final int numB)
Private Attributes
WB_AABBNode root
final int maxLevel
int depth
final int maxNumberOfFaces
Constructor & Destructor Documentation
wblut.geom.WB_AABBTree.WB_AABBTree (final HE_Mesh mesh, final int mnof)
Parameters
mesh
mnof
References wblut.geom.WB_AABBTree.buildTree(), and wblut.hemesh.HE_Mesh.getNumberOfFaces().
Member Function Documentation
double wblut.geom.WB_AABBTree.addNode (final WB_Coord p, final WB_AABBNode node, final PriorityQueue< Entry > entries, double closest2) private
References wblut.geom.WB_AABBTree.WB_AABBNode.aabb, wblut.geom.WB_AABBTree.WB_AABBNode.faces, wblut.hemesh.HE_Face.getClosestPoint(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), and wblut.geom.WB_AABBTree.WB_AABBNode.isLeaf.
void wblut.geom.WB_AABBTree.buildNode (final WB_AABBNode node, final List< HE_Face > faces, final HE_Mesh mesh, final int level) private
Parameters
node
faces
mesh
level
References wblut.geom.WB_AABBTree.WB_AABBNode.aabb, wblut.geom.WB_AABBTree.WB_AABBNode.childA, wblut.geom.WB_AABBTree.WB_AABBNode.childB, wblut.geom.WB_AABB.expandToInclude(), wblut.geom.WB_AABBTree.WB_AABBNode.faces, wblut.geom.WB_AABBTree.findOptimalSubset(), wblut.geom.WB_AABBTree.WB_AABBNode.isLeaf, wblut.geom.WB_AABBTree.WB_AABBNode.level, wblut.geom.WB_AABBTree.maxNumberOfFaces, and wblut.core.WB_ProgressReporter.WB_ProgressTracker.setDuringStatus().
void wblut.geom.WB_AABBTree.buildTree (final HE_Mesh mesh) private
Parameters
mesh
References wblut.geom.WB_AABBTree.buildNode(), wblut.hemesh.HE_Mesh.getFaces(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), and wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus().
void wblut.geom.WB_AABBTree.expandBy (final double d)
References wblut.geom.WB_AABBTree.WB_AABBNode.expandBy().
double wblut.geom.WB_AABBTree.findOptimalSubset (double bestSah, final WB_AABBNode node, final List< HE_Face > childA, final List< HE_Face > childB, final List< HE_Face > faces) private
References wblut.geom.WB_AABB.expandToInclude(), wblut.geom.WB_AABBTree.WB_AABBNode.getAABB(), wblut.geom.WB_AABB.getArea(), and wblut.geom.WB_AABBTree.getSAH().
Entry wblut.geom.WB_AABBTree.getClosestEntry (final WB_Coord p)
References wblut.geom.WB_AABBTree.addNode(), wblut.geom.WB_AABBTree.WB_AABBNode.getChildA(), and wblut.geom.WB_AABBTree.WB_AABBNode.getChildB().
HE_Face wblut.geom.WB_AABBTree.getClosestFace (final WB_Coord p)
References wblut.geom.WB_AABBTree.addNode(), wblut.geom.WB_AABBTree.WB_AABBNode.getChildA(), and wblut.geom.WB_AABBTree.WB_AABBNode.getChildB().
WB_Coord wblut.geom.WB_AABBTree.getClosestPoint (final WB_Coord p)
References wblut.geom.WB_AABBTree.addNode(), wblut.geom.WB_AABBTree.WB_AABBNode.getChildA(), and wblut.geom.WB_AABBTree.WB_AABBNode.getChildB().
int wblut.geom.WB_AABBTree.getDepth ()
References wblut.geom.WB_AABBTree.depth.
WB_AABBNode wblut.geom.WB_AABBTree.getRoot ()
Returns
References wblut.geom.WB_AABBTree.root.
static double wblut.geom.WB_AABBTree.getSAH (final double denom, final double surfaceAreaA, final int numA, final double surfaceAreaB, final int numB) static private
Surface area heuristic
Parameters
denom
surfaceAreaA
numA
surfaceAreaB
numB
Returns
Member Data Documentation
int wblut.geom.WB_AABBTree.depth private
final int wblut.geom.WB_AABBTree.maxLevel private
final int wblut.geom.WB_AABBTree.maxNumberOfFaces private
WB_AABBNode wblut.geom.WB_AABBTree.root private
final WB_ProgressTracker wblut.geom.WB_AABBTree.tracker = WB_ProgressTracker.instance() static
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_AABBTree.java