HE_Mesh: wblut.hemesh.HEM_TriSplit Class Reference
wblut.hemesh.HEM_TriSplit Class Reference
Public Member Functions
HEM_TriSplit ()
HEM_TriSplit setOffset (final double d)
HE_Selection getSplitFaces ()
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Static Public Member Functions
static HE_Selection splitFaceTri (final HE_Mesh mesh, final HE_Face face, final WB_Coord p)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Member Functions
void splitFacesTri (final HE_Selection selection, final double d)
HE_Selection splitFaceTri (final HE_Face face, final double d, final HE_Mesh mesh)
Private Attributes
double d
HE_Selection selectionOut
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_TriSplit.HEM_TriSplit ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_TriSplit.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HEM_TriSplit.d, wblut.hemesh.HE_Mesh.selectAllFaces(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HEM_TriSplit.splitFacesTri(), and wblut.hemesh.HE_Machine.tracker.
HE_Mesh wblut.hemesh.HEM_TriSplit.applySelf (final HE_Selection selection) protected
References wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HEM_TriSplit.splitFacesTri(), and wblut.hemesh.HE_Machine.tracker.
HE_Selection wblut.hemesh.HEM_TriSplit.getSplitFaces ()
Returns
References wblut.hemesh.HEM_TriSplit.selectionOut.
HEM_TriSplit wblut.hemesh.HEM_TriSplit.setOffset (final double d)
Parameters
d
Returns
References wblut.hemesh.HEM_TriSplit.d.
void wblut.hemesh.HEM_TriSplit.splitFacesTri (final HE_Selection selection, final double d) private
Tri split faces with offset along face normal.
Parameters
selection face selection to split
d offset along face normal
Returns
selection of new faces and new vertex
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Selection.getFacesAsArray(), wblut.hemesh.HE_Selection.getNumberOfFaces(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.hemesh.HEM_TriSplit.splitFaceTri(), and wblut.hemesh.HE_Machine.tracker.
HE_Selection wblut.hemesh.HEM_TriSplit.splitFaceTri (final HE_Face face, final double d, final HE_Mesh mesh) private
Tri split face with offset along face normal.
Parameters
face face
d offset along face normal
mesh
Returns
selection of new faces and new vertex
References wblut.geom.WB_Point.addMul(), wblut.hemesh.HEM_TriSplit.d, wblut.hemesh.HE_Face.getFaceCenter(), and wblut.hemesh.HE_Face.getFaceNormal().
static HE_Selection wblut.hemesh.HEM_TriSplit.splitFaceTri (final HE_Mesh mesh, final HE_Face face, final WB_Coord p) static
Parameters
mesh
face
p
Returns
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Face.copyProperties(), wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getHalfedgeCenter(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getUVW(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.hasHalfedgeUVW(), wblut.hemesh.HE_Vertex.hasUVW(), wblut.math.WB_Epsilon.isZero(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Vertex.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), and wblut.hemesh.HE_TextureCoordinate.wd().
Member Data Documentation
double wblut.hemesh.HEM_TriSplit.d private
HE_Selection wblut.hemesh.HEM_TriSplit.selectionOut private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_TriSplit.java