HE_Mesh: wblut.hemesh.HES_DooSabin Class Reference
wblut.hemesh.HES_DooSabin Class Reference
Public Member Functions
HES_DooSabin ()
HES_DooSabin setFactors (final double ff, final double ef)
HES_DooSabin setAbsolute (final boolean b)
HES_DooSabin setDistance (final double d)
Public Member Functions inherited from wblut.hemesh.HES_Subdividor
HES_Subdividor ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Public Attributes
HE_Selection faceFaces
HE_Selection edgeFaces
HE_Selection vertexFaces
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HES_Subdividor
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
double faceFactor
double edgeFactor
boolean absolute
double d
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HES_DooSabin.HES_DooSabin ()
Member Function Documentation
HE_Mesh wblut.hemesh.HES_DooSabin.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Point.add(), wblut.hemesh.HE_Selection.add(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HEC_Creator.create(), wblut.geom.WB_Point.divSelf(), wblut.hemesh.HES_DooSabin.edgeFactor, wblut.hemesh.HE_Mesh.eItr(), wblut.hemesh.HES_DooSabin.faceFactor, wblut.hemesh.HE_Mesh.fItr(), wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getHalfedgeCenter(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Selection.getNumberOfEdges(), wblut.hemesh.HE_Mesh.getNumberOfEdges(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Vertex.getVertexDegree(), wblut.math.WB_Epsilon.isZero(), wblut.hemesh.HE_Halfedge.key(), wblut.geom.WB_Vector.mul(), wblut.geom.WB_Point.mul(), wblut.geom.WB_Point.mulSelf(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_Mesh.selectBoundaryEdges(), wblut.hemesh.HEC_FromFacelist.setDuplicate(), wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HEC_FromFacelist.setVertices(), wblut.geom.WB_Point.subSelf(), and wblut.hemesh.HE_Mesh.vItr().
HE_Mesh wblut.hemesh.HES_DooSabin.applySelf (final HE_Selection selection) protected
HES_DooSabin wblut.hemesh.HES_DooSabin.setAbsolute (final boolean b)
Parameters
b
Returns
HES_DooSabin wblut.hemesh.HES_DooSabin.setDistance (final double d)
Parameters
d
Returns
References wblut.hemesh.HES_DooSabin.d.
HES_DooSabin wblut.hemesh.HES_DooSabin.setFactors (final double ff, final double ef)
Parameters
ff
ef
Returns
Member Data Documentation
boolean wblut.hemesh.HES_DooSabin.absolute private
double wblut.hemesh.HES_DooSabin.d private
HE_Selection wblut.hemesh.HES_DooSabin.edgeFaces
double wblut.hemesh.HES_DooSabin.edgeFactor private
HE_Selection wblut.hemesh.HES_DooSabin.faceFaces
double wblut.hemesh.HES_DooSabin.faceFactor private
HE_Selection wblut.hemesh.HES_DooSabin.vertexFaces
The documentation for this class was generated from the following file:
src/hemesh_subdividors/wblut/hemesh/HES_DooSabin.java