HE_Mesh: wblut.geom.WB_KDTree2D< T extends WB_Coord, V > Class Template Reference
wblut.geom.WB_KDTree2D< T extends WB_Coord, V > Class Template Reference
Classes
class QueryResult
class WB_KDEntry
class WB_KDNode
Public Member Functions
WB_KDTree2D ()
WB_KDTree2D (final int binsize)
List< WB_AABB2D > getLeafBounds ()
List< WB_AABB2D > getAllBounds ()
List< WB_AABB2D > getLeafRegions ()
List< WB_AABB2D > getAllRegions ()
V add (final T coord, final V val)
WB_KDEntry< T, V >[] getRange (final WB_AABB2D aabb)
WB_KDEntry< T, V >[] getRange (final WB_Coord center, final double radius)
WB_KDEntry< T, V >[] getRange (final WB_Coord center, final double lower, final double upper)
WB_KDEntry< T, V >[] getNearestNeighbors (final WB_Coord coord, final int num)
WB_KDEntry< T, V > getNearestNeighbor (final WB_Coord coord)
WB_KDEntry< T, V > getNearestNeighbor (final double x, final double y)
Private Attributes
final int _dim
final int _maximumBinSize
final WB_KDNode< T, V > root
Detailed Description
Class WB_KDTree.
Parameters
<T> generic type
<V> value type
Constructor & Destructor Documentation
wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.WB_KDTree2D ()
wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.WB_KDTree2D (final int binsize)
Parameters
binsize
Member Function Documentation
V wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.add (final T coord, final V val)
Parameters
coord
val
Returns
References wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.WB_KDNode< T extends WB_Coord, V >.add().
List<WB_AABB2D> wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.getAllBounds ()
Returns
References wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.WB_KDNode< T extends WB_Coord, V >.addBox().
List<WB_AABB2D> wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.getAllRegions ()
Get all regions.
Returns
all regions
References wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.WB_KDNode< T extends WB_Coord, V >.addRegion().
List<WB_AABB2D> wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.getLeafBounds ()
Returns
References wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.WB_KDNode< T extends WB_Coord, V >.addLeafBounds().
List<WB_AABB2D> wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.getLeafRegions ()
Get the leaf regions.
Returns
leaf regions
References wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.WB_KDNode< T extends WB_Coord, V >.addLeafRegion().
WB_KDEntry<T, V> wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.getNearestNeighbor (final WB_Coord coord)
Parameters
coord
Returns
References wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.QueryResult< T extends WB_Coord, V >.entries, and wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.WB_KDNode< T extends WB_Coord, V >.findNearest().
WB_KDEntry<T, V> wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.getNearestNeighbor (final double x, final double y)
Parameters
x
y
Returns
References wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.QueryResult< T extends WB_Coord, V >.entries, and wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.WB_KDNode< T extends WB_Coord, V >.findNearest().
WB_KDEntry<T, V> [] wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.getNearestNeighbors (final WB_Coord coord, final int num)
Parameters
coord
num
Returns
References wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.QueryResult< T extends WB_Coord, V >.entries, and wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.WB_KDNode< T extends WB_Coord, V >.findNearest().
WB_KDEntry<T, V> [] wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.getRange (final WB_AABB2D aabb)
Parameters
aabb
Returns
References wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.WB_KDNode< T extends WB_Coord, V >.range().
WB_KDEntry<T, V> [] wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.getRange (final WB_Coord center, final double radius)
Parameters
center
radius
Returns
References wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.WB_KDNode< T extends WB_Coord, V >.range().
WB_KDEntry<T, V> [] wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.getRange (final WB_Coord center, final double lower, final double upper)
Parameters
center
lower
upper
Returns
References wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.WB_KDNode< T extends WB_Coord, V >.range().
Member Data Documentation
final int wblut.geom.WB_KDTree2D< T extends WB_Coord, V >._dim private
dim.
final int wblut.geom.WB_KDTree2D< T extends WB_Coord, V >._maximumBinSize private
maximum bin size.
final WB_KDNode<T, V> wblut.geom.WB_KDTree2D< T extends WB_Coord, V >.root private
root.
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_KDTree2D.java