HE_Mesh: wblut.geom.WB_Vector2D Class Reference
wblut.geom.WB_Vector2D Class Reference
Public Member Functions
WB_Vector2D ()
WB_Vector2D (final double x, final double y)
WB_Vector2D (final double[] x)
WB_Vector2D (final double[] fromPoint, final double[] toPoint)
WB_Vector2D (final WB_Coord v)
WB_Vector2D (final WB_Coord fromPoint, final WB_Coord toPoint)
WB_Vector2D add (final double...x)
WB_Vector2D add (final WB_Coord p)
WB_Vector2D sub (final double...x)
WB_Vector2D sub (final WB_Coord p)
WB_Vector2D mul (final double f)
WB_Vector2D div (final double f)
WB_Vector2D addMul (final double f, final double...x)
WB_Vector2D addMul (final double f, final WB_Coord p)
WB_Vector2D mulAddMul (final double f, final double g, final double...x)
WB_Vector2D mulAddMul (final double f, final double g, final WB_Coord p)
void addInto (final WB_MutableCoord result, final double...x)
void addInto (final WB_MutableCoord result, final WB_Coord p)
void subInto (final WB_MutableCoord result, final double...x)
void subInto (final WB_MutableCoord result, final WB_Coord p)
void mulInto (final WB_MutableCoord result, final double f)
void divInto (final WB_MutableCoord result, final double f)
void addMulInto (final WB_MutableCoord result, final double f, final double...x)
void addMulInto (final WB_MutableCoord result, final double f, final WB_Coord p)
void mulAddMulInto (final WB_MutableCoord result, final double f, final double g, final double...x)
void mulAddMulInto (final WB_MutableCoord result, final double f, final double g, final WB_Coord p)
double dot2D (final WB_Coord p)
double absDot2D (final WB_Coord p)
WB_Vector2D addSelf (final double...x)
WB_Vector2D addSelf (final WB_Coord p)
WB_Vector2D subSelf (final double...x)
WB_Vector2D subSelf (final WB_Coord v)
WB_Vector2D mulSelf (final double f)
WB_Vector2D divSelf (final double f)
WB_Vector2D addMulSelf (final double f, final double...x)
WB_Vector2D addMulSelf (final double f, final WB_Coord p)
WB_Vector2D mulAddMulSelf (final double f, final double g, final double...x)
WB_Vector2D mulAddMulSelf (final double f, final double g, final WB_Coord p)
double normalizeSelf ()
WB_Vector2D trimSelf (final double d)
WB_Vector2D apply2D (final WB_Transform2D T)
WB_Point applyAsPoint2D (final WB_Transform2D T)
WB_Vector2D applyAsVector2D (final WB_Transform2D T)
WB_Vector2D applyAsNormal2D (final WB_Transform2D T)
void apply2DInto (final WB_MutableCoord result, final WB_Transform2D T)
void applyAsPoint2DInto (final WB_MutableCoord result, final WB_Transform2D T)
void applyAsVector2DInto (final WB_MutableCoord result, final WB_Transform2D T)
void applyAsNormal2DInto (final WB_MutableCoord result, final WB_Transform2D T)
WB_Coord translate2D (final double px, final double py)
void translate2DInto (final WB_MutableCoord result, final double px, final double py)
WB_Coord translate2D (final WB_Coord p)
void translate2DInto (final WB_MutableCoord result, final WB_Coord p)
WB_Vector2D rotateAboutPoint2D (final double angle, final double px, final double py)
void rotateAboutPoint2DInto (final WB_MutableCoord result, final double angle, final double px, final double py)
WB_Vector2D rotateAboutPoint2D (final double angle, final WB_Coord p)
void rotateAboutPoint2DInto (final WB_MutableCoord result, final double angle, final WB_Coord p)
WB_Vector2D rotateAboutOrigin2D (final double angle)
void rotateAboutOrigin2DInto (final WB_MutableCoord result, final double angle)
WB_Vector2D scale2D (final double f)
void scale2DInto (final WB_MutableCoord result, final double f)
WB_Vector2D scale2D (final double fx, final double fy)
void scale2DInto (final WB_MutableCoord result, final double fx, final double fy)
WB_Vector2D apply2DSelf (final WB_Transform2D T)
WB_Vector2D applyAsPoint2DSelf (final WB_Transform2D T)
WB_Vector2D applyAsVector2DSelf (final WB_Transform2D T)
WB_Vector2D applyAsNormal2DSelf (final WB_Transform2D T)
WB_Coord translate2DSelf (final double px, final double py)
WB_Coord translate2DSelf (final WB_Coord p)
WB_Vector2D rotateAboutPoint2DSelf (final double angle, final double px, final double py)
WB_Vector2D rotateAboutPoint2DSelf (final double angle, final WB_Coord p)
WB_Vector2D rotateAboutOrigin2DSelf (final double angle)
WB_Vector2D scale2DSelf (final double f)
WB_Vector2D scale2DSelf (final double fx, final double fy)
double getDistance2D (final WB_Coord p)
double getSqDistance2D (final WB_Coord p)
double getLength2D ()
double getSqLength2D ()
double getAngle (final WB_Coord p)
double getAngleNorm (final WB_Coord p)
double getHeading2D ()
WB_Vector2D getOrthoNormal2D ()
boolean isZero ()
void invert ()
double[] coords ()
WB_Vector2D copy ()
boolean isCollinear2D (final WB_Coord p, final WB_Coord q)
boolean isParallel2D (final WB_Coord p)
boolean isParallel2D (final WB_Coord p, final double t)
boolean isParallelNorm2D (final WB_Coord p)
boolean isParallelNorm2D (final WB_Coord p, final double t)
boolean isOrthogonal2D (final WB_Coord p)
boolean isOrthogonal2D (final WB_Coord p, final double t)
boolean isOrthogonalNorm2D (final WB_Coord p)
boolean isOrthogonalNorm2D (final WB_Coord p, final double t)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoordinate2D
WB_MutableCoordinate2D ()
WB_MutableCoordinate2D (final double x, final double y)
WB_MutableCoordinate2D (final double[] x)
WB_MutableCoordinate2D (final double[] fromPoint, final double[] toPoint)
WB_MutableCoordinate2D (final WB_Coord v)
WB_MutableCoordinate2D (final WB_Coord fromPoint, final WB_Coord toPoint)
double getd (final int i)
float getf (final int i)
double xd ()
double yd ()
double zd ()
double wd ()
float xf ()
float yf ()
float zf ()
float wf ()
void setX (final double x)
void setY (final double y)
void setZ (final double z)
void setW (final double w)
void setCoord (final int i, final double v)
void set (final WB_Coord v)
void set (final double x, final double y)
void set (final double x, final double y, final double z)
void set (final double x, final double y, final double z, final double w)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoord
void setX (double x)
void setY (double y)
void setZ (double z)
void setW (double w)
void setCoord (int i, double v)
void set (WB_Coord p)
void set (double x, double y)
void set (double x, double y, double z)
void set (double x, double y, double z, double w)
Public Member Functions inherited from wblut.geom.WB_Coord
double getd (int i)
float getf (int i)
Public Member Functions inherited from wblut.geom.WB_CoordinateTransform2D
void apply2DInto (WB_MutableCoord result, final WB_Transform2D T)
void rotateAboutPoint2DInto (WB_MutableCoord result, final double angle, final double px, final double py)
void rotateAboutPoint2DInto (WB_MutableCoord result, final double angle, final WB_Coord p)
void rotateAboutOrigin2DInto (WB_MutableCoord result, final double angle)
void scale2DInto (WB_MutableCoord result, final double fx, final double fy)
void scale2DInto (WB_MutableCoord result, final double f)
Public Member Functions inherited from wblut.geom.WB_CoordinateMetric2D
boolean isCollinear2D (WB_Coord p, WB_Coord q)
boolean isParallel2D (WB_Coord p)
boolean isParallel2D (WB_Coord p, double tol)
boolean isParallelNorm2D (WB_Coord p)
boolean isParallelNorm2D (WB_Coord p, double tol)
boolean isOrthogonal2D (WB_Coord p)
boolean isOrthogonal2D (WB_Coord p, double tol)
boolean isOrthogonalNorm2D (WB_Coord p)
boolean isOrthogonalNorm2D (WB_Coord p, double tol)
Static Public Member Functions
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
static WB_Vector2D add (final WB_Coord p, final WB_Coord q)
static WB_Vector2D sub (final WB_Coord p, final WB_Coord q)
static WB_Vector2D subToVector2D (final WB_Coord p, final WB_Coord q)
static WB_Vector2D subToVector2D (final WB_Coord p, final double x, final double y)
static WB_Vector2D mul (final WB_Coord p, final double f)
static WB_Vector2D div (final WB_Coord p, final double f)
static WB_Vector2D addMul (final WB_Coord p, final double f, final WB_Coord q)
static WB_Vector2D mulAddMul (final double f, final WB_Coord p, final double g, final WB_Coord q)
static double dot2D (final WB_Coord p, final WB_Coord q)
static double absDot2D (final WB_Coord p, final WB_Coord q)
static double getAngle (final WB_Coord q, final WB_Coord p)
static double getAngleNorm (final WB_Coord q, final WB_Coord p)
static double getDistance2D (final WB_Coord q, final WB_Coord p)
static double getLength2D (final WB_Coord p)
static double getSqDistance2D (final WB_Coord q, final WB_Coord p)
static double getSqLength2D (final WB_Coord v)
static double getHeading2D (final WB_Coord p)
static boolean isCollinear2D (final WB_Coord o, final WB_Coord p, final WB_Coord q)
static boolean isParallel2D (final WB_Coord p, final WB_Coord q)
static boolean isParallel2D (final WB_Coord p, final WB_Coord q, final double t)
static boolean isParallelNorm2D (final WB_Coord p, final WB_Coord q)
static boolean isParallelNorm2D (final WB_Coord p, final WB_Coord q, final double t)
static boolean isOrthogonal2D (final WB_Coord p, final WB_Coord q)
static boolean isOrthogonal2D (final WB_Coord p, final WB_Coord q, final double t)
static boolean isOrthogonalNorm2D (final WB_Coord p, final WB_Coord q)
static boolean isOrthogonalNorm2D (final WB_Coord p, final WB_Coord q, final double t)
static WB_Vector2D getOrthoNormal2D (final WB_Coord p)
static WB_Vector2D interpolate (final WB_Coord v, final WB_Coord w, final double f)
static WB_Vector2D interpolateEase (final WB_Coord v, final WB_Coord w, final double f, final WB_Ease ease, final WB_Ease.EaseType type)
Static Public Member Functions inherited from wblut.geom.WB_MutableCoordinate2D
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
Static Private Attributes
static final WB_Coord X = new WB_MutableCoordinate2D(1, 0)
static final WB_Coord Y = new WB_MutableCoordinate2D(0, 1)
static final WB_Coord ORIGIN = new WB_MutableCoordinate2D(0, 0)
static final WB_Coord ZERO = new WB_MutableCoordinate2D(0, 0)
Constructor & Destructor Documentation
wblut.geom.WB_Vector2D.WB_Vector2D ()
wblut.geom.WB_Vector2D.WB_Vector2D (final double x, final double y)
Parameters
x
y
wblut.geom.WB_Vector2D.WB_Vector2D (final double[] x)
Parameters
x
wblut.geom.WB_Vector2D.WB_Vector2D (final double[] fromPoint, final double[] toPoint)
Parameters
fromPoint
toPoint
wblut.geom.WB_Vector2D.WB_Vector2D (final WB_Coord v)
Parameters
v
wblut.geom.WB_Vector2D.WB_Vector2D (final WB_Coord fromPoint, final WB_Coord toPoint)
Parameters
fromPoint
toPoint
Member Function Documentation
static double wblut.geom.WB_Vector2D.absDot2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector2D.absDot2D (final WB_Coord p)
Absolute value of 2D dot product.
Parameters
p
Returns
absolute value of 2D dot product
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static WB_Vector2D wblut.geom.WB_Vector2D.add (final WB_Coord p, final WB_Coord q) static
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector2D wblut.geom.WB_Vector2D.add (final double... x)
Add coordinate values.
Parameters
x
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Vector2D wblut.geom.WB_Vector2D.add (final WB_Coord p)
Add coordinate values.
Parameters
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
void wblut.geom.WB_Vector2D.addInto (final WB_MutableCoord result, final double... x)
Add coordinate values and store in mutable coordinate.
Parameters
result
x
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
void wblut.geom.WB_Vector2D.addInto (final WB_MutableCoord result, final WB_Coord p)
Add coordinate values and store in mutable coordinate.
Parameters
result
p
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static WB_Vector2D wblut.geom.WB_Vector2D.addMul (final WB_Coord p, final double f, final WB_Coord q) static
Parameters
p
f
q
Returns
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector2D wblut.geom.WB_Vector2D.addMul (final double f, final double... x)
Add multiple of coordinate values.
Parameters
f multiplier
x
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Vector2D wblut.geom.WB_Vector2D.addMul (final double f, final WB_Coord p)
Add multiple of coordinate values.
Parameters
f
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
void wblut.geom.WB_Vector2D.addMulInto (final WB_MutableCoord result, final double f, final double... x)
Add multiple of coordinate values and store in mutable coordinate.
Parameters
result
f multiplier
x
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
void wblut.geom.WB_Vector2D.addMulInto (final WB_MutableCoord result, final double f, final WB_Coord p)
Add multiple of coordinate values and store in mutable coordinate.
Parameters
result
f
p
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Vector2D wblut.geom.WB_Vector2D.addMulSelf (final double f, final double... x)
Add multiple of coordinate values.
Parameters
f multiplier
x
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath2D.
References wblut.geom.WB_MutableCoordinate2D.set(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_MutableCoordinate2D.yd(), and wblut.geom.WB_MutableCoordinate2D.zd().
WB_Vector2D wblut.geom.WB_Vector2D.addMulSelf (final double f, final WB_Coord p)
Add multiple of coordinate values.
Parameters
f
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath2D.
References wblut.geom.WB_MutableCoordinate2D.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Vector2D wblut.geom.WB_Vector2D.addSelf (final double... x)
Add coordinate values.
Parameters
x
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath2D.
References wblut.geom.WB_MutableCoordinate2D.set(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_MutableCoordinate2D.yd(), and wblut.geom.WB_MutableCoordinate2D.zd().
WB_Vector2D wblut.geom.WB_Vector2D.addSelf (final WB_Coord p)
Add coordinate values.
Parameters
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath2D.
References wblut.geom.WB_MutableCoordinate2D.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Vector2D wblut.geom.WB_Vector2D.apply2D (final WB_Transform2D T)
Apply WB_Transform2D. Mode (point, vector or normal) is decided by implementation.
Parameters
T
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Vector2D.apply2DSelf(), and wblut.geom.WB_Vector2D.WB_Vector2D().
void wblut.geom.WB_Vector2D.apply2DInto (final WB_MutableCoord result, final WB_Transform2D T)
References wblut.geom.WB_Transform2D.applyAsVector2DInto().
WB_Vector2D wblut.geom.WB_Vector2D.apply2DSelf (final WB_Transform2D T)
Parameters
T
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform2D.
References wblut.geom.WB_Vector2D.applyAsVector2DSelf().
WB_Vector2D wblut.geom.WB_Vector2D.applyAsNormal2D (final WB_Transform2D T)
Apply WB_Transform2D as normal.
Parameters
T
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsNormal2DInto(), and wblut.geom.WB_Vector2D.WB_Vector2D().
void wblut.geom.WB_Vector2D.applyAsNormal2DInto (final WB_MutableCoord result, final WB_Transform2D T)
Apply WB_Transform2D as normal.
Parameters
result
T
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsNormal2DInto().
WB_Vector2D wblut.geom.WB_Vector2D.applyAsNormal2DSelf (final WB_Transform2D T)
Parameters
T
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsNormal2DSelf().
WB_Point wblut.geom.WB_Vector2D.applyAsPoint2D (final WB_Transform2D T)
Apply WB_Transform2D as point.
Parameters
T
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsPoint2DInto().
void wblut.geom.WB_Vector2D.applyAsPoint2DInto (final WB_MutableCoord result, final WB_Transform2D T)
Apply WB_Transform2D as point.
Parameters
result
T
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsPoint2DInto().
WB_Vector2D wblut.geom.WB_Vector2D.applyAsPoint2DSelf (final WB_Transform2D T)
Parameters
T
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsPoint2DSelf().
WB_Vector2D wblut.geom.WB_Vector2D.applyAsVector2D (final WB_Transform2D T)
Apply WB_Transform2D as vector.
Parameters
T
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsVector2DInto(), and wblut.geom.WB_Vector2D.WB_Vector2D().
void wblut.geom.WB_Vector2D.applyAsVector2DInto (final WB_MutableCoord result, final WB_Transform2D T)
Apply WB_Transform2D as vector.
Parameters
result
T
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsVector2DInto().
WB_Vector2D wblut.geom.WB_Vector2D.applyAsVector2DSelf (final WB_Transform2D T)
Parameters
T
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsVector2DSelf().
int wblut.geom.WB_Vector2D.compareTo (final WB_Coord p)
References wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate2D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate2D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate2D.zd().
int wblut.geom.WB_Vector2D.compareToY1st (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate2D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate2D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate2D.zd().
double [] wblut.geom.WB_Vector2D.coords ()
Returns
References wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Vector2D wblut.geom.WB_Vector2D.copy ()
Returns
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static WB_Vector2D wblut.geom.WB_Vector2D.div (final WB_Coord p, final double f) static
Parameters
p
f
Returns
References wblut.geom.WB_Vector2D.mul().
WB_Vector2D wblut.geom.WB_Vector2D.div (final double f)
Divide by factor.
Parameters
f
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector2D.mul().
void wblut.geom.WB_Vector2D.divInto (final WB_MutableCoord result, final double f)
Divide by factor and store in mutable coordinate.
Parameters
result
f
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector2D.mulInto().
WB_Vector2D wblut.geom.WB_Vector2D.divSelf (final double f)
Divide by factor.
Parameters
f
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath2D.
References wblut.geom.WB_Vector2D.mulSelf().
static double wblut.geom.WB_Vector2D.dot2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector2D.dot2D (final WB_Coord p)
2D dot product.
Parameters
p
Returns
2D dot product
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
boolean wblut.geom.WB_Vector2D.equals (final Object o)
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate2D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate2D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate2D.zd().
static double wblut.geom.WB_Vector2D.getAngle (final WB_Coord q, final WB_Coord p) static
Parameters
q
p
Returns
References wblut.geom.WB_GeometryOp2D.getAngleBetween2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector2D.getAngle (final WB_Coord p)
Angle between two vectors.
Parameters
p
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_GeometryOp2D.getAngleBetween2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static double wblut.geom.WB_Vector2D.getAngleNorm (final WB_Coord q, final WB_Coord p) static
Parameters
q
p
Returns
References wblut.geom.WB_GeometryOp2D.getAngleBetweenNorm2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector2D.getAngleNorm (final WB_Coord p)
Angle between two normalized vectors.
Parameters
p
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_GeometryOp2D.getAngleBetweenNorm2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static double wblut.geom.WB_Vector2D.getDistance2D (final WB_Coord q, final WB_Coord p) static
Parameters
q
p
Returns
References wblut.geom.WB_GeometryOp2D.getDistance2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector2D.getDistance2D (final WB_Coord p)
2D distance to coordinate
Parameters
p
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_GeometryOp2D.getDistance2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static double wblut.geom.WB_Vector2D.getHeading2D (final WB_Coord p) static
Parameters
p
Returns
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector2D.getHeading2D ()
2D heading of vector.
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static double wblut.geom.WB_Vector2D.getLength2D (final WB_Coord p) static
Parameters
p
Returns
References wblut.geom.WB_GeometryOp2D.getLength2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector2D.getLength2D ()
Length of 2D coordinate.
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_GeometryOp2D.getLength2D(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static WB_Vector2D wblut.geom.WB_Vector2D.getOrthoNormal2D (final WB_Coord p) static
Parameters
p
Returns
References wblut.geom.WB_Vector2D.normalizeSelf(), wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector2D wblut.geom.WB_Vector2D.getOrthoNormal2D ()
Get 2D vector perpendicular and CCW to this one.
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_Vector2D.normalizeSelf(), wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static double wblut.geom.WB_Vector2D.getSqDistance2D (final WB_Coord q, final WB_Coord p) static
Parameters
q
p
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistance2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector2D.getSqDistance2D (final WB_Coord p)
Square 2D distance to coordinate.
Parameters
p
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_GeometryOp2D.getSqDistance2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static double wblut.geom.WB_Vector2D.getSqLength2D (final WB_Coord v) static
Parameters
v
Returns
References wblut.geom.WB_GeometryOp2D.getSqLength2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector2D.getSqLength2D ()
Square length of 2D coordinate.
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_GeometryOp2D.getSqLength2D(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
int wblut.geom.WB_Vector2D.hashCode ()
References wblut.math.WB_HashCode.calculateHashCode(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static WB_Vector2D wblut.geom.WB_Vector2D.interpolate (final WB_Coord v, final WB_Coord w, final double f) static
References wblut.geom.WB_GeometryOp2D.interpolate2D(), wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static WB_Vector2D wblut.geom.WB_Vector2D.interpolateEase (final WB_Coord v, final WB_Coord w, final double f, final WB_Ease ease, final WB_Ease.EaseType type) static
References wblut.geom.WB_GeometryOp2D.interpolateEase2D(), wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_Vector2D.invert ()
References wblut.geom.WB_Vector2D.mulSelf().
static boolean wblut.geom.WB_Vector2D.isCollinear2D (final WB_Coord o, final WB_Coord p, final WB_Coord q) static
Parameters
o
p
q
Returns
References wblut.geom.WB_GeometryOp2D.isCollinear2D().
boolean wblut.geom.WB_Vector2D.isCollinear2D (final WB_Coord p, final WB_Coord q)
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.isCollinear2D().
static boolean wblut.geom.WB_Vector2D.isOrthogonal2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonal2D().
static boolean wblut.geom.WB_Vector2D.isOrthogonal2D (final WB_Coord p, final WB_Coord q, final double t) static
Parameters
p
q
t
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonal2D().
boolean wblut.geom.WB_Vector2D.isOrthogonal2D (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonal2D().
boolean wblut.geom.WB_Vector2D.isOrthogonal2D (final WB_Coord p, final double t)
Parameters
p
t
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonal2D().
static boolean wblut.geom.WB_Vector2D.isOrthogonalNorm2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonalNorm2D().
static boolean wblut.geom.WB_Vector2D.isOrthogonalNorm2D (final WB_Coord p, final WB_Coord q, final double t) static
Parameters
p
q
t
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonalNorm2D().
boolean wblut.geom.WB_Vector2D.isOrthogonalNorm2D (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonalNorm2D().
boolean wblut.geom.WB_Vector2D.isOrthogonalNorm2D (final WB_Coord p, final double t)
Parameters
p
t
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonalNorm2D().
static boolean wblut.geom.WB_Vector2D.isParallel2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.isParallel2D().
static boolean wblut.geom.WB_Vector2D.isParallel2D (final WB_Coord p, final WB_Coord q, final double t) static
Parameters
p
q
t
Returns
References wblut.geom.WB_GeometryOp2D.isParallel2D().
boolean wblut.geom.WB_Vector2D.isParallel2D (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp2D.isParallel2D().
boolean wblut.geom.WB_Vector2D.isParallel2D (final WB_Coord p, final double t)
Parameters
p
t
Returns
References wblut.geom.WB_GeometryOp2D.isParallel2D().
static boolean wblut.geom.WB_Vector2D.isParallelNorm2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.isParallelNorm2D().
static boolean wblut.geom.WB_Vector2D.isParallelNorm2D (final WB_Coord p, final WB_Coord q, final double t) static
Parameters
p
q
t
Returns
References wblut.geom.WB_GeometryOp2D.isParallelNorm2D().
boolean wblut.geom.WB_Vector2D.isParallelNorm2D (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp2D.isParallelNorm2D().
boolean wblut.geom.WB_Vector2D.isParallelNorm2D (final WB_Coord p, final double t)
Parameters
p
t
Returns
References wblut.geom.WB_GeometryOp2D.isParallelNorm2D().
boolean wblut.geom.WB_Vector2D.isZero ()
Is this a degenerate vector?
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_GeometryOp2D.isZero2D(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static WB_Vector2D wblut.geom.WB_Vector2D.mul (final WB_Coord p, final double f) static
Parameters
p
f
Returns
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector2D wblut.geom.WB_Vector2D.mul (final double f)
Multiply by factor.
Parameters
f
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static WB_Vector2D wblut.geom.WB_Vector2D.mulAddMul (final double f, final WB_Coord p, final double g, final WB_Coord q) static
Parameters
f
p
g
q
Returns
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector2D wblut.geom.WB_Vector2D.mulAddMul (final double f, final double g, final double... x)
Multiply this coordinate by factor f and add other coordinate values multiplied by g.
Parameters
f
g
x
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Vector2D wblut.geom.WB_Vector2D.mulAddMul (final double f, final double g, final WB_Coord p)
Multiply this coordinate by factor f and add other coordinate values multiplied by g.
Parameters
f
g
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
void wblut.geom.WB_Vector2D.mulAddMulInto (final WB_MutableCoord result, final double f, final double g, final double... x)
Multiply this coordinate by factor f, add other coordinate values multiplied by g and store result in mutable coordinate.
Parameters
result
f
g
x
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
void wblut.geom.WB_Vector2D.mulAddMulInto (final WB_MutableCoord result, final double f, final double g, final WB_Coord p)
Multiply this coordinate by factor f, add other coordinate values multiplied by g and store result in mutable coordinate.
Parameters
result
f
g
p
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Vector2D wblut.geom.WB_Vector2D.mulAddMulSelf (final double f, final double g, final double... x)
Multiply this coordinate by factor f and add other coordinate values multiplied by g.
Parameters
f
g
x
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath2D.
References wblut.geom.WB_MutableCoordinate2D.set(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Vector2D wblut.geom.WB_Vector2D.mulAddMulSelf (final double f, final double g, final WB_Coord p)
Multiply this coordinate by factor f and add other coordinate values multiplied by g.
Parameters
f
g
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath2D.
References wblut.geom.WB_MutableCoordinate2D.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
void wblut.geom.WB_Vector2D.mulInto (final WB_MutableCoord result, final double f)
Multiply by factor and store in mutable coordinate.
Parameters
result
f
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector2D.scale2DInto().
WB_Vector2D wblut.geom.WB_Vector2D.mulSelf (final double f)
Multiply by factor.
Parameters
f
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath2D.
References wblut.geom.WB_MutableCoordinate2D.set(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_MutableCoordinate2D.yd(), and wblut.geom.WB_MutableCoordinate2D.zd().
double wblut.geom.WB_Vector2D.normalizeSelf ()
Normalize this vector. Return the length before normalization. If this vector is degenerate 0 is returned and the vector remains the zero vector.
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath2D.
References wblut.geom.WB_Vector2D.getLength2D(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_MutableCoordinate2D.set(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static WB_Coord wblut.geom.WB_Vector2D.ORIGIN () static
Returns
WB_Vector2D wblut.geom.WB_Vector2D.rotateAboutOrigin2D (final double angle)
Rotate around origin.
Parameters
angle
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.addRotateAboutOrigin(), wblut.geom.WB_Transform2D.applyAsVector2DSelf(), and wblut.geom.WB_Vector2D.WB_Vector2D().
void wblut.geom.WB_Vector2D.rotateAboutOrigin2DInto (final WB_MutableCoord result, final double angle)
References wblut.geom.WB_Transform2D.addRotateAboutOrigin(), and wblut.geom.WB_Transform2D.applyAsVector2DInto().
WB_Vector2D wblut.geom.WB_Vector2D.rotateAboutOrigin2DSelf (final double angle)
Parameters
angle
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform2D.
References wblut.geom.WB_Transform2D.addRotateAboutOrigin(), and wblut.geom.WB_Transform2D.applyAsVector2DSelf().
WB_Vector2D wblut.geom.WB_Vector2D.rotateAboutPoint2D (final double angle, final double px, final double py)
Rotate around point.
Parameters
angle
px
py
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.addRotateAboutPoint(), wblut.geom.WB_Transform2D.applyAsVector2DSelf(), and wblut.geom.WB_Vector2D.WB_Vector2D().
WB_Vector2D wblut.geom.WB_Vector2D.rotateAboutPoint2D (final double angle, final WB_Coord p)
Rotate around point.
Parameters
angle
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.addRotateAboutPoint(), wblut.geom.WB_Transform2D.applyAsVector2DSelf(), and wblut.geom.WB_Vector2D.WB_Vector2D().
void wblut.geom.WB_Vector2D.rotateAboutPoint2DInto (final WB_MutableCoord result, final double angle, final double px, final double py)
References wblut.geom.WB_Transform2D.addRotateAboutPoint(), and wblut.geom.WB_Transform2D.applyAsVector2DInto().
void wblut.geom.WB_Vector2D.rotateAboutPoint2DInto (final WB_MutableCoord result, final double angle, final WB_Coord p)
References wblut.geom.WB_Transform2D.addRotateAboutPoint(), and wblut.geom.WB_Transform2D.applyAsVector2DInto().
WB_Vector2D wblut.geom.WB_Vector2D.rotateAboutPoint2DSelf (final double angle, final double px, final double py)
Parameters
angle
px
py
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform2D.
References wblut.geom.WB_Transform2D.addRotateAboutPoint(), and wblut.geom.WB_Transform2D.applyAsVector2DSelf().
WB_Vector2D wblut.geom.WB_Vector2D.rotateAboutPoint2DSelf (final double angle, final WB_Coord p)
Parameters
angle
p
Returns
Implements wblut.geom.WB_MutableCoordinateTransform2D.
References wblut.geom.WB_Transform2D.addRotateAboutPoint(), and wblut.geom.WB_Transform2D.applyAsVector2DSelf().
WB_Vector2D wblut.geom.WB_Vector2D.scale2D (final double f)
Uniform scale.
Parameters
f
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Vector2D.mul().
WB_Vector2D wblut.geom.WB_Vector2D.scale2D (final double fx, final double fy)
Non-uniform scale.
Parameters
fx
fy
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
void wblut.geom.WB_Vector2D.scale2DInto (final WB_MutableCoord result, final double f)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
void wblut.geom.WB_Vector2D.scale2DInto (final WB_MutableCoord result, final double fx, final double fy)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Vector2D wblut.geom.WB_Vector2D.scale2DSelf (final double f)
Parameters
f
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform2D.
References wblut.geom.WB_Vector2D.mulSelf().
WB_Vector2D wblut.geom.WB_Vector2D.scale2DSelf (final double fx, final double fy)
Parameters
fx
fy
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform2D.
References wblut.geom.WB_MutableCoordinate2D.set(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static WB_Vector2D wblut.geom.WB_Vector2D.sub (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector2D wblut.geom.WB_Vector2D.sub (final double... x)
Subtract coordinate values.
Parameters
x
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Vector2D wblut.geom.WB_Vector2D.sub (final WB_Coord p)
Subtract coordinate values.
Parameters
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
void wblut.geom.WB_Vector2D.subInto (final WB_MutableCoord result, final double... x)
Subtract coordinate values and store in mutable coordinate.
Parameters
result
x
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
void wblut.geom.WB_Vector2D.subInto (final WB_MutableCoord result, final WB_Coord p)
Subtract coordinate values and store in mutable coordinate.
Parameters
result
p
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Vector2D wblut.geom.WB_Vector2D.subSelf (final double... x)
Subtract coordinate values.
Parameters
x
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath2D.
References wblut.geom.WB_MutableCoordinate2D.set(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Vector2D wblut.geom.WB_Vector2D.subSelf (final WB_Coord p)
Subtract coordinate values.
Parameters
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath2D.
References wblut.geom.WB_MutableCoordinate2D.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
static WB_Vector2D wblut.geom.WB_Vector2D.subToVector2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static WB_Vector2D wblut.geom.WB_Vector2D.subToVector2D (final WB_Coord p, final double x, final double y) static
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
String wblut.geom.WB_Vector2D.toString ()
References wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Coord wblut.geom.WB_Vector2D.translate2D (final double px, final double py)
2D translate.
Parameters
px
py
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Coord wblut.geom.WB_Vector2D.translate2D (final WB_Coord p)
2D translate.
Parameters
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Vector2D.WB_Vector2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
void wblut.geom.WB_Vector2D.translate2DInto (final WB_MutableCoord result, final double px, final double py)
2D translate.
Parameters
result
px
py
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate2D.xd(), and wblut.geom.WB_MutableCoordinate2D.yd().
void wblut.geom.WB_Vector2D.translate2DInto (final WB_MutableCoord result, final WB_Coord p)
2D translate.
Parameters
result
p
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate2D.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate2D.yd().
WB_Coord wblut.geom.WB_Vector2D.translate2DSelf (final double px, final double py)
2D translate.
Parameters
px
py
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform2D.
WB_Coord wblut.geom.WB_Vector2D.translate2DSelf (final WB_Coord p)
2D translate.
Parameters
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform2D.
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector2D wblut.geom.WB_Vector2D.trimSelf (final double d)
If vector is larger than given value, trim vector.
Parameters
d
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath2D.
References wblut.geom.WB_Vector2D.getSqLength2D(), wblut.geom.WB_Vector2D.mulSelf(), and wblut.geom.WB_Vector2D.normalizeSelf().
static WB_Coord wblut.geom.WB_Vector2D.X () static
Returns
static WB_Coord wblut.geom.WB_Vector2D.Y () static
Returns
static WB_Coord wblut.geom.WB_Vector2D.ZERO () static
Returns
Member Data Documentation
final WB_Coord wblut.geom.WB_Vector2D.ORIGIN = new WB_MutableCoordinate2D(0, 0) static private
final WB_Coord wblut.geom.WB_Vector2D.X = new WB_MutableCoordinate2D(1, 0) static private
final WB_Coord wblut.geom.WB_Vector2D.Y = new WB_MutableCoordinate2D(0, 1) static private
final WB_Coord wblut.geom.WB_Vector2D.ZERO = new WB_MutableCoordinate2D(0, 0) static private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Vector2D.java