HE_Mesh: wblut.hemesh.HEC_FromQuads Class Reference
wblut.hemesh.HEC_FromQuads Class Reference
Public Member Functions
HEC_FromQuads ()
HEC_FromQuads (final WB_Quad[] qs)
HEC_FromQuads (final Collection< WB_Quad > qs)
HEC_FromQuads setQuads (final WB_Quad[] qs)
HEC_FromQuads setQuads (final Collection< WB_Quad > qs)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Attributes
WB_Quad[] quads
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Creates a new mesh from a list of quads. Duplicate vertices are fused.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_FromQuads.HEC_FromQuads ()
Instantiates a new HEC_FromQuads.
wblut.hemesh.HEC_FromQuads.HEC_FromQuads (final WB_Quad[] qs)
Instantiates a new HEC_FromQuads.
Parameters
qs the qs
wblut.hemesh.HEC_FromQuads.HEC_FromQuads (final Collection< WB_Quad > qs)
Instantiates a new HEC_FromQuads.
Parameters
qs
References wblut.hemesh.HEC_FromQuads.setQuads().
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_FromQuads.createBase () protected
References wblut.hemesh.HEC_FromFacelist.createBase(), wblut.geom.WB_Quad.p1, wblut.geom.WB_Quad.p2, wblut.geom.WB_Quad.p3, wblut.geom.WB_Quad.p4, wblut.hemesh.HEC_FromFacelist.setDuplicate(), wblut.hemesh.HEC_FromFacelist.setFaces(), and wblut.hemesh.HEC_FromFacelist.setVertices().
HEC_FromQuads wblut.hemesh.HEC_FromQuads.setQuads (final WB_Quad[] qs)
Sets the source quads.
Parameters
qs source quads
Returns
self
HEC_FromQuads wblut.hemesh.HEC_FromQuads.setQuads (final Collection< WB_Quad > qs)
Sets the source quads.
Parameters
qs source quads
Returns
self
Member Data Documentation
WB_Quad [] wblut.hemesh.HEC_FromQuads.quads private
Quads.
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_FromQuads.java