HE_Mesh: wblut.hemesh.HE_VertexHalfedgeInRevCirculator Class Reference
wblut.hemesh.HE_VertexHalfedgeInRevCirculator Class Reference
Public Member Functions
boolean hasNext ()
HE_Halfedge next ()
void remove ()
Private Attributes
final HE_Halfedge _start
HE_Halfedge _current
Member Function Documentation
boolean wblut.hemesh.HE_VertexHalfedgeInRevCirculator.hasNext ()
References wblut.hemesh.HE_VertexHalfedgeInRevCirculator._start, and wblut.hemesh.HE_Halfedge.getNextInVertex().
HE_Halfedge wblut.hemesh.HE_VertexHalfedgeInRevCirculator.next ()
References wblut.hemesh.HE_VertexHalfedgeInRevCirculator._start, wblut.hemesh.HE_Halfedge.getNextInVertex(), and wblut.hemesh.HE_Halfedge.getPair().
void wblut.hemesh.HE_VertexHalfedgeInRevCirculator.remove ()
Member Data Documentation
HE_Halfedge wblut.hemesh.HE_VertexHalfedgeInRevCirculator._current private
final HE_Halfedge wblut.hemesh.HE_VertexHalfedgeInRevCirculator._start private
The documentation for this class was generated from the following file:
src/hemesh_core/wblut/hemesh/HE_VertexHalfedgeInRevCirculator.java