HE_Mesh: wblut.hemesh.HEM_Twist Class Reference
wblut.hemesh.HEM_Twist Class Reference
Public Member Functions
HEM_Twist ()
HEM_Twist setTwistAxis (final WB_Line a)
HEM_Twist setTwistAxis (final WB_Coord o, final WB_Coord d)
HEM_Twist setTwistAxisFromPoints (final WB_Coord a, final WB_Coord b)
HEM_Twist setAngleFactor (final double f)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_Line twistAxis
double angleFactor
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Twist a mesh. Determined by a twist axis and an angle factor.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_Twist.HEM_Twist ()
Instantiates a new HEM_Twist.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Twist.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Line.getDirection(), wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Line.getOrigin(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Point.rotateAboutAxisSelf(), and wblut.hemesh.HE_Mesh.vItr().
HE_Mesh wblut.hemesh.HEM_Twist.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Selection.collectVertices(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Line.getOrigin(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Point.rotateAboutAxisSelf(), and wblut.hemesh.HE_Selection.vItr().
HEM_Twist wblut.hemesh.HEM_Twist.setAngleFactor (final double f)
Set angle factor, ratio of twist angle in degrees to distance to twist axis.
Parameters
f direction
Returns
self
HEM_Twist wblut.hemesh.HEM_Twist.setTwistAxis (final WB_Line a)
Set twist axis.
Parameters
a twist axis
Returns
self
HEM_Twist wblut.hemesh.HEM_Twist.setTwistAxis (final WB_Coord o, final WB_Coord d)
Parameters
o
d
Returns
HEM_Twist wblut.hemesh.HEM_Twist.setTwistAxisFromPoints (final WB_Coord a, final WB_Coord b)
Parameters
a
b
Returns
References wblut.geom.WB_Vector.normalizeSelf().
Member Data Documentation
double wblut.hemesh.HEM_Twist.angleFactor private
Angle factor.
WB_Line wblut.hemesh.HEM_Twist.twistAxis private
Twist axis.
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Twist.java