HE_Mesh: wblut.math.WB_M22 Class Reference
wblut.math.WB_M22 Class Reference
Public Member Functions
WB_M22 ()
WB_M22 (final double[][] matrix33)
WB_M22 (final double m11, final double m12, final double m13, final double m21, final double m22, final double m23, final double m31, final double m32, final double m33)
void set (final double[][] matrix33)
void set (final float[][] matrix33)
void set (final int[][] matrix33)
void set (final double m11, final double m12, final double m13, final double m21, final double m22, final double m23, final double m31, final double m32, final double m33)
void set (final WB_M22 m)
WB_M22 get ()
WB_Vector row (final int i)
void rowInto (final int i, final WB_MutableCoord result)
WB_Vector col (final int i)
void colInto (final int i, final WB_MutableCoord result)
void add (final WB_M22 m)
void sub (final WB_M22 m)
void mul (final double f)
void div (final double f)
void addInto (final WB_M22 m, final WB_M22 result)
void subInto (final WB_M22 m, final WB_M22 result)
void multInto (final double f, final WB_M22 result)
void divInto (final double f, final WB_M22 result)
WB_M22 mul (final WB_M22 n)
void multInto (final WB_M22 n, final WB_M22 result)
double det ()
void transpose ()
WB_M22 getTranspose ()
void transposeInto (final WB_M22 result)
WB_M22 inverse ()
WB_M22 Jacobi ()
double[][] toArray ()
boolean equals (final Object o)
Static Public Member Functions
static WB_M22 mul (final WB_M22 m, final WB_M22 n)
static void mulInto (final WB_M22 m, final WB_M22 n, final WB_M22 result)
static void mulInto (final WB_M22 m, final WB_Coord v, final WB_MutableCoord result)
static void mulInto (final WB_Coord v, final WB_M22 m, final WB_MutableCoord result)
static WB_Point mulToPoint (final WB_M22 m, final WB_Coord v)
static WB_Point mulToPoint (final WB_Coord v, final WB_M22 m)
static WB_Vector mulToVector (final WB_M22 m, final WB_Coord v)
static WB_Vector mulToVector (final WB_Coord v, final WB_M22 m)
static WB_Vector Cramer3 (final double a1, final double b1, final double c1, final double d1, final double a2, final double b2, final double c2, final double d2, final double a3, final double b3, final double c3, final double d3)
static WB_M22 covarianceMatrix (final WB_Coord[] points)
Public Attributes
double m11
double m21
double m31
Private Member Functions
double[] symSchur2 (final int p, final int q, final double[][] m)
Detailed Description
3x3 Matrix.
Author
Frederik Vanhoutte (W:Blut) 2010
Constructor & Destructor Documentation
wblut.math.WB_M22.WB_M22 ()
Instantiates a new WB_M33.
wblut.math.WB_M22.WB_M22 (final double matrix33[][])
Instantiates a new WB_M33.
Parameters
matrix33 double[3][3] array of values
wblut.math.WB_M22.WB_M22 (final double m11, final double m12, final double m13, final double m21, final double m22, final double m23, final double m31, final double m32, final double m33)
Instantiates a new WB_M33.
Parameters
m11 m11
m12 m12
m13 m13
m21 m21
m22 m22
m23 m23
m31 m31
m32 m32
m33 m33
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, and wblut.math.WB_M22.m31.
Member Function Documentation
void wblut.math.WB_M22.add (final WB_M22 m)
Add matrix.
Parameters
m matrix
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, and wblut.math.WB_M22.m31.
void wblut.math.WB_M22.addInto (final WB_M22 m, final WB_M22 result)
Add matrix into provided matrix.
Parameters
m matrix
result result
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, and wblut.math.WB_M22.m31.
WB_Vector wblut.math.WB_M22.col (final int i)
Get column as WB_Vector.
Parameters
i 0,1,2
Returns
col
void wblut.math.WB_M22.colInto (final int i, final WB_MutableCoord result)
Return col into provided WB_Vector.
Parameters
i 0,1,2
result WB_Point to store the col in
References wblut.geom.WB_MutableCoord.set().
static WB_M22 wblut.math.WB_M22.covarianceMatrix (final WB_Coord[] points) static
Get covariance matrix of an array of WB_Coord.
Parameters
points
Returns
covariance matrix
References wblut.geom.WB_Point.addSelf(), wblut.math.WB_M22.mul(), wblut.geom.WB_Point.mulSelf(), wblut.geom.WB_Point.sub(), wblut.math.WB_M22.WB_M22(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
static WB_Vector wblut.math.WB_M22.Cramer3 (final double a1, final double b1, final double c1, final double d1, final double a2, final double b2, final double c2, final double d2, final double a3, final double b3, final double c3, final double d3) static
Cramer rule for solving 3 linear equations and 3 unknowns.
Parameters
a1 the a1
b1 the b1
c1 the c1
d1 the d1
a2 the a2
b2 the b2
c2 the c2
d2 the d2
a3 the a3
b3 the b3
c3 the c3
d3 the d3
Returns
the w b_ vector
References wblut.math.WB_M22.det(), wblut.math.WB_Epsilon.isZero(), wblut.math.WB_M22.set(), and wblut.math.WB_M22.WB_M22().
double wblut.math.WB_M22.det ()
Get determinant of matrix.
Returns
determinant
References wblut.math.WB_M22.m31.
void wblut.math.WB_M22.div (final double f)
Divide by scalar.
Parameters
f factor
References wblut.math.WB_Epsilon.isZero().
void wblut.math.WB_M22.divInto (final double f, final WB_M22 result)
Divide with scalar into provided matrix.
Parameters
f factor
result result
References wblut.math.WB_Epsilon.isZero(), wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, and wblut.math.WB_M22.m31.
boolean wblut.math.WB_M22.equals (final Object o)
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, wblut.math.WB_M22.m31, and wblut.math.WB_M22.WB_M22().
WB_M22 wblut.math.WB_M22.get ()
Get copy.
Returns
copy
References wblut.math.WB_M22.WB_M22().
WB_M22 wblut.math.WB_M22.getTranspose ()
Get the transpose.
Returns
transposed matrix
References wblut.math.WB_M22.WB_M22().
WB_M22 wblut.math.WB_M22.inverse ()
Inverse matrix.
Returns
inverse
References wblut.math.WB_M22.det(), wblut.math.WB_M22.div(), wblut.math.WB_Epsilon.isZero(), and wblut.math.WB_M22.WB_M22().
WB_M22 wblut.math.WB_M22.Jacobi ()
Jacobi.
Returns
the w b_ m33
References wblut.math.WB_Math.fastAbs(), wblut.math.WB_M22.getTranspose(), wblut.math.WB_M22.mul(), wblut.math.WB_M22.set(), wblut.math.WB_M22.symSchur2(), wblut.math.WB_M22.toArray(), and wblut.math.WB_M22.WB_M22().
void wblut.math.WB_M22.mul (final double f)
Multiply with scalar.
Parameters
f factor
static WB_M22 wblut.math.WB_M22.mul (final WB_M22 m, final WB_M22 n) static
Multiply matrices into new matrix.
Parameters
m matrix
n matrix
Returns
result
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, wblut.math.WB_M22.m31, and wblut.math.WB_M22.WB_M22().
WB_M22 wblut.math.WB_M22.mul (final WB_M22 n)
Multiply with matrix into new matrix.
Parameters
n matrix
Returns
result
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, wblut.math.WB_M22.m31, and wblut.math.WB_M22.WB_M22().
static void wblut.math.WB_M22.mulInto (final WB_M22 m, final WB_M22 n, final WB_M22 result) static
Multiply matrices into provided matrix.
Parameters
m matrix
n matrix
result result
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, wblut.math.WB_M22.m31, and wblut.math.WB_M22.set().
static void wblut.math.WB_M22.mulInto (final WB_M22 m, final WB_Coord v, final WB_MutableCoord result) static
Multiply matrix and vector into provided vector.
Parameters
m matrix
v vector
result result
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, wblut.math.WB_M22.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static void wblut.math.WB_M22.mulInto (final WB_Coord v, final WB_M22 m, final WB_MutableCoord result) static
Parameters
v
m
result
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, wblut.math.WB_M22.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.math.WB_M22.multInto (final double f, final WB_M22 result)
Multiply with scalar into provided matrix.
Parameters
f factor
result result
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, and wblut.math.WB_M22.m31.
void wblut.math.WB_M22.multInto (final WB_M22 n, final WB_M22 result)
Multiply matrix into provided matrix.
Parameters
n matrix
result result
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, wblut.math.WB_M22.m31, and wblut.math.WB_M22.set().
static WB_Point wblut.math.WB_M22.mulToPoint (final WB_M22 m, final WB_Coord v) static
Multiply matrix and point into new point.
Parameters
m matrix
v point
Returns
result
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, wblut.math.WB_M22.m31, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static WB_Point wblut.math.WB_M22.mulToPoint (final WB_Coord v, final WB_M22 m) static
Multiply point and matrix into new point.
Parameters
v point
m matrix
Returns
result
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, wblut.math.WB_M22.m31, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static WB_Vector wblut.math.WB_M22.mulToVector (final WB_M22 m, final WB_Coord v) static
Parameters
m
v
Returns
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, wblut.math.WB_M22.m31, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static WB_Vector wblut.math.WB_M22.mulToVector (final WB_Coord v, final WB_M22 m) static
Parameters
v
m
Returns
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, wblut.math.WB_M22.m31, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.math.WB_M22.row (final int i)
Get row as WB_Vector.
Parameters
i 0,1,2
Returns
row
void wblut.math.WB_M22.rowInto (final int i, final WB_MutableCoord result)
Return row into provided WB_Vector.
Parameters
i 0,1,2
result WB_Point to store the row in
References wblut.geom.WB_MutableCoord.set().
void wblut.math.WB_M22.set (final double matrix33[][])
Set values.
Parameters
matrix33 double[3][3] array of values
void wblut.math.WB_M22.set (final float matrix33[][])
Set values.
Parameters
matrix33 float[3][3] array of values
void wblut.math.WB_M22.set (final int matrix33[][])
Set values.
Parameters
matrix33 int[3][3] array of values
void wblut.math.WB_M22.set (final double m11, final double m12, final double m13, final double m21, final double m22, final double m23, final double m31, final double m32, final double m33)
Set values.
Parameters
m11 m11
m12 m12
m13 m13
m21 m21
m22 m22
m23 m23
m31 m31
m32 m32
m33 m33
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, and wblut.math.WB_M22.m31.
void wblut.math.WB_M22.set (final WB_M22 m)
Set values.
Parameters
m matrix WB_M33
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, and wblut.math.WB_M22.m31.
void wblut.math.WB_M22.sub (final WB_M22 m)
Subtract matrix.
Parameters
m matrix
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, and wblut.math.WB_M22.m31.
void wblut.math.WB_M22.subInto (final WB_M22 m, final WB_M22 result)
Subtract matrix into provided matrix.
Parameters
m matrix
result result
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, and wblut.math.WB_M22.m31.
double [] wblut.math.WB_M22.symSchur2 (final int p, final int q, final double m[][]) private
Symmetric schur2 subfunction of Jacobi().
Parameters
p the p
q the q
m the m
Returns
the double[]
References wblut.math.WB_Math.fastAbs(), and wblut.math.WB_Epsilon.isZero().
double [][] wblut.math.WB_M22.toArray ()
Return matrix as array.
Returns
double[3][3]
References wblut.math.WB_M22.m11, wblut.math.WB_M22.m21, and wblut.math.WB_M22.m31.
void wblut.math.WB_M22.transpose ()
Transpose matrix.
References wblut.math.WB_M22.m21, and wblut.math.WB_M22.m31.
void wblut.math.WB_M22.transposeInto (final WB_M22 result)
Put transposed matrix into provide matrix.
Parameters
result result
References wblut.math.WB_M22.set().
Member Data Documentation
double wblut.math.WB_M22.m11
First row.
double wblut.math.WB_M22.m21
Second row.
double wblut.math.WB_M22.m31
Third row.
The documentation for this class was generated from the following file:
src/math/wblut/math/WB_M22.java