HE_Mesh: wblut.H3D Class Reference
wblut.H3D Class Reference
Public Member Functions
H3D ()
void center ()
void vertex (final WB_Coord v)
void normal (final WB_Coord n)
void vertex2D (final WB_Coord v)
void translate (final WB_Coord v)
void translate2D (final WB_Coord v)
Private Attributes
WB_Render3D render
Detailed Description
Author
FVH
Constructor & Destructor Documentation
wblut.H3D.H3D ()
Member Function Documentation
void wblut.H3D.center ()
References wblut.H3D.translate().
void wblut.H3D.normal (final WB_Coord n)
References wblut.processing.WB_Render3D.normal().
void wblut.H3D.translate (final WB_Coord v)
References wblut.processing.WB_Render3D.translate().
void wblut.H3D.translate2D (final WB_Coord v)
References wblut.processing.WB_Render2D.translate2D().
void wblut.H3D.vertex (final WB_Coord v)
References wblut.processing.WB_Render3D.vertex().
void wblut.H3D.vertex2D (final WB_Coord v)
References wblut.processing.WB_Render2D.vertex2D().
Member Data Documentation
WB_Render3D wblut.H3D.render private
The documentation for this class was generated from the following file:
src/processing/wblut/H3D.java