HE_Mesh: wblut.hemesh.HEC_SweepTube Class Reference
wblut.hemesh.HEC_SweepTube Class Reference
Public Member Functions
HEC_SweepTube ()
HEC_SweepTube (final double R, final int facets, final int steps, final WB_Curve curve)
HEC_SweepTube setRange (final double umin, final double umax)
HEC_SweepTube setScale (final double s)
HEC_SweepTube setRadius (final double R)
HEC_SweepTube setSteps (final int steps)
HEC_SweepTube setFacets (final int facets)
HEC_SweepTube setCap (final boolean topcap, final boolean bottomcap)
HEC_SweepTube setCurve (final WB_Curve curve)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Attributes
double R
int facets
int steps
WB_Curve curve
boolean topcap
boolean bottomcap
double umin
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Circle swept along curve.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_SweepTube.HEC_SweepTube ()
wblut.hemesh.HEC_SweepTube.HEC_SweepTube (final double R, final int facets, final int steps, final WB_Curve curve)
Parameters
R
facets
steps
curve
References wblut.hemesh.HEC_SweepTube.curve, wblut.hemesh.HEC_SweepTube.facets, wblut.hemesh.HEC_SweepTube.R, and wblut.hemesh.HEC_SweepTube.steps.
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_SweepTube.createBase () protected
References wblut.geom.WB_Point.addSelf(), wblut.math.WB_Math.clamp(), wblut.hemesh.HEC_FromFacelist.createBase(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Curve.curveDirection(), wblut.geom.WB_Curve.curvePoint(), wblut.geom.WB_Vector.dot(), wblut.hemesh.HEC_SweepTube.facets, wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.rotateAboutAxisSelf(), wblut.hemesh.HE_Mesh.scaleSelf(), wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HEC_FromFacelist.setVertices(), wblut.hemesh.HEC_SweepTube.steps, and wblut.hemesh.HEC_SweepTube.umin.
HEC_SweepTube wblut.hemesh.HEC_SweepTube.setCap (final boolean topcap, final boolean bottomcap)
Set capping options.
Parameters
topcap create top cap?
bottomcap create bottom cap?
Returns
self
References wblut.hemesh.HEC_SweepTube.bottomcap, and wblut.hemesh.HEC_SweepTube.topcap.
HEC_SweepTube wblut.hemesh.HEC_SweepTube.setCurve (final WB_Curve curve)
Parameters
curve
Returns
References wblut.hemesh.HEC_SweepTube.curve.
HEC_SweepTube wblut.hemesh.HEC_SweepTube.setFacets (final int facets)
Set number of sides.
Parameters
facets number of sides
Returns
self
References wblut.hemesh.HEC_SweepTube.facets.
HEC_SweepTube wblut.hemesh.HEC_SweepTube.setRadius (final double R)
Set fixed radius.
Parameters
R radius
Returns
self
References wblut.hemesh.HEC_SweepTube.R.
HEC_SweepTube wblut.hemesh.HEC_SweepTube.setRange (final double umin, final double umax)
Parameters
umin
umax
Returns
References wblut.hemesh.HEC_SweepTube.umin.
HEC_SweepTube wblut.hemesh.HEC_SweepTube.setScale (final double s)
HEC_SweepTube wblut.hemesh.HEC_SweepTube.setSteps (final int steps)
Set vertical divisions.
Parameters
steps vertical divisions
Returns
self
References wblut.hemesh.HEC_SweepTube.steps.
Member Data Documentation
boolean wblut.hemesh.HEC_SweepTube.bottomcap private
WB_Curve wblut.hemesh.HEC_SweepTube.curve private
Sweep curve.
int wblut.hemesh.HEC_SweepTube.facets private
Facets.
double wblut.hemesh.HEC_SweepTube.R private
Base radius.
int wblut.hemesh.HEC_SweepTube.steps private
Steps along curve.
boolean wblut.hemesh.HEC_SweepTube.topcap private
double wblut.hemesh.HEC_SweepTube.umin private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_SweepTube.java