HE_Mesh: wblut.geom.WB_HashGridDouble Class Reference
wblut.geom.WB_HashGridDouble Class Reference
Public Member Functions
WB_HashGridDouble (final int sizeI, final int sizeJ, final int sizeK, final double defaultValue)
WB_HashGridDouble (final int sizeI, final int sizeJ, final int sizeK)
boolean setValue (final double value, final int i, final int j, final int k)
boolean addValue (final double value, final int i, final int j, final int k)
boolean clearValue (final int i, final int j, final int k)
double getValue (final int i, final int j, final int k)
int getSizeI ()
int getSizeJ ()
int getSizeK ()
double getDefaultValue ()
long[] getKeys ()
int size ()
Private Member Functions
long safeIndex (final int i, final int j, final int k)
Private Attributes
final LongDoubleHashMap values
final double defaultValue
final int sizeI
Constructor & Destructor Documentation
wblut.geom.WB_HashGridDouble.WB_HashGridDouble (final int sizeI, final int sizeJ, final int sizeK, final double defaultValue)
Parameters
sizeI
sizeJ
sizeK
defaultValue
References wblut.geom.WB_HashGridDouble.defaultValue, and wblut.geom.WB_HashGridDouble.sizeI.
wblut.geom.WB_HashGridDouble.WB_HashGridDouble (final int sizeI, final int sizeJ, final int sizeK)
Parameters
sizeI
sizeJ
sizeK
References wblut.geom.WB_HashGridDouble.sizeI.
Member Function Documentation
boolean wblut.geom.WB_HashGridDouble.addValue (final double value, final int i, final int j, final int k)
Parameters
value
i
j
k
Returns
References wblut.geom.WB_HashGridDouble.safeIndex().
boolean wblut.geom.WB_HashGridDouble.clearValue (final int i, final int j, final int k)
Parameters
i
j
k
Returns
References wblut.geom.WB_HashGridDouble.safeIndex().
double wblut.geom.WB_HashGridDouble.getDefaultValue ()
Returns
References wblut.geom.WB_HashGridDouble.defaultValue.
long [] wblut.geom.WB_HashGridDouble.getKeys ()
Returns
int wblut.geom.WB_HashGridDouble.getSizeI ()
Returns
References wblut.geom.WB_HashGridDouble.sizeI.
int wblut.geom.WB_HashGridDouble.getSizeJ ()
Returns
int wblut.geom.WB_HashGridDouble.getSizeK ()
Returns
double wblut.geom.WB_HashGridDouble.getValue (final int i, final int j, final int k)
Parameters
i
j
k
Returns
References wblut.geom.WB_HashGridDouble.defaultValue, and wblut.geom.WB_HashGridDouble.safeIndex().
long wblut.geom.WB_HashGridDouble.safeIndex (final int i, final int j, final int k) private
Parameters
i
j
k
Returns
boolean wblut.geom.WB_HashGridDouble.setValue (final double value, final int i, final int j, final int k)
Parameters
value
i
j
k
Returns
References wblut.geom.WB_HashGridDouble.safeIndex().
int wblut.geom.WB_HashGridDouble.size ()
Returns
Member Data Documentation
final double wblut.geom.WB_HashGridDouble.defaultValue private
final int wblut.geom.WB_HashGridDouble.sizeI private
final LongDoubleHashMap wblut.geom.WB_HashGridDouble.values private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_HashGridDouble.java