HE_Mesh: wblut.hemesh.HET_WriterPOV Class Reference
wblut.hemesh.HET_WriterPOV Class Reference
Public Member Functions
void beginSave (final String path, final String name)
void beginSave (final PrintWriter pw)
void endSave ()
void beginMesh2 (final String name)
void endSection ()
void beginNormals (final int count)
void beginIndices (final int count)
void total (final int count)
void face (final int a, final int b, final int c)
int getCurrNormalOffset ()
int getCurrVertexOffset ()
void newObject (final String name)
void normal (final WB_Coord n)
void vertex (final WB_Coord v)
Protected Member Functions
void handleBeginSave ()
Protected Attributes
PrintWriter povWriter
int numVerticesWritten = 0
int numNormalsWritten = 0
Private Member Functions
StringBuilder buildVector (final int a, final int b, final int c)
StringBuilder buildVector (final WB_Coord n)
Member Function Documentation
void wblut.hemesh.HET_WriterPOV.beginIndices (final int count)
Output start of face_indices.
Parameters
count the count
References wblut.hemesh.HET_WriterPOV.total().
void wblut.hemesh.HET_WriterPOV.beginMesh2 (final String name)
Begin the mesh2 output as a PovRAY declaration.
Parameters
name the name
void wblut.hemesh.HET_WriterPOV.beginNormals (final int count)
Output start of normal_vectors.
Parameters
count the count
References wblut.hemesh.HET_WriterPOV.total().
void wblut.hemesh.HET_WriterPOV.beginSave (final String path, final String name)
Handles PrintWriter input.
Parameters
path
name
References wblut.hemesh.HET_WriterPOV.handleBeginSave().
void wblut.hemesh.HET_WriterPOV.beginSave (final PrintWriter pw)
Parameters
pw
References wblut.hemesh.HET_WriterPOV.handleBeginSave().
StringBuilder wblut.hemesh.HET_WriterPOV.buildVector (final int a, final int b, final int c) private
Builds the vector.
Parameters
a the a
b the b
c the c
Returns
the string builder
StringBuilder wblut.hemesh.HET_WriterPOV.buildVector (final WB_Coord n) private
Builds the vector.
Parameters
n the n
Returns
the string builder
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.hemesh.HET_WriterPOV.endSave ()
End of mesh2 declaration.
void wblut.hemesh.HET_WriterPOV.endSection ()
End the current section ie vertex_vector, normal_vector or face_indices.
void wblut.hemesh.HET_WriterPOV.face (final int a, final int b, final int c)
Face vertex indices.
Parameters
a the a
b the b
c the c
References wblut.hemesh.HET_WriterPOV.buildVector().
int wblut.hemesh.HET_WriterPOV.getCurrNormalOffset ()
Gets the curr normal offset.
Returns
the curr normal offset
References wblut.hemesh.HET_WriterPOV.numNormalsWritten.
int wblut.hemesh.HET_WriterPOV.getCurrVertexOffset ()
Gets the curr vertex offset.
Returns
the curr vertex offset
References wblut.hemesh.HET_WriterPOV.numVerticesWritten.
void wblut.hemesh.HET_WriterPOV.handleBeginSave () protected
Handle begin save.
void wblut.hemesh.HET_WriterPOV.newObject (final String name)
New object.
Parameters
name the name
void wblut.hemesh.HET_WriterPOV.normal (final WB_Coord n)
Triangle normals.
Parameters
n the n
References wblut.hemesh.HET_WriterPOV.buildVector().
void wblut.hemesh.HET_WriterPOV.total (final int count)
Used to output total count vertex_vector, normal_vector & face_indices.
Parameters
count the count
void wblut.hemesh.HET_WriterPOV.vertex (final WB_Coord v)
Triangle vertices.
Parameters
v the v
References wblut.hemesh.HET_WriterPOV.buildVector().
Member Data Documentation
int wblut.hemesh.HET_WriterPOV.numNormalsWritten = 0 protected
The num normals written.
int wblut.hemesh.HET_WriterPOV.numVerticesWritten = 0 protected
The num vertices written.
PrintWriter wblut.hemesh.HET_WriterPOV.povWriter protected
The pov writer.
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_WriterPOV.java