HE_Mesh: wblut.geom.WB_Earcut Class Reference
wblut.geom.WB_Earcut Class Reference
Classes
class Collinear
class EarcutException
enum EEarcutState
class Node
Static Public Member Functions
static final int[] triangulate2D (final WB_Polygon polygon)
static final long[] triangulate2Dkeys (final HE_Face face)
static final int[] triangulate2Dindices (final HE_Face face)
Private Member Functions
WB_Earcut ()
Static Private Member Functions
static final int[] earcut (final WB_IndexedPoint[][] pPoints, final boolean pIsClockwise)
static final Node onEliminateHoles (final WB_IndexedPoint[][] pPoints, Node lOuterNode, final boolean pIsZIndexed, final Deque< Collinear > collinears)
static final void onEliminateHole (final Node pHoleNode, Node pOuterNode, final boolean pIsZIndexed, final Deque< Collinear > collinears)
static final Node onEberlyFetchHoleBridge (final Node pHoleNode, final Node pOuterNode)
static final Node onFetchLeftmost (final Node pStart)
static final List< int[]> onEarcutLinkedList (Node lCurrentEar, final List< int[]> pTriangleList, final double pMinimumX, final double pMinimumY, final double pSize, final EEarcutState pEarcutState, final boolean pIsZIndexed, final Deque< Collinear > collinears)
static final boolean isEar (final Node pEar, final double pMinimumX, final double pMinimumY, final double pSize, final boolean pIsZIndexed)
static final Node onCureLocalIntersections (Node pStartNode, final List< int[]> pTriangleList)
static final void onSplitEarcut (final Node pStart, final List< int[]> pTriangleList, final double pMinimumX, final double pMinimumY, final double pSize, final boolean pIsZIndexed, final Deque< Collinear > collinears)
static final Node onSplitPolygon (final Node pNodeA, final Node pNodeB)
static final boolean isValidDiagonal (final Node pNodeA, final Node pNodeB)
static final boolean isLocallyInside (final Node pNodeA, final Node pNodeB)
static final boolean onMiddleInsert (final Node pPolygonStart, final double pX0, final double pY0, final double pX1, final double pY1)
static final boolean isIntersectingPolygon (final Node pStartNode, final double pX0, final double pY0, final double pX1, final double pY1)
static final boolean isIntersecting (final double pX0, final double pY0, final double pX1, final double pY1, final double pX2, final double pY2, final double pX3, final double pY3)
static final void onZIndexCurve (final Node pStartNode, final double pMinimumX, final double pMinimumY, final double pSize)
static final Node onTathamZSortList (Node pList)
static final int onCalculateZOrder (final double pX, final double pY, final double pMinimumX, final double pMinimumY, final double pSize)
static final Node onCreateDoublyLinkedList (final WB_IndexedPoint[] pPoints, final boolean pIsClockwise)
static final Node onFilterPoints (final Node pStartNode, Node pEndNode, final boolean pIsZIndexed, final Deque< Collinear > collinears)
static final Node onInsertNode (final WB_IndexedPoint p, final Node pLastNode)
static final boolean isVertexEquals (final double pX0, final double pY0, final double pX1, final double pY1)
static final WB_Classification onCalculateWindingOrder (final double pX0, final double pY0, final double pX1, final double pY1, final double pX2, final double pY2)
static List< int[]> reinsertCollinearPoints (final List< int[]> triangles, final Deque< Collinear > collinears)
static int triangleContainsEdge (final int[] triangle, final Collinear edge)
Static Private Attributes
static final Comparator< Node > COMPARATOR_SORT_BY_X
static final int CONTRACT_HOLES_INDEX = 1
static final int DEFAULT_THRESHOLD_SIMPLICITY = 80
static final int DEFAULT_COORDINATE_RANGE = 1000
Constructor & Destructor Documentation
wblut.geom.WB_Earcut.WB_Earcut () private
Member Function Documentation
static final int [] wblut.geom.WB_Earcut.earcut (final WB_IndexedPoint pPoints[][], final boolean pIsClockwise) static private
References wblut.geom.WB_Earcut.CONTRACT_HOLES_INDEX, wblut.geom.WB_Earcut.DEFAULT_THRESHOLD_SIMPLICITY, wblut.geom.WB_Earcut.EEarcutState.INIT, wblut.geom.WB_Earcut.onCreateDoublyLinkedList(), wblut.geom.WB_Earcut.onEarcutLinkedList(), wblut.geom.WB_Earcut.onEliminateHoles(), wblut.geom.WB_Earcut.onFilterPoints(), wblut.geom.WB_Earcut.onZIndexCurve(), wblut.geom.WB_Earcut.reinsertCollinearPoints(), and wblut.geom.WB_MutableCoordinate.xd().
static final boolean wblut.geom.WB_Earcut.isEar (final Node pEar, final double pMinimumX, final double pMinimumY, final double pSize, final boolean pIsZIndexed) static private
Determines whether a polygon node forms a valid ear with adjacent nodes.
References wblut.geom.WB_Earcut.onCalculateZOrder().
static final boolean wblut.geom.WB_Earcut.isIntersecting (final double pX0, final double pY0, final double pX1, final double pY1, final double pX2, final double pY2, final double pX3, final double pY3) static private
Determines whether two segments intersect.
References wblut.geom.WB_Earcut.onCalculateWindingOrder().
static final boolean wblut.geom.WB_Earcut.isIntersectingPolygon (final Node pStartNode, final double pX0, final double pY0, final double pX1, final double pY1) static private
Determines if the diagonal of a polygon is intersecting with any polygon elements.
References wblut.geom.WB_Earcut.isIntersecting().
static final boolean wblut.geom.WB_Earcut.isLocallyInside (final Node pNodeA, final Node pNodeB) static private
Determines whether a polygon diagonal rests locally within a polygon.
References wblut.geom.WB_Classification.COUNTERCLOCKWISE, and wblut.geom.WB_Earcut.onCalculateWindingOrder().
static final boolean wblut.geom.WB_Earcut.isValidDiagonal (final Node pNodeA, final Node pNodeB) static private
Determines whether a diagonal between two polygon nodes lies within a polygon interior. (This determines the validity of the ray.)
References wblut.geom.WB_Earcut.isIntersectingPolygon(), wblut.geom.WB_Earcut.isLocallyInside(), and wblut.geom.WB_Earcut.onMiddleInsert().
static final boolean wblut.geom.WB_Earcut.isVertexEquals (final double pX0, final double pY0, final double pX1, final double pY1) static private
Determines if two point vertices are equal.
static final WB_Classification wblut.geom.WB_Earcut.onCalculateWindingOrder (final double pX0, final double pY0, final double pX1, final double pY1, final double pX2, final double pY2) static private
Calculates the WindingOrder for a set of vertices.
References wblut.geom.WB_Classification.CLOCKWISE, wblut.geom.WB_Classification.COLLINEAR, wblut.geom.WB_Classification.COUNTERCLOCKWISE, and wblut.math.WB_Epsilon.EPSILON.
static final int wblut.geom.WB_Earcut.onCalculateZOrder (final double pX, final double pY, final double pMinimumX, final double pMinimumY, final double pSize) static private
Calculates the Z-Order of a given point given the vertex co-ordinates and size of the bounding box.
References wblut.geom.WB_Earcut.DEFAULT_COORDINATE_RANGE.
static final Node wblut.geom.WB_Earcut.onCreateDoublyLinkedList (final WB_IndexedPoint[] pPoints, final boolean pIsClockwise) static private
Creates a circular doubly linked list using polygon points. The order is governed by the specified winding order.
References wblut.geom.WB_Earcut.onInsertNode(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static final Node wblut.geom.WB_Earcut.onCureLocalIntersections (Node pStartNode, final List< int[]> pTriangleList) static private
Iterates through all polygon nodes and cures small local self-intersections.
References wblut.geom.WB_Earcut.isIntersecting(), and wblut.geom.WB_Earcut.isLocallyInside().
static final List<int[]> wblut.geom.WB_Earcut.onEarcutLinkedList (Node lCurrentEar, final List< int[]> pTriangleList, final double pMinimumX, final double pMinimumY, final double pSize, final EEarcutState pEarcutState, final boolean pIsZIndexed, final Deque< Collinear > collinears) static private
Main ear slicing loop which triangulates the vertices of a polygon, provided as a doubly-linked list.
References wblut.geom.WB_Earcut.EEarcutState.CURE, wblut.geom.WB_Earcut.isEar(), wblut.geom.WB_Earcut.onCureLocalIntersections(), wblut.geom.WB_Earcut.onEarcutLinkedList(), wblut.geom.WB_Earcut.onFilterPoints(), wblut.geom.WB_Earcut.onSplitEarcut(), and wblut.geom.WB_Earcut.EEarcutState.SPLIT.
static final Node wblut.geom.WB_Earcut.onEberlyFetchHoleBridge (final Node pHoleNode, final Node pOuterNode) static private
David Eberly's algorithm for finding a bridge between a hole and outer polygon.
References wblut.geom.WB_Earcut.isLocallyInside().
static final void wblut.geom.WB_Earcut.onEliminateHole (final Node pHoleNode, Node pOuterNode, final boolean pIsZIndexed, final Deque< Collinear > collinears) static private
Finds a bridge between vertices that connects a hole with an outer ring, and links it.
References wblut.geom.WB_Earcut.onEberlyFetchHoleBridge(), wblut.geom.WB_Earcut.onFilterPoints(), and wblut.geom.WB_Earcut.onSplitPolygon().
static final Node wblut.geom.WB_Earcut.onEliminateHoles (final WB_IndexedPoint pPoints[][], Node lOuterNode, final boolean pIsZIndexed, final Deque< Collinear > collinears) static private
Links every hole into the outer loop, producing a single-ring polygon without holes.
References wblut.geom.WB_Earcut.COMPARATOR_SORT_BY_X, wblut.geom.WB_Earcut.CONTRACT_HOLES_INDEX, wblut.geom.WB_Earcut.onCreateDoublyLinkedList(), wblut.geom.WB_Earcut.onEliminateHole(), wblut.geom.WB_Earcut.onFetchLeftmost(), and wblut.geom.WB_Earcut.onFilterPoints().
static final Node wblut.geom.WB_Earcut.onFetchLeftmost (final Node pStart) static private
Finds the left-most hole of a polygon ring.
static final Node wblut.geom.WB_Earcut.onFilterPoints (final Node pStartNode, Node pEndNode, final boolean pIsZIndexed, final Deque< Collinear > collinears) static private
Eliminates colinear/duplicate points.
References wblut.geom.WB_Classification.COLLINEAR, wblut.geom.WB_Earcut.isVertexEquals(), and wblut.geom.WB_Earcut.onCalculateWindingOrder().
static final Node wblut.geom.WB_Earcut.onInsertNode (final WB_IndexedPoint p, final Node pLastNode) static private
Creates a node and optionally links it with a previous node in a circular doubly-linked list.
static final boolean wblut.geom.WB_Earcut.onMiddleInsert (final Node pPolygonStart, final double pX0, final double pY0, final double pX1, final double pY1) static private
Determines whether the middle point of a polygon diagonal is contained within the polygon.
static final void wblut.geom.WB_Earcut.onSplitEarcut (final Node pStart, final List< int[]> pTriangleList, final double pMinimumX, final double pMinimumY, final double pSize, final boolean pIsZIndexed, final Deque< Collinear > collinears) static private
Tries to split a polygon and triangulate each side independently.
References wblut.geom.WB_Earcut.EEarcutState.INIT, wblut.geom.WB_Earcut.isValidDiagonal(), wblut.geom.WB_Earcut.onEarcutLinkedList(), wblut.geom.WB_Earcut.onFilterPoints(), and wblut.geom.WB_Earcut.onSplitPolygon().
static final Node wblut.geom.WB_Earcut.onSplitPolygon (final Node pNodeA, final Node pNodeB) static private
Links two polygon vertices using a bridge.
static final Node wblut.geom.WB_Earcut.onTathamZSortList (Node pList) static private
Simon Tatham's doubly-linked list merge/sort algorithm. (http://www.chiark.greenend.org.uk/~sgtatham/algorithms/listsort.html)
static final void wblut.geom.WB_Earcut.onZIndexCurve (final Node pStartNode, final double pMinimumX, final double pMinimumY, final double pSize) static private
Interlinks polygon nodes in Z-Order.
References wblut.geom.WB_Earcut.onCalculateZOrder(), and wblut.geom.WB_Earcut.onTathamZSortList().
static List<int[]> wblut.geom.WB_Earcut.reinsertCollinearPoints (final List< int[]> triangles, final Deque< Collinear > collinears) static private
References wblut.geom.WB_Earcut.triangleContainsEdge().
static int wblut.geom.WB_Earcut.triangleContainsEdge (final int[] triangle, final Collinear edge) static private
static final int [] wblut.geom.WB_Earcut.triangulate2D (final WB_Polygon polygon) static
References wblut.geom.WB_Earcut.earcut(), wblut.geom.WB_Polygon.getPlane(), wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_Map.mapPoint3D().
static final int [] wblut.geom.WB_Earcut.triangulate2Dindices (final HE_Face face) static
References wblut.geom.WB_Earcut.earcut(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Face.getPlane(), wblut.hemesh.HE_Halfedge.getVertex(), and wblut.geom.WB_Map.mapPoint3D().
static final long [] wblut.geom.WB_Earcut.triangulate2Dkeys (final HE_Face face) static
References wblut.geom.WB_Earcut.earcut(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Element.getKey(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Face.getPlane(), wblut.hemesh.HE_Halfedge.getVertex(), and wblut.geom.WB_Map.mapPoint3D().
Member Data Documentation
final Comparator<Node> wblut.geom.WB_Earcut.COMPARATOR_SORT_BY_X static private
Initial value:
= new Comparator<Node>() {
        @Override
        public int compare(final Node pNodeA, final Node pNodeB) {
            return pNodeA.xd() < pNodeB.xd() ? -1 : pNodeA.xd() == pNodeB.xd() ? 0 : 1;
        }
    }
final int wblut.geom.WB_Earcut.CONTRACT_HOLES_INDEX = 1 static private
final int wblut.geom.WB_Earcut.DEFAULT_COORDINATE_RANGE = 1000 static private
final int wblut.geom.WB_Earcut.DEFAULT_THRESHOLD_SIMPLICITY = 80 static private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Earcut.java