HE_Mesh: wblut.geom.WB_IsoValues3D.ImageStack3D Class Reference
wblut.geom.WB_IsoValues3D.ImageStack3D Class Reference
Public Member Functions
ImageStack3D (final String[] images, final PApplet home, final int sizeI, final int sizeJ, final int sizeK, final Mode mode)
ImageStack3D (final String[] images, final PApplet home, final int sizeI, final int sizeJ, final int sizeK)
double getValue (final int i, final int j, final int k)
int getSizeI ()
int getSizeJ ()
int getSizeK ()
Public Member Functions inherited from wblut.geom.WB_IsoValues3D
abstract double getValue (int i, int j, int k)
abstract int getSizeI ()
abstract int getSizeJ ()
abstract int getSizeK ()
WB_BinaryGrid3D getBinaryGrid3D (final int sizeX, final int sizeY, final int sizeZ, final double threshold)
Private Member Functions
void initialize ()
void fillSlice (final int k, final double[][] values)
void incrementSlice ()
double[][] updateSlice (final int k)
double getSingleSliceValue (final PImage img, final int i, final int j)
Private Attributes
String[] images
double[][] sliceK
int currentK
int sizeI
Mode mode
PApplet home
PImage slice
Constructor & Destructor Documentation
wblut.geom.WB_IsoValues3D.ImageStack3D.ImageStack3D (final String[] images, final PApplet home, final int sizeI, final int sizeJ, final int sizeK, final Mode mode)
References wblut.geom.WB_IsoValues3D.ImageStack3D.home, wblut.geom.WB_IsoValues3D.ImageStack3D.images, wblut.geom.WB_IsoValues3D.ImageStack3D.initialize(), wblut.geom.WB_IsoValues3D.ImageStack3D.mode, and wblut.geom.WB_IsoValues3D.ImageStack3D.sizeI.
wblut.geom.WB_IsoValues3D.ImageStack3D.ImageStack3D (final String[] images, final PApplet home, final int sizeI, final int sizeJ, final int sizeK)
References wblut.geom.WB_IsoValues3D.Mode.BRI, wblut.geom.WB_IsoValues3D.ImageStack3D.home, wblut.geom.WB_IsoValues3D.ImageStack3D.images, wblut.geom.WB_IsoValues3D.ImageStack3D.initialize(), and wblut.geom.WB_IsoValues3D.ImageStack3D.sizeI.
Member Function Documentation
void wblut.geom.WB_IsoValues3D.ImageStack3D.fillSlice (final int k, final double values[][]) private
References wblut.geom.WB_IsoValues3D.ImageStack3D.getSingleSliceValue(), and wblut.geom.WB_IsoValues3D.ImageStack3D.sizeI.
double wblut.geom.WB_IsoValues3D.ImageStack3D.getSingleSliceValue (final PImage img, final int i, final int j) private
int wblut.geom.WB_IsoValues3D.ImageStack3D.getSizeI ()
References wblut.geom.WB_IsoValues3D.ImageStack3D.sizeI.
int wblut.geom.WB_IsoValues3D.ImageStack3D.getSizeJ ()
int wblut.geom.WB_IsoValues3D.ImageStack3D.getSizeK ()
double wblut.geom.WB_IsoValues3D.ImageStack3D.getValue (final int i, final int j, final int k)
References wblut.geom.WB_IsoValues3D.ImageStack3D.incrementSlice(), and wblut.geom.WB_IsoValues3D.ImageStack3D.updateSlice().
void wblut.geom.WB_IsoValues3D.ImageStack3D.incrementSlice () private
References wblut.geom.WB_IsoValues3D.ImageStack3D.fillSlice(), and wblut.geom.WB_IsoValues3D.ImageStack3D.sliceK.
void wblut.geom.WB_IsoValues3D.ImageStack3D.initialize () private
References wblut.geom.WB_IsoValues3D.ImageStack3D.fillSlice(), and wblut.geom.WB_IsoValues3D.ImageStack3D.sizeI.
double [][] wblut.geom.WB_IsoValues3D.ImageStack3D.updateSlice (final int k) private
References wblut.geom.WB_IsoValues3D.ImageStack3D.fillSlice(), and wblut.geom.WB_IsoValues3D.ImageStack3D.sliceK.
Member Data Documentation
int wblut.geom.WB_IsoValues3D.ImageStack3D.currentK private
PApplet wblut.geom.WB_IsoValues3D.ImageStack3D.home private
String [] wblut.geom.WB_IsoValues3D.ImageStack3D.images private
Mode wblut.geom.WB_IsoValues3D.ImageStack3D.mode private
int wblut.geom.WB_IsoValues3D.ImageStack3D.sizeI private
PImage wblut.geom.WB_IsoValues3D.ImageStack3D.slice private
double [][] wblut.geom.WB_IsoValues3D.ImageStack3D.sliceK private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_IsoValues3D.java