HE_Mesh: wblut.hemesh.HET_InfoFace< E extends Object >.HET_FaceNormal Class Reference
wblut.hemesh.HET_InfoFace< E extends Object >.HET_FaceNormal Class Reference
Public Member Functions
WB_Vector retrieve (final HE_Face face)
Public Member Functions inherited from wblut.hemesh.HET_InfoFace< WB_Vector >
E retrieve (final HE_Face face)
Member Function Documentation
WB_Vector wblut.hemesh.HET_InfoFace< E extends Object >.HET_FaceNormal.retrieve (final HE_Face face)
References wblut.geom.WB_Vector.addSelf(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_Vector.normalizeSelf(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), and wblut.hemesh.HE_Vertex.zd().
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_InfoFace.java