HE_Mesh: wblut.hemesh.HET_MeshGraph Class Reference
wblut.hemesh.HET_MeshGraph Class Reference
Classes
class Edge
class Node
Public Member Functions
HET_MeshGraph (final WB_Mesh mesh)
HET_MeshGraph (final WB_Mesh mesh, final double offset)
HET_MeshGraph (final HE_Mesh mesh)
HET_MeshGraph (final HE_Mesh mesh, final double offset)
HET_MeshGraph (final List<?extends WB_Coord > points, final WB_Triangulation3D triangulation)
HET_MeshGraph (final WB_Coord[] points, final WB_Triangulation3D triangulation)
HET_MeshGraph (final WB_Coord[] points, final WB_Triangulation2D triangulation)
int getNodeIndex (final int i)
void computePathsToVertex (final int i)
int[] getShortestPathBetweenVertices (final int source, final int target)
double getShortestDistanceBetweenVertices (final int source, final int target)
WB_Network getNetwork (final int i)
WB_Network getNetwork (final int i, final int maxnodes)
WB_Network getNetwork (final int i, final int maxnodes, final double offset)
WB_Network getNetwork (final int i, final int maxnodes, final int cuttail)
Static Public Member Functions
static void main (final String[] args)
static List< HET_MeshGraph > getAllGraphs (final HE_Mesh mesh)
Private Attributes
final Node[] nodes
int lastSource
Constructor & Destructor Documentation
wblut.hemesh.HET_MeshGraph.HET_MeshGraph (final WB_Mesh mesh)
Parameters
mesh
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Mesh.getEdgesAsInt(), wblut.geom.WB_Mesh.getNumberOfVertices(), wblut.geom.WB_Mesh.getVertex(), and wblut.hemesh.HET_MeshGraph.Node.neighbors.
wblut.hemesh.HET_MeshGraph.HET_MeshGraph (final WB_Mesh mesh, final double offset)
Parameters
mesh
offset
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Mesh.getEdgesAsInt(), wblut.geom.WB_Mesh.getNumberOfVertices(), wblut.geom.WB_Mesh.getVertex(), wblut.geom.WB_Mesh.getVertexNormal(), and wblut.hemesh.HET_MeshGraph.Node.neighbors.
wblut.hemesh.HET_MeshGraph.HET_MeshGraph (final HE_Mesh mesh)
Parameters
mesh
wblut.hemesh.HET_MeshGraph.HET_MeshGraph (final HE_Mesh mesh, final double offset)
Parameters
mesh
offset
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.hemesh.HE_Mesh.getEdgesAsInt(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Mesh.getVertex(), wblut.hemesh.HE_Mesh.getVertexNormal(), and wblut.hemesh.HET_MeshGraph.Node.neighbors.
wblut.hemesh.HET_MeshGraph.HET_MeshGraph (final List<?extends WB_Coord > points, final WB_Triangulation3D triangulation)
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Triangulation3D.getEdges(), and wblut.hemesh.HET_MeshGraph.Node.neighbors.
wblut.hemesh.HET_MeshGraph.HET_MeshGraph (final WB_Coord[] points, final WB_Triangulation3D triangulation)
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Triangulation3D.getEdges(), and wblut.hemesh.HET_MeshGraph.Node.neighbors.
wblut.hemesh.HET_MeshGraph.HET_MeshGraph (final WB_Coord[] points, final WB_Triangulation2D triangulation)
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Triangulation2D.getEdges(), and wblut.hemesh.HET_MeshGraph.Node.neighbors.
Member Function Documentation
void wblut.hemesh.HET_MeshGraph.computePathsToVertex (final int i)
Parameters
i
References wblut.hemesh.HET_MeshGraph.Node.distanceToSource, wblut.hemesh.HET_MeshGraph.Node.neighbors, wblut.hemesh.HET_MeshGraph.Node.previous, wblut.hemesh.HET_MeshGraph.Node.reset(), wblut.hemesh.HET_MeshGraph.Edge.target, and wblut.hemesh.HET_MeshGraph.Edge.weight.
static List<HET_MeshGraph> wblut.hemesh.HET_MeshGraph.getAllGraphs (final HE_Mesh mesh) static
References wblut.hemesh.HE_MeshCollection.getMesh(), wblut.hemesh.HE_MeshCollection.getNumberOfMeshes(), wblut.hemesh.HET_MeshGraph.HET_MeshGraph(), and wblut.hemesh.HEMC_Explode.setMesh().
WB_Network wblut.hemesh.HET_MeshGraph.getNetwork (final int i)
Parameters
i
Returns
References wblut.geom.WB_Network.addConnection(), wblut.geom.WB_Network.addNode(), wblut.hemesh.HET_MeshGraph.computePathsToVertex(), wblut.geom.WB_Network.getNode(), and wblut.hemesh.HET_MeshGraph.getShortestPathBetweenVertices().
WB_Network wblut.hemesh.HET_MeshGraph.getNetwork (final int i, final int maxnodes)
Parameters
i
maxnodes
Returns
References wblut.geom.WB_Network.addConnection(), wblut.geom.WB_Network.addNode(), wblut.hemesh.HET_MeshGraph.computePathsToVertex(), wblut.geom.WB_Network.getNode(), wblut.hemesh.HET_MeshGraph.getShortestPathBetweenVertices(), and wblut.hemesh.HET_MeshGraph.nodes.
WB_Network wblut.hemesh.HET_MeshGraph.getNetwork (final int i, final int maxnodes, final double offset)
References wblut.geom.WB_Network.addConnection(), wblut.geom.WB_Network.addNode(), wblut.hemesh.HET_MeshGraph.computePathsToVertex(), wblut.geom.WB_Network.getNode(), and wblut.hemesh.HET_MeshGraph.getShortestPathBetweenVertices().
WB_Network wblut.hemesh.HET_MeshGraph.getNetwork (final int i, final int maxnodes, final int cuttail)
Parameters
i
maxnodes
cuttail
Returns
References wblut.geom.WB_Network.addConnection(), wblut.geom.WB_Network.addNode(), wblut.hemesh.HET_MeshGraph.computePathsToVertex(), wblut.geom.WB_Network.getNode(), wblut.hemesh.HET_MeshGraph.getShortestPathBetweenVertices(), and wblut.hemesh.HET_MeshGraph.nodes.
int wblut.hemesh.HET_MeshGraph.getNodeIndex (final int i)
Parameters
i
Returns
References wblut.hemesh.HET_MeshGraph.Node.index.
double wblut.hemesh.HET_MeshGraph.getShortestDistanceBetweenVertices (final int source, final int target)
References wblut.hemesh.HET_MeshGraph.computePathsToVertex(), and wblut.hemesh.HET_MeshGraph.Node.distanceToSource.
int [] wblut.hemesh.HET_MeshGraph.getShortestPathBetweenVertices (final int source, final int target)
Parameters
source
target
Returns
References wblut.hemesh.HET_MeshGraph.computePathsToVertex(), and wblut.hemesh.HET_MeshGraph.Node.previous.
static void wblut.hemesh.HET_MeshGraph.main (final String[] args) static
Parameters
args
References wblut.geom.WB_Geodesic.create(), wblut.hemesh.HET_MeshGraph.Node.distanceToSource, wblut.hemesh.HET_MeshGraph.getShortestPathBetweenVertices(), wblut.hemesh.HET_MeshGraph.HET_MeshGraph(), wblut.geom.WB_Geodesic.Type.ICOSAHEDRON, wblut.hemesh.HET_MeshGraph.Node.index, wblut.hemesh.HET_MeshGraph.nodes, and wblut.hemesh.HE_Mesh.smooth().
Member Data Documentation
int wblut.hemesh.HET_MeshGraph.lastSource private
final Node [] wblut.hemesh.HET_MeshGraph.nodes private
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_MeshGraph.java