HE_Mesh: wblut.hemesh.HEM_EqualizeValence Class Reference
wblut.hemesh.HEM_EqualizeValence Class Reference
Public Member Functions
HEM_EqualizeValence ()
HEM_EqualizeValence setThreshold (final double a)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
double threshold
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Bend a mesh. Determined by a ground plane, a bend axis and an angle factor.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_EqualizeValence.HEM_EqualizeValence ()
Instantiates a new HEM_Bend.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_EqualizeValence.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HET_MeshOp.flipEdge(), wblut.hemesh.HE_Mesh.getEdges(), wblut.hemesh.HE_Vertex.getNextInFace(), wblut.hemesh.HE_Vertex.getVertexDegree(), wblut.hemesh.HE_Vertex.isBoundary(), wblut.hemesh.HEM_EqualizeValence.threshold, and wblut.hemesh.HE_Mesh.triangulate().
HE_Mesh wblut.hemesh.HEM_EqualizeValence.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HET_MeshOp.flipEdge(), wblut.hemesh.HE_Selection.getInnerEdges(), wblut.hemesh.HE_Vertex.getNextInFace(), wblut.hemesh.HE_Vertex.getVertexDegree(), wblut.hemesh.HE_Vertex.isBoundary(), wblut.hemesh.HEM_EqualizeValence.threshold, and wblut.hemesh.HE_Mesh.triangulate().
HEM_EqualizeValence wblut.hemesh.HEM_EqualizeValence.setThreshold (final double a)
Set threshold angle.
Parameters
a threshold angle in radians
Returns
self
Member Data Documentation
double wblut.hemesh.HEM_EqualizeValence.threshold private
threshold.
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_EqualizeValence.java