HE_Mesh: wblut.geom.WB_RandomBox Class Reference
wblut.geom.WB_RandomBox Class Reference
Public Member Functions
WB_RandomBox ()
WB_RandomBox (final long seed)
WB_RandomBox setSeed (final long seed)
WB_RandomBox setSize (final double X, final double Y, final double Z)
WB_RandomBox set (final WB_AABB AABB)
WB_Point nextPoint ()
WB_Vector nextVector ()
void reset ()
WB_RandomBox setOffset (final WB_Coord offset)
WB_RandomBox setOffset (final double x, final double y)
WB_RandomBox setOffset (final double x, final double y, final double z)
Public Member Functions inherited from wblut.geom.WB_RandomPoint
WB_RandomPoint setOffset (WB_Coord offset)
WB_RandomPoint setOffset (double x, double y)
WB_RandomPoint setOffset (double x, double y, double z)
Private Attributes
final WB_MTRandom randomGen
double X
WB_Vector offset
Detailed Description
Random generator for vectors uniformly distributed in the halfopen box [-X/2,-Y/2,-Z/2]-(X/2,Y/2,Z/2).
Author
Frederik Vanhoutte, W:Blut
Constructor & Destructor Documentation
wblut.geom.WB_RandomBox.WB_RandomBox ()
wblut.geom.WB_RandomBox.WB_RandomBox (final long seed)
Parameters
seed
Member Function Documentation
WB_Point wblut.geom.WB_RandomBox.nextPoint ()
Get the next random point.
Returns
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.nextCenteredDouble().
WB_Vector wblut.geom.WB_RandomBox.nextVector ()
Get the next random vector.
Returns
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.nextCenteredDouble().
void wblut.geom.WB_RandomBox.reset ()
Reset the RNG.
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.reset().
WB_RandomBox wblut.geom.WB_RandomBox.set (final WB_AABB AABB)
References wblut.geom.WB_AABB.getCenterX(), wblut.geom.WB_AABB.getCenterY(), wblut.geom.WB_AABB.getCenterZ(), wblut.geom.WB_AABB.getDepth(), wblut.geom.WB_AABB.getHeight(), wblut.geom.WB_AABB.getWidth(), and wblut.geom.WB_MutableCoordinate.set().
WB_RandomBox wblut.geom.WB_RandomBox.setOffset (final WB_Coord offset)
WB_RandomBox wblut.geom.WB_RandomBox.setOffset (final double x, final double y)
References wblut.geom.WB_MutableCoordinate.set().
WB_RandomBox wblut.geom.WB_RandomBox.setOffset (final double x, final double y, final double z)
References wblut.geom.WB_MutableCoordinate.set().
WB_RandomBox wblut.geom.WB_RandomBox.setSeed (final long seed)
Set the seed for the RNG.
Parameters
seed
Returns
this
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.setSeed().
WB_RandomBox wblut.geom.WB_RandomBox.setSize (final double X, final double Y, final double Z)
Parameters
X
Y
Z
Returns
References wblut.geom.WB_RandomBox.X.
Member Data Documentation
WB_Vector wblut.geom.WB_RandomBox.offset private
final WB_MTRandom wblut.geom.WB_RandomBox.randomGen private
double wblut.geom.WB_RandomBox.X private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_RandomBox.java