HE_Mesh: wblut.geom.WB_IndexedSegment Class Reference
wblut.geom.WB_IndexedSegment Class Reference
Public Member Functions
WB_IndexedSegment (final int i1, final int i2, final WB_Coord[] points)
int i1 ()
int i2 ()
WB_IndexedSegment negate ()
void reverse ()
Public Member Functions inherited from wblut.geom.WB_Segment
WB_Segment ()
WB_Segment (final WB_Coord o, final WB_Coord d, final double l)
WB_Segment (final WB_Coord p1, final WB_Coord p2)
WB_Segment (final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
WB_Point getParametricPoint (final double t)
void getParametricPointInto (final double t, final WB_MutableCoord result)
WB_Coord getEndpoint ()
WB_Point getCenter ()
double getLength ()
WB_Segment negate ()
void reverse ()
WB_Segment apply (final WB_Transform T)
WB_Point curvePoint (final double u)
double getLowerU ()
double getUpperU ()
WB_Vector curveDirection (final double u)
WB_Vector curveDerivative (final double u)
boolean equals (final Object o)
int hashCode ()
Public Member Functions inherited from wblut.geom.WB_Line
WB_Line ()
WB_Line (final WB_Coord o, final WB_Coord d)
WB_Line (final double ox, final double oy, final double oz, final double dx, final double dy, final double dz)
WB_Line (final double ox, final double oy, final double dx, final double dy)
String toString ()
void setFromPoints (final WB_Coord p1, final WB_Coord p2)
double getT (final WB_Coord p)
WB_Point curvePoint (final double u)
WB_Vector curveDirection (final double u)
WB_Vector curveDerivative (final double u)
double getLowerU ()
double getUpperU ()
double a ()
double b ()
double c ()
WB_Coord getDirection ()
WB_Vector getNormal ()
WB_Coord getOrigin ()
WB_Point getParametricPoint (final double t)
void getParametricPointInto (final double t, final WB_MutableCoord result)
WB_Point getPoint (final double t)
void getPointInto (final double t, final WB_MutableCoord result)
boolean equals (final Object o)
int hashCode ()
Public Member Functions inherited from wblut.geom.WB_Curve
WB_Point curvePoint (double u)
WB_Vector curveDirection (double u)
WB_Vector curveDerivative (double u)
Protected Member Functions
WB_IndexedSegment (final int i1, final int i2, final WB_Coord p1, final WB_Coord p2)
Protected Member Functions inherited from wblut.geom.WB_Line
void set (final WB_Coord o, final WB_Coord d)
Private Attributes
int i1
int i2
Additional Inherited Members
Static Public Member Functions inherited from wblut.geom.WB_Segment
static WB_Segment X ()
static WB_Segment Y ()
static WB_Segment Z ()
static List< WB_Segment > negate (final List< WB_Segment > segs)
Static Public Member Functions inherited from wblut.geom.WB_Line
static WB_Line X ()
static WB_Line Y ()
static WB_Line Z ()
Protected Attributes inherited from wblut.geom.WB_Segment
double length
WB_Point endpoint
Protected Attributes inherited from wblut.geom.WB_Line
WB_Point origin
WB_Vector direction
Constructor & Destructor Documentation
wblut.geom.WB_IndexedSegment.WB_IndexedSegment (final int i1, final int i2, final WB_Coord[] points)
Parameters
i1
i2
points
References wblut.geom.WB_IndexedSegment.i1(), and wblut.geom.WB_IndexedSegment.i2().
wblut.geom.WB_IndexedSegment.WB_IndexedSegment (final int i1, final int i2, final WB_Coord p1, final WB_Coord p2) protected
Parameters
i1
i2
p1
p2
References wblut.geom.WB_IndexedSegment.i1(), and wblut.geom.WB_IndexedSegment.i2().
Member Function Documentation
int wblut.geom.WB_IndexedSegment.i1 ()
Returns
int wblut.geom.WB_IndexedSegment.i2 ()
Returns
WB_IndexedSegment wblut.geom.WB_IndexedSegment.negate ()
References wblut.geom.WB_Segment.endpoint, wblut.geom.WB_Line.origin, and wblut.geom.WB_IndexedSegment.WB_IndexedSegment().
void wblut.geom.WB_IndexedSegment.reverse ()
References wblut.geom.WB_Line.direction, wblut.geom.WB_Segment.endpoint, wblut.geom.WB_IndexedSegment.i1(), wblut.geom.WB_IndexedSegment.i2(), wblut.geom.WB_Vector.mulSelf(), and wblut.geom.WB_Line.origin.
Member Data Documentation
int wblut.geom.WB_IndexedSegment.i1 private
int wblut.geom.WB_IndexedSegment.i2 private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_IndexedSegment.java