HE_Mesh: wblut.geom.WB_OrthoProject Class Reference
wblut.geom.WB_OrthoProject Class Reference
Public Member Functions
WB_OrthoProject ()
WB_OrthoProject (final int mode)
WB_OrthoProject (final WB_Coord v)
WB_OrthoProject (final WB_Plane P)
void set (final WB_Coord c)
void mapPoint3D (final WB_Coord p, final WB_MutableCoord result)
void mapPoint3D (final double x, final double y, final double z, final WB_MutableCoord result)
void unmapPoint3D (final WB_Coord p, final WB_MutableCoord result)
void unmapPoint3D (final double u, final double v, final double w, final WB_MutableCoord result)
void unmapPoint2D (final double u, final double v, final WB_MutableCoord result)
void unmapPoint2D (final WB_Coord p, final WB_MutableCoord result)
void mapVector3D (final WB_Coord v, final WB_MutableCoord result)
void mapVector3D (final double x, final double y, final double z, final WB_MutableCoord result)
void unmapVector3D (final WB_Coord v, final WB_MutableCoord result)
void unmapVector3D (final double u, final double v, final double w, final WB_MutableCoord result)
void unmapVector2D (final double u, final double v, final WB_MutableCoord result)
void unmapVector2D (final WB_Coord v, final WB_MutableCoord result)
WB_Point mapPoint3D (final WB_Coord p)
WB_Point mapPoint3D (final double x, final double y, final double z)
WB_Point unmapPoint3D (final WB_Coord p)
WB_Point unmapPoint3D (final double u, final double v, final double w)
WB_Point unmapPoint2D (final double u, final double v)
WB_Point unmapPoint2D (final WB_Coord p)
WB_Vector mapVector3D (final WB_Coord v)
WB_Vector mapVector3D (final double x, final double y, final double z)
WB_Vector unmapVector3D (final WB_Coord v)
WB_Vector unmapVector3D (final double u, final double v, final double w)
WB_Vector unmapVector2D (final double u, final double v)
WB_Vector unmapVector2D (final WB_Coord v)
Public Member Functions inherited from wblut.geom.WB_Map2D
void unmapPoint2D (WB_Coord p, WB_MutableCoord result)
void unmapPoint2D (double u, double v, WB_MutableCoord result)
void unmapVector2D (WB_Coord v, WB_MutableCoord result)
void unmapVector2D (double u, double v, WB_MutableCoord result)
WB_Coord unmapPoint2D (WB_Coord p)
WB_Coord unmapPoint2D (double u, double v)
WB_Coord unmapVector2D (WB_Coord v)
WB_Coord unmapVector2D (double u, double v)
Public Member Functions inherited from wblut.geom.WB_Map
void mapPoint3D (WB_Coord p, WB_MutableCoord result)
void mapPoint3D (double x, double y, double z, WB_MutableCoord result)
void unmapPoint3D (WB_Coord p, WB_MutableCoord result)
void unmapPoint3D (double u, double v, double w, WB_MutableCoord result)
void mapVector3D (WB_Coord p, WB_MutableCoord result)
void mapVector3D (double x, double y, double z, WB_MutableCoord result)
void unmapVector3D (WB_Coord p, WB_MutableCoord result)
void unmapVector3D (double u, double v, double w, WB_MutableCoord result)
WB_Coord mapPoint3D (WB_Coord p)
WB_Coord mapPoint3D (double x, double y, double z)
WB_Coord unmapPoint3D (WB_Coord p)
WB_Coord unmapPoint3D (double u, double v, double w)
WB_Coord mapVector3D (WB_Coord p)
WB_Coord mapVector3D (double x, double y, double z)
WB_Coord unmapVector3D (WB_Coord p)
WB_Coord unmapVector3D (double u, double v, double w)
Static Public Attributes
static final int YZ = 0
static final int XZ = 1
static final int XY = 2
static final int YZrev = 3
static final int XZrev = 4
static final int XYrev = 5
Private Attributes
int mode
Detailed Description
WB_OrthoProject projects coordinates from world space to the X, Y or Z-plane. Since a projection is not reversible, the 2D-to-3D functions always return a point on the X-,Y- or Z-plane, unless the w-coordinate is explicitly given.
Constructor & Destructor Documentation
wblut.geom.WB_OrthoProject.WB_OrthoProject ()
References wblut.geom.WB_OrthoProject.XY.
wblut.geom.WB_OrthoProject.WB_OrthoProject (final int mode)
Parameters
mode
References wblut.geom.WB_OrthoProject.mode.
wblut.geom.WB_OrthoProject.WB_OrthoProject (final WB_Coord v)
Parameters
v
References wblut.geom.WB_OrthoProject.set().
wblut.geom.WB_OrthoProject.WB_OrthoProject (final WB_Plane P)
Parameters
P
References wblut.geom.WB_Plane.getNormal(), and wblut.geom.WB_OrthoProject.set().
Member Function Documentation
void wblut.geom.WB_OrthoProject.mapPoint3D (final WB_Coord p, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_OrthoProject.mapPoint3D (final double x, final double y, final double z, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set().
WB_Point wblut.geom.WB_OrthoProject.mapPoint3D (final WB_Coord p)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point wblut.geom.WB_OrthoProject.mapPoint3D (final double x, final double y, final double z)
References wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_OrthoProject.mapVector3D (final WB_Coord v, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_OrthoProject.mapVector3D (final double x, final double y, final double z, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set().
WB_Vector wblut.geom.WB_OrthoProject.mapVector3D (final WB_Coord v)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_OrthoProject.mapVector3D (final double x, final double y, final double z)
References wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_OrthoProject.set (final WB_Coord c)
Parameters
c
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_OrthoProject.XYrev, wblut.geom.WB_OrthoProject.XZrev, wblut.geom.WB_Coord.yd(), wblut.geom.WB_OrthoProject.YZrev, and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_OrthoProject.unmapPoint2D (final double u, final double v, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_OrthoProject.unmapPoint2D (final WB_Coord p, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
WB_Point wblut.geom.WB_OrthoProject.unmapPoint2D (final double u, final double v)
References wblut.geom.WB_MutableCoordinate.set().
WB_Point wblut.geom.WB_OrthoProject.unmapPoint2D (final WB_Coord p)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
void wblut.geom.WB_OrthoProject.unmapPoint3D (final WB_Coord p, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_OrthoProject.unmapPoint3D (final double u, final double v, final double w, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set().
WB_Point wblut.geom.WB_OrthoProject.unmapPoint3D (final WB_Coord p)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_OrthoProject.unmapPoint3D (final double u, final double v, final double w)
References wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_OrthoProject.unmapVector2D (final double u, final double v, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_OrthoProject.unmapVector2D (final WB_Coord v, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
WB_Vector wblut.geom.WB_OrthoProject.unmapVector2D (final double u, final double v)
References wblut.geom.WB_MutableCoordinate.set().
WB_Vector wblut.geom.WB_OrthoProject.unmapVector2D (final WB_Coord v)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
void wblut.geom.WB_OrthoProject.unmapVector3D (final WB_Coord v, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_OrthoProject.unmapVector3D (final double u, final double v, final double w, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set().
WB_Vector wblut.geom.WB_OrthoProject.unmapVector3D (final WB_Coord v)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_OrthoProject.unmapVector3D (final double u, final double v, final double w)
References wblut.geom.WB_MutableCoordinate.set().
Member Data Documentation
int wblut.geom.WB_OrthoProject.mode private
final int wblut.geom.WB_OrthoProject.XY = 2 static
final int wblut.geom.WB_OrthoProject.XYrev = 5 static
final int wblut.geom.WB_OrthoProject.XZ = 1 static
final int wblut.geom.WB_OrthoProject.XZrev = 4 static
final int wblut.geom.WB_OrthoProject.YZ = 0 static
final int wblut.geom.WB_OrthoProject.YZrev = 3 static
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_OrthoProject.java