HE_Mesh: wblut.hemesh.HEM_Crocodile Class Reference
wblut.hemesh.HEM_Crocodile Class Reference
Public Member Functions
HEM_Crocodile ()
HEM_Crocodile setDistance (final double d)
HEM_Crocodile setDistance (final WB_ScalarParameter d)
HEM_Crocodile setChamfer (final double c)
HEM_Crocodile setChamfer (final WB_ScalarParameter c)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_ScalarParameter distance
WB_ScalarParameter chamfer
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_Crocodile.HEM_Crocodile ()
References wblut.math.WB_ScalarParameter.ZERO.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Crocodile.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HEM_Modifier.apply(), and wblut.hemesh.HE_Mesh.selectAllVertices().
HE_Mesh wblut.hemesh.HEM_Crocodile.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.hemesh.HE_Selection.collectVertices(), wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Vertex.getEdgeStar(), wblut.hemesh.HE_Mesh.getEdgeWithKey(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedgeStar(), wblut.hemesh.HE_Selection.getNumberOfVertices(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Halfedge.getPrevInVertex(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_VertexHalfedgeOutCirculator.hasNext(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_VertexHalfedgeOutCirculator.next(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HET_MeshOp.splitEdge(), wblut.hemesh.HET_MeshOp.splitFace(), wblut.hemesh.HE_Machine.tracker, wblut.hemesh.HE_Selection.union(), wblut.hemesh.HE_Selection.vItr(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), wblut.hemesh.HE_Vertex.zd(), and wblut.math.WB_ScalarParameter.ZERO.
HEM_Crocodile wblut.hemesh.HEM_Crocodile.setChamfer (final double c)
Parameters
c
Returns
References wblut.math.WB_ScalarParameter.ZERO.
HEM_Crocodile wblut.hemesh.HEM_Crocodile.setChamfer (final WB_ScalarParameter c)
HEM_Crocodile wblut.hemesh.HEM_Crocodile.setDistance (final double d)
Parameters
d
Returns
References wblut.math.WB_ScalarParameter.ZERO.
HEM_Crocodile wblut.hemesh.HEM_Crocodile.setDistance (final WB_ScalarParameter d)
Member Data Documentation
WB_ScalarParameter wblut.hemesh.HEM_Crocodile.chamfer private
WB_ScalarParameter wblut.hemesh.HEM_Crocodile.distance private
WB_GeometryFactory wblut.hemesh.HEM_Crocodile.gf = new WB_GeometryFactory() static private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Crocodile.java