HE_Mesh: wblut.geom.WB_ExpressionCurve Class Reference
wblut.geom.WB_ExpressionCurve Class Reference
Public Member Functions
WB_ExpressionCurve (final String equationX, final String equationY, final String equationZ, final String var)
WB_ExpressionCurve (final String equationX, final String equationY, final String var)
WB_ExpressionCurve (final String equationX, final String equationY, final String equationZ, final String var, final double minU, final double maxU)
WB_ExpressionCurve (final String equationX, final String equationY, final String var, final double minU, final double maxU)
WB_Point curvePoint (final double u)
double getLowerU ()
double getUpperU ()
WB_Vector curveDirection (double u)
WB_Vector curveDerivative (final double u)
Public Member Functions inherited from wblut.geom.WB_Curve
WB_Point curvePoint (double u)
WB_Vector curveDerivative (double u)
Private Member Functions
WB_Point evaluate2D (final double value)
WB_Point evaluate3D (final double value)
Constructor & Destructor Documentation
wblut.geom.WB_ExpressionCurve.WB_ExpressionCurve (final String equationX, final String equationY, final String equationZ, final String var)
Parameters
equationX
equationY
equationZ
var
wblut.geom.WB_ExpressionCurve.WB_ExpressionCurve (final String equationX, final String equationY, final String var)
Parameters
equationX
equationY
var
wblut.geom.WB_ExpressionCurve.WB_ExpressionCurve (final String equationX, final String equationY, final String equationZ, final String var, final double minU, final double maxU)
Parameters
equationX
equationY
equationZ
var
minU
maxU
wblut.geom.WB_ExpressionCurve.WB_ExpressionCurve (final String equationX, final String equationY, final String var, final double minU, final double maxU)
Parameters
equationX
equationY
var
minU
maxU
Member Function Documentation
WB_Vector wblut.geom.WB_ExpressionCurve.curveDerivative (final double u)
References wblut.geom.WB_ExpressionCurve.curvePoint(), and wblut.geom.WB_Vector.div().
WB_Vector wblut.geom.WB_ExpressionCurve.curveDirection (double u)
Parameters
u
Returns
Implements wblut.geom.WB_Curve.
References wblut.geom.WB_ExpressionCurve.curvePoint(), and wblut.geom.WB_Vector.normalizeSelf().
WB_Point wblut.geom.WB_ExpressionCurve.curvePoint (final double u)
References wblut.geom.WB_ExpressionCurve.evaluate2D(), and wblut.geom.WB_ExpressionCurve.evaluate3D().
WB_Point wblut.geom.WB_ExpressionCurve.evaluate2D (final double value) private
Parameters
value
Returns
WB_Point wblut.geom.WB_ExpressionCurve.evaluate3D (final double value) private
Parameters
value
Returns
double wblut.geom.WB_ExpressionCurve.getLowerU ()
Returns
Implements wblut.geom.WB_Curve.
double wblut.geom.WB_ExpressionCurve.getUpperU ()
Returns
Implements wblut.geom.WB_Curve.
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_ExpressionCurve.java