HE_Mesh: wblut.processing.WB_Render2D Class Reference
wblut.processing.WB_Render2D Class Reference
Public Member Functions
WB_Render2D (final PApplet home)
WB_Render2D (final PGraphics home)
void vertex2D (final WB_Coord p)
void drawPoint2D (final WB_Coord p)
void drawPoint2D (final WB_Coord p, final double r)
void drawPoint2D (final Collection<?extends WB_Coord > points)
void drawPoint2D (final WB_Coord[] points)
void drawPoint2D (final Collection<?extends WB_Coord > points, final double r)
void drawPoint2D (final WB_Coord[] points, final double r)
void drawVector2D (final WB_Coord p, final WB_Coord v, final double r)
void drawLine2D (final WB_Line L, final double d)
void drawRay2D (final WB_Ray R, final double d)
void drawSegment2D (final WB_Coord p, final WB_Coord q)
void drawPolyLine2D (final WB_PolyLine P)
void drawRing2D (final WB_Ring P)
void drawPolygon2D (final WB_Polygon P)
void drawPolygon2D (final WB_Polygon[] P)
void drawPolygon2D (final Collection<?extends WB_Polygon > P)
void drawPolygonEdges2D (final WB_Polygon P)
void drawPolygonEdges2D (final WB_Polygon[] P)
void drawPolygonEdges2D (final Collection<?extends WB_Polygon > P)
void drawCircle2D (final WB_Circle C)
void drawTriangle2D (final WB_Triangle T)
void drawTriangle2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
void drawTriangle2D (final int[] tri, final List<?extends WB_Coord > points)
void drawTriangle2D (final int[] tri, final WB_Coord[] points)
void drawTriangulation2D (final WB_Triangulation2D tri, final List<?extends WB_Coord > points)
void drawTriangulation2D (final WB_Triangulation2D tri, final WB_CoordCollection points)
void drawTriangulationEdges2D (final WB_Triangulation2D tri, final List<?extends WB_Coord > points)
void drawTriangulation2D (final WB_Triangulation2D tri, final WB_Coord[] points)
void drawTriangulationEdges2D (final WB_Triangulation2D tri, final WB_Coord[] points)
void drawTriangle2D (final Collection<?extends WB_Triangle > triangles)
void drawTriangle2D (final WB_Triangle[] triangles)
void drawTriangle2DEdges (final Collection<?extends WB_Triangle > triangles)
void drawTriangle2DEdges (final WB_Triangle triangle)
void drawTriangle2DEdges (final WB_Triangle[] triangles)
void drawSegment2D (final Collection<?extends WB_Segment > segments)
void drawSegment2D (final WB_Segment segment)
void drawSegment2D (final WB_Segment[] segments)
void drawSegment2D (final int[] segs, final List<?extends WB_Coord > coords)
void translate2D (final WB_Coord p)
void drawAABB2D (final WB_AABB2D AABB)
void drawAABBNode2D (final WB_AABBNode2D node)
void drawAABBLeafNodes2D (final WB_AABBTree2D tree)
void drawAABBTree2D (final WB_AABBTree2D tree)
void drawAABBTree2D (final WB_AABBTree2D tree, final int level)
void drawAABBNode2D (final WB_IndexedAABBNode2D node)
void drawAABBLeafNodes2D (final WB_IndexedAABBTree2D tree)
void drawAABBTree2D (final WB_IndexedAABBTree2D tree)
void drawAABBTree2D (final WB_IndexedAABBTree2D tree, final int level)
void drawTriangulation2D (final WB_AlphaTriangulation2D tri)
void drawTriangulation2D (final WB_AlphaTriangulation2D tri, final double alpha)
void drawTriangulationEdges2D (final WB_AlphaTriangulation2D tri)
void drawTriangulation2D (final WB_Triangulation2DWithPoints tri)
void drawTriangulationEdges2D (final WB_Triangulation2DWithPoints tri)
void drawLineMapped (final WB_Line L, final double d, final WB_Map2D map)
void drawPointMapped (final Collection<?extends WB_Coord > points, final double r, final WB_Map2D map)
void drawPointMapped (final Collection<?extends WB_Coord > points, final WB_Map2D map)
void drawPointMapped (final WB_Coord p, final double r, final WB_Map2D map)
void drawPointMapped (final WB_Coord p, final WB_Map2D map)
void drawPointMapped (final WB_Coord[] points, final double r, final WB_Map2D map)
void drawPointMapped (final WB_Coord[] points, final WB_Map2D map)
void drawPolygonEdgesMapped (final WB_Polygon P, final WB_Map2D map)
void drawPolygonMapped (final WB_Polygon P, final WB_Map2D map)
void drawPolyLineMapped (final WB_PolyLine P, final WB_Map2D map)
void drawRayMapped (final WB_Ray R, final double d, final WB_Map2D map)
void drawRingMapped (final WB_Ring P, final WB_Map2D map)
void drawSegmentMapped (final Collection<?extends WB_Segment > segments, final WB_Map2D map)
void drawSegmentMapped (final WB_Coord p, final WB_Coord q, final WB_Map2D map)
void drawSegmentMapped (final WB_Segment segment, final WB_Map2D map)
void drawSegmentMapped (final WB_Segment[] segments, final WB_Map2D map)
void drawTriangleEdgesMapped (final Collection<?extends WB_Triangle > triangles, final WB_Map2D map)
void drawTriangleEdgesMapped (final WB_Triangle triangle, final WB_Map2D map)
void drawTriangleEdgesMapped (final WB_Triangle[] triangles, final WB_Map2D map)
void drawTriangleMapped (final Collection<?extends WB_Triangle > triangles, final WB_Map2D map)
void drawTriangleMapped (final int[] tri, final List<?extends WB_Coord > points, final WB_Map2D map)
void drawTriangleMapped (final int[] tri, final WB_Coord[] points, final WB_Map2D map)
void drawTriangleMapped (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Map2D map)
void drawTriangleMapped (final WB_Triangle T, final WB_Map2D map)
void drawTriangleMapped (final WB_Triangle[] triangles, final WB_Map2D map)
void drawTriangulationMapped (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map2D map)
void drawTriangulationMapped (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map2D map)
void drawVectorMapped (final WB_Coord p, final WB_Coord v, final double r, final WB_Map2D map)
void vertexMapped (final WB_Coord p, final WB_Map2D map)
void drawGizmo (final double d)
void drawTriangle2D (final WB_TriangleGenerator triangleGenerator)
Public Member Functions inherited from wblut.processing.WB_Processing
WB_Processing (final PApplet home)
WB_Processing (final PGraphics home)
Protected Member Functions
WB_Render2D ()
Protected Member Functions inherited from wblut.processing.WB_Processing
WB_Processing ()
Private Member Functions
void line2D (final WB_Coord p, final WB_Coord q)
void drawAABBNode2D (final WB_AABBNode2D node, final int level)
void drawAABBLeafNode2D (final WB_AABBNode2D node)
void drawAABBNode2D (final WB_IndexedAABBNode2D node, final int level)
void drawAABBLeafNode2D (final WB_IndexedAABBNode2D node)
Additional Inherited Members
Static Public Member Functions inherited from wblut.processing.WB_Processing
static int color (final int r, final int g, final int b)
Protected Attributes inherited from wblut.processing.WB_Processing
PGraphics home
Constructor & Destructor Documentation
wblut.processing.WB_Render2D.WB_Render2D () protected
wblut.processing.WB_Render2D.WB_Render2D (final PApplet home)
Parameters
home
wblut.processing.WB_Render2D.WB_Render2D (final PGraphics home)
Parameters
home
References wblut.processing.WB_Processing.home.
Member Function Documentation
void wblut.processing.WB_Render2D.drawAABB2D (final WB_AABB2D AABB)
References wblut.geom.WB_AABB2D.getHeight(), wblut.geom.WB_AABB2D.getMinX(), wblut.geom.WB_AABB2D.getMinY(), wblut.geom.WB_AABB2D.getWidth(), and wblut.processing.WB_Processing.home.
void wblut.processing.WB_Render2D.drawAABBLeafNode2D (final WB_AABBNode2D node) private
Draw leaf node.
Parameters
node the node
References wblut.processing.WB_Render2D.drawAABB2D(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getAABB(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getChildA(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getChildB(), and wblut.geom.WB_AABBTree2D.WB_AABBNode2D.isLeaf.
void wblut.processing.WB_Render2D.drawAABBLeafNode2D (final WB_IndexedAABBNode2D node) private
Draw leaf node.
Parameters
node the node
References wblut.processing.WB_Render2D.drawAABB2D(), wblut.processing.WB_Render2D.drawAABBLeafNode2D(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getAABB(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getChildA(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getChildB(), and wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.isLeaf.
void wblut.processing.WB_Render2D.drawAABBLeafNodes2D (final WB_AABBTree2D tree)
Draw leafs.
Parameters
tree the tree
References wblut.processing.WB_Render2D.drawAABBLeafNode2D(), and wblut.geom.WB_AABBTree2D.getRoot().
void wblut.processing.WB_Render2D.drawAABBLeafNodes2D (final WB_IndexedAABBTree2D tree)
Draw leafs.
Parameters
tree the tree
References wblut.processing.WB_Render2D.drawAABBLeafNode2D(), and wblut.geom.WB_IndexedAABBTree2D.getRoot().
void wblut.processing.WB_Render2D.drawAABBNode2D (final WB_AABBNode2D node)
/** Draw WB_AABBTree node.
Parameters
node the node
References wblut.processing.WB_Render2D.drawAABB2D(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getAABB(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getChildA(), and wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getChildB().
void wblut.processing.WB_Render2D.drawAABBNode2D (final WB_AABBNode2D node, final int level) private
Draw WB_AABBTree node.
Parameters
node the node
level the level
References wblut.processing.WB_Render2D.drawAABB2D(), wblut.processing.WB_Render2D.drawAABBNode2D(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getAABB(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getChildA(), wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getChildB(), and wblut.geom.WB_AABBTree2D.WB_AABBNode2D.getLevel().
void wblut.processing.WB_Render2D.drawAABBNode2D (final WB_IndexedAABBNode2D node)
Draw WB_AABBTree node.
Parameters
node the node
References wblut.processing.WB_Render2D.drawAABB2D(), wblut.processing.WB_Render2D.drawAABBNode2D(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getAABB(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getChildA(), and wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getChildB().
void wblut.processing.WB_Render2D.drawAABBNode2D (final WB_IndexedAABBNode2D node, final int level) private
Draw WB_AABBTree node.
Parameters
node the node
level the level
References wblut.processing.WB_Render2D.drawAABB2D(), wblut.processing.WB_Render2D.drawAABBNode2D(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getAABB(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getChildA(), wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getChildB(), and wblut.geom.WB_IndexedAABBTree2D.WB_IndexedAABBNode2D.getLevel().
void wblut.processing.WB_Render2D.drawAABBTree2D (final WB_AABBTree2D tree)
References wblut.processing.WB_Render2D.drawAABBNode2D(), and wblut.geom.WB_AABBTree2D.getRoot().
void wblut.processing.WB_Render2D.drawAABBTree2D (final WB_AABBTree2D tree, final int level)
References wblut.processing.WB_Render2D.drawAABBNode2D(), and wblut.geom.WB_AABBTree2D.getRoot().
void wblut.processing.WB_Render2D.drawAABBTree2D (final WB_IndexedAABBTree2D tree)
References wblut.processing.WB_Render2D.drawAABBNode2D(), and wblut.geom.WB_IndexedAABBTree2D.getRoot().
void wblut.processing.WB_Render2D.drawAABBTree2D (final WB_IndexedAABBTree2D tree, final int level)
References wblut.processing.WB_Render2D.drawAABBNode2D(), and wblut.geom.WB_IndexedAABBTree2D.getRoot().
void wblut.processing.WB_Render2D.drawCircle2D (final WB_Circle C)
Parameters
C
References wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Circle.getRadius(), wblut.processing.WB_Processing.home, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.processing.WB_Render2D.drawGizmo (final double d)
References wblut.processing.WB_Processing.home.
void wblut.processing.WB_Render2D.drawLine2D (final WB_Line L, final double d)
Parameters
L
d
References wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.processing.WB_Processing.home, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.processing.WB_Render2D.drawLineMapped (final WB_Line L, final double d, final WB_Map2D map)
Parameters
L
d
map
References wblut.geom.WB_Point.addMul(), wblut.processing.WB_Render2D.drawSegmentMapped(), wblut.geom.WB_Line.getDirection(), and wblut.geom.WB_Line.getOrigin().
void wblut.processing.WB_Render2D.drawPoint2D (final WB_Coord p)
Parameters
p
References wblut.processing.WB_Processing.home, wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
void wblut.processing.WB_Render2D.drawPoint2D (final WB_Coord p, final double r)
Parameters
p
r
References wblut.processing.WB_Processing.home, wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
void wblut.processing.WB_Render2D.drawPoint2D (final Collection<?extends WB_Coord > points)
Parameters
points
References wblut.processing.WB_Render2D.drawPoint2D().
void wblut.processing.WB_Render2D.drawPoint2D (final WB_Coord[] points)
Parameters
points
References wblut.processing.WB_Render2D.drawPoint2D().
void wblut.processing.WB_Render2D.drawPoint2D (final Collection<?extends WB_Coord > points, final double r)
Parameters
points
r
References wblut.processing.WB_Render2D.drawPoint2D().
void wblut.processing.WB_Render2D.drawPoint2D (final WB_Coord[] points, final double r)
Parameters
points
r
References wblut.processing.WB_Render2D.drawPoint2D().
void wblut.processing.WB_Render2D.drawPointMapped (final Collection<?extends WB_Coord > points, final double r, final WB_Map2D map)
Parameters
points
r
map
void wblut.processing.WB_Render2D.drawPointMapped (final Collection<?extends WB_Coord > points, final WB_Map2D map)
Parameters
points
map
References wblut.processing.WB_Render2D.drawPointMapped().
void wblut.processing.WB_Render2D.drawPointMapped (final WB_Coord p, final double r, final WB_Map2D map)
Parameters
p
r
map
References wblut.processing.WB_Render2D.drawPoint2D(), and wblut.geom.WB_Map.mapPoint3D().
void wblut.processing.WB_Render2D.drawPointMapped (final WB_Coord p, final WB_Map2D map)
Parameters
p
map
References wblut.processing.WB_Render2D.drawPoint2D(), and wblut.geom.WB_Map.mapPoint3D().
void wblut.processing.WB_Render2D.drawPointMapped (final WB_Coord[] points, final double r, final WB_Map2D map)
Parameters
points
r
map
References wblut.processing.WB_Render2D.drawPointMapped().
void wblut.processing.WB_Render2D.drawPointMapped (final WB_Coord[] points, final WB_Map2D map)
Parameters
points
map
References wblut.processing.WB_Render2D.drawPointMapped().
void wblut.processing.WB_Render2D.drawPolygon2D (final WB_Polygon P)
Parameters
P
References wblut.processing.WB_Render2D.drawTriangle2D(), wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_Polygon.getTriangles().
void wblut.processing.WB_Render2D.drawPolygon2D (final WB_Polygon[] P)
References wblut.processing.WB_Render2D.drawPolygon2D().
void wblut.processing.WB_Render2D.drawPolygon2D (final Collection<?extends WB_Polygon > P)
References wblut.processing.WB_Render2D.drawPolygon2D().
void wblut.processing.WB_Render2D.drawPolygonEdges2D (final WB_Polygon P)
Parameters
P
References wblut.geom.WB_Polygon.getNumberOfContours(), wblut.geom.WB_Polygon.getNumberOfPointsPerContour(), wblut.geom.WB_Polygon.getPoint(), wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertex2D().
void wblut.processing.WB_Render2D.drawPolygonEdges2D (final WB_Polygon[] P)
References wblut.processing.WB_Render2D.drawPolygon2D().
void wblut.processing.WB_Render2D.drawPolygonEdges2D (final Collection<?extends WB_Polygon > P)
References wblut.processing.WB_Render2D.drawPolygon2D().
void wblut.processing.WB_Render2D.drawPolygonEdgesMapped (final WB_Polygon P, final WB_Map2D map)
Parameters
P
map
References wblut.geom.WB_Polygon.getNumberOfContours(), wblut.geom.WB_Polygon.getNumberOfPointsPerContour(), wblut.geom.WB_Polygon.getPoint(), wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertexMapped().
void wblut.processing.WB_Render2D.drawPolygonMapped (final WB_Polygon P, final WB_Map2D map)
Parameters
P
map
References wblut.processing.WB_Render2D.drawTriangleMapped(), wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_Polygon.getTriangles().
void wblut.processing.WB_Render2D.drawPolyLine2D (final WB_PolyLine P)
Parameters
P
References wblut.geom.WB_PolyLine.getNumberOfPoints(), wblut.geom.WB_PolyLine.getPoint(), wblut.processing.WB_Processing.home, wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
void wblut.processing.WB_Render2D.drawPolyLineMapped (final WB_PolyLine P, final WB_Map2D map)
Parameters
P
map
References wblut.processing.WB_Render2D.drawSegmentMapped(), wblut.geom.WB_PolyLine.getNumberOfPoints(), and wblut.geom.WB_PolyLine.getPoint().
void wblut.processing.WB_Render2D.drawRay2D (final WB_Ray R, final double d)
Parameters
R
d
References wblut.geom.WB_Ray.getDirection(), wblut.geom.WB_Ray.getOrigin(), wblut.processing.WB_Processing.home, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.processing.WB_Render2D.drawRayMapped (final WB_Ray R, final double d, final WB_Map2D map)
Parameters
R
d
map
References wblut.geom.WB_Point.addMul(), wblut.processing.WB_Render2D.drawSegmentMapped(), wblut.geom.WB_Ray.getDirection(), and wblut.geom.WB_Ray.getOrigin().
void wblut.processing.WB_Render2D.drawRing2D (final WB_Ring P)
Parameters
P
References wblut.geom.WB_Ring.getNumberOfPoints(), wblut.geom.WB_Ring.getPoint(), wblut.processing.WB_Processing.home, wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
void wblut.processing.WB_Render2D.drawRingMapped (final WB_Ring P, final WB_Map2D map)
Parameters
P
map
References wblut.processing.WB_Render2D.drawSegmentMapped(), wblut.geom.WB_Ring.getNumberOfPoints(), and wblut.geom.WB_Ring.getPoint().
void wblut.processing.WB_Render2D.drawSegment2D (final WB_Coord p, final WB_Coord q)
Parameters
p
q
References wblut.processing.WB_Processing.home, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.processing.WB_Render2D.drawSegment2D (final Collection<?extends WB_Segment > segments)
Parameters
segments
References wblut.processing.WB_Render2D.drawSegment2D().
void wblut.processing.WB_Render2D.drawSegment2D (final WB_Segment segment)
Parameters
segment
References wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Line.getOrigin(), and wblut.processing.WB_Render2D.line2D().
void wblut.processing.WB_Render2D.drawSegment2D (final WB_Segment[] segments)
Parameters
segments
References wblut.processing.WB_Render2D.drawSegment2D().
void wblut.processing.WB_Render2D.drawSegment2D (final int[] segs, final List<?extends WB_Coord > coords)
References wblut.processing.WB_Render2D.line2D().
void wblut.processing.WB_Render2D.drawSegmentMapped (final Collection<?extends WB_Segment > segments, final WB_Map2D map)
Parameters
segments
map
void wblut.processing.WB_Render2D.drawSegmentMapped (final WB_Coord p, final WB_Coord q, final WB_Map2D map)
Parameters
p
q
map
References wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertexMapped().
void wblut.processing.WB_Render2D.drawSegmentMapped (final WB_Segment segment, final WB_Map2D map)
Parameters
segment
map
References wblut.processing.WB_Render2D.drawSegmentMapped(), wblut.geom.WB_Segment.getEndpoint(), and wblut.geom.WB_Line.getOrigin().
void wblut.processing.WB_Render2D.drawSegmentMapped (final WB_Segment[] segments, final WB_Map2D map)
Parameters
segments
map
References wblut.processing.WB_Render2D.drawSegmentMapped().
void wblut.processing.WB_Render2D.drawTriangle2D (final WB_Triangle T)
Parameters
T
References wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertex2D().
void wblut.processing.WB_Render2D.drawTriangle2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
Parameters
p1
p2
p3
References wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertex2D().
void wblut.processing.WB_Render2D.drawTriangle2D (final int[] tri, final List<?extends WB_Coord > points)
Parameters
tri
points
References wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertex2D().
void wblut.processing.WB_Render2D.drawTriangle2D (final int[] tri, final WB_Coord[] points)
Parameters
tri
points
References wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertex2D().
void wblut.processing.WB_Render2D.drawTriangle2D (final Collection<?extends WB_Triangle > triangles)
Parameters
triangles
References wblut.processing.WB_Render2D.drawTriangle2D().
void wblut.processing.WB_Render2D.drawTriangle2D (final WB_Triangle[] triangles)
Parameters
triangles
References wblut.processing.WB_Render2D.drawTriangle2D().
void wblut.processing.WB_Render2D.drawTriangle2D (final WB_TriangleGenerator triangleGenerator)
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_TriangleGenerator.getPoints(), wblut.geom.WB_TriangleGenerator.getTriangles(), wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertex2D().
void wblut.processing.WB_Render2D.drawTriangle2DEdges (final Collection<?extends WB_Triangle > triangles)
Parameters
triangles
void wblut.processing.WB_Render2D.drawTriangle2DEdges (final WB_Triangle triangle)
Parameters
triangle
References wblut.processing.WB_Render2D.line2D().
void wblut.processing.WB_Render2D.drawTriangle2DEdges (final WB_Triangle[] triangles)
Parameters
triangles
References wblut.processing.WB_Render2D.drawTriangle2DEdges().
void wblut.processing.WB_Render2D.drawTriangleEdgesMapped (final Collection<?extends WB_Triangle > triangles, final WB_Map2D map)
Parameters
triangles
map
void wblut.processing.WB_Render2D.drawTriangleEdgesMapped (final WB_Triangle triangle, final WB_Map2D map)
Parameters
triangle
map
References wblut.processing.WB_Render2D.drawSegmentMapped().
void wblut.processing.WB_Render2D.drawTriangleEdgesMapped (final WB_Triangle[] triangles, final WB_Map2D map)
Parameters
triangles
map
References wblut.processing.WB_Render2D.drawTriangleEdgesMapped().
void wblut.processing.WB_Render2D.drawTriangleMapped (final Collection<?extends WB_Triangle > triangles, final WB_Map2D map)
Parameters
triangles
map
void wblut.processing.WB_Render2D.drawTriangleMapped (final int[] tri, final List<?extends WB_Coord > points, final WB_Map2D map)
Parameters
tri
points
map
References wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertexMapped().
void wblut.processing.WB_Render2D.drawTriangleMapped (final int[] tri, final WB_Coord[] points, final WB_Map2D map)
Parameters
tri
points
map
References wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertexMapped().
void wblut.processing.WB_Render2D.drawTriangleMapped (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Map2D map)
Parameters
p1
p2
p3
map
References wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertexMapped().
void wblut.processing.WB_Render2D.drawTriangleMapped (final WB_Triangle T, final WB_Map2D map)
Parameters
T
map
References wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertexMapped().
void wblut.processing.WB_Render2D.drawTriangleMapped (final WB_Triangle[] triangles, final WB_Map2D map)
Parameters
triangles
map
References wblut.processing.WB_Render2D.drawTriangleMapped().
void wblut.processing.WB_Render2D.drawTriangulation2D (final WB_Triangulation2D tri, final List<?extends WB_Coord > points)
Parameters
tri
points
References wblut.geom.WB_Triangulation2D.getTriangles(), wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertex2D().
void wblut.processing.WB_Render2D.drawTriangulation2D (final WB_Triangulation2D tri, final WB_CoordCollection points)
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_Triangulation2D.getTriangles(), wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertex2D().
void wblut.processing.WB_Render2D.drawTriangulation2D (final WB_Triangulation2D tri, final WB_Coord[] points)
Parameters
tri
points
References wblut.geom.WB_Triangulation2D.getTriangles(), wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertex2D().
void wblut.processing.WB_Render2D.drawTriangulation2D (final WB_AlphaTriangulation2D tri)
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_AlphaTriangulation2D.getPoints(), wblut.geom.WB_AlphaTriangulation2D.getTriangles(), wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertex2D().
void wblut.processing.WB_Render2D.drawTriangulation2D (final WB_AlphaTriangulation2D tri, final double alpha)
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_AlphaTriangulation2D.getAlpha(), wblut.geom.WB_AlphaTriangulation2D.getPoints(), wblut.geom.WB_AlphaTriangulation2D.getTriangles(), wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertex2D().
void wblut.processing.WB_Render2D.drawTriangulation2D (final WB_Triangulation2DWithPoints tri)
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_Triangulation2DWithPoints.getPoints(), wblut.geom.WB_Triangulation2D.getTriangles(), wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertex2D().
void wblut.processing.WB_Render2D.drawTriangulationEdges2D (final WB_Triangulation2D tri, final List<?extends WB_Coord > points)
Parameters
tri
points
References wblut.processing.WB_Render2D.drawSegment2D(), and wblut.geom.WB_Triangulation2D.getEdges().
void wblut.processing.WB_Render2D.drawTriangulationEdges2D (final WB_Triangulation2D tri, final WB_Coord[] points)
Parameters
tri
points
References wblut.processing.WB_Render2D.drawSegment2D(), and wblut.geom.WB_Triangulation2D.getEdges().
void wblut.processing.WB_Render2D.drawTriangulationEdges2D (final WB_AlphaTriangulation2D tri)
References wblut.processing.WB_Render2D.drawSegment2D(), wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_AlphaTriangulation2D.getEdges(), and wblut.geom.WB_AlphaTriangulation2D.getPoints().
void wblut.processing.WB_Render2D.drawTriangulationEdges2D (final WB_Triangulation2DWithPoints tri)
References wblut.processing.WB_Render2D.drawSegment2D(), wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_Triangulation2D.getEdges(), and wblut.geom.WB_Triangulation2DWithPoints.getPoints().
void wblut.processing.WB_Render2D.drawTriangulationMapped (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map2D map)
Parameters
tri
points
map
References wblut.geom.WB_Triangulation2D.getTriangles(), wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertexMapped().
void wblut.processing.WB_Render2D.drawTriangulationMapped (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map2D map)
Parameters
tri
points
map
References wblut.geom.WB_Triangulation2D.getTriangles(), wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertexMapped().
void wblut.processing.WB_Render2D.drawVector2D (final WB_Coord p, final WB_Coord v, final double r)
Parameters
p
v
r
References wblut.processing.WB_Processing.home, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.yf().
void wblut.processing.WB_Render2D.drawVectorMapped (final WB_Coord p, final WB_Coord v, final double r, final WB_Map2D map)
Parameters
p
v
r
map
References wblut.geom.WB_Point.addMul(), and wblut.processing.WB_Render2D.drawSegmentMapped().
void wblut.processing.WB_Render2D.line2D (final WB_Coord p, final WB_Coord q) private
Parameters
p
q
References wblut.processing.WB_Processing.home, and wblut.processing.WB_Render2D.vertex2D().
void wblut.processing.WB_Render2D.translate2D (final WB_Coord p)
Parameters
p
References wblut.processing.WB_Processing.home, wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
void wblut.processing.WB_Render2D.vertex2D (final WB_Coord p)
Parameters
p
References wblut.processing.WB_Processing.home, wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
void wblut.processing.WB_Render2D.vertexMapped (final WB_Coord p, final WB_Map2D map)
Parameters
p
map
References wblut.geom.WB_Map.mapPoint3D(), and wblut.processing.WB_Render2D.vertex2D().
The documentation for this class was generated from the following file:
src/processing/wblut/processing/WB_Render2D.java