HE_Mesh: wblut.geom.WB_Subdivision Class Reference
wblut.geom.WB_Subdivision Class Reference
Classes
class H01
class H02
class H03
class H04
class H05
class H06
class H07
class H08
class H09
class H10
class H11
class O01
class O02
class O03
class O04
class O05
class O06
class O07
class O08
class O09
class O10
class O11
class O12
class O13
class O14
class P01
class P02
class P03
class P04
class P05
class P06
class P07
class P08
class P09
class P10
class P11
class Q01
class Q02
class Q03
class Q04
class Q05
class Q06
class Q07
class Q08
class Q09
class Q10
class Q11
class Q12
class Q13
class Q14
class Q15
class Q16
class Q17
class T00
class T01
class T02
class T03
class T04
class T05
class T06
class T07
class T08
class T09
class T10
class T11
class T12
class T13
class T14
interface WB_HexagonSubdivision
interface WB_OctagonSubdivision
interface WB_PentagonSubdivision
interface WB_QuadSubdivision
class WB_SubdivisionResult
interface WB_TriangleSubdivision
Static Public Member Functions
static WB_SubdivisionResult subdivide (final WB_Triangle triangle, final WB_TriangleSubdivision rule)
static WB_SubdivisionResult subdivide (final WB_Quad quad, final WB_QuadSubdivision rule)
static WB_SubdivisionResult subdivide (final WB_Pentagon pentagon, final WB_PentagonSubdivision rule)
static WB_SubdivisionResult subdivide (final WB_Hexagon hexagon, final WB_HexagonSubdivision rule)
static WB_SubdivisionResult subdivide (final WB_Octagon octagon, final WB_OctagonSubdivision rule)
Static Public Attributes
static WB_TriangleSubdivision[] TSubs
static WB_QuadSubdivision[] QSubs
static WB_PentagonSubdivision[] PSubs
static WB_HexagonSubdivision[] HSubs
static WB_OctagonSubdivision[] OSubs
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Detailed Description
Author
FVH
Member Function Documentation
static WB_SubdivisionResult wblut.geom.WB_Subdivision.subdivide (final WB_Triangle triangle, final WB_TriangleSubdivision rule) static
References wblut.geom.WB_Subdivision.WB_TriangleSubdivision.apply().
static WB_SubdivisionResult wblut.geom.WB_Subdivision.subdivide (final WB_Quad quad, final WB_QuadSubdivision rule) static
References wblut.geom.WB_Subdivision.WB_QuadSubdivision.apply().
static WB_SubdivisionResult wblut.geom.WB_Subdivision.subdivide (final WB_Pentagon pentagon, final WB_PentagonSubdivision rule) static
References wblut.geom.WB_Subdivision.WB_PentagonSubdivision.apply().
static WB_SubdivisionResult wblut.geom.WB_Subdivision.subdivide (final WB_Hexagon hexagon, final WB_HexagonSubdivision rule) static
References wblut.geom.WB_Subdivision.WB_HexagonSubdivision.apply().
static WB_SubdivisionResult wblut.geom.WB_Subdivision.subdivide (final WB_Octagon octagon, final WB_OctagonSubdivision rule) static
References wblut.geom.WB_Subdivision.WB_OctagonSubdivision.apply().
Member Data Documentation
WB_GeometryFactory wblut.geom.WB_Subdivision.gf = new WB_GeometryFactory() static private
WB_HexagonSubdivision [] wblut.geom.WB_Subdivision.HSubs static
Initial value:
= new WB_HexagonSubdivision[] { new H01(), new H02(), new H03(),
            new H04(), new H05(), new H06(), new H07(), new H08(), new H09(), new H10(), new H11() }
WB_OctagonSubdivision [] wblut.geom.WB_Subdivision.OSubs static
Initial value:
= new WB_OctagonSubdivision[] { new O01(), new O02(), new O03(),
            new O04(), new O05(), new O06(), new O07(), new O08(), new O09(), new O10(), new O11(), new O12(),
            new O13(), new O14() }
WB_PentagonSubdivision [] wblut.geom.WB_Subdivision.PSubs static
Initial value:
= new WB_PentagonSubdivision[] { new P01(), new P02(), new P03(),
            new P04(), new P05(), new P06(), new P07(), new P08(), new P09(), new P10(), new P11() }
WB_QuadSubdivision [] wblut.geom.WB_Subdivision.QSubs static
Initial value:
= new WB_QuadSubdivision[] { new Q01(), new Q02(), new Q03(), new Q04(),
            new Q05(), new Q06(), new Q07(), new Q08(), new Q09(), new Q10(), new Q11(), new Q12(), new Q13(),
            new Q14(), new Q15(), new Q16(), new Q17() }
WB_TriangleSubdivision [] wblut.geom.WB_Subdivision.TSubs static
Initial value:
= new WB_TriangleSubdivision[] { new T01(), new T02(), new T03(),
            new T04(), new T05(), new T06(), new T07(), new T08(), new T09(), new T10(), new T11(), new T12(),
            new T13(), new T14() }
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Subdivision.java