HE_Mesh: wblut.geom.WB_Segment Class Reference
wblut.geom.WB_Segment Class Reference
Public Member Functions
WB_Segment ()
WB_Segment (final WB_Coord o, final WB_Coord d, final double l)
WB_Segment (final WB_Coord p1, final WB_Coord p2)
WB_Segment (final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
WB_Point getParametricPoint (final double t)
void getParametricPointInto (final double t, final WB_MutableCoord result)
WB_Coord getEndpoint ()
WB_Point getCenter ()
double getLength ()
WB_Segment negate ()
void reverse ()
WB_Segment apply (final WB_Transform T)
WB_Point curvePoint (final double u)
double getLowerU ()
double getUpperU ()
WB_Vector curveDirection (final double u)
WB_Vector curveDerivative (final double u)
boolean equals (final Object o)
int hashCode ()
Public Member Functions inherited from wblut.geom.WB_Line
WB_Line ()
WB_Line (final WB_Coord o, final WB_Coord d)
WB_Line (final double ox, final double oy, final double oz, final double dx, final double dy, final double dz)
WB_Line (final double ox, final double oy, final double dx, final double dy)
String toString ()
void setFromPoints (final WB_Coord p1, final WB_Coord p2)
double getT (final WB_Coord p)
WB_Point curvePoint (final double u)
WB_Vector curveDirection (final double u)
WB_Vector curveDerivative (final double u)
double getLowerU ()
double getUpperU ()
double a ()
double b ()
double c ()
WB_Coord getDirection ()
WB_Vector getNormal ()
WB_Coord getOrigin ()
WB_Point getParametricPoint (final double t)
void getParametricPointInto (final double t, final WB_MutableCoord result)
WB_Point getPoint (final double t)
void getPointInto (final double t, final WB_MutableCoord result)
boolean equals (final Object o)
int hashCode ()
Public Member Functions inherited from wblut.geom.WB_Curve
WB_Point curvePoint (double u)
WB_Vector curveDirection (double u)
WB_Vector curveDerivative (double u)
Static Public Member Functions
static WB_Segment X ()
static WB_Segment Y ()
static WB_Segment Z ()
static List< WB_Segment > negate (final List< WB_Segment > segs)
Static Public Member Functions inherited from wblut.geom.WB_Line
static WB_Line X ()
static WB_Line Y ()
static WB_Line Z ()
Protected Attributes
double length
WB_Point endpoint
Protected Attributes inherited from wblut.geom.WB_Line
WB_Point origin
WB_Vector direction
Private Attributes
WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
Additional Inherited Members
Protected Member Functions inherited from wblut.geom.WB_Line
void set (final WB_Coord o, final WB_Coord d)
Constructor & Destructor Documentation
wblut.geom.WB_Segment.WB_Segment ()
wblut.geom.WB_Segment.WB_Segment (final WB_Coord o, final WB_Coord d, final double l)
Parameters
o
d
l
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Line.direction, wblut.geom.WB_Point.mulSelf(), and wblut.geom.WB_Line.origin.
wblut.geom.WB_Segment.WB_Segment (final WB_Coord p1, final WB_Coord p2)
Parameters
p1
p2
References wblut.geom.WB_GeometryOp3D.getSqDistance3D().
wblut.geom.WB_Segment.WB_Segment (final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
Parameters
p1x
p1y
p1z
p2x
p2y
p2z
References wblut.geom.WB_GeometryOp3D.getSqDistance3D(), and wblut.geom.WB_Line.origin.
Member Function Documentation
WB_Segment wblut.geom.WB_Segment.apply (final WB_Transform T)
References wblut.geom.WB_GeometryFactory3D.createSegment(), and wblut.geom.WB_Line.origin.
WB_Vector wblut.geom.WB_Segment.curveDerivative (final double u)
References wblut.geom.WB_Line.direction.
WB_Vector wblut.geom.WB_Segment.curveDirection (final double u)
References wblut.geom.WB_Line.direction.
WB_Point wblut.geom.WB_Segment.curvePoint (final double u)
References wblut.geom.WB_Segment.getParametricPoint().
boolean wblut.geom.WB_Segment.equals (final Object o)
References wblut.geom.WB_Point.equals(), wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Line.getOrigin(), and wblut.geom.WB_Line.origin.
WB_Point wblut.geom.WB_Segment.getCenter ()
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.mulSelf(), and wblut.geom.WB_Line.origin.
WB_Coord wblut.geom.WB_Segment.getEndpoint ()
Returns
References wblut.geom.WB_Segment.endpoint.
double wblut.geom.WB_Segment.getLength ()
Returns
References wblut.geom.WB_Segment.length.
double wblut.geom.WB_Segment.getLowerU ()
Returns
Implements wblut.geom.WB_Curve.
WB_Point wblut.geom.WB_Segment.getParametricPoint (final double t)
Parameters
t
Returns
References wblut.geom.WB_Point.addSelf(), wblut.math.WB_Math.clamp(), wblut.geom.WB_Line.direction, wblut.geom.WB_Segment.length, wblut.geom.WB_Line.origin, and wblut.geom.WB_Point.scaleSelf().
void wblut.geom.WB_Segment.getParametricPointInto (final double t, final WB_MutableCoord result)
Parameters
t
result
References wblut.math.WB_Math.clamp(), wblut.geom.WB_Line.direction, wblut.geom.WB_Segment.length, wblut.geom.WB_Line.origin, and wblut.geom.WB_MutableCoord.set().
double wblut.geom.WB_Segment.getUpperU ()
Returns
Implements wblut.geom.WB_Curve.
int wblut.geom.WB_Segment.hashCode ()
References wblut.geom.WB_Point.hashCode(), and wblut.geom.WB_Line.origin.
static List<WB_Segment> wblut.geom.WB_Segment.negate (final List< WB_Segment > segs) static
Parameters
segs
Returns
WB_Segment wblut.geom.WB_Segment.negate ()
Returns
References wblut.geom.WB_Line.origin, and wblut.geom.WB_Segment.WB_Segment().
void wblut.geom.WB_Segment.reverse ()
References wblut.geom.WB_Line.origin, and wblut.geom.WB_Line.set().
static WB_Segment wblut.geom.WB_Segment.X () static
Returns
References wblut.geom.WB_Segment.WB_Segment().
static WB_Segment wblut.geom.WB_Segment.Y () static
Returns
References wblut.geom.WB_Segment.WB_Segment().
static WB_Segment wblut.geom.WB_Segment.Z () static
Returns
References wblut.geom.WB_Segment.WB_Segment().
Member Data Documentation
WB_Point wblut.geom.WB_Segment.endpoint protected
WB_GeometryFactory wblut.geom.WB_Segment.geometryfactory = new WB_GeometryFactory() private
double wblut.geom.WB_Segment.length protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Segment.java