HE_Mesh: wblut.hemesh.HET_Export Class Reference
wblut.hemesh.HET_Export Class Reference
Static Public Member Functions
static void saveToOBJ (final HE_Mesh mesh, final String path, final String name)
static void saveToOBJNN (final HE_Mesh mesh, final String path, final String name)
static void saveToOBJWithFaceColor (final HE_Mesh mesh, final String path, final String name)
static void saveToOBJWithVertexColor (final HE_Mesh mesh, final String path, final String name)
static void saveToOBJ (final Collection<?extends HE_Mesh > mesh, final String path, final String name)
static void saveToOBJ (final HE_MeshCollection mesh, final String path, final String name)
static void saveToOBJNN (final Collection<?extends HE_Mesh > mesh, final String path, final String name)
static void saveToOBJNN (final HE_MeshCollection mesh, final String path, final String name)
static void saveToOBJWithFaceColor (final Collection<?extends HE_Mesh > mesh, final String path, final String name)
static void saveToOBJWithFaceColor (final HE_MeshCollection mesh, final String path, final String name)
static void saveToOBJWithVertexColor (final Collection<?extends HE_Mesh > mesh, final String path, final String name)
static void saveToOBJWithVertexColor (final HE_MeshCollection mesh, final String path, final String name)
static void saveToOBJ (final HE_Mesh[] mesh, final String path, final String name)
static void saveToOBJNN (final HE_Mesh[] mesh, final String path, final String name)
static void saveToOBJWithFaceColor (final HE_Mesh[] mesh, final String path, final String name)
static void saveToOBJWithVertexColor (final HE_Mesh[] mesh, final String path, final String name)
static void saveToSTL (final HE_Mesh mesh, final String path, final String name)
static void saveToSTLWithFaceColor (final HE_Mesh mesh, final String path, final String name, final int colormodel)
static void saveToSTLWithFaceColor (final HE_Mesh mesh, final HET_WriterSTL stl)
static void saveToSimpleMesh (final HE_Mesh mesh, final String path, final String name)
static void saveToHemesh (final HE_Mesh mesh, final String path, final String name)
static void saveToBinaryHemesh (final HE_Mesh mesh, final String path, final String name)
static void saveToPOV (final HE_Mesh mesh, final String path, final String name)
static void saveToPOV (final HE_Mesh mesh, final String path, final String name, final boolean saveNormals)
static void saveToPOV (final HE_Mesh mesh, final HET_WriterPOV pov, final boolean normals)
static void saveToPOV (final HE_Mesh mesh, final PrintWriter pw)
static void saveToPOV (final HE_Mesh mesh, final PrintWriter pw, final boolean saveNormals)
static void saveToWRLWithFaceColor (final HE_Mesh mesh, final String path, final String name)
static void saveToWRLWithVertexColor (final HE_Mesh mesh, final String path, final String name)
static void saveToWRL (final HE_Mesh mesh, final String path, final String name)
static void saveToPLY (final HE_Mesh mesh, final String path, final String name)
static void saveToPLYWithVertexColor (final HE_Mesh mesh, final String path, final String name)
static void saveToPLYWithFaceColor (final HE_Mesh mesh, final String path, final String name)
Static Public Attributes
static int NONE = -1
static int DEFAULT = 0
static int MATERIALISE = 1
Detailed Description
Collection of export functions.
Author
Frederik Vanhoutte, W:Blut
Member Function Documentation
static void wblut.hemesh.HET_Export.saveToBinaryHemesh (final HE_Mesh mesh, final String path, final String name) static
Saves the mesh as binary hemesh format to the given file path. Existing files will be overwritten. The file contains the vertex coordinates and all half-edge interconnection information. About the same size of a simpleMesh but a lot quicker to rebuild. Due to compression about half as fast as an ordinary hemesh file but only a third in size.
Parameters
mesh the mesh
path the path
name
References wblut.hemesh.HET_WriterBinaryHemesh.beginSave(), wblut.hemesh.HET_WriterBinaryHemesh.endSave(), wblut.hemesh.HET_WriterBinaryHemesh.face(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfHalfedges(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HET_WriterBinaryHemesh.halfedge(), wblut.hemesh.HE_Mesh.heItr(), wblut.hemesh.HE_Halfedge.key(), wblut.hemesh.HE_Face.key(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HET_WriterBinaryHemesh.sizes(), wblut.hemesh.HET_WriterBinaryHemesh.vertex(), and wblut.hemesh.HE_Mesh.vItr().
static void wblut.hemesh.HET_Export.saveToHemesh (final HE_Mesh mesh, final String path, final String name) static
Saves the mesh as hemesh format to the given file path. Existing files will be overwritten. The file contains the vertex coordinates and all half-edge interconnection information. Larger than a simpleMesh but much quicker to rebuild.
Parameters
mesh the mesh
path the path
name
References wblut.hemesh.HET_WriterHemesh.beginSave(), wblut.hemesh.HET_WriterHemesh.endSave(), wblut.hemesh.HET_WriterHemesh.face(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfHalfedges(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HET_WriterHemesh.halfedge(), wblut.hemesh.HE_Mesh.heItr(), wblut.hemesh.HE_Halfedge.key(), wblut.hemesh.HE_Face.key(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HET_WriterHemesh.sizes(), wblut.hemesh.HET_WriterHemesh.vertex(), and wblut.hemesh.HE_Mesh.vItr().
static void wblut.hemesh.HET_Export.saveToOBJ (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
static void wblut.hemesh.HET_Export.saveToOBJ (final Collection<?extends HE_Mesh > mesh, final String path, final String name) static
Parameters
mesh
path
name
static void wblut.hemesh.HET_Export.saveToOBJ (final HE_MeshCollection mesh, final String path, final String name) static
static void wblut.hemesh.HET_Export.saveToOBJ (final HE_Mesh[] mesh, final String path, final String name) static
Parameters
mesh
path
name
static void wblut.hemesh.HET_Export.saveToOBJNN (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
static void wblut.hemesh.HET_Export.saveToOBJNN (final Collection<?extends HE_Mesh > mesh, final String path, final String name) static
Parameters
mesh
path
name
static void wblut.hemesh.HET_Export.saveToOBJNN (final HE_MeshCollection mesh, final String path, final String name) static
static void wblut.hemesh.HET_Export.saveToOBJNN (final HE_Mesh[] mesh, final String path, final String name) static
Parameters
mesh
path
name
static void wblut.hemesh.HET_Export.saveToOBJWithFaceColor (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
static void wblut.hemesh.HET_Export.saveToOBJWithFaceColor (final Collection<?extends HE_Mesh > mesh, final String path, final String name) static
Parameters
mesh
path
name
static void wblut.hemesh.HET_Export.saveToOBJWithFaceColor (final HE_MeshCollection mesh, final String path, final String name) static
static void wblut.hemesh.HET_Export.saveToOBJWithFaceColor (final HE_Mesh[] mesh, final String path, final String name) static
Parameters
mesh
path
name
static void wblut.hemesh.HET_Export.saveToOBJWithVertexColor (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
static void wblut.hemesh.HET_Export.saveToOBJWithVertexColor (final Collection<?extends HE_Mesh > mesh, final String path, final String name) static
Parameters
mesh
path
name
static void wblut.hemesh.HET_Export.saveToOBJWithVertexColor (final HE_MeshCollection mesh, final String path, final String name) static
static void wblut.hemesh.HET_Export.saveToOBJWithVertexColor (final HE_Mesh[] mesh, final String path, final String name) static
Parameters
mesh
path
name
static void wblut.hemesh.HET_Export.saveToPLY (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
References wblut.hemesh.HET_WriterPLY.saveMesh().
static void wblut.hemesh.HET_Export.saveToPLYWithFaceColor (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
References wblut.hemesh.HET_WriterPLY.saveMeshWithFaceColor().
static void wblut.hemesh.HET_Export.saveToPLYWithVertexColor (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
References wblut.hemesh.HET_WriterPLY.saveMeshWithVertexColor().
static void wblut.hemesh.HET_Export.saveToPOV (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
static void wblut.hemesh.HET_Export.saveToPOV (final HE_Mesh mesh, final String path, final String name, final boolean saveNormals) static
Parameters
mesh
path
name
saveNormals
References wblut.hemesh.HET_WriterPOV.beginSave(), wblut.hemesh.HET_WriterPOV.endSave(), and wblut.hemesh.HET_Export.saveToPOV().
static void wblut.hemesh.HET_Export.saveToPOV (final HE_Mesh mesh, final HET_WriterPOV pov, final boolean normals) static
Saves the mesh as PovRAY mesh2 format by appending it to the given mesh.
Parameters
mesh the mesh
pov instance of HET_POVWriter
normals smooth faces HET_WriterPOV instance.
References wblut.hemesh.HET_WriterPOV.beginIndices(), wblut.hemesh.HET_WriterPOV.beginMesh2(), wblut.hemesh.HET_WriterPOV.beginNormals(), wblut.hemesh.HET_WriterPOV.endSection(), wblut.hemesh.HET_WriterPOV.face(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HET_WriterPOV.getCurrVertexOffset(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Element.getKey(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HET_WriterPOV.total(), wblut.hemesh.HET_WriterPOV.vertex(), and wblut.hemesh.HE_Mesh.vItr().
static void wblut.hemesh.HET_Export.saveToPOV (final HE_Mesh mesh, final PrintWriter pw) static
Saves the mesh as PovRAY format to the given PrintWriter.
Parameters
mesh HE_Mesh
pw PrintWriter
References wblut.hemesh.HET_Export.saveToPOV().
static void wblut.hemesh.HET_Export.saveToPOV (final HE_Mesh mesh, final PrintWriter pw, final boolean saveNormals) static
Saves the mesh as PovRAY format to the given PrintWriter.
Parameters
mesh HE_Mesh
pw PrintWriter
saveNormals boolean (Smooth face or otherwise)
References wblut.hemesh.HET_WriterPOV.beginSave(), wblut.hemesh.HET_WriterPOV.endSave(), and wblut.hemesh.HET_Export.saveToPOV().
static void wblut.hemesh.HET_Export.saveToSimpleMesh (final HE_Mesh mesh, final String path, final String name) static
Saves the mesh as simpleMesh format to the given file path. Existing files will be overwritten. The file gives the vertex coordinates and an indexed facelist.
Parameters
mesh the mesh
path the path
name
References wblut.hemesh.HET_WriterSimpleMesh.beginSave(), wblut.hemesh.HET_WriterSimpleMesh.endSave(), wblut.hemesh.HET_WriterSimpleMesh.faces(), wblut.hemesh.HE_Mesh.getFacesAsInt(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Mesh.getVerticesAsCoord(), wblut.hemesh.HET_WriterSimpleMesh.intValue(), and wblut.hemesh.HET_WriterSimpleMesh.vertices().
static void wblut.hemesh.HET_Export.saveToSTL (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
References wblut.hemesh.HET_Export.NONE, and wblut.hemesh.HET_Export.saveToSTLWithFaceColor().
static void wblut.hemesh.HET_Export.saveToSTLWithFaceColor (final HE_Mesh mesh, final String path, final String name, final int colormodel) static
Parameters
mesh
path
name
colormodel
References wblut.hemesh.HET_WriterSTL.beginSave(), wblut.hemesh.HET_WriterSTL.DEFAULT, wblut.hemesh.HET_WriterSTL.DEFAULT_BUFFER, wblut.hemesh.HET_WriterSTL.endSave(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HET_WriterSTL.MATERIALISE, and wblut.hemesh.HET_WriterSTL.NONE.
static void wblut.hemesh.HET_Export.saveToSTLWithFaceColor (final HE_Mesh mesh, final HET_WriterSTL stl) static
Parameters
mesh
stl
References wblut.hemesh.HET_WriterSTL.face(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.hasNext(), and wblut.hemesh.HE_FaceIterator.next().
static void wblut.hemesh.HET_Export.saveToWRL (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
References wblut.hemesh.HET_WriterWRL.saveMesh().
static void wblut.hemesh.HET_Export.saveToWRLWithFaceColor (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
References wblut.hemesh.HET_WriterWRL.saveMeshWithFaceColor().
static void wblut.hemesh.HET_Export.saveToWRLWithVertexColor (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
References wblut.hemesh.HET_WriterWRL.saveMeshWithVertexColor().
Member Data Documentation
int wblut.hemesh.HET_Export.DEFAULT = 0 static
int wblut.hemesh.HET_Export.MATERIALISE = 1 static
int wblut.hemesh.HET_Export.NONE = -1 static
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_Export.java