HE_Mesh: wblut.hemesh.HEM_TriangleInversion Class Reference
wblut.hemesh.HEM_TriangleInversion Class Reference
Public Member Functions
HEM_TriangleInversion ()
HEM_TriangleInversion (final WB_Triangle triangle, final double r)
HEM_TriangleInversion setTriangle (final WB_Triangle triangle)
HEM_TriangleInversion setTriangle (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
HEM_TriangleInversion setRadius (final double r)
HEM_TriangleInversion setCutoff (final double cutoff)
HEM_TriangleInversion setLinear (final boolean b)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_Triangle triangle
double r
double icutoff
boolean linear
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_TriangleInversion.HEM_TriangleInversion ()
wblut.hemesh.HEM_TriangleInversion.HEM_TriangleInversion (final WB_Triangle triangle, final double r)
References wblut.hemesh.HEM_TriangleInversion.r, and wblut.hemesh.HEM_TriangleInversion.triangle.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_TriangleInversion.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Vector.normalizeSelf(), wblut.hemesh.HE_Vertex.set(), wblut.geom.WB_Point.subToVector3D(), wblut.geom.WB_Vector.subToVector3D(), and wblut.hemesh.HE_Mesh.vItr().
HE_Mesh wblut.hemesh.HEM_TriangleInversion.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Vector.normalizeSelf(), wblut.hemesh.HE_Vertex.set(), wblut.geom.WB_Point.subToVector3D(), wblut.geom.WB_Vector.subToVector3D(), and wblut.hemesh.HE_Selection.vItr().
HEM_TriangleInversion wblut.hemesh.HEM_TriangleInversion.setCutoff (final double cutoff)
Parameters
cutoff
Returns
HEM_TriangleInversion wblut.hemesh.HEM_TriangleInversion.setLinear (final boolean b)
Parameters
b
Returns
HEM_TriangleInversion wblut.hemesh.HEM_TriangleInversion.setRadius (final double r)
Parameters
r
Returns
References wblut.hemesh.HEM_TriangleInversion.r.
HEM_TriangleInversion wblut.hemesh.HEM_TriangleInversion.setTriangle (final WB_Triangle triangle)
Parameters
triangle
Returns
References wblut.hemesh.HEM_TriangleInversion.triangle.
HEM_TriangleInversion wblut.hemesh.HEM_TriangleInversion.setTriangle (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
Member Data Documentation
double wblut.hemesh.HEM_TriangleInversion.icutoff private
boolean wblut.hemesh.HEM_TriangleInversion.linear private
double wblut.hemesh.HEM_TriangleInversion.r private
WB_Triangle wblut.hemesh.HEM_TriangleInversion.triangle private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_TriangleInversion.java