HE_Mesh: wblut.hemesh.HEM_CapHoles Class Reference
wblut.hemesh.HEM_CapHoles Class Reference
Public Member Functions
HEM_CapHoles ()
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
HE_Selection caps
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_CapHoles.HEM_CapHoles ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_CapHoles.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_RAS< E extends HE_Element >.add(), wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HE_Mesh.cleanUnusedElementsByFace(), wblut.hemesh.HE_RAS< E extends HE_Element >.contains(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_RAS< E extends HE_Element >.getObjects(), wblut.hemesh.HE_Mesh.getUnpairedHalfedges(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_RAS< E extends HE_Element >.getWithIndex(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Mesh.orderHalfedgesReverse(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setDuringStatus(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setPair(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HE_RAS< E extends HE_Element >.size(), and wblut.hemesh.HE_Machine.tracker.
HE_Mesh wblut.hemesh.HEM_CapHoles.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HEM_CapHoles.applySelf().
Member Data Documentation
HE_Selection wblut.hemesh.HEM_CapHoles.caps private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_CapHoles.java