HE_Mesh: wblut.hemesh.HET_Texture Class Reference
wblut.hemesh.HET_Texture Class Reference
Static Public Member Functions
static void cleanUVW (final HE_Mesh mesh)
static void clearUVW (final HE_Mesh mesh)
static void setVertexColorFromVertexNormal (final HE_Mesh mesh)
static void setVertexColorFromPalette (final HE_Mesh mesh, final int[] palette)
static void setRandomVertexColorFromPalette (final HE_Mesh mesh, final int[] palette)
static void setRandomVertexColorFromPalette (final HE_Mesh mesh, final int[] palette, final long seed)
static void setVertexColorFromVertexUmbrella (final HE_Mesh mesh, final double minrange, final double maxrange, final int[] palette)
static void setVertexColorFromVertexCurvature (final HE_Mesh mesh, final double minrange, final double maxrange, final int[] palette)
static void setFaceColorFromFaceNormal (final HE_Mesh mesh)
static void setFaceColorFromPalette (final HE_Mesh mesh, final int[] palette)
static void setRandomFaceColorFromPalette (final HE_Mesh mesh, final int[] palette)
static void setRandomFaceColorFromPalette (final HE_Mesh mesh, final int[] palette, final long seed)
static void setFaceColorFromTexture (final HE_Mesh mesh, final PImage texture)
static void setHalfedgeColorFromTexture (final HE_Mesh mesh, final PImage texture)
static void setVertexColorFromTexture (final HE_Mesh mesh, final PImage texture)
Member Function Documentation
static void wblut.hemesh.HET_Texture.cleanUVW (final HE_Mesh mesh) static
References wblut.hemesh.HE_Vertex.cleanUVW(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_VertexIterator.next(), and wblut.hemesh.HE_Mesh.vItr().
static void wblut.hemesh.HET_Texture.clearUVW (final HE_Mesh mesh) static
References wblut.hemesh.HE_Vertex.clearUVW(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_Mesh.heItr(), wblut.hemesh.HE_VertexIterator.next(), and wblut.hemesh.HE_Mesh.vItr().
static void wblut.hemesh.HET_Texture.setFaceColorFromFaceNormal (final HE_Mesh mesh) static
Set face colors according to the face normal normal.x: -1 to 1, red component from 0 to 255 normal.y: -1 to 1, green component from 0 to 255 normal.z: -1 to 1, blue component from 0 to 255
Parameters
mesh
References wblut.processing.WB_Color.color(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_MeshElement.setColor(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static void wblut.hemesh.HET_Texture.setFaceColorFromPalette (final HE_Mesh mesh, final int[] palette) static
Set face colors by face.getLabel() from a palette (an array of int)
Parameters
mesh
palette
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Element.getUserLabel(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), and wblut.hemesh.HE_MeshElement.setColor().
static void wblut.hemesh.HET_Texture.setFaceColorFromTexture (final HE_Mesh mesh, final PImage texture) static
Parameters
mesh
texture
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.divSelf(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.fvCrc(), wblut.processing.WB_Render3D.getColorFromPImage(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceVertexCirculator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_FaceVertexCirculator.next(), wblut.hemesh.HE_MeshElement.setColor(), wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static void wblut.hemesh.HET_Texture.setHalfedgeColorFromTexture (final HE_Mesh mesh, final PImage texture) static
Parameters
mesh
texture
References wblut.hemesh.HE_Face.fheiCrc(), wblut.hemesh.HE_Mesh.fItr(), wblut.processing.WB_Render3D.getColorFromPImage(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceHalfedgeInnerCirculator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_FaceHalfedgeInnerCirculator.next(), wblut.hemesh.HE_MeshElement.setColor(), wblut.hemesh.HE_TextureCoordinate.ud(), and wblut.hemesh.HE_TextureCoordinate.vd().
static void wblut.hemesh.HET_Texture.setRandomFaceColorFromPalette (final HE_Mesh mesh, final int[] palette) static
Set face colors randomly chosen from a palette (an array of int).
Parameters
mesh
palette
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), and wblut.hemesh.HE_MeshElement.setColor().
static void wblut.hemesh.HET_Texture.setRandomFaceColorFromPalette (final HE_Mesh mesh, final int[] palette, final long seed) static
Parameters
mesh
palette
seed
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.math.WB_MTRandom.nextDouble(), and wblut.hemesh.HE_MeshElement.setColor().
static void wblut.hemesh.HET_Texture.setRandomVertexColorFromPalette (final HE_Mesh mesh, final int[] palette) static
Set vertex colors randomly chosen from a palette (an array of int)
Parameters
mesh
palette
References wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HE_MeshElement.setColor(), and wblut.hemesh.HE_Mesh.vItr().
static void wblut.hemesh.HET_Texture.setRandomVertexColorFromPalette (final HE_Mesh mesh, final int[] palette, final long seed) static
Parameters
mesh
palette
seed
References wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_VertexIterator.next(), wblut.math.WB_MTRandom.nextDouble(), wblut.hemesh.HE_MeshElement.setColor(), and wblut.hemesh.HE_Mesh.vItr().
static void wblut.hemesh.HET_Texture.setVertexColorFromPalette (final HE_Mesh mesh, final int[] palette) static
Set vertex colors by vertex.getLabel() from a palette (an array of int)
Parameters
mesh
palette
References wblut.hemesh.HE_Element.getUserLabel(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HE_MeshElement.setColor(), and wblut.hemesh.HE_Mesh.vItr().
static void wblut.hemesh.HET_Texture.setVertexColorFromTexture (final HE_Mesh mesh, final PImage texture) static
Parameters
mesh
texture
References wblut.processing.WB_Render3D.getColorFromPImage(), wblut.hemesh.HE_Vertex.getVertexUVW(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HE_MeshElement.setColor(), wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), and wblut.hemesh.HE_Mesh.vItr().
static void wblut.hemesh.HET_Texture.setVertexColorFromVertexCurvature (final HE_Mesh mesh, final double minrange, final double maxrange, final int[] palette) static
Set vertex colors according to the Gaussian curvature.
Parameters
mesh
minrange
maxrange
palette
References wblut.hemesh.HE_Vertex.getGaussCurvature(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HE_MeshElement.setColor(), and wblut.hemesh.HE_Mesh.vItr().
static void wblut.hemesh.HET_Texture.setVertexColorFromVertexNormal (final HE_Mesh mesh) static
Set vertex colors according to the vertex normal normal.x: -1 to 1, red component from 0 to 255 normal.y: -1 to 1, green component from 0 to 255 normal.z: -1 to 1, blue component from 0 to 255
Parameters
mesh
References wblut.processing.WB_Color.color(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HE_MeshElement.setColor(), wblut.hemesh.HE_Mesh.vItr(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static void wblut.hemesh.HET_Texture.setVertexColorFromVertexUmbrella (final HE_Mesh mesh, final double minrange, final double maxrange, final int[] palette) static
Set vertex colors according to the umbrella angle. Angle: 0 (infinite outward or inward spike) to 2 Pi (flat).
Parameters
mesh
minrange
maxrange
palette
References wblut.hemesh.HE_Vertex.getUmbrellaAngle(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HE_MeshElement.setColor(), and wblut.hemesh.HE_Mesh.vItr().
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_Texture.java