HE_Mesh: wblut.geom.WB_Triangle Class Reference
wblut.geom.WB_Triangle Class Reference
Public Member Functions
WB_Triangle (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
void cycle ()
void cycle (int n)
WB_Coord p1 ()
WB_Coord p2 ()
WB_Coord p3 ()
double a ()
double b ()
double c ()
double cosA ()
double cosB ()
double cosC ()
WB_Coord getPoint (final int i)
WB_Point getCenter ()
WB_Triangle apply (final WB_Transform T)
WB_Plane getPlane ()
WB_Map2D getEmbeddedPlane ()
WB_Point getCentroid ()
WB_Point getCircumcenter ()
WB_Point getOrthocenter ()
WB_Point getPointFromTrilinear (final double x, final double y, final double z)
WB_Point getPointFromBarycentric (final double x, final double y, final double z)
double[] getBarycentricCoordinates (final WB_Coord p)
WB_Point getBarycentric (final WB_Coord p)
double getArea ()
WB_AABB getAABB ()
WB_AABB2D getAABB2D ()
double getSignedArea ()
WB_Circle getCircumcircle ()
WB_Circle getIncircle ()
WB_Point getIncenter ()
double minX ()
double minY ()
double minZ ()
double maxX ()
double maxY ()
double maxZ ()
Protected Member Functions
WB_Triangle ()
void update ()
Private Attributes
double a
double b
double c
double cosA
double cosB
double cosC
WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.geom.WB_Triangle.WB_Triangle () protected
wblut.geom.WB_Triangle.WB_Triangle (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
Parameters
p1
p2
p3
References wblut.geom.WB_Triangle.p1(), wblut.geom.WB_Triangle.p2(), wblut.geom.WB_Triangle.p3(), and wblut.geom.WB_Triangle.update().
Member Function Documentation
double wblut.geom.WB_Triangle.a ()
Returns
WB_Triangle wblut.geom.WB_Triangle.apply (final WB_Transform T)
References wblut.geom.WB_Transform.applyAsPoint(), and wblut.geom.WB_GeometryFactory3D.createTriangle().
double wblut.geom.WB_Triangle.b ()
Returns
double wblut.geom.WB_Triangle.c ()
Returns
double wblut.geom.WB_Triangle.cosA ()
Returns
double wblut.geom.WB_Triangle.cosB ()
Returns
double wblut.geom.WB_Triangle.cosC ()
Returns
void wblut.geom.WB_Triangle.cycle ()
References wblut.geom.WB_Triangle.p1(), wblut.geom.WB_Triangle.p2(), wblut.geom.WB_Triangle.p3(), and wblut.geom.WB_Triangle.update().
void wblut.geom.WB_Triangle.cycle (int n)
References wblut.geom.WB_Triangle.cycle().
WB_AABB wblut.geom.WB_Triangle.getAABB ()
References wblut.geom.WB_Triangle.maxX(), wblut.geom.WB_Triangle.maxY(), wblut.geom.WB_Triangle.maxZ(), wblut.geom.WB_Triangle.minX(), wblut.geom.WB_Triangle.minY(), and wblut.geom.WB_Triangle.minZ().
WB_AABB2D wblut.geom.WB_Triangle.getAABB2D ()
References wblut.geom.WB_Triangle.maxX(), wblut.geom.WB_Triangle.maxY(), wblut.geom.WB_Triangle.minX(), and wblut.geom.WB_Triangle.minY().
double wblut.geom.WB_Triangle.getArea ()
Gets the area.
Returns
the area
References wblut.math.WB_Math.fastAbs(), and wblut.geom.WB_Triangle.getSignedArea().
WB_Point wblut.geom.WB_Triangle.getBarycentric (final WB_Coord p)
Barycentric.
Parameters
p the p
Returns
the w b_ point
References wblut.geom.WB_Vector.cross(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Vector.subToVector3D(), wblut.geom.WB_GeometryOp2D.twiceSignedTriArea2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
double [] wblut.geom.WB_Triangle.getBarycentricCoordinates (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp2D.twiceSignedTriArea2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_Triangle.getCenter ()
References wblut.geom.WB_GeometryFactory3D.createMidpoint().
WB_Point wblut.geom.WB_Triangle.getCentroid ()
Get centroid.
Returns
centroid
References wblut.geom.WB_Triangle.getPointFromTrilinear().
WB_Point wblut.geom.WB_Triangle.getCircumcenter ()
Get circumcenter.
Returns
circumcenter
References wblut.geom.WB_Triangle.getPointFromTrilinear().
WB_Circle wblut.geom.WB_Triangle.getCircumcircle ()
Get circumcircle.
Returns
circumcircle
References wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Circle.setCenter(), wblut.geom.WB_Circle.setRadius(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Map2D wblut.geom.WB_Triangle.getEmbeddedPlane ()
Returns
References wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane(), and wblut.geom.WB_Triangle.getPlane().
WB_Point wblut.geom.WB_Triangle.getIncenter ()
Get incenter.
Returns
incenter
References wblut.geom.WB_Triangle.getPointFromTrilinear().
WB_Circle wblut.geom.WB_Triangle.getIncircle ()
Get incircle.
Returns
incircle
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Triangle.c(), wblut.geom.WB_Point.divSelf(), wblut.geom.WB_Point.mul(), wblut.geom.WB_Circle.setCenter(), and wblut.geom.WB_Circle.setRadius().
WB_Point wblut.geom.WB_Triangle.getOrthocenter ()
Get orthocenter.
Returns
orthocenter
References wblut.geom.WB_Triangle.a(), wblut.geom.WB_Triangle.b(), wblut.geom.WB_Triangle.c(), and wblut.geom.WB_Triangle.getPointFromBarycentric().
WB_Plane wblut.geom.WB_Triangle.getPlane ()
Get plane of triangle.
Returns
WB_Plane
References wblut.geom.WB_Triangle.getCenter(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Vector.getSqLength(), and wblut.math.WB_Epsilon.SQEPSILON.
WB_Coord wblut.geom.WB_Triangle.getPoint (final int i)
References wblut.geom.WB_Triangle.p1(), wblut.geom.WB_Triangle.p2(), and wblut.geom.WB_Triangle.p3().
WB_Point wblut.geom.WB_Triangle.getPointFromBarycentric (final double x, final double y, final double z)
Get point from barycentric coordinates.
Parameters
x the x
y the y
z the z
Returns
point
References wblut.geom.WB_Triangle.getPointFromTrilinear().
WB_Point wblut.geom.WB_Triangle.getPointFromTrilinear (final double x, final double y, final double z)
Get point from trilinear coordinates.
Parameters
x the x
y the y
z the z
Returns
point
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.divSelf(), wblut.geom.WB_Point.mulSelf(), and wblut.geom.WB_Point.sub().
double wblut.geom.WB_Triangle.getSignedArea ()
Returns
References wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Triangle.getPlane(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
double wblut.geom.WB_Triangle.maxX ()
References wblut.geom.WB_Coord.xd().
double wblut.geom.WB_Triangle.maxY ()
References wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Triangle.maxZ ()
References wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Triangle.minX ()
References wblut.geom.WB_Coord.xd().
double wblut.geom.WB_Triangle.minY ()
References wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Triangle.minZ ()
References wblut.geom.WB_Coord.zd().
WB_Coord wblut.geom.WB_Triangle.p1 ()
Returns
WB_Coord wblut.geom.WB_Triangle.p2 ()
Returns
WB_Coord wblut.geom.WB_Triangle.p3 ()
Returns
void wblut.geom.WB_Triangle.update () protected
Update side lengths and corner angles.
References wblut.geom.WB_Triangle.b(), wblut.geom.WB_Triangle.c(), wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane(), wblut.geom.WB_Vector.getDistance3D(), wblut.geom.WB_Triangle.getPlane(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Map.mapPoint3D(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
Member Data Documentation
double wblut.geom.WB_Triangle.a private
Length of side a.
double wblut.geom.WB_Triangle.b private
Length of side b.
double wblut.geom.WB_Triangle.c private
Length of side c.
double wblut.geom.WB_Triangle.cosA private
Cosine of angle A.
double wblut.geom.WB_Triangle.cosB private
Cosine of angle B.
double wblut.geom.WB_Triangle.cosC private
Cosine of angle C.
WB_GeometryFactory wblut.geom.WB_Triangle.geometryfactory = new WB_GeometryFactory() private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Triangle.java