HE_Mesh: wblut.math.WB_OSNoise Class Reference
wblut.math.WB_OSNoise Class Reference
Public Member Functions
WB_OSNoise ()
WB_OSNoise (final long seed)
void setSeed (long seed)
double value1D (final double x)
double value2D (final double x, final double y)
double value3D (final double x, final double y, final double z)
double value4D (final double x, final double y, final double z, final double w)
void setScale (final double sx)
void setScale (final double sx, final double sy)
void setScale (final double sx, final double sy, final double sz)
void setScale (final double sx, final double sy, final double sz, final double sw)
Public Member Functions inherited from wblut.math.WB_Noise
double value1D (double x)
double value2D (double x, double y)
double value3D (double x, double y, double z)
double value4D (double x, double y, double z, double w)
void setScale (double sx)
void setScale (double sx, double sy)
void setScale (double sx, double sy, double sz)
void setScale (double sx, double sy, double sz, double sw)
Private Member Functions
double extrapolate (final int xsb, final int ysb, final double dx, final double dy)
double extrapolate (final int xsb, final int ysb, final int zsb, final double dx, final double dy, final double dz)
double extrapolate (final int xsb, final int ysb, final int zsb, final int wsb, final double dx, final double dy, final double dz, final double dw)
Static Private Member Functions
static int fastFloor (final double x)
Private Attributes
short[] perm
short[] permGradIndex3D
double sx
Static Private Attributes
static final double STRETCH_CONSTANT_2D = -0.211324865405187
static final double SQUISH_CONSTANT_2D = 0.366025403784439
static final double STRETCH_CONSTANT_3D = -1.0 / 6
static final double SQUISH_CONSTANT_3D = 1.0 / 3
static final double STRETCH_CONSTANT_4D = -0.138196601125011
static final double SQUISH_CONSTANT_4D = 0.309016994374947
static final double NORM_CONSTANT_2D = 47
static final double NORM_CONSTANT_3D = 103
static final double NORM_CONSTANT_4D = 30
static byte[] gradients2D = new byte[] { 5, 2, 2, 5, -5, 2, -2, 5, 5, -2, 2, -5, -5, -2, -2, -5, }
static byte[] gradients3D
static byte[] gradients4D
Constructor & Destructor Documentation
wblut.math.WB_OSNoise.WB_OSNoise ()
wblut.math.WB_OSNoise.WB_OSNoise (final long seed)
Parameters
seed
References wblut.math.WB_OSNoise.setSeed().
Member Function Documentation
double wblut.math.WB_OSNoise.extrapolate (final int xsb, final int ysb, final double dx, final double dy) private
Parameters
xsb
ysb
dx
dy
Returns
References wblut.math.WB_OSNoise.gradients2D.
double wblut.math.WB_OSNoise.extrapolate (final int xsb, final int ysb, final int zsb, final double dx, final double dy, final double dz) private
Parameters
xsb
ysb
zsb
dx
dy
dz
Returns
References wblut.math.WB_OSNoise.gradients3D.
double wblut.math.WB_OSNoise.extrapolate (final int xsb, final int ysb, final int zsb, final int wsb, final double dx, final double dy, final double dz, final double dw) private
Parameters
xsb
ysb
zsb
wsb
dx
dy
dz
dw
Returns
References wblut.math.WB_OSNoise.gradients4D.
static int wblut.math.WB_OSNoise.fastFloor (final double x) static private
Parameters
x
Returns
void wblut.math.WB_OSNoise.setScale (final double sx)
References wblut.math.WB_OSNoise.sx.
void wblut.math.WB_OSNoise.setScale (final double sx, final double sy)
References wblut.math.WB_OSNoise.sx.
void wblut.math.WB_OSNoise.setScale (final double sx, final double sy, final double sz)
References wblut.math.WB_OSNoise.sx.
void wblut.math.WB_OSNoise.setScale (final double sx, final double sy, final double sz, final double sw)
References wblut.math.WB_OSNoise.sx.
void wblut.math.WB_OSNoise.setSeed (long seed)
Parameters
seed
Implements wblut.math.WB_Noise.
References wblut.math.WB_OSNoise.gradients3D.
double wblut.math.WB_OSNoise.value1D (final double x)
References wblut.math.WB_OSNoise.value2D().
double wblut.math.WB_OSNoise.value2D (final double x, final double y)
References wblut.math.WB_OSNoise.extrapolate(), wblut.math.WB_OSNoise.fastFloor(), wblut.math.WB_OSNoise.NORM_CONSTANT_2D, and wblut.math.WB_OSNoise.SQUISH_CONSTANT_2D.
double wblut.math.WB_OSNoise.value3D (final double x, final double y, final double z)
References wblut.math.WB_OSNoise.extrapolate(), wblut.math.WB_OSNoise.fastFloor(), wblut.math.WB_OSNoise.NORM_CONSTANT_3D, wblut.math.WB_OSNoise.SQUISH_CONSTANT_3D, and wblut.math.WB_OSNoise.STRETCH_CONSTANT_3D.
double wblut.math.WB_OSNoise.value4D (final double x, final double y, final double z, final double w)
References wblut.math.WB_OSNoise.extrapolate(), wblut.math.WB_OSNoise.fastFloor(), wblut.math.WB_OSNoise.NORM_CONSTANT_4D, and wblut.math.WB_OSNoise.SQUISH_CONSTANT_4D.
Member Data Documentation
byte [] wblut.math.WB_OSNoise.gradients2D = new byte[] { 5, 2, 2, 5, -5, 2, -2, 5, 5, -2, 2, -5, -5, -2, -2, -5, } static private
byte [] wblut.math.WB_OSNoise.gradients3D static private
Initial value:
= new byte[] { -11, 4, 4, -4, 11, 4, -4, 4, 11, 11, 4, 4, 4, 11, 4, 4, 4, 11, -11,
            -4, 4, -4, -11, 4, -4, -4, 11, 11, -4, 4, 4, -11, 4, 4, -4, 11, -11, 4, -4, -4, 11, -4, -4, 4, -11, 11, 4,
            -4, 4, 11, -4, 4, 4, -11, -11, -4, -4, -4, -11, -4, -4, -4, -11, 11, -4, -4, 4, -11, -4, 4, -4, -11, }
byte [] wblut.math.WB_OSNoise.gradients4D static private
Initial value:
= new byte[] { 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, -3, 1, 1, 1, -1, 3,
            1, 1, -1, 1, 3, 1, -1, 1, 1, 3, 3, -1, 1, 1, 1, -3, 1, 1, 1, -1, 3, 1, 1, -1, 1, 3, -3, -1, 1, 1, -1, -3, 1,
            1, -1, -1, 3, 1, -1, -1, 1, 3, 3, 1, -1, 1, 1, 3, -1, 1, 1, 1, -3, 1, 1, 1, -1, 3, -3, 1, -1, 1, -1, 3, -1,
            1, -1, 1, -3, 1, -1, 1, -1, 3, 3, -1, -1, 1, 1, -3, -1, 1, 1, -1, -3, 1, 1, -1, -1, 3, -3, -1, -1, 1, -1,
            -3, -1, 1, -1, -1, -3, 1, -1, -1, -1, 3, 3, 1, 1, -1, 1, 3, 1, -1, 1, 1, 3, -1, 1, 1, 1, -3, -3, 1, 1, -1,
            -1, 3, 1, -1, -1, 1, 3, -1, -1, 1, 1, -3, 3, -1, 1, -1, 1, -3, 1, -1, 1, -1, 3, -1, 1, -1, 1, -3, -3, -1, 1,
            -1, -1, -3, 1, -1, -1, -1, 3, -1, -1, -1, 1, -3, 3, 1, -1, -1, 1, 3, -1, -1, 1, 1, -3, -1, 1, 1, -1, -3, -3,
            1, -1, -1, -1, 3, -1, -1, -1, 1, -3, -1, -1, 1, -1, -3, 3, -1, -1, -1, 1, -3, -1, -1, 1, -1, -3, -1, 1, -1,
            -1, -3, -3, -1, -1, -1, -1, -3, -1, -1, -1, -1, -3, -1, -1, -1, -1, -3, }
final double wblut.math.WB_OSNoise.NORM_CONSTANT_2D = 47 static private
final double wblut.math.WB_OSNoise.NORM_CONSTANT_3D = 103 static private
final double wblut.math.WB_OSNoise.NORM_CONSTANT_4D = 30 static private
short [] wblut.math.WB_OSNoise.perm private
short [] wblut.math.WB_OSNoise.permGradIndex3D private
final double wblut.math.WB_OSNoise.SQUISH_CONSTANT_2D = 0.366025403784439 static private
final double wblut.math.WB_OSNoise.SQUISH_CONSTANT_3D = 1.0 / 3 static private
final double wblut.math.WB_OSNoise.SQUISH_CONSTANT_4D = 0.309016994374947 static private
final double wblut.math.WB_OSNoise.STRETCH_CONSTANT_2D = -0.211324865405187 static private
final double wblut.math.WB_OSNoise.STRETCH_CONSTANT_3D = -1.0 / 6 static private
final double wblut.math.WB_OSNoise.STRETCH_CONSTANT_4D = -0.138196601125011 static private
double wblut.math.WB_OSNoise.sx private
The documentation for this class was generated from the following file:
src/math/wblut/math/WB_OSNoise.java