HE_Mesh: wblut.geom.WB_TriGrid Class Reference
wblut.geom.WB_TriGrid Class Reference
Public Member Functions
WB_TriGrid ()
WB_TriGrid (final double scale)
WB_TriGrid setScale (final double scale)
WB_Point getPoint (final int b, final int c)
WB_Mesh getHex (final int level)
List< WB_Polygon > getHexTriangles (final int level)
Constructor & Destructor Documentation
wblut.geom.WB_TriGrid.WB_TriGrid ()
wblut.geom.WB_TriGrid.WB_TriGrid (final double scale)
Parameters
scale
Member Function Documentation
WB_Mesh wblut.geom.WB_TriGrid.getHex (final int level)
http://www.voidinspace.com/2014/07/project-twa-part-1-generating-a- hexagonal-tile-and-its-triangular-grid/
Parameters
level
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh().
List<WB_Polygon> wblut.geom.WB_TriGrid.getHexTriangles (final int level)
Parameters
level
Returns
References wblut.geom.WB_Point.copy(), and wblut.geom.WB_GeometryFactory2D.createSimplePolygon().
WB_Point wblut.geom.WB_TriGrid.getPoint (final int b, final int c)
Parameters
b
c
Returns
WB_TriGrid wblut.geom.WB_TriGrid.setScale (final double scale)
Parameters
scale
Returns
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_TriGrid.java