HE_Mesh: wblut.geom.WB_IndexedTriangle Class Reference
wblut.geom.WB_IndexedTriangle Class Reference
Public Member Functions
WB_IndexedTriangle (final int i1, final int i2, final int i3, final WB_CoordCollection points)
WB_IndexedTriangle (final int i, final int[] tris, final WB_CoordCollection points)
void cycle ()
int i1 ()
int i2 ()
int i3 ()
Public Member Functions inherited from wblut.geom.WB_Triangle
WB_Triangle (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
void cycle ()
void cycle (int n)
WB_Coord p1 ()
WB_Coord p2 ()
WB_Coord p3 ()
double a ()
double b ()
double c ()
double cosA ()
double cosB ()
double cosC ()
WB_Coord getPoint (final int i)
WB_Point getCenter ()
WB_Triangle apply (final WB_Transform T)
WB_Plane getPlane ()
WB_Map2D getEmbeddedPlane ()
WB_Point getCentroid ()
WB_Point getCircumcenter ()
WB_Point getOrthocenter ()
WB_Point getPointFromTrilinear (final double x, final double y, final double z)
WB_Point getPointFromBarycentric (final double x, final double y, final double z)
double[] getBarycentricCoordinates (final WB_Coord p)
WB_Point getBarycentric (final WB_Coord p)
double getArea ()
WB_AABB getAABB ()
WB_AABB2D getAABB2D ()
double getSignedArea ()
WB_Circle getCircumcircle ()
WB_Circle getIncircle ()
WB_Point getIncenter ()
double minX ()
double minY ()
double minZ ()
double maxX ()
double maxY ()
double maxZ ()
Additional Inherited Members
Protected Member Functions inherited from wblut.geom.WB_Triangle
WB_Triangle ()
void update ()
Detailed Description
Author
FVH
Constructor & Destructor Documentation
wblut.geom.WB_IndexedTriangle.WB_IndexedTriangle (final int i1, final int i2, final int i3, final WB_CoordCollection points)
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_IndexedTriangle.i1(), wblut.geom.WB_IndexedTriangle.i2(), and wblut.geom.WB_IndexedTriangle.i3().
wblut.geom.WB_IndexedTriangle.WB_IndexedTriangle (final int i, final int[] tris, final WB_CoordCollection points)
References wblut.geom.WB_CoordCollection.get().
Member Function Documentation
void wblut.geom.WB_IndexedTriangle.cycle ()
References wblut.geom.WB_IndexedTriangle.i1(), wblut.geom.WB_IndexedTriangle.i2(), wblut.geom.WB_IndexedTriangle.i3(), wblut.geom.WB_Triangle.p1(), wblut.geom.WB_Triangle.p2(), wblut.geom.WB_Triangle.p3(), and wblut.geom.WB_Triangle.update().
int wblut.geom.WB_IndexedTriangle.i1 ()
Returns
int wblut.geom.WB_IndexedTriangle.i2 ()
Returns
int wblut.geom.WB_IndexedTriangle.i3 ()
Returns
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_IndexedTriangle.java