HE_Mesh: wblut.hemesh.HEM_Inflate Class Reference
wblut.hemesh.HEM_Inflate Class Reference
Public Member Functions
HEM_Inflate ()
HEM_Inflate setAutoRescale (final boolean b)
HEM_Inflate setIterations (final int r)
HEM_Inflate setRadius (final double r)
HEM_Inflate setFactor (final double f)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
boolean autoRescale
int iter
double radius
double factor
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_Inflate.HEM_Inflate ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Inflate.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.add(), wblut.geom.WB_Point.add(), wblut.geom.WB_Vector.addSelf(), wblut.hemesh.HE_Mesh.fitInAABBConstrained(), wblut.hemesh.HE_Mesh.getAABB(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.getRange(), wblut.hemesh.HEM_Inflate.iter, wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Vector.subToVector3D(), and wblut.hemesh.HE_Mesh.vItr().
HE_Mesh wblut.hemesh.HEM_Inflate.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.add(), wblut.geom.WB_Point.add(), wblut.geom.WB_Vector.addSelf(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Mesh.fitInAABBConstrained(), wblut.hemesh.HE_Mesh.getAABB(), wblut.hemesh.HE_Selection.getNumberOfVertices(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.getRange(), wblut.hemesh.HEM_Inflate.iter, wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Vector.subToVector3D(), wblut.hemesh.HE_Selection.vItr(), and wblut.hemesh.HE_Mesh.vItr().
HEM_Inflate wblut.hemesh.HEM_Inflate.setAutoRescale (final boolean b)
Parameters
b
Returns
HEM_Inflate wblut.hemesh.HEM_Inflate.setFactor (final double f)
Parameters
f
Returns
HEM_Inflate wblut.hemesh.HEM_Inflate.setIterations (final int r)
Parameters
r
Returns
HEM_Inflate wblut.hemesh.HEM_Inflate.setRadius (final double r)
Parameters
r
Returns
Member Data Documentation
boolean wblut.hemesh.HEM_Inflate.autoRescale private
double wblut.hemesh.HEM_Inflate.factor private
int wblut.hemesh.HEM_Inflate.iter private
double wblut.hemesh.HEM_Inflate.radius private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Inflate.java