HE_Mesh: wblut.geom.WB_Mesh Class Reference
wblut.geom.WB_Mesh Class Reference
Classes
class FaceNormalRunner
class TriangulateRunner
Public Member Functions
WB_Mesh get ()
int[][] getFacesAsInt ()
int[][] getEdgesAsInt ()
WB_Plane getPlane (final int id, final double d)
WB_Plane getPlane (final int id)
List< WB_Plane > getPlanes (final double d)
List< WB_Plane > getPlanes ()
WB_Polygon getPolygon (final int id)
List< WB_Polygon > getPolygons ()
WB_Point getCenter ()
WB_AABB getAABB ()
WB_Mesh isoFitInAABB (final WB_AABB AABB)
WB_Mesh triangulate ()
WB_Mesh triangulateForceST ()
WB_Mesh triangulateForceMT ()
WB_Vector getFaceNormal (final int id)
WB_Point getFaceCenter (final int id)
WB_Vector getVertexNormal (final int i)
int getNumberOfFaces ()
int getNumberOfVertices ()
WB_Coord getVertex (final int i)
WB_CoordCollection getPoints ()
int[] vfNeighbors (final int i)
int[] getFace (final int i)
WB_Mesh apply (final WB_Transform WB_Point)
double k1 (final int i)
double k2 (final int i)
double K (final int i)
double k1min ()
double k2min ()
double Kmin ()
double k1max ()
double k2max ()
double Kmax ()
WB_Vector k1dir (final int i)
WB_Vector k2dir (final int i)
double[] DCurv (final int i)
double DCurvInvariant (final int i)
int[] getTriangles ()
Protected Member Functions
WB_Mesh ()
WB_Mesh (final WB_Mesh mesh)
WB_Mesh (final Collection<?extends WB_Coord > points, final int[][] faces)
WB_Mesh (final WB_Coord[] points, final int[][] faces)
Protected Attributes
int[][] faces
List< WB_Coord > vertices
WB_AABB aabb
Private Member Functions
List< WB_Coord > createVertices (final Collection<?extends WB_Coord > points)
List< WB_Coord > createVertices (final WB_Coord[] points)
WB_Mesh triangulateST ()
WB_Mesh triangulateMT ()
int[] triangulateMTIndices ()
void updatevfNeighbors ()
void updateVertexNormals ()
void updateVertexNormalsAngle ()
void updateFaceNormalsST ()
void updateFaceNormalsMT ()
void updateCurvatures ()
void updateDCurvatures ()
Private Attributes
WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.geom.WB_Mesh.WB_Mesh () protected
wblut.geom.WB_Mesh.WB_Mesh (final WB_Mesh mesh) protected
Parameters
mesh
References wblut.geom.WB_Mesh.createVertices(), wblut.geom.WB_Mesh.faces, and wblut.geom.WB_Mesh.vertices.
wblut.geom.WB_Mesh.WB_Mesh (final Collection<?extends WB_Coord > points, final int faces[][]) protected
Parameters
points
faces
References wblut.geom.WB_Mesh.createVertices().
wblut.geom.WB_Mesh.WB_Mesh (final WB_Coord[] points, final int faces[][]) protected
Parameters
points
faces
References wblut.geom.WB_Mesh.createVertices().
Member Function Documentation
WB_Mesh wblut.geom.WB_Mesh.apply (final WB_Transform WB_Point)
References wblut.geom.WB_Transform.applyAsPointInto(), wblut.geom.WB_GeometryFactory3D.createMesh(), and wblut.geom.WB_GeometryFactory3D.createPoint().
List<WB_Coord> wblut.geom.WB_Mesh.createVertices (final Collection<?extends WB_Coord > points) private
Parameters
points
Returns
References wblut.geom.WB_Mesh.vertices.
List<WB_Coord> wblut.geom.WB_Mesh.createVertices (final WB_Coord[] points) private
Parameters
points
Returns
References wblut.geom.WB_Mesh.vertices.
double [] wblut.geom.WB_Mesh.DCurv (final int i)
Parameters
i
Returns
References wblut.geom.WB_Mesh.updateDCurvatures().
double wblut.geom.WB_Mesh.DCurvInvariant (final int i)
Parameters
i
Returns
References wblut.geom.WB_Mesh.updateDCurvatures().
WB_Mesh wblut.geom.WB_Mesh.get ()
Returns
References wblut.geom.WB_Mesh.WB_Mesh().
WB_AABB wblut.geom.WB_Mesh.getAABB ()
WB_Point wblut.geom.WB_Mesh.getCenter ()
References wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_MutableCoordinate.xd().
int [][] wblut.geom.WB_Mesh.getEdgesAsInt ()
int [] wblut.geom.WB_Mesh.getFace (final int i)
Parameters
i
Returns
WB_Point wblut.geom.WB_Mesh.getFaceCenter (final int id)
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_Point.divSelf(), and wblut.geom.WB_Mesh.getVertex().
WB_Vector wblut.geom.WB_Mesh.getFaceNormal (final int id)
References wblut.geom.WB_Mesh.updateFaceNormalsST().
int [][] wblut.geom.WB_Mesh.getFacesAsInt ()
References wblut.geom.WB_Mesh.faces.
int wblut.geom.WB_Mesh.getNumberOfFaces ()
int wblut.geom.WB_Mesh.getNumberOfVertices ()
WB_Plane wblut.geom.WB_Mesh.getPlane (final int id, final double d)
Parameters
id
d
Returns
References wblut.geom.WB_Point.addMul(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_GeometryFactory3D.createPlane(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVector(), wblut.geom.WB_Point.divSelf(), wblut.geom.WB_Mesh.getFace(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Plane wblut.geom.WB_Mesh.getPlane (final int id)
Parameters
id
Returns
References wblut.geom.WB_Mesh.getPlane().
List<WB_Plane> wblut.geom.WB_Mesh.getPlanes (final double d)
Parameters
d
Returns
References wblut.geom.WB_Mesh.getPlane().
List<WB_Plane> wblut.geom.WB_Mesh.getPlanes ()
Returns
WB_CoordCollection wblut.geom.WB_Mesh.getPoints ()
Implements wblut.geom.WB_TriangleGenerator.
References wblut.geom.WB_CoordCollection.getCollection().
WB_Polygon wblut.geom.WB_Mesh.getPolygon (final int id)
Parameters
id
Returns
References wblut.geom.WB_GeometryFactory2D.createSimplePolygon(), and wblut.geom.WB_Mesh.getVertex().
List<WB_Polygon> wblut.geom.WB_Mesh.getPolygons ()
Returns
References wblut.geom.WB_Mesh.getPolygon().
int [] wblut.geom.WB_Mesh.getTriangles ()
Implements wblut.geom.WB_TriangleGenerator.
References wblut.geom.WB_Mesh.triangulateMTIndices().
WB_Coord wblut.geom.WB_Mesh.getVertex (final int i)
WB_Vector wblut.geom.WB_Mesh.getVertexNormal (final int i)
References wblut.geom.WB_Mesh.updateVertexNormals().
WB_Mesh wblut.geom.WB_Mesh.isoFitInAABB (final WB_AABB AABB)
Parameters
AABB
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_Mesh.getAABB(), wblut.geom.WB_AABB.getCenterX(), wblut.geom.WB_AABB.getCenterY(), wblut.geom.WB_AABB.getCenterZ(), wblut.geom.WB_AABB.getDepth(), wblut.geom.WB_AABB.getHeight(), wblut.geom.WB_AABB.getWidth(), and wblut.geom.WB_Point.mulSelf().
double wblut.geom.WB_Mesh.K (final int i)
Parameters
i
Returns
References wblut.geom.WB_Mesh.updateCurvatures().
double wblut.geom.WB_Mesh.k1 (final int i)
Parameters
i
Returns
References wblut.geom.WB_Mesh.updateCurvatures().
WB_Vector wblut.geom.WB_Mesh.k1dir (final int i)
Parameters
i
Returns
References wblut.geom.WB_Mesh.updateCurvatures().
double wblut.geom.WB_Mesh.k1max ()
Returns
References wblut.geom.WB_Mesh.updateCurvatures().
double wblut.geom.WB_Mesh.k1min ()
Returns
References wblut.geom.WB_Mesh.updateCurvatures().
double wblut.geom.WB_Mesh.k2 (final int i)
Parameters
i
Returns
References wblut.geom.WB_Mesh.updateCurvatures().
WB_Vector wblut.geom.WB_Mesh.k2dir (final int i)
Parameters
i
Returns
References wblut.geom.WB_Mesh.updateCurvatures().
double wblut.geom.WB_Mesh.k2max ()
Returns
References wblut.geom.WB_Mesh.updateCurvatures().
double wblut.geom.WB_Mesh.k2min ()
Returns
References wblut.geom.WB_Mesh.updateCurvatures().
double wblut.geom.WB_Mesh.Kmax ()
Returns
References wblut.geom.WB_Mesh.updateCurvatures().
double wblut.geom.WB_Mesh.Kmin ()
Returns
References wblut.geom.WB_Mesh.updateCurvatures().
WB_Mesh wblut.geom.WB_Mesh.triangulate ()
Returns
References wblut.geom.WB_Mesh.triangulateMT().
WB_Mesh wblut.geom.WB_Mesh.triangulateForceMT ()
Returns
References wblut.geom.WB_Mesh.triangulateMT().
WB_Mesh wblut.geom.WB_Mesh.triangulateForceST ()
Returns
References wblut.geom.WB_Mesh.triangulateST().
WB_Mesh wblut.geom.WB_Mesh.triangulateMT () private
Returns
int [] wblut.geom.WB_Mesh.triangulateMTIndices () private
WB_Mesh wblut.geom.WB_Mesh.triangulateST () private
Returns
References wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane(), wblut.geom.WB_Mesh.getPlane(), wblut.geom.WB_Mesh.getTriangles(), and wblut.geom.WB_PolygonTriangulatorJTS.triangulatePolygon2D().
void wblut.geom.WB_Mesh.updateCurvatures () private
References wblut.geom.WB_GeometryFactory3D.createTriMesh(), and wblut.geom.WB_TriangleMesh.updateCurvatures().
void wblut.geom.WB_Mesh.updateDCurvatures () private
References wblut.geom.WB_GeometryFactory3D.createTriMesh(), and wblut.geom.WB_TriangleMesh.updateDCurvatures().
void wblut.geom.WB_Mesh.updateFaceNormalsMT () private
void wblut.geom.WB_Mesh.updateFaceNormalsST () private
References wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_GeometryFactory3D.createVector(), wblut.geom.WB_Mesh.getVertex(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_Mesh.updateVertexNormals () private
References wblut.geom.WB_Mesh.updateVertexNormalsAngle().
void wblut.geom.WB_Mesh.updateVertexNormalsAngle () private
References wblut.geom.WB_Vector.addMulSelf(), wblut.geom.WB_GeometryFactory3D.createNormalizedVectorFromTo(), wblut.geom.WB_GeometryFactory3D.createVector(), wblut.geom.WB_Vector.getAngleNorm(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Mesh.updateFaceNormalsMT().
void wblut.geom.WB_Mesh.updatevfNeighbors () private
int [] wblut.geom.WB_Mesh.vfNeighbors (final int i)
Parameters
i
Returns
References wblut.geom.WB_Mesh.updatevfNeighbors().
Member Data Documentation
WB_AABB wblut.geom.WB_Mesh.aabb protected
int [][] wblut.geom.WB_Mesh.faces protected
WB_GeometryFactory wblut.geom.WB_Mesh.geometryfactory = new WB_GeometryFactory() private
List<WB_Coord> wblut.geom.WB_Mesh.vertices protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Mesh.java