HE_Mesh: wblut.geom.WB_Quadtree< V > Class Template Reference
wblut.geom.WB_Quadtree< V > Class Template Reference
Classes
class WB_QuadtreeEntry
Public Member Functions
WB_Quadtree (final WB_Coord center, final double size)
void addPoint (final WB_Coord p, final V value)
void clear ()
int getLevel ()
WB_Quadtree< V > getNode (final WB_Coord p)
double getMinNodeSize ()
int getNumNodes ()
WB_Coord getCenter ()
WB_Quadtree< V > getParent ()
int getNumberOfPoints ()
List< WB_Quadtree< V > > getNodes ()
double getSize ()
boolean remove (final WB_Coord p)
void removeAll (final Collection< WB_Coord > points)
void setMinNodeSize (final double minNodeSize)
void setAutoPrune (final boolean state)
WB_AABB2D getBox ()
List< WB_QuadtreeEntry< V > > getEntries ()
List< WB_QuadtreeEntry< V > > getEntriesInRange (final WB_AABB2D AABB)
List< WB_QuadtreeEntry< V > > getEntriesInRange (final WB_Circle circle)
List< WB_QuadtreeEntry< V > > getEntriesInRange (final WB_Coord center, final double radius)
List< WB_Coord > getPoints ()
List< WB_Coord > getPointsInRange (final WB_AABB2D AABB)
List< WB_Coord > getPointsInRange (final WB_Circle circle)
List< WB_Coord > getPointsInRange (final WB_Coord center, final double radius)
List< V > getValues ()
List< V > getValuesInRange (final WB_AABB2D AABB)
List< V > getValuesInRange (final WB_Circle circle)
List< V > getValuesInRange (final WB_Coord center, final double radius)
Protected Member Functions
final int getQuadrant (final WB_Coord p)
Protected Attributes
WB_AABB2D box
WB_Coord extent
WB_Coord min
double minNodeSize = 4.0
WB_Quadtree< V > parent
WB_Quadtree< V >[] nodes
int numNodes
List< WB_QuadtreeEntry< V > > entries
double size
WB_Coord center
Private Member Functions
WB_Quadtree (final WB_Quadtree< V > p, final WB_Coord center, final double size)
void prune ()
Private Attributes
int level = 0
boolean autoPrune = false
Constructor & Destructor Documentation
wblut.geom.WB_Quadtree< V >.WB_Quadtree (final WB_Quadtree< V > p, final WB_Coord center, final double size) private
References wblut.geom.WB_Quadtree< V >.size, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
wblut.geom.WB_Quadtree< V >.WB_Quadtree (final WB_Coord center, final double size)
References wblut.geom.WB_Quadtree< V >.size, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
Member Function Documentation
void wblut.geom.WB_Quadtree< V >.addPoint (final WB_Coord p, final V value)
References wblut.geom.WB_Point.add(), wblut.geom.WB_Quadtree< V >.addPoint(), wblut.geom.WB_AABB2D.contains(), and wblut.geom.WB_Quadtree< V >.getQuadrant().
void wblut.geom.WB_Quadtree< V >.clear ()
WB_AABB2D wblut.geom.WB_Quadtree< V >.getBox ()
References wblut.geom.WB_Quadtree< V >.box.
WB_Coord wblut.geom.WB_Quadtree< V >.getCenter ()
References wblut.geom.WB_Quadtree< V >.center.
List<WB_QuadtreeEntry<V> > wblut.geom.WB_Quadtree< V >.getEntries ()
References wblut.geom.WB_Quadtree< V >.getEntries().
List<WB_QuadtreeEntry<V> > wblut.geom.WB_Quadtree< V >.getEntriesInRange (final WB_AABB2D AABB)
References wblut.geom.WB_AABB2D.contains(), wblut.geom.WB_Quadtree< V >.getEntriesInRange(), and wblut.geom.WB_AABB2D.intersects().
List<WB_QuadtreeEntry<V> > wblut.geom.WB_Quadtree< V >.getEntriesInRange (final WB_Circle circle)
References wblut.geom.WB_Circle.contains(), wblut.geom.WB_Quadtree< V >.getEntriesInRange(), and wblut.geom.WB_AABB2D.intersects().
List<WB_QuadtreeEntry<V> > wblut.geom.WB_Quadtree< V >.getEntriesInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_Quadtree< V >.getEntriesInRange().
int wblut.geom.WB_Quadtree< V >.getLevel ()
References wblut.geom.WB_Quadtree< V >.level.
double wblut.geom.WB_Quadtree< V >.getMinNodeSize ()
References wblut.geom.WB_Quadtree< V >.minNodeSize.
WB_Quadtree<V> wblut.geom.WB_Quadtree< V >.getNode (final WB_Coord p)
References wblut.geom.WB_AABB2D.contains(), wblut.geom.WB_Quadtree< V >.getNode(), and wblut.geom.WB_Quadtree< V >.getQuadrant().
List<WB_Quadtree<V> > wblut.geom.WB_Quadtree< V >.getNodes ()
int wblut.geom.WB_Quadtree< V >.getNumberOfPoints ()
int wblut.geom.WB_Quadtree< V >.getNumNodes ()
References wblut.geom.WB_Quadtree< V >.numNodes.
WB_Quadtree<V> wblut.geom.WB_Quadtree< V >.getParent ()
References wblut.geom.WB_Quadtree< V >.parent.
List<WB_Coord> wblut.geom.WB_Quadtree< V >.getPoints ()
References wblut.geom.WB_Quadtree< V >.getPoints().
List<WB_Coord> wblut.geom.WB_Quadtree< V >.getPointsInRange (final WB_AABB2D AABB)
References wblut.geom.WB_Quadtree< V >.getEntriesInRange().
List<WB_Coord> wblut.geom.WB_Quadtree< V >.getPointsInRange (final WB_Circle circle)
References wblut.geom.WB_Quadtree< V >.getEntriesInRange().
List<WB_Coord> wblut.geom.WB_Quadtree< V >.getPointsInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_Quadtree< V >.getPointsInRange().
final int wblut.geom.WB_Quadtree< V >.getQuadrant (final WB_Coord p) protected
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Quadtree< V >.getSize ()
References wblut.geom.WB_Quadtree< V >.size.
List<V> wblut.geom.WB_Quadtree< V >.getValues ()
References wblut.geom.WB_Quadtree< V >.getEntries().
List<V> wblut.geom.WB_Quadtree< V >.getValuesInRange (final WB_AABB2D AABB)
References wblut.geom.WB_Quadtree< V >.getEntriesInRange().
List<V> wblut.geom.WB_Quadtree< V >.getValuesInRange (final WB_Circle circle)
References wblut.geom.WB_Quadtree< V >.getEntriesInRange().
List<V> wblut.geom.WB_Quadtree< V >.getValuesInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_Quadtree< V >.getValuesInRange().
void wblut.geom.WB_Quadtree< V >.prune () private
References wblut.geom.WB_Quadtree< V >.prune().
boolean wblut.geom.WB_Quadtree< V >.remove (final WB_Coord p)
References wblut.geom.WB_Quadtree< V >.WB_QuadtreeEntry< V >.coord, wblut.geom.WB_Quadtree< V >.entries, wblut.geom.WB_Quadtree< V >.getNode(), and wblut.geom.WB_Quadtree< V >.prune().
void wblut.geom.WB_Quadtree< V >.removeAll (final Collection< WB_Coord > points)
void wblut.geom.WB_Quadtree< V >.setAutoPrune (final boolean state)
void wblut.geom.WB_Quadtree< V >.setMinNodeSize (final double minNodeSize)
Member Data Documentation
boolean wblut.geom.WB_Quadtree< V >.autoPrune = false private
WB_AABB2D wblut.geom.WB_Quadtree< V >.box protected
WB_Coord wblut.geom.WB_Quadtree< V >.center protected
List<WB_QuadtreeEntry<V> > wblut.geom.WB_Quadtree< V >.entries protected
WB_Coord wblut.geom.WB_Quadtree< V >.extent protected
int wblut.geom.WB_Quadtree< V >.level = 0 private
WB_Coord wblut.geom.WB_Quadtree< V >.min protected
double wblut.geom.WB_Quadtree< V >.minNodeSize = 4.0 protected
WB_Quadtree<V> [] wblut.geom.WB_Quadtree< V >.nodes protected
int wblut.geom.WB_Quadtree< V >.numNodes protected
WB_Quadtree<V> wblut.geom.WB_Quadtree< V >.parent protected
double wblut.geom.WB_Quadtree< V >.size protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Quadtree.java