HE_Mesh: wblut.nurbs.WB_BSplineSurface Class Reference
wblut.nurbs.WB_BSplineSurface Class Reference
Public Member Functions
WB_BSplineSurface ()
WB_BSplineSurface (final WB_Coord[][] controlPoints, final WB_NurbsKnot uknot, final WB_NurbsKnot vknot)
WB_BSplineSurface (final WB_PointHomogeneous[][] controlPoints, final WB_NurbsKnot uknot, final WB_NurbsKnot vknot)
WB_BSplineSurface (final WB_Coord[][] controlPoints, final int udegree, final int vdegree)
WB_BSplineSurface (final WB_Coord point00, final WB_Coord point10, final WB_Coord point01, final WB_Coord point11)
WB_Point surfacePoint (final double u, final double v)
HE_Mesh toControlHemesh ()
WB_BSplineSurface insertUKnot (final double u)
WB_BSplineSurface insertUKnotMax (final double u)
WB_BSplineSurface insertUKnot (final double u, final int r)
WB_BSplineSurface insertVKnot (final double v)
WB_BSplineSurface insertVKnotMax (final double v)
WB_BSplineSurface insertVKnot (final double v, final int r)
WB_BSpline isoCurveU (final double u)
WB_BSpline isoCurveV (final double v)
WB_Coord[][] points ()
int p ()
int n ()
int q ()
int m ()
WB_NurbsKnot uknot ()
WB_NurbsKnot vknot ()
WB_BSplineSurface[] splitU (final double u)
WB_BSplineSurface[] splitV (final double v)
WB_BSplineSurface[] split (final double u, final double v)
double loweru ()
double upperu ()
double lowerv ()
double upperv ()
Public Member Functions inherited from wblut.geom.WB_Surface
WB_Point surfacePoint (double u, double v)
Protected Attributes
WB_NurbsKnot uknot
WB_NurbsKnot vknot
WB_Coord[][] points
int p
int n
int q
int m
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.nurbs.WB_BSplineSurface.WB_BSplineSurface ()
wblut.nurbs.WB_BSplineSurface.WB_BSplineSurface (final WB_Coord controlPoints[][], final WB_NurbsKnot uknot, final WB_NurbsKnot vknot)
Parameters
controlPoints
uknot
vknot
References wblut.nurbs.WB_NurbsKnot.n, wblut.nurbs.WB_NurbsKnot.p(), wblut.nurbs.WB_BSplineSurface.uknot(), and wblut.nurbs.WB_BSplineSurface.vknot().
wblut.nurbs.WB_BSplineSurface.WB_BSplineSurface (final WB_PointHomogeneous controlPoints[][], final WB_NurbsKnot uknot, final WB_NurbsKnot vknot)
Parameters
controlPoints
uknot
vknot
References wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_NurbsKnot.n, wblut.nurbs.WB_BSplineSurface.n(), wblut.nurbs.WB_NurbsKnot.p(), wblut.geom.WB_PointHomogeneous.project(), wblut.nurbs.WB_BSplineSurface.uknot(), and wblut.nurbs.WB_BSplineSurface.vknot().
wblut.nurbs.WB_BSplineSurface.WB_BSplineSurface (final WB_Coord controlPoints[][], final int udegree, final int vdegree)
Parameters
controlPoints
udegree
vdegree
References wblut.nurbs.WB_NurbsKnot.n, and wblut.nurbs.WB_NurbsKnot.p().
wblut.nurbs.WB_BSplineSurface.WB_BSplineSurface (final WB_Coord point00, final WB_Coord point10, final WB_Coord point01, final WB_Coord point11)
Parameters
point00
point10
point01
point11
References wblut.nurbs.WB_NurbsKnot.n, and wblut.nurbs.WB_NurbsKnot.p().
Member Function Documentation
WB_BSplineSurface wblut.nurbs.WB_BSplineSurface.insertUKnot (final double u)
Parameters
u
Returns
WB_BSplineSurface wblut.nurbs.WB_BSplineSurface.insertUKnot (final double u, final int r)
Parameters
u
r
Returns
References wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_NurbsKnot.multiplicity(), wblut.nurbs.WB_BSplineSurface.n(), wblut.nurbs.WB_BSplineSurface.p(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_NurbsKnot.value(), and wblut.nurbs.WB_BSplineSurface.WB_BSplineSurface().
WB_BSplineSurface wblut.nurbs.WB_BSplineSurface.insertUKnotMax (final double u)
Parameters
u
Returns
References wblut.nurbs.WB_BSplineSurface.insertUKnot(), and wblut.nurbs.WB_NurbsKnot.multiplicity().
WB_BSplineSurface wblut.nurbs.WB_BSplineSurface.insertVKnot (final double v)
Parameters
v
Returns
WB_BSplineSurface wblut.nurbs.WB_BSplineSurface.insertVKnot (final double v, final int r)
Parameters
v
r
Returns
References wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_NurbsKnot.multiplicity(), wblut.nurbs.WB_BSplineSurface.n(), wblut.nurbs.WB_BSplineSurface.q(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_NurbsKnot.value(), and wblut.nurbs.WB_BSplineSurface.WB_BSplineSurface().
WB_BSplineSurface wblut.nurbs.WB_BSplineSurface.insertVKnotMax (final double v)
Parameters
v
Returns
References wblut.nurbs.WB_BSplineSurface.insertVKnot(), and wblut.nurbs.WB_NurbsKnot.multiplicity().
WB_BSpline wblut.nurbs.WB_BSplineSurface.isoCurveU (final double u)
Parameters
u
Returns
References wblut.geom.WB_Point.addSelf(), wblut.nurbs.WB_NurbsKnot.basisFunctions(), wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_BSplineSurface.p(), wblut.nurbs.WB_NurbsKnot.span(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_BSpline wblut.nurbs.WB_BSplineSurface.isoCurveV (final double v)
Parameters
v
Returns
References wblut.geom.WB_Point.addSelf(), wblut.nurbs.WB_NurbsKnot.basisFunctions(), wblut.nurbs.WB_BSplineSurface.n(), wblut.nurbs.WB_BSplineSurface.q(), wblut.nurbs.WB_NurbsKnot.span(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.nurbs.WB_BSplineSurface.loweru ()
Get the lower end of the u parameter range.
Returns
u
Implements wblut.geom.WB_Surface.
References wblut.nurbs.WB_NurbsKnot.value().
double wblut.nurbs.WB_BSplineSurface.lowerv ()
Get the lower end of the v parameter range.
Returns
v
Implements wblut.geom.WB_Surface.
References wblut.nurbs.WB_NurbsKnot.value().
int wblut.nurbs.WB_BSplineSurface.m ()
Returns
int wblut.nurbs.WB_BSplineSurface.n ()
Returns
int wblut.nurbs.WB_BSplineSurface.p ()
Returns
WB_Coord [][] wblut.nurbs.WB_BSplineSurface.points ()
Returns
int wblut.nurbs.WB_BSplineSurface.q ()
Returns
WB_BSplineSurface [] wblut.nurbs.WB_BSplineSurface.split (final double u, final double v)
Parameters
u
v
Returns
References wblut.nurbs.WB_BSplineSurface.splitU(), and wblut.nurbs.WB_BSplineSurface.splitV().
WB_BSplineSurface [] wblut.nurbs.WB_BSplineSurface.splitU (final double u)
Parameters
u
Returns
References wblut.nurbs.WB_BSplineSurface.insertUKnotMax(), wblut.nurbs.WB_NurbsKnot.m, wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_NurbsKnot.normalize(), wblut.nurbs.WB_BSplineSurface.p(), wblut.nurbs.WB_BSplineSurface.points, wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_BSplineSurface.uknot, wblut.nurbs.WB_NurbsKnot.value(), and wblut.nurbs.WB_BSplineSurface.WB_BSplineSurface().
WB_BSplineSurface [] wblut.nurbs.WB_BSplineSurface.splitV (final double v)
Parameters
v
Returns
References wblut.nurbs.WB_BSplineSurface.insertVKnotMax(), wblut.nurbs.WB_NurbsKnot.m, wblut.nurbs.WB_BSplineSurface.n(), wblut.nurbs.WB_NurbsKnot.normalize(), wblut.nurbs.WB_BSplineSurface.points, wblut.nurbs.WB_BSplineSurface.q(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_NurbsKnot.value(), wblut.nurbs.WB_BSplineSurface.vknot, and wblut.nurbs.WB_BSplineSurface.WB_BSplineSurface().
WB_Point wblut.nurbs.WB_BSplineSurface.surfacePoint (final double u, final double v)
References wblut.geom.WB_Point.addSelf(), wblut.nurbs.WB_NurbsKnot.basisFunctions(), wblut.geom.WB_Point.mulSelf(), wblut.nurbs.WB_BSplineSurface.p(), wblut.nurbs.WB_BSplineSurface.q(), and wblut.nurbs.WB_NurbsKnot.span().
HE_Mesh wblut.nurbs.WB_BSplineSurface.toControlHemesh ()
Returns
References wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_BSplineSurface.n(), wblut.hemesh.HEC_FromFacelist.setFaces(), and wblut.hemesh.HEC_FromFacelist.setVertices().
WB_NurbsKnot wblut.nurbs.WB_BSplineSurface.uknot ()
Returns
double wblut.nurbs.WB_BSplineSurface.upperu ()
Get the upper end of the u parameter range.
Returns
u
Implements wblut.geom.WB_Surface.
References wblut.nurbs.WB_NurbsKnot.m, and wblut.nurbs.WB_NurbsKnot.value().
double wblut.nurbs.WB_BSplineSurface.upperv ()
Get the upper end of the v parameter range.
Returns
v
Implements wblut.geom.WB_Surface.
References wblut.nurbs.WB_NurbsKnot.m, and wblut.nurbs.WB_NurbsKnot.value().
WB_NurbsKnot wblut.nurbs.WB_BSplineSurface.vknot ()
Returns
Member Data Documentation
WB_GeometryFactory wblut.nurbs.WB_BSplineSurface.gf = new WB_GeometryFactory() static private
int wblut.nurbs.WB_BSplineSurface.m protected
int wblut.nurbs.WB_BSplineSurface.n protected
int wblut.nurbs.WB_BSplineSurface.p protected
WB_Coord [][] wblut.nurbs.WB_BSplineSurface.points protected
int wblut.nurbs.WB_BSplineSurface.q protected
WB_NurbsKnot wblut.nurbs.WB_BSplineSurface.uknot protected
WB_NurbsKnot wblut.nurbs.WB_BSplineSurface.vknot protected
The documentation for this class was generated from the following file:
src/nurbs/wblut/nurbs/WB_BSplineSurface.java