HE_Mesh: wblut.hemesh.HEM_SphericalInversion Class Reference
wblut.hemesh.HEM_SphericalInversion Class Reference
Public Member Functions
HEM_SphericalInversion ()
HEM_SphericalInversion (final double x, final double y, final double z, final double r)
HEM_SphericalInversion setCenter (final WB_Coord c)
HEM_SphericalInversion setCenter (final double x, final double y, final double z)
HEM_SphericalInversion setRadius (final double r)
HEM_SphericalInversion setCutoff (final double cutoff)
HEM_SphericalInversion setLinear (final boolean b)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_Point center
double r
double r2
double icutoff
boolean linear
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_SphericalInversion.HEM_SphericalInversion ()
wblut.hemesh.HEM_SphericalInversion.HEM_SphericalInversion (final double x, final double y, final double z, final double r)
References wblut.hemesh.HEM_SphericalInversion.r.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_SphericalInversion.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Vector.normalizeSelf(), wblut.hemesh.HE_Vertex.set(), wblut.geom.WB_Point.subToVector3D(), wblut.geom.WB_Vector.subToVector3D(), and wblut.hemesh.HE_Mesh.vItr().
HE_Mesh wblut.hemesh.HEM_SphericalInversion.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Vector.getLength(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.normalizeSelf(), wblut.hemesh.HE_Vertex.set(), wblut.geom.WB_Vector.subToVector3D(), and wblut.hemesh.HE_Selection.vItr().
HEM_SphericalInversion wblut.hemesh.HEM_SphericalInversion.setCenter (final WB_Coord c)
Parameters
c
Returns
HEM_SphericalInversion wblut.hemesh.HEM_SphericalInversion.setCenter (final double x, final double y, final double z)
Parameters
x
y
z
Returns
HEM_SphericalInversion wblut.hemesh.HEM_SphericalInversion.setCutoff (final double cutoff)
Parameters
cutoff
Returns
HEM_SphericalInversion wblut.hemesh.HEM_SphericalInversion.setLinear (final boolean b)
Parameters
b
Returns
HEM_SphericalInversion wblut.hemesh.HEM_SphericalInversion.setRadius (final double r)
Parameters
r
Returns
References wblut.hemesh.HEM_SphericalInversion.r.
Member Data Documentation
WB_Point wblut.hemesh.HEM_SphericalInversion.center private
double wblut.hemesh.HEM_SphericalInversion.icutoff private
boolean wblut.hemesh.HEM_SphericalInversion.linear private
double wblut.hemesh.HEM_SphericalInversion.r private
double wblut.hemesh.HEM_SphericalInversion.r2 private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_SphericalInversion.java