HE_Mesh: wblut.hemesh.HEC_FromBinaryHemeshFile Class Reference
wblut.hemesh.HEC_FromBinaryHemeshFile Class Reference
Public Member Functions
HEC_FromBinaryHemeshFile ()
HEC_FromBinaryHemeshFile (final String path)
HEC_FromBinaryHemeshFile setPath (final String path)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Attributes
String path
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Constructor & Destructor Documentation
wblut.hemesh.HEC_FromBinaryHemeshFile.HEC_FromBinaryHemeshFile ()
wblut.hemesh.HEC_FromBinaryHemeshFile.HEC_FromBinaryHemeshFile (final String path)
Parameters
path
References wblut.hemesh.HEC_FromBinaryHemeshFile.path.
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_FromBinaryHemeshFile.createBase () protected
References wblut.hemesh.HE_Mesh.addFaces(), wblut.hemesh.HE_Mesh.addHalfedges(), wblut.hemesh.HE_Mesh.addVertices(), wblut.hemesh.HE_Vertex.set(), wblut.hemesh.HE_MeshElement.setColor(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Face.setTextureId(), wblut.hemesh.HE_Element.setUserLabel(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Vertex.setUVW(), and wblut.hemesh.HE_Mesh.setVertex().
HEC_FromBinaryHemeshFile wblut.hemesh.HEC_FromBinaryHemeshFile.setPath (final String path)
Parameters
path
Returns
References wblut.hemesh.HEC_FromBinaryHemeshFile.path.
Member Data Documentation
String wblut.hemesh.HEC_FromBinaryHemeshFile.path private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_FromBinaryHemeshFile.java