HE_Mesh: wblut.geom.WB_OctreeDouble Class Reference
wblut.geom.WB_OctreeDouble Class Reference
Classes
class WB_OctreeDoubleEntry
Public Member Functions
WB_OctreeDouble (final WB_Coord center, final double size)
void addPoint (final WB_Coord p, final double value)
void clear ()
int getLevel ()
WB_OctreeDouble getNode (final WB_Coord p)
double getMinNodeSize ()
int getNumNodes ()
WB_Coord getCenter ()
WB_OctreeDouble getParent ()
int getNumberOfPoints ()
List< WB_OctreeDouble > getNodes ()
double getSize ()
boolean remove (final WB_Coord p)
void removeAll (final Collection< WB_Coord > points)
void setMinNodeSize (final double minNodeSize)
void setAutoPrune (final boolean state)
WB_AABB getBox ()
List< WB_OctreeDoubleEntry > getEntries ()
List< WB_OctreeDoubleEntry > getEntriesInRange (final WB_AABB AABB)
List< WB_OctreeDoubleEntry > getEntriesInRange (final WB_Sphere sphere)
List< WB_OctreeDoubleEntry > getEntriesInRange (final WB_Coord center, final double radius)
List< WB_Coord > getPoints ()
List< WB_Coord > getPointsInRange (final WB_AABB AABB)
List< WB_Coord > getPointsInRange (final WB_Sphere sphere)
List< WB_Coord > getPointsInRange (final WB_Coord center, final double radius)
double[] getValues ()
double[] getValuesInRange (final WB_AABB AABB)
double[] getValuesInRange (final WB_Sphere sphere)
double[] getValuesInRange (final WB_Coord center, final double radius)
Protected Member Functions
final int getOctant (final WB_Coord p)
Protected Attributes
WB_AABB box
WB_Coord extent
WB_Coord min
double minNodeSize = 4.0
WB_OctreeDouble parent
WB_OctreeDouble[] nodes
int numNodes
List< WB_OctreeDoubleEntry > entries
double size
WB_Coord center
Private Member Functions
WB_OctreeDouble (final WB_OctreeDouble p, final WB_Coord center, final double size)
void prune ()
Private Attributes
int level = 0
boolean autoPrune = false
Constructor & Destructor Documentation
wblut.geom.WB_OctreeDouble.WB_OctreeDouble (final WB_OctreeDouble p, final WB_Coord center, final double size) private
References wblut.geom.WB_OctreeDouble.level, wblut.geom.WB_OctreeDouble.minNodeSize, and wblut.geom.WB_OctreeDouble.size.
wblut.geom.WB_OctreeDouble.WB_OctreeDouble (final WB_Coord center, final double size)
References wblut.geom.WB_OctreeDouble.size.
Member Function Documentation
void wblut.geom.WB_OctreeDouble.addPoint (final WB_Coord p, final double value)
References wblut.geom.WB_Point.add(), wblut.geom.WB_OctreeDouble.addPoint(), wblut.geom.WB_AABB.contains(), wblut.geom.WB_OctreeDouble.getOctant(), and wblut.geom.WB_OctreeDouble.WB_OctreeDouble().
void wblut.geom.WB_OctreeDouble.clear ()
WB_AABB wblut.geom.WB_OctreeDouble.getBox ()
References wblut.geom.WB_OctreeDouble.box.
WB_Coord wblut.geom.WB_OctreeDouble.getCenter ()
References wblut.geom.WB_OctreeDouble.center.
List<WB_OctreeDoubleEntry> wblut.geom.WB_OctreeDouble.getEntries ()
References wblut.geom.WB_OctreeDouble.getEntries().
List<WB_OctreeDoubleEntry> wblut.geom.WB_OctreeDouble.getEntriesInRange (final WB_AABB AABB)
References wblut.geom.WB_AABB.contains(), wblut.geom.WB_OctreeDouble.getEntriesInRange(), and wblut.geom.WB_AABB.intersects().
List<WB_OctreeDoubleEntry> wblut.geom.WB_OctreeDouble.getEntriesInRange (final WB_Sphere sphere)
References wblut.geom.WB_Sphere.contains(), wblut.geom.WB_OctreeDouble.getEntriesInRange(), and wblut.geom.WB_AABB.intersects().
List<WB_OctreeDoubleEntry> wblut.geom.WB_OctreeDouble.getEntriesInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_OctreeDouble.getEntriesInRange().
int wblut.geom.WB_OctreeDouble.getLevel ()
References wblut.geom.WB_OctreeDouble.level.
double wblut.geom.WB_OctreeDouble.getMinNodeSize ()
References wblut.geom.WB_OctreeDouble.minNodeSize.
WB_OctreeDouble wblut.geom.WB_OctreeDouble.getNode (final WB_Coord p)
References wblut.geom.WB_AABB.contains(), wblut.geom.WB_OctreeDouble.getNode(), and wblut.geom.WB_OctreeDouble.getOctant().
List<WB_OctreeDouble> wblut.geom.WB_OctreeDouble.getNodes ()
int wblut.geom.WB_OctreeDouble.getNumberOfPoints ()
int wblut.geom.WB_OctreeDouble.getNumNodes ()
References wblut.geom.WB_OctreeDouble.numNodes.
final int wblut.geom.WB_OctreeDouble.getOctant (final WB_Coord p) protected
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_OctreeDouble wblut.geom.WB_OctreeDouble.getParent ()
References wblut.geom.WB_OctreeDouble.parent.
List<WB_Coord> wblut.geom.WB_OctreeDouble.getPoints ()
References wblut.geom.WB_OctreeDouble.getPoints().
List<WB_Coord> wblut.geom.WB_OctreeDouble.getPointsInRange (final WB_AABB AABB)
References wblut.geom.WB_OctreeDouble.getEntriesInRange().
List<WB_Coord> wblut.geom.WB_OctreeDouble.getPointsInRange (final WB_Sphere sphere)
References wblut.geom.WB_OctreeDouble.getEntriesInRange().
List<WB_Coord> wblut.geom.WB_OctreeDouble.getPointsInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_OctreeDouble.getPointsInRange().
double wblut.geom.WB_OctreeDouble.getSize ()
References wblut.geom.WB_OctreeDouble.size.
double [] wblut.geom.WB_OctreeDouble.getValues ()
References wblut.geom.WB_OctreeDouble.getEntries().
double [] wblut.geom.WB_OctreeDouble.getValuesInRange (final WB_AABB AABB)
References wblut.geom.WB_OctreeDouble.getEntriesInRange().
double [] wblut.geom.WB_OctreeDouble.getValuesInRange (final WB_Sphere sphere)
References wblut.geom.WB_OctreeDouble.getEntriesInRange().
double [] wblut.geom.WB_OctreeDouble.getValuesInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_OctreeDouble.getValuesInRange().
void wblut.geom.WB_OctreeDouble.prune () private
References wblut.geom.WB_OctreeDouble.prune().
boolean wblut.geom.WB_OctreeDouble.remove (final WB_Coord p)
References wblut.geom.WB_OctreeDouble.WB_OctreeDoubleEntry.coord, wblut.geom.WB_OctreeDouble.entries, wblut.geom.WB_OctreeDouble.getNode(), and wblut.geom.WB_OctreeDouble.prune().
void wblut.geom.WB_OctreeDouble.removeAll (final Collection< WB_Coord > points)
void wblut.geom.WB_OctreeDouble.setAutoPrune (final boolean state)
void wblut.geom.WB_OctreeDouble.setMinNodeSize (final double minNodeSize)
Member Data Documentation
boolean wblut.geom.WB_OctreeDouble.autoPrune = false private
WB_AABB wblut.geom.WB_OctreeDouble.box protected
WB_Coord wblut.geom.WB_OctreeDouble.center protected
List<WB_OctreeDoubleEntry> wblut.geom.WB_OctreeDouble.entries protected
WB_Coord wblut.geom.WB_OctreeDouble.extent protected
int wblut.geom.WB_OctreeDouble.level = 0 private
WB_Coord wblut.geom.WB_OctreeDouble.min protected
double wblut.geom.WB_OctreeDouble.minNodeSize = 4.0 protected
WB_OctreeDouble [] wblut.geom.WB_OctreeDouble.nodes protected
int wblut.geom.WB_OctreeDouble.numNodes protected
WB_OctreeDouble wblut.geom.WB_OctreeDouble.parent protected
double wblut.geom.WB_OctreeDouble.size protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_OctreeDouble.java