HE_Mesh: wblut.geom.WB_MeshGraph.WB_GraphVertex Class Reference
wblut.geom.WB_MeshGraph.WB_GraphVertex Class Reference
Public Member Functions
WB_GraphVertex (final int id, final WB_Coord pos)
String toString ()
int compareTo (final WB_GraphVertex other)
void reset ()
Public Attributes
final int index
List< WB_GraphEdge > neighbors
double distanceToSource = Double.POSITIVE_INFINITY
WB_GraphVertex previous
double x
Constructor & Destructor Documentation
wblut.geom.WB_MeshGraph.WB_GraphVertex.WB_GraphVertex (final int id, final WB_Coord pos)
Parameters
id
pos
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
Member Function Documentation
int wblut.geom.WB_MeshGraph.WB_GraphVertex.compareTo (final WB_GraphVertex other)
References wblut.geom.WB_MeshGraph.WB_GraphVertex.distanceToSource.
void wblut.geom.WB_MeshGraph.WB_GraphVertex.reset ()
String wblut.geom.WB_MeshGraph.WB_GraphVertex.toString ()
References wblut.geom.WB_MeshGraph.WB_GraphVertex.index.
Member Data Documentation
double wblut.geom.WB_MeshGraph.WB_GraphVertex.distanceToSource = Double.POSITIVE_INFINITY
final int wblut.geom.WB_MeshGraph.WB_GraphVertex.index
List<WB_GraphEdge> wblut.geom.WB_MeshGraph.WB_GraphVertex.neighbors
WB_GraphVertex wblut.geom.WB_MeshGraph.WB_GraphVertex.previous
double wblut.geom.WB_MeshGraph.WB_GraphVertex.x
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_MeshGraph.java