HE_Mesh: wblut.hemesh.HEM_Bend Class Reference
wblut.hemesh.HEM_Bend Class Reference
Public Member Functions
HEM_Bend ()
HEM_Bend setGroundPlane (final WB_Plane P)
HEM_Bend setGroundPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
HEM_Bend setBendAxis (final WB_Line a)
HEM_Bend setBendAxis (final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
HEM_Bend setAngleFactor (final double f)
HEM_Bend setPosOnly (final boolean b)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_Plane groundPlane
WB_Line bendAxis
double angleFactor
boolean posOnly
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Bend a mesh. Determined by a ground plane, a bend axis and an angle factor.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_Bend.HEM_Bend ()
Instantiates a new HEM_Bend.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Bend.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Line.getDirection(), wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Line.getOrigin(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Point.rotateAboutAxisSelf(), and wblut.hemesh.HE_Mesh.vItr().
HE_Mesh wblut.hemesh.HEM_Bend.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Line.getDirection(), wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Line.getOrigin(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Point.rotateAboutAxisSelf(), and wblut.hemesh.HE_Selection.vItr().
HEM_Bend wblut.hemesh.HEM_Bend.setAngleFactor (final double f)
Set angle factor, ratio of bend angle in degrees to distance to ground plane.
Parameters
f direction
Returns
self
HEM_Bend wblut.hemesh.HEM_Bend.setBendAxis (final WB_Line a)
Set bend axis.
Parameters
a bend axis
Returns
self
HEM_Bend wblut.hemesh.HEM_Bend.setBendAxis (final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
Sets the bend axis.
Parameters
p1x
p1y
p1z
p2x
p2y
p2z
Returns
self
HEM_Bend wblut.hemesh.HEM_Bend.setGroundPlane (final WB_Plane P)
Set ground plane.
Parameters
P ground plane
Returns
self
HEM_Bend wblut.hemesh.HEM_Bend.setGroundPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
Sets the ground plane.
Parameters
ox
oy
oz
nx
ny
nz
Returns
self
HEM_Bend wblut.hemesh.HEM_Bend.setPosOnly (final boolean b)
Positive only? Only apply modifier to positive side of ground plane.
Parameters
b true, false
Returns
self
Member Data Documentation
double wblut.hemesh.HEM_Bend.angleFactor private
Angle factor.
WB_Line wblut.hemesh.HEM_Bend.bendAxis private
Bend axis.
WB_Plane wblut.hemesh.HEM_Bend.groundPlane private
Ground plane.
boolean wblut.hemesh.HEM_Bend.posOnly private
Positive side of plane only?.
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Bend.java