HE_Mesh: wblut.nurbs.WB_RBSpline Class Reference
wblut.nurbs.WB_RBSpline Class Reference
Public Member Functions
WB_RBSpline (final WB_Point[] controlPoints, final WB_NurbsKnot knot)
WB_RBSpline (final WB_Point[] controlPoints, final WB_NurbsKnot knot, final double[] weights)
WB_RBSpline (final WB_PointHomogeneous[] controlPoints, final WB_NurbsKnot knot)
WB_RBSpline (final WB_Point[] controlPoints, final int order)
WB_RBSpline (final WB_PointHomogeneous[] controlPoints, final int order)
WB_RBSpline (final WB_Point[] controlPoints, final int order, final double[] weights)
WB_PointHomogeneous[] wpoints ()
double[] weights ()
WB_Point curvePoint (final double u)
void setWeight (final int i, final double w)
double getWeight (final int i)
void updateHomogeneous ()
WB_RBSpline insertKnot (final double u)
WB_RBSpline insertKnotMax (final double u)
WB_RBSpline insertKnot (final double u, final int r)
WB_RBSpline refineKnot (final WB_NurbsKnot K)
WB_RBSpline[] split (final double u)
WB_RBSpline elevateDegree (final int t)
Public Member Functions inherited from wblut.nurbs.WB_BSpline
WB_BSpline ()
WB_BSpline (final WB_Coord[] controlPoints, final WB_NurbsKnot knot)
WB_BSpline (final WB_PointHomogeneous[] controlPoints, final WB_NurbsKnot knot)
WB_BSpline (final WB_Coord[] controlPoints, final int order)
WB_Point curvePoint (final double u)
WB_Vector curveDirection (final double u)
WB_Vector curveDerivative (final double u)
WB_BSpline insertKnot (final double u)
WB_BSpline insertKnotMax (final double u)
WB_BSpline insertKnot (final double u, final int r)
WB_BSpline refineKnot (final WB_NurbsKnot K)
WB_Coord[] points ()
int p ()
int n ()
WB_NurbsKnot knot ()
WB_BSpline[] split (final double u)
WB_BSpline elevateDegree (final int t)
WB_Coord[][] curveDerivCPoints (final int d, final int r1, final int r2)
WB_Coord[] curveDerivs (final double u, final int d)
WB_Point[] curveDerivsNorm (final double u, final int d)
WB_Vector firstDerivative (final double u)
double getLowerU ()
double getUpperU ()
Public Member Functions inherited from wblut.geom.WB_Curve
WB_Point curvePoint (double u)
WB_Vector curveDirection (double u)
WB_Vector curveDerivative (double u)
Protected Attributes
WB_PointHomogeneous[] wpoints
Protected Attributes inherited from wblut.nurbs.WB_BSpline
WB_NurbsKnot knot
WB_Coord[] points
int p
int n
Private Member Functions
WB_RBSpline refineKnotRestricted (final double[] X)
Private Attributes
final double[] weights
Constructor & Destructor Documentation
wblut.nurbs.WB_RBSpline.WB_RBSpline (final WB_Point[] controlPoints, final WB_NurbsKnot knot)
Parameters
controlPoints
knot
References wblut.nurbs.WB_BSpline.n(), and wblut.nurbs.WB_BSpline.points().
wblut.nurbs.WB_RBSpline.WB_RBSpline (final WB_Point[] controlPoints, final WB_NurbsKnot knot, final double[] weights)
Parameters
controlPoints
knot
weights
References wblut.nurbs.WB_BSpline.n(), wblut.nurbs.WB_BSpline.points(), and wblut.nurbs.WB_RBSpline.weights().
wblut.nurbs.WB_RBSpline.WB_RBSpline (final WB_PointHomogeneous[] controlPoints, final WB_NurbsKnot knot)
Parameters
controlPoints
knot
References wblut.nurbs.WB_BSpline.knot(), wblut.nurbs.WB_NurbsKnot.n, wblut.nurbs.WB_BSpline.n(), wblut.nurbs.WB_NurbsKnot.p(), wblut.nurbs.WB_BSpline.p(), wblut.nurbs.WB_BSpline.points(), and wblut.geom.WB_MutableCoordinate4D.wd().
wblut.nurbs.WB_RBSpline.WB_RBSpline (final WB_Point[] controlPoints, final int order)
Parameters
controlPoints
order
wblut.nurbs.WB_RBSpline.WB_RBSpline (final WB_PointHomogeneous[] controlPoints, final int order)
Parameters
controlPoints
order
wblut.nurbs.WB_RBSpline.WB_RBSpline (final WB_Point[] controlPoints, final int order, final double[] weights)
Parameters
controlPoints
order
weights
References wblut.nurbs.WB_BSpline.n(), wblut.nurbs.WB_BSpline.points(), and wblut.nurbs.WB_RBSpline.weights().
Member Function Documentation
WB_Point wblut.nurbs.WB_RBSpline.curvePoint (final double u)
References wblut.geom.WB_Point4D.addMulSelf(), wblut.nurbs.WB_NurbsKnot.basisFunctions(), wblut.nurbs.WB_BSpline.knot(), wblut.nurbs.WB_NurbsKnot.p(), wblut.nurbs.WB_BSpline.p(), wblut.geom.WB_PointHomogeneous.project(), and wblut.nurbs.WB_NurbsKnot.span().
WB_RBSpline wblut.nurbs.WB_RBSpline.elevateDegree (final int t)
References wblut.geom.WB_Point4D.addMulSelf(), wblut.math.WB_Binomial.bin(), wblut.geom.WB_PointHomogeneous.interpolate(), wblut.nurbs.WB_BSpline.knot(), wblut.nurbs.WB_BSpline.n(), wblut.nurbs.WB_BSpline.p(), wblut.nurbs.WB_NurbsKnot.s(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.value(), and wblut.nurbs.WB_RBSpline.WB_RBSpline().
double wblut.nurbs.WB_RBSpline.getWeight (final int i)
Parameters
i
Returns
References wblut.nurbs.WB_BSpline.n().
WB_RBSpline wblut.nurbs.WB_RBSpline.insertKnot (final double u)
WB_RBSpline wblut.nurbs.WB_RBSpline.insertKnot (final double u, final int r)
References wblut.geom.WB_PointHomogeneous.interpolate(), wblut.nurbs.WB_BSpline.knot(), wblut.nurbs.WB_NurbsKnot.multiplicity(), wblut.nurbs.WB_BSpline.n(), wblut.nurbs.WB_BSpline.p(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_NurbsKnot.value(), and wblut.nurbs.WB_RBSpline.WB_RBSpline().
WB_RBSpline wblut.nurbs.WB_RBSpline.insertKnotMax (final double u)
References wblut.nurbs.WB_RBSpline.insertKnot(), wblut.nurbs.WB_BSpline.knot(), wblut.nurbs.WB_NurbsKnot.multiplicity(), and wblut.nurbs.WB_BSpline.p().
WB_RBSpline wblut.nurbs.WB_RBSpline.refineKnot (final WB_NurbsKnot K)
References wblut.nurbs.WB_BSpline.knot(), wblut.nurbs.WB_NurbsKnot.multiplicity(), wblut.nurbs.WB_NurbsKnot.multVal(), and wblut.nurbs.WB_RBSpline.refineKnotRestricted().
WB_RBSpline wblut.nurbs.WB_RBSpline.refineKnotRestricted (final double[] X) private
Parameters
X
Returns
References wblut.geom.WB_PointHomogeneous.interpolate(), wblut.math.WB_Epsilon.isZero(), wblut.nurbs.WB_BSpline.knot(), wblut.nurbs.WB_NurbsKnot.m, wblut.nurbs.WB_BSpline.n(), wblut.nurbs.WB_BSpline.p(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_NurbsKnot.value(), and wblut.nurbs.WB_RBSpline.WB_RBSpline().
void wblut.nurbs.WB_RBSpline.setWeight (final int i, final double w)
Parameters
i
w
References wblut.nurbs.WB_BSpline.n(), and wblut.nurbs.WB_BSpline.points().
WB_RBSpline [] wblut.nurbs.WB_RBSpline.split (final double u)
References wblut.nurbs.WB_RBSpline.insertKnotMax(), wblut.nurbs.WB_BSpline.knot, wblut.nurbs.WB_NurbsKnot.m, wblut.nurbs.WB_NurbsKnot.normalize(), wblut.nurbs.WB_BSpline.p(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_NurbsKnot.value(), wblut.nurbs.WB_RBSpline.WB_RBSpline(), and wblut.nurbs.WB_RBSpline.wpoints.
void wblut.nurbs.WB_RBSpline.updateHomogeneous ()
References wblut.nurbs.WB_BSpline.n(), and wblut.nurbs.WB_BSpline.points().
double [] wblut.nurbs.WB_RBSpline.weights ()
Returns
WB_PointHomogeneous [] wblut.nurbs.WB_RBSpline.wpoints ()
Returns
Member Data Documentation
final double [] wblut.nurbs.WB_RBSpline.weights private
WB_PointHomogeneous [] wblut.nurbs.WB_RBSpline.wpoints protected
The documentation for this class was generated from the following file:
src/nurbs/wblut/nurbs/WB_RBSpline.java