HE_Mesh: wblut.hemesh.HEM_Diagrid Class Reference
wblut.hemesh.HEM_Diagrid Class Reference
Public Member Functions
HEM_Diagrid ()
HEM_Diagrid setLimitAngle (final double a)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
double limitAngle
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Divides all faces in mesh or selection in triangles connecting the face center with each edge and deletes all original non-boundary edges with a dihedral angle larger that parameter limitAngle.
Author
frederikvanhoutte
Constructor & Destructor Documentation
wblut.hemesh.HEM_Diagrid.HEM_Diagrid ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Diagrid.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.deleteEdge(), wblut.hemesh.HE_Selection.eItr(), wblut.hemesh.HE_Halfedge.getEdgeDihedralAngle(), wblut.hemesh.HE_EdgeIterator.hasNext(), wblut.hemesh.HE_Halfedge.isInnerBoundary(), wblut.hemesh.HEM_Diagrid.limitAngle, wblut.hemesh.HE_EdgeIterator.next(), wblut.hemesh.HE_Mesh.selectAllEdges(), and wblut.hemesh.HET_MeshOp.splitFacesTri().
HE_Mesh wblut.hemesh.HEM_Diagrid.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_RAS< E extends HE_Element >.contains(), wblut.hemesh.HE_Mesh.deleteEdge(), wblut.hemesh.HE_Selection.eItr(), wblut.hemesh.HE_Halfedge.getEdgeDihedralAngle(), wblut.hemesh.HE_Selection.getOuterEdges(), wblut.hemesh.HE_EdgeIterator.hasNext(), wblut.hemesh.HEM_Diagrid.limitAngle, wblut.hemesh.HE_EdgeIterator.next(), and wblut.hemesh.HET_MeshOp.splitFacesTri().
HEM_Diagrid wblut.hemesh.HEM_Diagrid.setLimitAngle (final double a)
Set the lower limit dihedral angle.
Parameters
a : limit angle in radius, edges with dihedral angle lower than this angle are not removed. Default value is PI/2
Returns
Member Data Documentation
double wblut.hemesh.HEM_Diagrid.limitAngle private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Diagrid.java