HE_Mesh: wblut.geom.WB_IsoValues3D Class Reference
wblut.geom.WB_IsoValues3D Class Reference abstract
Classes
class Function3D
class Grid3D
class GridRaw3D
class HashGrid3D
class ImageStack3D
enum Mode
class SubValues3D
Public Member Functions
abstract double getValue (int i, int j, int k)
abstract int getSizeI ()
abstract int getSizeJ ()
abstract int getSizeK ()
WB_BinaryGrid3D getBinaryGrid3D (final int sizeX, final int sizeY, final int sizeZ, final double threshold)
Detailed Description
Author
FVH
Member Function Documentation
WB_BinaryGrid3D wblut.geom.WB_IsoValues3D.getBinaryGrid3D (final int sizeX, final int sizeY, final int sizeZ, final double threshold)
References wblut.geom.WB_BinaryGrid3D.createGrid(), wblut.geom.WB_IsoValues3D.getValue(), and wblut.geom.WB_BinaryGrid3D.set().
abstract int wblut.geom.WB_IsoValues3D.getSizeI () abstract
abstract int wblut.geom.WB_IsoValues3D.getSizeJ () abstract
abstract int wblut.geom.WB_IsoValues3D.getSizeK () abstract
abstract double wblut.geom.WB_IsoValues3D.getValue (int i, int j, int k) abstract
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_IsoValues3D.java