HE_Mesh: wblut.hemesh.HEC_FromFrame Class Reference
wblut.hemesh.HEC_FromFrame Class Reference
Classes
enum NodeType
class StrutNodeConnection
Public Member Functions
HEC_FromFrame ()
HEC_FromFrame setStrutRadius (final double r)
HEC_FromFrame setStrutRadius (final WB_ScalarParameter r)
HEC_FromFrame setMaximumStrutOffset (final WB_ScalarParameter o)
HEC_FromFrame setMaximumStrutOffset (final double o)
HEC_FromFrame setMinimumBalljointAngle (final double a)
HEC_FromFrame setMaximumStrutLength (final double d)
HEC_FromFrame setStrutFacets (final int f)
HEC_FromFrame setTaper (final boolean b)
HEC_FromFrame setCap (final boolean b)
HEC_FromFrame setSuppressBalljoint (final boolean b)
HEC_FromFrame setUseNodeValues (final boolean b)
HEC_FromFrame setCreateIsolatedNodes (final boolean b)
HEC_FromFrame setFidget (final double f)
HEC_FromFrame setFillFactor (final double ff)
HEC_FromFrame setAngleOffset (final double af)
HEC_FromFrame setAngleOffset (final WB_ScalarParameter af)
HEC_FromFrame setFrame (final WB_Frame frame)
HEC_FromFrame setFrame (final HE_Mesh mesh)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Member Functions
void getNodeTypes ()
void getStrutNodeConnections ()
void createNodeStrutConnection (final WB_FrameNode node, final int i, final double maxoff, final double off, final double rad)
void createVertices ()
int getStrutIndex (final WB_FrameNode node, final WB_FrameStrut strut)
void createStruts ()
void createNodes ()
Private Attributes
WB_Frame frame
int numberOfNodes
NodeType[] nodeTypes
StrutNodeConnection[] strutNodeConnections
WB_ScalarParameter strutRadius
int strutFacets
double fidget
double fillfactor
HE_Mesh mesh
double maximumStrutLength
double minimumBalljointAngle
WB_ScalarParameter maximumStrutOffset
boolean taper
boolean cap
boolean useNodeValues
boolean createIsolatedNodes
WB_ScalarParameter angleFactor
boolean suppressBalljoint
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Constructor & Destructor Documentation
wblut.hemesh.HEC_FromFrame.HEC_FromFrame ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_FromFrame.createBase () protected
References wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HEC_FromFrame.createNodes(), wblut.hemesh.HEC_FromFrame.createStruts(), wblut.hemesh.HEC_FromFrame.createVertices(), wblut.hemesh.HEC_FromFrame.getNodeTypes(), wblut.geom.WB_Frame.getNumberOfNodes(), wblut.geom.WB_Frame.getNumberOfStruts(), wblut.hemesh.HEC_FromFrame.getStrutNodeConnections(), wblut.hemesh.HEC_FromFrame.mesh, wblut.hemesh.HEC_FromFrame.numberOfNodes, and wblut.hemesh.HE_MeshStructure.pairHalfedges().
void wblut.hemesh.HEC_FromFrame.createNodes () private
References wblut.hemesh.HE_Mesh.add(), wblut.geom.WB_Vector.addSelf(), wblut.hemesh.HE_MeshStructure.addVertices(), wblut.hemesh.HE_MeshStructure.cleanUnusedElementsByFace(), wblut.hemesh.HE_Mesh.deleteFace(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HEC_FromFrame.fillfactor, wblut.hemesh.HE_MeshStructure.fItr(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.geom.WB_Frame.getNode(), wblut.geom.WB_Frame.getNodes(), wblut.geom.WB_Frame.WB_FrameNode.getStruts(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshStructure.getVertices(), wblut.hemesh.HE_MeshStructure.heItr(), wblut.hemesh.HE_Vertex.key(), wblut.geom.WB_Vector.mulSelf(), wblut.hemesh.HEC_Creator.setCenter(), wblut.hemesh.HE_MeshStructure.setFace(), wblut.hemesh.HE_MeshStructure.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_MeshStructure.setNext(), wblut.hemesh.HEC_ConvexHull.setPointsFromVertices(), wblut.hemesh.HE_MeshStructure.setVertex(), wblut.hemesh.HEC_FromFrame.strutFacets, wblut.hemesh.HE_MeshStructure.uncapBoundaryHalfedges(), and wblut.hemesh.HEC_ConvexHull.vertexToPointIndex.
void wblut.hemesh.HEC_FromFrame.createNodeStrutConnection (final WB_FrameNode node, final int i, final double maxoff, final double off, final double rad) private
Parameters
node
i
maxoff
off
rad
References wblut.geom.WB_Frame.WB_FrameNode.getStrut(), and wblut.hemesh.HEC_FromFrame.getStrutIndex().
void wblut.hemesh.HEC_FromFrame.createStruts () private
References wblut.hemesh.HE_Mesh.add(), wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.geom.WB_Frame.getStruts(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HEC_FromFrame.maximumStrutLength, wblut.hemesh.HE_MeshStructure.setFace(), wblut.hemesh.HE_MeshStructure.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_MeshStructure.setNext(), wblut.hemesh.HE_MeshStructure.setVertex(), and wblut.hemesh.HEC_FromFrame.strutFacets.
void wblut.hemesh.HEC_FromFrame.createVertices () private
References wblut.hemesh.HE_Mesh.add(), wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Vector.copy(), wblut.math.WB_ScalarParameter.evaluate(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Frame.getNumberOfStruts(), wblut.geom.WB_Plane.getU(), wblut.geom.WB_Vector.mul(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Vector.rotateAboutAxisSelf(), wblut.hemesh.HE_Element.setInternalLabel(), and wblut.hemesh.HEC_FromFrame.strutFacets.
void wblut.hemesh.HEC_FromFrame.getNodeTypes () private
References wblut.geom.WB_Frame.getNodes().
int wblut.hemesh.HEC_FromFrame.getStrutIndex (final WB_FrameNode node, final WB_FrameStrut strut) private
Parameters
node
strut
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.getIndex(), and wblut.geom.WB_Frame.WB_FrameStrut.start.
void wblut.hemesh.HEC_FromFrame.getStrutNodeConnections () private
References wblut.hemesh.HEC_FromFrame.createNodeStrutConnection(), wblut.math.WB_ScalarParameter.evaluate(), wblut.geom.WB_Frame.getNodes(), and wblut.geom.WB_Frame.getNumberOfStruts().
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setAngleOffset (final double af)
Parameters
af
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setAngleOffset (final WB_ScalarParameter af)
Parameters
af
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setCap (final boolean b)
Parameters
b
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setCreateIsolatedNodes (final boolean b)
Parameters
b
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setFidget (final double f)
Parameters
f
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setFillFactor (final double ff)
Parameters
ff
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setFrame (final WB_Frame frame)
Parameters
frame
Returns
References wblut.hemesh.HEC_FromFrame.frame.
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setFrame (final HE_Mesh mesh)
Parameters
mesh
Returns
References wblut.hemesh.HE_Mesh.getFrame().
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setMaximumStrutLength (final double d)
Parameters
d
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setMaximumStrutOffset (final WB_ScalarParameter o)
Parameters
o
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setMaximumStrutOffset (final double o)
Parameters
o
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setMinimumBalljointAngle (final double a)
Parameters
a
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setStrutFacets (final int f)
Parameters
f
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setStrutRadius (final double r)
Parameters
r
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setStrutRadius (final WB_ScalarParameter r)
Parameters
r
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setSuppressBalljoint (final boolean b)
Parameters
b
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setTaper (final boolean b)
Parameters
b
Returns
HEC_FromFrame wblut.hemesh.HEC_FromFrame.setUseNodeValues (final boolean b)
Parameters
b
Returns
Member Data Documentation
WB_ScalarParameter wblut.hemesh.HEC_FromFrame.angleFactor private
boolean wblut.hemesh.HEC_FromFrame.cap private
boolean wblut.hemesh.HEC_FromFrame.createIsolatedNodes private
double wblut.hemesh.HEC_FromFrame.fidget private
double wblut.hemesh.HEC_FromFrame.fillfactor private
WB_Frame wblut.hemesh.HEC_FromFrame.frame private
WB_GeometryFactory wblut.hemesh.HEC_FromFrame.gf = new WB_GeometryFactory() static private
double wblut.hemesh.HEC_FromFrame.maximumStrutLength private
WB_ScalarParameter wblut.hemesh.HEC_FromFrame.maximumStrutOffset private
HE_Mesh wblut.hemesh.HEC_FromFrame.mesh private
double wblut.hemesh.HEC_FromFrame.minimumBalljointAngle private
NodeType [] wblut.hemesh.HEC_FromFrame.nodeTypes private
int wblut.hemesh.HEC_FromFrame.numberOfNodes private
int wblut.hemesh.HEC_FromFrame.strutFacets private
StrutNodeConnection [] wblut.hemesh.HEC_FromFrame.strutNodeConnections private
WB_ScalarParameter wblut.hemesh.HEC_FromFrame.strutRadius private
boolean wblut.hemesh.HEC_FromFrame.suppressBalljoint private
boolean wblut.hemesh.HEC_FromFrame.taper private
boolean wblut.hemesh.HEC_FromFrame.useNodeValues private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_FromFrame.java