HE_Mesh: wblut.processing.WB_DebugRender3D Class Reference
wblut.processing.WB_DebugRender3D Class Reference
Public Member Functions
WB_DebugRender3D (final PApplet home)
WB_DebugRender3D (final PGraphics home)
void drawBadVertices (final HE_HalfedgeStructure mesh, final double d)
void drawBoundaryEdges (final HE_HalfedgeStructure mesh)
void drawBoundaryHalfedges (final HE_HalfedgeStructure mesh)
void drawUnpairedHalfedges (final HE_HalfedgeStructure mesh)
void drawFaceNormal (final HE_Face f, final double d)
void drawFaceNormals (final HE_HalfedgeStructure mesh, final double d)
void drawFaceTypes (final HE_HalfedgeStructure mesh)
void drawHalfedge (final HE_Halfedge he, final double d, final double s)
void drawHalfedge (final HE_Halfedge he, final double d, final double s, final double f)
void drawHalfedge (final Long key, final double d, final double s, final HE_Mesh mesh)
void drawHalfedges (final HE_HalfedgeStructure mesh, final double d, final double f)
void drawHalfedges (final HE_HalfedgeStructure mesh, final double d)
void drawHalfedgeSimple (final HE_Halfedge he, final double d, final double s)
void drawVertexNormals (final HE_HalfedgeStructure mesh, final double d)
Private Member Functions
void draw (final WB_Coord p, final WB_Coord v, final double d)
void drawFace (final HE_Face f)
Private Attributes
final PGraphics home
WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.processing.WB_DebugRender3D.WB_DebugRender3D (final PApplet home)
Parameters
home
wblut.processing.WB_DebugRender3D.WB_DebugRender3D (final PGraphics home)
Parameters
home
References wblut.processing.WB_DebugRender3D.home.
Member Function Documentation
void wblut.processing.WB_DebugRender3D.draw (final WB_Coord p, final WB_Coord v, final double d) private
Parameters
p
v
d
References wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
void wblut.processing.WB_DebugRender3D.drawBadVertices (final HE_HalfedgeStructure mesh, final double d)
Parameters
mesh
d
References wblut.hemesh.HE_HalfedgeStructure.contains(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_HalfedgeStructure.vItr(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_DebugRender3D.drawBoundaryEdges (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_HalfedgeStructure.heItr(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_DebugRender3D.drawBoundaryHalfedges (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_HalfedgeStructure.heItr(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_DebugRender3D.drawFace (final HE_Face f) private
Parameters
f
References wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
void wblut.processing.WB_DebugRender3D.drawFaceNormal (final HE_Face f, final double d)
Parameters
f
d
References wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.geom.WB_Point.mul(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_MutableCoordinate.xf(), wblut.geom.WB_Coord.yf(), wblut.geom.WB_MutableCoordinate.yf(), wblut.geom.WB_Coord.zf(), and wblut.geom.WB_MutableCoordinate.zf().
void wblut.processing.WB_DebugRender3D.drawFaceNormals (final HE_HalfedgeStructure mesh, final double d)
Parameters
mesh
d
References wblut.hemesh.HE_HalfedgeStructure.fItr(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
void wblut.processing.WB_DebugRender3D.drawFaceTypes (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.geom.WB_Classification.CONCAVE, wblut.geom.WB_Classification.CONVEX, wblut.processing.WB_DebugRender3D.drawFace(), wblut.hemesh.HE_HalfedgeStructure.fItr(), and wblut.hemesh.HE_Face.getFaceType().
void wblut.processing.WB_DebugRender3D.drawHalfedge (final HE_Halfedge he, final double d, final double s)
Parameters
he
d
s
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Classification.CONCAVE, wblut.geom.WB_Classification.CONVEX, wblut.hemesh.HE_Halfedge.getHalfedgeCenter(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Halfedge.getHalfedgeType(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_Point.translate(), wblut.geom.WB_MutableCoordinate.xf(), wblut.hemesh.HE_Vertex.xf(), wblut.geom.WB_MutableCoordinate.yf(), wblut.hemesh.HE_Vertex.yf(), wblut.geom.WB_MutableCoordinate.zf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_DebugRender3D.drawHalfedge (final HE_Halfedge he, final double d, final double s, final double f)
Parameters
he
d
s
f
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Classification.CONCAVE, wblut.geom.WB_Classification.CONVEX, wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Halfedge.getHalfedgeType(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_Point.translate(), wblut.geom.WB_MutableCoordinate.xf(), wblut.hemesh.HE_Vertex.xf(), wblut.geom.WB_MutableCoordinate.yf(), wblut.hemesh.HE_Vertex.yf(), wblut.geom.WB_MutableCoordinate.zf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_DebugRender3D.drawHalfedge (final Long key, final double d, final double s, final HE_Mesh mesh)
Parameters
key
d
s
mesh
References wblut.processing.WB_DebugRender3D.drawHalfedge(), and wblut.hemesh.HE_Mesh.getHalfedgeWithKey().
void wblut.processing.WB_DebugRender3D.drawHalfedges (final HE_HalfedgeStructure mesh, final double d, final double f)
Parameters
mesh
d
f
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Classification.CONCAVE, wblut.geom.WB_Classification.CONVEX, wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Halfedge.getHalfedgeType(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_HalfedgeStructure.heItr(), wblut.geom.WB_Point.translate(), wblut.geom.WB_MutableCoordinate.xf(), wblut.hemesh.HE_Vertex.xf(), wblut.geom.WB_MutableCoordinate.yf(), wblut.hemesh.HE_Vertex.yf(), wblut.geom.WB_MutableCoordinate.zf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_DebugRender3D.drawHalfedges (final HE_HalfedgeStructure mesh, final double d)
Parameters
mesh
d
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Classification.CONCAVE, wblut.geom.WB_Classification.CONVEX, wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Halfedge.getHalfedgeCenter(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Halfedge.getHalfedgeType(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_HalfedgeStructure.heItr(), wblut.geom.WB_Point.translate(), wblut.geom.WB_MutableCoordinate.xf(), wblut.hemesh.HE_Vertex.xf(), wblut.geom.WB_MutableCoordinate.yf(), wblut.hemesh.HE_Vertex.yf(), wblut.geom.WB_MutableCoordinate.zf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_DebugRender3D.drawHalfedgeSimple (final HE_Halfedge he, final double d, final double s)
Parameters
he
d
s
References wblut.geom.WB_Point.addMulSelf(), wblut.hemesh.HE_Halfedge.getHalfedgeCenter(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_Point.translate(), wblut.geom.WB_MutableCoordinate.xf(), wblut.hemesh.HE_Vertex.xf(), wblut.geom.WB_MutableCoordinate.yf(), wblut.hemesh.HE_Vertex.yf(), wblut.geom.WB_MutableCoordinate.zf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_DebugRender3D.drawUnpairedHalfedges (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_HalfedgeStructure.heItr(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_DebugRender3D.drawVertexNormals (final HE_HalfedgeStructure mesh, final double d)
Parameters
mesh
d
References wblut.processing.WB_DebugRender3D.draw(), wblut.hemesh.HE_Vertex.getVertexNormal(), and wblut.hemesh.HE_HalfedgeStructure.vItr().
Member Data Documentation
WB_GeometryFactory wblut.processing.WB_DebugRender3D.geometryfactory = new WB_GeometryFactory() private
final PGraphics wblut.processing.WB_DebugRender3D.home private
The documentation for this class was generated from the following file:
src/processing/wblut/processing/WB_DebugRender3D.java