HE_Mesh: wblut.hemesh.HEM_Wireframe Class Reference
wblut.hemesh.HEM_Wireframe Class Reference
Public Member Functions
HEM_Wireframe ()
HEM_Wireframe setConnectionRadius (final double r)
HEM_Wireframe setConnectionRadius (final WB_ScalarParameter r)
HEM_Wireframe setMaximumConnectionOffset (final double r)
HEM_Wireframe setMaximumConnectionOffset (final WB_ScalarParameter r)
HEM_Wireframe setConnectionFacets (final int N)
HEM_Wireframe setAngleOffset (final double af)
HEM_Wireframe setAngleOffset (final WB_ScalarParameter af)
HEM_Wireframe setFidget (final double f)
HEM_Wireframe setFillFactor (final double ff)
HEM_Wireframe setCap (final boolean b)
HEM_Wireframe setTaper (final boolean b)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_ScalarParameter connectionRadius
WB_ScalarParameter maxConnectionOffset
int facetN
WB_ScalarParameter angleFactor
double fillFactor
double fidget
boolean cap
boolean taper
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_Wireframe.HEM_Wireframe ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Wireframe.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HEC_Creator.create(), wblut.hemesh.HEC_FromNetwork.setAngleOffset(), wblut.hemesh.HEC_FromNetwork.setCap(), wblut.hemesh.HEC_FromNetwork.setConnectionFacets(), wblut.hemesh.HEC_FromNetwork.setConnectionRadius(), wblut.hemesh.HEC_FromNetwork.setFidget(), wblut.hemesh.HEC_FromNetwork.setFillFactor(), wblut.hemesh.HEC_FromNetwork.setMaximumConnectionOffset(), wblut.hemesh.HEC_FromNetwork.setNetwork(), and wblut.hemesh.HEC_FromNetwork.setTaper().
HE_Mesh wblut.hemesh.HEM_Wireframe.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HEM_Wireframe.applySelf().
HEM_Wireframe wblut.hemesh.HEM_Wireframe.setAngleOffset (final double af)
Parameters
af
Returns
HEM_Wireframe wblut.hemesh.HEM_Wireframe.setAngleOffset (final WB_ScalarParameter af)
Parameters
af
Returns
HEM_Wireframe wblut.hemesh.HEM_Wireframe.setCap (final boolean b)
Parameters
b
Returns
HEM_Wireframe wblut.hemesh.HEM_Wireframe.setConnectionFacets (final int N)
Parameters
N
Returns
HEM_Wireframe wblut.hemesh.HEM_Wireframe.setConnectionRadius (final double r)
Parameters
r
Returns
HEM_Wireframe wblut.hemesh.HEM_Wireframe.setConnectionRadius (final WB_ScalarParameter r)
Parameters
r
Returns
HEM_Wireframe wblut.hemesh.HEM_Wireframe.setFidget (final double f)
Parameters
f
Returns
HEM_Wireframe wblut.hemesh.HEM_Wireframe.setFillFactor (final double ff)
Parameters
ff
Returns
HEM_Wireframe wblut.hemesh.HEM_Wireframe.setMaximumConnectionOffset (final double r)
Parameters
r
Returns
HEM_Wireframe wblut.hemesh.HEM_Wireframe.setMaximumConnectionOffset (final WB_ScalarParameter r)
Parameters
r
Returns
HEM_Wireframe wblut.hemesh.HEM_Wireframe.setTaper (final boolean b)
Parameters
b
Returns
Member Data Documentation
WB_ScalarParameter wblut.hemesh.HEM_Wireframe.angleFactor private
boolean wblut.hemesh.HEM_Wireframe.cap private
WB_ScalarParameter wblut.hemesh.HEM_Wireframe.connectionRadius private
int wblut.hemesh.HEM_Wireframe.facetN private
double wblut.hemesh.HEM_Wireframe.fidget private
double wblut.hemesh.HEM_Wireframe.fillFactor private
WB_ScalarParameter wblut.hemesh.HEM_Wireframe.maxConnectionOffset private
boolean wblut.hemesh.HEM_Wireframe.taper private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Wireframe.java