HE_Mesh: wblut.geom.WB_MeshGraph Class Reference
wblut.geom.WB_MeshGraph Class Reference
Classes
class WB_GraphEdge
class WB_GraphVertex
Public Member Functions
WB_MeshGraph (final WB_Mesh mesh)
WB_MeshGraph (final WB_Mesh mesh, final double offset)
WB_MeshGraph (final HE_Mesh mesh)
WB_MeshGraph (final HE_Mesh mesh, final double offset)
WB_MeshGraph (final List<?extends WB_Coord > points, final WB_Triangulation3D triangulation)
WB_MeshGraph (final WB_Coord[] points, final WB_Triangulation3D triangulation)
WB_MeshGraph (final WB_Coord[] points, final WB_Triangulation2D triangulation)
int getVertexIndex (final int i)
void computePathsToVertex (final int i)
int[] getShortestPathBetweenVertices (final int source, final int target)
double getShortestDistanceBetweenVertices (final int source, final int target)
WB_Network getFrame (final int i)
WB_Network getFrame (final int i, final int maxnodes)
WB_Network getFrame (final int i, final int maxnodes, final double offset)
WB_Network getFrame (final int i, final int maxnodes, final int cuttail)
Static Public Member Functions
static void main (final String[] args)
static List< WB_MeshGraph > getAllGraphs (final HE_Mesh mesh)
Private Attributes
final WB_GraphVertex[] vertices
int lastSource
Constructor & Destructor Documentation
wblut.geom.WB_MeshGraph.WB_MeshGraph (final WB_Mesh mesh)
Parameters
mesh
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Mesh.getEdgesAsInt(), wblut.geom.WB_Mesh.getNumberOfVertices(), wblut.geom.WB_Mesh.getVertex(), and wblut.geom.WB_MeshGraph.WB_GraphVertex.neighbors.
wblut.geom.WB_MeshGraph.WB_MeshGraph (final WB_Mesh mesh, final double offset)
Parameters
mesh
offset
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Mesh.getEdgesAsInt(), wblut.geom.WB_Mesh.getNumberOfVertices(), wblut.geom.WB_Mesh.getVertex(), wblut.geom.WB_Mesh.getVertexNormal(), and wblut.geom.WB_MeshGraph.WB_GraphVertex.neighbors.
wblut.geom.WB_MeshGraph.WB_MeshGraph (final HE_Mesh mesh)
Parameters
mesh
wblut.geom.WB_MeshGraph.WB_MeshGraph (final HE_Mesh mesh, final double offset)
Parameters
mesh
offset
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.hemesh.HE_Mesh.getEdgesAsInt(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Mesh.getVertex(), wblut.hemesh.HE_Mesh.getVertexNormal(), and wblut.geom.WB_MeshGraph.WB_GraphVertex.neighbors.
wblut.geom.WB_MeshGraph.WB_MeshGraph (final List<?extends WB_Coord > points, final WB_Triangulation3D triangulation)
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Triangulation3D.getEdges(), and wblut.geom.WB_MeshGraph.WB_GraphVertex.neighbors.
wblut.geom.WB_MeshGraph.WB_MeshGraph (final WB_Coord[] points, final WB_Triangulation3D triangulation)
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Triangulation3D.getEdges(), and wblut.geom.WB_MeshGraph.WB_GraphVertex.neighbors.
wblut.geom.WB_MeshGraph.WB_MeshGraph (final WB_Coord[] points, final WB_Triangulation2D triangulation)
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Triangulation2D.getEdges(), and wblut.geom.WB_MeshGraph.WB_GraphVertex.neighbors.
Member Function Documentation
void wblut.geom.WB_MeshGraph.computePathsToVertex (final int i)
Parameters
i
References wblut.geom.WB_MeshGraph.WB_GraphVertex.distanceToSource, wblut.geom.WB_MeshGraph.WB_GraphVertex.neighbors, wblut.geom.WB_MeshGraph.WB_GraphVertex.previous, wblut.geom.WB_MeshGraph.WB_GraphVertex.reset(), wblut.geom.WB_MeshGraph.WB_GraphEdge.target, and wblut.geom.WB_MeshGraph.WB_GraphEdge.weight.
static List<WB_MeshGraph> wblut.geom.WB_MeshGraph.getAllGraphs (final HE_Mesh mesh) static
References wblut.hemesh.HE_MeshCollection.getMesh(), wblut.hemesh.HE_MeshCollection.getNumberOfMeshes(), wblut.hemesh.HEMC_Explode.setMesh(), and wblut.geom.WB_MeshGraph.WB_MeshGraph().
WB_Network wblut.geom.WB_MeshGraph.getFrame (final int i)
Parameters
i
Returns
References wblut.geom.WB_Network.addConnection(), wblut.geom.WB_Network.addNode(), wblut.geom.WB_MeshGraph.computePathsToVertex(), wblut.geom.WB_Network.getNode(), wblut.geom.WB_MeshGraph.getShortestPathBetweenVertices(), and wblut.geom.WB_Network.Node.value.
WB_Network wblut.geom.WB_MeshGraph.getFrame (final int i, final int maxnodes)
Parameters
i
maxnodes
Returns
References wblut.geom.WB_Network.addConnection(), wblut.geom.WB_Network.addNode(), wblut.geom.WB_MeshGraph.computePathsToVertex(), wblut.geom.WB_Network.getNode(), wblut.geom.WB_MeshGraph.getShortestPathBetweenVertices(), and wblut.geom.WB_Network.Node.value.
WB_Network wblut.geom.WB_MeshGraph.getFrame (final int i, final int maxnodes, final double offset)
References wblut.geom.WB_Network.addConnection(), wblut.geom.WB_Network.addNode(), wblut.geom.WB_MeshGraph.computePathsToVertex(), wblut.geom.WB_Network.getNode(), wblut.geom.WB_MeshGraph.getShortestPathBetweenVertices(), and wblut.geom.WB_Network.Node.value.
WB_Network wblut.geom.WB_MeshGraph.getFrame (final int i, final int maxnodes, final int cuttail)
Parameters
i
maxnodes
cuttail
Returns
References wblut.geom.WB_Network.addConnection(), wblut.geom.WB_Network.addNode(), wblut.geom.WB_MeshGraph.computePathsToVertex(), wblut.geom.WB_Network.getNode(), wblut.geom.WB_MeshGraph.getShortestPathBetweenVertices(), and wblut.geom.WB_Network.Node.value.
double wblut.geom.WB_MeshGraph.getShortestDistanceBetweenVertices (final int source, final int target)
References wblut.geom.WB_MeshGraph.computePathsToVertex(), and wblut.geom.WB_MeshGraph.WB_GraphVertex.distanceToSource.
int [] wblut.geom.WB_MeshGraph.getShortestPathBetweenVertices (final int source, final int target)
Parameters
source
target
Returns
References wblut.geom.WB_MeshGraph.computePathsToVertex(), and wblut.geom.WB_MeshGraph.WB_GraphVertex.previous.
int wblut.geom.WB_MeshGraph.getVertexIndex (final int i)
Parameters
i
Returns
References wblut.geom.WB_MeshGraph.WB_GraphVertex.index.
static void wblut.geom.WB_MeshGraph.main (final String[] args) static
Parameters
args
References wblut.geom.WB_Geodesic.create(), wblut.geom.WB_MeshGraph.WB_GraphVertex.distanceToSource, wblut.geom.WB_MeshGraph.getShortestPathBetweenVertices(), wblut.geom.WB_Geodesic.ICOSAHEDRON, wblut.geom.WB_MeshGraph.WB_GraphVertex.index, wblut.hemesh.HE_Mesh.smooth(), wblut.geom.WB_MeshGraph.vertices, and wblut.geom.WB_MeshGraph.WB_MeshGraph().
Member Data Documentation
int wblut.geom.WB_MeshGraph.lastSource private
final WB_GraphVertex [] wblut.geom.WB_MeshGraph.vertices private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_MeshGraph.java