HE_Mesh: wblut.geom.WB_RandomOnCylinder Class Reference
wblut.geom.WB_RandomOnCylinder Class Reference
Public Member Functions
WB_RandomOnCylinder ()
WB_RandomOnCylinder (final long seed)
WB_RandomOnCylinder setSeed (final long seed)
WB_RandomOnCylinder setRadius (final double r)
WB_RandomOnCylinder setHeight (final double h)
WB_Point nextPoint ()
WB_Vector nextVector ()
void reset ()
WB_RandomOnCylinder setOffset (final WB_Coord offset)
WB_RandomOnCylinder setOffset (final double x, final double y)
WB_RandomOnCylinder setOffset (final double x, final double y, final double z)
Public Member Functions inherited from wblut.geom.WB_RandomPoint
WB_RandomPoint setOffset (WB_Coord offset)
WB_RandomPoint setOffset (double x, double y)
WB_RandomPoint setOffset (double x, double y, double z)
Private Attributes
final WB_MTRandom randomGen
double radius
WB_Vector offset
Detailed Description
Random generator for vectors or points uniformly distributed on the mantle of a cylinder with radius r and height h.
Author
Frederik Vanhoutte, W:Blut
Constructor & Destructor Documentation
wblut.geom.WB_RandomOnCylinder.WB_RandomOnCylinder ()
wblut.geom.WB_RandomOnCylinder.WB_RandomOnCylinder (final long seed)
Parameters
seed
Member Function Documentation
WB_Point wblut.geom.WB_RandomOnCylinder.nextPoint ()
Get the next random point.
Returns
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.nextCenteredDouble(), and wblut.math.WB_MTRandom.nextDouble().
WB_Vector wblut.geom.WB_RandomOnCylinder.nextVector ()
Get the next random vector.
Returns
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.nextCenteredDouble(), and wblut.math.WB_MTRandom.nextDouble().
void wblut.geom.WB_RandomOnCylinder.reset ()
Reset the RNG.
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.reset().
WB_RandomOnCylinder wblut.geom.WB_RandomOnCylinder.setHeight (final double h)
Parameters
h
Returns
WB_RandomOnCylinder wblut.geom.WB_RandomOnCylinder.setOffset (final WB_Coord offset)
WB_RandomOnCylinder wblut.geom.WB_RandomOnCylinder.setOffset (final double x, final double y)
References wblut.geom.WB_MutableCoordinate.set().
WB_RandomOnCylinder wblut.geom.WB_RandomOnCylinder.setOffset (final double x, final double y, final double z)
References wblut.geom.WB_MutableCoordinate.set().
WB_RandomOnCylinder wblut.geom.WB_RandomOnCylinder.setRadius (final double r)
Parameters
r
Returns
WB_RandomOnCylinder wblut.geom.WB_RandomOnCylinder.setSeed (final long seed)
Set the seed for the RNG.
Parameters
seed
Returns
this
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.setSeed().
Member Data Documentation
WB_Vector wblut.geom.WB_RandomOnCylinder.offset private
double wblut.geom.WB_RandomOnCylinder.radius private
final WB_MTRandom wblut.geom.WB_RandomOnCylinder.randomGen private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_RandomOnCylinder.java