HE_Mesh: wblut.geom.WB_PyramidFactory Class Reference
wblut.geom.WB_PyramidFactory Class Reference
Public Member Functions
WB_PyramidFactory ()
WB_PyramidFactory setPoints (final WB_CoordCollection points)
WB_PyramidFactory setPoints (final WB_Polygon polygon)
WB_PyramidFactory setPoints (final Collection<?extends WB_Coord > points)
WB_PyramidFactory setPoints (final WB_Coord[] points)
WB_PyramidFactory setCap (final boolean cap)
WB_PyramidFactory setMap (final WB_Map2D map)
WB_Mesh createPyramidWithAngle (final double...angles)
WB_Mesh createPyramidWithHeightAndAngle (final double height, final double...angles)
WB_Mesh createPyramidWithHeight (final double height)
WB_Mesh createOffset (final double height, final double...offset)
Private Attributes
WB_CoordCollection points
boolean cap
WB_Map2D map
Detailed Description
Author
FVH
Constructor & Destructor Documentation
wblut.geom.WB_PyramidFactory.WB_PyramidFactory ()
Member Function Documentation
WB_Mesh wblut.geom.WB_PyramidFactory.createOffset (final double height, final double... offset)
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_CoordCollection.map(), wblut.geom.WB_CoordCollection.size(), wblut.geom.WB_Map2D.unmapPoint2D(), wblut.geom.WB_Map.unmapPoint3D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Mesh wblut.geom.WB_PyramidFactory.createPyramidWithAngle (final double... angles)
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_CoordCollection.map(), wblut.geom.WB_CoordCollection.size(), wblut.geom.WB_Map2D.unmapPoint2D(), wblut.geom.WB_Map.unmapPoint3D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Mesh wblut.geom.WB_PyramidFactory.createPyramidWithHeight (final double height)
Parameters
height
Returns
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_CoordCollection.map(), wblut.geom.WB_CoordCollection.size(), wblut.geom.WB_Map2D.unmapPoint2D(), wblut.geom.WB_Map.unmapPoint3D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Mesh wblut.geom.WB_PyramidFactory.createPyramidWithHeightAndAngle (final double height, final double... angles)
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_CoordCollection.map(), wblut.geom.WB_CoordCollection.size(), wblut.geom.WB_Map2D.unmapPoint2D(), wblut.geom.WB_Map.unmapPoint3D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_PyramidFactory wblut.geom.WB_PyramidFactory.setCap (final boolean cap)
References wblut.geom.WB_PyramidFactory.cap.
WB_PyramidFactory wblut.geom.WB_PyramidFactory.setMap (final WB_Map2D map)
References wblut.geom.WB_PyramidFactory.map.
WB_PyramidFactory wblut.geom.WB_PyramidFactory.setPoints (final WB_CoordCollection points)
References wblut.geom.WB_PyramidFactory.points.
WB_PyramidFactory wblut.geom.WB_PyramidFactory.setPoints (final WB_Polygon polygon)
References wblut.geom.WB_CoordCollection.getCollection().
WB_PyramidFactory wblut.geom.WB_PyramidFactory.setPoints (final Collection<?extends WB_Coord > points)
References wblut.geom.WB_CoordCollection.getCollection().
WB_PyramidFactory wblut.geom.WB_PyramidFactory.setPoints (final WB_Coord[] points)
References wblut.geom.WB_CoordCollection.getCollection().
Member Data Documentation
boolean wblut.geom.WB_PyramidFactory.cap private
WB_Map2D wblut.geom.WB_PyramidFactory.map private
WB_CoordCollection wblut.geom.WB_PyramidFactory.points private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_PyramidFactory.java