HE_Mesh: wblut.math.WB_Complex Class Reference
wblut.math.WB_Complex Class Reference
Public Member Functions
WB_Complex (final double r, final double i)
WB_Complex ()
WB_Complex get ()
double re ()
double im ()
double theta ()
double mod ()
double r ()
double mag ()
WB_Complex conjugate ()
WB_Complex conjugateSelf ()
WB_Complex add (final WB_Complex c)
WB_Complex addSelf (final WB_Complex c)
WB_Complex sub (final WB_Complex c)
WB_Complex subSelf (final WB_Complex c)
WB_Complex mul (final WB_Complex c)
WB_Complex mulSelf (final WB_Complex c)
WB_Complex mul (final double d)
WB_Complex mulSelf (final double d)
WB_Complex inverse ()
WB_Complex inverseSelf ()
WB_Complex div (final WB_Complex c)
WB_Complex divSelf (final WB_Complex c)
WB_Complex negate ()
WB_Complex negateSelf ()
WB_Complex positive ()
WB_Complex positiveSelf ()
WB_Complex sqrt ()
WB_Complex sin ()
WB_Complex cos ()
WB_Complex tan ()
WB_Complex sinh ()
WB_Complex cosh ()
WB_Complex tanh ()
boolean equals (final WB_Complex c)
boolean isZero ()
String toString ()
Private Member Functions
void set (final double r, final double i)
Static Private Member Functions
static double sinh (final double a)
static double cosh (final double a)
Private Attributes
double re
double im
Detailed Description
Author
FVH
Constructor & Destructor Documentation
wblut.math.WB_Complex.WB_Complex (final double r, final double i)
References wblut.math.WB_Complex.r().
wblut.math.WB_Complex.WB_Complex ()
Member Function Documentation
WB_Complex wblut.math.WB_Complex.add (final WB_Complex c)
References wblut.math.WB_Complex.im, wblut.math.WB_Complex.re, and wblut.math.WB_Complex.WB_Complex().
WB_Complex wblut.math.WB_Complex.addSelf (final WB_Complex c)
References wblut.math.WB_Complex.im, and wblut.math.WB_Complex.re.
WB_Complex wblut.math.WB_Complex.conjugate ()
References wblut.math.WB_Complex.WB_Complex().
WB_Complex wblut.math.WB_Complex.conjugateSelf ()
References wblut.math.WB_Complex.set().
WB_Complex wblut.math.WB_Complex.cos ()
References wblut.math.WB_Complex.cos(), wblut.math.WB_Complex.cosh(), wblut.math.WB_Complex.sinh(), and wblut.math.WB_Complex.WB_Complex().
static double wblut.math.WB_Complex.cosh (final double a) static private
WB_Complex wblut.math.WB_Complex.cosh ()
References wblut.math.WB_Complex.cos(), wblut.math.WB_Complex.sin(), wblut.math.WB_Complex.sinh(), and wblut.math.WB_Complex.WB_Complex().
WB_Complex wblut.math.WB_Complex.div (final WB_Complex c)
References wblut.math.WB_Complex.inverse(), and wblut.math.WB_Complex.mul().
WB_Complex wblut.math.WB_Complex.divSelf (final WB_Complex c)
References wblut.math.WB_Complex.inverse(), and wblut.math.WB_Complex.mulSelf().
boolean wblut.math.WB_Complex.equals (final WB_Complex c)
References wblut.math.WB_Complex.im, and wblut.math.WB_Complex.re.
WB_Complex wblut.math.WB_Complex.get ()
References wblut.math.WB_Complex.WB_Complex().
double wblut.math.WB_Complex.im ()
WB_Complex wblut.math.WB_Complex.inverse ()
References wblut.math.WB_Complex.im(), and wblut.math.WB_Complex.WB_Complex().
WB_Complex wblut.math.WB_Complex.inverseSelf ()
References wblut.math.WB_Complex.im(), and wblut.math.WB_Complex.set().
boolean wblut.math.WB_Complex.isZero ()
double wblut.math.WB_Complex.mag ()
References wblut.math.WB_Complex.im().
double wblut.math.WB_Complex.mod ()
WB_Complex wblut.math.WB_Complex.mul (final WB_Complex c)
References wblut.math.WB_Complex.im, wblut.math.WB_Complex.re, and wblut.math.WB_Complex.WB_Complex().
WB_Complex wblut.math.WB_Complex.mul (final double d)
References wblut.math.WB_Complex.WB_Complex().
WB_Complex wblut.math.WB_Complex.mulSelf (final WB_Complex c)
References wblut.math.WB_Complex.im, wblut.math.WB_Complex.re, and wblut.math.WB_Complex.set().
WB_Complex wblut.math.WB_Complex.mulSelf (final double d)
WB_Complex wblut.math.WB_Complex.negate ()
References wblut.math.WB_Complex.im(), wblut.math.WB_Complex.re(), and wblut.math.WB_Complex.WB_Complex().
WB_Complex wblut.math.WB_Complex.negateSelf ()
WB_Complex wblut.math.WB_Complex.positive ()
References wblut.math.WB_Complex.WB_Complex().
WB_Complex wblut.math.WB_Complex.positiveSelf ()
References wblut.math.WB_Complex.set().
double wblut.math.WB_Complex.r ()
References wblut.math.WB_Complex.mod().
double wblut.math.WB_Complex.re ()
void wblut.math.WB_Complex.set (final double r, final double i) private
References wblut.math.WB_Complex.r().
WB_Complex wblut.math.WB_Complex.sin ()
References wblut.math.WB_Complex.cos(), wblut.math.WB_Complex.cosh(), wblut.math.WB_Complex.sin(), wblut.math.WB_Complex.sinh(), and wblut.math.WB_Complex.WB_Complex().
static double wblut.math.WB_Complex.sinh (final double a) static private
WB_Complex wblut.math.WB_Complex.sinh ()
References wblut.math.WB_Complex.cos(), wblut.math.WB_Complex.cosh(), wblut.math.WB_Complex.sin(), and wblut.math.WB_Complex.WB_Complex().
WB_Complex wblut.math.WB_Complex.sqrt ()
References wblut.math.WB_Complex.r(), wblut.math.WB_Complex.theta(), and wblut.math.WB_Complex.WB_Complex().
WB_Complex wblut.math.WB_Complex.sub (final WB_Complex c)
References wblut.math.WB_Complex.im, wblut.math.WB_Complex.re, and wblut.math.WB_Complex.WB_Complex().
WB_Complex wblut.math.WB_Complex.subSelf (final WB_Complex c)
References wblut.math.WB_Complex.im, and wblut.math.WB_Complex.re.
WB_Complex wblut.math.WB_Complex.tan ()
References wblut.math.WB_Complex.cos(), wblut.math.WB_Complex.div(), and wblut.math.WB_Complex.sin().
WB_Complex wblut.math.WB_Complex.tanh ()
References wblut.math.WB_Complex.cos(), wblut.math.WB_Complex.cosh(), wblut.math.WB_Complex.sin(), wblut.math.WB_Complex.sinh(), and wblut.math.WB_Complex.WB_Complex().
double wblut.math.WB_Complex.theta ()
References wblut.math.WB_Complex.mod(), and wblut.math.WB_Complex.r().
String wblut.math.WB_Complex.toString ()
Member Data Documentation
double wblut.math.WB_Complex.im private
double wblut.math.WB_Complex.re private
The documentation for this class was generated from the following file:
src/math/wblut/math/WB_Complex.java