HE_Mesh: wblut.geom.WB_DefaultMap2D Class Reference
wblut.geom.WB_DefaultMap2D Class Reference
Public Member Functions
WB_DefaultMap2D ()
void mapPoint3D (final WB_Coord p, final WB_MutableCoord result)
void mapPoint3D (final double x, final double y, final double z, final WB_MutableCoord result)
void unmapPoint3D (final WB_Coord p, final WB_MutableCoord result)
void unmapPoint3D (final double u, final double v, final double w, final WB_MutableCoord result)
void unmapPoint2D (final double u, final double v, final WB_MutableCoord result)
void unmapPoint2D (final WB_Coord p, final WB_MutableCoord result)
void mapVector3D (final WB_Coord v, final WB_MutableCoord result)
void mapVector3D (final double x, final double y, final double z, final WB_MutableCoord result)
void unmapVector3D (final WB_Coord v, final WB_MutableCoord result)
void unmapVector3D (final double u, final double v, final double w, final WB_MutableCoord result)
void unmapVector2D (final double u, final double v, final WB_MutableCoord result)
void unmapVector2D (final WB_Coord v, final WB_MutableCoord result)
WB_Point mapPoint3D (final WB_Coord p)
WB_Point mapPoint3D (final double x, final double y, final double z)
WB_Point unmapPoint3D (final WB_Coord p)
WB_Point unmapPoint3D (final double u, final double v, final double w)
WB_Point unmapPoint2D (final double u, final double v)
WB_Point unmapPoint2D (final WB_Coord p)
WB_Vector mapVector3D (final WB_Coord v)
WB_Vector mapVector3D (final double x, final double y, final double z)
WB_Vector unmapVector3D (final WB_Coord v)
WB_Vector unmapVector3D (final double u, final double v, final double w)
WB_Vector unmapVector2D (final double u, final double v)
WB_Vector unmapVector2D (final WB_Coord v)
Public Member Functions inherited from wblut.geom.WB_Map2D
void unmapPoint2D (WB_Coord p, WB_MutableCoord result)
void unmapPoint2D (double u, double v, WB_MutableCoord result)
void unmapVector2D (WB_Coord v, WB_MutableCoord result)
void unmapVector2D (double u, double v, WB_MutableCoord result)
WB_Coord unmapPoint2D (WB_Coord p)
WB_Coord unmapPoint2D (double u, double v)
WB_Coord unmapVector2D (WB_Coord v)
WB_Coord unmapVector2D (double u, double v)
Public Member Functions inherited from wblut.geom.WB_Map
void mapPoint3D (WB_Coord p, WB_MutableCoord result)
void mapPoint3D (double x, double y, double z, WB_MutableCoord result)
void unmapPoint3D (WB_Coord p, WB_MutableCoord result)
void unmapPoint3D (double u, double v, double w, WB_MutableCoord result)
void mapVector3D (WB_Coord p, WB_MutableCoord result)
void mapVector3D (double x, double y, double z, WB_MutableCoord result)
void unmapVector3D (WB_Coord p, WB_MutableCoord result)
void unmapVector3D (double u, double v, double w, WB_MutableCoord result)
WB_Coord mapPoint3D (WB_Coord p)
WB_Coord mapPoint3D (double x, double y, double z)
WB_Coord unmapPoint3D (WB_Coord p)
WB_Coord unmapPoint3D (double u, double v, double w)
WB_Coord mapVector3D (WB_Coord p)
WB_Coord mapVector3D (double x, double y, double z)
WB_Coord unmapVector3D (WB_Coord p)
WB_Coord unmapVector3D (double u, double v, double w)
Constructor & Destructor Documentation
wblut.geom.WB_DefaultMap2D.WB_DefaultMap2D ()
Member Function Documentation
void wblut.geom.WB_DefaultMap2D.mapPoint3D (final WB_Coord p, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_DefaultMap2D.mapPoint3D (final double x, final double y, final double z, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set().
WB_Point wblut.geom.WB_DefaultMap2D.mapPoint3D (final WB_Coord p)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_DefaultMap2D.mapPoint3D (final double x, final double y, final double z)
References wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_DefaultMap2D.mapVector3D (final WB_Coord v, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_DefaultMap2D.mapVector3D (final double x, final double y, final double z, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set().
WB_Vector wblut.geom.WB_DefaultMap2D.mapVector3D (final WB_Coord v)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_DefaultMap2D.mapVector3D (final double x, final double y, final double z)
References wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_DefaultMap2D.unmapPoint2D (final double u, final double v, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_DefaultMap2D.unmapPoint2D (final WB_Coord p, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
WB_Point wblut.geom.WB_DefaultMap2D.unmapPoint2D (final double u, final double v)
References wblut.geom.WB_MutableCoordinate.set().
WB_Point wblut.geom.WB_DefaultMap2D.unmapPoint2D (final WB_Coord p)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
void wblut.geom.WB_DefaultMap2D.unmapPoint3D (final WB_Coord p, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_DefaultMap2D.unmapPoint3D (final double u, final double v, final double w, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set().
WB_Point wblut.geom.WB_DefaultMap2D.unmapPoint3D (final WB_Coord p)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_DefaultMap2D.unmapPoint3D (final double u, final double v, final double w)
References wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_DefaultMap2D.unmapVector2D (final double u, final double v, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_DefaultMap2D.unmapVector2D (final WB_Coord v, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
WB_Vector wblut.geom.WB_DefaultMap2D.unmapVector2D (final double u, final double v)
References wblut.geom.WB_MutableCoordinate.set().
WB_Vector wblut.geom.WB_DefaultMap2D.unmapVector2D (final WB_Coord v)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
void wblut.geom.WB_DefaultMap2D.unmapVector3D (final WB_Coord v, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
void wblut.geom.WB_DefaultMap2D.unmapVector3D (final double u, final double v, final double w, final WB_MutableCoord result)
References wblut.geom.WB_MutableCoord.set().
WB_Vector wblut.geom.WB_DefaultMap2D.unmapVector3D (final WB_Coord v)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_DefaultMap2D.unmapVector3D (final double u, final double v, final double w)
References wblut.geom.WB_MutableCoordinate.set().
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_DefaultMap2D.java