HE_Mesh: wblut.hemesh.HEC_VoronoiCell Class Reference
wblut.hemesh.HEC_VoronoiCell Class Reference
Public Member Functions
HEC_VoronoiCell ()
HEC_VoronoiCell setPoints (final WB_Coord[] points)
HEC_VoronoiCell setPoints (final Collection<?extends WB_Coord > points)
HEC_VoronoiCell setPoints (final double[][] points)
HEC_VoronoiCell setPoints (final float[][] points)
HEC_VoronoiCell setPointsToUse (final int[] pointsToUse)
HEC_VoronoiCell setPointsToUse (final ArrayList< Integer > pointsToUse)
HEC_VoronoiCell setCellIndex (final int i)
HEC_VoronoiCell setOffset (final double o)
HEC_VoronoiCell setOffset (final WB_ScalarParameter o)
HEC_VoronoiCell setContainer (final HE_Mesh container)
HEC_VoronoiCell setLimitPoints (final boolean b)
HEC_VoronoiCell setSurface (final boolean b)
HE_Mesh createBase ()
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Public Attributes
HE_Selection inner
HE_Selection outer
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Private Attributes
WB_Coord[] points
int numberOfPoints
int[] pointsToUse
int cellIndex
HE_Mesh container
boolean surface
WB_ScalarParameter offset
boolean limitPoints
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Creates the Voronoi cell of one point in a collection of points, constrained by a mesh.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_VoronoiCell.HEC_VoronoiCell ()
Instantiates a new HEC_VoronoiCell.
References wblut.math.WB_ScalarParameter.ZERO.
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_VoronoiCell.createBase ()
References wblut.hemesh.HE_Selection.add(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HEM_MultiSlice.applySelf(), wblut.hemesh.HEC_VoronoiCell.cellIndex, wblut.hemesh.HEC_VoronoiCell.container, wblut.hemesh.HE_Mesh.copy(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Selection.fItr(), wblut.hemesh.HE_Selection.getNumberOfFaces(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.geom.WB_Vector.mul(), wblut.geom.WB_Point.mulSelf(), wblut.hemesh.HE_FaceIterator.next(), wblut.geom.WB_Vector.normalizeSelf(), wblut.hemesh.HEC_VoronoiCell.numberOfPoints, wblut.hemesh.HEM_MultiSlice.origFaces, wblut.hemesh.HE_Mesh.selectFacesWithInternalLabel(), wblut.geom.WB_MutableCoordinate.set(), wblut.hemesh.HEM_MultiSlice.setCap(), wblut.hemesh.HEM_MultiSlice.setCenter(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HEM_MultiSlice.setLabels(), wblut.hemesh.HEM_MultiSlice.setPlanes(), wblut.hemesh.HE_Element.setUserLabel(), wblut.geom.WB_Vector.subSelf(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
HEC_VoronoiCell wblut.hemesh.HEC_VoronoiCell.setCellIndex (final int i)
Set index of cell to create.
Parameters
i index
Returns
self
HEC_VoronoiCell wblut.hemesh.HEC_VoronoiCell.setContainer (final HE_Mesh container)
Set enclosing mesh limiting cells.
Parameters
container enclosing mesh
Returns
self
References wblut.hemesh.HEC_VoronoiCell.container.
HEC_VoronoiCell wblut.hemesh.HEC_VoronoiCell.setLimitPoints (final boolean b)
Limit the points considered to those indices specified in the pointsToUseArray.
Parameters
b true, false
Returns
self
HEC_VoronoiCell wblut.hemesh.HEC_VoronoiCell.setOffset (final double o)
Set voronoi cell offset.
Parameters
o offset
Returns
self
HEC_VoronoiCell wblut.hemesh.HEC_VoronoiCell.setOffset (final WB_ScalarParameter o)
Set voronoi cell offset.
Parameters
o offset
Returns
self
HEC_VoronoiCell wblut.hemesh.HEC_VoronoiCell.setPoints (final WB_Coord[] points)
Set points that define cell centers.
Parameters
points array of vertex positions
Returns
self
References wblut.hemesh.HEC_VoronoiCell.points.
HEC_VoronoiCell wblut.hemesh.HEC_VoronoiCell.setPoints (final Collection<?extends WB_Coord > points)
HEC_VoronoiCell wblut.hemesh.HEC_VoronoiCell.setPoints (final double points[][])
Set points that define cell centers.
Parameters
points 2D array of double of vertex positions
Returns
self
HEC_VoronoiCell wblut.hemesh.HEC_VoronoiCell.setPoints (final float points[][])
Set points that define cell centers.
Parameters
points 2D array of float of vertex positions
Returns
self
HEC_VoronoiCell wblut.hemesh.HEC_VoronoiCell.setPointsToUse (final int[] pointsToUse)
Sets the points to use.
Parameters
pointsToUse the points to use
Returns
the hE c_ voronoi cell
References wblut.hemesh.HEC_VoronoiCell.pointsToUse.
HEC_VoronoiCell wblut.hemesh.HEC_VoronoiCell.setPointsToUse (final ArrayList< Integer > pointsToUse)
Sets the points to use.
Parameters
pointsToUse the points to use
Returns
the hE c_ voronoi cell
HEC_VoronoiCell wblut.hemesh.HEC_VoronoiCell.setSurface (final boolean b)
Set optional surface mesh mode.
Parameters
b true, false
Returns
self
Member Data Documentation
int wblut.hemesh.HEC_VoronoiCell.cellIndex private
Cell index.
HE_Mesh wblut.hemesh.HEC_VoronoiCell.container private
Container.
HE_Selection wblut.hemesh.HEC_VoronoiCell.inner
Faces fully interior to cell.
boolean wblut.hemesh.HEC_VoronoiCell.limitPoints private
The limit points.
int wblut.hemesh.HEC_VoronoiCell.numberOfPoints private
Number of points.
WB_ScalarParameter wblut.hemesh.HEC_VoronoiCell.offset private
Offset.
HE_Selection wblut.hemesh.HEC_VoronoiCell.outer
Faces part of container.
WB_Coord [] wblut.hemesh.HEC_VoronoiCell.points private
Points.
int [] wblut.hemesh.HEC_VoronoiCell.pointsToUse private
Use specific subselection of points.
boolean wblut.hemesh.HEC_VoronoiCell.surface private
Treat container as surface?.
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_VoronoiCell.java