HE_Mesh: wblut.geom.WB_OctreeInteger Class Reference
wblut.geom.WB_OctreeInteger Class Reference
Classes
class WB_OctreeIntegerEntry
Public Member Functions
WB_OctreeInteger (final WB_Coord center, final double size)
void addPoint (final WB_Coord p, final int value)
void addAll (final Collection<?extends WB_Coord > points)
void clear ()
int getLevel ()
WB_OctreeInteger getNode (final WB_Coord p)
double getMinNodeSize ()
int getNumNodes ()
WB_Coord getCenter ()
WB_OctreeInteger getParent ()
int getNumberOfPoints ()
List< WB_OctreeInteger > getNodes ()
double getSize ()
boolean remove (final WB_Coord p)
void removeAll (final Collection< WB_Coord > points)
void setMinNodeSize (final double minNodeSize)
void setAutoPrune (final boolean state)
WB_AABB getBox ()
List< WB_OctreeIntegerEntry > getEntries ()
List< WB_OctreeIntegerEntry > getEntriesInRange (final WB_AABB AABB)
List< WB_OctreeIntegerEntry > getEntriesInRange (final WB_Sphere sphere)
List< WB_OctreeIntegerEntry > getEntriesInRange (final WB_Coord center, final double radius)
List< WB_Coord > getPoints ()
List< WB_Coord > getPointsInRange (final WB_AABB AABB)
List< WB_Coord > getPointsInRange (final WB_Sphere sphere)
List< WB_Coord > getPointsInRange (final WB_Coord center, final double radius)
int[] getValues ()
int[] getValuesInRange (final WB_AABB AABB)
int[] getValuesInRange (final WB_Sphere sphere)
int[] getValuesInRange (final WB_Coord center, final double radius)
Static Public Member Functions
static void main (final String[] args)
Protected Member Functions
final int getOctant (final WB_Coord p)
Protected Attributes
WB_AABB box
WB_Coord extent
WB_Coord min
double minNodeSize = 4.0
WB_OctreeInteger parent
WB_OctreeInteger[] nodes
int numNodes
List< WB_OctreeIntegerEntry > entries
double size
WB_Coord center
Private Member Functions
WB_OctreeInteger (final WB_OctreeInteger p, final WB_Coord center, final double size)
void prune ()
Private Attributes
int level = 0
boolean autoPrune = false
Constructor & Destructor Documentation
wblut.geom.WB_OctreeInteger.WB_OctreeInteger (final WB_OctreeInteger p, final WB_Coord center, final double size) private
References wblut.geom.WB_OctreeInteger.level, wblut.geom.WB_OctreeInteger.minNodeSize, and wblut.geom.WB_OctreeInteger.size.
wblut.geom.WB_OctreeInteger.WB_OctreeInteger (final WB_Coord center, final double size)
References wblut.geom.WB_OctreeInteger.size.
Member Function Documentation
void wblut.geom.WB_OctreeInteger.addAll (final Collection<?extends WB_Coord > points)
References wblut.geom.WB_OctreeInteger.addPoint().
void wblut.geom.WB_OctreeInteger.addPoint (final WB_Coord p, final int value)
References wblut.geom.WB_Point.add(), wblut.geom.WB_OctreeInteger.addPoint(), wblut.geom.WB_AABB.contains(), wblut.geom.WB_OctreeInteger.getOctant(), and wblut.geom.WB_OctreeInteger.WB_OctreeInteger().
void wblut.geom.WB_OctreeInteger.clear ()
WB_AABB wblut.geom.WB_OctreeInteger.getBox ()
References wblut.geom.WB_OctreeInteger.box.
WB_Coord wblut.geom.WB_OctreeInteger.getCenter ()
References wblut.geom.WB_OctreeInteger.center.
List<WB_OctreeIntegerEntry> wblut.geom.WB_OctreeInteger.getEntries ()
References wblut.geom.WB_OctreeInteger.getEntries().
List<WB_OctreeIntegerEntry> wblut.geom.WB_OctreeInteger.getEntriesInRange (final WB_AABB AABB)
References wblut.geom.WB_AABB.contains(), wblut.geom.WB_OctreeInteger.getEntriesInRange(), and wblut.geom.WB_AABB.intersects().
List<WB_OctreeIntegerEntry> wblut.geom.WB_OctreeInteger.getEntriesInRange (final WB_Sphere sphere)
References wblut.geom.WB_Sphere.contains(), wblut.geom.WB_OctreeInteger.getEntriesInRange(), and wblut.geom.WB_AABB.intersects().
List<WB_OctreeIntegerEntry> wblut.geom.WB_OctreeInteger.getEntriesInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_OctreeInteger.getEntriesInRange().
int wblut.geom.WB_OctreeInteger.getLevel ()
References wblut.geom.WB_OctreeInteger.level.
double wblut.geom.WB_OctreeInteger.getMinNodeSize ()
References wblut.geom.WB_OctreeInteger.minNodeSize.
WB_OctreeInteger wblut.geom.WB_OctreeInteger.getNode (final WB_Coord p)
References wblut.geom.WB_AABB.contains(), wblut.geom.WB_OctreeInteger.getNode(), and wblut.geom.WB_OctreeInteger.getOctant().
List<WB_OctreeInteger> wblut.geom.WB_OctreeInteger.getNodes ()
int wblut.geom.WB_OctreeInteger.getNumberOfPoints ()
int wblut.geom.WB_OctreeInteger.getNumNodes ()
References wblut.geom.WB_OctreeInteger.numNodes.
final int wblut.geom.WB_OctreeInteger.getOctant (final WB_Coord p) protected
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_OctreeInteger wblut.geom.WB_OctreeInteger.getParent ()
References wblut.geom.WB_OctreeInteger.parent.
List<WB_Coord> wblut.geom.WB_OctreeInteger.getPoints ()
References wblut.geom.WB_OctreeInteger.getPoints().
List<WB_Coord> wblut.geom.WB_OctreeInteger.getPointsInRange (final WB_AABB AABB)
References wblut.geom.WB_OctreeInteger.getEntriesInRange().
List<WB_Coord> wblut.geom.WB_OctreeInteger.getPointsInRange (final WB_Sphere sphere)
References wblut.geom.WB_OctreeInteger.getEntriesInRange().
List<WB_Coord> wblut.geom.WB_OctreeInteger.getPointsInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_OctreeInteger.getPointsInRange().
double wblut.geom.WB_OctreeInteger.getSize ()
References wblut.geom.WB_OctreeInteger.size.
int [] wblut.geom.WB_OctreeInteger.getValues ()
References wblut.geom.WB_OctreeInteger.getEntries().
int [] wblut.geom.WB_OctreeInteger.getValuesInRange (final WB_AABB AABB)
References wblut.geom.WB_OctreeInteger.getEntriesInRange().
int [] wblut.geom.WB_OctreeInteger.getValuesInRange (final WB_Sphere sphere)
References wblut.geom.WB_OctreeInteger.getEntriesInRange().
int [] wblut.geom.WB_OctreeInteger.getValuesInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_OctreeInteger.getValuesInRange().
static void wblut.geom.WB_OctreeInteger.main (final String[] args) static
References wblut.geom.WB_OctreeInteger.addAll(), wblut.geom.WB_OctreeInteger.getPointsInRange(), wblut.geom.WB_RandomBox.setOffset(), wblut.geom.WB_RandomBox.setSize(), and wblut.geom.WB_OctreeInteger.WB_OctreeInteger().
void wblut.geom.WB_OctreeInteger.prune () private
References wblut.geom.WB_OctreeInteger.prune().
boolean wblut.geom.WB_OctreeInteger.remove (final WB_Coord p)
References wblut.geom.WB_OctreeInteger.WB_OctreeIntegerEntry.coord, wblut.geom.WB_OctreeInteger.entries, wblut.geom.WB_OctreeInteger.getNode(), and wblut.geom.WB_OctreeInteger.prune().
void wblut.geom.WB_OctreeInteger.removeAll (final Collection< WB_Coord > points)
void wblut.geom.WB_OctreeInteger.setAutoPrune (final boolean state)
void wblut.geom.WB_OctreeInteger.setMinNodeSize (final double minNodeSize)
Member Data Documentation
boolean wblut.geom.WB_OctreeInteger.autoPrune = false private
WB_AABB wblut.geom.WB_OctreeInteger.box protected
WB_Coord wblut.geom.WB_OctreeInteger.center protected
List<WB_OctreeIntegerEntry> wblut.geom.WB_OctreeInteger.entries protected
WB_Coord wblut.geom.WB_OctreeInteger.extent protected
int wblut.geom.WB_OctreeInteger.level = 0 private
WB_Coord wblut.geom.WB_OctreeInteger.min protected
double wblut.geom.WB_OctreeInteger.minNodeSize = 4.0 protected
WB_OctreeInteger [] wblut.geom.WB_OctreeInteger.nodes protected
int wblut.geom.WB_OctreeInteger.numNodes protected
WB_OctreeInteger wblut.geom.WB_OctreeInteger.parent protected
double wblut.geom.WB_OctreeInteger.size protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_OctreeInteger.java