HE_Mesh: wblut.hemesh.HEC_FromNetwork Class Reference
wblut.hemesh.HEC_FromNetwork Class Reference
Classes
class NodeConnection
enum NodeType
Public Member Functions
HEC_FromNetwork ()
HEC_FromNetwork setConnectionRadius (final double r)
HEC_FromNetwork setConnectionRadius (final WB_ScalarParameter r)
HEC_FromNetwork setMaximumConnectionOffset (final WB_ScalarParameter o)
HEC_FromNetwork setMaximumConnectionOffset (final double o)
HEC_FromNetwork setMinimumBalljointAngle (final double a)
HEC_FromNetwork setMaximumConnectionLength (final double d)
HEC_FromNetwork setConnectionFacets (final int f)
HEC_FromNetwork setTaper (final boolean b)
HEC_FromNetwork setCap (final boolean b)
HEC_FromNetwork setSuppressBalljoint (final boolean b)
HEC_FromNetwork setUseNodeValues (final boolean b)
HEC_FromNetwork setCreateIsolatedNodes (final boolean b)
HEC_FromNetwork setFidget (final double f)
HEC_FromNetwork setFillFactor (final double ff)
HEC_FromNetwork setAngleOffset (final double af)
HEC_FromNetwork setAngleOffset (final WB_ScalarParameter af)
HEC_FromNetwork setNetwork (final WB_Network network)
HEC_FromNetwork setNetwork (final HE_Mesh mesh)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Member Functions
void getNodeTypes ()
void getNodeConnections ()
void createNodeConnection (final Node node, final int i, final double maxoff, final double off, final double rad)
void createVertices ()
int getConnectionIndex (final Node node, final Connection connection)
void createConnections ()
void createNodes ()
Private Attributes
WB_Network network
int numberOfNodes
NodeType[] nodeTypes
NodeConnection[] connectionNodeConnections
WB_ScalarParameter connectionRadius
int connectionFacets
double fidget
double fillfactor
HE_Mesh mesh
double maximumConnectionLength
double minimumBalljointAngle
WB_ScalarParameter maximumConnectionOffset
boolean taper
boolean cap
boolean useNodeValues
boolean createIsolatedNodes
WB_ScalarParameter angleFactor
boolean suppressBalljoint
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Constructor & Destructor Documentation
wblut.hemesh.HEC_FromNetwork.HEC_FromNetwork ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_FromNetwork.createBase () protected
References wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HEC_FromNetwork.createConnections(), wblut.hemesh.HEC_FromNetwork.createNodes(), wblut.hemesh.HEC_FromNetwork.createVertices(), wblut.hemesh.HEC_FromNetwork.getNodeConnections(), wblut.hemesh.HEC_FromNetwork.getNodeTypes(), wblut.geom.WB_Network.getNumberOfConnections(), wblut.geom.WB_Network.getNumberOfNodes(), wblut.hemesh.HEC_FromNetwork.mesh, wblut.hemesh.HEC_FromNetwork.numberOfNodes, and wblut.hemesh.HE_Mesh.pairHalfedges().
void wblut.hemesh.HEC_FromNetwork.createConnections () private
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HEC_FromNetwork.connectionFacets, wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.geom.WB_Network.getConnections(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HEC_FromNetwork.maximumConnectionLength, wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setVertex().
void wblut.hemesh.HEC_FromNetwork.createNodeConnection (final Node node, final int i, final double maxoff, final double off, final double rad) private
Parameters
node
i
maxoff
off
rad
References wblut.geom.WB_Network.Node.getConnection(), and wblut.hemesh.HEC_FromNetwork.getConnectionIndex().
void wblut.hemesh.HEC_FromNetwork.createNodes () private
References wblut.hemesh.HE_Mesh.add(), wblut.geom.WB_Vector.addSelf(), wblut.hemesh.HE_Mesh.addVertices(), wblut.hemesh.HE_Mesh.cleanUnusedElementsByFace(), wblut.hemesh.HEC_FromNetwork.connectionFacets, wblut.hemesh.HE_Mesh.deleteFace(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HEC_FromNetwork.fillfactor, wblut.hemesh.HE_Mesh.fItr(), wblut.geom.WB_Network.Node.getConnections(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.geom.WB_Network.getNode(), wblut.geom.WB_Network.getNodes(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Mesh.getVertices(), wblut.hemesh.HE_Mesh.heItr(), wblut.hemesh.HE_Vertex.key(), wblut.geom.WB_Vector.mulSelf(), wblut.hemesh.HEC_Creator.setCenter(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HEC_ConvexHull.setPointsFromVertices(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HE_Mesh.uncapBoundaryHalfedges(), and wblut.hemesh.HEC_ConvexHull.vertexToPointIndex.
void wblut.hemesh.HEC_FromNetwork.createVertices () private
References wblut.hemesh.HE_Mesh.add(), wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HEC_FromNetwork.connectionFacets, wblut.geom.WB_Vector.copy(), wblut.math.WB_ScalarParameter.evaluate(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Network.getNumberOfConnections(), wblut.geom.WB_Plane.getU(), wblut.geom.WB_Vector.mul(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Vector.rotateAboutAxisSelf(), and wblut.hemesh.HE_Element.setInternalLabel().
int wblut.hemesh.HEC_FromNetwork.getConnectionIndex (final Node node, final Connection connection) private
Parameters
node
connection
Returns
References wblut.geom.WB_Network.Connection.getIndex(), and wblut.geom.WB_Network.Connection.start.
void wblut.hemesh.HEC_FromNetwork.getNodeConnections () private
References wblut.hemesh.HEC_FromNetwork.createNodeConnection(), wblut.math.WB_ScalarParameter.evaluate(), wblut.geom.WB_Network.getNodes(), and wblut.geom.WB_Network.getNumberOfConnections().
void wblut.hemesh.HEC_FromNetwork.getNodeTypes () private
References wblut.geom.WB_Network.getNodes().
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setAngleOffset (final double af)
Parameters
af
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setAngleOffset (final WB_ScalarParameter af)
Parameters
af
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setCap (final boolean b)
Parameters
b
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setConnectionFacets (final int f)
Parameters
f
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setConnectionRadius (final double r)
Parameters
r
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setConnectionRadius (final WB_ScalarParameter r)
Parameters
r
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setCreateIsolatedNodes (final boolean b)
Parameters
b
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setFidget (final double f)
Parameters
f
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setFillFactor (final double ff)
Parameters
ff
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setMaximumConnectionLength (final double d)
Parameters
d
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setMaximumConnectionOffset (final WB_ScalarParameter o)
Parameters
o
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setMaximumConnectionOffset (final double o)
Parameters
o
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setMinimumBalljointAngle (final double a)
Parameters
a
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setNetwork (final WB_Network network)
Parameters
network
Returns
References wblut.hemesh.HEC_FromNetwork.network.
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setNetwork (final HE_Mesh mesh)
Parameters
mesh
Returns
References wblut.hemesh.HE_Mesh.getNetwork().
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setSuppressBalljoint (final boolean b)
Parameters
b
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setTaper (final boolean b)
Parameters
b
Returns
HEC_FromNetwork wblut.hemesh.HEC_FromNetwork.setUseNodeValues (final boolean b)
Parameters
b
Returns
Member Data Documentation
WB_ScalarParameter wblut.hemesh.HEC_FromNetwork.angleFactor private
boolean wblut.hemesh.HEC_FromNetwork.cap private
int wblut.hemesh.HEC_FromNetwork.connectionFacets private
NodeConnection [] wblut.hemesh.HEC_FromNetwork.connectionNodeConnections private
WB_ScalarParameter wblut.hemesh.HEC_FromNetwork.connectionRadius private
boolean wblut.hemesh.HEC_FromNetwork.createIsolatedNodes private
double wblut.hemesh.HEC_FromNetwork.fidget private
double wblut.hemesh.HEC_FromNetwork.fillfactor private
WB_GeometryFactory wblut.hemesh.HEC_FromNetwork.gf = new WB_GeometryFactory() static private
double wblut.hemesh.HEC_FromNetwork.maximumConnectionLength private
WB_ScalarParameter wblut.hemesh.HEC_FromNetwork.maximumConnectionOffset private
HE_Mesh wblut.hemesh.HEC_FromNetwork.mesh private
double wblut.hemesh.HEC_FromNetwork.minimumBalljointAngle private
WB_Network wblut.hemesh.HEC_FromNetwork.network private
NodeType [] wblut.hemesh.HEC_FromNetwork.nodeTypes private
int wblut.hemesh.HEC_FromNetwork.numberOfNodes private
boolean wblut.hemesh.HEC_FromNetwork.suppressBalljoint private
boolean wblut.hemesh.HEC_FromNetwork.taper private
boolean wblut.hemesh.HEC_FromNetwork.useNodeValues private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_FromNetwork.java