HE_Mesh: wblut.geom.WB_GeometryFactory3D Class Reference
wblut.geom.WB_GeometryFactory3D Class Reference
Public Member Functions
WB_GeometryFactory3D ()
WB_Point origin ()
WB_Vector X ()
WB_Vector Y ()
WB_Vector Z ()
WB_Vector minX ()
WB_Vector minY ()
WB_Vector minZ ()
WB_Plane XY ()
WB_Plane YZ ()
WB_Plane ZX ()
WB_Plane YX ()
WB_Plane ZY ()
WB_Plane XZ ()
WB_CoordinateSystem3D createCSFromOX (final WB_Coord origin, final WB_Coord X)
WB_CoordinateSystem3D createCSFromOX (final WB_Coord origin, final WB_Coord X, final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D createCSFromOXY (final WB_Coord origin, final WB_Coord X, final WB_Coord Y)
WB_CoordinateSystem3D createCSFromOXY (final WB_Coord origin, final WB_Coord X, final WB_Coord Y, final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D createCSFromOXYZ (final WB_Coord origin, final WB_Coord X, final WB_Coord Y, final WB_Coord Z, final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D createCSFromOXYZ (final WB_Coord origin, final WB_Coord X, final WB_Coord Y, final WB_Coord Z)
WB_Map2D createEmbeddedPlane ()
WB_Map2D createEmbeddedPlane (final int mode, final double offset)
WB_Map2D createEmbeddedPlane (final int mode)
WB_Map2D createEmbeddedPlane (final WB_Plane P, final double offset)
WB_Map2D createEmbeddedPlane (final WB_Plane P)
WB_Point createPoint ()
WB_Point createPoint (final WB_Coord p)
WB_Point createPoint (final double[] p)
WB_Point createPoint (final double _x, final double _y)
WB_Point createPoint (final double _x, final double _y, final double _z)
WB_Point createPoint (final Coordinate coord)
WB_Point createInterpolatedPoint (final WB_Coord p, final WB_Coord q, final double f)
WB_Point createIncenter (final WB_Triangle tri)
WB_Point createOrthocenter (final WB_Triangle tri)
WB_Point createPointFromBarycentricCoordinates (final double u, final double v, final double w, final WB_Triangle tri)
WB_Point createPointFromCylindrical (final double r, final double phi, final double z)
WB_Point createPointFromSpherical (final double r, final double theta, final double phi)
WB_Point createPointFromParaboloidal (final double sigma, final double tau, final double phi)
WB_Point createPointFromParabolic (final double sigma, final double tau, final double z)
WB_Point createPointFromOblateSpheroidal (final double a, final double mu, final double nu, final double phi)
WB_Point createPointFromProlateSpheroidal (final double a, final double mu, final double nu, final double phi)
WB_Point createPointFromEllipsoidal (final double a, final double b, final double c, final double lambda, final double mu, final double nu)
WB_Point createPointFromElliptic (final double a, final double mu, final double nu, final double z)
WB_Point createPointFromToroidal (final double a, final double sigma, final double tau, final double phi)
WB_Point createPointFromBispherical (final double a, final double sigma, final double tau, final double phi)
WB_Point createPointFromBipolarCylindrical (final double a, final double sigma, final double tau, final double z)
WB_Point createPointFromConical (final double b, final double c, final double r, final double mu, final double nu)
WB_Point createCentroid (final WB_Triangle tri)
WB_Point createCentroid (final WB_Coord...points)
WB_Point createCircumcenter (final WB_Triangle tri)
WB_Point createPointFromTrilinearCoordinates (final double u, final double v, final double w, final WB_Triangle tri)
WB_Point createMidpoint (final WB_Coord p, final WB_Coord q)
WB_Point createMidpoint (final WB_Coord...p)
WB_Vector createVector ()
WB_Vector createVectorFromTo (final WB_Coord p, final WB_Coord q)
final WB_Vector createVector (final WB_Coord p)
WB_Vector createVector (final double _x, final double _y)
WB_Vector createVector (final double _x, final double _y, final double _z)
WB_Vector createNormalizedVector (final WB_Coord p)
WB_Vector createNormalizedVectorFromTo (final WB_Coord p, final WB_Coord q)
WB_Vector createNormalizedVector (final double _x, final double _y, final double _z)
WB_Vector createNormalizedVector (final double _x, final double _y, final double _z, final double _w)
WB_Vector createNormalizedVector (final double _x, final double _y)
WB_Vector createNormalizedPerpendicularVector (final double _x, final double _y)
WB_Vector createNormalizedPerpendicularVector (final double _x, final double _y, final double _z)
WB_Vector createNormalizedPerpendicularVector (final WB_Coord p)
WB_Vector createVectorFromCylindrical (final double r, final double phi, final double z)
WB_Vector createVectorFromSpherical (final double r, final double theta, final double phi)
WB_Vector createVectorFromParaboloidal (final double sigma, final double tau, final double phi)
WB_Vector createVectorFromParabolic (final double sigma, final double tau, final double z)
WB_Vector createVectorFromOblateSpheroidal (final double a, final double mu, final double nu, final double phi)
WB_Vector createVectorFromProlateSpheroidal (final double a, final double mu, final double nu, final double phi)
WB_Vector createVectorFromEllipsoidal (final double a, final double b, final double c, final double lambda, final double mu, final double nu)
WB_Vector createVectorFromElliptic (final double a, final double mu, final double nu, final double z)
WB_Vector createVectorFromToroidal (final double a, final double sigma, final double tau, final double phi)
WB_Vector createVectorFromBispherical (final double a, final double sigma, final double tau, final double phi)
WB_Vector createVectorFromBipolarCylindrical (final double a, final double sigma, final double tau, final double z)
WB_Vector createVectorFromConical (final double b, final double c, final double r, final double mu, final double nu)
WB_Line createLineThroughPoints (final WB_Coord p1, final WB_Coord p2)
WB_Line createLineThroughPoints (final double x1, final double y1, final double x2, final double y2)
WB_Line createLineThroughPoints (final double x1, final double y1, final double z1, final double x2, final double y2, final double z2)
WB_Line createLineWithDirection (final WB_Coord origin, final WB_Coord direction)
WB_Line createLineWithDirection (final double ox, final double oy, final double oz, final double dx, final double dy, final double dz)
WB_Line createParallelLineThroughPoint (final WB_Line L, final WB_Coord p)
WB_Plane createBisector (final WB_Coord p, final WB_Coord q)
WB_Ray createRayThroughPoints (final WB_Coord p1, final WB_Coord p2)
WB_Ray createRayThroughPoints (final double x1, final double y1, final double x2, final double y2)
WB_Ray createRayThroughPoints (final double x1, final double y1, final double z1, final double x2, final double y2, final double z2)
WB_Ray createRayWithDirection (final WB_Coord origin, final WB_Coord direction)
WB_Ray createRayWithDirection (final double ox, final double oy, final double oz, final double dx, final double dy, final double dz)
WB_Ray createParallelRayThroughPoint (final WB_Line L, final WB_Coord p)
WB_Segment createSegment (final WB_Coord p1, final WB_Coord p2)
WB_Segment createSegmentWithLength (final WB_Coord origin, final WB_Coord direction, final double length)
WB_Segment createSegment (final double x1, final double y1, final double x2, final double y2)
WB_Segment createSegmentWithLength (final double ox, final double oy, final double dx, final double dy, final double length)
WB_Segment createSegment (final double x1, final double y1, final double z1, final double x2, final double y2, final double z2)
WB_Segment createSegmentWithLength (final double ox, final double oy, final double oz, final double dx, final double dy, final double dz, final double length)
WB_Polygon createPolygonFromJTSPolygon (final Polygon JTSpoly, final WB_Map2D map)
WB_Polygon[] splitSimplePolygon (final WB_Polygon poly, final WB_Plane P)
WB_Triangle createTriangle (final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z, final double p3x, final double p3y, final double p3z)
WB_Triangle createTriangle (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
WB_Circle createInversionCircle (final WB_Circle C, final WB_Circle inversionCircle)
WB_Circle createCircumcircle3D (final WB_Triangle tri)
WB_Circle createIncircle (final WB_Triangle tri)
WB_Plane createPlane (final WB_Coord origin, final WB_Coord normal)
WB_Plane createPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
WB_Plane createPlane (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
WB_Plane createPlane (final WB_Triangle T)
WB_Plane createFlippedPlane (final WB_Plane P)
WB_Plane createOffsetPlane (final WB_Coord origin, final WB_Coord normal, final double offset)
WB_Plane createOffsetPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz, final double offset)
WB_Plane createOffsetPlane (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final double offset)
WB_Mesh createMesh (final WB_Coord[] points, final int[][] faces)
WB_Mesh createMesh (final Collection<?extends WB_Coord > points, final int[][] faces)
WB_Mesh createMesh (final WB_AABB aabb)
WB_Mesh createUniqueMesh (final WB_Mesh mesh)
WB_Mesh createUniqueMesh (final WB_Mesh mesh, final double threshold)
WB_Mesh createTriMesh (final WB_Coord[] points, final int[][] faces)
WB_Mesh createTriMesh (final Collection<?extends WB_Coord > points, final int[][] faces)
WB_Mesh createTriMesh (final WB_Mesh mesh)
WB_Mesh createRegularPrism (final int n, final double radius, final double h)
WB_Mesh createPrism (final Collection<?extends WB_Coord > points, final double h)
WB_Mesh createPrismOpen (final Collection<?extends WB_Coord > points, final double h)
WB_Mesh createPrism (final WB_Coord[] points, final double h)
WB_Mesh createPrism (final WB_Polygon poly, final double h)
WB_Mesh createPrism (final WB_Polygon poly, final double h, final double offset)
WB_Mesh createMesh (final WB_Polygon poly)
WB_Mesh createMesh (final WB_Polygon poly, final double offset)
WB_Mesh createPrismOpen (final WB_Polygon poly, final double h)
WB_Mesh createRegularAntiPrism (final int n, final double radius, final double h)
WB_Mesh createAntiPrism (final Collection<?extends WB_Coord > points, final double h)
WB_Mesh createAntiPrism (final WB_Coord[] points, final double h)
WB_Mesh createAntiPrism (final WB_Polygon poly, final double h)
WB_Mesh createArchimedes (final int type, final double edgeLength)
WB_Mesh createCatalan (final int type, final double edgeLength)
WB_Mesh createJohnson (final int type, final double edgeLength)
WB_Mesh createOtherPolyhedron (final int type, final double edgeLength)
WB_Mesh createPlato (final int type, final double edgeLength)
WB_Mesh createPolyhedron (String name, final double radius)
WB_Mesh createZonohedron (final WB_Coord[] vectors, final double scale)
WB_Mesh createStellatedIcosahedron (final int type, final double radius)
WB_Mesh createDipyramidWithAngleRange (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final WB_Map2D context)
WB_Mesh createDipyramidWithAngleRange (final WB_Coord[] points, final double minangle, final double maxangle, final WB_Map2D context)
WB_Mesh createDipyramidWithAngle (final Collection<?extends WB_Coord > points, final double angle, final WB_Map2D context)
WB_Mesh createDipyramidWithAngle (final WB_Coord[] points, final double angle, final WB_Map2D context)
WB_Mesh createDipyramidWithAngle (final Collection<?extends WB_Coord > points, final double angle)
WB_Mesh createDipyramidWithAngle (final WB_Coord[] points, final double angle)
WB_Mesh createDipyramidWithHeight (final Collection<?extends WB_Coord > points, final double height, final WB_Map2D context)
WB_Mesh createDipyramidWithHeight (final WB_Coord[] points, final double height)
WB_Mesh createDipyramidWithHeight (final WB_Coord[] points, final double height, final WB_Map2D context)
WB_Mesh createDipyramidWithHeight (final Collection<?extends WB_Coord > points, final double height)
WB_Mesh createTaperWithAnglesAndHeight (final Collection<?extends WB_Coord > points, final double[] angles, final double height, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createTaperWithAnglesAndHeight (final WB_Coord[] points, final double angles[], final double height, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createTaperWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createTaperWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createTaperWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height, final WB_Map2D context)
WB_Mesh createTaperWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height, final WB_Map2D context)
WB_Mesh createTaperWithAngleAndHeight (final Collection<?extends WB_Coord > points, final double angle, final double height, final WB_Map2D context)
WB_Mesh createTaperWithAngleAndHeight (final WB_Coord[] points, final double angle, final double height, final WB_Map2D context)
WB_Mesh createTaperWithAngleAndHeight (final Collection<?extends WB_Coord > points, final double angle, final double height)
WB_Mesh createTaperWithAngleAndHeight (final WB_Coord[] points, final double angle, final double height)
WB_Mesh createBitaperWithAnglesAndHeight (final Collection<?extends WB_Coord > points, final double[] angles, final double height, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createBitaperWithAnglesAndHeight (final WB_Coord[] points, final double[] angles, final double height, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createBitaperWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createBitaperWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createBitaperWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height, final WB_Map2D context)
WB_Mesh createBitaperWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height, final WB_Map2D context)
WB_Mesh createBitaperWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height)
WB_Mesh createBitaperWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height)
WB_Mesh createBitaperWithAngleAndHeight (final Collection<?extends WB_Coord > points, final double angle, final double height, final WB_Map2D context)
WB_Mesh createBitaperWithAngleAndHeight (final WB_Coord[] points, final double angle, final double height, final WB_Map2D context)
WB_Mesh createBitaperWithAngleAndHeight (final Collection<?extends WB_Coord > points, final double angle, final double height)
WB_Mesh createBitaperWithAngleAndHeight (final WB_Coord[] points, final double angle, final double height)
WB_Mesh createCapsuleWithAnglesAndHeight (final Collection<?extends WB_Coord > points, final double[] angles, final double height, final double cap, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createCapsuleWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height, final double cap, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createCapsuleWithAngleAndHeight (final Collection<?extends WB_Coord > points, final double angle, final double height, final double cap, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createCapsuleWithAnglesAndHeight (final Collection<?extends WB_Coord > points, final double[] angles, final double height, final double cap)
WB_Mesh createCapsuleWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height, final double cap)
WB_Mesh createCapsuleWithAngleAndHeight (final Collection<?extends WB_Coord > points, final double angle, final double height, final double cap)
WB_Mesh createCapsuleWithAnglesAndHeight (final WB_Coord[] points, final double[] angles, final double height, final double cap, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createCapsuleWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height, final double cap, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createCapsuleWithAngleAndHeight (final WB_Coord[] points, final double angle, final double height, final double cap, final boolean b, final boolean t, final WB_Map2D context)
WB_Mesh createCapsuleWithAnglesAndHeight (final WB_Coord[] points, final double[] angles, final double height, final double cap)
WB_Mesh createCapsuleWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height, final double cap)
WB_Mesh createCapsuleWithAngleAndHeight (final WB_Coord[] points, final double angle, final double height, final double cap)
WB_Mesh createSpindle (final Collection<?extends WB_Coord > points, final double height, final double cap, final WB_Map2D context)
WB_Mesh createSpindle (final Collection<?extends WB_Coord > points, final double height, final double cap)
WB_Mesh createSpindle (final WB_Coord[] points, final double height, final double cap, final WB_Map2D context)
WB_Mesh createSpindle (final WB_Coord[] points, final double height, final double cap)
WB_Mesh createConvexHull (final List<?extends WB_Coord > points)
WB_Mesh createConvexHull (final WB_Coord[] points)
WB_Mesh createConvexHull (final WB_Coord[] points, final boolean triangulate)
WB_Mesh createConvexHull (final List<?extends WB_Coord > points, final boolean triangulate)
WB_Mesh createConvexHullWithThreshold (final WB_Coord[] points, final boolean triangulate, final double threshold)
WB_Mesh createConvexHullWithThreshold (final List<?extends WB_Coord > points, final boolean triangulate, final double threshold)
WB_Point createClosestPointOnTriangle (final WB_Coord p, final WB_Coord a, final WB_Coord b, final WB_Coord c)
WB_Point createClosestPointOnPolygon (final WB_Coord p, final WB_Polygon poly)
WB_Sphere createSphereWithRadius (final WB_Coord center, final double radius)
WB_Sphere createSphereWithDiameter (final WB_Coord center, final double diameter)
WB_Sphere createSphereWithRadius (final double x, final double y, final double z, final double radius)
WB_Sphere createSphereWithDiameter (final double x, final double y, final double z, final double diameter)
WB_Tetrahedron createTetrahedron (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4)
WB_Point getIntersection (final WB_Coord a, final WB_Coord b, final WB_Plane P)
WB_Polygon createPolygonConvexHull (final WB_Polygon poly)
List< WB_Polygon > createBufferedPolygons (final WB_Polygon poly, final double d)
List< WB_Polygon > createBufferedPolygons (final WB_Polygon poly, final double d, final int n)
List< WB_Polygon > createBufferedPolygonsStraight (final WB_Polygon poly, final double d)
List< WB_Polygon > createBufferedPolygons (final Collection<?extends WB_Polygon > poly, final double d)
List< WB_Polygon > createBufferedPolygons (final Collection<?extends WB_Polygon > poly, final double d, final int n)
List< WB_Polygon > createBufferedPolygonsStraight (final Collection<?extends WB_Polygon > poly, final double d)
List< WB_Polygon > createBoundaryPolygons (final WB_Polygon poly)
List< WB_Polygon > createRibbonPolygons (final WB_Polygon poly, final double d)
List< WB_Polygon > createRibbonPolygons (final Collection<?extends WB_Polygon > poly, final double d)
List< WB_Polygon > createRibbonPolygons (final WB_Polygon poly, final double o, final double i)
List< WB_Polygon > createRibbonPolygons (final Collection<?extends WB_Polygon > poly, final double o, final double i)
List< WB_Polygon > createSimplifiedPolygon (final WB_Polygon poly, final double tol)
List< WB_Polygon > createDensifiedPolygon (final WB_Polygon poly, final double max)
List< WB_Polygon > constrainPolygons (final WB_Polygon poly, final WB_Polygon container)
List< WB_Polygon > constrainPolygons (final WB_Polygon[] polygons, final WB_Polygon container)
List< WB_Polygon > constrainPolygons (final List< WB_Polygon > polygons, final WB_Polygon container)
List< WB_Coord > createUniquePoints (final List< WB_Coord > points, final double threshold)
List< WB_Plane > createUniquePlanes (final List< WB_Plane > planes)
Public Member Functions inherited from wblut.geom.WB_GeometryFactory2D
WB_GeometryFactory2D ()
WB_CoordinateSystem3D WORLD ()
WB_Coord origin2D ()
WB_Coord X2D ()
WB_Coord Y2D ()
WB_Coord minX2D ()
WB_Coord minY2D ()
WB_CoordinateSystem3D createCSFromOX2D (final WB_Coord origin, final WB_Coord X)
WB_CoordinateSystem3D createCSFromOX2D (final WB_Coord origin, final WB_Coord X, final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D createCSFromOXY2D (final WB_Coord origin, final WB_Coord X, final WB_Coord Y)
WB_CoordinateSystem3D createCSFromOXY2D (final WB_Coord origin, final WB_Coord X, final WB_Coord Y, final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D createTransformedCS (final WB_CoordinateSystem3D CS, final WB_Transform T, final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D createTransformedCS (final WB_CoordinateSystem3D CS, final WB_Transform T)
WB_Point createPoint2D ()
WB_Point createPoint2D (final WB_Coord p)
WB_Point createPoint2D (final double x, final double y)
WB_Point createPoint2D (final Coordinate coord)
WB_Point createInterpolatedPoint2D (final WB_Coord p, final WB_Coord q, final double f)
WB_Point createPointFromPolar (final double r, final double phi)
WB_Point createPointFromBipolar (final double a, final double sigma, final double tau)
WB_Point createPointFromParabolic (final double sigma, final double tau)
WB_Point createPointFromHyperbolic (final double u, final double v)
WB_Point createPointFromElliptic (final double a, final double sigma, final double tau)
WB_Point createIncenter2D (final WB_Triangle tri)
WB_Point createClosestPointOnLine2D (final WB_Coord p, final WB_Line L)
List< WB_Point > createClosestPoint (final WB_Line L1, final WB_Line L2)
List< WB_Point > createIntersectionPoints2D (final WB_Circle C0, final WB_Circle C1)
List< WB_Point > createIntersectionPoints2D (final WB_Line L, final WB_Circle C)
WB_Point createIntersectionPoint2D (final WB_Line L1, final WB_Line L2)
WB_Point createMirrorPoint2D (final WB_Coord p, final double x0, final double y0, final double x1, final double y1)
WB_Point createMirrorPoint2D (final WB_Coord p, final WB_Line L)
WB_Point createPointFromBarycentricCoordinates2D (final double u, final double v, final double w, final WB_Triangle tri)
WB_Point createInversionPoint2D (final WB_Coord p, final WB_Circle inversionCircle)
WB_Point createCentroid2D (final WB_Triangle tri)
WB_Point createCentroid2D (final WB_Coord...points)
WB_Point createCircumcenter2D (final WB_Triangle tri)
WB_Point createOrthocenter2D (final WB_Triangle tri)
WB_Point createPointFromTrilinearCoordinates2D (final double u, final double v, final double w, final WB_Triangle tri)
WB_Point createMidpoint2D (final WB_Coord p, final WB_Coord q)
WB_Point createMidpoint2D (final WB_Coord...p)
WB_Vector createVector2D ()
WB_Vector createVectorFromTo2D (final WB_Coord p, final WB_Coord q)
WB_Vector createVector2D (final WB_Coord p)
WB_Vector createVector2D (final double _x, final double _y)
WB_Vector createNormalizedVector2D (final WB_Coord p)
WB_Vector createNormalizedVectorFromTo2D (final WB_Coord p, final WB_Coord q)
WB_Vector createNormalizedVector2D (final double _x, final double _y)
WB_Vector createNormalizedPerpendicularVector2D (final double _x, final double _y)
WB_Vector createNormalizedPerpendicularVector2D (final WB_Coord v)
WB_Vector createVectorFromPolar (final double r, final double phi)
WB_Vector createVectorFromBipolar (final double a, final double sigma, final double tau)
WB_Vector createVectorFromParabolic (final double sigma, final double tau)
WB_Vector createVectorFromHyperbolic (final double u, final double v)
WB_Vector createVectorFromElliptic (final double a, final double mu, final double nu)
WB_Line createLineThroughPoints2D (final WB_Coord p1, final WB_Coord p2)
WB_Line createLineThroughPoints2D (final double x1, final double y1, final double x2, final double y2)
WB_Line createLineWithDirection2D (final WB_Coord origin, final WB_Coord direction)
WB_Line createLineWithDirection2D (final double ox, final double oy, final double dx, final double dy)
WB_Line createParallelLineThroughPoint2D (final WB_Line L, final WB_Coord p)
WB_Line createPerpendicularLineThroughPoint2D (final WB_Line L, final WB_Coord p)
List< WB_Line > createParallelLines2D (final WB_Line L, final double d)
WB_Line createBisector2D (final WB_Coord p, final WB_Coord q)
List< WB_Line > createAngleBisector2D (final WB_Line L1, final WB_Line L2)
WB_Line createLineTangentToCircleInPoint (final WB_Circle C, final WB_Coord p)
List< WB_Line > createLinesTangentToCircleThroughPoint (final WB_Circle C, final WB_Coord p)
List< WB_Line > createLinesTangentTo2Circles (final WB_Circle C0, final WB_Circle C1)
List< WB_Line > createPerpendicularLinesTangentToCircle (final WB_Line L, final WB_Circle C)
WB_Ray createRayThroughPoints2D (final WB_Coord p1, final WB_Coord p2)
WB_Ray createRayThroughPoints2D (final double x1, final double y1, final double x2, final double y2)
WB_Ray createRayWithDirection2D (final WB_Coord origin, final WB_Coord direction)
WB_Ray createRayWithDirection2D (final double ox, final double oy, final double dx, final double dy)
WB_Ray createParallelRayThroughPoint2D (final WB_Line L, final WB_Coord p)
WB_Segment createSegment2D (final WB_Coord p1, final WB_Coord p2)
WB_Segment createSegmentWithLength2D (final WB_Coord origin, final WB_Coord direction, final double length)
WB_Segment createSegment2D (final double x1, final double y1, final double x2, final double y2)
WB_Segment createSegmentWithLength2D (final double ox, final double oy, final double dx, final double dy, final double length)
WB_PolyLine createPolyLine (final WB_Coord[] points)
WB_PolyLine createPolyLine (final Collection<?extends WB_Coord > points)
WB_Ring createRing (final WB_Coord[] points)
WB_Ring createRing (final List<?extends WB_Coord > points)
WB_Polygon createSimplePolygon (final WB_Coord...points)
WB_Polygon createSimplePolygon (final WB_CoordCollection points)
WB_Polygon createSimplePolygon (final WB_Polygon poly)
WB_Polygon createSimplePolygon (final Collection<?extends WB_Coord > points)
WB_Polygon createSimplePolygon (final WB_Triangle triangle)
WB_Polygon createSimplePolygon (final WB_Quad quad)
WB_Polygon createSimplePolygon (final WB_Pentagon pentagon)
WB_Polygon createSimplePolygon (final WB_Hexagon hexagon)
WB_Polygon createSimplePolygon (final WB_Octagon octagon)
WB_Polygon createSimplePolygon (final List<?extends WB_Coord > tuples, final int[] indices)
WB_Polygon createPolygonWithHole (final WB_Coord[] points, final WB_Coord[] innerpoints)
WB_Polygon createPolygonWithHole (final Collection<?extends WB_Coord > points, final Collection<?extends WB_Coord > innerpoints)
WB_Polygon createPolygonWithHoles (final WB_Coord[] points, final WB_Coord[][] innerpoints)
WB_Polygon createPolygonWithHoles (final Collection<?extends WB_Coord > points, final List<?extends WB_Coord >[] innerpoints)
WB_Polygon createPolygonFromJTSPolygon2D (final Polygon JTSpoly)
WB_Polygon createPolygonConvexHull2D (final WB_Polygon poly)
List< WB_Polygon > createConvexPolygonDecomposition2D (final WB_Polygon poly)
List< WB_Polygon > createBufferedPolygons2D (final WB_Polygon poly, final double d)
List< WB_Polygon > createBufferedPolygons2D (final Collection<?extends WB_Polygon > poly, final double d)
List< WB_Polygon > createBufferedPolygons2D (final WB_Polygon poly, final double d, final int n)
List< WB_Polygon > createBufferedPolygonsStraight2D (final WB_Polygon poly, final double d)
List< WB_Polygon > createBufferedPolygons2D (final Collection<?extends WB_Polygon > poly, final double d, final int n)
List< WB_Polygon > createBufferedPolygonsStraight2D (final Collection<?extends WB_Polygon > poly, final double d)
List< WB_Polygon > createBoundaryPolygons2D (final WB_Polygon poly)
List< WB_Polygon > createBoundaryPolygons2D (final Collection<?extends WB_Polygon > poly)
List< WB_Polygon > createRibbonPolygons2D (final WB_Polygon poly, final double d)
List< WB_Polygon > createRibbonPolygons2D (final Collection<?extends WB_Polygon > poly, final double d)
List< WB_Polygon > createRibbonPolygons2D (final WB_Polygon poly, final double o, final double i)
List< WB_Polygon > createRibbonPolygons2D (final Collection<?extends WB_Polygon > poly, final double o, final double i)
List< WB_Polygon > createSimplifiedPolygon2D (final WB_Polygon poly, final double tol)
List< WB_Polygon > createDensifiedPolygon2D (final WB_Polygon poly, final double max)
List< WB_Polygon > unionPolygons2D (final WB_Polygon poly1, final WB_Polygon poly2)
List< WB_Polygon > unionPolygons2D (final WB_Polygon poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > unionPolygons2D (final Collection<?extends WB_Polygon > poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > subtractPolygons2D (final WB_Polygon poly1, final WB_Polygon poly2)
List< WB_Polygon > subtractPolygons2D (final WB_Polygon poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > subtractPolygons2D (final Collection<?extends WB_Polygon > poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > subtractPolygons2D (final Collection<?extends WB_Polygon > poly1, final WB_Polygon poly2)
List< WB_Polygon > intersectPolygons2D (final WB_Polygon poly1, final WB_Polygon poly2)
List< WB_Polygon > intersectPolygons2D (final WB_Polygon poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > intersectPolygons2D (final Collection<?extends WB_Polygon > poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > symDifferencePolygons2D (final WB_Polygon poly1, final WB_Polygon poly2)
List< WB_Polygon > symDifferencePolygons2D (final WB_Polygon poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > symDifferencePolygons2D (final Collection<?extends WB_Polygon > poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > constrainPolygons2D (final WB_Polygon poly, final WB_Polygon container)
List< WB_Polygon > constrainPolygons2D (final WB_Polygon[] polygons, final WB_Polygon container)
List< WB_Polygon > constrainPolygons2D (final List< WB_Polygon > polygons, final WB_Polygon container)
List< WB_Polygon > createTextWithTrueTypeFont (final String text, final String fontName, final float pointSize)
List< WB_Polygon > createTextWithTrueTypeFont (final String text, final String fontName, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithTrueTypeFont (final String text, final String fontName, final int style, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithFont (final String text, final String fontName, final float pointSize)
List< WB_Polygon > createTextWithFont (final String text, final String fontName, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithFont (final String text, final String fontName, final int style, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithOpenTypeFont (final String text, final String fontName, final float pointSize)
List< WB_Polygon > createTextWithOpenTypeFont (final String text, final String fontName, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithOpenTypeFont (final String text, final String fontName, final int style, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithType1Font (final String text, final String fontName, final float pointSize)
List< WB_Polygon > createTextWithType1Font (final String text, final String fontName, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithType1Font (final String text, final String fontName, final int style, final float pointSize, final double flatness)
List< WB_Polygon > createText (final String text, final String fontName, final float pointSize)
List< WB_Polygon > createText (final String text, final String fontName, final float pointSize, final double flatness)
List< WB_Polygon > createText (final String text, final String fontName, final int style, final float pointSize, final double flatness)
List< WB_Polygon > createText (final String text, final Font font, final int style, final float pointSize, final double flatness)
List< WB_Polygon > createText (final String text, final Font font, final double flatness)
List< WB_Polygon > createShape (final Shape shape, final double flatness)
WB_Triangle createTriangle2D (final double p1x, final double p1y, final double p2x, final double p2y, final double p3x, final double p3y)
WB_Triangle createTriangle2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
WB_Circle createCircleWithDiameter (final WB_Coord center, final WB_Coord normal, final double diameter)
WB_Circle createCircleWithRadius (final WB_Coord center, final WB_Coord normal, final double radius)
WB_Circle createCircleWithRadius (final WB_Coord center, final double radius)
WB_Circle createCircleWithDiameter (final WB_Coord center, final double diameter)
WB_Circle createCircleWithRadius (final double x, final double y, final double radius)
WB_Circle createCircleWithDiameter (final double x, final double y, final double diameter)
WB_Circle createInversionCircle2D (final WB_Circle C, final WB_Circle inversionCircle)
WB_Circle createCircumcircle2D (final WB_Triangle tri)
WB_Circle createIncircle2D (final WB_Triangle tri)
WB_Circle createCirclePPP (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2)
List< WB_Circle > createCirclePPL (final WB_Coord p, final WB_Coord q, final WB_Line L)
List< WB_Circle > createCirclePLL (final WB_Coord p, final WB_Line L1, final WB_Line L2)
List< WB_Circle > createCirclePPC (final WB_Coord p, final WB_Coord q, final WB_Circle C)
List< WB_Circle > createCirclePCC (final WB_Coord p, final WB_Circle C1, final WB_Circle C2)
List< WB_Circle > createCirclePLC (final WB_Coord p, final WB_Line L, final WB_Circle C)
List< WB_Circle > createCircleLLL (final WB_Line L1, final WB_Line L2, final WB_Line L3)
List< WB_Circle > createCircleLLC (final WB_Line L1, final WB_Line L2, final WB_Circle C)
List< WB_Circle > createCircleLCC (final WB_Line L, final WB_Circle C1, final WB_Circle C2)
List< WB_Circle > createCircleCCC (WB_Circle C1, WB_Circle C2, WB_Circle C3)
List< WB_Circle > createCircleThrough2Points (final WB_Coord p0, final WB_Coord p1, final double r)
List< WB_Circle > createCircleTangentToLineThroughPoint (final WB_Line L, final WB_Coord p, final double r)
List< WB_Circle > createCircleTangentTo2Lines (final WB_Line L0, final WB_Line L1, final double r)
List< WB_Circle > createCircleTangentToCircleThroughPoint (final WB_Circle C, final WB_Coord p, final double r)
List< WB_Circle > createCircleTangentToLineAndCircle (final WB_Line L, final WB_Circle C, final double r)
List< WB_Circle > createCircleTangentTo2CirclesNonCollinear (final WB_Circle C0, final WB_Circle C1, final double r)
List< WB_Circle > createCircleTangentTo2CirclesCollinear (final WB_Circle C0, final WB_Circle C1)
List< WB_Circle > createCircleTangentTo2Circles (final WB_Circle C0, final WB_Circle C1, final double r)
WB_Point createClosestPointOnTriangle2D (final WB_Coord p, final WB_Coord a, final WB_Coord b, final WB_Coord c)
WB_Point createClosestPointOnPolygon2D (final WB_Coord p, final WB_Polygon poly)
List< WB_Coord > createUniquePoints2D (final List< WB_Coord > points, final double threshold)
Static Public Member Functions
static WB_GeometryFactory3D instance ()
Static Public Member Functions inherited from wblut.geom.WB_GeometryFactory2D
static WB_GeometryFactory2D instance ()
Private Member Functions
List< WB_Point > cleanPointlist (final List< WB_Point > points)
int[][] createPrismFaces (final int n)
int[][] createPrismFacesOpen (final int n)
int[][] createAntiprismFaces (final int n)
List< WB_Point > createVerticesFromArray (final double[][] vertices)
List< WB_Polygon > createPolygonsFromJTSGeometry (final Geometry geometry, final WB_Map2D map)
Private Attributes
final GeometryFactory JTSgf = new GeometryFactory()
Constructor & Destructor Documentation
wblut.geom.WB_GeometryFactory3D.WB_GeometryFactory3D ()
References wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createVector().
Member Function Documentation
List<WB_Point> wblut.geom.WB_GeometryFactory3D.cleanPointlist (final List< WB_Point > points) private
Parameters
points
Returns
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.constrainPolygons (final WB_Polygon poly, final WB_Polygon container)
Parameters
poly
container
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry(), and wblut.geom.WB_Polygon.getPlane().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.constrainPolygons (final WB_Polygon[] polygons, final WB_Polygon container)
Parameters
polygons
container
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.constrainPolygons (final List< WB_Polygon > polygons, final WB_Polygon container)
Parameters
polygons
container
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createAntiPrism (final Collection<?extends WB_Coord > points, final double h)
Parameters
points
h
Returns
References wblut.geom.WB_GeometryFactory3D.createAntiprismFaces(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createAntiPrism (final WB_Coord[] points, final double h)
Parameters
points
h
Returns
References wblut.geom.WB_GeometryFactory3D.createAntiprismFaces(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createAntiPrism (final WB_Polygon poly, final double h)
Parameters
poly
h
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVector(), wblut.geom.WB_Polygon.getNumberOfContours(), wblut.geom.WB_Polygon.getNumberOfPoints(), wblut.geom.WB_Polygon.getNumberOfPointsPerContour(), wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_Polygon.getTriangles().
int [][] wblut.geom.WB_GeometryFactory3D.createAntiprismFaces (final int n) private
Parameters
n
Returns
WB_Mesh wblut.geom.WB_GeometryFactory3D.createArchimedes (final int type, final double edgeLength)
Parameters
type
edgeLength
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVerticesFromArray(), wblut.geom.WB_Point.div(), wblut.geom.WB_Vector.getDistance(), and wblut.geom.WB_Point.subSelf().
WB_Plane wblut.geom.WB_GeometryFactory3D.createBisector (final WB_Coord p, final WB_Coord q)
References wblut.geom.WB_GeometryFactory3D.createMidpoint(), wblut.geom.WB_GeometryFactory3D.createPlane(), and wblut.geom.WB_GeometryFactory3D.createVectorFromTo().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleAndHeight (final Collection<?extends WB_Coord > points, final double angle, final double height, final WB_Map2D context)
Parameters
points
angle
height
context
Returns
References wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleRangeAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleAndHeight (final WB_Coord[] points, final double angle, final double height, final WB_Map2D context)
Parameters
points
angle
height
context
Returns
References wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleRangeAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleAndHeight (final Collection<?extends WB_Coord > points, final double angle, final double height)
Parameters
points
angle
height
Returns
References wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleAndHeight(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleAndHeight (final WB_Coord[] points, final double angle, final double height)
Parameters
points
angle
height
Returns
References wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleAndHeight(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
minangle
maxangle
height
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), and wblut.geom.WB_Map.unmapPoint3D().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
minangle
maxangle
height
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), and wblut.geom.WB_Map.unmapPoint3D().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height, final WB_Map2D context)
Parameters
points
minangle
maxangle
height
context
Returns
References wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleRangeAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height, final WB_Map2D context)
Parameters
points
minangle
maxangle
height
context
Returns
References wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleRangeAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height)
Parameters
points
minangle
maxangle
height
Returns
References wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleRangeAndHeight(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height)
Parameters
points
minangle
maxangle
height
Returns
References wblut.geom.WB_GeometryFactory3D.createBitaperWithAngleRangeAndHeight(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createBitaperWithAnglesAndHeight (final Collection<?extends WB_Coord > points, final double[] angles, final double height, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
angles
height
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), and wblut.geom.WB_Map.unmapPoint3D().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createBitaperWithAnglesAndHeight (final WB_Coord[] points, final double[] angles, final double height, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
angles
height
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), and wblut.geom.WB_Map.unmapPoint3D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createBoundaryPolygons (final WB_Polygon poly)
Parameters
poly
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry(), and wblut.geom.WB_Polygon.getPlane().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createBufferedPolygons (final WB_Polygon poly, final double d)
Parameters
poly
d
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry(), and wblut.geom.WB_Polygon.getPlane().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createBufferedPolygons (final WB_Polygon poly, final double d, final int n)
Parameters
poly
d
n
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry(), and wblut.geom.WB_Polygon.getPlane().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createBufferedPolygons (final Collection<?extends WB_Polygon > poly, final double d)
Parameters
poly
d
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createBufferedPolygons (final Collection<?extends WB_Polygon > poly, final double d, final int n)
Parameters
poly
d
n
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createBufferedPolygonsStraight (final WB_Polygon poly, final double d)
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry(), and wblut.geom.WB_Polygon.getPlane().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createBufferedPolygonsStraight (final Collection<?extends WB_Polygon > poly, final double d)
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createCapsuleWithAngleAndHeight (final Collection<?extends WB_Coord > points, final double angle, final double height, final double cap, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
angle
height
cap
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createCapsuleWithAnglesAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createCapsuleWithAngleAndHeight (final Collection<?extends WB_Coord > points, final double angle, final double height, final double cap)
Parameters
points
angle
height
cap
Returns
References wblut.geom.WB_GeometryFactory3D.createCapsuleWithAngleRangeAndHeight(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createCapsuleWithAngleAndHeight (final WB_Coord[] points, final double angle, final double height, final double cap, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
angle
height
cap
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createCapsuleWithAnglesAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createCapsuleWithAngleAndHeight (final WB_Coord[] points, final double angle, final double height, final double cap)
Parameters
points
angle
height
cap
Returns
References wblut.geom.WB_GeometryFactory3D.createCapsuleWithAngleRangeAndHeight(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createCapsuleWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height, final double cap, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
minangle
maxangle
height
cap
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createCapsuleWithAnglesAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createCapsuleWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height, final double cap)
Parameters
points
minangle
maxangle
height
cap
Returns
References wblut.geom.WB_GeometryFactory3D.createCapsuleWithAngleRangeAndHeight(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createCapsuleWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height, final double cap, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
minangle
maxangle
height
cap
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createCapsuleWithAnglesAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createCapsuleWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height, final double cap)
Parameters
points
minangle
maxangle
height
cap
Returns
References wblut.geom.WB_GeometryFactory3D.createCapsuleWithAngleRangeAndHeight(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createCapsuleWithAnglesAndHeight (final Collection<?extends WB_Coord > points, final double[] angles, final double height, final double cap, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
angles
height
cap
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), and wblut.geom.WB_Map.unmapPoint3D().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createCapsuleWithAnglesAndHeight (final Collection<?extends WB_Coord > points, final double[] angles, final double height, final double cap)
Parameters
points
angles
height
cap
Returns
References wblut.geom.WB_GeometryFactory3D.createCapsuleWithAnglesAndHeight(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createCapsuleWithAnglesAndHeight (final WB_Coord[] points, final double[] angles, final double height, final double cap, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
angles
height
cap
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), and wblut.geom.WB_Map.unmapPoint3D().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createCapsuleWithAnglesAndHeight (final WB_Coord[] points, final double[] angles, final double height, final double cap)
Parameters
points
angles
height
cap
Returns
References wblut.geom.WB_GeometryFactory3D.createCapsuleWithAnglesAndHeight(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createCatalan (final int type, final double edgeLength)
Parameters
type
edgeLength
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVerticesFromArray(), wblut.geom.WB_Point.div(), wblut.geom.WB_Vector.getDistance(), and wblut.geom.WB_Point.subSelf().
WB_Point wblut.geom.WB_GeometryFactory3D.createCentroid (final WB_Triangle tri)
Centroid of triangle.
Parameters
tri triangle
Returns
centroid
References wblut.geom.WB_Triangle.a, wblut.geom.WB_Triangle.b, wblut.geom.WB_Triangle.c, and wblut.geom.WB_GeometryFactory3D.createPointFromTrilinearCoordinates().
WB_Point wblut.geom.WB_GeometryFactory3D.createCentroid (final WB_Coord... points)
References wblut.geom.WB_Point.addSelf(), and wblut.geom.WB_Point.divSelf().
WB_Point wblut.geom.WB_GeometryFactory3D.createCircumcenter (final WB_Triangle tri)
Circumcenter of triangle.
Parameters
tri triangle
Returns
circumcenter
References wblut.geom.WB_Triangle.cosA, wblut.geom.WB_Triangle.cosB, wblut.geom.WB_Triangle.cosC, and wblut.geom.WB_GeometryFactory3D.createPointFromTrilinearCoordinates().
WB_Circle wblut.geom.WB_GeometryFactory3D.createCircumcircle3D (final WB_Triangle tri)
Parameters
tri
Returns
References wblut.geom.WB_Triangle.a, wblut.geom.WB_Triangle.b, wblut.geom.WB_Triangle.c, wblut.geom.WB_GeometryFactory3D.createCentroid(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory3D.createCircumcenter(), wblut.geom.WB_Plane.getNormal(), and wblut.geom.WB_Triangle.getPlane().
WB_Point wblut.geom.WB_GeometryFactory3D.createClosestPointOnPolygon (final WB_Coord p, final WB_Polygon poly)
Parameters
p
poly
Returns
References wblut.geom.WB_GeometryFactory3D.createClosestPointOnTriangle(), wblut.geom.WB_Polygon.getPoint(), wblut.geom.WB_Vector.getSqDistance(), wblut.geom.WB_Polygon.getTriangles(), and wblut.math.WB_Epsilon.isZeroSq().
WB_Point wblut.geom.WB_GeometryFactory3D.createClosestPointOnTriangle (final WB_Coord p, final WB_Coord a, final WB_Coord b, final WB_Coord c)
Parameters
p
a
b
c
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVectorFromTo(), wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Vector.mul().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createConvexHull (final List<?extends WB_Coord > points)
Parameters
points
Returns
WB_Mesh wblut.geom.WB_GeometryFactory3D.createConvexHull (final WB_Coord[] points)
Parameters
points
Returns
References wblut.geom.WB_GeometryFactory3D.createConvexHull().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createConvexHull (final WB_Coord[] points, final boolean triangulate)
Parameters
points
triangulate
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), and wblut.math.WB_Epsilon.SQEPSILON.
WB_Mesh wblut.geom.WB_GeometryFactory3D.createConvexHull (final List<?extends WB_Coord > points, final boolean triangulate)
Parameters
points
triangulate
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), and wblut.math.WB_Epsilon.SQEPSILON.
WB_Mesh wblut.geom.WB_GeometryFactory3D.createConvexHullWithThreshold (final WB_Coord[] points, final boolean triangulate, final double threshold)
Parameters
points
triangulate
threshold
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createConvexHullWithThreshold (final List<?extends WB_Coord > points, final boolean triangulate, final double threshold)
Parameters
points
triangulate
threshold
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh().
WB_CoordinateSystem3D wblut.geom.WB_GeometryFactory3D.createCSFromOX (final WB_Coord origin, final WB_Coord X)
Create a new right-handed coordinate system. The WORLD CS is the default parent; the z-coordinate of X is ignored and X is normalized, Z is (0,0,1) and Y is created from X and Z
Parameters
origin
X
Returns
coordinate
References wblut.geom.WB_GeometryFactory3D.createCSFromOXY(), wblut.geom.WB_GeometryFactory3D.createNormalizedVector(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVector(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_CoordinateSystem3D wblut.geom.WB_GeometryFactory3D.createCSFromOX (final WB_Coord origin, final WB_Coord X, final WB_CoordinateSystem3D parent)
Create a new right-handed coordinate ; the z-coordinate of X is ignored and X is normalized, Z is (0,0,1) and Y is created from X and Z.
Parameters
origin
X
parent parent coordinate system
Returns
coordinate system
References wblut.geom.WB_GeometryFactory3D.createCSFromOXY(), wblut.geom.WB_GeometryFactory3D.createNormalizedVector(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVector(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_CoordinateSystem3D wblut.geom.WB_GeometryFactory3D.createCSFromOXY (final WB_Coord origin, final WB_Coord X, final WB_Coord Y)
Create a new right-handed coordinate system. The WORLD CS is the default parent; X is normalized, Y is normalized and orthogonalized and Z is created from X and Y
Parameters
origin
X
Y
Returns
coordinate system
References wblut.geom.WB_GeometryFactory3D.createNormalizedVector(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_GeometryFactory2D.WORLD().
WB_CoordinateSystem3D wblut.geom.WB_GeometryFactory3D.createCSFromOXY (final WB_Coord origin, final WB_Coord X, final WB_Coord Y, final WB_CoordinateSystem3D parent)
Create a new right-handed coordinate with a defined parent. X is normalized, Y is normalized and orthogonalized and Z is created from X and Y
Parameters
origin
X
Y
parent parent coordinate system
Returns
coordinate system
References wblut.geom.WB_GeometryFactory3D.createNormalizedVector(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), and wblut.geom.WB_Vector.normalizeSelf().
WB_CoordinateSystem3D wblut.geom.WB_GeometryFactory3D.createCSFromOXYZ (final WB_Coord origin, final WB_Coord X, final WB_Coord Y, final WB_Coord Z, final WB_CoordinateSystem3D parent)
Parameters
origin
X
Y
Z
parent
Returns
WB_CoordinateSystem3D wblut.geom.WB_GeometryFactory3D.createCSFromOXYZ (final WB_Coord origin, final WB_Coord X, final WB_Coord Y, final WB_Coord Z)
Parameters
origin
X
Y
Z
Returns
References wblut.geom.WB_GeometryFactory2D.WORLD().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createDensifiedPolygon (final WB_Polygon poly, final double max)
Parameters
poly
max
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry(), and wblut.geom.WB_Polygon.getPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createDipyramidWithAngle (final Collection<?extends WB_Coord > points, final double angle, final WB_Map2D context)
Parameters
points
angle
context
Returns
References wblut.geom.WB_GeometryFactory3D.createDipyramidWithAngleRange().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createDipyramidWithAngle (final WB_Coord[] points, final double angle, final WB_Map2D context)
Parameters
points
angle
context
Returns
References wblut.geom.WB_GeometryFactory3D.createDipyramidWithAngleRange().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createDipyramidWithAngle (final Collection<?extends WB_Coord > points, final double angle)
Parameters
points
angle
Returns
References wblut.geom.WB_GeometryFactory3D.createDipyramidWithAngle(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createDipyramidWithAngle (final WB_Coord[] points, final double angle)
Parameters
points
angle
Returns
References wblut.geom.WB_GeometryFactory3D.createDipyramidWithAngle(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createDipyramidWithAngleRange (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final WB_Map2D context)
Parameters
points
minangle
maxangle
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), and wblut.geom.WB_Map.unmapPoint3D().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createDipyramidWithAngleRange (final WB_Coord[] points, final double minangle, final double maxangle, final WB_Map2D context)
Parameters
points
minangle
maxangle
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), and wblut.geom.WB_Map.unmapPoint3D().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createDipyramidWithHeight (final Collection<?extends WB_Coord > points, final double height, final WB_Map2D context)
Parameters
points
height
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), and wblut.geom.WB_Map.unmapPoint3D().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createDipyramidWithHeight (final WB_Coord[] points, final double height)
Parameters
points
height
Returns
References wblut.geom.WB_GeometryFactory3D.createDipyramidWithHeight(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createDipyramidWithHeight (final WB_Coord[] points, final double height, final WB_Map2D context)
Parameters
points
height
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), and wblut.geom.WB_Map.unmapPoint3D().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createDipyramidWithHeight (final Collection<?extends WB_Coord > points, final double height)
Parameters
points
height
Returns
References wblut.geom.WB_GeometryFactory3D.createDipyramidWithHeight(), and wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Map2D wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane ()
Returns
default 2D context: XY plane
WB_Map2D wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane (final int mode, final double offset)
Create a 2D context from an offset coordinate plane.
Parameters
mode 0=YZ, 1=ZX, 2=XY, 3=ZY, 4=XZ, 5=YX
offset offset of the 2D context origin along plane normal
Returns
2D context
WB_Map2D wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane (final int mode)
Create a 2D context from a coordinate plane.
Parameters
mode 0=YZ, 1=ZX, 2=XY, 3=ZY, 4=XZ, 5=YX
Returns
2D context
WB_Map2D wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane (final WB_Plane P, final double offset)
Create a 2D context from an offset plane.
Parameters
P plane
offset offset of the 2D context origin along plane normal
Returns
2D context
WB_Map2D wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane (final WB_Plane P)
Create a 2D context from a plane.
Parameters
P plane
Returns
2D context
WB_Plane wblut.geom.WB_GeometryFactory3D.createFlippedPlane (final WB_Plane P)
Parameters
P
Returns
References wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Plane.getOrigin(), and wblut.geom.WB_Vector.mul().
WB_Point wblut.geom.WB_GeometryFactory3D.createIncenter (final WB_Triangle tri)
Incenter of triangle, z-ordinate is ignored.
Parameters
tri triangle
Returns
incenter
References wblut.geom.WB_GeometryFactory3D.createPointFromTrilinearCoordinates().
WB_Circle wblut.geom.WB_GeometryFactory3D.createIncircle (final WB_Triangle tri)
Parameters
tri
Returns
References wblut.geom.WB_Triangle.a, wblut.geom.WB_Triangle.b, wblut.geom.WB_Triangle.c, wblut.geom.WB_GeometryFactory3D.createCentroid(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Triangle.getPlane(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint (final WB_Coord p, final WB_Coord q, final double f)
Interpolated point.
Parameters
p point
q point
f interpolation value, p=0,q=1
Returns
copy of point
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Circle wblut.geom.WB_GeometryFactory3D.createInversionCircle (final WB_Circle C, final WB_Circle inversionCircle)
Inversion of circle C over circle inversionCircle http://mathworld.wolfram.com/Inversion.html
Parameters
C circle
inversionCircle inversion circle
Returns
of circle C over circle inversionCircle, null if C is tangent to inversionCircle
References wblut.geom.WB_GeometryOp2D.classifyPointToCircle2D(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), wblut.geom.WB_Classification.ON, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createJohnson (final int type, final double edgeLength)
Johnson polyhedra.
Implemented by Frederik Vanhoutte (W:Blut), painstakingly collected by David Marec. Many thanks, without David this wouldn't be here.
Parameters
type
edgeLength
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVerticesFromArray(), wblut.geom.WB_Point.div(), wblut.geom.WB_Vector.getDistance(), and wblut.geom.WB_Point.subSelf().
WB_Line wblut.geom.WB_GeometryFactory3D.createLineThroughPoints (final WB_Coord p1, final WB_Coord p2)
Get line through two points. The first point will become the origin
Parameters
p1 point 1
p2 point 2
Returns
line through points
References wblut.geom.WB_GeometryFactory3D.createLineWithDirection(), and wblut.geom.WB_GeometryFactory3D.createVectorFromTo().
WB_Line wblut.geom.WB_GeometryFactory3D.createLineThroughPoints (final double x1, final double y1, final double x2, final double y2)
Get line through two points. The first point will become the origin
Parameters
x1 x-ordinate of point 1
y1 y-ordinate of point 1
x2 x-ordinate of point 2
y2 y-ordinate of point 2
Returns
line through points
References wblut.geom.WB_GeometryFactory3D.createLineWithDirection(), wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Line wblut.geom.WB_GeometryFactory3D.createLineThroughPoints (final double x1, final double y1, final double z1, final double x2, final double y2, final double z2)
Get line through two points. The first point will become the origin
Parameters
x1 x-ordinate of point 1
y1 y-ordinate of point 1 *
z1 z-ordinate of point 1
z1
x2 x-ordinate of point 2
y2 y-ordinate of point 2
z2 z-ordinate of point 2
Returns
line through points
References wblut.geom.WB_GeometryFactory3D.createLineWithDirection(), wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Line wblut.geom.WB_GeometryFactory3D.createLineWithDirection (final WB_Coord origin, final WB_Coord direction)
Get line through point with given direction.
Parameters
origin point on line
direction direction
Returns
line through point with direction
WB_Line wblut.geom.WB_GeometryFactory3D.createLineWithDirection (final double ox, final double oy, final double oz, final double dx, final double dy, final double dz)
Get 3D line through point with given direction.
Parameters
ox x-ordinate of origin
oy y-ordinate of origin
oz z-ordinate of origin
dx x-ordinate of direction
dy y-ordinate of direction
dz z-ordinate of direction
Returns
3D line through point with given direction
References wblut.geom.WB_GeometryFactory3D.createLineWithDirection(), wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createMesh (final WB_Coord[] points, final int faces[][])
Parameters
points
faces
Returns
WB_Mesh wblut.geom.WB_GeometryFactory3D.createMesh (final Collection<?extends WB_Coord > points, final int faces[][])
Parameters
points
faces
Returns
WB_Mesh wblut.geom.WB_GeometryFactory3D.createMesh (final WB_AABB aabb)
Parameters
aabb
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_AABB.getCorners(), and wblut.geom.WB_AABB.getFaces().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createMesh (final WB_Polygon poly)
References wblut.geom.WB_GeometryFactory3D.createMesh().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createMesh (final WB_Polygon poly, final double offset)
References wblut.geom.WB_Point.add(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Polygon.getNumberOfPoints(), wblut.geom.WB_Polygon.getPlane(), wblut.geom.WB_Polygon.getPoint(), wblut.geom.WB_Polygon.getTriangles(), and wblut.geom.WB_Vector.mul().
WB_Point wblut.geom.WB_GeometryFactory3D.createMidpoint (final WB_Coord p, final WB_Coord q)
Parameters
p
q
Returns
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point wblut.geom.WB_GeometryFactory3D.createMidpoint (final WB_Coord... p)
Parameters
p
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_Point.divSelf().
WB_Vector wblut.geom.WB_GeometryFactory3D.createNormalizedPerpendicularVector (final double _x, final double _y)
Normalized vector from Cartesian coordinates http://en.wikipedia.org/wiki/Cartesian_coordinate_system
Parameters
_x x
_y y
Returns
2D vector
References wblut.geom.WB_GeometryFactory3D.createVector(), and wblut.geom.WB_Vector.normalizeSelf().
WB_Vector wblut.geom.WB_GeometryFactory3D.createNormalizedPerpendicularVector (final double _x, final double _y, final double _z)
Parameters
_x
_y
_z
Returns
References wblut.geom.WB_GeometryFactory3D.createNormalizedVector().
WB_Vector wblut.geom.WB_GeometryFactory3D.createNormalizedPerpendicularVector (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryFactory3D.createNormalizedVector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_GeometryFactory3D.createNormalizedVector (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryFactory3D.createVector(), and wblut.geom.WB_Vector.normalizeSelf().
WB_Vector wblut.geom.WB_GeometryFactory3D.createNormalizedVector (final double _x, final double _y, final double _z)
Normalized vector from Cartesian coordinates http://en.wikipedia.org/wiki/Cartesian_coordinate_system
Parameters
_x x
_y y
_z z
Returns
3D vector
References wblut.geom.WB_GeometryFactory3D.createVector(), and wblut.geom.WB_Vector.normalizeSelf().
WB_Vector wblut.geom.WB_GeometryFactory3D.createNormalizedVector (final double _x, final double _y, final double _z, final double _w)
Parameters
_x
_y
_z
_w
Returns
References wblut.geom.WB_GeometryFactory3D.createVector(), and wblut.geom.WB_Vector.normalizeSelf().
WB_Vector wblut.geom.WB_GeometryFactory3D.createNormalizedVector (final double _x, final double _y)
References wblut.geom.WB_GeometryFactory3D.createVector(), and wblut.geom.WB_Vector.normalizeSelf().
WB_Vector wblut.geom.WB_GeometryFactory3D.createNormalizedVectorFromTo (final WB_Coord p, final WB_Coord q)
Parameters
p
q
Returns
References wblut.geom.WB_GeometryFactory3D.createVector(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Plane wblut.geom.WB_GeometryFactory3D.createOffsetPlane (final WB_Coord origin, final WB_Coord normal, final double offset)
Get plane through point on plane with normal direction.
Parameters
origin point on plane
normal
offset offset
Returns
plane
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Plane wblut.geom.WB_GeometryFactory3D.createOffsetPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz, final double offset)
Get plane through point on plane with normal direction.
Parameters
ox x-ordinate of point on plane
oy y-ordinate of point on plane
oz z-ordinate of point on plane
nx
ny
nz
offset offset
Returns
plane
References wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Plane wblut.geom.WB_GeometryFactory3D.createOffsetPlane (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final double offset)
Get offset plane through 3 points.
Parameters
p1 point on plane
p2 point on plane
p3 point on plane
offset offset
Returns
plane
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVectorFromTo(), wblut.geom.WB_Vector.crossSelf(), and wblut.geom.WB_Vector.normalizeSelf().
WB_Point wblut.geom.WB_GeometryFactory3D.createOrthocenter (final WB_Triangle tri)
Orthocenter of triangle, z-ordinate is ignored.
Parameters
tri triangle
Returns
orthocenter
References wblut.geom.WB_Triangle.a, wblut.geom.WB_Triangle.b, wblut.geom.WB_Triangle.c, and wblut.geom.WB_GeometryFactory3D.createPointFromBarycentricCoordinates().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createOtherPolyhedron (final int type, final double edgeLength)
Parameters
type
edgeLength
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVerticesFromArray(), wblut.geom.WB_Point.div(), wblut.geom.WB_Vector.getDistance(), and wblut.geom.WB_Point.subSelf().
WB_Line wblut.geom.WB_GeometryFactory3D.createParallelLineThroughPoint (final WB_Line L, final WB_Coord p)
Get a line parallel to a line and through point.
Parameters
L line
p point
Returns
parallel line through point
References wblut.geom.WB_GeometryFactory3D.createLineWithDirection(), and wblut.geom.WB_Line.getDirection().
WB_Ray wblut.geom.WB_GeometryFactory3D.createParallelRayThroughPoint (final WB_Line L, final WB_Coord p)
Get a ray parallel to a line and through point.
Parameters
L line
p point
Returns
parallel line through point
References wblut.geom.WB_GeometryFactory3D.createRayWithDirection(), and wblut.geom.WB_Line.getDirection().
WB_Plane wblut.geom.WB_GeometryFactory3D.createPlane (final WB_Coord origin, final WB_Coord normal)
Get plane through point on plane with normal direction.
Parameters
origin point on plane
normal
Returns
plane
WB_Plane wblut.geom.WB_GeometryFactory3D.createPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
Get plane through point on plane with normal direction.
Parameters
ox x-ordinate of point on plane
oy y-ordinate of point on plane
oz z-ordinate of point on plane
nx
ny
nz
Returns
plane
References wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Plane wblut.geom.WB_GeometryFactory3D.createPlane (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
Get plane through 3 points.
Parameters
p1 point on plane
p2 point on plane
p3 point on plane
Returns
plane
References wblut.geom.WB_GeometryFactory3D.createVectorFromTo(), and wblut.geom.WB_Vector.crossSelf().
WB_Plane wblut.geom.WB_GeometryFactory3D.createPlane (final WB_Triangle T)
Parameters
T
Returns
WB_Mesh wblut.geom.WB_GeometryFactory3D.createPlato (final int type, final double edgeLength)
Parameters
type
edgeLength
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVerticesFromArray(), wblut.geom.WB_Point.div(), wblut.geom.WB_Vector.getDistance(), and wblut.geom.WB_Point.subSelf().
WB_Point wblut.geom.WB_GeometryFactory3D.createPoint ()
New point at origin.
Returns
new point at origin
WB_Point wblut.geom.WB_GeometryFactory3D.createPoint (final WB_Coord p)
Create new point.If parameter p is same class as caller then the original point is returned. Unsafe if the point is aftwerwards modified with unsafe operators (_setSelf,_addSelf,_subSelf,..)
Parameters
p point
Returns
copy of point
WB_Point wblut.geom.WB_GeometryFactory3D.createPoint (final double[] p)
Parameters
p
Returns
WB_Point wblut.geom.WB_GeometryFactory3D.createPoint (final double _x, final double _y)
Point from Cartesian coordinates http://en.wikipedia.org/wiki/Cartesian_coordinate_system
Parameters
_x x
_y y
Returns
2D point
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Point wblut.geom.WB_GeometryFactory3D.createPoint (final double _x, final double _y, final double _z)
Point from Cartesian coordinates http://en.wikipedia.org/wiki/Elliptic_coordinates
Parameters
_x x
_y y
_z z
Returns
3D point
WB_Point wblut.geom.WB_GeometryFactory3D.createPoint (final Coordinate coord)
Parameters
coord
Returns
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromBarycentricCoordinates (final double u, final double v, final double w, final WB_Triangle tri)
Get point with triangle barycentric coordinates.
Parameters
u
v
w
tri triangle
Returns
point wit barycentric coordinates (u,v,w)
References wblut.geom.WB_Triangle.a, wblut.geom.WB_Triangle.b, wblut.geom.WB_Triangle.c, and wblut.geom.WB_GeometryFactory3D.createPointFromTrilinearCoordinates().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromBipolarCylindrical (final double a, final double sigma, final double tau, final double z)
Point from bipolar cylindrical coordinates http://en.wikipedia.org/wiki/Bipolar_cylindrical_coordinates
Parameters
a focus
sigma toroidal coordinate
tau toroidal coordinate
z height
Returns
3D point
References wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.math.WB_Epsilon.isZero().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromBispherical (final double a, final double sigma, final double tau, final double phi)
Point from bispherical coordinates http://en.wikipedia.org/wiki/Bispherical_coordinates
Parameters
a focus
sigma toroidal coordinate
tau toroidal coordinate
phi toroidal coordinate
Returns
3D point
References wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.math.WB_Epsilon.isZero().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromConical (final double b, final double c, final double r, final double mu, final double nu)
Point from conical coordinates http://en.wikipedia.org/wiki/Conical_coordinates
nu???<c???<mu???<b???
Parameters
b,c conical constants
c
r radius
mu conical coordinate
nu conical coordinate
Returns
3D point
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromCylindrical (final double r, final double phi, final double z)
Point from cylindrical coordinates http://en.wikipedia.org/wiki/Cylindrical_coordinate_system
Parameters
r radius
phi angle
z height
Returns
3D point
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromEllipsoidal (final double a, final double b, final double c, final double lambda, final double mu, final double nu)
Point from ellipsoidal coordinates http://en.wikipedia.org/wiki/Ellipsoidal_coordinates
lambda<c???<mu<b???<nu<a???
Parameters
a,b,c focus
b
c
lambda ellipsoidal coordinate
mu ellipsoidal coordinate
nu ellipsoidal coordinate
Returns
3D point
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromElliptic (final double a, final double mu, final double nu, final double z)
Point from elliptic coordinates http://en.wikipedia.org/wiki/Elliptic_cylindrical_coordinates
Parameters
a focus
mu elliptic coordinate >=0
nu elliptic coordinate between -PI and PI
z height
Returns
3D point
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromOblateSpheroidal (final double a, final double mu, final double nu, final double phi)
Point from oblate spheroidal coordinates http://en.wikipedia.org/wiki/Oblate_spheroidal_coordinates
Parameters
a focus
mu spheroidal coordinate >=0
nu spheroidal coordinate between -0.5*PI and 0.5*PI
phi azimuth coordinate between -PI and PI
Returns
3D point
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromParabolic (final double sigma, final double tau, final double z)
Point from parabolic coordinates http://en.wikipedia.org/wiki/Parabolic_cylindrical_coordinates
Parameters
sigma parabolic coordinate
tau parabolic coordinate
z height
Returns
3D point
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromParaboloidal (final double sigma, final double tau, final double phi)
Point from paraboloidal coordinates http://en.wikipedia.org/wiki/Paraboloidal_coordinates
Parameters
sigma parabolic coordinate
tau parabolic coordinate
phi azimuth coordinate between -PI and PI
Returns
3D point
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromProlateSpheroidal (final double a, final double mu, final double nu, final double phi)
Point from prolate spheroidal coordinates http://en.wikipedia.org/wiki/Prolate_spheroidal_coordinates
Parameters
a focus
mu spheroidal coordinate >=0
nu spheroidal coordinate between -0.5*PI and 0.5*PI
phi azimuth coordinate between -PI and PI
Returns
3D point
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromSpherical (final double r, final double theta, final double phi)
Point from spherical coordinates http://en.wikipedia.org/wiki/Spherical_coordinate_system
Parameters
r radius
theta inclination coordinate between -0.5*PI and 0.5*PI
phi azimuth coordinate between -PI and PI
Returns
3D point
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromToroidal (final double a, final double sigma, final double tau, final double phi)
Point from toroidal coordinates http://en.wikipedia.org/wiki/Toroidal_coordinates
Parameters
a focus
sigma toroidal coordinate
tau toroidal coordinate
phi toroidal coordinate
Returns
3D point
References wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.math.WB_Epsilon.isZero().
WB_Point wblut.geom.WB_GeometryFactory3D.createPointFromTrilinearCoordinates (final double u, final double v, final double w, final WB_Triangle tri)
Get point with triangle trilinear coordinates.
Parameters
u
v
w
tri triangle
Returns
point wit trilinear coordinates (u,v,w)
References wblut.geom.WB_Triangle.a, wblut.geom.WB_Triangle.b, wblut.geom.WB_Triangle.c, wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Polygon wblut.geom.WB_GeometryFactory3D.createPolygonConvexHull (final WB_Polygon poly)
Parameters
poly
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonFromJTSPolygon(), and wblut.geom.WB_Polygon.getPlane().
WB_Polygon wblut.geom.WB_GeometryFactory3D.createPolygonFromJTSPolygon (final Polygon JTSpoly, final WB_Map2D map)
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory2D.createPolygonWithHoles(), wblut.geom.WB_GeometryFactory2D.createSimplePolygon(), and wblut.geom.WB_Map.unmapPoint3D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry (final Geometry geometry, final WB_Map2D map) private
Parameters
geometry
map
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonFromJTSPolygon().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createPolyhedron (String name, final double radius)
Parameters
name
radius
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), and wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createPrism (final Collection<?extends WB_Coord > points, final double h)
Parameters
points
h
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createPrismFaces(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createPrism (final WB_Coord[] points, final double h)
Parameters
points
h
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createPrismFaces(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createPrism (final WB_Polygon poly, final double h)
References wblut.geom.WB_GeometryFactory3D.createPrism().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createPrism (final WB_Polygon poly, final double h, final double offset)
References wblut.geom.WB_Point.add(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Polygon.getNumberOfContours(), wblut.geom.WB_Polygon.getNumberOfPoints(), wblut.geom.WB_Polygon.getNumberOfPointsPerContour(), wblut.geom.WB_Polygon.getPlane(), wblut.geom.WB_Polygon.getPoint(), wblut.geom.WB_Polygon.getTriangles(), and wblut.geom.WB_Vector.mul().
int [][] wblut.geom.WB_GeometryFactory3D.createPrismFaces (final int n) private
Parameters
n
Returns
int [][] wblut.geom.WB_GeometryFactory3D.createPrismFacesOpen (final int n) private
Parameters
n
Returns
WB_Mesh wblut.geom.WB_GeometryFactory3D.createPrismOpen (final Collection<?extends WB_Coord > points, final double h)
Parameters
points
h
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createPrismFacesOpen(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createPrismOpen (final WB_Polygon poly, final double h)
Parameters
poly
h
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVector(), wblut.geom.WB_Polygon.getNumberOfPoints(), and wblut.geom.WB_Polygon.getPoint().
WB_Ray wblut.geom.WB_GeometryFactory3D.createRayThroughPoints (final WB_Coord p1, final WB_Coord p2)
Get ray through two points. The first point will become the origin
Parameters
p1 point 1
p2 point 2
Returns
ray through points
References wblut.geom.WB_GeometryFactory3D.createRayWithDirection(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Ray wblut.geom.WB_GeometryFactory3D.createRayThroughPoints (final double x1, final double y1, final double x2, final double y2)
Get ray through two points. The first point will become the origin
Parameters
x1 x-ordinate of point 1
y1 y-ordinate of point 1
x2 x-ordinate of point 2
y2 y-ordinate of point 2
Returns
ray through points
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createRayWithDirection(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Ray wblut.geom.WB_GeometryFactory3D.createRayThroughPoints (final double x1, final double y1, final double z1, final double x2, final double y2, final double z2)
Get ray through two points. The first point will become the origin
Parameters
x1 x-ordinate of point 1
y1 y-ordinate of point 1 *
z1 z-ordinate of point 1
z1
x2 x-ordinate of point 2
y2 y-ordinate of point 2
z2 z-ordinate of point 2
Returns
ray through points
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createRayWithDirection(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Ray wblut.geom.WB_GeometryFactory3D.createRayWithDirection (final WB_Coord origin, final WB_Coord direction)
Get ray through point with given direction.
Parameters
origin point on line
direction direction
Returns
ray through point with direction
WB_Ray wblut.geom.WB_GeometryFactory3D.createRayWithDirection (final double ox, final double oy, final double oz, final double dx, final double dy, final double dz)
Get 3D ray through point with given direction.
Parameters
ox x-ordinate of origin
oy y-ordinate of origin
oz z-ordinate of origin
dx x-ordinate of direction
dy y-ordinate of direction
dz z-ordinate of direction
Returns
3D ray through point with given direction
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createRayWithDirection(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createRegularAntiPrism (final int n, final double radius, final double h)
Parameters
n
radius
h
Returns
References wblut.geom.WB_GeometryFactory3D.createAntiprismFaces(), wblut.geom.WB_GeometryFactory3D.createMesh(), and wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createRegularPrism (final int n, final double radius, final double h)
Parameters
n
radius
h
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createPrismFaces().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createRibbonPolygons (final WB_Polygon poly, final double d)
Parameters
poly
d
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry(), and wblut.geom.WB_Polygon.getPlane().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createRibbonPolygons (final Collection<?extends WB_Polygon > poly, final double d)
Parameters
poly
d
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createRibbonPolygons (final WB_Polygon poly, final double o, final double i)
Parameters
poly
o
i
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry(), and wblut.geom.WB_Polygon.getPlane().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createRibbonPolygons (final Collection<?extends WB_Polygon > poly, final double o, final double i)
Parameters
poly
o
i
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry().
WB_Segment wblut.geom.WB_GeometryFactory3D.createSegment (final WB_Coord p1, final WB_Coord p2)
Get segment between two points. The first point will become the origin
Parameters
p1 point 1
p2 point 2
Returns
segment
WB_Segment wblut.geom.WB_GeometryFactory3D.createSegment (final double x1, final double y1, final double x2, final double y2)
Get segment. The first point will become the origin
Parameters
x1 x-ordinate of point 1
y1 y-ordinate of point 1
x2 x-ordinate of point 2
y2 y-ordinate of point 2
Returns
line through points
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createSegment(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Segment wblut.geom.WB_GeometryFactory3D.createSegment (final double x1, final double y1, final double z1, final double x2, final double y2, final double z2)
Get segment. The first point will become the origin
Parameters
x1 x-ordinate of point 1
y1 y-ordinate of point 1 *
z1 z-ordinate of point 1
z1
x2 x-ordinate of point 2
y2 y-ordinate of point 2
z2 z-ordinate of point 2
Returns
line through points
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createSegment(), and wblut.geom.WB_GeometryFactory3D.createVector().
WB_Segment wblut.geom.WB_GeometryFactory3D.createSegmentWithLength (final WB_Coord origin, final WB_Coord direction, final double length)
Get segment between two points. The first point will become the origin
Parameters
origin origin
direction direction
length length
Returns
segment
References wblut.geom.WB_GeometryFactory3D.createNormalizedVector(), wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createSegment().
WB_Segment wblut.geom.WB_GeometryFactory3D.createSegmentWithLength (final double ox, final double oy, final double dx, final double dy, final double length)
Get segment from point, direction and length.
Parameters
ox x-ordinate of origin
oy y-ordinate of origin
dx x-ordinate of direction
dy y-ordinate of direction
length length
Returns
segment
References wblut.geom.WB_GeometryFactory3D.createNormalizedVector(), wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createSegment().
WB_Segment wblut.geom.WB_GeometryFactory3D.createSegmentWithLength (final double ox, final double oy, final double oz, final double dx, final double dy, final double dz, final double length)
Get segment from point, direction and length.
Parameters
ox x-ordinate of origin
oy y-ordinate of origin
oz z-ordinate of origin
dx x-ordinate of direction
dy y-ordinate of direction
dz z-ordinate of direction
length length
Returns
segment
References wblut.geom.WB_GeometryFactory3D.createNormalizedVector(), wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createSegment().
List<WB_Polygon> wblut.geom.WB_GeometryFactory3D.createSimplifiedPolygon (final WB_Polygon poly, final double tol)
Parameters
poly
tol
Returns
References wblut.geom.WB_GeometryFactory3D.createPolygonsFromJTSGeometry(), and wblut.geom.WB_Polygon.getPlane().
WB_Sphere wblut.geom.WB_GeometryFactory3D.createSphereWithDiameter (final WB_Coord center, final double diameter)
Sphere with center and diameter.
Parameters
center
diameter
Returns
sphere
References wblut.geom.WB_GeometryFactory3D.createSphereWithRadius().
WB_Sphere wblut.geom.WB_GeometryFactory3D.createSphereWithDiameter (final double x, final double y, final double z, final double diameter)
Sphere with diameter and radius.
Parameters
x
y
z
diameter
Returns
sphere
References wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createSphereWithRadius().
WB_Sphere wblut.geom.WB_GeometryFactory3D.createSphereWithRadius (final WB_Coord center, final double radius)
Sphere with center and radius.
Parameters
center
radius
Returns
sphere
WB_Sphere wblut.geom.WB_GeometryFactory3D.createSphereWithRadius (final double x, final double y, final double z, final double radius)
Sphere with center and radius.
Parameters
x
y
z
radius
Returns
sphere
References wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createSphereWithRadius().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createSpindle (final Collection<?extends WB_Coord > points, final double height, final double cap, final WB_Map2D context)
Parameters
points
height
cap
context
Returns
WB_Mesh wblut.geom.WB_GeometryFactory3D.createSpindle (final Collection<?extends WB_Coord > points, final double height, final double cap)
Parameters
points
height
cap
Returns
References wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createSpindle (final WB_Coord[] points, final double height, final double cap, final WB_Map2D context)
Parameters
points
height
cap
context
Returns
WB_Mesh wblut.geom.WB_GeometryFactory3D.createSpindle (final WB_Coord[] points, final double height, final double cap)
Parameters
points
height
cap
Returns
References wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createStellatedIcosahedron (final int type, final double radius)
Parameters
type
radius
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), and wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createTaperWithAngleAndHeight (final Collection<?extends WB_Coord > points, final double angle, final double height, final WB_Map2D context)
Parameters
points
angle
height
context
Returns
References wblut.geom.WB_GeometryFactory3D.createTaperWithAngleRangeAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createTaperWithAngleAndHeight (final WB_Coord[] points, final double angle, final double height, final WB_Map2D context)
Parameters
points
angle
height
context
Returns
References wblut.geom.WB_GeometryFactory3D.createTaperWithAngleRangeAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createTaperWithAngleAndHeight (final Collection<?extends WB_Coord > points, final double angle, final double height)
Parameters
points
angle
height
Returns
References wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane(), and wblut.geom.WB_GeometryFactory3D.createTaperWithAngleAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createTaperWithAngleAndHeight (final WB_Coord[] points, final double angle, final double height)
Parameters
points
angle
height
Returns
References wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane(), and wblut.geom.WB_GeometryFactory3D.createTaperWithAngleAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createTaperWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
minangle
maxangle
height
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), wblut.geom.WB_Map2D.unmapPoint2D(), and wblut.geom.WB_Map.unmapPoint3D().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createTaperWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
minangle
maxangle
height
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), wblut.geom.WB_Map2D.unmapPoint2D(), and wblut.geom.WB_Map.unmapPoint3D().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createTaperWithAngleRangeAndHeight (final Collection<?extends WB_Coord > points, final double minangle, final double maxangle, final double height, final WB_Map2D context)
Parameters
points
minangle
maxangle
height
context
Returns
References wblut.geom.WB_GeometryFactory3D.createTaperWithAngleRangeAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createTaperWithAngleRangeAndHeight (final WB_Coord[] points, final double minangle, final double maxangle, final double height, final WB_Map2D context)
Parameters
points
minangle
maxangle
height
context
Returns
References wblut.geom.WB_GeometryFactory3D.createTaperWithAngleRangeAndHeight().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createTaperWithAnglesAndHeight (final Collection<?extends WB_Coord > points, final double[] angles, final double height, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
angles
height
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), wblut.geom.WB_Map2D.unmapPoint2D(), and wblut.geom.WB_Map.unmapPoint3D().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createTaperWithAnglesAndHeight (final WB_Coord[] points, final double angles[], final double height, final boolean b, final boolean t, final WB_Map2D context)
Parameters
points
angles
height
b
t
context
Returns
References wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createUniqueMesh(), wblut.geom.WB_Map2D.unmapPoint2D(), and wblut.geom.WB_Map.unmapPoint3D().
WB_Tetrahedron wblut.geom.WB_GeometryFactory3D.createTetrahedron (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4)
Get tetrahedron from 4 points.
Parameters
p1 first point of tetrahedron
p2 second point of tetrahedron
p3 third point of tetrahedron
p4 fourth point of tetrahedron
Returns
tetrahedron
WB_Triangle wblut.geom.WB_GeometryFactory3D.createTriangle (final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z, final double p3x, final double p3y, final double p3z)
Get triangle from 3 points.
Parameters
p1x x-ordinate of first point of triangle
p1y y-ordinate of first point of triangle
p1z z-ordinate of first point of triangle
p2x x-ordinate of second point of triangle
p2y y-ordinate of second point of triangle
p2z z-ordinate of second point of triangle
p3x x-ordinate of third point of triangle
p3y y-ordinate of third point of triangle
p3z z-ordinate of third point of triangle
Returns
triangle
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Triangle wblut.geom.WB_GeometryFactory3D.createTriangle (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
Get triangle from 3 points.
Parameters
p1 first point of triangle
p2 second point of triangle
p3 third point of triangle
Returns
triangle
WB_Mesh wblut.geom.WB_GeometryFactory3D.createTriMesh (final WB_Coord[] points, final int faces[][])
Parameters
points
faces
Returns
WB_Mesh wblut.geom.WB_GeometryFactory3D.createTriMesh (final Collection<?extends WB_Coord > points, final int faces[][])
Parameters
points
faces
Returns
WB_Mesh wblut.geom.WB_GeometryFactory3D.createTriMesh (final WB_Mesh mesh)
Parameters
mesh
Returns
WB_Mesh wblut.geom.WB_GeometryFactory3D.createUniqueMesh (final WB_Mesh mesh)
Parameters
mesh
Returns
References wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.add(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_Mesh.getFace(), wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.getNearestNeighbor(), wblut.geom.WB_Mesh.getNumberOfFaces(), wblut.geom.WB_Mesh.getNumberOfVertices(), wblut.geom.WB_Mesh.getVertex(), and wblut.math.WB_Epsilon.SQEPSILON.
WB_Mesh wblut.geom.WB_GeometryFactory3D.createUniqueMesh (final WB_Mesh mesh, final double threshold)
Parameters
mesh
threshold
Returns
References wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.add(), wblut.geom.WB_GeometryFactory3D.createMesh(), wblut.geom.WB_Mesh.getFace(), wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.getNearestNeighbor(), wblut.geom.WB_Mesh.getNumberOfFaces(), wblut.geom.WB_Mesh.getNumberOfVertices(), and wblut.geom.WB_Mesh.getVertex().
List<WB_Plane> wblut.geom.WB_GeometryFactory3D.createUniquePlanes (final List< WB_Plane > planes)
References wblut.geom.WB_Plane.get(), and wblut.geom.WB_GeometryOp3D.isEqual().
List<WB_Coord> wblut.geom.WB_GeometryFactory3D.createUniquePoints (final List< WB_Coord > points, final double threshold)
WB_Vector wblut.geom.WB_GeometryFactory3D.createVector ()
New zero-length vector.
Returns
zero-length vector
final WB_Vector wblut.geom.WB_GeometryFactory3D.createVector (final WB_Coord p)
Copy of coordinate as vector.
Parameters
p vector
Returns
vector
WB_Vector wblut.geom.WB_GeometryFactory3D.createVector (final double _x, final double _y)
Vector from Cartesian coordinates http://en.wikipedia.org/wiki/Cartesian_coordinate_system
Parameters
_x x
_y y
Returns
2D vector
References wblut.geom.WB_GeometryFactory3D.createVector().
WB_Vector wblut.geom.WB_GeometryFactory3D.createVector (final double _x, final double _y, final double _z)
Vector from Cartesian coordinates http://en.wikipedia.org/wiki/Elliptic_coordinates
Parameters
_x x
_y y
_z z
Returns
3D vector
WB_Vector wblut.geom.WB_GeometryFactory3D.createVectorFromBipolarCylindrical (final double a, final double sigma, final double tau, final double z)
Vector from bipolar cylindrical coordinates http://en.wikipedia.org/wiki/Bipolar_cylindrical_coordinates
Parameters
a focus
sigma toroidal coordinate
tau toroidal coordinate
z height
Returns
3D vector
References wblut.geom.WB_GeometryFactory3D.createVector(), and wblut.math.WB_Epsilon.isZero().
WB_Vector wblut.geom.WB_GeometryFactory3D.createVectorFromBispherical (final double a, final double sigma, final double tau, final double phi)
Vector from bispherical coordinates http://en.wikipedia.org/wiki/Bispherical_coordinates
Parameters
a focus
sigma toroidal coordinate
tau toroidal coordinate
phi toroidal coordinate
Returns
3D vector
References wblut.geom.WB_GeometryFactory3D.createVector(), and wblut.math.WB_Epsilon.isZero().
WB_Vector wblut.geom.WB_GeometryFactory3D.createVectorFromConical (final double b, final double c, final double r, final double mu, final double nu)
Vector from conical coordinates http://en.wikipedia.org/wiki/Conical_coordinates
nu???<c???<mu???<b???
Parameters
b,c conical constants
c
r radius
mu conical coordinate
nu conical coordinate
Returns
3D vector
References wblut.geom.WB_GeometryFactory3D.createVector().
WB_Vector wblut.geom.WB_GeometryFactory3D.createVectorFromCylindrical (final double r, final double phi, final double z)
Vector from cylindrical coordinates http://en.wikipedia.org/wiki/Cylindrical_coordinate_system
Parameters
r radius
phi angle
z height
Returns
3D vector
References wblut.geom.WB_GeometryFactory3D.createVector().
WB_Vector wblut.geom.WB_GeometryFactory3D.createVectorFromEllipsoidal (final double a, final double b, final double c, final double lambda, final double mu, final double nu)
Vector from ellipsoidal coordinates http://en.wikipedia.org/wiki/Ellipsoidal_coordinates
lambda<c???<mu<b???<nu<a???
Parameters
a,b,c focus
b
c
lambda ellipsoidal coordinate
mu ellipsoidal coordinate
nu ellipsoidal coordinate
Returns
3D vector
References wblut.geom.WB_GeometryFactory3D.createVector().
WB_Vector wblut.geom.WB_GeometryFactory3D.createVectorFromElliptic (final double a, final double mu, final double nu, final double z)
Vector from elliptic coordinates http://en.wikipedia.org/wiki/Elliptic_cylindrical_coordinates
Parameters
a focus
mu elliptic coordinate >=0
nu elliptic coordinate between -PI and PI
z height
Returns
3D vector
References wblut.geom.WB_GeometryFactory3D.createVector().
WB_Vector wblut.geom.WB_GeometryFactory3D.createVectorFromOblateSpheroidal (final double a, final double mu, final double nu, final double phi)
Vector from oblate spheroidal coordinates http://en.wikipedia.org/wiki/Oblate_spheroidal_coordinates
Parameters
a focus
mu spheroidal coordinate >=0
nu spheroidal coordinate between -0.5*PI and 0.5*PI
phi azimuth coordinate between -PI and PI
Returns
3D vector
References wblut.geom.WB_GeometryFactory3D.createVector().
WB_Vector wblut.geom.WB_GeometryFactory3D.createVectorFromParabolic (final double sigma, final double tau, final double z)
Vector from parabolic coordinates http://en.wikipedia.org/wiki/Parabolic_cylindrical_coordinates
Parameters
sigma parabolic coordinate
tau parabolic coordinate
z height
Returns
3D vector
References wblut.geom.WB_GeometryFactory3D.createVector().
WB_Vector wblut.geom.WB_GeometryFactory3D.createVectorFromParaboloidal (final double sigma, final double tau, final double phi)
Vector from paraboloidal coordinates http://en.wikipedia.org/wiki/Paraboloidal_coordinates
Parameters
sigma parabolic coordinate
tau parabolic coordinate
phi azimuth coordinate between -PI and PI
Returns
3D vector
References wblut.geom.WB_GeometryFactory3D.createVector().
WB_Vector wblut.geom.WB_GeometryFactory3D.createVectorFromProlateSpheroidal (final double a, final double mu, final double nu, final double phi)
Vector from prolate spheroidal coordinates http://en.wikipedia.org/wiki/Prolate_spheroidal_coordinates
Parameters
a focus
mu spheroidal coordinate >=0
nu spheroidal coordinate between -0.5*PI and 0.5*PI
phi azimuth coordinate between -PI and PI
Returns
3D vector
References wblut.geom.WB_GeometryFactory3D.createVector().
WB_Vector wblut.geom.WB_GeometryFactory3D.createVectorFromSpherical (final double r, final double theta, final double phi)
Vector from spherical coordinates http://en.wikipedia.org/wiki/Spherical_coordinate_system
Parameters
r radius
theta inclination coordinate between -0.5*PI and 0.5*PI
phi azimuth coordinate between -PI and PI
Returns
3D vector
References wblut.geom.WB_GeometryFactory3D.createVector().
WB_Vector wblut.geom.WB_GeometryFactory3D.createVectorFromTo (final WB_Coord p, final WB_Coord q)
Parameters
p
q
Returns
References wblut.geom.WB_GeometryFactory3D.createVector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_GeometryFactory3D.createVectorFromToroidal (final double a, final double sigma, final double tau, final double phi)
Vector from toroidal coordinates http://en.wikipedia.org/wiki/Toroidal_coordinates
Parameters
a focus
sigma toroidal coordinate
tau toroidal coordinate
phi toroidal coordinate
Returns
3D vector
References wblut.geom.WB_GeometryFactory3D.createVector(), and wblut.math.WB_Epsilon.isZero().
List<WB_Point> wblut.geom.WB_GeometryFactory3D.createVerticesFromArray (final double vertices[][]) private
Parameters
vertices
Returns
References wblut.geom.WB_GeometryFactory3D.createPoint().
WB_Mesh wblut.geom.WB_GeometryFactory3D.createZonohedron (final WB_Coord[] vectors, final double scale)
Parameters
vectors
scale
Returns
References wblut.geom.WB_Point.add(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory3D.createConvexHull(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_Point.mulSelf(), and wblut.geom.WB_Point.subSelf().
WB_Point wblut.geom.WB_GeometryFactory3D.getIntersection (final WB_Coord a, final WB_Coord b, final WB_Plane P)
Parameters
a
b
P
Returns
References wblut.geom.WB_GeometryOp3D.getIntersection3D(), and wblut.geom.WB_IntersectionResult.object.
static WB_GeometryFactory3D wblut.geom.WB_GeometryFactory3D.instance () static
Legacy code, WB_GeometryFactory used to be a singleton but this limited its use in multithreaded code.
Returns
References wblut.geom.WB_GeometryFactory3D.WB_GeometryFactory3D().
WB_Vector wblut.geom.WB_GeometryFactory3D.minX ()
Returns
negative X-axis direction
WB_Vector wblut.geom.WB_GeometryFactory3D.minY ()
Returns
negative Y-axis direction
WB_Vector wblut.geom.WB_GeometryFactory3D.minZ ()
Returns
default Z-axis direction
WB_Point wblut.geom.WB_GeometryFactory3D.origin ()
Returns
default origin
WB_Polygon [] wblut.geom.WB_GeometryFactory3D.splitSimplePolygon (final WB_Polygon poly, final WB_Plane P)
Parameters
poly
P
Returns
References wblut.geom.WB_Classification.BACK, wblut.geom.WB_GeometryOp3D.classifyPointToPlane3D(), wblut.geom.WB_GeometryFactory3D.cleanPointlist(), wblut.geom.WB_GeometryFactory2D.createSimplePolygon(), wblut.geom.WB_Classification.FRONT, wblut.geom.WB_GeometryFactory3D.getIntersection(), wblut.geom.WB_Polygon.getNumberOfPoints(), wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_Classification.ON.
WB_Vector wblut.geom.WB_GeometryFactory3D.X ()
Returns
default X-axis direction
WB_Plane wblut.geom.WB_GeometryFactory3D.XY ()
Returns
default XY-plane
References wblut.geom.WB_GeometryFactory3D.createPlane(), wblut.geom.WB_GeometryFactory3D.origin(), and wblut.geom.WB_GeometryFactory3D.Z().
WB_Plane wblut.geom.WB_GeometryFactory3D.XZ ()
Returns
default XZ-plane
References wblut.geom.WB_GeometryFactory3D.createPlane(), wblut.geom.WB_GeometryFactory3D.minY(), and wblut.geom.WB_GeometryFactory3D.origin().
WB_Vector wblut.geom.WB_GeometryFactory3D.Y ()
Returns
default Y-axis direction
WB_Plane wblut.geom.WB_GeometryFactory3D.YX ()
Returns
default YX-plane
References wblut.geom.WB_GeometryFactory3D.createPlane(), wblut.geom.WB_GeometryFactory3D.minZ(), wblut.geom.WB_GeometryFactory3D.origin(), and wblut.geom.WB_GeometryFactory3D.XY().
WB_Plane wblut.geom.WB_GeometryFactory3D.YZ ()
Returns
default YZ-plane
References wblut.geom.WB_GeometryFactory3D.createPlane(), wblut.geom.WB_GeometryFactory3D.origin(), and wblut.geom.WB_GeometryFactory3D.X().
WB_Vector wblut.geom.WB_GeometryFactory3D.Z ()
Returns
default Z-axis direction
WB_Plane wblut.geom.WB_GeometryFactory3D.ZX ()
Returns
default ZX-plane
References wblut.geom.WB_GeometryFactory3D.createPlane(), wblut.geom.WB_GeometryFactory3D.origin(), and wblut.geom.WB_GeometryFactory3D.Y().
WB_Plane wblut.geom.WB_GeometryFactory3D.ZY ()
Returns
default ZY-plane
References wblut.geom.WB_GeometryFactory3D.createPlane(), wblut.geom.WB_GeometryFactory3D.minX(), and wblut.geom.WB_GeometryFactory3D.origin().
Member Data Documentation
final GeometryFactory wblut.geom.WB_GeometryFactory3D.JTSgf = new GeometryFactory() private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_GeometryFactory3D.java