HE_Mesh: wblut.hemesh.HE_MeshCollection Class Reference
wblut.hemesh.HE_MeshCollection Class Reference
Classes
class MultiCreatorThread
class MultiModifierThread
class MultiSimplifierThread
class MultiSubdividorThread
Public Member Functions
HE_MeshCollection ()
HE_MeshCollection (final HEMC_MultiCreator creator)
void createThreaded (final HEMC_MultiCreator creator)
HE_MeshCollection modify (final HEM_Modifier modifier)
HE_MeshCollection modifyThreaded (final HEM_Modifier modifier)
HE_MeshCollection subdivide (final HES_Subdividor subdividor)
HE_MeshCollection subdivideThreaded (final HES_Subdividor subdividor)
HE_MeshCollection simplify (final HES_Simplifier simplifier)
HE_MeshCollection simplifyThreaded (final HES_Simplifier simplifier)
HE_MeshIterator mItr ()
HE_Mesh getMesh (final int i)
HE_Mesh set (final int i, final HE_Mesh mesh)
boolean add (final HE_Mesh mesh)
boolean addAll (final Collection<?extends HE_Mesh > meshes)
boolean remove (final HE_Mesh mesh)
int getNumberOfMeshes ()
int size ()
void update ()
boolean isFinished ()
Iterator< HE_Mesh > iterator ()
Detailed Description
OBject consisting of several meshes
Constructor & Destructor Documentation
wblut.hemesh.HE_MeshCollection.HE_MeshCollection ()
wblut.hemesh.HE_MeshCollection.HE_MeshCollection (final HEMC_MultiCreator creator)
References wblut.hemesh.HEMC_MultiCreator.create().
Member Function Documentation
boolean wblut.hemesh.HE_MeshCollection.add (final HE_Mesh mesh)
Parameters
mesh
Returns
boolean wblut.hemesh.HE_MeshCollection.addAll (final Collection<?extends HE_Mesh > meshes)
void wblut.hemesh.HE_MeshCollection.createThreaded (final HEMC_MultiCreator creator)
HE_Mesh wblut.hemesh.HE_MeshCollection.getMesh (final int i)
Parameters
i
Returns
References wblut.hemesh.HE_Mesh.get().
int wblut.hemesh.HE_MeshCollection.getNumberOfMeshes ()
Returns
boolean wblut.hemesh.HE_MeshCollection.isFinished ()
Iterator<HE_Mesh> wblut.hemesh.HE_MeshCollection.iterator ()
HE_MeshIterator wblut.hemesh.HE_MeshCollection.mItr ()
Returns
HE_MeshCollection wblut.hemesh.HE_MeshCollection.modify (final HEM_Modifier modifier)
References wblut.hemesh.HEM_Modifier.apply(), and wblut.hemesh.HE_Mesh.clearPrecomputed().
HE_MeshCollection wblut.hemesh.HE_MeshCollection.modifyThreaded (final HEM_Modifier modifier)
References wblut.hemesh.HE_MeshCollection.add().
boolean wblut.hemesh.HE_MeshCollection.remove (final HE_Mesh mesh)
Parameters
mesh
Returns
HE_Mesh wblut.hemesh.HE_MeshCollection.set (final int i, final HE_Mesh mesh)
Parameters
i
mesh
Returns
References wblut.hemesh.HE_Mesh.set().
HE_MeshCollection wblut.hemesh.HE_MeshCollection.simplify (final HES_Simplifier simplifier)
References wblut.hemesh.HE_MeshCollection.add(), and wblut.hemesh.HE_MeshCollection.simplify().
HE_MeshCollection wblut.hemesh.HE_MeshCollection.simplifyThreaded (final HES_Simplifier simplifier)
References wblut.hemesh.HE_MeshCollection.add().
int wblut.hemesh.HE_MeshCollection.size ()
Returns
HE_MeshCollection wblut.hemesh.HE_MeshCollection.subdivide (final HES_Subdividor subdividor)
References wblut.hemesh.HES_Subdividor.apply(), and wblut.hemesh.HE_Mesh.clearPrecomputed().
HE_MeshCollection wblut.hemesh.HE_MeshCollection.subdivideThreaded (final HES_Subdividor subdividor)
References wblut.hemesh.HE_MeshCollection.add().
void wblut.hemesh.HE_MeshCollection.update ()
The documentation for this class was generated from the following file:
src/hemesh_core/wblut/hemesh/HE_MeshCollection.java