HE_Mesh: wblut.hemesh.HES_Planar Class Reference
wblut.hemesh.HES_Planar Class Reference
Public Member Functions
HES_Planar ()
HES_Planar setRandom (final boolean b)
HES_Planar setSeed (final long seed)
HES_Planar setKeepTriangles (final boolean b)
HES_Planar setRange (final double r)
Public Member Functions inherited from wblut.hemesh.HES_Subdividor
HES_Subdividor ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Static Public Member Functions
static void main (final String[] args)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HES_Subdividor
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
boolean random
boolean keepTriangles
double range
final WB_MTRandom randomGen
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Planar subdivision of a mesh. Divides all edges in half. Non-triangular faces are divided in new faces connecting each vertex with the two adjacent mid edge vertices and the face center. Triangular faces are divided in four new triangular faces by connecting the mid edge points. Faces are tris or quads.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HES_Planar.HES_Planar ()
Instantiates a new HES_Planar.
Member Function Documentation
HE_Mesh wblut.hemesh.HES_Planar.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.addFaces(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Selection.addVertices(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Mesh.cycleHalfedges(), wblut.geom.WB_Point.divSelf(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Mesh.getEdgesAsArray(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Mesh.getFaces(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Vertex.getHalfedgeUVW(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Mesh.getNumberOfEdges(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Halfedge.getUVW(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.hasHalfedgeUVW(), wblut.hemesh.HE_Vertex.hasHalfedgeUVW(), wblut.hemesh.HE_Vertex.hasUVW(), wblut.hemesh.HES_Planar.keepTriangles, wblut.hemesh.HE_Face.key(), wblut.geom.WB_Point.mulSelf(), wblut.hemesh.HE_FaceIterator.next(), wblut.math.WB_MTRandom.nextDouble(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HET_MeshOp.pointIsStrictlyInFace(), wblut.hemesh.HES_Planar.range, wblut.hemesh.HE_Mesh.remove(), wblut.math.WB_MTRandom.reset(), wblut.hemesh.HE_Vertex.set(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Vertex.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HET_MeshOp.splitEdge(), wblut.hemesh.HET_MeshOp.splitEdges(), wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), and wblut.hemesh.HE_TextureCoordinate.wd().
HE_Mesh wblut.hemesh.HES_Planar.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.addFaces(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Selection.cleanSelection(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Mesh.cycleHalfedges(), wblut.geom.WB_Point.divSelf(), wblut.hemesh.HE_Selection.fItr(), wblut.hemesh.HE_Selection.getEdgesAsArray(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Selection.getFacesAsArray(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Vertex.getHalfedgeUVW(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Selection.getNumberOfEdges(), wblut.hemesh.HE_Selection.getNumberOfFaces(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Halfedge.getUVW(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.hasHalfedgeUVW(), wblut.hemesh.HE_Vertex.hasHalfedgeUVW(), wblut.hemesh.HE_Vertex.hasUVW(), wblut.hemesh.HES_Planar.keepTriangles, wblut.hemesh.HE_Face.key(), wblut.geom.WB_Point.mulSelf(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_VertexIterator.next(), wblut.math.WB_MTRandom.nextDouble(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HET_MeshOp.pointIsStrictlyInFace(), wblut.hemesh.HES_Planar.range, wblut.hemesh.HE_Mesh.removeFaces(), wblut.math.WB_MTRandom.reset(), wblut.hemesh.HE_Vertex.set(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Vertex.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HET_MeshOp.splitEdge(), wblut.hemesh.HET_MeshOp.splitEdges(), wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), wblut.hemesh.HE_Selection.vItr(), and wblut.hemesh.HE_TextureCoordinate.wd().
static void wblut.hemesh.HES_Planar.main (final String[] args) static
References wblut.hemesh.HES_Planar.HES_Planar(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HES_Planar.setKeepTriangles(), wblut.hemesh.HES_Planar.setRandom(), wblut.hemesh.HES_Planar.setRange(), wblut.hemesh.HES_Planar.setSeed(), wblut.hemesh.HE_Mesh.subdivide(), and wblut.hemesh.HE_Mesh.validate().
HES_Planar wblut.hemesh.HES_Planar.setKeepTriangles (final boolean b)
Set preservation of triangular faces.
Parameters
b true, false
Returns
self
HES_Planar wblut.hemesh.HES_Planar.setRandom (final boolean b)
Set random mode.
Parameters
b true, false
Returns
self
HES_Planar wblut.hemesh.HES_Planar.setRange (final double r)
Set range of random variation.
Parameters
r range (0..1)
Returns
self
HES_Planar wblut.hemesh.HES_Planar.setSeed (final long seed)
Set random seed.
Parameters
seed seed
Returns
self
References wblut.math.WB_MTRandom.setSeed().
Member Data Documentation
boolean wblut.hemesh.HES_Planar.keepTriangles private
Triangular division of triangles?.
boolean wblut.hemesh.HES_Planar.random private
Random subdivision.
final WB_MTRandom wblut.hemesh.HES_Planar.randomGen private
The random gen.
double wblut.hemesh.HES_Planar.range private
Random range.
The documentation for this class was generated from the following file:
src/hemesh_subdividors/wblut/hemesh/HES_Planar.java