HE_Mesh: wblut.hemesh.HEM_MultiSlice Class Reference
wblut.hemesh.HEM_MultiSlice Class Reference
Public Member Functions
HEM_MultiSlice setOffset (final double d)
HEM_MultiSlice ()
HEM_MultiSlice setPlanes (final Collection< WB_Plane > planes)
HEM_MultiSlice setPlanes (final WB_Plane[] planes)
HEM_MultiSlice setLabels (final int[] labels)
HEM_MultiSlice setReverse (final Boolean b)
HEM_MultiSlice setCenter (final WB_Point c)
HEM_MultiSlice setTriangulate (final boolean b)
HEM_MultiSlice setCap (final Boolean b)
HEM_MultiSlice setOptimizeCap (final boolean b)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Public Attributes
HE_Selection origFaces
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
ArrayList< WB_Plane > planes
int[] labels
boolean reverse = false
WB_Point center
boolean capHoles = true
boolean optimizeCap = true
boolean triangulate = false
double offset
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Multiple planar cuts of a mesh. Faces on positive side of cut plane are removed.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_MultiSlice.HEM_MultiSlice ()
Instantiates a new HEM_MultiSlice.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_MultiSlice.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HEM_Slice.applySelf(), wblut.hemesh.HEM_MultiSlice.center, wblut.hemesh.HE_Selection.fItr(), wblut.hemesh.HE_Mesh.fItr(), wblut.geom.WB_Plane.get(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.geom.WB_Plane.getOrigin(), wblut.hemesh.HE_Mesh.getSelection(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), wblut.geom.WB_GeometryOp3D.isEqual(), wblut.hemesh.HE_Mesh.removeSelection(), wblut.hemesh.HE_Mesh.resetFaceInternalLabels(), wblut.hemesh.HEM_Slice.setCap(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HEM_Slice.setOffset(), wblut.hemesh.HEM_Slice.setOptimizeCap(), wblut.hemesh.HEM_Slice.setPlane(), wblut.hemesh.HEM_Slice.setReverse(), and wblut.hemesh.HE_Mesh.triangulateConcaveFaces().
HE_Mesh wblut.hemesh.HEM_MultiSlice.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HEM_MultiSlice.applySelf().
HEM_MultiSlice wblut.hemesh.HEM_MultiSlice.setCap (final Boolean b)
Set option to cap holes.
Parameters
b true, false;
Returns
self
HEM_MultiSlice wblut.hemesh.HEM_MultiSlice.setCenter (final WB_Point c)
Set center for cut plane sorting.
Parameters
c center
Returns
self
References wblut.geom.WB_Point.copy().
HEM_MultiSlice wblut.hemesh.HEM_MultiSlice.setLabels (final int[] labels)
Set labels of cut planes. Cap faces will be labeled.
Parameters
labels array of int
Returns
self
References wblut.hemesh.HEM_MultiSlice.labels.
HEM_MultiSlice wblut.hemesh.HEM_MultiSlice.setOffset (final double d)
Set offset.
Parameters
d offset
Returns
self
HEM_MultiSlice wblut.hemesh.HEM_MultiSlice.setOptimizeCap (final boolean b)
HEM_MultiSlice wblut.hemesh.HEM_MultiSlice.setPlanes (final Collection< WB_Plane > planes)
Set cut planes from an arrayList of WB_Plane.
Parameters
planes arrayList of WB_Plane
Returns
self
HEM_MultiSlice wblut.hemesh.HEM_MultiSlice.setPlanes (final WB_Plane[] planes)
Set cut planes from an array of WB_Plane.
Parameters
planes arrayList of WB_Plane
Returns
self
HEM_MultiSlice wblut.hemesh.HEM_MultiSlice.setReverse (final Boolean b)
Set reverse option.
Parameters
b true, false
Returns
self
HEM_MultiSlice wblut.hemesh.HEM_MultiSlice.setTriangulate (final boolean b)
Parameters
b
Returns
Member Data Documentation
boolean wblut.hemesh.HEM_MultiSlice.capHoles = true private
Cap holes?.
WB_Point wblut.hemesh.HEM_MultiSlice.center private
Center used to sort cut planes.
int [] wblut.hemesh.HEM_MultiSlice.labels private
Labels of cut faces.
double wblut.hemesh.HEM_MultiSlice.offset private
The offset.
boolean wblut.hemesh.HEM_MultiSlice.optimizeCap = true private
The simple cap.
HE_Selection wblut.hemesh.HEM_MultiSlice.origFaces
Original faces?.
ArrayList<WB_Plane> wblut.hemesh.HEM_MultiSlice.planes private
Cut planes.
boolean wblut.hemesh.HEM_MultiSlice.reverse = false private
Reverse planar cuts.
boolean wblut.hemesh.HEM_MultiSlice.triangulate = false private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_MultiSlice.java