HE_Mesh: wblut.geom.WB_Predicates Class Reference
wblut.geom.WB_Predicates Class Reference
Public Member Functions
WB_Predicates ()
Static Public Member Functions
static double orient2D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc)
static double inCircle2D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc, final WB_Coord pd)
static double orient3D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc, final WB_Coord pd)
static double inSphere3D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc, final WB_Coord pd, final WB_Coord pe)
static boolean inTriangle2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord q)
static boolean inTetrahedron3D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4, final WB_Coord q)
static WB_Classification relativeSideOfLine2D (final WB_Coord p0, final WB_Coord p1, final WB_Coord q0, final WB_Coord q1)
static WB_Classification relativeSideOfPlane3D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord q0, final WB_Coord q1)
static boolean diffSideOfLine2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord q1, final WB_Coord q2)
static boolean diffSideOfPlane3D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord q1, final WB_Coord q2)
static boolean onLine2D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2)
static boolean onPlane3D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
static double[] circumcenter2D (final double[] a, final double[] b, final double[] c)
static double[] circumcenter2D (final WB_Coord a, final WB_Coord b, final WB_Coord c)
static double[] circumcenter3D (final double[] a, final double[] b, final double[] c, final double[] d)
static double[] circumcenter3D (final WB_Coord a, final WB_Coord b, final WB_Coord c, final WB_Coord d)
static double[] circumcenter3D (final double[] a, final double[] b, final double[] c, final double[] d, final double[] xi, final double[] eta, final double[] zeta)
static double[] circumcenter3D (final WB_Coord a, final WB_Coord b, final WB_Coord c, final WB_Coord d, final double[] xi, final double[] eta, final double[] zeta)
static double circumradius2D (final double[] p0, final double[] p1, final double[] p2)
static double circumradius2D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2)
static double circumradius3D (final double[] p0, final double[] p1, final double[] p2, final double[] p3)
static double circumradius3D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
static WB_Circle circumcircle2D (final double[] p0, final double[] p1, final double[] p2)
static WB_Circle circumcircle2D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2)
static WB_Sphere circumsphere3D (final double[] p0, final double[] p1, final double[] p2, final double[] p3)
static WB_Sphere circumsphere3D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
static boolean getIntersectionProper2D (final WB_Coord a, final WB_Coord b, final WB_Coord c, final WB_Coord d)
static void main (final String[] args)
Static Private Member Functions
static double findMachEpsilon ()
static void init ()
static double orientDD2D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc)
static double incircleDD2D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc, final WB_Coord pd)
static double orientDD3D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc, final WB_Coord pd)
static double insphereDD3D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc, final WB_Coord pd, final WB_Coord pe)
Static Private Attributes
static double orientErrorBound = -1
static double insphereErrorBound = -1
static double orientErrorBound2D = -1
static double incircleErrorBound2D = -1
Constructor & Destructor Documentation
wblut.geom.WB_Predicates.WB_Predicates ()
Member Function Documentation
static double [] wblut.geom.WB_Predicates.circumcenter2D (final double[] a, final double[] b, final double[] c) static
Circumcenter tri.
Parameters
a the a
b the b
c the c
Returns
the double[]
static double [] wblut.geom.WB_Predicates.circumcenter2D (final WB_Coord a, final WB_Coord b, final WB_Coord c) static
Parameters
a
b
c
Returns
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double [] wblut.geom.WB_Predicates.circumcenter3D (final double[] a, final double[] b, final double[] c, final double[] d) static
Parameters
a
b
c
d
Returns
static double [] wblut.geom.WB_Predicates.circumcenter3D (final WB_Coord a, final WB_Coord b, final WB_Coord c, final WB_Coord d) static
Parameters
a
b
c
d
Returns
References wblut.geom.WB_Predicates.circumcenter3D().
static double [] wblut.geom.WB_Predicates.circumcenter3D (final double[] a, final double[] b, final double[] c, final double[] d, final double[] xi, final double[] eta, final double[] zeta) static
Parameters
a
b
c
d
xi
eta
zeta
Returns
static double [] wblut.geom.WB_Predicates.circumcenter3D (final WB_Coord a, final WB_Coord b, final WB_Coord c, final WB_Coord d, final double[] xi, final double[] eta, final double[] zeta) static
Parameters
a
b
c
d
xi
eta
zeta
Returns
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static WB_Circle wblut.geom.WB_Predicates.circumcircle2D (final double[] p0, final double[] p1, final double[] p2) static
Parameters
p0
p1
p2
Returns
References wblut.geom.WB_Predicates.circumcenter2D().
static WB_Circle wblut.geom.WB_Predicates.circumcircle2D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2) static
Parameters
p0
p1
p2
Returns
References wblut.geom.WB_Predicates.circumcenter2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.geom.WB_Predicates.circumradius2D (final double[] p0, final double[] p1, final double[] p2) static
Circumradius tri.
Parameters
p0 the p0
p1 the p1
p2 the p2
Returns
the double
References wblut.geom.WB_Predicates.circumcenter2D().
static double wblut.geom.WB_Predicates.circumradius2D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2) static
Parameters
p0
p1
p2
Returns
References wblut.geom.WB_Predicates.circumcenter2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.geom.WB_Predicates.circumradius3D (final double[] p0, final double[] p1, final double[] p2, final double[] p3) static
Parameters
p0
p1
p2
p3
Returns
References wblut.geom.WB_Predicates.circumcenter3D().
static double wblut.geom.WB_Predicates.circumradius3D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord p3) static
Parameters
p0
p1
p2
p3
Returns
References wblut.geom.WB_Predicates.circumcenter3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static WB_Sphere wblut.geom.WB_Predicates.circumsphere3D (final double[] p0, final double[] p1, final double[] p2, final double[] p3) static
Parameters
p0
p1
p2
p3
Returns
References wblut.geom.WB_Predicates.circumcenter3D().
static WB_Sphere wblut.geom.WB_Predicates.circumsphere3D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord p3) static
Parameters
p0
p1
p2
p3
Returns
References wblut.geom.WB_Predicates.circumcenter3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static boolean wblut.geom.WB_Predicates.diffSideOfLine2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord q1, final WB_Coord q2) static
Parameters
p1
p2
q1
q2
Returns
References wblut.geom.WB_Predicates.orient2D().
static boolean wblut.geom.WB_Predicates.diffSideOfPlane3D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord q1, final WB_Coord q2) static
Parameters
p1
p2
p3
q1
q2
Returns
References wblut.geom.WB_Predicates.orient3D().
static double wblut.geom.WB_Predicates.findMachEpsilon () static private
static boolean wblut.geom.WB_Predicates.getIntersectionProper2D (final WB_Coord a, final WB_Coord b, final WB_Coord c, final WB_Coord d) static
Parameters
a
b
c
d
Returns
References wblut.geom.WB_Predicates.orient2D().
static double wblut.geom.WB_Predicates.inCircle2D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc, final WB_Coord pd) static
Parameters
pa
pb
pc
pd
Returns
References wblut.geom.WB_Predicates.incircleDD2D(), wblut.geom.WB_Predicates.init(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static double wblut.geom.WB_Predicates.incircleDD2D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc, final WB_Coord pd) static private
Parameters
pa
pb
pc
pd
Returns
References wblut.math.WB_DoubleDouble.add(), wblut.math.WB_DoubleDouble.compareTo(), wblut.math.WB_DoubleDouble.multiply(), wblut.math.WB_DoubleDouble.negate(), wblut.math.WB_DoubleDouble.valueOf(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.math.WB_DoubleDouble.ZERO.
static void wblut.geom.WB_Predicates.init () static private
References wblut.geom.WB_Predicates.findMachEpsilon().
static double wblut.geom.WB_Predicates.inSphere3D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc, final WB_Coord pd, final WB_Coord pe) static
Parameters
pa
pb
pc
pd
pe
Returns
References wblut.geom.WB_Predicates.init(), wblut.geom.WB_Predicates.insphereDD3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.geom.WB_Predicates.insphereDD3D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc, final WB_Coord pd, final WB_Coord pe) static private
References wblut.math.WB_DoubleDouble.add(), wblut.math.WB_DoubleDouble.compareTo(), wblut.math.WB_DoubleDouble.multiply(), wblut.math.WB_DoubleDouble.sqr(), wblut.math.WB_DoubleDouble.subtract(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_Coord.zd(), and wblut.math.WB_DoubleDouble.ZERO.
static boolean wblut.geom.WB_Predicates.inTetrahedron3D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord p4, final WB_Coord q) static
Parameters
p1
p2
p3
p4
q
Returns
References wblut.geom.WB_Predicates.diffSideOfPlane3D().
static boolean wblut.geom.WB_Predicates.inTriangle2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Coord q) static
Parameters
p1
p2
p3
q
Returns
References wblut.geom.WB_Predicates.diffSideOfLine2D().
static void wblut.geom.WB_Predicates.main (final String[] args) static
The main method.
Parameters
args the arguments
References wblut.geom.WB_Predicates.inCircle2D(), and wblut.geom.WB_Predicates.WB_Predicates().
static boolean wblut.geom.WB_Predicates.onLine2D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2) static
Parameters
p0
p1
p2
Returns
References wblut.geom.WB_Predicates.orient2D().
static boolean wblut.geom.WB_Predicates.onPlane3D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord p3) static
Parameters
p0
p1
p2
p3
Returns
References wblut.geom.WB_Predicates.orient3D().
static double wblut.geom.WB_Predicates.orient2D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc) static
Parameters
pa
pb
pc
Returns
References wblut.geom.WB_Predicates.init(), wblut.geom.WB_Predicates.orientDD2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static double wblut.geom.WB_Predicates.orient3D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc, final WB_Coord pd) static
Parameters
pa
pb
pc
pd
Returns
References wblut.geom.WB_Predicates.init(), wblut.geom.WB_Predicates.orientDD3D(), wblut.geom.WB_Predicates.orientErrorBound, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.geom.WB_Predicates.orientDD2D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc) static private
Parameters
pa
pb
pc
Returns
References wblut.math.WB_DoubleDouble.add(), wblut.math.WB_DoubleDouble.compareTo(), wblut.math.WB_DoubleDouble.multiply(), wblut.math.WB_DoubleDouble.negate(), wblut.math.WB_DoubleDouble.valueOf(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.math.WB_DoubleDouble.ZERO.
static double wblut.geom.WB_Predicates.orientDD3D (final WB_Coord pa, final WB_Coord pb, final WB_Coord pc, final WB_Coord pd) static private
References wblut.math.WB_DoubleDouble.add(), wblut.math.WB_DoubleDouble.compareTo(), wblut.math.WB_DoubleDouble.multiply(), wblut.math.WB_DoubleDouble.subtract(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_Coord.zd(), and wblut.math.WB_DoubleDouble.ZERO.
static WB_Classification wblut.geom.WB_Predicates.relativeSideOfLine2D (final WB_Coord p0, final WB_Coord p1, final WB_Coord q0, final WB_Coord q1) static
Parameters
p0
p1
q0
q1
Returns
References wblut.geom.WB_Classification.COLLINEAR, wblut.geom.WB_Classification.DIFF, wblut.geom.WB_Classification.DIFFEXCL, wblut.geom.WB_Predicates.orient2D(), wblut.geom.WB_Classification.SAME, and wblut.geom.WB_Classification.SAMEEXCL.
static WB_Classification wblut.geom.WB_Predicates.relativeSideOfPlane3D (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord q0, final WB_Coord q1) static
Parameters
p0
p1
p2
q0
q1
Returns
References wblut.geom.WB_Classification.COPLANAR, wblut.geom.WB_Classification.DIFF, wblut.geom.WB_Classification.DIFFEXCL, wblut.geom.WB_Predicates.orient3D(), wblut.geom.WB_Classification.SAME, and wblut.geom.WB_Classification.SAMEEXCL.
Member Data Documentation
double wblut.geom.WB_Predicates.incircleErrorBound2D = -1 static private
double wblut.geom.WB_Predicates.insphereErrorBound = -1 static private
double wblut.geom.WB_Predicates.orientErrorBound = -1 static private
double wblut.geom.WB_Predicates.orientErrorBound2D = -1 static private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Predicates.java