HE_Mesh: wblut.hemesh.HEMC_MultiCreator Class Reference
wblut.hemesh.HEMC_MultiCreator Class Reference abstract
Public Member Functions
HEMC_MultiCreator ()
final HE_MeshCollection create ()
int numberOfMeshes ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Attributes
int _numberOfMeshes
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEMC_MultiCreator.HEMC_MultiCreator ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEMC_MultiCreator.apply (final HE_Mesh mesh)
References wblut.hemesh.HEMC_MultiCreator.create().
HE_Mesh wblut.hemesh.HEMC_MultiCreator.apply (final HE_Selection sel)
References wblut.hemesh.HEMC_MultiCreator.create(), and wblut.hemesh.HE_MeshCollection.getMesh().
final HE_MeshCollection wblut.hemesh.HEMC_MultiCreator.create ()
Returns
int wblut.hemesh.HEMC_MultiCreator.numberOfMeshes ()
Returns
References wblut.hemesh.HEMC_MultiCreator._numberOfMeshes.
Member Data Documentation
int wblut.hemesh.HEMC_MultiCreator._numberOfMeshes protected
The documentation for this class was generated from the following file:
src/hemesh_core/wblut/hemesh/HEMC_MultiCreator.java