HE_Mesh: wblut.hemesh.HET_WriterSTL Class Reference
wblut.hemesh.HET_WriterSTL Class Reference
Classes
class DefaultSTLColorModel
class MaterialiseSTLColorModel
class NoColorModel
interface STLColorModel
Public Member Functions
HET_WriterSTL ()
HET_WriterSTL (final STLColorModel cm, final int bufSize)
void beginSave (final OutputStream stream, final int numFaces)
void beginSave (final String fn, final String name, final int numFaces)
void endSave ()
void face (final WB_Coord a, final WB_Coord b, final WB_Coord c, final WB_Coord normal)
void face (final WB_Coord a, final WB_Coord b, final WB_Coord c, final WB_Coord normal, final int rgb)
void setScale (final float s)
void setScale (final WB_Coord s)
void useInvertedNormals (final boolean state)
Static Public Member Functions
static OutputStream createOutputStream (final File file) throws IOException
static void createDirectories (final File file)
Static Public Attributes
static final int DEFAULT_RGB = -1
static final STLColorModel NONE = new NoColorModel()
static final STLColorModel DEFAULT = new DefaultSTLColorModel()
static final STLColorModel MATERIALISE = new MaterialiseSTLColorModel(0xffffffff)
static final int DEFAULT_BUFFER = 0x10000
Protected Member Functions
void writeFloat (final float a) throws IOException
void writeHeader (final int num) throws IOException
void writeInt (final int a) throws IOException
void writeScaledVector (final WB_Coord v)
void writeShort (final int a) throws IOException
void writeVector (final WB_Coord v)
Protected Attributes
OutputStream ds
byte[] buf = new byte[4]
int bufferSize
WB_Vector scale = new WB_Vector(1, 1, 1)
boolean useInvertedNormals = false
STLColorModel colorModel
Private Member Functions
final void prepareBuffer (final int a)
Detailed Description
A simple, but flexible and memory efficient exporter for binary STL files. Custom color support is implemented via the STLcolorModel interface and the exporter comes with the 2 most common format variations defined by the DEFAULT and MATERIALISE constants.
The minimal design of this exporter means it does not build an extra list of faces in RAM and so is able to easily export models with millions of faces.
http://en.wikipedia.org/wiki/STL_(file_format)
Constructor & Destructor Documentation
wblut.hemesh.HET_WriterSTL.HET_WriterSTL ()
References wblut.hemesh.HET_WriterSTL.DEFAULT, and wblut.hemesh.HET_WriterSTL.DEFAULT_BUFFER.
wblut.hemesh.HET_WriterSTL.HET_WriterSTL (final STLColorModel cm, final int bufSize)
Parameters
cm
bufSize
Member Function Documentation
void wblut.hemesh.HET_WriterSTL.beginSave (final OutputStream stream, final int numFaces)
Parameters
stream
numFaces
References wblut.hemesh.HET_WriterSTL.writeHeader().
void wblut.hemesh.HET_WriterSTL.beginSave (final String fn, final String name, final int numFaces)
Parameters
fn
name
numFaces
References wblut.hemesh.HET_WriterSTL.beginSave(), and wblut.hemesh.HET_WriterSTL.createOutputStream().
static void wblut.hemesh.HET_WriterSTL.createDirectories (final File file) static
Parameters
file
static OutputStream wblut.hemesh.HET_WriterSTL.createOutputStream (final File file) throws IOException static
Parameters
file
Returns
Exceptions
IOException
References wblut.hemesh.HET_WriterSTL.createDirectories().
void wblut.hemesh.HET_WriterSTL.endSave ()
void wblut.hemesh.HET_WriterSTL.face (final WB_Coord a, final WB_Coord b, final WB_Coord c, final WB_Coord normal)
Parameters
a
b
c
normal
void wblut.hemesh.HET_WriterSTL.face (final WB_Coord a, final WB_Coord b, final WB_Coord c, final WB_Coord normal, final int rgb)
Parameters
a
b
c
normal
rgb
References wblut.hemesh.HET_WriterSTL.STLColorModel.formatRGB(), wblut.hemesh.HET_WriterSTL.STLColorModel.getDefaultRGB(), wblut.hemesh.HET_WriterSTL.writeScaledVector(), wblut.hemesh.HET_WriterSTL.writeShort(), and wblut.hemesh.HET_WriterSTL.writeVector().
final void wblut.hemesh.HET_WriterSTL.prepareBuffer (final int a) private
Parameters
a
void wblut.hemesh.HET_WriterSTL.setScale (final float s)
Parameters
s
References wblut.geom.WB_MutableCoordinate.set().
void wblut.hemesh.HET_WriterSTL.setScale (final WB_Coord s)
Parameters
s
References wblut.geom.WB_MutableCoordinate.set().
void wblut.hemesh.HET_WriterSTL.useInvertedNormals (final boolean state)
Parameters
state
void wblut.hemesh.HET_WriterSTL.writeFloat (final float a) throws IOException protected
Parameters
a
Exceptions
IOException
References wblut.hemesh.HET_WriterSTL.prepareBuffer().
void wblut.hemesh.HET_WriterSTL.writeHeader (final int num) throws IOException protected
Parameters
num
Exceptions
IOException
References wblut.hemesh.HET_WriterSTL.STLColorModel.formatHeader(), and wblut.hemesh.HET_WriterSTL.writeInt().
void wblut.hemesh.HET_WriterSTL.writeInt (final int a) throws IOException protected
Parameters
a
Exceptions
IOException
References wblut.hemesh.HET_WriterSTL.prepareBuffer().
void wblut.hemesh.HET_WriterSTL.writeScaledVector (final WB_Coord v) protected
Parameters
v
References wblut.hemesh.HET_WriterSTL.writeFloat(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_MutableCoordinate.xf(), wblut.geom.WB_Coord.yf(), wblut.geom.WB_MutableCoordinate.yf(), wblut.geom.WB_Coord.zf(), and wblut.geom.WB_MutableCoordinate.zf().
void wblut.hemesh.HET_WriterSTL.writeShort (final int a) throws IOException protected
Parameters
a
Exceptions
IOException
void wblut.hemesh.HET_WriterSTL.writeVector (final WB_Coord v) protected
Parameters
v
References wblut.hemesh.HET_WriterSTL.writeFloat(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
Member Data Documentation
byte [] wblut.hemesh.HET_WriterSTL.buf = new byte[4] protected
int wblut.hemesh.HET_WriterSTL.bufferSize protected
STLColorModel wblut.hemesh.HET_WriterSTL.colorModel protected
final STLColorModel wblut.hemesh.HET_WriterSTL.DEFAULT = new DefaultSTLColorModel() static
final int wblut.hemesh.HET_WriterSTL.DEFAULT_BUFFER = 0x10000 static
final int wblut.hemesh.HET_WriterSTL.DEFAULT_RGB = -1 static
OutputStream wblut.hemesh.HET_WriterSTL.ds protected
final STLColorModel wblut.hemesh.HET_WriterSTL.MATERIALISE = new MaterialiseSTLColorModel(0xffffffff) static
final STLColorModel wblut.hemesh.HET_WriterSTL.NONE = new NoColorModel() static
WB_Vector wblut.hemesh.HET_WriterSTL.scale = new WB_Vector(1, 1, 1) protected
boolean wblut.hemesh.HET_WriterSTL.useInvertedNormals = false protected
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_WriterSTL.java