HE_Mesh: wblut.processing.WB_PVector Class Reference
wblut.processing.WB_PVector Class Reference
Public Member Functions
double xd ()
double yd ()
double zd ()
double wd ()
double getd (final int i)
float xf ()
float yf ()
float zf ()
float wf ()
float getf (final int i)
void setX (final double x)
void setY (final double y)
void setZ (final double z)
void setW (final double w)
void setCoord (final int i, final double v)
void set (final WB_Coord p)
void set (final double x, final double y)
void set (final double x, final double y, final double z)
void set (final double x, final double y, final double z, final double w)
int compareTo (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
Public Member Functions inherited from wblut.geom.WB_MutableCoord
void setX (double x)
void setY (double y)
void setZ (double z)
void setW (double w)
void setCoord (int i, double v)
void set (WB_Coord p)
void set (double x, double y)
void set (double x, double y, double z)
void set (double x, double y, double z, double w)
Public Member Functions inherited from wblut.geom.WB_Coord
double getd (int i)
float getf (int i)
Static Private Attributes
static final long serialVersionUID = 3211029434911447698L
Member Function Documentation
int wblut.processing.WB_PVector.compareTo (final WB_Coord p)
References wblut.geom.WB_Coord.wd(), wblut.processing.WB_PVector.wd(), wblut.geom.WB_Coord.xd(), wblut.processing.WB_PVector.xd(), wblut.geom.WB_Coord.yd(), wblut.processing.WB_PVector.yd(), wblut.geom.WB_Coord.zd(), and wblut.processing.WB_PVector.zd().
boolean wblut.processing.WB_PVector.equals (final Object o)
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_Coord.xd(), wblut.processing.WB_PVector.xd(), wblut.geom.WB_Coord.yd(), wblut.processing.WB_PVector.yd(), wblut.geom.WB_Coord.zd(), and wblut.processing.WB_PVector.zd().
double wblut.processing.WB_PVector.getd (final int i)
float wblut.processing.WB_PVector.getf (final int i)
int wblut.processing.WB_PVector.hashCode ()
References wblut.math.WB_HashCode.calculateHashCode(), wblut.processing.WB_PVector.xd(), wblut.processing.WB_PVector.yd(), and wblut.processing.WB_PVector.zd().
void wblut.processing.WB_PVector.set (final WB_Coord p)
References wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
void wblut.processing.WB_PVector.set (final double x, final double y)
void wblut.processing.WB_PVector.set (final double x, final double y, final double z)
void wblut.processing.WB_PVector.set (final double x, final double y, final double z, final double w)
void wblut.processing.WB_PVector.setCoord (final int i, final double v)
void wblut.processing.WB_PVector.setW (final double w)
void wblut.processing.WB_PVector.setX (final double x)
void wblut.processing.WB_PVector.setY (final double y)
void wblut.processing.WB_PVector.setZ (final double z)
double wblut.processing.WB_PVector.wd ()
Get w as double.
Returns
w
Implements wblut.geom.WB_Coord.
float wblut.processing.WB_PVector.wf ()
Get w as float.
Returns
w
Implements wblut.geom.WB_Coord.
double wblut.processing.WB_PVector.xd ()
Get x as double.
Returns
x
Implements wblut.geom.WB_Coord.
float wblut.processing.WB_PVector.xf ()
Get x as float.
Returns
x
Implements wblut.geom.WB_Coord.
double wblut.processing.WB_PVector.yd ()
Get y as double.
Returns
y
Implements wblut.geom.WB_Coord.
float wblut.processing.WB_PVector.yf ()
Get y as float.
Returns
y
Implements wblut.geom.WB_Coord.
double wblut.processing.WB_PVector.zd ()
Get z as double.
Returns
z
Implements wblut.geom.WB_Coord.
float wblut.processing.WB_PVector.zf ()
Get z as float.
Returns
z
Implements wblut.geom.WB_Coord.
Member Data Documentation
final long wblut.processing.WB_PVector.serialVersionUID = 3211029434911447698L static private
The documentation for this class was generated from the following file:
src/processing/wblut/processing/WB_PVector.java