HE_Mesh: wblut.hemesh.HE_Face Class Reference
wblut.hemesh.HE_Face Class Reference
Public Member Functions
HE_Face ()
HE_FaceEdgeCirculator feCrc ()
HE_FaceFaceCirculator ffCrc ()
HE_FaceVertexCirculator fvCrc ()
HE_FaceHalfedgeInnerCirculator fheiCrc ()
HE_FaceHalfedgeOuterCirculator fheoCrc ()
HE_FaceEdgeRevCirculator feRevCrc ()
HE_FaceFaceRevCirculator ffRevCrc ()
HE_FaceHalfedgeInnerRevCirculator fheiRevCrc ()
HE_FaceHalfedgeOuterRevCirculator fheoRevCrc ()
HE_FaceVertexRevCirculator fvRevCrc ()
long key ()
WB_Coord getFaceCenter ()
WB_Coord getFaceCenter (final double d)
WB_Coord getFaceNormal ()
WB_Coord getNonNormFaceNormal ()
double getFaceArea ()
WB_Classification getFaceType ()
List< HE_Vertex > getUniqueFaceVertices ()
List< HE_Vertex > getFaceVertices ()
List< HE_TextureCoordinate > getFaceUVWs ()
int getFaceDegree ()
List< HE_Halfedge > getFaceHalfedges ()
List< HE_Halfedge > getFaceHalfedgesTwoSided ()
List< HE_Halfedge > getFaceEdges ()
HE_Halfedge getHalfedge ()
HE_Halfedge getHalfedge (final HE_Vertex v)
HE_Halfedge getHalfedge (final HE_Face f)
void push (final WB_Coord c)
WB_Plane toPlane ()
WB_Plane getPlane ()
WB_Plane getPlane (final double d)
void sort ()
int compareTo (final HE_Face f)
int[] getTriangles ()
int[] getTriangles (final boolean optimize)
WB_AABB toAABB ()
WB_AABB getAABB ()
WB_Triangle toTriangle ()
WB_Polygon toPolygon ()
WB_Polygon toOrthoPolygon ()
WB_Polygon toPlanarPolygon ()
List< HE_Face > getNeighborFaces ()
String toString ()
boolean isPlanar ()
boolean isBoundary ()
boolean isDegenerate ()
void copyProperties (final HE_Face el)
void clear ()
void checkValidity ()
int getTextureId ()
void setTextureId (final int i)
void clearPrecomputed ()
WB_Coord getClosestPoint (final WB_Coord p)
boolean isNeighbor (final HE_Face f)
WB_CoordinateSystem3D getOrthonormalBase ()
WB_CoordCollection getPoints ()
Public Member Functions inherited from wblut.hemesh.HE_MeshElement
HE_MeshElement ()
void clearVisited ()
void setVisited ()
void setVisited (final boolean b)
boolean isVisited ()
void setVisible (final boolean b)
boolean isVisible ()
int hashCode ()
boolean equals (final Object other)
void copyProperties (final HE_MeshElement el)
int getColor ()
void setColor (final int color)
Public Member Functions inherited from wblut.hemesh.HE_Element
HE_Element ()
final void setUserLabel (final int label)
final long getKey ()
final int getInternalLabel ()
final int getUserLabel ()
int hashCode ()
boolean equals (final Object other)
void copyProperties (final HE_Element el)
Protected Member Functions
void _setHalfedge (final HE_Halfedge halfedge)
void _clearHalfedge ()
Protected Member Functions inherited from wblut.hemesh.HE_MeshElement
abstract void clear ()
Protected Member Functions inherited from wblut.hemesh.HE_Element
final void setInternalLabel (final int label)
abstract void clear ()
abstract void clearPrecomputed ()
Private Attributes
HE_Halfedge _halfedge
int textureId
Additional Inherited Members
Protected Attributes inherited from wblut.hemesh.HE_MeshElement
volatile boolean visited
boolean visible
int color
Protected Attributes inherited from wblut.hemesh.HE_Element
final long key
int internalLabel
int userLabel
Static Protected Attributes inherited from wblut.hemesh.HE_MeshElement
static final WB_GeometryFactory gf = new WB_GeometryFactory()
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Static Protected Attributes inherited from wblut.hemesh.HE_Element
static AtomicLong currentKey = new AtomicLong(0)
Detailed Description
Face element of half-edge data structure.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HE_Face.HE_Face ()
Instantiates a new HE_Face.
Member Function Documentation
void wblut.hemesh.HE_Face._clearHalfedge () protected
void wblut.hemesh.HE_Face._setHalfedge (final HE_Halfedge halfedge) protected
Parameters
halfedge
void wblut.hemesh.HE_Face.checkValidity ()
References wblut.hemesh.HE_Face._halfedge, wblut.geom.WB_GeometryFactory3D.createEmbeddedPlane(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.hemesh.HE_Face.getFaceArea(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Face.getPlane(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshElement.gf, wblut.geom.WB_Map.mapPoint3D(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
void wblut.hemesh.HE_Face.clear ()
void wblut.hemesh.HE_Face.clearPrecomputed ()
int wblut.hemesh.HE_Face.compareTo (final HE_Face f)
Parameters
f
Returns
References wblut.hemesh.HE_Halfedge.compareTo(), and wblut.hemesh.HE_Face.getHalfedge().
void wblut.hemesh.HE_Face.copyProperties (final HE_Face el)
Parameters
el
References wblut.hemesh.HE_Face.textureId.
HE_FaceEdgeCirculator wblut.hemesh.HE_Face.feCrc ()
Returns
HE_FaceEdgeRevCirculator wblut.hemesh.HE_Face.feRevCrc ()
Returns
HE_FaceFaceCirculator wblut.hemesh.HE_Face.ffCrc ()
Returns
HE_FaceFaceRevCirculator wblut.hemesh.HE_Face.ffRevCrc ()
Returns
HE_FaceHalfedgeInnerCirculator wblut.hemesh.HE_Face.fheiCrc ()
Returns
HE_FaceHalfedgeInnerRevCirculator wblut.hemesh.HE_Face.fheiRevCrc ()
Returns
HE_FaceHalfedgeOuterCirculator wblut.hemesh.HE_Face.fheoCrc ()
Returns
HE_FaceHalfedgeOuterRevCirculator wblut.hemesh.HE_Face.fheoRevCrc ()
Returns
HE_FaceVertexCirculator wblut.hemesh.HE_Face.fvCrc ()
Returns
HE_FaceVertexRevCirculator wblut.hemesh.HE_Face.fvRevCrc ()
Returns
WB_AABB wblut.hemesh.HE_Face.getAABB ()
Returns
References wblut.geom.WB_AABB.expandToInclude(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getVertex().
WB_Coord wblut.hemesh.HE_Face.getClosestPoint (final WB_Coord p)
References wblut.geom.WB_GeometryOp3D.getClosestPointToTriangle3D(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getHalfedge(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), and wblut.hemesh.HE_Face.getTriangles().
double wblut.hemesh.HE_Face.getFaceArea ()
Returns
References wblut.hemesh.HET_MeshOp.getFaceArea().
WB_Coord wblut.hemesh.HE_Face.getFaceCenter ()
Returns
References wblut.hemesh.HE_Face._halfedge, wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.divSelf(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getVertex().
WB_Coord wblut.hemesh.HE_Face.getFaceCenter (final double d)
Parameters
d
Returns
References wblut.hemesh.HE_Face._halfedge, wblut.geom.WB_Point.addMul(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.divSelf(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getVertex().
int wblut.hemesh.HE_Face.getFaceDegree ()
Returns
References wblut.hemesh.HE_Face._halfedge, and wblut.hemesh.HE_Halfedge.getNextInFace().
List<HE_Halfedge> wblut.hemesh.HE_Face.getFaceEdges ()
Returns
References wblut.hemesh.HE_Face._halfedge, wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPair(), and wblut.hemesh.HE_Halfedge.isEdge().
List<HE_Halfedge> wblut.hemesh.HE_Face.getFaceHalfedges ()
Returns
References wblut.hemesh.HE_Face._halfedge, and wblut.hemesh.HE_Halfedge.getNextInFace().
List<HE_Halfedge> wblut.hemesh.HE_Face.getFaceHalfedgesTwoSided ()
Returns
References wblut.hemesh.HE_Face._halfedge, wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getPair().
WB_Coord wblut.hemesh.HE_Face.getFaceNormal ()
Returns
References wblut.hemesh.HET_MeshOp.getFaceNormal().
WB_Classification wblut.hemesh.HE_Face.getFaceType ()
Returns
References wblut.hemesh.HET_MeshOp.getFaceType().
List<HE_TextureCoordinate> wblut.hemesh.HE_Face.getFaceUVWs ()
Returns
References wblut.hemesh.HE_Face._halfedge, wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getUVW(), and wblut.hemesh.HE_Halfedge.getVertex().
List<HE_Vertex> wblut.hemesh.HE_Face.getFaceVertices ()
References wblut.hemesh.HE_Face._halfedge, wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getVertex().
HE_Halfedge wblut.hemesh.HE_Face.getHalfedge ()
Returns
References wblut.hemesh.HE_Face._halfedge.
HE_Halfedge wblut.hemesh.HE_Face.getHalfedge (final HE_Vertex v)
Parameters
v
Returns
References wblut.hemesh.HE_Face._halfedge, wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getVertex().
HE_Halfedge wblut.hemesh.HE_Face.getHalfedge (final HE_Face f)
Parameters
f
Returns
References wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getPair().
List<HE_Face> wblut.hemesh.HE_Face.getNeighborFaces ()
Returns
References wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getPair().
WB_Coord wblut.hemesh.HE_Face.getNonNormFaceNormal ()
Returns
References wblut.hemesh.HET_MeshOp.getFaceNormalNotNormalized().
WB_CoordinateSystem3D wblut.hemesh.HE_Face.getOrthonormalBase ()
References wblut.geom.WB_Vector.cross(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Face.getHalfedge(), and wblut.hemesh.HE_Halfedge.getHalfedgeTangent().
WB_Plane wblut.hemesh.HE_Face.getPlane ()
Returns
References wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.geom.WB_Vector.getSqLength3D(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.math.WB_Epsilon.isEqualAbs(), and wblut.hemesh.HE_Vertex.xd().
WB_Plane wblut.hemesh.HE_Face.getPlane (final double d)
Parameters
d
Returns
References wblut.geom.WB_Point.addMul(), wblut.hemesh.HE_Face.getFaceCenter(), and wblut.hemesh.HE_Face.getFaceNormal().
WB_CoordCollection wblut.hemesh.HE_Face.getPoints ()
Implements wblut.geom.WB_TriangleGenerator.
References wblut.geom.WB_CoordCollection.getCollection(), and wblut.hemesh.HE_Face.getFaceVertices().
int wblut.hemesh.HE_Face.getTextureId ()
Returns
References wblut.hemesh.HE_Face.textureId.
int [] wblut.hemesh.HE_Face.getTriangles ()
Returns
Implements wblut.geom.WB_TriangleGenerator.
int [] wblut.hemesh.HE_Face.getTriangles (final boolean optimize)
Parameters
optimize
Returns
References wblut.hemesh.HE_Face._halfedge, wblut.hemesh.HE_Face.getFaceDegree(), wblut.geom.WB_Triangulation2D.getTriangles(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Face.isDegenerate(), wblut.hemesh.HE_Face.toOrthoPolygon(), wblut.geom.WB_PolygonTriangulatorJTS.triangulatePolygon2D(), wblut.geom.WB_PolygonTriangulatorJTS.triangulateQuad(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), and wblut.hemesh.HE_Vertex.zd().
List<HE_Vertex> wblut.hemesh.HE_Face.getUniqueFaceVertices ()
Returns
References wblut.hemesh.HE_Face._halfedge, wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getVertex().
boolean wblut.hemesh.HE_Face.isBoundary ()
Checks if is boundary.
Returns
true, if is boundary
References wblut.hemesh.HE_Face._halfedge, wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getPair().
boolean wblut.hemesh.HE_Face.isDegenerate ()
Returns
References wblut.hemesh.HE_Face.getFaceNormal(), and wblut.geom.WB_Vector.getLength3D().
boolean wblut.hemesh.HE_Face.isNeighbor (final HE_Face f)
References wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getPair().
boolean wblut.hemesh.HE_Face.isPlanar ()
Returns
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Face.getPlane(), wblut.hemesh.HE_Halfedge.getVertex(), and wblut.math.WB_Epsilon.isZero().
long wblut.hemesh.HE_Face.key ()
Returns
void wblut.hemesh.HE_Face.push (final WB_Coord c)
Parameters
c
References wblut.hemesh.HE_Face._halfedge, wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Vertex.getPosition(), and wblut.hemesh.HE_Halfedge.getVertex().
void wblut.hemesh.HE_Face.setTextureId (final int i)
Parameters
i
void wblut.hemesh.HE_Face.sort ()
References wblut.hemesh.HE_Face._halfedge, wblut.hemesh.HE_Vertex.compareTo(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getVertex().
WB_AABB wblut.hemesh.HE_Face.toAABB ()
Returns
References wblut.hemesh.HE_Face.getAABB().
WB_Polygon wblut.hemesh.HE_Face.toOrthoPolygon ()
Returns
References wblut.hemesh.HE_Face._halfedge, wblut.geom.WB_GeometryFactory2D.createSimplePolygon(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshElement.gf, and wblut.geom.WB_OrthoProject.mapPoint3D().
WB_Polygon wblut.hemesh.HE_Face.toPlanarPolygon ()
Returns
References wblut.hemesh.HE_Face._halfedge, wblut.geom.WB_GeometryFactory2D.createSimplePolygon(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Face.getPlane(), wblut.hemesh.HE_Halfedge.getVertex(), and wblut.hemesh.HE_MeshElement.gf.
WB_Plane wblut.hemesh.HE_Face.toPlane ()
Returns
References wblut.hemesh.HE_Face.getPlane().
WB_Polygon wblut.hemesh.HE_Face.toPolygon ()
Returns
References wblut.hemesh.HE_Face._halfedge, wblut.geom.WB_GeometryFactory2D.createSimplePolygon(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshElement.gf, wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), and wblut.hemesh.HE_Vertex.zd().
String wblut.hemesh.HE_Face.toString ()
References wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Element.getUserLabel(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Face.key(), and wblut.hemesh.HE_Vertex.key().
WB_Triangle wblut.hemesh.HE_Face.toTriangle ()
Returns
References wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Halfedge.getVertex().
Member Data Documentation
HE_Halfedge wblut.hemesh.HE_Face._halfedge private
Halfedge associated with this face.
int wblut.hemesh.HE_Face.textureId private
The documentation for this class was generated from the following file:
src/hemesh_core/wblut/hemesh/HE_Face.java