HE_Mesh: wblut.geom.WB_AlphaTriangulation2D Class Reference
wblut.geom.WB_AlphaTriangulation2D Class Reference
Classes
class Key
class Tuple
Public Member Functions
WB_AlphaTriangulation2D (final int[] tris, final Collection<?extends WB_Coord > points)
WB_AlphaTriangulation2D (final int[][] tris, final Collection<?extends WB_Coord > points)
WB_AlphaTriangulation2D (final int[] tris, final WB_Coord[] points)
WB_AlphaTriangulation2D (final int[][] tris, final WB_Coord[] points)
int[] getTriangles ()
int[] getEdges ()
WB_CoordCollection getPoints ()
double[] getAlpha ()
int[] getAlphaTriangles (final double a)
int[] getAlphaEdges (final double a)
Private Member Functions
void setAlpha ()
void extractEdges (final int[] tris)
long getIndex (final int i, final int j, final int f)
Private Attributes
int[] triangles
int[] edges
double[] alpha
FastList< WB_Coord > points
Detailed Description
WB_AlphaTriangulation2D stores the results of WB_Triangulate.alphaTriangulate2D: a 2D Delaunay triangulation with the corresponding circumcircle radii.
Constructor & Destructor Documentation
wblut.geom.WB_AlphaTriangulation2D.WB_AlphaTriangulation2D (final int[] tris, final Collection<?extends WB_Coord > points)
Parameters
tris
points
References wblut.geom.WB_AlphaTriangulation2D.extractEdges(), and wblut.geom.WB_AlphaTriangulation2D.setAlpha().
wblut.geom.WB_AlphaTriangulation2D.WB_AlphaTriangulation2D (final int tris[][], final Collection<?extends WB_Coord > points)
Parameters
tris
points
References wblut.geom.WB_AlphaTriangulation2D.extractEdges(), and wblut.geom.WB_AlphaTriangulation2D.setAlpha().
wblut.geom.WB_AlphaTriangulation2D.WB_AlphaTriangulation2D (final int[] tris, final WB_Coord[] points)
Parameters
tris
points
References wblut.geom.WB_AlphaTriangulation2D.extractEdges(), and wblut.geom.WB_AlphaTriangulation2D.setAlpha().
wblut.geom.WB_AlphaTriangulation2D.WB_AlphaTriangulation2D (final int tris[][], final WB_Coord[] points)
Parameters
tris
points
References wblut.geom.WB_AlphaTriangulation2D.extractEdges(), and wblut.geom.WB_AlphaTriangulation2D.setAlpha().
Member Function Documentation
void wblut.geom.WB_AlphaTriangulation2D.extractEdges (final int[] tris) private
References wblut.geom.WB_AlphaTriangulation2D.getIndex().
double [] wblut.geom.WB_AlphaTriangulation2D.getAlpha ()
Get the circumradii of the triangle vertices as a single array of double. Original values are copied.
Returns
int [] wblut.geom.WB_AlphaTriangulation2D.getAlphaEdges (final double a)
int [] wblut.geom.WB_AlphaTriangulation2D.getAlphaTriangles (final double a)
Get the indices to the alpha triangle vertices as a single array of int. 3 indices per triangle. Only triangles with a circumradius smaller or equal to a are returned.
Parameters
a alpha value
Returns
int [] wblut.geom.WB_AlphaTriangulation2D.getEdges ()
Returns
References wblut.geom.WB_AlphaTriangulation2D.edges.
long wblut.geom.WB_AlphaTriangulation2D.getIndex (final int i, final int j, final int f) private
WB_CoordCollection wblut.geom.WB_AlphaTriangulation2D.getPoints ()
Get the vertices of the triangulation as an unmodifiable List<WB_Coord>.
Returns
Implements wblut.geom.WB_TriangleGenerator.
References wblut.geom.WB_CoordCollection.getCollection().
int [] wblut.geom.WB_AlphaTriangulation2D.getTriangles ()
Get the indices to the triangles vertices as a single array of int. 3 indices per triangle.
Returns
Implements wblut.geom.WB_TriangleGenerator.
References wblut.geom.WB_AlphaTriangulation2D.triangles.
void wblut.geom.WB_AlphaTriangulation2D.setAlpha () private
References wblut.geom.WB_Predicates.circumradius2D().
Member Data Documentation
double [] wblut.geom.WB_AlphaTriangulation2D.alpha private
int [] wblut.geom.WB_AlphaTriangulation2D.edges private
FastList<WB_Coord> wblut.geom.WB_AlphaTriangulation2D.points private
int [] wblut.geom.WB_AlphaTriangulation2D.triangles private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_AlphaTriangulation2D.java