HE_Mesh: wblut.hemesh.HEM_ChamferCorners Class Reference
wblut.hemesh.HEM_ChamferCorners Class Reference
Public Member Functions
HEM_ChamferCorners ()
HEM_ChamferCorners setDistance (final double d)
HEM_ChamferCorners setDistance (final WB_ScalarParameter d)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_ScalarParameter distance
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Chamfer all convex corners.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_ChamferCorners.HEM_ChamferCorners ()
Instantiates a new HEM_ChamferCorners.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_ChamferCorners.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_Classification.CONVEX, wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Mesh.modify(), wblut.geom.WB_Point.mulSelf(), wblut.geom.WB_Vector.mulSelf(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HE_Mesh.renameSelection(), wblut.hemesh.HEM_MultiSlice.setPlanes(), and wblut.hemesh.HE_Mesh.vItr().
HE_Mesh wblut.hemesh.HEM_ChamferCorners.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Vector.addSelf(), wblut.hemesh.HE_Selection.collectVertices(), wblut.geom.WB_Classification.CONVEX, wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_Vertex.getVertexType(), wblut.hemesh.HE_Mesh.modify(), wblut.geom.WB_Point.mulSelf(), wblut.geom.WB_Vector.mulSelf(), wblut.hemesh.HE_Mesh.renameSelection(), wblut.hemesh.HEM_MultiSlice.setPlanes(), wblut.hemesh.HE_Selection.vItr(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), and wblut.hemesh.HE_Vertex.zd().
HEM_ChamferCorners wblut.hemesh.HEM_ChamferCorners.setDistance (final double d)
Set chamfer distance along vertex normals.
Parameters
d distance
Returns
self
HEM_ChamferCorners wblut.hemesh.HEM_ChamferCorners.setDistance (final WB_ScalarParameter d)
Set chamfer distance along vertex normals.
Parameters
d WB_Parameter
Returns
self
Member Data Documentation
WB_ScalarParameter wblut.hemesh.HEM_ChamferCorners.distance private
Chamfer distance.
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_ChamferCorners.java