HE_Mesh: wblut.geom.WB_Plane Class Reference
wblut.geom.WB_Plane Class Reference
Public Member Functions
WB_Plane (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
WB_Plane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
WB_Plane (final WB_Coord o, final WB_Coord n)
WB_Plane (final WB_Coord n, final double d)
WB_Plane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz, final double d)
WB_Plane (final WB_Coord o, final WB_Coord n, final double d)
WB_Plane (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final double d)
WB_Plane get ()
WB_Vector getNormal ()
double a ()
double b ()
double c ()
double d ()
WB_Point getOrigin ()
void flipNormal ()
String toString ()
WB_Point localPoint (final WB_Coord p)
WB_Point localPoint2D (final WB_Coord p)
WB_Point extractPoint (final WB_Coord p)
WB_Point extractPoint (final double x, final double y)
WB_Point extractPoint2D (final WB_Coord p)
WB_Point extractPoint (final double x, final double y, final double z)
WB_Point mirrorPoint (final WB_Coord p)
WB_Vector getU ()
WB_Vector getV ()
WB_Vector getW ()
Static Public Member Functions
static final WB_Plane XY ()
static final WB_Plane XZ ()
static final WB_Plane YZ ()
Protected Member Functions
void set (final WB_Coord o, final WB_Coord n)
Private Member Functions
void setAxes ()
Private Attributes
WB_Vector n
WB_Point origin
WB_Vector u
Constructor & Destructor Documentation
wblut.geom.WB_Plane.WB_Plane (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
Parameters
p1
p2
p3
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Plane.setAxes().
wblut.geom.WB_Plane.WB_Plane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
Parameters
ox
oy
oz
nx
ny
nz
References wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Plane.setAxes().
wblut.geom.WB_Plane.WB_Plane (final WB_Coord o, final WB_Coord n)
Parameters
o
n
References wblut.geom.WB_Plane.setAxes().
wblut.geom.WB_Plane.WB_Plane (final WB_Coord n, final double d)
Parameters
n
d
References wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Plane.setAxes(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
wblut.geom.WB_Plane.WB_Plane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz, final double d)
Parameters
ox
oy
oz
nx
ny
nz
d
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Plane.setAxes().
wblut.geom.WB_Plane.WB_Plane (final WB_Coord o, final WB_Coord n, final double d)
Parameters
o
n
d
References wblut.geom.WB_Point.addMulSelf(), and wblut.geom.WB_Plane.setAxes().
wblut.geom.WB_Plane.WB_Plane (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final double d)
Parameters
p1
p2
p3
d
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Plane.setAxes().
Member Function Documentation
double wblut.geom.WB_Plane.a ()
Returns
References wblut.geom.WB_MutableCoordinate.xd().
double wblut.geom.WB_Plane.b ()
Returns
References wblut.geom.WB_MutableCoordinate.yd().
double wblut.geom.WB_Plane.c ()
Returns
References wblut.geom.WB_MutableCoordinate.zd().
double wblut.geom.WB_Plane.d ()
Returns
References wblut.geom.WB_Vector.dot().
WB_Point wblut.geom.WB_Plane.extractPoint (final WB_Coord p)
Extract point.
Parameters
p
Returns
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Point wblut.geom.WB_Plane.extractPoint (final double x, final double y)
Extract point.
Parameters
x
y
Returns
References wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Point wblut.geom.WB_Plane.extractPoint (final double x, final double y, final double z)
Extract point.
Parameters
x
y
z
Returns
References wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Point wblut.geom.WB_Plane.extractPoint2D (final WB_Coord p)
Extract point.
Parameters
p
Returns
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_Plane.flipNormal ()
References wblut.geom.WB_Vector.mulSelf(), and wblut.geom.WB_Plane.setAxes().
WB_Plane wblut.geom.WB_Plane.get ()
Returns
References wblut.geom.WB_Plane.WB_Plane().
WB_Vector wblut.geom.WB_Plane.getNormal ()
Returns
References wblut.geom.WB_Vector.copy().
WB_Point wblut.geom.WB_Plane.getOrigin ()
Returns
References wblut.geom.WB_Point.copy().
WB_Vector wblut.geom.WB_Plane.getU ()
Gets the u.
Returns
the u
References wblut.geom.WB_Vector.copy().
WB_Vector wblut.geom.WB_Plane.getV ()
Gets the v.
Returns
the v
References wblut.geom.WB_Vector.copy().
WB_Vector wblut.geom.WB_Plane.getW ()
Gets the w.
Returns
the w
References wblut.geom.WB_Plane.getNormal().
WB_Point wblut.geom.WB_Plane.localPoint (final WB_Coord p)
Local point.
Parameters
p
Returns
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Point wblut.geom.WB_Plane.localPoint2D (final WB_Coord p)
Local point.
Parameters
p
Returns
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Point wblut.geom.WB_Plane.mirrorPoint (final WB_Coord p)
Mirror point.
Parameters
p
Returns
References wblut.geom.WB_Plane.extractPoint2D(), wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.math.WB_Epsilon.isZero(), and wblut.geom.WB_Plane.localPoint().
void wblut.geom.WB_Plane.set (final WB_Coord o, final WB_Coord n) protected
Parameters
o
n
References wblut.geom.WB_Plane.setAxes().
void wblut.geom.WB_Plane.setAxes () private
Sets the axes.
References wblut.geom.WB_Vector.cross(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
String wblut.geom.WB_Plane.toString ()
References wblut.geom.WB_Plane.d().
static final WB_Plane wblut.geom.WB_Plane.XY () static
Returns
References wblut.geom.WB_Plane.WB_Plane().
static final WB_Plane wblut.geom.WB_Plane.XZ () static
Returns
References wblut.geom.WB_Plane.WB_Plane().
static final WB_Plane wblut.geom.WB_Plane.YZ () static
Returns
References wblut.geom.WB_Plane.WB_Plane().
Member Data Documentation
WB_Vector wblut.geom.WB_Plane.n private
Plane normal.
WB_Point wblut.geom.WB_Plane.origin private
Origin.
WB_Vector wblut.geom.WB_Plane.u private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Plane.java