HE_Mesh: wblut.hemesh.HEC_FromOBJFile Class Reference
wblut.hemesh.HEC_FromOBJFile Class Reference
Public Member Functions
HEC_FromOBJFile ()
HEC_FromOBJFile (final String path)
HEC_FromOBJFile setPath (final String path)
HEC_FromOBJFile setScale (final double f)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Member Functions
InputStream createInputStream (final File file)
String[] loadStrings (final InputStream input)
String[] loadStrings (final BufferedReader reader)
Private Attributes
String path
double scale
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Constructor & Destructor Documentation
wblut.hemesh.HEC_FromOBJFile.HEC_FromOBJFile ()
wblut.hemesh.HEC_FromOBJFile.HEC_FromOBJFile (final String path)
Parameters
path
References wblut.hemesh.HEC_FromOBJFile.path.
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_FromOBJFile.createBase () protected
References wblut.hemesh.HEC_FromOBJFile.createInputStream(), wblut.hemesh.HEC_FromOBJFile.loadStrings(), wblut.hemesh.HEC_FromFacelist.setDuplicate(), wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HEC_FromFacelist.setFacesUVW(), wblut.hemesh.HEC_FromFacelist.setFaceVertexUVW(), and wblut.hemesh.HEC_FromFacelist.setVertices().
InputStream wblut.hemesh.HEC_FromOBJFile.createInputStream (final File file) private
Parameters
file
Returns
String [] wblut.hemesh.HEC_FromOBJFile.loadStrings (final InputStream input) private
Parameters
input
Returns
String [] wblut.hemesh.HEC_FromOBJFile.loadStrings (final BufferedReader reader) private
Parameters
reader
Returns
HEC_FromOBJFile wblut.hemesh.HEC_FromOBJFile.setPath (final String path)
Parameters
path
Returns
References wblut.hemesh.HEC_FromOBJFile.path.
HEC_FromOBJFile wblut.hemesh.HEC_FromOBJFile.setScale (final double f)
Parameters
f
Returns
Member Data Documentation
String wblut.hemesh.HEC_FromOBJFile.path private
double wblut.hemesh.HEC_FromOBJFile.scale private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_FromOBJFile.java