HE_Mesh: wblut.geom.WB_RandomInSphere Class Reference
wblut.geom.WB_RandomInSphere Class Reference
Public Member Functions
WB_RandomInSphere ()
WB_RandomInSphere (final long seed)
WB_RandomInSphere setSeed (final long seed)
WB_RandomInSphere setRadius (final double r)
WB_Point nextPoint ()
WB_Vector nextVector ()
void reset ()
WB_RandomInSphere setOffset (final WB_Coord offset)
WB_RandomInSphere setOffset (final double x, final double y)
WB_RandomInSphere setOffset (final double x, final double y, final double z)
Public Member Functions inherited from wblut.geom.WB_RandomPoint
WB_RandomPoint setOffset (WB_Coord offset)
WB_RandomPoint setOffset (double x, double y)
WB_RandomPoint setOffset (double x, double y, double z)
Private Attributes
final WB_MTRandom randomGen
double radius
WB_Vector offset
Detailed Description
Random generator for vectors uniformly distributed inside a sphere with radius r.
Author
Frederik Vanhoutte, W:Blut
Constructor & Destructor Documentation
wblut.geom.WB_RandomInSphere.WB_RandomInSphere ()
wblut.geom.WB_RandomInSphere.WB_RandomInSphere (final long seed)
Parameters
seed
Member Function Documentation
WB_Point wblut.geom.WB_RandomInSphere.nextPoint ()
Get the next random point.
Returns
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.nextDouble().
WB_Vector wblut.geom.WB_RandomInSphere.nextVector ()
Get the next random vector.
Returns
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.nextDouble().
void wblut.geom.WB_RandomInSphere.reset ()
Reset the RNG.
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.reset().
WB_RandomInSphere wblut.geom.WB_RandomInSphere.setOffset (final WB_Coord offset)
WB_RandomInSphere wblut.geom.WB_RandomInSphere.setOffset (final double x, final double y)
References wblut.geom.WB_MutableCoordinate.set().
WB_RandomInSphere wblut.geom.WB_RandomInSphere.setOffset (final double x, final double y, final double z)
References wblut.geom.WB_MutableCoordinate.set().
WB_RandomInSphere wblut.geom.WB_RandomInSphere.setRadius (final double r)
Parameters
r
Returns
WB_RandomInSphere wblut.geom.WB_RandomInSphere.setSeed (final long seed)
Set the seed for the RNG.
Parameters
seed
Returns
this
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.setSeed().
Member Data Documentation
WB_Vector wblut.geom.WB_RandomInSphere.offset private
double wblut.geom.WB_RandomInSphere.radius private
final WB_MTRandom wblut.geom.WB_RandomInSphere.randomGen private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_RandomInSphere.java