HE_Mesh: wblut.geom.WB_GeometryOp2D Class Reference
wblut.geom.WB_GeometryOp2D Class Reference
Classes
class WB_CircleFit
Static Public Member Functions
static final WB_IntersectionResult getIntersection2D (final WB_Segment S1, final WB_Segment S2)
static final void getIntersection2DInto (final WB_Segment S1, final WB_Segment S2, final WB_IntersectionResult i)
static final WB_Segment[] splitSegment2D (final WB_Segment S, final WB_Line L)
static final WB_Polygon[] splitPolygon2D (final WB_Polygon poly, final WB_Line L)
static final ArrayList< WB_Point > getIntersection2D (final WB_Circle C0, final WB_Circle C1)
static final ArrayList< WB_Point > getIntersection2D (final WB_Line L, final WB_Circle C)
static final ArrayList< WB_Point > getIntersection2D (final WB_Ray R, final WB_Circle C)
static final boolean checkIntersection2DProper (final WB_Coord a, final WB_Coord b, final WB_Coord c, final WB_Coord d)
static final WB_Point getClosestPoint2D (final WB_Coord p, final WB_Segment S)
static final WB_Point getClosestPoint2D (final WB_Coord p, final WB_PolyLine PL)
static final WB_Point getClosestPoint2D (final WB_Segment S, final WB_Coord p)
static final WB_Point getClosestPointToSegment2D (final WB_Coord p, final WB_Coord a, final WB_Coord b)
static final WB_Point getClosestPoint2D (final WB_Coord p, final WB_Line L)
static final WB_Point getClosestPointToLine2D (final WB_Coord p, final WB_Coord a, final WB_Coord b)
static final WB_Point getClosestPoint2D (final WB_Coord p, final WB_Ray R)
static final WB_Point getClosestPointToRay2D (final WB_Coord p, final WB_Coord a, final WB_Coord b)
static final WB_IntersectionResult getClosestPoint2D (final WB_Segment S1, final WB_Segment S2)
static final WB_IntersectionResult getClosestPoint2D (final WB_Line L1, final WB_Line L2)
static final WB_IntersectionResult getClosestPoint2D (final WB_Line L, final WB_Segment S)
static final WB_IntersectionResult getClosestPoint2D (final WB_Segment S, final WB_Line L)
static final WB_Point getClosestPoint2D (final WB_Coord p, final WB_Triangle T)
static final WB_Point getClosestPointToTriangle2D (final WB_Coord p, final WB_Coord a, final WB_Coord b, final WB_Coord c)
static final WB_Point getClosestPointOnPeriphery2D (final WB_Coord p, final WB_Triangle T)
static final WB_Point getClosestPoint2D (final WB_Coord p, final WB_Polygon poly)
static final WB_Point getClosestPoint2D (final WB_Coord p, final ArrayList<?extends WB_Triangle > tris)
static final WB_Point getClosestPointOnPeriphery2D (final WB_Coord p, final WB_Polygon poly)
static final WB_Point getClosestPointOnPeriphery2D (final WB_Coord p, final WB_Polygon poly, final ArrayList< WB_Triangle > tris)
static final boolean between2D (final WB_Coord a, final WB_Coord b, final WB_Coord c)
static final boolean betweenStrict2D (final WB_Coord a, final WB_Coord b, final WB_Coord c)
static final double getParameterOfPointOnLine2D (final WB_Coord a, final WB_Coord b, final WB_Coord p)
static final double getParameterOfPointOnLine2D (final WB_Coord p, final WB_Line L)
static final boolean contains2D (final WB_Coord p, final WB_AABB2D AABB)
static final double getDistanceToLine2D (final WB_Coord p, final WB_Line L)
static final double getDistance2D (final WB_Coord p, final WB_Segment S)
static final double getDistance2D (final WB_Coord p, final WB_Line L)
static final double getDistance2D (final WB_Coord p, final WB_Ray R)
static final double getDistanceToLine2D (final WB_Coord p, final WB_Coord a, final WB_Coord b)
static final double getDistanceToPoint2D (final WB_Coord p, final WB_Coord q)
static final double getDistanceToRay2D (final WB_Coord p, final WB_Coord a, final WB_Coord b)
static final double getDistanceToSegment2D (final WB_Coord p, final WB_Coord a, final WB_Coord b)
static final double getSqDistance2D (final WB_Coord p, final WB_Segment S)
static final double getSqDistance2D (final WB_Coord p, final WB_PolyLine PL)
static final double getDistance2D (final WB_Coord p, final WB_PolyLine PL)
static final double getSqDistance2D (final WB_Coord p, final WB_Line L)
static final double getSqDistance2D (final WB_Coord p, final WB_Ray R)
static final double getSqDistanceToLine2D (final WB_Coord p, final WB_Coord a, final WB_Coord b)
static final double getSqDistanceToLine2D (final WB_Coord p, final WB_Line L)
static final double getSqDistanceToPoint2D (final WB_Coord p, final WB_Coord q)
static final double getSqDistanceToRay2D (final WB_Coord p, final WB_Coord a, final WB_Coord b)
static final double getSqDistanceToSegment2D (final WB_Coord p, final WB_Coord a, final WB_Coord b)
static final int[] getExtremePointsAlongDirection2D (final WB_Coord[] points, final WB_Coord dir)
static final int[] getExtremePointsAlongDirection2D (final Collection<?extends WB_Coord > points, final WB_Coord dir)
static final WB_Classification classifyPointToLine2D (final WB_Coord p, final WB_Line L)
static final WB_Classification classifyPointToCircle2D (final WB_Coord p, final WB_Circle C)
static final WB_Classification classifyCircleToCircle2D (final WB_Circle C1, final WB_Circle C2)
static final WB_Classification classifyCircleToLine2D (final WB_Circle C, final WB_Line L)
static final boolean sameSideOfLine2D (final WB_Coord p, final WB_Coord q, final WB_Line L)
static final WB_Classification classifySegmentToLine2D (final WB_Segment seg, final WB_Line L)
static final WB_Classification classifyPolygonToLine2D (final WB_Polygon P, final WB_Line L)
static final boolean contains2D (final WB_Coord p, final WB_Polygon poly)
static final boolean contains2D (final WB_Coord p, final ArrayList<?extends WB_Triangle > tris)
static final boolean contains2D (final WB_Coord p, final WB_Triangle tris)
static final double[] getIntervalIntersection2D (final double u0, final double u1, final double v0, final double v1)
static final WB_Circle getBoundingCircle2D (final WB_Coord[] points)
static final WB_Circle getBoundingCircle2D (final Collection<?extends WB_Coord > points)
static final WB_Line getLineTangentToCircleAtPoint2D (final WB_Circle C, final WB_Coord p)
static final ArrayList< WB_Line > getLinesTangentToCircleThroughPoint (final WB_Circle C, final WB_Coord p)
static final ArrayList< WB_Line > getLinesTangentTo2Circles (final WB_Circle C0, final WB_Circle C1)
static final WB_Line getPerpendicularLineThroughPoint2D (final WB_Line L, final WB_Coord p)
static final WB_Line getParallelLineThroughPoint2D (final WB_Line L, final WB_Coord p)
static final WB_Line getBisector2D (final WB_Coord p, final WB_Coord q)
static final WB_Line[] getParallelLines2D (final WB_Line L, final double d)
static final WB_Line[] getPerpendicularLinesTangentToCircle2D (final WB_Line L, final WB_Circle C)
static final WB_Sphere getBoundingSphere (final Collection<?extends WB_Coord > points)
static final double getArea2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
static final double getSimpleArea2D (final WB_Polygon poly)
static final boolean sameSide2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord A, final WB_Coord B)
static final boolean pointInTriangle2D (final WB_Coord p, final WB_Coord A, final WB_Coord B, final WB_Coord C)
static final boolean pointInTriangle2D (final WB_Coord p, final WB_Triangle T)
static final boolean pointInTriangleBary2D (final WB_Coord p, final WB_Coord A, final WB_Coord B, final WB_Coord C)
static final boolean pointInTriangleBary2D (final WB_Coord p, final WB_Triangle T)
static final double twiceSignedTriArea2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
static final double twiceSignedTriArea2D (final double x1, final double y1, final double x2, final double y2, final double x3, final double y3)
static final double getSignedArea2D (final List<?extends WB_Coord > coords, final int start, final int end)
static final double getSignedArea2D (final WB_Coord[] coords, final int start, final int end)
static final double getSignedArea2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
static final WB_Coord projectToCircle2D (final WB_Circle C, final WB_Coord v)
static final WB_Circle growCircleByPoint2D (final WB_Circle C, final WB_Coord p)
static final WB_Polygon trimConvexPolygon2D (WB_Polygon poly, final double d)
static final WB_Polygon trimConvexPolygon2D (WB_Polygon poly, final double[] d)
static final boolean isLeftStrict2D (final WB_Coord a, final WB_Coord b, final WB_Coord p)
static final boolean isLeft2D (final WB_Coord a, final WB_Coord b, final WB_Coord p)
static final boolean isRightStrict2D (final WB_Coord a, final WB_Coord b, final WB_Coord p)
static final boolean isRight2D (final WB_Coord a, final WB_Coord b, final WB_Coord p)
static final boolean isReflex2D (final WB_Coord p0, final WB_Coord p, final WB_Coord p1)
static final WB_Coord getSegmentIntersection2D (final WB_Coord ap1, final WB_Coord ap2, final WB_Coord bp1, final WB_Coord bp2)
static final boolean getLineIntersectionInto2D (final WB_Coord a1, final WB_Coord a2, final WB_Coord b1, final WB_Coord b2, final WB_MutableCoord p)
static final WB_Circle fitCircleToPoints2D (final Collection<?extends WB_Coord > points)
static final WB_CircleFit fitCircleToPoints2D (final Collection<?extends WB_Coord > points, final int maxIterations, final double convergence)
static final WB_Circle fitCircleToPoints2D (final WB_Coord[] points)
static final WB_CircleFit fitCircleToPoints2D (final WB_Coord[] points, final int maxIterations, final double convergence)
static final WB_Circle getBoundingCircleInCenter2D (final Collection<?extends WB_Coord > points)
static final WB_Circle getBoundingCircleInCenter2D (final WB_Coord[] points)
static final WB_Circle mergeCircles2D (final WB_Circle C1, final WB_Circle C2)
static final boolean isTangent2D (final WB_Circle C1, final WB_Circle C2)
static final double cross2D (final WB_Coord v1, final WB_Coord v2)
static final double dot2D (final double ux, final double uy, final double vx, final double vy)
static final double dot2D (final WB_Coord u, final WB_Coord v)
static final double getAngleBetween2D (final double ux, final double uy, final double vx, final double vy)
static final double getAngleBetween2D (final double cx, final double cy, final double px, final double py, final double qx, final double qy)
static final double getAngleBetween2D (final WB_Coord u, final WB_Coord v)
static final double getAngleBetween2D (final WB_Coord c, final WB_Coord p, final WB_Coord q)
static final double getAngleBetweenNorm2D (final double ux, final double uy, final double vx, final double vy)
static final double getAngleBetweenNorm2D (final WB_Coord u, final WB_Coord v)
static final double getCosAngleBetween2D (final double ux, final double uy, final double vx, final double vy)
static final double getCosAngleBetween2D (final double cx, final double cy, final double px, final double py, final double qx, final double qy)
static final double getCosAngleBetweenNorm2D (final double ux, final double uy, final double vx, final double vy)
static final double getDistance2D (final double px, final double py, final double qx, final double qy)
static final double getDistance2D (final WB_Coord p, final WB_Coord q)
static final double getLength2D (final double ux, final double uy)
static final double getLength2D (final WB_Coord p)
static final double getSignedAngleBetween2D (final double ux, final double uy, final double vx, final double vy, final double nx, final double ny)
static final double getSignedAngleBetween2D (final double cx, final double cy, final double px, final double py, final double qx, final double qy, final double nx, final double ny)
static final double getSignedAngleBetweenNorm2D (final double ux, final double uy, final double vx, final double vy, final double nx, final double ny)
static final double getSqDistance2D (final double px, final double py, final double qx, final double qy)
static final double getSqDistance2D (final WB_Coord p, final WB_Coord q)
static final double getSqLength2D (final double ux, final double uy)
static final double getSqLength2D (final WB_Coord p)
static final double[] interpolate2D (final double px, final double py, final double qx, final double qy, final double t)
static final double[] interpolate2D (final WB_Coord p, final WB_Coord q, final double t)
static final double[] interpolateEase2D (final double px, final double py, final double qx, final double qy, final double t, final WB_Ease ease, final WB_Ease.EaseType type)
static final double[] interpolateEase2D (final WB_Coord p, final WB_Coord q, final double t, final WB_Ease ease, final WB_Ease.EaseType type)
static final boolean isCoincident2D (final WB_Coord a, final WB_Coord b)
static final boolean isCollinear2D (final WB_Coord o, final WB_Coord p, final WB_Coord q)
static final boolean isOrthogonal2D (final WB_Coord v0, final WB_Coord v1)
static final boolean isOrthogonal2D (final WB_Coord v0, final WB_Coord v1, final double epsilon)
static final boolean isOrthogonalNorm2D (final WB_Coord v0, final WB_Coord v1)
static final boolean isOrthogonalNorm2D (final WB_Coord v0, final WB_Coord v1, final double epsilon)
static final boolean isParallel2D (final WB_Coord v0, final WB_Coord v1)
static final boolean isParallel2D (final WB_Coord v0, final WB_Coord v1, final double epsilon)
static final boolean isParallelNorm2D (final WB_Coord v0, final WB_Coord v1)
static final boolean isParallelNorm2D (final WB_Coord v0, final WB_Coord v1, final double epsilon)
static final boolean isZero2D (final double ux, final double uy)
static double getDistance2D (final WB_Coord p, final WB_AABB2D AABB)
static double getSqDistance2D (final WB_Coord p, final WB_AABB2D AABB)
Static Public Member Functions inherited from wblut.geom.WB_GeometryOpGLU
static boolean GLUvertEq (final WB_Coord u, final WB_Coord v)
static boolean GLUvertLeq (final WB_Coord u, final WB_Coord v)
static boolean GLUtransLeq (final WB_Coord u, final WB_Coord v)
static boolean GLUedgeGoesLeft (final WB_Segment e)
static boolean GLUedgeGoesRight (final WB_Segment e)
static double GLUedgeEval (final WB_Coord u, final WB_Coord v, final WB_Coord w)
static double GLUedgeSign (final WB_Coord u, final WB_Coord v, final WB_Coord w)
static double GLUtransEval (final WB_Coord u, final WB_Coord v, final WB_Coord w)
static double GLUtransSign (final WB_Coord u, final WB_Coord v, final WB_Coord w)
static boolean GLUvertCCW (final WB_Coord u, final WB_Coord v, final WB_Coord w)
static double GLUrealInterpolate (double a, final double x, double b, final double y)
static double GLUinterpolate (final double a, final double x, final double b, final double y)
static WB_Coord GLUedgeIntersect (WB_Coord o1, WB_Coord d1, WB_Coord o2, WB_Coord d2)
static int GLUlongAxis (final WB_Coord v)
static int GLUlongAxis (final double[] v)
static WB_Coord GLUcomputeNormal (final List<?extends WB_Coord > vertices)
Static Private Member Functions
static final WB_IntersectionResult NOINTERSECTION ()
static final WB_Point[] getDirectionsOfLinesTangentToCircle2D (final WB_Coord w, final double a)
Static Private Attributes
static final WB_GeometryFactory gf = new WB_GeometryFactory()
Member Function Documentation
static final boolean wblut.geom.WB_GeometryOp2D.between2D (final WB_Coord a, final WB_Coord b, final WB_Coord c) static
Parameters
a
b
c
Returns
References wblut.geom.WB_GeometryOp2D.getParameterOfPointOnLine2D(), wblut.geom.WB_GeometryOp2D.getSqDistanceToLine2D(), wblut.geom.WB_GeometryOp2D.isCoincident2D(), and wblut.math.WB_Epsilon.SQEPSILON.
static final boolean wblut.geom.WB_GeometryOp2D.betweenStrict2D (final WB_Coord a, final WB_Coord b, final WB_Coord c) static
Parameters
a
b
c
Returns
References wblut.geom.WB_GeometryOp2D.getParameterOfPointOnLine2D(), wblut.geom.WB_GeometryOp2D.getSqDistanceToLine2D(), wblut.geom.WB_GeometryOp2D.isCoincident2D(), and wblut.math.WB_Epsilon.SQEPSILON.
static final boolean wblut.geom.WB_GeometryOp2D.checkIntersection2DProper (final WB_Coord a, final WB_Coord b, final WB_Coord c, final WB_Coord d) static
Parameters
a
b
c
d
Returns
References wblut.geom.WB_Predicates.orient2D().
static final WB_Classification wblut.geom.WB_GeometryOp2D.classifyCircleToCircle2D (final WB_Circle C1, final WB_Circle C2) static
Parameters
C1
C2
Returns
References wblut.geom.WB_Classification.CONTAINING, wblut.geom.WB_Classification.CROSSING, wblut.geom.WB_Circle.equals(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_GeometryOp2D.getDistanceToPoint2D(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Classification.INSIDE, wblut.geom.WB_Classification.ON, and wblut.geom.WB_Classification.OUTSIDE.
static final WB_Classification wblut.geom.WB_GeometryOp2D.classifyCircleToLine2D (final WB_Circle C, final WB_Line L) static
Parameters
C
L
Returns
References wblut.geom.WB_Classification.CROSSING, wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_GeometryOp2D.getDistanceToLine2D(), wblut.geom.WB_Circle.getRadius(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Classification.OUTSIDE, and wblut.geom.WB_Classification.TANGENT.
static final WB_Classification wblut.geom.WB_GeometryOp2D.classifyPointToCircle2D (final WB_Coord p, final WB_Circle C) static
Parameters
p
C
Returns
References wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_GeometryOp2D.getDistanceToPoint2D(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Classification.INSIDE, wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Classification.ON, and wblut.geom.WB_Classification.OUTSIDE.
static final WB_Classification wblut.geom.WB_GeometryOp2D.classifyPointToLine2D (final WB_Coord p, final WB_Line L) static
Parameters
p
L
Returns
References wblut.geom.WB_Classification.BACK, wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Classification.FRONT, wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Classification.ON, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final WB_Classification wblut.geom.WB_GeometryOp2D.classifyPolygonToLine2D (final WB_Polygon P, final WB_Line L) static
Parameters
P
L
Returns
References wblut.geom.WB_Classification.BACK, wblut.geom.WB_GeometryOp2D.classifyPointToLine2D(), wblut.geom.WB_Classification.CROSSING, wblut.geom.WB_Classification.FRONT, wblut.geom.WB_Polygon.getNumberOfPoints(), and wblut.geom.WB_Polygon.getPoint().
static final WB_Classification wblut.geom.WB_GeometryOp2D.classifySegmentToLine2D (final WB_Segment seg, final WB_Line L) static
Parameters
seg
L
Returns
References wblut.geom.WB_Classification.BACK, wblut.geom.WB_GeometryOp2D.classifyPointToLine2D(), wblut.geom.WB_Classification.CROSSING, wblut.geom.WB_Classification.FRONT, wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Line.getOrigin(), and wblut.geom.WB_Classification.ON.
static final boolean wblut.geom.WB_GeometryOp2D.contains2D (final WB_Coord p, final WB_AABB2D AABB) static
Parameters
p
AABB
Returns
References wblut.geom.WB_AABB2D.getMaxX(), wblut.geom.WB_AABB2D.getMaxY(), wblut.geom.WB_AABB2D.getMinX(), wblut.geom.WB_AABB2D.getMinY(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final boolean wblut.geom.WB_GeometryOp2D.contains2D (final WB_Coord p, final WB_Polygon poly) static
Parameters
p
poly
Returns
References wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), wblut.geom.WB_Vector.getSqDistance2D(), and wblut.math.WB_Epsilon.isZeroSq().
static final boolean wblut.geom.WB_GeometryOp2D.contains2D (final WB_Coord p, final ArrayList<?extends WB_Triangle > tris) static
Parameters
p
tris
Returns
References wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), wblut.geom.WB_Vector.getSqDistance2D(), and wblut.math.WB_Epsilon.isZeroSq().
static final boolean wblut.geom.WB_GeometryOp2D.contains2D (final WB_Coord p, final WB_Triangle tris) static
References wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), wblut.geom.WB_Vector.getSqDistance2D(), and wblut.math.WB_Epsilon.isZeroSq().
static final double wblut.geom.WB_GeometryOp2D.cross2D (final WB_Coord v1, final WB_Coord v2) static
Parameters
v1
v2
Returns
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final double wblut.geom.WB_GeometryOp2D.dot2D (final double ux, final double uy, final double vx, final double vy) static
Parameters
ux
uy
vx
vy
Returns
static final double wblut.geom.WB_GeometryOp2D.dot2D (final WB_Coord u, final WB_Coord v) static
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final WB_Circle wblut.geom.WB_GeometryOp2D.fitCircleToPoints2D (final Collection<?extends WB_Coord > points) static
References wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Circle.set().
static final WB_CircleFit wblut.geom.WB_GeometryOp2D.fitCircleToPoints2D (final Collection<?extends WB_Coord > points, final int maxIterations, final double convergence) static
References wblut.geom.WB_Point.add(), wblut.geom.WB_Vector.addMulSelf(), wblut.geom.WB_GeometryOp2D.fitCircleToPoints2D(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Vector.getLength2D(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Circle.setCenter(), wblut.geom.WB_Circle.setRadius(), and wblut.geom.WB_Vector.sub().
static final WB_Circle wblut.geom.WB_GeometryOp2D.fitCircleToPoints2D (final WB_Coord[] points) static
References wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Circle.set().
static final WB_CircleFit wblut.geom.WB_GeometryOp2D.fitCircleToPoints2D (final WB_Coord[] points, final int maxIterations, final double convergence) static
References wblut.geom.WB_Point.add(), wblut.geom.WB_Vector.addMulSelf(), wblut.geom.WB_GeometryOp2D.fitCircleToPoints2D(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Vector.getLength2D(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Circle.setCenter(), wblut.geom.WB_Circle.setRadius(), and wblut.geom.WB_Vector.sub().
static final double wblut.geom.WB_GeometryOp2D.getAngleBetween2D (final double ux, final double uy, final double vx, final double vy) static
Parameters
ux
uy
vx
vy
Returns
References wblut.geom.WB_Vector.dot2D(), and wblut.geom.WB_Vector.normalizeSelf().
static final double wblut.geom.WB_GeometryOp2D.getAngleBetween2D (final double cx, final double cy, final double px, final double py, final double qx, final double qy) static
Parameters
cx
cy
px
py
qx
qy
Returns
References wblut.geom.WB_Vector.dot2D(), and wblut.geom.WB_Vector.normalizeSelf().
static final double wblut.geom.WB_GeometryOp2D.getAngleBetween2D (final WB_Coord u, final WB_Coord v) static
References wblut.geom.WB_Vector.dot2D(), and wblut.geom.WB_Vector.normalizeSelf().
static final double wblut.geom.WB_GeometryOp2D.getAngleBetween2D (final WB_Coord c, final WB_Coord p, final WB_Coord q) static
References wblut.geom.WB_Vector.dot2D(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Vector.subToVector2D().
static final double wblut.geom.WB_GeometryOp2D.getAngleBetweenNorm2D (final double ux, final double uy, final double vx, final double vy) static
Parameters
ux
uy
vx
vy
Returns
References wblut.geom.WB_Vector.dot2D().
static final double wblut.geom.WB_GeometryOp2D.getAngleBetweenNorm2D (final WB_Coord u, final WB_Coord v) static
References wblut.geom.WB_Vector.dot2D().
static final double wblut.geom.WB_GeometryOp2D.getArea2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3) static
Gets the area.
Parameters
p1
p2
p3
Returns
the area
References wblut.math.WB_Math.fastAbs(), and wblut.geom.WB_GeometryOp2D.getSignedArea2D().
static final WB_Line wblut.geom.WB_GeometryOp2D.getBisector2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final WB_Circle wblut.geom.WB_GeometryOp2D.getBoundingCircle2D (final WB_Coord[] points) static
Parameters
points
Returns
References wblut.geom.WB_GeometryFactory3D.createMidpoint(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Vector.getSqDistance2D(), wblut.geom.WB_Point.mul(), wblut.geom.WB_Point.mulAddMulSelf(), and wblut.geom.WB_Point.mulSelf().
static final WB_Circle wblut.geom.WB_GeometryOp2D.getBoundingCircle2D (final Collection<?extends WB_Coord > points) static
Parameters
points
Returns
References wblut.geom.WB_GeometryFactory3D.createMidpoint(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Vector.getSqDistance2D(), wblut.geom.WB_Point.mul(), wblut.geom.WB_Point.mulAddMulSelf(), and wblut.geom.WB_Point.mulSelf().
static final WB_Circle wblut.geom.WB_GeometryOp2D.getBoundingCircleInCenter2D (final Collection<?extends WB_Coord > points) static
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.divSelf(), wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Vector.sub().
static final WB_Circle wblut.geom.WB_GeometryOp2D.getBoundingCircleInCenter2D (final WB_Coord[] points) static
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.divSelf(), wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Vector.sub().
static final WB_Sphere wblut.geom.WB_GeometryOp2D.getBoundingSphere (final Collection<?extends WB_Coord > points) static
Parameters
points
Returns
References wblut.geom.WB_GeometryFactory3D.createMidpoint(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Vector.getSqDistance3D(), wblut.geom.WB_Point.mul(), wblut.geom.WB_Point.mulAddMulSelf(), and wblut.geom.WB_Point.mulSelf().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPoint2D (final WB_Coord p, final WB_Segment S) static
Parameters
p
S
Returns
References wblut.geom.WB_Vector.dot(), wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Segment.getLength(), wblut.geom.WB_Line.getOrigin(), and wblut.geom.WB_Segment.getParametricPoint().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPoint2D (final WB_Coord p, final WB_PolyLine PL) static
References wblut.geom.WB_Vector.dot(), wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Segment.getLength(), wblut.geom.WB_PolyLine.getNumberSegments(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Segment.getParametricPoint(), wblut.geom.WB_PolyLine.getSegment(), and wblut.geom.WB_GeometryOp2D.getSqDistance2D().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPoint2D (final WB_Segment S, final WB_Coord p) static
Parameters
S
p
Returns
References wblut.geom.WB_GeometryOp2D.getClosestPoint2D().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPoint2D (final WB_Coord p, final WB_Line L) static
Parameters
p
L
Returns
References wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPoint2D (final WB_Coord p, final WB_Ray R) static
Parameters
p
R
Returns
References wblut.geom.WB_Vector.dot(), wblut.geom.WB_Ray.getDirection(), wblut.geom.WB_Ray.getOrigin(), and wblut.geom.WB_Ray.getPoint().
static final WB_IntersectionResult wblut.geom.WB_GeometryOp2D.getClosestPoint2D (final WB_Segment S1, final WB_Segment S2) static
Parameters
S1
S2
Returns
References wblut.math.WB_Math.clamp(), wblut.geom.WB_IntersectionResult.dimension, wblut.geom.WB_Vector.dot(), wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Segment.getParametricPoint(), wblut.geom.WB_GeometryOp2D.getSqDistance2D(), wblut.geom.WB_Vector.getSqLength(), wblut.geom.WB_IntersectionResult.intersection, wblut.math.WB_Epsilon.isZero(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_IntersectionResult.object, wblut.geom.WB_IntersectionResult.sqDist, wblut.geom.WB_Point.sub(), wblut.geom.WB_IntersectionResult.t1, and wblut.geom.WB_IntersectionResult.t2.
static final WB_IntersectionResult wblut.geom.WB_GeometryOp2D.getClosestPoint2D (final WB_Line L1, final WB_Line L2) static
Parameters
L1
L2
Returns
References wblut.geom.WB_IntersectionResult.dimension, wblut.geom.WB_Vector.dot(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Line.getPoint(), wblut.geom.WB_GeometryOp2D.getSqDistance2D(), wblut.geom.WB_IntersectionResult.intersection, wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_IntersectionResult.object, wblut.geom.WB_IntersectionResult.sqDist, wblut.geom.WB_Point.sub(), wblut.geom.WB_IntersectionResult.t1, and wblut.geom.WB_IntersectionResult.t2.
static final WB_IntersectionResult wblut.geom.WB_GeometryOp2D.getClosestPoint2D (final WB_Line L, final WB_Segment S) static
Parameters
L
S
Returns
References wblut.geom.WB_IntersectionResult.dimension, wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Segment.getLength(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_IntersectionResult.intersection, wblut.geom.WB_IntersectionResult.object, wblut.geom.WB_IntersectionResult.sqDist, and wblut.geom.WB_IntersectionResult.t2.
static final WB_IntersectionResult wblut.geom.WB_GeometryOp2D.getClosestPoint2D (final WB_Segment S, final WB_Line L) static
Parameters
S
L
Returns
References wblut.geom.WB_GeometryOp2D.getClosestPoint2D().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPoint2D (final WB_Coord p, final WB_Triangle T) static
Parameters
p
T
Returns
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_Vector.dot(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Point.sub(), and wblut.geom.WB_Vector.subToVector3D().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPoint2D (final WB_Coord p, final WB_Polygon poly) static
Parameters
p
poly
Returns
References wblut.geom.WB_GeometryOp2D.getClosestPointToTriangle2D(), wblut.geom.WB_GeometryOp2D.getDistance2D(), wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_Polygon.getTriangles().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPoint2D (final WB_Coord p, final ArrayList<?extends WB_Triangle > tris) static
Parameters
p
tris
Returns
References wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), and wblut.geom.WB_GeometryOp2D.getDistance2D().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPointOnPeriphery2D (final WB_Coord p, final WB_Triangle T) static
Parameters
p
T
Returns
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Vector.dot(), wblut.geom.WB_GeometryOp2D.getClosestPointToSegment2D(), wblut.geom.WB_GeometryOp2D.getSqDistance2D(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Point.sub(), and wblut.geom.WB_Vector.subToVector3D().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPointOnPeriphery2D (final WB_Coord p, final WB_Polygon poly) static
Parameters
p
poly
Returns
References wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), wblut.geom.WB_GeometryOp2D.getClosestPointToTriangle2D(), wblut.geom.WB_Polygon.getNumberOfShellPoints(), wblut.geom.WB_Polygon.getPoint(), wblut.geom.WB_GeometryOp2D.getSqDistance2D(), wblut.geom.WB_Polygon.getTriangles(), and wblut.math.WB_Epsilon.isZeroSq().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPointOnPeriphery2D (final WB_Coord p, final WB_Polygon poly, final ArrayList< WB_Triangle > tris) static
Parameters
p
poly
tris
Returns
References wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), wblut.geom.WB_Polygon.getNumberOfShellPoints(), wblut.geom.WB_Polygon.getPoint(), wblut.geom.WB_GeometryOp2D.getSqDistance2D(), and wblut.math.WB_Epsilon.isZeroSq().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPointToLine2D (final WB_Coord p, final WB_Coord a, final WB_Coord b) static
Parameters
p
a
b
Returns
References wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), and wblut.geom.WB_Line.setFromPoints().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPointToRay2D (final WB_Coord p, final WB_Coord a, final WB_Coord b) static
Parameters
p
a
b
Returns
References wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), and wblut.geom.WB_Ray.setFromPoints().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPointToSegment2D (final WB_Coord p, final WB_Coord a, final WB_Coord b) static
Parameters
p
a
b
Returns
References wblut.geom.WB_Vector.dot(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
static final WB_Point wblut.geom.WB_GeometryOp2D.getClosestPointToTriangle2D (final WB_Coord p, final WB_Coord a, final WB_Coord b, final WB_Coord c) static
Parameters
p
a
b
c
Returns
References wblut.geom.WB_Point.addMulSelf(), and wblut.geom.WB_Vector.dot().
static final double wblut.geom.WB_GeometryOp2D.getCosAngleBetween2D (final double ux, final double uy, final double vx, final double vy) static
Parameters
ux
uy
vx
vy
Returns
References wblut.geom.WB_Vector.dot2D(), and wblut.geom.WB_Vector.normalizeSelf().
static final double wblut.geom.WB_GeometryOp2D.getCosAngleBetween2D (final double cx, final double cy, final double px, final double py, final double qx, final double qy) static
Parameters
cx
cy
px
py
qx
qy
Returns
References wblut.geom.WB_Vector.dot2D(), and wblut.geom.WB_Vector.normalizeSelf().
static final double wblut.geom.WB_GeometryOp2D.getCosAngleBetweenNorm2D (final double ux, final double uy, final double vx, final double vy) static
Parameters
ux
uy
vx
vy
Returns
References wblut.geom.WB_Vector.dot2D().
static final WB_Point [] wblut.geom.WB_GeometryOp2D.getDirectionsOfLinesTangentToCircle2D (final WB_Coord w, final double a) static private
References wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final double wblut.geom.WB_GeometryOp2D.getDistance2D (final WB_Coord p, final WB_Segment S) static
Parameters
p
S
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistance2D().
static final double wblut.geom.WB_GeometryOp2D.getDistance2D (final WB_Coord p, final WB_Line L) static
Parameters
p
L
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistance2D().
static final double wblut.geom.WB_GeometryOp2D.getDistance2D (final WB_Coord p, final WB_Ray R) static
Parameters
p
R
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistance2D().
static final double wblut.geom.WB_GeometryOp2D.getDistance2D (final WB_Coord p, final WB_PolyLine PL) static
References wblut.geom.WB_GeometryOp2D.getSqDistance2D().
static final double wblut.geom.WB_GeometryOp2D.getDistance2D (final double px, final double py, final double qx, final double qy) static
Parameters
px
py
qx
qy
Returns
static final double wblut.geom.WB_GeometryOp2D.getDistance2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistance2D().
static double wblut.geom.WB_GeometryOp2D.getDistance2D (final WB_Coord p, final WB_AABB2D AABB) static
Parameters
p
AABB
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistance2D().
static final double wblut.geom.WB_GeometryOp2D.getDistanceToLine2D (final WB_Coord p, final WB_Line L) static
Parameters
p
L
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistanceToLine2D().
static final double wblut.geom.WB_GeometryOp2D.getDistanceToLine2D (final WB_Coord p, final WB_Coord a, final WB_Coord b) static
Parameters
p
a
b
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistanceToLine2D().
static final double wblut.geom.WB_GeometryOp2D.getDistanceToPoint2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistanceToPoint2D().
static final double wblut.geom.WB_GeometryOp2D.getDistanceToRay2D (final WB_Coord p, final WB_Coord a, final WB_Coord b) static
Parameters
p
a
b
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistanceToRay2D().
static final double wblut.geom.WB_GeometryOp2D.getDistanceToSegment2D (final WB_Coord p, final WB_Coord a, final WB_Coord b) static
Parameters
p
a
b
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistanceToSegment2D().
static final int [] wblut.geom.WB_GeometryOp2D.getExtremePointsAlongDirection2D (final WB_Coord[] points, final WB_Coord dir) static
Parameters
points
dir
Returns
References wblut.geom.WB_Vector.dot2D().
static final int [] wblut.geom.WB_GeometryOp2D.getExtremePointsAlongDirection2D (final Collection<?extends WB_Coord > points, final WB_Coord dir) static
Parameters
points
dir
Returns
References wblut.geom.WB_Vector.dot2D().
static final WB_IntersectionResult wblut.geom.WB_GeometryOp2D.getIntersection2D (final WB_Segment S1, final WB_Segment S2) static
Parameters
S1
S2
Returns
References wblut.geom.WB_IntersectionResult.dimension, wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Segment.getParametricPoint(), wblut.geom.WB_IntersectionResult.intersection, wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_GeometryOp2D.NOINTERSECTION(), wblut.geom.WB_IntersectionResult.object, wblut.geom.WB_IntersectionResult.sqDist, wblut.geom.WB_IntersectionResult.t1, wblut.geom.WB_IntersectionResult.t2, and wblut.geom.WB_GeometryOp2D.twiceSignedTriArea2D().
static final ArrayList<WB_Point> wblut.geom.WB_GeometryOp2D.getIntersection2D (final WB_Circle C0, final WB_Circle C1) static
Parameters
C0
C1
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_GeometryOp2D.getSqDistance2D(), wblut.geom.WB_Vector.getSqLength2D(), wblut.math.WB_Epsilon.isEqualAbs(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Point.mul(), wblut.geom.WB_Point.sub(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
static final ArrayList<WB_Point> wblut.geom.WB_GeometryOp2D.getIntersection2D (final WB_Line L, final WB_Circle C) static
Parameters
L
C
Returns
References wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Line.getPoint(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Vector.getSqLength2D(), wblut.geom.WB_GeometryOp2D.getSqLength2D(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final ArrayList<WB_Point> wblut.geom.WB_GeometryOp2D.getIntersection2D (final WB_Ray R, final WB_Circle C) static
References wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Ray.getDirection(), wblut.geom.WB_Ray.getOrigin(), wblut.geom.WB_Ray.getPoint(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Vector.getSqLength2D(), wblut.geom.WB_GeometryOp2D.getSqLength2D(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final void wblut.geom.WB_GeometryOp2D.getIntersection2DInto (final WB_Segment S1, final WB_Segment S2, final WB_IntersectionResult i) static
Parameters
S1
S2
i
References wblut.geom.WB_IntersectionResult.dimension, wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Segment.getParametricPoint(), wblut.geom.WB_IntersectionResult.intersection, wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_IntersectionResult.object, wblut.geom.WB_IntersectionResult.sqDist, wblut.geom.WB_IntersectionResult.t1, wblut.geom.WB_IntersectionResult.t2, and wblut.geom.WB_GeometryOp2D.twiceSignedTriArea2D().
static final double [] wblut.geom.WB_GeometryOp2D.getIntervalIntersection2D (final double u0, final double u1, final double v0, final double v1) static
Check the intersection of two intervals [u0,u1] and [v0,v1]. The result is an array of double, the first value gives the number of values needed to define the intersection interval. If the intervals do not intersect,the array contains no additional values. If the intervals intersect in a single value, the array contains this value. Otherwise the endvalues of the intersection interval are given The function sorts the passed intervals if necessary.
For example
[0,2] and [3,4]: result [0] [0,2] and [2,4]: result [1,2] [0,2] and [1,4]: result [2,1,2]
Parameters
u0
u1
v0
v1
Returns
static final double wblut.geom.WB_GeometryOp2D.getLength2D (final double ux, final double uy) static
Parameters
ux
uy
Returns
static final double wblut.geom.WB_GeometryOp2D.getLength2D (final WB_Coord p) static
Parameters
p
Returns
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final boolean wblut.geom.WB_GeometryOp2D.getLineIntersectionInto2D (final WB_Coord a1, final WB_Coord a2, final WB_Coord b1, final WB_Coord b2, final WB_MutableCoord p) static
Parameters
a1
a2
b1
b2
p
Returns
References wblut.geom.WB_GeometryFactory2D.createVectorFromTo2D(), wblut.geom.WB_GeometryOp2D.cross2D(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final ArrayList<WB_Line> wblut.geom.WB_GeometryOp2D.getLinesTangentTo2Circles (final WB_Circle C0, final WB_Circle C1) static
Parameters
C0
C1
Returns
References wblut.geom.WB_Point.add(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_GeometryOp2D.getDirectionsOfLinesTangentToCircle2D(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZero(), wblut.math.WB_Epsilon.SQEPSILON, wblut.geom.WB_Point.sub(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
static final ArrayList<WB_Line> wblut.geom.WB_GeometryOp2D.getLinesTangentToCircleThroughPoint (final WB_Circle C, final WB_Coord p) static
Parameters
C
p
Returns
References wblut.geom.WB_Vector.add(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_GeometryOp2D.getDistance2D(), wblut.geom.WB_Circle.getRadius(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static final WB_Line wblut.geom.WB_GeometryOp2D.getLineTangentToCircleAtPoint2D (final WB_Circle C, final WB_Coord p) static
Parameters
C
p
Returns
References wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static final WB_Line [] wblut.geom.WB_GeometryOp2D.getParallelLines2D (final WB_Line L, final double d) static
Parameters
L
d
Returns
References wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final WB_Line wblut.geom.WB_GeometryOp2D.getParallelLineThroughPoint2D (final WB_Line L, final WB_Coord p) static
Parameters
L
p
Returns
References wblut.geom.WB_Line.getDirection().
static final double wblut.geom.WB_GeometryOp2D.getParameterOfPointOnLine2D (final WB_Coord a, final WB_Coord b, final WB_Coord p) static
Parameters
a
b
p
Returns
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final double wblut.geom.WB_GeometryOp2D.getParameterOfPointOnLine2D (final WB_Coord p, final WB_Line L) static
Parameters
p
L
Returns
References wblut.geom.WB_Line.direction, wblut.geom.WB_Vector.dot2D(), wblut.geom.WB_Line.origin, wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
static final WB_Line [] wblut.geom.WB_GeometryOp2D.getPerpendicularLinesTangentToCircle2D (final WB_Line L, final WB_Circle C) static
Parameters
L
C
Returns
References wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final WB_Line wblut.geom.WB_GeometryOp2D.getPerpendicularLineThroughPoint2D (final WB_Line L, final WB_Coord p) static
Parameters
L
p
Returns
References wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final WB_Coord wblut.geom.WB_GeometryOp2D.getSegmentIntersection2D (final WB_Coord ap1, final WB_Coord ap2, final WB_Coord bp1, final WB_Coord bp2) static
Parameters
ap1
ap2
bp1
bp2
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryOp2D.cross2D(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Point.mul(), and wblut.geom.WB_Point.sub().
static final double wblut.geom.WB_GeometryOp2D.getSignedAngleBetween2D (final double ux, final double uy, final double vx, final double vy, final double nx, final double ny) static
Parameters
ux
uy
vx
vy
nx
ny
Returns
References wblut.geom.WB_Vector.cross(), and wblut.geom.WB_Vector.dot().
static final double wblut.geom.WB_GeometryOp2D.getSignedAngleBetween2D (final double cx, final double cy, final double px, final double py, final double qx, final double qy, final double nx, final double ny) static
Parameters
cx
cy
px
py
qx
qy
nx
ny
Returns
References wblut.geom.WB_Vector.cross(), and wblut.geom.WB_Vector.dot().
static final double wblut.geom.WB_GeometryOp2D.getSignedAngleBetweenNorm2D (final double ux, final double uy, final double vx, final double vy, final double nx, final double ny) static
Parameters
ux
uy
vx
vy
nx
ny
Returns
References wblut.geom.WB_Vector.cross(), and wblut.geom.WB_Vector.dot().
static final double wblut.geom.WB_GeometryOp2D.getSignedArea2D (final List<?extends WB_Coord > coords, final int start, final int end) static
static final double wblut.geom.WB_GeometryOp2D.getSignedArea2D (final WB_Coord[] coords, final int start, final int end) static
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final double wblut.geom.WB_GeometryOp2D.getSignedArea2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3) static
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final double wblut.geom.WB_GeometryOp2D.getSimpleArea2D (final WB_Polygon poly) static
References wblut.geom.WB_Polygon.getNumberOfShellPoints(), wblut.geom.WB_Polygon.getPoint(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final double wblut.geom.WB_GeometryOp2D.getSqDistance2D (final WB_Coord p, final WB_Segment S) static
Parameters
p
S
Returns
References wblut.geom.WB_Vector.dot2D(), wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Line.getOrigin(), and wblut.geom.WB_Vector.sub().
static final double wblut.geom.WB_GeometryOp2D.getSqDistance2D (final WB_Coord p, final WB_PolyLine PL) static
References wblut.geom.WB_PolyLine.getNumberSegments(), wblut.geom.WB_PolyLine.getSegment(), and wblut.geom.WB_GeometryOp2D.getSqDistance2D().
static final double wblut.geom.WB_GeometryOp2D.getSqDistance2D (final WB_Coord p, final WB_Line L) static
Parameters
p
L
Returns
References wblut.geom.WB_Vector.dot2D(), wblut.geom.WB_Line.getDirection(), and wblut.geom.WB_Line.getOrigin().
static final double wblut.geom.WB_GeometryOp2D.getSqDistance2D (final WB_Coord p, final WB_Ray R) static
Parameters
p
R
Returns
References wblut.geom.WB_Vector.dot2D(), wblut.geom.WB_Ray.getDirection(), and wblut.geom.WB_Ray.getOrigin().
static final double wblut.geom.WB_GeometryOp2D.getSqDistance2D (final double px, final double py, final double qx, final double qy) static
Parameters
px
py
qx
qy
Returns
static final double wblut.geom.WB_GeometryOp2D.getSqDistance2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static double wblut.geom.WB_GeometryOp2D.getSqDistance2D (final WB_Coord p, final WB_AABB2D AABB) static
Parameters
p
AABB
Returns
References wblut.geom.WB_AABB2D.getMaxX(), wblut.geom.WB_AABB2D.getMaxY(), wblut.geom.WB_AABB2D.getMinX(), wblut.geom.WB_AABB2D.getMinY(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final double wblut.geom.WB_GeometryOp2D.getSqDistanceToLine2D (final WB_Coord p, final WB_Coord a, final WB_Coord b) static
Parameters
p
a
b
Returns
References wblut.geom.WB_Vector.dot2D().
static final double wblut.geom.WB_GeometryOp2D.getSqDistanceToLine2D (final WB_Coord p, final WB_Line L) static
Parameters
p
L
Returns
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_Vector.dot2D(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final double wblut.geom.WB_GeometryOp2D.getSqDistanceToPoint2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final double wblut.geom.WB_GeometryOp2D.getSqDistanceToRay2D (final WB_Coord p, final WB_Coord a, final WB_Coord b) static
Parameters
p
a
b
Returns
References wblut.geom.WB_Vector.dot2D().
static final double wblut.geom.WB_GeometryOp2D.getSqDistanceToSegment2D (final WB_Coord p, final WB_Coord a, final WB_Coord b) static
Parameters
p
a
b
Returns
References wblut.geom.WB_Vector.dot2D().
static final double wblut.geom.WB_GeometryOp2D.getSqLength2D (final double ux, final double uy) static
Parameters
ux
uy
Returns
static final double wblut.geom.WB_GeometryOp2D.getSqLength2D (final WB_Coord p) static
Parameters
p
Returns
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final WB_Circle wblut.geom.WB_GeometryOp2D.growCircleByPoint2D (final WB_Circle C, final WB_Coord p) static
References wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Vector.getSqLength2D(), wblut.geom.WB_Point.subToVector2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
static final double [] wblut.geom.WB_GeometryOp2D.interpolate2D (final double px, final double py, final double qx, final double qy, final double t) static
Parameters
px
py
qx
qy
t
Returns
static final double [] wblut.geom.WB_GeometryOp2D.interpolate2D (final WB_Coord p, final WB_Coord q, final double t) static
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final double [] wblut.geom.WB_GeometryOp2D.interpolateEase2D (final double px, final double py, final double qx, final double qy, final double t, final WB_Ease ease, final WB_Ease.EaseType type) static
References wblut.math.WB_Ease.easeIn(), wblut.math.WB_Ease.easeInOut(), and wblut.math.WB_Ease.easeOut().
static final double [] wblut.geom.WB_GeometryOp2D.interpolateEase2D (final WB_Coord p, final WB_Coord q, final double t, final WB_Ease ease, final WB_Ease.EaseType type) static
References wblut.math.WB_Ease.easeIn(), wblut.math.WB_Ease.easeInOut(), wblut.math.WB_Ease.easeOut(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final boolean wblut.geom.WB_GeometryOp2D.isCoincident2D (final WB_Coord a, final WB_Coord b) static
Parameters
a
b
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistance2D(), and wblut.math.WB_Epsilon.SQEPSILON.
static final boolean wblut.geom.WB_GeometryOp2D.isCollinear2D (final WB_Coord o, final WB_Coord p, final WB_Coord q) static
Parameters
o
p
q
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistanceToLine2D(), wblut.geom.WB_GeometryOp2D.getSqDistanceToPoint2D(), and wblut.math.WB_Epsilon.isZeroSq().
static final boolean wblut.geom.WB_GeometryOp2D.isLeft2D (final WB_Coord a, final WB_Coord b, final WB_Coord p) static
Parameters
a
b
p
Returns
References wblut.geom.WB_Predicates.orient2D().
static final boolean wblut.geom.WB_GeometryOp2D.isLeftStrict2D (final WB_Coord a, final WB_Coord b, final WB_Coord p) static
Parameters
a
b
p
Returns
References wblut.geom.WB_Predicates.orient2D().
static final boolean wblut.geom.WB_GeometryOp2D.isOrthogonal2D (final WB_Coord v0, final WB_Coord v1) static
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.geom.WB_GeometryOp2D.getLength2D(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final boolean wblut.geom.WB_GeometryOp2D.isOrthogonal2D (final WB_Coord v0, final WB_Coord v1, final double epsilon) static
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.geom.WB_GeometryOp2D.getLength2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final boolean wblut.geom.WB_GeometryOp2D.isOrthogonalNorm2D (final WB_Coord v0, final WB_Coord v1) static
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final boolean wblut.geom.WB_GeometryOp2D.isOrthogonalNorm2D (final WB_Coord v0, final WB_Coord v1, final double epsilon) static
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final boolean wblut.geom.WB_GeometryOp2D.isParallel2D (final WB_Coord v0, final WB_Coord v1) static
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_GeometryOp2D.getLength2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final boolean wblut.geom.WB_GeometryOp2D.isParallel2D (final WB_Coord v0, final WB_Coord v1, final double epsilon) static
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.geom.WB_GeometryOp2D.getLength2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final boolean wblut.geom.WB_GeometryOp2D.isParallelNorm2D (final WB_Coord v0, final WB_Coord v1) static
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final boolean wblut.geom.WB_GeometryOp2D.isParallelNorm2D (final WB_Coord v0, final WB_Coord v1, final double epsilon) static
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final boolean wblut.geom.WB_GeometryOp2D.isReflex2D (final WB_Coord p0, final WB_Coord p, final WB_Coord p1) static
Parameters
p0
p
p1
Returns
References wblut.geom.WB_GeometryOp2D.isRightStrict2D().
static final boolean wblut.geom.WB_GeometryOp2D.isRight2D (final WB_Coord a, final WB_Coord b, final WB_Coord p) static
Parameters
a
b
p
Returns
References wblut.geom.WB_Predicates.orient2D().
static final boolean wblut.geom.WB_GeometryOp2D.isRightStrict2D (final WB_Coord a, final WB_Coord b, final WB_Coord p) static
Parameters
a
b
p
Returns
References wblut.geom.WB_Predicates.orient2D().
static final boolean wblut.geom.WB_GeometryOp2D.isTangent2D (final WB_Circle C1, final WB_Circle C2) static
Parameters
C1
C2
Returns
References wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Vector.getDistance2D(), wblut.geom.WB_Circle.getRadius(), and wblut.math.WB_Epsilon.isZero().
static final boolean wblut.geom.WB_GeometryOp2D.isZero2D (final double ux, final double uy) static
Parameters
ux
uy
Returns
References wblut.geom.WB_GeometryOp2D.getSqLength2D(), and wblut.math.WB_Epsilon.SQEPSILON.
static final WB_Circle wblut.geom.WB_GeometryOp2D.mergeCircles2D (final WB_Circle C1, final WB_Circle C2) static
References wblut.geom.WB_Point.addMul(), wblut.geom.WB_Vector.dot(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Circle.getRadius(), and wblut.geom.WB_Vector.sub().
static final WB_IntersectionResult wblut.geom.WB_GeometryOp2D.NOINTERSECTION () static private
Returns
References wblut.geom.WB_IntersectionResult.intersection, wblut.geom.WB_IntersectionResult.sqDist, wblut.geom.WB_IntersectionResult.t1, and wblut.geom.WB_IntersectionResult.t2.
static final boolean wblut.geom.WB_GeometryOp2D.pointInTriangle2D (final WB_Coord p, final WB_Coord A, final WB_Coord B, final WB_Coord C) static
References wblut.geom.WB_GeometryOp2D.getSqDistanceToLine2D(), wblut.math.WB_Epsilon.isZeroSq(), and wblut.geom.WB_GeometryOp2D.sameSide2D().
static final boolean wblut.geom.WB_GeometryOp2D.pointInTriangle2D (final WB_Coord p, final WB_Triangle T) static
References wblut.geom.WB_GeometryOp2D.pointInTriangle2D().
static final boolean wblut.geom.WB_GeometryOp2D.pointInTriangleBary2D (final WB_Coord p, final WB_Coord A, final WB_Coord B, final WB_Coord C) static
Check if point p lies in triangle A-B-C using barycentric coordinates.
Parameters
p the p
A the a
B the b
C the c
Returns
true, false
References wblut.geom.WB_Vector.dot2D(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_GeometryOp2D.getSqDistanceToLine2D(), wblut.math.WB_Epsilon.isZeroSq(), and wblut.geom.WB_Point.subSelf().
static final boolean wblut.geom.WB_GeometryOp2D.pointInTriangleBary2D (final WB_Coord p, final WB_Triangle T) static
References wblut.geom.WB_GeometryOp2D.pointInTriangleBary2D().
static final WB_Coord wblut.geom.WB_GeometryOp2D.projectToCircle2D (final WB_Circle C, final WB_Coord v) static
Project point to circle
Parameters
C
v
Returns
point projected to circle
References wblut.geom.WB_Point.addMul(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Circle.getRadius(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Point.normalizeSelf(), and wblut.geom.WB_Point.sub().
static final boolean wblut.geom.WB_GeometryOp2D.sameSide2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord A, final WB_Coord B) static
Check if points p1 and p2 lie on same side of line A-B.
Parameters
p1
p2
A
B
Returns
true, false
References wblut.geom.WB_Predicates.orient2D().
static final boolean wblut.geom.WB_GeometryOp2D.sameSideOfLine2D (final WB_Coord p, final WB_Coord q, final WB_Line L) static
Parameters
p
q
L
Returns
References wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Line.getPoint(), and wblut.geom.WB_Predicates.orient2D().
static final WB_Polygon [] wblut.geom.WB_GeometryOp2D.splitPolygon2D (final WB_Polygon poly, final WB_Line L) static
Parameters
poly
L
Returns
References wblut.geom.WB_Classification.BACK, wblut.geom.WB_GeometryOp2D.classifyPointToLine2D(), wblut.geom.WB_GeometryFactory2D.createSimplePolygon(), wblut.geom.WB_IntersectionResult.dimension, wblut.geom.WB_Classification.FRONT, wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), wblut.geom.WB_Polygon.getPoint(), wblut.geom.WB_IntersectionResult.object, and wblut.geom.WB_Classification.ON.
static final WB_Segment [] wblut.geom.WB_GeometryOp2D.splitSegment2D (final WB_Segment S, final WB_Line L) static
Parameters
S
L
Returns
References wblut.geom.WB_Classification.BACK, wblut.geom.WB_GeometryOp2D.classifyPointToLine2D(), wblut.geom.WB_IntersectionResult.dimension, wblut.geom.WB_Classification.FRONT, wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_IntersectionResult.intersection, and wblut.geom.WB_IntersectionResult.object.
static final WB_Polygon wblut.geom.WB_GeometryOp2D.trimConvexPolygon2D (WB_Polygon poly, final double d) static
Parameters
poly
d
Returns
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory3D.createNormalizedVectorFromTo(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Polygon.getPoint(), wblut.geom.WB_Point.mulSelf(), wblut.geom.WB_GeometryOp2D.splitPolygon2D(), and wblut.geom.WB_Vector.Z.
static final WB_Polygon wblut.geom.WB_GeometryOp2D.trimConvexPolygon2D (WB_Polygon poly, final double[] d) static
Parameters
poly
d
Returns
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory3D.createNormalizedVectorFromTo(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Polygon.getPoint(), wblut.geom.WB_Point.mulSelf(), wblut.geom.WB_GeometryOp2D.splitPolygon2D(), and wblut.geom.WB_Vector.Z.
static final double wblut.geom.WB_GeometryOp2D.twiceSignedTriArea2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3) static
Twice signed tri area2 d.
Parameters
p1 the p1
p2 the p2
p3 the p3
Returns
the double
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static final double wblut.geom.WB_GeometryOp2D.twiceSignedTriArea2D (final double x1, final double y1, final double x2, final double y2, final double x3, final double y3) static
Twice signed tri area2 d.
Parameters
x1 the x1
y1 the y1
x2 the x2
y2 the y2
x3 the x3
y3 the y3
Returns
the double
Member Data Documentation
final WB_GeometryFactory wblut.geom.WB_GeometryOp2D.gf = new WB_GeometryFactory() static private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_GeometryOp2D.java