HE_Mesh: wblut.hemesh.HEM_Skew Class Reference
wblut.hemesh.HEM_Skew Class Reference
Public Member Functions
HEM_Skew ()
HEM_Skew setGroundPlane (final WB_Plane P)
HEM_Skew setGroundPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
HEM_Skew setSkewDirection (final WB_Coord p)
HEM_Skew setSkewDirection (final double vx, final double vy, final double vz)
HEM_Skew setSkewFactor (final double f)
HEM_Skew setPosOnly (final boolean b)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_Plane groundPlane
WB_Vector skewDirection
double skewFactor
boolean posOnly
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Skew a mesh. Determined by a ground plane, a skew direction and a skew factor.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_Skew.HEM_Skew ()
Instantiates a new HEM_Skew.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Skew.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.mul(), and wblut.hemesh.HE_Mesh.vItr().
HE_Mesh wblut.hemesh.HEM_Skew.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Selection.collectVertices(), wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.mul(), and wblut.hemesh.HE_Selection.vItr().
HEM_Skew wblut.hemesh.HEM_Skew.setGroundPlane (final WB_Plane P)
Set ground plane.
Parameters
P ground plane
Returns
self
HEM_Skew wblut.hemesh.HEM_Skew.setGroundPlane (final double ox, final double oy, final double oz, final double nx, final double ny, final double nz)
Sets the ground plane.
Parameters
ox the ox
oy the oy
oz the oz
nx the nx
ny the ny
nz the nz
Returns
the hE m_ skew
HEM_Skew wblut.hemesh.HEM_Skew.setPosOnly (final boolean b)
Positive only? Only apply modifier to positive side of ground plane.
Parameters
b true, false
Returns
self
HEM_Skew wblut.hemesh.HEM_Skew.setSkewDirection (final WB_Coord p)
Set skew direction.
Parameters
p direction
Returns
self
References wblut.geom.WB_Vector.normalizeSelf().
HEM_Skew wblut.hemesh.HEM_Skew.setSkewDirection (final double vx, final double vy, final double vz)
Sets the skew direction.
Parameters
vx the vx
vy the vy
vz the vz
Returns
the hE m_ skew
References wblut.geom.WB_Vector.normalizeSelf().
HEM_Skew wblut.hemesh.HEM_Skew.setSkewFactor (final double f)
Set skew factor, ratio of skew distance to distance to ground plane.
Parameters
f direction
Returns
self
Member Data Documentation
WB_Plane wblut.hemesh.HEM_Skew.groundPlane private
Ground plane.
boolean wblut.hemesh.HEM_Skew.posOnly private
Only modify positive side of ground plane.
WB_Vector wblut.hemesh.HEM_Skew.skewDirection private
Skew direction.
double wblut.hemesh.HEM_Skew.skewFactor private
Skew factor.
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Skew.java