HE_Mesh: wblut.geom.WB_IsoSurfaceVOL2D Class Reference
wblut.geom.WB_IsoSurfaceVOL2D Class Reference
Public Member Functions
WB_IsoSurfaceVOL2D ()
WB_IsoSurfaceVOL2D setResolution (final int resx, final int resy)
WB_IsoSurfaceVOL2D setSize (final double dx, final double dy)
WB_IsoSurfaceVOL2D setZFactor (final double zf)
WB_IsoSurfaceVOL2D setValues (final double[][] values)
WB_IsoSurfaceVOL2D setValues (final float[][] values)
WB_IsoSurfaceVOL2D setValues (final WB_ScalarParameter function, final double xi, final double yi, final double dx, final double dy, final int width, final int height)
WB_IsoSurfaceVOL2D setValues (final WB_HashGridDouble2D values)
WB_IsoSurfaceVOL2D setValues (final String path, final PApplet home, final int width, final int height)
WB_IsoSurfaceVOL2D setValues (final String path, final PApplet home, final int width, final int height, final WB_IsoValues2D.Mode mode)
WB_IsoSurfaceVOL2D setValues (final PImage image, final PApplet home, final int width, final int height)
WB_IsoSurfaceVOL2D setValues (final PImage image, final PApplet home, final int width, final int height, final WB_IsoValues2D.Mode mode)
WB_IsoSurfaceVOL2D setValues (final WB_IsoValues2D values)
WB_IsoSurfaceVOL2D setIsolevel (final double isolevelmin, final double isolevelmax)
WB_IsoSurfaceVOL2D setCenter (final WB_Coord c)
List< WB_Triangle > getTriangles ()
Private Member Functions
int index (final int i, final int j)
double value (final int i, final int j)
WB_Point vertex (final int i, final int j, final WB_Point offset)
WB_Point xedge (final int i, final int j, final WB_Point offset, final double isolevel)
WB_Point yedge (final int i, final int j, final WB_Point offset, final double isolevel)
WB_Point interp (final double isolevel, final WB_Point p1, final WB_Point p2, final double valp1, final double valp2)
int classifyCell (final int i, final int j)
void polygonise ()
void getPolygons (final int i, final int j, final int cubeindex, final WB_Point offset)
WB_Point getIsoVertex (final int isopointindex, final int i, final int j, final WB_Point offset)
Private Attributes
int[] digits = new int[4]
int[][] entries
WB_IsoValues2D values
int resx
double cx
double dx
double isolevelmin
IntObjectHashMap< WB_Point > xedges
IntObjectHashMap< WB_Point > yedges
IntObjectHashMap< WB_Point > vertices
double zFactor
List< WB_Triangle > triangles
Constructor & Destructor Documentation
wblut.geom.WB_IsoSurfaceVOL2D.WB_IsoSurfaceVOL2D ()
Member Function Documentation
int wblut.geom.WB_IsoSurfaceVOL2D.classifyCell (final int i, final int j) private
Classify cell.
Parameters
i the i
j the j
Returns
the int
References wblut.geom.WB_IsoSurfaceVOL2D.value().
WB_Point wblut.geom.WB_IsoSurfaceVOL2D.getIsoVertex (final int isopointindex, final int i, final int j, final WB_Point offset) private
Parameters
isopointindex
i
j
offset
Returns
References wblut.geom.WB_IsoSurfaceVOL2D.vertex(), wblut.geom.WB_IsoSurfaceVOL2D.xedge(), and wblut.geom.WB_IsoSurfaceVOL2D.yedge().
void wblut.geom.WB_IsoSurfaceVOL2D.getPolygons (final int i, final int j, final int cubeindex, final WB_Point offset) private
Gets the polygons.
Parameters
i the i
j the j
cubeindex the cubeindex
offset
Returns
the polygons
References wblut.geom.WB_IsoSurfaceVOL2D.getIsoVertex().
List<WB_Triangle> wblut.geom.WB_IsoSurfaceVOL2D.getTriangles ()
References wblut.geom.WB_IsoSurfaceVOL2D.polygonise(), and wblut.geom.WB_IsoSurfaceVOL2D.triangles.
int wblut.geom.WB_IsoSurfaceVOL2D.index (final int i, final int j) private
Parameters
i
j
Returns
WB_Point wblut.geom.WB_IsoSurfaceVOL2D.interp (final double isolevel, final WB_Point p1, final WB_Point p2, final double valp1, final double valp2) private
Interp.
Parameters
isolevel the isolevel
p1 the p1
p2 the p2
valp1 the valp1
valp2 the valp2
Returns
the h e_ vertex
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
void wblut.geom.WB_IsoSurfaceVOL2D.polygonise () private
Polygonise.
References wblut.geom.WB_IsoSurfaceVOL2D.classifyCell(), wblut.geom.WB_IsoSurfaceVOL2D.getPolygons(), and wblut.geom.WB_IsoSurfaceVOL2D.resx.
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setCenter (final WB_Coord c)
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setIsolevel (final double isolevelmin, final double isolevelmax)
Parameters
isolevelmin
isolevelmax
Returns
References wblut.geom.WB_IsoSurfaceVOL2D.isolevelmin.
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setResolution (final int resx, final int resy)
Number of cells.
Parameters
resx the resx
resy the resy
Returns
self
References wblut.geom.WB_IsoSurfaceVOL2D.resx.
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setSize (final double dx, final double dy)
Parameters
dx
dy
Returns
References wblut.geom.WB_IsoSurfaceVOL2D.dx.
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setValues (final double values[][])
Values at grid points.
Parameters
values double[resx+1][resy+1]
Returns
self
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setValues (final float values[][])
Values at grid points.
Parameters
values float[resx+1][resy+1]
Returns
self
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setValues (final WB_ScalarParameter function, final double xi, final double yi, final double dx, final double dy, final int width, final int height)
Parameters
function
xi
yi
dx
dy
Returns
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setValues (final WB_HashGridDouble2D values)
Parameters
values
Returns
References wblut.geom.WB_HashGridDouble2D.getHeight(), and wblut.geom.WB_HashGridDouble2D.getWidth().
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setValues (final String path, final PApplet home, final int width, final int height)
Parameters
path
home
width
height
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), and wblut.geom.WB_IsoValues2D.getWidth().
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setValues (final String path, final PApplet home, final int width, final int height, final WB_IsoValues2D.Mode mode)
Parameters
path
home
width
height
mode
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), and wblut.geom.WB_IsoValues2D.getWidth().
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setValues (final PImage image, final PApplet home, final int width, final int height)
Parameters
image
home
width
height
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), and wblut.geom.WB_IsoValues2D.getWidth().
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setValues (final PImage image, final PApplet home, final int width, final int height, final WB_IsoValues2D.Mode mode)
Parameters
image
home
width
height
mode
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), and wblut.geom.WB_IsoValues2D.getWidth().
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setValues (final WB_IsoValues2D values)
Parameters
values
Returns
References wblut.geom.WB_IsoValues2D.getHeight(), wblut.geom.WB_IsoValues2D.getWidth(), and wblut.geom.WB_IsoSurfaceVOL2D.values.
WB_IsoSurfaceVOL2D wblut.geom.WB_IsoSurfaceVOL2D.setZFactor (final double zf)
double wblut.geom.WB_IsoSurfaceVOL2D.value (final int i, final int j) private
Value.
Parameters
i the i
j the j
Returns
the double
References wblut.geom.WB_IsoValues2D.value().
WB_Point wblut.geom.WB_IsoSurfaceVOL2D.vertex (final int i, final int j, final WB_Point offset) private
Parameters
i
j
offset
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_IsoSurfaceVOL2D.index(), and wblut.geom.WB_IsoSurfaceVOL2D.value().
WB_Point wblut.geom.WB_IsoSurfaceVOL2D.xedge (final int i, final int j, final WB_Point offset, final double isolevel) private
Xedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
offset
isolevel
Returns
edge vertex
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_IsoSurfaceVOL2D.index(), wblut.geom.WB_IsoSurfaceVOL2D.interp(), and wblut.geom.WB_IsoSurfaceVOL2D.value().
WB_Point wblut.geom.WB_IsoSurfaceVOL2D.yedge (final int i, final int j, final WB_Point offset, final double isolevel) private
Yedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
offset
isolevel
Returns
edge vertex
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_IsoSurfaceVOL2D.index(), wblut.geom.WB_IsoSurfaceVOL2D.interp(), and wblut.geom.WB_IsoSurfaceVOL2D.value().
Member Data Documentation
double wblut.geom.WB_IsoSurfaceVOL2D.cx private
int [] wblut.geom.WB_IsoSurfaceVOL2D.digits = new int[4] private
double wblut.geom.WB_IsoSurfaceVOL2D.dx private
int [][] wblut.geom.WB_IsoSurfaceVOL2D.entries private
double wblut.geom.WB_IsoSurfaceVOL2D.isolevelmin private
int wblut.geom.WB_IsoSurfaceVOL2D.resx private
List<WB_Triangle> wblut.geom.WB_IsoSurfaceVOL2D.triangles private
WB_IsoValues2D wblut.geom.WB_IsoSurfaceVOL2D.values private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurfaceVOL2D.vertices private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurfaceVOL2D.xedges private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurfaceVOL2D.yedges private
double wblut.geom.WB_IsoSurfaceVOL2D.zFactor private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_IsoSurfaceVOL2D.java