HE_Mesh: wblut.hemesh.HEC_Sphere Class Reference
wblut.hemesh.HEC_Sphere Class Reference
Public Member Functions
HEC_Sphere ()
HEC_Sphere setRadius (final double R)
HEC_Sphere setRadius (final double rx, final double ry, final double rz)
HEC_Sphere setUFacets (final int facets)
HEC_Sphere setVFacets (final int facets)
HEC_Sphere setPhase (final double p)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Member Functions
int index (final int u, final int v)
Private Attributes
double rx
int uFacets
int vFacets
double phase
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Sphere.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_Sphere.HEC_Sphere ()
Instantiates a new HEC_Sphere.
References wblut.geom.WB_Vector.Y, and wblut.hemesh.HEC_Creator.Z.
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_Sphere.createBase () protected
References wblut.hemesh.HEC_FromFacelist.createBase(), wblut.hemesh.HEC_Sphere.index(), wblut.hemesh.HE_Mesh.scaleSelf(), wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HEC_FromFacelist.setVertexUVW(), wblut.hemesh.HEC_FromFacelist.setVertices(), wblut.hemesh.HEC_Sphere.uFacets, and wblut.hemesh.HEC_Sphere.vFacets.
int wblut.hemesh.HEC_Sphere.index (final int u, final int v) private
Parameters
u
v
Returns
HEC_Sphere wblut.hemesh.HEC_Sphere.setPhase (final double p)
HEC_Sphere wblut.hemesh.HEC_Sphere.setRadius (final double R)
Set fixed radius.
Parameters
R radius
Returns
self
HEC_Sphere wblut.hemesh.HEC_Sphere.setRadius (final double rx, final double ry, final double rz)
Parameters
rx
ry
rz
Returns
References wblut.hemesh.HEC_Sphere.rx.
HEC_Sphere wblut.hemesh.HEC_Sphere.setUFacets (final int facets)
Set number of faces along equator.
Parameters
facets number of faces
Returns
self
HEC_Sphere wblut.hemesh.HEC_Sphere.setVFacets (final int facets)
Set number of facets along meridian.
Parameters
facets number of faces
Returns
self
Member Data Documentation
double wblut.hemesh.HEC_Sphere.phase private
double wblut.hemesh.HEC_Sphere.rx private
Radius.
int wblut.hemesh.HEC_Sphere.uFacets private
U facets.
int wblut.hemesh.HEC_Sphere.vFacets private
V facets.
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_Sphere.java