HE_Mesh: wblut.hemesh.HEC_Torus Class Reference
wblut.hemesh.HEC_Torus Class Reference
Public Member Functions
HEC_Torus ()
HEC_Torus (final double Ri, final double Ro, final int tubefacets, final int torusfacets)
HEC_Torus (final double Rix, final double Riz, final double Ro, final int tubefacets, final int torusfacets)
HEC_Torus setRadius (final double Ri, final double Ro)
HEC_Torus setRadius (final double Rix, final double Riz, final double Ro)
HEC_Torus setTorusRadius (final double Ro)
HEC_Torus setTubeRadius (final double Ri)
HEC_Torus setTubeRadius (final double Rix, final double Riz)
HEC_Torus setTorusRadius (final WB_ScalarParameter Ro)
HEC_Torus setTubeRadius (final WB_ScalarParameter Ri)
HEC_Torus setTubeRadius (final WB_ScalarParameter Rix, final WB_ScalarParameter Riz)
HEC_Torus setTubeFacets (final int facets)
HEC_Torus setTorusFacets (final int facets)
HEC_Torus setTwist (final int t)
HEC_Torus setTorusPhase (final double p)
HEC_Torus setTubePhase (final double p)
HEC_Torus setTubePhase (final WB_ScalarParameter p)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Attributes
WB_ScalarParameter Rix
WB_ScalarParameter Ro
int tubefacets
int torusfacets
int twist
WB_ScalarParameter tubephase
double torusphase
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Torus.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_Torus.HEC_Torus ()
wblut.hemesh.HEC_Torus.HEC_Torus (final double Ri, final double Ro, final int tubefacets, final int torusfacets)
Instantiates a new torus.
Parameters
Ri
Ro
tubefacets
torusfacets
References wblut.hemesh.HEC_Torus.torusfacets, and wblut.hemesh.HEC_Torus.tubefacets.
wblut.hemesh.HEC_Torus.HEC_Torus (final double Rix, final double Riz, final double Ro, final int tubefacets, final int torusfacets)
References wblut.hemesh.HEC_Torus.torusfacets, and wblut.hemesh.HEC_Torus.tubefacets.
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_Torus.createBase () protected
References wblut.hemesh.HEC_FromFacelist.createBase(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HEC_FromFacelist.setVertexUVW(), wblut.hemesh.HEC_FromFacelist.setVertices(), wblut.hemesh.HEC_Torus.torusfacets, wblut.hemesh.HEC_Torus.tubefacets, wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.zd().
HEC_Torus wblut.hemesh.HEC_Torus.setRadius (final double Ri, final double Ro)
Sets the radius.
Parameters
Ri
Ro
Returns
HEC_Torus wblut.hemesh.HEC_Torus.setRadius (final double Rix, final double Riz, final double Ro)
HEC_Torus wblut.hemesh.HEC_Torus.setTorusFacets (final int facets)
Sets the torus facets.
Parameters
facets
Returns
HEC_Torus wblut.hemesh.HEC_Torus.setTorusPhase (final double p)
Sets torus phase.
Parameters
p
Returns
HEC_Torus wblut.hemesh.HEC_Torus.setTorusRadius (final double Ro)
HEC_Torus wblut.hemesh.HEC_Torus.setTorusRadius (final WB_ScalarParameter Ro)
Sets the torus radius. Parameter should be a WB_ScalarParameter on the domain [0,2PI]
Parameters
Ro
Returns
References wblut.hemesh.HEC_Torus.Ro.
HEC_Torus wblut.hemesh.HEC_Torus.setTubeFacets (final int facets)
Sets the tube facets.
Parameters
facets
Returns
HEC_Torus wblut.hemesh.HEC_Torus.setTubePhase (final double p)
Sets tube phase.
Parameters
p
Returns
HEC_Torus wblut.hemesh.HEC_Torus.setTubePhase (final WB_ScalarParameter p)
Sets the tube phase, the rotation around the torus center circle. Parameter should be a WB_ScalarParameter on the domain [0,2PI]
Parameters
p
Returns
HEC_Torus wblut.hemesh.HEC_Torus.setTubeRadius (final double Ri)
HEC_Torus wblut.hemesh.HEC_Torus.setTubeRadius (final double Rix, final double Riz)
HEC_Torus wblut.hemesh.HEC_Torus.setTubeRadius (final WB_ScalarParameter Ri)
Sets the tube radius. Parameter should be a WB_ScalarParameter on the domain [0,2PI]
Parameters
Ri
Returns
HEC_Torus wblut.hemesh.HEC_Torus.setTubeRadius (final WB_ScalarParameter Rix, final WB_ScalarParameter Riz)
Sets the tube elliptical axes. Parameter should be a WB_ScalarParameter on the domain [0,2PI]
Parameters
Rix Elliptical axis in torus plane
Riz Elliptical axis along torus axis
Returns
References wblut.hemesh.HEC_Torus.Rix.
HEC_Torus wblut.hemesh.HEC_Torus.setTwist (final int t)
Sets twist.
Parameters
t
Returns
Member Data Documentation
WB_ScalarParameter wblut.hemesh.HEC_Torus.Rix private
Tube radius.
WB_ScalarParameter wblut.hemesh.HEC_Torus.Ro private
Torus Radius.
int wblut.hemesh.HEC_Torus.torusfacets private
Height steps.
double wblut.hemesh.HEC_Torus.torusphase private
int wblut.hemesh.HEC_Torus.tubefacets private
Facets.
WB_ScalarParameter wblut.hemesh.HEC_Torus.tubephase private
int wblut.hemesh.HEC_Torus.twist private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_Torus.java