HE_Mesh: wblut.geom.WB_QuadtreeDouble Class Reference
wblut.geom.WB_QuadtreeDouble Class Reference
Classes
class WB_QuadtreeDoubleEntry
Public Member Functions
WB_QuadtreeDouble (final WB_Coord center, final double size)
void addPoint (final WB_Coord p, final double value)
void addAll (final Collection<?extends WB_Coord > points)
void clear ()
int getLevel ()
WB_QuadtreeDouble getNode (final WB_Coord p)
double getMinNodeSize ()
int getNumNodes ()
WB_Coord getCenter ()
WB_QuadtreeDouble getParent ()
int getNumberOfPoints ()
List< WB_QuadtreeDouble > getNodes ()
double getSize ()
boolean remove (final WB_Coord p)
void removeAll (final Collection< WB_Coord > points)
void setMinNodeSize (final double minNodeSize)
void setAutoPrune (final boolean state)
WB_AABB2D getBox ()
List< WB_QuadtreeDoubleEntry > getEntries ()
List< WB_QuadtreeDoubleEntry > getEntriesInRange (final WB_AABB2D AABB)
List< WB_QuadtreeDoubleEntry > getEntriesInRange (final WB_Circle circle)
List< WB_QuadtreeDoubleEntry > getEntriesInRange (final WB_Coord center, final double radius)
List< WB_Coord > getPoints ()
List< WB_Coord > getPointsInRange (final WB_AABB2D AABB)
List< WB_Coord > getPointsInRange (final WB_Circle circle)
List< WB_Coord > getPointsInRange (final WB_Coord center, final double radius)
double[] getValues ()
double[] getValuesInRange (final WB_AABB2D AABB)
double[] getValuesInRange (final WB_Circle circle)
double[] getValuesInRange (final WB_Coord center, final double radius)
Protected Member Functions
final int getQuadrant (final WB_Coord p)
Protected Attributes
WB_AABB2D box
WB_Coord extent
WB_Coord min
double minNodeSize = 4.0
WB_QuadtreeDouble parent
WB_QuadtreeDouble[] nodes
int numNodes
List< WB_QuadtreeDoubleEntry > entries
double size
WB_Coord center
Private Member Functions
WB_QuadtreeDouble (final WB_QuadtreeDouble p, final WB_Coord center, final double size)
void prune ()
Private Attributes
int level = 0
boolean autoPrune = false
Constructor & Destructor Documentation
wblut.geom.WB_QuadtreeDouble.WB_QuadtreeDouble (final WB_QuadtreeDouble p, final WB_Coord center, final double size) private
References wblut.geom.WB_QuadtreeDouble.size, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
wblut.geom.WB_QuadtreeDouble.WB_QuadtreeDouble (final WB_Coord center, final double size)
References wblut.geom.WB_QuadtreeDouble.size, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
Member Function Documentation
void wblut.geom.WB_QuadtreeDouble.addAll (final Collection<?extends WB_Coord > points)
References wblut.geom.WB_QuadtreeDouble.addPoint().
void wblut.geom.WB_QuadtreeDouble.addPoint (final WB_Coord p, final double value)
References wblut.geom.WB_Point.add(), wblut.geom.WB_QuadtreeDouble.addPoint(), wblut.geom.WB_AABB2D.contains(), wblut.geom.WB_QuadtreeDouble.getQuadrant(), and wblut.geom.WB_QuadtreeDouble.WB_QuadtreeDouble().
void wblut.geom.WB_QuadtreeDouble.clear ()
WB_AABB2D wblut.geom.WB_QuadtreeDouble.getBox ()
References wblut.geom.WB_QuadtreeDouble.box.
WB_Coord wblut.geom.WB_QuadtreeDouble.getCenter ()
References wblut.geom.WB_QuadtreeDouble.center.
List<WB_QuadtreeDoubleEntry> wblut.geom.WB_QuadtreeDouble.getEntries ()
References wblut.geom.WB_QuadtreeDouble.getEntries().
List<WB_QuadtreeDoubleEntry> wblut.geom.WB_QuadtreeDouble.getEntriesInRange (final WB_AABB2D AABB)
References wblut.geom.WB_AABB2D.contains(), wblut.geom.WB_QuadtreeDouble.getEntriesInRange(), and wblut.geom.WB_AABB2D.intersects().
List<WB_QuadtreeDoubleEntry> wblut.geom.WB_QuadtreeDouble.getEntriesInRange (final WB_Circle circle)
References wblut.geom.WB_Circle.contains(), wblut.geom.WB_QuadtreeDouble.getEntriesInRange(), and wblut.geom.WB_AABB2D.intersects().
List<WB_QuadtreeDoubleEntry> wblut.geom.WB_QuadtreeDouble.getEntriesInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_QuadtreeDouble.getEntriesInRange().
int wblut.geom.WB_QuadtreeDouble.getLevel ()
References wblut.geom.WB_QuadtreeDouble.level.
double wblut.geom.WB_QuadtreeDouble.getMinNodeSize ()
References wblut.geom.WB_QuadtreeDouble.minNodeSize.
WB_QuadtreeDouble wblut.geom.WB_QuadtreeDouble.getNode (final WB_Coord p)
References wblut.geom.WB_AABB2D.contains(), wblut.geom.WB_QuadtreeDouble.getNode(), and wblut.geom.WB_QuadtreeDouble.getQuadrant().
List<WB_QuadtreeDouble> wblut.geom.WB_QuadtreeDouble.getNodes ()
int wblut.geom.WB_QuadtreeDouble.getNumberOfPoints ()
int wblut.geom.WB_QuadtreeDouble.getNumNodes ()
References wblut.geom.WB_QuadtreeDouble.numNodes.
WB_QuadtreeDouble wblut.geom.WB_QuadtreeDouble.getParent ()
References wblut.geom.WB_QuadtreeDouble.parent.
List<WB_Coord> wblut.geom.WB_QuadtreeDouble.getPoints ()
References wblut.geom.WB_QuadtreeDouble.getPoints().
List<WB_Coord> wblut.geom.WB_QuadtreeDouble.getPointsInRange (final WB_AABB2D AABB)
References wblut.geom.WB_QuadtreeDouble.getEntriesInRange().
List<WB_Coord> wblut.geom.WB_QuadtreeDouble.getPointsInRange (final WB_Circle circle)
References wblut.geom.WB_QuadtreeDouble.getEntriesInRange().
List<WB_Coord> wblut.geom.WB_QuadtreeDouble.getPointsInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_QuadtreeDouble.getPointsInRange().
final int wblut.geom.WB_QuadtreeDouble.getQuadrant (final WB_Coord p) protected
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_QuadtreeDouble.getSize ()
References wblut.geom.WB_QuadtreeDouble.size.
double [] wblut.geom.WB_QuadtreeDouble.getValues ()
References wblut.geom.WB_QuadtreeDouble.getEntries().
double [] wblut.geom.WB_QuadtreeDouble.getValuesInRange (final WB_AABB2D AABB)
References wblut.geom.WB_QuadtreeDouble.getEntriesInRange().
double [] wblut.geom.WB_QuadtreeDouble.getValuesInRange (final WB_Circle circle)
References wblut.geom.WB_QuadtreeDouble.getEntriesInRange().
double [] wblut.geom.WB_QuadtreeDouble.getValuesInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_QuadtreeDouble.getValuesInRange().
void wblut.geom.WB_QuadtreeDouble.prune () private
References wblut.geom.WB_QuadtreeDouble.prune().
boolean wblut.geom.WB_QuadtreeDouble.remove (final WB_Coord p)
References wblut.geom.WB_QuadtreeDouble.WB_QuadtreeDoubleEntry.coord, wblut.geom.WB_QuadtreeDouble.entries, wblut.geom.WB_QuadtreeDouble.getNode(), and wblut.geom.WB_QuadtreeDouble.prune().
void wblut.geom.WB_QuadtreeDouble.removeAll (final Collection< WB_Coord > points)
void wblut.geom.WB_QuadtreeDouble.setAutoPrune (final boolean state)
void wblut.geom.WB_QuadtreeDouble.setMinNodeSize (final double minNodeSize)
Member Data Documentation
boolean wblut.geom.WB_QuadtreeDouble.autoPrune = false private
WB_AABB2D wblut.geom.WB_QuadtreeDouble.box protected
WB_Coord wblut.geom.WB_QuadtreeDouble.center protected
List<WB_QuadtreeDoubleEntry> wblut.geom.WB_QuadtreeDouble.entries protected
WB_Coord wblut.geom.WB_QuadtreeDouble.extent protected
int wblut.geom.WB_QuadtreeDouble.level = 0 private
WB_Coord wblut.geom.WB_QuadtreeDouble.min protected
double wblut.geom.WB_QuadtreeDouble.minNodeSize = 4.0 protected
WB_QuadtreeDouble [] wblut.geom.WB_QuadtreeDouble.nodes protected
int wblut.geom.WB_QuadtreeDouble.numNodes protected
WB_QuadtreeDouble wblut.geom.WB_QuadtreeDouble.parent protected
double wblut.geom.WB_QuadtreeDouble.size protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_QuadtreeDouble.java