HE_Mesh: wblut.hemesh.HEM_Lattice Class Reference
wblut.hemesh.HEM_Lattice Class Reference
Public Member Functions
HEM_Lattice ()
HEM_Lattice setDepth (final double d)
HEM_Lattice setDepth (final WB_ScalarParameter d)
HEM_Lattice setWidth (final double w)
HEM_Lattice setWidth (final WB_ScalarParameter w)
HEM_Lattice setWidth (final double w, final double hew)
HEM_Lattice setWidth (final WB_ScalarParameter w, final WB_ScalarParameter hew)
HEM_Lattice setBulge (final double d)
HEM_Lattice setBulge (final WB_ScalarParameter d)
HEM_Lattice setBulge (final double inner, final double outer)
HEM_Lattice setBulge (final WB_ScalarParameter inner, final WB_ScalarParameter outer)
HEM_Lattice setFuse (final boolean b)
HEM_Lattice setThresholdAngle (final double a)
HEM_Lattice setFuseAngle (final double a)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_ScalarParameter d
WB_ScalarParameter sew
WB_ScalarParameter hew
double thresholdAngle
boolean fuse
double fuseAngle
WB_ScalarParameter ibulge
Static Private Attributes
static final WB_GeometryFactory gf = new WB_GeometryFactory()
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_Lattice.HEM_Lattice ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Lattice.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Selection.add(), wblut.hemesh.HEM_FlipFaces.applySelf(), wblut.hemesh.HEM_VertexExpand.applySelf(), wblut.geom.WB_Polygon.closestIndex(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HEC_Creator.create(), wblut.geom.WB_GeometryFactory2D.createSimplePolygon(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceHalfedges(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Mesh.getFacesAsArray(), wblut.hemesh.HE_Mesh.getFaceWithKey(), wblut.hemesh.HE_Mesh.getHalfedgeWithKey(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfHalfedges(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HEC_Copy.halfedgeCorrelation, wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Halfedge.key(), wblut.hemesh.HE_Face.key(), wblut.hemesh.HE_Mesh.modify(), wblut.geom.WB_Vector.mul(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Face.push(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_Mesh.selectAllFaces(), wblut.hemesh.HEM_Extrude.setChamfer(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.hemesh.HEM_VertexExpand.setDistance(), wblut.hemesh.HEM_Extrude.setDistance(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setDuringStatus(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HEM_Extrude.setFuse(), wblut.hemesh.HEM_Extrude.setFuseAngle(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HEM_Extrude.setHardEdgeChamfer(), wblut.hemesh.HEC_Copy.setMesh(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HEM_Extrude.setRelative(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HEM_Extrude.setThresholdAngle(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HE_Machine.tracker, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
HE_Mesh wblut.hemesh.HEM_Lattice.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Selection.add(), wblut.hemesh.HEM_FlipFaces.applySelf(), wblut.hemesh.HEM_VertexExpand.applySelf(), wblut.geom.WB_Polygon.closestIndex(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HEC_Creator.create(), wblut.geom.WB_GeometryFactory2D.createSimplePolygon(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceHalfedges(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Mesh.getFacesAsArray(), wblut.hemesh.HE_Mesh.getFaceWithKey(), wblut.hemesh.HE_Mesh.getHalfedgeWithKey(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfHalfedges(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HEC_Copy.halfedgeCorrelation, wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Halfedge.key(), wblut.hemesh.HE_Face.key(), wblut.hemesh.HE_Selection.modify(), wblut.geom.WB_Vector.mul(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Face.push(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_Mesh.selectAllFaces(), wblut.hemesh.HEM_Extrude.setChamfer(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.hemesh.HEM_VertexExpand.setDistance(), wblut.hemesh.HEM_Extrude.setDistance(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setDuringStatus(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HEM_Extrude.setFuse(), wblut.hemesh.HEM_Extrude.setFuseAngle(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HEM_Extrude.setHardEdgeChamfer(), wblut.hemesh.HEC_Copy.setMesh(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HEM_Extrude.setRelative(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HEM_Extrude.setThresholdAngle(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HE_Machine.tracker, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
HEM_Lattice wblut.hemesh.HEM_Lattice.setBulge (final double d)
Parameters
d
Returns
HEM_Lattice wblut.hemesh.HEM_Lattice.setBulge (final WB_ScalarParameter d)
References wblut.hemesh.HEM_Lattice.d.
HEM_Lattice wblut.hemesh.HEM_Lattice.setBulge (final double inner, final double outer)
Parameters
inner
outer
Returns
HEM_Lattice wblut.hemesh.HEM_Lattice.setBulge (final WB_ScalarParameter inner, final WB_ScalarParameter outer)
HEM_Lattice wblut.hemesh.HEM_Lattice.setDepth (final double d)
Parameters
d
Returns
HEM_Lattice wblut.hemesh.HEM_Lattice.setDepth (final WB_ScalarParameter d)
HEM_Lattice wblut.hemesh.HEM_Lattice.setFuse (final boolean b)
Parameters
b
Returns
HEM_Lattice wblut.hemesh.HEM_Lattice.setFuseAngle (final double a)
Parameters
a
Returns
HEM_Lattice wblut.hemesh.HEM_Lattice.setThresholdAngle (final double a)
Parameters
a
Returns
HEM_Lattice wblut.hemesh.HEM_Lattice.setWidth (final double w)
Parameters
w
Returns
HEM_Lattice wblut.hemesh.HEM_Lattice.setWidth (final WB_ScalarParameter w)
HEM_Lattice wblut.hemesh.HEM_Lattice.setWidth (final double w, final double hew)
Parameters
w
hew
Returns
HEM_Lattice wblut.hemesh.HEM_Lattice.setWidth (final WB_ScalarParameter w, final WB_ScalarParameter hew)
References wblut.hemesh.HEM_Lattice.hew.
Member Data Documentation
WB_ScalarParameter wblut.hemesh.HEM_Lattice.d private
boolean wblut.hemesh.HEM_Lattice.fuse private
double wblut.hemesh.HEM_Lattice.fuseAngle private
final WB_GeometryFactory wblut.hemesh.HEM_Lattice.gf = new WB_GeometryFactory() static private
WB_ScalarParameter wblut.hemesh.HEM_Lattice.hew private
WB_ScalarParameter wblut.hemesh.HEM_Lattice.ibulge private
WB_ScalarParameter wblut.hemesh.HEM_Lattice.sew private
double wblut.hemesh.HEM_Lattice.thresholdAngle private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Lattice.java