HE_Mesh: wblut.hemesh.HET_MeshGraph.Node Class Reference
wblut.hemesh.HET_MeshGraph.Node Class Reference
Public Member Functions
Node (final int id, final WB_Coord pos)
String toString ()
int compareTo (final Node other)
void reset ()
Public Attributes
final int index
List< Edge > neighbors
double distanceToSource = Double.POSITIVE_INFINITY
Node previous
double x
Constructor & Destructor Documentation
wblut.hemesh.HET_MeshGraph.Node.Node (final int id, final WB_Coord pos)
Parameters
id
pos
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
Member Function Documentation
int wblut.hemesh.HET_MeshGraph.Node.compareTo (final Node other)
References wblut.hemesh.HET_MeshGraph.Node.distanceToSource.
void wblut.hemesh.HET_MeshGraph.Node.reset ()
String wblut.hemesh.HET_MeshGraph.Node.toString ()
References wblut.hemesh.HET_MeshGraph.Node.index.
Member Data Documentation
double wblut.hemesh.HET_MeshGraph.Node.distanceToSource = Double.POSITIVE_INFINITY
final int wblut.hemesh.HET_MeshGraph.Node.index
List<Edge> wblut.hemesh.HET_MeshGraph.Node.neighbors
Node wblut.hemesh.HET_MeshGraph.Node.previous
double wblut.hemesh.HET_MeshGraph.Node.x
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_MeshGraph.java