HE_Mesh: wblut.geom.WB_Triangulation2DWithPoints Class Reference
wblut.geom.WB_Triangulation2DWithPoints Class Reference
Public Member Functions
WB_Triangulation2DWithPoints ()
WB_Triangulation2DWithPoints (final int[] T, final int[] E, final WB_CoordCollection P)
WB_Triangulation2DWithPoints (final int[] T, final int[] E, final List<?extends WB_Coord > P)
WB_Triangulation2DWithPoints (final int[] T, final int[] E, final WB_Coord[] P)
WB_Triangulation2DWithPoints (final int[] T, final WB_CoordCollection P)
WB_Triangulation2DWithPoints (final int[] T, final List<?extends WB_Coord > P)
WB_Triangulation2DWithPoints (final int[] T, final WB_Coord[] P)
WB_CoordCollection getPoints ()
Public Member Functions inherited from wblut.geom.WB_Triangulation2D
WB_Triangulation2D ()
WB_Triangulation2D (final int[] T, final int[] E)
WB_Triangulation2D (final int[] T)
int[] getTriangles ()
int[] getEdges ()
int[][] getNeighbors ()
Protected Member Functions
WB_Triangulation2DWithPoints (final WB_Triangulation2D tri)
Private Attributes
WB_CoordCollection _points
Constructor & Destructor Documentation
wblut.geom.WB_Triangulation2DWithPoints.WB_Triangulation2DWithPoints ()
wblut.geom.WB_Triangulation2DWithPoints.WB_Triangulation2DWithPoints (final int[] T, final int[] E, final WB_CoordCollection P)
wblut.geom.WB_Triangulation2DWithPoints.WB_Triangulation2DWithPoints (final int[] T, final int[] E, final List<?extends WB_Coord > P)
Parameters
T
E
P
References wblut.geom.WB_CoordCollection.getCollection().
wblut.geom.WB_Triangulation2DWithPoints.WB_Triangulation2DWithPoints (final int[] T, final int[] E, final WB_Coord[] P)
References wblut.geom.WB_CoordCollection.getCollection().
wblut.geom.WB_Triangulation2DWithPoints.WB_Triangulation2DWithPoints (final int[] T, final WB_CoordCollection P)
Parameters
T
P
wblut.geom.WB_Triangulation2DWithPoints.WB_Triangulation2DWithPoints (final int[] T, final List<?extends WB_Coord > P)
Parameters
T
P
References wblut.geom.WB_CoordCollection.getCollection().
wblut.geom.WB_Triangulation2DWithPoints.WB_Triangulation2DWithPoints (final int[] T, final WB_Coord[] P)
Parameters
T
P
References wblut.geom.WB_CoordCollection.getCollection().
wblut.geom.WB_Triangulation2DWithPoints.WB_Triangulation2DWithPoints (final WB_Triangulation2D tri) protected
Parameters
tri
References wblut.geom.WB_Triangulation2D.getEdges(), and wblut.geom.WB_Triangulation2D.getTriangles().
Member Function Documentation
WB_CoordCollection wblut.geom.WB_Triangulation2DWithPoints.getPoints ()
Returns
References wblut.geom.WB_Triangulation2DWithPoints._points.
Member Data Documentation
WB_CoordCollection wblut.geom.WB_Triangulation2DWithPoints._points private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Triangulation2DWithPoints.java