HE_Mesh: wblut.hemesh.HEC_Capsule Class Reference
wblut.hemesh.HEC_Capsule Class Reference
Public Member Functions
HEC_Capsule ()
HEC_Capsule (final double R, final double H, final int facets, final int steps, final int capfacets)
HEC_Capsule setRadius (final double R)
HEC_Capsule setHeight (final double H)
HEC_Capsule setSteps (final int steps)
HEC_Capsule setFacets (final int facets)
HEC_Capsule setCapFacets (final int facets)
HEC_Capsule setCapFacets (final int topfacets, final int bottomfacets)
HEC_Capsule setCap (final boolean topcap, final boolean bottomcap)
HEC_Capsule setPhase (final double p)
HEC_Capsule align (final WB_Coord direction)
HEC_Capsule align (final WB_Coord origin, final WB_Coord endpoint)
HEC_Capsule align (final WB_Segment segment)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Attributes
double R
double H
int facets
int topcapfacets
int steps
boolean topcap
boolean bottomcap
double phase
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Capsule.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_Capsule.HEC_Capsule ()
Instantiates a new Capsule.
References wblut.geom.WB_Vector.Y, and wblut.hemesh.HEC_Creator.Z.
wblut.hemesh.HEC_Capsule.HEC_Capsule (final double R, final double H, final int facets, final int steps, final int capfacets)
Parameters
R
H
facets
steps
capfacets
References wblut.hemesh.HEC_Capsule.facets, wblut.hemesh.HEC_Capsule.H, wblut.hemesh.HEC_Capsule.R, and wblut.hemesh.HEC_Capsule.steps.
Member Function Documentation
HEC_Capsule wblut.hemesh.HEC_Capsule.align (final WB_Coord direction)
Parameters
direction
Returns
References wblut.hemesh.HEC_Creator.setZAxis().
HEC_Capsule wblut.hemesh.HEC_Capsule.align (final WB_Coord origin, final WB_Coord endpoint)
Parameters
origin
endpoint
Returns
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Point.mulAddMul(), wblut.hemesh.HEC_Creator.setCenter(), wblut.hemesh.HEC_Capsule.setHeight(), and wblut.hemesh.HEC_Creator.setZAxis().
HEC_Capsule wblut.hemesh.HEC_Capsule.align (final WB_Segment segment)
Parameters
segment
Returns
References wblut.geom.WB_Segment.getCenter(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Segment.getLength(), wblut.hemesh.HEC_Creator.setCenter(), wblut.hemesh.HEC_Capsule.setHeight(), and wblut.hemesh.HEC_Creator.setZAxis().
HE_Mesh wblut.hemesh.HEC_Capsule.createBase () protected
References wblut.hemesh.HEC_FromFacelist.createBase(), wblut.hemesh.HEC_Capsule.facets, wblut.hemesh.HEC_Capsule.H, wblut.hemesh.HEC_Capsule.R, wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HEC_FromFacelist.setFaceTextureIds(), wblut.hemesh.HEC_FromFacelist.setVertexUVW(), wblut.hemesh.HEC_FromFacelist.setVertices(), wblut.hemesh.HEC_Capsule.steps, and wblut.hemesh.HEC_Capsule.topcapfacets.
HEC_Capsule wblut.hemesh.HEC_Capsule.setCap (final boolean topcap, final boolean bottomcap)
Set capping options.
Parameters
topcap create top cap?
bottomcap create bottom cap?
Returns
self
References wblut.hemesh.HEC_Capsule.bottomcap, and wblut.hemesh.HEC_Capsule.topcap.
HEC_Capsule wblut.hemesh.HEC_Capsule.setCapFacets (final int facets)
References wblut.hemesh.HEC_Capsule.facets.
HEC_Capsule wblut.hemesh.HEC_Capsule.setCapFacets (final int topfacets, final int bottomfacets)
HEC_Capsule wblut.hemesh.HEC_Capsule.setFacets (final int facets)
Set number of sides.
Parameters
facets number of sides
Returns
self
References wblut.hemesh.HEC_Capsule.facets.
HEC_Capsule wblut.hemesh.HEC_Capsule.setHeight (final double H)
set height.
Parameters
H height
Returns
self
References wblut.hemesh.HEC_Capsule.H.
HEC_Capsule wblut.hemesh.HEC_Capsule.setPhase (final double p)
HEC_Capsule wblut.hemesh.HEC_Capsule.setRadius (final double R)
Set radius.
Parameters
R radius
Returns
self
References wblut.hemesh.HEC_Capsule.R.
HEC_Capsule wblut.hemesh.HEC_Capsule.setSteps (final int steps)
Set vertical divisions.
Parameters
steps vertical divisions
Returns
self
References wblut.hemesh.HEC_Capsule.steps.
Member Data Documentation
boolean wblut.hemesh.HEC_Capsule.bottomcap private
int wblut.hemesh.HEC_Capsule.facets private
Facets.
double wblut.hemesh.HEC_Capsule.H private
Height.
double wblut.hemesh.HEC_Capsule.phase private
double wblut.hemesh.HEC_Capsule.R private
radius.
int wblut.hemesh.HEC_Capsule.steps private
Height steps.
boolean wblut.hemesh.HEC_Capsule.topcap private
int wblut.hemesh.HEC_Capsule.topcapfacets private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_Capsule.java