HE_Mesh: wblut.hemesh.HEM_Kaleidoscope Class Reference
wblut.hemesh.HEM_Kaleidoscope Class Reference
Public Member Functions
HEM_Kaleidoscope ()
HEM_Kaleidoscope setOrigin (final WB_Coord o)
HEM_Kaleidoscope setAxis (final WB_Coord v)
HEM_Kaleidoscope setSymmetry (final int n)
HEM_Kaleidoscope setAngle (final double a)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_Point origin
WB_Vector axis
int n
double angle
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_Kaleidoscope.HEM_Kaleidoscope ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Kaleidoscope.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HEM_Mirror.boundaryPairs, wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HE_Mesh.cleanUnusedElementsByFace(), wblut.geom.WB_Vector.cross(), wblut.hemesh.HE_Mesh.get(), wblut.hemesh.HE_Mesh.getIndex(), wblut.geom.WB_Vector.getOrthoNormal(), wblut.geom.WB_GeometryOp3D.getSqDistanceToLine3D(), wblut.hemesh.HE_Mesh.getVertexWithIndex(), wblut.math.WB_Epsilon.isZeroSq(), wblut.hemesh.HE_Mesh.modify(), wblut.geom.WB_Vector.mulSelf(), wblut.hemesh.HEM_Kaleidoscope.n, wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Mesh.renameSelection(), wblut.geom.WB_Point.rotateAboutAxisSelf(), wblut.geom.WB_Vector.rotateAboutAxisSelf(), wblut.hemesh.HE_Mesh.rotateAboutAxisSelf(), wblut.geom.WB_Vector.rotateAboutOriginSelf(), wblut.hemesh.HE_Mesh.selectAllFaces(), wblut.hemesh.HE_Vertex.set(), wblut.hemesh.HE_Mesh.setFaceInternalLabels(), wblut.hemesh.HEM_Mirror.setPlane(), and wblut.hemesh.HE_Mesh.uncapBoundaryHalfedges().
HE_Mesh wblut.hemesh.HEM_Kaleidoscope.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HEM_Kaleidoscope.applySelf().
HEM_Kaleidoscope wblut.hemesh.HEM_Kaleidoscope.setAngle (final double a)
Parameters
a
Returns
HEM_Kaleidoscope wblut.hemesh.HEM_Kaleidoscope.setAxis (final WB_Coord v)
Parameters
v
Returns
HEM_Kaleidoscope wblut.hemesh.HEM_Kaleidoscope.setOrigin (final WB_Coord o)
Parameters
o
Returns
HEM_Kaleidoscope wblut.hemesh.HEM_Kaleidoscope.setSymmetry (final int n)
Parameters
n
Returns
References wblut.hemesh.HEM_Kaleidoscope.n.
Member Data Documentation
double wblut.hemesh.HEM_Kaleidoscope.angle private
WB_Vector wblut.hemesh.HEM_Kaleidoscope.axis private
int wblut.hemesh.HEM_Kaleidoscope.n private
WB_Point wblut.hemesh.HEM_Kaleidoscope.origin private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Kaleidoscope.java