HE_Mesh: wblut.geom.WB_Sphere Class Reference
wblut.geom.WB_Sphere Class Reference
Public Member Functions
WB_Sphere ()
WB_Sphere (final WB_Coord center, final double radius)
boolean equals (final Object o)
int hashCode ()
WB_Sphere apply (final WB_Transform T)
WB_Sphere get ()
WB_Coord getCenter ()
void setCenter (final WB_Coord c)
double getRadius ()
void setRadius (final double r)
void growSpherebyPoint (final WB_Coord p)
WB_Coord projectToSphere (final WB_Coord v)
boolean contains (final WB_Coord p)
Private Member Functions
int hashCode (final double v)
Private Attributes
WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.geom.WB_Sphere.WB_Sphere ()
References wblut.geom.WB_GeometryFactory3D.createPoint().
wblut.geom.WB_Sphere.WB_Sphere (final WB_Coord center, final double radius)
Instantiates a new WB_Circle.
Parameters
center
radius
References wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.math.WB_Math.fastAbs().
Member Function Documentation
WB_Sphere wblut.geom.WB_Sphere.apply (final WB_Transform T)
References wblut.geom.WB_Point.applyAsPoint(), and wblut.geom.WB_GeometryFactory3D.createSphereWithRadius().
boolean wblut.geom.WB_Sphere.contains (final WB_Coord p)
References wblut.geom.WB_Vector.getSqDistance().
boolean wblut.geom.WB_Sphere.equals (final Object o)
References wblut.geom.WB_Point.equals(), wblut.geom.WB_Sphere.getCenter(), wblut.geom.WB_Sphere.getRadius(), and wblut.math.WB_Epsilon.isEqualAbs().
WB_Sphere wblut.geom.WB_Sphere.get ()
Get copy.
Returns
copy
References wblut.geom.WB_Sphere.WB_Sphere().
WB_Coord wblut.geom.WB_Sphere.getCenter ()
Gets the center.
Returns
the center
double wblut.geom.WB_Sphere.getRadius ()
Gets the radius.
Returns
the radius
void wblut.geom.WB_Sphere.growSpherebyPoint (final WB_Coord p)
Grow sphere to include point.
Parameters
p point to include
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Vector.getSqLength(), wblut.geom.WB_Point.subToVector3D(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
int wblut.geom.WB_Sphere.hashCode ()
References wblut.geom.WB_Point.hashCode().
int wblut.geom.WB_Sphere.hashCode (final double v) private
Parameters
v
Returns
WB_Coord wblut.geom.WB_Sphere.projectToSphere (final WB_Coord v)
Project point to sphere.
Parameters
v the v
Returns
point projected to sphere
References wblut.geom.WB_Point.addMul(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Point.normalizeSelf(), and wblut.geom.WB_Point.sub().
void wblut.geom.WB_Sphere.setCenter (final WB_Coord c)
Sets the center.
Parameters
c the new center
void wblut.geom.WB_Sphere.setRadius (final double r)
Sets the radius.
Parameters
r the new radius
Member Data Documentation
WB_GeometryFactory wblut.geom.WB_Sphere.geometryfactory = new WB_GeometryFactory() private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Sphere.java