HE_Mesh: wblut.geom.WB_Transform Class Reference
wblut.geom.WB_Transform Class Reference
Public Member Functions
WB_Transform ()
WB_Transform (final WB_Transform Trans)
WB_Transform (final WB_Coord sourceOrigin, final WB_Coord sourceDirection, final WB_Coord targetOrigin, final WB_Coord targetDirection)
WB_Transform (final WB_Coord sourceDirection, final WB_Coord targetDirection)
WB_Transform get ()
WB_Transform addTranslate (final WB_Coord v)
WB_Transform addTranslate (final double f, final WB_Coord v)
WB_Transform addScale (final WB_Coord s)
WB_Transform addScale (final double sx, final double sy, final double sz)
WB_Transform addScale (final double s)
WB_Transform addRotateX (final double angle)
WB_Transform addRotateY (final double angle)
WB_Transform addRotateZ (final double angle)
WB_Transform addRotateAboutOrigin (final double angle, final WB_Coord axis)
WB_Transform addRotateAboutAxis (final double angle, final WB_Coord p, final WB_Coord axis)
WB_Transform addRotateAboutAxis2P (final double angle, final WB_Coord p, final WB_Coord q)
WB_Transform addObjectToWorld (final WB_Coord origin, final WB_Coord up, final WB_Coord front)
WB_Transform addReflectX ()
WB_Transform addReflectY ()
WB_Transform addReflectZ ()
WB_Transform addInvert ()
WB_Transform addReflectX (final WB_Coord p)
WB_Transform addReflectY (final WB_Coord p)
WB_Transform addReflectZ (final WB_Coord p)
WB_Transform addInvert (final WB_Coord p)
WB_Transform addReflect (final WB_Plane P)
WB_Transform addShear (final WB_Plane P, final WB_Coord v, final double angle)
WB_Transform addFromCSToCS (final WB_CoordinateSystem3D CS1, final WB_CoordinateSystem3D CS2)
WB_Transform addFromCSToWorld (final WB_CoordinateSystem3D CS)
WB_Transform addFromWorldToCS (final WB_CoordinateSystem3D CS)
WB_Transform addFromCSToParent (final WB_CoordinateSystem3D CS)
WB_Transform addFromParentToCS (final WB_CoordinateSystem3D CS)
void inverse ()
void clear ()
WB_Point applyAsPoint (final WB_Coord p)
void applyAsPointSelf (final WB_MutableCoord p)
void applyAsPointInto (final WB_Coord p, final WB_MutableCoord result)
WB_Point applyAsPoint (final double x, final double y, final double z)
void applyAsPointInto (final double x, final double y, final double z, final WB_MutableCoord result)
WB_Point applyInvAsPoint (final WB_Coord p)
void applyInvAsPointSelf (final WB_MutableCoord p)
void applyInvAsPointInto (final WB_Coord p, final WB_MutableCoord result)
WB_Point applyInvAsPoint (final double x, final double y, final double z)
void applyInvAsPointInto (final double x, final double y, final double z, final WB_MutableCoord result)
WB_Vector applyAsVector (final WB_Coord p)
void applyAsVectorSelf (final WB_MutableCoord p)
void applyAsVectorInto (final WB_Coord p, final WB_MutableCoord result)
WB_Vector applyAsVector (final double x, final double y, final double z)
void applyAsVectorInto (final double x, final double y, final double z, final WB_MutableCoord result)
WB_Vector applyInvAsVector (final WB_Coord p)
void applyInvAsVectorSelf (final WB_MutableCoord v)
void applyInvAsVectorInto (final WB_Coord p, final WB_MutableCoord result)
WB_Vector applyInvAsVector (final double x, final double y, final double z)
void applyInvAsVectorInto (final double x, final double y, final double z, final WB_MutableCoord result)
WB_Vector applyAsNormal (final WB_Coord p)
void applyAsNormalSelf (final WB_MutableCoord n)
void applyAsNormalInto (final WB_Coord n, final WB_MutableCoord result)
WB_Vector applyAsNormal (final double x, final double y, final double z)
void applyAsNormalInto (final double x, final double y, final double z, final WB_MutableCoord result)
WB_Vector applyInvAsNormal (final WB_Coord n)
void applyInvAsNormalSelf (final WB_MutableCoord n)
void applyInvAsNormalInto (final WB_Coord n, final WB_MutableCoord result)
WB_Vector applyInvAsNormal (final double x, final double y, final double z)
void applyInvAsNormalInto (final double x, final double y, final double z, final WB_MutableCoord result)
String toString ()
WB_Vector getEulerAnglesXYZ ()
Private Attributes
double _xt
WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
WB_M44 T
WB_M44 invT
Constructor & Destructor Documentation
wblut.geom.WB_Transform.WB_Transform ()
Instantiates a new WB_Transfrom.
wblut.geom.WB_Transform.WB_Transform (final WB_Transform Trans)
Parameters
Trans
References wblut.math.WB_M44.get(), wblut.geom.WB_Transform.invT, and wblut.geom.WB_Transform.T.
wblut.geom.WB_Transform.WB_Transform (final WB_Coord sourceOrigin, final WB_Coord sourceDirection, final WB_Coord targetOrigin, final WB_Coord targetDirection)
Parameters
sourceOrigin
sourceDirection
targetOrigin
targetDirection
References wblut.geom.WB_Transform.addRotateAboutOrigin(), wblut.geom.WB_Transform.addTranslate(), wblut.geom.WB_GeometryFactory3D.createNormalizedPerpendicularVector(), wblut.geom.WB_GeometryFactory3D.createNormalizedVector(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.geom.WB_Vector.getLength(), wblut.math.WB_Epsilon.isZero(), and wblut.geom.WB_Vector.normalizeSelf().
wblut.geom.WB_Transform.WB_Transform (final WB_Coord sourceDirection, final WB_Coord targetDirection)
Parameters
sourceDirection
targetDirection
References wblut.geom.WB_Transform.addRotateAboutOrigin(), wblut.geom.WB_GeometryFactory3D.createNormalizedPerpendicularVector(), wblut.geom.WB_GeometryFactory3D.createNormalizedVector(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.geom.WB_Vector.getLength(), wblut.math.WB_Epsilon.isZero(), and wblut.geom.WB_Vector.normalizeSelf().
Member Function Documentation
WB_Transform wblut.geom.WB_Transform.addFromCSToCS (final WB_CoordinateSystem3D CS1, final WB_CoordinateSystem3D CS2)
Parameters
CS1
CS2
Returns
References wblut.geom.WB_Transform.addFromCSToWorld(), and wblut.geom.WB_Transform.addFromWorldToCS().
WB_Transform wblut.geom.WB_Transform.addFromCSToParent (final WB_CoordinateSystem3D CS)
Parameters
CS
Returns
References wblut.geom.WB_Transform.addTranslate(), wblut.geom.WB_Vector.dot(), wblut.geom.WB_CoordinateSystem3D.getOrigin(), wblut.geom.WB_CoordinateSystem3D.getX(), wblut.geom.WB_CoordinateSystem3D.getY(), wblut.geom.WB_CoordinateSystem3D.getZ(), wblut.geom.WB_CoordinateSystem3D.isWorld(), wblut.math.WB_M44.mult(), wblut.geom.WB_Point.subSelf(), and wblut.geom.WB_CoordinateSystem3D.WORLD().
WB_Transform wblut.geom.WB_Transform.addFromCSToWorld (final WB_CoordinateSystem3D CS)
Parameters
CS
Returns
References wblut.geom.WB_Transform.addFromCSToParent(), wblut.geom.WB_CoordinateSystem3D.getParent(), and wblut.geom.WB_CoordinateSystem3D.isWorld().
WB_Transform wblut.geom.WB_Transform.addFromParentToCS (final WB_CoordinateSystem3D CS)
Parameters
CS
Returns
References wblut.geom.WB_Transform.addFromCSToParent(), wblut.geom.WB_Transform.invT, wblut.geom.WB_CoordinateSystem3D.isWorld(), wblut.math.WB_M44.mult(), wblut.geom.WB_Transform.T, and wblut.geom.WB_Transform.WB_Transform().
WB_Transform wblut.geom.WB_Transform.addFromWorldToCS (final WB_CoordinateSystem3D CS)
Parameters
CS
Returns
References wblut.geom.WB_Transform.addFromCSToWorld(), wblut.geom.WB_Transform.invT, wblut.math.WB_M44.mult(), wblut.geom.WB_Transform.T, and wblut.geom.WB_Transform.WB_Transform().
WB_Transform wblut.geom.WB_Transform.addInvert ()
Adds the invert.
Returns
References wblut.geom.WB_Transform.addScale().
WB_Transform wblut.geom.WB_Transform.addInvert (final WB_Coord p)
Adds the invert.
Parameters
p the p
Returns
References wblut.geom.WB_Transform.addScale(), and wblut.geom.WB_Transform.addTranslate().
WB_Transform wblut.geom.WB_Transform.addObjectToWorld (final WB_Coord origin, final WB_Coord up, final WB_Coord front)
Add a object-to-world transform.
Parameters
origin object origin in world coordinates
up object up direction in world coordinates
front object front direction in world coordinates
Returns
self
References wblut.geom.WB_Vector.cross(), wblut.math.WB_M44.inverse(), wblut.math.WB_M44.mult(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Transform wblut.geom.WB_Transform.addReflect (final WB_Plane P)
Adds the reflect.
Parameters
P the p
Returns
References wblut.geom.WB_Vector.dot(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Plane.getOrigin(), wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.math.WB_M33.m31, wblut.math.WB_M44.mult(), wblut.geom.WB_Vector.tensor(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Transform wblut.geom.WB_Transform.addReflectX ()
Adds the reflect x.
Returns
References wblut.geom.WB_Transform.addScale().
WB_Transform wblut.geom.WB_Transform.addReflectX (final WB_Coord p)
Adds the reflect x.
Parameters
p the p
Returns
References wblut.geom.WB_Transform.addScale(), and wblut.geom.WB_Transform.addTranslate().
WB_Transform wblut.geom.WB_Transform.addReflectY ()
Adds the reflect y.
Returns
References wblut.geom.WB_Transform.addScale().
WB_Transform wblut.geom.WB_Transform.addReflectY (final WB_Coord p)
Adds the reflect y.
Parameters
p the p
Returns
References wblut.geom.WB_Transform.addScale(), and wblut.geom.WB_Transform.addTranslate().
WB_Transform wblut.geom.WB_Transform.addReflectZ ()
Adds the reflect z.
Returns
References wblut.geom.WB_Transform.addScale().
WB_Transform wblut.geom.WB_Transform.addReflectZ (final WB_Coord p)
Adds the reflect z.
Parameters
p the p
Returns
References wblut.geom.WB_Transform.addScale(), and wblut.geom.WB_Transform.addTranslate().
WB_Transform wblut.geom.WB_Transform.addRotateAboutAxis (final double angle, final WB_Coord p, final WB_Coord axis)
Add rotation about arbitrary axis defined by point and direction.
Parameters
angle angle in radians
p point
axis direction
Returns
self
References wblut.geom.WB_Transform.addRotateAboutOrigin(), and wblut.geom.WB_Transform.addTranslate().
WB_Transform wblut.geom.WB_Transform.addRotateAboutAxis2P (final double angle, final WB_Coord p, final WB_Coord q)
Add rotation about arbitrary axis defiend by two points .
Parameters
angle angle in radians
p first point
q second point
Returns
self
References wblut.geom.WB_Transform.addRotateAboutOrigin(), wblut.geom.WB_Transform.addTranslate(), and wblut.geom.WB_Vector.sub().
WB_Transform wblut.geom.WB_Transform.addRotateAboutOrigin (final double angle, final WB_Coord axis)
Add rotation about arbitrary axis in origin.
Parameters
angle angle in radians
axis WB_Vector
Returns
self
References wblut.math.WB_M44.getTranspose(), wblut.math.WB_M44.mult(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Transform wblut.geom.WB_Transform.addRotateX (final double angle)
Add rotation about X-axis.
Parameters
angle angle in radians
Returns
self
References wblut.math.WB_M44.getTranspose(), and wblut.math.WB_M44.mult().
WB_Transform wblut.geom.WB_Transform.addRotateY (final double angle)
Add rotation about Y-axis.
Parameters
angle angle in radians
Returns
self
References wblut.math.WB_M44.getTranspose(), and wblut.math.WB_M44.mult().
WB_Transform wblut.geom.WB_Transform.addRotateZ (final double angle)
Add rotation about Z-axis.
Parameters
angle angle in radians
Returns
self
References wblut.math.WB_M44.getTranspose(), and wblut.math.WB_M44.mult().
WB_Transform wblut.geom.WB_Transform.addScale (final WB_Coord s)
Add non-uniform scale to transform.
Parameters
s scaling vector
Returns
self
References wblut.math.WB_M44.mult(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Transform wblut.geom.WB_Transform.addScale (final double sx, final double sy, final double sz)
Add non-uniform scale to transform.
Parameters
sx scaling vector
sy scaling vector
sz scaling vector
Returns
self
References wblut.math.WB_M44.mult().
WB_Transform wblut.geom.WB_Transform.addScale (final double s)
Add uniform scale to transform.
Parameters
s scaling point
Returns
self
References wblut.math.WB_M44.mult().
WB_Transform wblut.geom.WB_Transform.addShear (final WB_Plane P, final WB_Coord v, final double angle)
Adds the shear.
Parameters
P the p
v the v
angle the angle
Returns
References wblut.geom.WB_Vector.dot(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Plane.getOrigin(), wblut.math.WB_M33.m11, wblut.math.WB_M33.m21, wblut.math.WB_M33.m31, wblut.math.WB_M44.mult(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Vector.tensor(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Transform wblut.geom.WB_Transform.addTranslate (final WB_Coord v)
Add translation to transform.
Parameters
v vector
Returns
self
References wblut.math.WB_M44.mult(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Transform wblut.geom.WB_Transform.addTranslate (final double f, final WB_Coord v)
Parameters
f
v
Returns
References wblut.math.WB_M44.mult(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Transform.applyAsNormal (final WB_Coord p)
Apply as normal.
Parameters
p
Returns
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Transform.applyAsNormal (final double x, final double y, final double z)
Apply as normal.
Parameters
x
y
z
Returns
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, and wblut.math.WB_M44.m31.
void wblut.geom.WB_Transform.applyAsNormalInto (final WB_Coord n, final WB_MutableCoord result)
Parameters
n
result
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_Transform.applyAsNormalInto (final double x, final double y, final double z, final WB_MutableCoord result)
Parameters
x
y
z
result
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_Transform.applyAsNormalSelf (final WB_MutableCoord n)
Apply transform to normal.
Parameters
n normal
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point wblut.geom.WB_Transform.applyAsPoint (final WB_Coord p)
Apply transform to point.
Parameters
p point
Returns
new WB_XYZ
References wblut.math.WB_Epsilon.isZero(), wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.math.WB_M44.m41, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point wblut.geom.WB_Transform.applyAsPoint (final double x, final double y, final double z)
Apply as point.
Parameters
x
y
z
Returns
References wblut.math.WB_Epsilon.isZero(), wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, and wblut.math.WB_M44.m41.
void wblut.geom.WB_Transform.applyAsPointInto (final WB_Coord p, final WB_MutableCoord result)
Parameters
p
result
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.math.WB_M44.m41, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_Transform.applyAsPointInto (final double x, final double y, final double z, final WB_MutableCoord result)
Parameters
x
y
z
result
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.math.WB_M44.m41, and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_Transform.applyAsPointSelf (final WB_MutableCoord p)
Apply transform to point.
Parameters
p point
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.math.WB_M44.m41, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Transform.applyAsVector (final WB_Coord p)
Apply transform to vector.
Parameters
p vector
Returns
new WB_Vector
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Transform.applyAsVector (final double x, final double y, final double z)
Apply as vector.
Parameters
x
y
z
Returns
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, and wblut.math.WB_M44.m31.
void wblut.geom.WB_Transform.applyAsVectorInto (final WB_Coord p, final WB_MutableCoord result)
Parameters
p
result
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_Transform.applyAsVectorInto (final double x, final double y, final double z, final WB_MutableCoord result)
Parameters
x
y
z
result
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_Transform.applyAsVectorSelf (final WB_MutableCoord p)
Apply transform to vector.
Parameters
p vector
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Transform.applyInvAsNormal (final WB_Coord n)
Parameters
n
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Transform.applyInvAsNormal (final double x, final double y, final double z)
Parameters
x
y
z
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, and wblut.math.WB_M44.m31.
void wblut.geom.WB_Transform.applyInvAsNormalInto (final WB_Coord n, final WB_MutableCoord result)
Parameters
n
result
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_Transform.applyInvAsNormalInto (final double x, final double y, final double z, final WB_MutableCoord result)
Parameters
x
y
z
result
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_Transform.applyInvAsNormalSelf (final WB_MutableCoord n)
Parameters
n
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point wblut.geom.WB_Transform.applyInvAsPoint (final WB_Coord p)
Parameters
p
Returns
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.math.WB_M44.m41, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point wblut.geom.WB_Transform.applyInvAsPoint (final double x, final double y, final double z)
Parameters
x
y
z
Returns
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, and wblut.math.WB_M44.m41.
void wblut.geom.WB_Transform.applyInvAsPointInto (final WB_Coord p, final WB_MutableCoord result)
Parameters
p
result
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.math.WB_M44.m41, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_Transform.applyInvAsPointInto (final double x, final double y, final double z, final WB_MutableCoord result)
Parameters
x
y
z
result
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.math.WB_M44.m41, and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_Transform.applyInvAsPointSelf (final WB_MutableCoord p)
Parameters
p
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.math.WB_M44.m41, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Transform.applyInvAsVector (final WB_Coord p)
Parameters
p
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Transform.applyInvAsVector (final double x, final double y, final double z)
Parameters
x
y
z
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, and wblut.math.WB_M44.m31.
void wblut.geom.WB_Transform.applyInvAsVectorInto (final WB_Coord p, final WB_MutableCoord result)
Parameters
p
result
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_Transform.applyInvAsVectorInto (final double x, final double y, final double z, final WB_MutableCoord result)
Parameters
x
y
z
result
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_Transform.applyInvAsVectorSelf (final WB_MutableCoord v)
Parameters
v
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_Transform.clear ()
Clear transform.
WB_Transform wblut.geom.WB_Transform.get ()
Returns
References wblut.geom.WB_Transform.WB_Transform().
WB_Vector wblut.geom.WB_Transform.getEulerAnglesXYZ ()
Get the Euler angles corresponding to the rotational part of the transformation. Only works if the transformation is rotation and translation, nothing else!
Returns
References wblut.geom.WB_GeometryFactory3D.createVector(), wblut.math.WB_Epsilon.isEqualAbs(), wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, and wblut.math.WB_M44.m31.
void wblut.geom.WB_Transform.inverse ()
Invert transform.
References wblut.geom.WB_Transform.invT, and wblut.geom.WB_Transform.T.
String wblut.geom.WB_Transform.toString ()
References wblut.math.WB_M44.m11, wblut.math.WB_M44.m21, wblut.math.WB_M44.m31, and wblut.math.WB_M44.m41.
Member Data Documentation
double wblut.geom.WB_Transform._xt private
WB_GeometryFactory wblut.geom.WB_Transform.geometryfactory = new WB_GeometryFactory() private
WB_M44 wblut.geom.WB_Transform.invT private
Inverse transform matrix.
WB_M44 wblut.geom.WB_Transform.T private
Transform matrix.
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Transform.java