HE_Mesh: wblut.hemesh.HEC_IsoSkin.Substrate Class Reference
wblut.hemesh.HEC_IsoSkin.Substrate Class Reference
Classes
class VertexRemap
Private Member Functions
void createGrid ()
void polygonise (final double isolevel, final boolean dummyrun, final HE_Mesh mesh)
void getPolygons2D (final Cell cell, final double isolevel, final boolean dummyrun, final HE_Mesh mesh)
void getPolygons3D (final Cell cell, final double isolevel, final boolean dummyrun, final HE_Mesh mesh)
int classifyCell2D (final Cell cell, final double isolevel)
int classifyCell3D (final Cell cell, final double isolevel)
HE_Vertex getIsoVertex2D (final int isopointindex, final Cell cell, final double isolevel, final boolean dummyrun, final HE_Mesh mesh)
HE_Vertex getIsoVertex3D (final int isopointindex, final Cell cell, final double isolevel, final boolean dummyrun, final HE_Mesh mesh)
HE_Vertex edge (final double isolevel, final int i, final int layeri, final int j, final int layerj, final boolean dummyrun, final HE_Mesh mesh)
HE_Vertex vertex (final int layer, final int i, final HE_Mesh mesh)
WB_Point interp (final double isolevel, final WB_Coord p1, final WB_Coord p2, final double valp1, final double valp2)
long edgeindex (final int layeri, final int i, final int layerj, final int j)
int vertexindex (final int layeri, final int i)
void setvalues (final double isolevel)
void snapvertices ()
void resetvalues ()
void setCells3D (final Cell[][] cells3d)
Private Attributes
IntObjectHashMap< VertexRemap > vertexremaps
int numberOfLayers
double[][] values
Cell[][] cells3D
Cell[][] cells2D
WB_Coord[][] gridpositions
LongObjectHashMap< HE_Vertex > edges
HE_Mesh substrate
int numberOfVertices
int totalNumberOfVertices
int[] digits
LongIntHashMap keysToIndex
IntObjectHashMap< HE_Vertex > vertices
double gamma
Member Function Documentation
int wblut.hemesh.HEC_IsoSkin.Substrate.classifyCell2D (final Cell cell, final double isolevel) private
References wblut.hemesh.HEC_IsoSkin.Cell.getCornerIndices(), wblut.hemesh.HEC_IsoSkin.isolevel, and wblut.hemesh.HEC_IsoSkin.Cell.layer.
int wblut.hemesh.HEC_IsoSkin.Substrate.classifyCell3D (final Cell cell, final double isolevel) private
References wblut.hemesh.HEC_IsoSkin.Cell.getCornerIndices(), wblut.hemesh.HEC_IsoSkin.isolevel, and wblut.hemesh.HEC_IsoSkin.Cell.layer.
void wblut.hemesh.HEC_IsoSkin.Substrate.createGrid () private
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Element.getKey(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_Mesh.heItr(), wblut.hemesh.HE_Halfedge.isInnerBoundary(), wblut.hemesh.HEC_IsoSkin.Cell.layer, wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HEC_IsoSkin.Substrate.numberOfLayers, and wblut.hemesh.HEC_IsoSkin.Substrate.setCells3D().
HE_Vertex wblut.hemesh.HEC_IsoSkin.Substrate.edge (final double isolevel, final int i, final int layeri, final int j, final int layerj, final boolean dummyrun, final HE_Mesh mesh) private
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HEC_IsoSkin.Substrate.edgeindex(), wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.hemesh.HEC_IsoSkin.Substrate.interp(), wblut.hemesh.HEC_IsoSkin.Substrate.vertex(), and wblut.hemesh.HEC_IsoSkin.Substrate.vertexindex().
long wblut.hemesh.HEC_IsoSkin.Substrate.edgeindex (final int layeri, final int i, final int layerj, final int j) private
HE_Vertex wblut.hemesh.HEC_IsoSkin.Substrate.getIsoVertex2D (final int isopointindex, final Cell cell, final double isolevel, final boolean dummyrun, final HE_Mesh mesh) private
References wblut.hemesh.HEC_IsoSkin.Substrate.edge(), wblut.hemesh.HEC_IsoSkin.Cell.getCornerIndices(), wblut.hemesh.HEC_IsoSkin.Cell.layer, and wblut.hemesh.HEC_IsoSkin.Substrate.vertex().
HE_Vertex wblut.hemesh.HEC_IsoSkin.Substrate.getIsoVertex3D (final int isopointindex, final Cell cell, final double isolevel, final boolean dummyrun, final HE_Mesh mesh) private
References wblut.hemesh.HEC_IsoSkin.Substrate.edge(), wblut.hemesh.HEC_IsoSkin.Cell.getCornerIndices(), wblut.hemesh.HEC_IsoSkin.Cell.layer, and wblut.hemesh.HEC_IsoSkin.Substrate.vertex().
void wblut.hemesh.HEC_IsoSkin.Substrate.getPolygons2D (final Cell cell, final double isolevel, final boolean dummyrun, final HE_Mesh mesh) private
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HEC_IsoSkin.Substrate.classifyCell2D(), wblut.hemesh.HE_Face.getFaceArea(), wblut.hemesh.HEC_IsoSkin.Substrate.getIsoVertex2D(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setVertex().
void wblut.hemesh.HEC_IsoSkin.Substrate.getPolygons3D (final Cell cell, final double isolevel, final boolean dummyrun, final HE_Mesh mesh) private
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HEC_IsoSkin.Substrate.classifyCell3D(), wblut.hemesh.HE_Face.getFaceArea(), wblut.hemesh.HEC_IsoSkin.Substrate.getIsoVertex3D(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setVertex().
WB_Point wblut.hemesh.HEC_IsoSkin.Substrate.interp (final double isolevel, final WB_Coord p1, final WB_Coord p2, final double valp1, final double valp2) private
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.hemesh.HEC_IsoSkin.Substrate.polygonise (final double isolevel, final boolean dummyrun, final HE_Mesh mesh) private
References wblut.hemesh.HEC_IsoSkin.Substrate.getPolygons2D(), wblut.hemesh.HEC_IsoSkin.Substrate.getPolygons3D(), and wblut.hemesh.HEC_IsoSkin.Substrate.numberOfLayers.
void wblut.hemesh.HEC_IsoSkin.Substrate.resetvalues () private
void wblut.hemesh.HEC_IsoSkin.Substrate.setCells3D (final Cell cells3d[][]) private
Parameters
cells3d the cells3D to set
void wblut.hemesh.HEC_IsoSkin.Substrate.setvalues (final double isolevel) private
References wblut.hemesh.HEC_IsoSkin.isolevel, and wblut.hemesh.HE_Vertex.set().
void wblut.hemesh.HEC_IsoSkin.Substrate.snapvertices () private
References wblut.hemesh.HE_Vertex.set().
HE_Vertex wblut.hemesh.HEC_IsoSkin.Substrate.vertex (final int layer, final int i, final HE_Mesh mesh) private
References wblut.hemesh.HE_Mesh.add(), and wblut.hemesh.HEC_IsoSkin.Substrate.vertexindex().
int wblut.hemesh.HEC_IsoSkin.Substrate.vertexindex (final int layeri, final int i) private
Member Data Documentation
Cell [][] wblut.hemesh.HEC_IsoSkin.Substrate.cells2D private
Cell [][] wblut.hemesh.HEC_IsoSkin.Substrate.cells3D private
int [] wblut.hemesh.HEC_IsoSkin.Substrate.digits private
LongObjectHashMap<HE_Vertex> wblut.hemesh.HEC_IsoSkin.Substrate.edges private
double wblut.hemesh.HEC_IsoSkin.Substrate.gamma private
WB_Coord [][] wblut.hemesh.HEC_IsoSkin.Substrate.gridpositions private
LongIntHashMap wblut.hemesh.HEC_IsoSkin.Substrate.keysToIndex private
int wblut.hemesh.HEC_IsoSkin.Substrate.numberOfLayers private
int wblut.hemesh.HEC_IsoSkin.Substrate.numberOfVertices private
HE_Mesh wblut.hemesh.HEC_IsoSkin.Substrate.substrate private
int wblut.hemesh.HEC_IsoSkin.Substrate.totalNumberOfVertices private
double [][] wblut.hemesh.HEC_IsoSkin.Substrate.values private
IntObjectHashMap<VertexRemap> wblut.hemesh.HEC_IsoSkin.Substrate.vertexremaps private
IntObjectHashMap<HE_Vertex> wblut.hemesh.HEC_IsoSkin.Substrate.vertices private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_IsoSkin.java