HE_Mesh: wblut.hemesh.HEC_ConvexHull Class Reference
wblut.hemesh.HEC_ConvexHull Class Reference
Public Member Functions
HEC_ConvexHull ()
HEC_ConvexHull setPoints (final WB_Coord[] points)
HEC_ConvexHull setPoints (final Collection<?extends WB_Coord > points)
HEC_ConvexHull setPointsFromVertices (final Collection<?extends WB_Coord > points)
HEC_ConvexHull setPoints (final double[][] points)
HEC_ConvexHull setPoints (final float[][] points)
HEC_ConvexHull setPoints (final int[][] points)
HEC_ConvexHull setN (final int N)
HE_Mesh createBase ()
HE_Mesh createWithQuickHull ()
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Public Attributes
Map< Long, Integer > vertexToPointIndex
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Private Attributes
WB_Coord[] points
int numberOfPoints
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Creates the convex hull of a collection of points.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_ConvexHull.HEC_ConvexHull ()
Instantiates a new HEC_ConvexHull.
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_ConvexHull.createBase ()
References wblut.hemesh.HEC_ConvexHull.createWithQuickHull().
HE_Mesh wblut.hemesh.HEC_ConvexHull.createWithQuickHull ()
Returns
References wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HE_Mesh.cleanUnusedElementsByFace(), wblut.hemesh.HEC_FromFacelist.createBase(), wblut.hemesh.HEC_FromFacelist.setCheckNormals(), wblut.hemesh.HEC_FromFacelist.setCleanUnused(), wblut.hemesh.HEC_FromFacelist.setDuplicate(), wblut.hemesh.HEC_FromFacelist.setVertices(), and wblut.hemesh.HE_Mesh.vItr().
HEC_ConvexHull wblut.hemesh.HEC_ConvexHull.setN (final int N)
Set number of points.
Parameters
N number of points
Returns
self
HEC_ConvexHull wblut.hemesh.HEC_ConvexHull.setPoints (final WB_Coord[] points)
Set points that define vertices.
Parameters
points array of vertex positions
Returns
self
HEC_ConvexHull wblut.hemesh.HEC_ConvexHull.setPoints (final Collection<?extends WB_Coord > points)
Set points that define vertices.
Parameters
points any Collection of vertex positions
Returns
self
HEC_ConvexHull wblut.hemesh.HEC_ConvexHull.setPoints (final double points[][])
Set points that define vertices.
Parameters
points 2D array of double of vertex positions
Returns
self
HEC_ConvexHull wblut.hemesh.HEC_ConvexHull.setPoints (final float points[][])
Set points that define vertices.
Parameters
points 2D array of float of vertex positions
Returns
self
HEC_ConvexHull wblut.hemesh.HEC_ConvexHull.setPoints (final int points[][])
Set points that define vertices.
Parameters
points 2D array of float of vertex positions
Returns
self
HEC_ConvexHull wblut.hemesh.HEC_ConvexHull.setPointsFromVertices (final Collection<?extends WB_Coord > points)
Set points that define vertices.
Parameters
points any Collection of vertex positions
Returns
self
Member Data Documentation
int wblut.hemesh.HEC_ConvexHull.numberOfPoints private
Number of points.
WB_Coord [] wblut.hemesh.HEC_ConvexHull.points private
Points.
Map<Long, Integer> wblut.hemesh.HEC_ConvexHull.vertexToPointIndex
The vertex to point index.
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_ConvexHull.java