HE_Mesh: wblut.math.WB_PNoise Class Reference
wblut.math.WB_PNoise Class Reference
Public Member Functions
WB_PNoise ()
WB_PNoise (final long seed)
void setSeed (final long seed)
double value1D (final double x)
double value2D (final double x, final double y)
double value3D (double x, double y, double z)
WB_PNoise setDetail (final int lod)
WB_PNoise setDetail (final int lod, final double falloff)
double value4D (final double x, final double y, final double z, final double w)
void setScale (final double sx)
void setScale (final double sx, final double sy)
void setScale (final double sx, final double sy, final double sz)
void setScale (final double sx, final double sy, final double sz, final double sw)
Public Member Functions inherited from wblut.math.WB_Noise
void setSeed (long seed)
double value1D (double x)
double value2D (double x, double y)
double value4D (double x, double y, double z, double w)
void setScale (double sx)
void setScale (double sx, double sy)
void setScale (double sx, double sy, double sz)
void setScale (double sx, double sy, double sz, double sw)
Static Protected Attributes
static final double cosLUT []
static final double SINCOS_PRECISION = 0.05
static final int SINCOS_LENGTH = (int) (360.0 / SINCOS_PRECISION)
Private Member Functions
double noise_fsc (final double i)
Private Attributes
double sx
Constructor & Destructor Documentation
wblut.math.WB_PNoise.WB_PNoise ()
wblut.math.WB_PNoise.WB_PNoise (final long seed)
Parameters
seed
References wblut.math.WB_PNoise.setSeed().
Member Function Documentation
double wblut.math.WB_PNoise.noise_fsc (final double i) private
Parameters
i
Returns
WB_PNoise wblut.math.WB_PNoise.setDetail (final int lod)
Parameters
lod
Returns
WB_PNoise wblut.math.WB_PNoise.setDetail (final int lod, final double falloff)
Parameters
lod
falloff
Returns
void wblut.math.WB_PNoise.setScale (final double sx)
References wblut.math.WB_PNoise.sx.
void wblut.math.WB_PNoise.setScale (final double sx, final double sy)
References wblut.math.WB_PNoise.sx.
void wblut.math.WB_PNoise.setScale (final double sx, final double sy, final double sz)
References wblut.math.WB_PNoise.sx.
void wblut.math.WB_PNoise.setScale (final double sx, final double sy, final double sz, final double sw)
References wblut.math.WB_PNoise.sx.
void wblut.math.WB_PNoise.setSeed (final long seed)
double wblut.math.WB_PNoise.value1D (final double x)
References wblut.math.WB_PNoise.value3D().
double wblut.math.WB_PNoise.value2D (final double x, final double y)
References wblut.math.WB_PNoise.value3D().
double wblut.math.WB_PNoise.value3D (double x, double y, double z)
Parameters
x
y
z
Returns
Implements wblut.math.WB_Noise.
References wblut.math.WB_MTRandom.nextDouble(), wblut.math.WB_PNoise.noise_fsc(), and wblut.math.WB_PNoise.SINCOS_LENGTH.
double wblut.math.WB_PNoise.value4D (final double x, final double y, final double z, final double w)
Member Data Documentation
final double wblut.math.WB_PNoise.cosLUT[] static protected
final int wblut.math.WB_PNoise.SINCOS_LENGTH = (int) (360.0 / SINCOS_PRECISION) static protected
final double wblut.math.WB_PNoise.SINCOS_PRECISION = 0.05 static protected
double wblut.math.WB_PNoise.sx private
The documentation for this class was generated from the following file:
src/math/wblut/math/WB_PNoise.java