HE_Mesh: wblut.geom.WB_Frame.WB_FrameNode Class Reference
wblut.geom.WB_Frame.WB_FrameNode Class Reference
Public Member Functions
WB_FrameNode (final WB_Coord pos, final int id, final double v)
boolean addStrut (final WB_FrameStrut strut)
boolean removeStrut (final WB_FrameStrut strut)
ArrayList< WB_FrameStrut > getStruts ()
ArrayList< WB_FrameNode > getNeighbors ()
int getIndex ()
double findSmallestSpan ()
double findSmallestSpanAroundStrut (final WB_FrameStrut strut)
double findSmallestSpanAroundStrut (final int i)
double findShortestStrut ()
int getOrder ()
double getValue ()
void setValue (final double v)
WB_FrameStrut getStrut (final int index)
void removeStrut (final int index)
WB_FrameNode getNeighbor (final int index)
WB_Point toPoint ()
Public Member Functions inherited from wblut.geom.WB_Point
WB_Point ()
WB_Point (final double x, final double y)
WB_Point (final double x, final double y, final double z)
WB_Point (final double[] x)
WB_Point (final double[] fromPoint, final double[] toPoint)
WB_Point (final WB_Coord v)
WB_Vector subToVector3D (final double x, final double y, final double z)
WB_Vector subToVector3D (final WB_Coord p)
WB_Vector subToVector2D (final double x, final double y, final double z)
WB_Vector subToVector2D (final WB_Coord p)
WB_Point add (final double...x)
WB_Point add (final WB_Coord p)
WB_Point sub (final double...x)
WB_Point sub (final WB_Coord p)
WB_Point mul (final double f)
WB_Point div (final double f)
WB_Point addMul (final double f, final double...x)
WB_Point addMul (final double f, final WB_Coord p)
WB_Point mulAddMul (final double f, final double g, final WB_Coord p)
WB_Point mulAddMul (final double f, final double g, final double...x)
WB_Point cross (final WB_Coord p)
WB_M33 tensor (final WB_Coord v)
double scalarTriple (final WB_Coord v, final WB_Coord w)
WB_Point addSelf (final WB_Coord p)
WB_Point subSelf (final double...x)
WB_Point subSelf (final WB_Coord v)
WB_Point mulSelf (final double f)
WB_Point divSelf (final double f)
WB_Point addMulSelf (final double f, final double...x)
WB_Point addMulSelf (final double f, final WB_Coord p)
WB_Point addSelf (final double...x)
WB_Point addSelf (final double x, final double y, final double z)
WB_Point mulAddMulSelf (final double f, final double g, final double...x)
WB_Point mulAddMulSelf (final double f, final double g, final WB_Coord p)
WB_Point crossSelf (final WB_Coord p)
double normalizeSelf ()
WB_Point trimSelf (final double d)
WB_Point apply2D (final WB_Transform2D T)
WB_Point applyAsPoint2D (final WB_Transform2D T)
WB_Point applyAsVector2D (final WB_Transform2D T)
WB_Point applyAsNormal2D (final WB_Transform2D T)
void apply2DInto (final WB_MutableCoord result, final WB_Transform2D T)
void applyAsPoint2DInto (final WB_MutableCoord result, final WB_Transform2D T)
void applyAsVector2DInto (final WB_MutableCoord result, final WB_Transform2D T)
void applyAsNormal2DInto (final WB_MutableCoord result, final WB_Transform2D T)
WB_Coord translate2D (final double px, final double py)
void translate2DInto (final WB_MutableCoord result, final double px, final double py)
WB_Coord translate2D (final WB_Coord p)
void translate2DInto (final WB_MutableCoord result, final WB_Coord p)
WB_Point rotateAboutPoint2D (final double angle, final double px, final double py)
void rotateAboutPoint2DInto (final WB_MutableCoord result, final double angle, final double px, final double py)
WB_Point rotateAboutPoint2D (final double angle, final WB_Coord p)
void rotateAboutPoint2DInto (final WB_MutableCoord result, final double angle, final WB_Coord p)
WB_Point rotateAboutOrigin2D (final double angle)
void rotateAboutOrigin2DInto (final WB_MutableCoord result, final double angle)
WB_Point scale2D (final double f)
void scale2DInto (final WB_MutableCoord result, final double f)
WB_Point scale2D (final double fx, final double fy)
void scale2DInto (final WB_MutableCoord result, final double fx, final double fy)
WB_Point apply2DSelf (final WB_Transform2D T)
WB_Point applyAsPoint2DSelf (final WB_Transform2D T)
WB_Point applyAsVector2DSelf (final WB_Transform2D T)
WB_Point applyAsNormal2DSelf (final WB_Transform2D T)
WB_Coord translate2DSelf (final double px, final double py)
WB_Coord translate2DSelf (final WB_Coord p)
WB_Point rotateAboutPoint2DSelf (final double angle, final double px, final double py)
WB_Point rotateAboutPoint2DSelf (final double angle, final WB_Coord p)
WB_Point rotateAboutOrigin2DSelf (final double angle)
WB_Point scale2DSelf (final double f)
WB_Point scale2DSelf (final double fx, final double fy)
WB_Point apply (final WB_Transform T)
WB_Point applyAsPoint (final WB_Transform T)
WB_Point applyAsNormal (final WB_Transform T)
WB_Point applyAsVector (final WB_Transform T)
void applyInto (final WB_MutableCoord result, final WB_Transform T)
void applyAsPointInto (final WB_MutableCoord result, final WB_Transform T)
void applyAsNormalInto (final WB_MutableCoord result, final WB_Transform T)
void applyAsVectorInto (final WB_MutableCoord result, final WB_Transform T)
WB_Coord translate (final double px, final double py, final double pz)
WB_Coord translateInto (final WB_MutableCoord result, final double px, final double py, final double pz)
WB_Coord translate (final WB_Coord p)
WB_Coord translateInto (final WB_MutableCoord result, final WB_Coord p)
WB_Point rotateAboutAxis2P (final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
void rotateAboutAxis2PInto (final WB_MutableCoord result, final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
WB_Point rotateAboutAxis2P (final double angle, final WB_Coord p1, final WB_Coord p2)
void rotateAboutAxis2PInto (final WB_MutableCoord result, final double angle, final WB_Coord p1, final WB_Coord p2)
WB_Point rotateAboutAxis (final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
void rotateAboutAxisInto (final WB_MutableCoord result, final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
WB_Point rotateAboutAxis (final double angle, final WB_Coord p, final WB_Coord a)
void rotateAboutAxisInto (final WB_MutableCoord result, final double angle, final WB_Coord p, final WB_Coord a)
WB_Point rotateAboutOrigin (final double angle, final double x, final double y, final double z)
void rotateAboutOriginInto (final WB_MutableCoord result, final double angle, final double x, final double y, final double z)
WB_Point rotateAboutOrigin (final double angle, final WB_Coord a)
void rotateAboutOriginInto (final WB_MutableCoord result, final double angle, final WB_Coord v)
WB_Point scale (final double f)
void scaleInto (final WB_MutableCoord result, final double f)
WB_Point scale (final double fx, final double fy, final double fz)
void scaleInto (final WB_MutableCoord result, final double fx, final double fy, final double fz)
WB_Point applySelf (final WB_Transform T)
WB_Point applyAsPointSelf (final WB_Transform T)
WB_Vector applyAsVectorSelf (final WB_Transform T)
WB_Vector applyAsNormalSelf (final WB_Transform T)
WB_Coord translateSelf (final double px, final double py, final double pz)
WB_Coord translateSelf (final WB_Coord p)
WB_Point rotateAboutAxis2PSelf (final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
WB_Point rotateAboutAxis2PSelf (final double angle, final WB_Coord p1, final WB_Coord p2)
WB_Point rotateAboutAxisSelf (final double angle, final WB_Coord p, final WB_Coord a)
WB_Point rotateAboutAxisSelf (final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
WB_Point rotateAboutOriginSelf (final double angle, final double x, final double y, final double z)
WB_Point rotateAboutOriginSelf (final double angle, final WB_Coord a)
WB_Point scaleSelf (final double f)
WB_Point scaleSelf (final double fx, final double fy, final double fz)
void invert ()
double[] coords ()
WB_Point copy ()
boolean smallerThan (final WB_Coord otherXYZ)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
double wd ()
float wf ()
double getd (final int i)
float getf (final int i)
Public Member Functions inherited from wblut.geom.WB_Vector
WB_Vector ()
WB_Vector (final double x, final double y)
WB_Vector (final double x, final double y, final double z)
WB_Vector (final double[] x)
WB_Vector (final double[] fromPoint, final double[] toPoint)
WB_Vector (final WB_Coord v)
WB_Vector (final WB_Coord fromPoint, final WB_Coord toPoint)
WB_Vector add (final double...x)
WB_Vector add (final WB_Coord p)
WB_Vector sub (final double...x)
WB_Vector sub (final WB_Coord p)
WB_Vector mul (final double f)
WB_Vector div (final double f)
WB_Vector addMul (final double f, final double...x)
WB_Vector addMul (final double f, final WB_Coord p)
WB_Vector mulAddMul (final double f, final double g, final WB_Coord p)
WB_Vector mulAddMul (final double f, final double g, final double...x)
void addInto (final WB_MutableCoord result, final double...x)
void addInto (final WB_MutableCoord result, final WB_Coord p)
void subInto (final WB_MutableCoord result, final double...x)
void subInto (final WB_MutableCoord result, final WB_Coord p)
void mulInto (final WB_MutableCoord result, final double f)
void divInto (final WB_MutableCoord result, final double f)
void addMulInto (final WB_MutableCoord result, final double f, final double...x)
void addMulInto (final WB_MutableCoord result, final double f, final WB_Coord p)
void mulAddMulInto (final WB_MutableCoord result, final double f, final double g, final WB_Coord p)
void mulAddMulInto (final WB_MutableCoord result, final double f, final double g, final double...x)
double dot2D (final WB_Coord p)
double absDot2D (final WB_Coord p)
double dot (final WB_Coord p)
double absDot (final WB_Coord p)
WB_Vector cross (final WB_Coord p)
void crossInto (final WB_MutableCoord result, final WB_Coord p)
WB_M33 tensor (final WB_Coord v)
double scalarTriple (final WB_Coord v, final WB_Coord w)
WB_Vector addSelf (final WB_Coord p)
WB_Vector subSelf (final double...x)
WB_Vector subSelf (final WB_Coord v)
WB_Vector mulSelf (final double f)
WB_Vector divSelf (final double f)
WB_Vector addMulSelf (final double f, final double...x)
WB_Vector addMulSelf (final double f, final WB_Coord p)
WB_Vector addSelf (final double...x)
WB_Vector addSelf (final double x, final double y, final double z)
WB_Vector mulAddMulSelf (final double f, final double g, final double...x)
WB_Vector mulAddMulSelf (final double f, final double g, final WB_Coord p)
WB_Vector crossSelf (final WB_Coord p)
double normalizeSelf ()
WB_Vector trimSelf (final double d)
WB_Vector apply2D (final WB_Transform2D T)
WB_Point applyAsPoint2D (final WB_Transform2D T)
WB_Vector applyAsVector2D (final WB_Transform2D T)
WB_Vector applyAsNormal2D (final WB_Transform2D T)
void apply2DInto (final WB_MutableCoord result, final WB_Transform2D T)
void applyAsPoint2DInto (final WB_MutableCoord result, final WB_Transform2D T)
void applyAsVector2DInto (final WB_MutableCoord result, final WB_Transform2D T)
void applyAsNormal2DInto (final WB_MutableCoord result, final WB_Transform2D T)
WB_Coord translate2D (final double px, final double py)
void translate2DInto (final WB_MutableCoord result, final double px, final double py)
WB_Coord translate2D (final WB_Coord p)
void translate2DInto (final WB_MutableCoord result, final WB_Coord p)
WB_Vector rotateAboutPoint2D (final double angle, final double px, final double py)
void rotateAboutPoint2DInto (final WB_MutableCoord result, final double angle, final double px, final double py)
WB_Vector rotateAboutPoint2D (final double angle, final WB_Coord p)
void rotateAboutPoint2DInto (final WB_MutableCoord result, final double angle, final WB_Coord p)
WB_Vector rotateAboutOrigin2D (final double angle)
void rotateAboutOrigin2DInto (final WB_MutableCoord result, final double angle)
WB_Vector scale2D (final double f)
void scale2DInto (final WB_MutableCoord result, final double f)
WB_Vector scale2D (final double fx, final double fy)
void scale2DInto (final WB_MutableCoord result, final double fx, final double fy)
WB_Vector apply2DSelf (final WB_Transform2D T)
WB_Vector applyAsPoint2DSelf (final WB_Transform2D T)
WB_Vector applyAsVector2DSelf (final WB_Transform2D T)
WB_Vector applyAsNormal2DSelf (final WB_Transform2D T)
WB_Coord translate2DSelf (final double px, final double py)
WB_Coord translate2DSelf (final WB_Coord p)
WB_Vector rotateAboutPoint2DSelf (final double angle, final double px, final double py)
WB_Vector rotateAboutPoint2DSelf (final double angle, final WB_Coord p)
WB_Vector rotateAboutOrigin2DSelf (final double angle)
WB_Vector scale2DSelf (final double f)
WB_Vector scale2DSelf (final double fx, final double fy)
WB_Vector apply (final WB_Transform T)
WB_Point applyAsPoint (final WB_Transform T)
WB_Vector applyAsNormal (final WB_Transform T)
WB_Vector applyAsVector (final WB_Transform T)
void applyInto (final WB_MutableCoord result, final WB_Transform T)
void applyAsPointInto (final WB_MutableCoord result, final WB_Transform T)
void applyAsNormalInto (final WB_MutableCoord result, final WB_Transform T)
void applyAsVectorInto (final WB_MutableCoord result, final WB_Transform T)
WB_Coord translate (final double px, final double py, final double pz)
WB_Coord translateInto (final WB_MutableCoord result, final double px, final double py, final double pz)
WB_Coord translate (final WB_Coord p)
WB_Coord translateInto (final WB_MutableCoord result, final WB_Coord p)
WB_Vector rotateAboutAxis2P (final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
void rotateAboutAxis2PInto (final WB_MutableCoord result, final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
WB_Vector rotateAboutAxis2P (final double angle, final WB_Coord p1, final WB_Coord p2)
void rotateAboutAxis2PInto (final WB_MutableCoord result, final double angle, final WB_Coord p1, final WB_Coord p2)
WB_Vector rotateAboutAxis (final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
void rotateAboutAxisInto (final WB_MutableCoord result, final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
WB_Vector rotateAboutAxis (final double angle, final WB_Coord p, final WB_Coord a)
void rotateAboutAxisInto (final WB_MutableCoord result, final double angle, final WB_Coord p, final WB_Coord a)
WB_Vector rotateAboutOrigin (final double angle, final double x, final double y, final double z)
void rotateAboutOriginInto (final WB_MutableCoord result, final double angle, final double x, final double y, final double z)
WB_Vector rotateAboutOrigin (final double angle, final WB_Coord a)
void rotateAboutOriginInto (final WB_MutableCoord result, final double angle, final WB_Coord v)
WB_Vector scale (final double f)
void scaleInto (final WB_MutableCoord result, final double f)
WB_Vector scale (final double fx, final double fy, final double fz)
void scaleInto (final WB_MutableCoord result, final double fx, final double fy, final double fz)
WB_Vector applySelf (final WB_Transform T)
WB_Vector applyAsPointSelf (final WB_Transform T)
WB_Vector applyAsVectorSelf (final WB_Transform T)
WB_Vector applyAsNormalSelf (final WB_Transform T)
WB_Coord translateSelf (final double px, final double py, final double pz)
WB_Coord translateSelf (final WB_Coord p)
WB_Vector rotateAboutAxis2PSelf (final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
WB_Vector rotateAboutAxis2PSelf (final double angle, final WB_Coord p1, final WB_Coord p2)
WB_Vector rotateAboutAxisSelf (final double angle, final WB_Coord p, final WB_Coord a)
WB_Vector rotateAboutAxisSelf (final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
WB_Vector rotateAboutOriginSelf (final double angle, final double x, final double y, final double z)
WB_Vector rotateAboutOriginSelf (final double angle, final WB_Coord a)
WB_Vector scaleSelf (final double f)
WB_Vector scaleSelf (final double fx, final double fy, final double fz)
void invert ()
double[] coords ()
WB_Vector copy ()
double getDistance2D (final WB_Coord p)
double getSqDistance2D (final WB_Coord p)
double getLength2D ()
double getSqLength2D ()
double getHeading2D ()
WB_Vector getOrthoNormal2D ()
boolean isCollinear2D (final WB_Coord p, final WB_Coord q)
boolean isParallel2D (final WB_Coord p)
boolean isParallel2D (final WB_Coord p, final double t)
boolean isParallelNorm2D (final WB_Coord p)
boolean isParallelNorm2D (final WB_Coord p, final double t)
boolean isOrthogonal2D (final WB_Coord p)
boolean isOrthogonal2D (final WB_Coord p, final double t)
boolean isOrthogonalNorm2D (final WB_Coord p)
boolean isOrthogonalNorm2D (final WB_Coord p, final double t)
double getDistance3D (final WB_Coord p)
double getDistance (final WB_Coord p)
double getSqDistance3D (final WB_Coord p)
double getSqDistance (final WB_Coord p)
double getLength3D ()
double getLength ()
double getSqLength3D ()
double getSqLength ()
double getAngle (final WB_Coord p)
double getAngleNorm (final WB_Coord p)
WB_Vector getOrthoNormal3D ()
WB_Vector getOrthoNormal ()
boolean isCollinear (final WB_Coord p, final WB_Coord q)
boolean isParallel (final WB_Coord p)
boolean isParallel (final WB_Coord p, final double t)
boolean isParallelNorm (final WB_Coord p)
boolean isParallelNorm (final WB_Coord p, final double t)
boolean isOrthogonal (final WB_Coord p)
boolean isOrthogonal (final WB_Coord p, final double t)
boolean isOrthogonalNorm (final WB_Coord p)
boolean isOrthogonalNorm (final WB_Coord p, final double t)
boolean isZero ()
boolean smallerThan (final WB_Coord otherXYZ)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoordinate
WB_MutableCoordinate ()
WB_MutableCoordinate (final double x, final double y)
WB_MutableCoordinate (final double x, final double y, final double z)
WB_MutableCoordinate (final double[] x)
WB_MutableCoordinate (final double[] fromPoint, final double[] toPoint)
WB_MutableCoordinate (final WB_Coord v)
WB_MutableCoordinate (final WB_Coord fromPoint, final WB_Coord toPoint)
double getd (final int i)
float getf (final int i)
double xd ()
double yd ()
double zd ()
double wd ()
float xf ()
float yf ()
float zf ()
float wf ()
void setX (final double x)
void setY (final double y)
void setZ (final double z)
void setW (final double w)
void setCoord (final int i, final double v)
void set (final double x, final double y)
void set (final double x, final double y, final double z)
void set (final double x, final double y, final double z, final double w)
void set (final WB_Coord v)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoordinate2D
WB_MutableCoordinate2D ()
WB_MutableCoordinate2D (final double x, final double y)
WB_MutableCoordinate2D (final double[] x)
WB_MutableCoordinate2D (final double[] fromPoint, final double[] toPoint)
WB_MutableCoordinate2D (final WB_Coord v)
WB_MutableCoordinate2D (final WB_Coord fromPoint, final WB_Coord toPoint)
double getd (final int i)
float getf (final int i)
double xd ()
double yd ()
double zd ()
double wd ()
float xf ()
float yf ()
float zf ()
float wf ()
void setX (final double x)
void setY (final double y)
void setZ (final double z)
void setW (final double w)
void setCoord (final int i, final double v)
void set (final WB_Coord v)
void set (final double x, final double y)
void set (final double x, final double y, final double z)
void set (final double x, final double y, final double z, final double w)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoord
void setX (double x)
void setY (double y)
void setZ (double z)
void setW (double w)
void setCoord (int i, double v)
void set (WB_Coord p)
void set (double x, double y)
void set (double x, double y, double z)
void set (double x, double y, double z, double w)
Public Member Functions inherited from wblut.geom.WB_Coord
double getd (int i)
float getf (int i)
Public Member Functions inherited from wblut.geom.WB_MutableCoordinateTransform3D
WB_Coord translateSelf (final double px, final double py, double pz)
Public Member Functions inherited from wblut.geom.WB_CoordinateTransform3D
void applyInto (WB_MutableCoord result, final WB_Transform T)
WB_Coord translate (final double px, final double py, double pz)
WB_Coord translateInto (final WB_MutableCoord result, final double px, final double py, double pz)
void rotateAboutAxis2PInto (WB_MutableCoord result, final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
void rotateAboutAxis2PInto (WB_MutableCoord result, final double angle, final WB_Coord p1, final WB_Coord p2)
void rotateAboutAxisInto (WB_MutableCoord result, final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
void rotateAboutAxisInto (WB_MutableCoord result, final double angle, final WB_Coord p, final WB_Coord a)
void rotateAboutOriginInto (WB_MutableCoord result, final double angle, final double x, final double y, final double z)
void rotateAboutOriginInto (WB_MutableCoord result, final double angle, final WB_Coord v)
void scaleInto (WB_MutableCoord result, final double fx, final double fy, final double fz)
void scaleInto (WB_MutableCoord result, final double f)
Public Member Functions inherited from wblut.geom.WB_CoordinateTransform2D
void apply2DInto (WB_MutableCoord result, final WB_Transform2D T)
void rotateAboutPoint2DInto (WB_MutableCoord result, final double angle, final double px, final double py)
void rotateAboutPoint2DInto (WB_MutableCoord result, final double angle, final WB_Coord p)
void rotateAboutOrigin2DInto (WB_MutableCoord result, final double angle)
void scale2DInto (WB_MutableCoord result, final double fx, final double fy)
void scale2DInto (WB_MutableCoord result, final double f)
Public Member Functions inherited from wblut.geom.WB_CoordinateMetric3D
boolean isCollinear (WB_Coord p, WB_Coord q)
boolean isParallel (WB_Coord p)
boolean isParallel (WB_Coord p, double tol)
boolean isParallelNorm (WB_Coord p)
boolean isParallelNorm (WB_Coord p, double tol)
boolean isOrthogonal (WB_Coord p)
boolean isOrthogonal (WB_Coord p, double tol)
boolean isOrthogonalNorm (WB_Coord p)
boolean isOrthogonalNorm (WB_Coord p, double tol)
Public Member Functions inherited from wblut.geom.WB_CoordinateMetric2D
boolean isCollinear2D (WB_Coord p, WB_Coord q)
boolean isParallel2D (WB_Coord p)
boolean isParallel2D (WB_Coord p, double tol)
boolean isParallelNorm2D (WB_Coord p)
boolean isParallelNorm2D (WB_Coord p, double tol)
boolean isOrthogonal2D (WB_Coord p)
boolean isOrthogonal2D (WB_Coord p, double tol)
boolean isOrthogonalNorm2D (WB_Coord p)
boolean isOrthogonalNorm2D (WB_Coord p, double tol)
Protected Attributes
final int index
double value
Private Attributes
final FastList< WB_FrameStrut > struts
Additional Inherited Members
Static Public Member Functions inherited from wblut.geom.WB_Point
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord Z ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
static WB_Point add (final WB_Coord p, final WB_Coord q)
static WB_Point sub (final WB_Coord p, final WB_Coord q)
static WB_Vector subToVector2D (final WB_Coord p, final WB_Coord q)
static WB_Vector subToVector3D (final WB_Coord p, final WB_Coord q)
static WB_Vector subToVector (final WB_Coord p, final WB_Coord q)
static WB_Vector subToVector2D (final WB_Coord p, final double x, final double y)
static WB_Vector subToVector3D (final WB_Coord p, final double x, final double y, final double z)
static WB_Vector subToVector (final WB_Coord p, final double x, final double y, final double z)
static WB_Point mul (final WB_Coord p, final double f)
static WB_Point div (final WB_Coord p, final double f)
static WB_Point addMul (final WB_Coord p, final double f, final WB_Coord q)
static WB_Point mulAddMul (final double f, final WB_Coord p, final double g, final WB_Coord q)
static WB_Point cross (final WB_Coord p, final WB_Coord q)
static WB_Point getOrthoNormal2D (final WB_Coord p)
static WB_Point getOrthoNormal3D (final WB_Coord p)
static WB_Point getOrthoNormal (final WB_Coord p)
static WB_Point interpolate (final WB_Coord v, final WB_Coord w, final double f)
static WB_Point interpolateEaseIn (final WB_Coord v, final WB_Coord w, final double f, final WB_Ease.Ease ease)
static WB_Point interpolateEaseOut (final WB_Coord v, final WB_Coord w, final double f, final WB_Ease.Ease ease)
static WB_Point interpolateEaseInOut (final WB_Coord v, final WB_Coord w, final double f, final WB_Ease.Ease ease)
Static Public Member Functions inherited from wblut.geom.WB_Vector
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord Z ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
static WB_Vector add (final WB_Coord p, final WB_Coord q)
static WB_Vector sub (final WB_Coord p, final WB_Coord q)
static WB_Vector subToVector2D (final WB_Coord p, final WB_Coord q)
static WB_Vector subToVector3D (final WB_Coord p, final WB_Coord q)
static WB_Vector subToVector2D (final WB_Coord p, final double x, final double y)
static WB_Vector subToVector3D (final WB_Coord p, final double x, final double y, final double z)
static WB_Vector mul (final WB_Coord p, final double f)
static WB_Vector div (final WB_Coord p, final double f)
static WB_Vector addMul (final WB_Coord p, final double f, final WB_Coord q)
static WB_Vector mulAddMul (final double f, final WB_Coord p, final double g, final WB_Coord q)
static double dot2D (final WB_Coord p, final WB_Coord q)
static double absDot2D (final WB_Coord p, final WB_Coord q)
static double dot (final WB_Coord p, final WB_Coord q)
static double absDot (final WB_Coord p, final WB_Coord q)
static WB_Vector cross (final WB_Coord p, final WB_Coord q)
static WB_M33 tensor (final WB_Coord u, final WB_Coord v)
static double scalarTriple (final WB_Coord u, final WB_Coord v, final WB_Coord w)
static double getDistance2D (final WB_Coord q, final WB_Coord p)
static double getDistance3D (final WB_Coord q, final WB_Coord p)
static double getDistance (final WB_Coord q, final WB_Coord p)
static double getSqDistance2D (final WB_Coord q, final WB_Coord p)
static double getSqDistance3D (final WB_Coord q, final WB_Coord p)
static double getSqDistance (final WB_Coord q, final WB_Coord p)
static double getLength2D (final WB_Coord p)
static double getLength3D (final WB_Coord p)
static double getLength (final WB_Coord p)
static double getSqLength2D (final WB_Coord v)
static double getSqLength3D (final WB_Coord v)
static double getSqLength (final WB_Coord v)
static double getAngle (final WB_Coord q, final WB_Coord p)
static double getAngleNorm (final WB_Coord q, final WB_Coord p)
static double getHeading2D (final WB_Coord p)
static boolean isCollinear (final WB_Coord o, final WB_Coord p, final WB_Coord q)
static boolean isCollinear2D (final WB_Coord o, final WB_Coord p, final WB_Coord q)
static boolean isParallel (final WB_Coord p, final WB_Coord q)
static boolean isParallel (final WB_Coord p, final WB_Coord q, final double t)
static boolean isParallelNorm (final WB_Coord p, final WB_Coord q)
static boolean isParallelNorm (final WB_Coord p, final WB_Coord q, final double t)
static boolean isParallel2D (final WB_Coord p, final WB_Coord q)
static boolean isParallel2D (final WB_Coord p, final WB_Coord q, final double t)
static boolean isParallelNorm2D (final WB_Coord p, final WB_Coord q)
static boolean isParallelNorm2D (final WB_Coord p, final WB_Coord q, final double t)
static boolean isOrthogonal (final WB_Coord p, final WB_Coord q)
static boolean isOrthogonal (final WB_Coord p, final WB_Coord q, final double t)
static boolean isOrthogonalNorm (final WB_Coord p, final WB_Coord q)
static boolean isOrthogonalNorm (final WB_Coord p, final WB_Coord q, final double t)
static boolean isOrthogonal2D (final WB_Coord p, final WB_Coord q)
static boolean isOrthogonal2D (final WB_Coord p, final WB_Coord q, final double t)
static boolean isOrthogonalNorm2D (final WB_Coord p, final WB_Coord q)
static boolean isOrthogonalNorm2D (final WB_Coord p, final WB_Coord q, final double t)
static WB_Vector getOrthoNormal2D (final WB_Coord p)
static WB_Vector getOrthoNormal3D (final WB_Coord p)
static WB_Vector getOrthoNormal (final WB_Coord p)
static WB_Vector interpolate (final WB_Coord v, final WB_Coord w, final double f)
static WB_Vector interpolateEaseIn (final WB_Coord v, final WB_Coord w, final double f, final WB_Ease.Ease ease)
static WB_Vector interpolateEaseOut (final WB_Coord v, final WB_Coord w, final double f, final WB_Ease.Ease ease)
static WB_Vector interpolateEaseInOut (final WB_Coord v, final WB_Coord w, final double f, final WB_Ease.Ease ease)
Static Public Member Functions inherited from wblut.geom.WB_MutableCoordinate
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord Z ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
Static Public Member Functions inherited from wblut.geom.WB_MutableCoordinate2D
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
Constructor & Destructor Documentation
wblut.geom.WB_Frame.WB_FrameNode.WB_FrameNode (final WB_Coord pos, final int id, final double v)
Parameters
pos
id
v
References wblut.math.WB_Epsilon.EPSILON.
Member Function Documentation
boolean wblut.geom.WB_Frame.WB_FrameNode.addStrut (final WB_FrameStrut strut)
Parameters
strut
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.end, and wblut.geom.WB_Frame.WB_FrameStrut.start.
double wblut.geom.WB_Frame.WB_FrameNode.findShortestStrut ()
Returns
double wblut.geom.WB_Frame.WB_FrameNode.findSmallestSpan ()
Returns
References wblut.geom.WB_Frame.WB_FrameNode.findSmallestSpanAroundStrut(), and wblut.geom.WB_Frame.WB_FrameNode.getOrder().
double wblut.geom.WB_Frame.WB_FrameNode.findSmallestSpanAroundStrut (final WB_FrameStrut strut)
Parameters
strut
Returns
double wblut.geom.WB_Frame.WB_FrameNode.findSmallestSpanAroundStrut (final int i)
Parameters
i
Returns
References wblut.math.WB_Math.clamp(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Frame.WB_FrameNode.getNeighbors(), wblut.math.WB_Math.min(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Vector.subToVector3D().
int wblut.geom.WB_Frame.WB_FrameNode.getIndex ()
Returns
References wblut.geom.WB_Frame.WB_FrameNode.index.
WB_FrameNode wblut.geom.WB_Frame.WB_FrameNode.getNeighbor (final int index)
Parameters
index
Returns
ArrayList<WB_FrameNode> wblut.geom.WB_Frame.WB_FrameNode.getNeighbors ()
Returns
int wblut.geom.WB_Frame.WB_FrameNode.getOrder ()
Returns
WB_FrameStrut wblut.geom.WB_Frame.WB_FrameNode.getStrut (final int index)
Parameters
index
Returns
ArrayList<WB_FrameStrut> wblut.geom.WB_Frame.WB_FrameNode.getStruts ()
Returns
double wblut.geom.WB_Frame.WB_FrameNode.getValue ()
Returns
References wblut.geom.WB_Frame.WB_FrameNode.value.
boolean wblut.geom.WB_Frame.WB_FrameNode.removeStrut (final WB_FrameStrut strut)
Parameters
strut
Returns
References wblut.geom.WB_Frame.WB_FrameStrut.end, and wblut.geom.WB_Frame.WB_FrameStrut.start.
void wblut.geom.WB_Frame.WB_FrameNode.removeStrut (final int index)
Parameters
index
void wblut.geom.WB_Frame.WB_FrameNode.setValue (final double v)
Parameters
v
References wblut.math.WB_Epsilon.EPSILON.
WB_Point wblut.geom.WB_Frame.WB_FrameNode.toPoint ()
Returns
References wblut.geom.WB_Point.WB_Point(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
Member Data Documentation
final int wblut.geom.WB_Frame.WB_FrameNode.index protected
final FastList<WB_FrameStrut> wblut.geom.WB_Frame.WB_FrameNode.struts private
double wblut.geom.WB_Frame.WB_FrameNode.value protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Frame.java