HE_Mesh: wblut.hemesh.HEC_Cylinder Class Reference
wblut.hemesh.HEC_Cylinder Class Reference
Public Member Functions
HEC_Cylinder ()
HEC_Cylinder (final double Ri, final double Ro, final double H, final int facets, final int steps)
HEC_Cylinder setRadius (final double R)
HEC_Cylinder setRadius (final double Ri, final double Ro)
HEC_Cylinder setHeight (final double H)
HEC_Cylinder setSteps (final int steps)
HEC_Cylinder setFacets (final int facets)
HEC_Cylinder setCap (final boolean topcap, final boolean bottomcap)
HEC_Cylinder setProfile (final WB_ScalarParameter t)
HEC_Cylinder setTaper (final WB_ScalarParameter t)
HEC_Cylinder setTaper (final WB_Ease E, final WB_Ease.EaseType type)
HEC_Cylinder setPhase (final double p)
HEC_Cylinder setHeightTaper (final WB_ScalarParameter t)
HEC_Cylinder setHeightTaper (final WB_Ease E, final WB_Ease.EaseType type)
HEC_Cylinder align (final WB_Coord direction)
HEC_Cylinder align (final WB_Coord origin, final WB_Coord endpoint)
HEC_Cylinder align (final WB_Segment segment)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Attributes
double Ri
double Ro
double H
int facets
int steps
boolean topcap
boolean bottomcap
WB_ScalarParameter profile
WB_ScalarParameter taper
WB_ScalarParameter heightTaper
double phase
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Cylinder.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_Cylinder.HEC_Cylinder ()
Instantiates a new cylinder.
References wblut.geom.WB_Vector.Y, and wblut.hemesh.HEC_Creator.Z.
wblut.hemesh.HEC_Cylinder.HEC_Cylinder (final double Ri, final double Ro, final double H, final int facets, final int steps)
Instantiates a new cylinder.
Parameters
Ri bottom radius
Ro top radius
H height
facets number of facets
steps number of height divisions
References wblut.hemesh.HEC_Cylinder.facets, wblut.hemesh.HEC_Cylinder.H, wblut.hemesh.HEC_Cylinder.Ri, wblut.hemesh.HEC_Cylinder.Ro, and wblut.hemesh.HEC_Cylinder.steps.
Member Function Documentation
HEC_Cylinder wblut.hemesh.HEC_Cylinder.align (final WB_Coord direction)
Parameters
direction
Returns
References wblut.hemesh.HEC_Creator.setZAxis().
HEC_Cylinder wblut.hemesh.HEC_Cylinder.align (final WB_Coord origin, final WB_Coord endpoint)
Parameters
origin
endpoint
Returns
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Point.mulAddMul(), wblut.hemesh.HEC_Creator.setCenter(), wblut.hemesh.HEC_Cylinder.setHeight(), and wblut.hemesh.HEC_Creator.setZAxis().
HEC_Cylinder wblut.hemesh.HEC_Cylinder.align (final WB_Segment segment)
Parameters
segment
Returns
References wblut.geom.WB_Segment.getCenter(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Segment.getLength(), wblut.hemesh.HEC_Creator.setCenter(), wblut.hemesh.HEC_Cylinder.setHeight(), and wblut.hemesh.HEC_Creator.setZAxis().
HE_Mesh wblut.hemesh.HEC_Cylinder.createBase () protected
References wblut.hemesh.HEC_Cone.createBase(), wblut.hemesh.HEC_FromFacelist.createBase(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HEC_Cylinder.facets, wblut.hemesh.HEC_Cylinder.H, wblut.math.WB_Epsilon.isZero(), wblut.hemesh.HEC_Cylinder.Ri, wblut.hemesh.HEC_Cone.setCap(), wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HEC_FromFacelist.setFaceTextureIds(), wblut.hemesh.HEC_Cone.setHeightTaper(), wblut.hemesh.HEC_Cone.setProfile(), wblut.hemesh.HEC_Cone.setReverse(), wblut.hemesh.HEC_Cone.setTaper(), wblut.hemesh.HEC_FromFacelist.setVertexUVW(), wblut.hemesh.HEC_FromFacelist.setVertices(), and wblut.hemesh.HEC_Cylinder.steps.
HEC_Cylinder wblut.hemesh.HEC_Cylinder.setCap (final boolean topcap, final boolean bottomcap)
Set capping options.
Parameters
topcap create top cap?
bottomcap create bottom cap?
Returns
self
References wblut.hemesh.HEC_Cylinder.bottomcap, and wblut.hemesh.HEC_Cylinder.topcap.
HEC_Cylinder wblut.hemesh.HEC_Cylinder.setFacets (final int facets)
Set number of sides.
Parameters
facets number of sides
Returns
self
References wblut.hemesh.HEC_Cylinder.facets.
HEC_Cylinder wblut.hemesh.HEC_Cylinder.setHeight (final double H)
set height.
Parameters
H height
Returns
self
References wblut.hemesh.HEC_Cylinder.H.
HEC_Cylinder wblut.hemesh.HEC_Cylinder.setHeightTaper (final WB_ScalarParameter t)
HEC_Cylinder wblut.hemesh.HEC_Cylinder.setHeightTaper (final WB_Ease E, final WB_Ease.EaseType type)
HEC_Cylinder wblut.hemesh.HEC_Cylinder.setPhase (final double p)
HEC_Cylinder wblut.hemesh.HEC_Cylinder.setProfile (final WB_ScalarParameter t)
Sets the profile. Parameter should be a WB_ScalarParameter on the domain [0,1]. The radius at fractional height x is multiplied by the profile value at x.
Parameters
t the t
Returns
self
HEC_Cylinder wblut.hemesh.HEC_Cylinder.setRadius (final double R)
Set fixed radius.
Parameters
R radius
Returns
self
HEC_Cylinder wblut.hemesh.HEC_Cylinder.setRadius (final double Ri, final double Ro)
Set lower and upper radius.
Parameters
Ri lower radius
Ro upper radius
Returns
self
References wblut.hemesh.HEC_Cylinder.Ri, and wblut.hemesh.HEC_Cylinder.Ro.
HEC_Cylinder wblut.hemesh.HEC_Cylinder.setSteps (final int steps)
Set vertical divisions.
Parameters
steps vertical divisions
Returns
self
References wblut.hemesh.HEC_Cylinder.steps.
HEC_Cylinder wblut.hemesh.HEC_Cylinder.setTaper (final WB_ScalarParameter t)
HEC_Cylinder wblut.hemesh.HEC_Cylinder.setTaper (final WB_Ease E, final WB_Ease.EaseType type)
Member Data Documentation
boolean wblut.hemesh.HEC_Cylinder.bottomcap private
int wblut.hemesh.HEC_Cylinder.facets private
Facets.
double wblut.hemesh.HEC_Cylinder.H private
Height.
WB_ScalarParameter wblut.hemesh.HEC_Cylinder.heightTaper private
double wblut.hemesh.HEC_Cylinder.phase private
WB_ScalarParameter wblut.hemesh.HEC_Cylinder.profile private
double wblut.hemesh.HEC_Cylinder.Ri private
Base radius.
double wblut.hemesh.HEC_Cylinder.Ro private
Top Radius.
int wblut.hemesh.HEC_Cylinder.steps private
Height steps.
WB_ScalarParameter wblut.hemesh.HEC_Cylinder.taper private
boolean wblut.hemesh.HEC_Cylinder.topcap private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_Cylinder.java