HE_Mesh: wblut.hemesh.HEC_Polygon Class Reference
wblut.hemesh.HEC_Polygon Class Reference
Public Member Functions
HEC_Polygon ()
HEC_Polygon (final WB_Polygon poly, final double d)
HEC_Polygon (final Collection<?extends WB_Polygon > polygons, final double d)
HEC_Polygon (final WB_Polygon[] polygons, final double d)
HEC_Polygon setPolygon (final WB_Polygon poly)
HEC_Polygon setPolygon (final Collection<?extends WB_Polygon > polygons)
HEC_Polygon setPolygon (final WB_Polygon[] polygons)
HEC_Polygon setThickness (final double d)
HEC_Polygon setOffset (final double d)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Attributes
List< WB_Polygon > polygon
double thickness
double offset
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Constructor & Destructor Documentation
wblut.hemesh.HEC_Polygon.HEC_Polygon ()
wblut.hemesh.HEC_Polygon.HEC_Polygon (final WB_Polygon poly, final double d)
Parameters
poly
d
wblut.hemesh.HEC_Polygon.HEC_Polygon (final Collection<?extends WB_Polygon > polygons, final double d)
References wblut.hemesh.HEC_Polygon.setPolygon().
wblut.hemesh.HEC_Polygon.HEC_Polygon (final WB_Polygon[] polygons, final double d)
References wblut.hemesh.HEC_Polygon.setPolygon().
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_Polygon.createBase () protected
References wblut.math.WB_Epsilon.isZero(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HE_Mesh.moveSelf(), wblut.geom.WB_Vector.mul(), and wblut.hemesh.HEC_Polygon.setThickness().
HEC_Polygon wblut.hemesh.HEC_Polygon.setOffset (final double d)
HEC_Polygon wblut.hemesh.HEC_Polygon.setPolygon (final WB_Polygon poly)
Parameters
poly
Returns
HEC_Polygon wblut.hemesh.HEC_Polygon.setPolygon (final Collection<?extends WB_Polygon > polygons)
Parameters
polygons
Returns
HEC_Polygon wblut.hemesh.HEC_Polygon.setPolygon (final WB_Polygon[] polygons)
Parameters
polygons
Returns
HEC_Polygon wblut.hemesh.HEC_Polygon.setThickness (final double d)
Parameters
d
Returns
Member Data Documentation
double wblut.hemesh.HEC_Polygon.offset private
List<WB_Polygon> wblut.hemesh.HEC_Polygon.polygon private
double wblut.hemesh.HEC_Polygon.thickness private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_Polygon.java