HE_Mesh: wblut.nurbs.WB_NurbsKnot Class Reference
wblut.nurbs.WB_NurbsKnot Class Reference
Public Member Functions
WB_NurbsKnot (final int ncp, final int degree)
WB_NurbsKnot (final int ncp, final int degree, final double[] val)
WB_NurbsKnot (final int degree, final double[] val)
WB_NurbsKnot (final WB_NurbsKnot knot)
int p ()
int n ()
int m ()
int s ()
String toString ()
double[] values ()
double value (final int i)
void setValue (final int i, final double k)
int span (final double u)
int multiplicity (final double u)
int multiplicity (final double u, final int span)
void normalize ()
double[][] multVal ()
Static Public Member Functions
static WB_NurbsKnot merge (final WB_NurbsKnot UA, final WB_NurbsKnot UB)
Protected Member Functions
double[] basisFunctions (final int span, final double u)
double[][] allBasisFunctions (final int span, final double u, final int p)
Protected Attributes
final double[] values
final int degree
final int n
final int m
Constructor & Destructor Documentation
wblut.nurbs.WB_NurbsKnot.WB_NurbsKnot (final int ncp, final int degree)
Parameters
ncp
degree
References wblut.nurbs.WB_NurbsKnot.degree.
wblut.nurbs.WB_NurbsKnot.WB_NurbsKnot (final int ncp, final int degree, final double[] val)
Parameters
ncp
degree
val
References wblut.nurbs.WB_NurbsKnot.degree.
wblut.nurbs.WB_NurbsKnot.WB_NurbsKnot (final int degree, final double[] val)
Parameters
degree
val
References wblut.nurbs.WB_NurbsKnot.degree, and wblut.nurbs.WB_NurbsKnot.m().
wblut.nurbs.WB_NurbsKnot.WB_NurbsKnot (final WB_NurbsKnot knot)
Parameters
knot
References wblut.nurbs.WB_NurbsKnot.degree, wblut.nurbs.WB_NurbsKnot.m(), wblut.nurbs.WB_NurbsKnot.n, and wblut.nurbs.WB_NurbsKnot.value().
Member Function Documentation
double [][] wblut.nurbs.WB_NurbsKnot.allBasisFunctions (final int span, final double u, final int p) protected
Parameters
span
u
p
Returns
References wblut.nurbs.WB_NurbsKnot.p().
double [] wblut.nurbs.WB_NurbsKnot.basisFunctions (final int span, final double u) protected
Parameters
span
u
Returns
References wblut.nurbs.WB_NurbsKnot.degree.
int wblut.nurbs.WB_NurbsKnot.m ()
Returns
static WB_NurbsKnot wblut.nurbs.WB_NurbsKnot.merge (final WB_NurbsKnot UA, final WB_NurbsKnot UB) static
Parameters
UA
UB
Returns
References wblut.nurbs.WB_NurbsKnot.degree, wblut.nurbs.WB_NurbsKnot.m, wblut.nurbs.WB_NurbsKnot.multiplicity(), wblut.nurbs.WB_NurbsKnot.p(), wblut.nurbs.WB_NurbsKnot.value(), and wblut.nurbs.WB_NurbsKnot.WB_NurbsKnot().
int wblut.nurbs.WB_NurbsKnot.multiplicity (final double u)
Parameters
u
Returns
References wblut.math.WB_Epsilon.isEqualAbs(), and wblut.nurbs.WB_NurbsKnot.span().
int wblut.nurbs.WB_NurbsKnot.multiplicity (final double u, final int span)
Parameters
u
span
Returns
References wblut.nurbs.WB_NurbsKnot.span().
double [][] wblut.nurbs.WB_NurbsKnot.multVal ()
References wblut.nurbs.WB_NurbsKnot.multiplicity().
int wblut.nurbs.WB_NurbsKnot.n ()
Returns
void wblut.nurbs.WB_NurbsKnot.normalize ()
References wblut.math.WB_Epsilon.isZero(), and wblut.nurbs.WB_NurbsKnot.m().
int wblut.nurbs.WB_NurbsKnot.p ()
Returns
References wblut.nurbs.WB_NurbsKnot.degree.
int wblut.nurbs.WB_NurbsKnot.s ()
Returns
References wblut.nurbs.WB_NurbsKnot.m().
void wblut.nurbs.WB_NurbsKnot.setValue (final int i, final double k)
Parameters
i
k
int wblut.nurbs.WB_NurbsKnot.span (final double u)
Parameters
u
Returns
References wblut.nurbs.WB_NurbsKnot.degree, and wblut.nurbs.WB_NurbsKnot.n().
String wblut.nurbs.WB_NurbsKnot.toString ()
References wblut.nurbs.WB_NurbsKnot.m().
double wblut.nurbs.WB_NurbsKnot.value (final int i)
Parameters
i
Returns
double [] wblut.nurbs.WB_NurbsKnot.values ()
Returns
Member Data Documentation
final int wblut.nurbs.WB_NurbsKnot.degree protected
final int wblut.nurbs.WB_NurbsKnot.m protected
final int wblut.nurbs.WB_NurbsKnot.n protected
final double [] wblut.nurbs.WB_NurbsKnot.values protected
The documentation for this class was generated from the following file:
src/nurbs/wblut/nurbs/WB_NurbsKnot.java