HE_Mesh: wblut.geom.WB_VoronoiCell3D Class Reference
wblut.geom.WB_VoronoiCell3D Class Reference
Public Member Functions
WB_VoronoiCell3D (final WB_Coord[] points, final WB_Point generator, final int index)
WB_VoronoiCell3D (final List<?extends WB_Coord > points, final WB_Point generator, final int index)
WB_VoronoiCell3D (final WB_Mesh cell, final WB_Point generator, final int index)
void constrain (final WB_AABB container)
void trim (final double d)
int getIndex ()
WB_Point getGenerator ()
WB_Mesh getMesh ()
WB_Mesh getUntrimmedMesh ()
boolean[] getVerticesOnBoundary ()
boolean[] getFacesOnBoundary ()
boolean isBoundary ()
boolean isTrimmed ()
Private Member Functions
void slice (final WB_Plane P)
WB_Classification[] ptsPlane (final WB_Plane P)
Private Attributes
WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.geom.WB_VoronoiCell3D.WB_VoronoiCell3D (final WB_Coord[] points, final WB_Point generator, final int index)
Parameters
points
generator
index
References wblut.geom.WB_GeometryFactory3D.createConvexHull(), wblut.geom.WB_Mesh.get(), wblut.geom.WB_Mesh.getNumberOfFaces(), and wblut.geom.WB_Mesh.getNumberOfVertices().
wblut.geom.WB_VoronoiCell3D.WB_VoronoiCell3D (final List<?extends WB_Coord > points, final WB_Point generator, final int index)
Parameters
points
generator
index
References wblut.geom.WB_GeometryFactory3D.createConvexHull(), wblut.geom.WB_Mesh.get(), wblut.geom.WB_Mesh.getNumberOfFaces(), and wblut.geom.WB_Mesh.getNumberOfVertices().
wblut.geom.WB_VoronoiCell3D.WB_VoronoiCell3D (final WB_Mesh cell, final WB_Point generator, final int index)
Parameters
cell
generator
index
References wblut.geom.WB_Mesh.get(), wblut.geom.WB_Mesh.getNumberOfFaces(), and wblut.geom.WB_Mesh.getNumberOfVertices().
Member Function Documentation
void wblut.geom.WB_VoronoiCell3D.constrain (final WB_AABB container)
Parameters
container
References wblut.geom.WB_AABB._max, wblut.geom.WB_AABB._min, wblut.geom.WB_Point.add(), wblut.geom.WB_AABB.contains(), wblut.geom.WB_GeometryFactory3D.createPlane(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_Mesh.get(), wblut.geom.WB_Mesh.getAABB(), and wblut.geom.WB_AABB.intersects().
boolean [] wblut.geom.WB_VoronoiCell3D.getFacesOnBoundary ()
Returns
WB_Point wblut.geom.WB_VoronoiCell3D.getGenerator ()
Returns
int wblut.geom.WB_VoronoiCell3D.getIndex ()
Returns
WB_Mesh wblut.geom.WB_VoronoiCell3D.getMesh ()
Returns
WB_Mesh wblut.geom.WB_VoronoiCell3D.getUntrimmedMesh ()
Returns
boolean [] wblut.geom.WB_VoronoiCell3D.getVerticesOnBoundary ()
Returns
boolean wblut.geom.WB_VoronoiCell3D.isBoundary ()
Returns
boolean wblut.geom.WB_VoronoiCell3D.isTrimmed ()
Returns
WB_Classification [] wblut.geom.WB_VoronoiCell3D.ptsPlane (final WB_Plane P) private
Parameters
P
Returns
References wblut.geom.WB_GeometryOp3D.classifyPointToPlane3D(), wblut.geom.WB_Mesh.getNumberOfVertices(), and wblut.geom.WB_Mesh.getVertex().
void wblut.geom.WB_VoronoiCell3D.slice (final WB_Plane P) private
Parameters
P
References wblut.geom.WB_Classification.BACK, wblut.geom.WB_GeometryFactory3D.createConvexHull(), wblut.geom.WB_Classification.FRONT, wblut.geom.WB_Mesh.getEdgesAsInt(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.geom.WB_Mesh.getVertex(), wblut.geom.WB_IntersectionResult.object, and wblut.geom.WB_VoronoiCell3D.ptsPlane().
void wblut.geom.WB_VoronoiCell3D.trim (final double d)
References wblut.geom.WB_Mesh.getPlanes(), wblut.math.WB_Epsilon.isZero(), and wblut.geom.WB_VoronoiCell3D.slice().
Member Data Documentation
WB_GeometryFactory wblut.geom.WB_VoronoiCell3D.geometryfactory = new WB_GeometryFactory() private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_VoronoiCell3D.java