HE_Mesh: wblut.hemesh.HEC_VoronoiSphere Class Reference
wblut.hemesh.HEC_VoronoiSphere Class Reference
Public Member Functions
HEC_VoronoiSphere ()
HEC_VoronoiSphere setCellIndex (final int i)
HEC_VoronoiSphere setLevel (final int l)
HEC_VoronoiSphere setNumTracers (final int n)
HEC_VoronoiSphere setTraceStep (final double d)
HEC_VoronoiSphere setCutoff (final double c)
HEC_VoronoiSphere setApprox (final boolean a)
HEC_VoronoiSphere setSeed (final long seed)
HEC_VoronoiSphere setOffset (final double o)
HE_Mesh createBase ()
HEC_VoronoiSphere setPoints (final Collection<?extends WB_Coord > points)
HEC_VoronoiSphere setPoints (final double[][] points)
HEC_VoronoiSphere setPoints (final float[][] points)
HEC_VoronoiSphere setPoints (final WB_Coord[] points)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Private Member Functions
void grow (final WB_Point[] tracers, final int index, final double offset)
Private Attributes
List< WB_Coord > points
int numberOfPoints
int cellIndex
int level
double cutoff
WB_Vector[] dir
boolean approx
int numTracers
double traceStep
final WB_RandomOnSphere randomGen
double offset
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Creates the Voronoi cell of one point in a collection of points, constrained by a maximum radius.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_VoronoiSphere.HEC_VoronoiSphere ()
Instantiates a new HEC_VoronoiSphere.
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_VoronoiSphere.createBase ()
References wblut.geom.WB_Point.addSelf(), wblut.hemesh.HEC_VoronoiSphere.grow(), wblut.hemesh.HE_Mesh.modify(), wblut.geom.WB_Vector.mul(), wblut.geom.WB_Point.mulSelf(), wblut.geom.WB_RandomOnSphere.nextPoint(), wblut.geom.WB_Vector.normalizeSelf(), wblut.hemesh.HEC_VoronoiSphere.numberOfPoints, wblut.hemesh.HEC_VoronoiSphere.numTracers, wblut.geom.WB_RandomOnSphere.reset(), wblut.hemesh.HEC_Geodesic.setB(), wblut.hemesh.HEC_Geodesic.setC(), wblut.hemesh.HEC_Creator.setCenter(), wblut.hemesh.HEM_MultiSlice.setCenter(), wblut.hemesh.HEC_ConvexHull.setN(), wblut.hemesh.HEM_MultiSlice.setPlanes(), wblut.hemesh.HEC_ConvexHull.setPoints(), wblut.hemesh.HEC_Geodesic.setRadius(), and wblut.geom.WB_Vector.subSelf().
void wblut.hemesh.HEC_VoronoiSphere.grow (final WB_Point[] tracers, final int index, final double offset) private
Parameters
tracers
index
offset
References wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.add(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.getNearestNeighbors(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), wblut.hemesh.HEC_VoronoiSphere.numberOfPoints, wblut.hemesh.HEC_VoronoiSphere.numTracers, wblut.hemesh.HEC_VoronoiSphere.traceStep, wblut.geom.WB_KDTreeInteger< T extends WB_Coord >.WB_KDEntryInteger< T extends WB_Coord >.value, wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
HEC_VoronoiSphere wblut.hemesh.HEC_VoronoiSphere.setApprox (final boolean a)
Set approximate mode.
Parameters
a true, false
Returns
self
HEC_VoronoiSphere wblut.hemesh.HEC_VoronoiSphere.setCellIndex (final int i)
Set index of cell to create.
Parameters
i index
Returns
self
HEC_VoronoiSphere wblut.hemesh.HEC_VoronoiSphere.setCutoff (final double c)
Set maximum radius of cell.
Parameters
c cutoff radius
Returns
self
HEC_VoronoiSphere wblut.hemesh.HEC_VoronoiSphere.setLevel (final int l)
Set level of geodesic sphere in each cell.
Parameters
l recursive level
Returns
self
HEC_VoronoiSphere wblut.hemesh.HEC_VoronoiSphere.setNumTracers (final int n)
Set number of tracer points to use in approximate model.
Parameters
n number of tracer points
Returns
self
HEC_VoronoiSphere wblut.hemesh.HEC_VoronoiSphere.setOffset (final double o)
HEC_VoronoiSphere wblut.hemesh.HEC_VoronoiSphere.setPoints (final Collection<?extends WB_Coord > points)
Set points that define cell centers.
Parameters
points collection of vertex positions
Returns
self
HEC_VoronoiSphere wblut.hemesh.HEC_VoronoiSphere.setPoints (final double points[][])
Set points that define cell centers.
Parameters
points 2D array of double of vertex positions
Returns
self
HEC_VoronoiSphere wblut.hemesh.HEC_VoronoiSphere.setPoints (final float points[][])
Set points that define cell centers.
Parameters
points 2D array of float of vertex positions
Returns
self
HEC_VoronoiSphere wblut.hemesh.HEC_VoronoiSphere.setPoints (final WB_Coord[] points)
Set points that define cell centers.
Parameters
points array of vertex positions
Returns
self
HEC_VoronoiSphere wblut.hemesh.HEC_VoronoiSphere.setSeed (final long seed)
Set seed of random generator.
Parameters
seed seed
Returns
self
References wblut.geom.WB_RandomOnSphere.setSeed().
HEC_VoronoiSphere wblut.hemesh.HEC_VoronoiSphere.setTraceStep (final double d)
Set initial trace step size.
Parameters
d trace step
Returns
self
Member Data Documentation
boolean wblut.hemesh.HEC_VoronoiSphere.approx private
Approximate mode?.
int wblut.hemesh.HEC_VoronoiSphere.cellIndex private
Cell index.
double wblut.hemesh.HEC_VoronoiSphere.cutoff private
Maximum radius.
WB_Vector [] wblut.hemesh.HEC_VoronoiSphere.dir private
Point directions.
int wblut.hemesh.HEC_VoronoiSphere.level private
Level of geodesic sphere in exact mode.
int wblut.hemesh.HEC_VoronoiSphere.numberOfPoints private
Number of points.
int wblut.hemesh.HEC_VoronoiSphere.numTracers private
Number of tracer points to use in approximate mode?.
double wblut.hemesh.HEC_VoronoiSphere.offset private
List<WB_Coord> wblut.hemesh.HEC_VoronoiSphere.points private
points.
final WB_RandomOnSphere wblut.hemesh.HEC_VoronoiSphere.randomGen private
The random gen.
double wblut.hemesh.HEC_VoronoiSphere.traceStep private
Starting trace step in approximate mode?.
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_VoronoiSphere.java