HE_Mesh: wblut.hemesh.HEM_Extrude Class Reference
wblut.hemesh.HEM_Extrude Class Reference
Public Member Functions
HEM_Extrude ()
HEM_Extrude setDistance (final double d)
HEM_Extrude setDistance (final WB_ScalarParameter d)
HEM_Extrude setChamfer (final double c)
HEM_Extrude setChamfer (final WB_ScalarParameter c)
HEM_Extrude setHardEdgeChamfer (final double c)
HEM_Extrude setHardEdgeChamfer (final WB_ScalarParameter c)
HEM_Extrude setRelative (final boolean relative)
HEM_Extrude setFuse (final boolean b)
HEM_Extrude setPeak (final boolean b)
HEM_Extrude setThresholdAngle (final double a)
HEM_Extrude setFuseAngle (final double a)
HEM_Extrude setDistances (final double[] distances)
HEM_Extrude setDistances (final float[] distances)
HEM_Extrude setDistances (final int[] distances)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Member Functions
HE_Mesh applyStraight (final HE_Mesh mesh, final List< HE_Face > faces)
boolean applyStraightToOneFaceIgnoreNeighborhood (final int id, final List< HE_Face > selfaces, final HE_Mesh mesh, final boolean[] visited, final double d)
boolean applyStraightToOneFace (final int id, final List< HE_Face > selfaces, final HE_Mesh mesh, final boolean[] visited, final double d)
HE_Mesh applyPeaked (final HE_Mesh mesh, final List< HE_Face > faces)
void applyPeakToOneFace (final int id, final List< HE_Face > selFaces, final HE_Mesh mesh, final double d)
HE_Mesh applyFlat (final HE_Mesh mesh, final List< HE_Face > faces, final boolean fuse)
boolean applyFlatToOneFace (final int id, final List< HE_Face > selFaces, final HE_Mesh mesh, final HE_Selection fuse)
Private Attributes
WB_ScalarParameter d
double thresholdAngle
WB_ScalarParameter chamfer
WB_ScalarParameter hardEdgeChamfer
boolean relative
boolean fuse
boolean peak
double fuseAngle
Map< Long, WB_Coord > _faceNormals
LongObjectHashMap< WB_Coord > _halfedgeNormals
LongDoubleHashMap _halfedgeEWs
Map< Long, WB_Coord > _faceCenters
double[] heights
HE_Selection walls
HE_Selection extruded
HE_Selection peaks
HE_Selection fused
List< HE_Face > failedFaces
List< Double > failedHeights
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Extrudes and scales a face along its face normal.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_Extrude.HEM_Extrude ()
Instantiates a new HEM_Extrude.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Extrude.applyFlat (final HE_Mesh mesh, final List< HE_Face > faces, final boolean fuse) private
Apply flat extrusion.
Parameters
mesh
faces
fuse
Returns
mesh
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HEM_Extrude.applyFlatToOneFace(), wblut.hemesh.HE_Mesh.deleteEdge(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Halfedge.getEdgeDihedralAngle(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Selection.getHalfedgeWithIndex(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_Selection.getNumberOfHalfedges(), wblut.hemesh.HE_Halfedge.getPair(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Halfedge.isEdge(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Machine.tracker, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
boolean wblut.hemesh.HEM_Extrude.applyFlatToOneFace (final int id, final List< HE_Face > selFaces, final HE_Mesh mesh, final HE_Selection fuse) private
Apply flat extrusion to one face.
Parameters
id
selFaces
mesh
fuse
Returns
true, if successful
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.geom.WB_Point.addMul(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Polygon.closestPoint(), wblut.hemesh.HET_MeshOp.collapseEdge(), wblut.geom.WB_Classification.CONVEX, wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Mesh.get(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Face.getFaceType(), wblut.hemesh.HE_Face.getHalfedge(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.geom.WB_Polygon.getNumberOfShellPoints(), wblut.hemesh.HE_Halfedge.getPair(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), wblut.hemesh.HE_Halfedge.getStartVertex(), wblut.math.WB_Epsilon.isZeroSq(), wblut.hemesh.HE_Face.key(), wblut.geom.WB_Point.mulSelf(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Mesh.remove(), wblut.geom.WB_MutableCoordinate.set(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Mesh.setVertex(), wblut.geom.WB_Point.subSelf(), wblut.hemesh.HE_Face.toPolygon(), and wblut.geom.WB_Polygon.trimConvexPolygon().
HE_Mesh wblut.hemesh.HEM_Extrude.applyPeaked (final HE_Mesh mesh, final List< HE_Face > faces) private
Apply peaked extrusion.
Parameters
mesh
faces
Returns
mesh
References wblut.hemesh.HEM_Extrude.applyPeakToOneFace(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Face.key(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.hemesh.HE_Machine.tracker, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.hemesh.HEM_Extrude.applyPeakToOneFace (final int id, final List< HE_Face > selFaces, final HE_Mesh mesh, final double d) private
Apply peaked extrusion to one face.
Parameters
id
selFaces
mesh
d
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Selection.addFaces(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Selection.getFacesAsArray(), wblut.hemesh.HE_Face.key(), wblut.geom.WB_Vector.mulSelf(), wblut.hemesh.HE_Element.setInternalLabel(), and wblut.hemesh.HEM_TriSplit.splitFaceTri().
HE_Mesh wblut.hemesh.HEM_Extrude.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.hemesh.HEM_Extrude.applyFlat(), wblut.hemesh.HEM_Extrude.applyPeaked(), wblut.hemesh.HEM_Extrude.applyStraight(), wblut.hemesh.HET_Texture.cleanUVW(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Mesh.getFaces(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getHalfedgeDihedralAngle(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Element.getKey(), wblut.hemesh.HE_Mesh.getKeyedFaceCenters(), wblut.hemesh.HE_Mesh.getKeyedFaceNormals(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Halfedge.key(), wblut.hemesh.HE_Face.key(), wblut.hemesh.HE_Mesh.resetFaceInternalLabels(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Machine.tracker, wblut.geom.WB_Coord.xd(), wblut.hemesh.HE_Vertex.xd(), wblut.geom.WB_Coord.yd(), wblut.hemesh.HE_Vertex.yd(), wblut.geom.WB_Coord.zd(), and wblut.hemesh.HE_Vertex.zd().
HE_Mesh wblut.hemesh.HEM_Extrude.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.hemesh.HEM_Extrude.applyFlat(), wblut.hemesh.HEM_Extrude.applyPeaked(), wblut.hemesh.HEM_Extrude.applyStraight(), wblut.hemesh.HET_Texture.cleanUVW(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Selection.getFaces(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getHalfedgeDihedralAngle(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Element.getKey(), wblut.hemesh.HE_Mesh.getKeyedFaceCenters(), wblut.hemesh.HE_Mesh.getKeyedFaceNormals(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Selection.getNumberOfFaces(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Halfedge.key(), wblut.hemesh.HE_Face.key(), wblut.hemesh.HE_Mesh.resetFaceInternalLabels(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Machine.tracker, wblut.geom.WB_Coord.xd(), wblut.hemesh.HE_Vertex.xd(), wblut.geom.WB_Coord.yd(), wblut.hemesh.HE_Vertex.yd(), wblut.geom.WB_Coord.zd(), and wblut.hemesh.HE_Vertex.zd().
HE_Mesh wblut.hemesh.HEM_Extrude.applyStraight (final HE_Mesh mesh, final List< HE_Face > faces) private
Apply straight extrusion.
Parameters
mesh the mesh
faces the faces
Returns
mesh
References wblut.hemesh.HEM_Extrude.applyStraightToOneFace(), wblut.hemesh.HEM_Extrude.applyStraightToOneFaceIgnoreNeighborhood(), wblut.math.WB_ScalarParameter.evaluate(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.hemesh.HE_Machine.tracker, wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
boolean wblut.hemesh.HEM_Extrude.applyStraightToOneFace (final int id, final List< HE_Face > selfaces, final HE_Mesh mesh, final boolean[] visited, final double d) private
Apply straight extrusion to one face.
Parameters
id the id
selfaces the selfaces
mesh the mesh
visited the visited
d
Returns
true, if successful
References wblut.geom.WB_Point.add(), wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Selection.addFaces(), wblut.geom.WB_Point.addMulSelf(), wblut.hemesh.HE_Mesh.addVertices(), wblut.hemesh.HE_Vertex.copyProperties(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getNeighborFaces(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_Vector.isParallel(), wblut.hemesh.HE_Face.key(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), and wblut.hemesh.HE_Mesh.setVertex().
boolean wblut.hemesh.HEM_Extrude.applyStraightToOneFaceIgnoreNeighborhood (final int id, final List< HE_Face > selfaces, final HE_Mesh mesh, final boolean[] visited, final double d) private
Parameters
id
selfaces
mesh
visited
d
Returns
References wblut.geom.WB_Point.add(), wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Selection.addFaces(), wblut.geom.WB_Point.addMulSelf(), wblut.hemesh.HE_Mesh.addVertices(), wblut.hemesh.HE_Vertex.copyProperties(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Face.key(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), and wblut.hemesh.HE_Mesh.setVertex().
HEM_Extrude wblut.hemesh.HEM_Extrude.setChamfer (final double c)
Set chamfer factor.
Parameters
c
Returns
self
References wblut.math.WB_Epsilon.isZero().
HEM_Extrude wblut.hemesh.HEM_Extrude.setChamfer (final WB_ScalarParameter c)
HEM_Extrude wblut.hemesh.HEM_Extrude.setDistance (final double d)
Set extrusion distance.
Parameters
d extrusion distance
Returns
self
References wblut.math.WB_Epsilon.isZero(), and wblut.math.WB_ScalarParameter.ZERO.
HEM_Extrude wblut.hemesh.HEM_Extrude.setDistance (final WB_ScalarParameter d)
Sets the distance.
Parameters
d
Returns
self
References wblut.hemesh.HEM_Extrude.d.
HEM_Extrude wblut.hemesh.HEM_Extrude.setDistances (final double[] distances)
Parameters
distances
Returns
HEM_Extrude wblut.hemesh.HEM_Extrude.setDistances (final float[] distances)
Parameters
distances
Returns
HEM_Extrude wblut.hemesh.HEM_Extrude.setDistances (final int[] distances)
Parameters
distances
Returns
HEM_Extrude wblut.hemesh.HEM_Extrude.setFuse (final boolean b)
Set fuse option: merges coplanar faces.
Parameters
b true, false
Returns
self
HEM_Extrude wblut.hemesh.HEM_Extrude.setFuseAngle (final double a)
Set threshold angle for fuse.
Parameters
a threshold angle
Returns
self
HEM_Extrude wblut.hemesh.HEM_Extrude.setHardEdgeChamfer (final double c)
Set hard edge chamfer distance
Parameters
c
Returns
self
HEM_Extrude wblut.hemesh.HEM_Extrude.setHardEdgeChamfer (final WB_ScalarParameter c)
HEM_Extrude wblut.hemesh.HEM_Extrude.setPeak (final boolean b)
Set peak option.
Parameters
b true, false
Returns
self
HEM_Extrude wblut.hemesh.HEM_Extrude.setRelative (final boolean relative)
Set chamfer mode.
Parameters
relative true/false
Returns
self
References wblut.hemesh.HEM_Extrude.relative.
HEM_Extrude wblut.hemesh.HEM_Extrude.setThresholdAngle (final double a)
Set threshold angle for hard edge.
Parameters
a threshold angle
Returns
self
Member Data Documentation
Map<Long, WB_Coord> wblut.hemesh.HEM_Extrude._faceCenters private
Face centers.
Map<Long, WB_Coord> wblut.hemesh.HEM_Extrude._faceNormals private
Vertex normals.
LongDoubleHashMap wblut.hemesh.HEM_Extrude._halfedgeEWs private
Extrusion widths.
LongObjectHashMap<WB_Coord> wblut.hemesh.HEM_Extrude._halfedgeNormals private
Halfedge normals.
WB_ScalarParameter wblut.hemesh.HEM_Extrude.chamfer private
Chamfer factor or distance.
WB_ScalarParameter wblut.hemesh.HEM_Extrude.d private
Extrusion distance.
HE_Selection wblut.hemesh.HEM_Extrude.extruded private
List<HE_Face> wblut.hemesh.HEM_Extrude.failedFaces private
List<Double> wblut.hemesh.HEM_Extrude.failedHeights private
boolean wblut.hemesh.HEM_Extrude.fuse private
Fuse coplanar faces.
double wblut.hemesh.HEM_Extrude.fuseAngle private
Limit angle for face fusion.
HE_Selection wblut.hemesh.HEM_Extrude.fused private
WB_ScalarParameter wblut.hemesh.HEM_Extrude.hardEdgeChamfer private
Hard edge chamfer distance.
double [] wblut.hemesh.HEM_Extrude.heights private
boolean wblut.hemesh.HEM_Extrude.peak private
Turn non-extrudable faces into spiked faces?.
HE_Selection wblut.hemesh.HEM_Extrude.peaks private
boolean wblut.hemesh.HEM_Extrude.relative private
Extrusion mode.
double wblut.hemesh.HEM_Extrude.thresholdAngle private
Threshold angle for hard edges.
HE_Selection wblut.hemesh.HEM_Extrude.walls private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Extrude.java