HE_Mesh: wblut.geom.WB_Circle Class Reference
wblut.geom.WB_Circle Class Reference
Public Member Functions
WB_Circle ()
WB_Circle (final WB_Coord center, final double radius)
WB_Circle (final WB_Coord center, final WB_Coord normal, final double radius)
WB_Circle (final double x, final double y, final double r)
double getRadius ()
WB_Coord getCenter ()
WB_Coord getNormal ()
WB_Circle apply (final WB_Transform T)
WB_Circle applySelf (final WB_Transform T)
void set (final WB_Circle c)
void setCenter (final double x, final double y)
void setCenter (final double x, final double y, final double z)
void setCenter (final WB_Coord c)
void setNormal (final double x, final double y, final double z)
void setNormal (final WB_Coord c)
void setRadius (final double radius)
void setDiameter (final double diameter)
boolean equals (final Object o)
int hashCode ()
boolean contains (final WB_Coord p)
WB_Point[] getPoints (final int n, final double phase)
WB_Point[] getPoints (final int n)
double[] getPointsAsArray (final int n)
WB_Plane getPlane ()
WB_Plane getPlane (final double d)
Private Member Functions
int hashCode (final double v)
Private Attributes
WB_Point center
WB_Vector normal
double radius
WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.geom.WB_Circle.WB_Circle ()
References wblut.geom.WB_GeometryFactory3D.createPoint(), and wblut.geom.WB_GeometryFactory3D.createVector().
wblut.geom.WB_Circle.WB_Circle (final WB_Coord center, final double radius)
Parameters
center
radius
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVector(), wblut.math.WB_Math.fastAbs(), and wblut.geom.WB_Circle.radius.
wblut.geom.WB_Circle.WB_Circle (final WB_Coord center, final WB_Coord normal, final double radius)
Parameters
center
normal
radius
References wblut.geom.WB_GeometryFactory3D.createNormalizedVector(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.math.WB_Math.fastAbs(), and wblut.geom.WB_Circle.radius.
wblut.geom.WB_Circle.WB_Circle (final double x, final double y, final double r)
Parameters
x
y
r
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVector(), and wblut.math.WB_Math.fastAbs().
Member Function Documentation
WB_Circle wblut.geom.WB_Circle.apply (final WB_Transform T)
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Vector.applyAsNormalSelf(), wblut.geom.WB_Point.applyAsPointSelf(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_GeometryFactory3D.createVector(), and wblut.geom.WB_Vector.getDistance2D().
WB_Circle wblut.geom.WB_Circle.applySelf (final WB_Transform T)
Parameters
T
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Vector.applyAsNormalSelf(), wblut.geom.WB_Point.applyAsPointSelf(), wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_Vector.getDistance2D(), and wblut.geom.WB_MutableCoordinate.set().
boolean wblut.geom.WB_Circle.contains (final WB_Coord p)
References wblut.geom.WB_Vector.getSqDistance2D().
boolean wblut.geom.WB_Circle.equals (final Object o)
References wblut.geom.WB_Point.equals(), wblut.geom.WB_Vector.equals(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Circle.getNormal(), wblut.geom.WB_Circle.getRadius(), and wblut.math.WB_Epsilon.isEqualAbs().
WB_Coord wblut.geom.WB_Circle.getCenter ()
Returns
References wblut.geom.WB_Circle.center.
WB_Coord wblut.geom.WB_Circle.getNormal ()
Returns
References wblut.geom.WB_Circle.normal.
WB_Plane wblut.geom.WB_Circle.getPlane ()
WB_Plane wblut.geom.WB_Circle.getPlane (final double d)
WB_Point [] wblut.geom.WB_Circle.getPoints (final int n, final double phase)
References wblut.geom.WB_Transform.addFromCSToWorld(), and wblut.geom.WB_Point.applySelf().
WB_Point [] wblut.geom.WB_Circle.getPoints (final int n)
References wblut.geom.WB_Transform.addFromCSToWorld(), and wblut.geom.WB_Point.applySelf().
double [] wblut.geom.WB_Circle.getPointsAsArray (final int n)
References wblut.geom.WB_Transform.addFromCSToWorld(), wblut.geom.WB_Point.applySelf(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
double wblut.geom.WB_Circle.getRadius ()
Returns
References wblut.geom.WB_Circle.radius.
int wblut.geom.WB_Circle.hashCode ()
References wblut.geom.WB_Point.hashCode(), and wblut.geom.WB_Vector.hashCode().
int wblut.geom.WB_Circle.hashCode (final double v) private
Parameters
v
Returns
void wblut.geom.WB_Circle.set (final WB_Circle c)
Parameters
c
References wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Circle.getNormal(), wblut.geom.WB_Circle.getRadius(), and wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_Circle.setCenter (final double x, final double y)
Parameters
x
y
References wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_Circle.setCenter (final double x, final double y, final double z)
Parameters
x
y
z
References wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_Circle.setCenter (final WB_Coord c)
Parameters
c
References wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_Circle.setDiameter (final double diameter)
Parameters
diameter
void wblut.geom.WB_Circle.setNormal (final double x, final double y, final double z)
Parameters
x
y
z
References wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_Circle.setNormal (final WB_Coord c)
Parameters
c
References wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_Circle.setRadius (final double radius)
Parameters
radius
References wblut.geom.WB_Circle.radius.
Member Data Documentation
WB_Point wblut.geom.WB_Circle.center private
WB_GeometryFactory wblut.geom.WB_Circle.geometryfactory = new WB_GeometryFactory() private
WB_Vector wblut.geom.WB_Circle.normal private
double wblut.geom.WB_Circle.radius private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Circle.java