HE_Mesh: wblut.math.WB_SDF Class Reference
wblut.math.WB_SDF Class Reference
Static Public Member Functions
static double fSphere (final WB_Coord p, final double r)
static double fPlane (final WB_Coord p, final WB_Coord n, final double distanceFromOrigin)
static double fBoxCheap (final WB_Coord p, final WB_Coord b)
static double fBox (final WB_Coord p, final WB_Coord b)
static double fBox2Cheap (final WB_Coord p, final WB_Coord b)
static double fBox2 (final WB_Coord p, final WB_Coord b)
static double fCorner (final WB_Coord p)
static double fBlob (final WB_Coord q)
static double fCylinder (final WB_Coord p, final double r, final double height)
static double fCapsule (final WB_Coord p, final double r, final double c)
static double fLineSegment (final WB_Coord p, final WB_Coord a, final WB_Coord b)
static double fCapsule (final WB_Coord p, final WB_Coord a, final WB_Coord b, final double r)
static double fTorus (final WB_Coord p, final double smallRadius, final double largeRadius)
static double fCircle (final WB_Coord p, final double r)
static double fDisc (final WB_Coord p, final double r)
static double fHexagonCircumcircle (final WB_Coord p, final WB_Coord h)
static double fHexagonIncircle (final WB_Coord p, final WB_Coord h)
static double fCone (final WB_Coord p, final double radius, final double height)
static double fGDF (final WB_Coord p, final double r, final double e, final int begin, final int end)
static double fGDF (final WB_Coord p, final double r, final int begin, final int end)
static double fOctahedron (final WB_Coord p, final double r, final double e)
static double fDodecahedron (final WB_Coord p, final double r, final double e)
static double fIcosahedron (final WB_Coord p, final double r, final double e)
static double fTruncatedOctahedron (final WB_Coord p, final double r, final double e)
static double fTruncatedIcosahedron (final WB_Coord p, final double r, final double e)
static double fOctahedron (final WB_Coord p, final double r)
static double fDodecahedron (final WB_Coord p, final double r)
static double fIcosahedron (final WB_Coord p, final double r)
static double fTruncatedOctahedron (final WB_Coord p, final double r)
static double fTruncatedIcosahedron (final WB_Coord p, final double r)
static void pR45 (final WB_Vector p)
static double pMod1 (double p, final double size)
static double fOpUnionChamfer (final double a, final double b, final double r)
static double fOpIntersectionChamfer (final double a, final double b, final double r)
static double fOpDifferenceChamfer (final double a, final double b, final double r)
static double fOpUnionRound (final double a, final double b, final double r)
static double fOpIntersectionRound (final double a, final double b, final double r)
static double fOpDifferenceRound (final double a, final double b, final double r)
static double fOpUnionColumns (final double a, final double b, final double r, final double n)
static double fOpDifferenceColumns (double a, final double b, final double r, final double n)
static double fOpIntersectionColumns (final double a, final double b, final double r, final double n)
static double fOpUnionStairs (final double a, final double b, final double r, final double n)
static double fOpIntersectionStairs (final double a, final double b, final double r, final double n)
static double fOpDifferenceStairs (final double a, final double b, final double r, final double n)
static double fOpUnionSoft (final double a, final double b, final double r)
static double fOpPipe (final double a, final double b, final double r)
static double fOpEngrave (final double a, final double b, final double r)
static double fOpGroove (final double a, final double b, final double ra, final double rb)
static double fOpTongue (final double a, final double b, final double ra, final double rb)
Static Public Attributes
static final double PI = Math.PI
static final double TAU = 2 * 2 * PI
static final double PHI = Math.sqrt(5) * 0.5 + 0.5
static final WB_Vector[] GDFVectors
Member Function Documentation
static double wblut.math.WB_SDF.fBlob (final WB_Coord q) static
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
static double wblut.math.WB_SDF.fBox (final WB_Coord p, final WB_Coord b) static
References wblut.geom.WB_Vector.sub().
static double wblut.math.WB_SDF.fBox2 (final WB_Coord p, final WB_Coord b) static
References wblut.geom.WB_Vector.sub().
static double wblut.math.WB_SDF.fBox2Cheap (final WB_Coord p, final WB_Coord b) static
References wblut.geom.WB_Vector.sub().
static double wblut.math.WB_SDF.fBoxCheap (final WB_Coord p, final WB_Coord b) static
References wblut.geom.WB_Vector.sub().
static double wblut.math.WB_SDF.fCapsule (final WB_Coord p, final double r, final double c) static
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.math.WB_SDF.fCapsule (final WB_Coord p, final WB_Coord a, final WB_Coord b, final double r) static
References wblut.math.WB_SDF.fLineSegment().
static double wblut.math.WB_SDF.fCircle (final WB_Coord p, final double r) static
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.math.WB_SDF.fCone (final WB_Coord p, final double radius, final double height) static
References wblut.geom.WB_Vector.sub(), wblut.geom.WB_Vector.subSelf(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.math.WB_SDF.fCorner (final WB_Coord p) static
static double wblut.math.WB_SDF.fCylinder (final WB_Coord p, final double r, final double height) static
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.math.WB_SDF.fDisc (final WB_Coord p, final double r) static
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.math.WB_SDF.fDodecahedron (final WB_Coord p, final double r, final double e) static
References wblut.math.WB_SDF.fGDF().
static double wblut.math.WB_SDF.fDodecahedron (final WB_Coord p, final double r) static
References wblut.math.WB_SDF.fGDF().
static double wblut.math.WB_SDF.fGDF (final WB_Coord p, final double r, final double e, final int begin, final int end) static
static double wblut.math.WB_SDF.fGDF (final WB_Coord p, final double r, final int begin, final int end) static
static double wblut.math.WB_SDF.fHexagonCircumcircle (final WB_Coord p, final WB_Coord h) static
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.math.WB_SDF.fHexagonIncircle (final WB_Coord p, final WB_Coord h) static
References wblut.math.WB_SDF.fHexagonCircumcircle(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static double wblut.math.WB_SDF.fIcosahedron (final WB_Coord p, final double r, final double e) static
References wblut.math.WB_SDF.fGDF().
static double wblut.math.WB_SDF.fIcosahedron (final WB_Coord p, final double r) static
References wblut.math.WB_SDF.fGDF().
static double wblut.math.WB_SDF.fLineSegment (final WB_Coord p, final WB_Coord a, final WB_Coord b) static
References wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Vector.sub(), and wblut.geom.WB_Vector.subSelf().
static double wblut.math.WB_SDF.fOctahedron (final WB_Coord p, final double r, final double e) static
References wblut.math.WB_SDF.fGDF().
static double wblut.math.WB_SDF.fOctahedron (final WB_Coord p, final double r) static
References wblut.math.WB_SDF.fGDF().
static double wblut.math.WB_SDF.fOpDifferenceChamfer (final double a, final double b, final double r) static
References wblut.math.WB_SDF.fOpIntersectionChamfer().
static double wblut.math.WB_SDF.fOpDifferenceColumns (double a, final double b, final double r, final double n) static
References wblut.geom.WB_Vector.addSelf(), wblut.math.WB_SDF.pMod1(), wblut.math.WB_SDF.pR45(), wblut.geom.WB_MutableCoordinate.setY(), wblut.geom.WB_Vector.subSelf(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static double wblut.math.WB_SDF.fOpDifferenceRound (final double a, final double b, final double r) static
References wblut.math.WB_SDF.fOpIntersectionRound().
static double wblut.math.WB_SDF.fOpDifferenceStairs (final double a, final double b, final double r, final double n) static
References wblut.math.WB_SDF.fOpUnionStairs().
static double wblut.math.WB_SDF.fOpEngrave (final double a, final double b, final double r) static
static double wblut.math.WB_SDF.fOpGroove (final double a, final double b, final double ra, final double rb) static
static double wblut.math.WB_SDF.fOpIntersectionChamfer (final double a, final double b, final double r) static
static double wblut.math.WB_SDF.fOpIntersectionColumns (final double a, final double b, final double r, final double n) static
References wblut.math.WB_SDF.fOpDifferenceColumns().
static double wblut.math.WB_SDF.fOpIntersectionRound (final double a, final double b, final double r) static
static double wblut.math.WB_SDF.fOpIntersectionStairs (final double a, final double b, final double r, final double n) static
References wblut.math.WB_SDF.fOpUnionStairs().
static double wblut.math.WB_SDF.fOpPipe (final double a, final double b, final double r) static
static double wblut.math.WB_SDF.fOpTongue (final double a, final double b, final double ra, final double rb) static
static double wblut.math.WB_SDF.fOpUnionChamfer (final double a, final double b, final double r) static
static double wblut.math.WB_SDF.fOpUnionColumns (final double a, final double b, final double r, final double n) static
References wblut.geom.WB_Vector.addSelf(), wblut.math.WB_SDF.pMod1(), wblut.math.WB_SDF.pR45(), wblut.geom.WB_MutableCoordinate.setY(), wblut.geom.WB_Vector.subSelf(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static double wblut.math.WB_SDF.fOpUnionRound (final double a, final double b, final double r) static
static double wblut.math.WB_SDF.fOpUnionSoft (final double a, final double b, final double r) static
static double wblut.math.WB_SDF.fOpUnionStairs (final double a, final double b, final double r, final double n) static
static double wblut.math.WB_SDF.fPlane (final WB_Coord p, final WB_Coord n, final double distanceFromOrigin) static
References wblut.geom.WB_Vector.dot().
static double wblut.math.WB_SDF.fSphere (final WB_Coord p, final double r) static
References wblut.geom.WB_Vector.getLength3D().
static double wblut.math.WB_SDF.fTorus (final WB_Coord p, final double smallRadius, final double largeRadius) static
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static double wblut.math.WB_SDF.fTruncatedIcosahedron (final WB_Coord p, final double r, final double e) static
References wblut.math.WB_SDF.fGDF().
static double wblut.math.WB_SDF.fTruncatedIcosahedron (final WB_Coord p, final double r) static
References wblut.math.WB_SDF.fGDF().
static double wblut.math.WB_SDF.fTruncatedOctahedron (final WB_Coord p, final double r, final double e) static
References wblut.math.WB_SDF.fGDF().
static double wblut.math.WB_SDF.fTruncatedOctahedron (final WB_Coord p, final double r) static
References wblut.math.WB_SDF.fGDF().
static double wblut.math.WB_SDF.pMod1 (double p, final double size) static
static void wblut.math.WB_SDF.pR45 (final WB_Vector p) static
References wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
Member Data Documentation
final WB_Vector [] wblut.math.WB_SDF.GDFVectors static
Initial value:
= new WB_Vector[] {
            normalize(new WB_Vector(1, 0, 0)), normalize(new WB_Vector(0, 1, 0)), normalize(new WB_Vector(0, 0, 1)),
            normalize(new WB_Vector(1, 1, 1)), normalize(new WB_Vector(-1, 1, 1)), normalize(new WB_Vector(1, -1, 1)),
            normalize(new WB_Vector(1, 1, -1)),
            normalize(new WB_Vector(0, 1, PHI + 1)), normalize(new WB_Vector(0, -1, PHI + 1)),
            normalize(new WB_Vector(PHI + 1, 0, 1)), normalize(new WB_Vector(-PHI - 1, 0, 1)),
            normalize(new WB_Vector(1, PHI + 1, 0)), normalize(new WB_Vector(-1, PHI + 1, 0)),
            normalize(new WB_Vector(0, PHI, 1)), normalize(new WB_Vector(0, -PHI, 1)),
            normalize(new WB_Vector(1, 0, PHI)), normalize(new WB_Vector(-1, 0, PHI)),
            normalize(new WB_Vector(PHI, 1, 0)), normalize(new WB_Vector(-PHI, 1, 0)) }
final double wblut.math.WB_SDF.PHI = Math.sqrt(5) * 0.5 + 0.5 static
final double wblut.math.WB_SDF.PI = Math.PI static
final double wblut.math.WB_SDF.TAU = 2 * 2 * PI static
The documentation for this class was generated from the following file:
src/math/wblut/math/WB_SDF.java