HE_Mesh: wblut.geom.WB_Line Class Reference
wblut.geom.WB_Line Class Reference
Public Member Functions
WB_Line ()
WB_Line (final WB_Coord o, final WB_Coord d)
WB_Line (final double ox, final double oy, final double oz, final double dx, final double dy, final double dz)
WB_Line (final double ox, final double oy, final double dx, final double dy)
String toString ()
void setFromPoints (final WB_Coord p1, final WB_Coord p2)
double getT (final WB_Coord p)
WB_Point curvePoint (final double u)
WB_Vector curveDirection (final double u)
WB_Vector curveDerivative (final double u)
double getLowerU ()
double getUpperU ()
double a ()
double b ()
double c ()
WB_Coord getDirection ()
WB_Vector getNormal ()
WB_Coord getOrigin ()
WB_Point getParametricPoint (final double t)
void getParametricPointInto (final double t, final WB_MutableCoord result)
WB_Point getPoint (final double t)
void getPointInto (final double t, final WB_MutableCoord result)
boolean equals (final Object o)
int hashCode ()
Public Member Functions inherited from wblut.geom.WB_Curve
WB_Point curvePoint (double u)
WB_Vector curveDirection (double u)
WB_Vector curveDerivative (double u)
Static Public Member Functions
static WB_Line X ()
static WB_Line Y ()
static WB_Line Z ()
Protected Member Functions
void set (final WB_Coord o, final WB_Coord d)
Protected Attributes
WB_Point origin
WB_Vector direction
Constructor & Destructor Documentation
wblut.geom.WB_Line.WB_Line ()
wblut.geom.WB_Line.WB_Line (final WB_Coord o, final WB_Coord d)
Parameters
o
d
References wblut.geom.WB_Vector.normalizeSelf().
wblut.geom.WB_Line.WB_Line (final double ox, final double oy, final double oz, final double dx, final double dy, final double dz)
Parameters
ox
oy
oz
dx
dy
dz
wblut.geom.WB_Line.WB_Line (final double ox, final double oy, final double dx, final double dy)
Parameters
ox
oy
dx
dy
Member Function Documentation
double wblut.geom.WB_Line.a ()
a.x+b.y+c=0
Returns
a for a 2D line
References wblut.geom.WB_MutableCoordinate.yd().
double wblut.geom.WB_Line.b ()
a.x+b.y+c=0
Returns
b for a 2D line
References wblut.geom.WB_MutableCoordinate.xd().
double wblut.geom.WB_Line.c ()
a.x+b.y+c=0
Returns
c for a 2D line
References wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
WB_Vector wblut.geom.WB_Line.curveDerivative (final double u)
WB_Vector wblut.geom.WB_Line.curveDirection (final double u)
WB_Point wblut.geom.WB_Line.curvePoint (final double u)
References wblut.geom.WB_Line.getPoint().
boolean wblut.geom.WB_Line.equals (final Object o)
References wblut.geom.WB_Point.equals(), wblut.geom.WB_Vector.equals(), wblut.geom.WB_Line.getDirection(), and wblut.geom.WB_Line.getOrigin().
WB_Coord wblut.geom.WB_Line.getDirection ()
Returns
References wblut.geom.WB_Line.direction.
double wblut.geom.WB_Line.getLowerU ()
Returns
Implements wblut.geom.WB_Curve.
WB_Vector wblut.geom.WB_Line.getNormal ()
Get vector perpendicular to the line
Returns
References wblut.geom.WB_Vector.cross(), wblut.math.WB_Epsilon.isZero(), and wblut.geom.WB_Vector.normalizeSelf().
WB_Coord wblut.geom.WB_Line.getOrigin ()
Returns
References wblut.geom.WB_Line.origin.
WB_Point wblut.geom.WB_Line.getParametricPoint (final double t)
Parameters
t
Returns
References wblut.geom.WB_Point.addSelf(), and wblut.geom.WB_Point.scaleSelf().
void wblut.geom.WB_Line.getParametricPointInto (final double t, final WB_MutableCoord result)
Parameters
t
result
References wblut.geom.WB_MutableCoord.set().
WB_Point wblut.geom.WB_Line.getPoint (final double t)
Parameters
t
Returns
References wblut.geom.WB_Point.addSelf(), and wblut.geom.WB_Point.scaleSelf().
void wblut.geom.WB_Line.getPointInto (final double t, final WB_MutableCoord result)
Parameters
t
result
References wblut.geom.WB_MutableCoord.set().
double wblut.geom.WB_Line.getT (final WB_Coord p)
Parameters
p
Returns
References wblut.math.WB_Math.fastAbs(), wblut.geom.WB_GeometryOp2D.getClosestPoint2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
double wblut.geom.WB_Line.getUpperU ()
Returns
Implements wblut.geom.WB_Curve.
int wblut.geom.WB_Line.hashCode ()
References wblut.geom.WB_Point.hashCode(), and wblut.geom.WB_Vector.hashCode().
void wblut.geom.WB_Line.set (final WB_Coord o, final WB_Coord d) protected
Parameters
o
d
References wblut.geom.WB_Vector.normalizeSelf().
void wblut.geom.WB_Line.setFromPoints (final WB_Coord p1, final WB_Coord p2)
Parameters
p1
p2
References wblut.geom.WB_Line.set().
String wblut.geom.WB_Line.toString ()
References wblut.geom.WB_Point.toString(), and wblut.geom.WB_Vector.toString().
static WB_Line wblut.geom.WB_Line.X () static
Returns
References wblut.geom.WB_Line.WB_Line().
static WB_Line wblut.geom.WB_Line.Y () static
Returns
References wblut.geom.WB_Line.WB_Line().
static WB_Line wblut.geom.WB_Line.Z () static
Returns
References wblut.geom.WB_Line.WB_Line().
Member Data Documentation
WB_Vector wblut.geom.WB_Line.direction protected
WB_Point wblut.geom.WB_Line.origin protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Line.java