HE_Mesh: wblut.hemesh.HET_WriterPLY Class Reference
wblut.hemesh.HET_WriterPLY Class Reference
Static Public Member Functions
static void saveMesh (final HE_Mesh mesh, final OutputStream stream)
static final int red (final int what)
static final int green (final int what)
static final int blue (final int what)
static void saveMesh (final HE_Mesh mesh, final String path, final String name)
static OutputStream createOutputStream (final File file) throws IOException
static void createDirectories (final File file)
static void saveMeshWithVertexColor (final HE_Mesh mesh, final OutputStream stream)
static void saveMeshWithVertexColor (final HE_Mesh mesh, final String path, final String name)
static void saveMeshWithFaceColor (final HE_Mesh mesh, final OutputStream stream)
static void saveMeshWithFaceColor (final HE_Mesh mesh, final String path, final String name)
Static Private Member Functions
static final byte[] le (final float f)
static final byte[] le (final int i)
Static Private Attributes
static final byte[] buf = new byte[4]
Member Function Documentation
static final int wblut.hemesh.HET_WriterPLY.blue (final int what) static
Parameters
what
Returns
static void wblut.hemesh.HET_WriterPLY.createDirectories (final File file) static
Parameters
file
static OutputStream wblut.hemesh.HET_WriterPLY.createOutputStream (final File file) throws IOException static
Parameters
file
Returns
Exceptions
IOException
References wblut.hemesh.HET_WriterPLY.createDirectories().
static final int wblut.hemesh.HET_WriterPLY.green (final int what) static
Parameters
what
Returns
static final byte [] wblut.hemesh.HET_WriterPLY.le (final float f) static private
Creates a little-endian version of the given float.
Parameters
f
Returns
static final byte [] wblut.hemesh.HET_WriterPLY.le (final int i) static private
Creates a little-endian version of the given int.
Parameters
i
Returns
References wblut.hemesh.HET_WriterPLY.buf.
static final int wblut.hemesh.HET_WriterPLY.red (final int what) static
Parameters
what
Returns
static void wblut.hemesh.HET_WriterPLY.saveMesh (final HE_Mesh mesh, final OutputStream stream) static
Parameters
mesh
stream
References wblut.hemesh.HE_Mesh.getFacesAsInt(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Mesh.getVertexNormals(), wblut.hemesh.HE_Mesh.getVerticesAsArray(), wblut.hemesh.HET_WriterPLY.le(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
static void wblut.hemesh.HET_WriterPLY.saveMesh (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
References wblut.hemesh.HET_WriterPLY.createOutputStream(), and wblut.hemesh.HET_WriterPLY.saveMesh().
static void wblut.hemesh.HET_WriterPLY.saveMeshWithFaceColor (final HE_Mesh mesh, final OutputStream stream) static
Parameters
mesh
stream
References wblut.hemesh.HET_WriterPLY.blue(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Mesh.getFacesAsInt(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Mesh.getVertexNormals(), wblut.hemesh.HE_Mesh.getVerticesAsArray(), wblut.hemesh.HET_WriterPLY.green(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HET_WriterPLY.red(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
static void wblut.hemesh.HET_WriterPLY.saveMeshWithFaceColor (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
References wblut.hemesh.HET_WriterPLY.createOutputStream(), and wblut.hemesh.HET_WriterPLY.saveMeshWithFaceColor().
static void wblut.hemesh.HET_WriterPLY.saveMeshWithVertexColor (final HE_Mesh mesh, final OutputStream stream) static
Parameters
mesh
stream
References wblut.hemesh.HET_WriterPLY.blue(), wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Mesh.getFacesAsInt(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Mesh.getVertexNormals(), wblut.hemesh.HE_Mesh.getVerticesAsArray(), wblut.hemesh.HET_WriterPLY.green(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HET_WriterPLY.red(), wblut.hemesh.HE_Mesh.vItr(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
static void wblut.hemesh.HET_WriterPLY.saveMeshWithVertexColor (final HE_Mesh mesh, final String path, final String name) static
Parameters
mesh
path
name
References wblut.hemesh.HET_WriterPLY.createOutputStream(), and wblut.hemesh.HET_WriterPLY.saveMeshWithVertexColor().
Member Data Documentation
final byte [] wblut.hemesh.HET_WriterPLY.buf = new byte[4] static private
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_WriterPLY.java