HE_Mesh: wblut.hemesh.HEM_VertexExpand Class Reference
wblut.hemesh.HEM_VertexExpand Class Reference
Public Member Functions
HEM_VertexExpand ()
HEM_VertexExpand setDistance (final double d)
HEM_VertexExpand setDistance (final WB_ScalarParameter d)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_ScalarParameter d
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_VertexExpand.HEM_VertexExpand ()
References wblut.math.WB_ScalarParameter.ZERO.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_VertexExpand.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_Mesh.vItr(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), wblut.hemesh.HE_Vertex.zd(), and wblut.math.WB_ScalarParameter.ZERO.
HE_Mesh wblut.hemesh.HEM_VertexExpand.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_Selection.vItr(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), wblut.hemesh.HE_Vertex.zd(), and wblut.math.WB_ScalarParameter.ZERO.
HEM_VertexExpand wblut.hemesh.HEM_VertexExpand.setDistance (final double d)
Parameters
d
Returns
References wblut.math.WB_ScalarParameter.ZERO.
HEM_VertexExpand wblut.hemesh.HEM_VertexExpand.setDistance (final WB_ScalarParameter d)
References wblut.hemesh.HEM_VertexExpand.d.
Member Data Documentation
WB_ScalarParameter wblut.hemesh.HEM_VertexExpand.d private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_VertexExpand.java