HE_Mesh: wblut.hemesh.HES_Smooth Class Reference
wblut.hemesh.HES_Smooth Class Reference
Public Member Functions
HES_Smooth ()
HES_Smooth setKeepEdges (final boolean b)
HES_Smooth setKeepBoundary (final boolean b)
HES_Smooth setWeight (final double origWeight, final double neigWeight)
Public Member Functions inherited from wblut.hemesh.HES_Subdividor
HES_Subdividor ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HES_Subdividor
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
boolean keepEdges = true
boolean keepBoundary = false
double origWeight
double neigWeight
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Catmull-Clark subdivision of a mesh.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HES_Smooth.HES_Smooth ()
Instantiates a new hE s_ smooth.
Member Function Documentation
HE_Mesh wblut.hemesh.HES_Smooth.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Selection.getInnerVertices(), wblut.hemesh.HE_Vertex.getNeighborVertices(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Selection.getOuterVertices(), wblut.geom.WB_Point.mulSelf(), wblut.hemesh.HES_Smooth.neigWeight, wblut.hemesh.HES_Smooth.origWeight, wblut.geom.WB_Point.scaleSelf(), wblut.hemesh.HE_Mesh.selectAllFaces(), wblut.hemesh.HE_Vertex.set(), wblut.hemesh.HET_MeshOp.splitFacesQuad(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), and wblut.hemesh.HE_Vertex.zd().
HE_Mesh wblut.hemesh.HES_Smooth.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Selection.contains(), wblut.geom.WB_Classification.FLAT, wblut.hemesh.HE_Selection.getAllBoundaryVertices(), wblut.hemesh.HE_Selection.getInnerVertices(), wblut.hemesh.HE_Vertex.getNeighborVertices(), wblut.hemesh.HE_Selection.getOuterVertices(), wblut.hemesh.HE_Mesh.getSharedFaces(), wblut.hemesh.HE_Vertex.getVertexType(), wblut.geom.WB_Point.mulSelf(), wblut.hemesh.HES_Smooth.neigWeight, wblut.hemesh.HES_Smooth.origWeight, wblut.geom.WB_Point.scaleSelf(), wblut.hemesh.HET_MeshOp.splitFacesQuad(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), and wblut.hemesh.HE_Vertex.zd().
HES_Smooth wblut.hemesh.HES_Smooth.setKeepBoundary (final boolean b)
Keep boundary edges fixed?.
Parameters
b true/false
Returns
self
HES_Smooth wblut.hemesh.HES_Smooth.setKeepEdges (final boolean b)
Keep edges of selection fixed when subdividing selection?.
Parameters
b true/false
Returns
self
HES_Smooth wblut.hemesh.HES_Smooth.setWeight (final double origWeight, final double neigWeight)
Set vertex weights?.
Parameters
origWeight weight of original vertex
neigWeight weight of neighbors
Returns
self
References wblut.hemesh.HES_Smooth.neigWeight, and wblut.hemesh.HES_Smooth.origWeight.
Member Data Documentation
boolean wblut.hemesh.HES_Smooth.keepBoundary = false private
Keep boundary?.
boolean wblut.hemesh.HES_Smooth.keepEdges = true private
Keep edges?.
double wblut.hemesh.HES_Smooth.neigWeight private
Weight of neighbor vertex.
double wblut.hemesh.HES_Smooth.origWeight private
Weight of original vertex.
The documentation for this class was generated from the following file:
src/hemesh_subdividors/wblut/hemesh/HES_Smooth.java