HE_Mesh: wblut.hemesh.HEC_SeaShell Class Reference
wblut.hemesh.HEC_SeaShell Class Reference
Public Member Functions
HEC_SeaShell ()
HEC_SeaShell setRange (final double sm, final double sM, final double thetam, final double thetaM)
HEC_SeaShell setDivisions (final double sdiv, final double thetadiv)
HEC_SeaShell setD (final double D)
HEC_SeaShell setA (final double A)
HEC_SeaShell setAlpha (final double alpha)
HEC_SeaShell setBeta (final double beta)
HEC_SeaShell setMu (final double mu)
HEC_SeaShell setOmega (final double omega)
HEC_SeaShell setPhi (final double phi)
HEC_SeaShell setMuFactor (final double muf)
HEC_SeaShell setOmegaFactor (final double omegaf)
HEC_SeaShell setPhiFactor (final double phif)
HEC_SeaShell seta (final double a)
HEC_SeaShell setb (final double b)
HEC_SeaShell setL (final double L)
HEC_SeaShell setP (final double P)
HEC_SeaShell setW1 (final double W1)
HEC_SeaShell setW2 (final double W2)
HEC_SeaShell setLFactor (final double Lf)
HEC_SeaShell setPFactor (final double Pf)
HEC_SeaShell setW1Factor (final double W1f)
HEC_SeaShell setW2Factor (final double W2f)
HEC_SeaShell setN (final double N)
HEC_SeaShell setScale (final double scale)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Member Functions
double l (final double theta)
double k (final double s, final double theta, final double lt)
double H (final double s, final double theta, final double lt)
Private Attributes
double D
double muf
double smin
double sdiv
int ssteps
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Seashell.
http://mathdl.maa.org/images/upload_library/23/picado/seashells/article.pdf
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_SeaShell.HEC_SeaShell ()
Instantiates a new seashell.
References wblut.hemesh.HEC_SeaShell.setA(), wblut.hemesh.HEC_SeaShell.seta(), wblut.hemesh.HEC_SeaShell.setAlpha(), wblut.hemesh.HEC_SeaShell.setb(), wblut.hemesh.HEC_SeaShell.setBeta(), wblut.hemesh.HEC_SeaShell.setD(), wblut.hemesh.HEC_SeaShell.setDivisions(), wblut.hemesh.HEC_SeaShell.setL(), wblut.hemesh.HEC_SeaShell.setMu(), wblut.hemesh.HEC_SeaShell.setN(), wblut.hemesh.HEC_SeaShell.setOmega(), wblut.hemesh.HEC_SeaShell.setP(), wblut.hemesh.HEC_SeaShell.setPhi(), wblut.hemesh.HEC_SeaShell.setRange(), wblut.hemesh.HEC_SeaShell.setScale(), wblut.hemesh.HEC_SeaShell.setW1(), and wblut.hemesh.HEC_SeaShell.setW2().
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_SeaShell.createBase () protected
References wblut.hemesh.HEC_FromFacelist.createBase(), wblut.hemesh.HEC_SeaShell.H(), wblut.hemesh.HEC_SeaShell.l(), wblut.hemesh.HEC_SeaShell.sdiv, wblut.hemesh.HEC_FromFacelist.setCheckNormals(), wblut.hemesh.HEC_FromFacelist.setDuplicate(), wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HEC_FromFacelist.setVertices(), and wblut.hemesh.HEC_SeaShell.ssteps.
double wblut.hemesh.HEC_SeaShell.H (final double s, final double theta, final double lt) private
Parameters
s
theta
lt
Returns
References wblut.hemesh.HEC_SeaShell.k().
double wblut.hemesh.HEC_SeaShell.k (final double s, final double theta, final double lt) private
Parameters
s
theta
lt
Returns
double wblut.hemesh.HEC_SeaShell.l (final double theta) private
Parameters
theta
Returns
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setA (final double A)
Parameters
A size of spiral aperture (distance of aperture origin to world origin at theta=0
Returns
this
HEC_SeaShell wblut.hemesh.HEC_SeaShell.seta (final double a)
Parameters
a half length of the major axis of ellipse (at the origin)
Returns
this
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setAlpha (final double alpha)
Parameters
alpha equiangular angle of spiral in degrees
Returns
this
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setb (final double b)
Parameters
b half length of the minor axis of ellipse (at the origin)
Returns
this
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setBeta (final double beta)
Parameters
beta angle between Z-axis and line from aperture local origin to world origin (in degrees)
Returns
this
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setD (final double D)
Parameters
D coiling: 1 or -1
Returns
this
References wblut.hemesh.HEC_SeaShell.D.
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setDivisions (final double sdiv, final double thetadiv)
Parameters
sdiv
thetadiv
Returns
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setL (final double L)
Parameters
L
Returns
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setLFactor (final double Lf)
Parameters
Lf change of L per full rotation
Returns
this
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setMu (final double mu)
Parameters
mu
Returns
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setMuFactor (final double muf)
Parameters
muf change of mu in degrees per full turn
Returns
this
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setN (final double N)
Parameters
N
Returns
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setOmega (final double omega)
Parameters
omega
Returns
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setOmegaFactor (final double omegaf)
Parameters
omegaf change of omega in degrees per full turn
Returns
this
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setP (final double P)
Parameters
P
Returns
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setPFactor (final double Pf)
Parameters
Pf change of P in degrees per full rotation
Returns
this
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setPhi (final double phi)
Parameters
phi
Returns
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setPhiFactor (final double phif)
Parameters
phif change of phi in degrees per full turn
Returns
this
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setRange (final double sm, final double sM, final double thetam, final double thetaM)
Parameters
sm
sM
thetam
thetaM
Returns
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setScale (final double scale)
Parameters
scale
Returns
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setW1 (final double W1)
Parameters
W1
Returns
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setW1Factor (final double W1f)
Parameters
W1f change of W1 in degrees per full rotation
Returns
this
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setW2 (final double W2)
Parameters
W2
Returns
HEC_SeaShell wblut.hemesh.HEC_SeaShell.setW2Factor (final double W2f)
Parameters
W2f change of W2 in degrees per full rotation
Returns
this
Member Data Documentation
double wblut.hemesh.HEC_SeaShell.D private
double wblut.hemesh.HEC_SeaShell.muf private
double wblut.hemesh.HEC_SeaShell.sdiv private
double wblut.hemesh.HEC_SeaShell.smin private
int wblut.hemesh.HEC_SeaShell.ssteps private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_SeaShell.java