HE_Mesh: wblut.geom.WB_Vector Class Reference
wblut.geom.WB_Vector Class Reference
Public Member Functions
WB_Vector ()
WB_Vector (final double x, final double y)
WB_Vector (final double x, final double y, final double z)
WB_Vector (final double[] x)
WB_Vector (final double[] fromPoint, final double[] toPoint)
WB_Vector (final WB_Coord v)
WB_Vector (final WB_Coord fromPoint, final WB_Coord toPoint)
WB_Vector add (final double...x)
WB_Vector add (final WB_Coord p)
WB_Vector sub (final double...x)
WB_Vector sub (final WB_Coord p)
WB_Vector mul (final double f)
WB_Vector div (final double f)
WB_Vector addMul (final double f, final double...x)
WB_Vector addMul (final double f, final WB_Coord p)
WB_Vector mulAddMul (final double f, final double g, final WB_Coord p)
WB_Vector mulAddMul (final double f, final double g, final double...x)
void addInto (final WB_MutableCoord result, final double...x)
void addInto (final WB_MutableCoord result, final WB_Coord p)
void subInto (final WB_MutableCoord result, final double...x)
void subInto (final WB_MutableCoord result, final WB_Coord p)
void mulInto (final WB_MutableCoord result, final double f)
void divInto (final WB_MutableCoord result, final double f)
void addMulInto (final WB_MutableCoord result, final double f, final double...x)
void addMulInto (final WB_MutableCoord result, final double f, final WB_Coord p)
void mulAddMulInto (final WB_MutableCoord result, final double f, final double g, final WB_Coord p)
void mulAddMulInto (final WB_MutableCoord result, final double f, final double g, final double...x)
double dot2D (final WB_Coord p)
double absDot2D (final WB_Coord p)
double dot (final WB_Coord p)
double absDot (final WB_Coord p)
WB_Vector cross (final WB_Coord p)
void crossInto (final WB_MutableCoord result, final WB_Coord p)
WB_M33 tensor (final WB_Coord v)
double scalarTriple (final WB_Coord v, final WB_Coord w)
WB_Vector addSelf (final WB_Coord p)
WB_Vector subSelf (final double...x)
WB_Vector subSelf (final WB_Coord v)
WB_Vector mulSelf (final double f)
WB_Vector divSelf (final double f)
WB_Vector addMulSelf (final double f, final double...x)
WB_Vector addMulSelf (final double f, final WB_Coord p)
WB_Vector addSelf (final double...x)
WB_Vector addSelf (final double x, final double y, final double z)
WB_Vector mulAddMulSelf (final double f, final double g, final double...x)
WB_Vector mulAddMulSelf (final double f, final double g, final WB_Coord p)
WB_Vector crossSelf (final WB_Coord p)
double normalizeSelf ()
WB_Vector trimSelf (final double d)
WB_Vector apply2D (final WB_Transform2D T)
WB_Point applyAsPoint2D (final WB_Transform2D T)
WB_Vector applyAsVector2D (final WB_Transform2D T)
WB_Vector applyAsNormal2D (final WB_Transform2D T)
void apply2DInto (final WB_MutableCoord result, final WB_Transform2D T)
void applyAsPoint2DInto (final WB_MutableCoord result, final WB_Transform2D T)
void applyAsVector2DInto (final WB_MutableCoord result, final WB_Transform2D T)
void applyAsNormal2DInto (final WB_MutableCoord result, final WB_Transform2D T)
WB_Coord translate2D (final double px, final double py)
void translate2DInto (final WB_MutableCoord result, final double px, final double py)
WB_Coord translate2D (final WB_Coord p)
void translate2DInto (final WB_MutableCoord result, final WB_Coord p)
WB_Vector rotateAboutPoint2D (final double angle, final double px, final double py)
void rotateAboutPoint2DInto (final WB_MutableCoord result, final double angle, final double px, final double py)
WB_Vector rotateAboutPoint2D (final double angle, final WB_Coord p)
void rotateAboutPoint2DInto (final WB_MutableCoord result, final double angle, final WB_Coord p)
WB_Vector rotateAboutOrigin2D (final double angle)
void rotateAboutOrigin2DInto (final WB_MutableCoord result, final double angle)
WB_Vector scale2D (final double f)
void scale2DInto (final WB_MutableCoord result, final double f)
WB_Vector scale2D (final double fx, final double fy)
void scale2DInto (final WB_MutableCoord result, final double fx, final double fy)
WB_Vector apply2DSelf (final WB_Transform2D T)
WB_Vector applyAsPoint2DSelf (final WB_Transform2D T)
WB_Vector applyAsVector2DSelf (final WB_Transform2D T)
WB_Vector applyAsNormal2DSelf (final WB_Transform2D T)
WB_Coord translate2DSelf (final double px, final double py)
WB_Coord translate2DSelf (final WB_Coord p)
WB_Vector rotateAboutPoint2DSelf (final double angle, final double px, final double py)
WB_Vector rotateAboutPoint2DSelf (final double angle, final WB_Coord p)
WB_Vector rotateAboutOrigin2DSelf (final double angle)
WB_Vector scale2DSelf (final double f)
WB_Vector scale2DSelf (final double fx, final double fy)
WB_Vector apply (final WB_Transform T)
WB_Point applyAsPoint (final WB_Transform T)
WB_Vector applyAsNormal (final WB_Transform T)
WB_Vector applyAsVector (final WB_Transform T)
void applyInto (final WB_MutableCoord result, final WB_Transform T)
void applyAsPointInto (final WB_MutableCoord result, final WB_Transform T)
void applyAsNormalInto (final WB_MutableCoord result, final WB_Transform T)
void applyAsVectorInto (final WB_MutableCoord result, final WB_Transform T)
WB_Coord translate (final double px, final double py, final double pz)
WB_Coord translateInto (final WB_MutableCoord result, final double px, final double py, final double pz)
WB_Coord translate (final WB_Coord p)
WB_Coord translateInto (final WB_MutableCoord result, final WB_Coord p)
WB_Vector rotateAboutAxis2P (final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
void rotateAboutAxis2PInto (final WB_MutableCoord result, final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
WB_Vector rotateAboutAxis2P (final double angle, final WB_Coord p1, final WB_Coord p2)
void rotateAboutAxis2PInto (final WB_MutableCoord result, final double angle, final WB_Coord p1, final WB_Coord p2)
WB_Vector rotateAboutAxis (final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
void rotateAboutAxisInto (final WB_MutableCoord result, final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
WB_Vector rotateAboutAxis (final double angle, final WB_Coord p, final WB_Coord a)
void rotateAboutAxisInto (final WB_MutableCoord result, final double angle, final WB_Coord p, final WB_Coord a)
WB_Vector rotateAboutOrigin (final double angle, final double x, final double y, final double z)
void rotateAboutOriginInto (final WB_MutableCoord result, final double angle, final double x, final double y, final double z)
WB_Vector rotateAboutOrigin (final double angle, final WB_Coord a)
void rotateAboutOriginInto (final WB_MutableCoord result, final double angle, final WB_Coord v)
WB_Vector scale (final double f)
void scaleInto (final WB_MutableCoord result, final double f)
WB_Vector scale (final double fx, final double fy, final double fz)
void scaleInto (final WB_MutableCoord result, final double fx, final double fy, final double fz)
WB_Vector applySelf (final WB_Transform T)
WB_Vector applyAsPointSelf (final WB_Transform T)
WB_Vector applyAsVectorSelf (final WB_Transform T)
WB_Vector applyAsNormalSelf (final WB_Transform T)
WB_Coord translateSelf (final double px, final double py, final double pz)
WB_Coord translateSelf (final WB_Coord p)
WB_Vector rotateAboutAxis2PSelf (final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
WB_Vector rotateAboutAxis2PSelf (final double angle, final WB_Coord p1, final WB_Coord p2)
WB_Vector rotateAboutAxisSelf (final double angle, final WB_Coord p, final WB_Coord a)
WB_Vector rotateAboutAxisSelf (final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
WB_Vector rotateAboutOriginSelf (final double angle, final double x, final double y, final double z)
WB_Vector rotateAboutOriginSelf (final double angle, final WB_Coord a)
WB_Vector scaleSelf (final double f)
WB_Vector scaleSelf (final double fx, final double fy, final double fz)
void invert ()
double[] coords ()
WB_Vector copy ()
double getDistance2D (final WB_Coord p)
double getSqDistance2D (final WB_Coord p)
double getLength2D ()
double getSqLength2D ()
double getHeading2D ()
WB_Vector getOrthoNormal2D ()
boolean isCollinear2D (final WB_Coord p, final WB_Coord q)
boolean isParallel2D (final WB_Coord p)
boolean isParallel2D (final WB_Coord p, final double t)
boolean isParallelNorm2D (final WB_Coord p)
boolean isParallelNorm2D (final WB_Coord p, final double t)
boolean isOrthogonal2D (final WB_Coord p)
boolean isOrthogonal2D (final WB_Coord p, final double t)
boolean isOrthogonalNorm2D (final WB_Coord p)
boolean isOrthogonalNorm2D (final WB_Coord p, final double t)
double getDistance3D (final WB_Coord p)
double getDistance (final WB_Coord p)
double getSqDistance3D (final WB_Coord p)
double getSqDistance (final WB_Coord p)
double getLength3D ()
double getLength ()
double getSqLength3D ()
double getSqLength ()
double getAngle (final WB_Coord p)
double getAngleNorm (final WB_Coord p)
WB_Vector getOrthoNormal3D ()
WB_Vector getOrthoNormal ()
boolean isCollinear (final WB_Coord p, final WB_Coord q)
boolean isParallel (final WB_Coord p)
boolean isParallel (final WB_Coord p, final double t)
boolean isParallelNorm (final WB_Coord p)
boolean isParallelNorm (final WB_Coord p, final double t)
boolean isOrthogonal (final WB_Coord p)
boolean isOrthogonal (final WB_Coord p, final double t)
boolean isOrthogonalNorm (final WB_Coord p)
boolean isOrthogonalNorm (final WB_Coord p, final double t)
boolean isZero ()
boolean smallerThan (final WB_Coord otherXYZ)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoordinate
WB_MutableCoordinate ()
WB_MutableCoordinate (final double x, final double y)
WB_MutableCoordinate (final double x, final double y, final double z)
WB_MutableCoordinate (final double[] x)
WB_MutableCoordinate (final double[] fromPoint, final double[] toPoint)
WB_MutableCoordinate (final WB_Coord v)
WB_MutableCoordinate (final WB_Coord fromPoint, final WB_Coord toPoint)
double getd (final int i)
float getf (final int i)
double xd ()
double yd ()
double zd ()
double wd ()
float xf ()
float yf ()
float zf ()
float wf ()
void setX (final double x)
void setY (final double y)
void setZ (final double z)
void setW (final double w)
void setCoord (final int i, final double v)
void set (final double x, final double y)
void set (final double x, final double y, final double z)
void set (final double x, final double y, final double z, final double w)
void set (final WB_Coord v)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoordinate2D
WB_MutableCoordinate2D ()
WB_MutableCoordinate2D (final double x, final double y)
WB_MutableCoordinate2D (final double[] x)
WB_MutableCoordinate2D (final double[] fromPoint, final double[] toPoint)
WB_MutableCoordinate2D (final WB_Coord v)
WB_MutableCoordinate2D (final WB_Coord fromPoint, final WB_Coord toPoint)
double getd (final int i)
float getf (final int i)
double xd ()
double yd ()
double zd ()
double wd ()
float xf ()
float yf ()
float zf ()
float wf ()
void setX (final double x)
void setY (final double y)
void setZ (final double z)
void setW (final double w)
void setCoord (final int i, final double v)
void set (final WB_Coord v)
void set (final double x, final double y)
void set (final double x, final double y, final double z)
void set (final double x, final double y, final double z, final double w)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoord
void setX (double x)
void setY (double y)
void setZ (double z)
void setW (double w)
void setCoord (int i, double v)
void set (WB_Coord p)
void set (double x, double y)
void set (double x, double y, double z)
void set (double x, double y, double z, double w)
Public Member Functions inherited from wblut.geom.WB_Coord
double getd (int i)
float getf (int i)
Public Member Functions inherited from wblut.geom.WB_MutableCoordinateTransform3D
WB_Coord translateSelf (final double px, final double py, double pz)
Public Member Functions inherited from wblut.geom.WB_CoordinateTransform3D
void applyInto (WB_MutableCoord result, final WB_Transform T)
WB_Coord translate (final double px, final double py, double pz)
WB_Coord translateInto (final WB_MutableCoord result, final double px, final double py, double pz)
void rotateAboutAxis2PInto (WB_MutableCoord result, final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
void rotateAboutAxis2PInto (WB_MutableCoord result, final double angle, final WB_Coord p1, final WB_Coord p2)
void rotateAboutAxisInto (WB_MutableCoord result, final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
void rotateAboutAxisInto (WB_MutableCoord result, final double angle, final WB_Coord p, final WB_Coord a)
void rotateAboutOriginInto (WB_MutableCoord result, final double angle, final double x, final double y, final double z)
void rotateAboutOriginInto (WB_MutableCoord result, final double angle, final WB_Coord v)
void scaleInto (WB_MutableCoord result, final double fx, final double fy, final double fz)
void scaleInto (WB_MutableCoord result, final double f)
Public Member Functions inherited from wblut.geom.WB_CoordinateTransform2D
void apply2DInto (WB_MutableCoord result, final WB_Transform2D T)
void rotateAboutPoint2DInto (WB_MutableCoord result, final double angle, final double px, final double py)
void rotateAboutPoint2DInto (WB_MutableCoord result, final double angle, final WB_Coord p)
void rotateAboutOrigin2DInto (WB_MutableCoord result, final double angle)
void scale2DInto (WB_MutableCoord result, final double fx, final double fy)
void scale2DInto (WB_MutableCoord result, final double f)
Public Member Functions inherited from wblut.geom.WB_CoordinateMetric3D
boolean isCollinear (WB_Coord p, WB_Coord q)
boolean isParallel (WB_Coord p)
boolean isParallel (WB_Coord p, double tol)
boolean isParallelNorm (WB_Coord p)
boolean isParallelNorm (WB_Coord p, double tol)
boolean isOrthogonal (WB_Coord p)
boolean isOrthogonal (WB_Coord p, double tol)
boolean isOrthogonalNorm (WB_Coord p)
boolean isOrthogonalNorm (WB_Coord p, double tol)
Public Member Functions inherited from wblut.geom.WB_CoordinateMetric2D
boolean isCollinear2D (WB_Coord p, WB_Coord q)
boolean isParallel2D (WB_Coord p)
boolean isParallel2D (WB_Coord p, double tol)
boolean isParallelNorm2D (WB_Coord p)
boolean isParallelNorm2D (WB_Coord p, double tol)
boolean isOrthogonal2D (WB_Coord p)
boolean isOrthogonal2D (WB_Coord p, double tol)
boolean isOrthogonalNorm2D (WB_Coord p)
boolean isOrthogonalNorm2D (WB_Coord p, double tol)
Static Public Member Functions
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord Z ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
static WB_Vector add (final WB_Coord p, final WB_Coord q)
static WB_Vector sub (final WB_Coord p, final WB_Coord q)
static WB_Vector subToVector2D (final WB_Coord p, final WB_Coord q)
static WB_Vector subToVector3D (final WB_Coord p, final WB_Coord q)
static WB_Vector subToVector2D (final WB_Coord p, final double x, final double y)
static WB_Vector subToVector3D (final WB_Coord p, final double x, final double y, final double z)
static WB_Vector mul (final WB_Coord p, final double f)
static WB_Vector div (final WB_Coord p, final double f)
static WB_Vector addMul (final WB_Coord p, final double f, final WB_Coord q)
static WB_Vector mulAddMul (final double f, final WB_Coord p, final double g, final WB_Coord q)
static double dot2D (final WB_Coord p, final WB_Coord q)
static double absDot2D (final WB_Coord p, final WB_Coord q)
static double dot (final WB_Coord p, final WB_Coord q)
static double absDot (final WB_Coord p, final WB_Coord q)
static WB_Vector cross (final WB_Coord p, final WB_Coord q)
static WB_M33 tensor (final WB_Coord u, final WB_Coord v)
static double scalarTriple (final WB_Coord u, final WB_Coord v, final WB_Coord w)
static double getDistance2D (final WB_Coord q, final WB_Coord p)
static double getDistance3D (final WB_Coord q, final WB_Coord p)
static double getDistance (final WB_Coord q, final WB_Coord p)
static double getSqDistance2D (final WB_Coord q, final WB_Coord p)
static double getSqDistance3D (final WB_Coord q, final WB_Coord p)
static double getSqDistance (final WB_Coord q, final WB_Coord p)
static double getLength2D (final WB_Coord p)
static double getLength3D (final WB_Coord p)
static double getLength (final WB_Coord p)
static double getSqLength2D (final WB_Coord v)
static double getSqLength3D (final WB_Coord v)
static double getSqLength (final WB_Coord v)
static double getAngle (final WB_Coord q, final WB_Coord p)
static double getAngleNorm (final WB_Coord q, final WB_Coord p)
static double getHeading2D (final WB_Coord p)
static boolean isCollinear (final WB_Coord o, final WB_Coord p, final WB_Coord q)
static boolean isCollinear2D (final WB_Coord o, final WB_Coord p, final WB_Coord q)
static boolean isParallel (final WB_Coord p, final WB_Coord q)
static boolean isParallel (final WB_Coord p, final WB_Coord q, final double t)
static boolean isParallelNorm (final WB_Coord p, final WB_Coord q)
static boolean isParallelNorm (final WB_Coord p, final WB_Coord q, final double t)
static boolean isParallel2D (final WB_Coord p, final WB_Coord q)
static boolean isParallel2D (final WB_Coord p, final WB_Coord q, final double t)
static boolean isParallelNorm2D (final WB_Coord p, final WB_Coord q)
static boolean isParallelNorm2D (final WB_Coord p, final WB_Coord q, final double t)
static boolean isOrthogonal (final WB_Coord p, final WB_Coord q)
static boolean isOrthogonal (final WB_Coord p, final WB_Coord q, final double t)
static boolean isOrthogonalNorm (final WB_Coord p, final WB_Coord q)
static boolean isOrthogonalNorm (final WB_Coord p, final WB_Coord q, final double t)
static boolean isOrthogonal2D (final WB_Coord p, final WB_Coord q)
static boolean isOrthogonal2D (final WB_Coord p, final WB_Coord q, final double t)
static boolean isOrthogonalNorm2D (final WB_Coord p, final WB_Coord q)
static boolean isOrthogonalNorm2D (final WB_Coord p, final WB_Coord q, final double t)
static WB_Vector getOrthoNormal2D (final WB_Coord p)
static WB_Vector getOrthoNormal3D (final WB_Coord p)
static WB_Vector getOrthoNormal (final WB_Coord p)
static WB_Vector interpolate (final WB_Coord v, final WB_Coord w, final double f)
static WB_Vector interpolateEase (final WB_Coord v, final WB_Coord w, final double f, final WB_Ease ease, final WB_Ease.EaseType type)
Static Public Member Functions inherited from wblut.geom.WB_MutableCoordinate
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord Z ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
Static Public Member Functions inherited from wblut.geom.WB_MutableCoordinate2D
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
Static Private Attributes
static final WB_Coord X = new WB_MutableCoordinate(1, 0, 0)
static final WB_Coord Y = new WB_MutableCoordinate(0, 1, 0)
static final WB_Coord Z = new WB_MutableCoordinate(0, 0, 1)
static final WB_Coord ORIGIN = new WB_MutableCoordinate(0, 0, 0)
static final WB_Coord ZERO = new WB_MutableCoordinate(0, 0, 0)
Constructor & Destructor Documentation
wblut.geom.WB_Vector.WB_Vector ()
wblut.geom.WB_Vector.WB_Vector (final double x, final double y)
Parameters
x
y
wblut.geom.WB_Vector.WB_Vector (final double x, final double y, final double z)
Parameters
x
y
z
wblut.geom.WB_Vector.WB_Vector (final double[] x)
Parameters
x
wblut.geom.WB_Vector.WB_Vector (final double[] fromPoint, final double[] toPoint)
Parameters
fromPoint
toPoint
wblut.geom.WB_Vector.WB_Vector (final WB_Coord v)
Parameters
v
wblut.geom.WB_Vector.WB_Vector (final WB_Coord fromPoint, final WB_Coord toPoint)
Parameters
fromPoint
toPoint
Member Function Documentation
static double wblut.geom.WB_Vector.absDot (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp3D.dot(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Vector.absDot (final WB_Coord p)
Absolute value of dot product.
Parameters
p
Returns
absolute value of dot product
Implements wblut.geom.WB_CoordinateMath3D.
References wblut.geom.WB_GeometryOp3D.dot(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
static double wblut.geom.WB_Vector.absDot2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector.absDot2D (final WB_Coord p)
Absolute value of 2D dot product.
Parameters
p
Returns
absolute value of 2D dot product
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
static WB_Vector wblut.geom.WB_Vector.add (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Vector.add (final double... x)
Add coordinate values.
Parameters
x
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.add (final WB_Coord p)
Add coordinate values.
Parameters
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_Vector.addInto (final WB_MutableCoord result, final double... x)
Add coordinate values and store in mutable coordinate.
Parameters
result
x
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_Vector.addInto (final WB_MutableCoord result, final WB_Coord p)
Add coordinate values and store in mutable coordinate.
Parameters
result
p
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
static WB_Vector wblut.geom.WB_Vector.addMul (final WB_Coord p, final double f, final WB_Coord q) static
Parameters
p
f
q
Returns
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Vector.addMul (final double f, final double... x)
Add multiple of coordinate values.
Parameters
f multiplier
x
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.addMul (final double f, final WB_Coord p)
Add multiple of coordinate values.
Parameters
f
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_Vector.addMulInto (final WB_MutableCoord result, final double f, final double... x)
Add multiple of coordinate values and store in mutable coordinate.
Parameters
result
f multiplier
x
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_Vector.addMulInto (final WB_MutableCoord result, final double f, final WB_Coord p)
Add multiple of coordinate values and store in mutable coordinate.
Parameters
result
f
p
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.addMulSelf (final double f, final double... x)
Add multiple of coordinate values.
Parameters
f multiplier
x
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.addMulSelf (final double f, final WB_Coord p)
Add multiple of coordinate values.
Parameters
f
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.addSelf (final WB_Coord p)
Add coordinate values.
Parameters
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.addSelf (final double... x)
Add coordinate values.
Parameters
x
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.addSelf (final double x, final double y, final double z)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.apply (final WB_Transform T)
Apply WB_Transform. Mode (point, vector or normal) is decided by implementation.
Parameters
T
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Transform.applyAsVector().
WB_Vector wblut.geom.WB_Vector.apply2D (final WB_Transform2D T)
Apply WB_Transform2D. Mode (point, vector or normal) is decided by implementation.
Parameters
T
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsVector2D().
void wblut.geom.WB_Vector.apply2DInto (final WB_MutableCoord result, final WB_Transform2D T)
References wblut.geom.WB_Transform2D.applyAsVector2DInto().
WB_Vector wblut.geom.WB_Vector.apply2DSelf (final WB_Transform2D T)
Parameters
T
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform2D.applyAsVector2DSelf().
WB_Vector wblut.geom.WB_Vector.applyAsNormal (final WB_Transform T)
Apply WB_Transform as normal.
Parameters
T
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Transform.applyAsNormal().
WB_Vector wblut.geom.WB_Vector.applyAsNormal2D (final WB_Transform2D T)
Apply WB_Transform2D as normal.
Parameters
T
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsNormal2D().
void wblut.geom.WB_Vector.applyAsNormal2DInto (final WB_MutableCoord result, final WB_Transform2D T)
Apply WB_Transform2D as normal.
Parameters
result
T
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsNormal2DInto().
WB_Vector wblut.geom.WB_Vector.applyAsNormal2DSelf (final WB_Transform2D T)
Parameters
T
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform2D.applyAsNormal2DSelf().
void wblut.geom.WB_Vector.applyAsNormalInto (final WB_MutableCoord result, final WB_Transform T)
Apply WB_Transform as normal.
Parameters
result
T
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Transform.applyAsNormalInto().
WB_Vector wblut.geom.WB_Vector.applyAsNormalSelf (final WB_Transform T)
Parameters
T
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform.applyAsNormalSelf().
WB_Point wblut.geom.WB_Vector.applyAsPoint (final WB_Transform T)
Apply WB_Transform as point.
Parameters
T
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Transform.applyAsPoint().
WB_Point wblut.geom.WB_Vector.applyAsPoint2D (final WB_Transform2D T)
Apply WB_Transform2D as point.
Parameters
T
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsPoint2D().
void wblut.geom.WB_Vector.applyAsPoint2DInto (final WB_MutableCoord result, final WB_Transform2D T)
Apply WB_Transform2D as point.
Parameters
result
T
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsPoint2DInto().
WB_Vector wblut.geom.WB_Vector.applyAsPoint2DSelf (final WB_Transform2D T)
Parameters
T
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform2D.applyAsPoint2DSelf().
void wblut.geom.WB_Vector.applyAsPointInto (final WB_MutableCoord result, final WB_Transform T)
Apply WB_Transform as point.
Parameters
result
T
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Transform.applyAsPointInto().
WB_Vector wblut.geom.WB_Vector.applyAsPointSelf (final WB_Transform T)
Parameters
T
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform.applyAsPointSelf().
WB_Vector wblut.geom.WB_Vector.applyAsVector (final WB_Transform T)
Apply WB_Transform as vector.
Parameters
T
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Transform.applyAsVector().
WB_Vector wblut.geom.WB_Vector.applyAsVector2D (final WB_Transform2D T)
Apply WB_Transform2D as vector.
Parameters
T
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsVector2D().
void wblut.geom.WB_Vector.applyAsVector2DInto (final WB_MutableCoord result, final WB_Transform2D T)
Apply WB_Transform2D as vector.
Parameters
result
T
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.applyAsVector2DInto().
WB_Vector wblut.geom.WB_Vector.applyAsVector2DSelf (final WB_Transform2D T)
Parameters
T
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform2D.applyAsVector2DSelf().
void wblut.geom.WB_Vector.applyAsVectorInto (final WB_MutableCoord result, final WB_Transform T)
Apply WB_Transform as vector.
Parameters
result
T
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Transform.applyAsVectorInto().
WB_Vector wblut.geom.WB_Vector.applyAsVectorSelf (final WB_Transform T)
Parameters
T
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform.applyAsVectorSelf().
void wblut.geom.WB_Vector.applyInto (final WB_MutableCoord result, final WB_Transform T)
References wblut.geom.WB_Transform.applyAsVectorInto().
WB_Vector wblut.geom.WB_Vector.applySelf (final WB_Transform T)
Parameters
T
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Vector.applyAsVectorSelf().
int wblut.geom.WB_Vector.compareTo (final WB_Coord p)
References wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
int wblut.geom.WB_Vector.compareToY1st (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
double [] wblut.geom.WB_Vector.coords ()
Returns
References wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.copy ()
Returns
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
static WB_Vector wblut.geom.WB_Vector.cross (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Vector.cross (final WB_Coord p)
Cross product of this coordinate with other coordinate.
Parameters
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath3D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_Vector.crossInto (final WB_MutableCoord result, final WB_Coord p)
Store cross product of this coordinate with other coordinate in mutable coordinate. coordinate.
Parameters
result
p
Implements wblut.geom.WB_CoordinateMath3D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.crossSelf (final WB_Coord p)
Parameters
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
static WB_Vector wblut.geom.WB_Vector.div (final WB_Coord p, final double f) static
Parameters
p
f
Returns
References wblut.geom.WB_Vector.mul().
WB_Vector wblut.geom.WB_Vector.div (final double f)
Divide by factor.
Parameters
f
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector.mul().
void wblut.geom.WB_Vector.divInto (final WB_MutableCoord result, final double f)
Divide by factor and store in mutable coordinate.
Parameters
result
f
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector.mulInto().
WB_Vector wblut.geom.WB_Vector.divSelf (final double f)
Divide by factor.
Parameters
f
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath3D.
References wblut.geom.WB_Vector.mulSelf().
static double wblut.geom.WB_Vector.dot (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp3D.dot(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Vector.dot (final WB_Coord p)
dot product.
Parameters
p
Returns
dot product
Implements wblut.geom.WB_CoordinateMath3D.
References wblut.geom.WB_GeometryOp3D.dot(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
static double wblut.geom.WB_Vector.dot2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector.dot2D (final WB_Coord p)
2D dot product.
Parameters
p
Returns
2D dot product
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_GeometryOp2D.dot2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
boolean wblut.geom.WB_Vector.equals (final Object o)
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
static double wblut.geom.WB_Vector.getAngle (final WB_Coord q, final WB_Coord p) static
Parameters
q
p
Returns
References wblut.geom.WB_GeometryOp3D.getAngleBetween(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Vector.getAngle (final WB_Coord p)
Angle between two vectors.
Parameters
p
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_GeometryOp3D.getAngleBetween(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
static double wblut.geom.WB_Vector.getAngleNorm (final WB_Coord q, final WB_Coord p) static
Parameters
q
p
Returns
References wblut.geom.WB_GeometryOp3D.getAngleBetweenNorm(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Vector.getAngleNorm (final WB_Coord p)
Angle between two normalized vectors.
Parameters
p
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_GeometryOp3D.getAngleBetweenNorm(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
static double wblut.geom.WB_Vector.getDistance (final WB_Coord q, final WB_Coord p) static
Parameters
q
p
Returns
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Vector.getDistance (final WB_Coord p)
3D distance to coordinate
Parameters
p
Returns
Implements wblut.geom.WB_CoordinateMetric3D.
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
static double wblut.geom.WB_Vector.getDistance2D (final WB_Coord q, final WB_Coord p) static
Parameters
q
p
Returns
References wblut.geom.WB_GeometryOp2D.getDistance2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector.getDistance2D (final WB_Coord p)
2D distance to coordinate
Parameters
p
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_GeometryOp2D.getDistance2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
static double wblut.geom.WB_Vector.getDistance3D (final WB_Coord q, final WB_Coord p) static
Parameters
q
p
Returns
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Vector.getDistance3D (final WB_Coord p)
Parameters
p
Returns
Implements wblut.geom.WB_CoordinateMetric3D.
References wblut.geom.WB_Vector.getDistance().
static double wblut.geom.WB_Vector.getHeading2D (final WB_Coord p) static
Parameters
p
Returns
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector.getHeading2D ()
2D heading of vector.
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static double wblut.geom.WB_Vector.getLength (final WB_Coord p) static
Parameters
p
Returns
References wblut.geom.WB_GeometryOp3D.getLength3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Vector.getLength ()
Length of 3D coordinate.
Returns
Implements wblut.geom.WB_CoordinateMetric3D.
References wblut.geom.WB_GeometryOp3D.getLength3D(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
static double wblut.geom.WB_Vector.getLength2D (final WB_Coord p) static
Parameters
p
Returns
References wblut.geom.WB_GeometryOp2D.getLength2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector.getLength2D ()
Length of 2D coordinate.
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_GeometryOp2D.getLength2D(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static double wblut.geom.WB_Vector.getLength3D (final WB_Coord p) static
Parameters
p
Returns
References wblut.geom.WB_GeometryOp3D.getLength3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Vector.getLength3D ()
Returns
Implements wblut.geom.WB_CoordinateMetric3D.
References wblut.geom.WB_Vector.getLength().
static WB_Vector wblut.geom.WB_Vector.getOrthoNormal (final WB_Coord p) static
Parameters
p
Returns
References wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Vector.getOrthoNormal ()
Get vector perpendicular and CCW to this one.
Returns
Implements wblut.geom.WB_CoordinateMetric3D.
References wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.zd().
static WB_Vector wblut.geom.WB_Vector.getOrthoNormal2D (final WB_Coord p) static
Parameters
p
Returns
References wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_Vector.getOrthoNormal2D ()
Get 2D vector perpendicular and CCW to this one.
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static WB_Vector wblut.geom.WB_Vector.getOrthoNormal3D (final WB_Coord p) static
Parameters
p
Returns
References wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Vector.getOrthoNormal3D ()
Returns
Implements wblut.geom.WB_CoordinateMetric3D.
References wblut.geom.WB_Vector.getOrthoNormal().
static double wblut.geom.WB_Vector.getSqDistance (final WB_Coord q, final WB_Coord p) static
Parameters
q
p
Returns
References wblut.geom.WB_GeometryOp3D.getSqDistance3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Vector.getSqDistance (final WB_Coord p)
Square 3D distance to coordinate.
Parameters
p
Returns
Implements wblut.geom.WB_CoordinateMetric3D.
References wblut.geom.WB_GeometryOp3D.getSqDistance3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
static double wblut.geom.WB_Vector.getSqDistance2D (final WB_Coord q, final WB_Coord p) static
Parameters
q
p
Returns
References wblut.geom.WB_GeometryOp2D.getSqDistance2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector.getSqDistance2D (final WB_Coord p)
Square 2D distance to coordinate.
Parameters
p
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_GeometryOp2D.getSqDistance2D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
static double wblut.geom.WB_Vector.getSqDistance3D (final WB_Coord q, final WB_Coord p) static
Parameters
q
p
Returns
References wblut.geom.WB_GeometryOp3D.getSqDistance3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Vector.getSqDistance3D (final WB_Coord p)
Parameters
p
Returns
Implements wblut.geom.WB_CoordinateMetric3D.
References wblut.geom.WB_Vector.getSqDistance().
static double wblut.geom.WB_Vector.getSqLength (final WB_Coord v) static
Parameters
v
Returns
References wblut.geom.WB_GeometryOp3D.getSqLength3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Vector.getSqLength ()
Square length of 3D coordinate.
Returns
Implements wblut.geom.WB_CoordinateMetric3D.
References wblut.geom.WB_GeometryOp3D.getSqLength3D(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
static double wblut.geom.WB_Vector.getSqLength2D (final WB_Coord v) static
Parameters
v
Returns
References wblut.geom.WB_GeometryOp2D.getSqLength2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
double wblut.geom.WB_Vector.getSqLength2D ()
Square length of 2D coordinate.
Returns
Implements wblut.geom.WB_CoordinateMetric2D.
References wblut.geom.WB_GeometryOp2D.getSqLength2D(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static double wblut.geom.WB_Vector.getSqLength3D (final WB_Coord v) static
Parameters
v
Returns
References wblut.geom.WB_GeometryOp3D.getSqLength3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Vector.getSqLength3D ()
Implements wblut.geom.WB_CoordinateMetric3D.
References wblut.geom.WB_Vector.getSqLength().
int wblut.geom.WB_Vector.hashCode ()
References wblut.math.WB_HashCode.calculateHashCode(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static WB_Vector wblut.geom.WB_Vector.interpolate (final WB_Coord v, final WB_Coord w, final double f) static
References wblut.geom.WB_GeometryOp3D.interpolate(), wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static WB_Vector wblut.geom.WB_Vector.interpolateEase (final WB_Coord v, final WB_Coord w, final double f, final WB_Ease ease, final WB_Ease.EaseType type) static
References wblut.geom.WB_GeometryOp3D.interpolateEase(), wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_Vector.invert ()
References wblut.geom.WB_Vector.mulSelf().
static boolean wblut.geom.WB_Vector.isCollinear (final WB_Coord o, final WB_Coord p, final WB_Coord q) static
Parameters
o
p
q
Returns
References wblut.geom.WB_GeometryOp3D.isCollinear().
boolean wblut.geom.WB_Vector.isCollinear (final WB_Coord p, final WB_Coord q)
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp3D.isCollinear().
static boolean wblut.geom.WB_Vector.isCollinear2D (final WB_Coord o, final WB_Coord p, final WB_Coord q) static
Parameters
o
p
q
Returns
References wblut.geom.WB_GeometryOp2D.isCollinear2D().
boolean wblut.geom.WB_Vector.isCollinear2D (final WB_Coord p, final WB_Coord q)
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.isCollinear2D().
static boolean wblut.geom.WB_Vector.isOrthogonal (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp3D.isOrthogonal().
static boolean wblut.geom.WB_Vector.isOrthogonal (final WB_Coord p, final WB_Coord q, final double t) static
Parameters
p
q
t
Returns
References wblut.geom.WB_GeometryOp3D.isOrthogonal().
boolean wblut.geom.WB_Vector.isOrthogonal (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp3D.isOrthogonal().
boolean wblut.geom.WB_Vector.isOrthogonal (final WB_Coord p, final double t)
Parameters
p
t
Returns
References wblut.geom.WB_GeometryOp3D.isOrthogonal().
static boolean wblut.geom.WB_Vector.isOrthogonal2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonal2D().
static boolean wblut.geom.WB_Vector.isOrthogonal2D (final WB_Coord p, final WB_Coord q, final double t) static
Parameters
p
q
t
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonal2D().
boolean wblut.geom.WB_Vector.isOrthogonal2D (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonal2D().
boolean wblut.geom.WB_Vector.isOrthogonal2D (final WB_Coord p, final double t)
Parameters
p
t
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonal2D().
static boolean wblut.geom.WB_Vector.isOrthogonalNorm (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp3D.isOrthogonalNorm().
static boolean wblut.geom.WB_Vector.isOrthogonalNorm (final WB_Coord p, final WB_Coord q, final double t) static
Parameters
p
q
t
Returns
References wblut.geom.WB_GeometryOp3D.isOrthogonalNorm().
boolean wblut.geom.WB_Vector.isOrthogonalNorm (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp3D.isOrthogonalNorm().
boolean wblut.geom.WB_Vector.isOrthogonalNorm (final WB_Coord p, final double t)
Parameters
p
t
Returns
References wblut.geom.WB_GeometryOp3D.isOrthogonalNorm().
static boolean wblut.geom.WB_Vector.isOrthogonalNorm2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonalNorm2D().
static boolean wblut.geom.WB_Vector.isOrthogonalNorm2D (final WB_Coord p, final WB_Coord q, final double t) static
Parameters
p
q
t
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonalNorm2D().
boolean wblut.geom.WB_Vector.isOrthogonalNorm2D (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonalNorm2D().
boolean wblut.geom.WB_Vector.isOrthogonalNorm2D (final WB_Coord p, final double t)
Parameters
p
t
Returns
References wblut.geom.WB_GeometryOp2D.isOrthogonalNorm2D().
static boolean wblut.geom.WB_Vector.isParallel (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp3D.isParallel().
static boolean wblut.geom.WB_Vector.isParallel (final WB_Coord p, final WB_Coord q, final double t) static
Parameters
p
q
t
Returns
References wblut.geom.WB_GeometryOp3D.isParallel().
boolean wblut.geom.WB_Vector.isParallel (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp3D.isParallel().
boolean wblut.geom.WB_Vector.isParallel (final WB_Coord p, final double t)
Parameters
p
t
Returns
References wblut.geom.WB_GeometryOp3D.isParallel().
static boolean wblut.geom.WB_Vector.isParallel2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.isParallel2D().
static boolean wblut.geom.WB_Vector.isParallel2D (final WB_Coord p, final WB_Coord q, final double t) static
Parameters
p
q
t
Returns
References wblut.geom.WB_GeometryOp2D.isParallel2D().
boolean wblut.geom.WB_Vector.isParallel2D (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp2D.isParallel2D().
boolean wblut.geom.WB_Vector.isParallel2D (final WB_Coord p, final double t)
Parameters
p
t
Returns
References wblut.geom.WB_GeometryOp2D.isParallel2D().
static boolean wblut.geom.WB_Vector.isParallelNorm (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp3D.isParallelNorm().
static boolean wblut.geom.WB_Vector.isParallelNorm (final WB_Coord p, final WB_Coord q, final double t) static
Parameters
p
q
t
Returns
References wblut.geom.WB_GeometryOp3D.isParallelNorm().
boolean wblut.geom.WB_Vector.isParallelNorm (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp3D.isParallelNorm().
boolean wblut.geom.WB_Vector.isParallelNorm (final WB_Coord p, final double t)
Parameters
p
t
Returns
References wblut.geom.WB_GeometryOp3D.isParallelNorm().
static boolean wblut.geom.WB_Vector.isParallelNorm2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_GeometryOp2D.isParallelNorm2D().
static boolean wblut.geom.WB_Vector.isParallelNorm2D (final WB_Coord p, final WB_Coord q, final double t) static
Parameters
p
q
t
Returns
References wblut.geom.WB_GeometryOp2D.isParallelNorm2D().
boolean wblut.geom.WB_Vector.isParallelNorm2D (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryOp2D.isParallelNorm2D().
boolean wblut.geom.WB_Vector.isParallelNorm2D (final WB_Coord p, final double t)
Parameters
p
t
Returns
References wblut.geom.WB_GeometryOp2D.isParallelNorm2D().
boolean wblut.geom.WB_Vector.isZero ()
Is this a degenerate vector?
Returns
Implements wblut.geom.WB_CoordinateMetric3D.
References wblut.geom.WB_GeometryOp3D.isZero3D(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
static WB_Vector wblut.geom.WB_Vector.mul (final WB_Coord p, final double f) static
Parameters
p
f
Returns
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Vector.mul (final double f)
Multiply by factor.
Parameters
f
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
static WB_Vector wblut.geom.WB_Vector.mulAddMul (final double f, final WB_Coord p, final double g, final WB_Coord q) static
Parameters
f
p
g
q
Returns
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Vector.mulAddMul (final double f, final double g, final WB_Coord p)
Multiply this coordinate by factor f and add other coordinate values multiplied by g.
Parameters
f
g
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.mulAddMul (final double f, final double g, final double... x)
Multiply this coordinate by factor f and add other coordinate values multiplied by g.
Parameters
f
g
x
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_Vector.mulAddMulInto (final WB_MutableCoord result, final double f, final double g, final WB_Coord p)
Multiply this coordinate by factor f, add other coordinate values multiplied by g and store result in mutable coordinate.
Parameters
result
f
g
p
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_Vector.mulAddMulInto (final WB_MutableCoord result, final double f, final double g, final double... x)
Multiply this coordinate by factor f, add other coordinate values multiplied by g and store result in mutable coordinate.
Parameters
result
f
g
x
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.mulAddMulSelf (final double f, final double g, final double... x)
Multiply this coordinate by factor f and add other coordinate values multiplied by g.
Parameters
f
g
x
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.mulAddMulSelf (final double f, final double g, final WB_Coord p)
Multiply this coordinate by factor f and add other coordinate values multiplied by g.
Parameters
f
g
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_Vector.mulInto (final WB_MutableCoord result, final double f)
Multiply by factor and store in mutable coordinate.
Parameters
result
f
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector.scaleInto().
WB_Vector wblut.geom.WB_Vector.mulSelf (final double f)
Multiply by factor.
Parameters
f
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
double wblut.geom.WB_Vector.normalizeSelf ()
Normalize this vector. Return the length before normalization. If this vector is degenerate 0 is returned and the vector remains the zero vector.
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath3D.
References wblut.geom.WB_Vector.getLength(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
static WB_Coord wblut.geom.WB_Vector.ORIGIN () static
Returns
WB_Vector wblut.geom.WB_Vector.rotateAboutAxis (final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
Rotate around axis defined by point and direction.
Parameters
angle
px
py
pz
ax
ay
az
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Transform.addRotateAboutAxis(), wblut.geom.WB_Transform.applyAsVectorSelf(), and wblut.geom.WB_Vector.WB_Vector().
WB_Vector wblut.geom.WB_Vector.rotateAboutAxis (final double angle, final WB_Coord p, final WB_Coord a)
Rotate around axis defined by point and direction.
Parameters
angle
p
a
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Transform.addRotateAboutAxis(), wblut.geom.WB_Transform.applyAsVectorSelf(), and wblut.geom.WB_Vector.WB_Vector().
WB_Vector wblut.geom.WB_Vector.rotateAboutAxis2P (final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
Rotate around axis defined by two points.
Parameters
angle
p1x
p1y
p1z
p2x
p2y
p2z
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Transform.addRotateAboutAxis(), wblut.geom.WB_Transform.applyAsVectorSelf(), and wblut.geom.WB_Vector.WB_Vector().
WB_Vector wblut.geom.WB_Vector.rotateAboutAxis2P (final double angle, final WB_Coord p1, final WB_Coord p2)
Parameters
angle
p1
p2
Returns
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Transform.addRotateAboutAxis(), wblut.geom.WB_Transform.applyAsVectorSelf(), and wblut.geom.WB_Vector.WB_Vector().
void wblut.geom.WB_Vector.rotateAboutAxis2PInto (final WB_MutableCoord result, final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
References wblut.geom.WB_Transform.addRotateAboutAxis(), wblut.geom.WB_Transform.applyAsVectorInto(), and wblut.geom.WB_Vector.WB_Vector().
void wblut.geom.WB_Vector.rotateAboutAxis2PInto (final WB_MutableCoord result, final double angle, final WB_Coord p1, final WB_Coord p2)
References wblut.geom.WB_Transform.addRotateAboutAxis(), wblut.geom.WB_Transform.applyAsVectorInto(), and wblut.geom.WB_Vector.WB_Vector().
WB_Vector wblut.geom.WB_Vector.rotateAboutAxis2PSelf (final double angle, final double p1x, final double p1y, final double p1z, final double p2x, final double p2y, final double p2z)
Parameters
angle
p1x
p1y
p1z
p2x
p2y
p2z
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform.addRotateAboutAxis(), wblut.geom.WB_Transform.applyAsVectorSelf(), and wblut.geom.WB_Vector.WB_Vector().
WB_Vector wblut.geom.WB_Vector.rotateAboutAxis2PSelf (final double angle, final WB_Coord p1, final WB_Coord p2)
Parameters
angle
p1
p2
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform.addRotateAboutAxis(), wblut.geom.WB_Transform.applyAsVectorSelf(), and wblut.geom.WB_Vector.WB_Vector().
void wblut.geom.WB_Vector.rotateAboutAxisInto (final WB_MutableCoord result, final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
References wblut.geom.WB_Transform.addRotateAboutAxis(), wblut.geom.WB_Transform.applyAsVectorInto(), and wblut.geom.WB_Vector.WB_Vector().
void wblut.geom.WB_Vector.rotateAboutAxisInto (final WB_MutableCoord result, final double angle, final WB_Coord p, final WB_Coord a)
References wblut.geom.WB_Transform.addRotateAboutAxis(), and wblut.geom.WB_Transform.applyAsVectorInto().
WB_Vector wblut.geom.WB_Vector.rotateAboutAxisSelf (final double angle, final WB_Coord p, final WB_Coord a)
Parameters
angle
p
a
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform.addRotateAboutAxis(), and wblut.geom.WB_Transform.applyAsVectorSelf().
WB_Vector wblut.geom.WB_Vector.rotateAboutAxisSelf (final double angle, final double px, final double py, final double pz, final double ax, final double ay, final double az)
Parameters
angle
px
py
pz
ax
ay
az
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform.addRotateAboutAxis(), wblut.geom.WB_Transform.applyAsVectorSelf(), and wblut.geom.WB_Vector.WB_Vector().
WB_Vector wblut.geom.WB_Vector.rotateAboutOrigin (final double angle, final double x, final double y, final double z)
Rotate around axis defined by origin and direction.
Parameters
angle
x
y
z
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Transform.addRotateAboutOrigin(), wblut.geom.WB_Transform.applyAsVectorSelf(), and wblut.geom.WB_Vector.WB_Vector().
WB_Vector wblut.geom.WB_Vector.rotateAboutOrigin (final double angle, final WB_Coord v)
Rotate around axis defined by origin and direction.
Parameters
angle
v
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Transform.addRotateAboutOrigin(), wblut.geom.WB_Transform.applyAsVectorSelf(), and wblut.geom.WB_Vector.WB_Vector().
WB_Vector wblut.geom.WB_Vector.rotateAboutOrigin2D (final double angle)
Rotate around origin.
Parameters
angle
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.addRotateAboutOrigin(), wblut.geom.WB_Transform2D.applyAsVector2DSelf(), and wblut.geom.WB_Vector.WB_Vector().
void wblut.geom.WB_Vector.rotateAboutOrigin2DInto (final WB_MutableCoord result, final double angle)
References wblut.geom.WB_Transform2D.addRotateAboutOrigin(), and wblut.geom.WB_Transform2D.applyAsVector2DInto().
WB_Vector wblut.geom.WB_Vector.rotateAboutOrigin2DSelf (final double angle)
Parameters
angle
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform2D.addRotateAboutOrigin(), and wblut.geom.WB_Transform2D.applyAsVector2DSelf().
void wblut.geom.WB_Vector.rotateAboutOriginInto (final WB_MutableCoord result, final double angle, final double x, final double y, final double z)
References wblut.geom.WB_Transform.addRotateAboutOrigin(), wblut.geom.WB_Transform.applyAsVectorInto(), and wblut.geom.WB_Vector.WB_Vector().
void wblut.geom.WB_Vector.rotateAboutOriginInto (final WB_MutableCoord result, final double angle, final WB_Coord v)
References wblut.geom.WB_Transform.addRotateAboutOrigin(), and wblut.geom.WB_Transform.applyAsVectorInto().
WB_Vector wblut.geom.WB_Vector.rotateAboutOriginSelf (final double angle, final double x, final double y, final double z)
Parameters
angle
x
y
z
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform.addRotateAboutOrigin(), wblut.geom.WB_Transform.applyAsVectorSelf(), and wblut.geom.WB_Vector.WB_Vector().
WB_Vector wblut.geom.WB_Vector.rotateAboutOriginSelf (final double angle, final WB_Coord v)
Parameters
angle
v
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform.addRotateAboutOrigin(), and wblut.geom.WB_Transform.applyAsVectorSelf().
WB_Vector wblut.geom.WB_Vector.rotateAboutPoint2D (final double angle, final double px, final double py)
Rotate around point.
Parameters
angle
px
py
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.addRotateAboutPoint(), wblut.geom.WB_Transform2D.applyAsVector2DSelf(), and wblut.geom.WB_Vector.WB_Vector().
WB_Vector wblut.geom.WB_Vector.rotateAboutPoint2D (final double angle, final WB_Coord p)
Rotate around point.
Parameters
angle
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Transform2D.addRotateAboutPoint(), wblut.geom.WB_Transform2D.applyAsVector2DSelf(), and wblut.geom.WB_Vector.WB_Vector().
void wblut.geom.WB_Vector.rotateAboutPoint2DInto (final WB_MutableCoord result, final double angle, final double px, final double py)
References wblut.geom.WB_Transform2D.addRotateAboutPoint(), and wblut.geom.WB_Transform2D.applyAsVector2DInto().
void wblut.geom.WB_Vector.rotateAboutPoint2DInto (final WB_MutableCoord result, final double angle, final WB_Coord p)
References wblut.geom.WB_Transform2D.addRotateAboutPoint(), and wblut.geom.WB_Transform2D.applyAsVector2DInto().
WB_Vector wblut.geom.WB_Vector.rotateAboutPoint2DSelf (final double angle, final double px, final double py)
Parameters
angle
px
py
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform2D.addRotateAboutPoint(), and wblut.geom.WB_Transform2D.applyAsVector2DSelf().
WB_Vector wblut.geom.WB_Vector.rotateAboutPoint2DSelf (final double angle, final WB_Coord p)
Parameters
angle
p
Returns
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Transform2D.addRotateAboutPoint(), and wblut.geom.WB_Transform2D.applyAsVector2DSelf().
static double wblut.geom.WB_Vector.scalarTriple (final WB_Coord u, final WB_Coord v, final WB_Coord w) static
Parameters
u
v
w
Returns
References wblut.geom.WB_GeometryOp3D.scalarTriple(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
double wblut.geom.WB_Vector.scalarTriple (final WB_Coord v, final WB_Coord w)
Scalar triple: this.(v x w)
Parameters
v
w
Returns
scalar triple
Implements wblut.geom.WB_CoordinateMath3D.
References wblut.geom.WB_GeometryOp3D.scalarTriple(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.scale (final double f)
Parameters
f
Returns
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Vector.mul().
WB_Vector wblut.geom.WB_Vector.scale (final double fx, final double fy, final double fz)
Parameters
fx
fy
fz
Returns
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.scale2D (final double f)
Uniform scale.
Parameters
f
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Vector.mul().
WB_Vector wblut.geom.WB_Vector.scale2D (final double fx, final double fy)
Non-uniform scale.
Parameters
fx
fy
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
void wblut.geom.WB_Vector.scale2DInto (final WB_MutableCoord result, final double f)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
void wblut.geom.WB_Vector.scale2DInto (final WB_MutableCoord result, final double fx, final double fy)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
WB_Vector wblut.geom.WB_Vector.scale2DSelf (final double f)
Parameters
f
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Vector.mulSelf().
WB_Vector wblut.geom.WB_Vector.scale2DSelf (final double fx, final double fy)
Parameters
fx
fy
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
void wblut.geom.WB_Vector.scaleInto (final WB_MutableCoord result, final double f)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_Vector.scaleInto (final WB_MutableCoord result, final double fx, final double fy, final double fz)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.scaleSelf (final double f)
Parameters
f
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_Vector.mulSelf().
WB_Vector wblut.geom.WB_Vector.scaleSelf (final double fx, final double fy, final double fz)
Parameters
fx
fy
fz
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
boolean wblut.geom.WB_Vector.smallerThan (final WB_Coord otherXYZ)
Parameters
otherXYZ
Returns
References wblut.math.WB_Epsilon.compareAbs(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
static WB_Vector wblut.geom.WB_Vector.sub (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_Vector.sub (final double... x)
Subtract coordinate values.
Parameters
x
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.sub (final WB_Coord p)
Subtract coordinate values.
Parameters
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_Vector.subInto (final WB_MutableCoord result, final double... x)
Subtract coordinate values and store in mutable coordinate.
Parameters
result
x
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_Vector.subInto (final WB_MutableCoord result, final WB_Coord p)
Subtract coordinate values and store in mutable coordinate.
Parameters
result
p
Implements wblut.geom.WB_CoordinateMath2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.subSelf (final double... x)
Subtract coordinate values.
Parameters
x
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.subSelf (final WB_Coord p)
Subtract coordinate values.
Parameters
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
static WB_Vector wblut.geom.WB_Vector.subToVector2D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static WB_Vector wblut.geom.WB_Vector.subToVector2D (final WB_Coord p, final double x, final double y) static
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static WB_Vector wblut.geom.WB_Vector.subToVector3D (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static WB_Vector wblut.geom.WB_Vector.subToVector3D (final WB_Coord p, final double x, final double y, final double z) static
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static WB_M33 wblut.geom.WB_Vector.tensor (final WB_Coord u, final WB_Coord v) static
Parameters
u
v
Returns
References wblut.geom.WB_GeometryOp3D.tensor3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_M33 wblut.geom.WB_Vector.tensor (final WB_Coord v)
Tensor product.
Parameters
v
Returns
tensor product
Implements wblut.geom.WB_CoordinateMath3D.
References wblut.geom.WB_GeometryOp3D.tensor3D(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
String wblut.geom.WB_Vector.toString ()
References wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Coord wblut.geom.WB_Vector.translate (final double px, final double py, final double pz)
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Coord wblut.geom.WB_Vector.translate (final WB_Coord p)
3D translate.
Parameters
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Coord wblut.geom.WB_Vector.translate2D (final double px, final double py)
2D translate.
Parameters
px
py
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
WB_Coord wblut.geom.WB_Vector.translate2D (final WB_Coord p)
2D translate.
Parameters
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_Vector.WB_Vector(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
void wblut.geom.WB_Vector.translate2DInto (final WB_MutableCoord result, final double px, final double py)
2D translate.
Parameters
result
px
py
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
void wblut.geom.WB_Vector.translate2DInto (final WB_MutableCoord result, final WB_Coord p)
2D translate.
Parameters
result
p
Implements wblut.geom.WB_CoordinateTransform2D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
WB_Coord wblut.geom.WB_Vector.translate2DSelf (final double px, final double py)
2D translate.
Parameters
px
py
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
WB_Coord wblut.geom.WB_Vector.translate2DSelf (final WB_Coord p)
2D translate.
Parameters
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
WB_Coord wblut.geom.WB_Vector.translateInto (final WB_MutableCoord result, final double px, final double py, final double pz)
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Coord wblut.geom.WB_Vector.translateInto (final WB_MutableCoord result, final WB_Coord p)
3D translate.
Parameters
result
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateTransform3D.
References wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Coord wblut.geom.WB_Vector.translateSelf (final double px, final double py, final double pz)
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Coord wblut.geom.WB_Vector.translateSelf (final WB_Coord p)
3D translate.
Parameters
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateTransform3D.
References wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate.zd().
WB_Vector wblut.geom.WB_Vector.trimSelf (final double d)
If vector is larger than given value, trim vector.
Parameters
d
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath3D.
References wblut.geom.WB_Vector.getSqLength(), wblut.geom.WB_Vector.mulSelf(), and wblut.geom.WB_Vector.normalizeSelf().
static WB_Coord wblut.geom.WB_Vector.X () static
Returns
static WB_Coord wblut.geom.WB_Vector.Y () static
Returns
static WB_Coord wblut.geom.WB_Vector.Z () static
Returns
static WB_Coord wblut.geom.WB_Vector.ZERO () static
Returns
Member Data Documentation
final WB_Coord wblut.geom.WB_Vector.ORIGIN = new WB_MutableCoordinate(0, 0, 0) static private
final WB_Coord wblut.geom.WB_Vector.X = new WB_MutableCoordinate(1, 0, 0) static private
final WB_Coord wblut.geom.WB_Vector.Y = new WB_MutableCoordinate(0, 1, 0) static private
final WB_Coord wblut.geom.WB_Vector.Z = new WB_MutableCoordinate(0, 0, 1) static private
final WB_Coord wblut.geom.WB_Vector.ZERO = new WB_MutableCoordinate(0, 0, 0) static private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Vector.java