HE_Mesh: wblut.hemesh.HEM_Noise Class Reference
wblut.hemesh.HEM_Noise Class Reference
Public Member Functions
HEM_Noise ()
HEM_Noise setDistance (final double d)
HEM_Noise setSeed (final long seed)
HEM_Noise setDistance (final WB_ScalarParameter d)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_ScalarParameter d
final WB_RandomOnSphere rs
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Expands or contracts all vertices along the vertex normals.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_Noise.HEM_Noise ()
Instantiates a new hE m_ noise.
References wblut.hemesh.HEM_Noise.setDistance().
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Noise.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Point.addSelf(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_RandomOnSphere.nextVector(), wblut.geom.WB_RandomOnSphere.reset(), wblut.hemesh.HE_Mesh.vItr(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), wblut.hemesh.HE_Vertex.zd(), and wblut.math.WB_ScalarParameter.ZERO.
HE_Mesh wblut.hemesh.HEM_Noise.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Selection.collectVertices(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_RandomOnSphere.nextVector(), wblut.geom.WB_RandomOnSphere.reset(), wblut.hemesh.HE_Selection.vItr(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), and wblut.hemesh.HE_Vertex.zd().
HEM_Noise wblut.hemesh.HEM_Noise.setDistance (final double d)
Set distance to move vertices.
Parameters
d distance
Returns
this
References wblut.math.WB_ScalarParameter.ZERO.
HEM_Noise wblut.hemesh.HEM_Noise.setDistance (final WB_ScalarParameter d)
Sets the distance.
Parameters
d the d
Returns
the hE m_ noise
References wblut.hemesh.HEM_Noise.d.
HEM_Noise wblut.hemesh.HEM_Noise.setSeed (final long seed)
Parameters
seed
Returns
References wblut.geom.WB_RandomOnSphere.setSeed().
Member Data Documentation
WB_ScalarParameter wblut.hemesh.HEM_Noise.d private
Expansion distance.
final WB_RandomOnSphere wblut.hemesh.HEM_Noise.rs private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Noise.java