HE_Mesh: wblut.hemesh.HEM_SmoothInset Class Reference
wblut.hemesh.HEM_SmoothInset Class Reference
Public Member Functions
HEM_SmoothInset ()
HEM_SmoothInset setLevel (final int level)
HEM_SmoothInset setOffset (final double offset)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
int rep
double offset
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_SmoothInset.HEM_SmoothInset ()
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_SmoothInset.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HET_MeshOp.divideEdge(), wblut.hemesh.HE_Selection.eItr(), wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Selection.modify(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HE_Mesh.renameSelection(), wblut.hemesh.HEM_SmoothInset.rep, wblut.hemesh.HEM_Extrude.setChamfer(), and wblut.hemesh.HEM_Extrude.setRelative().
HE_Mesh wblut.hemesh.HEM_SmoothInset.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HET_MeshOp.divideEdge(), wblut.hemesh.HE_Selection.eItr(), wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Selection.modify(), wblut.hemesh.HE_Mesh.renameSelection(), wblut.hemesh.HEM_SmoothInset.rep, wblut.hemesh.HEM_Extrude.setChamfer(), and wblut.hemesh.HEM_Extrude.setRelative().
HEM_SmoothInset wblut.hemesh.HEM_SmoothInset.setLevel (final int level)
Parameters
level
Returns
HEM_SmoothInset wblut.hemesh.HEM_SmoothInset.setOffset (final double offset)
Parameters
offset
Returns
References wblut.hemesh.HEM_SmoothInset.offset.
Member Data Documentation
double wblut.hemesh.HEM_SmoothInset.offset private
int wblut.hemesh.HEM_SmoothInset.rep private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_SmoothInset.java