HE_Mesh: wblut.hemesh.HET_TextFactory Class Reference
wblut.hemesh.HET_TextFactory Class Reference
Static Public Member Functions
static HE_Mesh createText (final String text, final Font font, final double flatness)
static HE_Mesh createText (final String text, final Font font, final int style, final float pointSize, final double flatness)
static HE_Mesh createText (final String text, final String fontName, final float pointSize)
static HE_Mesh createText (final String text, final String fontName, final float pointSize, final double flatness)
static HE_Mesh createText (final String text, final String fontName, final int style, final float pointSize, final double flatness)
static HE_Mesh createTextWithOpenTypeFont (final String text, final String fontName, final float pointSize)
static HE_Mesh createTextWithOpenTypeFont (final String text, final String fontName, final float pointSize, final double flatness)
static HE_Mesh createTextWithOpenTypeFont (final String text, final String fontName, final int style, final float pointSize, final double flatness)
static HE_Mesh createTextWithTrueTypeFont (final String text, final String fontName, final float pointSize)
static HE_Mesh createTextWithTrueTypeFont (final String text, final String fontName, final float pointSize, final double flatness)
static HE_Mesh createTextWithTrueTypeFont (final String text, final String fontName, final int style, final float pointSize, final double flatness)
static HE_Mesh createTextWithType1Font (final String text, final String fontName, final float pointSize)
static HE_Mesh createTextWithType1Font (final String text, final String fontName, final float pointSize, final double flatness)
static HE_Mesh createTextWithType1Font (final String text, final String fontName, final int style, final float pointSize, final double flatness)
static HE_Mesh createTextWithFont (final String text, final String fontName, final float pointSize)
static HE_Mesh createTextWithFont (final String text, final String fontName, final float pointSize, final double flatness)
static HE_Mesh createTextWithFont (final String text, final String fontName, final int style, final float pointSize, final double flatness)
Private Member Functions
HET_TextFactory ()
Detailed Description
Author
FVH
Constructor & Destructor Documentation
wblut.hemesh.HET_TextFactory.HET_TextFactory () private
Member Function Documentation
static HE_Mesh wblut.hemesh.HET_TextFactory.createText (final String text, final Font font, final double flatness) static
References wblut.geom.WB_GeometryFactory2D.createText().
static HE_Mesh wblut.hemesh.HET_TextFactory.createText (final String text, final Font font, final int style, final float pointSize, final double flatness) static
References wblut.geom.WB_GeometryFactory2D.createText().
static HE_Mesh wblut.hemesh.HET_TextFactory.createText (final String text, final String fontName, final float pointSize) static
Parameters
text
fontName
pointSize
Returns
References wblut.geom.WB_GeometryFactory2D.createText().
static HE_Mesh wblut.hemesh.HET_TextFactory.createText (final String text, final String fontName, final float pointSize, final double flatness) static
Parameters
text
fontName
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createText().
static HE_Mesh wblut.hemesh.HET_TextFactory.createText (final String text, final String fontName, final int style, final float pointSize, final double flatness) static
Parameters
text
fontName
style
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createText().
static HE_Mesh wblut.hemesh.HET_TextFactory.createTextWithFont (final String text, final String fontName, final float pointSize) static
Parameters
text
fontName
pointSize
Returns
References wblut.geom.WB_GeometryFactory2D.createTextWithFont().
static HE_Mesh wblut.hemesh.HET_TextFactory.createTextWithFont (final String text, final String fontName, final float pointSize, final double flatness) static
Parameters
text
fontName
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createTextWithFont().
static HE_Mesh wblut.hemesh.HET_TextFactory.createTextWithFont (final String text, final String fontName, final int style, final float pointSize, final double flatness) static
Parameters
text
fontName
style
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createTextWithFont().
static HE_Mesh wblut.hemesh.HET_TextFactory.createTextWithOpenTypeFont (final String text, final String fontName, final float pointSize) static
Parameters
text
fontName
pointSize
Returns
References wblut.geom.WB_GeometryFactory2D.createTextWithOpenTypeFont().
static HE_Mesh wblut.hemesh.HET_TextFactory.createTextWithOpenTypeFont (final String text, final String fontName, final float pointSize, final double flatness) static
Parameters
text
fontName
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createTextWithOpenTypeFont().
static HE_Mesh wblut.hemesh.HET_TextFactory.createTextWithOpenTypeFont (final String text, final String fontName, final int style, final float pointSize, final double flatness) static
Parameters
text
fontName
style
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createTextWithOpenTypeFont().
static HE_Mesh wblut.hemesh.HET_TextFactory.createTextWithTrueTypeFont (final String text, final String fontName, final float pointSize) static
Parameters
text
fontName
pointSize
Returns
References wblut.geom.WB_GeometryFactory2D.createTextWithTrueTypeFont().
static HE_Mesh wblut.hemesh.HET_TextFactory.createTextWithTrueTypeFont (final String text, final String fontName, final float pointSize, final double flatness) static
Parameters
text
fontName
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createTextWithTrueTypeFont().
static HE_Mesh wblut.hemesh.HET_TextFactory.createTextWithTrueTypeFont (final String text, final String fontName, final int style, final float pointSize, final double flatness) static
Parameters
text
fontName
style
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createTextWithTrueTypeFont().
static HE_Mesh wblut.hemesh.HET_TextFactory.createTextWithType1Font (final String text, final String fontName, final float pointSize) static
Parameters
text
fontName
pointSize
Returns
References wblut.geom.WB_GeometryFactory2D.createTextWithType1Font().
static HE_Mesh wblut.hemesh.HET_TextFactory.createTextWithType1Font (final String text, final String fontName, final float pointSize, final double flatness) static
Parameters
text
fontName
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createTextWithType1Font().
static HE_Mesh wblut.hemesh.HET_TextFactory.createTextWithType1Font (final String text, final String fontName, final int style, final float pointSize, final double flatness) static
Parameters
text
fontName
style
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createTextWithType1Font().
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_TextFactory.java