HE_Mesh: wblut.geom.WB_PlanarMap Class Reference
wblut.geom.WB_PlanarMap Class Reference
Public Member Functions
WB_PlanarMap ()
WB_PlanarMap (final WB_Coord c)
WB_PlanarMap (final int mode, final double offset)
WB_PlanarMap (final int mode)
WB_PlanarMap (final WB_Plane P)
WB_PlanarMap (final WB_Plane P, final double offset)
void mapPoint3D (final WB_Coord p, final WB_MutableCoord result)
void mapPoint3D (final double x, final double y, final double z, final WB_MutableCoord result)
void unmapPoint3D (final WB_Coord p, final WB_MutableCoord result)
void unmapPoint3D (final double u, final double v, final double w, final WB_MutableCoord result)
void unmapPoint2D (final double u, final double v, final WB_MutableCoord result)
void unmapPoint2D (final WB_Coord p, final WB_MutableCoord result)
void mapVector3D (final WB_Coord v, final WB_MutableCoord result)
void mapVector3D (final double x, final double y, final double z, final WB_MutableCoord result)
void unmapVector3D (final WB_Coord v, final WB_MutableCoord result)
void unmapVector3D (final double u, final double v, final double w, final WB_MutableCoord result)
void unmapVector2D (final double u, final double v, final WB_MutableCoord result)
void unmapVector2D (final WB_Coord v, final WB_MutableCoord result)
WB_Point mapPoint3D (final WB_Coord p)
WB_Point mapPoint3D (final double x, final double y, final double z)
WB_Point unmapPoint3D (final WB_Coord p)
WB_Point unmapPoint3D (final double u, final double v, final double w)
WB_Point unmapPoint2D (final double u, final double v)
WB_Point unmapPoint2D (final WB_Coord p)
WB_Vector mapVector3D (final WB_Coord v)
WB_Vector mapVector3D (final double x, final double y, final double z)
WB_Vector unmapVector3D (final WB_Coord v)
WB_Vector unmapVector3D (final double u, final double v, final double w)
WB_Vector unmapVector2D (final double u, final double v)
WB_Vector unmapVector2D (final WB_Coord v)
Public Member Functions inherited from wblut.geom.WB_CoordinateSystem3D
WB_CoordinateSystem3D (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_Coord z, final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_Coord z)
WB_CoordinateSystem3D (final WB_Plane P)
WB_CoordinateSystem3D ()
WB_CoordinateSystem3D (final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D get ()
WB_CoordinateSystem3D setParent (final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D setOrigin (final WB_Point o)
WB_CoordinateSystem3D setOrigin (final double ox, final double oy, final double oz)
WB_CoordinateSystem3D setXY (final WB_Coord X, final WB_Coord Y)
WB_CoordinateSystem3D setYX (final WB_Coord Y, final WB_Coord X)
WB_CoordinateSystem3D setXZ (final WB_Coord X, final WB_Coord Z)
WB_CoordinateSystem3D setZX (final WB_Coord Z, final WB_Coord X)
WB_CoordinateSystem3D setYZ (final WB_Coord Y, final WB_Coord Z)
WB_CoordinateSystem3D setZY (final WB_Coord Z, final WB_Coord Y)
WB_Vector getX ()
WB_Vector getY ()
WB_Vector getZ ()
WB_Point getOrigin ()
WB_CoordinateSystem3D getParent ()
boolean isWorld ()
WB_CoordinateSystem3D setXY (final double xx, final double xy, final double xz, final double yx, final double yy, final double yz)
WB_CoordinateSystem3D setYX (final double yx, final double yy, final double yz, final double xx, final double xy, final double xz)
WB_CoordinateSystem3D setXZ (final double xx, final double xy, final double xz, final double zx, final double zy, final double zz)
WB_CoordinateSystem3D setZX (final double zx, final double zy, final double zz, final double xx, final double xy, final double xz)
WB_CoordinateSystem3D setYZ (final double yx, final double yy, final double yz, final double zx, final double zy, final double zz)
WB_CoordinateSystem3D setZY (final double zx, final double zy, final double zz, final double yx, final double yy, final double yz)
WB_CoordinateSystem3D setX (final WB_Coord X)
WB_CoordinateSystem3D setY (final WB_Coord Y)
WB_CoordinateSystem3D setZ (final WB_Coord Z)
WB_CoordinateSystem3D rotateX (final double a)
WB_CoordinateSystem3D rotateY (final double a)
WB_CoordinateSystem3D rotateZ (final double a)
WB_CoordinateSystem3D rotate (final double a, final WB_Vector v)
WB_Transform getTransformFromParent ()
WB_Transform getTransformToParent ()
WB_Transform getTransformFromWorld ()
WB_Transform getTransformToWorld ()
WB_Transform getTransformFrom (final WB_CoordinateSystem3D CS)
WB_Transform getTransformTo (final WB_CoordinateSystem3D CS)
WB_CoordinateSystem3D setX (final double xx, final double xy, final double xz)
WB_CoordinateSystem3D setY (final double yx, final double yy, final double yz)
WB_CoordinateSystem3D setZ (final double zx, final double zy, final double zz)
void flipX ()
void flipY ()
void flipZ ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_Map2D
void unmapPoint2D (WB_Coord p, WB_MutableCoord result)
void unmapPoint2D (double u, double v, WB_MutableCoord result)
void unmapVector2D (WB_Coord v, WB_MutableCoord result)
void unmapVector2D (double u, double v, WB_MutableCoord result)
WB_Coord unmapPoint2D (WB_Coord p)
WB_Coord unmapPoint2D (double u, double v)
WB_Coord unmapVector2D (WB_Coord v)
WB_Coord unmapVector2D (double u, double v)
Public Member Functions inherited from wblut.geom.WB_Map
void mapPoint3D (WB_Coord p, WB_MutableCoord result)
void mapPoint3D (double x, double y, double z, WB_MutableCoord result)
void unmapPoint3D (WB_Coord p, WB_MutableCoord result)
void unmapPoint3D (double u, double v, double w, WB_MutableCoord result)
void mapVector3D (WB_Coord p, WB_MutableCoord result)
void mapVector3D (double x, double y, double z, WB_MutableCoord result)
void unmapVector3D (WB_Coord p, WB_MutableCoord result)
void unmapVector3D (double u, double v, double w, WB_MutableCoord result)
WB_Coord mapPoint3D (WB_Coord p)
WB_Coord mapPoint3D (double x, double y, double z)
WB_Coord unmapPoint3D (WB_Coord p)
WB_Coord unmapPoint3D (double u, double v, double w)
WB_Coord mapVector3D (WB_Coord p)
WB_Coord mapVector3D (double x, double y, double z)
WB_Coord unmapVector3D (WB_Coord p)
WB_Coord unmapVector3D (double u, double v, double w)
Static Public Attributes
static final int YZ = 0
static final int XZ = 1
static final int XY = 2
static final int YZrev = 3
static final int XZrev = 4
static final int XYrev = 5
static final int PLANE = 6
Private Attributes
double offset
final WB_Transform T2D3D
int mode
WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
Additional Inherited Members
Protected Member Functions inherited from wblut.geom.WB_CoordinateSystem3D
WB_CoordinateSystem3D (final boolean world)
void set (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_Coord z)
void set (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_Coord z, final WB_CoordinateSystem3D CS)
Static Protected Member Functions inherited from wblut.geom.WB_CoordinateSystem3D
static final WB_CoordinateSystem3D WORLD ()
Detailed Description
WB_EmbeddedPlane maps coordinates from world space into the coordinate system associated with a plane. The plane can be X-, Y- or Z-plane with offset, reverse X-, Y- or Z-plane with offset, or an arbitrary wblut.geom.WB_Plane
Constructor & Destructor Documentation
wblut.geom.WB_PlanarMap.WB_PlanarMap ()
References wblut.geom.WB_PlanarMap.XY.
wblut.geom.WB_PlanarMap.WB_PlanarMap (final WB_Coord c)
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_CoordinateSystem3D.getTransformToWorld(), wblut.geom.WB_GeometryFactory3D.minX(), wblut.geom.WB_GeometryFactory3D.minY(), wblut.geom.WB_GeometryFactory3D.minZ(), wblut.geom.WB_CoordinateSystem3D.set(), wblut.geom.WB_GeometryFactory2D.WORLD(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_PlanarMap.XY, wblut.geom.WB_PlanarMap.XYrev, wblut.geom.WB_PlanarMap.XZ, wblut.geom.WB_PlanarMap.XZrev, wblut.geom.WB_Coord.yd(), wblut.geom.WB_PlanarMap.YZ, wblut.geom.WB_PlanarMap.YZrev, and wblut.geom.WB_Coord.zd().
wblut.geom.WB_PlanarMap.WB_PlanarMap (final int mode, final double offset)
Parameters
mode
offset
References wblut.geom.WB_GeometryFactory3D.createPoint(), wblut.geom.WB_CoordinateSystem3D.getTransformToWorld(), wblut.geom.WB_GeometryFactory3D.minX(), wblut.geom.WB_GeometryFactory3D.minY(), wblut.geom.WB_GeometryFactory3D.minZ(), wblut.geom.WB_PlanarMap.mode, wblut.geom.WB_PlanarMap.offset, wblut.geom.WB_CoordinateSystem3D.set(), wblut.geom.WB_GeometryFactory2D.WORLD(), wblut.geom.WB_PlanarMap.XY, wblut.geom.WB_PlanarMap.XYrev, wblut.geom.WB_PlanarMap.XZ, wblut.geom.WB_PlanarMap.XZrev, wblut.geom.WB_PlanarMap.YZ, and wblut.geom.WB_PlanarMap.YZrev.
wblut.geom.WB_PlanarMap.WB_PlanarMap (final int mode)
Parameters
mode
References wblut.geom.WB_PlanarMap.mode.
wblut.geom.WB_PlanarMap.WB_PlanarMap (final WB_Plane P)
Parameters
P
References wblut.geom.WB_Plane.getOrigin(), wblut.geom.WB_CoordinateSystem3D.getTransformToWorld(), wblut.geom.WB_Plane.getU(), wblut.geom.WB_Plane.getV(), wblut.geom.WB_Plane.getW(), wblut.geom.WB_PlanarMap.PLANE, and wblut.geom.WB_CoordinateSystem3D.WB_CoordinateSystem3D().
wblut.geom.WB_PlanarMap.WB_PlanarMap (final WB_Plane P, final double offset)
Parameters
P
offset
References wblut.geom.WB_Point.addMul(), wblut.geom.WB_Plane.getNormal(), wblut.geom.WB_Plane.getOrigin(), wblut.geom.WB_CoordinateSystem3D.getTransformToWorld(), wblut.geom.WB_Plane.getU(), wblut.geom.WB_Plane.getV(), wblut.geom.WB_Plane.getW(), wblut.geom.WB_PlanarMap.PLANE, and wblut.geom.WB_CoordinateSystem3D.WB_CoordinateSystem3D().
Member Function Documentation
void wblut.geom.WB_PlanarMap.mapPoint3D (final WB_Coord p, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyInvAsPointInto(), wblut.geom.WB_PlanarMap.offset, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_PlanarMap.mapPoint3D (final double x, final double y, final double z, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyInvAsPointInto(), and wblut.geom.WB_MutableCoord.set().
WB_Point wblut.geom.WB_PlanarMap.mapPoint3D (final WB_Coord p)
References wblut.geom.WB_Transform.applyInvAsPointInto(), wblut.geom.WB_PlanarMap.offset, wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point wblut.geom.WB_PlanarMap.mapPoint3D (final double x, final double y, final double z)
References wblut.geom.WB_Transform.applyInvAsPointInto(), and wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_PlanarMap.mapVector3D (final WB_Coord v, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyInvAsVectorInto(), wblut.geom.WB_PlanarMap.offset, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_PlanarMap.mapVector3D (final double x, final double y, final double z, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyInvAsVectorInto(), and wblut.geom.WB_MutableCoord.set().
WB_Vector wblut.geom.WB_PlanarMap.mapVector3D (final WB_Coord v)
References wblut.geom.WB_Transform.applyInvAsVectorInto(), wblut.geom.WB_PlanarMap.offset, wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_PlanarMap.mapVector3D (final double x, final double y, final double z)
References wblut.geom.WB_Transform.applyInvAsVectorInto(), and wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_PlanarMap.unmapPoint2D (final double u, final double v, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsPointInto(), and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_PlanarMap.unmapPoint2D (final WB_Coord p, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsPointInto(), wblut.geom.WB_PlanarMap.offset, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
WB_Point wblut.geom.WB_PlanarMap.unmapPoint2D (final double u, final double v)
References wblut.geom.WB_Transform.applyAsPointInto(), and wblut.geom.WB_MutableCoordinate.set().
WB_Point wblut.geom.WB_PlanarMap.unmapPoint2D (final WB_Coord p)
References wblut.geom.WB_Transform.applyAsPointInto(), wblut.geom.WB_PlanarMap.offset, wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
void wblut.geom.WB_PlanarMap.unmapPoint3D (final WB_Coord p, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsPointInto(), wblut.geom.WB_PlanarMap.offset, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_PlanarMap.unmapPoint3D (final double u, final double v, final double w, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsPointInto(), and wblut.geom.WB_MutableCoord.set().
WB_Point wblut.geom.WB_PlanarMap.unmapPoint3D (final WB_Coord p)
References wblut.geom.WB_Transform.applyAsPointInto(), wblut.geom.WB_PlanarMap.offset, wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point wblut.geom.WB_PlanarMap.unmapPoint3D (final double u, final double v, final double w)
References wblut.geom.WB_Transform.applyAsPointInto(), and wblut.geom.WB_MutableCoordinate.set().
void wblut.geom.WB_PlanarMap.unmapVector2D (final double u, final double v, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsVectorInto(), and wblut.geom.WB_MutableCoord.set().
void wblut.geom.WB_PlanarMap.unmapVector2D (final WB_Coord v, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsVectorInto(), wblut.geom.WB_PlanarMap.offset, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
WB_Vector wblut.geom.WB_PlanarMap.unmapVector2D (final double u, final double v)
References wblut.geom.WB_Transform.applyAsVectorInto(), and wblut.geom.WB_MutableCoordinate.set().
WB_Vector wblut.geom.WB_PlanarMap.unmapVector2D (final WB_Coord v)
References wblut.geom.WB_Transform.applyAsVectorInto(), wblut.geom.WB_PlanarMap.offset, wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xf(), and wblut.geom.WB_Coord.yf().
void wblut.geom.WB_PlanarMap.unmapVector3D (final WB_Coord v, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsVectorInto(), wblut.geom.WB_PlanarMap.offset, wblut.geom.WB_MutableCoord.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.geom.WB_PlanarMap.unmapVector3D (final double u, final double v, final double w, final WB_MutableCoord result)
References wblut.geom.WB_Transform.applyAsVectorInto(), and wblut.geom.WB_MutableCoord.set().
WB_Vector wblut.geom.WB_PlanarMap.unmapVector3D (final WB_Coord v)
References wblut.geom.WB_Transform.applyAsVectorInto(), wblut.geom.WB_PlanarMap.offset, wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Vector wblut.geom.WB_PlanarMap.unmapVector3D (final double u, final double v, final double w)
References wblut.geom.WB_Transform.applyAsVectorInto(), and wblut.geom.WB_MutableCoordinate.set().
Member Data Documentation
WB_GeometryFactory wblut.geom.WB_PlanarMap.geometryfactory = new WB_GeometryFactory() private
int wblut.geom.WB_PlanarMap.mode private
double wblut.geom.WB_PlanarMap.offset private
final int wblut.geom.WB_PlanarMap.PLANE = 6 static
final WB_Transform wblut.geom.WB_PlanarMap.T2D3D private
final int wblut.geom.WB_PlanarMap.XY = 2 static
final int wblut.geom.WB_PlanarMap.XYrev = 5 static
final int wblut.geom.WB_PlanarMap.XZ = 1 static
final int wblut.geom.WB_PlanarMap.XZrev = 4 static
final int wblut.geom.WB_PlanarMap.YZ = 0 static
final int wblut.geom.WB_PlanarMap.YZrev = 3 static
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_PlanarMap.java