HE_Mesh: wblut.processing.WB_SelectRender3D Class Reference
wblut.processing.WB_SelectRender3D Class Reference
Public Member Functions
WB_SelectRender3D (final PApplet home)
void drawFaces (final HE_HalfedgeStructure mesh)
void drawEdges (final HE_HalfedgeStructure mesh, final double d)
void drawVertices (final HE_HalfedgeStructure mesh, final double d)
long getKeyAA (final int x, final int y)
long getKey (final int x, final int y)
long getKey ()
long getKeyAA ()
void image ()
Protected Attributes
int currentColor
HashMap< Integer, Long > colorToObject
Private Member Functions
void drawFace (final HE_Face f)
void setKey (final Long i)
Private Attributes
final PApplet home
final PGraphics3D selector
final int[] samples
final double scale
Constructor & Destructor Documentation
wblut.processing.WB_SelectRender3D.WB_SelectRender3D (final PApplet home)
Parameters
home
References wblut.processing.WB_SelectRender3D.home.
Member Function Documentation
void wblut.processing.WB_SelectRender3D.drawEdges (final HE_HalfedgeStructure mesh, final double d)
Draw mesh edges.
Parameters
mesh the mesh
d
Returns
key of edge at mouse position
References wblut.hemesh.HE_HalfedgeStructure.eItr(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.key(), wblut.processing.WB_SelectRender3D.setKey(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_SelectRender3D.drawFace (final HE_Face f) private
Draw one face.
Parameters
f face
References wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_SelectRender3D.drawFaces (final HE_HalfedgeStructure mesh)
Draw mesh faces. Typically used with noStroke();
Parameters
mesh the mesh
Returns
key of face at mouse position
References wblut.processing.WB_SelectRender3D.drawFace(), wblut.hemesh.HE_HalfedgeStructure.fItr(), wblut.hemesh.HE_Face.key(), and wblut.processing.WB_SelectRender3D.setKey().
void wblut.processing.WB_SelectRender3D.drawVertices (final HE_HalfedgeStructure mesh, final double d)
Draw mesh vertices as box.
Parameters
mesh the mesh
d size of box
Returns
key of vertex at mouse position
References wblut.hemesh.HE_Vertex.key(), wblut.processing.WB_SelectRender3D.setKey(), wblut.hemesh.HE_HalfedgeStructure.vItr(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
long wblut.processing.WB_SelectRender3D.getKey (final int x, final int y)
Parameters
x
y
Returns
long wblut.processing.WB_SelectRender3D.getKey ()
Returns
long wblut.processing.WB_SelectRender3D.getKeyAA (final int x, final int y)
Parameters
x
y
Returns
long wblut.processing.WB_SelectRender3D.getKeyAA ()
Returns
void wblut.processing.WB_SelectRender3D.image ()
void wblut.processing.WB_SelectRender3D.setKey (final Long i) private
Set the key.
Parameters
i new key
Member Data Documentation
HashMap<Integer, Long> wblut.processing.WB_SelectRender3D.colorToObject protected
The color to object.
int wblut.processing.WB_SelectRender3D.currentColor protected
The current_color.
final PApplet wblut.processing.WB_SelectRender3D.home private
final int [] wblut.processing.WB_SelectRender3D.samples private
final double wblut.processing.WB_SelectRender3D.scale private
final PGraphics3D wblut.processing.WB_SelectRender3D.selector private
The documentation for this class was generated from the following file:
src/processing/wblut/processing/WB_SelectRender3D.java