HE_Mesh: wblut.geom.WB_RandomSpherical Class Reference
wblut.geom.WB_RandomSpherical Class Reference
Public Member Functions
WB_RandomSpherical ()
WB_RandomSpherical (final long seed)
WB_RandomSpherical setSeed (final long seed)
WB_Point nextPoint ()
WB_Vector nextVector ()
void reset ()
WB_RandomPoint setOffset (final WB_Coord offset)
WB_RandomPoint setOffset (final double x, final double y)
WB_RandomPoint setOffset (final double x, final double y, final double z)
Public Member Functions inherited from wblut.geom.WB_RandomPoint
WB_RandomPoint setOffset (WB_Coord offset)
WB_RandomPoint setOffset (double x, double y)
WB_RandomPoint setOffset (double x, double y, double z)
Private Attributes
final WB_MTRandom randomGen
Detailed Description
Random generator for vectors uniformly distributed on a unit sphere. The coordinates returned give the angular parts of the spherical coordinates, theta and phi theta: 0-PI phi: 0-2PI
Author
Frederik Vanhoutte, W:Blut
Constructor & Destructor Documentation
wblut.geom.WB_RandomSpherical.WB_RandomSpherical ()
wblut.geom.WB_RandomSpherical.WB_RandomSpherical (final long seed)
Parameters
seed
Member Function Documentation
WB_Point wblut.geom.WB_RandomSpherical.nextPoint ()
Get the next random point.
Returns
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.nextDouble().
WB_Vector wblut.geom.WB_RandomSpherical.nextVector ()
Get the next random vector.
Returns
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.nextDouble().
void wblut.geom.WB_RandomSpherical.reset ()
Reset the RNG.
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.reset().
WB_RandomPoint wblut.geom.WB_RandomSpherical.setOffset (final WB_Coord offset)
WB_RandomPoint wblut.geom.WB_RandomSpherical.setOffset (final double x, final double y)
WB_RandomPoint wblut.geom.WB_RandomSpherical.setOffset (final double x, final double y, final double z)
WB_RandomSpherical wblut.geom.WB_RandomSpherical.setSeed (final long seed)
Set the seed for the RNG.
Parameters
seed
Returns
this
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.setSeed().
Member Data Documentation
final WB_MTRandom wblut.geom.WB_RandomSpherical.randomGen private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_RandomSpherical.java