HE_Mesh: wblut.processing.WB_PShapeFactory Class Reference
wblut.processing.WB_PShapeFactory Class Reference
Static Public Member Functions
static PShape createFacetedPShape (final HE_Mesh mesh, final PApplet home)
static PShape createFacetedPShape (final HE_Mesh mesh, final PImage img, final PApplet home)
static PShape createFacetedPShape (final HE_Mesh mesh, final PImage[] img, final PApplet home)
static PShape createFacetedPShape (final HE_HalfedgeStructure mesh, final double offset, final PApplet home)
static PShape createFacetedPShape (final WB_Mesh mesh, final PApplet home)
static PShape createFacetedPShapeWithFaceColor (final HE_Mesh mesh, final PApplet home)
static PShape createFacetedPShapeWithVertexColor (final HE_Mesh mesh, final PApplet home)
static PShape createFacettedPShape (final HE_Mesh mesh, final PApplet home)
static PShape createFacettedPShape (final HE_Mesh mesh, final PImage img, final PApplet home)
static PShape createFacettedPShape (final HE_Mesh mesh, final PImage[] img, final PApplet home)
static PShape createFacettedPShape (final HE_HalfedgeStructure mesh, final double offset, final PApplet home)
static PShape createFacettedPShape (final WB_Mesh mesh, final PApplet home)
static PShape createFacettedPShapeWithFaceColor (final HE_Mesh mesh, final PApplet home)
static PShape createFacettedPShapeWithVertexColor (final HE_Mesh mesh, final PApplet home)
static PShape createSmoothPShape (final HE_Mesh mesh, final PApplet home)
static PShape createSmoothPShape (final HE_Mesh mesh, final PImage img, final PApplet home)
static PShape createSmoothPShape (final HE_Mesh mesh, final PImage[] img, final PApplet home)
static PShape createSmoothPShape (final WB_Mesh mesh, final PApplet home)
static PShape createSmoothPShapeWithFaceColor (final HE_Mesh mesh, final PApplet home)
static PShape createSmoothPShapeWithVertexColor (final HE_Mesh mesh, final PApplet home)
static PShape createWireframePShape (final HE_HalfedgeStructure mesh, final PApplet home)
static PShape createSubstratePShape (final HEC_IsoSkin skin, final PApplet home)
Static Private Attributes
static WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
Detailed Description
Author
FVH
Member Function Documentation
static PShape wblut.processing.WB_PShapeFactory.createFacetedPShape (final HE_Mesh mesh, final PApplet home) static
Parameters
mesh
home
Returns
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_TextureCoordinate.uf(), wblut.hemesh.HE_TextureCoordinate.vf(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
static PShape wblut.processing.WB_PShapeFactory.createFacetedPShape (final HE_Mesh mesh, final PImage img, final PApplet home) static
Parameters
mesh
img
home
Returns
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_TextureCoordinate.uf(), wblut.hemesh.HE_TextureCoordinate.vf(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
static PShape wblut.processing.WB_PShapeFactory.createFacetedPShape (final HE_Mesh mesh, final PImage[] img, final PApplet home) static
Parameters
mesh
img
home
Returns
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTextureId(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_TextureCoordinate.uf(), wblut.hemesh.HE_TextureCoordinate.vf(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
static PShape wblut.processing.WB_PShapeFactory.createFacetedPShape (final HE_HalfedgeStructure mesh, final double offset, final PApplet home) static
Parameters
mesh
offset
home
Returns
References wblut.hemesh.HE_HalfedgeStructure.fItr(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.geom.WB_Coord.xf(), wblut.hemesh.HE_TextureCoordinate.xf(), wblut.hemesh.HE_Vertex.xf(), wblut.geom.WB_Coord.yf(), wblut.hemesh.HE_TextureCoordinate.yf(), wblut.hemesh.HE_Vertex.yf(), wblut.geom.WB_Coord.zf(), and wblut.hemesh.HE_Vertex.zf().
static PShape wblut.processing.WB_PShapeFactory.createFacetedPShape (final WB_Mesh mesh, final PApplet home) static
Parameters
mesh
home
Returns
References wblut.geom.WB_GeometryFactory3D.createTriMesh(), wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_Mesh.getFace(), wblut.geom.WB_Mesh.getNumberOfFaces(), wblut.geom.WB_Mesh.getPoints(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
static PShape wblut.processing.WB_PShapeFactory.createFacetedPShapeWithFaceColor (final HE_Mesh mesh, final PApplet home) static
Parameters
mesh
home
Returns
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_TextureCoordinate.uf(), wblut.hemesh.HE_TextureCoordinate.vf(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
static PShape wblut.processing.WB_PShapeFactory.createFacetedPShapeWithVertexColor (final HE_Mesh mesh, final PApplet home) static
Parameters
mesh
home
Returns
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_TextureCoordinate.uf(), wblut.hemesh.HE_TextureCoordinate.vf(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
static PShape wblut.processing.WB_PShapeFactory.createFacettedPShape (final HE_Mesh mesh, final PApplet home) static
Parameters
mesh
home
Returns
References wblut.processing.WB_PShapeFactory.createFacetedPShape().
static PShape wblut.processing.WB_PShapeFactory.createFacettedPShape (final HE_Mesh mesh, final PImage img, final PApplet home) static
Parameters
mesh
img
home
Returns
References wblut.processing.WB_PShapeFactory.createFacetedPShape().
static PShape wblut.processing.WB_PShapeFactory.createFacettedPShape (final HE_Mesh mesh, final PImage[] img, final PApplet home) static
Parameters
mesh
img
home
Returns
References wblut.processing.WB_PShapeFactory.createFacetedPShape().
static PShape wblut.processing.WB_PShapeFactory.createFacettedPShape (final HE_HalfedgeStructure mesh, final double offset, final PApplet home) static
Parameters
mesh
offset
home
Returns
References wblut.processing.WB_PShapeFactory.createFacetedPShape().
static PShape wblut.processing.WB_PShapeFactory.createFacettedPShape (final WB_Mesh mesh, final PApplet home) static
Parameters
mesh
home
Returns
References wblut.processing.WB_PShapeFactory.createFacetedPShape().
static PShape wblut.processing.WB_PShapeFactory.createFacettedPShapeWithFaceColor (final HE_Mesh mesh, final PApplet home) static
Parameters
mesh
home
Returns
References wblut.processing.WB_PShapeFactory.createFacetedPShapeWithFaceColor().
static PShape wblut.processing.WB_PShapeFactory.createFacettedPShapeWithVertexColor (final HE_Mesh mesh, final PApplet home) static
Parameters
mesh
home
Returns
References wblut.processing.WB_PShapeFactory.createFacetedPShapeWithVertexColor().
static PShape wblut.processing.WB_PShapeFactory.createSmoothPShape (final HE_Mesh mesh, final PApplet home) static
Parameters
mesh
home
Returns
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_TextureCoordinate.uf(), wblut.hemesh.HE_TextureCoordinate.vf(), wblut.geom.WB_Coord.xf(), wblut.hemesh.HE_Vertex.xf(), wblut.geom.WB_Coord.yf(), wblut.hemesh.HE_Vertex.yf(), wblut.geom.WB_Coord.zf(), and wblut.hemesh.HE_Vertex.zf().
static PShape wblut.processing.WB_PShapeFactory.createSmoothPShape (final HE_Mesh mesh, final PImage img, final PApplet home) static
Parameters
mesh
img
home
Returns
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_TextureCoordinate.uf(), wblut.hemesh.HE_TextureCoordinate.vf(), wblut.geom.WB_Coord.xf(), wblut.hemesh.HE_Vertex.xf(), wblut.geom.WB_Coord.yf(), wblut.hemesh.HE_Vertex.yf(), wblut.geom.WB_Coord.zf(), and wblut.hemesh.HE_Vertex.zf().
static PShape wblut.processing.WB_PShapeFactory.createSmoothPShape (final HE_Mesh mesh, final PImage[] img, final PApplet home) static
Parameters
mesh
img
home
Returns
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTextureId(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_TextureCoordinate.uf(), wblut.hemesh.HE_TextureCoordinate.vf(), wblut.geom.WB_Coord.xf(), wblut.hemesh.HE_Vertex.xf(), wblut.geom.WB_Coord.yf(), wblut.hemesh.HE_Vertex.yf(), wblut.geom.WB_Coord.zf(), and wblut.hemesh.HE_Vertex.zf().
static PShape wblut.processing.WB_PShapeFactory.createSmoothPShape (final WB_Mesh mesh, final PApplet home) static
Parameters
mesh
home
Returns
References wblut.geom.WB_GeometryFactory3D.createTriMesh(), wblut.geom.WB_GeometryFactory3D.createVector(), wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_Mesh.getFace(), wblut.geom.WB_Mesh.getNumberOfFaces(), wblut.geom.WB_Mesh.getPoints(), wblut.geom.WB_Mesh.getVertexNormal(), wblut.geom.WB_MutableCoordinate.set(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_MutableCoordinate.xf(), wblut.geom.WB_Coord.yf(), wblut.geom.WB_MutableCoordinate.yf(), wblut.geom.WB_Coord.zf(), and wblut.geom.WB_MutableCoordinate.zf().
static PShape wblut.processing.WB_PShapeFactory.createSmoothPShapeWithFaceColor (final HE_Mesh mesh, final PApplet home) static
Parameters
mesh
home
Returns
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_TextureCoordinate.uf(), wblut.hemesh.HE_TextureCoordinate.vf(), wblut.geom.WB_Coord.xf(), wblut.hemesh.HE_Vertex.xf(), wblut.geom.WB_Coord.yf(), wblut.hemesh.HE_Vertex.yf(), wblut.geom.WB_Coord.zf(), and wblut.hemesh.HE_Vertex.zf().
static PShape wblut.processing.WB_PShapeFactory.createSmoothPShapeWithVertexColor (final HE_Mesh mesh, final PApplet home) static
Parameters
mesh
home
Returns
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_TextureCoordinate.uf(), wblut.hemesh.HE_TextureCoordinate.vf(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
static PShape wblut.processing.WB_PShapeFactory.createSubstratePShape (final HEC_IsoSkin skin, final PApplet home) static
References wblut.hemesh.HEC_IsoSkin.getCells(), wblut.hemesh.HEC_IsoSkin.getGridpositions(), wblut.hemesh.HEC_IsoSkin.getNumberOfLayers(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
static PShape wblut.processing.WB_PShapeFactory.createWireframePShape (final HE_HalfedgeStructure mesh, final PApplet home) static
Parameters
mesh
home
Returns
References wblut.hemesh.HE_HalfedgeStructure.eItr(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
Member Data Documentation
WB_GeometryFactory wblut.processing.WB_PShapeFactory.geometryfactory = new WB_GeometryFactory() static private
The documentation for this class was generated from the following file:
src/processing/wblut/processing/WB_PShapeFactory.java