HE_Mesh: wblut.hemesh.HES_Subdividor Class Reference
wblut.hemesh.HES_Subdividor Class Reference abstract
Public Member Functions
HES_Subdividor ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Abstract base class for mesh subdivision. Implementation should preserve mesh validity.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HES_Subdividor.HES_Subdividor ()
Instantiates a new HES_Subdividor.
Member Function Documentation
HE_Mesh wblut.hemesh.HES_Subdividor.apply (final HE_Mesh mesh)
References wblut.hemesh.HES_Subdividor.applySelf(), wblut.hemesh.HE_Mesh.get(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), and wblut.hemesh.HE_Machine.tracker.
HE_Mesh wblut.hemesh.HES_Subdividor.apply (final HE_Selection selection)
References wblut.hemesh.HES_Subdividor.applySelf(), wblut.hemesh.HE_Mesh.get(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), and wblut.hemesh.HE_Machine.tracker.
abstract HE_Mesh wblut.hemesh.HES_Subdividor.applySelf (final HE_Mesh mesh) abstract protected
abstract HE_Mesh wblut.hemesh.HES_Subdividor.applySelf (final HE_Selection selection) abstract protected
The documentation for this class was generated from the following file:
src/hemesh_core/wblut/hemesh/HES_Subdividor.java