HE_Mesh: wblut.hemesh.HEC_Cone Class Reference
wblut.hemesh.HEC_Cone Class Reference
Public Member Functions
HEC_Cone ()
HEC_Cone (final double R, final double H, final int facets, final int steps)
HEC_Cone setRadius (final double R)
HEC_Cone setHeight (final double H)
HEC_Cone setFacets (final int facets)
HEC_Cone setSteps (final int steps)
HEC_Cone setCap (final boolean cap)
HEC_Cone setReverse (final boolean rev)
HEC_Cone align (final WB_Coord direction)
HEC_Cone align (final WB_Coord origin, final WB_Coord endpoint)
HEC_Cone align (final WB_Segment segment)
HEC_Cone setProfile (final WB_ScalarParameter t)
HEC_Cone setTaper (final WB_ScalarParameter t)
HEC_Cone setTaper (final WB_Ease E, final WB_Ease.EaseType type)
HEC_Cone setPhase (final double p)
HEC_Cone setHeightTaper (final WB_ScalarParameter t)
HEC_Cone setHeigthTaper (final WB_Ease E, final WB_Ease.EaseType type)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Static Public Member Functions
static void main (final String[] args)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Attributes
double R
double H
int steps
int facets
boolean cap
boolean reverse
WB_ScalarParameter profile
WB_ScalarParameter taper
WB_ScalarParameter heightTaper
double phase
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Cone.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_Cone.HEC_Cone ()
Instantiates a new cone.
References wblut.geom.WB_Vector.Y, and wblut.hemesh.HEC_Creator.Z.
wblut.hemesh.HEC_Cone.HEC_Cone (final double R, final double H, final int facets, final int steps)
Instantiates a new cone.
Parameters
R radius
H heights
facets number of facets
steps number of height divisions
References wblut.hemesh.HEC_Cone.facets, wblut.hemesh.HEC_Cone.H, wblut.hemesh.HEC_Cone.R, and wblut.hemesh.HEC_Cone.steps.
Member Function Documentation
HEC_Cone wblut.hemesh.HEC_Cone.align (final WB_Coord direction)
Parameters
direction
Returns
References wblut.hemesh.HEC_Creator.setZAxis().
HEC_Cone wblut.hemesh.HEC_Cone.align (final WB_Coord origin, final WB_Coord endpoint)
Parameters
origin
endpoint
Returns
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Point.mulAddMul(), wblut.hemesh.HEC_Creator.setCenter(), wblut.hemesh.HEC_Cone.setHeight(), and wblut.hemesh.HEC_Creator.setZAxis().
HEC_Cone wblut.hemesh.HEC_Cone.align (final WB_Segment segment)
Parameters
segment
Returns
References wblut.geom.WB_Segment.getCenter(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Segment.getLength(), wblut.hemesh.HEC_Creator.setCenter(), wblut.hemesh.HEC_Cone.setHeight(), and wblut.hemesh.HEC_Creator.setZAxis().
HE_Mesh wblut.hemesh.HEC_Cone.createBase () protected
References wblut.hemesh.HEC_FromFacelist.createBase(), wblut.math.WB_ScalarParameter.evaluate(), wblut.hemesh.HEC_Cone.facets, wblut.hemesh.HEC_Cone.H, wblut.hemesh.HEC_Cone.R, wblut.hemesh.HEC_FromFacelist.setFaces(), wblut.hemesh.HEC_FromFacelist.setFaceTextureIds(), wblut.hemesh.HEC_FromFacelist.setVertexUVW(), wblut.hemesh.HEC_FromFacelist.setVertices(), and wblut.hemesh.HEC_Cone.steps.
static void wblut.hemesh.HEC_Cone.main (final String[] args) static
References wblut.hemesh.HEC_Cone.HEC_Cone(), wblut.hemesh.HEC_Cone.setCap(), wblut.hemesh.HEC_Cone.setFacets(), wblut.hemesh.HEC_Cone.setHeight(), wblut.hemesh.HEC_Cone.setRadius(), wblut.hemesh.HEC_Cone.setReverse(), wblut.hemesh.HEC_Cone.setSteps(), wblut.hemesh.HEC_Creator.setZAxis(), and wblut.hemesh.HE_Mesh.validate().
HEC_Cone wblut.hemesh.HEC_Cone.setCap (final boolean cap)
Set capping options.
Parameters
cap create cap?
Returns
self
References wblut.hemesh.HEC_Cone.cap.
HEC_Cone wblut.hemesh.HEC_Cone.setFacets (final int facets)
Set number of sides.
Parameters
facets number of sides
Returns
self
References wblut.hemesh.HEC_Cone.facets.
HEC_Cone wblut.hemesh.HEC_Cone.setHeight (final double H)
Set height.
Parameters
H height
Returns
self
References wblut.hemesh.HEC_Cone.H.
HEC_Cone wblut.hemesh.HEC_Cone.setHeightTaper (final WB_ScalarParameter t)
HEC_Cone wblut.hemesh.HEC_Cone.setHeigthTaper (final WB_Ease E, final WB_Ease.EaseType type)
HEC_Cone wblut.hemesh.HEC_Cone.setPhase (final double p)
HEC_Cone wblut.hemesh.HEC_Cone.setProfile (final WB_ScalarParameter t)
Sets the profile. Parameter should be a WB_ScalarParameter on the domain [0,1]. The radius at fractional height x is multiplied by the profile value at x.
Parameters
t the t
Returns
self
HEC_Cone wblut.hemesh.HEC_Cone.setRadius (final double R)
Set base radius.
Parameters
R base radius
Returns
self
References wblut.hemesh.HEC_Cone.R.
HEC_Cone wblut.hemesh.HEC_Cone.setReverse (final boolean rev)
Reverse cone.
Parameters
rev the rev
Returns
self
HEC_Cone wblut.hemesh.HEC_Cone.setSteps (final int steps)
Set number of vertical divisions.
Parameters
steps vertical divisions
Returns
self
References wblut.hemesh.HEC_Cone.steps.
HEC_Cone wblut.hemesh.HEC_Cone.setTaper (final WB_ScalarParameter t)
HEC_Cone wblut.hemesh.HEC_Cone.setTaper (final WB_Ease E, final WB_Ease.EaseType type)
Member Data Documentation
boolean wblut.hemesh.HEC_Cone.cap private
The cap.
int wblut.hemesh.HEC_Cone.facets private
Facets.
double wblut.hemesh.HEC_Cone.H private
Height.
WB_ScalarParameter wblut.hemesh.HEC_Cone.heightTaper private
double wblut.hemesh.HEC_Cone.phase private
WB_ScalarParameter wblut.hemesh.HEC_Cone.profile private
The profile.
double wblut.hemesh.HEC_Cone.R private
Base radius.
boolean wblut.hemesh.HEC_Cone.reverse private
The reverse.
int wblut.hemesh.HEC_Cone.steps private
Height segments.
WB_ScalarParameter wblut.hemesh.HEC_Cone.taper private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_Cone.java