HE_Mesh: wblut.geom.WB_Swizzle.XXX Class Reference
wblut.geom.WB_Swizzle.XXX Class Reference
Public Member Functions
double xd (final WB_Coord p)
double yd (final WB_Coord p)
double zd (final WB_Coord p)
float xf (final WB_Coord p)
float yf (final WB_Coord p)
float zf (final WB_Coord p)
void swizzleSelf (final WB_MutableCoord p)
Public Member Functions inherited from wblut.geom.WB_Swizzle
abstract double xd (WB_Coord p)
abstract double yd (WB_Coord p)
abstract double zd (WB_Coord p)
abstract float xf (WB_Coord p)
abstract float yf (WB_Coord p)
abstract float zf (WB_Coord p)
abstract void swizzleSelf (WB_MutableCoord p)
Additional Inherited Members
Static Public Attributes inherited from wblut.geom.WB_Swizzle
static final WB_Swizzle X = new X()
static final WB_Swizzle Y = new Y()
static final WB_Swizzle Z = new Z()
static final WB_Swizzle XX = new XX()
static final WB_Swizzle XY = new XY()
static final WB_Swizzle XZ = new XZ()
static final WB_Swizzle YX = new YX()
static final WB_Swizzle YY = new YY()
static final WB_Swizzle YZ = new YZ()
static final WB_Swizzle ZX = new ZX()
static final WB_Swizzle ZY = new ZY()
static final WB_Swizzle ZZ = new ZZ()
static final WB_Swizzle XXX = new XXX()
static final WB_Swizzle XXY = new XXY()
static final WB_Swizzle XXZ = new XXZ()
static final WB_Swizzle XYX = new XYX()
static final WB_Swizzle XYY = new XYY()
static final WB_Swizzle XYZ = new XYZ()
static final WB_Swizzle XZX = new XZX()
static final WB_Swizzle XZY = new XZY()
static final WB_Swizzle XZZ = new XZZ()
static final WB_Swizzle YXX = new YXX()
static final WB_Swizzle YXY = new YXY()
static final WB_Swizzle YXZ = new YXZ()
static final WB_Swizzle YYX = new YYX()
static final WB_Swizzle YYY = new YYY()
static final WB_Swizzle YYZ = new YYZ()
static final WB_Swizzle YZX = new YZX()
static final WB_Swizzle YZY = new YZY()
static final WB_Swizzle YZZ = new YZZ()
static final WB_Swizzle ZXX = new ZXX()
static final WB_Swizzle ZXY = new ZXY()
static final WB_Swizzle ZXZ = new ZXZ()
static final WB_Swizzle ZYX = new ZYX()
static final WB_Swizzle ZYY = new ZYY()
static final WB_Swizzle ZYZ = new ZYZ()
static final WB_Swizzle ZZX = new ZZX()
static final WB_Swizzle ZZY = new ZZY()
static final WB_Swizzle ZZZ = new ZZZ()
Member Function Documentation
void wblut.geom.WB_Swizzle.XXX.swizzleSelf (final WB_MutableCoord p)
References wblut.geom.WB_MutableCoord.set(), and wblut.geom.WB_Coord.xd().
double wblut.geom.WB_Swizzle.XXX.xd (final WB_Coord p)
References wblut.geom.WB_Coord.xd().
float wblut.geom.WB_Swizzle.XXX.xf (final WB_Coord p)
References wblut.geom.WB_Coord.xf().
double wblut.geom.WB_Swizzle.XXX.yd (final WB_Coord p)
References wblut.geom.WB_Coord.xd().
float wblut.geom.WB_Swizzle.XXX.yf (final WB_Coord p)
References wblut.geom.WB_Coord.xf().
double wblut.geom.WB_Swizzle.XXX.zd (final WB_Coord p)
References wblut.geom.WB_Coord.xd().
float wblut.geom.WB_Swizzle.XXX.zf (final WB_Coord p)
References wblut.geom.WB_Coord.xf().
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Swizzle.java