HE_Mesh: wblut.processing.WB_Render3D Class Reference
wblut.processing.WB_Render3D Class Reference
Classes
class PickingRay
Public Member Functions
WB_Render3D (final PApplet home)
WB_Render3D (final PGraphicsOpenGL home)
void drawAABB (final WB_AABB AABB)
void drawAABBNode (final WB_AABBNode node)
void drawAABBLeafNodes (final WB_AABBTree tree)
void drawAABBTree (final WB_AABBTree tree)
void drawAABBTree (final WB_AABBTree tree, final int level)
void drawBezierEdges (final HE_HalfedgeStructure mesh)
void drawBoundaryEdges (final HE_HalfedgeStructure mesh)
void drawBoundaryFaces (final HE_HalfedgeStructure mesh)
void drawBoundaryHalfedges (final HE_HalfedgeStructure mesh)
void drawCircle (final WB_Circle C)
void drawCircle (final Collection< WB_Circle > circles)
void drawCircle (final WB_Circle[] circles)
void drawCurve (final Collection< WB_Curve > curves, final int steps)
void drawCurve (final WB_Curve C, final double minU, final double maxU, final int steps)
void drawCurve (final WB_Curve C, final int steps)
void drawEdge (final HE_Halfedge e)
void drawEdge (final long key, final HE_Mesh mesh)
void drawEdges (final Collection<?extends HE_HalfedgeStructure > meshes)
void drawEdges (final HE_MeshCollection meshes)
void drawEdges (final HE_Face f)
void drawEdges (final HE_HalfedgeStructure mesh)
void drawEdges (final HE_Selection selection)
void drawEdgesWithInternalLabel (final int label, final HE_HalfedgeStructure mesh)
void drawEdgesWithLabel (final int label, final HE_HalfedgeStructure mesh)
void drawFace (final HE_Face f)
void drawFace (final HE_Face f, final boolean smooth)
void drawFace (final HE_Face f, final PImage texture)
void drawFace (final HE_Face f, final PImage texture, final boolean smooth)
void drawFace (final HE_Face f, final PImage[] textures)
void drawFace (final HE_Face f, final PImage[] textures, final boolean smooth)
void drawFace (final long key, final boolean smooth, final HE_Mesh mesh)
void drawFace (final long key, final HE_Mesh mesh)
void drawFaceFC (final HE_Face f)
void drawFaceFC (final HE_Face f, final boolean smooth)
void drawFaceHC (final HE_Face f)
void drawFaceHC (final HE_Face f, final boolean smooth)
void drawFaceNormal (final HE_Face f, final double d)
void drawFaceNormals (final HE_HalfedgeStructure mesh, final double d)
void drawFaceOffset (final HE_Face f, final double d)
void drawFaceSmooth (final HE_Face f)
void drawFaceSmooth (final long key, final HE_Mesh mesh)
void drawFaceSmoothFC (final HE_Face f)
void drawFaceSmoothFC (final long key, final HE_Mesh mesh)
void drawFaceSmoothHC (final HE_Face f)
void drawFaceSmoothHC (final long key, final HE_Mesh mesh)
void drawFaceSmoothVC (final HE_Face f)
void drawFaceSmoothVC (final long key, final HE_Mesh mesh)
void drawFaceVC (final HE_Face f)
void drawFaceVC (final HE_Face f, final boolean smooth)
void drawFaces (final Collection<?extends HE_HalfedgeStructure > meshes)
void drawFaces (final HE_MeshCollection meshes)
void drawFaces (final HE_HalfedgeStructure mesh)
void drawFaces (final HE_HalfedgeStructure mesh, final PImage texture)
void drawFaces (final HE_HalfedgeStructure mesh, final PImage[] textures)
void drawFacesFC (final HE_HalfedgeStructure mesh)
void drawFacesHC (final HE_HalfedgeStructure mesh)
void drawFacesSmooth (final HE_HalfedgeStructure mesh)
void drawFacesSmooth (final HE_HalfedgeStructure mesh, final PImage texture)
void drawFacesSmooth (final HE_HalfedgeStructure mesh, final PImage[] textures)
void drawFacesSmoothFC (final HE_HalfedgeStructure mesh)
void drawFacesSmoothHC (final HE_HalfedgeStructure mesh)
void drawFacesSmoothVC (final HE_HalfedgeStructure mesh)
void drawFacesVC (final HE_HalfedgeStructure mesh)
void drawFacesWithInternalLabel (final int label, final HE_HalfedgeStructure mesh)
void drawFacesWithLabel (final int label, final HE_HalfedgeStructure mesh)
void drawNetwork (final WB_Network network)
void drawNetworkNode (final Node node, final double s)
void drawNetworkConnection (final Connection connection)
void drawHalfedgesWithInternalLabel (final int label, final HE_HalfedgeStructure mesh)
void drawHalfedgesWithLabel (final int label, final HE_HalfedgeStructure mesh)
void drawHalfedge (final HE_Halfedge he, final double d, final double s)
void drawHalfedge (final HE_Halfedge he, final double d, final double s, final double f)
void drawHalfedge (final long key, final double d, final double s, final HE_Mesh mesh)
void drawHalfedges (final HE_HalfedgeStructure mesh, final double d)
void drawHalfedges (final HE_HalfedgeStructure mesh, final double d, final double f)
void drawHalfedgeSimple (final HE_Halfedge he, final double d, final double s)
void drawLine (final WB_Line L, final double d)
void drawLineEmbedded2D (final WB_Line L, final double d, final WB_Map2D map)
void drawLineMapped (final WB_Line L, final double d, final WB_Map map)
void drawLineUnmapped (final WB_Line L, final double d, final WB_Map map)
void drawMesh (final WB_Mesh mesh)
void drawMeshEdges (final WB_Mesh mesh)
void drawMeshFaces (final WB_Mesh mesh)
void drawNetworkNodes (final WB_Network network, final double s)
void drawPath (final HE_Path path)
void drawPlane (final WB_Plane P, final double d)
void drawPoint (final Collection<?extends WB_Coord > points, final double d)
void drawPoint (final WB_Coord p)
void drawPoint (final WB_Coord[] points)
void drawPoint (final Collection<?extends WB_Coord > points)
void drawPoint (final WB_Coord p, final double r)
void drawPoint (final WB_Coord[] points, final double d)
void drawPointEmbedded2D (final Collection<?extends WB_Coord > points, final double r, final WB_Map2D map)
void drawPointEmbedded2D (final Collection<?extends WB_Coord > points, final WB_Map2D map)
void drawPointEmbedded2D (final WB_Coord p, final double r, final WB_Map2D map)
void drawPointEmbedded2D (final WB_Coord p, final WB_Map2D map)
void drawPointEmbedded2D (final WB_Coord[] points, final double r, final WB_Map2D map)
void drawPointEmbedded2D (final WB_Coord[] points, final WB_Map2D map)
void drawPointMapped (final Collection<?extends WB_Coord > points, final double r, final WB_Map map)
void drawPointMapped (final Collection<?extends WB_Coord > points, final WB_Map map)
void drawPointMapped (final WB_Coord p, final double r, final WB_Map map)
void drawPointMapped (final WB_Coord p, final WB_Map map)
void drawPointMapped (final WB_Coord[] points, final double r, final WB_Map map)
void drawPointMapped (final WB_Coord[] points, final WB_Map map)
void drawPointUnmapped (final Collection<?extends WB_Coord > points, final double r, final WB_Map map)
void drawPointUnmapped (final Collection<?extends WB_Coord > points, final WB_Map map)
void drawPointUnmapped (final WB_Coord p, final double r, final WB_Map map)
void drawPointUnmapped (final WB_Coord p, final WB_Map map)
void drawPointUnmapped (final WB_Coord[] points, final double r, final WB_Map map)
void drawPointUnmapped (final WB_Coord[] points, final WB_Map map)
void drawPolygon (final Collection<?extends WB_Polygon > polygons)
void drawPolygon (final int[] indices, final List<?extends WB_Coord > points)
void drawPolygon (final int[] indices, final WB_CoordCollection points)
void drawPolygon (final WB_Polygon P)
void drawPolygonEdges (final Collection<?extends WB_Polygon > polygons)
void drawPolygonEdges (final int[] indices, final List<?extends WB_Coord > points)
void drawPolygonEdges (final int[] indices, final WB_CoordCollection points)
void drawPolygonEdges (final WB_Polygon P)
void drawPolygonEdgesEmbedded2D (final WB_Polygon P, final WB_Map2D map)
void drawPolygonEdgesMapped (final WB_Polygon P, final WB_Map map)
void drawPolygonEdgesUnmapped (final WB_Polygon P, final WB_Map map)
void drawPolygonEmbedded2D (final WB_Polygon P, final WB_Map2D map)
void drawPolygonMapped (final WB_Polygon P, final WB_Map map)
void drawPolygonUnmapped (final WB_Polygon P, final WB_Map map)
void drawPolygonVertices (final Collection< WB_Polygon > polygons, final double d)
void drawPolygonVertices (final WB_Polygon polygon, final double d)
void drawPolyLine (final WB_PolyLine P)
void drawPolylineEdges (final Collection< WB_PolyLine > polylines)
void drawPolylineEdges (final WB_PolyLine P)
void drawPolyLineEmbedded2D (final WB_PolyLine P, final WB_Map2D map)
void drawPolyLineMapped (final WB_PolyLine P, final WB_Map map)
void drawPolyLineUnmapped (final WB_PolyLine P, final WB_Map map)
void drawPolylineVertices (final Collection< WB_PolyLine > polylines, final double d)
void drawPolylineVertices (final WB_PolyLine P, final double d)
void drawRay (final WB_Ray R, final double d)
void drawRayEmbedded2D (final WB_Ray R, final double d, final WB_Map2D map)
void drawRayMapped (final WB_Ray R, final double d, final WB_Map map)
void drawRayUnmapped (final WB_Ray R, final double d, final WB_Map map)
void drawRing (final WB_Ring P)
void drawRingEmbedded2D (final WB_Ring P, final WB_Map2D map)
void drawRingMapped (final WB_Ring P, final WB_Map map)
void drawRingUnmapped (final WB_Ring P, final WB_Map map)
void drawSegment (final Collection<?extends WB_Segment > segments)
void drawSegment (final List<?extends WB_Coord > points)
void drawSegment (final WB_Coord p, final WB_Coord q)
void drawSegment (final int[] segs, final List<?extends WB_Coord > coords)
void drawSegment (final WB_Segment S)
void drawSegmentEmbedded2D (final Collection<?extends WB_Segment > segments, final WB_Map2D map)
void drawSegmentEmbedded2D (final WB_Coord p, final WB_Coord q, final WB_Map2D map)
void drawSegmentEmbedded2D (final WB_Segment segment, final WB_Map2D map)
void drawSegmentEmbedded2D (final WB_Segment[] segments, final WB_Map2D map)
void drawSegmentMapped (final Collection<?extends WB_Segment > segments, final WB_Map map)
void drawSegmentMapped (final WB_Coord p, final WB_Coord q, final WB_Map map)
void drawSegmentMapped (final WB_Segment segment, final WB_Map map)
void drawSegmentMapped (final WB_Segment[] segments, final WB_Map map)
void drawSegmentUnmapped (final Collection<?extends WB_Segment > segments, final WB_Map map)
void drawSegmentUnmapped (final WB_Coord p, final WB_Coord q, final WB_Map map)
void drawSegmentUnmapped (final WB_Segment segment, final WB_Map map)
void drawSegmentUnmapped (final WB_Segment[] segments, final WB_Map map)
void drawSimplePolygon (final WB_Polygon P)
void drawTetrahedron (final int[] indices, final List<?extends WB_Coord > points)
void drawTetrahedron (final int[] indices, final WB_Coord[] points)
void drawTetrahedron (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
void drawTetrahedron (final WB_Tetrahedron tetra)
void drawTetrahedron (final Collection<?extends WB_Tetrahedron > tetras)
void drawTetrahedron (final WB_Tetrahedron[] tetras)
void drawTree (final WB_OctreeInteger tree)
void drawTree (final WB_QuadtreeInteger tree)
void drawTriangle (final Collection<?extends WB_Triangle > triangles)
void drawTriangle (final int[] tri, final List<?extends WB_Coord > points)
void drawTriangle (final List<?extends WB_Coord > points)
void drawTriangle (final int[] tri, final WB_Coord[] points)
void drawTriangle (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
void drawTriangle (final WB_Triangle triangle)
void drawTriangleEdges (final Collection<?extends WB_Triangle > triangles)
void drawTriangleEdges (final WB_Triangle triangle)
void drawTriangleEdgesEmbedded2D (final Collection<?extends WB_Triangle > triangles, final WB_Map2D map)
void drawTriangleEdgesEmbedded2D (final WB_Triangle triangle, final WB_Map2D map)
void drawTriangleEdgesEmbedded2D (final WB_Triangle[] triangles, final WB_Map2D map)
void drawTriangleEdgesMapped (final Collection<?extends WB_Triangle > triangles, final WB_Map map)
void drawTriangleEdgesMapped (final WB_Triangle triangle, final WB_Map map)
void drawTriangleEdgesMapped (final WB_Triangle[] triangles, final WB_Map map)
void drawTriangleEdgesUnmapped (final Collection<?extends WB_Triangle > triangles, final WB_Map map)
void drawTriangleEdgesUnmapped (final WB_Triangle triangle, final WB_Map map)
void drawTriangleEdgesUnmapped (final WB_Triangle[] triangles, final WB_Map map)
void drawTriangleEmbedded2D (final Collection<?extends WB_Triangle > triangles, final WB_Map2D map)
void drawTriangleEmbedded2D (final int[] tri, final List<?extends WB_Coord > points, final WB_Map2D map)
void drawTriangleEmbedded2D (final int[] tri, final WB_Coord[] points, final WB_Map2D map)
void drawTriangleEmbedded2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Map2D map)
void drawTriangleEmbedded2D (final WB_Triangle T, final WB_Map2D map)
void drawTriangleEmbedded2D (final WB_Triangle[] triangles, final WB_Map2D map)
void drawTriangleMapped (final Collection<?extends WB_Triangle > triangles, final WB_Map map)
void drawTriangleMapped (final int[] tri, final List<?extends WB_Coord > points, final WB_Map map)
void drawTriangleMapped (final int[] tri, final WB_Coord[] points, final WB_Map map)
void drawTriangleMapped (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Map map)
void drawTriangleMapped (final WB_Triangle T, final WB_Map map)
void drawTriangleMapped (final WB_Triangle[] triangles, final WB_Map map)
void drawTriangleUnmapped (final Collection<?extends WB_Triangle > triangles, final WB_Map map)
void drawTriangleUnmapped (final int[] tri, final List<?extends WB_Coord > points, final WB_Map map)
void drawTriangleUnmapped (final int[] tri, final WB_Coord[] points, final WB_Map map)
void drawTriangleUnmapped (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Map map)
void drawTriangleUnmapped (final WB_Triangle T, final WB_Map map)
void drawTriangleUnmapped (final WB_Triangle[] triangles, final WB_Map map)
void drawTriangulation (final WB_Triangulation2D tri, final List<?extends WB_Coord > points)
void drawTriangulation (final WB_Triangulation2D tri, final WB_Coord[] points)
void drawTriangulation (final WB_Triangulation3D tri, final List<?extends WB_Coord > points)
void drawTriangulation (final WB_Triangulation3D tri, final WB_Coord[] points)
void drawTriangulationEdges (final WB_Triangulation2D tri, final List<?extends WB_Coord > points)
void drawTriangulationEdges (final WB_Triangulation2D tri, final WB_Coord[] points)
void drawTriangulationEdgesEmbedded2D (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map2D map)
void drawTriangulationEdgesEmbedded2D (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map2D map)
void drawTriangulationEdgesMapped (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map map)
void drawTriangulationEdgesMapped (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map map)
void drawTriangulationEdgesUnmapped (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map map)
void drawTriangulationEdgesUnmapped (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map map)
void drawTriangulationEmbedded2D (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map2D map)
void drawTriangulationEmbedded2D (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map2D map)
void drawTriangulationMapped (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map map)
void drawTriangulationMapped (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map map)
void drawTriangulationUnmapped (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map map)
void drawTriangulationUnmapped (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map map)
void drawVector (final WB_Coord p, final WB_Coord v, final double r)
void drawVectorEmbedded2D (final WB_Coord p, final WB_Coord v, final double r, final WB_Map2D map)
void drawVectorMapped (final WB_Coord p, final WB_Coord v, final double r, final WB_Map map)
void drawVectorUnmapped (final WB_Coord p, final WB_Coord v, final double r, final WB_Map map)
void drawVertex (final long key, final HE_Mesh mesh, final double d)
void drawVertex (final HE_Vertex v, final double d)
void drawVertexNormals (final HE_HalfedgeStructure mesh, final double d)
void drawVertices (final HE_HalfedgeStructure mesh)
void drawVertices (final HE_HalfedgeStructure mesh, final double d)
PGraphicsOpenGL getHome ()
WB_Ray getPickingRay (final double x, final double y)
HE_Face pickClosestFace (final HE_Mesh mesh, final double x, final double y)
HE_Face pickClosestFace (final WB_AABBTree meshtree, final double x, final double y)
HE_Halfedge pickEdge (final HE_Mesh mesh, final double x, final double y)
HE_Halfedge pickEdge (final WB_AABBTree tree, final double x, final double y)
List< HE_Face > pickFaces (final HE_Mesh mesh, final double x, final double y)
List< HE_Face > pickFaces (final WB_AABBTree meshtree, final double x, final double y)
HE_Face pickFurthestFace (final HE_Mesh mesh, final double x, final double y)
HE_Face pickFurthestFace (final WB_AABBTree meshtree, final double x, final double y)
HE_Vertex pickVertex (final HE_Mesh mesh, final double x, final double y)
HE_Vertex pickVertex (final WB_AABBTree tree, final double x, final double y)
void setFaceColorFromTexture (final HE_Mesh mesh, final PImage texture)
void setHalfedgeColorFromTexture (final HE_Mesh mesh, final PImage texture)
void setVertexColorFromTexture (final HE_Mesh mesh, final PImage texture)
void translate (final WB_Coord p)
void vertex (final WB_Coord p)
void vertex (final double x, final double y, final double z)
void normal (final WB_Coord n)
void vertexEmbedded2D (final WB_Coord p, final WB_Map2D map)
void vertexMapped (final WB_Coord p, final WB_Map map)
void vertexUnmapped (final WB_Coord p, final WB_Map map)
void line (final double x1, final double y1, final double z1, final double x2, final double y2, final double z2)
void drawVerticesWithInternalLabel (final int label, final HE_HalfedgeStructure mesh, final double d)
void drawVerticesWithLabel (final int label, final HE_HalfedgeStructure mesh, final double d)
void drawQuad (final WB_Quad quad)
void drawQuad (final Collection<?extends WB_Quad > quads)
void drawPentagon (final WB_Pentagon pentagon)
void drawPentagon (final Collection<?extends WB_Pentagon > pentagons)
void drawHexagon (final WB_Hexagon hexagon)
void drawHexagon (final Collection<?extends WB_Hexagon > hexagons)
void drawOctagon (final WB_Octagon octagon)
void drawOctagon (final Collection<?extends WB_Octagon > octagons)
void drawGizmo (final double d)
void drawTriangle (final WB_TriangleGenerator triangleGenerator)
void drawOutline (final WB_BinaryGrid3D grid)
void draw (final WB_BinaryGrid3D grid)
Public Member Functions inherited from wblut.processing.WB_Render2D
WB_Render2D (final PApplet home)
WB_Render2D (final PGraphics home)
void vertex2D (final WB_Coord p)
void drawPoint2D (final WB_Coord p)
void drawPoint2D (final WB_Coord p, final double r)
void drawPoint2D (final Collection<?extends WB_Coord > points)
void drawPoint2D (final WB_Coord[] points)
void drawPoint2D (final Collection<?extends WB_Coord > points, final double r)
void drawPoint2D (final WB_Coord[] points, final double r)
void drawVector2D (final WB_Coord p, final WB_Coord v, final double r)
void drawLine2D (final WB_Line L, final double d)
void drawRay2D (final WB_Ray R, final double d)
void drawSegment2D (final WB_Coord p, final WB_Coord q)
void drawPolyLine2D (final WB_PolyLine P)
void drawRing2D (final WB_Ring P)
void drawPolygon2D (final WB_Polygon P)
void drawPolygon2D (final WB_Polygon[] P)
void drawPolygon2D (final Collection<?extends WB_Polygon > P)
void drawPolygonEdges2D (final WB_Polygon P)
void drawPolygonEdges2D (final WB_Polygon[] P)
void drawPolygonEdges2D (final Collection<?extends WB_Polygon > P)
void drawCircle2D (final WB_Circle C)
void drawTriangle2D (final WB_Triangle T)
void drawTriangle2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
void drawTriangle2D (final int[] tri, final List<?extends WB_Coord > points)
void drawTriangle2D (final int[] tri, final WB_Coord[] points)
void drawTriangulation2D (final WB_Triangulation2D tri, final List<?extends WB_Coord > points)
void drawTriangulation2D (final WB_Triangulation2D tri, final WB_CoordCollection points)
void drawTriangulationEdges2D (final WB_Triangulation2D tri, final List<?extends WB_Coord > points)
void drawTriangulation2D (final WB_Triangulation2D tri, final WB_Coord[] points)
void drawTriangulationEdges2D (final WB_Triangulation2D tri, final WB_Coord[] points)
void drawTriangle2D (final Collection<?extends WB_Triangle > triangles)
void drawTriangle2D (final WB_Triangle[] triangles)
void drawTriangle2DEdges (final Collection<?extends WB_Triangle > triangles)
void drawTriangle2DEdges (final WB_Triangle triangle)
void drawTriangle2DEdges (final WB_Triangle[] triangles)
void drawSegment2D (final Collection<?extends WB_Segment > segments)
void drawSegment2D (final WB_Segment segment)
void drawSegment2D (final WB_Segment[] segments)
void drawSegment2D (final int[] segs, final List<?extends WB_Coord > coords)
void translate2D (final WB_Coord p)
void drawAABB2D (final WB_AABB2D AABB)
void drawAABBNode2D (final WB_AABBNode2D node)
void drawAABBLeafNodes2D (final WB_AABBTree2D tree)
void drawAABBTree2D (final WB_AABBTree2D tree)
void drawAABBTree2D (final WB_AABBTree2D tree, final int level)
void drawAABBNode2D (final WB_IndexedAABBNode2D node)
void drawAABBLeafNodes2D (final WB_IndexedAABBTree2D tree)
void drawAABBTree2D (final WB_IndexedAABBTree2D tree)
void drawAABBTree2D (final WB_IndexedAABBTree2D tree, final int level)
void drawTriangulation2D (final WB_AlphaTriangulation2D tri)
void drawTriangulation2D (final WB_AlphaTriangulation2D tri, final double alpha)
void drawTriangulationEdges2D (final WB_AlphaTriangulation2D tri)
void drawTriangulation2D (final WB_Triangulation2DWithPoints tri)
void drawTriangulationEdges2D (final WB_Triangulation2DWithPoints tri)
void drawLineMapped (final WB_Line L, final double d, final WB_Map2D map)
void drawPointMapped (final Collection<?extends WB_Coord > points, final double r, final WB_Map2D map)
void drawPointMapped (final Collection<?extends WB_Coord > points, final WB_Map2D map)
void drawPointMapped (final WB_Coord p, final double r, final WB_Map2D map)
void drawPointMapped (final WB_Coord p, final WB_Map2D map)
void drawPointMapped (final WB_Coord[] points, final double r, final WB_Map2D map)
void drawPointMapped (final WB_Coord[] points, final WB_Map2D map)
void drawPolygonEdgesMapped (final WB_Polygon P, final WB_Map2D map)
void drawPolygonMapped (final WB_Polygon P, final WB_Map2D map)
void drawPolyLineMapped (final WB_PolyLine P, final WB_Map2D map)
void drawRayMapped (final WB_Ray R, final double d, final WB_Map2D map)
void drawRingMapped (final WB_Ring P, final WB_Map2D map)
void drawSegmentMapped (final Collection<?extends WB_Segment > segments, final WB_Map2D map)
void drawSegmentMapped (final WB_Coord p, final WB_Coord q, final WB_Map2D map)
void drawSegmentMapped (final WB_Segment segment, final WB_Map2D map)
void drawSegmentMapped (final WB_Segment[] segments, final WB_Map2D map)
void drawTriangleEdgesMapped (final Collection<?extends WB_Triangle > triangles, final WB_Map2D map)
void drawTriangleEdgesMapped (final WB_Triangle triangle, final WB_Map2D map)
void drawTriangleEdgesMapped (final WB_Triangle[] triangles, final WB_Map2D map)
void drawTriangleMapped (final Collection<?extends WB_Triangle > triangles, final WB_Map2D map)
void drawTriangleMapped (final int[] tri, final List<?extends WB_Coord > points, final WB_Map2D map)
void drawTriangleMapped (final int[] tri, final WB_Coord[] points, final WB_Map2D map)
void drawTriangleMapped (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Map2D map)
void drawTriangleMapped (final WB_Triangle T, final WB_Map2D map)
void drawTriangleMapped (final WB_Triangle[] triangles, final WB_Map2D map)
void drawTriangulationMapped (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map2D map)
void drawTriangulationMapped (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map2D map)
void drawVectorMapped (final WB_Coord p, final WB_Coord v, final double r, final WB_Map2D map)
void vertexMapped (final WB_Coord p, final WB_Map2D map)
void drawGizmo (final double d)
void drawTriangle2D (final WB_TriangleGenerator triangleGenerator)
Public Member Functions inherited from wblut.processing.WB_Processing
WB_Processing (final PApplet home)
WB_Processing (final PGraphics home)
Static Public Member Functions
static int getColorFromPImage (final double u, final double v, final PImage texture)
Static Public Member Functions inherited from wblut.processing.WB_Processing
static int color (final int r, final int g, final int b)
Static Public Attributes
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes
final PGraphicsOpenGL home
Protected Attributes inherited from wblut.processing.WB_Processing
PGraphics home
Private Member Functions
void drawAABBNode (final WB_AABBNode node, final int level)
void drawAABBLeafNode (final WB_AABBNode node)
void drawFaceInt (final HE_Face f)
void drawFaceInt (final HE_Face f, final boolean smooth)
void drawFaceInt (final HE_Face f, final PImage texture)
void drawFaceInt (final HE_Face f, final PImage texture, final boolean smooth)
void drawFaceFCInt (final HE_Face f)
void drawFaceFCInt (final HE_Face f, final boolean smooth)
void drawFaceHCInt (final HE_Face f)
void drawFaceHCInt (final HE_Face f, final boolean smooth)
void drawFaceVCInt (final HE_Face f)
void drawFaceVCInt (final HE_Face f, final boolean smooth)
void line (final WB_Coord p, final WB_Coord q)
Private Attributes
WB_GeometryFactory geometryfactory = new WB_GeometryFactory()
Additional Inherited Members
Protected Member Functions inherited from wblut.processing.WB_Render2D
WB_Render2D ()
Protected Member Functions inherited from wblut.processing.WB_Processing
WB_Processing ()
Constructor & Destructor Documentation
wblut.processing.WB_Render3D.WB_Render3D (final PApplet home)
wblut.processing.WB_Render3D.WB_Render3D (final PGraphicsOpenGL home)
Parameters
home
References wblut.processing.WB_Render3D.home.
Member Function Documentation
void wblut.processing.WB_Render3D.draw (final WB_BinaryGrid3D grid)
References wblut.geom.WB_BinaryGrid3D.getMin(), and wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawAABB (final WB_AABB AABB)
Parameters
AABB
References wblut.geom.WB_AABB.getCenter(), wblut.geom.WB_AABB.getDepth(), wblut.geom.WB_AABB.getHeight(), wblut.geom.WB_AABB.getWidth(), and wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawAABBLeafNode (final WB_AABBNode node) private
Draw leaf node.
Parameters
node the node
References wblut.processing.WB_Render3D.drawAABB(), wblut.geom.WB_AABBTree.WB_AABBNode.getAABB(), wblut.geom.WB_AABBTree.WB_AABBNode.getChildA(), wblut.geom.WB_AABBTree.WB_AABBNode.getChildB(), and wblut.geom.WB_AABBTree.WB_AABBNode.isLeaf.
void wblut.processing.WB_Render3D.drawAABBLeafNodes (final WB_AABBTree tree)
Draw leafs.
Parameters
tree the tree
References wblut.processing.WB_Render3D.drawAABBLeafNode(), and wblut.geom.WB_AABBTree.getRoot().
void wblut.processing.WB_Render3D.drawAABBNode (final WB_AABBNode node)
Draw WB_AABBTree node.
Parameters
node the node
References wblut.processing.WB_Render3D.drawAABB(), wblut.geom.WB_AABBTree.WB_AABBNode.getAABB(), wblut.geom.WB_AABBTree.WB_AABBNode.getChildA(), and wblut.geom.WB_AABBTree.WB_AABBNode.getChildB().
void wblut.processing.WB_Render3D.drawAABBNode (final WB_AABBNode node, final int level) private
Draw WB_AABBTree node.
Parameters
node the node
level the level
References wblut.processing.WB_Render3D.drawAABB(), wblut.processing.WB_Render3D.drawAABBNode(), wblut.geom.WB_AABBTree.WB_AABBNode.getAABB(), wblut.geom.WB_AABBTree.WB_AABBNode.getChildA(), wblut.geom.WB_AABBTree.WB_AABBNode.getChildB(), and wblut.geom.WB_AABBTree.WB_AABBNode.getLevel().
void wblut.processing.WB_Render3D.drawAABBTree (final WB_AABBTree tree)
References wblut.processing.WB_Render3D.drawAABBNode(), and wblut.geom.WB_AABBTree.getRoot().
void wblut.processing.WB_Render3D.drawAABBTree (final WB_AABBTree tree, final int level)
References wblut.processing.WB_Render3D.drawAABBNode(), and wblut.geom.WB_AABBTree.getRoot().
void wblut.processing.WB_Render3D.drawBezierEdges (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.hemesh.HE_HalfedgeStructure.fItr(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getHalfedgeCenter(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.vertex(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
void wblut.processing.WB_Render3D.drawBoundaryEdges (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_HalfedgeStructure.heItr(), wblut.hemesh.HE_MeshElement.isVisible(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawBoundaryFaces (final HE_HalfedgeStructure mesh)
References wblut.processing.WB_Render3D.drawFace(), wblut.hemesh.HE_HalfedgeStructure.fItr(), wblut.hemesh.HE_Face.isBoundary(), and wblut.hemesh.HE_MeshElement.isVisible().
void wblut.processing.WB_Render3D.drawBoundaryHalfedges (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.processing.WB_Render3D.drawBoundaryEdges().
void wblut.processing.WB_Render3D.drawCircle (final WB_Circle C)
Parameters
C
References wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Circle.getNormal(), wblut.geom.WB_Circle.getRadius(), and wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawCircle (final Collection< WB_Circle > circles)
Parameters
circles
References wblut.processing.WB_Render3D.drawCircle().
void wblut.processing.WB_Render3D.drawCircle (final WB_Circle[] circles)
Parameters
circles
References wblut.processing.WB_Render3D.drawCircle().
void wblut.processing.WB_Render3D.drawCurve (final Collection< WB_Curve > curves, final int steps)
Parameters
curves
steps
void wblut.processing.WB_Render3D.drawCurve (final WB_Curve C, final double minU, final double maxU, final int steps)
Parameters
C
minU
maxU
steps
References wblut.geom.WB_Curve.curvePoint(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawCurve (final WB_Curve C, final int steps)
Parameters
C
steps
References wblut.geom.WB_Curve.curvePoint(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawEdge (final HE_Halfedge e)
Draw one edge.
Parameters
e edge
References wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getStartVertex(), wblut.hemesh.HE_MeshElement.isVisible(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawEdge (final long key, final HE_Mesh mesh)
Parameters
key
mesh
References wblut.processing.WB_Render3D.drawEdge(), wblut.hemesh.HE_Mesh.getHalfedgeWithKey(), and wblut.hemesh.HE_MeshElement.isVisible().
void wblut.processing.WB_Render3D.drawEdges (final Collection<?extends HE_HalfedgeStructure > meshes)
Draw edges.
Parameters
meshes the meshes
void wblut.processing.WB_Render3D.drawEdges (final HE_MeshCollection meshes)
References wblut.processing.WB_Render3D.drawEdges(), and wblut.hemesh.HE_MeshCollection.mItr().
void wblut.processing.WB_Render3D.drawEdges (final HE_Face f)
Parameters
f
References wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshElement.isVisible(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawEdges (final HE_HalfedgeStructure mesh)
Draw mesh edges.
Parameters
mesh the mesh
References wblut.hemesh.HE_HalfedgeStructure.eItr(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshElement.isVisible(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawEdges (final HE_Selection selection)
Draw edges of selection.
Parameters
selection selection to draw
References wblut.hemesh.HE_Selection.eItr(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshElement.isVisible(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawEdgesWithInternalLabel (final int label, final HE_HalfedgeStructure mesh)
Parameters
label
mesh
References wblut.hemesh.HE_HalfedgeStructure.eItr(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshElement.isVisible(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawEdgesWithLabel (final int label, final HE_HalfedgeStructure mesh)
Draw mesh edges.
Parameters
label the label
mesh the mesh
References wblut.hemesh.HE_HalfedgeStructure.eItr(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Element.getUserLabel(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshElement.isVisible(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawFace (final HE_Face f)
Parameters
f
void wblut.processing.WB_Render3D.drawFace (final HE_Face f, final boolean smooth)
Parameters
f
smooth
References wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.normal(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawFace (final HE_Face f, final PImage texture)
Parameters
f
texture
References wblut.processing.WB_Render3D.drawFace().
void wblut.processing.WB_Render3D.drawFace (final HE_Face f, final PImage texture, final boolean smooth)
Parameters
f
texture
smooth
References wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.normal(), wblut.hemesh.HE_TextureCoordinate.uf(), wblut.hemesh.HE_TextureCoordinate.vf(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_Render3D.drawFace (final HE_Face f, final PImage[] textures)
Parameters
f
textures
References wblut.processing.WB_Render3D.drawFace().
void wblut.processing.WB_Render3D.drawFace (final HE_Face f, final PImage[] textures, final boolean smooth)
Parameters
f
textures
smooth
References wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTextureId(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.normal(), wblut.hemesh.HE_TextureCoordinate.uf(), wblut.hemesh.HE_TextureCoordinate.vf(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_Render3D.drawFace (final long key, final boolean smooth, final HE_Mesh mesh)
Parameters
key
smooth
mesh
References wblut.processing.WB_Render3D.drawFace(), and wblut.hemesh.HE_Mesh.getFaceWithKey().
void wblut.processing.WB_Render3D.drawFace (final long key, final HE_Mesh mesh)
Parameters
key
mesh
References wblut.processing.WB_Render3D.drawFace(), and wblut.hemesh.HE_Mesh.getFaceWithKey().
void wblut.processing.WB_Render3D.drawFaceFC (final HE_Face f)
Parameters
f
void wblut.processing.WB_Render3D.drawFaceFC (final HE_Face f, final boolean smooth)
Parameters
f
smooth
References wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.normal(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawFaceFCInt (final HE_Face f) private
void wblut.processing.WB_Render3D.drawFaceFCInt (final HE_Face f, final boolean smooth) private
References wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.normal(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawFaceHC (final HE_Face f)
Parameters
f
void wblut.processing.WB_Render3D.drawFaceHC (final HE_Face f, final boolean smooth)
Parameters
f
smooth
References wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceHalfedges(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.normal(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawFaceHCInt (final HE_Face f) private
void wblut.processing.WB_Render3D.drawFaceHCInt (final HE_Face f, final boolean smooth) private
References wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceHalfedges(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.normal(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawFaceInt (final HE_Face f) private
void wblut.processing.WB_Render3D.drawFaceInt (final HE_Face f, final boolean smooth) private
References wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.normal(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawFaceInt (final HE_Face f, final PImage texture) private
References wblut.processing.WB_Render3D.drawFaceInt().
void wblut.processing.WB_Render3D.drawFaceInt (final HE_Face f, final PImage texture, final boolean smooth) private
References wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.normal(), wblut.hemesh.HE_TextureCoordinate.uf(), wblut.hemesh.HE_TextureCoordinate.vf(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_Render3D.drawFaceNormal (final HE_Face f, final double d)
Parameters
f
d
References wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.processing.WB_Render3D.line(), and wblut.geom.WB_Point.mul().
void wblut.processing.WB_Render3D.drawFaceNormals (final HE_HalfedgeStructure mesh, final double d)
Parameters
mesh
d
References wblut.geom.WB_Point.addMul(), wblut.hemesh.HE_HalfedgeStructure.fItr(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Face.getFaceNormal(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawFaceOffset (final HE_Face f, final double d)
Parameters
f
d
References wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.geom.WB_Coord.xf(), wblut.hemesh.HE_Vertex.xf(), wblut.geom.WB_Coord.yf(), wblut.hemesh.HE_Vertex.yf(), wblut.geom.WB_Coord.zf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_Render3D.drawFaces (final Collection<?extends HE_HalfedgeStructure > meshes)
Parameters
meshes
void wblut.processing.WB_Render3D.drawFaces (final HE_MeshCollection meshes)
Parameters
meshes
References wblut.processing.WB_Render3D.drawFaces(), wblut.hemesh.HE_MeshIterator.hasNext(), wblut.hemesh.HE_MeshCollection.mItr(), and wblut.hemesh.HE_MeshIterator.next().
void wblut.processing.WB_Render3D.drawFaces (final HE_HalfedgeStructure mesh)
Draw mesh faces. Typically used with noStroke();
Parameters
mesh the mesh
References wblut.processing.WB_Render3D.drawFaceInt(), and wblut.hemesh.HE_HalfedgeStructure.fItr().
void wblut.processing.WB_Render3D.drawFaces (final HE_HalfedgeStructure mesh, final PImage texture)
Parameters
mesh
texture
References wblut.processing.WB_Render3D.drawFaceInt(), and wblut.hemesh.HE_HalfedgeStructure.fItr().
void wblut.processing.WB_Render3D.drawFaces (final HE_HalfedgeStructure mesh, final PImage[] textures)
Parameters
mesh
textures
References wblut.processing.WB_Render3D.drawFace(), and wblut.hemesh.HE_HalfedgeStructure.fItr().
void wblut.processing.WB_Render3D.drawFacesFC (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.processing.WB_Render3D.drawFaceFCInt(), and wblut.hemesh.HE_HalfedgeStructure.fItr().
void wblut.processing.WB_Render3D.drawFacesHC (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.processing.WB_Render3D.drawFaceHCInt(), and wblut.hemesh.HE_HalfedgeStructure.fItr().
void wblut.processing.WB_Render3D.drawFaceSmooth (final HE_Face f)
Parameters
f
References wblut.processing.WB_Render3D.drawFace().
void wblut.processing.WB_Render3D.drawFaceSmooth (final long key, final HE_Mesh mesh)
Draw one face using vertex normals.
Parameters
key key of face
mesh the mesh
References wblut.processing.WB_Render3D.drawFace(), and wblut.hemesh.HE_Mesh.getFaceWithKey().
void wblut.processing.WB_Render3D.drawFaceSmoothFC (final HE_Face f)
Parameters
f
References wblut.processing.WB_Render3D.drawFaceFC().
void wblut.processing.WB_Render3D.drawFaceSmoothFC (final long key, final HE_Mesh mesh)
Parameters
key
mesh
References wblut.processing.WB_Render3D.drawFaceFC(), and wblut.hemesh.HE_Mesh.getFaceWithKey().
void wblut.processing.WB_Render3D.drawFaceSmoothHC (final HE_Face f)
Parameters
f
References wblut.processing.WB_Render3D.drawFaceHC().
void wblut.processing.WB_Render3D.drawFaceSmoothHC (final long key, final HE_Mesh mesh)
Parameters
key
mesh
References wblut.processing.WB_Render3D.drawFaceHC(), and wblut.hemesh.HE_Mesh.getFaceWithKey().
void wblut.processing.WB_Render3D.drawFaceSmoothVC (final HE_Face f)
Parameters
f
References wblut.processing.WB_Render3D.drawFaceVC().
void wblut.processing.WB_Render3D.drawFaceSmoothVC (final long key, final HE_Mesh mesh)
Parameters
key
mesh
References wblut.processing.WB_Render3D.drawFaceVC(), and wblut.hemesh.HE_Mesh.getFaceWithKey().
void wblut.processing.WB_Render3D.drawFacesSmooth (final HE_HalfedgeStructure mesh)
Draw mesh faces using vertex normals. Typically used with noStroke().
Parameters
mesh the mesh
References wblut.processing.WB_Render3D.drawFaceInt(), and wblut.hemesh.HE_HalfedgeStructure.fItr().
void wblut.processing.WB_Render3D.drawFacesSmooth (final HE_HalfedgeStructure mesh, final PImage texture)
Parameters
mesh
texture
References wblut.processing.WB_Render3D.drawFaceInt(), and wblut.hemesh.HE_HalfedgeStructure.fItr().
void wblut.processing.WB_Render3D.drawFacesSmooth (final HE_HalfedgeStructure mesh, final PImage[] textures)
Parameters
mesh
textures
References wblut.processing.WB_Render3D.drawFace(), and wblut.hemesh.HE_HalfedgeStructure.fItr().
void wblut.processing.WB_Render3D.drawFacesSmoothFC (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.processing.WB_Render3D.drawFaceFCInt(), and wblut.hemesh.HE_HalfedgeStructure.fItr().
void wblut.processing.WB_Render3D.drawFacesSmoothHC (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.processing.WB_Render3D.drawFaceHCInt(), and wblut.hemesh.HE_HalfedgeStructure.fItr().
void wblut.processing.WB_Render3D.drawFacesSmoothVC (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.processing.WB_Render3D.drawFaceVCInt(), and wblut.hemesh.HE_HalfedgeStructure.fItr().
void wblut.processing.WB_Render3D.drawFacesVC (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.processing.WB_Render3D.drawFaceVCInt(), and wblut.hemesh.HE_HalfedgeStructure.fItr().
void wblut.processing.WB_Render3D.drawFacesWithInternalLabel (final int label, final HE_HalfedgeStructure mesh)
Parameters
label
mesh
References wblut.processing.WB_Render3D.drawFaceInt(), wblut.hemesh.HE_HalfedgeStructure.fItr(), and wblut.hemesh.HE_Element.getInternalLabel().
void wblut.processing.WB_Render3D.drawFacesWithLabel (final int label, final HE_HalfedgeStructure mesh)
Draw mesh faces matching label. Typically used with noStroke();
Parameters
label the label
mesh the mesh
References wblut.processing.WB_Render3D.drawFaceInt(), wblut.hemesh.HE_HalfedgeStructure.fItr(), and wblut.hemesh.HE_Element.getUserLabel().
void wblut.processing.WB_Render3D.drawFaceVC (final HE_Face f)
Parameters
f
void wblut.processing.WB_Render3D.drawFaceVC (final HE_Face f, final boolean smooth)
Parameters
f
smooth
References wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.normal(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawFaceVCInt (final HE_Face f) private
void wblut.processing.WB_Render3D.drawFaceVCInt (final HE_Face f, final boolean smooth) private
References wblut.hemesh.HE_MeshElement.getColor(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.normal(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawGizmo (final double d)
void wblut.processing.WB_Render3D.drawHalfedge (final HE_Halfedge he, final double d, final double s)
Parameters
he
d
s
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Classification.CONCAVE, wblut.geom.WB_Classification.CONVEX, wblut.hemesh.HE_Halfedge.getHalfedgeCenter(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Halfedge.getHalfedgeType(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.line(), and wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawHalfedge (final HE_Halfedge he, final double d, final double s, final double f)
Parameters
he
d
s
f
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Classification.CONCAVE, wblut.geom.WB_Classification.CONVEX, wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Halfedge.getHalfedgeType(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.line(), and wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawHalfedge (final long key, final double d, final double s, final HE_Mesh mesh)
Parameters
key
d
s
mesh
References wblut.processing.WB_Render3D.drawHalfedge(), and wblut.hemesh.HE_Mesh.getHalfedgeWithKey().
void wblut.processing.WB_Render3D.drawHalfedges (final HE_HalfedgeStructure mesh, final double d)
Parameters
mesh
d
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Classification.CONCAVE, wblut.geom.WB_Classification.CONVEX, wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Halfedge.getHalfedgeCenter(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Halfedge.getHalfedgeType(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_HalfedgeStructure.heItr(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.line(), and wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawHalfedges (final HE_HalfedgeStructure mesh, final double d, final double f)
Parameters
mesh
d
f
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Classification.CONCAVE, wblut.geom.WB_Classification.CONVEX, wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Halfedge.getHalfedgeType(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_HalfedgeStructure.heItr(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.line(), and wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawHalfedgeSimple (final HE_Halfedge he, final double d, final double s)
Parameters
he
d
s
References wblut.geom.WB_Point.addMulSelf(), wblut.hemesh.HE_Halfedge.getHalfedgeCenter(), wblut.hemesh.HE_Halfedge.getHalfedgeNormal(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.line(), and wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawHalfedgesWithInternalLabel (final int label, final HE_HalfedgeStructure mesh)
References wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_HalfedgeStructure.heItr(), wblut.hemesh.HE_MeshElement.isVisible(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawHalfedgesWithLabel (final int label, final HE_HalfedgeStructure mesh)
References wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Element.getUserLabel(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_HalfedgeStructure.heItr(), wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.line(), and wblut.geom.WB_Point.mulAddMul().
void wblut.processing.WB_Render3D.drawHexagon (final WB_Hexagon hexagon)
References wblut.geom.WB_Hexagon.p1, wblut.geom.WB_Hexagon.p2, wblut.geom.WB_Hexagon.p3, wblut.geom.WB_Hexagon.p4, wblut.geom.WB_Hexagon.p5, wblut.geom.WB_Hexagon.p6, and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawHexagon (final Collection<?extends WB_Hexagon > hexagons)
References wblut.processing.WB_Render3D.drawHexagon().
void wblut.processing.WB_Render3D.drawLine (final WB_Line L, final double d)
Parameters
L
d
References wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.processing.WB_Render3D.drawLineEmbedded2D (final WB_Line L, final double d, final WB_Map2D map)
Parameters
L
d
map
References wblut.geom.WB_Point.addMul(), wblut.processing.WB_Render3D.drawSegmentEmbedded2D(), wblut.geom.WB_Line.getDirection(), and wblut.geom.WB_Line.getOrigin().
void wblut.processing.WB_Render3D.drawLineMapped (final WB_Line L, final double d, final WB_Map map)
Parameters
L
d
map
References wblut.geom.WB_Point.addMul(), wblut.processing.WB_Render3D.drawSegmentMapped(), wblut.geom.WB_Line.getDirection(), and wblut.geom.WB_Line.getOrigin().
void wblut.processing.WB_Render3D.drawLineUnmapped (final WB_Line L, final double d, final WB_Map map)
Parameters
L
d
map
References wblut.geom.WB_Point.addMul(), wblut.processing.WB_Render3D.drawSegmentUnmapped(), wblut.geom.WB_Line.getDirection(), and wblut.geom.WB_Line.getOrigin().
void wblut.processing.WB_Render3D.drawMesh (final WB_Mesh mesh)
Parameters
mesh
References wblut.processing.WB_Render3D.drawPolygon(), wblut.geom.WB_Mesh.getFacesAsInt(), wblut.geom.WB_Mesh.getNumberOfVertices(), and wblut.geom.WB_Mesh.getPoints().
void wblut.processing.WB_Render3D.drawMeshEdges (final WB_Mesh mesh)
Parameters
mesh
References wblut.processing.WB_Render3D.drawPolygonEdges(), wblut.geom.WB_Mesh.getFacesAsInt(), wblut.geom.WB_Mesh.getNumberOfVertices(), and wblut.geom.WB_Mesh.getPoints().
void wblut.processing.WB_Render3D.drawMeshFaces (final WB_Mesh mesh)
Parameters
mesh
References wblut.processing.WB_Render3D.drawPolygon(), wblut.geom.WB_Mesh.getFacesAsInt(), wblut.geom.WB_Mesh.getNumberOfVertices(), and wblut.geom.WB_Mesh.getPoints().
void wblut.processing.WB_Render3D.drawNetwork (final WB_Network network)
Parameters
frame
References wblut.processing.WB_Render3D.drawNetworkConnection(), wblut.geom.WB_Network.getConnections(), and wblut.geom.WB_Network.getNumberOfConnections().
void wblut.processing.WB_Render3D.drawNetworkConnection (final Connection connection)
Parameters
strut
References wblut.geom.WB_Network.Connection.end, wblut.processing.WB_Render3D.line(), and wblut.geom.WB_Network.Connection.start.
void wblut.processing.WB_Render3D.drawNetworkNode (final Node node, final double s)
Parameters
node
s
References wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawNetworkNodes (final WB_Network network, final double s)
Draw nodes.
Parameters
network the frame
s the s
References wblut.processing.WB_Render3D.drawNetworkNode(), wblut.geom.WB_Network.getNodes(), and wblut.geom.WB_Network.getNumberOfNodes().
void wblut.processing.WB_Render3D.drawOctagon (final WB_Octagon octagon)
References wblut.geom.WB_Octagon.p1, wblut.geom.WB_Octagon.p2, wblut.geom.WB_Octagon.p3, wblut.geom.WB_Octagon.p4, wblut.geom.WB_Octagon.p5, wblut.geom.WB_Octagon.p6, wblut.geom.WB_Octagon.p7, wblut.geom.WB_Octagon.p8, and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawOctagon (final Collection<?extends WB_Octagon > octagons)
References wblut.processing.WB_Render3D.drawOctagon().
void wblut.processing.WB_Render3D.drawOutline (final WB_BinaryGrid3D grid)
References wblut.geom.WB_BinaryGrid3D.getMin(), and wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawPath (final HE_Path path)
Parameters
path
References wblut.processing.WB_Render3D.drawSegment(), wblut.hemesh.HE_PathHalfedge.getEndVertex(), wblut.hemesh.HE_Path.getPathHalfedge(), wblut.hemesh.HE_Path.getPathOrder(), wblut.hemesh.HE_Path.getPathVertices(), wblut.hemesh.HE_PathHalfedge.getStartVertex(), and wblut.hemesh.HE_Path.isLoop().
void wblut.processing.WB_Render3D.drawPentagon (final WB_Pentagon pentagon)
References wblut.geom.WB_Pentagon.p1, wblut.geom.WB_Pentagon.p2, wblut.geom.WB_Pentagon.p3, wblut.geom.WB_Pentagon.p4, wblut.geom.WB_Pentagon.p5, and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawPentagon (final Collection<?extends WB_Pentagon > pentagons)
References wblut.processing.WB_Render3D.drawPentagon().
void wblut.processing.WB_Render3D.drawPlane (final WB_Plane P, final double d)
Parameters
P
d
References wblut.geom.WB_Plane.getOrigin(), wblut.geom.WB_Plane.getU(), wblut.geom.WB_Plane.getV(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.processing.WB_Render3D.drawPoint (final Collection<?extends WB_Coord > points, final double d)
Parameters
points
d
void wblut.processing.WB_Render3D.drawPoint (final WB_Coord p)
Parameters
p
References wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
void wblut.processing.WB_Render3D.drawPoint (final WB_Coord[] points)
Parameters
points
References wblut.processing.WB_Render3D.drawPoint().
void wblut.processing.WB_Render3D.drawPoint (final Collection<?extends WB_Coord > points)
References wblut.processing.WB_Render3D.drawPoint().
void wblut.processing.WB_Render3D.drawPoint (final WB_Coord p, final double r)
Parameters
p
r
References wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawPoint (final WB_Coord[] points, final double d)
Parameters
points
d
References wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawPointEmbedded2D (final Collection<?extends WB_Coord > points, final double r, final WB_Map2D map)
Parameters
points
r
map
void wblut.processing.WB_Render3D.drawPointEmbedded2D (final Collection<?extends WB_Coord > points, final WB_Map2D map)
Parameters
points
map
References wblut.processing.WB_Render3D.drawPointEmbedded2D().
void wblut.processing.WB_Render3D.drawPointEmbedded2D (final WB_Coord p, final double r, final WB_Map2D map)
Parameters
p
r
map
References wblut.processing.WB_Render3D.drawPoint(), wblut.geom.WB_Map.mapPoint3D(), wblut.geom.WB_Map2D.unmapPoint2D(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
void wblut.processing.WB_Render3D.drawPointEmbedded2D (final WB_Coord p, final WB_Map2D map)
Parameters
p
map
References wblut.processing.WB_Render3D.drawPoint(), wblut.geom.WB_Map.mapPoint3D(), wblut.geom.WB_Map2D.unmapPoint2D(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
void wblut.processing.WB_Render3D.drawPointEmbedded2D (final WB_Coord[] points, final double r, final WB_Map2D map)
Parameters
points
r
map
References wblut.processing.WB_Render3D.drawPointEmbedded2D().
void wblut.processing.WB_Render3D.drawPointEmbedded2D (final WB_Coord[] points, final WB_Map2D map)
Parameters
points
map
References wblut.processing.WB_Render3D.drawPointEmbedded2D().
void wblut.processing.WB_Render3D.drawPointMapped (final Collection<?extends WB_Coord > points, final double r, final WB_Map map)
Parameters
points
r
map
void wblut.processing.WB_Render3D.drawPointMapped (final Collection<?extends WB_Coord > points, final WB_Map map)
Parameters
points
map
References wblut.processing.WB_Render3D.drawPointMapped().
void wblut.processing.WB_Render3D.drawPointMapped (final WB_Coord p, final double r, final WB_Map map)
Parameters
p
r
map
References wblut.processing.WB_Render3D.drawPoint(), and wblut.geom.WB_Map.mapPoint3D().
void wblut.processing.WB_Render3D.drawPointMapped (final WB_Coord p, final WB_Map map)
Parameters
p
map
References wblut.processing.WB_Render3D.drawPoint(), and wblut.geom.WB_Map.mapPoint3D().
void wblut.processing.WB_Render3D.drawPointMapped (final WB_Coord[] points, final double r, final WB_Map map)
Parameters
points
r
map
References wblut.processing.WB_Render3D.drawPointMapped().
void wblut.processing.WB_Render3D.drawPointMapped (final WB_Coord[] points, final WB_Map map)
Parameters
points
map
References wblut.processing.WB_Render3D.drawPointMapped().
void wblut.processing.WB_Render3D.drawPointUnmapped (final Collection<?extends WB_Coord > points, final double r, final WB_Map map)
Parameters
points
r
map
void wblut.processing.WB_Render3D.drawPointUnmapped (final Collection<?extends WB_Coord > points, final WB_Map map)
Parameters
points
map
References wblut.processing.WB_Render3D.drawPointUnmapped().
void wblut.processing.WB_Render3D.drawPointUnmapped (final WB_Coord p, final double r, final WB_Map map)
Parameters
p
r
map
References wblut.processing.WB_Render3D.drawPoint(), and wblut.geom.WB_Map.mapPoint3D().
void wblut.processing.WB_Render3D.drawPointUnmapped (final WB_Coord p, final WB_Map map)
Parameters
p
map
References wblut.processing.WB_Render3D.drawPoint(), and wblut.geom.WB_Map.mapPoint3D().
void wblut.processing.WB_Render3D.drawPointUnmapped (final WB_Coord[] points, final double r, final WB_Map map)
Parameters
points
r
map
References wblut.processing.WB_Render3D.drawPointUnmapped().
void wblut.processing.WB_Render3D.drawPointUnmapped (final WB_Coord[] points, final WB_Map map)
Parameters
points
map
References wblut.processing.WB_Render3D.drawPointUnmapped().
void wblut.processing.WB_Render3D.drawPolygon (final Collection<?extends WB_Polygon > polygons)
Parameters
polygons
void wblut.processing.WB_Render3D.drawPolygon (final int[] indices, final List<?extends WB_Coord > points)
Parameters
indices
points
void wblut.processing.WB_Render3D.drawPolygon (final int[] indices, final WB_CoordCollection points)
Parameters
indices
points
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
void wblut.processing.WB_Render3D.drawPolygon (final WB_Polygon P)
Parameters
P
References wblut.processing.WB_Render3D.drawTriangle(), wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_Polygon.getTriangles().
void wblut.processing.WB_Render3D.drawPolygonEdges (final Collection<?extends WB_Polygon > polygons)
Parameters
polygons
void wblut.processing.WB_Render3D.drawPolygonEdges (final int[] indices, final List<?extends WB_Coord > points)
Parameters
indices
points
void wblut.processing.WB_Render3D.drawPolygonEdges (final int[] indices, final WB_CoordCollection points)
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
void wblut.processing.WB_Render3D.drawPolygonEdges (final WB_Polygon P)
Parameters
P
References wblut.geom.WB_Polygon.getNumberOfContours(), wblut.geom.WB_Polygon.getNumberOfPointsPerContour(), wblut.geom.WB_Polygon.getPoint(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawPolygonEdgesEmbedded2D (final WB_Polygon P, final WB_Map2D map)
Parameters
P
map
References wblut.geom.WB_Polygon.getNumberOfContours(), wblut.geom.WB_Polygon.getNumberOfPointsPerContour(), wblut.geom.WB_Polygon.getPoint(), and wblut.processing.WB_Render3D.vertexEmbedded2D().
void wblut.processing.WB_Render3D.drawPolygonEdgesMapped (final WB_Polygon P, final WB_Map map)
Parameters
P
map
References wblut.geom.WB_Polygon.getNumberOfContours(), wblut.geom.WB_Polygon.getNumberOfPointsPerContour(), wblut.geom.WB_Polygon.getPoint(), and wblut.processing.WB_Render3D.vertexMapped().
void wblut.processing.WB_Render3D.drawPolygonEdgesUnmapped (final WB_Polygon P, final WB_Map map)
Parameters
P
map
References wblut.geom.WB_Polygon.getNumberOfContours(), wblut.geom.WB_Polygon.getNumberOfPointsPerContour(), wblut.geom.WB_Polygon.getPoint(), and wblut.processing.WB_Render3D.vertexUnmapped().
void wblut.processing.WB_Render3D.drawPolygonEmbedded2D (final WB_Polygon P, final WB_Map2D map)
Parameters
P
map
References wblut.processing.WB_Render3D.drawTriangleEmbedded2D(), wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_Polygon.getTriangles().
void wblut.processing.WB_Render3D.drawPolygonMapped (final WB_Polygon P, final WB_Map map)
Parameters
P
map
References wblut.processing.WB_Render3D.drawTriangleMapped(), wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_Polygon.getTriangles().
void wblut.processing.WB_Render3D.drawPolygonUnmapped (final WB_Polygon P, final WB_Map map)
Parameters
P
map
References wblut.processing.WB_Render3D.drawTriangleUnmapped(), wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_Polygon.getTriangles().
void wblut.processing.WB_Render3D.drawPolygonVertices (final Collection< WB_Polygon > polygons, final double d)
Parameters
polygons
d
void wblut.processing.WB_Render3D.drawPolygonVertices (final WB_Polygon polygon, final double d)
Parameters
polygon
d
References wblut.geom.WB_Polygon.getNumberOfPoints(), wblut.geom.WB_Polygon.getPoint(), and wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawPolyLine (final WB_PolyLine P)
Parameters
P
References wblut.geom.WB_PolyLine.getNumberOfPoints(), wblut.geom.WB_PolyLine.getPoint(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawPolylineEdges (final Collection< WB_PolyLine > polylines)
Parameters
polylines
void wblut.processing.WB_Render3D.drawPolylineEdges (final WB_PolyLine P)
Parameters
P
References wblut.geom.WB_PolyLine.getNumberOfPoints(), wblut.geom.WB_PolyLine.getPoint(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawPolyLineEmbedded2D (final WB_PolyLine P, final WB_Map2D map)
Parameters
P
map
References wblut.processing.WB_Render3D.drawSegmentEmbedded2D(), wblut.geom.WB_PolyLine.getNumberOfPoints(), and wblut.geom.WB_PolyLine.getPoint().
void wblut.processing.WB_Render3D.drawPolyLineMapped (final WB_PolyLine P, final WB_Map map)
Parameters
P
map
References wblut.processing.WB_Render3D.drawSegmentMapped(), wblut.geom.WB_PolyLine.getNumberOfPoints(), and wblut.geom.WB_PolyLine.getPoint().
void wblut.processing.WB_Render3D.drawPolyLineUnmapped (final WB_PolyLine P, final WB_Map map)
Parameters
P
map
References wblut.processing.WB_Render3D.drawSegmentUnmapped(), wblut.geom.WB_PolyLine.getNumberOfPoints(), and wblut.geom.WB_PolyLine.getPoint().
void wblut.processing.WB_Render3D.drawPolylineVertices (final Collection< WB_PolyLine > polylines, final double d)
Parameters
polylines
d
void wblut.processing.WB_Render3D.drawPolylineVertices (final WB_PolyLine P, final double d)
Parameters
P
d
References wblut.geom.WB_PolyLine.getNumberOfPoints(), wblut.geom.WB_PolyLine.getPoint(), and wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawQuad (final WB_Quad quad)
References wblut.geom.WB_Quad.p1, wblut.geom.WB_Quad.p2, wblut.geom.WB_Quad.p3, wblut.geom.WB_Quad.p4, and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawQuad (final Collection<?extends WB_Quad > quads)
References wblut.processing.WB_Render3D.drawQuad().
void wblut.processing.WB_Render3D.drawRay (final WB_Ray R, final double d)
Parameters
R
d
References wblut.geom.WB_Ray.getDirection(), wblut.geom.WB_Ray.getOrigin(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.processing.WB_Render3D.drawRayEmbedded2D (final WB_Ray R, final double d, final WB_Map2D map)
Parameters
R
d
map
References wblut.geom.WB_Point.addMul(), wblut.processing.WB_Render3D.drawSegmentEmbedded2D(), wblut.geom.WB_Ray.getDirection(), and wblut.geom.WB_Ray.getOrigin().
void wblut.processing.WB_Render3D.drawRayMapped (final WB_Ray R, final double d, final WB_Map map)
Parameters
R
d
map
References wblut.geom.WB_Point.addMul(), wblut.processing.WB_Render3D.drawSegmentMapped(), wblut.geom.WB_Ray.getDirection(), and wblut.geom.WB_Ray.getOrigin().
void wblut.processing.WB_Render3D.drawRayUnmapped (final WB_Ray R, final double d, final WB_Map map)
Parameters
R
d
map
References wblut.geom.WB_Point.addMul(), wblut.processing.WB_Render3D.drawSegmentUnmapped(), wblut.geom.WB_Ray.getDirection(), and wblut.geom.WB_Ray.getOrigin().
void wblut.processing.WB_Render3D.drawRing (final WB_Ring P)
Parameters
P
References wblut.geom.WB_Ring.getNumberOfPoints(), wblut.geom.WB_Ring.getPoint(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawRingEmbedded2D (final WB_Ring P, final WB_Map2D map)
Parameters
P
map
References wblut.processing.WB_Render3D.drawSegmentEmbedded2D(), wblut.geom.WB_Ring.getNumberOfPoints(), and wblut.geom.WB_Ring.getPoint().
void wblut.processing.WB_Render3D.drawRingMapped (final WB_Ring P, final WB_Map map)
Parameters
P
map
References wblut.processing.WB_Render3D.drawSegmentMapped(), wblut.geom.WB_Ring.getNumberOfPoints(), and wblut.geom.WB_Ring.getPoint().
void wblut.processing.WB_Render3D.drawRingUnmapped (final WB_Ring P, final WB_Map map)
Parameters
P
map
References wblut.processing.WB_Render3D.drawSegmentUnmapped(), wblut.geom.WB_Ring.getNumberOfPoints(), and wblut.geom.WB_Ring.getPoint().
void wblut.processing.WB_Render3D.drawSegment (final Collection<?extends WB_Segment > segments)
Parameters
segments
void wblut.processing.WB_Render3D.drawSegment (final List<?extends WB_Coord > points)
References wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawSegment (final WB_Coord p, final WB_Coord q)
Parameters
p
q
References wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawSegment (final int[] segs, final List<?extends WB_Coord > coords)
References wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawSegment (final WB_Segment S)
Parameters
S
References wblut.geom.WB_Segment.getEndpoint(), wblut.geom.WB_Line.getOrigin(), and wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawSegmentEmbedded2D (final Collection<?extends WB_Segment > segments, final WB_Map2D map)
Parameters
segments
map
void wblut.processing.WB_Render3D.drawSegmentEmbedded2D (final WB_Coord p, final WB_Coord q, final WB_Map2D map)
Parameters
p
q
map
References wblut.processing.WB_Render3D.vertexEmbedded2D().
void wblut.processing.WB_Render3D.drawSegmentEmbedded2D (final WB_Segment segment, final WB_Map2D map)
Parameters
segment
map
References wblut.processing.WB_Render3D.drawSegmentEmbedded2D(), wblut.geom.WB_Segment.getEndpoint(), and wblut.geom.WB_Line.getOrigin().
void wblut.processing.WB_Render3D.drawSegmentEmbedded2D (final WB_Segment[] segments, final WB_Map2D map)
Parameters
segments
map
References wblut.processing.WB_Render3D.drawSegmentEmbedded2D().
void wblut.processing.WB_Render3D.drawSegmentMapped (final Collection<?extends WB_Segment > segments, final WB_Map map)
Parameters
segments
map
void wblut.processing.WB_Render3D.drawSegmentMapped (final WB_Coord p, final WB_Coord q, final WB_Map map)
Parameters
p
q
map
References wblut.processing.WB_Render3D.vertexMapped().
void wblut.processing.WB_Render3D.drawSegmentMapped (final WB_Segment segment, final WB_Map map)
Parameters
segment
map
References wblut.processing.WB_Render3D.drawSegmentMapped(), wblut.geom.WB_Segment.getEndpoint(), and wblut.geom.WB_Line.getOrigin().
void wblut.processing.WB_Render3D.drawSegmentMapped (final WB_Segment[] segments, final WB_Map map)
Parameters
segments
map
References wblut.processing.WB_Render3D.drawSegmentMapped().
void wblut.processing.WB_Render3D.drawSegmentUnmapped (final Collection<?extends WB_Segment > segments, final WB_Map map)
Parameters
segments
map
void wblut.processing.WB_Render3D.drawSegmentUnmapped (final WB_Coord p, final WB_Coord q, final WB_Map map)
Parameters
p
q
map
References wblut.processing.WB_Render3D.vertexUnmapped().
void wblut.processing.WB_Render3D.drawSegmentUnmapped (final WB_Segment segment, final WB_Map map)
Parameters
segment
map
References wblut.processing.WB_Render3D.drawSegmentUnmapped(), wblut.geom.WB_Segment.getEndpoint(), and wblut.geom.WB_Line.getOrigin().
void wblut.processing.WB_Render3D.drawSegmentUnmapped (final WB_Segment[] segments, final WB_Map map)
Parameters
segments
map
References wblut.processing.WB_Render3D.drawSegmentUnmapped().
void wblut.processing.WB_Render3D.drawSimplePolygon (final WB_Polygon P)
Parameters
P
References wblut.geom.WB_Polygon.getNumberOfPoints(), wblut.geom.WB_Polygon.getPoint(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawTetrahedron (final int[] indices, final List<?extends WB_Coord > points)
Parameters
indices
points
void wblut.processing.WB_Render3D.drawTetrahedron (final int[] indices, final WB_Coord[] points)
Parameters
indices
points
References wblut.processing.WB_Render3D.drawTetrahedron().
void wblut.processing.WB_Render3D.drawTetrahedron (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
Parameters
p0
p1
p2
p3
References wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawTetrahedron (final WB_Tetrahedron tetra)
Parameters
tetra
References wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawTetrahedron (final Collection<?extends WB_Tetrahedron > tetras)
Parameters
tetras
References wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawTetrahedron (final WB_Tetrahedron[] tetras)
Parameters
tetras
References wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawTree (final WB_OctreeInteger tree)
References wblut.processing.WB_Render3D.drawAABB(), wblut.geom.WB_OctreeInteger.getBox(), wblut.geom.WB_OctreeInteger.getNodes(), and wblut.geom.WB_OctreeInteger.getNumNodes().
void wblut.processing.WB_Render3D.drawTree (final WB_QuadtreeInteger tree)
References wblut.processing.WB_Render2D.drawAABB2D(), wblut.processing.WB_Render3D.drawTree(), wblut.geom.WB_QuadtreeInteger.getBox(), wblut.geom.WB_QuadtreeInteger.getNodes(), and wblut.geom.WB_QuadtreeInteger.getNumNodes().
void wblut.processing.WB_Render3D.drawTriangle (final Collection<?extends WB_Triangle > triangles)
Parameters
triangles
void wblut.processing.WB_Render3D.drawTriangle (final int[] tri, final List<?extends WB_Coord > points)
Parameters
tri
points
References wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawTriangle (final List<?extends WB_Coord > points)
References wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawTriangle (final int[] tri, final WB_Coord[] points)
Parameters
tri
points
References wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawTriangle (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
Parameters
p1
p2
p3
References wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawTriangle (final WB_Triangle triangle)
Parameters
triangle
References wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawTriangle (final WB_TriangleGenerator triangleGenerator)
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_TriangleGenerator.getPoints(), wblut.geom.WB_TriangleGenerator.getTriangles(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawTriangleEdges (final Collection<?extends WB_Triangle > triangles)
Parameters
triangles
void wblut.processing.WB_Render3D.drawTriangleEdges (final WB_Triangle triangle)
Parameters
triangle
References wblut.processing.WB_Render3D.line().
void wblut.processing.WB_Render3D.drawTriangleEdgesEmbedded2D (final Collection<?extends WB_Triangle > triangles, final WB_Map2D map)
Parameters
triangles
map
void wblut.processing.WB_Render3D.drawTriangleEdgesEmbedded2D (final WB_Triangle triangle, final WB_Map2D map)
Parameters
triangle
map
References wblut.processing.WB_Render3D.drawSegmentEmbedded2D().
void wblut.processing.WB_Render3D.drawTriangleEdgesEmbedded2D (final WB_Triangle[] triangles, final WB_Map2D map)
Parameters
triangles
map
References wblut.processing.WB_Render3D.drawTriangleEdgesEmbedded2D().
void wblut.processing.WB_Render3D.drawTriangleEdgesMapped (final Collection<?extends WB_Triangle > triangles, final WB_Map map)
Parameters
triangles
map
void wblut.processing.WB_Render3D.drawTriangleEdgesMapped (final WB_Triangle triangle, final WB_Map map)
Parameters
triangle
map
References wblut.processing.WB_Render3D.drawSegmentMapped().
void wblut.processing.WB_Render3D.drawTriangleEdgesMapped (final WB_Triangle[] triangles, final WB_Map map)
Parameters
triangles
map
References wblut.processing.WB_Render3D.drawTriangleEdgesMapped().
void wblut.processing.WB_Render3D.drawTriangleEdgesUnmapped (final Collection<?extends WB_Triangle > triangles, final WB_Map map)
Parameters
triangles
map
void wblut.processing.WB_Render3D.drawTriangleEdgesUnmapped (final WB_Triangle triangle, final WB_Map map)
Parameters
triangle
map
References wblut.processing.WB_Render3D.drawSegmentUnmapped().
void wblut.processing.WB_Render3D.drawTriangleEdgesUnmapped (final WB_Triangle[] triangles, final WB_Map map)
Parameters
triangles
map
References wblut.processing.WB_Render3D.drawTriangleEdgesUnmapped().
void wblut.processing.WB_Render3D.drawTriangleEmbedded2D (final Collection<?extends WB_Triangle > triangles, final WB_Map2D map)
Parameters
triangles
map
void wblut.processing.WB_Render3D.drawTriangleEmbedded2D (final int[] tri, final List<?extends WB_Coord > points, final WB_Map2D map)
Parameters
tri
points
map
References wblut.processing.WB_Render3D.vertexEmbedded2D().
void wblut.processing.WB_Render3D.drawTriangleEmbedded2D (final int[] tri, final WB_Coord[] points, final WB_Map2D map)
Parameters
tri
points
map
References wblut.processing.WB_Render3D.vertexEmbedded2D().
void wblut.processing.WB_Render3D.drawTriangleEmbedded2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Map2D map)
Parameters
p1
p2
p3
map
References wblut.processing.WB_Render3D.vertexEmbedded2D().
void wblut.processing.WB_Render3D.drawTriangleEmbedded2D (final WB_Triangle T, final WB_Map2D map)
Parameters
T
map
References wblut.processing.WB_Render3D.vertexEmbedded2D().
void wblut.processing.WB_Render3D.drawTriangleEmbedded2D (final WB_Triangle[] triangles, final WB_Map2D map)
Parameters
triangles
map
References wblut.processing.WB_Render3D.drawTriangleEmbedded2D().
void wblut.processing.WB_Render3D.drawTriangleMapped (final Collection<?extends WB_Triangle > triangles, final WB_Map map)
Parameters
triangles
map
void wblut.processing.WB_Render3D.drawTriangleMapped (final int[] tri, final List<?extends WB_Coord > points, final WB_Map map)
Parameters
tri
points
map
References wblut.processing.WB_Render3D.vertexMapped().
void wblut.processing.WB_Render3D.drawTriangleMapped (final int[] tri, final WB_Coord[] points, final WB_Map map)
Parameters
tri
points
map
References wblut.processing.WB_Render3D.vertexMapped().
void wblut.processing.WB_Render3D.drawTriangleMapped (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Map map)
Parameters
p1
p2
p3
map
References wblut.processing.WB_Render3D.vertexMapped().
void wblut.processing.WB_Render3D.drawTriangleMapped (final WB_Triangle T, final WB_Map map)
Parameters
T
map
References wblut.processing.WB_Render3D.vertexMapped().
void wblut.processing.WB_Render3D.drawTriangleMapped (final WB_Triangle[] triangles, final WB_Map map)
Parameters
triangles
map
References wblut.processing.WB_Render3D.drawTriangleMapped().
void wblut.processing.WB_Render3D.drawTriangleUnmapped (final Collection<?extends WB_Triangle > triangles, final WB_Map map)
Parameters
triangles
map
void wblut.processing.WB_Render3D.drawTriangleUnmapped (final int[] tri, final List<?extends WB_Coord > points, final WB_Map map)
Parameters
tri
points
map
References wblut.processing.WB_Render3D.vertexUnmapped().
void wblut.processing.WB_Render3D.drawTriangleUnmapped (final int[] tri, final WB_Coord[] points, final WB_Map map)
Parameters
tri
points
map
References wblut.processing.WB_Render3D.vertexUnmapped().
void wblut.processing.WB_Render3D.drawTriangleUnmapped (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3, final WB_Map map)
Parameters
p1
p2
p3
map
References wblut.processing.WB_Render3D.vertexUnmapped().
void wblut.processing.WB_Render3D.drawTriangleUnmapped (final WB_Triangle T, final WB_Map map)
Parameters
T
map
References wblut.processing.WB_Render3D.vertexUnmapped().
void wblut.processing.WB_Render3D.drawTriangleUnmapped (final WB_Triangle[] triangles, final WB_Map map)
Parameters
triangles
map
References wblut.processing.WB_Render3D.drawTriangleUnmapped().
void wblut.processing.WB_Render3D.drawTriangulation (final WB_Triangulation2D tri, final List<?extends WB_Coord > points)
Parameters
tri
points
References wblut.geom.WB_Triangulation2D.getTriangles(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawTriangulation (final WB_Triangulation2D tri, final WB_Coord[] points)
Parameters
tri
points
References wblut.geom.WB_Triangulation2D.getTriangles(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.drawTriangulation (final WB_Triangulation3D tri, final List<?extends WB_Coord > points)
Parameters
tri
points
References wblut.processing.WB_Render3D.drawTetrahedron(), and wblut.geom.WB_Triangulation3D.getTetrahedra().
void wblut.processing.WB_Render3D.drawTriangulation (final WB_Triangulation3D tri, final WB_Coord[] points)
Parameters
tri
points
References wblut.processing.WB_Render3D.drawTetrahedron(), and wblut.geom.WB_Triangulation3D.getTetrahedra().
void wblut.processing.WB_Render3D.drawTriangulationEdges (final WB_Triangulation2D tri, final List<?extends WB_Coord > points)
Parameters
tri
points
References wblut.processing.WB_Render3D.drawSegment(), and wblut.geom.WB_Triangulation2D.getEdges().
void wblut.processing.WB_Render3D.drawTriangulationEdges (final WB_Triangulation2D tri, final WB_Coord[] points)
Parameters
tri
points
References wblut.processing.WB_Render3D.drawSegment(), and wblut.geom.WB_Triangulation2D.getEdges().
void wblut.processing.WB_Render3D.drawTriangulationEdgesEmbedded2D (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map2D map)
Parameters
tri
points
map
References wblut.processing.WB_Render3D.drawSegmentEmbedded2D(), and wblut.geom.WB_Triangulation2D.getEdges().
void wblut.processing.WB_Render3D.drawTriangulationEdgesEmbedded2D (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map2D map)
Parameters
tri
points
map
References wblut.processing.WB_Render3D.drawSegmentEmbedded2D(), and wblut.geom.WB_Triangulation2D.getEdges().
void wblut.processing.WB_Render3D.drawTriangulationEdgesMapped (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map map)
Parameters
tri
points
map
References wblut.processing.WB_Render3D.drawSegmentMapped(), and wblut.geom.WB_Triangulation2D.getEdges().
void wblut.processing.WB_Render3D.drawTriangulationEdgesMapped (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map map)
Parameters
tri
points
map
References wblut.processing.WB_Render3D.drawSegmentMapped(), and wblut.geom.WB_Triangulation2D.getEdges().
void wblut.processing.WB_Render3D.drawTriangulationEdgesUnmapped (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map map)
Parameters
tri
points
map
References wblut.processing.WB_Render3D.drawSegmentUnmapped(), and wblut.geom.WB_Triangulation2D.getEdges().
void wblut.processing.WB_Render3D.drawTriangulationEdgesUnmapped (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map map)
Parameters
tri
points
map
References wblut.processing.WB_Render3D.drawSegmentUnmapped(), and wblut.geom.WB_Triangulation2D.getEdges().
void wblut.processing.WB_Render3D.drawTriangulationEmbedded2D (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map2D map)
Parameters
tri
points
map
References wblut.geom.WB_Triangulation2D.getTriangles(), and wblut.processing.WB_Render3D.vertexEmbedded2D().
void wblut.processing.WB_Render3D.drawTriangulationEmbedded2D (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map2D map)
Parameters
tri
points
map
References wblut.geom.WB_Triangulation2D.getTriangles(), and wblut.processing.WB_Render3D.vertexEmbedded2D().
void wblut.processing.WB_Render3D.drawTriangulationMapped (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map map)
Parameters
tri
points
map
References wblut.geom.WB_Triangulation2D.getTriangles(), and wblut.processing.WB_Render3D.vertexMapped().
void wblut.processing.WB_Render3D.drawTriangulationMapped (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map map)
Parameters
tri
points
map
References wblut.geom.WB_Triangulation2D.getTriangles(), and wblut.processing.WB_Render3D.vertexMapped().
void wblut.processing.WB_Render3D.drawTriangulationUnmapped (final WB_Triangulation2D tri, final List<?extends WB_Coord > points, final WB_Map map)
Parameters
tri
points
map
References wblut.geom.WB_Triangulation2D.getTriangles(), and wblut.processing.WB_Render3D.vertexUnmapped().
void wblut.processing.WB_Render3D.drawTriangulationUnmapped (final WB_Triangulation2D tri, final WB_Coord[] points, final WB_Map map)
Parameters
tri
points
map
References wblut.geom.WB_Triangulation2D.getTriangles(), and wblut.processing.WB_Render3D.vertexUnmapped().
void wblut.processing.WB_Render3D.drawVector (final WB_Coord p, final WB_Coord v, final double r)
Parameters
p
v
r
References wblut.processing.WB_Render3D.translate(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
void wblut.processing.WB_Render3D.drawVectorEmbedded2D (final WB_Coord p, final WB_Coord v, final double r, final WB_Map2D map)
Parameters
p
v
r
map
References wblut.geom.WB_Point.addMul(), and wblut.processing.WB_Render3D.drawSegmentEmbedded2D().
void wblut.processing.WB_Render3D.drawVectorMapped (final WB_Coord p, final WB_Coord v, final double r, final WB_Map map)
Parameters
p
v
r
map
References wblut.geom.WB_Point.addMul(), and wblut.processing.WB_Render3D.drawSegmentMapped().
void wblut.processing.WB_Render3D.drawVectorUnmapped (final WB_Coord p, final WB_Coord v, final double r, final WB_Map map)
Parameters
p
v
r
map
References wblut.geom.WB_Point.addMul(), and wblut.processing.WB_Render3D.drawSegmentUnmapped().
void wblut.processing.WB_Render3D.drawVertex (final long key, final HE_Mesh mesh, final double d)
Parameters
key
mesh
d
References wblut.hemesh.HE_Mesh.getVertexWithKey(), wblut.hemesh.HE_MeshElement.isVisible(), and wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawVertex (final HE_Vertex v, final double d)
References wblut.hemesh.HE_MeshElement.isVisible(), and wblut.processing.WB_Render3D.translate().
void wblut.processing.WB_Render3D.drawVertexNormals (final HE_HalfedgeStructure mesh, final double d)
Parameters
mesh
d
References wblut.processing.WB_Render3D.drawVector(), wblut.hemesh.HE_Vertex.getVertexNormal(), and wblut.hemesh.HE_HalfedgeStructure.vItr().
void wblut.processing.WB_Render3D.drawVertices (final HE_HalfedgeStructure mesh)
Parameters
mesh
References wblut.hemesh.HE_MeshElement.isVisible(), wblut.hemesh.HE_HalfedgeStructure.vItr(), wblut.hemesh.HE_Vertex.xf(), wblut.hemesh.HE_Vertex.yf(), and wblut.hemesh.HE_Vertex.zf().
void wblut.processing.WB_Render3D.drawVertices (final HE_HalfedgeStructure mesh, final double d)
Parameters
mesh
d
References wblut.hemesh.HE_MeshElement.isVisible(), wblut.processing.WB_Render3D.translate(), and wblut.hemesh.HE_HalfedgeStructure.vItr().
void wblut.processing.WB_Render3D.drawVerticesWithInternalLabel (final int label, final HE_HalfedgeStructure mesh, final double d)
Parameters
label
mesh
d
References wblut.processing.WB_Render3D.drawVertex(), wblut.hemesh.HE_Element.getInternalLabel(), wblut.hemesh.HE_MeshElement.isVisible(), and wblut.hemesh.HE_HalfedgeStructure.vItr().
void wblut.processing.WB_Render3D.drawVerticesWithLabel (final int label, final HE_HalfedgeStructure mesh, final double d)
Parameters
label
mesh
d
References wblut.processing.WB_Render3D.drawVertex(), wblut.hemesh.HE_Element.getUserLabel(), wblut.hemesh.HE_MeshElement.isVisible(), and wblut.hemesh.HE_HalfedgeStructure.vItr().
static int wblut.processing.WB_Render3D.getColorFromPImage (final double u, final double v, final PImage texture) static
Parameters
u
v
texture
Returns
PGraphicsOpenGL wblut.processing.WB_Render3D.getHome ()
Returns
References wblut.processing.WB_Render3D.home.
WB_Ray wblut.processing.WB_Render3D.getPickingRay (final double x, final double y)
Parameters
x
y
Returns
void wblut.processing.WB_Render3D.line (final WB_Coord p, final WB_Coord q) private
Parameters
p
q
References wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.line (final double x1, final double y1, final double z1, final double x2, final double y2, final double z2)
References wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.normal (final WB_Coord n)
Parameters
n
References wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
HE_Face wblut.processing.WB_Render3D.pickClosestFace (final HE_Mesh mesh, final double x, final double y)
Parameters
mesh
x
y
Returns
References wblut.hemesh.HE_FaceIntersection.face, wblut.hemesh.HET_MeshOp.getClosestIntersection(), and wblut.processing.WB_Render3D.getPickingRay().
HE_Face wblut.processing.WB_Render3D.pickClosestFace (final WB_AABBTree meshtree, final double x, final double y)
Parameters
meshtree
x
y
Returns
References wblut.hemesh.HE_FaceIntersection.face, wblut.hemesh.HET_MeshOp.getClosestIntersection(), and wblut.processing.WB_Render3D.getPickingRay().
HE_Halfedge wblut.processing.WB_Render3D.pickEdge (final HE_Mesh mesh, final double x, final double y)
Parameters
mesh
x
y
Returns
References wblut.hemesh.HE_FaceIntersection.face, wblut.hemesh.HE_Face.feCrc(), wblut.hemesh.HET_MeshOp.getClosestIntersection(), wblut.geom.WB_GeometryOp3D.getDistanceToSegment3D(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.processing.WB_Render3D.getPickingRay(), wblut.hemesh.HE_Halfedge.getStartVertex(), wblut.hemesh.HE_FaceEdgeCirculator.hasNext(), wblut.hemesh.HE_FaceEdgeCirculator.next(), and wblut.hemesh.HE_FaceIntersection.point.
HE_Halfedge wblut.processing.WB_Render3D.pickEdge (final WB_AABBTree tree, final double x, final double y)
Parameters
tree
x
y
Returns
References wblut.hemesh.HE_FaceIntersection.face, wblut.hemesh.HE_Face.feCrc(), wblut.hemesh.HET_MeshOp.getClosestIntersection(), wblut.geom.WB_GeometryOp3D.getDistanceToSegment3D(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.processing.WB_Render3D.getPickingRay(), wblut.hemesh.HE_Halfedge.getStartVertex(), wblut.hemesh.HE_FaceEdgeCirculator.hasNext(), wblut.hemesh.HE_FaceEdgeCirculator.next(), and wblut.hemesh.HE_FaceIntersection.point.
List<HE_Face> wblut.processing.WB_Render3D.pickFaces (final HE_Mesh mesh, final double x, final double y)
Parameters
mesh
x
y
Returns
References wblut.hemesh.HET_MeshOp.getIntersection(), and wblut.processing.WB_Render3D.getPickingRay().
List<HE_Face> wblut.processing.WB_Render3D.pickFaces (final WB_AABBTree meshtree, final double x, final double y)
Parameters
meshtree
x
y
Returns
References wblut.hemesh.HET_MeshOp.getIntersection(), and wblut.processing.WB_Render3D.getPickingRay().
HE_Face wblut.processing.WB_Render3D.pickFurthestFace (final HE_Mesh mesh, final double x, final double y)
Parameters
mesh
x
y
Returns
References wblut.hemesh.HE_FaceIntersection.face, wblut.hemesh.HET_MeshOp.getFurthestIntersection(), and wblut.processing.WB_Render3D.getPickingRay().
HE_Face wblut.processing.WB_Render3D.pickFurthestFace (final WB_AABBTree meshtree, final double x, final double y)
Parameters
meshtree
x
y
Returns
References wblut.hemesh.HE_FaceIntersection.face, wblut.hemesh.HET_MeshOp.getFurthestIntersection(), and wblut.processing.WB_Render3D.getPickingRay().
HE_Vertex wblut.processing.WB_Render3D.pickVertex (final HE_Mesh mesh, final double x, final double y)
Parameters
mesh
x
y
Returns
References wblut.hemesh.HE_FaceIntersection.face, wblut.hemesh.HE_Face.fvCrc(), wblut.hemesh.HET_MeshOp.getClosestIntersection(), wblut.processing.WB_Render3D.getPickingRay(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.getSqDistance(), wblut.hemesh.HE_FaceVertexCirculator.hasNext(), wblut.hemesh.HE_FaceVertexCirculator.next(), and wblut.hemesh.HE_FaceIntersection.point.
HE_Vertex wblut.processing.WB_Render3D.pickVertex (final WB_AABBTree tree, final double x, final double y)
Parameters
tree
x
y
Returns
References wblut.hemesh.HE_FaceIntersection.face, wblut.hemesh.HE_Face.fvCrc(), wblut.hemesh.HET_MeshOp.getClosestIntersection(), wblut.processing.WB_Render3D.getPickingRay(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.getSqDistance(), wblut.hemesh.HE_FaceVertexCirculator.hasNext(), wblut.hemesh.HE_FaceVertexCirculator.next(), and wblut.hemesh.HE_FaceIntersection.point.
void wblut.processing.WB_Render3D.setFaceColorFromTexture (final HE_Mesh mesh, final PImage texture)
Parameters
mesh
texture
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.divSelf(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.fvCrc(), wblut.processing.WB_Render3D.getColorFromPImage(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceVertexCirculator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_FaceVertexCirculator.next(), wblut.hemesh.HE_MeshElement.setColor(), wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
void wblut.processing.WB_Render3D.setHalfedgeColorFromTexture (final HE_Mesh mesh, final PImage texture)
Parameters
mesh
texture
References wblut.hemesh.HE_Face.fheiCrc(), wblut.hemesh.HE_Mesh.fItr(), wblut.processing.WB_Render3D.getColorFromPImage(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceHalfedgeInnerCirculator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_FaceHalfedgeInnerCirculator.next(), wblut.hemesh.HE_MeshElement.setColor(), wblut.hemesh.HE_TextureCoordinate.ud(), and wblut.hemesh.HE_TextureCoordinate.vd().
void wblut.processing.WB_Render3D.setVertexColorFromTexture (final HE_Mesh mesh, final PImage texture)
Parameters
mesh
texture
References wblut.processing.WB_Render3D.getColorFromPImage(), wblut.hemesh.HE_Vertex.getVertexUVW(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_VertexIterator.next(), wblut.hemesh.HE_MeshElement.setColor(), wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), and wblut.hemesh.HE_Mesh.vItr().
void wblut.processing.WB_Render3D.translate (final WB_Coord p)
Parameters
p
References wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
void wblut.processing.WB_Render3D.vertex (final WB_Coord p)
Parameters
p
References wblut.geom.WB_Coord.xf(), wblut.geom.WB_Coord.yf(), and wblut.geom.WB_Coord.zf().
void wblut.processing.WB_Render3D.vertex (final double x, final double y, final double z)
void wblut.processing.WB_Render3D.vertexEmbedded2D (final WB_Coord p, final WB_Map2D map)
Parameters
p
map
References wblut.geom.WB_Map.mapPoint3D(), wblut.geom.WB_Map2D.unmapPoint2D(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.vertexMapped (final WB_Coord p, final WB_Map map)
Parameters
p
map
References wblut.geom.WB_Map.mapPoint3D(), and wblut.processing.WB_Render3D.vertex().
void wblut.processing.WB_Render3D.vertexUnmapped (final WB_Coord p, final WB_Map map)
Parameters
p
map
References wblut.geom.WB_Map.mapPoint3D(), and wblut.processing.WB_Render3D.vertex().
Member Data Documentation
WB_GeometryFactory wblut.processing.WB_Render3D.geometryfactory = new WB_GeometryFactory() private
final PGraphicsOpenGL wblut.processing.WB_Render3D.home protected
final WB_ProgressTracker wblut.processing.WB_Render3D.tracker = WB_ProgressTracker.instance() static
The documentation for this class was generated from the following file:
src/processing/wblut/processing/WB_Render3D.java