HE_Mesh: wblut.hemesh.HEC_Geodesic Class Reference
wblut.hemesh.HEC_Geodesic Class Reference
Public Member Functions
HEC_Geodesic ()
HEC_Geodesic (final double R)
HEC_Geodesic setRadius (final double R)
HEC_Geodesic setSphere (final WB_Sphere S)
HEC_Geodesic setRadius (final double rx, final double ry, final double rz)
HEC_Geodesic setB (final int b)
HEC_Geodesic setC (final int c)
HEC_Geodesic setType (final Type t)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Private Attributes
double rx
Type type
int b
int c
Additional Inherited Members
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Constructor & Destructor Documentation
wblut.hemesh.HEC_Geodesic.HEC_Geodesic ()
References wblut.geom.WB_Geodesic.Type.ICOSAHEDRON.
wblut.hemesh.HEC_Geodesic.HEC_Geodesic (final double R)
Parameters
R
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_Geodesic.createBase () protected
References wblut.hemesh.HE_Mesh.scaleSelf().
HEC_Geodesic wblut.hemesh.HEC_Geodesic.setB (final int b)
Parameters
b
Returns
References wblut.hemesh.HEC_Geodesic.b.
HEC_Geodesic wblut.hemesh.HEC_Geodesic.setC (final int c)
Parameters
c
Returns
References wblut.hemesh.HEC_Geodesic.c.
HEC_Geodesic wblut.hemesh.HEC_Geodesic.setRadius (final double R)
Parameters
R
Returns
HEC_Geodesic wblut.hemesh.HEC_Geodesic.setRadius (final double rx, final double ry, final double rz)
Parameters
rx
ry
rz
Returns
References wblut.hemesh.HEC_Geodesic.rx.
HEC_Geodesic wblut.hemesh.HEC_Geodesic.setSphere (final WB_Sphere S)
References wblut.geom.WB_Sphere.getCenter(), wblut.geom.WB_Sphere.getRadius(), and wblut.hemesh.HEC_Creator.setCenter().
HEC_Geodesic wblut.hemesh.HEC_Geodesic.setType (final Type t)
Parameters
t
Returns
Member Data Documentation
int wblut.hemesh.HEC_Geodesic.b private
int wblut.hemesh.HEC_Geodesic.c private
double wblut.hemesh.HEC_Geodesic.rx private
Type wblut.hemesh.HEC_Geodesic.type private
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_Geodesic.java