HE_Mesh: wblut.geom.WB_Point4D Class Reference
wblut.geom.WB_Point4D Class Reference
Public Member Functions
WB_Point4D ()
WB_Point4D (final double x, final double y, final double z, final double w)
WB_Point4D (final WB_Coord v)
WB_Point4D (final WB_Coord v, final double w)
WB_Point4D add (final double...x)
WB_Point4D add (final WB_Coord p)
WB_Point4D sub (final double...x)
WB_Point4D sub (final WB_Coord p)
WB_Point4D mul (final double f)
WB_Point4D div (final double f)
WB_Point4D addMul (final double f, final double...x)
WB_Point4D addMul (final double f, final WB_Coord p)
WB_Point4D mulAddMul (final double f, final double g, final double...x)
WB_Point4D mulAddMul (final double f, final double g, final WB_Coord p)
WB_Point4D addSelf (final double...x)
WB_Point4D addSelf (final WB_Coord p)
WB_Point4D subSelf (final double...x)
WB_Point4D subSelf (final WB_Coord v)
WB_Point4D mulSelf (final double f)
WB_Point4D divSelf (final double f)
WB_Point4D addMulSelf (final double f, final double...x)
WB_Point4D addMulSelf (final double f, final WB_Coord p)
WB_Point4D mulAddMulSelf (final double f, final double g, final double...x)
WB_Point4D mulAddMulSelf (final double f, final double g, final WB_Coord p)
WB_Point4D trimSelf (final double d)
WB_Point4D add3D (final double x, final double y, final double z)
WB_Point4D add3D (final WB_Coord p)
WB_Point4D sub3D (final double x, final double y, final double z)
WB_Point4D sub3D (final WB_Coord p)
WB_Point4D mul3D (final double f)
WB_Point4D div3D (final double f)
WB_Point4D addMul3D (final double f, final double x, final double y, final double z)
WB_Point4D addMul3D (final double f, final WB_Coord p)
WB_Point4D mulAddMul3D (final double f, final double g, final double x, final double y, final double z)
WB_Point4D mulAddMul3D (final double f, final double g, final WB_Coord p)
WB_Point4D add3DSelf (final double x, final double y, final double z)
WB_Point4D add3DSelf (final WB_Coord p)
WB_Point4D sub3DSelf (final double x, final double y, final double z)
WB_Point4D sub3DSelf (final WB_Coord v)
WB_Point4D mul3DSelf (final double f)
WB_Point4D div3DSelf (final double f)
WB_Point4D addMul3DSelf (final double f, final double x, final double y, final double z)
WB_Point4D addMul3DSelf (final double f, final WB_Coord p)
WB_Point4D mulAddMul3DSelf (final double f, final double g, final double x, final double y, final double z)
WB_Point4D mulAddMul3DSelf (final double f, final double g, final WB_Coord p)
WB_Point4D rotateXWSelf (final double theta)
WB_Point4D rotateXYSelf (final double theta)
WB_Point4D rotateXZSelf (final double theta)
WB_Point4D rotateYWSelf (final double theta)
WB_Point4D rotateYZSelf (final double theta)
WB_Point4D rotateZWSelf (final double theta)
WB_Point4D copy ()
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_Vector4D
WB_Vector4D ()
WB_Vector4D (final double x, final double y)
WB_Vector4D (final double x, final double y, final double z)
WB_Vector4D (final double x, final double y, final double z, final double w)
WB_Vector4D (final double[] x)
WB_Vector4D (final WB_Coord v)
WB_Vector4D add (final double...x)
WB_Vector4D add (final WB_Coord p)
WB_Vector4D sub (final double...x)
WB_Vector4D sub (final WB_Coord p)
WB_Vector4D mul (final double f)
WB_Vector4D div (final double f)
WB_Vector4D addMul (final double f, final double...x)
WB_Vector4D addMul (final double f, final WB_Coord p)
WB_Vector4D mulAddMul (final double f, final double g, final double...x)
WB_Vector4D mulAddMul (final double f, final double g, final WB_Coord p)
double absDot (final WB_Coord p)
double dot (final WB_Coord p)
void addInto (final WB_MutableCoord result, final double...x)
void addInto (final WB_MutableCoord result, final WB_Coord p)
void subInto (final WB_MutableCoord result, final double...x)
void subInto (final WB_MutableCoord result, final WB_Coord p)
void mulInto (final WB_MutableCoord result, final double f)
void divInto (final WB_MutableCoord result, final double f)
void addMulInto (final WB_MutableCoord result, final double f, final double...x)
void addMulInto (final WB_MutableCoord result, final double f, final WB_Coord p)
void mulAddMulInto (final WB_MutableCoord result, final double f, final double g, final double...x)
void mulAddMulInto (final WB_MutableCoord result, final double f, final double g, final WB_Coord p)
WB_Vector4D addSelf (final double...x)
WB_Vector4D addSelf (final WB_Coord p)
WB_Vector4D subSelf (final double...x)
WB_Vector4D subSelf (final WB_Coord v)
WB_Vector4D mulSelf (final double f)
WB_Vector4D divSelf (final double f)
WB_Vector4D addMulSelf (final double f, final double...x)
WB_Vector4D addMulSelf (final double f, final WB_Coord p)
WB_Vector4D mulAddMulSelf (final double f, final double g, final double...x)
WB_Vector4D mulAddMulSelf (final double f, final double g, final WB_Coord p)
double normalizeSelf ()
WB_Vector4D trimSelf (final double d)
void invert ()
WB_Vector4D add3D (final double x, final double y, final double z)
WB_Vector4D add3D (final WB_Coord p)
WB_Vector4D sub3D (final double x, final double y, final double z)
WB_Vector4D sub3D (final WB_Coord p)
WB_Vector4D mul3D (final double f)
WB_Vector4D div3D (final double f)
WB_Vector4D addMul3D (final double f, final double x, final double y, final double z)
WB_Vector4D addMul3D (final double f, final WB_Coord p)
WB_Vector4D mulAddMul3D (final double f, final double g, final double x, final double y, final double z)
WB_Vector4D mulAddMul3D (final double f, final double g, final WB_Coord p)
void add3DInto (final WB_MutableCoord result, final double x, final double y, final double z)
void add3DInto (final WB_MutableCoord result, final WB_Coord p)
void sub3DInto (final WB_MutableCoord result, final double x, final double y, final double z)
void sub3DInto (final WB_MutableCoord result, final WB_Coord p)
void mul3DInto (final WB_MutableCoord result, final double f)
void div3DInto (final WB_MutableCoord result, final double f)
void addMul3DInto (final WB_MutableCoord result, final double f, final double x, final double y, final double z)
void addMul3DInto (final WB_MutableCoord result, final double f, final WB_Coord p)
void mulAddMul3DInto (final WB_MutableCoord result, final double f, final double g, final double x, final double y, final double z)
void mulAddMul3DInto (final WB_MutableCoord result, final double f, final double g, final WB_Coord p)
WB_Vector4D add3DSelf (final double x, final double y, final double z)
WB_Vector4D add3DSelf (final WB_Coord p)
WB_Vector4D sub3DSelf (final double x, final double y, final double z)
WB_Vector4D sub3DSelf (final WB_Coord v)
WB_Vector4D mul3DSelf (final double f)
WB_Vector4D div3DSelf (final double f)
WB_Vector4D addMul3DSelf (final double f, final double x, final double y, final double z)
WB_Vector4D addMul3DSelf (final double f, final WB_Coord p)
WB_Vector4D mulAddMul3DSelf (final double f, final double g, final double x, final double y, final double z)
WB_Vector4D mulAddMul3DSelf (final double f, final double g, final WB_Coord p)
WB_Vector4D rotateXWSelf (final double theta)
WB_Vector4D rotateXYSelf (final double theta)
WB_Vector4D rotateXZSelf (final double theta)
WB_Vector4D rotateYWSelf (final double theta)
WB_Vector4D rotateYZSelf (final double theta)
WB_Vector4D rotateZWSelf (final double theta)
double getDistance4D (final WB_Coord p)
double getLength4D ()
double getSqDistance4D (final WB_Coord p)
double getSqLength4D ()
boolean isZero ()
double[] coords ()
WB_Vector4D copy ()
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoordinate4D
WB_MutableCoordinate4D ()
WB_MutableCoordinate4D (final double x, final double y)
WB_MutableCoordinate4D (final double x, final double y, final double z)
WB_MutableCoordinate4D (final double x, final double y, final double z, final double w)
WB_MutableCoordinate4D (final double[] x)
WB_MutableCoordinate4D (final WB_Coord v)
WB_MutableCoordinate4D (final double[] fromPoint, final double[] toPoint)
double getd (final int i)
float getf (final int i)
double xd ()
double yd ()
double zd ()
double wd ()
float xf ()
float yf ()
float zf ()
float wf ()
void setX (final double x)
void setY (final double y)
void setZ (final double z)
void setW (final double w)
void setCoord (final int i, final double v)
void set (final double x, final double y)
void set (final double x, final double y, final double z)
void set (final double x, final double y, final double z, final double w)
void set (final WB_Coord v)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoordinate
WB_MutableCoordinate ()
WB_MutableCoordinate (final double x, final double y)
WB_MutableCoordinate (final double x, final double y, final double z)
WB_MutableCoordinate (final double[] x)
WB_MutableCoordinate (final double[] fromPoint, final double[] toPoint)
WB_MutableCoordinate (final WB_Coord v)
WB_MutableCoordinate (final WB_Coord fromPoint, final WB_Coord toPoint)
double getd (final int i)
float getf (final int i)
double xd ()
double yd ()
double zd ()
double wd ()
float xf ()
float yf ()
float zf ()
float wf ()
void setX (final double x)
void setY (final double y)
void setZ (final double z)
void setW (final double w)
void setCoord (final int i, final double v)
void set (final double x, final double y)
void set (final double x, final double y, final double z)
void set (final double x, final double y, final double z, final double w)
void set (final WB_Coord v)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoordinate2D
WB_MutableCoordinate2D ()
WB_MutableCoordinate2D (final double x, final double y)
WB_MutableCoordinate2D (final double[] x)
WB_MutableCoordinate2D (final double[] fromPoint, final double[] toPoint)
WB_MutableCoordinate2D (final WB_Coord v)
WB_MutableCoordinate2D (final WB_Coord fromPoint, final WB_Coord toPoint)
double getd (final int i)
float getf (final int i)
double xd ()
double yd ()
double zd ()
double wd ()
float xf ()
float yf ()
float zf ()
float wf ()
void setX (final double x)
void setY (final double y)
void setZ (final double z)
void setW (final double w)
void setCoord (final int i, final double v)
void set (final WB_Coord v)
void set (final double x, final double y)
void set (final double x, final double y, final double z)
void set (final double x, final double y, final double z, final double w)
int compareTo (final WB_Coord p)
int compareToY1st (final WB_Coord p)
boolean equals (final Object o)
int hashCode ()
String toString ()
Public Member Functions inherited from wblut.geom.WB_MutableCoord
void setX (double x)
void setY (double y)
void setZ (double z)
void setW (double w)
void setCoord (int i, double v)
void set (WB_Coord p)
void set (double x, double y)
void set (double x, double y, double z)
void set (double x, double y, double z, double w)
Public Member Functions inherited from wblut.geom.WB_Coord
double getd (int i)
float getf (int i)
Public Member Functions inherited from wblut.geom.WB_MutableCoordinateTransform4D
WB_Vector4D rotateXWSelf (double angle)
WB_Vector4D rotateXYSelf (double angle)
WB_Vector4D rotateXZSelf (double angle)
WB_Vector4D rotateYWSelf (double angle)
WB_Vector4D rotateYZSelf (double angle)
WB_Vector4D rotateZWSelf (double angle)
Static Public Member Functions
static final WB_Point4D ZERO ()
static WB_Point4D add (final WB_Coord p, final WB_Coord q)
static WB_Point4D sub (final WB_Coord p, final WB_Coord q)
static WB_Point4D mul (final WB_Coord p, final double f)
static WB_Point4D div (final WB_Coord p, final double f)
static WB_Point4D addMul (final WB_Coord p, final double f, final WB_Coord q)
static WB_Point4D mulAddMul (final double f, final WB_Coord p, final double g, final WB_Coord q)
static WB_Point4D interpolate (final WB_Coord p0, final WB_Coord p1, final double t)
Static Public Member Functions inherited from wblut.geom.WB_Vector4D
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord Z ()
static WB_Coord ZERO ()
static WB_Vector4D add (final WB_Coord p, final WB_Coord q)
static WB_Vector4D sub (final WB_Coord p, final WB_Coord q)
static WB_Vector4D mul (final WB_Coord p, final double f)
static WB_Vector4D div (final WB_Coord p, final double f)
static WB_Vector4D addMul (final WB_Coord p, final double f, final WB_Coord q)
static WB_Vector4D mulAddMul (final double f, final WB_Coord p, final double g, final WB_Coord q)
static double absDot (final WB_Coord p, final WB_Coord q)
static double dot (final WB_Coord p, final WB_Coord q)
static double getDistance4D (final WB_Coord q, final WB_Coord p)
static double getSqDistance4D (final WB_Coord q, final WB_Coord p)
static double getLength4D (final WB_Coord p)
static double getSqLength4D (final WB_Coord v)
static WB_Vector4D interpolate (final WB_Coord p0, final WB_Coord p1, final double t)
Static Public Member Functions inherited from wblut.geom.WB_MutableCoordinate4D
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord Z ()
static WB_Coord W ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
Static Public Member Functions inherited from wblut.geom.WB_MutableCoordinate
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord Z ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
Static Public Member Functions inherited from wblut.geom.WB_MutableCoordinate2D
static WB_Coord X ()
static WB_Coord Y ()
static WB_Coord ZERO ()
static WB_Coord ORIGIN ()
Constructor & Destructor Documentation
wblut.geom.WB_Point4D.WB_Point4D ()
wblut.geom.WB_Point4D.WB_Point4D (final double x, final double y, final double z, final double w)
Parameters
x
y
z
w
wblut.geom.WB_Point4D.WB_Point4D (final WB_Coord v)
Parameters
v
References wblut.geom.WB_Coord.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
wblut.geom.WB_Point4D.WB_Point4D (final WB_Coord v, final double w)
Parameters
v
w
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
Member Function Documentation
static WB_Point4D wblut.geom.WB_Point4D.add (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point4D wblut.geom.WB_Point4D.add (final double... x)
Add coordinate values.
Parameters
x
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.add (final WB_Coord p)
Add coordinate values.
Parameters
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.add3D (final double x, final double y, final double z)
Parameters
x
y
z
Returns
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.add3D (final WB_Coord p)
Add 3D coordinate values. Leave w-value unchanged.
Parameters
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.add3DSelf (final double x, final double y, final double z)
Parameters
x
y
z
Returns
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.add3DSelf (final WB_Coord p)
Parameters
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
static WB_Point4D wblut.geom.WB_Point4D.addMul (final WB_Coord p, final double f, final WB_Coord q) static
Parameters
p
f
q
Returns
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point4D wblut.geom.WB_Point4D.addMul (final double f, final double... x)
Add multiple of coordinate values.
Parameters
f multiplier
x
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.addMul (final double f, final WB_Coord p)
Add multiple of coordinate values.
Parameters
f
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.addMul3D (final double f, final double x, final double y, final double z)
Add multiple of 3D coordinate values. Leave w-value unchanged.
Parameters
f multiplier
x
y
z
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.addMul3D (final double f, final WB_Coord p)
Add multiple of 3D coordinate values. Leave w-value unchanged.
Parameters
f
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.addMul3DSelf (final double f, final double x, final double y, final double z)
Parameters
f
x
y
z
Returns
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.addMul3DSelf (final double f, final WB_Coord p)
Parameters
f
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.addMulSelf (final double f, final double... x)
Parameters
f
x
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.addMulSelf (final double f, final WB_Coord p)
Parameters
f
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.addSelf (final double... x)
Parameters
x
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.addSelf (final WB_Coord p)
Parameters
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
int wblut.geom.WB_Point4D.compareTo (final WB_Coord p)
References wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
int wblut.geom.WB_Point4D.compareToY1st (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.copy ()
Returns
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
static WB_Point4D wblut.geom.WB_Point4D.div (final WB_Coord p, final double f) static
Parameters
p
f
Returns
References wblut.geom.WB_Point4D.mul().
WB_Point4D wblut.geom.WB_Point4D.div (final double f)
Divide by factor.
Parameters
f
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.mul().
WB_Point4D wblut.geom.WB_Point4D.div3D (final double f)
Divide by factor. Leave w-value unchanged.
Parameters
f
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.mul3D().
WB_Point4D wblut.geom.WB_Point4D.div3DSelf (final double f)
Parameters
f
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_Point4D.mul3DSelf().
WB_Point4D wblut.geom.WB_Point4D.divSelf (final double f)
Parameters
f
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_Point4D.mulSelf().
boolean wblut.geom.WB_Point4D.equals (final Object o)
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
int wblut.geom.WB_Point4D.hashCode ()
References wblut.math.WB_HashCode.calculateHashCode(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
static WB_Point4D wblut.geom.WB_Point4D.interpolate (final WB_Coord p0, final WB_Coord p1, final double t) static
Parameters
p0
p1
t
Returns
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static WB_Point4D wblut.geom.WB_Point4D.mul (final WB_Coord p, final double f) static
Parameters
p
f
Returns
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point4D wblut.geom.WB_Point4D.mul (final double f)
Multiply by factor.
Parameters
f
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.mul3D (final double f)
Multiply by factor. Leave w-value unchanged.
Parameters
f
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.mul3DSelf (final double f)
Parameters
f
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
static WB_Point4D wblut.geom.WB_Point4D.mulAddMul (final double f, final WB_Coord p, final double g, final WB_Coord q) static
Parameters
f
p
g
q
Returns
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point4D wblut.geom.WB_Point4D.mulAddMul (final double f, final double g, final double... x)
Multiply this coordinate by factor f and add other coordinate values multiplied by g.
Parameters
f
g
x
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.mulAddMul (final double f, final double g, final WB_Coord p)
Multiply this coordinate by factor f and add other coordinate values multiplied by g.
Parameters
f
g
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.mulAddMul3D (final double f, final double g, final double x, final double y, final double z)
Multiply this coordinate by factor f and add other coordinate values multiplied by g. Leave w-value unchanged.
Parameters
f
g
x
y
z
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.mulAddMul3D (final double f, final double g, final WB_Coord p)
Multiply this coordinate by factor f and add other coordinate values multiplied by g. Leave w-value unchanged.
Parameters
f
g
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.mulAddMul3DSelf (final double f, final double g, final double x, final double y, final double z)
Parameters
f
g
x
y
z
Returns
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.mulAddMul3DSelf (final double f, final double g, final WB_Coord p)
Parameters
f
g
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.mulAddMulSelf (final double f, final double g, final double... x)
Parameters
f
g
x
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.mulAddMulSelf (final double f, final double g, final WB_Coord p)
Parameters
f
g
p
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.mulSelf (final double f)
Parameters
f
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.rotateXWSelf (final double theta)
Parameters
theta
Returns
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.rotateXYSelf (final double theta)
Parameters
theta
Returns
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.rotateXZSelf (final double theta)
Parameters
theta
Returns
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.rotateYWSelf (final double theta)
Parameters
theta
Returns
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.rotateYZSelf (final double theta)
Parameters
theta
Returns
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.rotateZWSelf (final double theta)
Parameters
theta
Returns
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
static WB_Point4D wblut.geom.WB_Point4D.sub (final WB_Coord p, final WB_Coord q) static
Parameters
p
q
Returns
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Point4D wblut.geom.WB_Point4D.sub (final double... x)
Subtract coordinate values.
Parameters
x
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.sub (final WB_Coord p)
Subtract coordinate values.
Parameters
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.sub3D (final double x, final double y, final double z)
Subtract 3D coordinate values. Leave w-value unchanged.
Parameters
x
y
z
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.sub3D (final WB_Coord p)
Subtract 3D coordinate values. Leave w-value unchanged.
Parameters
p
Returns
new WB_Coord
Implements wblut.geom.WB_CoordinateMath4D.
References wblut.geom.WB_Point4D.WB_Point4D(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.sub3DSelf (final double x, final double y, final double z)
Parameters
x
y
z
Returns
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.sub3DSelf (final WB_Coord v)
Parameters
v
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.subSelf (final double... x)
Parameters
x
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.subSelf (final WB_Coord v)
Parameters
v
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_MutableCoordinate4D.set(), wblut.geom.WB_Coord.wd(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_Coord.yd(), wblut.geom.WB_MutableCoordinate4D.yd(), wblut.geom.WB_Coord.zd(), and wblut.geom.WB_MutableCoordinate4D.zd().
String wblut.geom.WB_Point4D.toString ()
References wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_Point4D wblut.geom.WB_Point4D.trimSelf (final double d)
Parameters
d
Returns
this
Implements wblut.geom.WB_MutableCoordinateMath4D.
References wblut.geom.WB_Vector4D.getSqLength4D(), wblut.geom.WB_Point4D.mulSelf(), and wblut.geom.WB_Vector4D.normalizeSelf().
static final WB_Point4D wblut.geom.WB_Point4D.ZERO () static
Returns
References wblut.geom.WB_Point4D.WB_Point4D().
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Point4D.java