HE_Mesh: wblut.geom.WB_PolygonSplitter Class Reference
wblut.geom.WB_PolygonSplitter Class Reference
Classes
class EdgeOnLineComparator
class PolyEdge
Static Public Member Functions
static List< WB_Polygon > splitSimplePolygon2D (final WB_Polygon polygon, final WB_Line L)
static List< WB_Polygon > splitSimplePolygon3D (final WB_Polygon polygon, final WB_Plane P)
static List< WB_Polygon > splitPolygon2D (final WB_Polygon polygon, final WB_Line L)
static List< WB_Polygon > splitPolygon3D (final WB_Polygon polygon, final WB_Plane P)
static void main (final String[] args)
Detailed Description
Author
FVH
    Port of David Geier's algorithm
    https://geidav.wordpress.com/2015/03/21/splitting-an-arbitrary-
    polygon-by-a-line/
Member Function Documentation
static void wblut.geom.WB_PolygonSplitter.main (final String[] args) static
References wblut.geom.WB_PolygonSplitter.splitSimplePolygon2D(), and wblut.geom.WB_PolygonSplitter.splitSimplePolygon3D().
static List<WB_Polygon> wblut.geom.WB_PolygonSplitter.splitPolygon2D (final WB_Polygon polygon, final WB_Line L) static
References wblut.geom.WB_GeometryFactory2D.createSimplePolygon(), wblut.geom.WB_TriangleGenerator.getPoints(), and wblut.geom.WB_CoordCollection.toList().
static List<WB_Polygon> wblut.geom.WB_PolygonSplitter.splitPolygon3D (final WB_Polygon polygon, final WB_Plane P) static
References wblut.geom.WB_GeometryFactory2D.createSimplePolygon(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.geom.WB_Polygon.getPlane(), wblut.geom.WB_TriangleGenerator.getPoints(), wblut.geom.WB_IntersectionResult.intersection, wblut.geom.WB_IntersectionResult.object, and wblut.geom.WB_CoordCollection.toList().
static List<WB_Polygon> wblut.geom.WB_PolygonSplitter.splitSimplePolygon2D (final WB_Polygon polygon, final WB_Line L) static
References wblut.geom.WB_TriangleGenerator.getPoints(), and wblut.geom.WB_CoordCollection.toList().
static List<WB_Polygon> wblut.geom.WB_PolygonSplitter.splitSimplePolygon3D (final WB_Polygon polygon, final WB_Plane P) static
References wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.geom.WB_Polygon.getPlane(), wblut.geom.WB_TriangleGenerator.getPoints(), wblut.geom.WB_IntersectionResult.intersection, wblut.geom.WB_IntersectionResult.object, and wblut.geom.WB_CoordCollection.toList().
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_PolygonSplitter.java