HE_Mesh: wblut.hemesh.HET_MeshOp Class Reference
wblut.hemesh.HET_MeshOp Class Reference
Classes
class HET_IntersectionResult
Static Public Member Functions
static HE_Selection splitEdge (final HE_Mesh mesh, final HE_Halfedge edge)
static HE_Selection splitEdge (final HE_Mesh mesh, final HE_Halfedge edge, final double f)
static void splitEdge (final HE_Mesh mesh, final HE_Halfedge edge, final double x, final double y, final double z)
static void splitEdge (final HE_Mesh mesh, final HE_Halfedge edge, final double[] f)
static void splitEdge (final HE_Mesh mesh, final HE_Halfedge edge, final float[] f)
static HE_Selection splitEdge (final HE_Mesh mesh, final HE_Halfedge edge, final WB_Coord v)
static HE_Selection splitEdge (final HE_Mesh mesh, final long key)
static HE_Selection splitEdge (final HE_Mesh mesh, final long key, final double f)
static void splitEdge (final HE_Mesh mesh, final long key, final double x, final double y, final double z)
static void splitEdge (final HE_Mesh mesh, final long key, final double[] f)
static void splitEdge (final HE_Mesh mesh, final long key, final float[] f)
static HE_Selection splitEdge (final HE_Mesh mesh, final Long key, final WB_Point v)
static HE_Selection splitEdges (final HE_Mesh mesh)
static HE_Selection splitEdges (final HE_Mesh mesh, final double offset)
static HE_Selection splitEdges (final HE_Selection selection)
static HE_Selection splitEdges (final HE_Selection selection, final double offset)
static void divideEdge (final HE_Mesh mesh, final HE_Halfedge origE, final int n)
static void divideEdge (final HE_Mesh mesh, final long key, final int n)
static HE_Selection splitFace (final HE_Mesh mesh, final HE_Face face, final HE_Vertex vi, final HE_Vertex vj)
static HE_Selection splitFace (final HE_Mesh mesh, final long fkey, final long vkeyi, final long vkeyj)
static HE_Selection splitFacesCenter (final HE_Mesh mesh)
static HE_Selection splitFacesCenter (final HE_Mesh mesh, final double d)
static HE_Selection splitFacesCenter (final HE_Mesh mesh, final double d, final double c)
static HE_Selection splitFacesCenter (final HE_Selection faces)
static HE_Selection splitFacesCenter (final HE_Selection faces, final double d)
static HE_Selection splitFacesCenter (final HE_Selection faces, final double d, final double c)
static HE_Selection splitFacesCenterHole (final HE_Mesh mesh)
static HE_Selection splitFacesCenterHole (final HE_Mesh mesh, final double d)
static HE_Selection splitFacesCenterHole (final HE_Mesh mesh, final double d, final double c)
static HE_Selection splitFacesCenterHole (final HE_Selection faces)
static HE_Selection splitFacesCenterHole (final HE_Selection faces, final double d)
static HE_Selection splitFacesCenterHole (final HE_Selection faces, final double d, final double c)
static HE_Selection splitFacesHybrid (final HE_Mesh mesh)
static HE_Selection splitFacesHybrid (final HE_Selection sel)
static HE_Selection splitFacesMidEdge (final HE_Mesh mesh)
static HE_Selection splitFacesMidEdge (final HE_Selection selection)
static HE_Selection splitFacesMidEdgeHole (final HE_Mesh mesh)
static HE_Selection splitFacesMidEdgeHole (final HE_Selection selection)
static HE_Selection splitFacesQuad (final HE_Mesh mesh)
static HE_Selection splitFacesQuad (final HE_Mesh mesh, final double d)
static HE_Selection splitFacesQuad (final HE_Selection sel)
static HE_Selection splitFacesQuad (final HE_Selection sel, final double d)
static HE_Selection splitFacesTri (final HE_Mesh mesh)
static HE_Selection splitFacesTri (final HE_Mesh mesh, final double d)
static HE_Selection splitFacesTri (final HE_Selection selection)
static HE_Selection splitFacesTri (final HE_Selection selection, final double d)
static HE_Selection triangulate (final HE_Mesh mesh)
static HE_Selection triangulate (final HE_Mesh mesh, final HE_Face face)
static HE_Selection triangulate (final HE_Selection sel)
static HE_Selection triangulate (final HE_Mesh mesh, final long key)
static HE_Selection triangulateConcaveFace (final HE_Mesh mesh, final HE_Face face)
static HE_Selection triangulateConcaveFace (final HE_Mesh mesh, final long key)
static HE_Selection triangulateConcaveFaces (final HE_Mesh mesh)
static HE_Selection triangulateConcaveFaces (final HE_Mesh mesh, final List< HE_Face > sel)
static HE_Selection triangulateFaceStar (final HE_Mesh mesh, final HE_Vertex v)
static HE_Selection triangulateFaceStar (final HE_Mesh mesh, final long vertexkey)
static HE_Face createFaceFromHalfedgeLoop (final HE_Mesh mesh, final HE_Halfedge he)
static List< HE_Face > createFaceFromHalfedgeLoop (final HE_Mesh mesh, final List< HE_Halfedge > hes)
static HE_RAS< HE_Face > selectAllFacesConnectedToUnpairedHalfedge (final HE_Mesh mesh, final HE_Halfedge unpairedHalfedge)
static HE_Mesh flipFaces (final HE_Mesh mesh)
static void flipFaces (final HE_Mesh mesh, final HE_RAS< HE_Face > faces)
static boolean flipEdge (final HE_Mesh mesh, final HE_Halfedge he)
static boolean flipEdgeConditional (final HE_Mesh mesh, final HE_Halfedge he)
static boolean flipPlanarEdgeConditional (final HE_Mesh mesh, final HE_Halfedge he, final double cosa)
static boolean flipPlanarEdgeConditional (final HE_Mesh mesh, final HE_Halfedge he)
static void improveTriangulation (final HE_Mesh mesh, final HE_Selection triangles)
static void improveTriangulation (final HE_Mesh mesh)
static void improveTriangulation (final HE_Mesh mesh, final double cosa)
static void improveTriangulation (final HE_Mesh mesh, final HE_Selection triangles, final double cosa)
static HE_Mesh cleanUnusedElementsByFace (final HE_Mesh mesh)
static void assignFaceToLoop (final HE_Mesh mesh, final HE_Face face, final HE_Halfedge halfedge)
static HE_FaceIntersection getIntersection (final HE_Face face, final WB_Line line)
static HE_FaceIntersection getIntersection (final HE_Face face, final WB_Ray ray)
static HE_FaceIntersection getIntersection (final HE_Face face, final WB_Segment segment)
static double getIntersection (final HE_Halfedge e, final WB_Plane P)
static List< HE_FaceIntersection > getIntersection (final WB_AABBTree tree, final WB_Ray ray)
static boolean isInside (final HE_Mesh mesh, final WB_Coord p)
static boolean isInside (final WB_AABBTree tree, final WB_Coord p)
static List< HE_FaceIntersection > getIntersection (final WB_AABBTree tree, final WB_Segment segment)
static List< HE_FaceIntersection > getIntersection (final WB_AABBTree tree, final WB_Line line)
static List< WB_Segment > getIntersection (final WB_AABBTree tree, final WB_Plane P)
static List< HE_Face > getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_Plane P)
static List< HE_Face > getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_Triangle T)
static List< HE_Face > getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_AABB AABB)
static List< HE_Face > getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_Coord p)
static List< HE_Face > getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_Ray R)
static List< HE_Face > getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_Line L)
static List< HE_Face > getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_Segment segment)
static HE_FaceIntersection getClosestIntersection (final WB_AABBTree tree, final WB_Ray ray)
static HE_FaceIntersection getFurthestIntersection (final WB_AABBTree tree, final WB_Ray ray)
static HE_FaceIntersection getClosestIntersection (final WB_AABBTree tree, final WB_Line line)
static HE_FaceIntersection getFurthestIntersection (final WB_AABBTree tree, final WB_Line line)
static HE_FaceIntersection getClosestIntersection (final WB_AABBTree tree, final WB_Segment segment)
static HE_FaceIntersection getFurthestIntersection (final WB_AABBTree tree, final WB_Segment segment)
static List< HE_FaceIntersection > getIntersection (final HE_Mesh mesh, final WB_Ray ray)
static List< HE_FaceIntersection > getIntersection (final HE_Mesh mesh, final WB_Segment segment)
static List< HE_FaceIntersection > getIntersection (final HE_Mesh mesh, final WB_Line line)
static List< WB_Segment > getIntersection (final HE_Mesh mesh, final WB_Plane P)
static List< HE_Face > getPotentialIntersectedFaces (final HE_Mesh mesh, final WB_Plane P)
static List< HE_Face > getPotentialIntersectedFaces (final HE_Mesh mesh, final WB_Ray R)
static List< HE_Face > getPotentialIntersectedFaces (final HE_Mesh mesh, final WB_Line L)
static List< HE_Face > getPotentialIntersectedFaces (final HE_Mesh mesh, final WB_Segment segment)
static HE_FaceIntersection getClosestIntersection (final HE_Mesh mesh, final WB_Ray ray)
static HE_FaceIntersection getFurthestIntersection (final HE_Mesh mesh, final WB_Ray ray)
static HE_FaceIntersection getClosestIntersection (final HE_Mesh mesh, final WB_Line line)
static HE_FaceIntersection getFurthestIntersection (final HE_Mesh mesh, final WB_Line line)
static HE_FaceIntersection getClosestIntersection (final HE_Mesh mesh, final WB_Segment segment)
static HE_FaceIntersection getFurthestIntersection (final HE_Mesh mesh, final WB_Segment segment)
static WB_Classification classifyFaceToPlane3D (final HE_Face f, final WB_Plane P)
static WB_Classification classifyEdgeToPlane3D (final HE_Halfedge edge, final WB_Plane P)
static WB_Classification classifyVertexToPlane3D (final HE_Vertex v, final WB_Plane P)
static WB_Classification getVertexType (final HE_Vertex vertex)
static WB_CoordinateSystem3D getVertexCS (final HE_Vertex v)
static WB_Coord getVertexNormal (final HE_Vertex v)
static WB_Coord getVertexNormalAverage (final HE_Vertex v)
static WB_Coord getVertexNormalArea (final HE_Vertex v)
static WB_Coord getVertexNormalAngle (final HE_Vertex v)
static WB_Coord getVertexNormalGaussCurvature (final HE_Vertex v)
static WB_Coord getVertexNormalMeanCurvature (final HE_Vertex v)
static WB_Coord getVertexNormalSphereInscribed (final HE_Vertex v)
static double getUmbrellaAngle (final HE_Vertex v)
static double getAngleDefect (final HE_Vertex v)
static double getAngleDefect (final HE_Mesh mesh)
static double getScalarGaussCurvature (final HE_Vertex v)
static double getScalarMeanCurvature (final HE_Vertex v)
static double getVertexArea (final HE_Vertex v)
static double getBarycentricDualVertexArea (final HE_Vertex v)
static double getCircumcentricDualVertexArea (final HE_Vertex v)
static double[] getPrincipalCurvatures (final HE_Vertex v)
static double getGaussianCurvature (final HE_Vertex vertex, final WB_Vector meanCurvatureVector)
static double getGaussCurvature (final HE_Vertex vertex)
static WB_CoordinateSystem3D getCurvatureDirections (final HE_Vertex v)
static WB_Coord getFaceNormal (final HE_Face face)
static WB_Coord getFaceNormalNotNormalized (final HE_Face face)
static double getFaceArea (final HE_Face face)
static WB_Classification getFaceType (final HE_Face face)
static boolean collapseHalfedge (final HE_Mesh mesh, final HE_Halfedge he)
static boolean collapseHalfedgeBoundaryPreserving (final HE_Mesh mesh, final HE_Halfedge he)
static boolean collapseEdge (final HE_Mesh mesh, final HE_Halfedge e)
static boolean collapseEdgeBoundaryPreserving (final HE_Mesh mesh, final HE_Halfedge e, final boolean strict)
static boolean pointIsInFace (final WB_Coord p, final HE_Face f)
static boolean pointIsStrictlyInFace (final WB_Coord p, final HE_Face f)
static void expandVertexToEdge (final HE_Mesh mesh, final HE_Vertex v, final HE_Face f1, final HE_Face f2, final WB_Coord vn)
static double getVolume (final HE_Mesh mesh)
static WB_Coord[] getClosestPointToTriangleFace (final WB_Coord p, final HE_Face T)
static WB_Coord[] getClosestPointToTriangleMesh (final WB_Coord p, final HE_Mesh mesh)
static void liftEdges (final HE_Selection edges, final double d)
static double getCotan (final HE_Halfedge he)
static DoubleMatrix2D getLaplaceMatrix (final HE_Mesh mesh)
static DoubleMatrix2D getMassMatrix (final HE_Mesh mesh)
static double[] getMassArray (final HE_Mesh mesh)
static DoubleMatrix2D getHodgeStar0Form (final HE_Mesh mesh)
static DoubleMatrix2D getHodgeStar1Form (final HE_Mesh mesh)
static DoubleMatrix2D getHodgeStar2Form (final HE_Mesh mesh)
static DoubleMatrix2D getExteriorDerivative0Form (final HE_Mesh mesh)
static DoubleMatrix2D getExteriorDerivative1Form (final HE_Mesh mesh)
static List< HET_IntersectionResult > getIntersection (final HE_Mesh mesh1, final HE_Mesh mesh2)
Static Public Attributes
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Private Member Functions
HET_MeshOp ()
Static Private Member Functions
static WB_Vector findOptimalSolution (final HE_Vertex v, final WB_Vector normal, final WB_Vector t1, final WB_Vector t2)
static double signedVolume (final HE_Face f, final WB_Coord center)
Static Private Attributes
static WB_GeometryFactory gf = new WB_GeometryFactory()
Constructor & Destructor Documentation
wblut.hemesh.HET_MeshOp.HET_MeshOp () private
Member Function Documentation
static void wblut.hemesh.HET_MeshOp.assignFaceToLoop (final HE_Mesh mesh, final HE_Face face, final HE_Halfedge halfedge) static
Assign face to halfedge loop.
Parameters
mesh
face face
halfedge halfedge loop
References wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.hemesh.HE_Mesh.setFace().
static WB_Classification wblut.hemesh.HET_MeshOp.classifyEdgeToPlane3D (final HE_Halfedge edge, final WB_Plane P) static
References wblut.geom.WB_Classification.BACK, wblut.geom.WB_GeometryOp3D.classifyPointToPlane3D(), wblut.geom.WB_Classification.CROSSING, wblut.geom.WB_Classification.FRONT, wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getStartVertex(), and wblut.geom.WB_Classification.ON.
static WB_Classification wblut.hemesh.HET_MeshOp.classifyFaceToPlane3D (final HE_Face f, final WB_Plane P) static
References wblut.geom.WB_Classification.BACK, wblut.geom.WB_GeometryOp3D.classifyPointToPlane3D(), wblut.geom.WB_Classification.CROSSING, wblut.geom.WB_Classification.FRONT, wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), and wblut.geom.WB_Classification.ON.
static WB_Classification wblut.hemesh.HET_MeshOp.classifyVertexToPlane3D (final HE_Vertex v, final WB_Plane P) static
References wblut.geom.WB_GeometryOp3D.classifyPointToPlane3D().
static HE_Mesh wblut.hemesh.HET_MeshOp.cleanUnusedElementsByFace (final HE_Mesh mesh) static
Clean all mesh elements not used by any faces. Will leave boundary halfedges uncapped!
Parameters
mesh
Returns
self
References wblut.hemesh.HE_RAS< E extends HE_Element >.add(), wblut.hemesh.HE_Mesh.clearPair(), wblut.hemesh.HE_RAS< E extends HE_Element >.contains(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Mesh.getVertices(), wblut.hemesh.HE_RAS< E extends HE_Element >.getWithIndex(), wblut.hemesh.HE_Mesh.heItr(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_Mesh.removeHalfedges(), wblut.hemesh.HE_Mesh.removeVertices(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatusStr(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatusStr(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatusStr(), and wblut.hemesh.HE_RAS< E extends HE_Element >.size().
static boolean wblut.hemesh.HET_MeshOp.collapseEdge (final HE_Mesh mesh, final HE_Halfedge e) static
Collapse edge. End vertices are averaged. Degenerate faces are removed. This function can result in non-manifold meshes.
Parameters
mesh
e edge to collapse
Returns
true, if successful
References wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HET_Fixer.deleteTwoEdgeFace(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedgeStar(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.isEdge(), wblut.geom.WB_Point.mulSelf(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setVertex().
static boolean wblut.hemesh.HET_MeshOp.collapseEdgeBoundaryPreserving (final HE_Mesh mesh, final HE_Halfedge e, final boolean strict) static
Collapse edge to its midpoint or to point on boundary
Parameters
mesh
e
strict if true then an edge with two vertices on the boundary is always preserved
Returns
References wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HET_Fixer.deleteTwoEdgeFace(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedgeStar(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Vertex.isBoundary(), wblut.hemesh.HE_Halfedge.isEdge(), wblut.hemesh.HE_Halfedge.isInnerBoundary(), wblut.geom.WB_Point.mulSelf(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_Vertex.set(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setVertex().
static boolean wblut.hemesh.HET_MeshOp.collapseHalfedge (final HE_Mesh mesh, final HE_Halfedge he) static
References wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HET_Fixer.deleteTwoEdgeFace(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedgeStar(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setVertex().
static boolean wblut.hemesh.HET_MeshOp.collapseHalfedgeBoundaryPreserving (final HE_Mesh mesh, final HE_Halfedge he) static
Collapse halfedge if its vertex doesn't belong to the boundary
Parameters
mesh
he he
Returns
true, if successful
References wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HET_Fixer.deleteTwoEdgeFace(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedgeStar(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Vertex.isBoundary(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setVertex().
static HE_Face wblut.hemesh.HET_MeshOp.createFaceFromHalfedgeLoop (final HE_Mesh mesh, final HE_Halfedge he) static
Parameters
mesh
he
Returns
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Mesh.setFace(), and wblut.hemesh.HE_Mesh.setHalfedge().
static List<HE_Face> wblut.hemesh.HET_MeshOp.createFaceFromHalfedgeLoop (final HE_Mesh mesh, final List< HE_Halfedge > hes) static
Parameters
mesh
hes
Returns
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Mesh.contains(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), and wblut.hemesh.HE_MeshElement.setVisited().
static void wblut.hemesh.HET_MeshOp.divideEdge (final HE_Mesh mesh, final HE_Halfedge origE, final int n) static
Divide edge.
Parameters
mesh
origE edge to divide
n number of parts
References wblut.hemesh.HET_MeshOp.splitEdge().
static void wblut.hemesh.HET_MeshOp.divideEdge (final HE_Mesh mesh, final long key, final int n) static
Parameters
mesh
key
n
References wblut.hemesh.HET_MeshOp.divideEdge(), and wblut.hemesh.HE_Mesh.getHalfedgeWithKey().
static void wblut.hemesh.HET_MeshOp.expandVertexToEdge (final HE_Mesh mesh, final HE_Vertex v, final HE_Face f1, final HE_Face f2, final WB_Coord vn) static
Expand vertex to new edge.
Parameters
mesh
v vertex to expand
f1 first face
f2 second face
vn position of new vertex
References wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), and wblut.hemesh.HE_Mesh.setVertex().
static WB_Vector wblut.hemesh.HET_MeshOp.findOptimalSolution (final HE_Vertex v, final WB_Vector normal, final WB_Vector t1, final WB_Vector t2) static private
Parameters
v
normal
t1
t2
Returns
References wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.geom.WB_Vector.getLength(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.math.WB_M33.inverse(), wblut.math.WB_M33.mulToPoint(), wblut.geom.WB_MutableCoordinate.setX(), wblut.geom.WB_MutableCoordinate.setY(), wblut.math.WB_Epsilon.SQEPSILON, wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
static boolean wblut.hemesh.HET_MeshOp.flipEdge (final HE_Mesh mesh, final HE_Halfedge he) static
Parameters
mesh
he
Returns
References wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_GeometryOp3D.getArea(), wblut.hemesh.HE_Halfedge.getEdgeDihedralAngle(), wblut.hemesh.HE_Halfedge.getEdgeNormal(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Halfedge.getHalfedgeCenter(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_GeometryOp3D.projectOnPlane(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setVertex().
static boolean wblut.hemesh.HET_MeshOp.flipEdgeConditional (final HE_Mesh mesh, final HE_Halfedge he) static
References wblut.geom.WB_GeometryOp3D.getArea(), wblut.hemesh.HE_Halfedge.getEdgeNormal(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Halfedge.getHalfedgeCenter(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.getSqDistance(), wblut.hemesh.HE_Halfedge.getSqLength(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_GeometryOp3D.projectOnPlane(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setVertex().
static HE_Mesh wblut.hemesh.HET_MeshOp.flipFaces (final HE_Mesh mesh) static
Reverse all faces. Flips normals.
Parameters
mesh
Returns
References wblut.hemesh.HE_Mesh.modify().
static void wblut.hemesh.HET_MeshOp.flipFaces (final HE_Mesh mesh, final HE_RAS< HE_Face > faces) static
Parameters
mesh
faces
References wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_FaceHalfedgeInnerCirculator.hasNext(), wblut.hemesh.HE_FaceHalfedgeInnerCirculator.next(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setVertex().
static boolean wblut.hemesh.HET_MeshOp.flipPlanarEdgeConditional (final HE_Mesh mesh, final HE_Halfedge he, final double cosa) static
References wblut.geom.WB_GeometryOp3D.getArea(), wblut.hemesh.HE_Halfedge.getEdgeCosDihedralAngle(), wblut.hemesh.HE_Halfedge.getEdgeNormal(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Halfedge.getHalfedgeCenter(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.getSqDistance(), wblut.hemesh.HE_Halfedge.getSqLength(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_GeometryOp3D.projectOnPlane(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), and wblut.hemesh.HE_Mesh.setVertex().
static boolean wblut.hemesh.HET_MeshOp.flipPlanarEdgeConditional (final HE_Mesh mesh, final HE_Halfedge he) static
References wblut.math.WB_Epsilon.EPSILONANGLE, and wblut.hemesh.HET_MeshOp.flipPlanarEdgeConditional().
static double wblut.hemesh.HET_MeshOp.getAngleDefect (final HE_Vertex v) static
Computes the angle defect at a vertex (= 2PI minus the sum of incident angles at an interior vertex or PI minus the sum of incident angles at a boundary vertex).
Returns
References wblut.hemesh.HE_Halfedge.getAngle(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInVertex(), and wblut.hemesh.HE_Vertex.isBoundary().
static double wblut.hemesh.HET_MeshOp.getAngleDefect (final HE_Mesh mesh) static
References wblut.hemesh.HE_Vertex.getAngleDefect(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_VertexIterator.next(), and wblut.hemesh.HE_Mesh.vItr().
static double wblut.hemesh.HET_MeshOp.getBarycentricDualVertexArea (final HE_Vertex v) static
Get the barycentric dual area. Triangles only.
Returns
References wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceArea(), wblut.hemesh.HE_Vertex.getHalfedge(), and wblut.hemesh.HE_Halfedge.getNextInVertex().
static double wblut.hemesh.HET_MeshOp.getCircumcentricDualVertexArea (final HE_Vertex v) static
Get the circumcentric dual area. Triangles only.
Returns
References wblut.hemesh.HE_Halfedge.getCotan(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPrevInFace(), and wblut.hemesh.HE_Halfedge.getSqLength().
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getClosestIntersection (final WB_AABBTree tree, final WB_Ray ray) static
Parameters
tree
ray
Returns
References wblut.hemesh.HET_MeshOp.getIntersection(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.geom.WB_Ray.getOrigin(), wblut.geom.WB_Vector.getSqDistance(), and wblut.hemesh.HE_FaceIntersection.point.
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getClosestIntersection (final WB_AABBTree tree, final WB_Line line) static
Parameters
tree
line
Returns
References wblut.hemesh.HET_MeshOp.getIntersection(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Vector.getSqDistance(), and wblut.hemesh.HE_FaceIntersection.point.
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getClosestIntersection (final WB_AABBTree tree, final WB_Segment segment) static
Parameters
tree
segment
Returns
References wblut.hemesh.HET_MeshOp.getIntersection(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Vector.getSqDistance(), and wblut.hemesh.HE_FaceIntersection.point.
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getClosestIntersection (final HE_Mesh mesh, final WB_Ray ray) static
Parameters
mesh
ray
Returns
References wblut.hemesh.HET_MeshOp.getClosestIntersection().
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getClosestIntersection (final HE_Mesh mesh, final WB_Line line) static
Parameters
mesh
line
Returns
References wblut.hemesh.HET_MeshOp.getClosestIntersection().
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getClosestIntersection (final HE_Mesh mesh, final WB_Segment segment) static
Parameters
mesh
segment
Returns
References wblut.hemesh.HET_MeshOp.getClosestIntersection().
static WB_Coord [] wblut.hemesh.HET_MeshOp.getClosestPointToTriangleFace (final WB_Coord p, final HE_Face T) static
Get the closest point to triangle face and its normal.
Parameters
p point
T
Returns
WB_Coord[2], first WB_Coord is the closest point, second WB_Coord is the normal
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_Vector.dot(), wblut.hemesh.HE_Halfedge.getEdge(), wblut.hemesh.HE_Halfedge.getEdgeNormal(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.geom.WB_Vector.mulSelf(), and wblut.geom.WB_Point.subToVector3D().
static WB_Coord [] wblut.hemesh.HET_MeshOp.getClosestPointToTriangleMesh (final WB_Coord p, final HE_Mesh mesh) static
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Mesh.get(), wblut.hemesh.HET_MeshOp.getClosestPointToTriangleFace(), wblut.geom.WB_Vector.getSqDistance3D(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), and wblut.hemesh.HE_Mesh.triangulate().
static double wblut.hemesh.HET_MeshOp.getCotan (final HE_Halfedge he) static
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.hemesh.HE_Halfedge.getHalfedgeVector(), wblut.geom.WB_Vector.getLength(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPrevInFace(), and wblut.hemesh.HE_Halfedge.isOuterBoundary().
static WB_CoordinateSystem3D wblut.hemesh.HET_MeshOp.getCurvatureDirections (final HE_Vertex v) static
Returns
References wblut.geom.WB_GeometryFactory3D.createCSFromOXYZ(), wblut.math.WB_Epsilon.EPSILON, wblut.hemesh.HET_MeshOp.findOptimalSolution(), wblut.hemesh.HET_MeshOp.getVertexCS(), wblut.geom.WB_CoordinateSystem3D.getX(), wblut.geom.WB_CoordinateSystem3D.getY(), wblut.geom.WB_CoordinateSystem3D.getZ(), wblut.geom.WB_Vector.mulAddMul(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
static DoubleMatrix2D wblut.hemesh.HET_MeshOp.getExteriorDerivative0Form (final HE_Mesh mesh) static
Builds a sparse matrix encoding the exterior derivative on 0-forms.
Parameters
mesh
Returns
References wblut.hemesh.HE_Mesh.eItr(), wblut.hemesh.HE_Mesh.getIndex(), wblut.hemesh.HE_Mesh.getNumberOfEdges(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Halfedge.getPair(), and wblut.hemesh.HE_Halfedge.getVertex().
static DoubleMatrix2D wblut.hemesh.HET_MeshOp.getExteriorDerivative1Form (final HE_Mesh mesh) static
Builds a sparse matrix encoding the exterior derivative on 1-forms.
Parameters
mesh
Returns
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Halfedge.getEdge(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Mesh.getIndex(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Mesh.getNumberOfEdges(), and wblut.hemesh.HE_Mesh.getNumberOfFaces().
static double wblut.hemesh.HET_MeshOp.getFaceArea (final HE_Face face) static
References wblut.math.WB_Math.fastAbs(), wblut.hemesh.HET_MeshOp.getFaceNormal(), wblut.hemesh.HE_Face.getHalfedge(), wblut.geom.WB_Vector.getLength3D(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_Coord.xd(), wblut.hemesh.HE_Vertex.xd(), wblut.geom.WB_Coord.yd(), wblut.hemesh.HE_Vertex.yd(), wblut.geom.WB_Coord.zd(), and wblut.hemesh.HE_Vertex.zd().
static WB_Coord wblut.hemesh.HET_MeshOp.getFaceNormal (final HE_Face face) static
References wblut.geom.WB_Vector.addSelf(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_Vector.normalizeSelf(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), and wblut.hemesh.HE_Vertex.zd().
static WB_Coord wblut.hemesh.HET_MeshOp.getFaceNormalNotNormalized (final HE_Face face) static
References wblut.geom.WB_Vector.addSelf(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Vertex.xd(), wblut.hemesh.HE_Vertex.yd(), and wblut.hemesh.HE_Vertex.zd().
static WB_Classification wblut.hemesh.HET_MeshOp.getFaceType (final HE_Face face) static
Returns
References wblut.geom.WB_Classification.CONCAVE, wblut.geom.WB_Classification.CONVEX, wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getHalfedgeType(), wblut.hemesh.HE_Halfedge.getNextInFace(), and wblut.geom.WB_Classification.UNKNOWN.
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getFurthestIntersection (final WB_AABBTree tree, final WB_Ray ray) static
Parameters
tree
ray
Returns
References wblut.hemesh.HET_MeshOp.getIntersection(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.geom.WB_Ray.getOrigin(), wblut.geom.WB_Vector.getSqDistance(), and wblut.hemesh.HE_FaceIntersection.point.
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getFurthestIntersection (final WB_AABBTree tree, final WB_Line line) static
Parameters
tree
line
Returns
References wblut.hemesh.HET_MeshOp.getIntersection(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Vector.getSqDistance(), and wblut.hemesh.HE_FaceIntersection.point.
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getFurthestIntersection (final WB_AABBTree tree, final WB_Segment segment) static
Parameters
tree
segment
Returns
References wblut.hemesh.HET_MeshOp.getIntersection(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Vector.getSqDistance(), and wblut.hemesh.HE_FaceIntersection.point.
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getFurthestIntersection (final HE_Mesh mesh, final WB_Ray ray) static
Parameters
mesh
ray
Returns
References wblut.hemesh.HET_MeshOp.getFurthestIntersection().
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getFurthestIntersection (final HE_Mesh mesh, final WB_Line line) static
Parameters
mesh
line
Returns
References wblut.hemesh.HET_MeshOp.getFurthestIntersection().
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getFurthestIntersection (final HE_Mesh mesh, final WB_Segment segment) static
Parameters
mesh
segment
Returns
References wblut.hemesh.HET_MeshOp.getFurthestIntersection().
static double wblut.hemesh.HET_MeshOp.getGaussCurvature (final HE_Vertex vertex) static
Returns the discrete Gaussian curvature. These discrete operators are described in "Discrete Differential-Geometry Operators for Triangulated 2-Manifolds", Mark Meyer, Mathieu Desbrun, Peter Schr?der, and Alan H. Barr. http://www.cs.caltech.edu/~mmeyer/Publications/diffGeomOps.pdf http://www.cs.caltech.edu/~mmeyer/Publications/diffGeomOps.pdf Note: on a sphere, the Gaussian curvature is very accurate, but not the mean curvature. Guoliang Xu suggests improvements in his papers http://lsec.cc.ac.cn/~xuguo/xuguo3.htm
Returns
References wblut.geom.WB_Vector.addMulSelf(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.geom.WB_Vector.getLength(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Vertex.isBoundary(), wblut.geom.WB_Vector.mulAddMul(), and wblut.geom.WB_Vector.mulSelf().
static double wblut.hemesh.HET_MeshOp.getGaussianCurvature (final HE_Vertex vertex, final WB_Vector meanCurvatureVector) static
Returns the discrete Gaussian curvature and the mean normal. These discrete operators are described in "Discrete Differential-Geometry Operators for Triangulated 2-Manifolds", Mark Meyer, Mathieu Desbrun, Peter Schr???der, and Alan H. Barr. http://www.cs.caltech.edu/~mmeyer/Publications/diffGeomOps.pdf http://www.cs.caltech.edu/~mmeyer/Publications/diffGeomOps.pdf Note: on a sphere, the Gaussian curvature is very accurate, but not the mean curvature. Guoliang Xu suggests improvements in his papers http://lsec.cc.ac.cn/~xuguo/xuguo3.htm
Parameters
vertex
meanCurvatureVector
Returns
References wblut.geom.WB_Vector.addMulSelf(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.geom.WB_Vector.getLength(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_Vector.mulAddMul(), wblut.geom.WB_Vector.mulSelf(), and wblut.geom.WB_MutableCoordinate.set().
static DoubleMatrix2D wblut.hemesh.HET_MeshOp.getHodgeStar0Form (final HE_Mesh mesh) static
Builds a sparse diagonal matrix encoding the Hodge operator on 0-forms. By convention, the area of a vertex is 1.
Parameters
mesh
Returns
References wblut.hemesh.HET_MeshOp.getBarycentricDualVertexArea(), wblut.hemesh.HE_Mesh.getIndex(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), and wblut.hemesh.HE_Mesh.vItr().
static DoubleMatrix2D wblut.hemesh.HET_MeshOp.getHodgeStar1Form (final HE_Mesh mesh) static
Builds a sparse diagonal matrix encoding the Hodge operator on 1-forms.
Parameters
mesh
Returns
References wblut.hemesh.HE_Mesh.eItr(), wblut.hemesh.HET_MeshOp.getCotan(), wblut.hemesh.HE_Mesh.getIndex(), wblut.hemesh.HE_Mesh.getNumberOfEdges(), and wblut.hemesh.HE_Halfedge.getPair().
static DoubleMatrix2D wblut.hemesh.HET_MeshOp.getHodgeStar2Form (final HE_Mesh mesh) static
Builds a sparse diagonal matrix encoding the Hodge operator on 2-forms. By convention, the area of a vertex is 1.
Parameters
mesh
Returns
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HET_MeshOp.getFaceArea(), wblut.hemesh.HE_Mesh.getIndex(), and wblut.hemesh.HE_Mesh.getNumberOfFaces().
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getIntersection (final HE_Face face, final WB_Line line) static
Parameters
face
line
Returns
References wblut.geom.WB_GeometryOp3D.getDistanceToClosestPoint3D(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.hemesh.HE_Face.getPlane(), wblut.geom.WB_IntersectionResult.intersection, wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_IntersectionResult.object, wblut.hemesh.HE_FaceIntersection.point, and wblut.hemesh.HE_Face.toPolygon().
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getIntersection (final HE_Face face, final WB_Ray ray) static
Parameters
face
ray
Returns
References wblut.geom.WB_GeometryOp3D.getDistanceToClosestPoint3D(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.hemesh.HE_Face.getPlane(), wblut.geom.WB_IntersectionResult.intersection, wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_IntersectionResult.object, wblut.hemesh.HE_FaceIntersection.point, and wblut.hemesh.HE_Face.toPolygon().
static HE_FaceIntersection wblut.hemesh.HET_MeshOp.getIntersection (final HE_Face face, final WB_Segment segment) static
Parameters
face
segment
Returns
References wblut.geom.WB_GeometryOp3D.getDistanceToClosestPoint3D(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.hemesh.HE_Face.getPlane(), wblut.geom.WB_IntersectionResult.intersection, wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_IntersectionResult.object, wblut.hemesh.HE_FaceIntersection.point, and wblut.hemesh.HE_Face.toPolygon().
static double wblut.hemesh.HET_MeshOp.getIntersection (final HE_Halfedge e, final WB_Plane P) static
Parameters
e
P
Returns
References wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.hemesh.HE_Halfedge.getStartVertex(), wblut.geom.WB_IntersectionResult.intersection, and wblut.geom.WB_IntersectionResult.t1.
static List<HE_FaceIntersection> wblut.hemesh.HET_MeshOp.getIntersection (final WB_AABBTree tree, final WB_Ray ray) static
Parameters
tree
ray
Returns
References wblut.hemesh.HET_MeshOp.getIntersection(), and wblut.geom.WB_GeometryOp3D.getIntersection3D().
static List<HE_FaceIntersection> wblut.hemesh.HET_MeshOp.getIntersection (final WB_AABBTree tree, final WB_Segment segment) static
Parameters
tree
segment
Returns
References wblut.hemesh.HET_MeshOp.getIntersection(), and wblut.geom.WB_GeometryOp3D.getIntersection3D().
static List<HE_FaceIntersection> wblut.hemesh.HET_MeshOp.getIntersection (final WB_AABBTree tree, final WB_Line line) static
Parameters
tree
line
Returns
References wblut.hemesh.HET_MeshOp.getIntersection(), and wblut.geom.WB_GeometryOp3D.getIntersection3D().
static List<WB_Segment> wblut.hemesh.HET_MeshOp.getIntersection (final WB_AABBTree tree, final WB_Plane P) static
Parameters
tree
P
Returns
References wblut.geom.WB_GeometryOp3D.getIntersection3D().
static List<HE_FaceIntersection> wblut.hemesh.HET_MeshOp.getIntersection (final HE_Mesh mesh, final WB_Ray ray) static
Parameters
mesh
ray
Returns
References wblut.hemesh.HET_MeshOp.getIntersection().
static List<HE_FaceIntersection> wblut.hemesh.HET_MeshOp.getIntersection (final HE_Mesh mesh, final WB_Segment segment) static
Parameters
mesh
segment
Returns
References wblut.hemesh.HET_MeshOp.getIntersection().
static List<HE_FaceIntersection> wblut.hemesh.HET_MeshOp.getIntersection (final HE_Mesh mesh, final WB_Line line) static
Parameters
mesh
line
Returns
References wblut.hemesh.HET_MeshOp.getIntersection().
static List<WB_Segment> wblut.hemesh.HET_MeshOp.getIntersection (final HE_Mesh mesh, final WB_Plane P) static
Parameters
mesh
P
Returns
References wblut.hemesh.HET_MeshOp.getIntersection().
static List<HET_IntersectionResult> wblut.hemesh.HET_MeshOp.getIntersection (final HE_Mesh mesh1, final HE_Mesh mesh2) static
References wblut.hemesh.HE_Selection.add(), wblut.geom.WB_GeometryOp3D.getIntersection3D(), wblut.geom.WB_IntersectionResult.intersection, wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_IntersectionResult.object, wblut.hemesh.HE_Mesh.resetFaceInternalLabels(), and wblut.hemesh.HE_Mesh.triangulate().
static DoubleMatrix2D wblut.hemesh.HET_MeshOp.getLaplaceMatrix (final HE_Mesh mesh) static
Builds a sparse laplace matrix. The laplace operator is negative semidefinite; instead we build a positive definite matrix by multiplying the entries of the laplace matrix by -1 and shifting the diagonal elements by a small constant (e.g. 1e-8).
Parameters
mesh
Returns
References wblut.hemesh.HET_MeshOp.getCotan(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Mesh.getIndex(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Halfedge.getPair(), and wblut.hemesh.HE_Mesh.vItr().
static double [] wblut.hemesh.HET_MeshOp.getMassArray (final HE_Mesh mesh) static
References wblut.hemesh.HET_MeshOp.getBarycentricDualVertexArea(), wblut.hemesh.HE_Mesh.getIndex(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.hemesh.HE_VertexIterator.next(), and wblut.hemesh.HE_Mesh.vItr().
static DoubleMatrix2D wblut.hemesh.HET_MeshOp.getMassMatrix (final HE_Mesh mesh) static
Builds a sparse diagonal mass matrix containing the barycentric dual area of each vertex of a mesh. unique index.
Parameters
mesh
Returns
References wblut.hemesh.HET_MeshOp.getBarycentricDualVertexArea(), wblut.hemesh.HE_Mesh.getIndex(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), and wblut.hemesh.HE_Mesh.vItr().
static List<HE_Face> wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_Plane P) static
Parameters
tree
P
Returns
References wblut.geom.WB_GeometryOp3D.getIntersection3D().
static List<HE_Face> wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_Triangle T) static
Parameters
tree
T
Returns
References wblut.geom.WB_GeometryOp3D.getIntersection3D().
static List<HE_Face> wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_AABB AABB) static
References wblut.geom.WB_GeometryOp3D.getIntersection3D().
static List<HE_Face> wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_Coord p) static
References wblut.geom.WB_GeometryOp3D.getIntersection3D().
static List<HE_Face> wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_Ray R) static
Parameters
tree
R
Returns
References wblut.geom.WB_GeometryOp3D.getIntersection3D().
static List<HE_Face> wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_Line L) static
Parameters
tree
L
Returns
References wblut.geom.WB_GeometryOp3D.getIntersection3D().
static List<HE_Face> wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces (final WB_AABBTree tree, final WB_Segment segment) static
Parameters
tree
segment
Returns
References wblut.geom.WB_GeometryOp3D.getIntersection3D().
static List<HE_Face> wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces (final HE_Mesh mesh, final WB_Plane P) static
Parameters
mesh
P
Returns
References wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces().
static List<HE_Face> wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces (final HE_Mesh mesh, final WB_Ray R) static
Parameters
mesh
R
Returns
References wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces().
static List<HE_Face> wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces (final HE_Mesh mesh, final WB_Line L) static
Parameters
mesh
L
Returns
References wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces().
static List<HE_Face> wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces (final HE_Mesh mesh, final WB_Segment segment) static
Parameters
mesh
segment
Returns
References wblut.hemesh.HET_MeshOp.getPotentialIntersectedFaces().
static double [] wblut.hemesh.HET_MeshOp.getPrincipalCurvatures (final HE_Vertex v) static
Computes the (pointwise) minimum and maximum principal curvature values at a vertex.
Parameters
v
Returns
References wblut.hemesh.HET_MeshOp.getAngleDefect(), wblut.hemesh.HET_MeshOp.getCircumcentricDualVertexArea(), and wblut.hemesh.HET_MeshOp.getScalarMeanCurvature().
static double wblut.hemesh.HET_MeshOp.getScalarGaussCurvature (final HE_Vertex v) static
Computes the (integrated) scalar gauss curvature at a vertex.
Parameters
v
Returns
References wblut.hemesh.HET_MeshOp.getAngleDefect().
static double wblut.hemesh.HET_MeshOp.getScalarMeanCurvature (final HE_Vertex v) static
Computes the (integrated) scalar mean curvature at a vertex.
Parameters
v
Returns
References wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getHalfedgeDihedralAngle(), wblut.hemesh.HE_Halfedge.getLength(), and wblut.hemesh.HE_Halfedge.getNextInVertex().
static double wblut.hemesh.HET_MeshOp.getUmbrellaAngle (final HE_Vertex v) static
Returns
References wblut.hemesh.HE_Halfedge.getAngle(), wblut.hemesh.HE_Vertex.getHalfedge(), and wblut.hemesh.HE_Halfedge.getNextInVertex().
static double wblut.hemesh.HET_MeshOp.getVertexArea (final HE_Vertex v) static
References wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceArea(), wblut.hemesh.HE_Vertex.getHalfedge(), and wblut.hemesh.HE_Halfedge.getNextInVertex().
static WB_CoordinateSystem3D wblut.hemesh.HET_MeshOp.getVertexCS (final HE_Vertex v) static
Returns
References wblut.geom.WB_GeometryFactory3D.createCSFromOXYZ(), wblut.geom.WB_Vector.cross(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Vector.getLength(), wblut.hemesh.HET_MeshOp.getVertexNormal(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_MutableCoordinate.setX(), wblut.geom.WB_MutableCoordinate.setY(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
static WB_Coord wblut.hemesh.HET_MeshOp.getVertexNormal (final HE_Vertex v) static
Returns
References wblut.hemesh.HE_Vertex.getHalfedge(), and wblut.hemesh.HET_MeshOp.getVertexNormalAngle().
static WB_Coord wblut.hemesh.HET_MeshOp.getVertexNormalAngle (final HE_Vertex v) static
Computes the normal at a vertex using the "tip angle weights" method.
Returns
References wblut.geom.WB_Vector.addMulSelf(), wblut.hemesh.HE_Halfedge.getAngle(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInVertex(), and wblut.geom.WB_Vector.normalizeSelf().
static WB_Coord wblut.hemesh.HET_MeshOp.getVertexNormalArea (final HE_Vertex v) static
Computes the normal at a vertex using the "face area weights" method.
Returns
References wblut.geom.WB_Vector.addMulSelf(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceArea(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInVertex(), and wblut.geom.WB_Vector.normalizeSelf().
static WB_Coord wblut.hemesh.HET_MeshOp.getVertexNormalAverage (final HE_Vertex v) static
Computes the normal at a vertex using the "equally weighted" method.
Returns
References wblut.geom.WB_Vector.addSelf(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInVertex(), and wblut.geom.WB_Vector.normalizeSelf().
static WB_Coord wblut.hemesh.HET_MeshOp.getVertexNormalGaussCurvature (final HE_Vertex v) static
Computes the normal at a vertex using the "gauss curvature" method.
Returns
References wblut.geom.WB_Vector.addMulSelf(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getHalfedgeDihedralAngle(), wblut.hemesh.HE_Halfedge.getHalfedgeVector(), wblut.hemesh.HE_Halfedge.getLength(), wblut.hemesh.HE_Halfedge.getNextInVertex(), and wblut.geom.WB_Vector.normalizeSelf().
static WB_Coord wblut.hemesh.HET_MeshOp.getVertexNormalMeanCurvature (final HE_Vertex v) static
Computes the normal at a vertex using the "mean curvature" method. Triangles only.
Returns
References wblut.geom.WB_Vector.addMulSelf(), wblut.hemesh.HE_Halfedge.getCotan(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getHalfedgeVector(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPair(), and wblut.geom.WB_Vector.normalizeSelf().
static WB_Coord wblut.hemesh.HET_MeshOp.getVertexNormalSphereInscribed (final HE_Vertex v) static
Computes the normal at a vertex using the "inscribed sphere" method. Triangles only.
Returns
References wblut.geom.WB_Vector.addMulSelf(), wblut.geom.WB_Vector.cross(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getHalfedgeVector(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.geom.WB_Vector.getSqLength(), and wblut.geom.WB_Vector.normalizeSelf().
static WB_Classification wblut.hemesh.HET_MeshOp.getVertexType (final HE_Vertex vertex) static
References wblut.geom.WB_Classification.CONCAVE, wblut.geom.WB_Classification.CONVEX, wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Classification.FLAT, wblut.geom.WB_Classification.FLATCONCAVE, wblut.geom.WB_Classification.FLATCONVEX, wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Face.getFaceNormal(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getNextInVertex(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.geom.WB_Classification.SADDLE, wblut.geom.WB_Point.subSelf(), and wblut.geom.WB_Classification.UNKNOWN.
static double wblut.hemesh.HET_MeshOp.getVolume (final HE_Mesh mesh) static
References wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Mesh.getCenter(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceIterator.next(), and wblut.hemesh.HET_MeshOp.signedVolume().
static void wblut.hemesh.HET_MeshOp.improveTriangulation (final HE_Mesh mesh, final HE_Selection triangles) static
References wblut.math.WB_Epsilon.EPSILONANGLE.
static void wblut.hemesh.HET_MeshOp.improveTriangulation (final HE_Mesh mesh) static
References wblut.math.WB_Epsilon.EPSILONANGLE, wblut.hemesh.HET_MeshOp.improveTriangulation(), and wblut.hemesh.HE_Mesh.selectAllFaces().
static void wblut.hemesh.HET_MeshOp.improveTriangulation (final HE_Mesh mesh, final double cosa) static
References wblut.hemesh.HET_MeshOp.improveTriangulation(), and wblut.hemesh.HE_Mesh.selectAllFaces().
static void wblut.hemesh.HET_MeshOp.improveTriangulation (final HE_Mesh mesh, final HE_Selection triangles, final double cosa) static
References wblut.hemesh.HE_Selection.addFaces(), wblut.hemesh.HE_Selection.clearEdges(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HET_MeshOp.flipPlanarEdgeConditional(), wblut.hemesh.HE_Selection.getFaces(), and wblut.hemesh.HE_Selection.getInnerEdges().
static boolean wblut.hemesh.HET_MeshOp.isInside (final HE_Mesh mesh, final WB_Coord p) static
static boolean wblut.hemesh.HET_MeshOp.isInside (final WB_AABBTree tree, final WB_Coord p) static
References wblut.hemesh.HET_MeshOp.getIntersection(), and wblut.geom.WB_GeometryOp3D.getIntersection3D().
static void wblut.hemesh.HET_MeshOp.liftEdges (final HE_Selection edges, final double d) static
References wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Selection.clearFaces(), wblut.hemesh.HE_Selection.clearVertices(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Selection.get(), wblut.hemesh.HE_Selection.getNumberOfVertices(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Vertex.getVertexNormal(), wblut.hemesh.HE_VertexIterator.hasNext(), wblut.geom.WB_Vector.mul(), wblut.hemesh.HE_VertexIterator.next(), and wblut.hemesh.HE_Selection.vItr().
static boolean wblut.hemesh.HET_MeshOp.pointIsInFace (final WB_Coord p, final HE_Face f) static
Check if point lies inside or on edge of face.
Parameters
p point
f the f
Returns
true/false
References wblut.geom.WB_GeometryOp3D.getDistanceToClosestPoint3D(), wblut.math.WB_Epsilon.isZero(), and wblut.hemesh.HE_Face.toPolygon().
static boolean wblut.hemesh.HET_MeshOp.pointIsStrictlyInFace (final WB_Coord p, final HE_Face f) static
Check if point lies strictly inside face.
Parameters
p point
f the f
Returns
true/false
References wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.geom.WB_GeometryOp3D.getClosestPointOnPeriphery3D(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), wblut.math.WB_Epsilon.isZeroSq(), and wblut.hemesh.HE_Face.toPolygon().
static HE_RAS<HE_Face> wblut.hemesh.HET_MeshOp.selectAllFacesConnectedToUnpairedHalfedge (final HE_Mesh mesh, final HE_Halfedge unpairedHalfedge) static
Parameters
mesh
unpairedHalfedge
Returns
References wblut.hemesh.HE_RAS< E extends HE_Element >.add(), wblut.hemesh.HE_MeshElement.clearVisited(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_RAS< E extends HE_Element >.getWithIndex(), wblut.hemesh.HE_FaceIterator.hasNext(), wblut.hemesh.HE_FaceHalfedgeInnerCirculator.hasNext(), wblut.hemesh.HE_MeshElement.isVisited(), wblut.hemesh.HE_FaceIterator.next(), wblut.hemesh.HE_FaceHalfedgeInnerCirculator.next(), wblut.hemesh.HE_RAS< E extends HE_Element >.remove(), wblut.hemesh.HE_MeshElement.setVisited(), and wblut.hemesh.HE_RAS< E extends HE_Element >.size().
static double wblut.hemesh.HET_MeshOp.signedVolume (final HE_Face f, final WB_Coord center) static private
References wblut.hemesh.HE_Face.getFaceVertices(), wblut.hemesh.HE_Face.getTriangles(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
static HE_Selection wblut.hemesh.HET_MeshOp.splitEdge (final HE_Mesh mesh, final HE_Halfedge edge) static
Split edge in half.
Parameters
mesh
edge edge to split.
Returns
selection of new vertex and new edge
References wblut.geom.WB_GeometryFactory3D.createMidpoint(), wblut.hemesh.HE_Halfedge.getEndVertex(), and wblut.hemesh.HE_Halfedge.getVertex().
static HE_Selection wblut.hemesh.HET_MeshOp.splitEdge (final HE_Mesh mesh, final HE_Halfedge edge, final double f) static
Split edge in two parts.
Parameters
mesh
edge edge to split
f fraction of first part (0..1)
Returns
selection of new vertex and new edge
References wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.isEdge(), and wblut.hemesh.HET_MeshOp.splitEdge().
static void wblut.hemesh.HET_MeshOp.splitEdge (final HE_Mesh mesh, final HE_Halfedge edge, final double x, final double y, final double z) static
Insert vertex in edge.
Parameters
mesh
edge edge to split
x x-coordinate of new vertex
y y-coordinate of new vertex
z z-coordinate of new vertex
References wblut.hemesh.HET_MeshOp.splitEdge().
static void wblut.hemesh.HET_MeshOp.splitEdge (final HE_Mesh mesh, final HE_Halfedge edge, final double[] f) static
Split edge in multiple parts.
Parameters
mesh
edge edge to split
f array of fractions (0..1)
References wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.hemesh.HE_Selection.eItr(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.isEdge(), wblut.hemesh.HE_EdgeIterator.next(), and wblut.hemesh.HET_MeshOp.splitEdge().
static void wblut.hemesh.HET_MeshOp.splitEdge (final HE_Mesh mesh, final HE_Halfedge edge, final float[] f) static
Split edge in multiple parts.
Parameters
mesh
edge edge to split
f array of fractions (0..1)
References wblut.geom.WB_GeometryFactory3D.createInterpolatedPoint(), wblut.hemesh.HE_Selection.eItr(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.isEdge(), wblut.hemesh.HE_EdgeIterator.next(), and wblut.hemesh.HET_MeshOp.splitEdge().
static HE_Selection wblut.hemesh.HET_MeshOp.splitEdge (final HE_Mesh mesh, final HE_Halfedge edge, final WB_Coord v) static
Insert vertex in edge.
Parameters
mesh
edge edge to split
v position of new vertex
Returns
selection of new vertex and new edge
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Selection.addEdge(), wblut.hemesh.HE_Halfedge.copyProperties(), wblut.geom.WB_Vector.getDistance(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Halfedge.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.hasUVW(), wblut.hemesh.HE_Halfedge.isEdge(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Halfedge.setUVW(), and wblut.hemesh.HE_Mesh.setVertex().
static HE_Selection wblut.hemesh.HET_MeshOp.splitEdge (final HE_Mesh mesh, final long key) static
Split edge in half.
Parameters
mesh
key key of edge to split.
Returns
selection of new vertex and new edge
References wblut.geom.WB_GeometryFactory3D.createMidpoint(), wblut.hemesh.HE_Halfedge.getEndVertex(), wblut.hemesh.HE_Mesh.getHalfedgeWithKey(), wblut.hemesh.HE_Halfedge.getVertex(), and wblut.hemesh.HET_MeshOp.splitEdge().
static HE_Selection wblut.hemesh.HET_MeshOp.splitEdge (final HE_Mesh mesh, final long key, final double f) static
Split edge in two parts.
Parameters
mesh
key key of edge to split
f fraction of first part (0..1)
Returns
selection of new vertex and new edge
References wblut.hemesh.HE_Mesh.getHalfedgeWithKey(), and wblut.hemesh.HET_MeshOp.splitEdge().
static void wblut.hemesh.HET_MeshOp.splitEdge (final HE_Mesh mesh, final long key, final double x, final double y, final double z) static
Insert vertex in edge.
Parameters
mesh
key key of edge to split
x x-coordinate of new vertex
y y-coordinate of new vertex
z z-coordinate of new vertex
References wblut.hemesh.HET_MeshOp.splitEdge().
static void wblut.hemesh.HET_MeshOp.splitEdge (final HE_Mesh mesh, final long key, final double[] f) static
Split edge in multiple parts.
Parameters
mesh
key key of edge to split
f array of fractions (0..1)
References wblut.hemesh.HE_Mesh.getHalfedgeWithKey(), and wblut.hemesh.HET_MeshOp.splitEdge().
static void wblut.hemesh.HET_MeshOp.splitEdge (final HE_Mesh mesh, final long key, final float[] f) static
Split edge in multiple parts.
Parameters
mesh
key key of edge to split
f array of fractions (0..1)
References wblut.hemesh.HE_Mesh.getHalfedgeWithKey(), and wblut.hemesh.HET_MeshOp.splitEdge().
static HE_Selection wblut.hemesh.HET_MeshOp.splitEdge (final HE_Mesh mesh, final Long key, final WB_Point v) static
Insert vertex in edge.
Parameters
mesh
key key of edge to split
v position of new vertex
Returns
selection of new vertex and new edge
References wblut.hemesh.HE_Mesh.getHalfedgeWithKey(), and wblut.hemesh.HET_MeshOp.splitEdge().
static HE_Selection wblut.hemesh.HET_MeshOp.splitEdges (final HE_Mesh mesh) static
Split all edges in half.
Parameters
mesh
Returns
selection of new vertices and new edges
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.getEdgesAsArray(), and wblut.hemesh.HET_MeshOp.splitEdge().
static HE_Selection wblut.hemesh.HET_MeshOp.splitEdges (final HE_Mesh mesh, final double offset) static
Split all edges in half, offset the center by a given distance along the edge normal.
Parameters
mesh
offset the offset
Returns
selection of new vertices and new edges
References wblut.hemesh.HE_Selection.add(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Mesh.getEdgesAsArray(), wblut.hemesh.HE_Mesh.getNumberOfEdges(), wblut.geom.WB_Point.mulSelf(), and wblut.hemesh.HET_MeshOp.splitEdge().
static HE_Selection wblut.hemesh.HET_MeshOp.splitEdges (final HE_Selection selection) static
Split edge in half.
Parameters
selection edges to split.
Returns
selection of new vertices and new edges
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Selection.addHalfedges(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.getEdgesAsArray(), wblut.hemesh.HE_Selection.heItr(), and wblut.hemesh.HET_MeshOp.splitEdge().
static HE_Selection wblut.hemesh.HET_MeshOp.splitEdges (final HE_Selection selection, final double offset) static
Split edge in half, offset the center by a given distance along the edge normal.
Parameters
selection edges to split.
offset the offset
Returns
selection of new vertices and new edges
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Selection.addHalfedges(), wblut.geom.WB_Point.addSelf(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Halfedge.getEdgeNormal(), wblut.hemesh.HE_Selection.getEdgesAsArray(), wblut.hemesh.HE_Halfedge.getHalfedgeCenter(), wblut.hemesh.HE_Selection.heItr(), wblut.geom.WB_Point.mulSelf(), and wblut.hemesh.HET_MeshOp.splitEdge().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFace (final HE_Mesh mesh, final HE_Face face, final HE_Vertex vi, final HE_Vertex vj) static
Divide face along two vertices.
Parameters
mesh
face face to divide
vi first vertex
vj second vertex
Returns
new face and edge
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Selection.addEdge(), wblut.hemesh.HET_MeshOp.assignFaceToLoop(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HET_Fixer.deleteTwoEdgeFace(), wblut.geom.WB_Vector.getDistance(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Vertex.getHalfedgeStar(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Vertex.getPosition(), wblut.hemesh.HE_Halfedge.getPrevInFace(), wblut.hemesh.HE_Halfedge.getUVW(), wblut.hemesh.HE_Halfedge.hasUVW(), wblut.hemesh.HE_Halfedge.isEdge(), wblut.math.WB_Epsilon.isZero(), wblut.hemesh.HE_Selection.remove(), wblut.hemesh.HE_Mesh.remove(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Halfedge.setUVW(), and wblut.hemesh.HE_Mesh.setVertex().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFace (final HE_Mesh mesh, final long fkey, final long vkeyi, final long vkeyj) static
Divide face along two vertices.
Parameters
mesh
fkey key of face
vkeyi key of first vertex
vkeyj key of second vertex
Returns
new face and edge
References wblut.hemesh.HE_Mesh.getFaceWithKey(), wblut.hemesh.HE_Mesh.getVertexWithKey(), and wblut.hemesh.HET_MeshOp.splitFace().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesCenter (final HE_Mesh mesh) static
Parameters
mesh
Returns
References wblut.hemesh.HE_Mesh.getSelection(), and wblut.hemesh.HE_Mesh.modify().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesCenter (final HE_Mesh mesh, final double d) static
Parameters
mesh
d
Returns
References wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Mesh.modify(), and wblut.hemesh.HEM_CenterSplit.setOffset().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesCenter (final HE_Mesh mesh, final double d, final double c) static
Parameters
mesh
d
c
Returns
References wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HEM_CenterSplit.setChamfer(), and wblut.hemesh.HEM_CenterSplit.setOffset().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesCenter (final HE_Selection faces) static
Parameters
faces
Returns
References wblut.hemesh.HE_Mesh.getSelection(), and wblut.hemesh.HE_Selection.modify().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesCenter (final HE_Selection faces, final double d) static
Parameters
faces
d
Returns
References wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Selection.modify(), and wblut.hemesh.HEM_CenterSplit.setOffset().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesCenter (final HE_Selection faces, final double d, final double c) static
Parameters
faces
d
c
Returns
References wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Selection.modify(), wblut.hemesh.HEM_CenterSplit.setChamfer(), and wblut.hemesh.HEM_CenterSplit.setOffset().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesCenterHole (final HE_Mesh mesh) static
Parameters
mesh
Returns
References wblut.hemesh.HEM_CenterSplitHole.getWallFaces(), and wblut.hemesh.HE_Mesh.modify().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesCenterHole (final HE_Mesh mesh, final double d) static
Parameters
mesh
d
Returns
References wblut.hemesh.HEM_CenterSplitHole.getWallFaces(), wblut.hemesh.HE_Mesh.modify(), and wblut.hemesh.HEM_CenterSplitHole.setOffset().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesCenterHole (final HE_Mesh mesh, final double d, final double c) static
Parameters
mesh
d
c
Returns
References wblut.hemesh.HEM_CenterSplitHole.getWallFaces(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HEM_CenterSplitHole.setChamfer(), and wblut.hemesh.HEM_CenterSplitHole.setOffset().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesCenterHole (final HE_Selection faces) static
Parameters
faces
Returns
References wblut.hemesh.HEM_CenterSplitHole.getWallFaces(), and wblut.hemesh.HE_Selection.modify().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesCenterHole (final HE_Selection faces, final double d) static
Parameters
faces
d
Returns
References wblut.hemesh.HEM_CenterSplitHole.getWallFaces(), wblut.hemesh.HE_Selection.modify(), and wblut.hemesh.HEM_CenterSplitHole.setOffset().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesCenterHole (final HE_Selection faces, final double d, final double c) static
Parameters
faces
d
c
Returns
References wblut.hemesh.HEM_CenterSplitHole.getWallFaces(), wblut.hemesh.HE_Selection.modify(), wblut.hemesh.HEM_CenterSplitHole.setChamfer(), and wblut.hemesh.HEM_CenterSplitHole.setOffset().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesHybrid (final HE_Mesh mesh) static
Hybrid split faces: midsplit for triangles, quad split otherwise.
Parameters
mesh
Returns
selection of new faces and new vertices
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Selection.addFaces(), wblut.hemesh.HE_Selection.addVertices(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Mesh.getFacesAsArray(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Halfedge.getUVW(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.hasHalfedgeUVW(), wblut.hemesh.HE_Halfedge.hasUVW(), wblut.hemesh.HE_Vertex.hasUVW(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Vertex.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HET_MeshOp.splitEdges(), wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), and wblut.hemesh.HE_TextureCoordinate.wd().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesHybrid (final HE_Selection sel) static
Hybrid split faces: midsplit for triangles, quad split otherwise.
Parameters
sel the sel
Returns
selection of new faces and new vertices
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Selection.addFaces(), wblut.hemesh.HE_Selection.addVertices(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Selection.fItr(), wblut.hemesh.HE_Face.getFaceCenter(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Selection.getFacesAsArray(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Selection.getNumberOfFaces(), wblut.hemesh.HE_Halfedge.getUVW(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Selection.getVerticesAsArray(), wblut.hemesh.HE_Halfedge.hasHalfedgeUVW(), wblut.hemesh.HE_Halfedge.hasUVW(), wblut.hemesh.HE_Vertex.hasUVW(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Vertex.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HET_MeshOp.splitEdges(), wblut.hemesh.HE_TextureCoordinate.ud(), wblut.hemesh.HE_TextureCoordinate.vd(), and wblut.hemesh.HE_TextureCoordinate.wd().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesMidEdge (final HE_Mesh mesh) static
Midedge split faces.
Parameters
mesh
Returns
selection of new faces and new vertices
References wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Selection.addFaces(), wblut.hemesh.HE_Selection.addVertices(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Mesh.getFacesAsArray(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Halfedge.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.hasUVW(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), and wblut.hemesh.HET_MeshOp.splitEdges().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesMidEdge (final HE_Selection selection) static
Mid edge split selected faces.
Parameters
selection selection to split
Returns
selection of new faces and new vertices
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Selection.addFaces(), wblut.hemesh.HE_Selection.addVertices(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Selection.fItr(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Selection.getFacesAsArray(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Selection.getNumberOfFaces(), wblut.hemesh.HE_Halfedge.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Selection.getVerticesAsArray(), wblut.hemesh.HE_Halfedge.hasUVW(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), and wblut.hemesh.HET_MeshOp.splitEdges().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesMidEdgeHole (final HE_Mesh mesh) static
Mid edge split faces.
Parameters
mesh
Returns
selection of new faces and new vertices
References wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Selection.addFaces(), wblut.hemesh.HE_Selection.addVertices(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Mesh.deleteFace(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Mesh.getFacesAsArray(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Halfedge.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.hasUVW(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), and wblut.hemesh.HET_MeshOp.splitEdges().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesMidEdgeHole (final HE_Selection selection) static
Parameters
selection
Returns
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.addDerivedElement(), wblut.hemesh.HE_Selection.addFaces(), wblut.hemesh.HE_Selection.addVertices(), wblut.hemesh.HE_Selection.collectEdgesByFace(), wblut.hemesh.HE_Selection.collectVertices(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Mesh.deleteFace(), wblut.hemesh.HE_Selection.fItr(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_Selection.getFacesAsArray(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Selection.getNumberOfFaces(), wblut.hemesh.HE_Halfedge.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Halfedge.hasUVW(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Mesh.setPair(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), and wblut.hemesh.HET_MeshOp.splitEdges().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesQuad (final HE_Mesh mesh) static
Quad split faces.
Parameters
mesh
Returns
selection of new faces and new vertices
References wblut.hemesh.HES_QuadSplit.getSplitFaces(), and wblut.hemesh.HE_Mesh.subdivide().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesQuad (final HE_Mesh mesh, final double d) static
Quad split faces.
Parameters
mesh
d
Returns
selection of new faces and new vertices
References wblut.hemesh.HES_QuadSplit.getSplitFaces(), wblut.hemesh.HES_QuadSplit.setOffset(), and wblut.hemesh.HE_Mesh.subdivide().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesQuad (final HE_Selection sel) static
Quad split selected faces.
Parameters
sel selection to split
Returns
selection of new faces and new vertices
References wblut.hemesh.HES_QuadSplit.getSplitFaces(), and wblut.hemesh.HE_Selection.subdivide().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesQuad (final HE_Selection sel, final double d) static
Quad split selected faces.
Parameters
sel selection to split
d
Returns
selection of new faces and new vertices
References wblut.hemesh.HES_QuadSplit.getSplitFaces(), wblut.hemesh.HES_QuadSplit.setOffset(), and wblut.hemesh.HE_Selection.subdivide().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesTri (final HE_Mesh mesh) static
Tri split faces.
Parameters
mesh
Returns
selection of new faces and new vertex
References wblut.hemesh.HEM_TriSplit.getSplitFaces(), and wblut.hemesh.HE_Mesh.modify().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesTri (final HE_Mesh mesh, final double d) static
Tri split faces with offset along face normal.
Parameters
mesh
d offset along face normal
Returns
selection of new faces and new vertex
References wblut.hemesh.HEM_TriSplit.getSplitFaces(), wblut.hemesh.HE_Mesh.modify(), and wblut.hemesh.HEM_TriSplit.setOffset().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesTri (final HE_Selection selection) static
Tri split faces.
Parameters
selection face selection to split
Returns
selection of new faces and new vertex
References wblut.hemesh.HEM_TriSplit.getSplitFaces(), and wblut.hemesh.HE_Selection.modify().
static HE_Selection wblut.hemesh.HET_MeshOp.splitFacesTri (final HE_Selection selection, final double d) static
Tri split faces with offset along face normal.
Parameters
selection face selection to split
d offset along face normal
Returns
selection of new faces and new vertex
References wblut.hemesh.HEM_TriSplit.getSplitFaces(), wblut.hemesh.HE_Selection.modify(), and wblut.hemesh.HEM_TriSplit.setOffset().
static HE_Selection wblut.hemesh.HET_MeshOp.triangulate (final HE_Mesh mesh) static
Triangulate all faces.
Parameters
mesh
Returns
References wblut.hemesh.HE_Mesh.modify(), and wblut.hemesh.HEM_TriangulateMT.triangles.
static HE_Selection wblut.hemesh.HET_MeshOp.triangulate (final HE_Mesh mesh, final HE_Face face) static
Parameters
mesh
face
Returns
References wblut.hemesh.HE_Selection.add(), and wblut.hemesh.HET_MeshOp.triangulate().
static HE_Selection wblut.hemesh.HET_MeshOp.triangulate (final HE_Selection sel) static
Triangulate.
Parameters
sel selection
Returns
References wblut.hemesh.HE_Selection.modify(), and wblut.hemesh.HEM_TriangulateMT.triangles.
static HE_Selection wblut.hemesh.HET_MeshOp.triangulate (final HE_Mesh mesh, final long key) static
Triangulate face.
Parameters
mesh
key key of face
Returns
References wblut.hemesh.HE_Mesh.getFaceWithKey(), and wblut.hemesh.HET_MeshOp.triangulate().
static HE_Selection wblut.hemesh.HET_MeshOp.triangulateConcaveFace (final HE_Mesh mesh, final HE_Face face) static
Triangulate face if concave.
Parameters
mesh
face key of face
Returns
References wblut.hemesh.HE_Selection.add(), wblut.geom.WB_Classification.CONCAVE, wblut.hemesh.HE_Face.getFaceType(), and wblut.hemesh.HET_MeshOp.triangulate().
static HE_Selection wblut.hemesh.HET_MeshOp.triangulateConcaveFace (final HE_Mesh mesh, final long key) static
Triangulate face if concave.
Parameters
mesh
key key of face
Returns
References wblut.hemesh.HE_Mesh.getFaceWithKey(), and wblut.hemesh.HET_MeshOp.triangulateConcaveFace().
static HE_Selection wblut.hemesh.HET_MeshOp.triangulateConcaveFaces (final HE_Mesh mesh) static
Triangulate all concave faces.
Parameters
mesh
Returns
References wblut.geom.WB_Classification.CONCAVE, wblut.hemesh.HE_Mesh.getFacesAsArray(), wblut.hemesh.HET_MeshOp.getFaceType(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HET_MeshOp.triangulate(), and wblut.hemesh.HE_Selection.union().
static HE_Selection wblut.hemesh.HET_MeshOp.triangulateConcaveFaces (final HE_Mesh mesh, final List< HE_Face > sel) static
Parameters
mesh
sel
Returns
References wblut.hemesh.HE_Selection.add(), wblut.geom.WB_Classification.CONCAVE, wblut.hemesh.HE_Mesh.get(), wblut.hemesh.HE_Element.key, wblut.hemesh.HET_MeshOp.triangulate(), and wblut.hemesh.HE_Selection.union().
static HE_Selection wblut.hemesh.HET_MeshOp.triangulateFaceStar (final HE_Mesh mesh, final HE_Vertex v) static
Parameters
mesh
v
Returns
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Face.getFaceDegree(), wblut.hemesh.HE_VertexFaceCirculator.hasNext(), wblut.hemesh.HE_VertexFaceCirculator.next(), and wblut.hemesh.HET_MeshOp.triangulate().
static HE_Selection wblut.hemesh.HET_MeshOp.triangulateFaceStar (final HE_Mesh mesh, final long vertexkey) static
Parameters
mesh
vertexkey
Returns
References wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Selection.contains(), wblut.hemesh.HE_Mesh.getVertexWithKey(), wblut.hemesh.HE_VertexFaceCirculator.hasNext(), wblut.hemesh.HE_VertexFaceCirculator.next(), and wblut.hemesh.HET_MeshOp.triangulate().
Member Data Documentation
WB_GeometryFactory wblut.hemesh.HET_MeshOp.gf = new WB_GeometryFactory() static private
final WB_ProgressTracker wblut.hemesh.HET_MeshOp.tracker = WB_ProgressTracker.instance() static
The documentation for this class was generated from the following file:
src/hemesh_tools/wblut/hemesh/HET_MeshOp.java