HE_Mesh: wblut.geom.WB_Subdivision.T04 Class Reference
wblut.geom.WB_Subdivision.T04 Class Reference
Public Member Functions
WB_SubdivisionResult apply (final WB_Triangle triangle)
T04 setF (final double ff)
Public Member Functions inherited from wblut.geom.WB_Subdivision.WB_TriangleSubdivision
WB_SubdivisionResult apply (WB_Triangle triangle)
Private Attributes
double f = 0.5
Member Function Documentation
WB_SubdivisionResult wblut.geom.WB_Subdivision.T04.apply (final WB_Triangle triangle)
References wblut.geom.WB_Subdivision.WB_SubdivisionResult.addQuad(), wblut.geom.WB_Subdivision.WB_SubdivisionResult.addTriangle(), and wblut.geom.WB_Point.interpolate().
T04 wblut.geom.WB_Subdivision.T04.setF (final double ff)
Member Data Documentation
double wblut.geom.WB_Subdivision.T04.f = 0.5 private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Subdivision.java