HE_Mesh: wblut.geom.WB_CoordinateSystem3D Class Reference
wblut.geom.WB_CoordinateSystem3D Class Reference
Public Member Functions
WB_CoordinateSystem3D (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_Coord z, final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_Coord z)
WB_CoordinateSystem3D (final WB_Plane P)
WB_CoordinateSystem3D ()
WB_CoordinateSystem3D (final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D get ()
WB_CoordinateSystem3D setParent (final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D setOrigin (final WB_Point o)
WB_CoordinateSystem3D setOrigin (final double ox, final double oy, final double oz)
WB_CoordinateSystem3D setXY (final WB_Coord X, final WB_Coord Y)
WB_CoordinateSystem3D setYX (final WB_Coord Y, final WB_Coord X)
WB_CoordinateSystem3D setXZ (final WB_Coord X, final WB_Coord Z)
WB_CoordinateSystem3D setZX (final WB_Coord Z, final WB_Coord X)
WB_CoordinateSystem3D setYZ (final WB_Coord Y, final WB_Coord Z)
WB_CoordinateSystem3D setZY (final WB_Coord Z, final WB_Coord Y)
WB_Vector getX ()
WB_Vector getY ()
WB_Vector getZ ()
WB_Point getOrigin ()
WB_CoordinateSystem3D getParent ()
boolean isWorld ()
WB_CoordinateSystem3D setXY (final double xx, final double xy, final double xz, final double yx, final double yy, final double yz)
WB_CoordinateSystem3D setYX (final double yx, final double yy, final double yz, final double xx, final double xy, final double xz)
WB_CoordinateSystem3D setXZ (final double xx, final double xy, final double xz, final double zx, final double zy, final double zz)
WB_CoordinateSystem3D setZX (final double zx, final double zy, final double zz, final double xx, final double xy, final double xz)
WB_CoordinateSystem3D setYZ (final double yx, final double yy, final double yz, final double zx, final double zy, final double zz)
WB_CoordinateSystem3D setZY (final double zx, final double zy, final double zz, final double yx, final double yy, final double yz)
WB_CoordinateSystem3D setX (final WB_Coord X)
WB_CoordinateSystem3D setY (final WB_Coord Y)
WB_CoordinateSystem3D setZ (final WB_Coord Z)
WB_CoordinateSystem3D rotateX (final double a)
WB_CoordinateSystem3D rotateY (final double a)
WB_CoordinateSystem3D rotateZ (final double a)
WB_CoordinateSystem3D rotate (final double a, final WB_Vector v)
WB_Transform getTransformFromParent ()
WB_Transform getTransformToParent ()
WB_Transform getTransformFromWorld ()
WB_Transform getTransformToWorld ()
WB_Transform getTransformFrom (final WB_CoordinateSystem3D CS)
WB_Transform getTransformTo (final WB_CoordinateSystem3D CS)
WB_CoordinateSystem3D setX (final double xx, final double xy, final double xz)
WB_CoordinateSystem3D setY (final double yx, final double yy, final double yz)
WB_CoordinateSystem3D setZ (final double zx, final double zy, final double zz)
void flipX ()
void flipY ()
void flipZ ()
String toString ()
Protected Member Functions
WB_CoordinateSystem3D (final boolean world)
void set (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_Coord z)
void set (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_Coord z, final WB_CoordinateSystem3D CS)
Static Protected Member Functions
static final WB_CoordinateSystem3D WORLD ()
Private Attributes
WB_CoordinateSystem3D _parent
WB_Point _origin
WB_Vector _X
WB_Vector _Y
WB_Vector _Z
boolean _isWorld
Constructor & Destructor Documentation
wblut.geom.WB_CoordinateSystem3D.WB_CoordinateSystem3D (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_Coord z, final WB_CoordinateSystem3D parent)
Parameters
origin
x
y
z
parent
wblut.geom.WB_CoordinateSystem3D.WB_CoordinateSystem3D (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_Coord z)
References wblut.geom.WB_CoordinateSystem3D.WORLD().
wblut.geom.WB_CoordinateSystem3D.WB_CoordinateSystem3D (final WB_Plane P)
References wblut.geom.WB_Plane.getOrigin(), wblut.geom.WB_Plane.getU(), wblut.geom.WB_Plane.getV(), and wblut.geom.WB_Plane.getW().
wblut.geom.WB_CoordinateSystem3D.WB_CoordinateSystem3D (final boolean world) protected
Parameters
world
References wblut.geom.WB_CoordinateSystem3D.WORLD(), wblut.geom.WB_Vector.X, wblut.geom.WB_Vector.Y, wblut.geom.WB_Vector.Z, and wblut.geom.WB_Point.ZERO.
wblut.geom.WB_CoordinateSystem3D.WB_CoordinateSystem3D ()
wblut.geom.WB_CoordinateSystem3D.WB_CoordinateSystem3D (final WB_CoordinateSystem3D parent)
Parameters
parent
References wblut.geom.WB_Vector.X, wblut.geom.WB_Vector.Y, wblut.geom.WB_Vector.Z, and wblut.geom.WB_Point.ZERO.
Member Function Documentation
void wblut.geom.WB_CoordinateSystem3D.flipX ()
References wblut.geom.WB_Vector.mulSelf().
void wblut.geom.WB_CoordinateSystem3D.flipY ()
References wblut.geom.WB_Vector.mulSelf().
void wblut.geom.WB_CoordinateSystem3D.flipZ ()
References wblut.geom.WB_Vector.mulSelf().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.get ()
Returns
References wblut.geom.WB_CoordinateSystem3D.WB_CoordinateSystem3D().
WB_Point wblut.geom.WB_CoordinateSystem3D.getOrigin ()
Returns
References wblut.geom.WB_Point.copy().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.getParent ()
Returns
References wblut.geom.WB_CoordinateSystem3D._parent.
WB_Transform wblut.geom.WB_CoordinateSystem3D.getTransformFrom (final WB_CoordinateSystem3D CS)
Parameters
CS
Returns
References wblut.geom.WB_Transform.addFromCSToCS().
WB_Transform wblut.geom.WB_CoordinateSystem3D.getTransformFromParent ()
Returns
References wblut.geom.WB_Transform.addFromParentToCS().
WB_Transform wblut.geom.WB_CoordinateSystem3D.getTransformFromWorld ()
Returns
References wblut.geom.WB_Transform.addFromWorldToCS().
WB_Transform wblut.geom.WB_CoordinateSystem3D.getTransformTo (final WB_CoordinateSystem3D CS)
Parameters
CS
Returns
References wblut.geom.WB_Transform.addFromCSToCS().
WB_Transform wblut.geom.WB_CoordinateSystem3D.getTransformToParent ()
Returns
References wblut.geom.WB_Transform.addFromCSToParent().
WB_Transform wblut.geom.WB_CoordinateSystem3D.getTransformToWorld ()
Returns
References wblut.geom.WB_Transform.addFromCSToWorld().
WB_Vector wblut.geom.WB_CoordinateSystem3D.getX ()
Returns
References wblut.geom.WB_Vector.copy().
WB_Vector wblut.geom.WB_CoordinateSystem3D.getY ()
Returns
References wblut.geom.WB_Vector.copy().
WB_Vector wblut.geom.WB_CoordinateSystem3D.getZ ()
Returns
References wblut.geom.WB_Vector.copy().
boolean wblut.geom.WB_CoordinateSystem3D.isWorld ()
Returns
References wblut.geom.WB_CoordinateSystem3D._isWorld.
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.rotate (final double a, final WB_Vector v)
Parameters
a
v
Returns
References wblut.geom.WB_Vector.copy(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Vector.rotateAboutAxisSelf().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.rotateX (final double a)
Parameters
a
Returns
References wblut.geom.WB_Vector.rotateAboutAxisSelf().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.rotateY (final double a)
Parameters
a
Returns
References wblut.geom.WB_Vector.rotateAboutAxisSelf().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.rotateZ (final double a)
Parameters
a
Returns
References wblut.geom.WB_Vector.rotateAboutAxisSelf().
void wblut.geom.WB_CoordinateSystem3D.set (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_Coord z) protected
Parameters
origin
x
y
z
void wblut.geom.WB_CoordinateSystem3D.set (final WB_Coord origin, final WB_Coord x, final WB_Coord y, final WB_Coord z, final WB_CoordinateSystem3D CS) protected
Parameters
origin
x
y
z
CS
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setOrigin (final WB_Point o)
Parameters
o
Returns
References wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setOrigin (final double ox, final double oy, final double oz)
Parameters
ox
oy
oz
Returns
References wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setParent (final WB_CoordinateSystem3D parent)
Parameters
parent
Returns
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setX (final WB_Coord X)
Parameters
X
Returns
References wblut.math.WB_Math.clamp(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_CoordinateSystem3D.flipX(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_CoordinateSystem3D.rotate().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setX (final double xx, final double xy, final double xz)
Parameters
xx
xy
xz
Returns
References wblut.math.WB_Math.clamp(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_CoordinateSystem3D.flipX(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_CoordinateSystem3D.rotate().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setXY (final WB_Coord X, final WB_Coord Y)
Parameters
X
Y
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setXY (final double xx, final double xy, final double xz, final double yx, final double yy, final double yz)
Parameters
xx
xy
xz
yx
yy
yz
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setXZ (final WB_Coord X, final WB_Coord Z)
Parameters
X
Z
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setXZ (final double xx, final double xy, final double xz, final double zx, final double zy, final double zz)
Parameters
xx
xy
xz
zx
zy
zz
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setY (final WB_Coord Y)
Parameters
Y
Returns
References wblut.math.WB_Math.clamp(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_CoordinateSystem3D.flipY(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_CoordinateSystem3D.rotate().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setY (final double yx, final double yy, final double yz)
Parameters
yx
yy
yz
Returns
References wblut.math.WB_Math.clamp(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_CoordinateSystem3D.flipY(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_CoordinateSystem3D.rotate().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setYX (final WB_Coord Y, final WB_Coord X)
Parameters
Y
X
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setYX (final double yx, final double yy, final double yz, final double xx, final double xy, final double xz)
Parameters
yx
yy
yz
xx
xy
xz
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setYZ (final WB_Coord Y, final WB_Coord Z)
Parameters
Y
Z
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setYZ (final double yx, final double yy, final double yz, final double zx, final double zy, final double zz)
Parameters
yx
yy
yz
zx
zy
zz
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setZ (final WB_Coord Z)
Parameters
Z
Returns
References wblut.math.WB_Math.clamp(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_CoordinateSystem3D.flipZ(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_CoordinateSystem3D.rotate().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setZ (final double zx, final double zy, final double zz)
Parameters
zx
zy
zz
Returns
References wblut.math.WB_Math.clamp(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.dot(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_CoordinateSystem3D.flipZ(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_CoordinateSystem3D.rotate().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setZX (final WB_Coord Z, final WB_Coord X)
Parameters
Z
X
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setZX (final double zx, final double zy, final double zz, final double xx, final double xy, final double xz)
Parameters
zx
zy
zz
xx
xy
xz
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setZY (final WB_Coord Z, final WB_Coord Y)
Parameters
Z
Y
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.setZY (final double zx, final double zy, final double zz, final double yx, final double yy, final double yz)
Parameters
zx
zy
zz
yx
yy
yz
Returns
References wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_MutableCoordinate.set().
String wblut.geom.WB_CoordinateSystem3D.toString ()
static final WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D.WORLD () static protected
Returns
References wblut.geom.WB_CoordinateSystem3D.WB_CoordinateSystem3D().
Member Data Documentation
boolean wblut.geom.WB_CoordinateSystem3D._isWorld private
WB_Point wblut.geom.WB_CoordinateSystem3D._origin private
WB_CoordinateSystem3D wblut.geom.WB_CoordinateSystem3D._parent private
WB_Vector wblut.geom.WB_CoordinateSystem3D._X private
WB_Vector wblut.geom.WB_CoordinateSystem3D._Y private
WB_Vector wblut.geom.WB_CoordinateSystem3D._Z private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_CoordinateSystem3D.java