HE_Mesh: wblut.nurbs.WB_RBSplineSurface Class Reference
wblut.nurbs.WB_RBSplineSurface Class Reference
Public Member Functions
WB_RBSplineSurface (final WB_Coord[][] controlPoints, final WB_NurbsKnot uknot, final WB_NurbsKnot vknot, final double[][] weights)
WB_RBSplineSurface (final WB_Point[][] controlPoints, final int udegree, final int vdegree, final double[][] weights)
WB_RBSplineSurface (final WB_Point[][] controlPoints, final int udegree, final int vdegree)
WB_RBSplineSurface (final WB_PointHomogeneous[][] controlPoints, final WB_NurbsKnot uknot, final WB_NurbsKnot vknot)
void setWeight (final int i, final int j, final double w)
WB_Point surfacePoint (final double u, final double v)
void updateWeights ()
WB_RBSplineSurface insertUKnot (final double u)
WB_RBSplineSurface insertUKnotMax (final double u)
WB_RBSplineSurface insertUKnot (final double u, final int r)
WB_RBSplineSurface insertVKnot (final double v)
WB_RBSplineSurface insertVKnotMax (final double v)
WB_RBSplineSurface insertVKnot (final double v, final int r)
WB_RBSpline isoCurveU (final double u)
WB_RBSpline isoCurveV (final double v)
WB_RBSplineSurface[] splitU (final double u)
WB_RBSplineSurface[] splitV (final double v)
WB_RBSplineSurface[] split (final double u, final double v)
Public Member Functions inherited from wblut.nurbs.WB_BSplineSurface
WB_BSplineSurface ()
WB_BSplineSurface (final WB_Coord[][] controlPoints, final WB_NurbsKnot uknot, final WB_NurbsKnot vknot)
WB_BSplineSurface (final WB_PointHomogeneous[][] controlPoints, final WB_NurbsKnot uknot, final WB_NurbsKnot vknot)
WB_BSplineSurface (final WB_Coord[][] controlPoints, final int udegree, final int vdegree)
WB_BSplineSurface (final WB_Coord point00, final WB_Coord point10, final WB_Coord point01, final WB_Coord point11)
WB_Point surfacePoint (final double u, final double v)
HE_Mesh toControlHemesh ()
WB_BSplineSurface insertUKnot (final double u)
WB_BSplineSurface insertUKnotMax (final double u)
WB_BSplineSurface insertUKnot (final double u, final int r)
WB_BSplineSurface insertVKnot (final double v)
WB_BSplineSurface insertVKnotMax (final double v)
WB_BSplineSurface insertVKnot (final double v, final int r)
WB_BSpline isoCurveU (final double u)
WB_BSpline isoCurveV (final double v)
WB_Coord[][] points ()
int p ()
int n ()
int q ()
int m ()
WB_NurbsKnot uknot ()
WB_NurbsKnot vknot ()
WB_BSplineSurface[] splitU (final double u)
WB_BSplineSurface[] splitV (final double v)
WB_BSplineSurface[] split (final double u, final double v)
double loweru ()
double upperu ()
double lowerv ()
double upperv ()
Public Member Functions inherited from wblut.geom.WB_Surface
WB_Point surfacePoint (double u, double v)
Protected Attributes
WB_PointHomogeneous[][] wpoints
Protected Attributes inherited from wblut.nurbs.WB_BSplineSurface
WB_NurbsKnot uknot
WB_NurbsKnot vknot
WB_Coord[][] points
int p
int n
int q
int m
Private Attributes
final double[][] weights
Constructor & Destructor Documentation
wblut.nurbs.WB_RBSplineSurface.WB_RBSplineSurface (final WB_Coord controlPoints[][], final WB_NurbsKnot uknot, final WB_NurbsKnot vknot, final double weights[][])
Parameters
controlPoints
uknot
vknot
weights
References wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_BSplineSurface.n(), wblut.nurbs.WB_BSplineSurface.points(), and wblut.nurbs.WB_RBSplineSurface.weights.
wblut.nurbs.WB_RBSplineSurface.WB_RBSplineSurface (final WB_Point controlPoints[][], final int udegree, final int vdegree, final double weights[][])
Parameters
controlPoints
udegree
vdegree
weights
References wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_BSplineSurface.n(), wblut.nurbs.WB_BSplineSurface.points(), and wblut.nurbs.WB_RBSplineSurface.weights.
wblut.nurbs.WB_RBSplineSurface.WB_RBSplineSurface (final WB_Point controlPoints[][], final int udegree, final int vdegree)
Parameters
controlPoints
udegree
vdegree
References wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_BSplineSurface.n(), and wblut.nurbs.WB_BSplineSurface.points().
wblut.nurbs.WB_RBSplineSurface.WB_RBSplineSurface (final WB_PointHomogeneous controlPoints[][], final WB_NurbsKnot uknot, final WB_NurbsKnot vknot)
Parameters
controlPoints
uknot
vknot
References wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_NurbsKnot.n, wblut.nurbs.WB_BSplineSurface.n(), wblut.nurbs.WB_NurbsKnot.p(), wblut.nurbs.WB_BSplineSurface.p(), wblut.nurbs.WB_BSplineSurface.points(), wblut.geom.WB_PointHomogeneous.project(), wblut.nurbs.WB_BSplineSurface.q(), wblut.nurbs.WB_BSplineSurface.uknot(), wblut.nurbs.WB_BSplineSurface.vknot(), and wblut.geom.WB_MutableCoordinate4D.wd().
Member Function Documentation
WB_RBSplineSurface wblut.nurbs.WB_RBSplineSurface.insertUKnot (final double u)
WB_RBSplineSurface wblut.nurbs.WB_RBSplineSurface.insertUKnot (final double u, final int r)
References wblut.geom.WB_PointHomogeneous.interpolate(), wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_NurbsKnot.multiplicity(), wblut.nurbs.WB_BSplineSurface.n(), wblut.nurbs.WB_BSplineSurface.p(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_BSplineSurface.uknot(), wblut.nurbs.WB_NurbsKnot.value(), wblut.nurbs.WB_BSplineSurface.vknot(), and wblut.nurbs.WB_RBSplineSurface.WB_RBSplineSurface().
WB_RBSplineSurface wblut.nurbs.WB_RBSplineSurface.insertUKnotMax (final double u)
References wblut.nurbs.WB_RBSplineSurface.insertUKnot(), wblut.nurbs.WB_NurbsKnot.multiplicity(), wblut.nurbs.WB_BSplineSurface.p(), and wblut.nurbs.WB_BSplineSurface.uknot().
WB_RBSplineSurface wblut.nurbs.WB_RBSplineSurface.insertVKnot (final double v)
WB_RBSplineSurface wblut.nurbs.WB_RBSplineSurface.insertVKnot (final double v, final int r)
References wblut.geom.WB_PointHomogeneous.interpolate(), wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_NurbsKnot.multiplicity(), wblut.nurbs.WB_BSplineSurface.n(), wblut.nurbs.WB_BSplineSurface.q(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_BSplineSurface.uknot(), wblut.nurbs.WB_NurbsKnot.value(), wblut.nurbs.WB_BSplineSurface.vknot(), and wblut.nurbs.WB_RBSplineSurface.WB_RBSplineSurface().
WB_RBSplineSurface wblut.nurbs.WB_RBSplineSurface.insertVKnotMax (final double v)
References wblut.nurbs.WB_RBSplineSurface.insertVKnot(), wblut.nurbs.WB_NurbsKnot.multiplicity(), wblut.nurbs.WB_BSplineSurface.q(), and wblut.nurbs.WB_BSplineSurface.vknot().
WB_RBSpline wblut.nurbs.WB_RBSplineSurface.isoCurveU (final double u)
References wblut.geom.WB_Point4D.add(), wblut.nurbs.WB_NurbsKnot.basisFunctions(), wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_BSplineSurface.p(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_BSplineSurface.uknot(), wblut.nurbs.WB_BSplineSurface.vknot(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
WB_RBSpline wblut.nurbs.WB_RBSplineSurface.isoCurveV (final double v)
References wblut.geom.WB_Point4D.add(), wblut.nurbs.WB_NurbsKnot.basisFunctions(), wblut.nurbs.WB_BSplineSurface.n(), wblut.nurbs.WB_BSplineSurface.q(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_BSplineSurface.uknot(), wblut.nurbs.WB_BSplineSurface.vknot(), wblut.geom.WB_MutableCoordinate4D.wd(), wblut.geom.WB_MutableCoordinate4D.xd(), wblut.geom.WB_MutableCoordinate4D.yd(), and wblut.geom.WB_MutableCoordinate4D.zd().
void wblut.nurbs.WB_RBSplineSurface.setWeight (final int i, final int j, final double w)
Parameters
i
j
w
References wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_BSplineSurface.n(), and wblut.nurbs.WB_BSplineSurface.points().
WB_RBSplineSurface [] wblut.nurbs.WB_RBSplineSurface.split (final double u, final double v)
References wblut.nurbs.WB_RBSplineSurface.splitU(), and wblut.nurbs.WB_RBSplineSurface.splitV().
WB_RBSplineSurface [] wblut.nurbs.WB_RBSplineSurface.splitU (final double u)
References wblut.nurbs.WB_RBSplineSurface.insertUKnotMax(), wblut.nurbs.WB_NurbsKnot.m, wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_NurbsKnot.normalize(), wblut.nurbs.WB_BSplineSurface.p(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_BSplineSurface.uknot, wblut.nurbs.WB_NurbsKnot.value(), wblut.nurbs.WB_BSplineSurface.vknot(), wblut.nurbs.WB_RBSplineSurface.WB_RBSplineSurface(), and wblut.nurbs.WB_RBSplineSurface.wpoints.
WB_RBSplineSurface [] wblut.nurbs.WB_RBSplineSurface.splitV (final double v)
References wblut.nurbs.WB_RBSplineSurface.insertVKnotMax(), wblut.nurbs.WB_NurbsKnot.m, wblut.nurbs.WB_BSplineSurface.n(), wblut.nurbs.WB_NurbsKnot.normalize(), wblut.nurbs.WB_BSplineSurface.q(), wblut.nurbs.WB_NurbsKnot.setValue(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_BSplineSurface.uknot(), wblut.nurbs.WB_NurbsKnot.value(), wblut.nurbs.WB_BSplineSurface.vknot, wblut.nurbs.WB_RBSplineSurface.WB_RBSplineSurface(), and wblut.nurbs.WB_RBSplineSurface.wpoints.
WB_Point wblut.nurbs.WB_RBSplineSurface.surfacePoint (final double u, final double v)
References wblut.geom.WB_Point4D.addSelf(), wblut.nurbs.WB_NurbsKnot.basisFunctions(), wblut.geom.WB_Point4D.mulSelf(), wblut.nurbs.WB_BSplineSurface.p(), wblut.geom.WB_PointHomogeneous.project(), wblut.nurbs.WB_BSplineSurface.q(), wblut.nurbs.WB_NurbsKnot.span(), wblut.nurbs.WB_BSplineSurface.uknot(), and wblut.nurbs.WB_BSplineSurface.vknot().
void wblut.nurbs.WB_RBSplineSurface.updateWeights ()
References wblut.nurbs.WB_BSplineSurface.m(), wblut.nurbs.WB_BSplineSurface.n(), and wblut.nurbs.WB_BSplineSurface.points().
Member Data Documentation
final double [][] wblut.nurbs.WB_RBSplineSurface.weights private
WB_PointHomogeneous [][] wblut.nurbs.WB_RBSplineSurface.wpoints protected
The documentation for this class was generated from the following file:
src/nurbs/wblut/nurbs/WB_RBSplineSurface.java