HE_Mesh: wblut.geom.WB_Ray Class Reference
wblut.geom.WB_Ray Class Reference
Public Member Functions
WB_Ray ()
WB_Ray (final WB_Coord o, final WB_Coord d)
WB_Ray (final double ox, final double oy, final double oz, final double dx, final double dy, final double dz)
String toString ()
void set (final WB_Coord o, final WB_Coord d)
void setFromPoints (final WB_Coord p1, final WB_Coord p2)
WB_Point getPoint (final double t)
void getPointInto (final double t, final WB_MutableCoord p)
WB_Point getParametricPoint (final double t)
void getParametricPointInto (final double t, final WB_MutableCoord p)
WB_Coord getOrigin ()
WB_Coord getDirection ()
WB_Point curvePoint (final double u)
WB_Vector curveDirection (final double u)
WB_Vector curveDerivative (final double u)
double getLowerU ()
double getUpperU ()
boolean equals (final Object o)
int hashCode ()
Public Member Functions inherited from wblut.geom.WB_Line
WB_Line ()
WB_Line (final WB_Coord o, final WB_Coord d)
WB_Line (final double ox, final double oy, final double oz, final double dx, final double dy, final double dz)
WB_Line (final double ox, final double oy, final double dx, final double dy)
String toString ()
void setFromPoints (final WB_Coord p1, final WB_Coord p2)
double getT (final WB_Coord p)
WB_Point curvePoint (final double u)
WB_Vector curveDirection (final double u)
WB_Vector curveDerivative (final double u)
double getLowerU ()
double getUpperU ()
double a ()
double b ()
double c ()
WB_Coord getDirection ()
WB_Vector getNormal ()
WB_Coord getOrigin ()
WB_Point getParametricPoint (final double t)
void getParametricPointInto (final double t, final WB_MutableCoord result)
WB_Point getPoint (final double t)
void getPointInto (final double t, final WB_MutableCoord result)
boolean equals (final Object o)
int hashCode ()
Public Member Functions inherited from wblut.geom.WB_Curve
WB_Point curvePoint (double u)
WB_Vector curveDirection (double u)
WB_Vector curveDerivative (double u)
Static Public Member Functions
static WB_Ray X ()
static WB_Ray Y ()
static WB_Ray Z ()
Static Public Member Functions inherited from wblut.geom.WB_Line
static WB_Line X ()
static WB_Line Y ()
static WB_Line Z ()
Additional Inherited Members
Protected Member Functions inherited from wblut.geom.WB_Line
void set (final WB_Coord o, final WB_Coord d)
Protected Attributes inherited from wblut.geom.WB_Line
WB_Point origin
WB_Vector direction
Constructor & Destructor Documentation
wblut.geom.WB_Ray.WB_Ray ()
References wblut.geom.WB_Line.direction, and wblut.geom.WB_Line.origin.
wblut.geom.WB_Ray.WB_Ray (final WB_Coord o, final WB_Coord d)
Parameters
o
d
References wblut.geom.WB_Line.direction, wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Line.origin.
wblut.geom.WB_Ray.WB_Ray (final double ox, final double oy, final double oz, final double dx, final double dy, final double dz)
Parameters
ox
oy
oz
dx
dy
dz
References wblut.geom.WB_Line.direction, wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Line.origin.
Member Function Documentation
WB_Vector wblut.geom.WB_Ray.curveDerivative (final double u)
References wblut.geom.WB_Line.direction.
WB_Vector wblut.geom.WB_Ray.curveDirection (final double u)
References wblut.geom.WB_Line.direction.
WB_Point wblut.geom.WB_Ray.curvePoint (final double u)
References wblut.geom.WB_Ray.getPoint().
boolean wblut.geom.WB_Ray.equals (final Object o)
References wblut.geom.WB_Line.direction, wblut.geom.WB_Point.equals(), wblut.geom.WB_Vector.equals(), wblut.geom.WB_Ray.getDirection(), wblut.geom.WB_Ray.getOrigin(), and wblut.geom.WB_Line.origin.
WB_Coord wblut.geom.WB_Ray.getDirection ()
References wblut.geom.WB_Line.direction.
double wblut.geom.WB_Ray.getLowerU ()
Returns
Implements wblut.geom.WB_Curve.
WB_Coord wblut.geom.WB_Ray.getOrigin ()
References wblut.geom.WB_Line.origin.
WB_Point wblut.geom.WB_Ray.getParametricPoint (final double t)
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Line.direction, wblut.math.WB_Math.max(), wblut.geom.WB_Line.origin, and wblut.geom.WB_Point.scaleSelf().
void wblut.geom.WB_Ray.getParametricPointInto (final double t, final WB_MutableCoord p)
References wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_Line.direction, wblut.geom.WB_Vector.mul(), wblut.geom.WB_Line.origin, and wblut.geom.WB_MutableCoord.set().
WB_Point wblut.geom.WB_Ray.getPoint (final double t)
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Line.direction, wblut.math.WB_Math.max(), wblut.geom.WB_Line.origin, and wblut.geom.WB_Point.scaleSelf().
void wblut.geom.WB_Ray.getPointInto (final double t, final WB_MutableCoord p)
References wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_Line.direction, wblut.geom.WB_Vector.mul(), wblut.geom.WB_Line.origin, and wblut.geom.WB_MutableCoord.set().
double wblut.geom.WB_Ray.getUpperU ()
Returns
Implements wblut.geom.WB_Curve.
int wblut.geom.WB_Ray.hashCode ()
References wblut.geom.WB_Line.direction, wblut.geom.WB_Point.hashCode(), wblut.geom.WB_Vector.hashCode(), and wblut.geom.WB_Line.origin.
void wblut.geom.WB_Ray.set (final WB_Coord o, final WB_Coord d)
References wblut.geom.WB_Line.direction, wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Line.origin.
void wblut.geom.WB_Ray.setFromPoints (final WB_Coord p1, final WB_Coord p2)
Parameters
p1
p2
References wblut.geom.WB_Line.direction, wblut.geom.WB_Vector.normalizeSelf(), and wblut.geom.WB_Line.origin.
String wblut.geom.WB_Ray.toString ()
References wblut.geom.WB_Line.direction, wblut.geom.WB_Line.origin, wblut.geom.WB_Point.toString(), and wblut.geom.WB_Vector.toString().
static WB_Ray wblut.geom.WB_Ray.X () static
Returns
References wblut.geom.WB_Ray.WB_Ray().
static WB_Ray wblut.geom.WB_Ray.Y () static
Returns
References wblut.geom.WB_Ray.WB_Ray().
static WB_Ray wblut.geom.WB_Ray.Z () static
Returns
References wblut.geom.WB_Ray.WB_Ray().
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Ray.java