HE_Mesh: wblut.geom.WB_IsoSurface Class Reference
wblut.geom.WB_IsoSurface Class Reference
Classes
class VertexRemap
Public Member Functions
WB_IsoSurface ()
WB_IsoSurface setGamma (final double gamma)
WB_IsoSurface setResolution (final int resx, final int resy, final int resz)
WB_IsoSurface setSize (final double dx, final double dy, final double dz)
WB_IsoSurface setValues (final double[][][] values)
WB_IsoSurface setValues (final float[][][] values)
WB_IsoSurface setValues (final WB_ScalarParameter function, final double xi, final double yi, final double zi, final double dx, final double dy, final double dz, final int sizeI, final int sizeJ, final int sizeK)
WB_IsoSurface setValues (final WB_HashGridDouble values)
WB_IsoSurface setValues (final String[] images, final PApplet home, final int sizeI, final int sizeJ, final int sizeK)
WB_IsoSurface setValues (final String[] images, final PApplet home, final int sizeI, final int sizeJ, final int sizeK, final WB_IsoValues3D.Mode mode)
WB_IsoSurface setValues (final WB_IsoValues3D values)
WB_IsoSurface setIsolevel (final double v)
WB_IsoSurface setBoundary (final double v)
WB_IsoSurface clearBoundary ()
WB_IsoSurface setInvert (final boolean invert)
WB_IsoSurface setCenter (final WB_Coord c)
List< WB_Triangle > getTriangles ()
Private Member Functions
void mapvertices ()
void setvalues ()
void polygonise ()
void snapvertices ()
List< WB_Triangle > getPolygons (final int i, final int j, final int k, final int cubeindex, final WB_Point offset, final boolean dummyrun)
int classifyCell (final int i, final int j, final int k)
WB_Point getIsoVertex (final int isopointindex, final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun)
WB_Point vertex (final int i, final int j, final int k, final WB_Point offset)
WB_Point xedge (final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun)
WB_Point yedge (final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun)
WB_Point zedge (final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun)
WB_Point interp (final double isolevel, final WB_Point p1, final WB_Point p2, final double valp1, final double valp2)
int index (final int i, final int j, final int k)
double value (final int i, final int j, final int k)
Private Attributes
int[] digits = new int[8]
int[][] entries
WB_IsoValues3D values
int resx
double cx
double dx
double isolevel
double boundary
IntObjectHashMap< WB_Point > xedges
IntObjectHashMap< WB_Point > yedges
IntObjectHashMap< WB_Point > zedges
IntObjectHashMap< WB_Point > vertices
IntObjectHashMap< VertexRemap > vertexremaps
IntDoubleHashMap valueremaps
double gamma
boolean invert
FastList< WB_Triangle > tris
Constructor & Destructor Documentation
wblut.geom.WB_IsoSurface.WB_IsoSurface ()
Member Function Documentation
int wblut.geom.WB_IsoSurface.classifyCell (final int i, final int j, final int k) private
Classify cell.
Parameters
i the i
j the j
k the k
Returns
the int
References wblut.geom.WB_IsoSurface.isolevel, and wblut.geom.WB_IsoSurface.value().
WB_IsoSurface wblut.geom.WB_IsoSurface.clearBoundary ()
Clear boundary level.
Returns
self
WB_Point wblut.geom.WB_IsoSurface.getIsoVertex (final int isopointindex, final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun) private
Parameters
isopointindex
i
j
k
offset
dummyrun
Returns
References wblut.geom.WB_IsoSurface.vertex(), wblut.geom.WB_IsoSurface.xedge(), wblut.geom.WB_IsoSurface.yedge(), and wblut.geom.WB_IsoSurface.zedge().
List<WB_Triangle> wblut.geom.WB_IsoSurface.getPolygons (final int i, final int j, final int k, final int cubeindex, final WB_Point offset, final boolean dummyrun) private
Gets the polygons.
Parameters
i the i
j the j
k the k
cubeindex the cubeindex
offset
dummyrun
Returns
the polygons
References wblut.geom.WB_IsoSurface.getIsoVertex(), and wblut.geom.WB_IsoSurface.tris.
List<WB_Triangle> wblut.geom.WB_IsoSurface.getTriangles ()
References wblut.geom.WB_IsoSurface.mapvertices(), wblut.geom.WB_IsoSurface.polygonise(), wblut.geom.WB_IsoSurface.setvalues(), wblut.geom.WB_IsoSurface.snapvertices(), and wblut.geom.WB_IsoSurface.tris.
int wblut.geom.WB_IsoSurface.index (final int i, final int j, final int k) private
Parameters
i
j
k
Returns
WB_Point wblut.geom.WB_IsoSurface.interp (final double isolevel, final WB_Point p1, final WB_Point p2, final double valp1, final double valp2) private
Interp.
Parameters
isolevel the isolevel
p1 the p1
p2 the p2
valp1 the valp1
valp2 the valp2
Returns
the h e_ vertex
References wblut.math.WB_Epsilon.isEqualAbs(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_MutableCoordinate.yd(), and wblut.geom.WB_MutableCoordinate.zd().
void wblut.geom.WB_IsoSurface.mapvertices () private
References wblut.geom.WB_IsoSurface.classifyCell(), wblut.geom.WB_IsoSurface.getPolygons(), and wblut.geom.WB_IsoSurface.resx.
void wblut.geom.WB_IsoSurface.polygonise () private
Polygonise.
References wblut.geom.WB_IsoSurface.classifyCell(), wblut.geom.WB_IsoSurface.getPolygons(), and wblut.geom.WB_IsoSurface.resx.
WB_IsoSurface wblut.geom.WB_IsoSurface.setBoundary (final double v)
Boundary level.
Parameters
v boundary level
Returns
self
WB_IsoSurface wblut.geom.WB_IsoSurface.setCenter (final WB_Coord c)
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_IsoSurface wblut.geom.WB_IsoSurface.setGamma (final double gamma)
Parameters
gamma
Returns
References wblut.geom.WB_IsoSurface.gamma.
WB_IsoSurface wblut.geom.WB_IsoSurface.setInvert (final boolean invert)
Invert isosurface.
Parameters
invert true/false
Returns
self
References wblut.geom.WB_IsoSurface.invert.
WB_IsoSurface wblut.geom.WB_IsoSurface.setIsolevel (final double v)
Isolevel to render.
Parameters
v isolevel
Returns
self
WB_IsoSurface wblut.geom.WB_IsoSurface.setResolution (final int resx, final int resy, final int resz)
Number of cells.
Parameters
resx the resx
resy the resy
resz the resz
Returns
self
References wblut.geom.WB_IsoSurface.resx.
WB_IsoSurface wblut.geom.WB_IsoSurface.setSize (final double dx, final double dy, final double dz)
Size of cell.
Parameters
dx
dy
dz
Returns
self
References wblut.geom.WB_IsoSurface.dx.
WB_IsoSurface wblut.geom.WB_IsoSurface.setValues (final double values[][][])
Values at grid points.
Parameters
values double[resx+1][resy+1][resz+1]
Returns
self
WB_IsoSurface wblut.geom.WB_IsoSurface.setValues (final float values[][][])
Sets the values.
Parameters
values float[resx+1][resy+1][resz+1]
Returns
self
WB_IsoSurface wblut.geom.WB_IsoSurface.setValues (final WB_ScalarParameter function, final double xi, final double yi, final double zi, final double dx, final double dy, final double dz, final int sizeI, final int sizeJ, final int sizeK)
Parameters
function
xi
yi
zi
dx
dy
dz
Returns
WB_IsoSurface wblut.geom.WB_IsoSurface.setValues (final WB_HashGridDouble values)
Parameters
values
Returns
References wblut.geom.WB_HashGridDouble.getSizeI(), wblut.geom.WB_HashGridDouble.getSizeJ(), and wblut.geom.WB_HashGridDouble.getSizeK().
WB_IsoSurface wblut.geom.WB_IsoSurface.setValues (final String[] images, final PApplet home, final int sizeI, final int sizeJ, final int sizeK)
Parameters
images
home
sizeI
sizeJ
sizeK
Returns
References wblut.geom.WB_IsoValues3D.getSizeI(), wblut.geom.WB_IsoValues3D.getSizeJ(), and wblut.geom.WB_IsoValues3D.getSizeK().
WB_IsoSurface wblut.geom.WB_IsoSurface.setValues (final String[] images, final PApplet home, final int sizeI, final int sizeJ, final int sizeK, final WB_IsoValues3D.Mode mode)
Parameters
images
home
sizeI
sizeJ
sizeK
mode
Returns
References wblut.geom.WB_IsoValues3D.getSizeI(), wblut.geom.WB_IsoValues3D.getSizeJ(), and wblut.geom.WB_IsoValues3D.getSizeK().
WB_IsoSurface wblut.geom.WB_IsoSurface.setValues (final WB_IsoValues3D values)
References wblut.geom.WB_IsoValues3D.getSizeI(), wblut.geom.WB_IsoValues3D.getSizeJ(), wblut.geom.WB_IsoValues3D.getSizeK(), and wblut.geom.WB_IsoSurface.values.
void wblut.geom.WB_IsoSurface.setvalues () private
References wblut.geom.WB_IsoSurface.index().
void wblut.geom.WB_IsoSurface.snapvertices () private
double wblut.geom.WB_IsoSurface.value (final int i, final int j, final int k) private
Value.
Parameters
i the i
j the j
k the k
Returns
the double
References wblut.geom.WB_IsoSurface.boundary, wblut.geom.WB_IsoValues3D.getValue(), wblut.geom.WB_IsoSurface.index(), and wblut.geom.WB_IsoSurface.isolevel.
WB_Point wblut.geom.WB_IsoSurface.vertex (final int i, final int j, final int k, final WB_Point offset) private
Parameters
i
j
k
offset
Returns
References wblut.geom.WB_Point.addSelf(), and wblut.geom.WB_IsoSurface.index().
WB_Point wblut.geom.WB_IsoSurface.xedge (final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun) private
Xedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
k k: -1 .. resz+1
offset
dummyrun
Returns
edge vertex
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_IsoSurface.dx, wblut.geom.WB_IsoSurface.index(), wblut.geom.WB_IsoSurface.interp(), wblut.geom.WB_IsoSurface.value(), and wblut.geom.WB_IsoSurface.vertex().
WB_Point wblut.geom.WB_IsoSurface.yedge (final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun) private
Yedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
k k: -1 .. resz+1
offset
dummyrun
Returns
edge vertex
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_IsoSurface.index(), wblut.geom.WB_IsoSurface.interp(), wblut.geom.WB_IsoSurface.value(), and wblut.geom.WB_IsoSurface.vertex().
WB_Point wblut.geom.WB_IsoSurface.zedge (final int i, final int j, final int k, final WB_Point offset, final boolean dummyrun) private
Zedge.
Parameters
i i: -1 .. resx+1
j j: -1 .. resy+1
k k: -1 .. resz+1
offset
dummyrun
Returns
edge vertex
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_IsoSurface.index(), wblut.geom.WB_IsoSurface.interp(), wblut.geom.WB_IsoSurface.value(), and wblut.geom.WB_IsoSurface.vertex().
Member Data Documentation
double wblut.geom.WB_IsoSurface.boundary private
double wblut.geom.WB_IsoSurface.cx private
int [] wblut.geom.WB_IsoSurface.digits = new int[8] private
double wblut.geom.WB_IsoSurface.dx private
int [][] wblut.geom.WB_IsoSurface.entries private
double wblut.geom.WB_IsoSurface.gamma private
boolean wblut.geom.WB_IsoSurface.invert private
double wblut.geom.WB_IsoSurface.isolevel private
int wblut.geom.WB_IsoSurface.resx private
FastList<WB_Triangle> wblut.geom.WB_IsoSurface.tris private
IntDoubleHashMap wblut.geom.WB_IsoSurface.valueremaps private
WB_IsoValues3D wblut.geom.WB_IsoSurface.values private
IntObjectHashMap<VertexRemap> wblut.geom.WB_IsoSurface.vertexremaps private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurface.vertices private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurface.xedges private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurface.yedges private
IntObjectHashMap<WB_Point> wblut.geom.WB_IsoSurface.zedges private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_IsoSurface.java