HE_Mesh: wblut.hemesh.HEM_Shell Class Reference
wblut.hemesh.HEM_Shell Class Reference
Public Member Functions
HEM_Shell ()
HEM_Shell setThickness (final double d)
HEM_Shell setThickness (final WB_ScalarParameter d)
HEM_Shell setUseFaceExpand (final boolean b)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_ScalarParameter d
boolean useFace
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Detailed Description
Turns a solid into a rudimentary shelled structure.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEM_Shell.HEM_Shell ()
References wblut.math.WB_ScalarParameter.ZERO.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_Shell.applySelf (final HE_Mesh mesh) protected
References wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HEC_Creator.create(), wblut.hemesh.HET_MeshOp.flipFaces(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Mesh.getHalfedgeWithKey(), wblut.hemesh.HE_Mesh.getNewSelection(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Vertex.getUVW(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HEC_Copy.halfedgeCorrelation, wblut.hemesh.HE_Halfedge.isOuterBoundary(), wblut.hemesh.HE_Mesh.modify(), wblut.hemesh.HE_Mesh.pairHalfedges(), wblut.hemesh.HE_Mesh.selectAllFaces(), wblut.hemesh.HEM_VertexExpand.setDistance(), wblut.hemesh.HEM_FaceExpand.setDistance(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.hemesh.HE_Element.setInternalLabel(), wblut.hemesh.HEC_Copy.setMesh(), wblut.hemesh.HE_Mesh.setNext(), wblut.hemesh.HE_Halfedge.setUVW(), wblut.hemesh.HE_Mesh.setVertex(), and wblut.math.WB_ScalarParameter.ZERO.
HE_Mesh wblut.hemesh.HEM_Shell.applySelf (final HE_Selection selection) protected
References wblut.hemesh.HEM_Shell.applySelf().
HEM_Shell wblut.hemesh.HEM_Shell.setThickness (final double d)
Parameters
d
Returns
References wblut.math.WB_ScalarParameter.ZERO.
HEM_Shell wblut.hemesh.HEM_Shell.setThickness (final WB_ScalarParameter d)
Parameters
d
Returns
References wblut.hemesh.HEM_Shell.d.
HEM_Shell wblut.hemesh.HEM_Shell.setUseFaceExpand (final boolean b)
Parameters
b
Returns
Member Data Documentation
WB_ScalarParameter wblut.hemesh.HEM_Shell.d private
boolean wblut.hemesh.HEM_Shell.useFace private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_Shell.java