HE_Mesh: wblut.geom.WB_GeometryFactory2D Class Reference
wblut.geom.WB_GeometryFactory2D Class Reference
Public Member Functions
WB_GeometryFactory2D ()
WB_CoordinateSystem3D WORLD ()
WB_Coord origin2D ()
WB_Coord X2D ()
WB_Coord Y2D ()
WB_Coord minX2D ()
WB_Coord minY2D ()
WB_CoordinateSystem3D createCSFromOX2D (final WB_Coord origin, final WB_Coord X)
WB_CoordinateSystem3D createCSFromOX2D (final WB_Coord origin, final WB_Coord X, final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D createCSFromOXY2D (final WB_Coord origin, final WB_Coord X, final WB_Coord Y)
WB_CoordinateSystem3D createCSFromOXY2D (final WB_Coord origin, final WB_Coord X, final WB_Coord Y, final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D createTransformedCS (final WB_CoordinateSystem3D CS, final WB_Transform T, final WB_CoordinateSystem3D parent)
WB_CoordinateSystem3D createTransformedCS (final WB_CoordinateSystem3D CS, final WB_Transform T)
WB_Point createPoint2D ()
WB_Point createPoint2D (final WB_Coord p)
WB_Point createPoint2D (final double x, final double y)
WB_Point createPoint2D (final Coordinate coord)
WB_Point createInterpolatedPoint2D (final WB_Coord p, final WB_Coord q, final double f)
WB_Point createPointFromPolar (final double r, final double phi)
WB_Point createPointFromBipolar (final double a, final double sigma, final double tau)
WB_Point createPointFromParabolic (final double sigma, final double tau)
WB_Point createPointFromHyperbolic (final double u, final double v)
WB_Point createPointFromElliptic (final double a, final double sigma, final double tau)
WB_Point createIncenter2D (final WB_Triangle tri)
WB_Point createClosestPointOnLine2D (final WB_Coord p, final WB_Line L)
List< WB_Point > createClosestPoint (final WB_Line L1, final WB_Line L2)
List< WB_Point > createIntersectionPoints2D (final WB_Circle C0, final WB_Circle C1)
List< WB_Point > createIntersectionPoints2D (final WB_Line L, final WB_Circle C)
WB_Point createIntersectionPoint2D (final WB_Line L1, final WB_Line L2)
WB_Point createMirrorPoint2D (final WB_Coord p, final double x0, final double y0, final double x1, final double y1)
WB_Point createMirrorPoint2D (final WB_Coord p, final WB_Line L)
WB_Point createPointFromBarycentricCoordinates2D (final double u, final double v, final double w, final WB_Triangle tri)
WB_Point createInversionPoint2D (final WB_Coord p, final WB_Circle inversionCircle)
WB_Point createCentroid2D (final WB_Triangle tri)
WB_Point createCentroid2D (final WB_Coord...points)
WB_Point createCircumcenter2D (final WB_Triangle tri)
WB_Point createOrthocenter2D (final WB_Triangle tri)
WB_Point createPointFromTrilinearCoordinates2D (final double u, final double v, final double w, final WB_Triangle tri)
WB_Point createMidpoint2D (final WB_Coord p, final WB_Coord q)
WB_Point createMidpoint2D (final WB_Coord...p)
WB_Vector createVector2D ()
WB_Vector createVectorFromTo2D (final WB_Coord p, final WB_Coord q)
WB_Vector createVector2D (final WB_Coord p)
WB_Vector createVector2D (final double _x, final double _y)
WB_Vector createNormalizedVector2D (final WB_Coord p)
WB_Vector createNormalizedVectorFromTo2D (final WB_Coord p, final WB_Coord q)
WB_Vector createNormalizedVector2D (final double _x, final double _y)
WB_Vector createNormalizedPerpendicularVector2D (final double _x, final double _y)
WB_Vector createNormalizedPerpendicularVector2D (final WB_Coord v)
WB_Vector createVectorFromPolar (final double r, final double phi)
WB_Vector createVectorFromBipolar (final double a, final double sigma, final double tau)
WB_Vector createVectorFromParabolic (final double sigma, final double tau)
WB_Vector createVectorFromHyperbolic (final double u, final double v)
WB_Vector createVectorFromElliptic (final double a, final double mu, final double nu)
WB_Line createLineThroughPoints2D (final WB_Coord p1, final WB_Coord p2)
WB_Line createLineThroughPoints2D (final double x1, final double y1, final double x2, final double y2)
WB_Line createLineWithDirection2D (final WB_Coord origin, final WB_Coord direction)
WB_Line createLineWithDirection2D (final double ox, final double oy, final double dx, final double dy)
WB_Line createParallelLineThroughPoint2D (final WB_Line L, final WB_Coord p)
WB_Line createPerpendicularLineThroughPoint2D (final WB_Line L, final WB_Coord p)
List< WB_Line > createParallelLines2D (final WB_Line L, final double d)
WB_Line createBisector2D (final WB_Coord p, final WB_Coord q)
List< WB_Line > createAngleBisector2D (final WB_Line L1, final WB_Line L2)
WB_Line createLineTangentToCircleInPoint (final WB_Circle C, final WB_Coord p)
List< WB_Line > createLinesTangentToCircleThroughPoint (final WB_Circle C, final WB_Coord p)
List< WB_Line > createLinesTangentTo2Circles (final WB_Circle C0, final WB_Circle C1)
List< WB_Line > createPerpendicularLinesTangentToCircle (final WB_Line L, final WB_Circle C)
WB_Ray createRayThroughPoints2D (final WB_Coord p1, final WB_Coord p2)
WB_Ray createRayThroughPoints2D (final double x1, final double y1, final double x2, final double y2)
WB_Ray createRayWithDirection2D (final WB_Coord origin, final WB_Coord direction)
WB_Ray createRayWithDirection2D (final double ox, final double oy, final double dx, final double dy)
WB_Ray createParallelRayThroughPoint2D (final WB_Line L, final WB_Coord p)
WB_Segment createSegment2D (final WB_Coord p1, final WB_Coord p2)
WB_Segment createSegmentWithLength2D (final WB_Coord origin, final WB_Coord direction, final double length)
WB_Segment createSegment2D (final double x1, final double y1, final double x2, final double y2)
WB_Segment createSegmentWithLength2D (final double ox, final double oy, final double dx, final double dy, final double length)
WB_PolyLine createPolyLine (final WB_Coord[] points)
WB_PolyLine createPolyLine (final Collection<?extends WB_Coord > points)
WB_Ring createRing (final WB_Coord[] points)
WB_Ring createRing (final List<?extends WB_Coord > points)
WB_Polygon createSimplePolygon (final WB_Coord...points)
WB_Polygon createSimplePolygon (final WB_CoordCollection points)
WB_Polygon createSimplePolygon (final WB_Polygon poly)
WB_Polygon createSimplePolygon (final Collection<?extends WB_Coord > points)
WB_Polygon createSimplePolygon (final WB_Triangle triangle)
WB_Polygon createSimplePolygon (final WB_Quad quad)
WB_Polygon createSimplePolygon (final WB_Pentagon pentagon)
WB_Polygon createSimplePolygon (final WB_Hexagon hexagon)
WB_Polygon createSimplePolygon (final WB_Octagon octagon)
WB_Polygon createSimplePolygon (final List<?extends WB_Coord > tuples, final int[] indices)
WB_Polygon createPolygonWithHole (final WB_Coord[] points, final WB_Coord[] innerpoints)
WB_Polygon createPolygonWithHole (final Collection<?extends WB_Coord > points, final Collection<?extends WB_Coord > innerpoints)
WB_Polygon createPolygonWithHoles (final WB_Coord[] points, final WB_Coord[][] innerpoints)
WB_Polygon createPolygonWithHoles (final Collection<?extends WB_Coord > points, final List<?extends WB_Coord >[] innerpoints)
WB_Polygon createPolygonFromJTSPolygon2D (final Polygon JTSpoly)
WB_Polygon createPolygonConvexHull2D (final WB_Polygon poly)
List< WB_Polygon > createConvexPolygonDecomposition2D (final WB_Polygon poly)
List< WB_Polygon > createBufferedPolygons2D (final WB_Polygon poly, final double d)
List< WB_Polygon > createBufferedPolygons2D (final Collection<?extends WB_Polygon > poly, final double d)
List< WB_Polygon > createBufferedPolygons2D (final WB_Polygon poly, final double d, final int n)
List< WB_Polygon > createBufferedPolygonsStraight2D (final WB_Polygon poly, final double d)
List< WB_Polygon > createBufferedPolygons2D (final Collection<?extends WB_Polygon > poly, final double d, final int n)
List< WB_Polygon > createBufferedPolygonsStraight2D (final Collection<?extends WB_Polygon > poly, final double d)
List< WB_Polygon > createBoundaryPolygons2D (final WB_Polygon poly)
List< WB_Polygon > createBoundaryPolygons2D (final Collection<?extends WB_Polygon > poly)
List< WB_Polygon > createRibbonPolygons2D (final WB_Polygon poly, final double d)
List< WB_Polygon > createRibbonPolygons2D (final Collection<?extends WB_Polygon > poly, final double d)
List< WB_Polygon > createRibbonPolygons2D (final WB_Polygon poly, final double o, final double i)
List< WB_Polygon > createRibbonPolygons2D (final Collection<?extends WB_Polygon > poly, final double o, final double i)
List< WB_Polygon > createSimplifiedPolygon2D (final WB_Polygon poly, final double tol)
List< WB_Polygon > createDensifiedPolygon2D (final WB_Polygon poly, final double max)
List< WB_Polygon > unionPolygons2D (final WB_Polygon poly1, final WB_Polygon poly2)
List< WB_Polygon > unionPolygons2D (final WB_Polygon poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > unionPolygons2D (final Collection<?extends WB_Polygon > poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > subtractPolygons2D (final WB_Polygon poly1, final WB_Polygon poly2)
List< WB_Polygon > subtractPolygons2D (final WB_Polygon poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > subtractPolygons2D (final Collection<?extends WB_Polygon > poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > subtractPolygons2D (final Collection<?extends WB_Polygon > poly1, final WB_Polygon poly2)
List< WB_Polygon > intersectPolygons2D (final WB_Polygon poly1, final WB_Polygon poly2)
List< WB_Polygon > intersectPolygons2D (final WB_Polygon poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > intersectPolygons2D (final Collection<?extends WB_Polygon > poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > symDifferencePolygons2D (final WB_Polygon poly1, final WB_Polygon poly2)
List< WB_Polygon > symDifferencePolygons2D (final WB_Polygon poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > symDifferencePolygons2D (final Collection<?extends WB_Polygon > poly1, final Collection<?extends WB_Polygon > poly2)
List< WB_Polygon > constrainPolygons2D (final WB_Polygon poly, final WB_Polygon container)
List< WB_Polygon > constrainPolygons2D (final WB_Polygon[] polygons, final WB_Polygon container)
List< WB_Polygon > constrainPolygons2D (final List< WB_Polygon > polygons, final WB_Polygon container)
List< WB_Polygon > createTextWithTrueTypeFont (final String text, final String fontName, final float pointSize)
List< WB_Polygon > createTextWithTrueTypeFont (final String text, final String fontName, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithTrueTypeFont (final String text, final String fontName, final int style, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithFont (final String text, final String fontName, final float pointSize)
List< WB_Polygon > createTextWithFont (final String text, final String fontName, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithFont (final String text, final String fontName, final int style, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithOpenTypeFont (final String text, final String fontName, final float pointSize)
List< WB_Polygon > createTextWithOpenTypeFont (final String text, final String fontName, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithOpenTypeFont (final String text, final String fontName, final int style, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithType1Font (final String text, final String fontName, final float pointSize)
List< WB_Polygon > createTextWithType1Font (final String text, final String fontName, final float pointSize, final double flatness)
List< WB_Polygon > createTextWithType1Font (final String text, final String fontName, final int style, final float pointSize, final double flatness)
List< WB_Polygon > createText (final String text, final String fontName, final float pointSize)
List< WB_Polygon > createText (final String text, final String fontName, final float pointSize, final double flatness)
List< WB_Polygon > createText (final String text, final String fontName, final int style, final float pointSize, final double flatness)
List< WB_Polygon > createText (final String text, final Font font, final int style, final float pointSize, final double flatness)
List< WB_Polygon > createText (final String text, final Font font, final double flatness)
List< WB_Polygon > createShape (final Shape shape, final double flatness)
WB_Triangle createTriangle2D (final double p1x, final double p1y, final double p2x, final double p2y, final double p3x, final double p3y)
WB_Triangle createTriangle2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
WB_Circle createCircleWithDiameter (final WB_Coord center, final WB_Coord normal, final double diameter)
WB_Circle createCircleWithRadius (final WB_Coord center, final WB_Coord normal, final double radius)
WB_Circle createCircleWithRadius (final WB_Coord center, final double radius)
WB_Circle createCircleWithDiameter (final WB_Coord center, final double diameter)
WB_Circle createCircleWithRadius (final double x, final double y, final double radius)
WB_Circle createCircleWithDiameter (final double x, final double y, final double diameter)
WB_Circle createInversionCircle2D (final WB_Circle C, final WB_Circle inversionCircle)
WB_Circle createCircumcircle2D (final WB_Triangle tri)
WB_Circle createIncircle2D (final WB_Triangle tri)
WB_Circle createCirclePPP (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2)
List< WB_Circle > createCirclePPL (final WB_Coord p, final WB_Coord q, final WB_Line L)
List< WB_Circle > createCirclePLL (final WB_Coord p, final WB_Line L1, final WB_Line L2)
List< WB_Circle > createCirclePPC (final WB_Coord p, final WB_Coord q, final WB_Circle C)
List< WB_Circle > createCirclePCC (final WB_Coord p, final WB_Circle C1, final WB_Circle C2)
List< WB_Circle > createCirclePLC (final WB_Coord p, final WB_Line L, final WB_Circle C)
List< WB_Circle > createCircleLLL (final WB_Line L1, final WB_Line L2, final WB_Line L3)
List< WB_Circle > createCircleLLC (final WB_Line L1, final WB_Line L2, final WB_Circle C)
List< WB_Circle > createCircleLCC (final WB_Line L, final WB_Circle C1, final WB_Circle C2)
List< WB_Circle > createCircleCCC (WB_Circle C1, WB_Circle C2, WB_Circle C3)
List< WB_Circle > createCircleThrough2Points (final WB_Coord p0, final WB_Coord p1, final double r)
List< WB_Circle > createCircleTangentToLineThroughPoint (final WB_Line L, final WB_Coord p, final double r)
List< WB_Circle > createCircleTangentTo2Lines (final WB_Line L0, final WB_Line L1, final double r)
List< WB_Circle > createCircleTangentToCircleThroughPoint (final WB_Circle C, final WB_Coord p, final double r)
List< WB_Circle > createCircleTangentToLineAndCircle (final WB_Line L, final WB_Circle C, final double r)
List< WB_Circle > createCircleTangentTo2CirclesNonCollinear (final WB_Circle C0, final WB_Circle C1, final double r)
List< WB_Circle > createCircleTangentTo2CirclesCollinear (final WB_Circle C0, final WB_Circle C1)
List< WB_Circle > createCircleTangentTo2Circles (final WB_Circle C0, final WB_Circle C1, final double r)
WB_Point createClosestPointOnTriangle2D (final WB_Coord p, final WB_Coord a, final WB_Coord b, final WB_Coord c)
WB_Point createClosestPointOnPolygon2D (final WB_Coord p, final WB_Polygon poly)
List< WB_Coord > createUniquePoints2D (final List< WB_Coord > points, final double threshold)
Static Public Member Functions
static WB_GeometryFactory2D instance ()
Private Member Functions
List< WB_Vector > getDirections2D (final WB_Coord w, final double a)
List< WB_Polygon > createPolygonsFromJTSGeometry2D (final Geometry geometry)
double[] toDouble (final WB_Coord p)
List< WB_Circle > uniqueOnly (final List< WB_Circle > circles)
Private Attributes
final GeometryFactory JTSgf = new GeometryFactory()
WB_ShapeReader shapereader
Constructor & Destructor Documentation
wblut.geom.WB_GeometryFactory2D.WB_GeometryFactory2D ()
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), and wblut.geom.WB_GeometryFactory2D.createVector2D().
Member Function Documentation
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.constrainPolygons2D (final WB_Polygon poly, final WB_Polygon container)
Parameters
poly
container
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.constrainPolygons2D (final WB_Polygon[] polygons, final WB_Polygon container)
Parameters
polygons
container
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.constrainPolygons2D (final List< WB_Polygon > polygons, final WB_Polygon container)
Parameters
polygons
container
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Line> wblut.geom.WB_GeometryFactory2D.createAngleBisector2D (final WB_Line L1, final WB_Line L2)
Get the 2D angle bisectors of two 2D lines.
Parameters
L1 2D line
L2 2D line
Returns
2D angle bisector
References wblut.geom.WB_Vector.add(), wblut.geom.WB_Point.add(), wblut.geom.WB_Point.addMul(), wblut.geom.WB_GeometryFactory2D.createClosestPointOnLine2D(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoint2D(), wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Vector.dot(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Point.mulAddMul(), wblut.geom.WB_Point.sub(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
WB_Line wblut.geom.WB_GeometryFactory2D.createBisector2D (final WB_Coord p, final WB_Coord q)
Get the 2D bisector of two 2D points. The points should be distinct.
Parameters
p 2D point
q 2D point
Returns
2D bisector
References wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createBoundaryPolygons2D (final WB_Polygon poly)
Parameters
poly
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createBoundaryPolygons2D (final Collection<?extends WB_Polygon > poly)
Parameters
poly
Returns
References wblut.geom.WB_GeometryFactory2D.createBoundaryPolygons2D(), and wblut.geom.WB_GeometryFactory2D.unionPolygons2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createBufferedPolygons2D (final WB_Polygon poly, final double d)
Parameters
poly
d
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createBufferedPolygons2D (final Collection<?extends WB_Polygon > poly, final double d)
Parameters
poly
d
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createBufferedPolygons2D (final WB_Polygon poly, final double d, final int n)
Parameters
poly
d
n
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createBufferedPolygons2D (final Collection<?extends WB_Polygon > poly, final double d, final int n)
Parameters
poly
d
n
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createBufferedPolygonsStraight2D (final WB_Polygon poly, final double d)
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createBufferedPolygonsStraight2D (final Collection<?extends WB_Polygon > poly, final double d)
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
WB_Point wblut.geom.WB_GeometryFactory2D.createCentroid2D (final WB_Triangle tri)
Centroid of triangle.
Parameters
tri triangle
Returns
centroid
References wblut.geom.WB_Triangle.a, wblut.geom.WB_Triangle.b, wblut.geom.WB_Triangle.c, and wblut.geom.WB_GeometryFactory2D.createPointFromTrilinearCoordinates2D().
WB_Point wblut.geom.WB_GeometryFactory2D.createCentroid2D (final WB_Coord... points)
References wblut.geom.WB_Point.addSelf(), and wblut.geom.WB_Point.divSelf().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCircleCCC (WB_Circle C1, WB_Circle C2, WB_Circle C3)
Parameters
C1
C2
C3
Returns
References wblut.geom.WB_GeometryFactory2D.createCirclePCC(), wblut.geom.WB_GeometryFactory2D.createCirclePPC(), wblut.geom.WB_GeometryFactory2D.createCirclePPP(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_Circle.equals(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_GeometryOp2D.isTangent2D(), and wblut.geom.WB_GeometryFactory2D.uniqueOnly().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCircleLCC (final WB_Line L, final WB_Circle C1, final WB_Circle C2)
Gets circles tangent to 2D line and two circles.
Parameters
L line
C1 circle
C2 circle
Returns
circles tangent to 2D line and two circles
References wblut.geom.WB_Vector.addMul(), wblut.geom.WB_GeometryFactory2D.createCirclePLC(), wblut.geom.WB_GeometryFactory2D.createCirclePPL(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_GeometryOp2D.getDistanceToLine2D(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_GeometryOp2D.isTangent2D(), wblut.geom.WB_GeometryFactory2D.uniqueOnly(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCircleLLC (final WB_Line L1, final WB_Line L2, final WB_Circle C)
Gets circles tangent to 2 2D lines and a circle.
Parameters
L1 line
L2 line
C circle
Returns
circles tangent to 2 2D lines through point
References wblut.geom.WB_GeometryFactory2D.createAngleBisector2D(), wblut.geom.WB_GeometryFactory2D.createCirclePLL(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoint2D(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoints2D(), wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_GeometryOp2D.getDistanceToLine2D(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Circle.getRadius(), wblut.math.WB_Epsilon.isEqualAbs(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_GeometryFactory2D.uniqueOnly(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCircleLLL (final WB_Line L1, final WB_Line L2, final WB_Line L3)
Gets the circle tangent to 3 2D lines.
Parameters
L1
L2
L3
Returns
circle tangent to 3 lines
References wblut.geom.WB_Point.add(), wblut.geom.WB_GeometryFactory2D.createAngleBisector2D(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createClosestPointOnLine2D(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoint2D(), and wblut.geom.WB_GeometryFactory2D.uniqueOnly().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCirclePCC (final WB_Coord p, final WB_Circle C1, final WB_Circle C2)
http://www.cut-the-knot.org/Curriculum/Geometry/GeoGebra/PCC.shtml# solution
Parameters
p
C1
C2
Returns
circles through point and tangent to two circles
References wblut.geom.WB_Point.addMul(), wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_GeometryOp2D.classifyCircleToCircle2D(), wblut.geom.WB_GeometryOp2D.classifyPointToCircle2D(), wblut.geom.WB_Classification.CONTAINING, wblut.geom.WB_GeometryFactory2D.createCircleLCC(), wblut.geom.WB_GeometryFactory2D.createCirclePLC(), wblut.geom.WB_GeometryFactory2D.createCirclePPC(), wblut.geom.WB_GeometryFactory2D.createCirclePPP(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createClosestPointOnLine2D(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoint2D(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoints2D(), wblut.geom.WB_GeometryFactory2D.createInversionCircle2D(), wblut.geom.WB_GeometryFactory2D.createInversionPoint2D(), wblut.geom.WB_GeometryFactory2D.createLinesTangentTo2Circles(), wblut.geom.WB_GeometryFactory2D.createLineTangentToCircleInPoint(), wblut.geom.WB_GeometryFactory2D.createLineThroughPoints2D(), wblut.geom.WB_GeometryFactory2D.createNormalizedVectorFromTo2D(), wblut.geom.WB_GeometryFactory2D.createParallelLineThroughPoint2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_Classification.CROSSING, wblut.geom.WB_Circle.equals(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_GeometryOp2D.getDistance2D(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Classification.INSIDE, wblut.geom.WB_GeometryOp2D.isTangent2D(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Classification.ON, wblut.geom.WB_Classification.OUTSIDE, wblut.geom.WB_GeometryFactory2D.uniqueOnly(), and wblut.geom.WB_GeometryFactory2D.X2D().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCirclePLC (final WB_Coord p, final WB_Line L, final WB_Circle C)
Gets circles through a 2D point tangent to a circle and a 2D line. http://www.epab.bme.hu/geoc2/GC2_Lecture_notes_11_Spring.pdf
Parameters
p 2D point
L 2D line
C circle
Returns
circles through a 2D point tangent to circle and 2D line
References wblut.geom.WB_Point.add(), wblut.geom.WB_Point.addMul(), wblut.geom.WB_GeometryOp2D.classifyCircleToLine2D(), wblut.geom.WB_GeometryOp2D.classifyPointToCircle2D(), wblut.geom.WB_GeometryOp2D.classifyPointToLine2D(), wblut.geom.WB_GeometryFactory2D.createBisector2D(), wblut.geom.WB_GeometryFactory2D.createCirclePLL(), wblut.geom.WB_GeometryFactory2D.createCirclePPL(), wblut.geom.WB_GeometryFactory2D.createCirclePPP(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createClosestPointOnLine2D(), wblut.geom.WB_GeometryFactory2D.createInterpolatedPoint2D(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoint2D(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoints2D(), wblut.geom.WB_GeometryFactory2D.createInversionPoint2D(), wblut.geom.WB_GeometryFactory2D.createLinesTangentTo2Circles(), wblut.geom.WB_GeometryFactory2D.createLineTangentToCircleInPoint(), wblut.geom.WB_GeometryFactory2D.createLineThroughPoints2D(), wblut.geom.WB_GeometryFactory2D.createPerpendicularLineThroughPoint2D(), wblut.geom.WB_Circle.equals(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Vector.getDistance2D(), wblut.geom.WB_GeometryOp2D.getDistanceToLine2D(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Line.getPoint(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Classification.INSIDE, wblut.geom.WB_Vector.isCollinear(), wblut.math.WB_Epsilon.isZero(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Classification.ON, wblut.geom.WB_Classification.TANGENT, wblut.geom.WB_GeometryFactory2D.uniqueOnly(), wblut.geom.WB_GeometryFactory2D.X2D(), and wblut.geom.WB_GeometryFactory2D.Y2D().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCirclePLL (final WB_Coord p, final WB_Line L1, final WB_Line L2)
Gets circles tangent to 2 2D lines through point. http://www.cut-the-knot.org/Curriculum/Geometry/GeoGebra/PLL.shtml
Parameters
p point
L1 line
L2 line
Returns
circles tangent to 2 2D lines through point
References wblut.geom.WB_Point.add(), wblut.geom.WB_GeometryFactory2D.createAngleBisector2D(), wblut.geom.WB_GeometryFactory2D.createCircleTangentTo2Lines(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoint2D(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoints2D(), wblut.geom.WB_GeometryFactory2D.createLineThroughPoints2D(), wblut.geom.WB_GeometryFactory2D.createNormalizedVector2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_Vector.getDistance2D(), wblut.geom.WB_GeometryOp2D.getDistanceToLine2D(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_GeometryOp2D.sameSideOfLine2D(), wblut.geom.WB_Point.sub(), and wblut.geom.WB_GeometryFactory2D.uniqueOnly().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCirclePPC (final WB_Coord p, final WB_Coord q, final WB_Circle C)
Gets circles through two 2d points tangent to circle. http://mathafou.free.fr/pbg_en/sol136.html
Parameters
p 2D point
q 2D point
C circle
Returns
circles through two 2d points tangent to circle
References wblut.geom.WB_Point.addMul(), wblut.geom.WB_GeometryOp2D.classifyPointToCircle2D(), wblut.geom.WB_GeometryFactory2D.createBisector2D(), wblut.geom.WB_GeometryFactory2D.createCirclePPP(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createClosestPointOnLine2D(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoint2D(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoints2D(), wblut.geom.WB_GeometryFactory2D.createInversionPoint2D(), wblut.geom.WB_GeometryFactory2D.createLinesTangentToCircleThroughPoint(), wblut.geom.WB_GeometryFactory2D.createLineThroughPoints2D(), wblut.geom.WB_GeometryFactory2D.createNormalizedVector2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Vector.getDistance2D(), wblut.geom.WB_GeometryOp2D.getDistance2D(), wblut.geom.WB_GeometryOp2D.getDistanceToPoint2D(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Line.getPoint(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), wblut.geom.WB_Vector.isCollinear(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Classification.ON, wblut.geom.WB_Classification.OUTSIDE, wblut.geom.WB_GeometryFactory2D.uniqueOnly(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCirclePPL (final WB_Coord p, final WB_Coord q, final WB_Line L)
http://www.cut-the-knot.org/Curriculum/Geometry/GeoGebra/PPL.shtml
Parameters
p
q
L
Returns
circles through 2 points and tangent to line
References wblut.geom.WB_Point.add(), wblut.geom.WB_Point.addMul(), wblut.geom.WB_GeometryOp2D.classifyPointToLine2D(), wblut.geom.WB_GeometryFactory2D.createBisector2D(), wblut.geom.WB_GeometryFactory2D.createCirclePPP(), wblut.geom.WB_GeometryFactory2D.createCircleThrough2Points(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createClosestPointOnLine2D(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoint2D(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoints2D(), wblut.geom.WB_GeometryFactory2D.createLineThroughPoints2D(), wblut.geom.WB_GeometryFactory2D.createPerpendicularLineThroughPoint2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Vector.getDistance2D(), wblut.geom.WB_GeometryOp2D.getDistanceToPoint2D(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Point.mulAddMul(), wblut.geom.WB_Classification.ON, wblut.geom.WB_GeometryOp2D.sameSideOfLine2D(), wblut.geom.WB_GeometryFactory2D.uniqueOnly(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Circle wblut.geom.WB_GeometryFactory2D.createCirclePPP (final WB_Coord p0, final WB_Coord p1, final WB_Coord p2)
Gets the circle through 3 2D points, z-ordinate is ignored.
Parameters
p0
p1
p2
Returns
circle through 3 points
References wblut.geom.WB_Predicates.circumcenter2D(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_Vector.getDistance2D(), and wblut.geom.WB_GeometryFactory2D.toDouble().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCircleTangentTo2Circles (final WB_Circle C0, final WB_Circle C1, final double r)
Return all circles tangential to two given circles. This function returns all circles with a collinear center regardless of radius and the circles with a non-collinear center with the given radius.
Parameters
C0
C1
r
Returns
References wblut.geom.WB_GeometryFactory2D.createCircleTangentTo2CirclesCollinear(), and wblut.geom.WB_GeometryFactory2D.createCircleTangentTo2CirclesNonCollinear().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCircleTangentTo2CirclesCollinear (final WB_Circle C0, final WB_Circle C1)
Gets circles tangent to two circles. This will return all tangent circles whose center are collinear with the the two centers.
Parameters
C0
C1
Returns
collinear circles tangent to two circles
References wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createInterpolatedPoint2D(), wblut.geom.WB_Circle.equals(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_GeometryOp2D.getDistance2D(), wblut.geom.WB_Circle.getRadius(), and wblut.math.WB_Epsilon.isZero().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCircleTangentTo2CirclesNonCollinear (final WB_Circle C0, final WB_Circle C1, final double r)
Gets circles with given radius tangent to two circles. This will return all tangent circles with a certaun radius whose center are non-collinear with the the two centers.
Parameters
C0
C1
r radius
Returns
non-collinear circles with given radius tangent to two circles
References wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoints2D(), wblut.geom.WB_Circle.equals(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_GeometryOp2D.getDistance2D(), wblut.geom.WB_Circle.getRadius(), and wblut.math.WB_Epsilon.isZero().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCircleTangentTo2Lines (final WB_Line L0, final WB_Line L1, final double r)
Gets circles with given radius tangent to 2 2D lines.
Parameters
L0 line
L1 line
r radius
Returns
circles with radius tangent to 2 2D lines
References wblut.geom.WB_Line.a(), wblut.geom.WB_Line.b(), wblut.geom.WB_Line.c(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), and wblut.geom.WB_GeometryFactory2D.createPoint2D().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCircleTangentToCircleThroughPoint (final WB_Circle C, final WB_Coord p, final double r)
Gets circles with given radius through 2D point and tangent to circle.
Parameters
C circle
p point
r radius
Returns
circles with given radius through point and tangent to circle
References wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoints2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Vector.getDistance2D(), and wblut.geom.WB_Circle.getRadius().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCircleTangentToLineAndCircle (final WB_Line L, final WB_Circle C, final double r)
Gets the circle tangent to line and circle.
Parameters
L the l
C the c
r the r
Returns
the circle tangent to line and circle
References wblut.geom.WB_Vector.addMul(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createIntersectionPoints2D(), wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_GeometryOp2D.getDistanceToLine2D(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCircleTangentToLineThroughPoint (final WB_Line L, final WB_Coord p, final double r)
Gets circles with given radius tangent to 2D line through 2D point.
Parameters
L line
p point
r radius
Returns
circles with given radius tangent to line through point
References wblut.geom.WB_Line.a(), wblut.geom.WB_Point.add(), wblut.geom.WB_Line.b(), wblut.geom.WB_Line.c(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.createCircleThrough2Points (final WB_Coord p0, final WB_Coord p1, final double r)
Gets the circles with given radius through 2 points.
Parameters
p0
p1
r radius
Returns
circles with given radius through 2 points
References wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), and wblut.geom.WB_GeometryFactory2D.createIntersectionPoints2D().
WB_Circle wblut.geom.WB_GeometryFactory2D.createCircleWithDiameter (final WB_Coord center, final WB_Coord normal, final double diameter)
Circle with center and radius.
Parameters
center
normal
diameter
Returns
circle
WB_Circle wblut.geom.WB_GeometryFactory2D.createCircleWithDiameter (final WB_Coord center, final double diameter)
Circle with center and diameter.
Parameters
center
diameter
Returns
circle
References wblut.geom.WB_GeometryFactory2D.createCircleWithRadius().
WB_Circle wblut.geom.WB_GeometryFactory2D.createCircleWithDiameter (final double x, final double y, final double diameter)
Circle with diameter and radius.
Parameters
x
y
diameter
Returns
circle
References wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), and wblut.geom.WB_GeometryFactory2D.createPoint2D().
WB_Circle wblut.geom.WB_GeometryFactory2D.createCircleWithRadius (final WB_Coord center, final WB_Coord normal, final double radius)
Circle with center and diameter.
Parameters
center
normal
radius
Returns
circle
WB_Circle wblut.geom.WB_GeometryFactory2D.createCircleWithRadius (final WB_Coord center, final double radius)
Parameters
center
radius
Returns
WB_Circle wblut.geom.WB_GeometryFactory2D.createCircleWithRadius (final double x, final double y, final double radius)
Circle with center and radius.
Parameters
x
y
radius
Returns
circle
References wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), and wblut.geom.WB_GeometryFactory2D.createPoint2D().
WB_Point wblut.geom.WB_GeometryFactory2D.createCircumcenter2D (final WB_Triangle tri)
Circumcenter of triangle.
Parameters
tri triangle
Returns
circumcenter
References wblut.geom.WB_Triangle.cosA, wblut.geom.WB_Triangle.cosB, wblut.geom.WB_Triangle.cosC, and wblut.geom.WB_GeometryFactory2D.createPointFromTrilinearCoordinates2D().
WB_Circle wblut.geom.WB_GeometryFactory2D.createCircumcircle2D (final WB_Triangle tri)
Get circumcircle of 2D triangle, z-ordinate is ignored.
Parameters
tri triangle
Returns
circumcircle
References wblut.geom.WB_Triangle.a, wblut.geom.WB_Triangle.b, wblut.geom.WB_Triangle.c, wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
List<WB_Point> wblut.geom.WB_GeometryFactory2D.createClosestPoint (final WB_Line L1, final WB_Line L2)
Closest points between two 2D lines, z-ordinate is ignored.
Parameters
L1 2D line
L2 2D line
Returns
if crossing: intersection, if parallel: origin of L1 + point on L2 closest to origin of L1
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_Vector.dot2D(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Line.getPoint(), and wblut.math.WB_Epsilon.isZero().
WB_Point wblut.geom.WB_GeometryFactory2D.createClosestPointOnLine2D (final WB_Coord p, final WB_Line L)
Closest point to 2D line, z-ordinate is ignored.
Parameters
p WB_Coordinate
L WB_Line
Returns
closest point on line
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_GeometryFactory2D.createClosestPointOnPolygon2D (final WB_Coord p, final WB_Polygon poly)
Parameters
p
poly
Returns
References wblut.geom.WB_GeometryFactory2D.createClosestPointOnTriangle2D(), wblut.geom.WB_Polygon.getPoint(), wblut.geom.WB_Vector.getSqDistance2D(), wblut.geom.WB_Polygon.getTriangles(), and wblut.math.WB_Epsilon.isZeroSq().
WB_Point wblut.geom.WB_GeometryFactory2D.createClosestPointOnTriangle2D (final WB_Coord p, final WB_Coord a, final WB_Coord b, final WB_Coord c)
Parameters
p
a
b
c
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_GeometryFactory2D.createVectorFromTo2D(), wblut.geom.WB_Vector.dot(), and wblut.geom.WB_Vector.mul().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createConvexPolygonDecomposition2D (final WB_Polygon poly)
Parameters
poly
Returns
References wblut.geom.WB_PolygonDecomposer.decomposePolygon2D().
WB_CoordinateSystem3D wblut.geom.WB_GeometryFactory2D.createCSFromOX2D (final WB_Coord origin, final WB_Coord X)
Create a new right-handed coordinate system. The WORLD CS is the default parent; the z-coordinate of X is ignored and X is normalized, Z is (0,0,1) and Y is created from X and Z
Parameters
origin
X
Returns
coordinate
References wblut.geom.WB_GeometryFactory2D.createCSFromOXY2D(), wblut.geom.WB_GeometryFactory2D.createNormalizedVector2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_CoordinateSystem3D wblut.geom.WB_GeometryFactory2D.createCSFromOX2D (final WB_Coord origin, final WB_Coord X, final WB_CoordinateSystem3D parent)
Create a new right-handed coordinate ; the z-coordinate of X is ignored and X is normalized, Z is (0,0,1) and Y is created from X and Z.
Parameters
origin
X
parent parent coordinate system
Returns
coordinate system
References wblut.geom.WB_GeometryFactory2D.createCSFromOXY2D(), wblut.geom.WB_GeometryFactory2D.createNormalizedVector2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_CoordinateSystem3D wblut.geom.WB_GeometryFactory2D.createCSFromOXY2D (final WB_Coord origin, final WB_Coord X, final WB_Coord Y)
Create a new right-handed coordinate system. The WORLD CS is the default parent; X is normalized, Y is normalized and orthogonalized and Z is created from X and Y
Parameters
origin
X
Y
Returns
coordinate system
References wblut.geom.WB_GeometryFactory2D.createNormalizedVector2D(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZeroSq(), and wblut.geom.WB_GeometryFactory2D.WORLD().
WB_CoordinateSystem3D wblut.geom.WB_GeometryFactory2D.createCSFromOXY2D (final WB_Coord origin, final WB_Coord X, final WB_Coord Y, final WB_CoordinateSystem3D parent)
Create a new right-handed coordinate with a defined parent. X is normalized, Y is normalized and orthogonalized and Z is created from X and Y
Parameters
origin
X
Y
parent parent coordinate system
Returns
coordinate system
References wblut.geom.WB_GeometryFactory2D.createNormalizedVector2D(), wblut.geom.WB_Vector.cross(), wblut.geom.WB_Vector.getSqLength(), and wblut.math.WB_Epsilon.isZeroSq().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createDensifiedPolygon2D (final WB_Polygon poly, final double max)
Parameters
poly
max
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
WB_Point wblut.geom.WB_GeometryFactory2D.createIncenter2D (final WB_Triangle tri)
Incenter of triangle, z-ordinate is ignored.
Parameters
tri triangle
Returns
incenter
References wblut.geom.WB_GeometryFactory2D.createPointFromTrilinearCoordinates2D().
WB_Circle wblut.geom.WB_GeometryFactory2D.createIncircle2D (final WB_Triangle tri)
Get incircle of triangle, z-ordinate is ignored.
Parameters
tri triangle
Returns
incircle
References wblut.geom.WB_Triangle.a, wblut.geom.WB_Triangle.b, wblut.geom.WB_Triangle.c, wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_GeometryFactory2D.createInterpolatedPoint2D (final WB_Coord p, final WB_Coord q, final double f)
Interpolated point.
Parameters
p point
q point
f interpolation value, p=0,q=1
Returns
copy of point
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_GeometryFactory2D.createIntersectionPoint2D (final WB_Line L1, final WB_Line L2)
Gets intersection points of two 2D lines, z-ordinate is ignored.
Parameters
L1
L2
Returns
intersection point
References wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Vector.dot(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Line.getPoint(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Point.mulAddMul(), and wblut.geom.WB_Vector.sub().
List<WB_Point> wblut.geom.WB_GeometryFactory2D.createIntersectionPoints2D (final WB_Circle C0, final WB_Circle C1)
Gets intersection points of two circles, z-ordinate is ignored.
Parameters
C0
C1
Returns
intersection points of two circles
References wblut.geom.WB_GeometryFactory2D.createInterpolatedPoint2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isEqualAbs(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
List<WB_Point> wblut.geom.WB_GeometryFactory2D.createIntersectionPoints2D (final WB_Line L, final WB_Circle C)
Gets intersection points of 2D line and circle, z-ordinate is ignored.
Parameters
L
C
Returns
intersection points of line and circle
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.math.WB_Epsilon.EPSILON, wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Line.getPoint(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Vector.getSqLength3D(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Circle wblut.geom.WB_GeometryFactory2D.createInversionCircle2D (final WB_Circle C, final WB_Circle inversionCircle)
Inversion of circle C over circle inversionCircle http://mathworld.wolfram.com/Inversion.html
Parameters
C circle
inversionCircle inversion circle
Returns
of circle C over circle inversionCircle, null if C is tangent to inversionCircle
References wblut.geom.WB_GeometryOp2D.classifyPointToCircle2D(), wblut.geom.WB_GeometryFactory2D.createCircleWithRadius(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_GeometryOp3D.getSqDistance3D(), wblut.geom.WB_Classification.ON, wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_GeometryFactory2D.createInversionPoint2D (final WB_Coord p, final WB_Circle inversionCircle)
Inversion of 2D point p over circle C http://mathworld.wolfram.com/Inversion.html
Parameters
p 2D point
inversionCircle inversion circle
Returns
Inversion of 2D point p over circle C, null if p coincides with inversion circle center
References wblut.geom.WB_Point.addMul(), wblut.geom.WB_GeometryFactory2D.createNormalizedVectorFromTo2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_GeometryOp2D.getDistance2D(), wblut.geom.WB_Circle.getRadius(), and wblut.math.WB_Epsilon.isZero().
List<WB_Line> wblut.geom.WB_GeometryFactory2D.createLinesTangentTo2Circles (final WB_Circle C0, final WB_Circle C1)
Gets the 2D lines tangent to 2 circles.
Parameters
C0 circle
C1 circle
Returns
the 2D lines tangent to the 2 circles
References wblut.geom.WB_Vector.add(), wblut.geom.WB_Point.add(), wblut.geom.WB_GeometryFactory2D.createInterpolatedPoint2D(), wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), wblut.geom.WB_GeometryFactory2D.createNormalizedVector2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_GeometryFactory2D.getDirections2D(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Vector.getSqLength(), wblut.math.WB_Epsilon.isZero(), wblut.math.WB_Epsilon.isZeroSq(), wblut.geom.WB_Coord.xd(), wblut.geom.WB_MutableCoordinate.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_MutableCoordinate.yd().
List<WB_Line> wblut.geom.WB_GeometryFactory2D.createLinesTangentToCircleThroughPoint (final WB_Circle C, final WB_Coord p)
Gets the 2D lines tangent to a circle through 2D point.
Parameters
C circle
p point
Returns
2D lines tangent to circle through point
References wblut.geom.WB_Vector.add(), wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_GeometryOp2D.getDistance2D(), wblut.geom.WB_Circle.getRadius(), wblut.math.WB_Epsilon.isZero(), wblut.geom.WB_Vector.sub(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
WB_Line wblut.geom.WB_GeometryFactory2D.createLineTangentToCircleInPoint (final WB_Circle C, final WB_Coord p)
Get the 2D line tangent to a circle at a 2D point.
Parameters
C circle
p point
Returns
2D line tangent to circle at point
References wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Vector.sub(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
WB_Line wblut.geom.WB_GeometryFactory2D.createLineThroughPoints2D (final WB_Coord p1, final WB_Coord p2)
Get line through two points. The first point will become the origin
Parameters
p1 point 1
p2 point 2
Returns
line through points
References wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), and wblut.geom.WB_GeometryFactory2D.createVectorFromTo2D().
WB_Line wblut.geom.WB_GeometryFactory2D.createLineThroughPoints2D (final double x1, final double y1, final double x2, final double y2)
Get line through two points. The first point will become the origin
Parameters
x1 x-ordinate of point 1
y1 y-ordinate of point 1
x2 x-ordinate of point 2
y2 y-ordinate of point 2
Returns
line through points
References wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), and wblut.geom.WB_GeometryFactory2D.createVector2D().
WB_Line wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D (final WB_Coord origin, final WB_Coord direction)
Get line through point with given direction.
Parameters
origin point on line
direction direction
Returns
line through point with direction
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), and wblut.geom.WB_GeometryFactory2D.createVector2D().
WB_Line wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D (final double ox, final double oy, final double dx, final double dy)
Get 2D line through point with given direction.
Parameters
ox x-ordinate of origin
oy y-ordinate of origin
dx x-ordinate of direction
dy y-ordinate of direction
Returns
2D line through point with given direction
References wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), and wblut.geom.WB_GeometryFactory2D.createVector2D().
WB_Point wblut.geom.WB_GeometryFactory2D.createMidpoint2D (final WB_Coord p, final WB_Coord q)
Parameters
p
q
Returns
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_GeometryFactory2D.createMidpoint2D (final WB_Coord... p)
Parameters
p
Returns
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), and wblut.geom.WB_Point.divSelf().
WB_Point wblut.geom.WB_GeometryFactory2D.createMirrorPoint2D (final WB_Coord p, final double x0, final double y0, final double x1, final double y1)
Mirror 2D point about 2D line.
Parameters
p
x0
y0
x1
y1
Returns
mirrored point
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_GeometryFactory2D.createMirrorPoint2D (final WB_Coord p, final WB_Line L)
Mirror 2D point about 2D line.
Parameters
p WB_Coordinate
L WB_Linear
Returns
mirrored point
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_GeometryFactory2D.createNormalizedPerpendicularVector2D (final double _x, final double _y)
Normalized vector from Cartesian coordinates http://en.wikipedia.org/wiki/Cartesian_coordinate_system
Parameters
_x x
_y y
Returns
2D vector
References wblut.geom.WB_GeometryFactory2D.createVector2D(), and wblut.geom.WB_Vector.normalizeSelf().
WB_Vector wblut.geom.WB_GeometryFactory2D.createNormalizedPerpendicularVector2D (final WB_Coord v)
References wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_GeometryFactory2D.createNormalizedVector2D (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_GeometryFactory2D.createVector2D(), and wblut.geom.WB_Vector.normalizeSelf().
WB_Vector wblut.geom.WB_GeometryFactory2D.createNormalizedVector2D (final double _x, final double _y)
Normalized vector from Cartesian coordinates http://en.wikipedia.org/wiki/Cartesian_coordinate_system
Parameters
_x x
_y y
Returns
2D vector
References wblut.geom.WB_GeometryFactory2D.createVector2D(), and wblut.geom.WB_Vector.normalizeSelf().
WB_Vector wblut.geom.WB_GeometryFactory2D.createNormalizedVectorFromTo2D (final WB_Coord p, final WB_Coord q)
Parameters
p
q
Returns
References wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Vector.normalizeSelf(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_GeometryFactory2D.createOrthocenter2D (final WB_Triangle tri)
Orthocenter of triangle.
Parameters
tri triangle
Returns
orthocenter
References wblut.geom.WB_Triangle.a, wblut.geom.WB_Triangle.b, wblut.geom.WB_Triangle.c, and wblut.geom.WB_GeometryFactory2D.createPointFromBarycentricCoordinates2D().
List<WB_Line> wblut.geom.WB_GeometryFactory2D.createParallelLines2D (final WB_Line L, final double d)
Get the two 2D lines parallel to a 2D line and separated by a distance d.
Parameters
L 2D line
d distance
Returns
two parallel 2D lines
References wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Line.getOrigin(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Line wblut.geom.WB_GeometryFactory2D.createParallelLineThroughPoint2D (final WB_Line L, final WB_Coord p)
Get a line parallel to a line and through point.
Parameters
L line
p point
Returns
parallel line through point
References wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), and wblut.geom.WB_Line.getDirection().
WB_Ray wblut.geom.WB_GeometryFactory2D.createParallelRayThroughPoint2D (final WB_Line L, final WB_Coord p)
Get a ray parallel to a line and through point.
Parameters
L line
p point
Returns
parallel line through point
References wblut.geom.WB_GeometryFactory2D.createRayWithDirection2D(), and wblut.geom.WB_Line.getDirection().
List<WB_Line> wblut.geom.WB_GeometryFactory2D.createPerpendicularLinesTangentToCircle (final WB_Line L, final WB_Circle C)
Gets the two 2D lines perpendicular to a 2D line and tangent to a circle.
Parameters
L 2D line
C circle
Returns
2D lines perpendicular to line and tangent to circle
References wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Circle.getCenter(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Circle.getRadius(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Line wblut.geom.WB_GeometryFactory2D.createPerpendicularLineThroughPoint2D (final WB_Line L, final WB_Coord p)
Get a 2D line perpendicular to 2D line and through 2D point.
Parameters
L 2D line
p 2D point
Returns
perpendicular 2D line through point
References wblut.geom.WB_GeometryFactory2D.createLineWithDirection2D(), wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Line.getDirection(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_GeometryFactory2D.createPoint2D ()
New point at origin.
Returns
new point at origin
WB_Point wblut.geom.WB_GeometryFactory2D.createPoint2D (final WB_Coord p)
Copy of coordinate as point, z-ordinate is ignored.
Parameters
p point
Returns
copy of point
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Point wblut.geom.WB_GeometryFactory2D.createPoint2D (final double x, final double y)
Point from Cartesian coordinates http://en.wikipedia.org/wiki/Cartesian_coordinate_system
Parameters
x x
y y
Returns
2D point
WB_Point wblut.geom.WB_GeometryFactory2D.createPoint2D (final Coordinate coord)
Parameters
coord
Returns
WB_Point wblut.geom.WB_GeometryFactory2D.createPointFromBarycentricCoordinates2D (final double u, final double v, final double w, final WB_Triangle tri)
Get point with triangle barycentric coordinates.
Parameters
u
v
w
tri triangle
Returns
point wit barycentric coordinates (u,v,w)
References wblut.geom.WB_Triangle.a, wblut.geom.WB_Triangle.b, wblut.geom.WB_Triangle.c, and wblut.geom.WB_GeometryFactory2D.createPointFromTrilinearCoordinates2D().
WB_Point wblut.geom.WB_GeometryFactory2D.createPointFromBipolar (final double a, final double sigma, final double tau)
Point from bipolar coordinates http://en.wikipedia.org/wiki/Bipolar_coordinates
Parameters
a focus
sigma bipolar coordinate
tau bipolar coordinate
Returns
2D point
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), and wblut.math.WB_Epsilon.isZero().
WB_Point wblut.geom.WB_GeometryFactory2D.createPointFromElliptic (final double a, final double sigma, final double tau)
Point from elliptic coordinates http://en.wikipedia.org/wiki/Elliptic_coordinates
Parameters
a focus
sigma elliptic coordinate >=0
tau elliptic coordinate between -1 and 1
Returns
2D point
References wblut.geom.WB_GeometryFactory2D.createPoint2D().
WB_Point wblut.geom.WB_GeometryFactory2D.createPointFromHyperbolic (final double u, final double v)
Point from hyperbolic coordinates http://en.wikipedia.org/wiki/Hyperbolic_coordinates
Parameters
u hyperbolic angle
v geometric mean >0
Returns
2D point
References wblut.geom.WB_GeometryFactory2D.createPoint2D().
WB_Point wblut.geom.WB_GeometryFactory2D.createPointFromParabolic (final double sigma, final double tau)
Point from parabolic coordinates http://en.wikipedia.org/wiki/Parabolic_coordinates
Parameters
sigma parabolic coordinate
tau parabolic coordinate
Returns
2D point
References wblut.geom.WB_GeometryFactory2D.createPoint2D().
WB_Point wblut.geom.WB_GeometryFactory2D.createPointFromPolar (final double r, final double phi)
Point from polar coordinates http://en.wikipedia.org/wiki/Polar_coordinate_system
Parameters
r radius
phi angle
Returns
2D point
References wblut.geom.WB_GeometryFactory2D.createPoint2D().
WB_Point wblut.geom.WB_GeometryFactory2D.createPointFromTrilinearCoordinates2D (final double u, final double v, final double w, final WB_Triangle tri)
Get point with triangle trilinear coordinates.
Parameters
u
v
w
tri triangle
Returns
point wit trilinear coordinates (u,v,w)
References wblut.geom.WB_Triangle.a, wblut.geom.WB_Triangle.b, wblut.geom.WB_Triangle.c, wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Polygon wblut.geom.WB_GeometryFactory2D.createPolygonConvexHull2D (final WB_Polygon poly)
Parameters
poly
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonFromJTSPolygon2D().
WB_Polygon wblut.geom.WB_GeometryFactory2D.createPolygonFromJTSPolygon2D (final Polygon JTSpoly)
Parameters
JTSpoly
Returns
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_GeometryFactory2D.createPolygonWithHoles(), and wblut.geom.WB_GeometryFactory2D.createSimplePolygon().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D (final Geometry geometry) private
Parameters
geometry
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonFromJTSPolygon2D().
WB_Polygon wblut.geom.WB_GeometryFactory2D.createPolygonWithHole (final WB_Coord[] points, final WB_Coord[] innerpoints)
Parameters
points
innerpoints
Returns
WB_Polygon wblut.geom.WB_GeometryFactory2D.createPolygonWithHole (final Collection<?extends WB_Coord > points, final Collection<?extends WB_Coord > innerpoints)
Parameters
points
innerpoints
Returns
WB_Polygon wblut.geom.WB_GeometryFactory2D.createPolygonWithHoles (final WB_Coord[] points, final WB_Coord innerpoints[][])
Parameters
points
innerpoints
Returns
WB_Polygon wblut.geom.WB_GeometryFactory2D.createPolygonWithHoles (final Collection<?extends WB_Coord > points, final List<?extends WB_Coord >[] innerpoints)
Parameters
points
innerpoints
Returns
WB_PolyLine wblut.geom.WB_GeometryFactory2D.createPolyLine (final WB_Coord[] points)
Parameters
points
Returns
WB_PolyLine wblut.geom.WB_GeometryFactory2D.createPolyLine (final Collection<?extends WB_Coord > points)
Parameters
points
Returns
WB_Ray wblut.geom.WB_GeometryFactory2D.createRayThroughPoints2D (final WB_Coord p1, final WB_Coord p2)
Get ray through two points. The first point will become the origin
Parameters
p1 point 1
p2 point 2
Returns
ray through points
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_GeometryFactory2D.createRayWithDirection2D(), and wblut.geom.WB_GeometryFactory2D.createVectorFromTo2D().
WB_Ray wblut.geom.WB_GeometryFactory2D.createRayThroughPoints2D (final double x1, final double y1, final double x2, final double y2)
Get ray through two points. The first point will become the origin
Parameters
x1 x-ordinate of point 1
y1 y-ordinate of point 1
x2 x-ordinate of point 2
y2 y-ordinate of point 2
Returns
ray through points
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_GeometryFactory2D.createRayWithDirection2D(), and wblut.geom.WB_GeometryFactory2D.createVector2D().
WB_Ray wblut.geom.WB_GeometryFactory2D.createRayWithDirection2D (final WB_Coord origin, final WB_Coord direction)
Get ray through point with given direction.
Parameters
origin point on line
direction direction
Returns
ray through point with direction
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), and wblut.geom.WB_GeometryFactory2D.createVector2D().
WB_Ray wblut.geom.WB_GeometryFactory2D.createRayWithDirection2D (final double ox, final double oy, final double dx, final double dy)
Get 2D ray through point with given direction.
Parameters
ox x-ordinate of origin
oy y-ordinate of origin
dx x-ordinate of direction
dy y-ordinate of direction
Returns
2D ray through point with given direction
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_GeometryFactory2D.createRayWithDirection2D(), and wblut.geom.WB_GeometryFactory2D.createVector2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createRibbonPolygons2D (final WB_Polygon poly, final double d)
Parameters
poly
d
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createRibbonPolygons2D (final Collection<?extends WB_Polygon > poly, final double d)
Parameters
poly
d
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createRibbonPolygons2D (final WB_Polygon poly, final double o, final double i)
Parameters
poly
o
i
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createRibbonPolygons2D (final Collection<?extends WB_Polygon > poly, final double o, final double i)
Parameters
poly
o
i
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
WB_Ring wblut.geom.WB_GeometryFactory2D.createRing (final WB_Coord[] points)
Parameters
points
Returns
WB_Ring wblut.geom.WB_GeometryFactory2D.createRing (final List<?extends WB_Coord > points)
Parameters
points
Returns
WB_Segment wblut.geom.WB_GeometryFactory2D.createSegment2D (final WB_Coord p1, final WB_Coord p2)
Get segment between two points. The first point will become the origin
Parameters
p1 point 1
p2 point 2
Returns
segment
References wblut.geom.WB_GeometryFactory2D.createPoint2D().
WB_Segment wblut.geom.WB_GeometryFactory2D.createSegment2D (final double x1, final double y1, final double x2, final double y2)
Get segment. The first point will become the origin
Parameters
x1 x-ordinate of point 1
y1 y-ordinate of point 1
x2 x-ordinate of point 2
y2 y-ordinate of point 2
Returns
line through points
References wblut.geom.WB_GeometryFactory2D.createPoint2D(), wblut.geom.WB_GeometryFactory2D.createSegment2D(), and wblut.geom.WB_GeometryFactory2D.createVector2D().
WB_Segment wblut.geom.WB_GeometryFactory2D.createSegmentWithLength2D (final WB_Coord origin, final WB_Coord direction, final double length)
Get segment between two points. The first point will become the origin
Parameters
origin origin
direction direction
length length
Returns
segment
References wblut.geom.WB_GeometryFactory2D.createNormalizedVector2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), and wblut.geom.WB_GeometryFactory2D.createSegment2D().
WB_Segment wblut.geom.WB_GeometryFactory2D.createSegmentWithLength2D (final double ox, final double oy, final double dx, final double dy, final double length)
Get segment from point, direction and length.
Parameters
ox x-ordinate of origin
oy y-ordinate of origin
dx x-ordinate of direction
dy y-ordinate of direction
length length
Returns
segment
References wblut.geom.WB_GeometryFactory2D.createNormalizedVector2D(), wblut.geom.WB_GeometryFactory2D.createPoint2D(), and wblut.geom.WB_GeometryFactory2D.createSegment2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createShape (final Shape shape, final double flatness)
Parameters
shape
flatness
Returns
WB_Polygon wblut.geom.WB_GeometryFactory2D.createSimplePolygon (final WB_Coord... points)
Parameters
points
Returns
WB_Polygon wblut.geom.WB_GeometryFactory2D.createSimplePolygon (final WB_CoordCollection points)
WB_Polygon wblut.geom.WB_GeometryFactory2D.createSimplePolygon (final WB_Polygon poly)
Parameters
poly
Returns
References wblut.geom.WB_PolygonTriangulatorJTS.makeSimplePolygon().
WB_Polygon wblut.geom.WB_GeometryFactory2D.createSimplePolygon (final Collection<?extends WB_Coord > points)
Parameters
points
Returns
WB_Polygon wblut.geom.WB_GeometryFactory2D.createSimplePolygon (final WB_Triangle triangle)
WB_Polygon wblut.geom.WB_GeometryFactory2D.createSimplePolygon (final WB_Quad quad)
References wblut.geom.WB_Quad.p1, wblut.geom.WB_Quad.p2, wblut.geom.WB_Quad.p3, and wblut.geom.WB_Quad.p4.
WB_Polygon wblut.geom.WB_GeometryFactory2D.createSimplePolygon (final WB_Pentagon pentagon)
References wblut.geom.WB_Pentagon.p1, wblut.geom.WB_Pentagon.p2, wblut.geom.WB_Pentagon.p3, wblut.geom.WB_Pentagon.p4, and wblut.geom.WB_Pentagon.p5.
WB_Polygon wblut.geom.WB_GeometryFactory2D.createSimplePolygon (final WB_Hexagon hexagon)
References wblut.geom.WB_Hexagon.p1, wblut.geom.WB_Hexagon.p2, wblut.geom.WB_Hexagon.p3, wblut.geom.WB_Hexagon.p4, wblut.geom.WB_Hexagon.p5, and wblut.geom.WB_Hexagon.p6.
WB_Polygon wblut.geom.WB_GeometryFactory2D.createSimplePolygon (final WB_Octagon octagon)
References wblut.geom.WB_Octagon.p1, wblut.geom.WB_Octagon.p2, wblut.geom.WB_Octagon.p3, wblut.geom.WB_Octagon.p4, wblut.geom.WB_Octagon.p5, wblut.geom.WB_Octagon.p6, wblut.geom.WB_Octagon.p7, and wblut.geom.WB_Octagon.p8.
WB_Polygon wblut.geom.WB_GeometryFactory2D.createSimplePolygon (final List<?extends WB_Coord > tuples, final int[] indices)
Parameters
tuples
indices
Returns
References wblut.geom.WB_GeometryFactory2D.createSimplePolygon().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createSimplifiedPolygon2D (final WB_Polygon poly, final double tol)
Parameters
poly
tol
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createText (final String text, final String fontName, final float pointSize)
Parameters
text
fontName
pointSize
Returns
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createText (final String text, final String fontName, final float pointSize, final double flatness)
Parameters
text
fontName
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createText().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createText (final String text, final String fontName, final int style, final float pointSize, final double flatness)
Parameters
text
fontName
style
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createText().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createText (final String text, final Font font, final int style, final float pointSize, final double flatness)
Parameters
text
font
style
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createText().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createText (final String text, final Font font, final double flatness)
Parameters
text
font
flatness
Returns
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createTextWithFont (final String text, final String fontName, final float pointSize)
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createTextWithFont (final String text, final String fontName, final float pointSize, final double flatness)
References wblut.geom.WB_GeometryFactory2D.createTextWithFont().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createTextWithFont (final String text, final String fontName, final int style, final float pointSize, final double flatness)
References wblut.geom.WB_GeometryFactory2D.createText().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createTextWithOpenTypeFont (final String text, final String fontName, final float pointSize)
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createTextWithOpenTypeFont (final String text, final String fontName, final float pointSize, final double flatness)
References wblut.geom.WB_GeometryFactory2D.createTextWithOpenTypeFont().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createTextWithOpenTypeFont (final String text, final String fontName, final int style, final float pointSize, final double flatness)
Parameters
text
fontName
style
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createText().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createTextWithTrueTypeFont (final String text, final String fontName, final float pointSize)
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createTextWithTrueTypeFont (final String text, final String fontName, final float pointSize, final double flatness)
References wblut.geom.WB_GeometryFactory2D.createTextWithTrueTypeFont().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createTextWithTrueTypeFont (final String text, final String fontName, final int style, final float pointSize, final double flatness)
Parameters
text
fontName
style
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createText().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createTextWithType1Font (final String text, final String fontName, final float pointSize)
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createTextWithType1Font (final String text, final String fontName, final float pointSize, final double flatness)
References wblut.geom.WB_GeometryFactory2D.createTextWithType1Font().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.createTextWithType1Font (final String text, final String fontName, final int style, final float pointSize, final double flatness)
Parameters
text
fontName
style
pointSize
flatness
Returns
References wblut.geom.WB_GeometryFactory2D.createText().
WB_CoordinateSystem3D wblut.geom.WB_GeometryFactory2D.createTransformedCS (final WB_CoordinateSystem3D CS, final WB_Transform T, final WB_CoordinateSystem3D parent)
Parameters
CS
T
parent
Returns
WB_CoordinateSystem3D wblut.geom.WB_GeometryFactory2D.createTransformedCS (final WB_CoordinateSystem3D CS, final WB_Transform T)
Parameters
CS
T
Returns
WB_Triangle wblut.geom.WB_GeometryFactory2D.createTriangle2D (final double p1x, final double p1y, final double p2x, final double p2y, final double p3x, final double p3y)
Get triangle from 3 points.
Parameters
p1x x-ordinate of first point of triangle
p1y y-ordinate of first point of triangle
p2x x-ordinate of second point of triangle
p2y y-ordinate of second point of triangle
p3x x-ordinate of third point of triangle
p3y y-ordinate of third point of triangle
Returns
triangle
References wblut.geom.WB_GeometryFactory2D.createPoint2D().
WB_Triangle wblut.geom.WB_GeometryFactory2D.createTriangle2D (final WB_Coord p1, final WB_Coord p2, final WB_Coord p3)
Get triangle from 3 points.
Parameters
p1 first point of triangle
p2 second point of triangle
p3 third point of triangle
Returns
triangle
References wblut.geom.WB_GeometryFactory2D.createPoint2D().
List<WB_Coord> wblut.geom.WB_GeometryFactory2D.createUniquePoints2D (final List< WB_Coord > points, final double threshold)
WB_Vector wblut.geom.WB_GeometryFactory2D.createVector2D ()
New zero-length vector.
Returns
zero-length vector
WB_Vector wblut.geom.WB_GeometryFactory2D.createVector2D (final WB_Coord p)
Copy of coordinate as vector, z-ordinate is ignored.
Parameters
p vector
Returns
vector
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
WB_Vector wblut.geom.WB_GeometryFactory2D.createVector2D (final double _x, final double _y)
Vector from Cartesian coordinates http://en.wikipedia.org/wiki/Cartesian_coordinate_system
Parameters
_x x
_y y
Returns
2D vector
WB_Vector wblut.geom.WB_GeometryFactory2D.createVectorFromBipolar (final double a, final double sigma, final double tau)
Vector from bipolar coordinates http://en.wikipedia.org/wiki/Bipolar_coordinates
Parameters
a focus
sigma bipolar coordinate
tau bipolar coordinate
Returns
2D vector
References wblut.geom.WB_GeometryFactory2D.createVector2D(), and wblut.math.WB_Epsilon.isZero().
WB_Vector wblut.geom.WB_GeometryFactory2D.createVectorFromElliptic (final double a, final double mu, final double nu)
Vector from elliptic coordinates http://en.wikipedia.org/wiki/Elliptic_coordinates
Parameters
a focus
mu elliptic coordinate >=0
nu elliptic coordinate between -PI and PI
Returns
2D vector
References wblut.geom.WB_GeometryFactory2D.createVector2D().
WB_Vector wblut.geom.WB_GeometryFactory2D.createVectorFromHyperbolic (final double u, final double v)
Vector from hyperbolic coordinates http://en.wikipedia.org/wiki/Hyperbolic_coordinates
Parameters
u hyperbolic angle
v geometric mean >0
Returns
2D vector
References wblut.geom.WB_GeometryFactory2D.createVector2D().
WB_Vector wblut.geom.WB_GeometryFactory2D.createVectorFromParabolic (final double sigma, final double tau)
Vector from parabolic coordinates http://en.wikipedia.org/wiki/Parabolic_coordinates
Parameters
sigma parabolic coordinate
tau parabolic coordinate
Returns
2D vector
References wblut.geom.WB_GeometryFactory2D.createVector2D().
WB_Vector wblut.geom.WB_GeometryFactory2D.createVectorFromPolar (final double r, final double phi)
Vector from polar coordinates http://en.wikipedia.org/wiki/Polar_coordinate_system
Parameters
r radius
phi angle
Returns
2D vector
References wblut.geom.WB_GeometryFactory2D.createVector2D().
WB_Vector wblut.geom.WB_GeometryFactory2D.createVectorFromTo2D (final WB_Coord p, final WB_Coord q)
Parameters
p
q
Returns
References wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
List<WB_Vector> wblut.geom.WB_GeometryFactory2D.getDirections2D (final WB_Coord w, final double a) private
Parameters
w
a
Returns
References wblut.geom.WB_GeometryFactory2D.createVector2D(), wblut.math.WB_Math.fastAbs(), wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
static WB_GeometryFactory2D wblut.geom.WB_GeometryFactory2D.instance () static
Legacy code, WB_GeometryFactory used to be a singleton but this limited its use in multithreaded code.
Returns
References wblut.geom.WB_GeometryFactory2D.WB_GeometryFactory2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.intersectPolygons2D (final WB_Polygon poly1, final WB_Polygon poly2)
Parameters
poly1
poly2
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.intersectPolygons2D (final WB_Polygon poly1, final Collection<?extends WB_Polygon > poly2)
Parameters
poly1
poly2
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.intersectPolygons2D (final Collection<?extends WB_Polygon > poly1, final Collection<?extends WB_Polygon > poly2)
Parameters
poly1
poly2
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
WB_Coord wblut.geom.WB_GeometryFactory2D.minX2D ()
Returns
negative X-axis direction
WB_Coord wblut.geom.WB_GeometryFactory2D.minY2D ()
Returns
negative Y-axis direction
WB_Coord wblut.geom.WB_GeometryFactory2D.origin2D ()
Returns
default origin
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.subtractPolygons2D (final WB_Polygon poly1, final WB_Polygon poly2)
Parameters
poly1
poly2
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.subtractPolygons2D (final WB_Polygon poly1, final Collection<?extends WB_Polygon > poly2)
Parameters
poly1
poly2
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.subtractPolygons2D (final Collection<?extends WB_Polygon > poly1, final Collection<?extends WB_Polygon > poly2)
Parameters
poly1
poly2
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.subtractPolygons2D (final Collection<?extends WB_Polygon > poly1, final WB_Polygon poly2)
Parameters
poly1
poly2
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.symDifferencePolygons2D (final WB_Polygon poly1, final WB_Polygon poly2)
Parameters
poly1
poly2
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.symDifferencePolygons2D (final WB_Polygon poly1, final Collection<?extends WB_Polygon > poly2)
Parameters
poly1
poly2
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.symDifferencePolygons2D (final Collection<?extends WB_Polygon > poly1, final Collection<?extends WB_Polygon > poly2)
Parameters
poly1
poly2
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
double [] wblut.geom.WB_GeometryFactory2D.toDouble (final WB_Coord p) private
Parameters
p
Returns
References wblut.geom.WB_Coord.xd(), and wblut.geom.WB_Coord.yd().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.unionPolygons2D (final WB_Polygon poly1, final WB_Polygon poly2)
Parameters
poly1
poly2
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.unionPolygons2D (final WB_Polygon poly1, final Collection<?extends WB_Polygon > poly2)
Parameters
poly1
poly2
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Polygon> wblut.geom.WB_GeometryFactory2D.unionPolygons2D (final Collection<?extends WB_Polygon > poly1, final Collection<?extends WB_Polygon > poly2)
Parameters
poly1
poly2
Returns
References wblut.geom.WB_GeometryFactory2D.createPolygonsFromJTSGeometry2D().
List<WB_Circle> wblut.geom.WB_GeometryFactory2D.uniqueOnly (final List< WB_Circle > circles) private
Parameters
circles
Returns
WB_CoordinateSystem3D wblut.geom.WB_GeometryFactory2D.WORLD ()
Returns
default origin
References wblut.geom.WB_CoordinateSystem3D.WORLD().
WB_Coord wblut.geom.WB_GeometryFactory2D.X2D ()
Returns
default X-axis direction
WB_Coord wblut.geom.WB_GeometryFactory2D.Y2D ()
Returns
default Y-axis direction
Member Data Documentation
final GeometryFactory wblut.geom.WB_GeometryFactory2D.JTSgf = new GeometryFactory() private
WB_ShapeReader wblut.geom.WB_GeometryFactory2D.shapereader private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_GeometryFactory2D.java