HE_Mesh: wblut.hemesh.HEM_CircleInversion Class Reference
wblut.hemesh.HEM_CircleInversion Class Reference
Public Member Functions
HEM_CircleInversion ()
HEM_CircleInversion (final WB_Circle circle, final double r)
HEM_CircleInversion setCircle (final WB_Circle circle)
HEM_CircleInversion setCircle (final WB_Coord c, final double radius)
HEM_CircleInversion setCircle (final WB_Coord c, final WB_Coord n, final double radius)
HEM_CircleInversion setRadius (final double r)
HEM_CircleInversion setCutoff (final double cutoff)
HEM_CircleInversion setLinear (final boolean b)
Public Member Functions inherited from wblut.hemesh.HEM_Modifier
HEM_Modifier ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection selection)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Protected Member Functions
HE_Mesh applySelf (final HE_Mesh mesh)
HE_Mesh applySelf (final HE_Selection selection)
Protected Member Functions inherited from wblut.hemesh.HEM_Modifier
abstract HE_Mesh applySelf (final HE_Mesh mesh)
abstract HE_Mesh applySelf (final HE_Selection selection)
Private Attributes
WB_Circle circle
double r
double icutoff
boolean linear
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Constructor & Destructor Documentation
wblut.hemesh.HEM_CircleInversion.HEM_CircleInversion ()
wblut.hemesh.HEM_CircleInversion.HEM_CircleInversion (final WB_Circle circle, final double r)
References wblut.hemesh.HEM_CircleInversion.circle, and wblut.hemesh.HEM_CircleInversion.r.
Member Function Documentation
HE_Mesh wblut.hemesh.HEM_CircleInversion.applySelf (final HE_Mesh mesh) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Vector.normalizeSelf(), wblut.hemesh.HE_Vertex.set(), wblut.geom.WB_Point.subToVector3D(), wblut.geom.WB_Vector.subToVector3D(), and wblut.hemesh.HE_Mesh.vItr().
HE_Mesh wblut.hemesh.HEM_CircleInversion.applySelf (final HE_Selection selection) protected
References wblut.geom.WB_Point.addMulSelf(), wblut.geom.WB_Point.addSelf(), wblut.geom.WB_GeometryOp3D.getClosestPoint3D(), wblut.hemesh.HE_Vertex.getPosition(), wblut.geom.WB_Vector.mulSelf(), wblut.geom.WB_Vector.normalizeSelf(), wblut.hemesh.HE_Vertex.set(), wblut.geom.WB_Point.subToVector3D(), wblut.geom.WB_Vector.subToVector3D(), and wblut.hemesh.HE_Selection.vItr().
HEM_CircleInversion wblut.hemesh.HEM_CircleInversion.setCircle (final WB_Circle circle)
Parameters
circle
Returns
References wblut.hemesh.HEM_CircleInversion.circle.
HEM_CircleInversion wblut.hemesh.HEM_CircleInversion.setCircle (final WB_Coord c, final double radius)
HEM_CircleInversion wblut.hemesh.HEM_CircleInversion.setCircle (final WB_Coord c, final WB_Coord n, final double radius)
HEM_CircleInversion wblut.hemesh.HEM_CircleInversion.setCutoff (final double cutoff)
Parameters
cutoff
Returns
HEM_CircleInversion wblut.hemesh.HEM_CircleInversion.setLinear (final boolean b)
Parameters
b
Returns
HEM_CircleInversion wblut.hemesh.HEM_CircleInversion.setRadius (final double r)
Parameters
r
Returns
References wblut.hemesh.HEM_CircleInversion.r.
Member Data Documentation
WB_Circle wblut.hemesh.HEM_CircleInversion.circle private
double wblut.hemesh.HEM_CircleInversion.icutoff private
boolean wblut.hemesh.HEM_CircleInversion.linear private
double wblut.hemesh.HEM_CircleInversion.r private
The documentation for this class was generated from the following file:
src/hemesh_modifiers/wblut/hemesh/HEM_CircleInversion.java