HE_Mesh: wblut.geom.WB_AlphaTriangulation3D Class Reference
wblut.geom.WB_AlphaTriangulation3D Class Reference
Classes
class Key
class Triple
Public Member Functions
WB_AlphaTriangulation3D (final int[] tetra, final WB_CoordCollection points)
WB_AlphaTriangulation3D (final int[][] tetra, final WB_CoordCollection points)
WB_AlphaTriangulation3D (final int[] tetra, final Collection<?extends WB_Coord > points)
WB_AlphaTriangulation3D (final int[][] tetra, final Collection<?extends WB_Coord > points)
WB_AlphaTriangulation3D (final int[] tetra, final WB_Coord[] points)
WB_AlphaTriangulation3D (final int[][] tetra, final WB_Coord[] points)
int[] getTetrahedra ()
List< WB_Coord > getpoints ()
double[] getAlpha ()
int[] getAlphaTetrahedra (final double a)
int[] getAlphaTriangles (final double a)
Private Member Functions
void setAlpha ()
Private Attributes
int[] tetrahedra
double[] alpha
FastList< WB_Coord > points
Detailed Description
WB_AlphaTriangulation3D stores the results of WB_Triangulate.alphaTriangulate3D: a 3D Delaunay triangulation with the corresponding circumsphere radii.
Constructor & Destructor Documentation
wblut.geom.WB_AlphaTriangulation3D.WB_AlphaTriangulation3D (final int[] tetra, final WB_CoordCollection points)
Parameters
tetra
points
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_AlphaTriangulation3D.setAlpha(), and wblut.geom.WB_CoordCollection.size().
wblut.geom.WB_AlphaTriangulation3D.WB_AlphaTriangulation3D (final int tetra[][], final WB_CoordCollection points)
Parameters
tetra
points
References wblut.geom.WB_CoordCollection.get(), wblut.geom.WB_AlphaTriangulation3D.setAlpha(), and wblut.geom.WB_CoordCollection.size().
wblut.geom.WB_AlphaTriangulation3D.WB_AlphaTriangulation3D (final int[] tetra, final Collection<?extends WB_Coord > points)
Parameters
tetra
points
References wblut.geom.WB_AlphaTriangulation3D.setAlpha().
wblut.geom.WB_AlphaTriangulation3D.WB_AlphaTriangulation3D (final int tetra[][], final Collection<?extends WB_Coord > points)
Parameters
tetra
points
References wblut.geom.WB_AlphaTriangulation3D.setAlpha().
wblut.geom.WB_AlphaTriangulation3D.WB_AlphaTriangulation3D (final int[] tetra, final WB_Coord[] points)
Parameters
tetra
points
References wblut.geom.WB_AlphaTriangulation3D.setAlpha().
wblut.geom.WB_AlphaTriangulation3D.WB_AlphaTriangulation3D (final int tetra[][], final WB_Coord[] points)
Parameters
tetra
points
References wblut.geom.WB_AlphaTriangulation3D.setAlpha().
Member Function Documentation
double [] wblut.geom.WB_AlphaTriangulation3D.getAlpha ()
Get the circumradii of the tetrahedra vertices as a single array of double. Original values are copied.
Returns
int [] wblut.geom.WB_AlphaTriangulation3D.getAlphaTetrahedra (final double a)
Get the indices to the alpha tetrahedra vertices as a single array of int. 4 indices per tetrahedron. Only tetrahedra with a circumradius smaller or equal to a are returned.
Parameters
a alpha value
Returns
int [] wblut.geom.WB_AlphaTriangulation3D.getAlphaTriangles (final double a)
Get the indices to the alpha triangle vertices as a single array of int. 3 indices per triangle. Only unpaired triangles from the collection of tetrahedra with a circumradius smaller or equal to a are returned.
Parameters
a alpha value
Returns
List<WB_Coord> wblut.geom.WB_AlphaTriangulation3D.getpoints ()
Get the vertices of the triangulation as an unmodifiable List<WB_Coord>.
Returns
int [] wblut.geom.WB_AlphaTriangulation3D.getTetrahedra ()
Get the indices to the tetrahedra vertices as a single array of int. 4 indices per tetrahedron.
Returns
References wblut.geom.WB_AlphaTriangulation3D.tetrahedra.
void wblut.geom.WB_AlphaTriangulation3D.setAlpha () private
References wblut.geom.WB_Predicates.circumradius3D().
Member Data Documentation
double [] wblut.geom.WB_AlphaTriangulation3D.alpha private
FastList<WB_Coord> wblut.geom.WB_AlphaTriangulation3D.points private
int [] wblut.geom.WB_AlphaTriangulation3D.tetrahedra private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_AlphaTriangulation3D.java