HE_Mesh: wblut.geom.WB_Polygon Class Reference
wblut.geom.WB_Polygon Class Reference
Public Member Functions
WB_Polygon (final Collection<?extends WB_Coord > points)
WB_Polygon (final WB_CoordCollection points)
WB_Polygon (final WB_Coord...points)
WB_Polygon (final Collection<?extends WB_Coord > points, final Collection<?extends WB_Coord > innerpoints)
WB_Polygon (final WB_Coord[] points, final WB_Coord[] innerpoints)
WB_Polygon (final Collection<?extends WB_Coord > points, final List<?extends WB_Coord >[] innerpoints)
WB_Polygon (final WB_Coord[] points, final WB_Coord[][] innerpoints)
boolean equals (final Object o)
int getNumberOfPoints ()
int getNumberOfShellPoints ()
int getNumberOfHoles ()
int getNumberOfContours ()
int[] getNumberOfPointsPerContour ()
int[] getTriangles ()
int[] getTriangles (final boolean optimize)
WB_Plane getPlane (final double d)
WB_Plane getPlane ()
WB_Vector getNormal ()
WB_Point getCenter ()
WB_Point getPoint (final int i)
double getd (final int i, final int j)
float getf (final int i, final int j)
boolean isSimple ()
boolean isCW2D ()
WB_Polygon toPolygon2D ()
WB_Polygon toPolygon2DOrtho ()
boolean is2D ()
boolean isPlanar ()
boolean isConvex2D (final int i, final boolean CW)
boolean isConvex2D ()
WB_Polygon negate ()
WB_Polygon[] splitPolygon (final WB_Plane P)
WB_Polygon trimConvexPolygon (final double d)
WB_Polygon trimConvexPolygon (final double[] d)
List< WB_Polygon > trimPolygon2D (final double d)
WB_Coord closestPoint (final WB_Coord p)
int closestIndex (final WB_Coord p)
List< WB_Segment > toSegments ()
WB_AABB getAABB ()
double getSignedArea ()
double[][] toVertices2D ()
WB_Polygon getSimplePolygon ()
Public Member Functions inherited from wblut.geom.WB_Ring
WB_Vector getDirection (final int i)
WB_Vector getNormal (final int i)
double a (final int i)
double b (final int i)
double c (final int i)
double getLength (final int i)
boolean equals (final Object o)
boolean isCCW ()
WB_Ring apply (final WB_Transform T)
WB_Point getPoint (final int i)
double getd (final int i, final int j)
float getf (final int i, final int j)
WB_Point getPointOnLine (final double t)
WB_Point getParametricPointOnLine (final double t)
int getNumberOfPoints ()
WB_Segment getSegment (final int i)
Public Member Functions inherited from wblut.geom.WB_PolyLine
WB_Point getPoint (final int i)
double getd (final int i, final int j)
float getf (final int i, final int j)
WB_Point getPointOnLine (final double t)
WB_Point getParametricPointOnLine (final double t)
WB_Vector getDirection (final int i)
WB_Vector getNormal (final int i)
double a (final int i)
double b (final int i)
double c (final int i)
int getNumberOfPoints ()
WB_Segment getSegment (final int i)
int getNumberSegments ()
double getLength (final int i)
WB_PolyLine (final Collection<?extends WB_Coord > points)
WB_PolyLine (final WB_Coord...points)
boolean equals (final Object o)
int hashCode ()
WB_PolyLine apply (final WB_Transform T)
WB_CoordCollection getPoints ()
Public Member Functions inherited from wblut.geom.WB_TriangleGenerator
WB_CoordCollection getPoints ()
Private Member Functions
void calculateDirections ()
Static Private Attributes
static final WB_GeometryFactory gf = new WB_GeometryFactory()
Additional Inherited Members
Protected Member Functions inherited from wblut.geom.WB_Ring
WB_Ring ()
WB_Ring (final List<?extends WB_Coord > points)
WB_Ring (final WB_Coord[] points)
Protected Member Functions inherited from wblut.geom.WB_PolyLine
WB_PolyLine ()
Constructor & Destructor Documentation
wblut.geom.WB_Polygon.WB_Polygon (final Collection<?extends WB_Coord > points)
Parameters
points
References wblut.geom.WB_Polygon.calculateDirections().
wblut.geom.WB_Polygon.WB_Polygon (final WB_CoordCollection points)
Parameters
points
References wblut.geom.WB_Polygon.calculateDirections(), wblut.geom.WB_CoordCollection.get(), and wblut.geom.WB_CoordCollection.size().
wblut.geom.WB_Polygon.WB_Polygon (final WB_Coord... points)
Parameters
points
References wblut.geom.WB_Polygon.calculateDirections().
wblut.geom.WB_Polygon.WB_Polygon (final Collection<?extends WB_Coord > points, final Collection<?extends WB_Coord > innerpoints)
Parameters
points
innerpoints
References wblut.geom.WB_Polygon.calculateDirections().
wblut.geom.WB_Polygon.WB_Polygon (final WB_Coord[] points, final WB_Coord[] innerpoints)
Parameters
points
innerpoints
References wblut.geom.WB_Polygon.calculateDirections().
wblut.geom.WB_Polygon.WB_Polygon (final Collection<?extends WB_Coord > points, final List<?extends WB_Coord >[] innerpoints)
Parameters
points
innerpoints
References wblut.geom.WB_Polygon.calculateDirections().
wblut.geom.WB_Polygon.WB_Polygon (final WB_Coord[] points, final WB_Coord innerpoints[][])
Parameters
points
innerpoints
References wblut.geom.WB_Polygon.calculateDirections().
Member Function Documentation
void wblut.geom.WB_Polygon.calculateDirections () private
References wblut.geom.WB_Vector.getLength().
int wblut.geom.WB_Polygon.closestIndex (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_GeometryOp3D.getSqDistance3D().
WB_Coord wblut.geom.WB_Polygon.closestPoint (final WB_Coord p)
Parameters
p
Returns
References wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_GeometryOp3D.getSqDistance3D().
boolean wblut.geom.WB_Polygon.equals (final Object o)
References wblut.geom.WB_Point.equals(), wblut.geom.WB_Polygon.getNumberOfPoints(), wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_Polygon.WB_Polygon().
WB_AABB wblut.geom.WB_Polygon.getAABB ()
Returns
References wblut.geom.WB_AABB.expandToInclude(), and wblut.geom.WB_Polygon.getPoint().
WB_Point wblut.geom.WB_Polygon.getCenter ()
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Point.divSelf(), and wblut.geom.WB_Polygon.getNumberOfShellPoints().
double wblut.geom.WB_Polygon.getd (final int i, final int j)
float wblut.geom.WB_Polygon.getf (final int i, final int j)
WB_Vector wblut.geom.WB_Polygon.getNormal ()
Returns
References wblut.geom.WB_Vector.addSelf(), wblut.geom.WB_GeometryFactory3D.createVector(), wblut.geom.WB_Polygon.getNumberOfShellPoints(), and wblut.geom.WB_Vector.normalizeSelf().
int wblut.geom.WB_Polygon.getNumberOfContours ()
Returns
int wblut.geom.WB_Polygon.getNumberOfHoles ()
Returns
int wblut.geom.WB_Polygon.getNumberOfPoints ()
int [] wblut.geom.WB_Polygon.getNumberOfPointsPerContour ()
Returns
int wblut.geom.WB_Polygon.getNumberOfShellPoints ()
Returns
WB_Plane wblut.geom.WB_Polygon.getPlane (final double d)
Parameters
d
Returns
References wblut.geom.WB_GeometryFactory3D.createPlane(), wblut.geom.WB_Polygon.getNormal(), and wblut.geom.WB_Vector.getSqLength().
WB_Plane wblut.geom.WB_Polygon.getPlane ()
Returns
WB_Point wblut.geom.WB_Polygon.getPoint (final int i)
double wblut.geom.WB_Polygon.getSignedArea ()
Returns
References wblut.geom.WB_Polygon.getNumberOfHoles(), wblut.geom.WB_Polygon.getNumberOfPointsPerContour(), wblut.geom.WB_Polygon.getNumberOfShellPoints(), wblut.geom.WB_Polygon.getPoint(), and wblut.geom.WB_GeometryOp3D.getSignedArea().
WB_Polygon wblut.geom.WB_Polygon.getSimplePolygon ()
Returns
References wblut.geom.WB_PolygonTriangulatorJTS.makeSimplePolygon().
int [] wblut.geom.WB_Polygon.getTriangles ()
Returns
Implements wblut.geom.WB_TriangleGenerator.
int [] wblut.geom.WB_Polygon.getTriangles (final boolean optimize)
Parameters
optimize
Returns
References wblut.geom.WB_Triangulation2D.getTriangles(), wblut.geom.WB_Polygon.toPolygon2DOrtho(), wblut.geom.WB_PolygonTriangulatorEarcut.triangulatePolygon2D(), wblut.geom.WB_PolygonTriangulatorJTS.triangulatePolygon2D(), and wblut.geom.WB_PolygonTriangulatorJTS.triangulateQuad().
boolean wblut.geom.WB_Polygon.is2D ()
Returns
References wblut.math.WB_Epsilon.isZero().
boolean wblut.geom.WB_Polygon.isConvex2D (final int i, final boolean CW)
Parameters
i
CW
Returns
References wblut.geom.WB_Predicates.orient2D().
boolean wblut.geom.WB_Polygon.isConvex2D ()
Returns
boolean wblut.geom.WB_Polygon.isCW2D ()
Returns
References wblut.geom.WB_Predicates.orient2D(), wblut.geom.WB_MutableCoordinate.xd(), and wblut.geom.WB_MutableCoordinate.yd().
boolean wblut.geom.WB_Polygon.isPlanar ()
Returns
References wblut.geom.WB_GeometryOp3D.getDistance3D(), wblut.geom.WB_Polygon.getPlane(), and wblut.math.WB_Epsilon.isZero().
boolean wblut.geom.WB_Polygon.isSimple ()
Returns
WB_Polygon wblut.geom.WB_Polygon.negate ()
Returns
References wblut.geom.WB_Polygon.isSimple(), and wblut.geom.WB_Polygon.WB_Polygon().
WB_Polygon [] wblut.geom.WB_Polygon.splitPolygon (final WB_Plane P)
Parameters
P
Returns
References wblut.geom.WB_GeometryOp3D.splitPolygon().
WB_Polygon wblut.geom.WB_Polygon.toPolygon2D ()
Returns
References wblut.geom.WB_Polygon.getPlane(), wblut.geom.WB_Polygon.isSimple(), wblut.geom.WB_PlanarMap.mapPoint3D(), and wblut.geom.WB_Polygon.WB_Polygon().
WB_Polygon wblut.geom.WB_Polygon.toPolygon2DOrtho ()
Returns
References wblut.geom.WB_Polygon.getPlane(), wblut.geom.WB_Polygon.isSimple(), wblut.geom.WB_OrthoProject.mapPoint3D(), and wblut.geom.WB_Polygon.WB_Polygon().
List<WB_Segment> wblut.geom.WB_Polygon.toSegments ()
Returns
References wblut.geom.WB_Polygon.getPoint().
double [][] wblut.geom.WB_Polygon.toVertices2D ()
Returns
References wblut.geom.WB_Polygon.getPlane(), wblut.geom.WB_PlanarMap.mapPoint3D(), wblut.geom.WB_MutableCoordinate.xf(), and wblut.geom.WB_MutableCoordinate.yf().
WB_Polygon wblut.geom.WB_Polygon.trimConvexPolygon (final double d)
Parameters
d
Returns
References wblut.geom.WB_GeometryOp3D.trimConvexPolygon().
WB_Polygon wblut.geom.WB_Polygon.trimConvexPolygon (final double[] d)
Parameters
d
Returns
References wblut.geom.WB_GeometryOp3D.trimConvexPolygon().
List<WB_Polygon> wblut.geom.WB_Polygon.trimPolygon2D (final double d)
Parameters
d
Returns
References wblut.geom.WB_GeometryFactory2D.createBufferedPolygons2D().
Member Data Documentation
final WB_GeometryFactory wblut.geom.WB_Polygon.gf = new WB_GeometryFactory() static private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Polygon.java