HE_Mesh: wblut.geom.WB_Octree< V > Class Template Reference
wblut.geom.WB_Octree< V > Class Template Reference
Classes
class WB_OctreeEntry
Public Member Functions
WB_Octree (final WB_Coord center, final double size)
void addPoint (final WB_Coord p, final V value)
void clear ()
int getLevel ()
WB_Octree< V > getNode (final WB_Coord p)
double getMinNodeSize ()
int getNumNodes ()
WB_Coord getCenter ()
WB_Octree< V > getParent ()
int getNumberOfPoints ()
List< WB_Octree< V > > getNodes ()
double getSize ()
boolean remove (final WB_Coord p)
void removeAll (final Collection< WB_Coord > points)
void setMinNodeSize (final double minNodeSize)
void setAutoPrune (final boolean state)
WB_AABB getBox ()
List< WB_OctreeEntry< V > > getEntries ()
List< WB_OctreeEntry< V > > getEntriesInRange (final WB_AABB AABB)
List< WB_OctreeEntry< V > > getEntriesInRange (final WB_Sphere sphere)
List< WB_OctreeEntry< V > > getEntriesInRange (final WB_Coord center, final double radius)
List< WB_Coord > getPoints ()
List< WB_Coord > getPointsInRange (final WB_AABB AABB)
List< WB_Coord > getPointsInRange (final WB_Sphere sphere)
List< WB_Coord > getPointsInRange (final WB_Coord center, final double radius)
List< V > getValues ()
List< V > getValuesInRange (final WB_AABB AABB)
List< V > getValuesInRange (final WB_Sphere sphere)
List< V > getValuesInRange (final WB_Coord center, final double radius)
Protected Member Functions
final int getOctant (final WB_Coord p)
Protected Attributes
WB_AABB box
WB_Coord extent
WB_Coord min
double minNodeSize = 4.0
WB_Octree< V > parent
WB_Octree< V >[] nodes
int numNodes
List< WB_OctreeEntry< V > > entries
double size
WB_Coord center
Private Member Functions
WB_Octree (final WB_Octree< V > p, final WB_Coord center, final double size)
void prune ()
Private Attributes
int level = 0
boolean autoPrune = false
Constructor & Destructor Documentation
wblut.geom.WB_Octree< V >.WB_Octree (final WB_Octree< V > p, final WB_Coord center, final double size) private
References wblut.geom.WB_Octree< V >.level, wblut.geom.WB_Octree< V >.minNodeSize, and wblut.geom.WB_Octree< V >.size.
wblut.geom.WB_Octree< V >.WB_Octree (final WB_Coord center, final double size)
References wblut.geom.WB_Octree< V >.size.
Member Function Documentation
void wblut.geom.WB_Octree< V >.addPoint (final WB_Coord p, final V value)
References wblut.geom.WB_Point.add(), wblut.geom.WB_Octree< V >.addPoint(), wblut.geom.WB_AABB.contains(), and wblut.geom.WB_Octree< V >.getOctant().
void wblut.geom.WB_Octree< V >.clear ()
WB_AABB wblut.geom.WB_Octree< V >.getBox ()
References wblut.geom.WB_Octree< V >.box.
WB_Coord wblut.geom.WB_Octree< V >.getCenter ()
References wblut.geom.WB_Octree< V >.center.
List<WB_OctreeEntry<V> > wblut.geom.WB_Octree< V >.getEntries ()
References wblut.geom.WB_Octree< V >.getEntries().
List<WB_OctreeEntry<V> > wblut.geom.WB_Octree< V >.getEntriesInRange (final WB_AABB AABB)
References wblut.geom.WB_AABB.contains(), wblut.geom.WB_Octree< V >.getEntriesInRange(), and wblut.geom.WB_AABB.intersects().
List<WB_OctreeEntry<V> > wblut.geom.WB_Octree< V >.getEntriesInRange (final WB_Sphere sphere)
References wblut.geom.WB_Sphere.contains(), wblut.geom.WB_Octree< V >.getEntriesInRange(), and wblut.geom.WB_AABB.intersects().
List<WB_OctreeEntry<V> > wblut.geom.WB_Octree< V >.getEntriesInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_Octree< V >.getEntriesInRange().
int wblut.geom.WB_Octree< V >.getLevel ()
References wblut.geom.WB_Octree< V >.level.
double wblut.geom.WB_Octree< V >.getMinNodeSize ()
References wblut.geom.WB_Octree< V >.minNodeSize.
WB_Octree<V> wblut.geom.WB_Octree< V >.getNode (final WB_Coord p)
References wblut.geom.WB_AABB.contains(), wblut.geom.WB_Octree< V >.getNode(), and wblut.geom.WB_Octree< V >.getOctant().
List<WB_Octree<V> > wblut.geom.WB_Octree< V >.getNodes ()
int wblut.geom.WB_Octree< V >.getNumberOfPoints ()
int wblut.geom.WB_Octree< V >.getNumNodes ()
References wblut.geom.WB_Octree< V >.numNodes.
final int wblut.geom.WB_Octree< V >.getOctant (final WB_Coord p) protected
References wblut.geom.WB_Coord.xd(), wblut.geom.WB_Coord.yd(), and wblut.geom.WB_Coord.zd().
WB_Octree<V> wblut.geom.WB_Octree< V >.getParent ()
References wblut.geom.WB_Octree< V >.parent.
List<WB_Coord> wblut.geom.WB_Octree< V >.getPoints ()
References wblut.geom.WB_Octree< V >.getPoints().
List<WB_Coord> wblut.geom.WB_Octree< V >.getPointsInRange (final WB_AABB AABB)
References wblut.geom.WB_Octree< V >.getEntriesInRange().
List<WB_Coord> wblut.geom.WB_Octree< V >.getPointsInRange (final WB_Sphere sphere)
References wblut.geom.WB_Octree< V >.getEntriesInRange().
List<WB_Coord> wblut.geom.WB_Octree< V >.getPointsInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_Octree< V >.getPointsInRange().
double wblut.geom.WB_Octree< V >.getSize ()
References wblut.geom.WB_Octree< V >.size.
List<V> wblut.geom.WB_Octree< V >.getValues ()
References wblut.geom.WB_Octree< V >.getEntries().
List<V> wblut.geom.WB_Octree< V >.getValuesInRange (final WB_AABB AABB)
References wblut.geom.WB_Octree< V >.getEntriesInRange().
List<V> wblut.geom.WB_Octree< V >.getValuesInRange (final WB_Sphere sphere)
References wblut.geom.WB_Octree< V >.getEntriesInRange().
List<V> wblut.geom.WB_Octree< V >.getValuesInRange (final WB_Coord center, final double radius)
References wblut.geom.WB_Octree< V >.getValuesInRange().
void wblut.geom.WB_Octree< V >.prune () private
References wblut.geom.WB_Octree< V >.prune().
boolean wblut.geom.WB_Octree< V >.remove (final WB_Coord p)
References wblut.geom.WB_Octree< V >.WB_OctreeEntry< V >.coord, wblut.geom.WB_Octree< V >.entries, wblut.geom.WB_Octree< V >.getNode(), and wblut.geom.WB_Octree< V >.prune().
void wblut.geom.WB_Octree< V >.removeAll (final Collection< WB_Coord > points)
void wblut.geom.WB_Octree< V >.setAutoPrune (final boolean state)
void wblut.geom.WB_Octree< V >.setMinNodeSize (final double minNodeSize)
Member Data Documentation
boolean wblut.geom.WB_Octree< V >.autoPrune = false private
WB_AABB wblut.geom.WB_Octree< V >.box protected
WB_Coord wblut.geom.WB_Octree< V >.center protected
List<WB_OctreeEntry<V> > wblut.geom.WB_Octree< V >.entries protected
WB_Coord wblut.geom.WB_Octree< V >.extent protected
int wblut.geom.WB_Octree< V >.level = 0 private
WB_Coord wblut.geom.WB_Octree< V >.min protected
double wblut.geom.WB_Octree< V >.minNodeSize = 4.0 protected
WB_Octree<V> [] wblut.geom.WB_Octree< V >.nodes protected
int wblut.geom.WB_Octree< V >.numNodes protected
WB_Octree<V> wblut.geom.WB_Octree< V >.parent protected
double wblut.geom.WB_Octree< V >.size protected
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_Octree.java