HE_Mesh: wblut.geom.WB_RandomCurve Class Reference
wblut.geom.WB_RandomCurve Class Reference
Public Member Functions
WB_RandomCurve (final WB_Curve curve, final double start, final double end)
WB_RandomCurve (final WB_Curve curve, final double start, final double end, final long seed)
WB_RandomCurve setSeed (final long seed)
WB_Point nextPoint ()
WB_Vector nextVector ()
void reset ()
WB_RandomCurve setOffset (final WB_Coord offset)
WB_RandomCurve setOffset (final double x, final double y)
WB_RandomCurve setOffset (final double x, final double y, final double z)
Public Member Functions inherited from wblut.geom.WB_RandomPoint
WB_RandomPoint setOffset (WB_Coord offset)
WB_RandomPoint setOffset (double x, double y)
WB_RandomPoint setOffset (double x, double y, double z)
Private Attributes
final WB_MTRandom randomGen
WB_Curve curve
double start
WB_Vector offset
Detailed Description
Random generator for points on a halfopen curve. The distribution is only uniform in the curve parameter.
Author
Frederik Vanhoutte, W:Blut
Constructor & Destructor Documentation
wblut.geom.WB_RandomCurve.WB_RandomCurve (final WB_Curve curve, final double start, final double end)
Parameters
curve
start
end
References wblut.geom.WB_RandomCurve.curve, and wblut.geom.WB_RandomCurve.start.
wblut.geom.WB_RandomCurve.WB_RandomCurve (final WB_Curve curve, final double start, final double end, final long seed)
Parameters
curve
start
end
seed
References wblut.geom.WB_RandomCurve.curve, and wblut.geom.WB_RandomCurve.start.
Member Function Documentation
WB_Point wblut.geom.WB_RandomCurve.nextPoint ()
Get the next random point.
Returns
Implements wblut.geom.WB_RandomPoint.
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Curve.curvePoint(), wblut.math.WB_MTRandom.nextDouble(), and wblut.geom.WB_RandomCurve.start.
WB_Vector wblut.geom.WB_RandomCurve.nextVector ()
Get the next random vector.
Returns
Implements wblut.geom.WB_RandomPoint.
References wblut.geom.WB_Point.addSelf(), wblut.geom.WB_Curve.curvePoint(), wblut.math.WB_MTRandom.nextDouble(), and wblut.geom.WB_RandomCurve.start.
void wblut.geom.WB_RandomCurve.reset ()
Reset the RNG.
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.reset().
WB_RandomCurve wblut.geom.WB_RandomCurve.setOffset (final WB_Coord offset)
WB_RandomCurve wblut.geom.WB_RandomCurve.setOffset (final double x, final double y)
References wblut.geom.WB_MutableCoordinate.set().
WB_RandomCurve wblut.geom.WB_RandomCurve.setOffset (final double x, final double y, final double z)
References wblut.geom.WB_MutableCoordinate.set().
WB_RandomCurve wblut.geom.WB_RandomCurve.setSeed (final long seed)
Set the seed for the RNG.
Parameters
seed
Returns
this
Implements wblut.geom.WB_RandomPoint.
References wblut.math.WB_MTRandom.setSeed().
Member Data Documentation
WB_Curve wblut.geom.WB_RandomCurve.curve private
WB_Vector wblut.geom.WB_RandomCurve.offset private
final WB_MTRandom wblut.geom.WB_RandomCurve.randomGen private
double wblut.geom.WB_RandomCurve.start private
The documentation for this class was generated from the following file:
src/geom/wblut/geom/WB_RandomCurve.java