HE_Mesh: wblut.hemesh.HEC_Copy Class Reference
wblut.hemesh.HEC_Copy Class Reference
Public Member Functions
HEC_Copy ()
HEC_Copy (final HE_HalfedgeStructure source)
HEC_Copy setMesh (final HE_HalfedgeStructure source)
Public Member Functions inherited from wblut.hemesh.HEC_Creator
HEC_Creator ()
HEC_Creator setCenter (final double x, final double y, final double z)
HEC_Creator setScale (final double s)
HEC_Creator setCenter (final WB_Coord c)
HEC_Creator setZAngle (final double a)
HEC_Creator setZAxis (final double x, final double y, final double z)
HEC_Creator setZAxis (final double p0x, final double p0y, final double p0z, final double p1x, final double p1y, final double p1z)
HEC_Creator setZAxis (final WB_Coord p)
HEC_Creator setZAxis (final WB_Coord p0, final WB_Coord p1)
HEC_Creator setToModelview (final PApplet home)
HEC_Creator setToWorldview ()
HEC_Creator setManifoldCheck (final boolean b)
HEC_Creator setOverride (final boolean b)
final HE_Mesh create ()
HE_Mesh apply (final HE_Mesh mesh)
HE_Mesh apply (final HE_Selection sel)
Public Member Functions inherited from wblut.hemesh.HE_Machine
abstract HE_Mesh apply (HE_Mesh mesh)
abstract HE_Mesh apply (HE_Selection selection)
String getName ()
void setName (final String name)
Public Attributes
LongLongHashMap vertexCorrelation
LongLongHashMap faceCorrelation
LongLongHashMap halfedgeCorrelation
Public Attributes inherited from wblut.hemesh.HEC_Creator
PApplet home
Protected Member Functions
HE_Mesh createBase ()
Protected Member Functions inherited from wblut.hemesh.HEC_Creator
abstract HE_Mesh createBase ()
Additional Inherited Members
Static Public Attributes inherited from wblut.hemesh.HE_Machine
static final WB_ProgressTracker tracker = WB_ProgressTracker.instance()
Protected Attributes inherited from wblut.hemesh.HEC_Creator
WB_Point center
double zangle
WB_Vector zaxis
boolean override
boolean override2D
boolean toModelview
WB_Vector Z
boolean manifoldCheck
double scale
Detailed Description
Axis Aligned Box.
Author
Frederik Vanhoutte (W:Blut)
Constructor & Destructor Documentation
wblut.hemesh.HEC_Copy.HEC_Copy ()
wblut.hemesh.HEC_Copy.HEC_Copy (final HE_HalfedgeStructure source)
Parameters
source
References wblut.hemesh.HEC_Copy.setMesh().
Member Function Documentation
HE_Mesh wblut.hemesh.HEC_Copy.createBase () protected
References wblut.hemesh.HE_Halfedge._setNext(), wblut.hemesh.HE_Halfedge._setPair(), wblut.hemesh.HE_Halfedge._setPrev(), wblut.hemesh.HE_RAS< E extends HE_Element >.add(), wblut.hemesh.HE_Mesh.add(), wblut.hemesh.HE_Selection.add(), wblut.hemesh.HE_Mesh.capHalfedges(), wblut.hemesh.HE_Selection.completeFromFaces(), wblut.hemesh.HE_MeshElement.copyProperties(), wblut.hemesh.HE_Halfedge.copyProperties(), wblut.hemesh.HE_Vertex.copyProperties(), wblut.hemesh.HE_Face.copyProperties(), wblut.hemesh.HE_Selection.fItr(), wblut.hemesh.HE_Mesh.fItr(), wblut.hemesh.HE_Halfedge.getFace(), wblut.hemesh.HE_Mesh.getFaceWithKey(), wblut.hemesh.HE_Vertex.getHalfedge(), wblut.hemesh.HE_Face.getHalfedge(), wblut.hemesh.HE_Mesh.getHalfedges(), wblut.hemesh.HE_Mesh.getHalfedgeWithKey(), wblut.hemesh.HE_Halfedge.getNextInFace(), wblut.hemesh.HE_Selection.getNumberOfFaces(), wblut.hemesh.HE_Mesh.getNumberOfFaces(), wblut.hemesh.HE_Selection.getNumberOfHalfedges(), wblut.hemesh.HE_Mesh.getNumberOfHalfedges(), wblut.hemesh.HE_Selection.getNumberOfVertices(), wblut.hemesh.HE_Mesh.getNumberOfVertices(), wblut.hemesh.HE_Halfedge.getPair(), wblut.hemesh.HE_Mesh.getSelection(), wblut.hemesh.HE_Mesh.getSelectionNames(), wblut.hemesh.HE_Halfedge.getVertex(), wblut.hemesh.HE_Mesh.getVertexWithKey(), wblut.hemesh.HE_RAS< E extends HE_Element >.getWithKey(), wblut.hemesh.HE_Selection.heItr(), wblut.core.WB_ProgressReporter.WB_ProgressCounter.increment(), wblut.hemesh.HE_RAS< E extends HE_Element >.iterator(), wblut.hemesh.HE_Halfedge.key(), wblut.hemesh.HE_Face.key(), wblut.hemesh.HE_Vertex.key(), wblut.hemesh.HE_Machine.name, wblut.hemesh.HE_Vertex.set(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setCounterStatus(), wblut.hemesh.HE_Mesh.setFace(), wblut.hemesh.HE_Mesh.setHalfedge(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStartStatus(), wblut.core.WB_ProgressReporter.WB_ProgressTracker.setStopStatus(), wblut.hemesh.HE_Mesh.setVertex(), wblut.hemesh.HE_Machine.tracker, wblut.hemesh.HE_Selection.vItr(), and wblut.hemesh.HE_Mesh.vItr().
HEC_Copy wblut.hemesh.HEC_Copy.setMesh (final HE_HalfedgeStructure source)
Parameters
source
Returns
Member Data Documentation
LongLongHashMap wblut.hemesh.HEC_Copy.faceCorrelation
LongLongHashMap wblut.hemesh.HEC_Copy.halfedgeCorrelation
LongLongHashMap wblut.hemesh.HEC_Copy.vertexCorrelation
The documentation for this class was generated from the following file:
src/hemesh_creators/wblut/hemesh/HEC_Copy.java